### ISSUE TITLE
OBS 2.6 appliances based on openSUSE 13.2 can't handle very long URLs

### ISSUE THREAD

**Issue by gollub** [openSUSE/open-build-service#1000]
The apache2 build of openSUSE 13.2 has the required patch dropped to fix bnc#690734.

Latest openSUSE.org:Apache/apache2 works fine.

The OBS 2.5 appliance on base of 13.1 works fine as well.

**Comment by adrianschroeter** [comment]
grrr .. so I re-opened that bug and branched a fixed version into :2.6 and :Unstable project. interessting that the fix is still in Factory....
