### ISSUE TITLE
add webhook setup to web ui

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#10006]
**Is your feature request related to a problem? Please describe.**
Setting up web hooks to automatically trigger builds in obs based on github/gitlab events is more complicated involving manual editing than needed:
https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.source_service.html#sec.obs.sserv.token_usage

**Describe the solution you'd like**
In the  [package view](https://build.opensuse.org/package/show/home:lnussel/toy) add another tab "Webhook". List existing tokens resp add an option to generate a token there. If a token exists, display the webhook url ready for direct copy&paste to github resp gitlab. Ie no need to manually stitch instance name, project, package or token it together for an url.

**Comment by hennevogel** [comment]
We are on our way to do this now. There is a [first beta](https://openbuildservice.org/2021/05/31/scm-integration/) ready. A token UI is also on [the roadmap](https://www.featuremap.co/mp/Tn8Am3/scm-ci-integration). Please make sure you give us feedback: TIA :smile:

**Comment by hennevogel** [comment]
Everything is there now...
