### ISSUE TITLE
Include prjconf in _buildenv

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/open-build-service#10020]
When working on reproducible builds for openSUSE, I try to verify that binaries published by OBS, really correspond to the source code using my `nachbau` script. For that, I grab the old binaries listed in _buildenv into a `deps` dir and do a `osc build -p deps` 
This regularly breaks when prjconf gets updated in certain ways.
E.g. atm I get `unresolvable: nothing provides libpython3_8-1_0 = 3.8.5 needed by python38-base, (got version 3.8.3-4.2)`
maybe because 
```
osc meta prjconf openSUSE:Factory
FileProvides: /usr/bin/python3 python38-base
```

**Describe the solution you'd like**
I would like to have a way to build with the prjconf used for the old build.
This at least needs a reference to the prjconf revision in `_buildenv`
and a way to use that revision later.

It could also include a full copy of the old prjconf either in `_buildenv` or a separate `_prjconf` .
And if OBS/osc would allow builds with a custom prjconf, that might also be a nice addition for debugging and testing

**Describe alternatives you've considered**
I could use old revisions from
https://github.com/bmwiedemann/openSUSE/blob/master/packages/_/_project/_config
but so far, finding the right version is not trivial and using it for OBS-resolution is not possible.

**Comment by adrianschroeter** [comment]
On Dienstag, 18. August 2020, 05:45:03 CEST wrote Bernhard M. Wiedemann:
> When working on reproducible builds for openSUSE, I try to verify that binaries published by OBS, really correspond to the source code using my `nachbau` script. For that, I grab the old binaries listed in _buildenv into a `deps` dir and do a `osc build -p deps` 
> This regularly breaks when prjconf gets updated in certain ways.

I would not include it, but add a reference to the version.

And we should consider a way to get merged configs (via multiple project pathes)
in a versioned way.

However, since this is indeed an importent topic, please create a jira
request for this.

thanks
adrian

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by bmwiedemann** [comment]
The other interesting question is then: how do I use the older prjconf for building?

**Comment by adrianschroeter** [comment]
On Donnerstag, 5. November 2020, 11:31:58 CET Bernhard M. Wiedemann wrote:
> The other interesting question is then: how do I use the older prjconf for building?

yes, this is just first part for this feature.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer
