### ISSUE TITLE
Packages not listed correctly

### ISSUE THREAD

**Issue by azouhr** [openSUSE/open-build-service#10048]
# Issue Description
In the Webfrontend in openSUSE:Factory:zSystems, i see different numbers for succeeded, building, failed, unresolvable packages. However, when clicking on these numbers, I get 
succeeded: no packages for for images, and just a fraction of the succeeded packages in standard (12419 succeeded, just 2709 records displayed). 
failed: 399 failed packages in the overview, 114 records in the list
unresolvable: 619 packages in the overview, 128 records in the list

This makes it hard to track down dependency issues and package failures.

Expected Result
============
I would like to see consistent statistics with records displayed, and also consistent with what osc tells me.

How to Reproduce
===============
1. Go to https://build.opensuse.org/project/show/openSUSE:Factory:zSystems
2. Check the number of succeeded images->local
3. Click on succeeded
4. compare with the number of records displayed
5. repeat for the other entries.

Further Information
===============
Using osc results openSUSE:Factory:zSystems displays the packages in the respective state, which means, the detailed lists are wrong.

**Comment by azouhr** [comment]
One more information to look at: It looks like only noarch packages are displayed, but not arch specific packages.

**Comment by hennevogel** [comment]
Works for me. Where you looking at outdated build results? Did you apply any filters or pagination on the monitor page?

![Peek 2020-08-24 15-10](https://user-images.githubusercontent.com/514785/91048448-fd83cc00-e61b-11ea-9d6e-196c38666375.gif)

**Comment by azouhr** [comment]
ok ... sorry, my error. There was a filter active, and I did not notice.
