### ISSUE TITLE
build env failed.. Could not load "/usr/lib/graphviz/libgvplugin_pango.so.6" - file not found

### ISSUE THREAD

**Issue by mckaygerhard** [openSUSE/open-build-service#10043]
Good to go? Then please remove these lines above, including this one, and help us understand your issue by answering the following:

# Issue Description

i try to build xcb debian but got error at packages depends install, Could not load "/usr/lib/graphviz/libgvplugin_pango.so.6" - file not found

seems is a cairo problem cos depends on others libs not installed, so then i try to force that by depends on libcairodev and libpango also.. but not a redundant depends happened

Expected Result
============
build environment install and start to build

How to Reproduce
===============
1. create a package and define debian base.. i used debian 8, also 9
2. upload and unmodified pacakge of libxcb directly, dsc, debian dir and source orig

Further Information
===============
* https://build.opensuse.org/package/show/home:vegnuli:system-vnx1/libxcb

LOG:
=====

This is the first error before forced the depends on cairo and pango:

´´´
[   30s] [168/201] installing libstdc++6-4.7-dev-4.7.2-5
[   30s] [169/201] installing libfontconfig1-2.9.0-7.1
[   30s] [170/201] installing libpam-modules-1.1.3-7.1
[   30s] Processing triggers for man-db ...
[   31s] [171/201] installing libtool-2.4.2-1.1
[   31s] Processing triggers for man-db ...
[   31s] [172/201] installing python-xcbgen-1.10-1
[   31s] [173/201] installing libpam-runtime-1.1.3-7.1
[   31s] Processing triggers for man-db ...
[   31s] [174/201] installing fontconfig-2.9.0-7.1
[   33s] Regenerating fonts cache... done.
[   33s] Processing triggers for man-db ...
[   34s] [175/201] installing libxft2-2.3.1-1
[   34s] [176/201] installing passwd-1:4.1.5.1-1
[   34s] Shadow passwords are now on.
[   34s] Processing triggers for man-db ...
[   34s] [177/201] installing libcairo2-1.12.2-3
[   34s] dpkg: libcairo2:i386: dependency problems, but configuring anyway as you requested:
[   34s]  libcairo2:i386 depends on libxcb-render0; however:
[   34s]   Package libxcb-render0 is not installed.
[   34s]  libcairo2:i386 depends on libxcb-shm0; however:
[   34s]   Package libxcb-shm0 is not installed.
[   34s]  libcairo2:i386 depends on libxcb1 (>= 1.6); however:
[   34s]   Package libxcb1 is not installed.
[   34s] [178/201] installing adduser-3.113+nmu3
[   34s] Processing triggers for man-db ...
[   35s] [179/201] installing libuuid1-2.20.1-5.3
[   35s] [180/201] installing login-1:4.1.5.1-1
[   35s] Processing triggers for man-db ...
[   35s] [181/201] installing libpango1.0-0-1.30.0-1
[   35s] [182/201] installing libblkid1-2.20.1-5.3
[   35s] [183/201] installing user-setup-1.48
[   36s] [184/201] installing libsm6-2:1.2.1-2
[   36s] [185/201] installing libgvc5-2.26.3-14
[   36s] Warning: Could not load "/usr/lib/graphviz/libgvplugin_pango.so.6" - file not found
[   36s] Segmentation fault (core dumped)
[   36s] dpkg: error processing libgvc5 (--install):
[   36s]  subprocess installed post-installation script returned error exit status 139
[   36s] Processing triggers for man-db ...
[   36s] Errors were encountered while processing:
[   36s]  libgvc5
[   36s] exit ...
[   36s] ### VM INTERACTION START ###
[   39s] [   35.867582] reboot: Power down
[   39s] ### VM INTERACTION END ###
[   39s] 
[   39s] build83 failed "build libxcb_1.10-4.dsc" at Sat Aug 22 13:10:39 UTC 2020.
´´´

AFTER FORCE THE DEPENDS ON CAIRO AND PANGO GOT THAT : 

´´´
[   83s] [256/274] installing dpkg-dev-1.17.25
[   83s] Processing triggers for man-db (2.7.0.2-5) ...
[   84s] [257/274] installing gir1.2-pango-1.0-1.36.8-3
[   84s] [258/274] installing libcairo2-dev-1.14.0-2.1
[   84s] dpkg: libcairo2-dev: dependency problems, but configuring anyway as you requested:
[   84s]  libcairo2-dev depends on libxcb1-dev (>= 1.6); however:
[   84s]   Package libxcb1-dev is not installed.
[   84s]  libcairo2-dev depends on libxcb-render0-dev (>= 1.6); however:
[   84s]   Package libxcb-render0-dev is not installed.
[   84s]  libcairo2-dev depends on libxcb-shm0-dev; however:
[   84s]   Package libxcb-shm0-dev is not installed.
[   85s] [259/274] installing libgvc6-2.38.0-7
[   85s] Warning: Could not load "/usr/lib/graphviz/libgvplugin_gd.so.6" - file not found
[   85s] Warning: Could not load "/usr/lib/graphviz/libgvplugin_xlib.so.6" - file not found
[   85s] Segmentation fault (core dumped)
´´´

**Comment by dmarcoux** [comment]
I will have to close this since this is a issue tracker for the OBS codebase. To get help with packaging on OBS, I suggest asking on the #opensuse-packaging channel on Freenode (IRC).

**Comment by mckaygerhard** [comment]
@dmarcoux  seems the parameter for the env are not right configured.. i try to build same in debcow or another build environment adn works! but not in OBS!
