### ISSUE TITLE
Suggestion: change URL's of repositories in YMP files to HTTPS variants for Leap 15.2

### ISSUE THREAD

**Issue by Kadilov** [openSUSE/open-build-service#10045]
Leap 15.2 installer now uses HTTPS variants of URL's when configuring online repositories. In result, a user performing 1-Click Install procedure may get a redundant HTTP entry in the list of repositories when HTTPS variant is already there, configured during OS installation.
I suggest changing links in YMP files to HTTPS for Leap 15.2 repositories. Maybe it also fits Tumbleweed, I just don't know what Tumbleweed installer saves to list.

**Comment by adrianschroeter** [comment]
changed the config now (note: this is global, not limited to specific distros)
