### ISSUE TITLE
Result on package/project search are no links anymore

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#1005]
![screenshot from 2015-07-31 11 12 37](https://cloud.githubusercontent.com/assets/968949/9004327/5a1d31be-3775-11e5-98d4-9ff0875e8a87.png)

**Comment by hennevogel** [comment]
@mdeniz that sounds like yours...

**Comment by mdeniz** [comment]
@bgeuken what do you mean with "search are no links"? I have done the same search and I get links to your projects...

![image](https://cloud.githubusercontent.com/assets/11314634/9005537/544fb162-377f-11e5-960d-be039e21e8a5.png)

**Comment by bgeuken** [comment]
This one was also caused by the backend outage.
