### ISSUE TITLE
Project owner can not reacquire their project from webui

### ISSUE THREAD

**Issue by zzndb** [openSUSE/open-build-service#10067]
# Issue Description
After unchecking all roles of a project user from webui, the user will disappear normally after the page refresh. Same disappear for project owner. It seems you can not reacquire the project from webui.

Expected Result
============
Keep the explicit owner of a project (maybe just home project?) even if there are no role be checked in the project configuration

(Even if we can use `osc maintainer -a` to add ourselves to our project from cli)

How to Reproduce
===============
1. Go to self home project page
2. Click on 'Users'
3. Uncheck all roles for yourself
4. Refresh page
5. See your own user no longer exists

**Comment by adrianschroeter** [comment]
On Dienstag, 25. August 2020, 08:59:09 CEST zzndb wrote:
> # Issue Description
> After unchecking all roles of a project user from webui, the user will disappear normally after the page refresh. Same disappear for project owner. It seems you can not reacquire the project from webui.
> 
> Expected Result
> ============
> Keep the explicit owner of a project (maybe just home project?) even if there are no role be checked in the project configuration

it must still be possible to remove maintainer role.

But permission handling actually allows to edit meta of own home project, so it
should be possible to add roles back in the webui (if allow_user_to_create_home_project is set to true).

> (Even if we can use `osc maintainer -a` to add ourselves to our project from cli)
> 
> How to Reproduce
> ===============
> 1. Go to self home project page
> 2. Click on 'Users'
> 3. Uncheck all roles for yourself
> 4. Refresh page
> 5. See your own user no longer exists
> 
> 
> 


-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by zzndb** [comment]
> it must still be possible to remove maintainer role.

maybe a different logic for right delete button to remove the user (even the project owner)?

> But permission handling actually allows to edit meta of own home project

actually, i can not save the meta file without maintainer role with 
`{"error":"Sorry, you are not authorized to update this Project."}`
from [OBS](https://build.opensuse.org) webui.

**Comment by dmarcoux** [comment]
@zzndb This is now fixed. It's been a while since you opened this issue, but I guess it's better late than never :slightly_smiling_face:
