### ISSUE TITLE
[production][project#destroy] undefined method `write_to_backend' for nil:NilClass

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#10081]
project#destroy threw this 0 times
<pre>
undefined method `write_to_backend&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/project/destroy](https://build.opensuse.org/project/destroy)"

[See this exception on Errbit](https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/5f362ab7f0a31c00081cc542)

**Comment by dmarcoux** [comment]
This happened once 3 years ago and never again, so I'm closing this. The backtrace is completely different now, so I don't see how I can reproduce this.
