### ISSUE TITLE
Unable to download some tarballs from webui when logged-in

### ISSUE THREAD

**Issue by ggardet** [openSUSE/open-build-service#10096]
# Issue Description
I am unable to download _some_ source tarballs from webui when logged-in.

Expected Result
============
Download icon should be shown.

How to Reproduce
===============
1. Login to build.o.o
2. Go to: https://build.opensuse.org/package/show/openSUSE:Factory:ARM/efl
3. No download icon for `efl-1.24.3.tar.xz`

Further Information
===============
* https://build.opensuse.org/package/show/openSUSE:Factory:ARM/efl

**Comment by krauselukas** [comment]
We don't show the download link in the Webui if the size of the file exceeds 4MB, there is a reason behind this if I remember correctly. I will double check this

**Comment by krauselukas** [comment]
Ok, double checked, the behavior changed in a recent code adjustment in this area. We will bring back the download button, thanks for reporting this

**Comment by ggardet** [comment]
Thanks for the quick fix! :)
