### ISSUE TITLE
[production][submissions#create] undefined method `packages' for nil:NilClass

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#10116]
submissions#create threw this 2 times
<pre>
undefined method `packages&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/projects/Base:System/packages/coreutils/submissions](https://build.opensuse.org/projects/Base:System/packages/coreutils/submissions)"

[See this exception on Errbit](https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/5f491bd05ad1a80008c1d0bf)

**Comment by saraycp** [comment]
Not only `submissions#create` but also `branches#create` and  `source#package_command`,

**Comment by adrianschroeter** [comment]
fixed the configuration and fixed the error handling: https://github.com/openSUSE/open-build-service/pull/10537
