### ISSUE TITLE
notifications: not getting email notifications anymore

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#10123]
According to https://build.opensuse.org/my/subscriptions in my user account, email delivery of notifications is enabled across the board, yet I am consistently not getting any mails for state changes (e.g. new -> review) for openSUSE:Factory packages anymore.
For example, SR 832489 .

**Comment by eduardoj** [comment]
Having a look at the users and groups that have permissions over openSUSE:Factory, it seems that the group you belong to (`opensuse-review-team`) is not related to to openSUSE:Factory: https://build.opensuse.org/project/users/openSUSE:Factory

That would explain you don't receive emails. Can you confirm the above?

**Comment by eduardoj** [comment]
The `opensuse-review-team` was included as a reviewer of this particular request (SR 832489). Still working on it.

**Comment by eduardoj** [comment]
Could you please check that you have in the section "You will receive emails from the checked groups" of https://build.opensuse.org/my/subscriptions (at the very top of the page) your group checked?

![Screenshot from 2020-09-07 16-16-43](https://user-images.githubusercontent.com/24919/92396610-9428b080-f125-11ea-9204-4c1ce068a213.png)

**Comment by jengelh** [comment]
That checkbox was off. I don't recall turning it off, but I can't rule it out either. Or maybe it's a new checkbox that just wasn't there (and hence did not influence email) before August 17 2020.
I enabled it now, let's see what happens.
