### ISSUE TITLE
Not all messages are in JSON via AMQP

### ISSUE THREAD

**Issue by isbm** [openSUSE/open-build-service#10146]
# Issue Description
Some messages via AMQP aren't in JSON. Examples:

```
project.delete,home=true value=1

package.create,home=true value=1

project.create,home=true value=1

user.create value=1
```

# Expected Result

Have them also in JSON.

**Comment by hennevogel** [comment]
Those are on the metrics routing key. They are in the [InfluxDB line protocal format](https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_tutorial/).

**Comment by isbm** [comment]
@hennevogel whatever they are, then content type must do a bit better job for this. Because listening to all messages, where all of them has the same content type but different content is clearly a problem.

**Comment by isbm** [comment]
This is actually a separate issue for it: https://github.com/openSUSE/open-build-service/issues/10147

**Comment by hennevogel** [comment]
Not sure what you mean by "content type must do a bit better job". Different routings serve different data and hence different content type.

**Comment by isbm** [comment]
@hennevogel if you are not sure, maybe you should not go and cowboy-close all issues without even talking and try to understand the problem. :disappointed:

**Comment by hennevogel** [comment]
Closing and opening issues is free, it's just clicking a button :smile_cat:

And we are still talking aren't we? Feel free to come up with new arguments.
