### ISSUE TITLE
search for request by id ?

### ISSUE THREAD

**Issue by bugfinder** [openSUSE/open-build-service#10155]
would be cool if https://build.opensuse.org/search would also be able to search for a request number (like bugzilla can just search for the bug id in the search field)

**Comment by dmarcoux** [comment]
Just to be sure I understand you correctly, you would want to search for `kde` (just an example) and then see a list of all requests matching `kde`. Those requests could contain the search term `kde` somewhere in their description or/and they could be for packages matching `kde`. This would allow you to then find the ID of the request you were looking for.

Is this what you would like to be able to do with the search?

**Comment by hennevogel** [comment]
Search for \#12345
