### ISSUE TITLE
filter notifications by group

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#10154]
It would also be great if it had capability to filter notifications via group, being someone who is in the maintenance-team group but doesn't care about the stuff that gets generated from there currently 95% of my view is items I don't care about and don't need to know about which makes the view pretty unusable.

_Originally posted by @simotek in https://github.com/openSUSE/open-build-service/issues/9282#issuecomment-611261518_

**Comment by dmarcoux** [comment]
@jcronenberg and I worked on this a bit, then we realized that it's not possible right now due to the issue #9958. It's preventing us from reliably finding notifications for the users of a certain group.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Filter by group](https://trello.com/c/d9PDB2mD/2140-filter-by-group)

**Comment by saraycp** [comment]
We can close this issue since we already implemented the notifications' filter by group. More details in [this card](https://trello.com/c/d9PDB2mD/135-filter-by-group).
