### ISSUE TITLE
Arch Linux builds are broken

### ISSUE THREAD

**Issue by pfactum** [openSUSE/open-build-service#10163]
Arch Linux package builds fail with the following error in the preinstall phase:

```
[    1s] [8/65] preinstalling filesystem...
[    1s] usr/sbin: is a symlink
[    1s]
[    1s] build81 failed "build PKGBUILD" at Thu Sep 17 09:12:37 UTC 2020.
```

**Comment by pfactum** [comment]
Would it be possible to just install `base-devel` group since it provides a bare minimum for Arch pkg build environment?

**Comment by adrianschroeter** [comment]
On Donnerstag, 17. September 2020, 11:35:30 CEST Oleksandr Natalenko wrote:
> Would it be possible to just install `base-devel` group since it provides a bare minimum for Arch pkg build environment?

no

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by adrianschroeter** [comment]
On Donnerstag, 17. September 2020, 11:29:10 CEST Oleksandr Natalenko wrote:
> Arch Linux package builds fail with the following error in the preinstall phase:
> 
> ```
> [    1s] [8/65] preinstalling filesystem...
> [    1s] usr/sbin: is a symlink
> [    1s]
> [    1s] build81 failed "build PKGBUILD" at Thu Sep 17 09:12:37 UTC 2020.

already reported for build script, WIP

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by dmarcoux** [comment]
This issue belongs to https://github.com/openSUSE/obs-build? If so, we can transfer it.

**Comment by mlschroe** [comment]
This was fixed some days ago.
