### ISSUE TITLE
Notifications count in the top-right is not updating when marking notifications as read/unread

### ISSUE THREAD

**Issue by OleksandrOrlov** [openSUSE/open-build-service#10169]
# Issue Description
When marking Notifications as Read/Unread, the badge with Notifications count in the top-right is not updating (![badge](https://user-images.githubusercontent.com/37581072/93573037-f63fac00-f996-11ea-83b7-56bb91f0da66.png) ).

Expected Result
============
Counter in the top-right should be updated each time when notification is marked as Read/Unread. So that it shows the actual amount of unread notifications.

How to Reproduce
===============
1. Generate notifications:
   - SSH into running _frontend_ container;
   - Execute `bundle exec rake ts:start`;
   - Then run `bundle exec rake dev:notifications:data[2]`.
2. Log in to the application;
3. Go to Notifications Page (e.g. click on the bell in the top-right or proceed by the link: http://localhost:3000/my/notifications);
4. Remember the number, that is shown in Notifications counter in the top-right;
5. Mark any notification as read;
6. Check the number in Notifications counter.

Actual result:
The notifications counter is not updated. It will be updated only if refresh the page or select some other filter (e.g. click "Unread").

Further Information
===============
![not_updating_notifications_badge](https://user-images.githubusercontent.com/37581072/93573219-26874a80-f997-11ea-85bf-50f3be34d36b.png)

**Comment by dmarcoux** [comment]
The notifications count on the top-right is rendered on the page load and never updated afterwards. It's only a matter of having some JS to handle this.
