### ISSUE TITLE
Pagination links are broken after marking a notification as read

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#10171]
# Issue Description
After marking a notification as "Read", the links of the pagination buttons at the bottom of the page are broken. They include the id of the notification already being read.

Expected Result
============
After marking a notification as "Read", the pagination buttons at the bottom of the page should link to proper paginated pages.

How to Reproduce
===============
1. Generate enough notifications to create pagination:
   - SSH into running _frontend_ container;
   - Execute `bundle exec rake ts:start`;
   - Then run `bundle exec rake dev:notifications:data[30]`.
1. Log in to the application;
1. Go to Notifications Page (e.g. click on the bell in the top-right or proceed by the link: http://localhost:3000/my/notifications);
1. Mark any notification as read;
1. Click in any pagination button at the bottom of the page.

**Comment by dmarcoux** [comment]
I can reproduce this bug.
