### ISSUE TITLE
20150716124906 AddTypeToProject migration fails

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#1017]
The new migration fails, luckily after all important things happened and manual cleanup can be done without service disruption. However, we need to find the reason for it at least.

-- remove_foreign_key(:projects, {:name=>"projects_ibfk_1"})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Error on rename of './obs_production/projects' to './obs_production/#sql2-503a-26837' (errno: 152): ALTER TABLE `projects` DROP FOREIGN KEY projects_ibfk_1/srv/www/obs/api/db/migrate/20150716124906_add_type_to_project.rb:19:in `up'
/usr/bin/rake.ruby2.2:33:in `<main>'
ActiveRecord::StatementInvalid: Mysql2::Error: Error on rename of './obs_production/projects' to './obs_production/#sql2-503a-26837' (errno: 152): ALTER TABLE `projects` DROP FOREIGN KEY projects_ibfk_1
/srv/www/obs/api/db/migrate/20150716124906_add_type_to_project.rb:19:in `up'
/usr/bin/rake.ruby2.2:33:in `<main>'
Mysql2::Error: Error on rename of './obs_production/projects' to './obs_production/#sql2-503a-26837' (errno: 152)
/srv/www/obs/api/db/migrate/20150716124906_add_type_to_project.rb:19:in `up'
/usr/bin/rake.ruby2.2:33:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by hennevogel** [comment]
So according to this [mysql bug](http://bugs.mysql.com/bug.php?id=14347) you should use the constraint name (we do) and the name is case sensitive. I need a DB dump from before to see what exactly the constraint name was.

**Comment by hennevogel** [comment]
Found dump from Tuesday. The projects_ibfk_1 is _NOT_ in the production DB hence it can't be deleted. This is a broken DB...

**Comment by hennevogel** [comment]
This production issues now tracked in https://progress.opensuse.org/issues/8440
