### ISSUE TITLE
Current pagination page is not preserved after marking a notification as read

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#10173]
# Issue Description
After marking a notification as "Read", the curent pagination is not preserved. Instead, after marking a notification as "Read", the first page of the results is always shown.

Expected Result
============
After marking a notification as "Read", the current pagination page is shown.

How to Reproduce
===============
1. Generate enough notifications to create pagination:
   - SSH into running _frontend_ container;
   - Execute `bundle exec rake ts:start`;
   - Then run `bundle exec rake dev:notifications:data[30]`.
1. Log in to the application;
1. Go to Notifications Page (e.g. click on the bell in the top-right or proceed by the link: http://localhost:3000/my/notifications);
1. Click in the pagination button "2" at the bottom of the page;
1. Mark any notification as read;
1. Observe that the results of the first page of the pagination are shown, instead of the results of the second page.

**Comment by dmarcoux** [comment]
One thing to consider for this is to handle the case when there's a single notification on a page. Once it's marked as read, we should take the user to the previous page, otherwise they will see an empty page.
