### ISSUE TITLE
_libexecdir in .spec resolves different during the build

### ISSUE THREAD

**Issue by quicktrick** [openSUSE/open-build-service#10186]
Sorry, I'm not a regular developer, so forgive me any incorrectness.

Here is my [fail2ban 0.11 package](https://build.opensuse.org/package/show/home:quicktrick:fail2ban-11/fail2ban). After I last updated the source, the package refused to build because it could not find the file `.../usr/lib/tmpfiles.d/fail2ban.conf`. It first copied this file to the wrong location: `.../usr/libexec/tmpfiles.d/fail2ban.conf` instead of `.../usr/lib/tmpfiles.d/fail2ban.conf`, though in the [.spec file](https://build.opensuse.org/package/view_file/home:quicktrick:fail2ban-11/fail2ban/fail2ban.spec?expand=1) the location is specified as `%{buildroot}%{_libexecdir}/tmpfiles.d/`.

So it obviously resolves `_libexecdir` one time as `/usr/libexec` and another time as `/usr/lib` (correctly) during the build.  It did not behave like that some time ago.

To get around this error I had to add an explicit definition `%define _libexecdir /usr/lib` in the .spec file. After that the build succeeded.

I've attached the previous failed build log in the 
[_log.zip](https://github.com/openSUSE/open-build-service/files/5259777/_log.zip)

The new successful build log is [here](https://build.opensuse.org/package/live_build_log/home:quicktrick:fail2ban-11/fail2ban/openSUSE_Tumbleweed/x86_64).

**Comment by dmarcoux** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us for some specific installations or package builds.

However, there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.

**Comment by quicktrick** [comment]
I didn't ask for support, I reported an error.  There was not such an error some time ago.  This is a new issue.

**Comment by dmarcoux** [comment]
It might be related to the changes in how `libexecdir` is handled. This recently changed: https://en.opensuse.org/openSUSE:Specfile_guidelines#Libexecdir
