### ISSUE TITLE
Have a scrollbar at the bottom in all sizes

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#10197]
No matter how large I have the browser window, there is always a vertical scrollbar. 

I only tested with chrome, chromium and Edge.

![image](https://user-images.githubusercontent.com/1067203/93999080-aba6a100-fd95-11ea-935e-2701d95f2a4b.png)

**Comment by danidoni** [comment]
Are you talking about the **horizontal** scrollbar maybe?

**Comment by coolo** [comment]
Well, I guess it's a question of definition 😄 
I'm talking about the scrollbar at the bottom - I guess you can call it horizontal, yes.

**Comment by danidoni** [comment]
> Well, I guess it's a question of definition smile
> I'm talking about the scrollbar at the bottom - I guess you can call it horizontal, yes.

Scrollbar at the bottom is better :+1:

**Comment by eduardoj** [comment]
Confirmed to happen in chrome.

It is fixed using the new [responsive layout](https://openbuildservice.org/2020/03/03/who-said-obs-was-unusable/), as for today, still in beta.

**Comment by eduardoj** [comment]
Changes in the responsive-ux have been rolled-out. This does not happen any more. Closing.
