### ISSUE TITLE
The AppImage service produces broken .zsync files, leading to non-updateable AppImages

### ISSUE THREAD

**Issue by zilti** [openSUSE/open-build-service#10201]
#Issue Description
OBS generates a .zsync file alongside the AppImage, which in theory allows the AppImage to be updateable - in practice, though, the .zsync files generated by OBS are broken and unparseable. The error is: `zsync2: Reading and/or parsing .zsync file failed!`

Expected Result
============
The zsync file is valid and allows tools like AppImageUpdate to update it if a new version is available.

How to Reproduce
===============
1. Go to any AppImage on OBS and download it
2. Try to update it using AppImageUpdate or AppImageLauncher
3. Witness error message

Further Information
===============
* A link to an OBS instance showing the issue: https://build.opensuse.org/package/binaries/home:zilti:appimages/Discord/AppImage
* Exact server version (in case a private instance is used): does not apply

**Comment by zilti** [comment]
It seems OBS adds a redundant `http:` in front of the URL, I've seen the following when doing a build:

`echo zsync_url: zsync|https:https://download.opensuse.org/repositories/home:/zilti:/appimages/AppImage/Element-latest-x86_64.AppImage.zsync`

**Comment by adrianschroeter** [comment]
fix in build-pkg2appimage package (not really an OBS issue)

**Comment by zilti** [comment]
Whatever you adjusted didn't fix it, I still get the same line in my build logs. You can Ctrl+F for `zsync_url` in https://build.opensuse.org/package/live_build_log/home:zilti:clojure/clj-kondo/AppImage/x86_64

**Comment by adrianschroeter** [comment]
On Sonntag, 4. Oktober 2020, 21:28:08 CEST Daniel Ziltener wrote:
> Whatever you adjusted didn't fix it, I still get the same line in my build logs. You can Ctrl+F for `zsync_url` in https://build.opensuse.org/package/live_build_log/home:zilti:clojure/clj-kondo/AppImage/x86_64

yeah, stupid mistake.

should be fine now.

(the code is not in OBS itself, it is in build-pkg2appimage package)

bye
adrian

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer
