### ISSUE TITLE
Packet submission to openSUSE:42:SLE12-Picks fails 

### ISSUE THREAD

**Issue by coogor** [openSUSE/open-build-service#1021]
Submitting a package to openSUSE:42:SLE12-Picks (via Web frontend) results in 'unable to submit' error messages.

The CLI is a bit more verbose:
docb@T520:~/buildservice/network:telephony> osc sr  -m 'hylafax' network:telephony/hylafax+ openSUSE:42:SLE12-Picks
Warning: failed to fetch meta data for 'openSUSE:42:SLE12-Picks' package 'hylafax+' (new package?) 
Server returned an error: HTTP Error 403: Forbidden
The target project openSUSE:42:SLE12-Picks is not accepting requests because: please submit to openSUSE:42 instead
docb@T520:~/buildservice/network:telephony> osc sr  -m 'hylafax' network:telephony/hylafax+ openSUSE:42
created request id 321802

The error message in the web frontend should be more verbose. Just a 'unable to submit' does not give enough information to solve the problem

**Comment by adrianschroeter** [comment]
common problem when OBS:RejectRequests attribute is set. this could be maybe even also handled before trying to create the request. But there are also other possible errors when creating a request, so the error message should become visible in any case.
