### ISSUE TITLE
osc search --binary doesn't seem to find anything

### ISSUE THREAD

**Issue by lkocman** [openSUSE/open-build-service#10226]
Hello team,

I was just trying to find what aside from python3-kerberos provides given .so as we see a conflict during PackageHub builds however binary search doesn't seem to work as expected. For sure we should see at least python*-kerberos in the first case and bash in the second.

```
osc -A https://api.suse.de search -B SUSE:SLE-15-SP2:Update --binary '/usr/lib64/python3.6/site-packages/kerberos.cpython-36m-x86_64-linux-gnu.so'
No matches found for '/usr/lib64/python3.6/site-packages/kerberos.cpython-36m-x86_64-linux-gnu.so' in published/binary/ids
osc -A https://api.suse.de search -B SUSE:SLE-15-SP2:Update --binary '/bin/bash'
No matches found for '/bin/bash' in published/binary/ids

```

osc-0.170.0-2.2.noarch
Ismail confirmed the same behavior.

**Comment by coolo** [comment]
`/bin/bash` is not a OBS binary but a pathname within a rpm.

**Comment by dmarcoux** [comment]
From `osc search --help`:
```
--binary            search binary packages
```

So you're searching for binary packages, not a binary in packages. This is confusing, naming things is hard...
