### ISSUE TITLE
patchinfo editor drops <name> tag

### ISSUE THREAD

**Issue by msmeissn** [openSUSE/open-build-service#1023]
the patchinfo editor in the webui drops the <name> tag we need for SLE11 during editing.

**Comment by adrianschroeter** [comment]
@bbrunner can you have a look at this?

**Comment by bgeuken** [comment]
I'll have a look at this. Might be that I broke something with my last changes.

**Comment by bgeuken** [comment]
This should be fixed now. Though it's not yet deployed;-)
