### ISSUE TITLE
FullTextSearch#search specifying classes without any class is expected to eql ...

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#10232]
```
Failure/Error: it { expect(subject).to eql([package, project]) }

ThinkingSphinx::Search::StaleIdsException:
  Record IDs found by Sphinx but not by ActiveRecord : 
./spec/models/full_text_search_spec.rb:55:in `block (5 levels) in <top (required)>'
```

Link to [CircleCI](https://app.circleci.com/pipelines/github/openSUSE/open-build-service/1615/workflows/fe7ff36d-f15b-4979-8db2-b53d53661bf3/jobs/50833)

**Comment by hennevogel** [comment]
You find flickering specs on circle now.

https://app.circleci.com/insights/github/openSUSE/open-build-service/workflows/test_all/tests?branch=master&reporting-window=last-30-days
