### ISSUE TITLE
Notifications: The left/right margins are a bit too much between 700px and 760px

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#10241]
It looks a bit weird:

![margin-notifications](https://user-images.githubusercontent.com/1102934/94691007-170de700-0331-11eb-951f-a5bffd19f443.png)

**Comment by hennevogel** [comment]
This looks fine now...

![Screenshot from 2021-01-19 12-42-25](https://user-images.githubusercontent.com/514785/105030297-e246ac80-5a53-11eb-87f3-cbb7c6b56e62.png)
