### ISSUE TITLE
Notification: Mark as Read button is not really disabled

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#10248]
The look and feel of the button is like a disabled one, but it still working, making requests to the server.

![Screenshot_2020-10-02 openSUSE Build Service(2)](https://user-images.githubusercontent.com/1212806/94939402-5fb0d600-04d2-11eb-8633-34bc7bd90a40.png)

**Comment by dmarcoux** [comment]
Another small issue with that button: It's not disabled when clicked, so users can click multiple times, submitting multiple requests.
