### ISSUE TITLE
Support of entering URL in package "Edit description"

### ISSUE THREAD

**Issue by stoecker** [openSUSE/open-build-service#10273]
The function "edit description" of a package allows to enter title and description tags of XML meta data. URL is missing, but URL is in my eyes the most important one, as it provides an easy to use link to check the package upstream status.

Please add a field to edit URL.

**Comment by stoecker** [comment]
Hmm, I've seen that when editing a project there is an URL field, but not editiing a package. That's strange, as I'd expect it the other way round. Never seen a project with an URL.

**Comment by dmarcoux** [comment]
This seems to be working fine. See my screenshot below:

![edit-package-url](https://user-images.githubusercontent.com/1102934/98684297-479c6400-2366-11eb-9809-ea3342c4bbfd.png)
