### ISSUE TITLE
0x13 characters in Edit description of a package via webinterface

### ISSUE THREAD

**Issue by stoecker** [openSUSE/open-build-service#10272]
When changing the description of a package via "Edit description" in the webinterface the resulting XML contains` &#13;`. This wastes space and looks ugly. Please strip these characters.

Workflow:
* Open Edit description
* Open spec file in another tab
* Copy text from spec file description to package description

**Comment by hennevogel** [comment]
`&#13;` is the HTML entity for carriage return

**Comment by stoecker** [comment]
I know :-) And it probably comes from the usage of that character in the HTTP/HTML transmission.

But it should be stripped when handling the XML.
