### ISSUE TITLE
[production][submissions#create] uninitialized constant BsRequestPermissionCheck::PostRequestMissingParamater
Did you mean?  PostR...

### ISSUE THREAD

**Issue by krauselukas** [openSUSE/open-build-service#10299]
submissions#create threw this 0 times
<pre>
uninitialized constant BsRequestPermissionCheck::PostRequestMissingParamater
Did you mean?  PostRequestNoPermission
</pre>
[https://build.opensuse.org/projects/home:alefnode:branches:devel:ARM:Factory:Contrib:PinePhone/packages/gnome-control-center/submissions](https://build.opensuse.org/projects/home:alefnode:branches:devel:ARM:Factory:Contrib:PinePhone/packages/gnome-control-center/submissions)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5f86fa48cef92c000db5378b)

**Comment by dmarcoux** [comment]
Hum... Param**a**ter ??? It's not the cause of the issue, but it's a nice typo :see_no_evil:

**Comment by krauselukas** [comment]
Yeah, I guess this is a leftover from the zeitwerk migration, but its good that this exception class didnt occured until now :D

**Comment by dmarcoux** [comment]
Duplicate of #10079
