### ISSUE TITLE
Cannot add or edit attributes via Web UI

### ISSUE THREAD

**Issue by afaerber** [openSUSE/open-build-service#1029]
As previously reported, I was unable to add an openSUSE:DisableAutoSubmit attribute to Virtualization qemu package via the Web UI. Adding it via `osc meta attribute` worked okay (on openSUSE 13.2).

Similarly for editing, it said "Sorry you're not allowed to edit this Attrib", while `osc meta attribute` works as expected.

I am both project and package maintainer, so not being the direct maintainer can't be the problem here.

**Comment by hennevogel** [comment]
This is a duplicate of #904
