### ISSUE TITLE
Make autocomplete while adding users to a Group to be case-insensitive.

### ISSUE THREAD

**Issue by OleksandrOrlov** [openSUSE/open-build-service#10315]
**Is your feature request related to a problem? Please describe.**
User name search is case sensitive while adding a user to a Group. It makes searching for a user a little bit confusing. For example, typing 'admin' will not suggest 'Admin' in autocomplete list.

I believe that forcing to type a name in exact case a little bit overcomplicates the action.

**Describe the solution you'd like**
Make autocomplete while searching for users to be case-insensitive. So, for example, while typing 'admin', the auto-completion list should suggest 'Admin' user.

**Describe alternatives you've considered**
I do not have alternatives.

**Additional context**
<img src="https://user-images.githubusercontent.com/37581072/96243419-04d4af80-0fa5-11eb-979c-58b23c966f00.png" width="400"> <img src="https://user-images.githubusercontent.com/37581072/96243420-056d4600-0fa5-11eb-9548-25566f763992.png" width="408">

NOTE: The same issue with case-sensitive autocomplete list is happened while creating new group:
<img src="https://user-images.githubusercontent.com/37581072/96245728-ecb25f80-0fa7-11eb-9e81-c3179420faad.png" width="500">

**Comment by dmarcoux** [comment]
I cannot reproduce this. See the 2 GIFs I recorded below:

![add-user-to-group](https://user-images.githubusercontent.com/1102934/98105431-4962b500-1e98-11eb-8eff-fc477e003fe5.gif)
![create-group-1](https://user-images.githubusercontent.com/1102934/98105435-49fb4b80-1e98-11eb-9b1c-d82df4b9d808.gif)
