### ISSUE TITLE
User profile page, "Involved Packages and Projects" missing clear filters option

### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#10323]
Once the filter is applied by the user then a button called ‘Reset Filters’ or ‘’Clear All’’ should be given next to the filters so that the user can quickly make changes. If we don't have it, we will force the user to either refresh the page (assuming that the filter will be erased) or user have to empty the search and click on "Filter results"

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address issues for the involved projects/packages feature](https://trello.com/c/BPrPcOcO/2061-address-issues-for-the-involved-projects-packages-feature)

**Comment by coogor** [comment]
Sorry to say, but this new overview is a mess! I really struggle to find my packages - old overview was much more productive

**Comment by hennevogel** [comment]
@coogor thanks for your feedback. Can you be in any way specific? What exactly is less productive and why?

**Comment by coogor** [comment]
Sure.
1) When I enter 'my profile' I get an unsorted list of projects, including description. First I need to scroll down to look for the right project, second I know what in the projects, so the description is a waste of space
2) When I filter, e.g. for gnuhealth, I get exactly one package presented: Application:ERP:GNUHealth:Factory / gnuhealth
The same package is as well in A:E:G:3.2/3.4/3.6, but this is not displayed
3) The search for Tryton gives exactly Zero Results (oops....)
So, I need to juggle with filters without getting a proper result. Before I had a sorted list of involved projects, and on another page a list of packages. One click and I was where I needed to go.
Now I need a bunch of clicks to not get a result.
Does that explain? Otherwise I'm happy to explain further...

**Comment by eduardoj** [comment]
Hi, thanks for the clarification of the issues.

> Sure.
> 
> 1. When I enter 'my profile' I get an unsorted list of projects, including description. First I need to scroll down to look for the right project, second I know what in the projects, so the description is a waste of space

Before introducing this redesign, the title of the project was displayed. Packages have no title, so nothing related to the package was displayed.

In an attempt to provide some context also for packages, the description for the packages was added. By the contrary, the whole description of each package should not be displayed. This will be fixed.

I will also revise the sorting.

> 2. When I filter, e.g. for gnuhealth, I get exactly one package presented: Application:ERP:GNUHealth:Factory / gnuhealth
>        The same package is as well in A:E:G:3.2/3.4/3.6, but this is not displayed

The search is case sensitive. Please try again, searching with `GNUHealth`.

> 3. The search for Tryton gives exactly Zero Results (oops....)

I think you faced the same case sensitive search issue. Please try searching by `Tryton`, making sure you have no other filter selected.

> So, I need to juggle with filters without getting a proper result. Before I had a sorted list of involved projects, and on another page a list of packages. One click and I was where I needed to go.

By default you are presented a list of all projects and packages you are involved with, mixed. However, you could use the "Projects / Packages" select box to filter either by "Projects" or by "Packages". Please bear with me and give it a try again.

**Comment by coogor** [comment]
Hi,

> > 1. When I enter 'my profile' I get an unsorted list of projects, including description. First I need to scroll down to look for the right project, second I know what in the projects, so the description is a waste of space
> 
> Before introducing this redesign, the title of the project was displayed. In the case of packages, nothing related to the package was displayed.
> 
> In an attempt to provide some context also for packages, the description for the packages was added. By the contrary, the whole description of each package should not be displayed. This will be fixed.

The full description of project/package can be quite lengthy, summary should be sufficient

> I will also revise the sorting.

Good!
 
> > 1. When I filter, e.g. for gnuhealth, I get exactly one package presented: Application:ERP:GNUHealth:Factory / gnuhealth
> >    The same package is as well in A:E:G:3.2/3.4/3.6, but this is not displayed
> 
> The search is case sensitive. Please try again, searching with `GNUHealth`.

All of the above projects have a package gnuhealth, so it should at least give 4 results - search for gnuhealth* even more. A filter for packages does not help

GNUHealth gives the 4 projects, correct
 
> > 1. The search for Tryton gives exactly Zero Results (oops....)
> 
> I think you faced the same case sensitive search issue. Please try searching by `Tryton`, making sure you have no other filter selected.

Same as above, 'Tryton' gives some projects, tryton or tryton* not a single package:

docb@X1E:~> osc se tryton
No matches found for 'tryton' in projects

matches for 'tryton' in packages:

Project                             Package
Application:ERP:GNUHealth:3.2         tryton
Application:ERP:GNUHealth:3.4         tryton
Application:ERP:GNUHealth:3.6         tryton
Application:ERP:Tryton:4.2            tryton
Application:ERP:Tryton:4.6            tryton
Application:ERP:Tryton:5.0            tryton
home:Gankov                           tryton
openSUSE:Backports:SLE-15             tryton
openSUSE:Backports:SLE-15-SP1         tryton
openSUSE:Backports:SLE-15-SP1:Update  tryton
openSUSE:Backports:SLE-15:Update      tryton
openSUSE:Leap:15.0                    tryton
openSUSE:Leap:15.0:Update             tryton
openSUSE:Leap:15.1                    tryton
openSUSE:Leap:15.1:Update             tryton
openSUSE:Leap:42.2                    tryton
openSUSE:Leap:42.2:Update             tryton
openSUSE:Leap:42.3                    tryton
openSUSE:Leap:42.3:Update             tryton

> > So, I need to juggle with filters without getting a proper result. Before I had a sorted list of involved projects, and on another page a list of packages. One click and I was where I needed to go.
> 
> By default you are presented a list of all projects and packages you are involved with, mixed. However, you could use the "Projects / Packages" select box to filter either by "Projects" or by "Packages". Please bear with me and give it a try again.

See above - even if it works I need some additional clicks to get a result....

**Comment by eduardoj** [comment]
> The full description of project/package can be quite lengthy, summary should be sufficient

Yes.

> > I will also revise the sorting.
> 
> Good!

> > > 1. When I filter, e.g. for gnuhealth, I get exactly one package presented: Application:ERP:GNUHealth:Factory / gnuhealth
> > >    The same package is as well in A:E:G:3.2/3.4/3.6, but this is not displayed
> > 
> > The search is case sensitive. Please try again, searching with `GNUHealth`.
> 
> All of the above projects have a package gnuhealth, so it should at least give 4 results - search for gnuhealth* even more. A filter for packages does not help

That would be a new functionality. What you describe would be, to search by packages that could also inherit some role from their parent projects. That was not implemented in the former "Involved Packages" tab. You could check this if you, temporarily, switch to the beta program.

![Screenshot from 2020-11-05 11-05-26](https://user-images.githubusercontent.com/24919/98226825-d9ffca80-1f56-11eb-82bd-bf6000d576aa.png)

So, summing up: searching by involved projects/packages has not changed the functionality, but the design of the search form.

> > > 1. The search for Tryton gives exactly Zero Results (oops....)
> > 
> > I think you faced the same case sensitive search issue. Please try searching by `Tryton`, making sure you have no other filter selected.
> 
> Same as above, 'Tryton' gives some projects, tryton or tryton* not a single package:
> 
> [...]

Also same case as before: searching from "tryton" in the former "Involved Packages" tab (not in beta program) also returns no records.

> > > So, I need to juggle with filters without getting a proper result. Before I had a sorted list of involved projects, and on another page a list of packages. One click and I was where I needed to go.
> > 
> > By default you are presented a list of all projects and packages you are involved with, mixed. However, you could use the "Projects / Packages" select box to filter either by "Projects" or by "Packages". Please bear with me and give it a try again.
> 
> See above - even if it works I need some additional clicks to get a result....

For sure, based in your comments, we will rethink the component to select Projects and/or Packages.

The improvements of the search form was meant to provide more options to search, keeping simplicity as much as possible. We also wanted to deliver a better responsive experience. Some compromises had to be addressed.

Thanks again for your feedback.
