### ISSUE TITLE
WebUI#UserController needs some love

### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#10324]
There are some methods, specially regarding with involved project/packages filtering that should refactored either to Service Objects or Presenters. Those methods need to be tested once they're extracted.

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address issues for the involved projects/packages feature](https://trello.com/c/BPrPcOcO/2061-address-issues-for-the-involved-projects-packages-feature)

**Comment by vpereira** [comment]
look into the pagination and caching opportunities

related with that https://github.com/openSUSE/open-build-service/issues/10332

**Comment by dmarcoux** [comment]
Look into the private methods of the controller and see how we can refactor this to not have everything in the controller, especially the code for filters. It should be easier to test.

The pagination was added in #10334.

**Comment by krauselukas** [comment]
Closed by https://github.com/openSUSE/open-build-service/pull/10911
