### ISSUE TITLE
Badge for Role filter in involved projects/packages tab of profile page

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#10333]
# Issue Description
In the involved projects/packages tab of the profile page, selecting/unselecting roles doesn't update the badge in the role filter.

Expected Result
============
Selecting/unselecting roles in the role filter should update the badge.

How to Reproduce
===============
1. Login as a user
2. Go to the profile page of that user
3. Select/unselect roles in the role filter
4. The badge isn't updated until the page is re-rendered.

Further Information
===============
![involved-projects-and-packages-role-filter-badge](https://user-images.githubusercontent.com/1102934/96850859-9d60a900-1457-11eb-98d1-ca0c4731c95c.gif)

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address issues for the involved projects/packages feature](https://trello.com/c/BPrPcOcO/2061-address-issues-for-the-involved-projects-packages-feature)

**Comment by vpereira** [comment]
I think we are showing the number of applied filters and not the number of selected filters
The counter will just update to "3" in your case if you click on "apply filter".
