### ISSUE TITLE
WebUI::UserController#show view performance deterioration 

### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#10332]
After the PR https://github.com/openSUSE/open-build-service/pull/10313, we noticed that the user profile page got slower in the beta program, if you are involved in more than 20 projects.

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address issues for the involved projects/packages feature](https://trello.com/c/BPrPcOcO/2061-address-issues-for-the-involved-projects-packages-feature)

**Comment by vpereira** [comment]
closed by #10334
