### ISSUE TITLE
Can't delete project which is referencing a repository in the same project 

### ISSUE THREAD

**Issue by gollub** [openSUSE/open-build-service#1035]
If you have a project like this:
```
<project name="home:dgollub:delete-prj-test">
  <title></title>
  <description></description>
  <person userid="dgollub" role="maintainer"/>
  <repository name="openSUSE_Tumbleweed">
    <path project="openSUSE:Factory" repository="snapshot"/>
    <arch>i586</arch>
    <arch>x86_64</arch>
  </repository>
  <repository name="images">
    <path project="home:dgollub:delete-prj-test" repository="openSUSE_Tumbleweed"/>
    <path project="openSUSE:Factory" repository="images"/>
    <arch>i586</arch>
    <arch>x86_64</arch>
  </repository>
</project>
```

E.g. to build images/ISOs which is referencing in the same project a regular package repository (in this exampe: local repo "openSUSE_Tumbleweed") a deletion of the entire project fails:

```
Unable to delete repository; following repositories depend on this project:
home:dgollub:delete-prj-test/images
```

It would be nice if the project in this case could just get deleted without removing first the images repository to drop the dependency.

Not really a critical issue, more an enhancement request. At least for our CI where each private project gets created like this to build images ... very likely the AutoCleanup will not work for people without manual deleting the images repository first. Or in case the CI tries to cleanup the project automatically because the topic branch in the Git tree got deleted.

**Comment by hennevogel** [comment]
There is a force parameter to do this...

**Comment by gollub** [comment]
I see - this would solve the case if people use osc or if some CI is doing that.

What about the WebUI or the OBS:AutoCleanup?

**Comment by hennevogel** [comment]
OBS:AutoCleanup will never force anything. WebUI there is a feature request for this somewhere :-)
