### ISSUE TITLE
Architectures tab on Configuration page doesn't update available architectures

### ISSUE THREAD

**Issue by KyleFromKitware** [openSUSE/open-build-service#10358]
# Issue Description
When I edit the available architectures in the web interface at Configuration -> Architectures, navigate away from the Configuration page, and come back, the old architectures are still listed.

Expected Result
============
I expect the new architectures to take effect and still be present when I return to the Architectures page.

How to Reproduce
===============
1. Go to Configuration
2. Go to Architectures
3. Edit the available architectures
4. Go back to the home page
5. Go to Configuration again
6. Go to Architectures again

Further Information
===============
* Exact server version: 2.10.2-lp151.34.2.noarch (with some light local patches to allow network access inside workers)

**Comment by jengelh** [comment]
Still broken on obs-server-2.10.10-lp152.63.1.noarch.
Enabling architectures will just not update the `architectures` SQL table.
On the other hand, if manually modifying the SQL table, the webpage reflects it and one can turn off architectures (but then they're stuck in off again).

**Comment by dmarcoux** [comment]
I believe this was fixed on `obs-server-unstable` in this PR #11017.
