### ISSUE TITLE
Benchmark libxml-ruby vs xmlhash

### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#10377]
We have everywhere in the code base the [Xmlhash](https://github.com/coolo/xmlhash) to parse XML to hashes.

Rails has its own way to achieve the same via https://apidock.com/rails/v6.0.0/Hash/from_xml/class. To make it faster, it's [recommended](https://www.rubydoc.info/docs/rails/ActiveSupport/XmlMini) to install [libxml-ruby](https://github.com/xml4r/libxml-ruby), a well maintained and widely used gem

Other possibility is to use `Nokogiri` as well, setting the XmlMini backend to `Nokogiri` (but it's probably slower)

The idea is to benchmark both and see if it make sense to update it or not.

**Comment by dmarcoux** [comment]
As we discussed together, I've updated my last comment in #10085 to have some performance benchmark regarding the possible replacement solutions for xmlhash.

I'm closing this issue.
