### ISSUE TITLE
Speed up travis builds by excluding non-essential dependencies 

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#1039]
According to the [travis documentation](http://docs.travis-ci.com/user/languages/ruby/#Speed-up-your-build-by-excluding-non-essential-dependencies) test runs in travis can be speed up by minimizing the ruby gems selected for the test environment.

It might be worth to have a look if there are gems we don't need there and check if travis tests get significantly faster by doing so.

**Comment by bgeuken** [comment]
The gem list has been reduced in #1061 and the travis speed got increased quite a bit in #1046. So I tihnk we can close this one.

**Comment by hennevogel** [comment]
Yeah awesome :-)
