### ISSUE TITLE
API documentation mentions non-existent command "createtoken"

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#10395]
The API documentation mentions a non-existent command "createtoken" for the `POST /trigger/runservice` route:
https://github.com/openSUSE/open-build-service/blob/c5bfd58798df61e780338794f06a981939ca6131/docs/api/api/api.txt#L1436

Should this be `POST /person/<userid>/token` instead?

**Comment by adrianschroeter** [comment]
On Donnerstag, 5. November 2020, 17:39:03 CET Dan Čermák wrote:
> The API documentation mentions a non-existent command "createtoken" for the `POST /trigger/runservice` route:
> https://github.com/openSUSE/open-build-service/blob/c5bfd58798df61e780338794f06a981939ca6131/docs/api/api/api.txt#L1436
> 
> Should this be `POST /person/<userid>/token` instead?

POST /person/<userid>/token?cmd=create

actually .... will improve the line ...


-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by adrianschroeter** [comment]
https://github.com/openSUSE/open-build-service/pull/10398
