### ISSUE TITLE
Suggest useful steps when a maintenance request can not be opened due to no defined default maintenance project

### ISSUE THREAD

**Issue by okurz** [openSUSE/open-build-service#10401]
Feature Description
====================

Trying to create a submit request on build.opensuse.org against openSUSE:Leap:15.3 shows:

```
$ osc sr -m "Update" openSUSE:Factory os-autoinst openSUSE:Leap:15.3
WARNING:
WARNING: Project does not accept submit request, a NEW maintenance incident request will be created instead
WARNING:
WARNING: This project is not maintained in the maintenance project specified by 'OBS:MaintenanceProject', looking elsewhere
BuildService API error: Server did not define a default maintenance project, can't submit.
```

so instead of an SR an MR is tried but that fails where an error is thrown. I think it could be helpful if a suggestion is shown what the user could do, e.g. fallback to contact the "Maintainer" of the target project.

Expected Result
============
A helpful hint what to do should be shown.

How to Reproduce
===============
1.call `osc sr -m "Update" openSUSE:Factory os-autoinst openSUSE:Leap:15.3`
2. observe warnings and error on console

**Comment by vpereira** [comment]
isn't that logic built into `osc` @okurz ? if yes wouldn't make sense to open this issue on https://github.com/openSUSE/osc ?

**Comment by okurz** [comment]
hm. I don't know. @hennevogel added "Frontend" so I don't know if it's just osc functionality.

**Comment by adrianschroeter** [comment]
it is neither.

It looks like a setup issue, but it seems to be gone.

**Comment by okurz** [comment]
Thank you for crosschecking. I can confirm that

```
osc sr -m "Update" openSUSE:Factory os-autoinst openSUSE:Leap:15.3
```

successfully created https://build.opensuse.org/request/show/852949 now
