### ISSUE TITLE
OBS responds with an internal server error when creating a user right after startup

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#10423]
# Issue Description

I am launching obs via the docker-compose test setup and wait until it the `/about` route is responding. Once that is the case, I try to create a new user via:
```ShellSession
$ ${CURL} -X PUT ${obs_url}/person/${TEST_USER} -d "
<person>
<login>${TEST_USER}</login>
<email>${TEST_USER}@notexisting.com</email>
<state>confirmed</state>
</person>
"
```
which first fails with a error 500. Waiting ~10-30 seconds "fixes" the problem (then the user can be created).

Expected Result
============
It would be nice if once the `/about` route is up, all others are accessible as well.

**Comment by adrianschroeter** [comment]
a trace from the production.log would be helpful

**Comment by vpereira** [comment]
> a trace from the production.log would be helpful

its development environment.. nothing related with production

**Comment by vpereira** [comment]
@dcermak not possible to reproduce it, for me I get a 401 as expected. We have the dependencies on the `docker-compose.yml` right. I don't see any action to be taken here.
