### ISSUE TITLE
/distributions API is not available

### ISSUE THREAD

**Issue by abitrolly** [openSUSE/open-build-service#10440]
In API docs at https://build.opensuse.org/apidocs/index `/distributions` endpoint gives 404.

There is however https://build.opensuse.org/public/distributions which works, but undocumented. A reference to it can be found in `api_routes.rb`.

https://github.com/openSUSE/open-build-service/blob/92db4fe672630292d015e1996b587798b5195dcd/src/api/config/routes/api_routes.rb#L211

How to Reproduce
===============
1. Go to https://build.opensuse.org/distributions
2. See error 404

Further Information
===============
I expected to get the list with `osc` tool - https://github.com/openSUSE/osc/issues/862

**Comment by adrianschroeter** [comment]
use https://api.opensuse.org/distributions   and not the webui. it works for me. /public is for internal needs only and can go away.

**Comment by abitrolly** [comment]
@adrianschroeter https://api.opensuse.org/distributions is 404 too.

**Comment by coolo** [comment]
if you ask with accept: text/html yes. If you ask with curl, you get 401 - only if you authorize (with e.g. osc api /distributions) you get a proper answer

**Comment by abitrolly** [comment]
@coolo is it possible to return `401` instead of `404` for the web version too?

**Comment by abitrolly** [comment]
Why two endpoints? Does private install require deploying two endpoints too?
