### ISSUE TITLE
parameter localbuild does not exist on the route  GET /build/<project>/_result 

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#10459]
Issue Description
=============

The [api docs](https://build.opensuse.org/apidocs/index#110) mention that there is a parameter called `localbuild` for the route ` GET /build/<project>/_result `, but that parameter does not appear to exist?
```ShellSession
$ osc api '/build/Virtualization:Appliances:Images:openSUSE-Tumbleweed/_result?view=binarylist&package=kiwi-images-vagrant&localbuild=1'
Server returned an error: HTTP Error 400: unknown parameter 'localbuild'
unknown parameter 'localbuild'
```

Expected Result
============

The parameter should be removed from the API documentation if it is no longer valid or the error message needs improving if the parameter is only valid for the "right" packages.

How to Reproduce
===============
```ShellSession
$ osc api '/build/${ANY_PROJECT}/_result?localbuild=1'
Server returned an error: HTTP Error 400: unknown parameter 'localbuild'
unknown parameter 'localbuild'
```

Further Information
===============
* tested against build.opensuse.org

**Comment by eduardoj** [comment]
It seems that the documentation should be changed to `locallink`. This has more sense:

`locallink: bool, include build results from packages with project local links`

@dcermak: could you check?

**Comment by dcermak** [comment]
"Eduardo J." <notifications@github.com> writes:

> It seems that the documentation should be changed to `locallink`. This has more sense:
>
> `locallink: bool, include build results from packages with project
> local links`

Yep, locallink works (the server accepts it, no idea where it makes a
difference though).
