### ISSUE TITLE
https://build.opensuse.org/ is down

### ISSUE THREAD

**Issue by abitrolly** [openSUSE/open-build-service#10451]
https://build.opensuse.org/  is down.
https://lists.opensuse.org/obs-devel/ is down.
https://status.opensuse.org/ is down too.
https://en.opensuse.org/ the same.

**Comment by dmarcoux** [comment]
There's currently a power outage where the servers are located...

**Comment by abitrolly** [comment]
@dmarcoux looks like the servers are in Nuremberg.
```
✗ curl https://freegeoip.app/xml/status.opensuse.org
<Response>
	<IP>195.135.221.160</IP>
	<CountryCode>DE</CountryCode>
	<CountryName>Germany</CountryName>
	<RegionCode>BY</RegionCode>
	<RegionName>Bavaria</RegionName>
	<City>Nuremberg</City>
	<ZipCode>90403</ZipCode>
	<TimeZone>Europe/Berlin</TimeZone>
	<Latitude>49.4527</Latitude>
	<Longitude>11.0783</Longitude>
	<MetroCode>0</MetroCode>
</Response>
```

**Comment by dmarcoux** [comment]
Indeed, they are.

**Comment by abitrolly** [comment]
@dmarcoux my finger tired from pressing browser refresh. Any news? Is it a city wide blackout, or just a single building?

**Comment by Conan-Kudo** [comment]
City power is back up, apparently, just somehow the networking in the datacenter is busted now. 😕 

At least, that's based on what's been said in IRC...

**Comment by abitrolly** [comment]
I am not sure it is related - I am just thinking that Software Defined Networking needs online backups and diffs too.

**Comment by saraycp** [comment]
The power outage brought other collateral damages. Many people did a great job to recover all the services affected. Today we'll still keep an eye on them to help to detect any possible malfunctioning.

Thanks for your consideration.

**Comment by abitrolly** [comment]
@saraycp thanks! If https://status.opensuse.org would be somehow secured to resist such events, I would be interested to read an article how it is done correctly.
