### ISSUE TITLE
remove /home/abuild before every build

### ISSUE THREAD

**Issue by mslacken** [openSUSE/open-build-service#10497]
Sometimes old configurations from previous builds pop as /home/abuild is just partly cleaned before a new build.
So I propose to remove/clean the complete /home/abuild directory before a build, not just remove /home/abuild/rpmbuild
As workarround one can use '--clean', but this costs always some seconds before a build.

**Comment by adrianschroeter** [comment]
OBS workers are always using --clean.

So most likely you want to report it with some context somewhere else ... (obs-build ? osc ?)

**Comment by mslacken** [comment]
I though osc is also in this repo. Sorry.
