### ISSUE TITLE
Cannot restore a DELETED user

### ISSUE THREAD

**Issue by byteduty** [openSUSE/open-build-service#10500]
# Issue Description
I cannot change a deleted user using either the frontend or the REST API back to being a normal user. In both cases I just get an error. 500 - Internal Error

https://my.server/user/save (500 - Internal Error)

Additionally, I cannot create a new duplicate user with the same user error, in this case I get told the there is a user with the same existing credentials.

I understand that there may be some limitation that means we cannot completely blow away a user. Although it would be nice if there was some recipe for this

Server version: 2.10.7-lp152.48.16

We have been testing LDAP, but for the problems with the user described above this is a user created without any LDAP enabled, and attempts to remove and reenable after any LDAP testing occurred.

**Comment by byteduty** [comment]
I was able to get it to work on a later try with:
cat role:
<person>
  <login>bob_the_builder</login>
  <email/>
  <realname>bob_the_builder</realname>
  <state>confirmed</state>
  <globalrole>Staff</globalrole>
  <ignore_auth_services>false</ignore_auth_services>
  <watchlist/>
</person>

osc -A https://my.server api -X PUT /person/bob_the_builder -f role
<status code="ok">
  <summary>Ok</summary>
</status>

**Comment by vpereira** [comment]
Hi @byteduty so as i understand, there is no issue there and therefore the bug can be closed?

**Comment by byteduty** [comment]
@vpereira No there is still an issue here. I was not able to use the user interface at all to restore the USER with this version. My older 2.9 instance is fine doing this via the user interface. Also with the direct API method above, I was only able to re-enable the user by providing every parameter in the POST.

I suspect there is some conditional in the interface that is not being me.

Also, off topic, is there no real way to do a complete user purge?

**Comment by vpereira** [comment]
Hey @byteduty 

are you sure that the user that you are logged in is admin? I was able to recover an user via webui without issue. "Deleted" is just one state, like "confirmed" so you should be able to see the deleted user https://my.server/users, click on edit and change the user state. You push all parameters via webui but some one them get filtered out, unless you are admin. And no, there is no way to delete an user.

**Comment by byteduty** [comment]
I am satisfied that I can at least restore a DELETED user using the API call above.
