### ISSUE TITLE
Build log for previous revision

### ISSUE THREAD

**Issue by abitrolly** [openSUSE/open-build-service#10509]
I can't find build logs for previous revisions.

The revision page https://build.opensuse.org/package/show/home:abitrolly:branches:home:andrew_z/bleachbit?srcmd5=bdc4d498d05f3a39acc297e6b5e812b7 links to latest logs and build results.

**Describe the solution you'd like**
Ability to change logs from previous revision for comparison, or compare them directly.

**Comment by hennevogel** [comment]
> I can't find build logs for previous revisions.

That is because we don't store build logs for previous versions you will have to do that yourself. We are doing around 1.5 million builds per week on build.opensuse.org

**Comment by abitrolly** [comment]
Can OBS expose the stats how much space do these logs take?
How much resources will it take to store just two last revisions?
Are there any compression methods employed for storing logs on OBS?

**Comment by hennevogel** [comment]
> Can OBS expose the stats how much space do these logs take?

That very much depends on the individual build, so no not really.

> How much resources will it take to store just two last revisions?

See above

> Are there any compression methods employed for storing logs on b.o.o?

Nope

You really want to start discussing on the mailing list instead of the issue tracker if you don't understand something. There are very capable OBS users and admins subscribed there that help each other. This issue tracker is not a way to get support.

**Comment by abitrolly** [comment]
Sent reply to https://lists.opensuse.org/opensuse-buildservice/ Pending moderator approval.

**Comment by abitrolly** [comment]
@hennevogel the message is still not on the list. Is the list for subscribers only?

**Comment by hennevogel** [comment]
I think so yes. Please note I am not the owner or administrator of this list. If you have problems with it, contact admin@opensuse.org

**Comment by abitrolly** [comment]
No response from the moderator.  Suppose I have to subscribe.
