### ISSUE TITLE
Make api.build.opensuse.org point to API docs

### ISSUE THREAD

**Issue by abitrolly** [openSUSE/open-build-service#10502]
I'm always frustrated when I go to https://api.opensuse.org/ and see https://build.opensuse.org/

**Describe the solution you'd like**
https://api.opensuse.org/ to be a different site with API docs and link back to https://build.opensuse.org/

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us for some specific instance.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.

**Comment by abitrolly** [comment]
@hennevogel does the source code support this separation?

Do you have a tracker for https://build.opensuse.org/ instance? For issues like this one, #10451 and a follow up about permanent Thursday maintenance on status page.

**Comment by hennevogel** [comment]
In general the opensuse admins you can always reach at admin@opensuse.org and the OBS maintainers in particular on opensuse-buildservice@opensuse.org

**Comment by abitrolly** [comment]
No public tracker, I see.
