### ISSUE TITLE
Edit package description: Cancel button not working

### ISSUE THREAD

**Issue by coogor** [openSUSE/open-build-service#10510]
Using the OBS beta program, I tried to edit a package description, but then decided not to do so.
I used 'Cancel' to cancel the activity
Expected result: Go back to package overview
Actual result: Nothing happens (stays in edit mode)

**Comment by dmarcoux** [comment]
Thank you @coogor for reporting this. I can reproduce the issue.

**Comment by danidoni** [comment]
The problem is that the Cancel button action is being processed as `:html` format instead of `:js`. We can look at the Cancel response preview in any browser inspector and see that its rendering the whole page instead of a partial.
