### ISSUE TITLE
GET '/status_reports/requests/<id>/reports' results in an error 500

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#10539]
# Issue Description

Querying the status reports of requests results in a internal server error on build.opensuse.org:
```ShellSession
$ osc api '/status_reports/requests/13245/reports'
Server returned an error: HTTP Error 500: Internal Server Error

Request: https://api.opensuse.org/status_reports/requests/13245/reports
Headers:
Date: Mon, 07 Dec 2020 19:46:42 GMT
Server: Apache/2.4.33 (Linux/SUSE)
Strict-Transport-Security: max-age=31536000
x-runtime: 0.065725
x-powered-by: Phusion Passenger 6.0.6
content-length: 131
status: 500 Internal Server Error
content-type: application/xml; charset=utf-8
Connection: close
```

Expected Result
============

Anything but an internal server error.

Further Information
===============
* Tested against build.opensuse.org
* does not appear to occur on my local test deployment, where I get a 404 instead

**Comment by eduardoj** [comment]
Link to errbit: https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/5fce508284bf46052aaa2be6

**Comment by adaugherity** [comment]
Is this the same error causing a 500 when viewing an OBS request through the web (e.g. https://build.opensuse.org/request/show/583146), or should I file another issue for that?

Whatever it is, it's been ongoing for at least a week...

**Comment by hennevogel** [comment]
It's not. The HTTP error number for exceptions is always 500...

**Comment by eduardoj** [comment]
This seems to be fixed. It returns a 404: Not Found error now:

```
> osc api '/status_reports/requests/13245/reports'
Server returned an error: HTTP Error 404: Not Found
Couldn't find Status::Report with [WHERE `status_reports`.`checkable_id` = ? AND `status_reports`.`checkable_type` = ?]
>
```
@dcermak, please reopen if this still happens to you.
