### ISSUE TITLE
Allow guest to see Diff and File Changes

### ISSUE THREAD

**Issue by trmdi** [openSUSE/open-build-service#10534]
For example, when a user (not a packager) wants to see Diff and File Changes of a linked package compared to the original one before deciding to install it or not... but they can't do that currently.

![image](https://user-images.githubusercontent.com/11857205/101239007-dce90900-3716-11eb-9d04-8740796202dd.png)

**Comment by dmarcoux** [comment]
Thank you @trmdi for reporting this.

I can reproduce the issue as an anonymous user and visiting https://build.opensuse.org/package/show/home:dmarcoux:obs-dev/kiwi-templates-Leap15-JeOS. I have the same result as reported above.

I expect to be able to see the diffs.

**Comment by hennevogel** [comment]
We changed this because there are malicious bots that do not respect robots.txt causing very high load with diff generation...
