### ISSUE TITLE
Left side actions feedback - right side and action frequency

### ISSUE THREAD

**Issue by abitrolly** [openSUSE/open-build-service#10542]
About https://openbuildservice.org/2020/12/03/revisit-actions-left-side-navigation/

1. Why not right side navigation?
2. Are there any stats which actions are more frequent on OBS?

**Comment by dmarcoux** [comment]
To answer your questions:

1. We based our work on a research study which is explained in this blog post:  https://uxmovement.com/navigation/the-fastest-navigation-layout-for-a-three-level-menu/ 
2. We don't have stats are which actions are more frequent on OBS.

**Comment by abitrolly** [comment]
@dmarcoux the research study did not consider right side navigation at all. Also the study is from 2004. That probably predates the time when burger menu was invented. With browser layout capabilities of that time it was nearly impossible to have right hand panes similar to the one you see right now.

Stats would be nice to consider items for inclusion. It may also reveal the terminal action that user need to take, if there are many requests in a single session for a short period of time.

**Comment by dmarcoux** [comment]
Many popular websites like GitHub, GitLab, Trello and more also rely on left side navigation. I don't see how the burger menu would change anything on that front, especially on desktop, since the hamburger menu is better suited to mobile devices.

**Comment by abitrolly** [comment]
Only GitLab uses left side navigation. GitHub uses top navigation, left side is used only for filters. Trello doesn't have any left hand navigation at all.

The burger menu is just a reference that web had changed a lot since 2004.

**Comment by dmarcoux** [comment]
Those look a lot like left navigation to me... Sure, they also rely on top navigation, but there is also a left navigation on a few pages.

![github-left-navigation](https://user-images.githubusercontent.com/1102934/101622772-c47b3600-3a17-11eb-9fba-328af5073df0.png)

![trello-left-navigation](https://user-images.githubusercontent.com/1102934/101622999-14f29380-3a18-11eb-8b10-e4b35d56edab.png)

Anyway, I don't really know what you want us to do. We can argue about this all day, but I'm going to move on. The left navigation is still a common and valid pattern, even if the research is from 2004.

**Comment by abitrolly** [comment]
Never used those screens. Must admit I am using Trello maybe a few times a year using specific boards.

> We can argue about this all day, but I'm going to move on. 

Sorry for not being clear enough. I expressed the doubts that the decision is based on dated research, which didn't consider right side navigation at all. If the post said "we did that, because GitHub does that", I would not bother with feedback, but I've seen that there are people who are interested in UX and decided to check if they are aware of more up to date studies.

**Comment by hennevogel** [comment]
All cultures read from the top down and most cultures read from left to right...

**Comment by abitrolly** [comment]
@hennevogel but when people scan pages or photos, do they do the same? I personally find it awkward reaching out for left hand items with my right hand. The basic navigation is the scrollbar and it is located to the right.

**Comment by adrianschroeter** [comment]
On Mittwoch, 9. Dezember 2020, 12:51:13 CET Henne Vogelsang wrote:
> All cultures read from the top down and most cultures read from left to right...

You did not watch japanese Karate movies in the youth? ;)

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by hennevogel** [comment]
> You did not watch japanese Karate movies in the youth? ;)

These days they would also yokogaki

**Comment by abitrolly** [comment]
![image](https://user-images.githubusercontent.com/8781107/101648632-0ffb0780-3a4b-11eb-90a4-b61b9447bc8d.png)
