### ISSUE TITLE
UI reports invalid version for valid kiwi image

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#10540]
# Issue Description

The beta UI has a new section "View Image" that I tried for the [kiwi-images-vagrant](https://build.opensuse.org/package/show/Virtualization:Appliances:Images:openSUSE-Tumbleweed/kiwi-images-vagrant) package. That view shows the kiwi file and a red error message that the version is invalid:
![Screenshot_2020-12-08 openSUSE Build Service](https://user-images.githubusercontent.com/45594031/101490176-490b7d00-3962-11eb-967e-241508c93423.png)

But kiwi accepts this recipe, so I assume that is a bug?

Expected Result
============
The error should not be present, when the kiwi file is valid.

How to Reproduce
===============
1. Activate the beta UI
1. Go to https://build.opensuse.org/package/show/Virtualization:Appliances:Images:openSUSE-Tumbleweed/kiwi-images-vagrant
2. Click on "View Image"

Further Information
===============
* direct url: https://build.opensuse.org/package/view_file/Virtualization:Appliances:Images:openSUSE-Tumbleweed/kiwi-images-vagrant/Tumbleweed.kiwi

**Comment by dcermak** [comment]
Looks like this issue is gone now, but no idea what fixed it.

**Comment by danidoni** [comment]
Let's close it. Feel free to reopen it if it happens again.
