### ISSUE TITLE
Placement of 'Save'-Button (Editor) 

### ISSUE THREAD

**Issue by coogor** [openSUSE/open-build-service#10556]
I participate in the beta program of OBS. For some reason I was forced to use the Web frontend to edit files.

The placement of the Save-button at the bottom of the page is - friendly speaking - an unlucky design. It should be placed in the top-bar next to 'Undo/Redo', and this is the main reason:

- If I make a change to a file it is typically at the top of the file. Specially for .changes.
There is no point in scrolling down 3000 lines, save, scroll up 3000 lines and just then being able to switch to the 'Overview' tab.
Go to the next file, same procedure. You spend a half day scrolling up and down, this is seriously a PITA.

Please consider a better UX!
Thank you!

**Comment by danidoni** [comment]
Yes, in the last weeks we delivered some changes to the UI that we believe are better, but we are far from done regarding UX.

Thanks for the feedback and keep it coming!

**Comment by hennevogel** [comment]
The best UX is your END key. We had this discussion numerous times, both ways. See the issue archive...

**Comment by coogor** [comment]
> The best UX is your END key. We had this discussion numerous times, both ways. See the issue archive...

Sorry but I disagree. The END key does exactly nothing in the editor window. CRTL-END brings you to the bottom, but then you still have to scroll down further. Either way, no easy way to save your work.
Making it harder for the user than necessary is bad UX design, sorry to say

**Comment by hennevogel** [comment]
Please look up the discussions we already had about this...
