### ISSUE TITLE
add ubuntu 12.04

### ISSUE THREAD

**Issue by amidevous** [openSUSE/open-build-service#10563]
how to add ubuntu 12.04 as a version for my compilation i need to have ubuntu 12.04, 14.04, 18.04 and 20.04 but the 12.04 is not offered out of some of my projects only works on this version so how to add it on my own OBS server

I found it well Add custom OBS instance

but i have to put what in Remote OBS api url

to have ubuntu 12.04?

**Comment by danidoni** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are not a way to request support from us for some specific instance.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members.

Thank you for your consideration.

**Comment by danidoni** [comment]
You can add the distro from the "Repositories" tab, clicking on "Add from a Project" and typing the distribution name in the project input field.

**Comment by amidevous** [comment]
lol the problem is that there is not 12.04 in the list in the repository there are the LTS that from 14.04 and it is only developers like you who can solve this problem except it is very expensive for you the support of development it is neither on a chat nor on a forum that we will be able to regulate its but in the source code because the distribution must be added it exists before but it was withdrawn while the support of the server version and until April 2022 for LTS server versions it is 10 years of support dear canonical so there are still 2 years left before removing this version even on lauchpad it and still available 2019 end of support for the desktop version but the server version is 2022
