### ISSUE TITLE
Notifications don't appear to match configuration.

### ISSUE THREAD

**Issue by sreeves** [openSUSE/open-build-service#1058]
It seems like I am getting notifications for which I have configured my settings to not receive.

I received a notification that "Request 324428 created by dimstar..."
Actions:
- submit GNOME:Factory/gnome-control-center => openSUSE:Factory/gnome-control-center

I do NOT have the source_maintainer checkbox enabled for the "Request created" line and I am not a maintainer in openSUSE:Factory. I don't think I should be receiving these notifications, correct ?

**Comment by sreeves** [comment]
Still receiving tons of these notifications which hide the actual ones I want to see. Any ideas on this...

**Comment by hennevogel** [comment]
Have you checked if those come from Hermes maybe?

**Comment by sreeves** [comment]
Hi Henne,
The following 2 lines are the footer of the email notifications.

Configure notifications at https://build.opensuse.org/user/notifications
openSUSE Build Service (https://build.opensuse.org/)

So they appear to be configured via the build service.
Can you give me some more info on how to check ?

**Comment by hennevogel** [comment]
Go to https://hermes.opensuse.org/ and see if you have configured something :-)

**Comment by sreeves** [comment]
I was asking more along the lines if I could inspect the mail headers or something for information that would point to the origin of the notification.

I do not have any notifications configured in hermes - they are all unchecked or disabled.

**Comment by ChrisBr** [comment]
@sreeves is this still a problem?

**Comment by eduardoj** [comment]
This seems not to be a problem. Closing because lack of feedback.
