### ISSUE TITLE
add maintenance request to delete/invalidate a package from update repository

### ISSUE THREAD

**Issue by dsamx** [openSUSE/open-build-service#10589]
It is possible to add a package version to an update repository that is not supposed to go there (and it may pass all reviews etc).
There is no way to take the package back. It will always stay there and can only be ignored if a package with a higher version or higher epoch is added to the repo. Buth these possibilities may not be a solution (an epoch is kept forever and creating a higher package number may be forbidden from a non-technical reason).

Example: package foo 1.1 was released originally, then foo 2.0 was added via maintenance. Then it became clear that foo 2.0 is just wrong for this repo, it should have been foo 1.2 instead. So foo 2.0 has to be removed and 1.2 has to be added. As long as 2.0 exists, zypper up would always prefer it over the real update. Obsoleting 2.0 is also not an option sometimes (say, 2.0 is the right version for a new product version, then you could never update to 2.0).

One solution would be deleting the patchinfo from the OBS filesystem (as admin), removing the update via webinterface (as admin) and create a new update.

So, as rpm features may not be used always, OBS requires a feature to remove or invalidate a package without being admin and tooling around manually in the OBS filesystem and such.

**Comment by hennevogel** [comment]
I think you want to report problems with some distro specific packaging stack to the respective distribution. openSUSE for instance allows downgrades of updates via zypper. 

There is nothing we will do about this from our end.

**Comment by adrianschroeter** [comment]
It does exist actually, this is just a normal delete request for the patchinfo package in the :Update project (or channel project).
