### ISSUE TITLE
Cleanup /tmp properly

### ISSUE THREAD

**Issue by dsamx** [openSUSE/open-build-service#10590]
The /tmp directory keeps empty tmpXXXXXXXX directories, like "tmpo2uphhg7" and such. They may be up to a couple of months old; I found and deleted around 20000 of them now.
It is unclear which process creates them (which should also be improved, e.g. by adding the program name to the temporary directory), except they belonged to obsservicerun:obsrun.

**Comment by hennevogel** [comment]
On a modern OS, /tmp clears itself. There are also multiple services that can do this for you. And files are identifiable...

**Comment by dsamx** [comment]
I don't think this is right, every program should cleanup the temp files it creates: if files from 2019 are still there and the system was restarted several times since then, the processes don't exist anymore, the random filename allows no further backtracking and if the system still keeps these files, then there is a bug somewhere.
Keeping thousands of empty files uses up inodes and some day the partition is full and the system breaks,
