### ISSUE TITLE
webui: View build history with a reason for build

### ISSUE THREAD

**Issue by abitrolly** [openSUSE/open-build-service#10606]
**Is your feature request related to a problem? Please describe.**
I've received the humble request to remove my fork of `openSUSE:Tools`, because it is using resources. The last commit was month ago, but the build shown had been made in last 24 hours. I can't find the build history or the reason for the rebuild. Would be nice to have a page for that.

**Comment by hennevogel** [comment]
There is. https://build.opensuse.org/packages/$PACKAGE/job_history/$PROJECT/$REPOSITORY/$ARCHITECTURE

You can find it linked from the binaries page.

**Comment by abitrolly** [comment]
@hennevogel what you point to is a *job history* for the specified project, repo and arch. What I expected to see is a *build history* for package. The build is the events that triggers multiple jobs. I want to see the history of all these events.

**Comment by hennevogel** [comment]
There is no such thing as you describe sorry. There are multiple events that will trigger a build ("job" as you call it) to be scheduled.

**Comment by abitrolly** [comment]
@hennevogel so how about to add such thing as "build", which can be triggered by multiple events? With current UI users are not aware that forks like mine are rebuilt every day wasting openSUSE resources. We all want OBS to be faster, don't we? )

**Comment by abitrolly** [comment]
> ("job" as you call it)

It is not me, it is in URL.

> There are multiple events that will trigger a build

Is there a list of them?
