### ISSUE TITLE
Builds labelled as "xUbuntu18.04" are not compatible with Ubuntu 18.04 due to GLIBC 2.28

### ISSUE THREAD

**Issue by AlexanderSamoilov** [openSUSE/open-build-service#10610]
Hello,

I need help, please! I've tried running podman and buildah from Kubic project from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ on Ubuntu 18.04.

I downloaded them from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/buildah_1.18.0~3.tar.gz and https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/podman_2.2.1~4.tar.gz respectively.

Both fail on Ubuntu 18.04 with the error message "/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found", because Ubuntu/xUbuntu 18.04 have just GLIBC 2.27 and no GLIBC 2.28.

So it was either wrongly built and the build should be fixed to be indeed compatible with Ubuntu 18.04, or the subfolder name "xUbuntu_18.04" should be corrected/removed, because it confuses the user who wants to install these products for Ubuntu/xUbuntu 18.04.

If these binaries were built for some non-standard configuration (that is Ubuntu 18.04 + GLIBC 2.28) then please mention it on the download page and explain where can one get this "special" Ubuntu.

--
Best Regards,
Alexander

**Comment by hennevogel** [comment]
You should report this to the podman project -> https://github.com/containers/podman

The issue tracker is about the source code of OBS, not about what people build with it.

**Comment by AlexanderSamoilov** [comment]
Thanks for you comment. Opened an issue https://github.com/containers/podman/issues/8943.
