### ISSUE TITLE
Announcement overlaps login modal

### ISSUE THREAD

**Issue by saraycp** [openSUSE/open-build-service#10621]
# Issue Description

The announcement overlaps other important elements of the page. In this case, it overlaps the login modal, making it difficult to enter the username.

![Screenshot_2021-01-13 OBS_broken png](https://user-images.githubusercontent.com/2581944/104478505-aaa6b300-55c2-11eb-9675-a0296bf75f02.png)

Expected Result
============

The flash message doesn't overlap other elements of the page.

How to Reproduce
===============

1. Log in (only users with Admin or Staff role)
2. Create a Status Message with `severity: "announcement"` and `communication_scope: "all_users"`.
3. Log out
4. Check the announcement is visible for not-logged users
5. Click on `Log in`
6. Check the announcement overlaps the Log in form.

Further Information
===============

We could try to fix it playing around with `z-index`. There is also a proposal to find alternatives to flash messages in #10188 .

**Comment by eduardoj** [comment]
This doesn't happen any more, after rolling the navigation redesign out of beta. Closing.
