### ISSUE TITLE
404 when accessing the API Swagger docs without a trailing slash

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#10631]
# Issue Description

Accessing https://build.opensuse.org/apidocs-new/ is showing the API Swagger docs, while https://build.opensuse.org/apidocs-new is a 404.

Expected Result
============
https://build.opensuse.org/apidocs-new shows the API Swagger docs.

How to Reproduce
===============
1. Go to https://build.opensuse.org/apidocs-new
2. See 404

Further Information
===============
We'll have to change the Apache configuration for the `apidocs-new` directory. Documentation for the [DirectorySlash directive](https://httpd.apache.org/docs/2.4/mod/mod_dir.html#directoryslash) in Apache. It's enabled by default, but it might be disabled in our Apache configuration.

**Comment by vpereira** [comment]
hm looking around other swagger-ui implementations[1], they solve it with a meta refresh[2]. That way, it will always work regardless of being in development or test (without apache).

References:
[1]  https://www.w3docs.com/snippets/html/how-to-redirect-a-web-page-in-html.html#example-of-redirecting-a-web-page-10
[2] https://matrix.org/docs/api/client-server

**Comment by dmarcoux** [comment]
I tried solving the issue by using the approach you suggest @vpereira and it didn't work. I added, under the `<head>`, the following line to [src/api/public/apidocs-new/index.html](https://github.com/openSUSE/open-build-service/blob/ed3bac8e464fb54a00fdc9f8ab1ca3ca3397c18d/src/api/public/apidocs-new/index.html):
```html
<meta http-equiv="refresh" content="0;url=/apidocs-new/" />
```

It results in an infinite redirection loop.

**Comment by hennevogel** [comment]
Putting this into `public/` does the trick.

```html
<!-- apidocs-new.html -->
<html>
        <head>
        <meta http-equiv="refresh" content="0;url=/apidocs-new/" />
        </head>
        <body>
        </body>
</html>
```
