### ISSUE TITLE
WebUI error when submitting a comment to a SR

### ISSUE THREAD

**Issue by agraul** [openSUSE/open-build-service#10630]
# Issue Description
After filling out the comment text field on a SR I get the error message "Failed to create comment" and the homepage rendered in the "comments-element".

Expected Result
============
My comment is posted successfully as it is previewed.

How to Reproduce
===============
1. Go to https://build.opensuse.org/request/show/855492
2. Fill out comment text field (not "my decision")
3. Click on "Add comment"
4. See error (screenshot below)

Further Information
===============
* Happened this morning
* I participate in the public beta

![Screenshot from 2021-01-14 11-44-07](https://user-images.githubusercontent.com/19352524/104590987-5e17b200-566c-11eb-833f-5782e46e598f.png)

**Comment by hennevogel** [comment]
Yeah this can happen if some UJS request ends in 500...
