### ISSUE TITLE
XML validation occurs before authentication, in issue_tracker API POST and PUT endpoints

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#10649]
Creating or modifying an issue tracker with the API using an invalid XML without authentication credentials, results in an XML validation error (400).

Expected Result
============
An authentication error (401) response. Authentication should be performed before the validation of the sent XML.

How to Reproduce
===============
1. Set up a development environment.
2. `curl -iH 'Content-Type: application/xml; charset=utf-8' -X POST http://localhost:3000/issue_trackers -d '<foo></foo>'`
3. See error:
   ```
   <status code="validation_failed">
     <summary>issue_tracker validation error: 1:0: ERROR: Expecting element issue-tracker, got foo</summary>
   </status>
   ```
4. It should have returned:
   ```
   <status code="anonymous_user">
     <summary>Anonymous user is not allowed here - please login</summary>
   </status>
   ```

Further information
===============
Also happens with the update action:

`curl -iH 'Content-Type: application/xml; charset=utf-8' -X PUT http://localhost:3000/issue_trackers/bar -d '<foo></foo>'`

**Comment by vpereira** [comment]
> <status code="validation_failed">
>   <summary>issue_tracker validation error: 1:0: ERROR: Expecting element issue-tracker, got foo</summary>
> </status>

Interesting. We are limiting the access to admins only in this route: https://github.com/openSUSE/open-build-service/blob/master/src/api/app/controllers/issue_trackers_controller.rb#L2
