### ISSUE TITLE
After login the view goes back in browser history

### ISSUE THREAD

**Issue by antlarr** [openSUSE/open-build-service#10654]
# Issue Description

When you're browsing obs and visit page1, then page2, and then login, after the login the user is redirected to page1 instead of staying in page2.

This might seem unimportant, but it happened to me that I was visiting a package on a devel project, then I opened the derived packages and went to my branched package to delete it. I logged in to have permissions to delete my branched package, and after logging in, I was redirected to the devel project so if I hadn't noticed. I would have deleted the package in the development project instead of my home project, which would have been... "not nice".

Expected Result
============
After login in the view should stay in the same page instead of going one page back in history.

How to Reproduce
===============
1. Log out.
2. Go to https://build.opensuse.org/package/show/X11:XOrg/xeyes
2. Click on 'Devel package for openSUSE:Factory' link
3. Click on Log In on the top-right cornet
4. Log in
5. You're redirected to the package in X11:Xorg instead of staying at openSUSE:Factory.

**Comment by danidoni** [comment]
I can confirm this
