### ISSUE TITLE
Empty page after login

### ISSUE THREAD

**Issue by Kashcheyeu** [openSUSE/open-build-service#10688]
I'm trying to log in to https://build.opensuse.org/, but after that I have a blank page opened. What could be the problem?

**Comment by hennevogel** [comment]
We don't serve blank pages. Try with another browser or fail safe mode without extensions etc.

**Comment by Kashcheyeu** [comment]
I turned off all add-ons in Firefox, protection from tracking and went in private mode — the same empty page. I understand that the problem is most likely on my side, but what if someone else has encountered it?

**Comment by hennevogel** [comment]
Can you tell me your login name please?

**Comment by Kashcheyeu** [comment]
Кощеев

**Comment by hennevogel** [comment]
Sorry we don't allow unicode in usernames. Please choose another login name, stick to ASCII.

**Comment by hennevogel** [comment]
See #10688
