### ISSUE TITLE
Open Build Service "Error 500: Internal Server Error" 

### ISSUE THREAD

**Issue by Kurfunkode** [openSUSE/open-build-service#10699]
Having problems with accessing the site it says "500: Internal Server Error" might just be me. Have a look: https://build.opensuse.org/

**Comment by osvaldop4** [comment]
I am with the same problem when I going to login.

**Comment by krauselukas** [comment]
@Kurfunkode did you signed up your account at build.opensuse.org just recently? There are some issues at the moment with that, we are working on it

**Comment by Kurfunkode** [comment]
@krauselukas Yes

**Comment by hennevogel** [comment]
Make sure you follow the instructions here: https://status.opensuse.org/incidents/240
