### ISSUE TITLE
Error 500 on Authentication 

### ISSUE THREAD

**Issue by osvaldop4** [openSUSE/open-build-service#10697]
# Issue Description

When I try to login at https://build.opensuse.org the next page shows the following message.

_500: Internal Server Error
Oooops, something went terribly wrong, our application crashed :-( We think it's best if you search if this issue is already reported on GitHub._ 

Expected Result
============

How to Reproduce
===============

Further Information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)

**Comment by hennevogel** [comment]
Please tell us your username.

**Comment by osvaldop4** [comment]
> Please tell us your username.

osvaldo.duarte

**Comment by osvaldop4** [comment]
osvaldo.duarte in 

> Please tell us your username.
in Obs is osvaldo.duarte

**Comment by osvaldop4** [comment]
In OBS os osvaldo.duarte

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by hennevogel** [comment]
Have you verified your account? 

https://idp-portal.suse.com/univention/self-service/#page=verifyaccount

**Comment by osvaldop4** [comment]
Yes I did all tasks to verify account but it happen the error.

**Comment by hennevogel** [comment]
what error?

**Comment by osvaldop4** [comment]
500: Internal Server Error
Oooops, something went terribly wrong, our application crashed :-( We think it's best if you search if this issue is already reported on GitHub.

**Comment by hennevogel** [comment]
Alright. So we might have a problem with usernames with dots in them again.

**Comment by osvaldop4** [comment]
what I have to do...Delete the user and create other that not has dot.

**Comment by hennevogel** [comment]
@osvaldop4 if you don't want to wait for for a fix, you can do that.

**Comment by osvaldop4** [comment]
Create a new user osvaldopdjr
Now the error is other. I dont't put the password wrong but the error show that I am.

_**Server error message:
Either username or password is incorrect or you are not allowed to use this service.**_

**Comment by osvaldop4** [comment]
With the user osvaldo.duarte I don't the error 

Server error message:
Either username or password is incorrect or you are not allowed to use this service.
Happens the error 
500: Internal Server Error
Oooops, something went terribly wrong, our application crashed :-( We think it's best if you search if this issue is already reported on GitHub.
Today has other issue about same error
When the bug will be resolved.

**Comment by krauselukas** [comment]
@osvaldop4 I was able to reproduce your issues, we are currently investigating. I cannot tell when exactly this will be resolved, but we are working on it.

**Comment by hennevogel** [comment]
This is resolved now. Make sure you follow the instructions here: https://status.opensuse.org/incidents/240
