### ISSUE TITLE
openbuildservice.org broken

### ISSUE THREAD

**Issue by stativ** [openSUSE/open-build-service#10724]
It's not possible to connect to openbuildservice.org

Any attempt to connect results in "SSL_ERROR_BAD_CERT_DOMAIN". The list of domains in the certificate lists a lot of opensuse.org domains, but it's indeed missing openbuildservice.org.

When forcing Firefox to accept the certificate, the website shows only:

"Unconfigured host name (did you mean to use https?)"

**Comment by jagardaniel** [comment]
I can visit openbuildservice.org again (over http) after I flushed my DNS cache. It previously resolved to 195.135.221.162 (and now a bunch of 185-addresses) so my guess is that it was moved recently. I still get the same error over https.

**Comment by adrianschroeter** [comment]
this was a misconfiguration in DNS and now github needs to settle for the SSL cert.

But this has absolute nothing to do with our code here.
