### ISSUE TITLE
The ability to flag packages as out of date

### ISSUE THREAD

**Issue by romulasry** [openSUSE/open-build-service#10775]
**Is your feature request related to a problem? Please describe.**
I always wanted to be able to flag packages out of date either in obs or zypper

**Describe the solution you'd like**
Flag a package out of date

**Describe alternatives you've considered**
zypper out of date for a package as well

**Additional context**

**Comment by hennevogel** [comment]
You should take this to https://github.com/rpm-software-management/createrepo_c
