### ISSUE TITLE
Debian Testing/Unstable builds unresolvable

### ISSUE THREAD

**Issue by tumic0** [openSUSE/open-build-service#10773]
Debian_Testing/Debian_Unstable builds using _qtbase5-private-dev_ are unresolvable on [build.opensuse.org](https://build.opensuse.org) due to the following issue:

`unresolvable: have choice for libfontconfig1-dev needed by qtbase5-private-dev: libfontconfig-dev libfontconfig1-dev`

See the [GPXSee build](https://build.opensuse.org/package/show/home:tumic:GPXSee/gpxsee) for an example.

**Comment by adrianschroeter** [comment]
please do not report content problems here.

Please go to our mailing lists like opensuse-buildservice in such cases.

**Comment by tumic0** [comment]
Is this really a content problem? Does OBS generally work fine with Debian transitional packages that are causing the issue and only the Debian build hosts at build.opensuse.org are broken?!

**Comment by kernc** [comment]
> have choice for libjpeg-dev needed by libgdk-pixbuf-2.0-dev: libjpeg-dev libjpeg62-turbo-dev,
> have choice for libjpeg-dev needed by libtiff-dev: libjpeg-dev libjpeg62-turbo-dev

@adrianschroeter If a package doesn't _directly depend_ on libjpeg-dev, it shouldn't need to specify it as a dependency, right? The build service should try to resolve package dependency ambiguities in some default headless manner. A bug of the worker's APT preferences or some such.

**Comment by Lukey3332** [comment]
For anyone stumbling over this problem, [here](https://en.opensuse.org/openSUSE:Build_Service_prjconf#Prefer) is the solution.
e.g. in your case you'd add something like the following to your project config:
```
Prefer: -libjpeg-dev
```

**Comment by kernc** [comment]
@Lukey3332 Thanks, but IIUC, this works for RPM spec files, not for debian control files, right?

**Comment by Lukey3332** [comment]
No, works for debian too. You don't add this config to the package itself, but to your obs project under the "Project Config" tab.

**Comment by kernc** [comment]
Managed to fix that for Debian as well as xUbuntu targets with:
```text
Prefer: -libjpeg-dev
Prefer: libjpeg-turbo8-dev
```
in Project Config tab. Thanks!
