### ISSUE TITLE
CentOS 8 Stream builds unresolvable

### ISSUE THREAD

**Issue by tumic0** [openSUSE/open-build-service#10772]
Centos_8_Stream builds are unresolvable on [build.opensuse.org](https://build.opensuse.org/) due to the following issue:

`unresolvable: have choice for centos-release: centos-linux-release centos-stream-release, have choice for system-release needed by setup: centos-linux-release centos-stream-release`

See the [GPXSee build](https://build.opensuse.org/package/show/home:tumic:GPXSee/gpxsee) for an example.

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.

**Comment by tumic0** [comment]
> I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are not a way to request support from us.

Well this is not a support request, but a bug report. In case this is not the place for the [build.opensuse.org](https://build.opensuse.org/) instance bugs, than someone at SUSE should maybe consider to do something about the (only) "Reporting a bug" link at [build.opensuse.org](https://build.opensuse.org/) which leads to [https://openbuildservice.org/support](https://openbuildservice.org/support/) where the bug report link leads here...

**Comment by adrianschroeter** [comment]
On Montag, 15. Februar 2021, 20:00:22 CET Martin Tůma wrote:
> > I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are not a way to request support from us.
> 
> Well this is not a support request, but a bug report. In case this is not the place for the [build.opensuse.org](https://build.opensuse.org/) instance bugs, than someone at SUSE should maybe consider to do something about the (only) "Reporting a bug" link at [build.opensuse.org](https://build.opensuse.org/) which leads to [https://openbuildservice.org/support](https://openbuildservice.org/support/) where the bug report link leads here...


Indeed, doing so now:

 https://github.com/openSUSE/obs-landing/pull/283

thanks a lot for the hint!


-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer
