### ISSUE TITLE
Build flags in branches are inconsistent with the original project

### ISSUE THREAD

**Issue by ar-lex** [openSUSE/open-build-service#10793]
# Issue Description
When branching a package the build flags are being ignored and package is being built for any architecture that is available in the original project.

Expected Result
============
Branched project is using the same set of build flags as in the original project.

How to Reproduce
===============
1. Go to the package view of the original project
2. Click on 'Branch package' and confirm branching
3. Go to the meta view of a branched project
4. Confirm that there are no build flags in meta

Further Information
===============
* OBS version 2.10.7

**Comment by hennevogel** [comment]
Not sure this is what we want. @adrianschroeter any opinion?

**Comment by adrianschroeter** [comment]
flags should not be tampered with on branch. These are always local decisions inside of a concrete project or package. Also repository names may not fit.

Use other mechanics, like ExcludeArch if the decision is bound to the source. These will have an effect as well in a branch.

**Comment by coolo** [comment]
> These are always local decisions inside of a concrete project or package.

But if I branch from a concrete project or package, I would expect to follow the local decision.

**Comment by adrianschroeter** [comment]
On Dienstag, 23. Februar 2021, 13:27:21 CET Stephan Kulow wrote:
> > These are always local decisions inside of a concrete project or package.
> 
> But if I branch from a concrete project or package, I would expect to follow the local decision.

would you also expect that the information is transfered with submit requests then?
won't work either ...

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by coolo** [comment]
No, what information is transffered with submit requests have little to do with branching. And it's always a local decision of the request reviewer what information he requires :)

But if I look at https://build.opensuse.org/package/show/devel:languages:ruby/ruby - the package is on purpose only enabled for tumbleweed. Are you seriously asking we pollute the spec file with repository names to exclude to build it only there in that very project? I'd argue build flags are made for exactly this.

Now if someone branched the ruby package, why would she have to duplicate the flag setup? I would expect a direct mapping of the flags to be generated in my branch.

**Comment by adrianschroeter** [comment]
On Dienstag, 23. Februar 2021, 13:33:27 CET Stephan Kulow wrote:
> No, what information is transffered with submit requests have little to do with branching. And it's always a local decision of the request reviewer what information he requires :)
> 
> But if I look at https://build.opensuse.org/package/show/devel:languages:ruby/ruby - the package is on purpose only enabled for tumbleweed. Are you seriously asking we pollute the spec file with repository names to exclude to build it only there in that very project? I'd argue build flags are made for exactly this.
>
> Now if someone branched the ruby package, why would she have to duplicate the flag setup? I would expect a direct mapping of the flags to be generated in my branch. 

who says that he has the same repo names? okay, one could behave different when the project got
also created, but it does not make it more understandable behaviour.

Also definitinive not when you branch into existing projects, like
maintenance incidents. You would need to reverse engineer and guess which flags.

It would be also an incompatible behaviour, so all what we could do
would allow a flag copy via opt-in.

What you could also do is to disable the build via prjconf via exclude build
buildflag though. That way you would have the effect you ask for.



-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by coolo** [comment]
> who says that he has the same repo names? okay, one could behave different when the project got also created, but it does not make it more understandable behaviour.

I'm only talking about the scenario where the project is generated - and as such I read also the issue

**Comment by adrianschroeter** [comment]
On Dienstag, 23. Februar 2021, 14:15:29 CET Stephan Kulow wrote:
> > who says that he has the same repo names? okay, one could behave different when the project got also created, but it does not make it more understandable behaviour.
> 
> I'm only talking about the scenario where the project is generated - and as such I read also the issue

so you branch package A and afterwards package B from same project and you have a different
behaviour for A and B? no way, sorry.

Please use the mentioned other mechanics, if you want to achieve a behaviour
which follows the source or repository configuration.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by coolo** [comment]
So why do we have build flags at all? What is their use case?

**Comment by adrianschroeter** [comment]
for local overrides only.
