### ISSUE TITLE
diff call failed: cpio read error head

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/open-build-service#10797]
While doing a submission for review with a .obscpio container generated by the `node_modules` service, the diff call failed with the above error. The `node_modules` service uses a custom cpio generation routine by @lnussel 

Running the `node_modules.obscpio` archive through `cpio` binary doesn't produce errors or warnings.

```
> cpio -W all -dium < ../node_modules.obscpio 
107411 blocks
> echo $?
0
```

Further Information
-------------------------
* submit request (ibs) 236501
* https://github.com/openSUSE/obs-service-node_modules/blob/master/node_modules.py#L107

**Comment by lnussel** [comment]
OBS wants trailer size to be zero but it isn't. The trailer should have size zero indeed I guess. Question is whether obs should insist though :)
https://github.com/openSUSE/open-build-service/blob/3909f7e498a5a098e502137ee7ee7265e4f2bfcf/src/backend/BSSrcdiff.pm#L372

**Comment by mlschroe** [comment]
The check is done so that a non-empty filename called 'TRAILER!!!' is possible. I don't think there is an RFC or something that specifies the cpio format.

**Comment by lnussel** [comment]
anyway fixed in https://github.com/openSUSE/obs-service-node_modules/commit/d24a8cd5c02f5daafe511c08998230136bcca1fe

**Comment by AdamMajer** [comment]
If we use `cpio` as the "reference implementation", then they don't seem to check if the magic trailer has any data or not,

      /* Is this the header for the TRAILER file?  */
      if (strcmp (CPIO_TRAILER_NAME, file_hdr.c_name) == 0)
        {
          done = true;
          break;
        } 

It simply completes extraction when it sees the trailer.

**Comment by AdamMajer** [comment]
In lieu of @lnussel fix in node_modules, I'll close it here. But this may come up again in the future I guess if we want to keep behaviour different from `cpio`'s implementation
