### ISSUE TITLE
Long build results string interferes on the Package#show layout

### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#10805]
Browser: Google Chrome

![Screenshot_2021-02-24_10-54-02](https://user-images.githubusercontent.com/37418/109005079-d761e600-76a9-11eb-8119-e77635781c4f.png)

**Comment by vpereira** [comment]
I'm not sure if it's related with the flash message. https://build.opensuse.org/package/show/home:vpereirabr:branches:OBS:Server:Unstable:container:Leap152/frontend-base

**Comment by hennevogel** [comment]
![Screenshot from 2021-02-24 16-54-08](https://user-images.githubusercontent.com/514785/109032941-7399e600-76c6-11eb-8ca6-3243161d5cd3.png)

Very long string in a container without `word-break: break-all;`
