### ISSUE TITLE
Unable to expand text of Mentioned Issues

### ISSUE THREAD

**Issue by asdil12** [openSUSE/open-build-service#10829]
When I open a SR with "Mentioned Issues" in OBS - eg https://build.suse.de/request/show/236964 it look like this:

```
bsc#12345
this is a te [+]
```

Expected Result
============
The `[+]` should expand the text when being clicked, but it doesn't.

**Comment by dmarcoux** [comment]
Thank you @asdil12 for reporting this issue. I could reproduce it with the link you provided.

Here's a screenshot of the `Mentioned Issues` section (with fake data):
![example](https://user-images.githubusercontent.com/1102934/109941920-eeb95880-7cd3-11eb-90b4-3ed86d67bf03.png)
