### ISSUE TITLE
unresolvable mouse over shows help instead of actual error

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#10837]
Looking at https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/wicked it's unresolvable. Moving the mouse over the unresolvable text shows the help instead of the the actual error message from the obs backend though. Also clicking the text doesn't change that.

![unresolvable](https://user-images.githubusercontent.com/722232/110291420-34d02e00-7fec-11eb-8b01-c553d5c1454f.gif)

MozillaFirefox-78.7.0-lp152.2.43.1.x86_64

**Comment by coolo** [comment]
It's there on your screen: "nothing provides rpmlint-mini"

**Comment by coolo** [comment]
The problem that the real error is hidden in help text.

**Comment by okurz** [comment]
I thought https://github.com/openSUSE/open-build-service/issues/9936 should have helped to resolve this

**Comment by coolo** [comment]
9936 made sure you can click on the text and not only the icon

**Comment by lnussel** [comment]
ok ic it's there. So problem is missing attention span reading to the end of the irrelevant text then :)
