### ISSUE TITLE
webui: clicking on request status does not jump to the request history section

### ISSUE THREAD

**Issue by shunghsiyu** [openSUSE/open-build-service#10840]
# Issue Description
In the request detail page (i.e. https://build.opensuse.org/request/show/$REQUEST_ID), clicking on the request status hyperlink does not correctly jump to the request history section.

![screenshot](https://user-images.githubusercontent.com/6041291/110407307-9791fa00-80be-11eb-8458-c24265f56388.jpg)

Expected Result
============
The screen jumps to the request history section.

Further Information
===============
I believe this is caused by a mismatch between the fragment used in the hyperlink `request_history` and the ID given to the DOM node `request-history` (hyphen instead of underscore).

**Comment by dmarcoux** [comment]
Thank you @shunghsiyu for reporting this issue. I can reproduce it and you are right, there is a mismatch between the ID from the DOM element and the link.
