### ISSUE TITLE
"No live log available" when a separate worker build job finished

### ISSUE THREAD

**Issue by yuening1999** [openSUSE/open-build-service#10845]
I am freshman about OBS server and OBS worker.  I had installed a private OBS server (2.9.6 appliance)on x86_64 machine and disable obs worker component, Meanwhile, I also installed a separate x86_64 worker on another machine and a arm64 obs worker on raspberry pi4,  I configure obs server and these two separate obs worker(x86_64 and arm64 pi4) according to manual "https://openbuildservice.org/help/manuals/obs-admin-guide/" and "https://openbuildservice.org/help/manuals/obs-user-guide/"

I can registered two separate obs workers to obs server (2.9.6) and build jobs may be started (both arm64 and x86_64), but alway get the following hint on WebUI/API after I start debian package "hello" building

"No live log available: package 'hello' has no logfile"

on obs worker machine,  look up /var/cache/obs/worker/root_x, all debs(debian packages) may be made successufully.  why does I alway get the ERRROR?  Could you give me any help or advices ?

**Comment by adrianschroeter** [comment]
On Mittwoch, 10. März 2021, 07:41:56 CET yuening1999 wrote:
> I am freshman about OBS server and OBS worker.  I had installed a private OBS server (2.9.6 appliance)on x86_64 machine and disable obs worker component, Meanwhile, I also installed a separate x86_64 worker on another machine and a arm64 obs worker on raspberry pi4,  I configure obs server and these two separate obs worker(x86_64 and arm64 pi4) according to manual "https://openbuildservice.org/help/manuals/obs-admin-guide/" and "https://openbuildservice.org/help/manuals/obs-user-guide/"
> 
> I can registered two separate obs workers to obs server (2.9.6) and build jobs may be started (both arm64 and x86_64), but alway get the following hint on WebUI/API after I start debian package "hello" building
> 
> "No live log available: package 'hello' has no logfile"
> 
> on obs worker machine,  look up /var/cache/obs/worker/root_x, all debs(debian packages) may be made successufully.  why does I alway get the ERRROR?  Could you give me any help or advices ?

The first thing I would check are the ajax jobs of src and rep server. Restart them in doubt.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by adrianschroeter** [comment]
but github is not our support interface, please come to the mailing list for generic support questions.

https://openbuildservice.org/support/
