### ISSUE TITLE
ldap starts before network

### ISSUE THREAD

**Issue by martingabelmann** [openSUSE/open-build-service#1086]
There are many errors in journal after boot because ldap is trying to connect before network is established. Its systemd unit may should depend on `network-online.target`.

**Comment by adrianschroeter** [comment]
which ldap? the obs api stack? Which OBS version and which distribution?

**Comment by martingabelmann** [comment]
Sorry...
OpenSuse 13.2, recent pam_ldap  (version 186)

**Comment by adrianschroeter** [comment]
So please create a bugzilla report directly to the maintainer. You can find him via this search:

 https://build.opensuse.org/search/owner?search_text=pam_ldap&owner=1
