### ISSUE TITLE
UI shows wrong records in path list for repo

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#10864]
On https://build.opensuse.org/repositories/systemsmanagement:saltstack:bundle

![Screenshot from 2021-03-12 15-32-08](https://user-images.githubusercontent.com/514785/110953884-24031d80-8348-11eb-858a-b13fa08826c1.png)

On https://build.opensuse.org/projects/systemsmanagement:saltstack:bundle/meta

```xml
<repository name="Ubuntu_18.04">
    <path project="systemsmanagement:saltstack:bundle:debbuild" repository="Ubuntu_18.04"/>
    <path project="Ubuntu:debbuild" repository="Ubuntu_18.04"/>
    <path project="Ubuntu:18.04" repository="universe"/>
    <path project="Ubuntu:18.04" repository="universe-update"/>
    <path project="Ubuntu:18.04" repository="update"/>
    <arch>x86_64</arch>
  </repository>
```

Where do the Ubuntu 16.04 path's come from?

**Comment by rubhanazeem** [comment]
We have tried to reproduce it and it's not happening anymore. I'm going to close the issue, if someone faces the same issue again please reopen it.
