### ISSUE TITLE
User home link redirects to empy create project page if no home exists

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#1090]
Instead the form on the create project page should be already filled with 

```
home:user
```

**Comment by bgeuken** [comment]
For new users this seems to be the case. Tested on my dev machine and build.opensuse.org

May it be that we did not migrate existing users that doesn't have a home project?

**Comment by bgeuken** [comment]
Apparently there is a flag that we have to consider: Configuration.allow_user_to_create_home_project

**Comment by hennevogel** [comment]
I don't get your bug description. What is happening?

**Comment by ChrisBr** [comment]
If you don't have a home directory and you click the home link you'll be redirected to /project/new -> fine! When you then try to create the home you get a permission error, because of the missing namespace ```home:username```. For you this is obvious what's happening, for a new user maybe not ;) Therefore we should fill the form with namespace when redirected from home.

**Comment by imobach** [comment]
Yes, I was expecting something like this http://openbuildservice.org/help/manuals/obs-best-practices/images/home_project_webui_description.png instead of a 404.

**Comment by hennevogel** [comment]
How do you try to create the home on /project/new?

**Comment by imobach** [comment]
@hennevogel I only tried to navigate to the `Home project` link in the web UI and I got a `404`.

**Comment by bgeuken** [comment]
Solved with #1189
