### ISSUE TITLE
400 remote error: Logfile is not that big

### ISSUE THREAD

**Issue by yuening1999** [openSUSE/open-build-service#10900]
when deploying two separate workers(x86 and arm64, disable worker built in obs server), I found that "Logfile is not that big" was be reported on reposerver.log when separate worker finished build jobs. after investigating bs_worker souce code, I found that "sub stream_logfile()" delivery the error, I can not understand the error,
what does code "die("Logfile is not that big\n")  if $s[7] < abs($start)" means?
I know that is exception quit,but I can not understand the triggering situation, Could you explain why does the error occur? because I am not good at perl programming.

**Comment by marcus-h** [comment]
On 2021-03-17 03:29:15 -0700, yuening1999 wrote:
> when deploying two separate workers(x86 and arm64, disable worker built in obs server), I found that "Logfile is not that big" was be reported on reposerver.log when separate worker finished build jobs. after investigating bs_worker souce code, I found that "sub stream_logfile()" delivery the error, I can not understand the error,
> what does code "die("Logfile is not that big\n")  if $s[7] < abs($start)" means?

$s[7] is the size of the the buildlog file and $start is a "user"
provided offset into this file. You could trigger this, for instance,
via "osc rbl <prj> <pkg> <repo> <arch> --offset <some large number>"
while the build of <prj> <pkg> <repo> <arch> is still running.

> I know that is exception quit,but I can not understand the triggering situation, Could you explain why does the error occur? because I good at perl programming.
>

**Comment by yuening1999** [comment]
Hi, marcus
thank you for your quick reply.
but what does sentence" "user" provided offset into this file " means? why "user" offset into the file? what does "user" point to?

**Comment by marcus-h** [comment]
On 2021-03-17 05:02:08 -0700, yuening1999 wrote:
> Hi, marcus
> thank you for your quick reply.
> but what does sentence" "user" provided offset into this file " means? why "user" offset into the file? what does "user" point to?
>
It is a parameter that is controlled/specified by a user (for instance, you,
if you execute the mentioned osc command).

**Comment by yuening1999** [comment]
thanks, marcus, I gotten it. I will try the command that you said.

**Comment by yuening1999** [comment]
Hi, marcus
according to your hint, I use the following "osc command" to view remote build log, as your description, it can get real-time build info on my host. I found that the final  build result is  consistent with one of Web UI ("No live log file").

$ osc rbl home:ynliu:test openssh-server Debian_10 x86_64

[  239s] ### VM INTERACTION START ###
[  240s] Powering off.
[  240s] [  234.427363] reboot: Power down
[  240s] ### VM INTERACTION END ###
[  240s] build: extracting built packages...
[  240s] DEBS/ssh_7.9p1-10+deb10u2_all.deb
[  240s] DEBS/ssh-askpass-gnome_7.9p1-10+deb10u2_amd64.deb
[  240s] DEBS/openssh-server-dbgsym_7.9p1-10+deb10u2_amd64.deb
[  240s] DEBS/openssh-server_7.9p1-10+deb10u2_amd64.deb
[  240s] DEBS/openssh-sftp-server-dbgsym_7.9p1-10+deb10u2_amd64.deb
[  240s] DEBS/openssh_7.9p1.orig.tar.gz.asc
[  240s] DEBS/openssh-client_7.9p1-10+deb10u2_amd64.deb
[  240s] DEBS/openssh-sftp-server_7.9p1-10+deb10u2_amd64.deb
[  240s] DEBS/ssh-askpass-gnome-dbgsym_7.9p1-10+deb10u2_amd64.deb
[  240s] DEBS/openssh-server-udeb_7.9p1-10+deb10u2_amd64.udeb
[  240s] DEBS/openssh-client-udeb_7.9p1-10+deb10u2_amd64.udeb
[  240s] DEBS/openssh_7.9p1.orig.tar.gz
[  240s] DEBS/openssh_7.9p1-10+deb10u2_amd64.buildinfo
[  240s] DEBS/openssh_7.9p1-10+deb10u2.dsc
[  240s] DEBS/openssh-tests_7.9p1-10+deb10u2_amd64.deb
[  240s] DEBS/openssh_7.9p1-10+deb10u2_amd64.changes
[  240s] DEBS/openssh-client-dbgsym_7.9p1-10+deb10u2_amd64.deb
[  240s] DEBS/openssh_7.9p1-10+deb10u2.debian.tar.xz
[  240s] DEBS/openssh-tests-dbgsym_7.9p1-10+deb10u2_amd64.deb
[  240s] OTHER/_statistics
Server returned an error: HTTP Error 404: Not Found
remote error: package 'openssh-server' has no logfile

If I use the built-in worker in OBS server, everything is OK,  why does using separate worker delivery the error, IS THIS a BUG, I have no idea about it, Could you give me a idea or advice to fix it ?

**Comment by marcus-h** [comment]
On 2021-03-17 17:32:20 -0700, yuening1999 wrote:
> If I use the built-in worker in OBS server, everything is OK,  why does using separate worker delivery the error, IS THIS a BUG, I have no idea about it, Could you give me a idea or advice to fix it ?
>
If a job is dispatched to your "separate" worker, is it still possible
to view the live buildlog?

**Comment by yuening1999** [comment]
yes, marcus, I can view buildlog on separate in real-time.

Can updating BSConfig.pm configuration resolve the problem  or modifying relevant codes ?

**Comment by marcus-h** [comment]
On 2021-03-18 06:01:57 -0700, yuening1999 wrote:
> yes, marcus, I can view buildlog on separate worker  in real-time.
>
> Can updating BSConfig.pm configuration resolve the problem  or modifying relevant codes ?
>
Did the "error" occur again while running the build + viewing the
buildlog? The "error" message itself is not necessarily a
problem...

**Comment by yuening1999** [comment]
sure, marcus, the error always ocurr, and badhost event was reported in dispatcher.log;  Dispatcher will select next idle worker to create a new building, until wear out all idle workers; 

In my opinion, the reason that lead to the result above is buildlog can not be sent back to repo server. maybe this is a defect.

In addition,  separate arm64 worker also can not work fine,  same error ocurr. if you think this is not a problem, Could you give good suggestion about separate worker usage, or using x86 worker emulate arm64 build job?

**Comment by yuening1999** [comment]
> On 2021-03-18 06:01:57 -0700, yuening1999 wrote:
> > yes, marcus, I can view buildlog on separate worker  in real-time.
> >
> > Can updating BSConfig.pm configuration resolve the problem  or modifying relevant codes ?
> >
> Did the "error" occur again while running the build + viewing the
> buildlog? The "error" message itself is not necessarily a
> problem...
> 

Basically, I can determine the problem lie in     "repo server", it seem as if repo server automatically close its TCP connection. Could anybody tell me why?  maybe starting code investigation can get good answer.  But that is not a good choice to me at present, because I only want to get a good usage experience now.

**Comment by marcus-h** [comment]
On 2021-03-21 19:03:56 -0700, yuening1999 wrote:
> > On 2021-03-18 06:01:57 -0700, yuening1999 wrote:
> > > yes, marcus, I can view buildlog on separate worker  in real-time.
> > >
> > > Can updating BSConfig.pm configuration resolve the problem  or modifying relevant codes ?
> > >
> > Did the "error" occur again while running the build + viewing the
> > buildlog? The "error" message itself is not necessarily a
> > problem...
> >
>
> Basically, I can determine the problem lie in     "repo server", it seem as if repo server automatically close its TCP connection. Could anybody tell me why?

I'm a bit puzzled now - I don't see any relation between this "error"
message and a TCP connection. About which TCP connection are you
talking?

> maybe starting code investigation can get good answer.  But that is not a good choice to me at present, because I only want to get a good usage experience now.
>
Hmm what is actually "broken" (from a user's POV)?

**Comment by yuening1999** [comment]
> On 2021-03-21 19:03:56 -0700, yuening1999 wrote:
> > > On 2021-03-18 06:01:57 -0700, yuening1999 wrote:
> > > > yes, marcus, I can view buildlog on separate worker  in real-time.
> > > >
> > > > Can updating BSConfig.pm configuration resolve the problem  or modifying relevant codes ?
> > > >
> > > Did the "error" occur again while running the build + viewing the
> > > buildlog? The "error" message itself is not necessarily a
> > > problem...
> > >
> >
> > Basically, I can determine the problem lie in     "repo server", it seem as if repo server automatically close its TCP connection. Could anybody tell me why?
> 
> I'm a bit puzzled now - I don't see any relation between this "error"
> message and a TCP connection. About which TCP connection are you
> talking?
I also was confused with the context, because I monitor worker's tcp port by "nc" command, it work fine, therefore, I think the   problem lie in scheduler  server or repository server(I only conclude this point by  "18.2 communication flow" in obs-user-guide, if my point is not correct, pls point out). In addition, Could you explain that how do build log info interact between worker and scheduler/repo server in detail?
> 
> > maybe starting code investigation can get good answer.  But that is not a good choice to me at present, because I only want to get a good usage experience now.
> >
> Hmm what is actually "broken" (from a user's POV)?
From POV,  only  build log can not be taken from worker. But after I investigate /var/cache/obs/worker/root_x on my worker host, I found that .build.log exist during whole compiling process. after all deb packages were delivered(buildjob finished),
.build.log will disappear, meanwhile, errors above occur that can be viewed from web front UI or "osc rbl" command.

sincerely speaking, I need your help, because I can not resolve the problem from user view,  I had been broken for a month above on the problem

**Comment by marcus-h** [comment]
On 2021-03-22 18:08:50 -0700, yuening1999 wrote:
> > Hmm what is actually "broken" (from a user's POV)?
> From POV,  only  build log can not be taken from worker.

What does this mean?

> But after I investigate /var/cache/obs/worker/root_x on my worker host, I found that .build.log exist during whole compiling process. after all deb packages were delivered(buildjob finished),
> .build.log will disappear, meanwhile, errors above occur that can be viewed from web front UI or "osc rbl" command.
>
That is, the error occurs while viewing the live build log via
"osc rbl ..."? If so, can you please share the whole output of
"osc -d rbl ..."?
(If I got you right, you said in another mail that the live build log
works for you.)

**Comment by yuening1999** [comment]
> On 2021-03-22 18:08:50 -0700, yuening1999 wrote: > Hmm what is actually "broken" (from a user's POV)? From POV, only build log can not be taken from worker.
> What does this mean?
> But after I investigate /var/cache/obs/worker/root_x on my worker host, I found that .build.log exist during whole compiling process. after all deb packages were delivered(buildjob finished), .build.log will disappear, meanwhile, errors above occur that can be viewed from web front UI or "osc rbl" command.
> That is, the error occurs while viewing the live build log via "osc rbl ..."? If so, can you please share the whole output of "osc -d rbl ..."? (If I got you right, you said in another mail that the live build log works for you.)

sorry, marcus, I make you confused, live log work fine, But after  build job finished, the errror occur as following(use "osc -d rbl ...",  tttt.txt is full build log, everything is ok,):

Server returned an error: HTTP Error 400: Bad Request
Date: Wed, 24 Mar 2021 08:31:42 GMT
Server: Apache
Cache-Control: private
Vary: Accept-Encoding
Referrer-Policy: strict-origin-when-cross-origin
X-Permitted-Cross-Domain-Policies: none
X-XSS-Protection: 1; mode=block
X-Opensuse-Runtimes: {"view":null,"db":29.686594999475346,"backend":0}
X-Request-Id: 5f7ae850-6f47-4f7c-b112-2558d0df4b12
X-Opensuse-APIVersion: 2.10.10
Content-Disposition: inline
X-Download-Options: noopen
Content-Transfer-Encoding: binary
X-Runtime: 0.833344
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Powered-By: Phusion Passenger 6.0.7
Status: 400 Bad Request
Cache-Control: public
Connection: close
Transfer-Encoding: chunked
Content-Type: text/xml

<status code="400">
  <summary>remote error: remote error  Logfile is not that big</summary>
  <details>400 remote error: remote error  Logfile is not that big</details>
</status>

remote error: remote error  Logfile is not that big


[tttt.txt](https://github.com/openSUSE/open-build-service/files/6193542/tttt.txt)

**Comment by marcus-h** [comment]
On 2021-03-23 17:43:00 -0700, yuening1999 wrote:
> > On 2021-03-22 18:08:50 -0700, yuening1999 wrote: > Hmm what is actually "broken" (from a user's POV)? From POV, only build log can not be taken from worker.
> > What does this mean?
> > But after I investigate /var/cache/obs/worker/root_x on my worker host, I found that .build.log exist during whole compiling process. after all deb packages were delivered(buildjob finished), .build.log will disappear, meanwhile, errors above occur that can be viewed from web front UI or "osc rbl" command.
> > That is, the error occurs while viewing the live build log via "osc rbl ..."? If so, can you please share the whole output of "osc -d rbl ..."? (If I got you right, you said in another mail that the live build log works for you.)
>
> sorry, marcus, I make you confused, live log work fine, But after  build job finished, the errror occur as following(use "osc -d rbl ...",  tttt.txt is full build log, everything is ok,):
>
Hmm unfortunately osc's debug output is not part of the tttt.txt file:/
Either you manually copy the output from your terminal or you use the
appropriate redirections: osc -d rbl ... > log.txt 2>&1
(If you choose the latter, you have to use a patched osc:/ (see [1])).

[1] https://github.com/openSUSE/osc/pull/906

**Comment by yuening1999** [comment]
> On 2021-03-23 17:43:00 -0700, yuening1999 wrote: > On 2021-03-22 18:08:50 -0700, yuening1999 wrote: > Hmm what is actually "broken" (from a user's POV)? From POV, only build log can not be taken from worker. > What does this mean? > But after I investigate /var/cache/obs/worker/root_x on my worker host, I found that .build.log exist during whole compiling process. after all deb packages were delivered(buildjob finished), .build.log will disappear, meanwhile, errors above occur that can be viewed from web front UI or "osc rbl" command. > That is, the error occurs while viewing the live build log via "osc rbl ..."? If so, can you please share the whole output of "osc -d rbl ..."? (If I got you right, you said in another mail that the live build log works for you.) sorry, marcus, I make you confused, live log work fine, But after build job finished, the errror occur as following(use "osc -d rbl ...", tttt.txt is full build log, everything is ok,):
> Hmm unfortunately osc's debug output is not part of the tttt.txt file:/ Either you manually copy the output from your terminal or you use the appropriate redirections: osc -d rbl ... > log.txt 2>&1 (If you choose the latter, you have to use a patched osc:/ (see [1])). [1] [openSUSE/osc#906](https://github.com/openSUSE/osc/pull/906)

Hi, macus 
In fact, the previous log(tttt.txt) + Server returned an error: HTTP Error 400: Bad Request.... = "log.txt"  : )
[log.txt](https://github.com/openSUSE/open-build-service/files/6203043/log.txt)

**Comment by marcus-h** [comment]
On 2021-03-25 01:18:25 -0700, yuening1999 wrote:
> In fact, the previous log(tttt.txt) + Server returned an error: HTTP Error 400: Bad Request.... = "log.txt"  : )
> [log.txt](https://github.com/openSUSE/open-build-service/files/6203043/log.txt)
>
No, the log.txt also contains the "GET ..." lines:)
Can you apply the following patch to your bs_worker file, restart
the build and post the output of "osc -d rbl ..."?

```
diff --git a/src/backend/bs_worker b/src/backend/bs_worker
index bc0b3ee1c8..021333c15b 100755
--- a/src/backend/bs_worker
+++ b/src/backend/bs_worker
@@ -848,7 +848,7 @@ sub stream_logfile {
     $end -= $start;
     die("end is smaller than start\n") if $end < 0;
   }
-  die("Logfile is not that big\n") if $s[7] < abs($start);
+  die("Logfile is not that big ($s[7] vs. $start)\n") if $s[7] < abs($start);
   defined(sysseek(F, $start, $start < 0 ? Fcntl::SEEK_END : Fcntl::SEEK_SET)) || die("sysseek: $!\n");

   BSServer::reply(undef, 'Content-Type: text/plain', 'Transfer-Encoding: chunked');
```

(The bs_worker file is located on the host where the bs_repserver is
installed/running (the file on your worker is automatically "updated").)

Which osc version are you using?

**Comment by yuening1999** [comment]
> On 2021-03-25 01:18:25 -0700, yuening1999 wrote: In fact, the previous log(tttt.txt) + Server returned an error: HTTP Error 400: Bad Request.... = "log.txt" : ) [log.txt](https://github.com/openSUSE/open-build-service/files/6203043/log.txt)
> No, the log.txt also contains the "GET ..." lines:) Can you apply the following patch to your bs_worker file, restart the build and post the output of "osc -d rbl ..."? ``` diff --git a/src/backend/bs_worker b/src/backend/bs_worker index bc0b3ee1c8..021333c15b 100755 --- a/src/backend/bs_worker +++ b/src/backend/bs_worker @@ -848,7 +848,7 @@ sub stream_logfile { $end -= $start; die("end is smaller than start\n") if $end < 0; } - die("Logfile is not that big\n") if $s[7] < abs($start); + die("Logfile is not that big ($s[7] vs. $start)\n") if $s[7] < abs($start); defined(sysseek(F, $start, $start < 0 ? Fcntl::SEEK_END : Fcntl::SEEK_SET)) || die("sysseek: $!\n"); BSServer::reply(undef, 'Content-Type: text/plain', 'Transfer-Encoding: chunked'); ``` (The bs_worker file is located on the host where the bs_repserver is installed/running (the file on your worker is automatically "updated").) Which osc version are you using?

Hi, macus
According to  the added debug info for your code patch, I test it again using "osc -d rbl ....", I can got the following output error,  logfile size is 0,  wow, why? 

[   45s] [   39.124597] sysrq: SysRq : Power Off
[   45s] [   39.126303] reboot: Power down
[   45s] ### VM INTERACTION END ###
[   45s] build: extracting built packages...
[   45s] DEBS/hello_2.10-2_amd64.buildinfo
[   45s] DEBS/hello_2.10-2.dsc
[   45s] DEBS/hello_2.10.orig.tar.gz
[   45s] DEBS/hello-dbgsym_2.10-2_amd64.deb
[   45s] DEBS/hello_2.10-2_amd64.changes
[   45s] DEBS/hello_2.10-2.debian.tar.xz
[   45s] DEBS/hello_2.10-2_amd64.deb
[   45s] OTHER/_statistics
GET https://linx-obs.rd5.linx-info.com/build/home:ynliu:test/Debian_10/x86_64/hello/_log?start=102277&nostream=1
Server returned an error: HTTP Error 400: Bad Request
Date: Fri, 26 Mar 2021 09:03:30 GMT
Server: Apache
Cache-Control: private
Vary: Accept-Encoding
Referrer-Policy: strict-origin-when-cross-origin
X-Permitted-Cross-Domain-Policies: none
X-XSS-Protection: 1; mode=block
X-Opensuse-Runtimes: {"view":null,"db":55.34284099985598,"backend":0}
X-Request-Id: e4279307-83ba-4581-9f8b-6ea162e1d8d1
X-Opensuse-APIVersion: 2.10.10
Content-Disposition: inline
X-Download-Options: noopen
Content-Transfer-Encoding: binary
X-Runtime: 0.283617
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Powered-By: Phusion Passenger 6.0.7
Status: 400 Bad Request
Cache-Control: public
Connection: close
Transfer-Encoding: chunked
Content-Type: text/xml

<status code="400">
  <summary>remote error: remote error  Logfile is not that big (0 vs. 102277)</summary>
  <details>400 remote error: remote error  Logfile is not that big (0 vs. 102277)</details>
</status>

remote error: remote error  Logfile is not that big (0 vs. 102277)

In addition , my osc verison is as following:

$ osc --version
0.164.2

**Comment by marcus-h** [comment]
On 2021-03-25 18:22:23 -0700, yuening1999 wrote:
> According to  the added debug info for your code patch, I test it again using "osc -d rbl ....", I can got the following output error,  logfile size is 0,  wow, why?
>
That's interesting. How many workers do you have? Does it only happen
with this specific worker or are also other workers affected? What's
the arch/distro of the worker?
Which version of the "build" package is installed on the bs_repserver
host? (rpm -q build)

Can you try the following:
- run "tail -f /srv/obs/log/dispatcher.log"
- run "tail -f /srv/obs/log/scheduler_x86_64.log"
- trigger a rebuild of the home:ynliu:test hello package
- run "osc -d rbl ..." again

After the error occurs, collect the output of the two tail commands.

> In addition , my osc verison is as following:
>
> $ osc --version
> 0.164.2
>
Hmm that's old but it shouldn't cause this error.

**Comment by yuening1999** [comment]
> On 2021-03-25 18:22:23 -0700, yuening1999 wrote: According to the added debug info for your code patch, I test it again using "osc -d rbl ....", I can got the following output error, logfile size is 0, wow, why?
> That's interesting. How many workers do you have? Does it only happen with this specific worker or are also other workers affected? What's the arch/distro of the worker?

Two separate workers(a x86_64 and a aarch64), I both install opensuse leap 15.1/15.2 on x86_64 and aarch64 platform,
and only install obsworker package on opensuse leap 15.1/15.2 as describled on administrator guide;The same problem/defect occur on x86_64 and aarch64 platform


 Which version of the "build" package is installed on the bs_repserver host? (rpm -q build)
I can not understand "build" package you said, it seem as if that is specially a tool package to opensuse, right? 

$ rpm -q build
build-20210120-lp151.7.1.noarch
I upgrade it to build-20210120-lp151.367.1.noarch using following command
$ zypper install build-20210120-lp151.367.1.noarch
But the upgrade did not contribute to the resolving the problem






 Can you try the following: - run "tail -f /srv/obs/log/dispatcher.log" - run "tail -f /srv/obs/log/scheduler_x86_64.log" - trigger a rebuild of the home:ynliu:test hello package - run "osc -d rbl ..." again After the error occurs, collect the output of the two tail commands.

linx-obs:~ # tail -f /srv/obs/log/scheduler_x86_64.log
setting up watcher for https://api.opensuse.org/public, start=245283002
2021-03-29 10:21:45: [1790]  waiting for an event...
response from watcher for https://api.opensuse.org/public
setting up watcher for https://api.opensuse.org/public, start=245283102
2021-03-29 10:24:28: [1790]  waiting for an event...
2021-03-29 10:26:36: [1790]  event dispatchdetails
2021-03-29 10:26:36: [1790]  waiting for an event...
response from watcher for https://api.opensuse.org/public
setting up watcher for https://api.opensuse.org/public, start=245283203
2021-03-29 10:27:17: [1790]  waiting for an event...


linx-obs:~ # tail -f /srv/obs/log/dispatcher.log
2021-03-29 10:27:36: [1791]  assignjob x86_64/home:ynliu:test::Debian_10::hello-6713ef9989f08b71080b5f21cf3e86ca -> x86_64:obs-worker-x86:11
2021-03-29 10:27:36: [1791]  badhost event: home:ynliu:test/hello/x86_64/x86_64:obs-worker-x86:13
Use of uninitialized value in concatenation (.) or string at /usr/lib/obs/server/bs_dispatch line 660.
Use of uninitialized value in concatenation (.) or string at /usr/lib/obs/server/bs_dispatch line 661.
2021-03-29 10:27:36: [1791]  assigned 1 jobs
2021-03-29 10:28:47: [1791]  assignjob x86_64/home:ynliu:test::Debian_10::hello-6713ef9989f08b71080b5f21cf3e86ca -> x86_64:obs-worker-x86:18
2021-03-29 10:28:47: [1791]  badhost event: home:ynliu:test/hello/x86_64/x86_64:obs-worker-x86:11
Use of uninitialized value in concatenation (.) or string at /usr/lib/obs/server/bs_dispatch line 660.
Use of uninitialized value in concatenation (.) or string at /usr/lib/obs/server/bs_dispatch line 661.
2021-03-29 10:28:47: [1791]  assigned 1 jobs



> In addition , my osc verison is as following: $ osc --version 0.164.2
> Hmm that's old but it shouldn't cause this error.

In addition, I got a different http error code(404) after a modification to /usr/lib/obs/server/BSConfig.pm and
/srv/www/obs/api/config/options.yml

diff BSConfig.pm BSConfig.pm-bak 
55,56c55,56
< our $workersrcserver = "http://$hostname:5353";
< our $workerreposerver = "http://$hostname:5253";
---
> #our $workersrcserver = "http://$hostname:5353";
> #our $workerreposerver = "http://$hostname:5253";

diff /srv/www/obs/api/config/options.yml /srv/www/obs/api/config/options.yml-bak
9c9
<   use_xforward: true
---
>   #use_xforward: true


[   44s] 
[   44s] ### VM INTERACTION START ###
GET https://linx-obs.rd5.linx-info.com/build/home:ynliu:test/Debian_10/x86_64/hello/_log?start=101819&nostream=1
[   47s] [   41.014336] sysrq: SysRq : Power Off
[   47s] [   41.016102] reboot: Power down
[   47s] ### VM INTERACTION END ###
[   47s] build: extracting built packages...
[   47s] DEBS/hello_2.10-2_amd64.buildinfo
[   47s] DEBS/hello_2.10.orig.tar.gz
[   47s] DEBS/hello-dbgsym_2.10-2_amd64.deb
[   47s] DEBS/hello_2.10-2.debian.tar.xz
[   47s] DEBS/hello_2.10-2_amd64.deb
[   47s] DEBS/hello_2.10-2.dsc
[   47s] DEBS/hello_2.10-2_amd64.changes
[   47s] OTHER/_statistics
GET https://linx-obs.rd5.linx-info.com/build/home:ynliu:test/Debian_10/x86_64/hello/_log?start=102293&nostream=1
Server returned an error: HTTP Error 404: remote error  package 'hello' has no logfile
Date: Mon, 29 Mar 2021 10:28:46 GMT
Server: Apache
Cache-Control: private, no-transform
Referrer-Policy: strict-origin-when-cross-origin
X-Permitted-Cross-Domain-Policies: none
X-XSS-Protection: 1; mode=block
X-Opensuse-Runtimes: {"view":null,"db":27.783311000121103,"backend":0}
X-Request-Id: 2d63a853-0d85-4ffe-a113-11992621b6ac
X-Opensuse-APIVersion: 2.10.10
X-Download-Options: noopen
X-Runtime: 0.239625
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Powered-By: Phusion Passenger 6.0.7
Content-Type: text/xml
Cache-Control: no-cache, public
Content-Length: 166
Connection: close

<status code="404">
  <summary>remote error: package 'hello' has no logfile</summary>
  <details>404 remote error: package 'hello' has no logfile</details>
</status>

remote error: package 'hello' has no logfile

**Comment by marcus-h** [comment]
On 2021-03-28 19:50:42 -0700, yuening1999 wrote:
>
> > On 2021-03-25 18:22:23 -0700, yuening1999 wrote: According to the added debug info for your code patch, I test it again using "osc -d rbl ....", I can got the following output error, logfile size is 0, wow, why?
> > That's interesting. How many workers do you have? Does it only happen with this specific worker or are also other workers affected? What's the arch/distro of the worker?
>
> Two separate workers(a x86_64 and a aarch64), I both install opensuse leap 15.1/15.2 on x86_64 and aarch64 platform,
> and only install obsworker package on opensuse leap 15.1/15.2 as describled on administrator guide;The same problem/defect occur on x86_64 and aarch64 platform
>
>
>  Which version of the "build" package is installed on the bs_repserver host? (rpm -q build)
> I can not understand "build" package you said, it seem as if that is specially a tool package to opensuse, right?
>
> $ rpm -q build
> build-20210120-lp151.7.1.noarch
> I upgrade it to build-20210120-lp151.367.1.noarch using following command
> $ zypper install build-20210120-lp151.367.1.noarch
> But the upgrade did not contribute to the resolving the problem
>
>
>
>
>
>
>  Can you try the following: - run "tail -f /srv/obs/log/dispatcher.log" - run "tail -f /srv/obs/log/scheduler_x86_64.log" - trigger a rebuild of the home:ynliu:test hello package - run "osc -d rbl ..." again After the error occurs, collect the output of the two tail commands.
>
Can you do the same but this time also include the rep_server.log?
tail -f /srv/obs/log/rep_server.log

> > In addition , my osc verison is as following: $ osc --version 0.164.2
> > Hmm that's old but it shouldn't cause this error.
>
> In addition, I got a different http error code(404) after a modification to /usr/lib/obs/server/BSConfig.pm and
> /srv/www/obs/api/config/options.yml
>
> diff BSConfig.pm BSConfig.pm-bak
> 55,56c55,56
> < our $workersrcserver = "http://$hostname:5353";
> < our $workerreposerver = "http://$hostname:5253";
> ---
> > #our $workersrcserver = "http://$hostname:5353";
> > #our $workerreposerver = "http://$hostname:5253";
>
Hmm IMHO you can disable this setting (keep the commented default)
but from a quick glance at the code it shouldn't make a difference.

**Comment by marcus-h** [comment]
On 2021-03-29 06:45:19 -0700, yuening1999 wrote:
> From developer view, maybe no problems were found,

Uhm I didn't say that there no issue... that's why I asked for the
rep_server.log

> Does some special instructions exist for configuring it to work fine? Because I can not gotten it work fine according to "user guide" and "administrator guide".
>
If you install/use the appliance it should probably just work "out
of the "box".

**Comment by yuening1999** [comment]
> On 2021-03-29 06:45:19 -0700, yuening1999 wrote: From developer view, maybe no problems were found,
> Uhm I didn't say that there no issue... that's why I asked for the rep_server.log
> Does some special instructions exist for configuring it to work fine? Because I can not gotten it work fine according to "user guide" and "administrator guide".
> If you install/use the appliance it should probably just work "out of the "box".

Hi, marcus
I upload the relevant four log file on previous testing environments due to reinstalling my OBS appliance,
the following log files were gotten using official ISO appliance(2.10.x) + separate worker(opensuse 15.2 + install obsworker package), hope these are helpful

[dispatcher.log](https://github.com/openSUSE/open-build-service/files/6225297/dispatcher.log)
[src_server.log](https://github.com/openSUSE/open-build-service/files/6225298/src_server.log)
[rep_server.log](https://github.com/openSUSE/open-build-service/files/6225299/rep_server.log)
[scheduler_x86_64.log](https://github.com/openSUSE/open-build-service/files/6225300/scheduler_x86_64.log)

**Comment by marcus-h** [comment]
On 2021-03-29 17:32:19 -0700, yuening1999 wrote:
> I upload the relevant four log file on previous testing environments due to reinstalling my OBS appliance,
> the following log files were gotten using official ISO appliance(2.10.x) + separate worker(opensuse 15.2 + install obsworker package), hope these are helpful
>
Definitely! It seems that the clock of the worker host and the clock
of the repserver host deviate "significantly". From the rep_server.log:

2021-03-03 09:34:08: [10087] POST (172.30.20.19)    /putjob?job=home:ynliu:test::Debian_10::hello-6713ef9989f08b71080b5f21cf3e86ca&arch=x86_64&jobid=a36a82c70684a97c77b8252bd14bf914&code=succeeded&now=1614735253&workerid=obs-worker-x86:7
172.30.20.19 [10087]: time mismatch

The bs_repserver only accepts a deviation of one hour (1614735253 is
"Wed Mar  3 02:34:13 AM CET 2021"). Hence, as a first step, you should
adjust your clocks.

However, this does not explain the "Logfile is not that big" error,
unless several workers, in particular obs-worker-x86:7 and
obs-worker-x86:9, share the _same_ buildroot (--root ... option)
(which would be a misconfiguration).

**Comment by yuening1999** [comment]
Hi,marcus
whether I can skip error "Logfile is not that big" by update bs_worker souce code and make the process continue to the step which archive my deb packages compiled out to repository(viewed on http:// <observername>:82)

**Comment by marcus-h** [comment]
On 2021-03-31 01:15:38 -0700, yuening1999 wrote:
> whether I can skip error "Logfile is not that big" by update bs_worker souce code and make the process continue to the step which archive my deb packages compiled out to repository(viewed on http:// <observername>:82)
>
Hmm I'm not sure what you mean... If you adjust the clocks the built deb
should eventually show up in the in repo. If it doesn't, please share the
logs again (after adjusting the clocks + triggering a rebuild, of course).

**Comment by yuening1999** [comment]
Hi,marcus
I had resolve the problem. I will close it.

In addition, the problem lie in our network environment, maybe network security policy lead to the problem, irrelevant to OBS source code
