### ISSUE TITLE
Can't create Project in Development Environment

### ISSUE THREAD

**Issue by kvelichko-omp** [openSUSE/open-build-service#10913]
# Issue Description
Geting exception `ThinkingSphinx::SphinxError in Webui::ProjectController#create` when try create project in Development environment with Admin credential.
 
Expected Result
============
Project must created

How to Reproduce
===============
1. Create Development environment with commands:
    ```
    git clone git@github.com:openSUSE/open-build-service.git
    git submodule init
    git submodule update
    rake docker:build
    docker-compose up
    ```
2. Go to  'http://localhost:3000'/ Login with Admin and default password.
3. Press `Create Project`
4. Fill in the field `Project Name`. Press `Accept`
5. Get Exception

Further Information
===============
* docker-compose version 1.27.4
* rake version 12.3.1
* http://127.0.0.1:3000/project/new
* OBS master HEAD

**Comment by dmarcoux** [comment]
I don't know why ThinkingSphinx isn't running, but it should. You can start a shell in the `frontend` container with `docker exec -it name-of-frontend-container bash --l` (find the name of the frontend container with `docker ps`, then run `bundle exec rake ts:start` and ThinkingSphinx will be started. This should fix the issue you're having.

**Comment by kvelichko-omp** [comment]
I'm enter in frontend container with command `docker exec -ti <FRONTENDID> bash`.
Check currently running process:
```
> ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
frontend     1  0.3  0.1 132076 21700 ?        Ssl  10:32   0:00 foreman: master
frontend     9 14.7  2.0 1281944 324600 ?      Sl   10:32   0:11 puma 5.2.2 (tcp://0.0.0.0:3000) [api]
frontend    10 15.5  1.3 579660 220828 ?       Sl   10:32   0:12 script/delayed_job.api.rb run
frontend    11  5.8  1.1 596200 186244 ?       Sl   10:32   0:04 ruby.ruby2.5 /usr/bin/clockworkd --log-dir=log -l -c config/clock.rb run
frontend    12 11.8  1.1 389660 179520 ?       Sl   10:32   0:09 /usr/bin/ruby.ruby2.5 bin/rails ts:start NODETACH=true
frontend   139  0.2  0.0 145512 12644 ?        Sl   10:32   0:00 /usr/bin/searchd --pidfile --config /obs/src/api/config/development.sphinx.conf --nodetach
frontend   188  0.2  0.0  16972  6052 pts/0    Ss   10:33   0:00 bash
frontend   217  0.0  0.0  34884  3216 pts/0    R+   10:33   0:00 ps aux
```
Sphinx is running.

Execute `bundle exec rake ts:start`:
```
> bundle exec rake ts:start
rake aborted!
ThinkingSphinx::SphinxAlreadyRunning: searchd is already running

Tasks: TOP => ts:start
(See full trace by running task with --trace)
```

Exception present.

**Comment by kvelichko-omp** [comment]
I execute `bundle exec rake ts:rebuild` and reboot Developer enviroment. And Project created successfull.

**Comment by dmarcoux** [comment]
Glad to know that it's working now.
