### ISSUE TITLE
Reviews disappear when sorting by Source

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#10950]
I have 10 open reviews atm, but if I click on 'Source' column once, 5 of them disappear. If I click on Source column as 2nd time, even only 4 are displayed. if I go back to sort by "Created at", it's 10 again. 

The sources are all different projects.

Expected Result
============
It should be 10 out of 10 no matter how sorted.

Further Information
===============
* I've seen this on build.suse.de, on build.opensuse.org I have no reviews atm

**Comment by dmarcoux** [comment]
This is on the `Tasks` page. Screenshots are the ones @coolo shared on Rocket.Chat

**Sorting by `Created`**
![1](https://user-images.githubusercontent.com/1102934/112845827-980e2700-90a5-11eb-89a7-18870cd9308c.png)

**Sorting by `Source` (ascending and descending)**
![2](https://user-images.githubusercontent.com/1102934/112845830-993f5400-90a5-11eb-8bf1-3878dfefa8f7.png)
![3](https://user-images.githubusercontent.com/1102934/112845831-99d7ea80-90a5-11eb-9e41-654590e845c2.png)

**Comment by coolo** [comment]
thanks for filling the gaps
