### ISSUE TITLE
User.involved_patchinfos performance

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#10959]
There are users who are involved in hundreds of patchinfos. This method is not handling this gracefully, querying (building a hash) of 230 takes around 30 to 40 seconds. Rendering them another 6-7 minutes.

This leads to enormous [load times](https://bs-monitor.nue.suse.com:3000/d/fzuOfHQik/api_internal-request?orgId=1&var-request_id=85fa23b2-731c-43ec-828a-f79462d46354&from=1614621636601&to=1614622117627&var-method=Webui::Users::TasksController%23index) for the my tasks page for instance.

**Comment by dmarcoux** [comment]
Creating a few records to test this out in the development environment:
1. Create a patchinfo in the home project of the `Admin` user.
2. Run this in the Rails console: `50.times { FactoryBot.create(:package_issue, issue: FactoryBot.create(:issue, state: 'OPEN', issue_tracker: issue_tracker, owner: User.find_by(login: 'Admin')), package: PackageKind.last.package) }`
