### ISSUE TITLE
Error when try remove group member with dot

### ISSUE THREAD

**Issue by kvelichko-omp** [openSUSE/open-build-service#10955]
# Issue Description
Error received when try to remove user with dot from group members. 

Request `DELETE /groups/GROUPNAME/user/u.name` return 404 Not Found.

Expected Result
============
Remove user with dot from group members.

How to Reproduce
===============
1. Go to 'https://os-build.devel.pro/group/show/GROUPNAME'
2. Add Group member with dot `u.name`
3. Click on 'Remove member from group' `(X)`

Further Information
===============
* OBS Server 2.10.10

**Comment by dmarcoux** [comment]
Hi @kvelichko-omp,

To remove a group member from a group with the API, I suggest using [osc](https://github.com/openSUSE/osc):
```bash
osc --apiurl=https://os-build.devel.pro api -X POST "group/GROUP_NAME?cmd=remove_user&userid=USER_LOGIN"
```

As for removing a group member in the UI, it's true that it doesn't work when the user's login contains one or multiple dots. This is definitely a bug. The modal, allowing you to remove the group member, doesn't appear.

**Comment by kvelichko-omp** [comment]
Thanks. This helpful.

**Comment by kvelichko-omp** [comment]
Will you be porting this patch to 2.10?

**Comment by dmarcoux** [comment]
We tend to create new `2.10` releases only for fixing security issues, so even if I ported this to `2.10`, it wouldn't be released until there is a security issue we need to address.

**Comment by kvelichko-omp** [comment]
Ok. Then I cherry-pick these changes to my local installation. thanks
