### ISSUE TITLE
Cannot build OBS 2.10

### ISSUE THREAD

**Issue by ar-lex** [openSUSE/open-build-service#10965]
# Issue Description
OBS 2.10 cannot be built since the licensing issue with `mimemagic` gem. Without any changes to packaging the `bundle_gems` source service fails to install yanked `mimemagic` vesion.

Expected Result
============
`bundle_gems` service successfully downloads all gems. OBS service is successfully built with bundled gems.

How to Reproduce
===============
1. Create a home project branch of obs-server package in OBS:Server:2.10 project
2. See the failed source service

**Comment by dmarcoux** [comment]
This was handled in #10977. It will be fixed once we release 2.10.11.
