### ISSUE TITLE
Enable debbuild engine for Ubuntu targets on build.opensuse.org

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/open-build-service#1099]
Currently, debbuild is only enabled for Debian targets on build.opensuse.org, however, it fully supports detecting and supporting Ubuntu targets just fine. It even defines a %{ubuntu} variable that can be used to do release-specific configuration.

Please enable it so that the debbuild engine can be used for Ubuntu targets as well as Debian targets.

**Comment by adrianschroeter** [comment]
debbuild is also not enable by default for Debian targets as well. 
I fear to enable it by default, since it will make the already slow on debian install process even slower and resource (not verified, but that was the case for fedora mock engine). Also the switch might have an effect to the build result, so I would do so only for new targets.

We could add a second special repo which is using this engine though.

**Comment by mlschroe** [comment]
You mean add Ubuntu:debbuild, like with Debian:debbuild? Sure, we can do that.

**Comment by adrianschroeter** [comment]
doesn't it make sense to have this as second repo instead? We will forget to update the :debbuild project otherwise (like it happened with Debian:8.0 already;)

**Comment by Conan-Kudo** [comment]
I didn't mean enable by default, just enable it so I can turn it on. :)

Right now... I can't even do that.

**Comment by mlschroe** [comment]
(I've created Ubuntu:debbuild for now)

**Comment by Conan-Kudo** [comment]
@mlschroe Could you add Ubuntu 12.04 LTS and 14.04 LTS targets to Ubuntu:debbuild?

**Comment by mlschroe** [comment]
Sure, done.

**Comment by Conan-Kudo** [comment]
@mlschroe Thank you!

@adrianschroeter To your mention of adding time to the Debian/Ubuntu target setup, adding debbuild adds no time because its dependencies are mostly already satisfied by the build environment. Unless you're also pulling in the "Suggests", which would include RPM (for spec sanity checking) and subversion (which is pretty much unnecessary), there's not much that isn't already in the build environment for debbuild. That said, it shouldn't be the default build engine for those targets. Ideally, a configure switch exposed in the GUI would allow people to choose.

In any case, I propose that a project called "BuildEngine:debbuild" gets created with all the Debian/Ubuntu targets. That way, there's one place that has to be updated for debbuild to get updated for projects that use it. I don't know if it's possible for projects to "automatically" get newer targets when OBS has them added, but if it is, that should probably be done too.

After all, when I submit new releases of debbuild to OBS, it'd be nice if it were updated for all targets...
