### ISSUE TITLE
Enable debbuild engine for Debian and Ubuntu targets for private OBS instances

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/open-build-service#1100]
Note: This is somewhat dependent on #1099, as at the time of this writing, Ubuntu targets aren't enabled on build.opensuse.org.

I'd like to use the debbuild engine on my local OBS appliances for both Debian and Ubuntu targets, as I find it to be a much nicer way to construct packages targeting a wider array of distributions. While debbuild itself works in build.opensuse.org, local appliances cannot yet use it, it seems.

Could you please enable it for private instances?

**Comment by adrianschroeter** [comment]
independend of what we do on build.o.o, you can always use it in your instance by adding 

BuildEngine: debbuild
Support: debbuild pax
Keep: debbuild


to your project config (osc meta prjconf)

**Comment by Conan-Kudo** [comment]
I've done that, but it bombs out on my private instance on trying to get rpm. Meaning it doesn't know what the debbuild engine is.

**Comment by Conan-Kudo** [comment]
I had to upgrade to the latest packaged unstable code, but now I'm finally able to use the engine.
