### ISSUE TITLE
Edit of package Text in Webfrontend pulls wrong values

### ISSUE THREAD

**Issue by coogor** [openSUSE/open-build-service#11055]
I want to edit a typo in a package description:
![Screenshot_20210428_092953](https://user-images.githubusercontent.com/5717703/116364617-af574600-a804-11eb-9810-4877766d651a.png)
When I hit 'Edit' the following information is prefilled:
![Screenshot_20210428_093022](https://user-images.githubusercontent.com/5717703/116364716-c7c76080-a804-11eb-8de1-8c2eb5052ae3.png)
-> somehow the wrong information is prefilled in the different fields....

**Comment by hennevogel** [comment]
Pressing the cancel button is not resetting the form, just hiding it. Shit+reload will reset the form.
