### ISSUE TITLE
link.xml in docs/api/api/ is invalid

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#11067]
The example `_link` file:
https://github.com/openSUSE/open-build-service/blob/65901a1d979c2665b21c8f643edf25ad1cc47757/docs/api/api/link.xml#L2

is invalid provided that I understand the backend code correctly:
https://github.com/openSUSE/open-build-service/blob/65901a1d979c2665b21c8f643edf25ad1cc47757/src/backend/BSSrcServer/Link.pm#L556

So `cicount` should be either `add`, `copy`, `local` or not present at all, but not a number.

**Comment by dcermak** [comment]
I'll be more than happy to submit a PR, if someone would confirm my observation. @adrianschroeter or @mlschroe maybe?

**Comment by adrianschroeter** [comment]
yep, you are right, make it a choice in rng please.
