### ISSUE TITLE
migrate :with_data is failing

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#11118]
Our documented (and used in deploy scripts) way of updating fails atm:

# rails db:migrate:with_data

This happens because the data migration "backfill_add_kind_to_path_element" runs before the kind column to the path_elements table got added
it works when doing it first without :with_data , but that is a different behavior we used to have.

**Comment by hennevogel** [comment]
Hm somehow I fscked up the the timestamps. See #11129
