### ISSUE TITLE
Branching a package copies the description and the title but not the url

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#11127]
# Issue Description
Branching a package copies the title and the description, but not the url.

As can be seen in [this branch of ding](https://build.opensuse.org/package/show/home:danidoni:branches:X11:Utilities/ding), it lacks the url the [linked package](https://build.opensuse.org/package/show/X11:Utilities/ding) has.

Expected Result
============
The branching should copy the title, the description and the url.

How to Reproduce
===============
1. Go to [ding](https://build.opensuse.org/package/show/X11:Utilities/ding) package.
2. Branch it off clicking on the left action menu.
3. See no url in the branched package.

**Comment by vishaldeepak** [comment]
Id like to give this a shot

**Comment by dmarcoux** [comment]
@vishaldeepak Sure, let us know if something isn't clear.

**Comment by saraycp** [comment]
This was fixed in PR [#11352](https://github.com/openSUSE/open-build-service/pull/11352)
