### ISSUE TITLE
Authorization issues with the "Files Changed" link

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#11125]
# Issue Description
Somehow, I need to log in to see files changed in a package revision. Whether this is fine or not, I'm not sure. It's clearly wrong though that the link is displayed if someone isn't authorized to navigate to that page.

Expected Result
============
We either authorize anonymous users to see files changed or we hide the link.

How to Reproduce
===============
1. As an anonymous user, go to https://build.opensuse.org/package/revisions/utilities/tealdeer
2. Click on a `Files Changed` link.
3. See the authorization error

Further Information
===============
![files-changes-authorization](https://user-images.githubusercontent.com/1102934/117795354-65cc1980-b24e-11eb-820b-d9d61c056d5f.gif)

**Comment by hennevogel** [comment]
> It's clearly wrong though that the link is displayed if someone isn't authorized to navigate to that page.

It's more a matter of style IMHO, you can do both. This style for instance encourages sign-ups.

**Comment by hennevogel** [comment]
Performance. Generating diffs can be a very costly operation.

**Comment by dmarcoux** [comment]
Okay, so I guess we keep it as it is. I'll just add a comment to the code regarding this.
