### ISSUE TITLE
The diff in SR is broken when diff is > 999 lines on chrome/chromium

### ISSUE THREAD

**Issue by ggardet** [openSUSE/open-build-service#11168]
# Issue Description
The diff in SR is broken when diff is > 999 lines on chrome/chromium
See: https://paste.opensuse.org/view/raw/69034898 and https://paste.opensuse.org/view/raw/82007511

Expected Result
============
The diff should not break when number of lines is > 999

How to Reproduce
===============
1. Go to https://build.opensuse.org/request/show/894192 with chrome/chromium
2. See the problem

Further Information
===============
* On OBS: https://build.opensuse.org/request/show/894192

**Comment by eduardoj** [comment]
Related to #11133.
