### ISSUE TITLE
search doesn't find packages in openSUSE:Leap:15.3

### ISSUE THREAD

**Issue by JanZerebecki** [openSUSE/open-build-service#11191]
# Issue Description
The search doesn't show results for openSUSE:Leap:15.3.

Expected Result
============
The package openSUSE:Leap:15.3:Update/rubygem-redcarpet is in the results.

How to Reproduce
===============
```
> osc ls openSUSE:Leap:15.3:Update rubygem-redcarpet
_link
# -> openSUSE:Leap:15.3:Update rubygem-redcarpet.14964 (latest)
gem2rpm.yml
redcarpet-3.4.0.gem
rubygem-redcarpet-rpmlintrc
rubygem-redcarpet.changes
rubygem-redcarpet.spec
> osc --debug search -s redcarpet
GET https://api.opensuse.org/search/project?match=contains%28%40name%2C+%27redcarpet%27%29+or+contains%28title%2C+%27redcarpet%27%29+or+contains%28description%2C+%27redcarpet%27%29
GET https://api.opensuse.org/search/package?match=contains%28%40name%2C+%27redcarpet%27%29+or+contains%28title%2C+%27redcarpet%27%29+or+contains%28description%2C+%27redcarpet%27%29
[no mention of Leap]
```

**Comment by vpereira** [comment]
if i remember correctly, it should show up here too `osc maintained rubygem-redcarpet`

**Comment by adrianschroeter** [comment]
15.3 is using the Jump concept. Therefore these packages are not part of 15.3 itself anymore:

# osc meta pkg openSUSE:Leap:15.3:Update rubygem-redcarpet
<package name="rubygem-redcarpet" project="SUSE:SLE-15-SP1:Update">

osc maintained finds exactly this version.

still, branching and submiting back still works. However, all that is a setup issue and has nothing to do with OBS code, so closing this here now.
