### ISSUE TITLE
SCM integration doesn't support gitlab private instances

### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#11198]
Based on this code https://github.com/openSUSE/open-build-service/blob/master/src/api/app/services/workflows/yaml_downloader.rb#L28, we just support gitlab.com, and not i.e gitlab.suse.de

**Comment by hennevogel** [comment]
I think we should clarify this limit in the blog post too.

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support private instances of GitLab and GitHub Enterprise](https://trello.com/c/BH6wfawy/2277-support-private-instances-of-gitlab-and-github-enterprise)

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Don't hardcode SCM URLs](https://trello.com/c/HY5ug2HA/2262-dont-hardcode-scm-urls)

**Comment by vpereira** [comment]
> I think we should clarify this limit in the blog post too.

We did it https://openbuildservice.org/2021/06/14/scm-integration-improvements/
