### ISSUE TITLE
No compliant workers for package for Fedora 34 on aarch64

### ISSUE THREAD

**Issue by braewoods** [openSUSE/open-build-service#11205]
# Issue Description
I think I have found a bug with OBS and how it finds compliant workers. The project is home:ungoogled_chromium and the package is ungoogled-chromium-fedora. The Fedora 34 repository fails to build with the message "no compliant workers" on aarch64 architecture but it succeeds on Fedora 33. The only build constraints we use are part of the project config which shouldn't be a problem here yet Fedora 34 is failing where Fedora 33 succeeds on the same architecture.

Expected Result
============
That the build is able to start.

How to Reproduce
===============
1. Upload package.
2. Wait for services to run.
3. See that Fedora 34 on aarch64 cannot start building due to aforementioned error.

Further Information
===============
* https://build.opensuse.org/package/live_build_log/home:ungoogled_chromium/ungoogled-chromium-fedora/Fedora_33/aarch64
* https://build.opensuse.org/package/live_build_log/home:ungoogled_chromium/ungoogled-chromium-fedora/Fedora_34/aarch64

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
