### ISSUE TITLE
SCM integration: OBS branched package doesn't get updated if already exists

### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#11209]
if you open a MR and the package with same id exists as the new MR, the package doesn't get updated

How to reproduce it:

GITLAB:

- Assuming that the gitlab repository had already 2 MRs open. The next MR would be the MR number 3.
- Assuming the source package being `home:vpereirabr:hello_world`

Go to your OBS and branch manually your source package to `home:vpereirabr:PR-3/hello_world`, go to your gitlab repository, and create a new MR. It will be the MR 3

Observed results:

on OBS,  the package `home:vpereirabr:PR-3/hello_world` and don't reflect the changes from MR3

Expected results:

on OBS,  the package `home:vpereirabr:PR-3/hello_world` and include the changes from MR3

References:
- https://build.opensuse.org/package/show/home:vpereirabr:PR-3/hello_world
- https://gitlab.com/vpereira/hello_world/-/merge_requests/3/diffs

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OBS branched package doesn't get updated if already exists](https://trello.com/c/rwKfdGl1/2276-obs-branched-package-doesnt-get-updated-if-already-exists)

**Comment by hennevogel** [comment]
> Go to your OBS and branch manually your source package to home:vpereirabr:PR-3/hello_world

So? Don't do that :)
