### ISSUE TITLE
commitfilelist breaks with broken link

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#1123]
The attempt to remove a "_link" file which points to a not existing revision using "commitfilelist" fails.
We should cover this either in the source server (not expanding when modifing _link file) or we need to special case it in osc.

coolo reported this a comment of issue#1074

**Comment by adrianschroeter** [comment]
(osc could use DELETE operation here of course, but do we really want the commitfilelist failure here?)

**Comment by mlschroe** [comment]
Dunno, I don't see anything in the code that could break. Are you sure that osc doesn't send the 'keeplink' parameter?

**Comment by mlschroe** [comment]
Come to think of it, getprojectservices is called the wrong way anyway. It should not care about the package state before the commit, i.e. if I change a link from project A to project B with a commit, I want the services from B and not A. Adrian, are you ok with that change?

**Comment by adrianschroeter** [comment]
that makes sense, however, how do you want to implement this? First uploading the link, second run getprojectservices using uncommited _link and third commit?

**Comment by mlschroe** [comment]
You're thinking much too complicated. Fixed in commit 95c866e2aa79e9ea8a5e4189c152f7fb7650d0b8
