### ISSUE TITLE
SCM integration: webhook fails with error 500 "Oooops, something went terribly wrong, our application crashed"

### ISSUE THREAD

**Issue by bluca** [openSUSE/open-build-service#11238]
I have set up the Github PR integration as described here: https://openbuildservice.org/2021/05/31/scm-integration/

The webhook setup seems fine, and the "X-GitHub-Event: ping" on creation completed correctly. But when opening a PR with the workflow.yml, nothing happens and under the webhook settings page I can see the request failed with error 500, and somewhere in the response there is "Oooops, something went terribly wrong, our application crashed"

PR: https://github.com/zeromq/libzmq/pull/4214
Project/package it hooks into: https://build.opensuse.org/package/show/network:messaging:zeromq:git-draft/libzmq

Is this a known issue? DId I do something wrong?

**Comment by vpereira** [comment]
Hi @bluca, the `.obs/workflows.yml` should be already on your main/master/whatever branch. It won't get read straight from the PR.

**Comment by bluca** [comment]
Ah yes indeed, thank you! Might be good to add a line to the docs about this

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Document that `.obs/workflows.yml` is only read from the default branch of the SCM repository](https://trello.com/c/nvtaVGjI/2256-document-that-obs-workflowsyml-is-only-read-from-the-default-branch-of-the-scm-repository)
