### ISSUE TITLE
SCM integration: Package build fails on Tumbleweed -  KeyError: 'object_kind'

### ISSUE THREAD

**Issue by nodeg** [openSUSE/open-build-service#11243]
I tested the new CI integration beta feature mentioned [here](https://openbuildservice.org/2021/05/31/scm-integration/) and ran into some issues regarding building the package on Tumbleweed.

# Issue Description
The package build on Tumbleweed fails with the following error message:

```bash
[   41s] now finalizing build dir...
[   41s] ... running 01-add_abuild_user_to_trusted_group
[   41s] ... running 02-set_timezone_to_utc
[   41s] ... running 11-hack_uname_version_to_kernel_version
[   41s] RTNETLINK answers: File exists
[   41s] RTNETLINK answers: File exists
[   41s] Unpacking cobbler-3.2.1+git20210615.30837f37.obscpio ...
[   41s] 4359 blocks
[   41s] Running build time source services...
[   41s] Traceback (most recent call last):
[   41s]   File "/usr/lib/obs/service/tar", line 30, in <module>
[   41s]     main()
[   41s]   File "/usr/lib/obs/service/tar", line 26, in main
[   41s]     TarSCM.run()
[   41s]   File "/usr/lib/obs/service/TarSCM/__init__.py", line 39, in run
[   41s]     task_list.process_list()
[   41s]   File "/usr/lib/obs/service/TarSCM/tasks.py", line 118, in process_list
[   41s]     self.process_single_task(task)
[   41s]   File "/usr/lib/obs/service/TarSCM/tasks.py", line 173, in process_single_task
[   41s]     self.args = self.check_for_branch_request(args)
[   41s]   File "/usr/lib/obs/service/TarSCM/tasks.py", line 156, in check_for_branch_request
[   41s]     if j['object_kind'] == 'merge_request':
[   41s] KeyError: 'object_kind'
[   41s] service run failed for service 'tar'
[   41s] ### VM INTERACTION START ###
[   44s] [   30.534691] sysrq: Power Off
[   44s] [   30.550182] reboot: Power down
[   44s] ### VM INTERACTION END ###
```
On Leap 15.3 e.g. the build succeeds.

Expected Result
============
The package for Tumbleweed should be built successfully.

How to Reproduce
===============
1. Set up the CI integration for OBS and GitHub
2. Set up the use of SCM sources for the repo with a `_service` file
3. Open a pull request
4. See the error in the OBS/Tumbleweed log

Further Information
===============
* [Tumbleweed build log](https://build.opensuse.org/build/home:dgedon:home:dgedon:cobbler:PR-2671/openSUSE_Tumbleweed/x86_64/cobbler/_log)
* [Leap 15.3 build log](https://build.opensuse.org/build/home:dgedon:home:dgedon:cobbler:PR-2671/openSUSE_Leap_15.3/x86_64/cobbler/_log)
* [Branched package in OBS](https://build.opensuse.org/package/show/home:dgedon:home:dgedon:cobbler:PR-2671/cobbler)

**Comment by dmarcoux** [comment]
Which version of `obs-service_tar_scm` do you have installed? This bug was fixed in the latest version `0.10.25`, [in this commit](https://github.com/openSUSE/obs-service-tar_scm/commit/405750618935948f6e316c2f660ae48681e14654).

**Comment by dmarcoux** [comment]
So somehow, the workers building package have an outdated version of `obs-service_tar_scm`. @openSUSE/obs-frontend: What can we do about this?

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update outdated obs-service-tar_scm in build workers](https://trello.com/c/yr7LpuY2/2265-update-outdated-obs-service-tarscm-in-build-workers)

**Comment by hennevogel** [comment]
Not sure why tar_scm would run during build time..

`[   41s] Running build time source services...`

@M0ses should know

**Comment by adrianschroeter** [comment]
build time sources are configured in sources and the services are used from configured repositories.

**Comment by vpereira** [comment]
@nodeg could you try to rebuild your package please?

**Comment by nodeg** [comment]
Thank you all for the quick response. I already tested it in a [different projekt](https://build.opensuse.org/package/show/systemsmanagement:orthos2:github_master_ci/cobbler-master) today and the build for Tumbleweed was [successful](https://build.opensuse.org/build/systemsmanagement:orthos2:github_master_ci/openSUSE_Tumbleweed/x86_64/cobbler-master/_log). The worked who handled the request must have already had the newer `obs-service_tar_scm` packaged installed. I will have a look at the open request and report back if the error occurs after it was accepted.

**Comment by dmarcoux** [comment]
The request mentionned by @vpereira was merged on last Friday. @nodeg Could you try again in the project which was having issues and let us know how it went?

**Comment by nodeg** [comment]
According to the [build logs](https://build.opensuse.org/package/show/home:dgedon:systemsmanagement:orthos2:github_master_ci:PR-2673/cobbler-master) this issue seems to be fixed.

**Comment by dmarcoux** [comment]
Perfect, thank you @nodeg for testing this again. I checked in the build logs and it's all good. Have a great day!

**Comment by nodeg** [comment]
Thank you all for the quick fix. Have a nice day, too!
