### ISSUE TITLE
Setting an GitHub -> OBS integration with no workflows file in the project root fails

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#11240]
# Issue Description
Setting an GitHub -> OBS integration with no `.obs/workflows.yml` file in the project root fails. It raises an `no implicit conversion of Array into String` error in our [errbit](https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/60b5459484bf4607a94657f7) instance and GitHub's Continuous Integration status reports that `Continuous integration has not been set up`.

Expected Result
============
OBS raising a meaningful error when there is no yml file in the main branch.

How to Reproduce
===============
1. Set up the GitHub integration as explained in [here](https://openbuildservice.org/2021/05/31/scm-integration/) but do not create any `.obs/workflows.yml` file in the repository.
2. Create a PR on the repo.
3. See the `Continuous integration has not been set up` message.
4. See an error in [Errbit](https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/60b5459484bf4607a94657f7) about `no implicit conversion of Array into String`.

**Comment by dmarcoux** [comment]
I don't understand this sentence in the `Expected Results` section:

> The GitHub -> OBS integration be there, and of course no error is raised.

So you expect that no error is raised? I would expect that nothing happens, so no errors and also no reporting back to the SCM.

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Setting an GitHub -> OBS integration with no workflows file in the project root fails](https://trello.com/c/tvLHJGfy/2258-setting-an-github-obs-integration-with-no-workflows-file-in-the-project-root-fails)

**Comment by vpereira** [comment]
> So you expect that no error is raised? I would expect that nothing happens, so no errors and also no reporting back to the SCM.

I think the expectation here is a meaningful error message, not a 500.
