### ISSUE TITLE
The site openbuildservice.org like any google-hosted site, is inaccessible from Crimea

### ISSUE THREAD

**Issue by IlyaIndigo** [openSUSE/open-build-service#11241]
The site https://openbuildservice.org like any google-hosted site, is inaccessible from Crimea.

**Comment by dmarcoux** [comment]
It's hosted on [Netlify](https://www.netlify.com/). Sorry, but there's not much we can do about that... Perhaps this helps you: https://answers.netlify.com/t/access-to-netlify-sites-from-russia-and-ukraine/15314
