### ISSUE TITLE
OBS SCM integration: Be able to limit building per arch or repository

### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#11255]
Today when we have the SCM integration enabled and configured, for every PR we branch source package and try to build the PR for all the same arch/repositories as configured on source package. Ideally, we should be able to configure it.

If you for example for our `obs-server`, you just want to have OBS building for 2 or 3 repositories and 1 or 2 architectures. It should be configurable on `workflows.yml` 

Examples:

- https://build.opensuse.org/project/show/home:vpereirabr:OBS:Server:Unstable:PR-11253
- https://github.com/openSUSE/open-build-service/pull/11253

**Comment by dmarcoux** [comment]
Or perhaps at least only report for certain repositories/architectures. That would already be a good first step.

**Comment by hennevogel** [comment]
This can be achieved by combining `link_package` and `configure_repositories` steps
