### ISSUE TITLE
Request search does not find some requests

### ISSUE THREAD

**Issue by mlschroe** [openSUSE/open-build-service#11266]
```
iosc api /search/request\?match=history%2F%40who%3D%27mlschroe%27
```
does not contain request 240647, which contains:
```
<history who="mlschroe" when="2021-05-05T09:37:28">
    <description>Request created</description>
    <comment>- update to rpm-4.14.3</comment>
</history>
```

**Comment by adrianschroeter** [comment]
"Request Created" became a fake entry, not part of the history element database. Therefore the search does not find it.

the better way for your use case might be a possibility to search for the creator anyway
