### ISSUE TITLE
[production][] nil is invalid as a repository identifier. Use the user/repo (String) format, or the repository I...

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#11262]
threw this 180 times
<pre>
nil is invalid as a repository identifier. Use the user/repo (String) format, or the repository ID (Integer), or a hash containing :repo and :user keys.
</pre>

[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/60c1916e84bf4607a3462372)

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix error "nil is invalid as a repository identifier"](https://trello.com/c/GZJ0ozNb/2275-fix-error-nil-is-invalid-as-a-repository-identifier)

**Comment by eduardoj** [comment]
This error is caused by obsolete EventSubscriptions payloads. These payloads were created without the `target_repository_full_name` key.

This was fixed by hand updating and removing the obsolete subscriptions. This will make these exceptions to not happen any more.

In the case of the update, the payloads were modified from:
```
   {"scm"=>"github",
    "repo_url"=>"https://github.com/my_user/hello_world",
    "commit_sha"=>"56random_sha74",
    "pr_number"=>1,
    "source_branch"=>"my_branch",
    "target_branch"=>"master",
    "action"=>"opened",
    "repository_full_name"=>"my_user/hello_world",
    "event"=>"pull_request"}
```
to:
```                                                                                                                                                      
   {"scm"=>"github",
    "commit_sha"=>"56random_sha74",
    "pr_number"=>1,
    "source_branch"=>"my_branch",
    "target_branch"=>"master",
    "action"=>"opened",
    "source_repository_full_name"=>"my_user/hello_world",
    "target_repository_full_name"=>"my_user/hello_world",
    "event"=>"pull_request"}
```
