### ISSUE TITLE
Requests with rev=upload should be forbidden

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#11273]
rev=upload is basically a fake revision that can be altered before commit, requests with that "revision" don't make any sense.

@marcus-h pointed this out in https://github.com/openSUSE/open-build-service/pull/11263#issuecomment-866577739, but this is a problem independent of that PR

**Comment by adrianschroeter** [comment]
we can/should just disallow "upload" revisions in request actions, I see no usecase for them there.
