### ISSUE TITLE
Research notice: Sustainability in Open Source Projects

### ISSUE THREAD

**Issue by yochannah** [openSUSE/open-build-service#11295]
Please note that this repository is participating in a reserach study called "[Sustainability in Open Source Projects](https://sustainable-open-science-and-software.github.io/)". Data will be gathered about this repository for approximately the next 12 months, starting from June 2021. Data collected will include number of contributors, number of PRs, time taken to close/merge these PRs, and issues closed. For more information, please visit [the informational page](https://sustainable-open-science-and-software.github.io/) or download the [participant information sheet](https://sustainable-open-science-and-software.github.io/assets/PIS_sustainable_software.pdf).

This notice has been placed in compliance with the ethics review board process from the Department of Computer Science at University of Manchester in the United Kingdom. The presence of this notice does not exclude other projects from gathering metrics via GitHub's open-access API.

You can also see initial discussion about this notice here: #11206 - after chatting offline with @hennevogel we agreed an issue would be a better pathway.

----

I would recommend leaving this issue open for a while so contributors can spot it; I'll try to loop back and close it after the final surveys are done in one year!

**Comment by dmarcoux** [comment]
Again, I stand by what I wrote in the PR you previously opened. I don't see the point in having this issue here.

> I would list the open source projects on the research project website. It's much less time consuming for both parties: the open source contributors and you. There's no need to review a PR for contributors and you can directly list projects on the website without having to submit a PR on all projects involved in your research. I find this important because a lot of open source projects are quite overloaded with work... not every project has a team of paid software engineers like the Open Build Service.

**Comment by hennevogel** [comment]
> I don't see the point in having this issue here.

The point is that people know that there is this nice research going on.

**Comment by dmarcoux** [comment]
The 12-month mark is over, I'm closing this issue.
