### ISSUE TITLE
Cannot automatically resolve and install dependency packages when compiling Debian10

### ISSUE THREAD

**Issue by snowliuping** [openSUSE/open-build-service#11308]
When compiling the package of Debian10, the dependent package is not installed, such as:
[   27s] [57/259] installing libpython3.7-minimal-3.7.3-2+deb10u3
[   28s] dpkg: libpython3.7-minimal:amd64: dependency problems, but configuring anyway as you requested:
[   28s]  libpython3.7-minimal:amd64 depends on libssl1.1 (>= 1.1.1); however:
[   28s]   Package libssl1.1 is not installed.

The problem caused the compilation to fail

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
