### ISSUE TITLE
Erroneous return of HTTP 200 code when accessing login-restricted items

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#11300]
```
$ curl -D- https://build.opensuse.org/package/binary/GNOME:Next/at-spi2-core/openSUSE_Factory/x86_64/typelib-1_0-Atspi-2_0-2.40.2-360.3.x86_64.rpm
HTTP/2 200 
status: 200 OK
```

When opening this URL with a web browser, it gives a red box `Please login to access the requested page.` The HTTP request should therefore not respond with 200, because that erroneously suggests to automated tools that there was success, when it fact, there was not. It should return 403 as a HTTP status code (and the same HTML content with the main page/red box as it currently does.)

**Comment by eduardoj** [comment]
This happens on purpose for this and other Web-UI URLs. The web client is detected as a bot and the response returned is a 200 HTTP code before performing any user login authentication. Closing.
