### ISSUE TITLE
SRs are not displayed in package view

### ISSUE THREAD

**Issue by k0da** [openSUSE/open-build-service#1131]
In case I want to see what SRs are coming per package, webui displays none. In order to see them I have to go to project view and filter all coming SRs there.

**Comment by coolo** [comment]
Can't say that:
https://build.opensuse.org/package/requests/openSUSE:Leap:42.1/branding-openSUSE

**Comment by coolo** [comment]
I assume this is in in project links / remote projects?

**Comment by k0da** [comment]
Oh, it fixed then.
