### ISSUE TITLE
Package Retention

### ISSUE THREAD

**Issue by EvanCarroll** [openSUSE/open-build-service#11323]
Currently OBS can only keep one package on the repos it creates. It would be nice if a server-administrator could set it to retain multiple packages. Say, the last `$x` packages.

**Comment by adrianschroeter** [comment]
you can have multiple versions if you build them in parallel in the project.

**Comment by tacerus** [comment]
Hi,

could you clarify how to build two versions in parallel in a project? Or do you mean creating two separate packages?
