### ISSUE TITLE
[production][trigger_workflow#create] undefined method `with_indifferent_access' for nil:NilClass

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#11336]
trigger_workflow#create threw this 4 times
<pre>
undefined method `with_indifferent_access&#39; for nil:NilClass
</pre>

[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/60e152e984bf4607e2ab9379)

**Comment by danidoni** [comment]
I think this does not happen anymore. I'll close it
