### ISSUE TITLE
Diff between two maintenance requests is broken

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/open-build-service#11353]
on IBS, for superseded requests, the diff displayed seems to be always the full diff and not incremental.

For example, 244312?diff_to_superseded=244243

**Comment by AdamMajer** [comment]
Also broken with regular requests on OBS

https://build.opensuse.org/request/show/904052?diff_to_superseded=903828

**Comment by hennevogel** [comment]
Thanks for the report @AdamMajer 💐

**Comment by AdamMajer** [comment]
Thank you for the fix :1st_place_medal:
