### ISSUE TITLE
Searching with string "Channels" causes Error 500

### ISSUE THREAD

**Issue by a-kpappas** [openSUSE/open-build-service#11381]
# Issue Description
Searching with string "Channels" causes Error 500

Expected Result
============
The Channels project should appear, or a search result matching the string.

How to Reproduce
===============
1. Go to ibs.suse.de
2. Click on the search bar and enter "Channels" 
or
1. Go to https://build.suse.de/search?search_text=Channels

Further Information
===============
* https://build.suse.de/search?search_text=Channels

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

Thank you for your consideration.
