### ISSUE TITLE
20150917 [webui]: all java enabled features are broken

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#1139]
Sine the update of the webui on Sept 17 2015, anything relating to Javascript is non-functional:

* buildlog watching
* project watchlist dropdown (top right)
* /project/monitor: drop downs for arch, status, repository
* /monitor: no graphs are being loaded

Tested with firefox, chrome and chromium

**Comment by DimStar77** [comment]
The javascript debugger nags most often about:

ReferenceError: setup_buildresult_tooltip is not defined dimstar:4310:12

and once : 
ReferenceError: $ is not defined dimstar:10431:4

which comes from this code block:
//<![CDATA[

    $(document).ready(function() {
      $('#open_patchinfos-table').dataTable();
    });

//]]>

**Comment by DimStar77** [comment]
according to a net-trace, the application-[id].js is missing in the assets/webui location... resulting in the main error

**Comment by adrianschroeter** [comment]
should work meanwhile again, right?

(passenger is not reloading ruby stack propperly on update, restart apache is needed)

**Comment by DimStar77** [comment]
Yes - it's back operational and usable again.. thanks a lot @adrianschroeter
