### ISSUE TITLE
OBS xashds

### ISSUE THREAD

**Issue by WiyPower** [openSUSE/open-build-service#11395]
For security issues, please refer to [SECURITY.md](https://github.com/openSUSE/open-build-service/blob/master/SECURITY.md).

Any content related problems of our public instance build.opensuse.org, like not building packages or distribution setup should
get reported either on the mailing lists or in the [openSUSE Bugzilla](https://bugzilla.opensuse.org).

Having problems with the OBS command line interface osc? It has its own issue tracker here: https://github.com/openSUSE/osc

Having problems with the obs-build tool that controls the build process? It has its issue tracker here: https://github.com/openSUSE/obs-build

Good to go? Then please remove these lines above, including this one, and help us understand your issue by answering the following:

# Issue Description

Expected Result
============

How to Reproduce
===============

Further Information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)
![Uploading Screenshot_2021-07-16-22-04-40.png…]()

**Comment by hennevogel** [comment]
...
