### ISSUE TITLE
[production][] POST https://api.github.com/repos/openSUSE/open-build-service/statuses/b9ab04955829fef2a47a59b010...

### ISSUE THREAD

**Issue by krauselukas** [openSUSE/open-build-service#11408]
threw this 247 times
<pre>
POST https://api.github.com/repos/openSUSE/open-build-service/statuses/b9ab04955829fef2a47a59b010e0d4561aba5616: 404 - Not Found // See: https://docs.github.com/rest/reference/repos#create-a-commit-status
</pre>

[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/60f015a584bf4607dfab953e)

**Comment by krauselukas** [comment]
When a user uses a github token with insufficient permissions, the `Octokit` gem throws an `Octokit::NotFound` exception which is not handled in the `SCMStatusReporter` https://github.com/openSUSE/open-build-service/blob/48b331bf94f1ca32559a877f752a6f8eb63cf8ef/src/api/app/services/scm_status_reporter.rb#L16

Since this will happen more frequently with a growing number of users, we should handle this properly.

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Handle Octokit::NotFound exception in SCMStatusReporter](https://trello.com/c/xZJHK2Ek/2300-handle-octokitnotfound-exception-in-scmstatusreporter)

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Handle Gitlab/Octokit Errors in SCMStatusReporter](https://trello.com/c/NgyLPdA8/2303-handle-gitlab-octokit-errors-in-scmstatusreporter)

**Comment by dmarcoux** [comment]
Closed in #11592
