### ISSUE TITLE
API not working as documented: `POST /source/<project>/<package>?cmd=diff`

### ISSUE THREAD

**Issue by crazyscientist** [openSUSE/open-build-service#11411]
# Issue Description

According to the API docs the endpoint [POST /source/<project>/<package>?cmd=diff](https://build.opensuse.org/apidocs/index#55) accepts various parameters, e.g. `view=xml`, `withissues` or `onlyissues`.

The response from the API does not change, when ...

* any of the parameters gets added to the query or
* a parameter value gets changed

Expected Result
============
The API behaves as documented

**Comment by marcus-h** [comment]
On 2021-07-22 02:38:59 -0700, Andreas Hasenkopf wrote:
> According to the API docs the endpoint [POST /source/<project>/<package>?cmd=diff](https://build.opensuse.org/apidocs/index#55) accepts various parameters, e.g. `view=xml`, `withissues` or `onlyissues`.
>
withissues/onlyissues also require view=xml. That is,
POST /source/<project>/<package>?view=xml&onlyissues=1 should do
the trick.

**Comment by crazyscientist** [comment]
@marcus-h Thanks for the pointer. Seems like the actual _problematic_ parameter is `unified=1`, which override the `view=xml` parameter

**Comment by eduardoj** [comment]
> @marcus-h Thanks for the pointer. Seems like the actual _problematic_ parameter is `unified=1`, which override the `view=xml` parameter

This parameter is documentend in the "soonish to be rolled-out" "new API documentation", [here](https://api.opensuse.org/apidocs-new/#/Sources%20-%20Packages/post_source__project_name___package_name__cmd_diff). The `unified` parameter contains this sentence: `Setting unified to 1 takes precedence on the setting of the view parameter.`.

Closing. @crazyscientist please reopen if you notice something is wrong or missing.
