### ISSUE TITLE
[production][package#show] undefined method `tos_url' for #<Class:0x000055a8d784fac8>

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#11424]
package#show threw this 9118 times
<pre>
undefined method `tos_url&#39; for #&lt;Class:0x000055a8d784fac8&gt;
</pre>
[https://build-test-1.opensuse.org/package/show/Cloud:OpenStack:Master/python-django-allauth](https://build-test-1.opensuse.org/package/show/Cloud:OpenStack:Master/python-django-allauth)"

[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/60ff157a84bf4607e9fd6132)

**Comment by dmarcoux** [comment]
@hennevogel This is related to #11415

**Comment by hennevogel** [comment]
wth...

**Comment by hennevogel** [comment]
some production setup whoes...
