### ISSUE TITLE
edit project config in webui does not work any more

### ISSUE THREAD

**Issue by bugfinder** [openSUSE/open-build-service#1142]
the save button is always read if you changed the config and you can not save

**Comment by ChrisBr** [comment]
Probably introduced by 8b4d426e63a02440ca76359f6a163ae17cdd6ca3
The problem is that we don't set the project in the before filter to authorize in 
https://github.com/openSUSE/open-build-service/master/src/api/app/controllers/webui/project_controller.rb#L727

**Comment by coolo** [comment]
I wonder there is no test case catching this

**Comment by ChrisBr** [comment]
@coolo yes, ideally this should be covered by a test but AFAIK we don't have controller tests and testing this as a feature is hard because it makes use of the codemirror js library and you would need to inject js to test the it (it's not possible to just say ```click 'save'```)

**Comment by bgeuken** [comment]
Maybe we should have controller tests to have some "lightweight" testing of controller funtionality. I noticed that writing capybara test, or fixing them, can be tedious due to long timeouts. Funtional tests would help there as well.
