### ISSUE TITLE
[production][delayed_job#ConfigurationWriteToBackendJob] <status code="400">
  <summary>unknown element 'tos_url'</summary>
</status>


### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#11436]
delayed_job#ConfigurationWriteToBackendJob threw this 14 times
<pre>
&lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;unknown element &#39;tos_url&#39;&lt;/summary&gt;
&lt;/status&gt;

</pre>

[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/6100236e84bf4607e9fd7372)

**Comment by krauselukas** [comment]
Still happening since the backend throws a 400 when the frontend tries to write the configuration to it (through the `ConfigurationWriteToBackendJob`)
