### ISSUE TITLE
Issue tracker

### ISSUE THREAD

**Issue by Alilux** [openSUSE/open-build-service#11459]
Please only create code related issues/feature requests for the Open Build Service server here, GitHub issues are not meant to be used for support requests and neither for content problems of any instance!

Any content related problems of our public instance build.opensuse.org, like not building packages or distribution setup should
get reported either on the mailing lists or in the [openSUSE Bugzilla](https://bugzilla.opensuse.org).

For security issues, please refer to [SECURITY.md](https://github.com/openSUSE/open-build-service/blob/master/SECURITY.md).

For support contact our OBS community, they meet online in a chat/mailing list. There you can ask questions if you have trouble understanding something, seek advice and mingle with other OBS community members. See http://openbuildservice.org/support/ for further information.

Having problems with the OBS command line interface osc? It has its own issue tracker here: https://github.com/openSUSE/osc

Having problems with the obs-build tool that controls the build process? It has its issue tracker here: https://github.com/openSUSE/obs-build

Good to go? Then please remove these lines above, including this one, and help us understand your issue by answering the following:

Issue/Feature Description
====================

Expected Result
============

How to Reproduce
===============
1. When I want to do X
2. and Y is given
3. Z is happening

Further Information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)

**Comment by eduardoj** [comment]
Spam, again?
