### ISSUE TITLE
Security.md

### ISSUE THREAD

**Issue by Alilux** [openSUSE/open-build-service#11460]
![WARNING](https://media.giphy.com/media/Zsx8ZwmX3ajny/giphy.gif)

Please only create issues/feature requests for the Open Build Service server here, GitHub issues are not meant to be used for support requests!

For security issues, please refer to [SECURITY.md](https://github.com/openSUSE/open-build-service/blob/master/SECURITY.md).

For support contact our OBS community, they meet online in a chat/mailing list. There you can ask questions if you have trouble understanding something, seek advice and mingle with other OBS community members. For further information see http://openbuildservice.org/support/

**Comment by eduardoj** [comment]
Spam?

**Comment by Alilux** [comment]
Yeah..
