### ISSUE TITLE
Trigger service run in a branched project catches wrong version

### ISSUE THREAD

**Issue by coogor** [openSUSE/open-build-service#1147]
I had created a branch  home:DocB:branches:Application:ERP:Tryton:3.4/trytond in version 3.4.4
In between the source was updated to version 3.4.6.
This is correctly reflected in the spec file of the branched project.
Anyway, when I trigger a service run (download file) in the branched project, it fetched 3.4.4...which leads to a build error, as it expects 3.4.6

**Comment by hennevogel** [comment]
I don't see any revision with a spec file of 3.4.6. Services run on the server...
