### ISSUE TITLE
Unclear how to watch build failures

### ISSUE THREAD

**Issue by k0da** [openSUSE/open-build-service#1148]
Currently OBS automatically notifies a user with maintainer/bugowner roles from respective projects.

It would be great if I can watch build failures of individual projects with specific architectures.

e.g. watch all failures in openSUSE:Factory:Staging project for ppc64le architecture

**Comment by hennevogel** [comment]
We should include the users watchlist in the notifications...

**Comment by ChrisBr** [comment]
Done in https://github.com/openSUSE/open-build-service/pull/3992
