### ISSUE TITLE
Gitlab -> OBS API = strange response

### ISSUE THREAD

**Issue by black13ua** [openSUSE/open-build-service#11481]
I trying to setup gitlab -> obs webhook by Push new Tag
I created token:
`$ osc token --create  platform:31 zabbix_scripts
`
and checked it:
`$ curl -H "Authorization: Token <TOKEN>" -X POST -k 'https://obs20p.internal/trigger/runservice?project=platform:31&package=zabbix_scripts'
<status code="ok" />
`

In gitlab for webhook **Tag Push events** i getting error:
`403 No valid token found "Authorization" header`

But if i use in Gitlab **Push events** and branch master: everything OK, response 200 and obs triggering pkg to build

**Comment by hennevogel** [comment]
`$ osc token --create platform:31 zabbix_scripts`

This will create a `runservice` token. Please see our blogpost how to do this

https://openbuildservice.org/2021/05/31/scm-integration/#2-create-a-workflow-token-in-obs

**Comment by hennevogel** [comment]
Let us know if you need anything else 😃

**Comment by black13ua** [comment]
I tried this setup too
https://openbuildservice.org/2021/05/31/scm-integration/#2-create-a-workflow-token-in-obs

but got error:
`Hook executed successfully but returned HTTP 404 <?xml version="1.0" encoding="UTF-8"?> <hash> <status type="integer">404</status> <error>Not Found</error> </hash>`

**Comment by black13ua** [comment]
> Let us know if you need anything else

maybe you know any FAQ for setup gitlab->obs trigger by Push Tag Event

**Comment by hennevogel** [comment]
Maybe you can explain what you are trying to achieve? You push a tag to your repository on gitlab, the webhook is triggered and then you want what to happen on OBS?

**Comment by black13ua** [comment]
> Maybe you can explain what you are trying to achieve? You push a tag to your repository on gitlab, the webhook is triggered and then you want what to happen on OBS?

I would like to only **Tag Push Events** trigger OBS pkg build (by obs_sfm _service) build, but if i set in gitlab webhook settings:
**URL**: https://obs20p.intranet/trigger/runservice?project=platform:31&package=zabbix_scripts
**Trigger**: Tag push event
I get error (in gitlab):
`Hook executed successfully but returned HTTP 403 <status code="permission_denied"> <summary>No valid token found "Authorization" header</summary> </status>`

but if i change gitlab webhook settings to:
**URL**: https://obs20p.intranet/trigger/runservice?project=platform:31&package=zabbix_scripts
**Trigger**: Push events (branch: master)
I get http 200 (in gitlab) and triggered build in OBS

Maybe i can enable some debug in OBS? I want to understand why **Tag push event** from gitlab dont work

**Comment by hennevogel** [comment]
You you using a specific gitlab version?

**Comment by black13ua** [comment]
> You you using a specific gitlab/OBS version?

`GitLab13.5.4 (7f5f940041c)
`
```
obs20p:~> rpm -qa |grep obs
obs-common-2.10.11-lp153.78.3.noarch
obs-service-format_spec_file-20210511-lp153.242.1.noarch
obs-api-deps-2.10.11-lp153.78.1.x86_64
system-user-obsrun-2.10.11-lp153.78.3.noarch
obs-service-source_validator-0.21-lp153.144.1.noarch
obs-service-verify_file-0.1.1-lp153.35.2.noarch
obs-utils-2.10.11-lp153.78.3.noarch
system-user-obsservicerun-2.10.11-lp153.78.3.noarch
obs-service-obs_scm-0.10.27.1626072657.0fb7a03-lp153.308.1.noarch
obs-service-recompress-0.5.1-lp153.47.1.noarch
obs-service-set_version-0.5.14-lp153.123.1.noarch
obs-server-2.10.11-lp153.78.3.noarch
obs-service-download_files-0.7.2-lp153.90.1.noarch
system-user-obsapidelayed-2.10.11-lp153.78.3.noarch
obs-cloud-uploader-2.10.11-lp153.78.3.noarch
obs-service-tar_scm-0.10.27.1626072657.0fb7a03-lp153.308.1.noarch
obs-bundled-gems-2.10.11-lp153.78.1.x86_64
obs-service-extract_file-0.4-lp153.20.1.noarch
obs-service-obs_scm-common-0.10.27.1626072657.0fb7a03-lp153.308.1.noarch
obs-signd-2.5.10-lp153.1.1.x86_64
obs-service-download_src_package-0.2-lp153.3.1.noarch
obs-service-generator_driver_update_disk-0.2-lp153.2.1.noarch
obs-service-tar-0.10.27.1626072657.0fb7a03-lp153.308.1.noarch
obs-worker-2.10.11-lp153.78.3.noarch
obs-api-2.10.11-lp153.78.3.noarch
obs-service-download_url-0.1.3-lp153.29.1.noarch
obs20p:~>
```

**Comment by hennevogel** [comment]
Can you tell me the Request headers of your webhook?

Gitlab -> Your Repository -> Settings -> Webhooks -> Project Hooks -> Edit ->  Recent Deliveries -> Vie Details

Warning: You should *not* paste the `X-Gitlab-Token` here!

**Comment by black13ua** [comment]
> Can you tell me the Request headers of your webhook?
> 
> Gitlab -> Your Repository -> Settings -> Webhooks -> Project Hooks -> Edit -> Recent Deliveries -> Vie Details
> 
> Warning: You should **not** paste the `X-Gitlab-Token` here!

**Request headers:**
Content-Type: application/json
X-Gitlab-Event: Tag Push Hook
X-Gitlab-Token: _my_token_

**Response headers:**
```
Date: Tue, 10 Aug 2021 09:20:38 GMT
Server: Apache
Cache-Control: no-cache, public
Vary: Accept-Encoding
Referrer-Policy: strict-origin-when-cross-origin
X-Permitted-Cross-Domain-Policies: none
X-Xss-Protection: 1; mode=block
X-Opensuse-Runtimes: {"view":0.6161100000099395,"db":0,"backend":0}
X-Request-Id: 7993c54e-316b-495c-8245-ecd8db61ad47
X-Opensuse-Apiversion: 2.10.11
X-Download-Options: noopen
X-Runtime: 0.005719
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Opensuse-Errorcode: permission_denied
X-Powered-By: Phusion Passenger 6.0.1
Status: 403 Forbidden
Connection: close
Transfer-Encoding: chunked
Content-Type: application/xml; charset=utf-8
```
**Response body:**
```
<status code="permission_denied">
  <summary>No valid token found "Authorization" header</summary>
</status>
```

**Comment by hennevogel** [comment]
OBS 2.10.x only supports the "Push Hook" event.

**Comment by black13ua** [comment]
> OBS 2.10.x only supports the "Push Hook" event. Sorry...

which OBS version support other gitlab events? Or maybe present some patches for 2.10? Or other variants ... ?

**Comment by hennevogel** [comment]
> which OBS version support other gitlab events? Or maybe present some patches for 2.10? Or other variants ... ?

None released. There is support for Push Hook, Tag Push Hook and Merge Request Hook coming up in the next version.
If you want to patch it yourself,  [TokenExtractor](https://github.com/openSUSE/open-build-service/blob/2.10/src/api/app/services/trigger_controller_service/token_extractor.rb#L13) would be the place.

**Comment by black13ua** [comment]
> > which OBS version support other gitlab events? Or maybe present some patches for 2.10? Or other variants ... ?
> 
> None released. There is support for Push Hook, Tag Push Hook and Merge Request Hook coming up in the next version.
> If you want to patch it yourself, [TokenExtractor](https://github.com/openSUSE/open-build-service/blob/2.10/src/api/app/services/trigger_controller_service/token_extractor.rb#L13) would be the place.

Thanks for your help

Best regards!
