### ISSUE TITLE
urbackup-server RHEL_7 is pointing at the wrong version 3.2 instead of 3.1

### ISSUE THREAD

**Issue by johntwillis** [openSUSE/open-build-service#11505]
The urbackup-server repo metadata is pointed at the latest version built for Centos7 version 3.2

The urbackup-server repo metadata for Rhel7 is not at version 3.2, the build queue only outputs version 3.1

So a 

# yum install urbackup-server 

"Fails" on all version of Rhel7

Either 

The Rhel7 build queue is failing to build version 3.2 and its reporting success.. bad build system problem.
Or
The Rhel7 build queue is stalled at build version 3.1 and somehow the Rhel7 metadata is tracking the wrong version, its tracking the Centos7 instead.
Or 
The problem is in whatever makes the metadata for the Rhel7 repo

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
