### ISSUE TITLE
Github webhook: per-package disabled build meta does not transfer to branches

### ISSUE THREAD

**Issue by bluca** [openSUSE/open-build-service#11522]
Using the Github webhook as described https://openbuildservice.org/2021/05/31/scm-integration/ pointing to a package which has some build targets disabled specifically for the package (they are enabled on the project meta), because that specific package does not support them. The branch project created by the Github hook integration does not transfer the per-package meta, so these builds fail in the PR.

Project meta: https://build.opensuse.org/projects/network:messaging:zeromq:git-draft/meta
Package meta: https://build.opensuse.org/package/show/network:messaging:zeromq:git-draft/pyzmq
PR: https://github.com/zeromq/pyzmq/pull/1599

**Comment by hennevogel** [comment]
This is actually more a missing functionality of `BranchPackage`.

**Comment by hennevogel** [comment]
We discussed changing the default of package branching but that would create too much fall out in other places.

If you need some *very* specifc repository with the SCM/CI Workflows there is the option of setting the `add_repositories` option for the `branch_package` step to anything else than `enabled` and use the ` configure_repositories` step to configure exactly what you want to have.

You can check our own setup for instance:

https://github.com/openSUSE/open-build-service/blob/eb99509c50851700bd0694cab11d7583b175b8de/.obs/workflows.yml#L3-L17

**Comment by bluca** [comment]
My issue is not with adding new targets, but removing some - can that be done using what you suggest? IE, I have 10 build targets, I want the workflow to use only 5. This is encoded in the package as the build is disabled, but if I have to replicate the blocklist in the workflow file, while a bit annoying, that would be fine. I don't want to have to redefine the entire thing though, as that duplicates maintenance.

**Comment by hennevogel** [comment]
>  I have 10 build targets, I want the workflow to use only 5

`add_repositories` will skip *all* repositories from the source_project and then you explicitly set the 5 build targets you want.

**Comment by hennevogel** [comment]
> This really looks like the wrong default to me

Like I wrote, we discussed changing the default in the team and the conclusion was that changing the default of package branching would create too much fall out in other places where it's used.

**Comment by LebedevRI** [comment]
In which case, just add a `truly_branch_package` step, that actually does the right thing?

**Comment by hennevogel** [comment]
@LebedevRI "the right thing" for your situation maybe. The *right thing* by default is what we do now. There is an explicit way to achieve what you want with the way I described above. Now you want us to build another way? :)

**Comment by LebedevRI** [comment]
> The _right thing_ by default is what we do now.

I'm curious, what will happen if Source Project meta disables builds for all repositories,
and Source Package meta selectively enables some builds?
I'm guessing that `branch_package` will result in no builds being performed at all?

> There is an explicit way to achieve what you want with the way I described above.

Because i have already configured what builds should happen for the Source Package.
It is not expected behaviour that one now needs to do the same (and keep it in sync!)
in `workflow.yml`

> Now you want us to build another way? :)

I think everyone would like to have a way that works as expected.
It is not obvious to me why deviating by default from the Source build matrix is the most expected default behaviour.
