### ISSUE TITLE
[production][trigger#create] undefined method `with_indifferent_access' for nil:NilClass

### ISSUE THREAD

**Issue by krauselukas** [openSUSE/open-build-service#11535]
trigger#create threw this 1 times
<pre>
undefined method `with_indifferent_access&#39; for nil:NilClass
</pre>
[https://api.opensuse.org/trigger/runservice](https://api.opensuse.org/trigger/runservice)"

[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/6127564d84bf4607ebfd7c00)

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix error in trigger_controller.rb](https://trello.com/c/xInqte2G/2316-fix-error-in-triggercontrollerrb)
