### ISSUE TITLE
Add link back to git in the PR projects

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#11552]
I would like to have a link to https://github.com/openSUSE/open-build-service/pull/11489 in https://build.opensuse.org/project/show/home:bs-team:OBS:Server:Unstable:PR-11489

The project description says atm "This project was created for package obs-server via attribute OBS:Maintained" and I think that's wrong and having a proper link could help.

BTW: it would be great if those old projects could be removed, they cause a lot of build churn (and in this very case emails for build failures in my inbox)

**Comment by hennevogel** [comment]
> BTW: it would be great if those old projects could be removed

Cleanup is high on the TODO

**Comment by dmarcoux** [comment]
> it would be great if those old projects could be removed,

With the merge of #11596, workflows for closed or merged pull requests are now cleaning up after themselves. However, we still need to clean up old projects created by workflows before those changes were introduced.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/openSUSE/open-build-service/issues/11552](https://trello.com/c/N4LEhNDY/321-https-githubcom-opensuse-open-build-service-issues-11552)

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/openSUSE/open-build-service/issues/11552](https://trello.com/c/N4LEhNDY/321-https-githubcom-opensuse-open-build-service-issues-11552)
