### ISSUE TITLE
WebUI error with latest version (2.10.11)

### ISSUE THREAD

**Issue by c-hoeger** [openSUSE/open-build-service#11565]
While testing a fresh OBS deployment based on Leap 15.3 and OBS 2.10.11 I noticed, that the WebUI seems to have some issues.

```
# rpm -qa | grep obs
obs-signd-2.5.10-lp153.1.1.x86_64
system-user-obsapidelayed-2.10.11-lp153.78.3.noarch
obs-common-2.10.11-lp153.78.3.noarch
obs-server-2.10.11-lp153.78.3.noarch
system-user-obsrun-2.10.11-lp153.78.3.noarch
obs-api-deps-2.10.11-lp153.78.1.x86_64
system-user-obsservicerun-2.10.11-lp153.78.3.noarch
obs-bundled-gems-2.10.11-lp153.78.1.x86_64
obs-api-2.10.11-lp153.78.3.noarch
```

When I click on most of the projects in the project list (https://buildwebgui.example.com/project/myproject), I see an error
and nothing more (There has been an internal error. Please try again.)

Looks like that issue is tied to whether a user has the "Admin" role or not.
Once it has, that error is shown. Once it is removed, it works again.
In addition, on many places in the webui, when you click on Logout, you end up with a
"The page isn’t redirecting properly"
browser warning.

That's all what I see in the logs within /srv/www/obs/api/log/:

```
W, [2021-09-01T13:42:48.392177 #11463]  WARN -- : [4ed92b65-dc8a-40b0-9c12-6ceeee4066a6] [11463:13405.43] DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "LOWER(name)". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from block in <class:Package> at /srv/www/obs/api/app/models/package.rb:86)

==> /srv/www/obs/api/log/backend_access.log <==
I, [2021-09-01T13:42:48.447205 #11463]  INFO -- : 20210901T134248 GET localhost:5352/build/backend-develop/_result?code=failed&code=broken&code=unresolvable&view=status 200 0.034502175
I, [2021-09-01T13:42:48.447381 #11463]  INFO -- : (non-XML data) String
I, [2021-09-01T13:42:48.540628 #11463]  INFO -- : 20210901T134248 GET localhost:5352/source/backend-develop/_keyinfo?donotcreatecert=1&withsslcert=1 400 0.009444639
I, [2021-09-01T13:42:48.540746 #11463]  INFO -- : (non-XML data) String

==> /srv/www/obs/api/log/production.log <==
I, [2021-09-01T13:42:48.545059 #11463]  INFO -- : [4ed92b65-dc8a-40b0-9c12-6ceeee4066a6] [11463:13405.58] method=GET path=/project/show/backend-develop format=html controller=Webui::ProjectController action=show status=302 duration=163.70 view=0.00 db=10.88 location=https://buildwebgui.test.open-xchange.com/project params={"project"=>"backend-develop"} host=10.10.10.219 time=13766.51 backend=43.95 user=obs-admin

==> /srv/www/obs/api/log/apache_access.log <==
10.10.10.219 - - [01/Sep/2021:13:42:48 +0200] "GET /project/show/backend-develop HTTP/1.1" 302 125

==> /srv/www/obs/api/log/production.log <==
I, [2021-09-01T13:42:48.676053 #11463]  INFO -- : [ae0a276a-2a0c-4cd5-b3b5-fe9652fc9627] [11463:13405.71] method=GET path=/project format=html controller=Webui::ProjectController action=index status=200 duration=106.04 view=86.33 db=6.80 params={} host=10.10.10.219 time=13766.70 backend=0 user=obs-admin

==> /srv/www/obs/api/log/apache_access.log <==
10.10.10.219 - - [01/Sep/2021:13:42:48 +0200] "GET /project HTTP/1.1" 200 3249

==> /srv/www/obs/api/log/production.log <==
I, [2021-09-01T13:42:49.481898 #11463]  INFO -- : [bc9291fd-685f-4680-b677-71950fd287c6] [11463:13406.52] method=GET path=/project.json format=json controller=Webui::ProjectController action=index status=200 duration=41.40 view=25.56 db=6.14 params={"draw"=>"1", "columns"=>{"0"=>{"data"=>"name", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "1"=>{"data"=>"title", "name"=>"", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}}, "order"=>{"0"=>{"column"=>"0", "dir"=>"asc"}}, "start"=>"0", "length"=>"25", "search"=>{"value"=>"", "regex"=>"false"}, "all"=>"false", "_"=>"1630496569040"} host=10.10.10.219 time=13767.57 backend=0 user=obs-admin

==> /srv/www/obs/api/log/apache_access.log <==
10.10.10.219 - - [01/Sep/2021:13:42:49 +0200] "GET /project.json?draw=1&columns%5B0%5D%5Bdata%5D=name&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=title&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=25&search%5Bvalue%5D=&search%5Bregex%5D=false&all=false&_=1630496569040 HTTP/1.1" 200 267
```

Last time I ran some tests had been with 2.10.10 or 2.10.9 not showing that behaviour (about a month ago).

Is there anything I am missing?

The difference to our production OBS, which runs 2.10.8 is, that the HTTP response code to a request to

https://buildwebgui.example.com/project/myproject is 200 in contrary to 302 (Found) on 2.10.11

I assume that this is the problem.

**Comment by c-hoeger** [comment]
You don't need to be a global admin, it is sufficient to give a person the "maintainer" role to a project and from there on that user can no longer access that repository and sees the "internal error" instead.

**Comment by eduardoj** [comment]
Hi @c-hoeger!

> While testing a fresh OBS deployment based on Leap 15.3 and OBS 2.10.11 I noticed, that the WebUI seems to have some issues.

I have done my tests with an appliance with the last version of OBS, the 2.10.11 version. It has the same .rpm packages as you have listed.

> When I click on most of the projects in the project list (https://buildwebgui.example.com/project/myproject), I see an error
> and nothing more (There has been an internal error. Please try again.)

The url to access the project list should look like this: https://buildwebgui.example.com/project
The url to access a single project should look like this: https://buildwebgui.example.com/project/show/myproject

None of these two urls match the one you provide. In wich WebUI page did your find that url? If it is a result of a redirect, please provide the original url.

In the appliance where I tried, an url of the form https://buildwebgui.example.com/project/myproject always returns a 404 (for an existing project `myproject`, or when it doesn't exist).

Before going further, please help me clarify this point first.

**Comment by c-hoeger** [comment]
Well, I can't reproduce the problem today...

At the time of the report, I redeployed the system two times, tried two different browsers before reporting it.
Today everything works as it should.

>  The url to access a single project should look like this: https://buildwebgui.example.com/project/show/myproject

That sounds like the cause of the problem. Could be a browser caching issue maybe, but I tried a second browser
which I usually do not use at all (Safari) which showed the same behavior.

Also the log messages of this kind:

```
I, [2021-09-01T13:42:48.545059 #11463]  INFO -- : [4ed92b65-dc8a-40b0-9c12-6ceeee4066a6] [11463:13405.58] method=GET path=/project/show/backend-develop format=html controller=Webui::ProjectController action=show status=302 duration=163.70 view=0.00 db=10.88 location=https://buildwebgui.test.open-xchange.com/project params={"project"=>"backend-develop"} host=10.10.10.219 time=13766.51 backend=43.95 user=obs-admin
```

Do not appear in the installation from today.
I only see status=302 during session creation:

```
I, [2021-09-10T08:15:35.708693 #4822]  INFO -- : [a530a3ab-4f59-4588-b89d-5b8d710c172f] [4822:1132.01] method=POST path=/session/create format=html controller=Webui::SessionController action=create status=302 duration=37.55 view=0.00 db=8.61 location=https://buildwebgui.test.open-xchan
ge.com/ params={"utf8"=>"342234223", "authenticity_token"=>"TiPeW543wUHQaM2A6nqVNqVzz6KUPalgvJRee0P57r7JKuSih-Zc2nKpURneNiLaqn5DaceyJnPu1n990CocUQ", "username"=>"obs-admin", "password"=>"[FILTERED]", "commit"=>"Log In"} host=10.10.10.219 time=1468.43 backend=0 user=obs-admin
```

Strange...

Closing this for now.
