### ISSUE TITLE
Debian building for Testing and Unstable selects incorrect packages

### ISSUE THREAD

**Issue by norbusan** [openSUSE/open-build-service#11564]
# Issue Description

Adding `Debian:Next` adds in fact `Debian:11`, `Debian:Testing`, and `Debian:Next` as repositories, in *this* order.
That means, that packages are first checked in Debian Stable and used.

This prohibits building packages that rely on build dependencies in versions only available in Testing or Unstable, because the OBS resolver will install the version from Stable (11) and then dpkg will complain about unsatisfied dependencies.

Furthermore, if there is an ABI change between versions in stable-testing-unstable, the packages targeting unstable or testing will be compiled against an old ABI version and thus will not work.

Expected Result
============

Adding the `Debian:Next` should add the repositories in the reverse order, that is: `Debian:Next`, `Debian:Testing`, `Debian:11`, or in fact only `Debian:Next` alone.

Similarly, adding `Debian:Testing` should either not add `Debian:11` at all, or only after `Debian:Testing` in the list.

With this change, builds will be correctly compiled against the packages in the target distribution.

How to Reproduce
===============
1. Go to any project, repostories
2. Click on `Add from distribution`
3. Select `Debian Unstable`
4. Check with the actually added repositories and see the list.

Further Information
===============
* A link to an OBS instance showing the issue: https://build.opensuse.org/project/show/home:npreining:debian-kde:other Package digikam cannot be build because it can only be satisfied in Testing and Unstable, but not Stable. Dropping the version from the B-D builds on unstable, too, but against the version of libopencv-dnn in Stable which is ABI incompatible.

**Comment by adrianschroeter** [comment]
I can not reproduce this, but in your meta history you seem to have manually added further pathes to your home project.

can you remove the Debian_* repos completely and try to add them back?

**Comment by norbusan** [comment]
Hi @adrianschroeter 
thanks for looking at this.
The strange thing is when I remove `Debian_Testing` from the unstable repo list, it is removed there, but also from he Debian/11 and Debian/Testing repos.

So after removing this the xml files looks like:
```
<project name="home:npreining:debian-kde:other">
  <title>Some other apps that depend on changes here</title>
  <description/>
  <person userid="npreining" role="maintainer"/>
  <repository name="Debian_Unstable" rebuild="local">
    <path project="home:npreining:debian-kde:frameworks" repository="Debian_Unstable"/>
    <path project="home:npreining:debian-kde:apps2108" repository="Debian_Unstable"/>
    <path project="home:npreining:debian-kde:other-deps" repository="Debian_Unstable"/>
    <arch>x86_64</arch>
    <arch>i586</arch>
    <arch>aarch64</arch>
  </repository>
  <repository name="Debian_Testing" rebuild="local">
    <path project="home:npreining:debian-kde:frameworks" repository="Debian_Testing"/>
    <path project="home:npreining:debian-kde:apps2108" repository="Debian_Testing"/>
    <path project="home:npreining:debian-kde:other-deps" repository="Debian_Testing"/>
    <arch>x86_64</arch>
    <arch>i586</arch>
    <arch>aarch64</arch>
  </repository>
  <repository name="Debian_11">
    <path project="home:npreining:debian-kde:frameworks" repository="Debian_11"/>
    <path project="home:npreining:debian-kde:apps2108" repository="Debian_11"/>
    <path project="home:npreining:debian-kde:other-deps" repository="Debian_11"/>
    <arch>i586</arch>
    <arch>x86_64</arch>
    <arch>aarch64</arch>
  </repository>
</project>
```

After that I add `Debian:Next` (standard) to the Unstable repo list. All fine.

After that I add `Debian:Testing` (standard) to the Testing repo list. And here it is getting strange, because the Unstable repo list is updated to contain both the `Debian:Testing` and the `Debian:Unstable` and in this order.

If I add `Debian:11` to the repo list of stable, it is added also the the testing and unstable repo lists in the GUI.

Interestingly, the XML file looks correct:
```
<project name="home:npreining:debian-kde:other">
  <title>Some other apps that depend on changes here</title>
  <description/>
  <person userid="npreining" role="maintainer"/>
  <repository name="Debian_Unstable" rebuild="local">
    <path project="home:npreining:debian-kde:frameworks" repository="Debian_Unstable"/>
    <path project="home:npreining:debian-kde:apps2108" repository="Debian_Unstable"/>
    <path project="home:npreining:debian-kde:other-deps" repository="Debian_Unstable"/>
    <path project="Debian:Next" repository="standard"/>
    <arch>x86_64</arch>
    <arch>i586</arch>
    <arch>aarch64</arch>
  </repository>
  <repository name="Debian_Testing" rebuild="local">
    <path project="home:npreining:debian-kde:frameworks" repository="Debian_Testing"/>
    <path project="home:npreining:debian-kde:apps2108" repository="Debian_Testing"/>
    <path project="home:npreining:debian-kde:other-deps" repository="Debian_Testing"/>
    <path project="Debian:Testing" repository="standard"/>
    <arch>x86_64</arch>
    <arch>i586</arch>
    <arch>aarch64</arch>
  </repository>
  <repository name="Debian_11">
    <path project="home:npreining:debian-kde:frameworks" repository="Debian_11"/>
    <path project="home:npreining:debian-kde:apps2108" repository="Debian_11"/>
    <path project="home:npreining:debian-kde:other-deps" repository="Debian_11"/>
    <path project="Debian:11" repository="standard"/>
    <arch>i586</arch>
    <arch>x86_64</arch>
    <arch>aarch64</arch>
  </repository>
</project>
```

But digikam can still not be build because the b-d are unresolvable with the message:

```
nothing provides libopencv-dev >= 4.5.3~, (got version 4.5.1+dfsg-5)
```

Note that the libopencv-dev version given is the one from Debian/stable, although this is checked in the Debian/Unstable repository.

**Comment by adrianschroeter** [comment]
debian unstable has changed their gpg key, need to update the config. But this is not an obs code issue, so closing this ticket.
