### ISSUE TITLE
Request not in state accepted after accepting

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#1157]
https://build.opensuse.org/request/show/331816 was allowed to be accepted 3 times. See https://build.opensuse.org/package/revisions/games/stratagus

**Comment by ChrisBr** [comment]
I wonder how this was possible! I get an 
`` raise PostRequestNoPermission.new 'change state from an accepted state is not allowed.' ``
exception when I try to change the state of an accepted request ...

Did you changed the state with osc or webui? Can you provide more information?

**Comment by Mailaender** [comment]
Web UI which was responding slow, but I don't remember exactly. It has been over 2 months now.

**Comment by coolo** [comment]
this must be a case of missing transaction

**Comment by ChrisBr** [comment]
Changing the request state is already in a with_lock statement but the permission check and (which raises the exception) and creating the history is outside. I wasn't able to reproduce this but I can imagine that having the permission check outside the lock statement can cause this.

I'll move the permission check and creating the history inside the with_lock. Hopefully this will fix the issue.

Thanks @coolo for the hint
