### ISSUE TITLE
Scrollbar is covered by buttons

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/open-build-service#11626]
# Issue Description
You cannot scroll the table horizontally because the scroll bar is covered by a div containing buttons.

Expected Result
============
You should be able to click and drag the scrollbar.

How to Reproduce
===============
1. Go to https://build.opensuse.org/project/monitor/Emulators?blocked=0&building=0&dispatching=0&finished=0&scheduled=0&signing=0&succeeded=0
2. Try to scroll the table horizontally

Further Information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)

**Comment by dmarcoux** [comment]
Thank you @guoyunhe for submitting an issue about this. We're already tracking this in #11235.
