### ISSUE TITLE
i586 and armv7l archs keep coming back after checked them off

### ISSUE THREAD

**Issue by kailiu42** [openSUSE/open-build-service#11660]
# Issue Description
I just deployed OBS 2.10 on openSUSE Leap 15.3. After the web front-end was up, I went to Configuration and checked off i586 and armv7l architectures, left only x86_64. However after a few seconds, I switched back to the Architectures configure package, they are back. I tried this a few times, it's the same.

I them tried to modify it by `osc api -e /configuration`. I removed the two archs line from the XML, submitted it. Everything went fine, no error returned. Again, after a few seconds, I got the two back on the web UI and the /configuration API.

Expected Result
============
After checked the unwanted architectures off, they shouldn't come back again.

How to Reproduce
===============
1. Go to 'Configuration' on the front page, as Admin.
2. Click on 'Architectures' tab.
3. Uncheck 'i586' and 'armv7l.
4. Refresh the page every couple of seconds.
5. After a few seconds, the two architectures come back as checked.

Further Information
===============
* openSUSE Leap 15.3
* OBS 2.10 from https://download.opensuse.org/repositories/OBS:/Server:/2.10/15.3/OBS:Server:2.10.repo
* Initial setup via `/usr/lib/obs/server/setup-appliance.sh`

**Comment by cschneemann** [comment]
Hi,

my procedure to remove the not wanted architectures:

- systemctl stop obsscheduler (make sure all schedulers are stopped)
- rm /srv/obs/run/bs_sched.i586.lock
- rm /srv/obs/run/bs_sched.armv7.lock
- remove the archs from configuration (osc api /configuration or webui)
- systemctl start obsscheduler

**Comment by kailiu42** [comment]
Thanks! This worked for me.

So is this how it suppose to be or a workaround for this bug?
