### ISSUE TITLE
Github webhook: add support for tags in 'filter' configuration

### ISSUE THREAD

**Issue by bluca** [openSUSE/open-build-service#11665]
Recently the SCM workflow interface added support for filtering on push to branches. It would be nice, and in line with other CI systems, to be able to filter on tag push events, so that a job can be configured only to run when a new tag is pushed.

The practical use case is to trigger a source service run only when a release tag is pushed to a repository, rather than on every push to a branch.

**Comment by dmarcoux** [comment]
Thank you @bluca for creating this issue. We're definitely going to take your feedback into account for the upcoming development in the SCM/CI integration.

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support push events for tags](https://trello.com/c/C8Ocj5ua/2359-support-push-events-for-tags)

**Comment by dmarcoux** [comment]
In the SCM/CI integration, OBS now supports push events for tags. It's possible to run workflows only if tags are pushed. As for running a workflow only when a tag's name is matching a certain string (with support for basic regular expression), this will be added later.

We've documented this in our latest blog post under the [Push Events for Tags](https://openbuildservice.org/2021/11/22/scm-workflow-runs/) section. Details about how this works is in the [user documentation](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html).

Let us know how this works for you @bluca.

**Comment by bluca** [comment]
Thank you, that's great!

The blog post says `These kinds of events will affect the branch package and the link package steps only.` - is there any chance of getting this also enabled for `rebuild_package`? That's what it would be useful to me - a release tag is pushed, trigger the service to rebuild. So that only releases are built, and other pushes are ignored.

**Comment by dmarcoux** [comment]
This isn't only for branch package and link package steps. All steps can be used. I can see how this part of the blog post can be confusing. I'm going to rephrase this.

For the branch package and link package steps, the package created by those steps will contain the name of the tag which triggered the webhook event.

As for the rebuild package step, nothing changed in its behavior. If you have a workflow running only when push events for tags happen (so with the filter `event: tag_push` as presented in the blog post), the package will be rebuilt whenever a tag is pushed.

**Comment by bluca** [comment]
Thanks, tested and the trigger works! But: the rebuild_package is only doing a rebuild of the current sources, it does not trigger a service run?

**Comment by dmarcoux** [comment]
True, it doesn't trigger a service run, so new sources aren't pulled. We need to handle this.

**Comment by bluca** [comment]
A new step perhaps? Something like `service_run` or such?

**Comment by bluca** [comment]
Anyway it's unrelated, so I'll close this and open a new RFE

**Comment by bluca** [comment]
https://github.com/openSUSE/open-build-service/issues/11889
