### ISSUE TITLE
Improve issue list in submit request web ui review 

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/open-build-service#11680]
Currently, webui for submit request lists all the issues found on changelog, as "mentioned".

On SLE side, the policy is to never drop CVE / bug number or feature request number. It would be better to reflect in webui the state available from the XML issue query (available when using osc api call directly " POST "/source/$TARGET/$PACKAGE?cmd=diff&view=xml&onlyissues" ), as "mentioned / removed / added".

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Expand on Issue "State" in the mentioned issues tab](https://trello.com/c/bjfTceKA/133-expand-on-issue-state-in-the-mentioned-issues-tab)
