### ISSUE TITLE
Ubuntu:Next meta is pointing to incorrect download URL

### ISSUE THREAD

**Issue by hswong3i** [openSUSE/open-build-service#11695]
# Issue Description
https://build.opensuse.org/projects/Ubuntu:Next/meta show the download URL as:
```
http://ftp.halifax.rwth-aachen.de/ubuntu/devel/universe
``` 

Expected Result
============
The correct URL should be:
```
http://ftp.halifax.rwth-aachen.de/ubuntu/dists/devel/universe
```

How to Reproduce
===============
1. Go to https://build.opensuse.org/projects/Ubuntu:Next/meta
2. Line 14 now show as `<download arch="x86_64" url="http://ftp.halifax.rwth-aachen.de/ubuntu/devel/universe" repotype="deb">`

Further Information
===============
* My build for https://build.opensuse.org/project/show/home:alvistack and Ubuntu:Next now blocked as `downloading 104 dod packages`

**Comment by adrianschroeter** [comment]
On Dienstag, 5. Oktober 2021, 06:09:28 CEST Wong Hoi Sing Edison wrote:
> # Issue Description
> https://build.opensuse.org/projects/Ubuntu:Next/meta show the download URL as:
> ```
> http://ftp.halifax.rwth-aachen.de/ubuntu/devel/universe
> ``` 
> 
> Expected Result
> ============
> The correct URL should be:
> ```
> http://ftp.halifax.rwth-aachen.de/ubuntu/dists/devel/universe

no, it needs to be written different, since debian repos are more complex.

But I changed the writing to avoid peoples confusion now.

However, this is not an OBS code bug in any case.

-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by adrianschroeter** [comment]
the mirror had no universe though.

**Comment by hswong3i** [comment]
![BEB7BCE4-033C-443B-BF03-87F5AAB52882](https://user-images.githubusercontent.com/780562/135993057-b2a6215c-d4f8-4bd8-a382-ad296ae52a7d.png)

So should this blocked result expected?
