### ISSUE TITLE
OBS cannot read the workflow file from the source branch of a pr

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/open-build-service#11796]
# Issue Description
It is a limitation of the Github/Gitlab integration that it is not possible to read the workflow file from the source branch for a pull request.

This makes it impossible to perform new functions or tests of the integration in a specific branch, you always have to use the master or main branch.

This is a massive limitation e.g. for the initial setup of the integration, because you always have to create an extra project to show the functionality e.g. to a project maintainer as is was required at https://github.com/vsg-dev/vsgGIS/pull/16.

Expected Result
============
The workflow file should be readable from the source branch for a pull request or the branch that was pushed to.

How to Reproduce
===============
1. see https://github.com/vsg-dev/vsgGIS/pull/16

**Comment by dmarcoux** [comment]
Hi @rhabacker, while we understand this limitation could be quite a barrier to adoption in some projects, it's a conscious decision we took. Without this, anybody could run **any** workflow instructions, since those would be taken from changes of the PR they've submitted. They could, for example, branch thousands of packages with the token linked to the OBS workflow. Nothing is preventing them from doing such things.

**Comment by hennevogel** [comment]
Handing out `.obs/workflows.yml`  is handing out the keys to the kingdom. We will never do this sorry...

**Comment by rhabacker** [comment]
Doesn't this also apply to the Travis or Appveyor CI integration on Github ? How is it ensured that no one can abuse it ?

**Comment by hennevogel** [comment]
They don't 'care', there is no real abuse possible as their jobs run in a system that is just for this: CI. OBS is more...

**Comment by hennevogel** [comment]
Also see the *tons* of key leaks people produced with this because they did not understand that people can just fork the repo and run the CI cycle...

**Comment by rhabacker** [comment]
github [addressed](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) that issue:
>Anyone can fork a public repository, and then submit a pull request that proposes changes to the repository's GitHub Actions workflows. Although workflows from forks do not have access to sensitive data such as secrets, they can be an annoyance for maintainers if they are modified for abusive purposes.

>To help prevent this, workflows on pull requests to public repositories from some outside contributors will not run automatically, and might need to be approved first. By default, all first-time contributors require approval to run workflows.

See https://github.com/assimp/assimp/pull/4185#issuecomment-972604781 for a working example.

**Comment by hennevogel** [comment]
Yes they addressed leaking secrets inside the build yes. We have many different attack vectors as I explained, we are *more* than a CI service.
