### ISSUE TITLE
requests no longer revoked on delete of source project

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#1181]
https://build.opensuse.org/request/show/334890, *91, *94 ... are all requests for a no longer existant project

**Comment by bgeuken** [comment]
This got disabled for the webui with 90d50c9f036894db092cf87bec0110d39b7f26ca. Henne got a [PR](#1161) that should re-enable it.

**Comment by hennevogel** [comment]
This is merged now again....
