### ISSUE TITLE
Login always redirects to home page

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/open-build-service#1182]
This was probably be broken by commit d27f674b3e5da6898928a203c9a691527044b40b.

**Comment by bgeuken** [comment]
Are you using build.opensuse.org or some other instance? In the latter case which OBS version does that instance use?

**Comment by andreas-schwab** [comment]
The former.

**Comment by bgeuken** [comment]
And are you using this page: https://build.opensuse.org/user/login or this black pop-up login form? What browser are you using?

**Comment by andreas-schwab** [comment]
The pop-up.

**Comment by nemysis** [comment]
When I use this page: https://build.opensuse.org/user/login or https://build.opensuse.org/ and login get: https://build.opensuse.org/ and not my homepage. I use Firefox 41.0.

**Comment by bgeuken** [comment]
Me too. Anyway, we have been doing some group refactoring in that area last week. I am having a look at this again once it got merged.

**Comment by adrianschroeter** [comment]
still an issue it seems

**Comment by bgeuken** [comment]
This is fixed in master and is planed to be deployed next week

=> closing
