### ISSUE TITLE
Allow the .obs/workflows.yml path to be configurable

### ISSUE THREAD

**Issue by nickbroon** [openSUSE/open-build-service#11827]
**Is your feature request related to a problem? Please describe.**
Sometimes the contents of the top-level directory in a git repository cannot be easily modified to include `.obs`.
For example debian packages maintained in git, and built using gbp, often require that only modifications to to the git repo, which is basically a mirror of an upstream, be limited to only within a `/debian` directory that it maintains changes in and applies as patches.

**Describe the solution you'd like**
It would be useful if the path to OBS workflow directory could be changed, most likely in the OBS installation configuration.

**Describe alternatives you've considered**
This can be worked around for things like debian gbp packages by adding `extend-diff-ignore="^.obs/"` in `debian/sources/options`
https://manpages.debian.org/buster/dpkg-dev/dpkg-source.1.en.html#FILES

**Additional context**
An example of something similar is GitLab allowing the paths to it's CI workflow file to be configured (it defaults to toplevel .gitlab-ci.yml):
https://docs.gitlab.com/ee/ci/pipelines/settings.html#specify-a-custom-cicd-configuration-file

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow workflows file path to be configurable](https://trello.com/c/9HVojYJy/2401-allow-workflows-file-path-to-be-configurable)

**Comment by nickbroon** [comment]
Was implemented in https://github.com/openSUSE/open-build-service/pull/13499
