### ISSUE TITLE
ScmWebhookEventValidator too strict

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#11853]
There are tons of actions that can happen on a pull/merge requests. Like applying a label, editing the description and whatnot. Every of those actions will fire a webhook. 

Currently we report an error back to the webhook because we don't "support" those events. We should just return and do nothing. Otherwise you end up with tons of errors on the SCM side and the *real* errors are hard to find.

**Comment by dmarcoux** [comment]
Good point. We need to check which pull/merge request actions have to be ignored. We can track those in a constant like we already do for the allowed pull/merge request actions:

https://github.com/openSUSE/open-build-service/blob/b043ff059acb31235d0af36abd99967ddcf2192c/src/api/app/validators/scm_webhook_event_validator.rb#L5-L6

Documentation for the possible pull/merge request actions for:
- [GitHub](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request)
- [GitLab](https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#merge-request-events)

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ignore pull/merge request actions on which workflows shouldn't act](https://trello.com/c/3J6IVNJk/2409-ignore-pull-merge-request-actions-on-which-workflows-shouldnt-act)
