### ISSUE TITLE
OBS does not support the GitHub webhook `ping` event.

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#11865]
When you set up a webhook in GitHub pointing to `b.o.o`, the first thing that happens is that a request with a [ping](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#ping) event is sent to OBS.

Expected Result
============
Respond with a `200` and the usual `Ok` body.

How to Reproduce
===============
1. Set up an SCM/OBS Integration like described in the [OBS User Guide](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html)
2. Go to the webhook's Recent Deliveries.
3. The first entry is a request with a response code of `400` and a body saying that:
```
<status code="bad_request">
  <summary>Failed to parse the JSON payload of your request</summary>
</status>
```

**Comment by dmarcoux** [comment]
GitLab doesn't have a *ping* event, so this is only for GitHub.

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support GitHub webhook `ping` event](https://trello.com/c/TmwVyPkm/2410-support-github-webhook-ping-event)

**Comment by hennevogel** [comment]
this is supported now
