### ISSUE TITLE
Comments (tested on submitreqs) no longer support markdown

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#1187]
Formatting comments on submitrequests is no longer possible... markdown is simply no longer interpreted.

See for example: https://build.opensuse.org/request/show/335465

(the comment

I'm not sure, but your patch explicitly removes the installation of the tty-ask-password agent: - instmultiple -o \ - $systemdutildir/system-generators/systemd-cryptsetup-generator \ - $systemdutildir/systemd-cryptsetup \ - $systemdsystemunitdir/systemd-ask-password-console.path \ - $systemdsystemunitdir/systemd-ask-password-console.service \ - $systemdsystemunitdir/cryptsetup.target \ - $systemdsystemunitdir/sysinit.target.wants/cryptsetup.target \ - systemd-ask-password systemd-tty-ask-password-agent - instscript "$moddir"/crypt-run-generator.sh /sbin/crypt-run-generator dracutneedinitqueue

wrapped the instmodule[...] part in a &lt;pre&gt; without success

**Comment by hennevogel** [comment]
I'm working on this.

**Comment by hennevogel** [comment]
This is 'fixed' meanwhile
