### ISSUE TITLE
Github webhook: add new 'service_run' action/step

### ISSUE THREAD

**Issue by bluca** [openSUSE/open-build-service#11889]
Currently there's the `rebuild_package` step, but it only rebuilds the fetched sources, it does not trigger a service run. It would be very useful to have another step, `service_run` or so, that triggers a service run.
It would be useful in combination with the `tag_push` filters for me, so that I can configure a workflow that triggers a service run when a new release tag is pushed to a github repository.

**Comment by hennevogel** [comment]
Yeah this is already on the menu. You can see our plan on [trello](https://trello.com/c/PYCMrJW3) and on our [featuremap](https://app.featuremap.co/mp/Tn8Am3/scm-ci-integration).

Thanks for reporting anyway!

**Comment by bluca** [comment]
Nice, thank you! I will try it ASAP on my projects!
