### ISSUE TITLE
Cleanup footer

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#1188]
Current footer looks like this:

![obs_footer](https://cloud.githubusercontent.com/assets/968949/10246499/36abe01c-6912-11e5-85e3-dfbad7abe9a6.png)

To me the user information and locations doesn't belong there. Both are already covered by the ui. Location data can be found on the main page. The user related links are visible on top of every page.

So both could get removed.

**Comment by bgeuken** [comment]
@hennevogel @mdeniz @ChrisBr Thoughts? Opinions?

**Comment by mdeniz** [comment]
I agree ;)

**Comment by afaerber** [comment]
I've found the "Status Monitor" link helpful, it spares going to the (slow-loading) main page first on a local OBS. In particular when you're on a project page seeing the Build Results to the right, the Status Monitor is a quick way of checking how the "building" jobs have been distributed to workers (which is weird at times).

Agree that the user links could be dropped down there.

Cut off in the above screenshot is that the "Open Build Service" link under Help duplicates the link further below on "Open Build Service (OBS) is an openSUSE project.". If we could also drop the Twitter link (which I consider to be more about receiving info that contacting anyone) we could save a line, symmetrically having three bullet points each.

**Comment by coolo** [comment]
I even have a bookmark for the status page because I visit it often - the footer is about convenience I'd think. Not sure what you gain by removing links

**Comment by bgeuken** [comment]
Well, if you have a bookmark for the status page I assume that particular link in the footer isn't that useful for you. Usually a footer is the least prominent part of a website. And I am not saying it should get removed completely. But the user related links, especially the logout, as well as the 'Projects' and 'Search' links don't belong there.

And I just noticed there is an 'Open Build Service'. We might want to rename that one^^

**Comment by bgeuken** [comment]
Let's close this one.

If we ever have time for this and find it important enough, we can jsut do it:-)
