### ISSUE TITLE
OBS 2.10 package not installable on SUSE Enterprise Server 15 SP3

### ISSUE THREAD

**Issue by kagehisa** [openSUSE/open-build-service#11910]
# Issue Description
OBS 2.10 package not installable on SUSE Enterprise Server 15 SP3.
First there seems to be no repository for SLE 15 SP3, so I used the following URL:
`https://download.opensuse.org/repositories/OBS:/Server:/2.10/15.3/OBS:Server:2.10.repo`

This leads to the following problem during the install phase with zypper:
```Refreshing service 'Basesystem_Module_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Server_x86_64'.
Refreshing service 'Server_Applications_Module_x86_64'.
Retrieving repository '2.10 version of the Open Build Service Server (SLE_15_SP2)' metadata ........................................................................[done]Building repository '2.10 version of the Open Build Service Server (SLE_15_SP2)' cache .............................................................................[done]Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'bsdtar' needed by the to be installed obs-worker-2.10.11-78.3.noarch
 Solution 1: do not install pattern:OBS_Server-.noarch
 Solution 2: break obs-worker-2.10.11-78.3.noarch by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c):
```

I also tried it with the repository for SLES 15 SP2. Which got me the same result.

Expected Result
============
Successfull installation of the OBS 2.10 Server package via zypper.

How to Reproduce
===============
1. Use a fresh installed and registered SUSE Enterprise 15 SP3
2. Type `zypper ar -f https://download.opensuse.org/repositories/OBS:/Server:/2.10/15.3/OBS:Server:2.10.repo`
3. Type `zypper in -t pattern OBS_Server`

**Comment by kagehisa** [comment]
The [Documentation](https://openbuildservice.org/download/other/) on openbuildservice.org lists the following for installation on SLES:
`zypper ar -f https://download.opensuse.org/repositories/OBS:/Server:/2.10/SLE_15_SP3/OBS:Server:2.10.repo`

But since the repo doesn't exist I get:

```
File '/repositories/OBS:/Server:/2.10/SLE_15_SP3/OBS:Server:2.10.repo' not found on medium 'https://download.opensuse.org/'
Abort, retry, ignore? [a/r/i/...? shows all options] (a):
```

It would be nice to be able to install OBS on SLES without building it from source.

**Comment by vpereira** [comment]
Hi @kagehisa, it was changed some time ago to a different location: https://download.opensuse.org/repositories/OBS:/Server:/2.10/15.3/OBS:Server:2.10.repo

Hope that helps you

**Comment by kagehisa** [comment]
Hi,
thank you for the reply. But this doesn't help. See my [initial issue](https://github.com/openSUSE/open-build-service/issues/11910#issue-1066221913). There is a problem with needed dependencies.

**Comment by vpereira** [comment]
> Hi,
> thank you for the reply. But this doesn't help. See my [initial issue](https://github.com/openSUSE/open-build-service/issues/11910#issue-1066221913). There is a problem with needed dependencies

Hm, ok. The repository now is right, however the necessary packages/package versions aren't there? Just to be sure, did you run `zypper refresh` after adding the repository with zypper?

**Comment by kagehisa** [comment]
Yes, I did. I also performed a `zypper update` before installing. But the error remains the same:
```
Resolving package dependencies...

Problem: nothing provides 'bsdtar' needed by the to be installed obs-worker-2.10.11-lp153.78.3.noarch
 Solution 1: do not install pattern:OBS_Server-.noarch
 Solution 2: break obs-worker-2.10.11-lp153.78.3.noarch by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c):
```

**Comment by adrianschroeter** [comment]
bsdtar is provided by the  "Developement Tools" channel of SLE.

**Comment by kagehisa** [comment]
Alright that was the missing part, thanks. After adding that extension module as well as the desktop applications and web scripting module, the installation succeeded. Thank you!

**Comment by danidoni** [comment]
@kagehisa do you consider this issue closed?
