### ISSUE TITLE
error with adding comment to OpenSUSE OBS home:ecsos/mysql-workbench

### ISSUE THREAD

**Issue by Dutchglory** [openSUSE/open-build-service#1197]
error with adding comment to OpenSUSE OBS home:ecsos/mysql-workbench

500: Internal Server Error

full url: 
https://build.opensuse.org/package/comments/home:ecsos/mysql-workbench

should i report this at bugzilla..??

**Comment by adrianschroeter** [comment]
On Sonntag, 4. Oktober 2015, 07:13:53 CEST wrote Andre Verwijs:
> error with adding comment to OpenSUSE OBS home:ecsos/mysql-workbench
> 
> 500: Internal Server Error
> 
> full url: 
> https://build.opensuse.org/package/comments/home:ecsos/mysql-workbench
> 
> should i report this at bugzilla..??  

I get a 404 error on that link ... where got you this URL from?

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imend�rffer, Jane Smithard, Graham Norton, HRB 21284 (AG N�rnberg) 
 
Maxfeldstra�e 5                         
90409 N�rnberg 
Germany

**Comment by hennevogel** [comment]
I guess you mean https://build.opensuse.org/comments/package/home:ecsos/mysql-workbench

**Comment by Dutchglory** [comment]
Yep...  when adding a comment, the server can't connect....

**Comment by Dutchglory** [comment]
From OpenSUSE build service, a mysql-workbench build .... 

When adding a comment, the server can't connect.... 

"Adrian Schröter" <notifications@github.com> schreef op 5 oktober 2015 11:17:40 CEST:
>On Sonntag, 4. Oktober 2015, 07:13:53 CEST wrote Andre Verwijs:
>> error with adding comment to OpenSUSE OBS home:ecsos/mysql-workbench
>> 
>> 500: Internal Server Error
>> 
>> full url: 
>>
>https://build.opensuse.org/package/comments/home:ecsos/mysql-workbench
>> 
>> should i report this at bugzilla..??  
>
>I get a 404 error on that link ... where got you this URL from?
>
>-- 
>
>Adrian Schroeter
>email: adrian@suse.de
>
>SUSE Linux GmbH, GF: Felix Imend�rffer, Jane Smithard, Graham Norton,
>HRB 21284 (AG N�rnberg) 
> 
>Maxfeldstra�e 5                         
>90409 N�rnberg 
>Germany 
>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/openSUSE/open-build-service/issues/1197#issuecomment-145472139

-- 
Verstuurd vanaf mijn Android apparaat met Email. Excuseer mijn beknoptheid.

**Comment by Dutchglory** [comment]
dutchgigalo@gmail.com sent you an invitation to join MEGA.

--- Message from user: ---
Hallo, kom ook op MEGA en krijg toegang tot versleutelde opslag en
communicatie. Krijg 50GB gratis!
---

Please create your free MEGA account by clicking on the following
link:
https://mega.nz/#newsignupcmVwbHkrMDAwNzBhYWQzODRmMDQwYWU4NDU1YjM3M2I2NjZlOWJhMTQ0NjllZjAzODZhZmZkOTJjZjAwMDAwMDAxMTIyYTAyMzQ5MmExNjljZTA2ODlhMTFiQHJlcGx5LmdpdGh1Yi5jb21ToyEcX8D5hQ

Best regards,

Team MEGA

**Comment by ChrisBr** [comment]
Not reproducible, closing!
