### ISSUE TITLE
User editing seems not to work anymore in webui

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#1199]
Going to https://build.opensuse.org/users tells me "Requires admin privileges". But I am and editing works via the api.

**Comment by bgeuken** [comment]
Works for me with current master code. Might be fixed already.

**Comment by adrianschroeter** [comment]
Do we have a testcase for it?

**Comment by bgeuken** [comment]
Doesn't look like. I am going to write one

**Comment by bgeuken** [comment]
So it worked for me because I reload the page after login. Without a page reload one get's the reported access denied message

**Comment by bgeuken** [comment]
Let's wait for the login / api login rewrite we did last week. Might solve this one as well.

**Comment by adrianschroeter** [comment]
The permission error is indeed away, but the user tab is loading way slower then it used to load. (waiting for for minutes now and expecting a timeout error).

We used pages to be able to load this fast.

**Comment by adrianschroeter** [comment]
pagenation works again
