### ISSUE TITLE
Containers not building due to ArchExclusiveLine aren't listed as "disabled" 

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/open-build-service#11992]
If a Dockerfile contains:
#!ArchExclusiveLine: x86_64

OBS will not reports it is "disabled" for other architectures (similar to specfile) but instead, will output some errors on unresolvable packages which are installed using zypper in the Dockerfile (because they can't be found, obviously).

**Comment by adrianschroeter** [comment]
I think you look for

#!ExclusiveArch: x86_64

to excude it for other architectures.

ArchExclusiveLine is a marker to run the next line only for this architecture.
