### ISSUE TITLE
Error: hdrmd5 mismatch ... cannot make a local build

### ISSUE THREAD

**Issue by mcepl** [openSUSE/open-build-service#12034]
In many packages (three in the last week or so) I just cannot build locally, because of errors like this:
```
python-factory_boy@stitny$ oscb --clean
Building python-factory_boy.spec for openSUSE_Tumbleweed/x86_64
Run source service: /usr/lib/obs/service/format_spec_file --outdir /home/matej/build/devel:languages:python/python-factory_boy/tmpjzbk82gd.format_spec_file.service
Run source service: /usr/lib/obs/service/source_validator --outdir /home/matej/build/devel:languages:python/python-factory_boy/tmpe9m3igme.source_validator.service
Run source service: /usr/lib/obs/service/format_spec_file --outdir /home/matej/build/devel:languages:python/python-factory_boy/tmp29wn_igu.format_spec_file.service
Run source service: /usr/lib/obs/service/source_validator --outdir /home/matej/build/devel:languages:python/python-factory_boy/tmpd9jmsgl1.source_validator.service
Getting buildconfig from server and store to /home/matej/build/devel:languages:python/python-factory_boy/.osc/_buildconfig-openSUSE_Tumbleweed-x86_64
Getting buildinfo from server and store to /home/matej/build/devel:languages:python/python-factory_boy/.osc/_buildinfo-openSUSE_Tumbleweed-x86_64.xml
Updating cache of required packages
0.8% cache miss. 238/240 dependencies cached.

[1/2] (devel:languages:python) python39-ordered-set-4.0.2-17.2.noarch.rpm: 100%|#########| Time: 0:00:00
[2/2] (devel:languages:python) python38-ordered-set-4.0.2-17.2.noarch.rpm: 100%|#########| Time: 0:00:00
Verifying integrity of cached packages
using keys from openSUSE:Tumbleweed, devel:languages:python
Error: hdrmd5 mismatch for /var/tmp/osbuild-packagecache/devel:languages:python/openSUSE_Tumbleweed/noarch/python39-ordered-set-4.0.2-17.2.noarch.rpm: 48aabe9718ecab003fdfbd2f9046f5da != 6b6d2ed28f4d734762d22a750afa1624
python-factory_boy@stitny$
```

Trying to build `python-factory_boy` package in devel:languages:python. I have even `osc wipebinaries --all` and `osc rebuild --all` on python-ordered-set, so that I may be certain that all packages and metadata are fresh, but to no avail. This is how it ended.

It really makes my work with OBS quite complicated, because I have to do all builds remotely on OBS and it is very slow.

**Comment by marcus-h** [comment]
On 2021-12-28 14:18:49 -0800, Matěj Cepl wrote:
> In many packages (three in the last week or so) I just cannot build locally, because of errors like this:
> ```
> ***@***.***$ oscb --clean
> Building python-factory_boy.spec for openSUSE_Tumbleweed/x86_64
> Run source service: /usr/lib/obs/service/format_spec_file --outdir /home/matej/build/devel:languages:python/python-factory_boy/tmpjzbk82gd.format_spec_file.service
> Run source service: /usr/lib/obs/service/source_validator --outdir /home/matej/build/devel:languages:python/python-factory_boy/tmpe9m3igme.source_validator.service
> Run source service: /usr/lib/obs/service/format_spec_file --outdir /home/matej/build/devel:languages:python/python-factory_boy/tmp29wn_igu.format_spec_file.service
> Run source service: /usr/lib/obs/service/source_validator --outdir /home/matej/build/devel:languages:python/python-factory_boy/tmpd9jmsgl1.source_validator.service
> Getting buildconfig from server and store to /home/matej/build/devel:languages:python/python-factory_boy/.osc/_buildconfig-openSUSE_Tumbleweed-x86_64
> Getting buildinfo from server and store to /home/matej/build/devel:languages:python/python-factory_boy/.osc/_buildinfo-openSUSE_Tumbleweed-x86_64.xml
> Updating cache of required packages
> 0.8% cache miss. 238/240 dependencies cached.
>
> [1/2] (devel:languages:python) python39-ordered-set-4.0.2-17.2.noarch.rpm: 100%|#########| Time: 0:00:00
> [2/2] (devel:languages:python) python38-ordered-set-4.0.2-17.2.noarch.rpm: 100%|#########| Time: 0:00:00
> Verifying integrity of cached packages
> using keys from openSUSE:Tumbleweed, devel:languages:python
> Error: hdrmd5 mismatch for /var/tmp/osbuild-packagecache/devel:languages:python/openSUSE_Tumbleweed/noarch/python39-ordered-set-4.0.2-17.2.noarch.rpm: 48aabe9718ecab003fdfbd2f9046f5da != 6b6d2ed28f4d734762d22a750afa1624
> ***@***.***$
> ```
>
You are using osc from git master, right? As a workaround, you can
run "osc build --download-api-only ..." if you encounter this issue.
Probably, osc should do this automatically if it encounters a hdrmd5
mismatch.

**Comment by mcepl** [comment]
That doesn’t help:
```sh
~$ alias oscb='osc build --cpio-bulk-download --download-api-only'
```

**Comment by marcus-h** [comment]
On 2021-12-30 05:53:20 -0800, Matěj Cepl wrote:
> That doesn’t help:
> ```sh
> ~$ alias oscb='osc build --cpio-bulk-download --download-api-only'
> ```
>
Indeed. Currently, the --download-api-only is not honored anymore...
As a really ugly workaround, you can apply the following hack to your
git tree (untested)

diff --git a/osc/build.py b/osc/build.py
index cad5261a..609ea298 100644
--- a/osc/build.py
+++ b/osc/build.py
@@ -1056,7 +1056,8 @@ def main(apiurl, opts, argv):
                       http_debug = config['http_debug'],
                       modules = bi.modules,
                       enable_cpio = not opts.disable_cpio_bulk_download,
-                      cookiejar=cookiejar)
+                      cookiejar=cookiejar,
+                      download_api_only=opts.download_api_only)

     if not opts.trust_all_projects:
         # implicitly trust the project we are building for
diff --git a/osc/fetch.py b/osc/fetch.py
index 4c05eb0a..ae3d7189 100644
--- a/osc/fetch.py
+++ b/osc/fetch.py
@@ -29,7 +29,7 @@ from .meter import create_text_meter
 class Fetcher:
     def __init__(self, cachedir='/tmp', api_host_options={}, urllist=[],
                  http_debug=False, cookiejar=None, offline=False,
-                 enable_cpio=True, modules=[]):
+                 enable_cpio=True, modules=[], download_api_only=False):
         # set up progress bar callback
         self.progress_obj = None
         if sys.stdout.isatty():
@@ -43,6 +43,7 @@ class Fetcher:
         self.offline = offline
         self.cpio = {}
         self.enable_cpio = enable_cpio
+        self.download_api_only = download_api_only

         self.gr = OscFileGrabber(progress_obj=self.progress_obj)

@@ -195,6 +196,8 @@ class Fetcher:
                 sys.exit(1)

     def _build_urllist(self, buildinfo, pac):
+        if self.download_api_only:
+            return []
         urllist = self.urllist
         key = '%s/%s' % (pac.project, pac.repository)
         project_repo_url = buildinfo.urls.get(key)

**Comment by mcepl** [comment]
OK, I have made your suggestion into a patch, and let us see what happens.

**Comment by marcus-h** [comment]
On 2021-12-30 09:50:23 -0800, Matěj Cepl wrote:
> OK, I have made your suggestion into a patch, and let us see what happens.
>
Just to be sure: are you using osc from git master?

**Comment by mcepl** [comment]
> Just to be sure: are you using osc from git master?

Yup, via `python3 setup.py develop --user`, so it is always the current top of master.

**Comment by vpereira** [comment]
@marcus-h @mcepl would you mind to report it to osc upstream here https://github.com/openSUSE/osc/issues ? Looks like there are some issues that should be fixed there, no?

**Comment by mcepl** [comment]
That sounds rather too bureaucratic. @adrianschroeter cannot read this thread?

**Comment by vpereira** [comment]
> That sounds rather too bureaucratic. @adrianschroeter cannot read this thread?

how create the issue in the right upstream project is bureaucratic? `osc` is maintainer by a different set of people...
