### ISSUE TITLE
get /person/$user called from admins should include watchlist of the user

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#1204]
I edited my user through osc meta user coolo -e

This doesn't show the watchlist of the webui, but if you save the user meta, it will remove all watched projects -> data loss!

**Comment by ChrisBr** [comment]
:flushed:
@adrianschroeter how is the watched project list related to the user meta?

**Comment by hennevogel** [comment]
The watchlist is part of the user data

```
$ osc meta user hennevogel
<person>
  <login>hennevogel</login>
  <email>hvogel@suse.com</email>
  <realname>Hendrik Vogelsang</realname>
  <state>confirmed</state>
  <globalrole>User</globalrole>
  <watchlist>
    <project name="devel:languages:ruby:extensions"/>
    <project name="devel:languages:ruby"/>
  </watchlist>
</person>
```

**Comment by bgeuken** [comment]
I couldn't reproduce this so far. @coolo Which osc version are you using? And where can I get the package from?

**Comment by bgeuken** [comment]
Talked with coolo and it turned out not to be a regression, at least.

**Comment by coolo** [comment]
the problem was that Adrian edited my user before I edited it myself.

**Comment by bgeuken** [comment]
Yep, I was quite worried last week that this was caused by my refactoring (#1198). Glad this wasn't the case.

Hopefully #1206 prevent such things in the future.
