### ISSUE TITLE
memoryperjob constraint not applied

### ISSUE THREAD

**Issue by StefanBruens** [openSUSE/open-build-service#12069]
# Issue Description
hardware constraints like "memory" are applied correctly, but "memoryperjob" is ignored completely.

With e.g. memoryperjob=2G, a host with 5GB and 4 jobs should\* be pruned from the eligible worker list, but it is not.

*) Unless dynamic job settings are implemented, but that is a different issue.

Expected Result
============
Only a host where `jobs * memoryperjob <= swap + mem` is fulfilled should be used to build.

e.g.:
`osc less home:StefanBruens:CheckMemory mpj_2G_M6G  _constraints`
```
<?xml version="1.0" encoding="UTF-8"?>
<constraints>
  <hardware>
    <memoryperjob>
      <size unit="G">2</size>
    </memoryperjob>
    <memory>
      <size unit="G">6</size>
    </memory>
  </hardware>
</constraints>
```

should only select host with at least 6G of (swap + mem), and (jobs <= (swap+mem)/2G).

How to Reproduce
===============
Some example projects are available in home:StefanBruens:CheckMemory

`osc checkconstraints home:StefanBruens:CheckMemory mpj_2G  openSUSE_Tumbleweed x86_64 | grep "cloud..4:1"`
```
x86_64:cloud104:1
x86_64:cloud114:1
x86_64:cloud124:1
x86_64:cloud134:1
```
`osc checkconstraints home:StefanBruens:CheckMemory mpj_2G_M6G  openSUSE_Tumbleweed x86_64 | grep "cloud..4:1"`
```
x86_64:cloud134:1
```
`osc workerinfo x86_64:cloud104:1 | grep -E 'swap|jobs|memory'`
```
    <jobs>4</jobs>
    <memory>3072</memory>
    <swap>2000</swap>
```
`osc workerinfo x86_64:cloud134:1 | grep -E 'swap|jobs|memory'`
```
    <jobs>8</jobs>
    <memory>6000</memory>
    <swap>2000</swap>
```

The `<memory>` constraint is applied correctly, `<memoryperjob>` is not.

Further Information
===============
This has been fixed apparently, but not deployed:

https://github.com/openSUSE/open-build-service/pull/10033

**Comment by StefanBruens** [comment]
@antlarr - this is the bug you are trying to work around.

**Comment by adrianschroeter** [comment]
That is indeed a bug and is fixed here: https://github.com/openSUSE/open-build-service/pull/12070

However, it is the opposite what antlarr tries to achieve, when he wants to build on workers with reduced number of jobs.

**Comment by adrianschroeter** [comment]
btw, Stefan, thans a lot for your very good example setup!

**Comment by StefanBruens** [comment]
@adrianschroeter  Thanks for fixing it so quickly. Any timeline when this will be deployed on the public OBS?

**Comment by adrianschroeter** [comment]
On Mittwoch, 12. Januar 2022, 16:33:53 CET StefanBruens wrote:
> @adrianschroeter  Thanks for fixing it so quickly. Any timeline when this will be deployed on the public OBS?

tomorrow morning most likely.

-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH, Maxfeldstr. 5, 90409 Nürnberg, Germany
(HRB 36809, AG Nürnberg) Geschäftsführer: Ivo Totev
