### ISSUE TITLE
[production][meta#update] Project not found: dev:languages:ruby

### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#12073]
Adding an non existing project to a "_meta" file leads to 500.

How to reproduce it:

- Open a "meta" file from a page
- Add an non existing project to as path
- Save the file

i.e:
```
  <repository name="openSUSE_15.2">
    <path project="foo:bar" repository="openSUSE_15.2"/>
    <arch>x86_64</arch>
    <arch>armv7l</arch>
    <arch>aarch64</arch>
    <arch>ppc64le</arch>
  </repository>
```

**Comment by Yash621** [comment]
@vpereira can I work on this ?

**Comment by dmarcoux** [comment]
> @vpereira can I work on this ?

For sure! Let us know if something isn't clear :slightly_smiling_face:

**Comment by eduardoj** [comment]
This got fixed meanwhile. Now, a message with the text _"A project with the name foo:bar does not exist. Please update the repository path elements."_. Closing.
