### ISSUE TITLE
after removing user from prj, user still receives comments for prj

### ISSUE THREAD

**Issue by olafhering** [openSUSE/open-build-service#12075]
User `olh` used to have an entry `role="maintainer"` in prj "`network`".
Other users added comments to the prj, emails about these comments arrived as expected.
Once user `olh` was removed from this role in the prj, new comments still trigger emails.
I expect no further emails because I have no role in the prj anymore.

**Comment by hennevogel** [comment]
You are still involved in the comment thread of that project though. So you count as subscriber...

**Comment by coolo** [comment]
i.e. remove all your old comments

**Comment by olafhering** [comment]
So it is not `per-thread`, but a global thing. Nice to know.
