### ISSUE TITLE
Give project admins a chance to remove comments in packages and projects

### ISSUE THREAD

**Issue by stoecker** [openSUSE/open-build-service#1209]
Hello,

the commenting feature is a nice thing, but old comments are disturbing. Please give the project admins the chance to remove comments again, e.g. here: https://build.opensuse.org/project/show/games. As far as I see ATM it's only possible to remove own comments.

Or when removing is not wanted at least set them on "hidding" or "archived", so they aren't visible normally.

**Comment by coolo** [comment]
for what it's worth, you can remove comments through the API.

osc api /comments/project/games will give you the IDS you can then osc api -X DELETE /comment/$ID

What's missing is a button in the webui

**Comment by ChrisBr** [comment]
This is possible now!
