### ISSUE TITLE
'suse-packagehub-15-x86_64' key expired (pub   2048R/65176565 2015-05-29 [expired: 2021-12-10])

### ISSUE THREAD

**Issue by uhering** [openSUSE/open-build-service#12097]
Hello all,

the repo key

https://download.opensuse.org/repositories/openSUSE:/Backports:/SLE-15/standard/repodata/repomd.xml.key
https://downloadcontent.opensuse.org/repositories/openSUSE:/Backports:/SLE-15/standard/repodata/repomd.xml.key

has expired in the mid of october 2021. It should be renewed.

Regards,

Uwe

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us for some specific instance.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS.  See https://openbuildservice.org/support/

Thank you for your consideration.
