### ISSUE TITLE
WebUI: build link from monitor no longer points to live log

### ISSUE THREAD

**Issue by k0da** [openSUSE/open-build-service#1211]
In monitor view of the project, links are pointing to raw log instead of live build log.

Like: https://build.opensuse.org/build/openSUSE:Factory:PowerPC/standard/ppc64le/MozillaFirefox/_log
instead of 
https://build.opensuse.org/package/live_build_log/openSUSE:Factory:PowerPC/MozillaFirefox/standard/ppc64le

**Comment by coolo** [comment]
this happens if the package is not local to the project

**Comment by coolo** [comment]
https://github.com/openSUSE/open-build-service/blob/master/src/api/app/helpers/webui/webui_helper.rb#L112

**Comment by adrianschroeter** [comment]
raw log should only happen when source is stored on remote obs
