### ISSUE TITLE
SCM/CI: Report pending status for multibuilds

### ISSUE THREAD

**Issue by perlpunk** [openSUSE/open-build-service#12121]
We are about to use the SCM/CI for openQA projects.
We are using multibuilds, and it is a documented limitation, that multibuilds don't report a pending status, but only report the final fail or success.
https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html#sec.obs.obs_scm_ci_workflow_integration.setup.status_reporting

This can be problematic because when looking at a PR, one doesn't even know if there are still running checks, and we have a lot of checks.
A PR might get merged because every check passes.
We also use mergify to automatically merge in certain conditions, and we have to manually add every OBS build/platform to the configuration to be sure that it doesn't merge before those checks are reported.

So it would be nice if the pending status could also be reported.

**Comment by dmarcoux** [comment]
This isn't true anymore and the documentation needs to be updated. The build status of multibuild flavors is reported. Thank you for reporting this @perlpunk.

**Comment by perlpunk** [comment]
@dmarcoux oh, since when does that work?
It wasn't working yet last friday:
https://github.com/perlpunk/os-autoinst/pull/12
You can see the checks are all reported, but they only appeared when they were finished, not during the running check.

**Comment by dmarcoux** [comment]
Hum... I'll need to double-check, but I'm pretty sure the initial report is working.

**Comment by dmarcoux** [comment]
It's not working somehow, we need to investigate. Thank you again for reporting this.

**Comment by vpereira** [comment]
Tested locally on master and I couldn't reproduce it.

![Screenshot_2022-01-26_13-05-08](https://user-images.githubusercontent.com/37418/151160200-7e3c3671-30e5-40b1-b7c4-24fad00e8fe3.png)

**Comment by perlpunk** [comment]
@vpereira I will try again right now and create a PR in https://github.com/os-autoinst/os-autoinst/pulls and ping you directly after it. maybe you can see it

**Comment by dmarcoux** [comment]
@perlpunk I had a look at the PR and the initial report with the "pending" status weren't reported. It is the same that I experienced in a test I did.

**Comment by okurz** [comment]
So seems like there seems to a little difference in what you guys, @dmarcoux and @vpereira did? I read that at least there is the difference between "what is deployed+configured to build.opensuse.org" and "locally on master", right?

**Comment by vpereira** [comment]
> @vpereira I will try again right now and create a PR in https://github.com/os-autoinst/os-autoinst/pulls and ping you directly after it. maybe you can see it

As we talked privately, our issue is that we cannot reproduce it in development, but as @dmarcoux said he is able to reproduce in production. We are still investigating the issue.

**Comment by dmarcoux** [comment]
This was closed by mistake, there's still more to do for this. Reopening.

**Comment by perlpunk** [comment]
One more thing, I don't know if it's related: builds that are unresolvable are also not reported.
Example: https://github.com/os-autoinst/openQA/pull/4494
I would expect them to be reported as failures.

**Comment by dmarcoux** [comment]
Yes, this is sadly not implemented. We're tracking this in https://trello.com/c/0N3jHq5M/2257-report-back-to-scm-when-build-results-arent-failed-and-succeeded

**Comment by perlpunk** [comment]
ok thanks

**Comment by JanZerebecki** [comment]
This will be important for [ALP/Git](https://en.opensuse.org/openSUSE:ALP/Workgroups/Git-Packaging-Workflow).

**Comment by hennevogel** [comment]
As we are tracking this in our backlog, let's close this issue here.
