### ISSUE TITLE
Make sure Issue.name is something valid

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#1215]
[Security issue from Hakiri](https://hakiri.io/projects/24a4980a727941/stacks/beceb185080072/builds/9f4cab3b56e087/warnings/d6fc3236809c77): Unescaped model attribute rendered inline in app/controllers/issues_controller.rb

**Comment by hennevogel** [comment]
This is rendering xml, not html.

**Comment by hennevogel** [comment]
However we should whitelist what can end up in Issue.name

**Comment by ztmeyer** [comment]
Hey @hennevogel,

I wanted to bounce some ideas off of you. My initial thoughts are to add a before create hook on `Issue.rb`, like:
```ruby
  before_create :sanitize_name

  def sanitize_name
    self.name = ActionController::Base.helpers.sanitize self.name
  end
```

But it sounds like you might want to do more? Should it also be numeric with a dash (1234-5...)? Thanks!

**Comment by hennevogel** [comment]
hey @ztmeyer 👋🏻

It should only be [numeric + dash](http://guides.rubyonrails.org/active_record_validations.html#format), then we don't have to sanitize it at all.

**Comment by ztmeyer** [comment]
Ah ok - I see similar logic in https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/issue.rb#L52-L56.

So are you thinking a model validation on what you described? I.e.
```ruby
  validates :name, format: { with: /\A\d\d\d\d-\d+\z/,
                             message: 'four digits, hyphen, 1 or more digits' }
```

**Comment by hennevogel** [comment]
It's not so much about `Issue.name` being in a specific format. It's about `Issue.name` to only contain numbers and dashes. That is what all `IssueTracker`'s have in common.

**Comment by ztmeyer** [comment]
Ah ok - so we can relax the rules a bit:
```ruby
  validates :name, format: { with: /\A[\d\-]+\z/,
                             message: 'only digits and hyphens' }
```

Is this more what you're thinking?

**Comment by hennevogel** [comment]
@ztmeyer yes :-)

**Comment by ztmeyer** [comment]
Sounds great @hennevogel - I've created a PR here: https://github.com/openSUSE/open-build-service/pull/4128

**Comment by ztmeyer** [comment]
Darn - tests are failing, looks like this needs to be added to some factories too.

I'll close this for now. Will try to pick up again in future (or if someone else wants to please go ahead).

**Comment by hennevogel** [comment]
keep at it! :-)
