### ISSUE TITLE
Cross-Site Scripting Warning in app/views/webui/project/_packages_table.html.erb

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#1216]
[Security issue from Hakiri](https://hakiri.io/projects/24a4980a727941/stacks/beceb185080072/builds/9f4cab3b56e087/warnings/b96e1faf37daff): Unescaped model attribute in app/views/webui/project/_packages_table.html.erb

**Comment by ChrisBr** [comment]
Invalid!
Table shows package.name & project.name and both don't allow html / js tags!
