### ISSUE TITLE
"rebuild_package" workflow doesn't run OBS services

### ISSUE THREAD

**Issue by mwilck** [openSUSE/open-build-service#12173]
# Issue Description

I'm trying the [rebuild_package workflow](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html#sec.obs.obs_scm_ci_workflow_integration.obs_workflows.steps.rebuild_a_package) for the multipath-tools package. I have created rebuild workflows for the branches "next" and "edge", where the former is supposed to trigger a rebuild in [home:mwilck:multipath](https://build.opensuse.org/project/show/home:mwilck:multipath), and the latter in [home:mwilck:Future](https://build.opensuse.org/package/show/home:mwilck:Future/multipath-tools).

`.obs/workflows.xml` is the same in both branches, [see here](https://github.com/openSUSE/multipath-tools/blob/7b12856c5eb4923c7cb8b5a5141015b525a9fc2b/.obs/workflows.yml), relevant part below:

```
rebuild_next:
  steps:
    - rebuild_package:
        project: home:mwilck:multipath
        package: multipath-tools
  filters:
    event: push
    branches:
      only:
         - next

rebuild_edge:
  steps:
    - rebuild_package:
        project: home:mwilck:Future
        package: multipath-tools
  filters:
    event: push
    branches:
      only:
        - edge
```

In order to make sure that both Github and OBS were aware of this file, I pushed [multipath-tools commit ff1127c3](https://github.com/openSUSE/multipath-tools/commit/ff1127c39013177fdcb014646bb3c60f1b0ad9be) (with `workflows.xml` as above) to both branches on GH, and ran the OBS services manually in both projects to make sure this version was built on OBS. I even waited for the build to finish.

With the above code in place and the GH workflow set to trigger on **push** events, I expected the rebuild to be triggered on the next push. So I pushed a new commit to the "edge" branch, [d490717](https://github.com/openSUSE/multipath-tools/commit/d49071752b631d484800d185029424f2f46d8a6f). 

On the GH webhooks page, I can see a successful webhook delivery at 2022-02-07 21:05 with return code 200. Request (truncated, let me know if you need more info):

```
Request URL: https://build.opensuse.org/trigger/workflow?id=5319
Request method: POST
Accept: */*
content-type: application/json
User-Agent: GitHub-Hookshot/5fb002b
X-GitHub-Delivery: 51ed8fdc-8851-11ec-91c9-ef1ca791e76c
X-GitHub-Event: push
X-GitHub-Hook-ID: 317551402
X-GitHub-Hook-Installation-Target-ID: 327431130
X-GitHub-Hook-Installation-Target-Type: repository
X-Hub-Signature: sha1=8591a7ae652127cd893f2e00d24eb1ff8072b9ba
X-Hub-Signature-256: sha256=3177fd573ef8920c1d3c25fec216f109625586a581ee59a4a9acd55a0d5da64f

Body:
{
  "ref": "refs/heads/edge",
  "before": "ff1127c39013177fdcb014646bb3c60f1b0ad9be",
  "after": "d49071752b631d484800d185029424f2f46d8a6f",
  "repository": {
    "id": 327431130,
    "node_id": "MDEwOlJlcG9zaXRvcnkzMjc0MzExMzA=",
    "name": "multipath-tools",
    "full_name": "openSUSE/multipath-tools",
    "private": false,
...
  "head_commit": {
    "id": "d49071752b631d484800d185029424f2f46d8a6f",
    "tree_id": "be3bc72346e9dc6fc989b69a4b650402f9a0cc7e",
    "distinct": true,
    "message": "libmultipath: hwtable: use ALUA for all LIO targets\n\nLIO supports ALUA for all backends. Use it by default.\n\nSigned-off-by: Martin Wilck <mwilck@suse.com>",
    "timestamp": "2022-02-07T20:56:05+01:00",
    "url": "https://github.com/openSUSE/multipath-tools/commit/d49071752b631d484800d185029424f2f46d8a6f",
    "author": {
      "name": "Martin Wilck",
      "email": "mwilck@suse.com",
      "username": "mwilck"
    },
    "committer": {
      "name": "Martin Wilck",
      "email": "mwilck@suse.com",
      "username": "mwilck"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "libmultipath/hwtable.c"
    ]
  }
}
```

Response:
```
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/xml; charset=utf-8
Date: Mon, 07 Feb 2022 20:05:40 GMT
Etag: W/&quot;92acaf86ec8927d07247cf5ccc80701c&quot;
Referrer-Policy: strict-origin-when-cross-origin
Server: Apache/2.4.51 (Linux/SUSE)
Status: 200 OK
Strict-Transport-Security: max-age=31536000
Vary: Accept,Accept-Encoding
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Opensuse-Apiversion: 2.11~alpha.20220204T170231.ea402e1ea9
X-Opensuse-Runtimes: {&quot;view&quot;:2.7835280634462833,&quot;db&quot;:53.8936770753935,&quot;backend&quot;:112.198735}
X-Permitted-Cross-Domain-Policies: none
X-Powered-By: Phusion Passenger(R) 6.0.8
X-Request-Id: 0f66c773-7323-498b-b2ca-fcee42c0adb6
X-Runtime: 1.296252
X-Xss-Protection: 1; mode=block

Body

<status code="ok">
  <summary>Ok</summary>
</status>
```

Expected Result
============

I expected that that multipath-tools would be rebuilt in the `home:mwilck:Future` project, running the OBS services first to fetch the latest commits. I'd discussed this with Dany on Slack and he confirmed to me that " The rebuild_package step should definitely pull the changes from GitHub".

But this didn't happen. A rebuild was triggered, but without running the source services first, so that OBS simply built the previous commit ff1127c3 again. That can be seen immediately because I add the abbreviated hash to the package version number. In the buildlog on OBS, I saw only

```
Retried build at Mon Feb  7 20:07:10 2022 returned same result, skipped
```

When I click the "redeliver" button on GH, I can see again that OBS starts to build, but still with the same outdated sources. I must click on "Trigger Services" on OBS in order to pull in the code (but on the "edge" branch, I won't be doing it now to give you a chance to have a look; I'll continue working on "next").

How to Reproduce
===============

I am not sure. It seems to happen reproducibly when I run the OBS workflow from my multipath-tools repo.

**Comment by mwilck** [comment]
FTR, here is my [_service](https://build.opensuse.org/package/view_file/home:mwilck:Future/multipath-tools/_service?expand=1) file.

**Comment by mwilck** [comment]
Hm, I just tried the same on the "next" branch, and it didn't even start rebuilding, even though I'd got a "200 Ok" response again.

### request

```
Headers

Request URL: https://build.opensuse.org/trigger/workflow?id=5319
Request method: POST
Accept: */*
content-type: application/json
User-Agent: GitHub-Hookshot/5fb002b
X-GitHub-Delivery: c6a36878-8857-11ec-9d7e-a3f2c4470fb3
X-GitHub-Event: push
X-GitHub-Hook-ID: 317551402
X-GitHub-Hook-Installation-Target-ID: 327431130
X-GitHub-Hook-Installation-Target-Type: repository
X-Hub-Signature: sha1=07214a16f6faba597a0d3a8ce8a028f890b8ea9f
X-Hub-Signature-256: sha256=df840758aa84ecaccea7f84155c9f071c9957656b8f7d917630ae9253b9bbc82

Payload

{
  "ref": "refs/heads/next",
  "before": "ff1127c39013177fdcb014646bb3c60f1b0ad9be",
  "after": "d49071752b631d484800d185029424f2f46d8a6f",
...
```

### response
```
 Headers

Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/xml; charset=utf-8
Date: Mon, 07 Feb 2022 20:51:52 GMT
Etag: W/&quot;92acaf86ec8927d07247cf5ccc80701c&quot;
Referrer-Policy: strict-origin-when-cross-origin
Server: Apache/2.4.51 (Linux/SUSE)
Status: 200 OK
Strict-Transport-Security: max-age=31536000
Vary: Accept,Accept-Encoding
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Opensuse-Apiversion: 2.11~alpha.20220204T170231.ea402e1ea9
X-Opensuse-Runtimes: {&quot;view&quot;:4.783204989507794,&quot;db&quot;:33.237839001230896,&quot;backend&quot;:27.846705999999998}
X-Permitted-Cross-Domain-Policies: none
X-Powered-By: Phusion Passenger(R) 6.0.8
X-Request-Id: 6ff002ba-a743-43bc-a0b9-3731ff3dacbc
X-Runtime: 1.067347
X-Xss-Protection: 1; mode=block

Body

<status code="ok">
  <summary>Ok</summary>
</status>
```
I'm probably making some dumb mistake, but I can't figure it out.

**Comment by mwilck** [comment]
As soon as I clicked on "Trigger services", the latest commit d490717 was fetched and the rebuild started, but no sooner.

**Comment by hennevogel** [comment]
Rebuilding a package never runs services. A step for running services is on the TODO

**Comment by mwilck** [comment]
Ok, thanks. That's what I suspected but Dany told me otherwise — perhaps I got him wrong. I had also tried regular "push" workflow, but the way this creates lots of new packages with odd names didn't suit my workflow well. I suppose for what I need the traditional "runservice token" based method is the best choice, then.

**Comment by mwilck** [comment]
I have to say though - I fail to understand the rationale behind the rebuild feature then. What's the point of pushing to a branch, and having another, older code base rebuilt on OBS?

**Comment by hennevogel** [comment]
There is no real rationale 😸  We can't (and won't) figure out all the workflows people want to / will plug together. We just try to expose functionality.

**Comment by mwilck** [comment]
Fair enough. Waiting for the rebuild-with-pull workflow, then.
