### ISSUE TITLE
Cross-Site Scripting Warning in app/views/webui/project/_packages_table.html.erb

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#1219]
[Security issue from Hakiri](https://hakiri.io/projects/24a4980a727941/stacks/beceb185080072/builds/9f4cab3b56e087/warnings/ce4ea5d19a6a65): Unescaped model attribute in app/views/webui/project/_packages_table.html.erb

**Comment by bgeuken** [comment]
The data used in the code snippet comes from the DB. => false positive

Note that the p value is actually defined in the map block. Seems to be a bug in hakiri.
