### ISSUE TITLE
Cross-Site Scripting Warning in app/controllers/person_controller.rb

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#1220]
[Security issue from Hakiri](https://hakiri.io/projects/24a4980a727941/stacks/beceb185080072/builds/9f4cab3b56e087/warnings/ea8f44c644b38a): Unescaped model attribute rendered inline in app/controllers/person_controller.rb

**Comment by bgeuken** [comment]
No user provided value get's directly parsed in the view here -> false positive
