### ISSUE TITLE
Unstaging Requests with source_project missing fails

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#12250]
Max just had a request ([954389](https://build.opensuse.org/request/show/954389)) where the source project was deleted. Unstaging failed with

```
<status code="unknown_project">\n  <summary>Project not found: home:sbrabec:branches:graphics</summary>\n</status>\n'
```

**Comment by rubhanazeem** [comment]
This is not reproducing again. I've also tested a superseded request and I'm able to remove the branch from staging projects when the source project was deleted.

**Comment by dmarcoux** [comment]
Maybe @nilxam can provide more details on what happened. If not, we should close this issue.
