### ISSUE TITLE
webui: unable to load build log for repo with U+00A0

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#12349]
Observed:

Upon visiting https://build.opensuse.org/package/live_build_log/home:jengelh/test/st%C2%A0andard/x86_64 , it shows `No live log available: project 'home:jengelh' has no repository 'st andard'`.

`osc bl $(echo -en 'st\xc2\xa0''andard') x86_64` succeeds, so it's just a webui issue.

**Comment by hennevogel** [comment]
Duplicate of #7021
