### ISSUE TITLE
"openSUSE Leap 15.4" and "openSUSE Backports for SLE 15 SP4" has the same repo name while adding it via webui

### ISSUE THREAD

**Issue by nilxam** [openSUSE/open-build-service#12352]
# Issue Description
`openSUSE Leap 15.4` and `openSUSE Backports for SLE 15 SP4` repository option on webui has the same repo name, therefore you can not adding both two via webui, otherwise it give an error **Can't add repository: Name 15.4 is already used by a repository of this project**.

Expected Result
============
1. User should be able to add both two repository in its project without an error via webui.
2. `openSUSE Backports for SLE 15 SP4` should not use `15.4` as its default repo name otherwise it confuses user.

How to Reproduce
===============
1. Go to 'Repositories' option in the any project
3. Click on 'Add from a Distribution'
4. There are multiple options in the 15.4 Variants list
5. Selected on `openSUSE Leap 15.4` for adding it, then selecting `openSUSE Backports for SLE 15 SP4`
6. See error. Or vice versa, adding `openSUSE Backports for SLE 15 SP4` first then selecting  `openSUSE Leap 15.4`

**Comment by hennevogel** [comment]
This is why it's listed as variants.

![Screenshot from 2022-03-24 18-02-22](https://user-images.githubusercontent.com/514785/159970775-64c785a1-9472-4ec1-a177-6bafb46ea6bb.png)
