### ISSUE TITLE
build.opensuse.org sends no verification e-mail on account creation

### ISSUE THREAD

**Issue by Kaoticz** [openSUSE/open-build-service#12450]
Hello. Today I tried to create an account at https://build.opensuse.org/
I filled the form, sent my request, and got redirected to this page.

![screen](https://user-images.githubusercontent.com/1812311/163682380-a21ac91c-bcf3-43ad-8158-7d9f3ad1d9f8.png)

However, no e-mail was sent to my inbox. I've also checked the junk mails, it's not there.
Clicking on **Verify E-Mail Address** and requesting a new token yields the same result.

Browser: Firefox 99.0.1

**Comment by madsciencecoder** [comment]
I have the same issue. I tried resetting my password for an account I haven't used in a long time and tried creating a new account with a different email address but I never receive an email for either.

**Comment by Kaoticz** [comment]
So, today I got several e-mails to activate my account.
Whatever it was, it magically solved itself.

**Comment by hennevogel** [comment]
For the future: This functionality has nothing to do with OBS. Please contact the [openSUSE heroes](https://en.opensuse.org/openSUSE:Heroes) for help via admin@opensuse.org
