### ISSUE TITLE
mod_passenger proposes use of wrong ruby version

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#12459]
`/etc/apache2/conf.d/mod_passenger.conf`, owned by http://download.opensuse.org/repositories/OBS:/Server:/2.10/15.3/x86_64/rubygem-passenger-apache2-6.0.12-lp153.400.1.x86_64.rpm , contains

```
  PassengerRuby "/usr/bin/ruby"
```

On Leap 15.3, this ruby is version 2.5. However, obs-api depends on ruby 2.7 (according to rpm -qR), and I am getting an error message to that end from Phusion after setting `PassengerFriendlyErrorPages on` in `/etc/apache2/vhosts.d/obs.conf`:

```
The Phusion Passenger(R) application server tried to start the web application through a Passenger-internal helper tool called the "wrapper"). But that helper tool encountered an internal error.
 
The stdout/stderr output of the subprocess so far is:
 
/usr/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- phusion_passenger (LoadError)
        from /usr/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib64/passenger/6.0.12//helper-scripts/rack-preloader.rb:52:in `init_passenger'
        from /usr/lib64/passenger/6.0.12//helper-scripts/rack-preloader.rb:182:in `<module:App>'
        from /usr/lib64/passenger/6.0.12//helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
        from /usr/lib64/passenger/6.0.12//helper-scripts/rack-preloader.rb:29:in `<main>'
```

Changing mod_passenger.conf to point to ruby 2.7 resolves that particular issue.

**Comment by hennevogel** [comment]
See the release announcement about that manual step.

https://lists.opensuse.org/archives/list/buildservice@lists.opensuse.org/thread/JN52NSNX4QBD2SRYPGWBA5LEVCCDISQG/

**Comment by hennevogel** [comment]
Sorry for the inconvenience but `mod_passenger.conf` is marked as `%config(noreplace)`. Can't really do anything about it...
