### ISSUE TITLE
AppImages built by Opensuse Build Service do not show up on https://software.opensuse.org

### ISSUE THREAD

**Issue by leukimi** [openSUSE/open-build-service#12513]
In the Repositories section it is possible to choose distribution "AppImage". Fine. It builds and all seems good. But when you search for AppImage software on [https://software.opensuse.org](https://software.opensuse.org) it does not show up.

Do you, or somebody you know, know why AppImages built by Opensuse Build Service do not show up on [https://software.opensuse.org](https://software.opensuse.org)?

AppImages compile in the same project as those other distributions that compile well, which are then later all visible on [https://software.opensuse.org](https://software.opensuse.org). Seems strange why community built AppImages don't show up on [https://software.opensuse.org](https://software.opensuse.org) even though they show up in the repository and are downloadable if you know where they are. Not sure if you have noticed the same odd behavior.

**Comment by saraycp** [comment]
Hi @leukimi,

I recommend you to send this question to the IRC channel #opensuse-buildservice (irc.libera.chat) or via email to buildservice@lists.opensuse.org. There you can find a big community of OBS users and contributors that can help you.

I'm going to close this issue if you don't mind.
