### ISSUE TITLE
[production][webui/package#save_file] Suse::ValidationError: service validation error: Start tag expected, '<' not found

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#1253]
webui/package#save_file threw this 0 times
<pre>
Suse::ValidationError: service validation error: Start tag expected, &#39;&lt;&#39; not found
</pre>
[https://build.opensuse.org/package/save_file/home:scalpel4k/libmlt](https://build.opensuse.org/package/save_file/home:scalpel4k/libmlt)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5620fcd3764b23000c00000d)

**Comment by hennevogel** [comment]
This happens when you upload a `_service` file via webui

**Comment by hennevogel** [comment]
Another part of this is #1253

**Comment by ChrisBr** [comment]
I'll have a look at this!
