### ISSUE TITLE
corrupted maintenance request due to source included more than one time

### ISSUE THREAD

**Issue by deneb-alpha** [openSUSE/open-build-service#12548]
# Issue Description
While working at a maintenance request that includes several source packages can happen that a maintainer could submit some duplicated sources by mistake.

The main issue is that if a submitter will issue this kind of maintenance requests the problem will be visible only when maintenance team will try to process the maintenance request.

For those cases, when maintenance will issue the `request accept` command, IBS (and potentially also OBS) will reply with a 404 error.

As example:
`osc -A https://api.suse.de request accept 271426 -m "ok"`
this will result in 
```
HTTP Error 404: Not Found
not_found
Couldn't find Package
```
Looking at  the details of the maintenance request 271426, the source  package `golang-github-prometheus-promu` exists two times.

On more detail that could be relevant is that in all the affected cases, the submitter provided also a patchinfo with the maintenance request and I'm not sure if this could also be related  to this issue.

Before trying to accept the maintenance request there are no visible issues reported on it, after the first attempt to accept the maintenance request the patchinfo source is empty.

This issue happened already with a request including two times the patchinfo while with MR#271426 the duplicate was a normal source package. In all those cases the patchinfo provided will be corrupted after the first attempt to accept the maintenance request while the remaining source in the project will be still ok.

Expected Result
============
osc should prevent (or at  least warn) the user if the resulting maintenance request will include the same source more than one time for the same release target.

How to Reproduce
===============
1. prepare a dummy project with a patchinfo 
2. osc -A https://api.suse.de/ mr -m "submit a source two times" $source patchinfo patchinfo $target 
3. osc -A https://api.suse.de/  request accept $ID -m "trying to accept a submission with duplicates"

Further Information
===============
* [source package submitted twice and corrupted after trying to accept](https://build.suse.de/request/show/271426)
* [example of corrupted patchinfo](https://build.suse.de/package/show/SUSE:Maintenance:REQUEST:271426/patchinfo)
* [patchinfo submitted twice](https://build.suse.de/request/show/270445)

**Comment by juliogonzalez** [comment]
> osc should prevent (or at least warn) the user if the resulting maintenance request will include the same source more than one time for the same release target.

IMHO `osc` should either:
- Just reject the submission
- Go ahead and remove the duplicate, since the source project and the source package are 100% the same

I'd avoid the warning :-)

**Comment by deneb-alpha** [comment]
@hennevogel one  more "discovery" that could probably increase the priority  on this issue...

when IBS replies with that 404 error it creates in any case the initial maintenance incident, but only on the DB side but the same incident will be also reused by the next maintenance request that will be accepted (corrupting the incident). 

if you look at `isc log -M SUSE:Maintenance:24136`  you will see that on r1 there's ` rq271426` but from r68 it's also visible that the same incident has  been reused for other  submissions.

**Comment by deneb-alpha** [comment]
one more 404 error. :( 
this time there were no duplicated source or nothing visible that sounded suspicious. 
the  new submission was https://build.suse.de/request/show/271828, the command for accepting the maintenance request was ` isc request accept 271828 -m "ok"` and the error from IBS is:
```
HTTP Error 404: Not Found
not_found
Couldn't find Package
```
I'm now looking for the next corrupted maintenance incident.

**Comment by adrianschroeter** [comment]
Should be also solved via https://github.com/openSUSE/open-build-service/pull/12570

**Comment by juliogonzalez** [comment]
@adrianschroeter can we close https://build.suse.de/request/show/272075, then?
