### ISSUE TITLE
Backend servers refuses to bind to IPv6 [only] hostname

### ISSUE THREAD

**Issue by laf0rge** [openSUSE/open-build-service#12550]
I've been using several self-hosted "single node" OBS appliances for years, and now am setting it up in a more distributed manner for the first time.  However, I cannot get the workers connect to the reposerver / sourceserver at all.

My basis is opensuse 15.3 with OBS 2.10 from the official OBS package feed.

In the default install, the backend services bind to IPv4-only 0.0.0.0, while the frontend binds to the IPv4+IPv6 ::

This is despite the fact that the FQDN (obs.osmocom.org) resolves fine to an IPv6 AAAA record.  I would have expected the logic 
"my $hostname = Net::Domain::hostfqdn() || 'localhost';" to use that FQDN in this context?

Still, despite that FQDN, the services (with default BSConfig.pm) bind to 0.0.0.0 (IPv4 INADDR_ANY):
`
tcp        0      0 0.0.0.0:5252            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:5352            0.0.0.0:*               LISTEN     
`

I then further edited BSConfig.pm to hard-code 
`
our $srcserver = "http://obs.osmocom.org:5352";
our $reposerver = "http://obs.osmocom.org:5252";
our $serviceserver = "http://obs.osmocom.org:5152";
our $clouduploadserver = "http://obs.osmocom.org:5452";
`
but still this is ignored and the services continue to bind to v4-only INADDR_ANY just like before.

What am I doing wrong?

**Comment by saraycp** [comment]
Hi @laf0rge,

We are using Github issues to track issues in the source code, not to request support.

I recommend you send this question to the IRC channel #opensuse-buildservice (irc.libera.chat) or via email to [buildservice@lists.opensuse.org](mailto:buildservice@lists.opensuse.org). There you can find a big community of OBS users and contributors that can help you.

I'm going to close this issue if you don't mind.

**Comment by mlschroe** [comment]
The backend code currently only supports ipv4, as strange as that might sound. Adding ipv6 support is not hard though, so we will probably have it in the next major OBS release.

**Comment by laf0rge** [comment]
@saraycp, so this is a bug after all. Please reopen.  Either IPv6 needs to be implemented (it's 2022!) or the restriction to IPv4-only needs to be added to the manual, IMHO.  I could not find any mention in the administrator guide or anywhere else documenting that constraint.

**Comment by laf0rge** [comment]
It seems this was already mentioned 7 years ago in #895

**Comment by saraycp** [comment]
@laf0rge thanks for the clarification. I've re-opened it.

**Comment by mlschroe** [comment]
This is now done, see commit 6436640a89550a0aadb65c78dfc5b5c36b731907
