### ISSUE TITLE
[production][webui/project#save_distributions] ActiveRecord::RecordInvalid: Validation failed: Project already has repository with name SLE_12

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#1259]
webui/project#save_distributions threw this 6 times
<pre>
ActiveRecord::RecordInvalid: Validation failed: Project already has repository with name SLE_12
</pre>
[https://build.opensuse.org/project/save_distributions?project=home%3Avickreman%3ARealTime](https://build.opensuse.org/project/save_distributions?project=home%3Avickreman%3ARealTime)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/56210195764b23000900000e)

**Comment by hennevogel** [comment]
Isn't this catched?

**Comment by bgeuken** [comment]
Doesn't look like it.

**Comment by adrianschroeter** [comment]
IIRC we didn't offer the repositories which are already used in the project in the past.

**Comment by bgeuken** [comment]
This got merged now and will reach production with the next deployment.
