### ISSUE TITLE
Publishing disabled in PR created by SCM/CI integration

### ISSUE THREAD

**Issue by ailin-nemui** [openSUSE/open-build-service#12609]
# Issue Description
According to the docs, publishing is enabled by default. On the PR projects created by the SCM/CI integration in my home, it is disabled. I cannot seem to explicitly enable it either

Expected Result
============
Publishing enabled

How to Reproduce
===============
1. OBS Workflow config (a): https://github.com/ailin-nemui/irssi/blob/9f71a391c3e1c61eb71be22fe4226b783dc03096/.obs/workflows.yml#L10
2. OBS Workflow config (b): https://github.com/ailin-nemui/irssi/blob/8b01364d/.obs/workflows.yml#L3
3. Project auto-created by integration: https://build.opensuse.org/repositories/home:ailin_nemui:CI:ailin-nemui:irssi:PR-87
4. See that publish is disabled (not disabled by me)

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enable publishing for projects created by workflows](https://trello.com/c/kL3HF4ET/174-enable-publishing-for-projects-created-by-workflows)

**Comment by krauselukas** [comment]
@ailin-nemui we fixed the issue and soonish after the next deployment of build.o.o your workflow with the set_flags step should work as expected
