### ISSUE TITLE
[webui/user#requests] This route is completely borked...

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#1261]
webui/user#requests threw this 4 times
<pre>
NoMethodError: undefined method `to_sym&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/home/requests?user=](https://build.opensuse.org/home/requests?user=)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5621952226c5970009000007)

**Comment by hennevogel** [comment]
The `user/requests` route is completely borked...

**Comment by bgeuken** [comment]
fixed
