### ISSUE TITLE
[webui/package#save_file] Uploading _service/_link files broken

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#1264]
webui/package#save_file threw this 3 times
<pre>
RuntimeError: illegal option; need content for /srv/www/obs/api/public/schema//service
</pre>
[https://build.opensuse.org/package/save_file/home:malkavi/unknown-horizons-git](https://build.opensuse.org/package/save_file/home:malkavi/unknown-horizons-git)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/56211607764b23000600000f)

**Comment by ChrisBr** [comment]
#1313 will fix this
