### ISSUE TITLE
/monitor graphs give very strange pattern

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#1266]
Something is strange - it looks like the scheduler events go from 0 to 100 and back in short intervals
![blank2](https://cloud.githubusercontent.com/assets/1067203/10574982/b8d872e0-7659-11e5-82a8-6b9e5413dd08.png)

**Comment by coolo** [comment]
There are always 3 values per second - instead of the sum of them (there are 3 schedulers)

```
=> [#<StatusHistory id: 431172794, time: 1445249368, key: "squeue_high_i586", value: 22.0>, #<StatusHistory id: 431172867, time: 1445249397, key: "squeue_high_i586", value: 0.0>, #<StatusHistory id: 431172907, time: 1445249397, key: "squeue_high_i586", value: 0.0>, #<StatusHistory id: 431172947, time: 1445249397, key: "squeue_high_i586", value: 17.0>, #<StatusHistory id: 431173020, time: 1445249428, key: "squeue_high_i586", value: 0.0>, #<StatusHistory id: 431173060, time: 1445249428, key: "squeue_high_i586", value: 0.0>, #<StatusHistory id: 431173100, time: 1445249428, key: "squeue_high_i586", value: 17.0>, #<StatusHistory id: 431173173, time: 1445249458, key: "squeue_high_i586", value: 0.0>, #<StatusHistory id: 431173213, time: 1445249458, key: "squeue_high_i586", value: 0.0>, #<StatusHistory id: 431173253, time: 1445249458, key: "squeue_high_i586", value: 17.0>]
```

**Comment by coolo** [comment]
e39a9a7b7563aa063700d15da876da2df10db531 moved from calling /status/history to direct DB access. And the /status/history call had so far hidden the fact that we have 3 keys as it sampled, i.e giving the average between the 3 schedulers.

**Comment by coolo** [comment]
the bug is not in the webui - it affects /status/history just as well, just noone spotted the lies it spits out :)

the problem is that for "jobs" and "blocked", the src_server will cummulate the numbers and the API has nothing to do, but for the squeue values the API was never adapted for the partitioning.

**Comment by coolo** [comment]
https://gist.github.com/coolo/f065b21d792f84a1de9f would be my proposal for a fix

**Comment by coolo** [comment]
(completely untested)

**Comment by hennevogel** [comment]
#1272

**Comment by coolo** [comment]
this was fixed and the graphs look monotone again, but I noticed a small change - and perhaps you want to fix that that too (so I leave the issue open): previously the details were smoothed out over the watched time. Now the graph show the results as they are in the database - increasing the dataset quite heavily and making the last hour/day pretty noisy.

Perhaps you still want to scale the samples out before giving them to the browser

**Comment by hennevogel** [comment]
Hmmm

**Comment by bgeuken** [comment]
Closing, since the main issue is solved and we probably won't manage to tackle the other issue anytime soon.
