### ISSUE TITLE
Timecop affects OBS's test coverage

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#1268]
We need to cleanup calls of Timecop in our tests. Either by running Timecop.return after any test that uses Timecop.freeze or by running the freeze in a block. See #1262 for more details.

**Comment by bgeuken** [comment]
Assigning to myself for now. If anyone wants to pick this one up, feel free to do so:)

**Comment by hennevogel** [comment]
If you don't want to work on it don't assign it to yourself :-)

**Comment by bgeuken** [comment]
Reading is an art I heard

**Comment by hennevogel** [comment]
I don't get what you are trying to say.

**Comment by hennevogel** [comment]
Some of it is fixed in #1272

**Comment by bgeuken** [comment]
solved
