### ISSUE TITLE
notifications crashing with error 500 caused by undefined method `commentable' 

### ISSUE THREAD

**Issue by bugfinder** [openSUSE/open-build-service#12704]
Seeing this on the IBS instance currently but I assume it should be possible to cause this on other instances as well

internal errbit url https://errbit.suse.de/apps/53bac9aad9d1af372d012a0c/problems/62a6dc84d9d1af061dad23d5

undefined method `commentable' for nil:NilClass bs_request = @notification.notifiable.commentable 
WHERE	notifications#update

**Comment by eduardoj** [comment]
It most likely could be related to #9424.

**Comment by mcepl** [comment]
Tried, but I haven’t managed to reproduce (whole day work with IBS).

**Comment by eduardoj** [comment]
It doesn't happen anymore. Closing.
