### ISSUE TITLE
RPM spec and RPM changes syntax highlighting is broken on private instances

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/open-build-service#1273]
I just installed a fresh OBS 2.6.6 instance and encountered a distinct lack of syntax highlighting for RPM spec and RPM changes files. Upgrading to the latest unstable code didn't help either.

It's rather annoying that the nice syntax highlighting that's present on build.opensuse.org can't be replicated on the private instances.

I'd appreciate a fix making it into 2.6, but at least fix it in the latest unstable code being published to the OBS:Unstable repository.

**Comment by hennevogel** [comment]
The reference server is using master. So which problems did you have with this?

This will not be something we port back to 2.6, sorry.

**Comment by Conan-Kudo** [comment]
It doesn't show up at all. Both changes files and spec files show up without any syntax highlighting whatsoever.

I set up a build service appliance using the ISO on the website, and then changed the zypper repository configuration to point to Server:Unstable (which I need anyway because debbuild doesn't work in 2.6), and upgraded everything. Both prior and after the upgrade, I have no syntax highlighting for SPEC files and CHANGES files. It renders like regular plain text, which makes it hard to pick apart.

**Comment by Conan-Kudo** [comment]
This has been long fixed...
