### ISSUE TITLE
Repository creation errors are not visible

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#1274]
webui is not showing repository creation errors. It just stays forever in "has not been created yet". Since osc is not showing the error either the user has no chance to detect his error until he calls api calls directly.

The repo state code stays in "finished" unfortunatly (we should introduce a "broken" or other error state here). But we can still detect the situation by showing the details attribute content, if it exists. Idealy the repository icon should also turn into some kind of red-error symbol.

Example xml from _result api call:

  &lt;result project="home:Reki:leechcraft:masterbranch" repository="openSUSE_13.1" arch="i586" code="finished" state="finished" details="delta generation: unresolvable: have choice for libatomic1 &gt;= 4.8.1_20130909-3.2.1 needed by gcc48: libatomic1-gcc49 libatomic1, have choice for libitm1 &gt;= 4.8.1_20130909-3.2.1 needed by gcc48: libitm1-gcc49 libitm1"%gt;

Important since this is quite misleading to the user and people tend to wait for month until reporting a problem.

**Comment by hennevogel** [comment]
This? #1259

**Comment by adrianschroeter** [comment]
no, it is not about creating a repository definition in project. It is about to publish a repository which has finished building. The above example shows that the user has configured delta rpm creation, but he broke the delta rpm setup. So the delta generation build jobs could never get created.

**Comment by adrianschroeter** [comment]
the fact that the repo is not become broken state was a bug in scheduler, fix is on the way.

**Comment by adrianschroeter** [comment]
Everything is done, except that the webui is not showing the details yet.

repo_status_icon(status, details = nil)  helper function is prepared, but not used in the view yet.

**Comment by mdeniz** [comment]
This was fixed in bacc6e87a9dde0cffa4a7f6202b8d152f25d9654
