### ISSUE TITLE
Notifications lack a group hint when gaining a role through a group

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#12873]
Related to the new code that's also causing [(1)](https://github.com/openSUSE/open-build-service/issues/12588), [(2)](https://github.com/openSUSE/open-build-service/issues/12590).

A prj meta was changed; a line was added:
```
  <group groupid="opensuse-review-team" role="reviewer"/>
```

Observed mail
=========

```
dirkmueller made you reviewer of openSUSE:Leap:15.5:ARM:Images
```

($actor made you $role of $project)

This occurred on build.opensuse.org with the particular version it ran that day.

Expected to see instead
============

If a prjmeta change does not include $actor by username, it should emit how the maintainership/reviewership came to be, e.g.

```
dirkmueller made you (member of the group opensuse-review-team) reviewer for openSUSE:Leap:15.5:ARM:Images
```

**Comment by dmarcoux** [comment]
This was addressed in #13418.
