### ISSUE TITLE
Rate limiting and metrics for opening public API

### ISSUE THREAD

**Issue by abitrolly** [openSUSE/open-build-service#12882]
I'm always frustrated when I can't access public info without login and password.

**Describe the solution you'd like**

https://github.com/openSUSE/open-build-service/issues/7510#issuecomment-487948010 mentions that there is [no public read-only API](https://build.opensuse.org/apidocs/index). Endpoints like https://build.opensuse.org/public/distributions are not documented and not recommended for usage, because there is no rate limiting to keep service usage at bay.

I don't see any issues with endpoints like https://build.opensuse.org/public/distributions that can be cached plain static pages, regenerated only when the data change.

Because that will require embedding some static generator into Ruby on Rails app, which may or may not be a trivial task, it would be actually nice to get some monthly metrics about load that is caused by public endpoints in comparison to authenticated API and plain web site pages. This will allow to open less static endpoints as well, such as binary package lists.

If metrics will show that some endpoints are popular among users, but add a significant load, then a rate limiting service for anonymous can be deployed. I don't know what is the best way to do this in Ruby on Rails API app. Any hints?

**Comment by hennevogel** [comment]
You are mixing up some things. The `/public` API is an internal OBS API that is used for the interconnect. We don't recommend to use it because we will change what is provided and how it at will. And yeah, the name might be confusing...

We want you to login for other things because want to have a say in how you are using our service. One dimension of this is performance of certain operations, but only one dimension.

If you want to discuss this further, please make use of the mailing lists or IRC.

**Comment by abitrolly** [comment]
@hennevogel mailing lists are hard. You can not reply to existing topics. Irrelevant threads start to pop into mailbox. IRC doesn't preserve public history.

Now that you've mentioned that you want me to login to collect the data of how I am using the service.. even if I just want to list supported Distributions list.. thanks to GDPR/CCPA.. and I wouldn't ask otherwise for the free service.. so..

What data do you collect about me exactly? Can I hope to see it in near future with some `osc gdpr` coomand? Very curious. )

**Comment by hennevogel** [comment]
> Now that you've mentioned that you want me to login to collect the data of how I am using the service..

Sorry, you are mixing up things again. I said we want to have **a say** in how you are using our service. Specifically intentionally or unintentionally abusive behavior.

If you want to make a GDPR request for some instance like build.opensuse.org, see it's terms of site.

**Comment by abitrolly** [comment]
Not sure I understand how limiting people to know what distributions OBS supports, or which binaries are available, helps in directing users how to use the service. What it does, is provide lesser security, as now occasional users like me are tempted to use temporary config files with plain password just to read some info.

**Comment by hennevogel** [comment]
I'm not quite sure what you are arguing here? That there should be finer grained authentication for some specific part of the API? We all agree on that. What is it you want?

**Comment by dmarcoux** [comment]
> (...) is provide lesser security, as now occasional users like me are tempted to use temporary config files with plain password just to read some info.

You do what you want, but nothing is forcing you to store your password is plain text to use OBS and its API. With _osc_, you can use one of the supported [keyrings](https://github.com/openSUSE/osc#keyrings) to store passwords.

I don't really understand what is the issue with having rate limiting for APIs. It's a standard practice to limit abuse.

**Comment by abitrolly** [comment]
> That there should be finer grained authentication for some specific part of the API? We all agree on that. What is it you want?

That's correct. No authentication for some parts of the API.

**Comment by hennevogel** [comment]
> That's correct. No authentication for some parts of the API.

And we all agree on that, no need to repeat the argument again...

**Comment by abitrolly** [comment]
> And we all agree on that, no need to repeat the argument again...

If we agree, then why close this issue? In https://github.com/openSUSE/open-build-service/issues/7510#issuecomment-487948010 you said that the reason there is no unauthenticated calls is because you don't have rate limiting.

> The reason we don't have a public API is that we don't have rate limiting currently.

And when I propose to add rate limiting (if needed) to open the API, you close the issue.

**Comment by hennevogel** [comment]
> If we agree, then why close this issue?

Because #7510 is already the feature request?

**Comment by abitrolly** [comment]
#7510 doesn't cover rate limiting, but you said that the rate limiting is a blocker, so I created this issue to tracker the blocker.

**Comment by hennevogel** [comment]
Cool but we don't track solutions here, we track problems 😃
