### ISSUE TITLE
one obs-worker run different kernel in kvm

### ISSUE THREAD

**Issue by TengHuang168** [openSUSE/open-build-service#12902]
I want to use one obs-worker to run different kernel use vm_type = kvm ,  but I don't know how to config.

**Comment by dmarcoux** [comment]
Sorry @TengHuang168, but we're tracking issues about the source code of the Open Build Service here. To get some help regarding how to run OBS, please refer to the [Community](https://github.com/openSUSE/open-build-service#community) in our README.

**Comment by TengHuang168** [comment]
ok! thank you.
