### ISSUE TITLE
Merge User.can_modify_project?/User.can_create_project?

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#1291]
`User.can_modify_project?` will return true for Projects not yet saved into the database even if I can't create them. There is another method `User.can_create_project?` which can handle this.

Instead of different methods for different intentions we should have one method that covers all intentions.

**Comment by hennevogel** [comment]
This makes it possible to create home projects with the webui even though `Configuration.allow_user_to_create_home_project` is false

**Comment by bgeuken** [comment]
@hennevogel Where is this used? The check for ability to create a project is User#can_create_project?.
May it be that we are just using the wrong method somewhere?

And no this isn't confusing at;-)

**Comment by bgeuken** [comment]
Think I found [it](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/policies/project_policy.rb#L10).

**Comment by hennevogel** [comment]
I just mean the function. It will tell me "yes you can modify the project". When I use it on a new record like this

`User.can_modify_project?(Project.new(name: 'home:henne'))`

even if

`Configuration.allow_user_to_create_home_project` is false...

**Comment by hennevogel** [comment]
with pundit? no...
