### ISSUE TITLE
Can't wipe binaries of multibuild flavors in the webui

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#12913]
https://build.opensuse.org/package/binaries/home:coolo:alp/libappindicator:gtk2/standard got a "Delete Binaries" icon (for me obviously, most others not) but I click it, I end up on 
https://build.opensuse.org/package/binaries/home:coolo:alp/libappindicator/standard with an error flash saying "Error while triggering wipe binaries for home:coolo:alp/libappindicator: unknown package: libappindicator%3Agtk2 404 unknown package: libappindicator%3Agtk2 ."

**Comment by dmarcoux** [comment]
This is where the backend errors out: https://github.com/openSUSE/open-build-service/blob/a46cfdc581b09e8ef8c1ef8f7c26b871abf274dd/src/backend/bs_srcserver#L4285-L4287

This code should support multibuild flavors.

**Comment by coolo** [comment]
I was able to wipe it using osc - it's not a backend problem

**Comment by dmarcoux** [comment]
What was your `osc` call exactly, was it `osc wipebinaries home:coolo:alp libappindicator:gtk2`?

**Comment by coolo** [comment]
`osc wipebinaries home:coolo:alp/libappindicator -r standard -a x86_64 -M gtk2`

**Comment by hramrach** [comment]
Also abort build and rebuild behave the same.

**Comment by hramrach** [comment]
See also #7866
