### ISSUE TITLE
Layout issues if a request is in accepted state

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#12937]
See https://build.opensuse.org/request/show/993778

**Comment by hennevogel** [comment]
Might be solved by #12921

**Comment by dmarcoux** [comment]
What is the layout issue exactly?

**Comment by hennevogel** [comment]
![Screenshot 2022-08-15 at 11-06-46 openSUSE Build Service](https://user-images.githubusercontent.com/514785/184607982-86496917-d798-4847-bc5c-c96a61d5a909.png)
