### ISSUE TITLE
Question regarding Debian Package Build Dependencies

### ISSUE THREAD

**Issue by wentz89** [openSUSE/open-build-service#12960]
Hi,

I know that this may not be the right place to ask Questions but I really can not find any Information about my Problem and don't know where else to ask.

Short Version: Is it possible to have build dependencies (in debain/control) on older Versions of a Package.

Lets say I got this Version Table (from apt-cache policy gcc-9):
  Version table:
 *** 9.4.0-1ubuntu1~20.04.1 500
        500 http://mirror.de/ubuntu focal-security/main amd64 Packages
        500 http://mirror.de/ubuntu focal-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     9.3.0-10ubuntu2 500
        500 http://mirror.de/ubuntu focal/main amd64 Packages
And my debian-package really needs to build against gcc 9.3, so in my control file I would add
Build-Depends: gcc-9 (=9.3.0)

Is that something OBS can handle?

Background: They are using OBS in my Company as a backend and I have no possibility to see or configure anything in OBS and my build will always fail with an error message like:
nothing provides gcc-9 = 9.3.0, (got version 9.4.0)

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.libera.chat/openSUSE-buildservice) or on the [OBS mailing list](https://lists.opensuse.org/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 
 
Thank you for your consideration.
