### ISSUE TITLE
Projects deleted should decline reviews by_project $self

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#1296]
If a project is deleted with an open review, the reviews become unacceptable as a review accept will give you a 404.

So I suggest the review is accepted or declined - declining makes more sense I assume

**Comment by hennevogel** [comment]
This already happens in [Project#revoke_requests](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/project.rb#L206). Are you looking for something else?

**Comment by hennevogel** [comment]
Anyhow. BsRequest.remove_review is broken...
