### ISSUE TITLE
Feedback for beta /request/show remodeling

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#13009]
https://build.opensuse.org/request/show/868044

Under the beta program, there are now subtabs "Conversation", "Build Results" and "Changes".
The bad part of the remake is that one now has to switch from conversation to changes and then back again; having the diff right above the comment field was better.

**Comment by rubhanazeem** [comment]
@jengelh we have diff comments now to have conversations about the changes. If it's still a problem and you have some more suggestions please feel free to open a new issue
