### ISSUE TITLE
use a https port for scmsync gitlfs instead of 9999

### ISSUE THREAD

**Issue by JanZerebecki** [openSUSE/open-build-service#13013]
**Is your feature request related to a problem? Please describe.**
Currently the gitlfs support for use with scmsync is available at http://gitea.opensuse.org:9999/gitlfs . Using a non-https port may make it harder for some to reach.

**Describe the solution you'd like**
Use a reverse proxy to map the default gitlfs path: https://github.com/git-lfs/git-lfs/blob/main/docs/api/server-discovery.md#guessing-the-server
This has the advantage that we do not need to configure it for a repo to work (though we might still want to).

**Describe alternatives you've considered**
Use a different domain, e.g. a subdomain.

**Additional context**

**Comment by coolo** [comment]
that server is hardly a build service feature. That issue belongs here I guess: https://github.com/adrianschroeter/git-lfs-ro-server

**Comment by adrianschroeter** [comment]
jfyi, it is anyway planned to move that url to an own sub domain. 
I can also look into ssl support later on.
