### ISSUE TITLE
Requests review web page remodelling: Allow inline commenting in "Changes" tab

### ISSUE THREAD

**Issue by badshah400** [openSUSE/open-build-service#13011]
**Is your feature request related to a problem? Please describe.**

The web-interface always annoys me when I have to copy-paste snippets from the diff for my comment/review. Firstly, this seems like a clumsy way to add a review that references specific diffs; secondly copying from the diff shown in the web interface ends up copying the line numbers as well leading to a rather untidy pasted snippet, unless one cleans it up in a text editor first.

With the remodelled approach, this gets worse because in addition to neither of the above annoyances being solved, we have to go back to the "Conversation" tab to paste copied snippets from the "Changes" tab.

**Describe the solution you'd like**

Allow in-line comments for the diff shown in "Changes" tab directly, with no copy-pasting required. This would be similar to how GH handles commenting on pull requests in their "Changes" tab, for instance.

**Comment by dmarcoux** [comment]
Thank you @badshah400 for the feedback, this is definitely something we want to implement.

**Comment by badshah400** [comment]
Hi, this now seems to implemented as a beta feature. Many thanks!

As someone with beta features enabled, I can now make inline comments. However, these comments are simply invisible to another user who is not subscribed to beta features, i.e. they have zero indication of my comments (for example over a review). See https://build.opensuse.org/request/show/1084153 for the misunderstanding it can cause.

**Comment by hennevogel** [comment]
@badshah400 we are aware of this, thanks for bringing this up.

**Comment by hennevogel** [comment]
both things work now, changes related comments and displaying them in and outside beta
