### ISSUE TITLE
support createrepo compress-type option

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/open-build-service#13094]
**Is your feature request related to a problem? Please describe.**

Problem: When we publish Leap 15.3 SLE update repos, a 900MB primary xml file is created. With current gzip compression, it leaves a 120MB xml.gz file and then 900 users download this before it hits our mirrors, creating a traffic spike of 100GB/h that hit downloadcontent.o.o. My experiments showed, that with default `xz -6` it can be 7.6 MB, which is an improvement by factor 16 over gzip. Unfortunately, the compression is slower (259s instead of 11s).
`zstd --long -c1` would offer much faster compression than gzip (1s instead of 11s) at comparable output size as xz (10.7MB), but `createrepo_c` does not support this, yet.

**Describe the solution you'd like**
src/backend/bs_publish should support passing the `--compress-type` option to `createrepo_c` or another way to enable .xz xml compression

**Describe alternatives you've considered**
We could patch the toolchain to fully support `zstd --long`

**Additional context**

Looking for input from @mlschroe .

**Comment by mlschroe** [comment]
We use 'gzip --rsyncable' because we support delta downloads of repository metadata.

The way forward would be to switch to zchunk metadata compression. All the code is in place, but somebody has to ask for it.

**Comment by bmwiedemann** [comment]
> We use 'gzip --rsyncable' because we support delta downloads of repository metadata.

I checked today's logs and found that zypper seems to always fetch the full 120MB xml.gz file, even when it has chunk hashes. Also verified with tcpdump on a local `zypper ref` so I know those are not just scratch systems without previous versions.

> The way forward would be to switch to zchunk metadata compression

I ask you to try it to see how big 15.3 sle update primary.xml transfers would be with it.

**Comment by bmwiedemann** [comment]
We have .xml.zst files now in https://download.opensuse.org/tumbleweed/repo/oss/repodata/?P=*zst so can we close it?

**Comment by bmwiedemann** [comment]
This is solved by adding such a line to prjconf:
```
RepoType: rpm-md:sha512:filelists-ext:compression-zstd
```
