### ISSUE TITLE
create subproject workflow ignores allow_user_to_create_home_project configuration

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#1309]
When Configuration.allow_user_to_create_home_project is false users still can create subprojects.

**Comment by adrianschroeter** [comment]
Maybe there is a misunderstanding, once a user has his home project, he should be allowed to create subprojects. But it should not work before. And he should not be able to create his home project on his own with this setting.

This is tested in this commit: 4ee5338c249c5927e873b741a66481f55bb9d13a

Do I miss something?

**Comment by bgeuken** [comment]
Alright. Nevermind then

**Comment by bgeuken** [comment]
Looking at https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/user.rb#L564 makes me think that it shouldn't. Might be somewhere in has_local_permissions is another check that allows it then. Who knows?

-> back to Studio duties
