### ISSUE TITLE
preinstallimage: generated /etc/hosts breaks installation of netcfg

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/open-build-service#13104]
`openSUSE:Factory` is using preinstallimage for package builds. Unfortunately, the generated /etc/hosts in these preinstalled images breaks installation of netcfg and thus has broken IPv6 support since generated /etc/hosts lacks entries for IPv6 localhost entries.

```
[    1s] init_buildsystem --configdir /var/run/obs/worker/3/build/configs --cachedir /var/cache/build --prepare --clean --rpmlist /var/cache/obs/worker/root_3/.build.rpmlist /var/cache/obs/w
orker/root_3/.build-srcdir/nodejs18.spec build ...
[    2s] unpacking preinstall image openSUSE:Factory/standard/preinstallimage-base [70a9776c8fd3bdbf526d4ea20271ed4c]
[    6s] 
[    6s] copying packages...

...

[   18s] [158/179] cumulate netcfg-11.6-9.12

...

[   18s] netcfg-11.6-9.12                      ########################################
[   18s] warning: /etc/hosts created as /etc/hosts.rpmnew

```

**Comment by AdamMajer** [comment]
This is still a problem. Is there any way to solve this from my side?

**Comment by hennevogel** [comment]
Please bring this up on the factory mailing list where it belongs

https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/

**Comment by eduardoj** [comment]
Just to link to what it belongs, this issue was also created here: https://github.com/openSUSE/obs-build/issues/848
