### ISSUE TITLE
bcntsync tag is not supported in maintenance incidents

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#1310]

**Comment by hennevogel** [comment]
This is fixed in 639ff2134076856e1d873f5bdf15574377e3ce9d right?

**Comment by adrianschroeter** [comment]
hopefully, but I did not test the backend yet, neither I have testcases for it yet ....
So I like to keep the issue open until then.

**Comment by ChrisBr** [comment]
@adrianschroeter ping?
