### ISSUE TITLE
the api doc page uses build.opensuse.org instead of api.opensuse.org

### ISSUE THREAD

**Issue by portaloffreedom** [openSUSE/open-build-service#13139]
# Issue Description
On the website https://build.opensuse.org/apidocs-new there is a nice API interface, but in the examples it uses `build.opensuse.org` instead of `api.opensuse.org`. This implies
1. Curl examples are given using build.opensuse.org
2. the "try out" in the webpage does not work when logged out of build.opensuse.org

Expected Result
============
The documentation should give the correct examples. 
The examples of the documentation should work when logged out of build.opensuse.org (it works if you are logged in because of cookies)

How to Reproduce
===============
1. Open incognito mode
3. Navigate to https://build.opensuse.org/apidocs-new
4. Insert credentials in authorize button
5. Test the Architectures endpoint (or any that is not About really) https://build.opensuse.org/apidocs-new/#/General%20Information/get_architectures
6. Observe it fail and keep asking for authentication
7. Observe the curl example using build... instead of api....

Further Information
===============
* the Basic authentication flag only works with api.opensuse.org and not with build.opensuse.org
* errors when not using the correct endpoint are very cryptic, wasting me a lot of time

**Comment by danidoni** [comment]
We recommend to use https://api.opensuse.org/apidocs-new/index.html for accessing the API documentation. That way you won't have any problem.

We even added a link in the legacy API documentation https://api.opensuse.org/apidocs/index so new users start using the preferred url.

Thanks for reporting the issue!
