### ISSUE TITLE
Bogus error from https://build.opensuse.org/package/binaries/openSUSE:Factory:ARM/aaa_base/standard

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/open-build-service#13147]
https://build.opensuse.org/package/binaries/openSUSE:Factory:ARM/aaa_base/standard
results in 
404 repository 'openSUSE:Factory/standard' has no architecture 'aarch64'

**Comment by coolo** [comment]
At least it's no longer crashing anymore. This used to be a 500 :)

**Comment by hennevogel** [comment]
Yeah this package comes through a project link and they are not very well supported...

**Comment by andreas-schwab** [comment]
It's a regression.

**Comment by hennevogel** [comment]
yeah maybe fallout from #13091

**Comment by hennevogel** [comment]
Indeed `FlagHelper` does not support project links....

**Comment by hennevogel** [comment]
> keep in mind that package meta flags have no influence via project links while you are on it

Yeah I already look at repo linkedbuild and project settings.
