### ISSUE TITLE
[production][webui/package#save_file] RuntimeError: illegal option; need content for /srv/www/obs/api/public/schema//service

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#1315]
webui/package#save_file threw this 0 times
<pre>
RuntimeError: illegal option; need content for /srv/www/obs/api/public/schema//service
</pre>
[https://build.opensuse.org/package/save_file/home:cfelder/python-gr](https://build.opensuse.org/package/save_file/home:cfelder/python-gr)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5631cc9557ee420009000002)

**Comment by adrianschroeter** [comment]
The webui seems to try to store empty files, when using "adding a new file" functionality. 
This leads to crashes on special files which gets validated.

It used to be an activexml error before, which did not show up as exception, but it did not work before either.

However, the 500 error is a regression.

**Comment by ChrisBr** [comment]
@adrianschroeter  #1313 will fix this!

**Comment by ChrisBr** [comment]
@adrianschroeter I guess we don't want to store empty special files, do we? So showing a flash message with a proper error message instead of the 500 should be fine?

**Comment by adrianschroeter** [comment]
this would be the old behaviour.

Not sure if we can do something better easily. Maybe providing a sceletion for these kind of files. Let's discuss this together later.
