### ISSUE TITLE
Consider using different icons for Requests in Watchlist

### ISSUE THREAD

**Issue by marxin** [openSUSE/open-build-service#13187]
Hey, Watchlist is a nice feature and it would be even better if you use different icons for Requests so that one can easily distinguish `New`, `Accepted` and other states quickly:

![Screenshot from 2022-10-06 12-47-43](https://user-images.githubusercontent.com/2658545/194294741-c90ec964-4d2f-49ac-996f-865fb971c368.png)

Right now needs to hover over `?`. You can take inspiration from GitHub listing of PRs and Issues:
https://github.com/sphinx-doc/sphinx/pulls?q=

![Screenshot from 2022-10-06 12-51-26](https://user-images.githubusercontent.com/2658545/194295025-95d0df4a-8ef8-4e4c-a7b8-237f98f293c5.png)

**Comment by saraycp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Differenciate request states in the icon](https://trello.com/c/7qOu8Eky/2747-differenciate-request-states-in-the-icon)

**Comment by hennevogel** [comment]
hey @marxin would you mind telling us what you need this for? What are you using the state for?

**Comment by ncounter** [comment]
I'm closing this as it is addressed in https://github.com/openSUSE/open-build-service/pull/14118
And JFYI: enhancement is in progress in https://github.com/openSUSE/open-build-service/pull/14119

Thank you @marxin
