### ISSUE TITLE
The obs-server VM cannot obtain an ip address in bridge mode

### ISSUE THREAD

**Issue by mstsky115** [openSUSE/open-build-service#13198]
The VM for which the obs-server mapping file is created using VMware is in bridge mode. Therefore, the VM cannot obtain an ip address or access the network. I tried a lot of ways, but I couldn't

**Comment by M0ses** [comment]
The ip address should be provided by an dhcp-server. Do you have such a service running in your network?

**Comment by mstsky115** [comment]
> 

Yes, Vmware DHCP Service.However, the VM running obs-server still cannot obtain the ip address

**Comment by M0ses** [comment]
Sorry I cannot assist to much here as I have no VMWare installation.

Have you already tried the official openSUSE 15.4 image?

(e.g. https://download.opensuse.org/distribution/leap/15.4/appliances/openSUSE-Leap-15.4-JeOS.x86_64-VMware.vmdk.xz)

**Comment by mstsky115** [comment]
> Sorry I cannot assist to much here as I have no VMWare installation.
> 
> Have you already tried the official openSUSE 15.4 image?
> 
> (e.g. https://download.opensuse.org/distribution/leap/15.4/appliances/openSUSE-Leap-15.4-JeOS.x86_64-VMware.vmdk.xz)

Thanks,I tried,but I need to create a single image  for obs-server

**Comment by mstsky115** [comment]
> 抱歉，由于我没有安装 VMWare，因此我无法提供太多帮助。
> 
> 您是否已经尝试过官方的 openSUSE 15.4 镜像？
> 
> （例如https://download.opensuse.org/distribution/leap/15.4/appliances/openSUSE-Leap-15.4-JeOS.x86_64-VMware.vmdk.xz）

Hello,Could I watch your flie information about /etc/sysconfig/network/ifcfg-eth0?

I think I might need to configure this file information

Not if it offends you

**Comment by M0ses** [comment]
It gets created here:

https://build.opensuse.org/package/view_file/OBS:Server:Unstable/OBS-Appliance/config.sh?expand=1

Line 113

BTW: Could you get console access to the create VM?

**Comment by mstsky115** [comment]
> 

Thanks! Yes,I can.

**Comment by M0ses** [comment]
Then you can have a look into `journalctl -u wickedd-dhcp4` - Maybe you find a hint - or you can restart the network with `rcnetwork` and follow the output of `journalctl`

Overall: For me it looks like a very individual problem and therefore I would like to ask you to close this GH issue and better ask for help either on IRC or on the mailinglist (https://openbuildservice.org/support/). 

There you will find a broader audience with a much broader level of expertise in different areas.

If you find a problem which needs to be fixed in the appliance, please don`t hesitate to open a new issue.

**Comment by mstsky115** [comment]
> Then you can have a look into `journalctl -u wickedd-dhcp4` - Maybe you find a hint - or you can restart the network with `rcnetwork` and follow the output of `journalctl`
> 
> Overall: For me it looks like a very individual problem and therefore I would like to ask you to close this GH issue and better ask for help either on IRC or on the mailinglist (https://openbuildservice.org/support/).
> 
> There you will find a broader audience with a much broader level of expertise in different areas.
> 
> If you find a problem which needs to be fixed in the appliance, please don`t hesitate to open a new issue.

OK,thanks
