### ISSUE TITLE
vendorchange to obs://build.opensuse.org/home:plater: not found

### ISSUE THREAD

**Issue by Reissner** [openSUSE/open-build-service#13197]
# Issue Description
zypper dup 

notifies vendor change for several packages as e.g. libliveMedia106 
openSUSE -> obs://build.opensuse.org/home:plater
But then: 

Retrieving package libliveMedia106-2022.04.26-66.4.x86_64                      (3/5), 411.2 KiB (  1.2 MiB unpacked)
Retrieving: libliveMedia106-2022.04.26-66.4.x86_64.rpm ..................................................[not found]
File './x86_64/libliveMedia106-2022.04.26-66.4.x86_64.rpm' not found on medium 'https://download.opensuse.org/repositories/home:/plater/Tumbleweed/'
Abort, retry, ignore? [a/r/i/...? shows all options] (a): 

Expected Result
============
ending command without warning or error

How to Reproduce
===============
open console, become root with `su` and issue `zypper dup`

Further Information
===============
I think nothing needed.

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.libera.chat/openSUSE-buildservice) or on the [OBS mailing list](https://lists.opensuse.org/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
