### ISSUE TITLE
Appliance ISO not installable due to some space constraint

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#13259]
# Issue Description

* Go to https://openbuildservice.org/download/
* Download "OBS 2.10 Appliance Installer" obs-server.x86_64-oem.iso; current filesize is 793772032 sha256sum 8128e3fbe7d3202ef15706caa8b24bdcc5636e966f57a7c6aef699013719202f .
* Using Tumbleweed's VirtualBox (6.1.40), create a machine with 6144 MB RAM and 60 GB disk.

Observed result
============
![1](https://user-images.githubusercontent.com/8861948/197489625-5a1d6fdf-d839-4cd4-a21b-8db8f0dde8d6.png)

Expected Result
============
Let the installer tell how much more space it needs. (The download page does not specify any immediate obvious requirements either.)

**Comment by hennevogel** [comment]
Requirements are documented in the manual

https://openbuildservice.org/help/manuals/obs-admin-guide/obs.cha.installation_and_configuration.html#_resource_planning

**Comment by adrianschroeter** [comment]
and the installer comes from kiwi. Please open an issue there if you want that information, but we won't work from OBS side on this.
