### ISSUE TITLE
"Latest" link in download repository is not updated upon new AppImage builds

### ISSUE THREAD

**Issue by adamkpickering** [openSUSE/open-build-service#13264]
Issue Description
=============

Rancher Desktop uses OBS to build packages (rpm, deb and AppImage) for Linux. There has been a problem with the last two releases of Rancher Desktop. It seems that the link in the download repository for the "latest" AppImage build is not updated when a new build is made. You can see an example here: https://download.opensuse.org/repositories/isv:/Rancher:/stable/AppImage/

Here is a screenshot showing the issue in case the download repository changes:

![image](https://user-images.githubusercontent.com/19395776/197644281-1a7891b0-4e6e-4306-83ad-dd9f70dd663e.png)

As you can see, we have a build for Rancher Desktop 1.5.1, which was last modified on August 16, 2022. We have another build for Rancher Desktop 1.6.1 that was last modified on October 6, 2022. However, the link `rancher-desktop-latest-x86_64.AppImage` was last updated on August 16, 2022. When clicked, it downloads 1.5.1, not 1.6.0, despite 1.6.0 being a month and a half newer.

When this issue was first noticed around the 1.5.1 release, I was able to update the "latest" link by going to the repository state page (i.e. https://build.opensuse.org/package/binaries/isv:Rancher:stable/rancher-desktop-1.5/AppImage), clicking "Delete all built binaries", and then clicking "Trigger rebuild". However, I'm not sure if this is actually what caused the link to be updated, because I had been messing around the `PublishFilter` flag in the project config beforehand. The problem seemed to be solved, but just now I looked and discovered that the same problem has occurred following the 1.6.0 release.

It seems that the issue is present in our development project as well: https://download.opensuse.org/repositories/isv:/Rancher:/dev/AppImage/

Screenshot in case something changes:

![image](https://user-images.githubusercontent.com/19395776/197646017-72836f3c-7b6d-4ca6-9e69-cabe1b6e32a3.png)

A final note: it seems that the "latest" zsync file hasn't been updated for even longer. This isn't causing a problem for us, but I figured it's worth noting.

Expected Result
============

The "latest" link in the download repository should point to the AppImage build that was most recently modified.

How to Reproduce
===============

I'm afraid I can't think of a way to reproduce this other than to direct you to the projects that are exhibiting the issue. Please let me know if I can provide any more information!

**Comment by krauselukas** [comment]
@adrianschroeter I guess this is related to the backend, any idea?

**Comment by darix** [comment]
This could also be a Mirrorcache issue @andrii-suse is looking into it.

**Comment by darix** [comment]
```
curl -v -L -O https://download.opensuse.org/repositories/isv:/Rancher:/stable/AppImage/rancher-desktop-latest-x86_64.AppImage
[snip]
* Issue another request to this URL: 'http://downloadcontent.opensuse.org/repositories/isv:/Rancher:/stable/AppImage/rancher-desktop-1.6.1-Build4.5.glibc2.27-x86_64.AppImage'
[snip]
```

Based on the file on disk... This looks correct. How did you test this?

**Comment by darix** [comment]
I removed some unrelated noise from the output.


```
repositories/isv:/Rancher:/stable/AppImage # ls -lrt
Jan 28  2022 rancher-desktop-0.7.1-Build2.6.glibc2.27-x86_64.AppImage
Jan 28  2022 rancher-desktop-0.7.1-Build2.6.glibc2.27-x86_64.AppImage.zsync
Feb  2  2022 rancher-desktop-1.0.1-Build7.1.glibc2.27-x86_64.AppImage
Feb  2  2022 rancher-desktop-1.0.1-Build7.1.glibc2.27-x86_64.AppImage.zsync
Mar  4  2022 rancher-desktop-1.1.1-Build3.1.glibc2.27-x86_64.AppImage
Mar  4  2022 rancher-desktop-1.1.1-Build3.1.glibc2.27-x86_64.AppImage.zsync
Mar 24  2022 rancher-desktop-1.2.1-Build4.1.glibc2.27-x86_64.AppImage
Mar 24  2022 rancher-desktop-1.2.1-Build4.1.glibc2.27-x86_64.AppImage.zsync
Apr 28 21:08 rancher-desktop-1.3.0-Build2.1.glibc2.27-x86_64.AppImage
Apr 28 21:08 rancher-desktop-1.3.0-Build2.1.glibc2.27-x86_64.AppImage.zsync
Aug 16 16:24 rancher-desktop-1.4.1-Build2.2.glibc2.27-x86_64.AppImage
Aug 16 16:24 rancher-desktop-1.4.1-Build2.2.glibc2.27-x86_64.AppImage.zsync
Oct 24 22:01 rancher-desktop-1.5.1-Build6.3.glibc2.27-x86_64.AppImage
Oct 24 22:02 rancher-desktop-1.5.1-Build6.3.glibc2.27-x86_64.AppImage.zsync
Oct 25 17:54 rancher-desktop-1.6.1-Build4.5.glibc2.27-x86_64.AppImage
Oct 25 17:54 rancher-desktop-1.6.1-Build4.5.glibc2.27-x86_64.AppImage.zsync
Oct 25 17:55 rancher-desktop-latest-x86_64.AppImage.zsync -> rancher-desktop-1.6.1-Build4.5.glibc2.27-x86_64.AppImage.zsync
Oct 25 17:55 rancher-desktop-latest-x86_64.AppImage -> rancher-desktop-1.6.1-Build4.5.glibc2.27-x86_64.AppImage
```

For stable you can see that the symlink actually points to the latest file.


```
repositories/isv:/Rancher:/dev/AppImage # ls -lrt
Apr 28 21:24 rancher-desktop-0.release1.0.1643833302.9ed007e-Build9.1.glibc2.27-x86_64.AppImage
Apr 28 21:24 rancher-desktop-0.release1.0.1643833302.9ed007e-Build9.1.glibc2.27-x86_64.AppImage.zsync
Apr 28 21:44 rancher-desktop-0.release1.1.1646420681.aaa54ec-Build4.1.glibc2.27-x86_64.AppImage
Apr 28 21:44 rancher-desktop-0.release1.1.1646420681.aaa54ec-Build4.1.glibc2.27-x86_64.AppImage.zsync
Apr 28 21:44 rancher-desktop-0.release1.2.1648074053.97d211b-Build4.1.glibc2.27-x86_64.AppImage
Apr 28 21:44 rancher-desktop-0.release1.2.1648074053.97d211b-Build4.1.glibc2.27-x86_64.AppImage.zsync
Apr 28 21:47 rancher-desktop-0.release1.3.1651103087.b65193d-Build3.1.glibc2.27-x86_64.AppImage
Apr 28 21:47 rancher-desktop-0.release1.3.1651103087.b65193d-Build3.1.glibc2.27-x86_64.AppImage.zsync
Jun  8 20:19 rancher-desktop-0.release1.4.1654642978.84415ef-Build2.1.glibc2.27-x86_64.AppImage
Jun  8 20:19 rancher-desktop-0.release1.4.1654642978.84415ef-Build2.1.glibc2.27-x86_64.AppImage.zsync
Aug 15 23:07 rancher-desktop-0.release1.5.1660242706.b35e3a9-Build8.3.glibc2.27-x86_64.AppImage
Aug 15 23:07 rancher-desktop-0.release1.5.1660242706.b35e3a9-Build8.3.glibc2.27-x86_64.AppImage.zsync
Oct 21 00:05 rancher-desktop-0.release1.6.1666309696.b2d8bdd-Build9.1.glibc2.27-x86_64.AppImage
Oct 21 00:05 rancher-desktop-0.release1.6.1666309696.b2d8bdd-Build9.1.glibc2.27-x86_64.AppImage.zsync
Oct 25 21:59 rancher-desktop-9.main.1666734258.326348e-Build697.1.glibc2.27-x86_64.AppImage
Oct 25 21:59 rancher-desktop-9.main.1666734258.326348e-Build697.1.glibc2.27-x86_64.AppImage.zsync
Oct 25 21:59 rancher-desktop-latest-x86_64.AppImage.zsync -> rancher-desktop-0.release1.6.1666309696.b2d8bdd-Build9.1.glibc2.27-x86_64.AppImage.zsync
Oct 25 21:59 rancher-desktop-latest-x86_64.AppImage -> rancher-desktop-0.release1.6.1666309696.b2d8bdd-Build9.1.glibc2.27-x86_64.AppImage
```

For dev it seems to ignore the `9.main` version of the package. While the symlink was updated at the same time as publishing the main image.

**Comment by darix** [comment]
@hennevogel pointed out in a discussion that https://build.opensuse.org/projects/isv:Rancher:dev/prjconf has some `Release:` config which might affect the whole sorting and publishing of static links.

**Comment by andrii-suse** [comment]
> This could also be a Mirrorcache issue @andrii-suse is looking into it.

Just fyi: I've looked from MirrorCache point of view and have fixed unrelated issue, but this one should happen before Web Services could mess things up (during publishing?).

**Comment by adamkpickering** [comment]
@darix it seems you're looking at the current state of things, which is now fine for stable. When I created this issue I thought this might happen - that's why I posted the screenshots. If you look at the last modified column you can see that something is fishy.

I was able to get the stable branch into a better state by deleting the builds and triggering a rebuild as I described in the original issue description. It doesn't work every time - I tried it two days ago (when I made this issue), and it didn't work. But I tried it again yesterday morning and it appears to have worked.

> @hennevogel pointed out in a discussion that https://build.opensuse.org/projects/isv:Rancher:dev/prjconf has some Release: config which might affect the whole sorting and publishing of static links.

What is `Release:` for? It seems there is no information on it in the [project config reference](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.prjconfig.html#sec.prjconfig.syntax). Do you know where I could find info on this? How could this affect the sorting and publishing of static links?

**Comment by hennevogel** [comment]
> What is Release: for?

https://en.opensuse.org/openSUSE:Build_Service_prjconf#Release

**Comment by ml8mr** [comment]
Did we ever chase down what caused this discrepancy? We're in the same state again now, and can't find any reason why the latest link wouldn't have been updated to point to the latest release.

**Comment by adrianschroeter** [comment]
this is correct on the obs server side, it needs to be checked on the download server. Sorry, I have no access there (anymore).

Better open a ticket via admin@opensuse.org as this is not an OBS server thing, sorry.

**Comment by adrianschroeter** [comment]
k, rudi pointed me to the issue, taking it back.

**Comment by adrianschroeter** [comment]
your repo should be fine now, fix is coming here: https://github.com/openSUSE/open-build-service/pull/16747
