### ISSUE TITLE
Can't release Factory anymore 

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#1326]
OBS managed to break the Tumbleweed release process - we use for more than a year now.

POST /source/openSUSE:Factory:Live/kiwi-image-livecd-gnome?cmd=release&setrelease=Snapshot20151030

gives 400. Looking at the log, this 400 is coming from this backend call generated:

```
/source/openSUSE%3AFactory%3AToTest/kiwi-image-livecd-gnome?cmd=copy&user=coolo&oproject=openSUSE%3AFactory%3ALive&opackage=kiwi-image-livecd-gnome&comment=Release+from+openSUSE%3AFactory%3ALive+%2F+kiwi-image-livecd-gnome&expand=1&withvrev=1&noservice=1&freezelink=1&withacceptinfo=1
```

So I assume the introduction of freezelink=1 is guilty - but it's just guessing.

**Comment by coolo** [comment]
@DimStar77 @nilxam - just in case you wonder...

**Comment by adrianschroeter** [comment]
yes, freezing should only happen on release when link target is equal to release target. Will add a check ...

**Comment by adrianschroeter** [comment]
fixed on server and git
