### ISSUE TITLE
How do I use ccache on obs-server 2.10

### ISSUE THREAD

**Issue by mstsky115** [openSUSE/open-build-service#13297]
How do I configure ccache to be used without upgrading obs-server 2.11?

**Comment by dmarcoux** [comment]
This issues tracker is only for issues related to the source code of OBS. For anything related to hosting OBS, I suggest using [IRC](irc://irc.libera.chat/openSUSE-buildservice) or the [mailing list](https://lists.opensuse.org/archives/list/buildservice@lists.opensuse.org/).
