### ISSUE TITLE
Sudo fails while building for ArchLinux

### ISSUE THREAD

**Issue by copyme** [openSUSE/open-build-service#1329]
I cannot build packages on ArchExtra via OBS because of sudo problems:

[  138s] sudo: no tty present and no askpass program specified
[  138s] ==> ERROR: 'pacman' failed to install missing dependencies.

My project: https://build.opensuse.org/package/show/home:copyme:DGtal/DGtal

**Comment by adrianschroeter** [comment]
1. This is not an OBS code problem, but a config decision
2. The default config of all distros in build.opensuse.org is not allowing to run sudo

**Comment by adrianschroeter** [comment]
also, you would not have network access at all inside of the build environent. It would be a security issue and contradicts the idea of having reproducable builds.

**Comment by copyme** [comment]
@adrianschroeter Wait, even sudo is prohibited (which seems fair), there must be a way to resolve dependencies. It works for openSUSE,  Fedora, etc.

**Comment by adrianschroeter** [comment]
you need to write dependencies into your build description, the PKGBUILD file in the depends= or makedepends= line. OBS will parse that line and install the required packages to build env.

**Comment by copyme** [comment]
@adrianschroeter I have that. Nevertheless after sometime I've re-trigged rebuild and there was no problem any more. Thanks.
