### ISSUE TITLE
scm source service failures get send to the wrong email address

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#13336]
# SCM source service failures get send to the wrong account email

I have created a project managed via the SCM under my private account https://build.opensuse.org/users/defolos, yet the source service failures for https://build.opensuse.org/project/show/home:defolos:BCI:CR:Tumbleweed get delivered to my corporate account (https://build.opensuse.org/users/dancermak)

Expected Result
============
The emails should be sent to the account to whom the project belongs

Further Information
===============
projects where this occurred:
* https://build.opensuse.org/project/show/home:defolos:BCI:CR:Tumbleweed
* https://build.opensuse.org/project/show/home:defolos:BCI:CR:SLE-15-SP4

**Comment by dcermak** [comment]
Well, the project in question uses the SCM bridge, so I guess yes?

**Comment by dmarcoux** [comment]
I wasn't sure from only reading your issue description. Thanks for the clarification.

**Comment by dcermak** [comment]
As I said, I am not sure if this is **really** related to the scmsync feature though, the issue is that the emails get send to the wrong account.

**Comment by hennevogel** [comment]
The OBS for sure does not know about the connection between the accounts so this can't be the reason. Your corporate account is maintainer of this project too, that is the reason I guess.

**Comment by hennevogel** [comment]
And `dancermak` has subscriptions for service failed while `defolos` does not.

**Comment by dcermak** [comment]
I think the issue is that I setup the webhook to trigger the branching as `dancermak` and not as `defolos`.
