### ISSUE TITLE
project_command_freezelink appears to be completely unused

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#13337]
The function `project_command_freezelink` is not used anywhere in the repo:
https://github.com/openSUSE/open-build-service/blob/aec807c034c94f60cdedc8e1b0c79edb87069c87/src/api/app/controllers/source_controller.rb#L491

Can it be removed?

**Comment by hennevogel** [comment]
I'm not sure how you got to that conclusion but it's wrong :-)
