### ISSUE TITLE
SCM/CI terminology - "branch a package" ?

### ISSUE THREAD

**Issue by abitrolly** [openSUSE/open-build-service#13334]
As a person coming from GitHub/GitLab I find OBS terminology unclear. It would be nice to have all workflow steps link to corresponding terminology here.

https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html#sec.obs.obs_scm_ci_workflow_integration.setup.obs_workflows.steps

* Branch a package in a project (branch_package).

What is "branch a package"?

* Link a package to a project (link_package).

Why I need to link packages to projects? Why packages are not linked to GitHub projects automatically?

* Configure repositories/architectures for a project (configure_repositories)

The GitHub repository is already sending web hook even? Why is it needed?

* Rebuild a package (rebuild_package)

Ok. But why rebuild? Why not just `build_package`?

* Set flags for projects, packages, repositories or architectures (set_flags)

Flags?

* Trigger services of a package (trigger_services)

Services?

---

I am just helping with https://github.com/bleachbit/bleachbit/issues/1171 I don't have access to the repository to setup anything, so I just need to write down the workflow without any experiments, and I can't. A shame, given that I have some first hand OBS experience and even committed something to `osc` https://github.com/openSUSE/osc/commits?author=abitrolly

**Comment by dmarcoux** [comment]
All of the OBS terms are listed in the [User Guide](https://openbuildservice.org/help/manuals/obs-user-guide/). As an example, this is the section about [branching a package](https://openbuildservice.org/help/manuals/obs-user-guide/art.obs.bg.html#sec.obsbg.uc.branchprj). Please refer to that guide for answers to your questions.

**Comment by dmarcoux** [comment]
It does... The text below is taken from the link I shared earlier:

>  There are different reasons to branch a package:
>
> - To modify the source code, building it, trying the effect of the changes, and submitting back changes to the original project. Usually, you use this workflow when you do not have write permissions for a project.
>
> - To make changes without affecting the original project.
>
> - To apply temporary changes to try out a different path of development.

**Comment by abitrolly** [comment]
@dmarcoux in the context of CI/CD, `project` is a GitHub/GitLab project, `branch` is a `git` branch on GitHub/GitLab, `package` is a compiled binary.

**Comment by dmarcoux** [comment]
I am well aware of this, but you asked about the OBS terminology, so this is why I shared the [User Guide](https://openbuildservice.org/help/manuals/obs-user-guide/) with you. Words can have different meanings depending on the context. This won't change whether you like it or not. The next step is you either learn this terminology or don't. It's all in your hands. Arguing further won't change the outcome.

**Comment by abitrolly** [comment]
I don't see your point. I am trying to tell that people coming to the user guide to setup OBS as a CI/CD for testing Linux builds have only hard way of learning the terminology, because CI/CD guide doesn't help them in any way. Maybe you assume that people should read the User Guide from start to finish like in the old good days of Atari games, but my point is that modern people don't work this way. If you want posts like https://openbuildservice.org/2022/09/21/trigger-workflow-rollout/ to reach broader audience than existing OBS users, this content need to be adopted to these people.
