### ISSUE TITLE
Cant add custom dependencies to my packages

### ISSUE THREAD

**Issue by a51kot** [openSUSE/open-build-service#13362]
My dependencies've built well in OBS   
https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing/opencolorio1

But my packages  ant detect my custom dependencies (aur packages that i-ve  built on my obs stance in order to build these packages)  

https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing/openfx-arena

So it still reports unresovable as if i aint've built opencolorio1

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.libera.chat/openSUSE-buildservice) or on the [OBS mailing list](https://lists.opensuse.org/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
