### ISSUE TITLE
status reports to gitlab.com are rejected / invalid

### ISSUE THREAD

**Issue by JanZerebecki** [openSUSE/open-build-service#13377]
# Issue Description

I tried setting up a workflow for merge requests on Gitlab, but it seems the resulting status reports are rejected by Gitlab.

The request parameters show (see below) do not look like the API docs: https://docs.gitlab.com/ee/api/commits.html#post-the-build-status-to-a-commit

Expected Result
============
Status reports show up on the merge request.

How to Reproduce
===============
1. setup workflow on merge request 
2. open a merge request
3. check workflow run that was triggered

Further Information
===============
Tested with https://gitlab.com/source-security/git-verify/-/merge_requests/3 (webhook was disabled afterwards, because I'm also missing server side obs-service-cargo_vendor)
Run was https://build.opensuse.org/my/tokens/6632/workflow_runs/80948#tab-pane-scm-reports-tab-content80948

Response body
`Fail`
`Failed to report back to GitLab: Request forbidden.`
Request parameters
```
{
  "api_endpoint": "https://gitlab.com",
  "target_repository_full_name": null,
  "commit_sha": "467c9e645e85345c790593eb2933469231a749f4",
  "state": "pending",
  "status_options": {
    "context": "OBS:  - /",
    "target_url": null
  }
}
```

Response body
`Fail`
`Failed to report back to GitLab: Bad request. Please modify your request and try again.`
Request parameters
```
{
  "api_endpoint": "https://gitlab.com",
  "target_repository_full_name": null,
  "commit_sha": "467c9e645e85345c790593eb2933469231a749f4",
  "state": "failure",
  "status_options": {
    "context": "OBS: git-verify - openSUSE_Leap_15.3/aarch64",
    "target_url": "https://build.opensuse.org/package/show/home:GeckoGoldDust:CI:target:security:git-verify:source-security:git-verify:PR-3/git-verify"
  }
}
```

**Comment by dmarcoux** [comment]
With a quick glance, this looks `"target_repository_full_name": null,` really weird in the request parameters. For GitLab, we should have `project_id` instead as defined here:

https://github.com/openSUSE/open-build-service/blob/29fe2bfa66335797cce355f8f70500685056e507/src/api/app/services/gitlab_status_reporter.rb#L14-L18

**Comment by JanZerebecki** [comment]
Seems the exception handler always only logs the github options: 
https://github.com/openSUSE/open-build-service/blob/48b1002a526ab7a8a1ed1ef4c2bbbe12edd923ba/src/api/app/services/scm_exception_handler.rb#L70

**Comment by hennevogel** [comment]
We did what we could to be able to reproduce this next time it happens.. closing.
