### ISSUE TITLE
make obs-service-cargo_vendor available on build.opensuse.org

### ISSUE THREAD

**Issue by JanZerebecki** [openSUSE/open-build-service#13378]
Please make https://github.com/openSUSE/obs-service-cargo_vendor available for server side use on build.opensuse.org .

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

For the instance you mention the admins are reachable at admin@opensuse.org or via ticket on https://wiki.suse.net/index.php/Trello_guidelines

Thank you for your consideration.
