### ISSUE TITLE
OBS gives build errors 

### ISSUE THREAD

**Issue by a51kot** [openSUSE/open-build-service#13389]
I got this error 
==> ERROR: Cannot find the gzip binary required for compressing man and info pages.

even when i declare gzip+ xz+zip+minizip+unzip as builddeps 

what should i do  
https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing/thunderbird-beta

**Comment by danidoni** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are not a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.libera.chat/openSUSE-buildservice) or on the [OBS mailing list](https://lists.opensuse.org/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members.

Thank you for your consideration.
