### ISSUE TITLE
OBS stays stalled at finished  

### ISSUE THREAD

**Issue by a51kot** [openSUSE/open-build-service#13390]
i-ve compiled some stuff

obs calls it a success *finished + package should jmp to archpkgs)  
but it remains stalled at finished + i cant get my new packages

its a bug

https://build.opensuse.org/package/live_build_log/home:Area51Kacz:branches:home:ungoogled_chromium:testing/qt4/Arch/x86_64

https://build.opensuse.org/package/live_build_log/home:Area51Kacz:branches:home:ungoogled_chromium:testing/firefox-beta/Arch/x86_64

**Comment by danidoni** [comment]
I don't understand, the packages are there: https://build.opensuse.org/package/binaries/home:Area51Kacz:branches:home:ungoogled_chromium:testing/qt4/Arch

**Comment by danidoni** [comment]
Package builds succeeded:
![image](https://user-images.githubusercontent.com/2650/202405742-d614fdb1-2ab8-43ac-ac07-c85e35eaa6e4.png)

**Comment by adrianschroeter** [comment]
it is not a bug, OBS is a batch system to handle any kind of load. But it means operations can take longer when a high load exists.
