### ISSUE TITLE
Regression: OBS does not install gzip when building Arch Linux packages, which breaks builds

### ISSUE THREAD

**Issue by antermin** [openSUSE/open-build-service#13403]
# Issue Description
gzip, which is part of the `base-devel` group, and required by the `base` package on Arch Linux, should be already installed when building packages.

https://wiki.archlinux.org/title/PKGBUILD says:
> The group [base-devel](https://archlinux.org/groups/x86_64/base-devel/) is assumed to be already installed when building with makepkg. Members of this group should not be included in makedepends array.

Recently, for unknown reason, OBS no longer installs gzip (unless gzip is explicitly specified in makedepends array). Arch Linux package builds thus fail with `ERROR: Cannot find the gzip binary required for compressing man and info pages.`.

Expected Result
============
OBS should make sure that:
1. All dependencies required by the `base` package are installed. (`base` is the "minimal package set to define a basic Arch Linux installation".)
2. All members in the `base-devel` group are installed.

How to Reproduce
===============
1. Try to build an Arch Linux package, e.g. [virtualbox-host-modules-arch](https://github.com/archlinux/svntogit-community/blob/packages/virtualbox-host-modules-arch/trunk/PKGBUILD)
2. View the build log

Further Information
===============
* OBS instance: Official instance (build.opensuse.org)
* I have searched Arch Linux homepage and Arch Linux Forums, and I cannot find any changes / issue reports on the Arch Linux side. Therefore, I believe this is a problem in OBS.
* Another user has reported similar issue in #13389, but @danidoni quickly closed it because "Github issues are not a way to request support from us." However, I believe we are indeed "tracking issues in the source code" as this is a regression. OBS previously has installed the correct set of dependencies, but now it appears one of the dependencies is missing.

**Comment by danidoni** [comment]
Sorry, but I will have to close this as well. There's nothing we can do about this in the OBS source code.

What you are reporting here is a "packaging issue".

You should forward your issue to [the packaging mailinglist](https://lists.opensuse.org/archives/list/packaging@lists.opensuse.org/). I'm sure you will get help regarding why this package is not building.

Thanks for your consideration.

**Comment by luc14n0** [comment]
Actually this is not a packaging issue. Arch Linux builds were working fine -- obviously `gzip` was, somehow, being pulled before -- and now it's not.

Let's take `osc` from **openSUSE:Tools** project as an example. Currently it's on version **0.182.0**. The last change to `PKGBUILD` was this:

``` patch
@@ -1,5 +1,5 @@
 pkgname=osc
-pkgver=0.181.0
+pkgver=0.182.0
 pkgrel=0
 pkgdesc="Open Build Service client"
 arch=('x86_64')
```

That's from revision [371](https://build.opensuse.org/package/rdiff/openSUSE:Tools/osc?linkrev=base&rev=371#revision_details_2). It built fine, since we have [binaries](https://build.opensuse.org/package/binaries/openSUSE:Tools/osc/Arch) for it.

Than something changed and now it fails with:

```
warning: /etc/pacman.conf installed as /etc/pacman.conf.pacnew
now finalizing build dir...
SIOCSIFADDR: File exists
Running build time source services...
Preparing sources...
==> ERROR: Cannot find the gzip binary required for compressing man and info pages.
failed to prepare sources
```

See the [job history](https://build.opensuse.org/packages/osc/job_history/openSUSE:Tools/Arch/x86_64).

In **[Arch:Core](https://build.opensuse.org/project/show/Arch:Core)** project we can see the wary red triangle, meaning something's not right and in the [project configuration](https://build.opensuse.org/projects/Arch:Core/prjconf) we can see that `gzip` is no longer a `Preinstall` requirement -- that is, assuming this is how `gzip` was being there before for Arch builds without the need to explicitly requiring it.

**Comment by danidoni** [comment]
> Actually this is not a packaging issue. Arch Linux builds were working fine -- obviously `gzip` was, somehow, being pulled before -- and now it's not.

Thanks for the explanation @luc14n0!

**Comment by danidoni** [comment]
I've been told that you can ask for help in the [Factory mailing list](https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/)

**Comment by DimStar77** [comment]
> I've been told that you can ask for help in the [Factory mailing list](https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/)

Factory mailing list deals with openSUSE distributions in development (i.e. Tumbleweed, MicroOS, Leap, 'future'). Arch building is not related to any openSUSE distribution -> so, no, that list won't be useful for this issue

**Comment by danidoni** [comment]
> > I've been told that you can ask for help in the [Factory mailing list](https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/)
> 
> Factory mailing list deals with openSUSE distributions in development (i.e. Tumbleweed, MicroOS, Leap, 'future'). Arch building is not related to any openSUSE distribution -> so, no, that list won't be useful for this issue

Okay, my bad then. Sorry for the noise.

**Comment by DimStar77** [comment]
`osc rdiff -r 36:37 Arch:Core/_project`

That eliminated `-Required: base-devel` from the prjconf, which, reading this ticket, seems like ARch packagers would rely on.

OTOH that happened in September 2020; feels a bit long to be the relevant change

**Comment by luc14n0** [comment]
> What Luciano said is valuable, try the Build Service mailing list

I should've reported back, as I had taken a look at the **[Pulse](https://build.opensuse.org/projects/Arch:Core/pulse)** of Arch:Core and, just like Dominique said, there's no recent changes to the project configuration that would result in the problem we're seeing.

Also, I'm gonna propose a PR to our **obs-build** repo that should fix this problem.

**Comment by luc14n0** [comment]
> `osc rdiff -r 36:37 Arch:Core/_project`
> 
> That eliminated `-Required: base-devel` from the prjconf, which, reading this ticket, seems like ARch packagers would rely on.
> 
> OTOH that happened in September 2020; feels a bit long to be the relevant change

I don't know if back in 2020 things were different, but nowadays `base-devel` is a package _group_, so if we use `Required: base-devel` we get a **unresolvable** :disappointed:

**Comment by hennevogel** [comment]
This is not a code issue. You will need to contact the maintainers of build.o.o, they are reachable at admin@opensuse.org

**Comment by mlschroe** [comment]
I've added 'gzip' to the support packages list.

**Comment by mlschroe** [comment]
Regarding base-devel: the package list of a group is coming from the packages itself, right? I.e. "base-devel" is all packages that have "base-devel" in their groups attribute? If that's the case then we can't really use it in OBS, nothing looks at the "groups" definition.
(It's also kinda weird that any package from anywhere can make itself be a part of the "base-devel" set)

**Comment by luc14n0** [comment]
You got that part almost right, the list is defined in the group itself - it's not a package.

I think there's a "smart" way we could go about this, @mlschroe. We could make a meta package containing all the packages from the `base-devel` package group, but only packages that are really useful in our build environment. This way it's easier to add/exclude packages from it, a package maintainer could take care of this, and no need to tweak the project configuration - regarding this matter -, and we could keep a changelog, something that project configurations also have, but are well hidden from the most users. I could create this meta package, if it's of interest.
