### ISSUE TITLE
Internal Server Error when displaying delete request

### ISSUE THREAD

**Issue by coogor** [openSUSE/open-build-service#13414]
Issue/Feature Description
====================
Admin-generated delete request:
Visit https://build.opensuse.org/request/show/1036863

Description:
This is a humble request to remove this project.
...

DR was accepted, clicking on Request (e.g. in notification section) throws up 500: Internal server error

Expected Result
============
display DR

How to Reproduce
===============
Click on DR

**Comment by dmarcoux** [comment]
This is happening for the beta version of this page, sorry for that @coogor. We're looking into this.

**Comment by dmarcoux** [comment]
_Note for developers_

This is the [Errbit report](https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/637ceb7984bf46052270e696) for this issue.
