### ISSUE TITLE
Addressing potential EULA issues when using source services

### ISSUE THREAD

**Issue by lawmurray** [openSUSE/open-build-service#13432]
**Is your feature request related to a problem? Please describe.**
Packages may have external build dependencies that can be downloaded with the source services feature. One such example is CUDA and its `nvcc` compiler, used for compiling code to run on Nvidia GPUs. When these build dependencies are not open source, however, the `_service:` links created by OBS in the web interface may violate that build dependency's EULA on redistribution.

**Describe the solution you'd like**
Two suggestions that might address the issue:

1. A `mode="external"` or the like that changes `_service:` links in the web interface to point to the original URL, rather than the downloaded file. In the case of CUDA, for example, the link would be back to Nvidia's site, which would not violate the EULA.

2. A `mode="hidden"` or the like that allows `_service:` links to be hidden entirely.

In the case of CUDA, at least, there appears to be no issue with a build worker downloading the CUDA installer from Nvidia via the source services feature and using it to build a package. It is even within the EULA to redistribute certain parts of CUDA within that package. It is not permitted to redistribute the whole CUDA installer, however.

**Describe alternatives you've considered**
* Having the user build the package themselves.
* Using a private deployment of OBS.
* Using `mode="buildtime"`. From the [documentation](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.source_service.html#sec.obs.sserv.mode), it seems that this would download the file on each build (in the case of CUDA it is a bit large for doing this: 4.1 GB). It also does not work when build workers are running in secure mode, as on https://build.opensuse.org.

**Additional context**
* Some discussion on the [mailing list](https://lists.opensuse.org/archives/list/buildservice@lists.opensuse.org/thread/CBDPWMOYAF66TJYYDPAGBLNBB4IXMBSL/).
* The CUDA [EULA](https://docs.nvidia.com/cuda/eula/index.html#distribution-requirements) on redistribution.

**Comment by hennevogel** [comment]
You are only allowed to upload software to build.opensuse.org that has an OSI approved open source license and has no other legal implications (like an EULA). We are not going to build features to circumvent this :-)

**Comment by lawmurray** [comment]
Thanks @hennevogel. To be clear, this suggestion is meant for software that is open source, of course, but that to enable certain features (e.g. GPU support) may need to be built with a compiler that is not open source (in this case CUDA's `nvcc`). Still, I understand this is not something that you wish to support on build.opensuse.org, and appreciate the reply (and I do wish Nvidia would open source CUDA...).
