### ISSUE TITLE
Changes tab isn't working anymore

### ISSUE THREAD

**Issue by perlpunk** [openSUSE/open-build-service#13443]
# Issue Description

In this request https://build.opensuse.org/request/show/1038718#tab-pane-changes the Changes tab doesn't work, it says "Crunching the latest data" forever...

And it seems to happen for other requests as well

**Comment by dmarcoux** [comment]
This happens inside or outside the beta. Somehow the `loadChanges()` JS function should be called whenever clicking on the button. That function was removed in 2f23bedd1f100e6dcd7ac1ab23f3153982755b29 as part of #13029.

![load-changes](https://user-images.githubusercontent.com/1102934/204356672-cc87ee67-d813-48db-b5f6-dfc397607363.gif)

**Comment by eduardoj** [comment]
We have found that in this specific request there is an error when trying to uncompress the `.tar.xz` file. This is what we get from the API call:

```
The diff call for home:cdywan:branches:devel:languages:python/python-openqa_client failed: tar: exit status 512
```

This is not correctly shown in the UI. We are working on a fix on this.

**Comment by hennevogel** [comment]
So this is "just" a problem with this particular request, dropped the priority label.

**Comment by eduardoj** [comment]
> The 404 response could still be reproduced, with the same API call (`POST /request/1038718?cmd=diff`). It sounds to me that the backend should answer with another HTTP status, different to 404, for a `failed: tar: exit status 512` error.
> 
> An alternative could be to rescue from `Backend::NotFoundError` exceptions, in the [method source_diff](https://github.com/openSUSE/open-build-service/blob/81831ae612b29cc091367a7484716a8f802f8594/src/api/app/models/bs_request_action/differ/for_source.rb#L59-L65). But I still don't think this would be the right approach.
> 
> Could this be checked in the backend? CC: @openSUSE/obs-backend

I was wrong. A `Backend::NotFoundError` inherits from `Backend::Error`: https://github.com/openSUSE/open-build-service/blob/8cad6c83f9a462b94d4e4fdd426c05fb7c167a08/src/api/app/lib/backend/not_found_error.rb#L1-L3

This is not a problem in the backend.

**Comment by rubhanazeem** [comment]
This issue is no longer occurring. Closing it now! If it happens anywhere else, please feel free to reopen it.

**Comment by eduardoj** [comment]
Just for the record, the answer from the backend returns a different error:
```
> osc api -X POST "/request/1038718?cmd=diff"
Server returned an error: HTTP Error 404: Not Found
The diff call for home:cdywan:branches:devel:languages:python/python-openqa_client failed: bad link: conflict in file _service
>
```

... and the Changes tag correctly shows the error message: 

```
The diff call for home:cdywan:branches:devel:languages:python/python-openqa_client failed: bad link: conflict in file _service
```
