### ISSUE TITLE
3 methods to calculative activity in app/models/package.rb 

### ISSUE THREAD

**Issue by darix** [openSUSE/open-build-service#13450]
```
def update_activity
def self.activity_algorithm
def activity
```

why do we need all 3?

**Comment by hennevogel** [comment]
- `update_activity` is the method setting the position in the activity index
- `self.activity_algorithm` is returning a string of SQL used in to fetch objects by activity in `StatisticsController`
- `activity` is the same as `self.activity_algorithm` but in Ruby. It's used to render Package activity in the API
