### ISSUE TITLE
Improve management of status messages for admin/staff

### ISSUE THREAD

**Issue by lrupp** [openSUSE/open-build-service#13458]
**Is your feature request related to a problem? Please describe.**

At the moment, I see the following Admin News when visiting https://build.opensuse.org/  :

![Admin-News_when_logged_out](https://user-images.githubusercontent.com/3956279/204768180-5e8eb525-0660-419d-9516-bbcd92e655dd.png)

You might notice the 3 months old message about "reduced availability of workers" at the top.

I think, this message is not useful any longer and should either be removed or edited/updated. 

So  I log in to the system and get presented the following homepage:

![Admin-News_after_lgging_in](https://user-images.githubusercontent.com/3956279/204768522-379e3b21-ca14-45bf-9d3e-d2b76f2085e0.png)

-> the 3 month old message is gone. And while I can edit or delete the current messages, there is no obvious way for me to manage all (>600, if I'm correct) Admin news. If I check the "Configuration" menu option, I see a "Notifications" (https://build.opensuse.org/notifications) entry, but this leads me to the wrong kind of notifications/news.

**Describe the solution you'd like**

I like to request an additional tab in the "Configuration" menu labelled "Admin News" (or similar), which would allow me to edit/update/delete all administrative news of the page.

**Describe alternatives you've considered**

An alternative might be a "more" button on the homepage in the "News" are (see the screenshots above), which would allow to see more Admin news - but I think a separate menu entry might make more sense.

**Comment by dmarcoux** [comment]
Hey Lars, I can see how this is confusing. The status messages to be displayed will be different depending on various conditions. So in your examples, when you're not logged in, it differs from what you see after logging in.

We can definitely improve this. Having a new tab in the _Configuration_ page to manage status messages is a good idea, especially since there are a lot of status messages. Managing them directly on the homepage would be cumbersome.

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve management of status messages for Admin/Staff](https://trello.com/c/0BGnqxZ1/2077-improve-management-of-status-messages-for-admin-staff)

**Comment by dmarcoux** [comment]
Hey @lrupp,

let us know what you think of the `Manage News` page. It's accessible from the home page by clicking on `News` and on the `Configuration` page. To delete the news regarding the reduced availability of workers, you would have to select the `All users` communication scope.

**Comment by lrupp** [comment]
Hey @dmarcoux 
The new feature looks very promising: exactly what I needed/ wanted! :-)

I already moved the message in question to the "logged in" users only. Maybe it's time to think about another queue for obsolete (trash?) messages someone (like me) wants to keep for reference?  ;-)

But regarding the issue here, thanks for fixing! :-)

**Comment by dmarcoux** [comment]
> Maybe it's time to think about another queue for obsolete (trash?) messages someone (like me) wants to keep for reference? ;-)

I created an issue for this, it's #13658.
