### ISSUE TITLE
[dist issue] Server:Unstable obs-api cannot be installed during upgrade from 2.6 to Unstable

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/open-build-service#1347]
After some judicious poking with @ChrisBr to figure out the cause of #1273, I discovered that the reason I have no syntax highlighting is because when upgrading from `Server:2.6` to `Server:Unstable`, the `obs-api` package does not get updated.

When attempting to `zypper up obs-api`, I get the following output:
```
obs-server:~ # zypper up obs-api
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: obs-api-2.6.51.git20151105.818f056-1424.1.noarch requires rubygem(ruby:2.2.0:rake) = 10.4.2, but this requirement cannot be provided
  uninstallable providers: ruby2.2-stdlib-2.2.2-19.1.x86_64[OBS:Server:Unstable]
 Solution 1: install ruby2.1-stdlib-2.1.6-34.4.x86_64 (with vendor change)
  openSUSE  -->  obs://build.opensuse.org/OBS
 Solution 2: do not install obs-api-2.6.51.git20151105.818f056-1424.1.noarch
 Solution 3: break obs-api-2.6.51.git20151105.818f056-1424.1.noarch by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/3/c] (c): c
obs-server:~ #
```

From my untrained eyes, it looks like parts of `Server:Unstable` are being built against ruby 2.1 instead of ruby 2.2, which breaks the upgrade path.

A more general `zypper up` yields similar results:
```
obs-server:~ # zypper up
Loading repository data...
Reading installed packages...

The following 51 package updates will NOT be installed:
  createrepo libruby2_1-2_1 nodejs OBS-Addon-release obs-api perl-Socket-MsgHdr qemu-linux-user ruby ruby2.1 ruby2.1-rubygem-actionview-4_1 ruby2.1-rubygem-acts_as_list ruby2.1-rubygem-arel
  ruby2.1-rubygem-capybara_minitest_spec ruby2.1-rubygem-chunky_png ruby2.1-rubygem-clockwork ruby2.1-rubygem-codemirror-rails ruby2.1-rubygem-dalli ruby2.1-rubygem-database_cleaner
  ruby2.1-rubygem-escape_utils ruby2.1-rubygem-execjs ruby2.1-rubygem-flog ruby2.1-rubygem-font-awesome-rails ruby2.1-rubygem-kaminari ruby2.1-rubygem-kgio ruby2.1-rubygem-mail ruby2.1-rubygem-mime-types
  ruby2.1-rubygem-multi_json ruby2.1-rubygem-pkg-config ruby2.1-rubygem-poltergeist ruby2.1-rubygem-pundit ruby2.1-rubygem-rack-mini-profiler ruby2.1-rubygem-rails-4_1 ruby2.1-rubygem-rails_tokeninput
  ruby2.1-rubygem-rdoc ruby2.1-rubygem-redcarpet ruby2.1-rubygem-riddle ruby2.1-rubygem-ruby-ldap ruby2.1-rubygem-ruby_parser ruby2.1-rubygem-sass-rails ruby2.1-rubygem-sexp_processor
  ruby2.1-rubygem-simplecov ruby2.1-rubygem-sprite-factory ruby2.1-rubygem-thinking-sphinx ruby2.1-rubygem-thread_safe ruby2.1-rubygem-timecop ruby2.1-rubygem-uglifier ruby2.1-rubygem-unicorn
  ruby2.1-rubygem-webmock ruby2.1-rubygem-websocket-driver ruby2.1-stdlib ruby-common

The following product update will NOT be installed:
  "openSUSE Build Service Add on"

Nothing to do.
obs-server:~ #
```

**Comment by hennevogel** [comment]
You can just accept the vendor change. And in general, if you are not able to cope with things like this you really shouldn't use `:Unstable`

**Comment by Conan-Kudo** [comment]
@hennevogel Well, I didn't know I can accept the vendor change!

**Comment by adrianschroeter** [comment]
:Unstable is built against ruby 2.2, while OBS:Server:2.6 was built against ruby 2.1. 
We should add some hint in the packages to make updating easier though.

**Comment by hennevogel** [comment]
@Conan-Kudo don't get me wrong, I don't have anything against you using :Unstable but it's called :Unstable for a reason: It's unstable :-)

**Comment by darix** [comment]
the whole :unstable discussion is mood, because as soon as you release 2.7 or 2.8 the same issue would hit also people upgrading there.

**Comment by Conan-Kudo** [comment]
@darix Exactly. Broken upgrades should be fixed regardless. :)

**Comment by Conan-Kudo** [comment]
@hennevogel: So I actually did do the vendor change, and my OBS instance is pretty much broken now. Attempts to view projects cause internal server errors, and I've gone from 8 build roots to zero. Another system now gives me HTTP 403 errors when attempting to access the system.

@adrianschroeter Please fix the OBS:Unstable repository so that I can safely upgrade, as I really don't want to be stuck in this halfway upgraded state on my production system.
