### ISSUE TITLE
Missing centos-release for CentOS 5 environment

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/open-build-service#1349]
I've been building software to the EL5 target on OBS, and I had software fail to build because during the compilation, it cannot properly detect things because centos-release isn't installed as part of the environment. This is not a problem on CentOS 6 and newer, where centos-release is installed as part of the environment.

Could centos-release get added to the environment? I'm currently working around it with a "BuildRequires" for it, but I'd rather that it be properly fixed for anyone else who might have this issue.

P.S.: Update to CentOS 5.11?

**Comment by adrianschroeter** [comment]
centos-release-5-10.el5.centos.x86_64.rpm is already imported and providing centos-release. So until you can show an example where it is not working this is a non-issue for me.

**Comment by adrianschroeter** [comment]
changed in prjconf
