### ISSUE TITLE
GPG key seems to be expired for xUbuntu_18.06

### ISSUE THREAD

**Issue by shoaebmjindani786** [openSUSE/open-build-service#13493]
`curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_18.04/Release.key | gpg --show-keys
`
![image](https://user-images.githubusercontent.com/40020259/206133407-390ef59a-df9e-4eef-b626-0a523b2e7974.png)

**Comment by dmarcoux** [comment]
We're tracking issues in the source code here. Please contact the [maintainers of xUbuntu_18.04](https://build.opensuse.org/project/users/Ubuntu:18.04) to get this issue fixed.

**Comment by adrianschroeter** [comment]
right, just that you should go to the maintainers of devel:kubic project instead ....

**Comment by shoaebmjindani786** [comment]
The key seems to be extended .

![image](https://user-images.githubusercontent.com/40020259/206403368-f25bc508-f4aa-47d4-8c82-6610ed5012d6.png)
