### ISSUE TITLE
Workflow runs show view displays incorrect scm name in webhook tab

### ISSUE THREAD

**Issue by krauselukas** [openSUSE/open-build-service#13527]
# Issue Description

The webhook tab on the workflow runs show view displays the name Github even the webhook was coming from an Gitea instance.

![screenshot_webhook_tab](https://user-images.githubusercontent.com/22001671/207560401-c590c037-a9a0-4423-93b9-1cc49a4dd1b6.png)

Expected Result
============
The tab displays the correct scm name.

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Workflow runs show view displays incorrect scm name in webhook tab](https://trello.com/c/8WIRCQMd/210-workflow-runs-show-view-displays-incorrect-scm-name-in-webhook-tab)

**Comment by ncounter** [comment]
This has been fixed by https://github.com/openSUSE/open-build-service/pull/13828
