### ISSUE TITLE
"Build Service Notification" mail needs a better subject line

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/open-build-service#13525]
I recently started receiving dozens of mails from build.opensuse.org which have as subject just "Build Service Notification
". Other notification mails carry actual information in their subject like "Request 42 created" or "Request 1337 commented".

**Comment by saraycp** [comment]
Some of the events didn't have a `subject` method implemented, therefore they used the default text: "Build Service Notification".

Since [this PR ](https://github.com/openSUSE/open-build-service/pull/16142) was deployed, all the events have a proper subject.
