### ISSUE TITLE
HTML entities in source files downloaded with source services

### ISSUE THREAD

**Issue by gryffus** [openSUSE/open-build-service#1353]
I have added a script which i need to run in prep to generate a patch. This script is downloaded from Github with tar_scm source service (i have tried also download_url with same results).
When i try to run the script i get error about bad characters in script. So i tred to cat the script in build process and i have noticed that there is indeed messed up formatting. The script is full of HTML entities instead of right chars. I can see `&lt;` , `&gt;` and `&amp;` entities.
If i download the script and view it on my local machine, it is all right.
The package is here: https://build.opensuse.org/package/show/home:gryffus:nine/Mesa-git-nine
Any clue?

**Comment by coolo** [comment]
that's just the webui live log escaping too much - try with osc bl

**Comment by gryffus** [comment]
Oh, the problem was that i invoked the script with "sh" instead of "bash" and bash in sh mode disables >( )... Sorry for confusion and thanks

**Comment by coolo** [comment]
the bug about double escaping < is still valid - but possibly it already exists :)
