### ISSUE TITLE
Support Clear Linux package building

### ISSUE THREAD

**Issue by johndoe1991239** [openSUSE/open-build-service#13539]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Is it possible in the future to support Clear Linux package building?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us. 

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.libera.chat/openSUSE-buildservice) or on the [OBS mailing list](https://lists.opensuse.org/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
