### ISSUE TITLE
[production][project#restore] 500 error when restoring home project

### ISSUE THREAD

**Issue by aspiers** [openSUSE/open-build-service#13544]
# Issue Description

My home project was [auto-deleted](https://build.opensuse.org/request/show/1013494) a couple of months ago, and I only just noticed.  I was relieved to be given an option to restore it from [the page for (re)creating a home project](https://build.opensuse.org/project/new?name=home%3Aaspiers&restore_option=true) (thanks for being kind enough to implement this very considerate feature!).  But unfortunately when I tried it, I got a 500 error page.

I tried again a few times in case this was a glitch, and after roughly the third attempt, the error changed, and now I'm getting an inline notification instead of the separate 500 page:

![image](https://user-images.githubusercontent.com/100738/208208457-12c5a2a3-11fc-483e-8b55-bf9a01513d95.png)

Expected Result
============
I expected to get my original `home:aspiers` project back with all the old packages.

How to Reproduce
===============
1. Login to an account with a home project which was auto-deleted
2. Click on "Create Your Home Project"
3. Click on "[Click here](https://build.opensuse.org/project/restore?project=home%3Aaspiers) if you want to restore the project"
4. (Probably) observe the same 500 error page I got.

Further Information
===============

https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/639cff2184bf460521649a7a

**Comment by saraycp** [comment]
@aspiers your project and its packages are restored now.
Except a package called `_meta` which is no longer a valid package name and whose content seemed empty. We had to skip that one to make the restore work.

I hope everything is fine now.

**Comment by aspiers** [comment]
That's fantastic, thanks so much @saraycp!
