### ISSUE TITLE
Ubuntu 22.10

### ISSUE THREAD

**Issue by winterz** [openSUSE/open-build-service#13583]
Is Ubuntu 22.10 supported as a distro yet?
I  don't see it listed at https://build.opensuse.org/projects/isv:KDAB/distributions/new

**Comment by dmarcoux** [comment]
> Is Ubuntu 22.10 supported as a distro yet?

Not yet, but this should be added soon.

**Comment by winterz** [comment]
I see  Ubuntu 22.10  today.
thanks!

closing this
