### ISSUE TITLE
Badge status calculation should ignore Excluded results

### ISSUE THREAD

**Issue by marxin** [openSUSE/open-build-service#13582]
@hellcp  First, I would like to thank a log for the feature!

As mentioned in the title, the following should not present `50%` (and `unknown` status):
https://build.opensuse.org/package/show/devel:openSUSE:Factory:rpmlint/rpmlint

[![build result](https://build.opensuse.org/projects/devel:openSUSE:Factory:rpmlint/packages/rpmlint/badge.svg?type=percent)](https://build.opensuse.org/package/show/devel:openSUSE:Factory:rpmlint/rpmlint)
[![build result](https://build.opensuse.org/projects/devel:openSUSE:Factory:rpmlint/packages/rpmlint/badge.svg?type=default)](https://build.opensuse.org/package/show/devel:openSUSE:Factory:rpmlint/rpmlint)

**Comment by hellcp** [comment]
I assume excluded, disabled and the such? Until this is fixed, feel free to use the version with the repository specified: https://build.opensuse.org/projects/devel:openSUSE:Factory:rpmlint/packages/rpmlint/badge.svg?type=default&repository=openSUSE_Factory

**Comment by hellcp-work** [comment]
This was fixed already
