### ISSUE TITLE
Document the Token Trigger endpoint query parameters fully

### ISSUE THREAD

**Issue by SchoolGuy** [openSUSE/open-build-service#13585]
# Issue Description

Not all parameters accepted by the endpoint at `/trigger/{operation}` are currently documented.

Expected Result
============

The openAPI specification shows all query parameters supported by the OBS instance.

How to Reproduce
===============

1. Go to https://build.opensuse.org/apidocs-new/#/Trigger/post_trigger__operation_
2. See error

Further Information
===============

I discovered this while implementing a [PR](https://github.com/openSUSE/osc/pull/1208) for osc and the following comment by Adrian: https://github.com/openSUSE/osc/issues/1194#issuecomment-1318253860

**Comment by SchoolGuy** [comment]
If this is just a matter of adding all the parameters [here](https://github.com/openSUSE/open-build-service/blob/master/src/api/public/apidocs-new/OBS-v2.10.50.yaml) I will gladly contribute that. However, I lack Ruby and project context knowledge atm.

**Comment by dmarcoux** [comment]
Yes, it's a matter of updating the file linked on the `$ref` line:

https://github.com/openSUSE/open-build-service/blob/addcf91778f1e6066cc90532394866db64f6aee7/src/api/public/apidocs-new/OBS-v2.10.50.yaml#L337-L338

**Comment by eduardoj** [comment]
The not yet documented parameters (targetproject, targetrepository, filter_source_repository, multibuild_flavor) should be documented in #12563 (or after merging it).

I will add a commit to this PR to provide a draft documentation, which should be adapted with something meaningful before merging. I don't know the specifics of each new introduced parameter.

**Comment by eduardoj** [comment]
This was documented in #13701. Closing.
