### ISSUE TITLE
Users#index user delete modal doesn't work with low breakpoints

### ISSUE THREAD

**Issue by hellcp-work** [openSUSE/open-build-service#13604]
# Issue Description
On lower breakpoints, when datatable collapses on users#index, the user delete modal stops functioning
![remove_when_collapsed](https://user-images.githubusercontent.com/114928900/209950401-4c3d0890-ed9c-45c5-95ab-244d18253eeb.gif)

Expected Result
============
You can still delete users when the viewport is narrow

How to Reproduce
===============
1. Make your viewport narrow
2. Open the actions dropdown
3. Click delete user button

**Comment by eduardoj** [comment]
Confirmed. I could reproduce the issue for `Configuration / Manage Users`.

I could not reproduce the issue for the Users of a project or the Users of a package.
