### ISSUE TITLE
Test OBS:Server:Unstable appliances in openQA automatically

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#1362]
Set up basic automated test of OBS appliance in openQA.

It should run the appliance, connect with osc and web browser and do the following actions:

* Add an interconnect to api.opensuse.org
* create home project
* Branch a package from remote to home project eg:
  openSUSE.org:openSUSE:Tools build
* Add a repository
* Monitor that the package is building successful

**Comment by sysrich** [comment]
This sounds like a really fun idea :+1:

**Comment by shyukri** [comment]
Done in #1624 and openQA tests tracked in https://github.com/os-autoinst/os-autoinst-distri-obs
Results in https://openqa.opensuse.org/group_overview/17
