### ISSUE TITLE
Painful new color scheme on staging dashboard

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#13665]
On Jan 9 2023, the color scheme of the staging dashboard, for requests 'with pending reviews' has been changed from 'blue background' (review) to 'yellow background' (building)

Let alone that the blue background matched better the state of the request, the new palette is very unfriendly on the eye:

![image](https://user-images.githubusercontent.com/532559/211285445-841f6227-09f8-48c9-a4f7-100d17794b1d.png)

**Comment by DimStar77** [comment]
The Legend at the bottom of the page does still carry the 'old' colors (so does not match reality now):

![image](https://user-images.githubusercontent.com/532559/211286531-8f6480ef-b504-40cf-ad50-ea533f365ae5.png)

**Comment by dmarcoux** [comment]
Thank you @DimStar77 for reporting the issue. We're looking into it.
