### ISSUE TITLE
_link to derived project is not visible in web interface, if package does not exist there

### ISSUE THREAD

**Issue by stanislav-brabec** [openSUSE/open-build-service#1366]
I did
osc linkpac openSUSE:Leap:42.1:Update epydoc M17N:l10n.opensuse.org

However epydoc does not exist in openSUSE:Leap:42.1:Update yet, just only in openSUSE:Leap:42.1, link was created, checkout works correctly, and the package builds.

But the web interface is not able to recognize the link:
https://build.opensuse.org/package/show/M17N:l10n.opensuse.org/epydoc

**Comment by adrianschroeter** [comment]
this got fixed
