### ISSUE TITLE
Non request views don't display diffs when request beta is on

### ISSUE THREAD

**Issue by hellcp-work** [openSUSE/open-build-service#13713]
# Issue Description
When request redesign beta is on, views that make use of the diff component don't display any content

Expected Result
============
A diff is displayed

How to Reproduce
===============
1. Make sure you have request redesign beta turned on
2. Go to a package view
3. Click Files Changed in Latest Revision
4. No diff is rendered

Further Information
===============
* Example of a view: https://build.opensuse.org/package/rdiff/X11:Utilities/arandr?linkrev=base&rev=19

**Comment by eduardoj** [comment]
Fixed by #13717.
