### ISSUE TITLE
Flag table behaviour change

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#1372]
Flag tables show a different behaviour as they used to. Eg. when click on the global disable button the other fields used to change as well (IIRC greyed disable symbol).

Rudi saw also more problems, please ask him directly.

**Comment by coolo** [comment]
this is hopefully just a display problem, right?

**Comment by adrianschroeter** [comment]
yes, seems so.

**Comment by mmohring** [comment]
It is not only a display problem. E.g. if I switch off all builds in the WebUI with "all disable", not only do the other flags not show "disable", but if I issue then a rebuild via osc rebuild, the package I trigger a rebuild gets a rebuild started.

**Comment by mmohring** [comment]
And the monitor page does not show any changes if I change flags in the WebUI. I am talking about the WebUI  <OBSURL>/project/repositories/<projectname>.

**Comment by hennevogel** [comment]
@mmohring how does the xml look like before and after?

**Comment by mmohring** [comment]
The meta prj xml does not change when I change flags in the /project/repositories. When I change it via osc meta prj it shows up in the WebUI.  The WebUI /project/monitor/<projectname> always reflects the correct build flags, .e.g. disabled if package is disabled, or build status like succeded if package is enabled. So yes the WebUI /project/repositories for build flag does not do anything for current git master.

**Comment by hennevogel** [comment]
@mmohring this is your own instance?

**Comment by mmohring** [comment]
Yes. I use a deployment that is like OBS:Server:Unstable but with git commit controlled obs-api-deps and obs-server packages using rpm/zypper to install the packages. I try now to go back to a git commit that worked.

**Comment by mmohring** [comment]
I saw the issue with git commits d25aad855890ddd197d29eb5a403b02a444cd8e6 and 891117d4134acb773efc0d8c5160f84852020850. Going now back even more.

**Comment by mmohring** [comment]
Cross check with old commit fc7da3fb4083b0019d2fb4905b37ed0484918089 - works with that version.

**Comment by Mailaender** [comment]
I can confirm that this is a problem at https://build.opensuse.org/package/repositories/games:openra/development

![image](https://cloud.githubusercontent.com/assets/756669/11375221/54836028-92da-11e5-94bc-579096bd141d.png)

**Comment by hennevogel** [comment]
So only the icons are wrong now. We are on it...

**Comment by stoecker** [comment]
Could this issue please be fully fixed and deploxed? As it is now on build.opensuse.org the enable/disable buttons are nearly useless - neither showing the correct state nor allowing to do the correct changes.

**Comment by hennevogel** [comment]
We are very well aware of this :-)

It's already here: https://github.com/openSUSE/open-build-service/pull/1411

**Comment by Mailaender** [comment]
I tend to edit https://build.opensuse.org/package/meta/ manually for quite some time now. Also discovered the useful `<url>` tag there again.

**Comment by stoecker** [comment]
I see the awareness, but only little progress. That's why I added the comment. Not everybody knows that as a crude workaround meta files can be edited by hand.

**Comment by hennevogel** [comment]
This is fixed since fa1c1f22dc9c2ef7b25e02989d382da33e237f22
