### ISSUE TITLE
GET /search/owner returns html unless Accept header is set to application/xml

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#13737]
# Issue Description

if you issue a GET request to the `/search/owner` route, then obs will respond with a html page unless you set the header `Accept` to `application/xml`. This is not required for most of the other routes.

Expected Result
============

- the header should either be mandatory everywhere or nowhere
- the requirement should be documented

**Comment by hennevogel** [comment]
It is the [default unless set](https://github.com/openSUSE/open-build-service/blob/master/src/api/config/initializers/prefer_xml_over_html.rb). If it is set, whatever you request is preferred.

**Comment by eduardoj** [comment]
In the new API documentation this is alredy defined on the "Responses" section of each endpoint (action + path, for example: `GET` + `/search/owner`): https://build.opensuse.org/apidocs-new/#/Search/get_search_owner

![Screenshot from 2023-01-19 15-10-47](https://user-images.githubusercontent.com/24919/213464499-2ca81235-75b7-40cf-9809-359af069c3c2.png)

Anyway, I created a PR to make it clearer in the general description section of the API documents that clients should make sure that they use the correct Accept header: #13741

**Comment by dcermak** [comment]
Ah, I was looking at the old `apidocs.txt`, where that is not mentioned. I would consider this resolved, however I would suggest to forward anything that hits `api.opensuse.org` to the API and everything else to the webui. But I'm not sure if that is easily doable in Rails (it probably is), or whether that would be wanted.
