### ISSUE TITLE
Links to required packages are broken

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/open-build-service#13746]
For every built package there's the "Details" link which shows a list of requires and the packages which provide it.
Clicking on any of those packages leads to an error page saying `Architecture '' is invalid.`

**Comment by danidoni** [comment]
I'm not sure if I'm following, are you talking about the `Details` link that appears for example [here](https://build.opensuse.org/package/binaries/OBS:Server:Unstable/obs-server/15.4)?

**Comment by danidoni** [comment]
Ah, I understand now. The issue is clicking on any of the required packages inside the Details page...

**Comment by Vogtinator** [comment]
Yep!

**Comment by danidoni** [comment]
![image](https://user-images.githubusercontent.com/2650/213666516-572bc582-a1de-455e-b0a3-ba61f6f684bf.png)
Just leaving this screenshot for future reference. Clicking on the link pointed by the arrow gives you the error showed in red

**Comment by Vogtinator** [comment]
Any news here?

**Comment by danidoni** [comment]
> Any news here?

Still failing, we haven't looked into it yet.
