### ISSUE TITLE
Warning popping about repository not signed

### ISSUE THREAD

**Issue by TomIGo2** [openSUSE/open-build-service#13763]
# Issue Description
Currently receiving the following error when attempting to use the Software Management function within Yast2:

An error occurred during repository initialization. [https-download.opensuse.org-5fcd8163|https://download.opensuse.org/update/leap/15.4/sle] Valid metadata not found at specified URL History: - Signature verification failed for repomd.xml - Can't provide /repodata/repomd.xml

Expected Result
============
No errors regarding signing of production repositories.

How to Reproduce
===============
1. Go to 'Yast2' via Application Menu/Settings, select 'Yast2'
2. Click on 'Software Management'
3. Warning screen pops during and after the 'Load the configuration repositories'

Further Information
===============
> cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.4"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.4"
PRETTY_NAME="openSUSE Leap 15.4"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.4"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

If you have a question about some content in some specific instance, like build.opensuse.org, then contact the admins of this instance. Like in this case admin@opensuse.org

Thank you for your consideration.
