### ISSUE TITLE
Unwatch button doesn't work

### ISSUE THREAD

**Issue by gmbr3** [openSUSE/open-build-service#13767]
# Issue Description
Pressing the unwatch button doesn't change anything

Expected Result
============
It gets unwatched

How to Reproduce
===============
1. Click the watch button on any package or project
2. The message 'Added project/package to the watchlist' appears
3. Click the unwatch button
4. Nothing happens

Further Information
===============
* Found on build.opensuse.org

**Comment by dmarcoux** [comment]
The fix for this is already done, but not live yet on build.opensuse.org. We will deploy the changes as soon as possible. Sorry for the inconvenience.

For details on how this was fixed, see #13738.

**Comment by dmarcoux** [comment]
@gmbr3 The fix for this issue is now live on build.opensuse.org. Have a good day! :slightly_smiling_face:
