### ISSUE TITLE
Internal Server Error when adding a new repository

### ISSUE THREAD

**Issue by dscharrer** [openSUSE/open-build-service#1377]
Visiting https://build.opensuse.org/project/add_repository_from_default_list/home:dscharrer while logged in gives me "500: Internal Server Error".

Here is the id from a failed request:

    X-Request-Id: df230c99-cd6c-4a3a-b610-1e8531e1830a

The error happens every time. It also happens when trying to add a repo to the sub project.

**Comment by bgeuken** [comment]
Adrian fixed this one already
