### ISSUE TITLE
Builds in devel:languages:haskell:ghc-8.10.x hang forever in "signing" phase

### ISSUE THREAD

**Issue by peti** [openSUSE/open-build-service#13771]
Builds in https://build.opensuse.org/project/show/devel:languages:haskell:ghc-8.10.x don't finish; they appear to hang forever in the "signing" phase without ever completing it. I have triggered all kinds of re-build in the project but had no success remedying this issue. Is this a known problem? Is there any solution for this issue?

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.libera.chat/openSUSE-buildservice) or on the [OBS mailing list](https://lists.opensuse.org/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 


Thank you for your consideration.
