### ISSUE TITLE
RHEL 9 support?

### ISSUE THREAD

**Issue by jhdxr** [openSUSE/open-build-service#13794]
Hi,

Is there any chance to get support for RHEL 9 based distributions? e.g. Rocky Linux 9, or CentOS Stream 9. Thanks.

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us for some specific instance.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.libera.chat/openSUSE-buildservice) or on the [OBS mailing list](https://lists.opensuse.org/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
