### ISSUE TITLE
Files could not be expanded: Running /usr/lib/obs/service/download_url

### ISSUE THREAD

**Issue by ederag** [openSUSE/open-build-service#1380]
This error shows up only on the site, 
https://build.opensuse.org/package/show/home:ederag:branches:graphics/ipe,
not for a local build. 
Here is the error: `Files could not be expanded: Running /usr/lib/obs/service/download_url --protocol https --host dl.bintray.com --path otfried/generic/ipe/7.1/ipe-7.1.9-src.tar.gz --filename ipe-7.1.9.tar.gz --outdir /lxc.tmp.5560/out`
Locally, `/usr/lib/obs/service/download_url --protocol https --host dl.bintray.com --path otfried/generic/ipe/7.1/ipe-7.1.9-src.tar.gz --filename ipe-7.1.9.tar.gz --outdir /tmp/obs-try` works fine.

There was a server change, from github to bintray. Is it related ?

There was a similar issue: #429.

**Comment by adrianschroeter** [comment]
[12:59] <edogawa> i'd think ederag has made a mistake, not found a bug - his _service has <param name="filename">ipe-7.1.9.tar.gz</param> but there's only a file ipe-7.1.9-src.tar.gz in that directory

**Comment by ederag** [comment]
But it does work locally.
Isn't the purpose of the `filename` parameter to rename the downloaded file ?
At least there an inconsistency.

**Comment by ederag** [comment]
Besides, changing the name to be exactly the same as that of the downloaded file,
does not fix anything.
https://build.opensuse.org/package/show/home:ederag:branches:graphics/ipe?rev=4

@adrianschroeter Could you please be more specific about the mistake you think I'm doing ?

**Comment by ederag** [comment]
Without download (file added), the error does not show up.
cf. https://build.opensuse.org/package/show/home:ederag:branches:graphics/ipe?rev=5

**Comment by ederag** [comment]
@adrianschroeter Could you please reopen this bug ? (or explain why not)

**Comment by pgnd** [comment]
Similarly

@ https://build.opensuse.org/package/show/home:pgnd:usrlocal/openssl

"Files could not be expanded: Running /usr/lib/obs/service/download_url --protocol https --host www.openssl.org --path source/openssl-1.0.2f.tar.gz --filename openssl-1.0.2f.tar.gz --outdir /lxc.tmp.18850/out"

**Comment by adrianschroeter** [comment]
www.openssl.org has a very limited support for ssl protocols. most likely the openSUSE 13.2 SSL was not able to connect there, but there are chances that 42.1 meanwhile can.

However, not an OBS bug.

**Comment by pgnd** [comment]
@adrianschroeter 

I'm using Opensuse Leap 42.1 locally.  How does what I am using on the desktop affect what error OBS website fires?

"limited support"?  On what are you basing that statement?

Openssl.org's website passes Qualsys tests with flying colors, https://www.ssllabs.com/ssltest/analyze.html?d=www.openssl.org&s=194.97.150.234 -- with an "A+".

Otoh, for reference, build.opensuse.org passes with a significantly lesser mark, https://www.ssllabs.com/ssltest/analyze.html?d=build.opensuse.org&s=195.135.221.133 -- a "C".

No other application exhibits any problems accessing, or downloading from, openssl.org.

How is this anything BUT an issue an OBS?

**Comment by adrianschroeter** [comment]
openssl.org get's A+ _because_ you can not connect with older clients anymore.

we used to have 13.2 as host OS for services, but that got upgraded to 42.1.

But no, this has nothing to with obs code base. It just the openssl implementation  of the base system versus the apache configuration on the 3rd party server side.

All the mentioned examples in this report are working (I have also triggered home:pgnd:usrlocal/openssl to verify), so there is really nothing here to do anymore.
