### ISSUE TITLE
Revisions Page improvement

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#13866]
I was wondering why [some requests](https://obs-measure.opensuse.org/d/fzuOfHQik/measurements-per-request?orgId=1&var-request_id=f95bd60b-4eef-4022-b0fd-69401d08f6c5&from=1676256611958&to=1676256643639&var-method=Webui%3A%3APackageController%23show) to `PackageController#revision` are so slow.

It's because we paginate an array of numbers

https://github.com/openSUSE/open-build-service/blob/022f041aab945711a3d148f82f6ec38cf41bd9c0/src/api/app/controllers/webui/package_controller.rb#L270

to load & render all revisions on the page

https://github.com/openSUSE/open-build-service/blob/022f041aab945711a3d148f82f6ec38cf41bd9c0/src/api/app/views/webui/package/revisions.html.haml#L12

this is a bad idea with a package with 7K+ revisions

**Comment by dmarcoux** [comment]
I turned the links into permalinks, this is possible by pressing `Y` and copying the URL when looking at a file. This is explained [here](https://docs.github.com/en/repositories/working-with-files/using-files/getting-permanent-links-to-files).
