### ISSUE TITLE
Built OVA files not published

### ISSUE THREAD

**Issue by stevemallindine** [openSUSE/open-build-service#13873]
# Issue Description
Publishing of resulting OVA files not done

Expected Result
============
Built OVA files should be published to /srv/obs/repos/

How to Reproduce
===============
1. Build OVA kiwi image 
2. Check for built files in /srv/obs/build/$project/images/$arch/$package/xxx.ova
3. Check for (not) published files in /srv/obs/repos/$project/images/xxx.ova

Further Information
===============
* Private OBS installation
* OBS version 2.10.20-lp154.109.1
* Fix:
/usr/lib/obs/server/bs_publish +1957
`} elsif ($bin =~ /^(.*)\.(?:box|json|ovf|phar|qcow2|vdi|vhdfixed|vmx|vmdk|vhdx)(?:\.xz)?(\.sha256)?$/) {`
  to include 'ova'
`} elsif ($bin =~ /^(.*)\.(?:box|json|ovf|ova|phar|qcow2|vdi|vhdfixed|vmx|vmdk|vhdx)(?:\.xz)?(\.sha256)?$/) {`

**Comment by adrianschroeter** [comment]
did it that way now ... 
a pull request might have been faster ;) (*hint*)

**Comment by mlschroe** [comment]
(For reference: I broke ova publishing with commit 6b5bceb82bbbc2b7033a8f1cb96a723acad83975 in 2014)
