### ISSUE TITLE
libz1 missing on SLE 11 SP4 ?

### ISSUE THREAD

**Issue by plinnell** [openSUSE/open-build-service#1387]
See  https://build.opensuse.org/request/show/345101  SP4 shows "unresolvable"  SP3 is fine.

**Comment by bgeuken** [comment]
JFYI libz1 is part of zlib package which is failing in your project: https://build.opensuse.org/package/show/devel:libraries:c_c++/zlib

Might be that something in your project / zlib package is wrongly configured
