### ISSUE TITLE
Notification bar margin

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#13890]
![Screenshot from 2023-02-24 11-39-03](https://user-images.githubusercontent.com/514785/221158865-8319f2d6-0b97-4967-aff4-70cf3c8a2009.png)

**Comment by Jaskaran2** [comment]
Hi @hennevogel . Hope you are doing well. I wanted to ask is it ok if I may pick this up?

**Comment by dmarcoux** [comment]
@Jaskaran2 Yes, nobody is assigned to this issue, so you're free to work on it. Let us know if something isn't clear.

**Comment by Jaskaran2** [comment]
Sure thank you. Will let you know if I have any questions.
