### ISSUE TITLE
indirect inherited packages are not visible in webui anymore

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#1390]
As with commit ae6929a93b76867ae8b009b95460ce892682f5ad we do not support listing of packages in inherited package view in webui, since it is only a single join, but no recursive lookup anymore.

This means packages from project C won't be visible anymore when you use a setup via project links like this:

 A -> B -> C

Ask if you need a real-life example. Since the api is using now the same method ( Project.packages_from_linked_projects ) it is broken there as well now.

**Comment by hennevogel** [comment]
Fixed...
