### ISSUE TITLE
search engine CI problems

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#1391]
The Webui::SearchControllerTest take a way too long time inside of the package builds. 
It creates also random failures due to timeout errors.

This might be caused by the fact that we do not have access to external network, but sphinx should not need it.

**Comment by adrianschroeter** [comment]
It seems to be dead locks. When it runs into such a problem package build is hanging forever or at least until obs worker is killing it. It succeeds when it is trying to build often enough.

**Comment by DavidKang** [comment]
@adrianschroeter, is still a problem?

**Comment by eduardoj** [comment]
@adrianschroeter, ping.

**Comment by adrianschroeter** [comment]
well, don't know, you look at the package build failures as well, no? ;)

Let's close it, it is 4 years old ....
