### ISSUE TITLE
project meta: insufficient validation error message

### ISSUE THREAD

**Issue by dmach** [openSUSE/open-build-service#13925]
# Issue Description
Project meta validation gives no hint on what's wrong with the data.

Expected Result
============
Inform about which field failed to validate and what is the invalid value.

How to Reproduce
===============
Send a PUT request to `source/<project>/_meta` with an invalid architecture:
```
  <repository name="repo">
    <path project="project" repository="standard" />
    <arch>foo</arch>
  </repository>
```
Server returned an error: HTTP Error 400: Bad Request
project validation error: 15:0: ERROR: Error validating value 

^^^ No clue what's wrong.

**Comment by hennevogel** [comment]
`15:0: ERROR: Error validating value` is the error from the [validation of nokogiri](https://nokogiri.org/rdoc/Nokogiri/XML/SyntaxError.html). 15 is the line of the XML. There is no other information...

**Comment by hennevogel** [comment]
What's the difference you like to see? The value name?

**Comment by darix** [comment]
well the letting the user know that the value of the element did not validate might help

**Comment by hennevogel** [comment]
> well the letting the user know that the value of the element did not validate might help

Erm.. `15:0: ERROR: Error validating value` ?

**Comment by eduardoj** [comment]
The call to `schema.validate(doc)` returns an array of errors.

With this code, an exception is raised on the first element of the errors' array: https://github.com/openSUSE/open-build-service/blob/4b62fbffec5f10569307983d3fecf6bfcabe2dd2/src/api/app/lib/suse/validator.rb#L102-L108

Whould it be maybe more helpful to return a string with all the errors' array elements joined, instead of only the first element?

**Comment by eduardoj** [comment]
> Only if you would parse and make this human readable somehow. I doubt people using the OBS API want to dig into nokogiri docu...

I still see it could be an improvement to provide all the nokogiri errors, instead of the first one.

Instead of returning:
```
Server returned an error: HTTP Error 400: Bad Request
project validation error: 6:0: ERROR: Error validating value 
```

... this could be returned:
```
Server returned an error: HTTP Error 400: Bad Request
project validation error: 6:0: ERROR: Error validating value 
6:0: ERROR: Element arch failed to validate content
ERROR: Extra element arch in interleave
6:0: ERROR: Element repository failed to validate content
ERROR: Extra element repository in interleave
1:0: ERROR: Element project failed to validate content
```

**Comment by darix** [comment]
well i kinda missed the original error message above. but i think the extra errors about interleave is just a follow up error.

we already started discussing if we should have the rng files in /usr/share/obs/schema/ and then osc can validate client side.

**Comment by hennevogel** [comment]
@darix I guess you are talking about openSUSE/osc#1208 right?
