### ISSUE TITLE
Some OBS attributes not created after installation

### ISSUE THREAD

**Issue by dmach** [openSUSE/open-build-service#13931]
# Issue Description
The following attributes do not get created automatically:
* OBS:BranchSkipRepositories
* OBS:PlannedReleaseDate
* OBS:EnforceRevisionsInRequests
 
Expected Result
============
The attributes get created.

How to Reproduce
===============
1. install OBS
2. osc -A <url> api /attribute/OBS
3. The attributes listed above are missing from the output

Further Information
===============
Actual output:
```
<directory count="24"> 
 <entry name="AllowSubmitToMaintenanceRelease"/> 
 <entry name="ApprovedRequestSource"/> 
 <entry name="AutoCleanup"/> 
 <entry name="BranchRepositoriesFromProject"/> 
 <entry name="BranchTarget"/> 
 <entry name="CreatorCannotAcceptOwnRequests"/> 
 <entry name="DelegateRequestTarget"/> 
 <entry name="EmbargoDate"/> 
 <entry name="ImageTemplates"/> 
 <entry name="IncidentPriority"/> 
 <entry name="InitializeDevelPackage"/> 
 <entry name="Issues"/> 
 <entry name="Maintained"/> 
 <entry name="MaintenanceIdTemplate"/> 
 <entry name="MaintenanceProject"/> 
 <entry name="MakeOriginOlder"/> 
 <entry name="OwnerRootProject"/> 
 <entry name="ProjectStatusPackageFailComment"/> 
 <entry name="QualityCategory"/> 
 <entry name="RejectRequests"/> 
 <entry name="RequestCloned"/> 
 <entry name="ScreenShots"/> 
 <entry name="UpdateProject"/> 
 <entry name="VeryImportantProject"/> 
</directory>
```

The listing doesn't match attributes from attribute_descriptions.rb

**Comment by eduardoj** [comment]
It looks like those should be added in [src/api/db/seeds.rb](https://github.com/openSUSE/open-build-service/blob/master/src/api/db/seeds.rb)...

**Comment by eduardoj** [comment]
> The following attributes do not get created automatically:
> 
>     * OBS:BranchSkipRepositories
>     * OBS:PlannedReleaseDate

The migrations for creating both of these attributes were removed in [this pull request](https://github.com/openSUSE/open-build-service/pull/10740). This should be addressed.

>     * OBS:EnforceRevisionsInRequests

The migration to create this attribute seems to be still there: https://github.com/openSUSE/open-build-service/blob/master/src/api/db/data/20210409135426_add_enforce_revision.rb

Can you confirm if this case gets solved running the migrations?
