### ISSUE TITLE
<url> tag for Project Meta Configuration

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#1394]
The <url> tag is really underused and now nicely integrated into the web UI (again).

> ![image](https://cloud.githubusercontent.com/assets/756669/11318841/fad966fe-9062-11e5-8d09-239cdf7db8e2.png)

It would be nice to also have it in Meta Configuration of projects:

![image](https://cloud.githubusercontent.com/assets/756669/11318847/4ec96408-9063-11e5-886e-751e271bb8c1.png)

**Comment by hennevogel** [comment]
This is the case by now...
