### ISSUE TITLE
WebUI: "There has been an internal error. Please try again." - Page was previously visible

### ISSUE THREAD

**Issue by biggestsonicfan** [openSUSE/open-build-service#14007]
# Issue Description
Up until yesterday, the following url: https://build.opensuse.org/project/show/openSUSE:Tumbleweed:OldKey could be navigated to with the webui, but now returns the following error "There has been an internal error. Please try again." and kicks you back to https://build.opensuse.org/

The project is still accessible via osc/api. The url was working as of 3/13.

Expected Result
============
Open the project page.

How to Reproduce
===============
1. Navigate to https://build.opensuse.org/project/show/openSUSE:Tumbleweed:OldKey

Further Information
===============
I am not the maintainer of this repo, merely reporting information as I'm seeing it. The maintainer stated I should file a bug here based on what's happened.

**Comment by lkocman** [comment]
I do experience this issue only while logged in as mantainer of the project (openSUSE:Leap:16.0 / lkocman-factory), or not logged in at all. Page is perfectly visible if I'm logged in as a regular user (lkocman)

**Comment by krauselukas** [comment]
@biggestsonicfan @lkocman webui should load again after the next deployment

**Comment by biggestsonicfan** [comment]
Nice! Thanks much!
