### ISSUE TITLE
new request workflow: repo building state is confusing

### ISSUE THREAD

**Issue by dirkmueller** [openSUSE/open-build-service#14000]
The current building state display is slightly confusing: 

![image](https://user-images.githubusercontent.com/1029152/225006148-6ef008ce-78f8-4af8-90ce-08fda43d7089.png)

I understand now that the 2nd line is the "repository" state, which is confusing on a package view imho. 

And the "question mark" icon has no function, clicking on it doesn't expand a help like it did before. 

Expected Result
============

maybe the repository status should be shown alongside the repository to make that clearer. 

![image](https://user-images.githubusercontent.com/1029152/225007037-68a9a8e3-9541-461d-9351-28007548c502.png)

Further Information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)

**Comment by rubhanazeem** [comment]
This is no longer relevant. The build results page has been completely changed.
