### ISSUE TITLE
Branching of projects with udate repo is redirecting to wrong page, which causes a 404

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#1402]
In that particular case the branched project get's an ":Update" suffix, which causes the wrong redirect.

For testing purposes you can try it with a package from this project:
  https://build.opensuse.org/project/show/openSUSE:13.2
or on our dev machines with:
  BaseDistro/pack1

**Comment by bgeuken** [comment]
Adrian told me that there are additional cases were the actual branch differs from the project name that the branch got created from. Like some of the SLE branches.

**Comment by adrianschroeter** [comment]
btw, also the package name can differ when having a devel package definition. (it is quite unusual though)

**Comment by adrianschroeter** [comment]
The BranchPackage.branch command is delivering the right container and also the origin inside of the return value.

**Comment by bgeuken** [comment]
Thing is that now there is an authorize call in the controller which needs the project name. And to make that one work we needed the branch name before creating it.
That's how the bug got introduced.

**Comment by bgeuken** [comment]
merged to master
