### ISSUE TITLE
Ghost package

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/open-build-service#14067]
$ osc pr -q -sB openSUSE:Factory:ARM
 gtk3:doc
 B  containerfile aarch64 (blocked)
 B  containerfile armv7l (blocked)
 B  images aarch64 (outdated)
 B  images armv7l (blocked)
 B  images local (blocked)
 B  standard aarch64 (building)
 B  standard armv7l (outdated)

$ osc r openSUSE:Factory:ARM gtk3:doc
Server returned an error: HTTP Error 404: unknown package 'gtk3 doc'

**Comment by hennevogel** [comment]
Yet another project link bug...

**Comment by adrianschroeter** [comment]
no, that was a regression in the scheduler. Fixed meanwhile

**Comment by eduardoj** [comment]
Time interval between both `osc pr ...` and `osc r ...` command calls could be important.

There was a change in the `gtk3` package, where the `_multifbuild` file was removed from the `gtk3` package and it didn't build the multibuild package `gtk3:doc` any more. It happened on 2023-03-24 14:18 UTC. See: https://build.opensuse.org/package/rdiff/openSUSE:Factory:ARM/gtk3?linkrev=base&rev=183

@andreas-schwab, do you still remember if those command calls were performed around this time? If you had performed the `osc pr ...` command before 2023-03-24 14:18 UTC, and the `osc r ...` command after, that could explain this issue you created.

**Comment by andreas-schwab** [comment]
The error persisted for several days.
