### ISSUE TITLE
Request page ends up with error 500 (after authentication only)

### ISSUE THREAD

**Issue by Werkov** [openSUSE/open-build-service#14109]
# Issue Description

Request page won't show up for authenticated user (its author).

![Screenshot from 2023-04-04 17-23-34](https://user-images.githubusercontent.com/630751/229840848-7f41171a-1844-4441-82d6-d661cb60ddc7.png)

Expected Result
============

The webpage with request information is shown even for authenticated user.

How to Reproduce
===============

1. Log in to OBS
2. Go to https://build.opensuse.org/request/show/1077228
3. See error

Further Information
===============

EDIT: The page (perhaps without some details) shows just fine for an anonymous user.

**Comment by eduardoj** [comment]
Confirmed.

Error in Errbit: https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/642c3ba784bf4604fe227a93

**Comment by Werkov** [comment]
I can access the request. Thanks!
