### ISSUE TITLE
Some obscpio files are huge

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/open-build-service#14127]
# Issue Description

Project https://build.opensuse.org/package/show/Emulators/rpcs3

rpcs3-0.0.27~git20230409.obscpio is 1.7GB which is much bigger than usual tar.gz or tar.xz files.

The problem is that each time I update the package, it takes me one hour to run `osc ci`.

Expected Result
============

obscpio files should have much smaller sizes.

How to Reproduce
===============
1. osc co Emulators/rpcs3
2. osc service run
3. check the size of rpcs3-*.obscpio

**Comment by hennevogel** [comment]
Run your tar/re-compress services also `localonly` before you upload?

**Comment by guoyunhe** [comment]
It doesn't make any sense...

```
1.9G    rpcs3-0.0.27~git20230411.obscpio
56M     rpcs3-0.0.27~git20230411.tar.xz
```

Will go with tar_scm instead...

**Comment by guoyunhe** [comment]
In `obs_scm`, `exclude` rules don't work, so you cannot exclude submodules like llvm and ffmpeg that you don't actually need.

`tar_scm` works fine and thus has much smaller output.

Isn't this a bug?
