### ISSUE TITLE
Typo in airbrake.rb: "blacklist_keys" should be "blocklist_keys"

### ISSUE THREAD

**Issue by linuxrrze** [openSUSE/open-build-service#14170]
Sorry for not supplying all surrounding information, but I'm a little short on time and I hope the typo is more or less obvious for people knowing the code (especially because the correct function is even referenced in the comment two lines above):

Typo in src/api/config/initializers/airbrake.rb prevents frontend from running:
"blacklist_keys" should be "blocklist_keys"

```
  # A list of parameters that should be filtered out of what is sent to
  # Airbrake. By default, all "password" attributes will have their contents
  # replaced.
  # https://github.com/airbrake/airbrake-ruby#blocklist_keys
  # FIXME: `string` is a column from the Tokens table, this column should be renamed.
  c.blacklist_keys = [/password/i, /authorization/i, /scm_token/i, /string/i]
```

**Comment by hennevogel** [comment]
With the latest airbrake maybe, which we don't use....
