### ISSUE TITLE
Dependency info on the server is not updated for pkgs when prj config changes in another project

### ISSUE THREAD

**Issue by kaltsi** [openSUSE/open-build-service#1423]
Here's a demo:

https://build.opensuse.org/project/show/home:kaltsi:test1

https://build.opensuse.org/project/show/home:kaltsi:test2

```home:kaltsi:test1``` uses CentOS:7 repository.
```home:kaltsi:test2``` uses repository from ```test1```

```test1``` sets one macro in its project config ```%mymacro```.

This macro is used in the ```BuildRequires``` of the only package in project ```home:kaltsi:test2```.

The macro is initially set to some unresolvable package name like  ```foobar``` and the package in  ```test2``` is in state ```unresolvable: nothing provides foobar```.

Then macro in ```test1``` project config is set to something resolvable like ```vim``` => package in  ```test2``` stays in unresovable state. This is the state now in these test projects.

Forcing rebuild on package (with ```osc```) does not resolve the issue on the server. Only committing a change to the package or declaring the same macro name in ```test2``` project config resolves the issue.

Update: it's enough to refresh the prj conf of ```test2``` to update the macros. Refresh can be just a PUT of the same prj conf contents that ```test2``` already has.

When building the package from the ```test2``` project with ```osc``` the dependency information is received correctly.

When debugging this on a local OBS installation, it looks like the ```:depends``` file in the affected project's ```build``` directory still contains the original macro value ```foobar```.

**Comment by adrianschroeter** [comment]
Micha, is a low-prio event really a problem? Would we need a low-low one?

**Comment by adrianschroeter** [comment]
We can add a configuration option in BSConfig.pm to propagate such changes, but we won't enable this by default. (It would kill at least larger instance performance wise).

**Comment by tuminoid** [comment]
Configuration options sounds reasonable.

**Comment by adrianschroeter** [comment]
Some experimental code exists in commit 6b0d5e324a804351f7d0409de259fc92fa46e5a5 . It is untested atm.
