### ISSUE TITLE
Macro expanded in comment

### ISSUE THREAD

**Issue by KAMiKAZOW** [openSUSE/open-build-service#1425]
[  393s] RPM build errors:
[  393s]     Macro expanded in comment

Yeah, that's why it's in a comment. Don't touch it.

See https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW:Fedora/dolphin-emu/Fedora_23/x86_64 for details.

**Comment by coolo** [comment]
your build fails and fedora's rpm is giving you a hint what *might* be the problem.

But this is:

```
[  384s] /usr/include/wx-3.0/wx/defs.h:3412:31: error: conflicting declaration 'typedef struct _GdkWindow GdkWindow'
[  384s]      typedef struct _GdkWindow GdkWindow;
```

And this issue tracker is the wrong one to discuss fedora's rpm version.
