### ISSUE TITLE
Help determine when users have left the platform

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#14278]
**Is your feature request related to a problem? Please describe.**

As a OBS project maintainer, I would like to get an indication whether a user has gone dormant, whether this other user has effectively abandoned maintainership on the package in the same project.

As a regular OBS user with no specific role, I would like to get an indication whether a user has gone dormant as before, and whether it is time to look at maintainership resets or do anything else with respect to unmaintained packages/projects.

**Describe the solution you'd like**

An endpoint that lists the most recent OBS actions of the user who supposedly has gone AWOL, e.g. commits made to a package (osc ci), or submit requests modified in any way (create, commented, etc.).

**Describe alternatives you've considered**

-

**Comment by hennevogel** [comment]
There is already a contribution graph on the user page and the "pulse" tab on every project you can use for that.

**Comment by hennevogel** [comment]
We also plan some form of [audit log](https://trello.com/c/JPNwBR1M) functionality for the future which would go into that direction for project managers.

**Comment by jengelh** [comment]
I do not know what user page you are referring to. https://build.opensuse.org/users/FunkyM does not have a graph.

There also is no graph on https://build.opensuse.org/projects/hardware/pulse , just a listing of request actions (which is a start) for fixed periods.

**Comment by hennevogel** [comment]
@jengelh the feature is disabled on build.o.o because of privacy concerns which SUSE has to evaluate.

**Comment by jengelh** [comment]
meanwhile `osc rq show -s all -U <interest>`

**Comment by hennevogel** [comment]
> Now if something like that were to exist for retrieving comments...

There isn't, only for yourself...

https://api.opensuse.org/apidocs-new/#/Comments/get_comments_user
