### ISSUE TITLE
Details view from WebUI doesn't work with .deb

### ISSUE THREAD

**Issue by deneb-alpha** [openSUSE/open-build-service#14292]
# Issue Description
From the WebUI is it possible to view the details of a built RPM like provides, requires etc. This feature doesn't work with .deb

Expected Result
============
The same feature available for .rpm is available with .deb

How to Reproduce
===============
1. Login 
2. Go for example to 'https://build.opensuse.org/package/binaries/systemsmanagement:Uyuni:Master:Ubuntu1804-Uyuni-Client-Tools/salt/xUbuntu_18.04'
3. Click on 'details' of a given .deb, for example on 'https://build.opensuse.org/package/binary/systemsmanagement:Uyuni:Master:Ubuntu1804-Uyuni-Client-Tools/salt/xUbuntu_18.04/x86_64/salt-api_3006.0+ds-1+214.1.uyuni_all.deb'
4. See error: `There has been an internal error. Please try again.`

Further Information
===============
* The issue can be reproduced on both IBS and OBS
* The download feature for the selected .deb works as expected. Only the `details` are broken

**Comment by hennevogel** [comment]
When accessing those binaries with `view=fileinfo_ext` on the backend we get a 400 error

```
<status code="400">
  <summary>excess hash entries: sourcedep</summary>
</status>
```

**Comment by nickbroon** [comment]
The "excess hash entries" error is also mentioned in #12469, which silences the error in the frontend.

**Comment by adrianschroeter** [comment]
fixed in build script parser.

**Comment by nickbroon** [comment]
https://github.com/openSUSE/obs-build/commit/d02a35abc42160ba5387c7d151f8437588e1e6eb

Fab, thanks @adrianschroeter! 🙂
