### ISSUE TITLE
blocked: downloading 2 dod packages

### ISSUE THREAD

**Issue by Freeman310** [openSUSE/open-build-service#14293]
Hello!
There is a need to build some packages and newer versions of gcc for Debian 10. In order to compile gcc-cross properly, cross-toolchain-base-ports must be compiled. However, when I threw in the source code files, the compilation of the worker was blocked with a message: "blocked: downloading 2 dod packages". How to solve this problem?

**Comment by saraycp** [comment]
Hi @Freeman310,

I recommend you send this question to the IRC channel #opensuse-buildservice (irc.libera.chat) or via email to [buildservice@lists.opensuse.org](mailto:buildservice@lists.opensuse.org). There you can find a big community of OBS users and contributors that can help you.

**Comment by saraycp** [comment]
I'm closing this issue, feel free to open a new one in case you need to request any feature or report a bug.
