### ISSUE TITLE
2.3.7: [backend] Download on Demand: Updated packages are not downloaded

### ISSUE THREAD

**Issue by dstolte** [openSUSE/open-build-service#143]
When a package of a DoD project has been downloaded to a local OBS system and  a newer package is published later then this newer package is not downloaded anymore. The local OBS will always use the oldest locally available package. The workaround is to manually delete the old package and the cache (.solv) and restart the schedular. This is a major pita. OBS version in use is 2.3.7.

**Comment by mlschroe** [comment]
Fixed with the new DoD handling some months ago. Didn't know about the issue, so I didn't close it. Sorry.
