### ISSUE TITLE
OBS install image for USB sticks cannot install OBS appliance

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/open-build-service#1434]
When attempting to install the appliance using the install image for USB sticks, the installation always fails with a verification error and a reboot exception is thrown. This issue is not present in the ISO install image.

**Comment by hennevogel** [comment]
Is the checksum correct?

**Comment by Conan-Kudo** [comment]
@hennevogel Yes. The checksums of the downloaded files are correct.

**Comment by Conan-Kudo** [comment]
@hennevogel The verification step that happens in the installer also appears to pass (which makes it strange why it fails due to failed verification).

**Comment by M0ses** [comment]
@Conan-Kudo : Which image did/do you download? Maybe this is the same problem as in #1436 ?

**Comment by Conan-Kudo** [comment]
@M0ses I downloaded the one for USB sticks linked on openbuildservice.org, which is this one: http://download.opensuse.org/repositories/OBS:/Server:/2.6/images/obs-server.x86_64.raw.install.raw.xz

**Comment by M0ses** [comment]
Just tried it - worked for me. Do you use bare metal HW and real USB stick, or in a virtualized environment?

**Comment by Conan-Kudo** [comment]
I used the former (bare mental HW and a real USB stick).

**Comment by M0ses** [comment]
This might be a issue with your hardware. As you stated anyway, you`d prefer to install Unstable, I will  
test 2.6.8 again and close this issue. I would recommend to go with Unstable iso in your case. As discussed with @adrianschroeter today, in Unstable we will activate the hybrid mode for kiwi. It`s the common way to create a usbstick for opensuse and in future it will also be for obs.

Please follow #1436 as I will not track progress here

**Comment by Conan-Kudo** [comment]
It's definitely not a hardware issue, as it also happens on VMs (I just tested it). I used KVM on Fedora 23 and it happens there, too.

**Comment by M0ses** [comment]
2.6.8 worked for me too ( virtualized on TW)

@Conan-Kudo: thanks for your hint
