### ISSUE TITLE
Provide an issue tracker for each package.

### ISSUE THREAD

**Issue by rokejulianlockhart** [openSUSE/open-build-service#14359]
**Is your feature request related to a problem? Please describe.**

Sometimes, a package on the OBS has an issue, but this issue isn't present upstream. This means that I specifically need to report it to the maintainers of the package. However, build.opensuse.org doesn't appear to provide this functionality.

**Describe the solution you'd like**

Integrate (a 3rd-party OSS?) bugtracker into the OBS so that I can directly report issues about a package. Mailing lists and the forums are simply inadequate compared to a decent bugtracker, as at least https://github.com/openSUSE/open-build-service/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc demonstrates, and the Factory mailing list is obviously solely for https://build.opensuse.org/package/show/openSUSE:Factory anyway. 

**Describe alternatives you've considered**

0. [ ] Provide an auto-generated anonymous (`*@build.opensuse.org`) `mailto:` or `matrix:` address for each OpenSUSE LDAP user.
0. [ ] Provide an external bug-tracking link of some sort...?

**Additional context**

https://build.opensuse.org/package/show/openSUSE:Factory/torbrowser-launcher#comment-1780106
https://build.opensuse.org/package/show/openSUSE:Factory/torbrowser-launcher#comment-1780115

**Comment by rokejulianlockhart** [comment]
@krauselukas, I don't see it (yet).

![image](https://github.com/openSUSE/open-build-service/assets/42837531/325e133a-1452-43df-ae8c-6de57e5a4a89)

Has the change not been pushed yet? If so, when might it be?

**Comment by hennevogel** [comment]
It's deployed since a while. See it on [home:hennevogel](https://build.opensuse.org/project/show/home:hennevogel) for instance. Project's need to define a bugowner for it to be visible.
