### ISSUE TITLE
Enable GitHub Discussion.

### ISSUE THREAD

**Issue by rokejulianlockhart** [openSUSE/open-build-service#14358]
**Is your feature request related to a problem? Please describe.**
I want to be able to ask questions specifically about this and be able to use GitHub's useful integrations, such as being able to mark questions as answered and transfer them into issues.

**Describe the solution you'd like**
What the title states – enable https://docs.github.com/discussions.

**Describe alternatives you've considered**
Post to https://forums.opensuse.org/.

**Additional context**
Additional rationale is available at https://github.com/8go/matrix-commander/issues/68#issue-1237645245.

**Comment by hennevogel** [comment]
We do support via IRC and mailing list already. See https://openbuildservice.org/support/

**Comment by rokejulianlockhart** [comment]
@hennevogel, is there at least a Matrix bridge to the IRC chat?

**Comment by hennevogel** [comment]
Sure https://matrix.to/#/#obs:opensuse.org
