### ISSUE TITLE
OBS install image for USB sticks for Server:Unstable doesn't exist

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/open-build-service#1436]
The URL for OBS install images for USB sticks for Server:Unstable doesn't appear to exist. When opening http://download.opensuse.org/repositories/OBS:/Server:/Unstable/images/obs-server.x86_64.install.raw.xz, it returns the following in the browser:

```
xz: /usr/src/packages/KIWI-oem/obs-server.x86_64-2.6.51.install.raw: No such file or directory
```

**Comment by bgeuken** [comment]
@mlschroe Could you have a look at this one? I would try a image rebuild but I don't have permissions for that project...

**Comment by hennevogel** [comment]
Something is fishy with the link creation @adrianschroeter

**Comment by M0ses** [comment]
I doubt, that this a backend problem. I guess this is a kiwi problem. Compared to 2.6 in the kiwi file "installiso" _and_ "installstick" are given, which was only 

https://build.opensuse.org/package/view_file/OBS:Server:Unstable/OBS-Appliance/OBS-Appliance.kiwi?expand=1

https://build.opensuse.org/package/view_file/OBS:Server:2.6/OBS-Appliance/OBS-Appliance.kiwi?expand=1

the ".raw.install.raw.xz" do not exists in the buildresult of Unstable and I cant see any evidence in the logs, that the "install.raw" file has been built at all. The error message of the "xz" command is simply the output on the STDERR.

**Comment by M0ses** [comment]
new hybrid iso images are created, tested and available in Unstable. Docs will be updated with next release.
