### ISSUE TITLE
"Revert to revision" ignores revision

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#1438]
https://build.opensuse.org/package/submit_request_dialog/project/package?revision=42&target_project=project will submit the latest version which completely defeats the purpose of reverting.

**Comment by bgeuken** [comment]
potentially a junior issue... ;-)

**Comment by hennevogel** [comment]
@Mailaender how did you reach this dialog with this parameter? Or are you proposing to add the feature to the UI?

**Comment by Mailaender** [comment]
1. find any package with revisions > 1 https://build.opensuse.org/package/show/games:openra/release
2. click revisions: https://build.opensuse.org/package/revisions/games:openra/release
3. click Files changed on the 2nd last revision https://build.opensuse.org/package/rdiff/games:openra/release?linkrev=base&rev=33
4. See a revert to revision XX link: https://build.opensuse.org/package/submit_request_dialog/games:openra/release?revision=33&target_project=games%3Aopenra

This feature worked, but that was long ago and I can't tell when it regressed.

**Comment by adrianschroeter** [comment]
Thanks a lot to Tumo who fixed it. But we should add a test case for this feature.
