### ISSUE TITLE
mbranch fetches changes from devel package, overwrites previous changes

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/open-build-service#1439]
We are having an issue with mbranch.

There are devel projects definitions in `openSUSE:Leap:42.1`, e.g. in `openSUSE:Leap:42.1/gtk2-branding-openSUSE`:
    <devel project="GNOME:STABLE:3.16" package="gtk2-branding-openSUSE"/>

This is picked up by `osc maintained gtk2-branding-openSUSE`:

    [...]
    openSUSE:Leap:42.1:Update/gtk2-branding-openSUSE using sources from GNOME:STABLE:3.16/gtk2-branding-openSUSE

and

    osc api -X POST "source?attribute=OBS%3AMaintained&cmd=branch&dryrun=1&update_project_attribute=OBS%3AUpdateProject&package=gtk2-branding-openSUSE"
    [...]
    <package project="openSUSE:Leap:42.1:Update" package="gtk2-branding-openSUSE">
        <devel project="GNOME:STABLE:3.16" package="gtk2-branding-openSUSE"/>
        <target project="home:AndreasStieger:branches:OBS_Maintained:gtk2-branding-openSUSE" package="gtk2-branding-openSUSE.openSUSE:Leap:42.1:Update"/>
    </package>

An mbranch will fetch the diff from the devel project and throw away previously released changes and changes done during openSUSE:Leap:42.1 during development:

    "fetch updates from devel package GNOME:STABLE:3.16/gtk2-branding-openSUSE"

Users need to branch such packages `--nodevelproject` ( `ignoredevel=1` ). However I believe that for `mbranch` the default should be `--nodevelproject`, as in the context of maintenance devel project definitions do not make sense.

**Comment by adrianschroeter** [comment]
If you define a devel package for a maintained package it is the purpose to collect changes for upcoming maintenance updates. So, why do you define a devel package when you don't want to use it?

**Comment by adrianschroeter** [comment]
we agreed that the devel package setup was broken here.

**Comment by andreasstieger** [comment]
Talked with @adrianschroeter and @coolo. Per package this problem is resolved with the first released updates. Maintenance will go through and submit diffs between the devel package and the released updates to the devel projects, if any.
