### ISSUE TITLE
RSS feed or social media hooks

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#1440]
https://build.opensuse.org/project/show/games is pretty active. In contrast to http://www.playdeb.net/ it doesn't have a nice store frontend with screenshots nor a news feed like https://plus.google.com/+playdeb Even something simple like an RSS feed or autogenerated messages like https://twitter.com/arch_update_bot for accepted submit requests may be interesting.

**Comment by hennevogel** [comment]
There is the [software.o.o](https://software.opensuse.org/packages/Games) appstream frontend (although broken currently, please report bugs [there](https://github.com/openSUSE/software-o-o)) and there is the [commit feed](https://build.opensuse.org/project/latest_commits/games). Marketing for packages is really out of scope for the OBS imho. If you miss something technically, let us know :-)

**Comment by Mailaender** [comment]
Reported the problem at https://github.com/openSUSE/software-o-o/issues/56.
