### ISSUE TITLE
Dependency parser seems to be confused by some macros

### ISSUE THREAD

**Issue by vincentbernat** [openSUSE/open-build-service#1441]
Hey!

I am having a hard time to use some conditional build requires. I have something like this:

```
# On RHEL < 7, use embedded libnl.
%if 0%{?rhel_version} > 0 && 0%{?rhel_version} < 700 || 0%{?centos_version} > 0 && 0%{?centos_version} < 600 || 0%{?suse_version} > 0 && 0%{?suse_version} < 1200
%bcond_with system_libnl
%else
%bcond_without system_libnl
%endif
```

```
%if %{with system_libnl}
BuildRequires: libnl3-devel
%endif
```

Using `rpmspec --define 'centos_version 500' -P redhat/lldpd.spec` tell me that there is no `BuildRequires` on `libnl3-devel` but when trying to build on OBS, I get an error that `libnl3-devel` cannot be found.

The whole stuff can be found here: https://build.opensuse.org/package/show/home:vbernat/lldpd-tests

**Comment by bgeuken** [comment]
Closing. The package in question got removed and it seems you solved your issue yourself. Nothing left to do:-)

**Comment by vincentbernat** [comment]
Oh, I did remove the package because it was published along the normal package and some users reported they were using them. I have other unrelated issues that I need to handle first. I'll reopen this bug report if I still have the problem once those issues are resolved.

**Comment by vincentbernat** [comment]
The spec file is still available here: https://github.com/vincentbernat/lldpd/blob/master/redhat/lldpd.spec
