### ISSUE TITLE
Add 'manage comments' section + 'report Spam' button

### ISSUE THREAD

**Issue by lrupp** [openSUSE/open-build-service#14516]
**Is your feature request related to a problem? Please describe.**

Public OBS is currently getting some Spam in the project and package comment sections. At the moment, this spam is not easy to detect and needs manual screening of the projects and packages - which is not doable manually, because of the huge amount of existing projects and packages.

As result, the administrators need to rely on users to report Spam via various ways (progress.o.o, mailing lists, IRC, ...). This does not allow a coordinated way of handling the Spam.

**Describe the solution you'd like**

A first step is to get an overview about the existing comments. This is hopefully not hard to implement and might later be useful for other topics as well. So I like to request an additional tab in the 'Configuration' section, where we have 'Manage News', 'Notifications' and more  already. The 'manage news' tab might be used as template for the new 'manage comments' tab here. Sorting by date might be enough - a separate search box for projects/packages might also be nice.

Later(?) a 'report spam' button should help logged in users to report any misuse of the comment section directly to the right place. As this might need additional tables and maybe even API endpoints (to use `osc` to review these requests?), I expect this to take some more time. Feel free to split out another feature request for this.

**Describe alternatives you've considered**

As long as we allow free subscription, there seems to be only a limited amount of alternatives. Captchas might be one alternative, but this would require at least similar implementation work.

**Additional context**

Spam prevention might need more work in the future (thinking about files uploaded to home projects). So I'm trying to suggest only two possible solutions that 
* might be quick to implement
* don't break existing workflows
* integrate in the current OBS setup

In happy two join a meeting about the "spam topic" to discuss a general roadmap for handling this problem. Just ping me ;-)

**Comment by hennevogel** [comment]
We are already planing this... https://trello.com/c/TswDwjVA
