### ISSUE TITLE
OBS doesn't support long hyperlinks.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [openSUSE/open-build-service#14544]
0. **Issue Description**

	I can't pull the source code from the origin URI due to its length – for whatever reason, https://files03.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE2ODAxNjUxNjgiLCJ1IjoiNzAwNzQ3IiwibHQiOiJkb3dubG9hZCIsInMiOiI0OWY4MmI3OGRmNzY5ZDQ2ZTdjNmVlZTMwY2VjNThkNzczNDVmN2MyYWVkODNmNGMxNDBlYWY2YjI4OWMxMDUzYTEyMmZiYmVkNDU2M2FhMGFkY2ZhYWNkMjE3Y2Q0MWQyNWM5MjgwZDUxM2I0ZGFhOTQwYWFlMjNiNWViOWI2NiIsInQiOjE2ODc1NDQ2NzMsInN0ZnAiOiI1NTE1Y2QwN2VmY2M3ODNlYzRkNTJjZjAxNWVmZjNmOSIsInN0aXAiOiIyYTAyOmM3Yzo2YWE2OjNmMDA6ZjIyZjo3NGZmOmZlMjM6NTVlZiJ9.g6tH1CWR__sdA6hSTO9nWf2k4fJcG1ca9MVav7pEzFY/ClamAV-GUI-0.5.0.tgz is truncated when pasted into `file_url` at https://build.opensuse.org/projects/home:rokejulianlockhart/packages/ClamAV-GUI/files/new or `package_details_url` at https://build.opensuse.org/package/show/home:rokejulianlockhart/ClamAV-GUI (the URL field visible when editing the repository metadata).

0. **Expected Result**

0. **How to Reproduce**

	1. Visit https://build.opensuse.org/projects/home:rokejulianlockhart/packages/ClamAV-GUI/files/new
	2. Paste https://files03.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE2ODAxNjUxNjgiLCJ1IjoiNzAwNzQ3IiwibHQiOiJkb3dubG9hZCIsInMiOiI0OWY4MmI3OGRmNzY5ZDQ2ZTdjNmVlZTMwY2VjNThkNzczNDVmN2MyYWVkODNmNGMxNDBlYWY2YjI4OWMxMDUzYTEyMmZiYmVkNDU2M2FhMGFkY2ZhYWNkMjE3Y2Q0MWQyNWM5MjgwZDUxM2I0ZGFhOTQwYWFlMjNiNWViOWI2NiIsInQiOjE2ODc1NDQ2NzMsInN0ZnAiOiI1NTE1Y2QwN2VmY2M3ODNlYzRkNTJjZjAxNWVmZjNmOSIsInN0aXAiOiIyYTAyOmM3Yzo2YWE2OjNmMDA6ZjIyZjo3NGZmOmZlMjM6NTVlZiJ9.g6tH1CWR__sdA6hSTO9nWf2k4fJcG1ca9MVav7pEzFY/ClamAV-GUI-0.5.0.tgz into `file_url`.

	1. Visit https://build.opensuse.org/package/show/home:rokejulianlockhart/ClamAV-GUI
	2. Click "Edit"
	3. Paste https://files03.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE2ODAxNjUxNjgiLCJ1IjoiNzAwNzQ3IiwibHQiOiJkb3dubG9hZCIsInMiOiI0OWY4MmI3OGRmNzY5ZDQ2ZTdjNmVlZTMwY2VjNThkNzczNDVmN2MyYWVkODNmNGMxNDBlYWY2YjI4OWMxMDUzYTEyMmZiYmVkNDU2M2FhMGFkY2ZhYWNkMjE3Y2Q0MWQyNWM5MjgwZDUxM2I0ZGFhOTQwYWFlMjNiNWViOWI2NiIsInQiOjE2ODc1NDQ2NzMsInN0ZnAiOiI1NTE1Y2QwN2VmY2M3ODNlYzRkNTJjZjAxNWVmZjNmOSIsInN0aXAiOiIyYTAyOmM3Yzo2YWE2OjNmMDA6ZjIyZjo3NGZmOmZlMjM6NTVlZiJ9.g6tH1CWR__sdA6hSTO9nWf2k4fJcG1ca9MVav7pEzFY/ClamAV-GUI-0.5.0.tgz into `package_details_url`.

0. **Further Information**

	* A link to an OBS instance showing the issue: https://build.opensuse.org/package/show/home:rokejulianlockhart/ClamAV-GUI
	* Exact server version: Unknown.

**Comment by bmwiedemann** [comment]
[related exception](https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/6495e28584bf46054c5b69cb) for devs.

    Mysql2::Error: Data too long for column 'url' at row 1

https://github.com/openSUSE/open-build-service/blob/4b4cf5ad6/src/api/app/models/package.rb#L1374 lists `url` as `string(255)` and your URL has 533 chars.

**Comment by Justinzobel** [comment]
Use the actual source code, not a file link from Pling. Pling generate download URLs for each download, so the above link will become in active after a period of time.

**Comment by eduardoj** [comment]
> 1. **Issue Description**
>        I can't pull the source code from the origin URI due to its length ...

@RokeJulianLockhart, I recognize two issues here:

- If you want to use the "URL:" text field to add information about your OBS package: yes, it currently fails without any further message when the URL is greater than 255 characters. I'll take care of this issue.
- If you want to pull source code from an URI: you should use the "Add an empty file or service " link from your package page. And then use the "File URL:" field. Again, you'll not be able to pull files from a URL longer than 200 characters. This is fixed in the interface. You won't face any unexpected errors.
