### ISSUE TITLE
"what's new" overlay hides information, and can't be removed if not logged in

### ISSUE THREAD

**Issue by cboltz** [openSUSE/open-build-service#14576]
# Issue Description

The "what's new" overlay hides information, and can't be removed / clicked away if you are not logged in.

![obs-news](https://github.com/openSUSE/open-build-service/assets/146882/b3e2b4dd-9e85-4b05-b8d5-e201aefd416b)

Try to see the build status... (yes, there's a small green line ;-)

Expected Result
============

- make it possible to close the overlay even if not logged in (and remember that in a session cookie) and/or
- drop "position: fixed" from the overlay so that it doesn't hide information, and scrolls away when scrolling down

How to Reproduce
===============
1. open any build.o.o page in a private browser window (to ensure you aren't logged in) when there's a news announcement shown
2. try to get rid of the news overlay

Further Information
===============
* Screenshot was taken at https://build.opensuse.org/package/live_build_log/openSUSE:infrastructure:Images:15.5/jeos/images/x86_64 - but any OBS page should do.

**Comment by bmwiedemann** [comment]
This likely comes from
https://github.com/openSUSE/open-build-service/blob/d5f0c54b/src/api/app/views/layouts/webui/webui.html.haml#L53

**Comment by hennevogel** [comment]
This is a (misused) feature, not a bug. We would have to track your visit to be able to do that and we don't want to.

**Comment by hennevogel** [comment]
fixed it on build.o.o just for you @cboltz 😘
