### ISSUE TITLE
Submitrequests from scmsync packages are sometimes broken for no apparent reason

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#14589]
# Issue Description

Submitting packages that are synced via `scmsync` are sometimes broken for no reason that is apparent to the end user, e.g.: https://build.opensuse.org/request/show/1096301. The diff shows that all sources are to be deleted, but the source package: https://build.opensuse.org/package/show/devel:Factory:git-workflow:staging:SCM_STAGING:par_text:1/par_text is doing just fine.

Looking into the request with osc reveals that OBS picked some srcmd5 for reasons that I do not understand:
```ShellSession
❯ osc request show 1096301|head -5
Request:    1096301
Created by: defolos

Actions:
  submit:       devel:Factory:git-workflow:staging:SCM_STAGING:par_text:1/par_text@d41d8cd98f00b204e9800998ecf8427e -> openSUSE:Factory
```
Especially given that the source package has just one commit at a completely **different** md5:
```ShellSession
❯ osc api "/source/devel:Factory:git-workflow:staging:SCM_STAGING:par_text:1/par_text/_history"
<revisionlist>
  <revision rev="1" vrev="1">
    <srcmd5>5b024c26dc26f42f43972e2011362a6b</srcmd5>
    <version>1.53.0+git.1584347654.eb0590f</version>
    <time>1688225547</time>
    <user>defolos</user>
    <comment>[info=6f8520d70a62e22a8bdc0fe43e5b4530af434ebd]</comment>
  </revision>
</revisionlist>
```

For the record, the revision that OBS picked does indeed exist and is unsurprisingly empty:
```ShellSession
❯ osc api "/source/devel:Factory:git-workflow:staging:SCM_STAGING:par_text:1/par_text?rev=d41d8cd98f00b204e9800998ecf8427e"
<directory name="par_text" rev="d41d8cd98f00b204e9800998ecf8427e" srcmd5="d41d8cd98f00b204e9800998ecf8427e">
</directory>
```

But I have no idea where this revision came from or why it was picked to create the submission.

Expected Result
============

Creating submitrequests from scmsync packages should not result in submissions that try to delete everything.

**Comment by hennevogel** [comment]
> But I have no idea where this revision came from or why it was picked to create the submission.

A `Project` with the OBS `Attribute` named `EnforceRevisionsInRequests` will set the md5 of the submitted directory as revision if the `BsRequest` doesn't include one. This is to make sure the source isn't updated in the middle of the review process.
