### ISSUE TITLE
SCM CI: support creating submit requests

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#14603]
**Is your feature request related to a problem? Please describe.**

We would like to get most if not all of the functionality currently implemented by https://github.com/openSUSE/scm-staging into OBS proper. One of the missing pieces is the ability to create submit requests from a pull request on gitea/gitlab/github.

**Describe the solution you'd like**

Provide a new OBS workflow step `submit_package` that could be used as follows:
```yaml
workflow:
  steps:
    - submit_package:
        target_project: openSUSE:Factory
```

OBS should then take the package that has been previously created either by `branch_package` or `link_package` and create a submission to the target project.

Optionally, one could specify the source package & project to use for the submission if there are no previously created packages (and one does not desire to create them). However, we don't need such a functionality at the moment.

**Describe alternatives you've considered**

We are currently rolling our own solution, but it would be nice to offload as much as possible to OBS.

**Comment by hennevogel** [comment]
Do you need specific time in the SCM workflow where this happens?

**Comment by dcermak** [comment]
> Do you need specific time in the SCM workflow where this happens?

There's a choice?

Eventually it would be nice to only create a submitrequest if there are approvals from the maintainer and some automated checks pass, but initially just the SR would be fine.

**Comment by hennevogel** [comment]
> There's a choice?

All of the SCMs include different "actions" in webhooks when there is activity on a pull/merge request. Github/Gitea for instance provide the standard stuff like: PR opened, PR synchronized & PR closed. But also more detailed things like PR assigned, PR labeled or PR reviewed. You can find the full list in the [docu](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request). 

We are currently limited in which of the PR actions we support. Hence my question about your workflow, so we can maybe prioritize stuff you need...

**Comment by dcermak** [comment]
> All of the SCMs include different "actions" in webhooks when there is activity on a pull/merge request. Github/Gitea for instance provide the standard stuff like: PR opened, PR synchronized & PR closed. But also more detailed things like PR assigned, PR labeled or PR reviewed. You can find the full list in the [docu](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request).

At the moment we really only care about gitea. Initially it would be good enough to create the SR on "PR opened", update it (if need be) on "PR synchronized" and close it on "PR closed".

**Comment by hennevogel** [comment]
>  update it (if need be) 

SR's can't be updated. Would you want a superseded SR on every PR synchronize?

**Comment by hennevogel** [comment]
And another question: What should happen to SRs if the PR is merged?

**Comment by hennevogel** [comment]
> For our workflow, we'd like the PR to get merged once the SR is accepted and not the other way around. Thus I don't have any requirements on this part. 

Okay that makes things we need to report to the PR more clear.

>  I think it'd be fine to just close the SR. Wouldn't the package that got branched by the SCM CI get deleted on PR merge anyway? That would close the SR automatically.

We currently don't distinguish between close and merged in that case. But that would be possible too of course. Maybe something for later if you don't need it...

**Comment by hennevogel** [comment]
> If there is a source change: yes

JFYI: synchronize means whenever a pull request's head branch was updated. The resulting source change on the OBS side might be the same, in case of a rebase for instance. I don't think it's distinguishable for us as we would have to track previous head branch and compare. You will probably have to have rules about that on your side or live with the superseded SRs...

**Comment by dcermak** [comment]
> JFYI: synchronize means whenever a pull request's head branch was updated. The resulting source change on the OBS side might be the same, in case of a rebase for instance. I don't think it's distinguishable for us as we would have to track previous head branch and compare. You will probably have to have rules about that on your side or live with the superseded SRs...

That sounds good to me. I don't think there's a sensible alternative to just superseding the previous request.

**Comment by dcermak** [comment]
Adrian Schröter ***@***.***> writes:

>> SR's can't be updated. Would you want a superseded SR on every PR synchronize?
>
> submit request actions can decide not to have a revision. So it would always follow the source. 
>
> However, this makes only sense when the review happens in git and not in requests anymore.

And it would break many assumptions about submitrequests. So let's not
do that.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Workflow::Step to create a BsRequest](https://trello.com/c/ZzeoLm50/226-create-workflowstep-to-create-a-bsrequest)

**Comment by hennevogel** [comment]
https://openbuildservice.org/2023/08/08/submit-step-for-the-scm-ci-integration/
