### ISSUE TITLE
repository cloned by bs_admin to another project is considered obsolete and deleted

### ISSUE THREAD

**Issue by tuminoid** [openSUSE/open-build-service#1461]
If you clone a repository using `bs_admin`'s clone repository option into different project (not just another repository in source project), scheduler considers all those packages obsoleted when it first scans new repository and deletes them instantly. Thus clone operation has zero effect.

**Comment by adrianschroeter** [comment]
Do you use the new full tree handling? (default since OBS 2.6, an option in 2.5)

**Comment by tuminoid** [comment]
Which setting determines that? We have 2.6 based installation, so it should be at default value.

**Comment by adrianschroeter** [comment]
okay, this is not how the clone repository call is supposed to used.

Can't you use the release mechanism? This will also copy the source containers. And this makes sure that scheduler won't cleanup.

I have added a few lines of documentation here:

http://openbuildservice.org/help/manuals/obs-reference-guide/cha.obs.product_building.html#idm140478961321504

**Comment by tuminoid** [comment]
Release mechanism sounds usable. Thank for the pointer, and the new docs.

I'd still like to point out that clone-repository does accept those arguments, and yet practically fails doing it. If it is not working or even supported, why not get rid of that form of the arguments, and/or improve the help so user can understand what it is supposed to be doing, if not the obvious?

**Comment by tuminoid** [comment]
Cleaning up my old issues. Its been 7 years, closing.
