### ISSUE TITLE
Using OBS to distribute already-built packages?

### ISSUE THREAD

**Issue by LebedevRI** [openSUSE/open-build-service#14624]
While building RPM's from `.spec` is reasonably nice,
handling of debian packages is not quite nice,
most especially because of having to upload a `.dsc`,
which would need to be manually kept up to date
from a manual deb build.

I see that there is a Download-On-Demand for repositories
to be used as build dependencies, but what about
redistributing (publishing/mirroring) existing repositories? Is that possible?

Also, normally a binary package is built on OBS and then published,
is there a way to just publish an already-build binary package?

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.libera.chat/openSUSE-buildservice) or on the [OBS mailing list](https://lists.opensuse.org/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.

**Comment by hennevogel** [comment]
@LebedevRI as my grandma used to say: you can eat everything (once) but not know everything.
