### ISSUE TITLE
AmazonLinux 2023 repositories do not work with OBS

### ISSUE THREAD

**Issue by cmouse** [openSUSE/open-build-service#14654]
# Issue Description
We are trying to use AmazonLinux2023 DoD repository and are facing a problem that we get 403 from the upstream repository server. This is because the HTTP client used by OBS does not normalize the request URL. The URL that OBS tries to download is `http://cdn.amazonlinux.com/al2023/core/guids/46ff4933b89b948580f3b223b826fee3c1830b85885db3f7f90502c0ac99698c/x86_64/../../../../blobstore/d4bc54fde91b3f7552dad9a45c65631e580f11da2c4ba704c6a3fe5eb419e251/acl-2.3.1-2.amzn2023.0.2.x86_64.rpm`, and if you try this with cURL it works because cURL normalizes the URL into `/al2023/blobstore/d4bc54fde91b3f7552dad9a45c65631e580f11da2c4ba704c6a3fe5eb419e251/acl-2.3.1-2.amzn2023.0.2.x86_64.rpm`, which then downloads just fine.

Expected Result
===========
Repository packages should download

How to Reproduce
===============
1. Create DoD repository
   -  Architecture: x86_64
   - Type: rpmmd
   - Url: https://cdn.amazonlinux.com/al2023/core/guids/46ff4933b89b948580f3b223b826fee3c1830b85885db3f7f90502c0ac99698c/x86_64/
 2. Create project which tries to download something from this repo
 3. It gets stuck

You can see further details with
```
# curl "http://localhost:5252/build/AmazonLinux:AmazonLinux2023/standard/x86_64/_repository?view=binaryversions&binary=acl"
<status code="403">
  <summary>http://cdn.amazonlinux.com/al2023/core/guids/46ff4933b89b948580f3b223b826fee3c1830b85885db3f7f90502c0ac99698c/x86_64/../../../../blobstore/d4bc54fde91b3f7552dad9a45c65631e580f11da2c4ba704c6a3fe5eb419e251/acl-2.3.1-2.amzn2023.0.2.x86_64.rpm: remote error: Forbidden</summary>
  <details>403 http://cdn.amazonlinux.com/al2023/core/guids/46ff4933b89b948580f3b223b826fee3c1830b85885db3f7f90502c0ac99698c/x86_64/../../../../blobstore/d4bc54fde91b3f7552dad9a45c65631e580f11da2c4ba704c6a3fe5eb419e251/acl-2.3.1-2.amzn2023.0.2.x86_64.rpm: remote error: Forbidden</details>
</status>
```

Further Information
===============
Exact server version: obs-server-2.10.20-lp153.109.1.noarch

**Comment by cmouse** [comment]
Any update here?

**Comment by cmouse** [comment]
just tried to fix this and it was about 2 line fix using URL::Normalize. Is is possible to please reconsider fixing this?

```patch
http://cdn.amazonlinux.com/al2023/core/guids/46ff4933b89b948580f3b223b826fee3c1830b85885db3f7f90502c0ac99698c/x86_64/../../../../blobstore/d4bc54fde91b3f7552dad9a45c65631e580f11da2c4ba704c6a3fe5eb419e251/acl-2.3.1-2.amzn2023.0.2.x86_64.rpm
```

**Comment by adrianschroeter** [comment]
On Freitag, 11. August 2023, 11:06:03 CEST Aki Tuomi wrote:
>  just tried to fix this and it was about 2 line fix using URL::Normalize. Is is possible to please reconsider fixing this?
> 
> ```patch
> diff -uN a/bs_repserver b/bs_repserver
> --- a/bs_repserver	2023-08-11 11:05:37.752180794 +0200
> +++ b/bs_repserver	2023-08-11 11:05:21.928022496 +0200
> @@ -82,6 +82,8 @@
>  use BSCando;
>  use Build;
>  
> +use URL::Normalize;
> +

oh well, please create a pull request, but please move this dependency to BSRepServer/DoD.pm

>  # configure Build module for buildinfo queries
>  $Build::Rpm::unfilteredprereqs = 1 if defined $Build::Rpm::unfilteredprereqs;
>  $Build::Rpm::conflictdeps = 1 if defined $Build::Rpm::conflictdeps;
> @@ -149,6 +151,8 @@
>    $url .= $pool->pkg2path($p);
>    my $tmp = "$reporoot/$reponame/$arch/:full/.dod.$$.$pkgname";
>    #print "fetching: $url\n";
> +  my $n = URL::Normalize->new($url);
> +  $url = $n->remove_dot_segments;

and this above the print line.

>    my $param = {'uri' => $url, 'filename' => $tmp, 'receiver' => \&BSHTTP::file_receiver, 'proxy' => $proxy};
>    $param->{'maxredirects'} = $maxredirects if defined $maxredirects;
>    my $r;
> /x86_64/../../../../blobstore/d4bc54fde91b3f7552dad9a45c65631e580f11da2c4ba704c6a3fe5eb419e251/acl-2.3.1-2.amzn2023.0.2.x86_64.rpm



-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH, Frankenstraße 146, 90461 Nürnberg, Germany
(HRB 36809, AG Nürnberg) Geschäftsführer: Ivo Totev

**Comment by cmouse** [comment]
Thanks, I'll take a look at this after next week.
