### ISSUE TITLE
Notifications: Add a way to select accepted requests

### ISSUE THREAD

**Issue by luc14n0** [openSUSE/open-build-service#14675]
Project maintainers overseeing hundreds of packages usually will have their **Notifications** page filled with *lots* of accepted request quickly, depending on how fast upstream moves. And personally I like to mark them as read while leaving requests with state `new`/`review` there until they move on (get accepted, declined or superseded).

Currently we have a **Select All** checkbox next to the **Mark selected as 'Read'** button. It would be really nice also have a **Select Accepted Requests** - or just **Select Accepted** - checkbox that would show up in the default view - without filters - and the **Requests** filtered view.

Cleaning up dozens, sometimes hundreds of accepted requests notifications - if I procrastinate - manually is no fun.

**Comment by luc14n0** [comment]
Oh, I see we got some new filters:

![image](https://github.com/openSUSE/open-build-service/assets/31497094/a5d1ee6e-d313-43c6-875c-0e80f61fec71)

Perhaps, instead of going with my initial proposition of adding a **Select Accepted Requests**/**Select Accepted** checkbox, an **Accepted Requests** filter makes more sense now.

**Comment by saraycp** [comment]
https://trello.com/c/7OGCmSp7/152-implementation-filters-for-bsrequests-states

**Comment by saraycp** [comment]
Hi @luc14n0! Based on your suggestion, we have extended the requests filtering. From now on, you can also filter the requests by type, not only the accepted ones. We hope this is helpful!

![Screenshot from 2024-07-10 08-55-56](https://github.com/openSUSE/open-build-service/assets/114928900/65070e11-46b1-47c6-86c5-fdd3fdfdb3e1)

I'm closing this issue, but feel free to file any issue if you find some.

**Comment by luc14n0** [comment]
Oh, that's wonderful news. I'm sure many of us will find it helpful :+1:
