### ISSUE TITLE
regression: local 'osc build' fails since Jan 21

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#1467]
Calling 'osc build' locally fails with:

Building gnome-shell.spec for openSUSE_Factory/x86_64
Getting buildinfo from server and store to /home/dimstar/Documents/osc/GNOME/Next/gnome-shell/.osc/_buildinfo-openSUSE_Factory-x86_64.xml
Server returned an error: HTTP Error 400: Bad Request
remote error: remote error  unknown parameter 'parseremote'

(same error happens with osc buildinfo)

**Comment by DimStar77** [comment]
trying to build for example openSUSE:Factory/aaa_base

osc -d build

Building aaa_base.spec for standard/x86_64
Getting buildinfo from server and store to /home/dimstar/Documents/osc/openSUSE:Factory/aaa_base/.osc/_buildinfo-standard-x86_64.xml
POST https://api.opensuse.org/build/openSUSE:Factory/standard/x86_64/aaa_base/_buildinfo
Server returned an error: HTTP Error 400: Bad Request
Date: Thu, 21 Jan 2016 08:57:51 GMT
Server: Apache/2.2.12 (Linux/SUSE)
Strict-Transport-Security: max-age=31536000
Cache-Control: no-cache
Vary: Accept-Encoding
X-XSS-Protection: 1; mode=block
X-Opensuse-Runtimes: {"view":0.771065941080451,"db":9.56996,"backend":80.22935100000001,"xml":0.114384}
X-Request-Id: 1c6e7e2a-22e1-448b-9a26-bc0b519ab11e
X-Opensuse-APIVersion: %version
X-Runtime: 0.105755
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Powered-By: Phusion Passenger 5.0.22
Status: 400 Bad Request
Content-Type: application/xml; charset=utf-8
Connection: close
Transfer-Encoding: chunked

<status code="400" origin="backend">
  <summary>remote error: remote error  unknown parameter 'parseremote'</summary>
  <details>400 remote error: remote error  unknown parameter 'parseremote'</details>
</status>
remote error: remote error  unknown parameter 'parseremote'

**Comment by adrianschroeter** [comment]
fixed
