### ISSUE TITLE
osc api about returns <revision>%version</revision>

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#1468]
~> osc api about
<about>
  <title>Open Build Service API</title>
  <description>API to the Open Build Service</description>
  <revision>%version</revision>
</about>

Same happens when doing the request to our test instance. On my development machine I get: <revision>2.5.50</revision>. So this might be a configuration issue.

**Comment by coolo** [comment]
this is done in the package AFAIK

**Comment by coolo** [comment]
62f306921299d5f8b6979ca8bdf6c722e3a0ca5f moved the %version replacement from obs-server.spec to src/api/Makefile - but in that Makefile there is no %version expansion. So the spec file %version is lost

**Comment by coolo** [comment]
@M0ses ^

**Comment by M0ses** [comment]
Thanks for hints,

working on it:

https://github.com/M0ses/open-build-service/tree/fix_version_string_in_api

**Comment by M0ses** [comment]
fixed
