### ISSUE TITLE
Increase default GPG key size in setup-appliance.sh to 4096?

### ISSUE THREAD

**Issue by johanneskastl** [openSUSE/open-build-service#14709]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The `setup-appliance.sh` script generates a GPG key with 2048 bits. It might be a good idea to increase that to 4096, as I guess many OBS admins use that script to get started and might not change the key afterwards.

**Describe alternatives you've considered**
Keeping the existing default.

**Comment by varshneydevansh** [comment]
Can I start from this? Although I will start in a few days. =)

**Comment by pedrocarr** [comment]
I think this is already done inside the `prepare_obssigner` function which is on `functions.setup-appliance.sh` and it's being used `setup-appliance.sh`

<img width="1668" alt="Screenshot 2024-01-30 at 15 07 57" src="https://github.com/openSUSE/open-build-service/assets/45405776/31fb659a-1293-4844-a451-e3d093620c56">
