### ISSUE TITLE
Add a checkbox for project search to be case insensitive

### ISSUE THREAD

**Issue by pevik** [openSUSE/open-build-service#14718]
https://build.opensuse.org/search/owner
I'd like to put opensuseway and find https://build.opensuse.org/package/show/X11:Wayland/openSUSEway

**Comment by hennevogel** [comment]
You can for the project/package search. Owner search is something else entirely. 

https://build.opensuse.org/search?search_text=opensuseway&search_for=0&name=1&attrib_type_id=
