### ISSUE TITLE
Build error in openSUSE leap 15.4: nothing provides rpmlint-mini needed by rpmlint-Factory  

### ISSUE THREAD

**Issue by wb0716** [openSUSE/open-build-service#14749]
In openSuse leap 15.4,
rpmlint-Factory will require rpmlint-mini,
but rpmlint-mini is not in its repository.
You can check:  https://download.opensuse.org/distribution/leap/15.4/repo/oss/

So it will show the above error.

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of openSUSE packagers and developers that support each other in their usage of the OBS. They meet online in a the openSUSE Packaging IRC chat (irc://irc.opensuse.org/openSUSE-packaging) or on the [OBS mailing list](https://lists.opensuse.org/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something.

Thank you for your consideration.
