### ISSUE TITLE
'unresolvable' status of appimage build

### ISSUE THREAD

**Issue by linuxhw** [openSUSE/open-build-service#14768]
Hello

Appimages have stopped to build. Instead I see 'unresolvable' status of new builds w/o any building activity.

![Screenshot-20230806180646-483x305](https://github.com/openSUSE/open-build-service/assets/15686469/677745bc-f2ea-463d-8166-fc2b9aa60386)

**Comment by linuxhw** [comment]
The project is https://build.opensuse.org/package/show/home:linuxbuild/hw-probe

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other with software packaging with the OBS. They meet online in a the openSUSE Packager IRC chat (irc://irc.libera.chat/openSUSE-packaging) or on the [packaging mailing list](https://lists.opensuse.org/archives/list/packaging@lists.opensuse.org/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other packager community members. 

Thank you for your consideration.
