### ISSUE TITLE
gitea push events of a scm-synced package fork result in a broken package on OBS

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#14776]
# Issue Description

I have enabled `scmsync` on my package [vagrant-libvirt](https://build.opensuse.org/package/show/Virtualization:vagrant/vagrant-libvirt) so that it is synced from gitea: https://src.opensuse.org/pool/vagrant-libvirt.
Additionally, I added a [`.obs/workflows.yml`](https://src.opensuse.org/pool/vagrant-libvirt/src/branch/factory/.obs/workflows.yml) and added the corresponding webhook to my fork: https://src.opensuse.org/defolos/vagrant-libvirt. A push to the `factory` branch resulted in the workflow https://build.opensuse.org/my/tokens/7481/workflow_runs/185438 and the following package: https://build.opensuse.org/package/show/devel:Factory:git-workflow:staging:defolos:vagrant-libvirt/vagrant-libvirt-eb3031953a893c641167a754e014aeb9b5524a46

The package is totally broken, because the `scmsync` url is wrong:
```xml
  <scmsync>https://src.opensuse.org/pool/vagrant-libvirt#eb3031953a893c641167a754e014aeb9b5524a46</scmsync>
```

The problem is that the url should point to `defolos/vagrant-libvirt` and not to `pool/vagrant-libvirt`. OBS has to correct the scmsync url using `source_repository_full_name`:
https://github.com/openSUSE/open-build-service/blob/7930b985c9421fe61ec6169dcbb9dc09053c2bcb/src/api/app/models/gitea_payload/push.rb#L9

This should probably happen in: https://github.com/openSUSE/open-build-service/blob/7930b985c9421fe61ec6169dcbb9dc09053c2bcb/src/api/app/models/concerns/scm_sync_enabled_step.rb#L2

**Comment by hennevogel** [comment]
Why would you setup the webhook on to the fork?

**Comment by dcermak** [comment]
I did it just for testing

**Comment by hennevogel** [comment]
Well if you set the webhook up on the fork then the fork becomes what this is about. You change **the fork** and not upstream. 

We also talked offline and I explained how this makes not much sense.
