### ISSUE TITLE
Broken OBS2.10 Appliance Installer Link

### ISSUE THREAD

**Issue by davidaniva** [openSUSE/open-build-service#14775]
The OBS2.10 Appliance Installer is not available. The link at https://openbuildservice.org/download/ links to https://download.opensuse.org/repositories/OBS:/Server:/2.10/images/iso/obs-server.x86_64-oem.iso returns:

 Resource is no longer available!
The requested URL is no longer available on this server and there is no forwarding address. Please inform the author of the [referring page](https://openbuildservice.org/) that the link is outdated.

If you think this is a server error, please contact the [webmaster](mailto:webmaster@opensuse.org).

Error 404
[download.opensuse.org](https://download.opensuse.org/)
Apache

**Comment by eduardoj** [comment]
Yes. this file wasn't available for a while. It should be fixed now. Thanks for reporting the issue.
