### ISSUE TITLE
Cannot set the name field of a token

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#14811]
The swagger docs mention the `name` parameter of a token: https://api.opensuse.org/apidocs/index#/Person/post_person__login__token as well as the schema documentation:
https://github.com/openSUSE/open-build-service/blob/cc034e0bd4b75ad1a31a17c5d9f43a0d1a5f3959/docs/api/api/tokenlist.rng#L50C26-L50C26

However, it is impossible to either set or read the name of this field:
```ShellSession
❯ osc api -X POST "/person/dancermak/token?cmd=create&name=foobar&description=bazbarf"
<status code="ok">
  <summary>Ok</summary>
  <data name="token">REDACTED</data>
  <data name="id">7523</data>
</status>

❯ osc api "/person/dancermak/token"
<directory count="1">
  <entry id="7523" string="REDACTED" kind="service" description="bazbarf" triggered_at=""/>
</directory>

```

**Comment by hennevogel** [comment]
That is because there is no name field...

**Comment by dcermak** [comment]
Both documents claim the opposite.
