### ISSUE TITLE
Files `_buildenv` and `_statistics` are returned into the list of built binaries

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#14823]
# Issue Description

The endpoint `GET /build/{project_name}/{repository_name}/{architecture_name}/{package_name}`, documented [here](https://api.opensuse.org/apidocs/index.html#/Build/get_build__project_name___repository_name___architecture_name___package_name_), returns the files `_buildenv` and `_statistics` into the list of binaries built by the sources of the specified package.

Expected Result
============

Both files `_buildenv` and `_statistics` should not be returned into the list of build artifacts, in that endpoint.

We can always access the contents of those files with the following endpoints:
- `GET /build/{project_name}/{repository_name}/{architecture_name}/{package_name}/_buildenv`, documented [here](https://api.opensuse.org/apidocs/index.html#/Build/get_build__project_name___repository_name___architecture_name___package_name___buildenv),

- `GET /build/{project_name}/{repository_name}/{architecture_name}/{package_name}/_statistics`, documented [here](https://api.opensuse.org/apidocs/index.html#/Build/get_build__project_name___repository_name___architecture_name___package_name___statistics).

How to Reproduce
===============
1. `osc api "/build/openSUSE:Factory/standard/x86_64/qemu"`
2. See result:
   ```
   <binarylist>
     <binary filename="_buildenv" size="242113" mtime="1691889166"/>
     <binary filename="_statistics" size="1110" mtime="1691889166"/>
     <binary filename="qemu-8.0.4-1.2.src.rpm" size="177885078" mtime="1691889170"/>
     [...]
     <binary filename="qemu-x86-debuginfo-8.0.4-1.2.x86_64.rpm" size="29317696" mtime="1691889185"/>
     <binary filename="rpmlint.log" size="9144" mtime="1691889166"/>
   <binarylist>
   ```

Further Information
===============
* https://trello.com/c/qBYnhEAb/2979-get-build-buildenv-and-statistics

**Comment by adrianschroeter** [comment]
that is intentional, they are just generated files after all and part of the buid result.

They are not "a special endpoint".

**Comment by adrianschroeter** [comment]
and not listing them would break download tools

**Comment by eduardoj** [comment]
> and not listing them would break download tools

What are the download tools you are referring to? Those download tools could also be modified.

**Comment by bmwiedemann** [comment]
e.g. I fetch and use _buildenv in
https://github.com/bmwiedemann/reproducibleopensuse/blob/abeb3c6c/nachbau#L19
via `osc getbinaries`

**Comment by eduardoj** [comment]
> e.g. I fetch and use _buildenv in https://github.com/bmwiedemann/reproducibleopensuse/blob/abeb3c6c/nachbau#L19 via `osc getbinaries`

Then this code would simply perform the same:
```bash
osc getbinaries $repo $arch _buildenv || exit 16
osc getbinaries $repo $arch || exit 16
```

This is code which should work now, and after `_buildenv` gets removed from the list of artifacts.

**Comment by adrianschroeter** [comment]
we have a stable api, what is the point of removing files used to be there?

As I said before, these files a part of the build result and should be handled like that. It is not something what the middleware is making up dynamicly.

**Comment by eduardoj** [comment]
> we have a stable api, what is the point of removing files used to be there?

Most likely I'm missing something, but the endpoint (this one: `GET /build/{project_name}/{repository_name}/{architecture_name}/{package_name}`) returns a list of files always including the files `_buildenv` and `_statistics`. I don't see a case where those files aren't returned. I find it unnecessary redundant.

Why do we need to include the files `_buildenv` and `_statistics` in that list? And why do we **always** need to include them?

> As I said before, these files a part of the build result and should be handled like that. It is not something what the middleware is making up dynamicly.

These files are a part of the build result only if the build happens in an OBS instance, if I'm not wrong.

**Comment by adrianschroeter** [comment]
On Donnerstag, 24. August 2023, 10:22:36 CEST Eduardo J. wrote:
> > we have a stable api, what is the point of removing files used to be there?
> 
> Most likely I'm missing something, but the endpoint (this one: `GET /build/{project_name}/{repository_name}/{architecture_name}/{package_name}`) returns a list of files always including the files `_buildenv` and `_statistics`. I don't see a case where those files aren't returned. I find it unnecessary redundant.
> 
> Why do we need to include the files `_buildenv` and `_statistics` in that list? And why do we **always** need to include them?

Let me ask the opposite, they are build result files. A result from the build process.
Why should we filter them with special rules?

> > As I said before, these files a part of the build result and should be handled like that. It is not something what the middleware is making up dynamicly.
> 
> These files are a part of the build result only if the build happens in an OBS instance, if I'm not wrong.

that is true.

in any case, we have these since years now, I see no reason why we need to become incompatible now.

-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH, Frankenstraße 146, 90461 Nürnberg, Germany
(HRB 36809, AG Nürnberg) Geschäftsführer: Ivo Totev
