### ISSUE TITLE
"Have choice" message should show path for packages

### ISSUE THREAD

**Issue by darix** [openSUSE/open-build-service#1482]
```
openSUSE_42.1        i586       unresolvable: have choice for liburcu.so.2 needed by knot2: liburcu2 liburcu0
openSUSE_42.1        x86_64     unresolvable: have choice for liburcu.so.2()(64bit) needed by knot2: liburcu2 liburcu0
```

it would be nice to know without manually debugging with "osc ls -b" to know where the backend saw each package.

**Comment by mlschroe** [comment]
It already does this if you use 'osc buildinfo --debug'.

**Comment by darix** [comment]
1. why not have it by default?
2. the webui still does not show the information.
