### ISSUE TITLE
Can't exec "debtransformxz": No such file or directory

### ISSUE THREAD

**Issue by pbek** [openSUSE/open-build-service#1483]
First a big thank you for the the **awesome** openSUSE build service!

At <https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop> I was building for openSUSE, Fedora and Arch and it worked great.

When I tried also to build for Debian I had the issue that I need a `.tar.gz` as archive.
OBS should be able to convert the `.tar.xz` archive, that is needed by all other targets (otherwise the build fails), thanks to <https://github.com/openSUSE/obs-build/commit/31e0e4c96cf0ac27d3ffeb5ac6ae43dd0cd33a8e>.

But when building for Debian I got this error message at <https://build.opensuse.org/package/live_build_log/home:pbek:QOwnNotes/desktop/Debian_8.0/i586>:
```
[  112s] Attempting automatic discovery of a debian archive.
[  112s] converting //usr/src/packages/SOURCES/qownnotes-0.84.5.tar.xz to qownnotes-0.84.5.tar.gz
[  112s] Can't exec "debtransformxz": No such file or directory at /.build/debtransform line 343.
[  112s] cannot transform .tar.xz to .tar.gz at /.build/debtransform line 343.
```

Also uploading a `.tar.gz` doesn't work, because then OBS doesn't know which archive to use for the Debian build.

Am I missing something?
Thanks again for OBS and keep up the great work!

Cheers, Patrizio

**Comment by bugfinder** [comment]
fixed in git for the build script (debtransformxz was there but not being installed), so I fixed the Makefile

**Comment by pbek** [comment]
Thanks a lot, @bugfinder ! It's already working.
