### ISSUE TITLE
500: Internal Server Error

### ISSUE THREAD

**Issue by viikei** [openSUSE/open-build-service#14849]
I installed obs on the suse15.5 operating system, but when I click on the created project, the page reports an error, as shown below:
![image](https://github.com/openSUSE/open-build-service/assets/62841836/5f3c7094-2a56-4dfa-b0bf-1563bbb72672)
![image](https://github.com/openSUSE/open-build-service/assets/62841836/9d2c52f2-16a1-464c-bddd-364be4a7a466)

**Comment by hennevogel** [comment]
You installed which OBS and how? Please provide some details.

**Comment by viikei** [comment]
My mistake, I did not have a dns server, and at the same time, I misconfigured the domain name resolution in the hosts file, which caused the web page to be unstable. After reconfiguration, the page was restored
