### ISSUE TITLE
Delete associated comment notifications in 'mark_as_spammer!' method on user model

### ISSUE THREAD

**Issue by krauselukas** [openSUSE/open-build-service#14874]
# Issue Description

Right now the `mark_as_spammer!` method deletes the comments associated with the user, but leaves behind the notifications that are associated with the comments. This causes a code 500 (see https://github.com/openSUSE/open-build-service/issues/14460) when the user tries to access the notification index view, since the notifiable of the notification is `nil`.

Expected Result
============
The associated notifications are deleted as well.

How to Reproduce
===============
1. Create a comment with user `foo` on a package or project where user `bar` is subscribed to and receives a notification.
2. Delete user `foo` who created the comment with the `mark_as_spammer!` method.
3. See the associated notification still existing in the DB with the notifiable being `nil`.

**Comment by hennevogel** [comment]
Hm... 

https://github.com/openSUSE/open-build-service/blob/053dc7b1830eaeb95a5f4b8f7b0d1d39a7baf3e9/src/api/app/models/comment.rb#L20
