### ISSUE TITLE
Can't download files without logging in

### ISSUE THREAD

**Issue by mixedCase** [openSUSE/open-build-service#1488]
Hello, I can't seem to be able to download files from build.opensuse.org without being logged in.

Example: `https://build.opensuse.org/source/home:jejb1:UEFI/sbsigntools/sbsigntools_0.7.99.orig.tar.gz` from the project `https://build.opensuse.org/package/show/home:jejb1:UEFI/sbsigntools` returns 401 Unauthorized.

If I do it from the web UI, the page just reloads.

Is this intentional or is this a bug?

**Comment by adrianschroeter** [comment]
That is a bug, it should not be possible (for bandwidth protection). Regression from webui merge.

**Comment by mixedCase** [comment]
>it should not be possible (for bandwidth protection)

This statement is throwing me off a bit, so should it be possible or not to download files without logging in?
If not, then I take it there's no bug.

**Comment by adrianschroeter** [comment]
ah, I misunderstood then. No, it should NOT be possible on purpose for bandwidth protection. We ship the src.rpms already via the mirrors. Please note we make a difference here between the tar balls and the patches.
