### ISSUE TITLE
How to improve the performance of the scheduler program

### ISSUE THREAD

**Issue by Zeno-sole** [openSUSE/open-build-service#14944]
The scheduler program can only work using a single thread, which results in very slow calculations

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of OBS developers and admins that support each other with developing and operating the OBS. They meet online in a the OBS IRC chat (irc://irc.libera.chat/openSUSE-buildservice) or on the [OBS mailing list](https://lists.opensuse.org/archives/list/buildservice@lists.opensuse.org/)).

Over there you can ask questions if you have trouble understanding something, you can seek advice and mingle with the OBS operator community.

Thank you for your consideration.
