### ISSUE TITLE
OBS fails to set CI_CNT.B_CNT in Debian builds

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#1496]
```
[   33s] -----------------------------------------------------------------
[   33s] I have the following modifications for gsoap-zarafa.spec:
[   33s] 5c5
[   33s] < Release:        0
[   33s] ---
[   33s] > Release:        23.1
[   33s] -----------------------------------------------------------------
[   33s] ----- building gsoap-zarafa.spec (user abuild)
[   33s] -----------------------------------------------------------------
```
This substitution is only done for RPM specfiles, but not for the Debian descriptions. This leads to rebuilds always carrying the same filename even if CI_CNT or B_CNT actually increased, and `apt-get dist-upgrade` will subsequently never pick the new builds for installation because of this.

**Comment by dg0yt** [comment]
It seems to be missing from the [wiki page](https://en.opensuse.org/openSUSE:Build_Service_Debian_builds):

You need to have ```DEBTRANSFORM-RELEASE: 1``` in your .dsc file. See https://github.com/openSUSE/obs-build/commit/53e20ebf890c7c140e7846a3ce82078d0ea79fef.

**Comment by dg0yt** [comment]
You must also provide a separate "debian.changelog" file with at least one changelog entry, according to that commit. I updated to wiki page.

**Comment by hennevogel** [comment]
Thanks for the edits @dg0yt

**Comment by dg0yt** [comment]
For the record, DEBTRANSFORM-RELEASE will work (debtransform will be run) only if there is any debian.* file. It doesn't need to be the changelog.

It is implemented in build-recipe-dsc and debtransform which reside in the https://github.com/openSUSE/obs-build repository.

**Comment by adrianschroeter** [comment]
that functionality is just not implemented in the build script. You may want to create a pull request for build-recipe-arch ...
