### ISSUE TITLE
Public endpoint for repositories

### ISSUE THREAD

**Issue by kalabiyau** [openSUSE/open-build-service#1497]
The endpoint in question is

```
https://<xxxx>/public/source/SUSE:SLE-12:GA/_product?view=productrepositories&product=SLES&format=xml
```

It returns 

```xml
<status code="400">
  <summary>unknown parameter 'format'</summary>
</status>
```

**Comment by adrianschroeter** [comment]
On Dienstag, 2. Februar 2016, 07:53:40 CET wrote Artem Chernikov:
> The endpoint in question is
> 
> ```
> https://<xxxx>/public/source/SUSE:SLE-12:GA/_product?view=productrepositories&product=SLES&format=xml
> ```
> 
> It returns 
> 
> ```xml
> <status code="400">
>   <summary>unknown parameter 'format'</summary>
> </status>

format is not an official supported parameter for all calls.

You would always need to know where the call is implemented.

Please just use api.opensuse.org host and it will provide 
the api format (usually xml).

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imend�rffer, Jane Smithard, Graham Norton, HRB 21284 (AG N�rnberg) 
 
Maxfeldstra�e 5                         
90409 N�rnberg 
Germany

**Comment by kalabiyau** [comment]
@adrianschroeter I am afraid I am specifically interested in the `api.suse.de` rather than `api.opensuse.org` as that endpoint we use in SCC and we just need to know how to call it via public namespace
