### ISSUE TITLE
Allow to search for Submit Request IDs

### ISSUE THREAD

**Issue by lrupp** [openSUSE/open-build-service#14982]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I got a submit request ID posted somewhere and want to look after it. Via osc, this is a simple `osc rq show $ID` call away. But I could not find a solution for the WebUI so far that allows something similar simple.

**Describe the solution you'd like**
Either one of the two - or both:
1. Allow to search for requests in the "Search" field at the top right of the WebUI. If the search string just contains numbers (maybe even limited to numbers between 1,000,000 and 2,000,000)
2. In the detailed search (section "Search issues"), just include another item allowing to search for 'RQ' issues, which will return the requests from the local OBS instance.

In any way, please include a short information in the search results containing:
* (linked) ID
* Description
* Source
* Target
* Type
* Priority
* Requester
* Created 
* Updated

**Describe alternatives you've considered**

* osc is a clear alternative, but not helpful if you don't have a terminal available
* a generic bookmark containing https://build.opensuse.org/request/show/ helps, even if it first throws a 404 error, someone can enter the request ID in question afterward

**Comment by lrupp** [comment]
How cool is that!?!
Where can I find this documented?

**Comment by hennevogel** [comment]
Documentation is here: https://github.com/openSUSE/obs-docu/
