### ISSUE TITLE
api should be User-Agent agnostic

### ISSUE THREAD

**Issue by kalabiyau** [openSUSE/open-build-service#1505]
Generally good idea to not to enforce any behavior in the API based on user-agent header.
So, when browser (which is totally valid user-agent) is used for the same endpoints as e.g. curl - that should have exactly the same behavior

**Comment by coolo** [comment]
it does as long as you request the same mimetypes than a browser.

**Comment by hennevogel** [comment]
What @coolo is trying to say is that the user agent has nothing to do with it. See WebuiMatcher and APIMatcher in [config/routes.rb](https://github.com/openSUSE/open-build-service/blob/master/src/api/config/routes.rb)
