### ISSUE TITLE
Inconsistent naming for service/runservice tokens

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#15078]
# Issue Description

The runservice/service type tokens are named inconsistently in the API:
1. When creating a token via `POST /person/$name/token?type=runservice` you have to specify `runservice` as the type
2. When querying tokens via `GET /person/$name/token` they appear as `kind="service"`:

This difference makes it inconvenient to use in API wrappers as you have to handle both values as the same one.

Expected Result
============

The token kind name should be the same.

**Comment by dmarcoux** [comment]
Hey @dcermak,

I had a look just now and this isn't a bug. The _POST_ should have been `POST /person/$name/token?operation=runservice`. See the API documentation about this endpoint [here](https://api.opensuse.org/apidocs/index#/Person/post_person__login__token).

**Comment by dcermak** [comment]
That was not the point of my report. The point is that the POST is with operation=**runservice** while the GET responds with **service**.

**Comment by dmarcoux** [comment]
Oh right. Sorry for that. I understand now. I'm reopening the issue.
