### ISSUE TITLE
enable build-compare for cycles

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/open-build-service#15108]
# Issue Description
We want to avoid publishing binary packages that have not changed in a rebuild. However, OBS skips `build-compare` for packages with `baselibs.conf` that are considered part of a cycle. The original intention was to keep internal meta data small.

Expected Result
============
build-compare should run as it does with other packages.

How to Reproduce
===============
1. go to zstd package
2. click rebuild
3. watch new version with increased rebuild counter published

**Comment by mlschroe** [comment]
https://github.com/openSUSE/open-build-service/commit/d8d6ef215df765d756c1d36bb1a49195427239ea
