### ISSUE TITLE
The revoked badge in a request page is rendered a big misaligned

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#15111]
# Issue Description
The revoked state badge is rendering a bit weird: the slash is a bit misaligned.

![image](https://github.com/openSUSE/open-build-service/assets/2650/dede6c8f-bc8e-49f7-b52b-16979d5554e1)

Expected Result
============
That the badge is rendered properly.

How to Reproduce
===============
1. Go to https://build.opensuse.org/request/show/718975
2. The slash in the "revoked" badge is misaligned.

**Comment by dmarcoux** [comment]
I cannot reproduce this issue on Firefox and Chromium. It looks just like it should:

![revoked](https://github.com/openSUSE/open-build-service/assets/1102934/67d63d2d-8e26-47a5-b998-52f99ccb5bfb)

**Comment by danidoni** [comment]
I cannot reproduce it again... Closing.
