### ISSUE TITLE
Inline comments cannot be replied to

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#15157]
**Is your feature request related to a problem? Please describe.**

It is not possible to reply to inline comments because of a lack of a Reply button underneath it (cf. e.g. https://build.opensuse.org/request/show/1121472 ). As a result, if I *do* have something to comment, I can only make a normal comment, but this does not seem to trigger a notification to the author of the inline comment.

**Describe the solution you'd like**

Disallow inline comments.

**Describe alternatives you've considered**

Support replies to inline comments.

**Comment by danidoni** [comment]
Looks like I have a reply button:
![image](https://github.com/openSUSE/open-build-service/assets/2650/42079e8a-6d10-4e94-b6b3-ded80205fddb)

Is this what you are referring to?

**Comment by jengelh** [comment]
This is the UI I am presented with.

![1](https://github.com/openSUSE/open-build-service/assets/8861948/f4ef1ec6-0c45-4d06-b8c0-021f5d834153)
