### ISSUE TITLE
Fedora prjconf lacks some macro definitions

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/open-build-service#15159]
# Issue Description

We imported a package that builds for Fedora with `mock` but found that it does not build when imported into OBS
https://build.opensuse.org/package/show/home:marmarek:QubesOS/qubes-db

Because our Fedora:39 prjconf lacks a define
```
%python3_pkgversion 3
```

Expected Result
============
We should be able to build packages for Fedora without too many extra steps.

**Comment by mlschroe** [comment]
I added
```
# important macros
DistMacro: python3_pkgversion 3
```
to the prjconf of Fedora:39 and Fedora:Rawhide. Please reopen if you need more macros.

**Comment by mlschroe** [comment]
(Side note: Do not (mis-)use the Macros section for this.)
