### ISSUE TITLE
Show number of downloads of a package for each OS/architecture

### ISSUE THREAD

**Issue by jstaf** [openSUSE/open-build-service#15171]
**Is your feature request related to a problem? Please describe.**
It would be nice to see download stats for architectures and packages published on build.opensuse.org. Fedora COPR does this, but OBS does not. There are two reasons to do this:

* It makes maintainers feel nice to see that their software is getting used. :slightly_smiling_face: 
* Maintainers can see which distributions and architectures are relatively unused, making it easier to make decisions about dropping support for an OS or architecture when writing or building packages. (Perhaps you want to use a new feature or package from the latest Tumbleweed release when building software, but Ubuntu 20.04 doesn't have the feature you need, so you want to gauge how many users you'd actually lose if you dropped support for Ubuntu 20.04.)

**Describe the solution you'd like**
Some page on build.opensuse.org where I can see how many times a package has been downloaded, similar to https://copr.fedorainfracloud.org/coprs/jstaf/onedriver/

**Describe alternatives you've considered**
I don't really want to build telemetry into software just to see download stats.

**Additional context**
Just a direct copy of COPR's functionality would be nice: https://copr.fedorainfracloud.org/coprs/jstaf/onedriver/. It would be nice to see both total # of downloads for all time ("this software has been used by X number of users!") and total # of downloads in the last Y number of days ("no one actually uses my aarch64 builds, therefore I don't actually need to support aarch64").

**Comment by hennevogel** [comment]
OBS is not handling downloads but passes this on to however you serve your repositories. build.opensuse.org for instance passes it on to openSUSEs [MirrorCache](https://github.com/openSUSE/MirrorCache) CDN.

**Comment by jstaf** [comment]
Ok, maybe this is just a case of missing documentation or something. Is there a way to get stats for build.opensuse.org downloads?

**Comment by hennevogel** [comment]
> Ok, maybe this is just a case of missing documentation or something. Is there a way to get stats for build.opensuse.org downloads?

You mean for the MirrorCache CDN? You will have to ask them please. I'm not aware. @andrii-suse maybe does...

**Comment by andrii-suse** [comment]
I was planning to add something like this to download.o.o, despite that that would miss stats when packages were downloaded from mirrors directly. When we are leaning towards using  CDN.o.o as primary site, that would be even more tricky, unless Dirk has an idea.

**Comment by jstaf** [comment]
Yeah it would just be nice to have some kindo of stats, even if they were somewhat inaccurate/missing some info (the relative proportion of total users on each distro/version/architecture is the important part for me). 

For me, I think this is just a really long rant about older Ubuntu/Debian versions not having Golang versions >= 1.16 or 1.18 (those are the two big versions with new features for me), and I want to gauge how many users would be affected if I dropped support for those.
