### ISSUE TITLE
  Repository and releasetarget have not the same architectureon position 1: ...

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#1518]
when trying to create a release request where the list of architectures is not exactly the list of architectures in the target the message 
> Repository and releasetarget have not the same architectureon position 1: projectA / projectB

That is a) not really proper English :-) and b) a bit annoying as the order shouldn't matter.

**Comment by adrianschroeter** [comment]
a) you mean the missing space or what else? (fixed that)

b) the order matters a lot since patchinfos are only created in one arch and there is the risk that not a single rpm goes out on release.

**Comment by lnussel** [comment]
I'm not a native speaker but I'd use "don't have" instead of "have not"

**Comment by adrianschroeter** [comment]
right, sounds better. adapting.
