### ISSUE TITLE
after all packages compiled, repositories are not published, shows cached packages older builds

### ISSUE THREAD

**Issue by mckaygerhard** [openSUSE/open-build-service#15197]
I build a couple of packages yesterday and wait for a day cos we understand is a free service and we must take consideration

but after 48 hours.. i cant see that packages and repositories are public yet!

after all packages compiled, repositories are not published, just marks as "jobs are pending" but i dont have any build pending

![image](https://github.com/openSUSE/open-build-service/assets/1571724/ca2bd969-bfba-41ed-98bf-7bbe82516751)

![image](https://github.com/openSUSE/open-build-service/assets/1571724/a066668f-e18e-4741-8d72-b87c33bf5ce9)

**Comment by v-fox** [comment]
It seems that it's a complete outage for publishing even for all official repos. And not a pip about it on mailing lists, OBS news blog or anywhere. Not the first time such major outage happens with complete silence like it's a normal thing to do. I guess this is how so-called 'gaslighting' feels like.

**Comment by mckaygerhard** [comment]
upstream bugzilla service claims that is fixed but the problem persist! i dont know if there is someting related here so i leave open until repos are published as must be

**Comment by hennevogel** [comment]
publishing is a queue, it can take time because other publishing jobs are in front of you in the queue or because the queue does not move at all...

**Comment by mckaygerhard** [comment]
hi @hennevogel  thanks for repy, i understand that and i already posted that after 48 hours still does not work but today .. time ago after such problem i got some "older" data, by example i installer mc and when downloaded it says that the package differs.. so i guess the problems still persist.. (the compilation was on last sunday one week before this comment)..

**Comment by hennevogel** [comment]
@mckaygerhard if you have some specific problem with the openSUSE instance and publishing please talk to admin@opensuse.org. We are tracking problems in the code here...
