### ISSUE TITLE
New request redesign breaks build results with long names

### ISSUE THREAD

**Issue by gmoro** [openSUSE/open-build-service#15212]
![image](https://github.com/openSUSE/open-build-service/assets/588585/4333817c-ca6d-4974-aa04-71130dd1ed2e)

https://build.suse.de/request/show/312832/build_results

**Comment by ncounter** [comment]
The Request Build Results Tab page got revamped completely. I'm closing this issue as long names is not an issue anymore. Thank you for reporting it, @gmoro
