### ISSUE TITLE
Cannot access notifications (500: Internal Server Error)

### ISSUE THREAD

**Issue by badshah400** [openSUSE/open-build-service#15213]
My account on build.o.o (badshah400) is hit with the dreaded `500: Internal Server Error` issue (again) when trying to access unread notifications. Thanks in advance for any help getting this fixed. The unread notifications badge shows 40 unread ones and not being able to read them is giving me palpitations :sweat_smile:

**Comment by danidoni** [comment]
Related to https://github.com/openSUSE/open-build-service/issues/15081
