### ISSUE TITLE
Replying to comment on a code change needs to be fixed

### ISSUE THREAD

**Issue by saraycp** [openSUSE/open-build-service#15241]
# Issue Description

If you are on the Conversation tab and try to reply to a comment on code changes you'll see something like this:

![Screenshot 2023-11-20 at 12-17-08 Open Build Service](https://github.com/openSUSE/open-build-service/assets/2581944/71a5dcc0-4466-4b50-9d9a-98fd073b6795)

Right after you submit the form, the code snippet disappears, as you can see here:

![Screenshot 2023-11-20 at 12-17-25 Open Build Service](https://github.com/openSUSE/open-build-service/assets/2581944/24cbd038-9552-4dd2-8f24-c6872bd30906)

Then, if you refresh the page, the reply is duplicated and displayed in the wrong position, as shown in this image:

![Screenshot 2023-11-20 at 12-17-52 Open Build Service](https://github.com/openSUSE/open-build-service/assets/2581944/22b7fb68-25fd-4f8e-8bd3-b2d5baf62292)

Expected Result
============

The reply is displayed only once inside the conversation tree.

How to Reproduce
===============
1. Join beta
2. Go to a request Changes tab
3. Add a comment in a line of code
4. Go to the Conversation tab
5. Try to reply to the comment you created in 3.
6. See the error

**Comment by saraycp** [comment]
The issue https://github.com/openSUSE/open-build-service/issues/15216 talks about the same, but this is more detailed.
Please don't forget to close both issues when this is fixed.

**Comment by rubhanazeem** [comment]
Fixed in https://github.com/openSUSE/open-build-service/pull/15501
