### ISSUE TITLE
Comment bubble overflows in beta UI of requests

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#15278]
# Issue Description

Adding a code/verbatim block to a request comment in the beta UI can cause the comment bubble to overflow and start hiding the project maintainers:

![image](https://github.com/openSUSE/open-build-service/assets/45594031/f65380ad-f0cc-47e0-8299-5e638a76d78f)

Expected Result
============

The bubble should not overflow and the maintainers should be visible as seen here:

![image](https://github.com/openSUSE/open-build-service/assets/45594031/d4143cb6-5876-4870-af13-820641f25458)

Further Information
===============
* https://build.opensuse.org/request/show/1129301

**Comment by dmarcoux** [comment]
Thank you @dcermak for reporting this issue.
