### ISSUE TITLE
Beta view of SubmitRequests don't show message why it was declined

### ISSUE THREAD

**Issue by rrahl0** [openSUSE/open-build-service#15287]
# Issue Description
The beta view doesn't show any Request History like in the old page. Which means when a Request gets declined, there is no way to see the message why it got declined. Here is a screenshot of an example. https://paste.opensuse.org/pastes/25984a24eee8 (sorry for the small font, but I wanted to get the page in one whole screenshot)

# Expected Result
See the reason why some Requests get declined

# How to reproduce
Create a SR which you decline and add a message to it why it got declined

**Comment by dmarcoux** [comment]
The reason why the request was declined is on the page... but it's a bit hidden. It's really not intuitive... Here's how you can see it:

![request-declined](https://github.com/openSUSE/open-build-service/assets/1102934/6600ed27-f345-4bbd-bf4d-8ac4db02b39b)

This is definitely something we need to change, so thank you for reporting this issue.

**Comment by rrahl0** [comment]
thank you. definitely overlooked that arrow

**Comment by hennevogel** [comment]
This shouldn't be collapsed...
