### ISSUE TITLE
Redirection to login portal broken when authentication cookie expired

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/open-build-service#15315]
Since anomymous access is disabled on build service on IBS, 

Firefox is complaining every morning on pages already loaded in tabs ( https://build.suse.de/staging_workflows/SUSE:ALP:Source:Standard:1.0 or https://build.suse.de/project/show/SUSE:ALP:Source:Standard:Core:1.0:Build for instance) with the following message:

"can't redirect properly, problem might be disabled or refusing cookies"

and doesn't redirect properly to login page.

I need to open https://build.suse.de/ manually and login from there.

**Comment by hennevogel** [comment]
This happens when you are doing what? reload the page?

**Comment by msirringhaus** [comment]
I'm having the same issue. 
Happens when trying to access any URL `build.suse.de/*`, while not being logged in. 
So, e.g. log out, then click "All Projects". 
Happens to me also, after successfully logging in to idp, and a redirect back to IBS should happen.

**Comment by fcrozat** [comment]
> This happens when you are doing what? reload the page?

when firefox tries to reload the tab, usually in the morning after laptop was suspended for the night. A forced-reload doesn't fix the issue. Only a manual login from https://build.suse.de/ in another tab will allow reload to work properly.

**Comment by hennevogel** [comment]
This is monkey patched on IBS now. Let's see if it helps tomorrow morning :)

**Comment by eliroca** [comment]
Could we do something like  `redirect_to CONFIG['proxy_auth_login_page'] + "?RedirectTo=" + request.path` ? Otherwise the IDP just redirects to `/`

**Comment by fcrozat** [comment]
I can confirm the monkey patch on IBS works fine

**Comment by msirringhaus** [comment]
If I open a random project now, while not being logged in, I get redirected directly to IDP, which is nice.
However, if I log in now, I do get redirected back to IBS-home, instead of the project-URL I wanted to open.
Not sure if this is to be expected or not. Sounds a bit like one redirect too many (random project -> IBS-home -> IDP, which then redirects back to IBS-home)?

**Comment by hennevogel** [comment]
@msirringhaus we are aware and work on a solution

**Comment by eliroca** [comment]
For the setup we have, the build service needs to point our IDP in the right direction. Something like:
```
CONFIG['proxy_auth_login_page'] + "?ReturnTo=" + URI.encode_www_form_component(request.fullpath)
```

@hennevogel any thoughts?

**Comment by hennevogel** [comment]
@eliroca you'll find my thoughts in #15318
