### ISSUE TITLE
Vagrant box broken after restart

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#1531]
If you restart the vagrant frontend box the mount from /tmp/vagrant_tmp happens in the initrd. This is way before the shared folder is set up so it's beneath it again. Whats the reason for mounting src/api/tmp from fstab?

**Comment by hennevogel** [comment]
@ChrisBr that's the reason you backend can't start

**Comment by M0ses** [comment]
taken for contrib/common.sh line 167

```
  # Put the backend data dir outside the shared folder so it can use hardlinks
  # which isn't possible with VirtualBox shared folders...
```

why this is needed in fstab - I don`t know - it wasn`t me who added this initially - I only adepted in the common.sh as part of refactor.

Maybe It would be also smart to split vagrantfiles between virtualbox and libvirt as the behavior of synced folders is quite different and only link to Vagrantfile.virtualbox initially.  So it might be very convinient for virtualbox users and easy to change for libvirt users

What do you think about this approach.

**Comment by hennevogel** [comment]
Nah I think this is getting out of hand. We have started with a simple Vagrant file and one shell script. It seems like it's getting more and more complicated...

I'll dig into fixing this somehow...
