### ISSUE TITLE
Make the OBS API endpoint for querying the  list of accepted trackers available  without authentication

### ISSUE THREAD

**Issue by deneb-alpha** [openSUSE/open-build-service#15312]
**Is your feature request related to a problem? Please describe.**
Hello all,
with the goal to improve the quality of provided .changes files, Uyuni has some checks exectuted  via  GitHub actions for validating some rules.
The rules we are  enforcing are coming from https://en.opensuse.org/openSUSE:Creating_a_changes_file_(RPM) and from some maintenance and security best-practices around patchinfo files. 
 One of the checks we are interested to run is a validation of the mentioned trackers in the .changes files

**Describe the solution you'd like**
`osc -A https://api.opensuse.org/ api /issue_trackers/` is providing the list of valid trackers but the info is available only for  authenticated users.

Instead of requesting a new bot account only for this reason and store the credentials in a GitHub secret, it could be beneficial  to get  the reply of that  API call also for not authenticated users.

At the end, the list of trackers is  (partially?) published at https://en.opensuse.org/openSUSE:Packaging_Patches_guidelines#Current_set_of_abbreviations

**Describe alternatives you've considered**
One other option could be to export the result of that  API call in a file and validate it directly in the GitHub action.

**Additional context**
See thread at [slack](https://suse.slack.com/archives/C02BXKBMXNV/p1701716099089389)

**Comment by msmeissn** [comment]
just getting approved trackers is okay from a security point.

**Comment by hennevogel** [comment]
We don't have a public, non-authenticated API sorry...
