### ISSUE TITLE
Failed To Build Debian Package: The systemd package cannot be installed because this system does not have a merged /usr.

### ISSUE THREAD

**Issue by raniaamina** [openSUSE/open-build-service#15357]
I try to build inkscape as i did in every release, but in last release i get this error and it seem come from OBS. This error only happen in Debian. 

```bash
[   43s] [417/713] installing systemd-255-1
[   43s] ******************************************************************************
[   43s] *
[   43s] * The systemd package cannot be installed because this system does
[   43s] * not have a merged /usr.
[   43s] *
[   43s] * Please install the usrmerge package to convert this system to merged-/usr.
[   43s] *
[   43s] * For more information please read https://wiki.debian.org/UsrMerge.
[   43s] *
[   43s] ******************************************************************************
[   43s] dpkg: error processing archive .init_b_cache/systemd.deb (--install):
[   43s]  new systemd package pre-installation script subprocess returned error exit status 1
[   43s] Errors were encountered while processing:
[   43s]  .init_b_cache/systemd.deb
[   43s] exit ...
```

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other with software packaging with the OBS. They meet online in a the openSUSE Packager IRC chat (irc://irc.libera.chat/openSUSE-packaging) or on the [packaging mailing list](https://lists.opensuse.org/archives/list/packaging@lists.opensuse.org/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other packager community members. 

Thank you for your consideration.
