### ISSUE TITLE
Ability to flag a package out of date on the public OBS instance.

### ISSUE THREAD

**Issue by ghost** [openSUSE/open-build-service#15438]
**Is your feature request related to a problem? Please describe.**
Sometimes some packages might get left behind and be out of date for a while when there is a new release available, due to a packager not being aware a new release is available

**Describe the solution you'd like**
Due to this it might be useful to have a flag out-of-date feature on the public OBS web instance to let the maintainer know the package is out of date. Arch already has a feature like this on their packages website. I feel like opensuse tumbleweed can benefit from this especially since it is a rolling release like arch

**Comment by hennevogel** [comment]
You can comment on every package page. For the more complicated features that touches this topic see #11646
