### ISSUE TITLE
Loading large projects is very slow on newer Firefox versions

### ISSUE THREAD

**Issue by msirringhaus** [openSUSE/open-build-service#15442]
# Issue Description
Opening large projects (like [Leap](https://build.opensuse.org/project/show/openSUSE:Leap:15.5)) takes a long time. There seems to be a very significant difference between browsers, however. While it takes ~10s in Chromium, it often takes 30 or more seconds on newer Firefox versions (using FF121 with Tumbleweed). It seems to have gotten worse the last couple of months, even sometimes triggering the "This page is slowing down Firefox."-notification.

Expected Result
============
Loading speed should be roughly the same on all browsers.

How to Reproduce
===============
1. Go to https://build.opensuse.org/project/show/openSUSE:Leap:15.5
2. Wait until the package-list is fully populated.
3. Compare measured times (or start the built-in profiler before-hand)

Further Information
===============

The culprit seems to me to be the displaying of the package list (or maybe/probably the filtering out of inherited packages). So not network-related, but "CPU bound".

Looking into the profilers of each browser, it seems that 20+ seconds in Firefox are spent running `Node.removeChild` 21.000 times. Using the old Firefox ESR (115.6), the page does load significantly faster (even faster than Chromium), and `Node.removeChild` is only hit <300 times.

This may very well be a Firefox regression and not an OBS issue. But I want to make sure it is not OBS simply doing things differently for different browsers (e.g. based on the user agent string or on the features they advertise).

**Comment by hennevogel** [comment]
> But I want to make sure it is not OBS simply doing things differently for different browsers 

No such code in OBS. But despite the differences in browsers, this is the *very* large "interhited packages" table that get's rendered on page load.

**Comment by msirringhaus** [comment]
For reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1873649

**Comment by msirringhaus** [comment]
Fixed upstream and shipped.
