### ISSUE TITLE
Show the crucial decision information on Request GUI

### ISSUE THREAD

**Issue by rtsvetkov** [openSUSE/open-build-service#15467]
**Problem:**
The beta design of the GUI main page hides the crucial information for making a decision from the release manager. Eg: mentioned issues are hidden and the build results are hidden. It requires additional clicks and loses time.

**Proposed Solution**
The important information for approvals should be shown on the main page. At least 80% of the SRs are trivial and need mainly a reference to the issues and build status.

**Alternatives considered**
Provide a generalized "traffic light" indicator on the build status. This doesn't solve the mentioned issues.

**Comment by rubhanazeem** [comment]
@rtsvetkov, have you looked at the new changes on the request page? You now have a summary of build results and a counter indicating the issues mentioned. I believe this would solve the issues you have mentioned. If you have more suggestions please feel free to open a new issue.
