### ISSUE TITLE
obs does not recognize %dist

### ISSUE THREAD

**Issue by youngk123** [openSUSE/open-build-service#15466]
obs does not recognize %dist . It modifies the Rlease field to a random value
[   88s] now finalizing build dir...
[   89s] -----------------------------------------------------------------
[   89s] I have the following modifications for libarchive.spec:
[   89s] 5c5
[   89s] < Release:        3%{?dist}
[   89s] ---
[   89s] > Release:        3.2

**Comment by krauselukas** [comment]
Hello @youngk123,

I need more context to understand the issue, not sure if there is a general issue or if its a problem with the package/spec file. Can you share a link to the package where you facing the problem? If its a packaging problem, I would suggest you try to get some help in our IRC channel.

**Comment by youngk123** [comment]
sorry，i am build packages on local，i can not share link. I mean the Release field in the spec file seems to only be set to numbers when I try to set a {%? dist}, obs will change the release field to a random value like this:
%bcond_without check

Name:           libarchive
Version:        3.3.3
Release:        3%{?dist}

when obs finsh build, Release is change, become libarchive-3.3.3-3.2.x86_64.rpm

**Comment by youngk123** [comment]
this is my project config set:
Macros:
%centos_version 700
%_vendor redhat

%centos 7
%centos_ver 7

#From RedHat buildsys-macros package
%rhel 7
%dist .el7
%el7 7

%kernel_module_package_buildreqs kernel-devel redhat-rpm-config

%ext_info .gz
%ext_man .gz

%info_add(:-:) test -x /sbin/install-info -a -f %{?2}%{?!2:%{_infodir}}/%{1}%ext_info && /sbin/install-info --info-dir=%{?2}%{?!2:%{_infodir}} %{?2}%{?!2:%{_infodir}}/%{1}%ext_info \
%{nil}

%info_del(:-:) test -x /sbin/install-info -a ! -f %{?2}%{?!2:%{_infodir}}/%{1}%ext_info && /sbin/install-info --quiet --delete --info-dir=%{?2}%{?!2:%{_infodir}} %{?2}%{?!2:%{_infodir}}/%{1}%ext_info \
%{nil}
:Macros

so expect  libarchive-3.3.3-3.el7.x86_64.rpm， instead of libarchive-3.3.3-3.2.x86_64.rpm

**Comment by krauselukas** [comment]
@youngk123 this is a packaging topic. Sorry but I will close the issue. We tracking issues here related to the OBS source. I suggest that you reach out for help on the [opensuse packaging mailing list](https://lists.opensuse.org/archives/list/packaging@lists.opensuse.org/) or in the [IRC chat](irc://irc.libera.chat/openSUSE-packaging)
