### ISSUE TITLE
Remove staging review from the review menu 

### ISSUE THREAD

**Issue by rtsvetkov** [openSUSE/open-build-service#15471]
**Problem**
Miss-clicking on the GUI and "approving" staging moves the package directly to GA. This leads ti a lot of complications and added effort. Simply put, The cost for clicks is low with a substantial probability, but the price of the repair is very high. 

**Solution description**
Forcing the package to GA is not "approving", and it should be removed from the menu. Move this functionality to a separate place/button.  

**Describe alternatives you've considered**
Completly removing this from GUI and relying on the command line interface. 

**Additional context**
![Screenshot from 2024-01-11 15-07-10](https://github.com/openSUSE/open-build-service/assets/40271459/7e529fe0-fe26-443b-806f-be86d723d20e)

**Comment by rtsvetkov** [comment]
You can call the UI element and move it away from the reviews [Accept package from the staging]

**Comment by hennevogel** [comment]
@rtsvetkov I'm not quite sure I understand the problem you are facing. What did you do? Please take us through it.

**Comment by rtsvetkov** [comment]
It is too easy to misclick the so-called 'review' for the staging. A small lag of the mouse pointer and the mischieve is done :(

**Comment by rtsvetkov** [comment]
These menu entries should be separated by seas

**Comment by hennevogel** [comment]
So you gave the review for `SUSE:SLE-15-SP6:GA:Staging:B` by accident?

**Comment by rtsvetkov** [comment]
not only me and not only once

**Comment by rtsvetkov** [comment]
But to return - this is not a "review"

**Comment by rtsvetkov** [comment]
@hennevogel, we are getting new team members to make the reviews. This implementation will help us to avoid many mistakes.

**Comment by hennevogel** [comment]
@rtsvetkov I understand
