### ISSUE TITLE
unintelligible 'is in conflict' build dependency error

### ISSUE THREAD

**Issue by hramrach** [openSUSE/open-build-service#15483]
# Issue Description
For some reason rpm conflict happened when resolving package build dependencies. OBS does not give the reason.

Expected Result
============
Error message provides sufficient information for resolving error.

How to Reproduce
===============
https://build.opensuse.org/package/show/home:michals:pytest/python-diskcache

**Comment by krauselukas** [comment]
@hramrach there is already an issue open for this https://github.com/openSUSE/open-build-service/issues/11694 thanks for reporting, I will close this. Just ping incase I'm missing something
