### ISSUE TITLE
Forbidden project caching

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#1551]
With #1550 we have disabled caching of the forbidden projects in the User instances. This means that the `default_scope` of `Project` always runs `Relationship.forbidden_project_ids_for_user` which iterates an array of `Project` ids. With many forbidden `Projects` this is potentially slow.

**Comment by hennevogel** [comment]
We could create a namespace in the cache pool where `User` caches `User` specific id's and drop the whole namespace when the cache gets invalid. If dropping a namespace is possible...

**Comment by hennevogel** [comment]
Reading the [caching guide](http://guides.rubyonrails.org/caching_with_rails.html) sounds like `namespace` only works for the whole pool not for single keys.

**Comment by hennevogel** [comment]
@mdeniz and I came up with this: 

https://github.com/hennevogel/open-build-service/commit/ff4cf57a7b322d174d0b45c5a343dacdc51894a6

**Comment by mdeniz** [comment]
Should we close this henne?

**Comment by hennevogel** [comment]
jupp
