### ISSUE TITLE
Server:Unstable appliance ISO says it can't get network (but I have it..?)

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/open-build-service#1553]
Whenever the OBS appliance is installed, it always shows the following error:
<img width="912" alt="screen shot 2016-02-17 at 8 41 52 am" src="https://cloud.githubusercontent.com/assets/276796/13111173/6b2ff6f0-d552-11e5-8240-2c009d4e9394.png">

However, after logging in, I do seem to have a usable network connection. I'm not sure what defines an "unusable" connection.

**Comment by M0ses** [comment]
our setup-appliance.sh relies on namesserver resolution as we use "hostname -f" to determine full qualified hostname for ssl-cert generation. Virtualization solutions like Virtualbox might break this by not providing a proper dns resolution in hostonly or nat networks - so please use bridged network with proper dns resolution or use another virtualization solution like libvirt/qemu-kvm for example

**Comment by Conan-Kudo** [comment]
@M0ses It also happens on my Fedora 23 box using KVM, as well as VMware Fusion on my Mac.

**Comment by M0ses** [comment]
when you login on the appliance and do "hostname -f", whats the result?

**Comment by M0ses** [comment]
implemented better explanation of error in #1567
