### ISSUE TITLE
export SOURCE_DATE_EPOCH

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#1555]
the reproducible builds initiative suggets to set SOURCE_DATE_EPOCH in the environment: https://reproducible-builds.org/specs/source-date-epoch/

Sounds like a job for obs itself. Maybe it could be done in a more generic way so it doesn't rely on the .changes file but uses last commit timestamp, newest modification time of all source files or something like that.

**Comment by k0da** [comment]
There must be a revtime in buildinfo, but it seems it is not set:
osc buildinfo openSUSE:Factory/make/standard/x86_64 | grep revtime
returns nothing.

Once revtime is visible in buildinfo, this can be used as SOURCE_DATE_EPOCH

**Comment by mlschroe** [comment]
Dunno. Using revtime doesn't work well for links.

**Comment by k0da** [comment]
well, assuming we don't trust user meta having a revtime there different should be ok.

**Comment by k0da** [comment]
The other way could be just get it through
`date -r newest_file +%s` from %{_sourcedir}

**Comment by StefanBruens** [comment]
I see two occasions where newest file won't work as is:
- spec file generation from templates (often a script called pre_checkin.sh). *If* the generator sets the time of the generated files to the newest input file, this would be no issue
- sources generated by _services. For e.g. git tar_scm, one could use the commit time.

**Comment by jnweiger** [comment]
as of 2 years later:
it seems the  SOURCE_DATE_EPOCH env var is honored correctly by RPM builds, but not when building DEB packages with OBS. Is this a known issue?

**Comment by adrianschroeter** [comment]
because this is not a build service (or build script) feature, but a feature in rpm itself.

So you would need to add support to debian tool chain for this.

**Comment by jnweiger** [comment]
Wasn't that feature originally desigend by debian?
I'd assume that their build toolchain has it already.

**Comment by crrodriguez** [comment]
https://wiki.debian.org/ReproducibleBuilds apparently already implemented at least partially.

**Comment by Thaodan** [comment]
> because this is not a build service (or build script) feature, but a feature in rpm itself.
> 
> So you would need to add support to debian tool chain for this.

Would it make sense to add it for any package manager that supports it?
Waiting for Debian seams like not the right call here.
