### ISSUE TITLE
Build results of project "succeeded: [all]", download repository show the files, but download result in "404 Not Found"

### ISSUE THREAD

**Issue by wla70** [openSUSE/open-build-service#15599]
Build is successful, build results of project show "succeeded: [all]", download repository show the files, but download result in "404 Not Found". Please check the links below.

(sub)project: https://build.opensuse.org/project/show/home:wla70:vdr_2.6.6
repository:    https://download.opensuse.org/repositories/home:/wla70:/vdr_2.6.6/15.4/x86_64/
                     https://download.opensuse.org/repositories/home:/wla70:/vdr_2.6.6/15.5/x86_64/

**Comment by ncounter** [comment]
@wla70 Hi, are you talking about downloading the content of the published repository from `download.opensuse.org`? If so, could you please check again? It might be only a timing matter. Was the repository already tagged as `Published`?

**Comment by wla70** [comment]
Yes, for both questions. It shows the files with nonzero size in the repository, but "404 Not Found" when download.
Today, it works now.
I think, after it appears in the repository, "Not Found" should not be possible.

**Comment by ncounter** [comment]
In this case, I'd suggest you to submit this issue to admin@opensuse.org as this is out of the **OpenBuildService** umbrella.

I'm closing this issue meanwhile. Thank you.
