### ISSUE TITLE
New dark theme: Attribute values are not readable

### ISSUE THREAD

**Issue by asdil12** [openSUSE/open-build-service#15607]
![image](https://github.com/openSUSE/open-build-service/assets/725608/ac9da136-45ae-4a51-bbdc-b934693fd9d7)
(some text was selected here to show that there is actually text in the white box)

**Comment by snehalchaudhari98** [comment]
Hi @hennevogel ! I want to try to fix the issue. It's the first time I'm contributing to an open-source project, so I think I would be able to fix it and contribute something. Could you please assign this issue to me?
