### ISSUE TITLE
need public api to fetch binaries

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#1561]
The release notes sync script fetches binaries from the public api:
https://github.com/openSUSE/release-notes-openSUSE/blob/master/tools/bin/update_release_notes

it used to do that via https://build.opensuse.org/public/build/Documentation:Auto/openSUSE_Factory/x86_64/_repository/release-notes-openSUSE and that worked until https://github.com/openSUSE/open-build-service/commit/85de8b8e783618dbeb1ac220aba2b6d3fea510ca

**Comment by adrianschroeter** [comment]
hot-fixed on production ... clean fix is WIP ...

**Comment by lnussel** [comment]
works again, thanks!
