### ISSUE TITLE
DoD downloads wrong architecture

### ISSUE THREAD

**Issue by azouhr** [openSUSE/open-build-service#15624]
# Issue Description

On a private OBS Instance, a project configured as dod for Leap:15.5 with architectures x86_64 and s390x, the s390x part only downloads x86_64 rpms instead of the required s390x rpms.

The prj meta configuration looks like this:
```
<project name="openSUSE:Leap:15.5:GA">
  <title>DOD openSUSE Leap 15.5 GA Level</title>
  <description/>
  <person userid="Admin" role="maintainer"/>
  <repository name="standard">
    <download arch="x86_64" url="http://download.opensuse.org/distribution/leap/15.5/repo/oss/" repotype="rpmmd"/>
    <download arch="s390x" url="http://download.opensuse.org/distribution/leap/15.5/repo/oss/" repotype="rpmmd"/>
    <arch>s390x</arch>
    <arch>x86_64</arch>
  </repository>
</project>
```

When adding a small package to that project, OBS starts downloading for both, x86_64 and s390x, however looking at the packages in /srv/obs/build/openSUSE:Leap:15.5:GA/standard/s390x/:full with rpm -qpi, it turns out, that all packages downloaded are with architecture x86_64.

Expected Result
============
I would expect that the correct packages are downloaded to the :full directory.

How to Reproduce
===============
1. use private instance of OBS and configure with x86_64 and s390x
2. setup worker for x86_64 and s390x (qemu-s390x would work)
3. create dod project like the one in the description, add projectconfig, and add some package 
4. check rpms that are downloaded to `/srv/obs/build/openSUSE:Leap:15.5:GA/standard/s390x/:full`

Further Information
===============
* Exact server version (in case a private instance is used): 2.11~alpha.20240207T153337.f6633e819

**Comment by adrianschroeter** [comment]
you need to use archfilter elements. Check openSUSE:Tumbleweed project on build.o.o as reference.
