### ISSUE TITLE
Provide source revision value in the build results

### ISSUE THREAD

**Issue by hellcp-work** [openSUSE/open-build-service#15637]
**Is your feature request related to a problem? Please describe.**
There is currently no easy way to tell what the source revision was the base for a build result. It does get even more difficult with `lastsuccess` call.

**Describe the solution you'd like**
A source rev value in resultlist status view

**Describe alternatives you've considered**

- Another endpoint for finding out which revision value corresponds to a build result
- An additional query parameter for getting that information

**Comment by hennevogel** [comment]
https://api.opensuse.org/apidocs/#/Build/get_build__project_name___repository_name___architecture_name___package_name___history
