### ISSUE TITLE
Incorrect .gz downloads from download.opensuse.org in Firefox

### ISSUE THREAD

**Issue by dg0yt** [openSUSE/open-build-service#1566]
.gz downloads from download.opensuse.org with Firefox (on Ubuntu 14.04) are gzipped once more without notice. This affects the sources of .deb packages which is a serious issue for GPL software.

Steps to reproduce:
 1. Check the meta information on http://download.opensuse.org/repositories/home:/dg0yt/xUbuntu_14.04/openorienteering-mapper_0.6.1-3.1.diff.gz.mirrorlist:

        Size: 4.0K (4118 bytes)
        [...]
        MD5 Hash: f82c38d217389fe09c751d518455a794 

 2. Download http://download.opensuse.org/repositories/home:/dg0yt/xUbuntu_14.04/openorienteering-mapper_0.6.1-3.1.diff.gz with Firefox.
 3. Check the file:

        dg0yt@ubuntu:/tmp$ for I in "ls -l" md5sum file; do $I openorienteering-mapper_0.6.1-3.1.diff.gz; done
        -rw-rw-r-- 1 dg0yt dg0yt 4141 Feb 20 11:18 openorienteering-mapper_0.6.1-3.1.diff.gz
        d1d7ca18d1022a14bc0145e323704da9  openorienteering-mapper_0.6.1-3.1.diff.gz
        openorienteering-mapper_0.6.1-3.1.diff.gz: gzip compressed data, from Unix

    Neither size nor MD5SUM match.

 4. Ungzip, and check again:

        dg0yt@ubuntu:/tmp$ gunzip openorienteering-mapper_0.6.1-3.1.diff.gz
        dg0yt@ubuntu:/tmp$ for I in "ls -l" md5sum file; do $I openorienteering-mapper_0.6.1-3.1.diff; done
        -rw-rw-r-- 1 dg0yt dg0yt 4118 Feb 20 11:18 openorienteering-mapper_0.6.1-3.1.diff
        f82c38d217389fe09c751d518455a794  openorienteering-mapper_0.6.1-3.1.diff
        openorienteering-mapper_0.6.1-3.1.diff: gzip compressed data, was "openorienteering-mapper_0.6.1-3.1.diff", from Unix, last modified: Sun Jan 10 17:51:36 2016, max compression

    Size and MD5DUM match, and it is still gzipped.

I could not reproduce the issue with wget. But I assume the compression happens on the webserver, and it doesn't make much sense for .gz files.

**Comment by hennevogel** [comment]
download.o.o has nothing to do with the OBS. Please report this to admin@opensuse.org 

https://en.opensuse.org/openSUSE:Services_help#download.opensuse.org
