### ISSUE TITLE
Foreign SUSE commenting software breaks appearance in OBS

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#15719]
Issue Description
========

There seems to exist some software inside — what I guess is IBS — which produces OBS comments with redundant information and which are almost unreadable.

https://build.opensuse.org/request/show/1153212

Observed result
===========

```
darix declined request

mrueckert wrote (1153212) (https://build.opensuse.org/request/show/1153212),```,+Thu Feb 29 04:44:52 UTC 2024 - jun wang ,+,+- Update to 1.5.2,+ * no changelog for 1.5.2,+ * Drop...
```

* duplication of user info and/or leak of internal names the way one looks at it (darix<>mrueckert)
* request ID triplicated
* newlines all gone

Expected result
=======

```
darix declined request

`​``
+Thu Feb 29 04:44:52 UTC 2024 - jun wang
+
+- Update to release 1.5.2
+  * no changelog for 1.5.2
```

How to Reproduce
===============
Unclear. Seems to be OBS-related software but only ever observed with IBS user identities.

**Comment by hennevogel** [comment]
This is probably some request mirroring or whatever, you will have to take this up with the opensuse-factory list.
