### ISSUE TITLE
Merge POST request?cmd=diff into GET request

### ISSUE THREAD

**Issue by dmach** [openSUSE/open-build-service#15710]
**Is your feature request related to a problem? Please describe.**
I frequently need to make two HTTP requests to get full information about a request.

**Describe the solution you'd like**
Add the following options to `GET /request/$ID`:
 - `diff` (if set to 1, return also diff data and enable the options below)
 - `with_issues` (requires `diff=1`)
 - `with_description_issues` (requires `diff=1`)
 - `diff_to_superseded` (requires `diff=1`)

**Describe alternatives you've considered**
Keep loading OBS with 2 requests instead of 1.

**Comment by adrianschroeter** [comment]
IMHO the overhead of doing two requests is very little compared to the amount of work which is needed to be done for each of the operations.

We could add additional fields to the xml diff though when using an extra parameter to stay backward compatible. So we could do that if it helps you really on the client side.

**Comment by dmach** [comment]
If you're fine with the overhead, I can continue using the 2 requests.
It is slightly more inconvenient than a single request, but I can definitely live with it.
Feel free to close the issue if you're not planning to make any change in this regard.
