### ISSUE TITLE
Service run errors are too persistent

### ISSUE THREAD

**Issue by tuminoid** [openSUSE/open-build-service#1572]
Using OBS 2.6.8:

1. create a project, say `home:id:test`
2. copy a package with _service that is not disabled, and have it failed (say crash service server, `systemctl stop obsservice` to simulate), to that project
3. package appears broken
4. delete package
5. failure is fixed (`systemctl start obsservice`)
6. copy same package and same rev again to same project

Expected: service runs and package builds
Actual: cached serviceerror is displayed and package is broken again, even there is no reason

There seems not to be apparent way to get rid of this "revision paralysis", as deleting package or project does not actually delete anything from `/srv/obs/trees`. Especially easy to achieve completely broken and confusing results if you combine CI and service files.

**Comment by adrianschroeter** [comment]
This could be fixed by f3091136977ccd38aa6b155b012985de3a22e924 .
We could backport this also to 2.6 if needed.

**Comment by adrianschroeter** [comment]
dup of #852

**Comment by tuminoid** [comment]
This seems to fix the issue. Apply to 2.6 as well.

**Comment by adrianschroeter** [comment]
Backported the relevant part of that commit in

40968808f7ff37d721b6af471c58f0824475b583
