### ISSUE TITLE
Invisible navigation links after updating to the last unstable version

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/open-build-service#15723]
# Issue Description
I have updated a local obs installation to the latest unstable version. Several links are now invisible in the frontend.
![grafik](https://github.com/openSUSE/open-build-service/assets/602903/0bc6c030-5578-4e48-84e0-8cbc98f826ba)

Expected Result
============
The navigation links and buttons should be visible.

Further Information
===============
* A link to an OBS instance showing the issue
The server is question is private

* Exact server version (in case a private instance is used)
```
$ rpm -qa | grep obs | grep '\-2\.'
obs-common-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.noarch
obs-bundled-gems-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.x86_64
system-user-obsservicerun-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.noarch
obs-tests-appliance-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.noarch
system-user-obsrun-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.noarch
obs-signd-2.8.3-150500.2.5.x86_64
obs-worker-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.noarch
obs-api-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.noarch
obs-server-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.noarch
obs-api-deps-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.x86_64
obs-cloud-uploader-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.noarch
```
```
$ rpm -qa | grep ruby3.1
libruby3_1-3_1-3.1.4-150500.44.10.x86_64
ruby3.1-rubygem-rack-2.2-2.2.8.1-150500.39.1.x86_64
ruby3.1-rubygem-gem2rpm-0.10.1-150500.70.1.x86_64
ruby3.1-rubygem-rack-2.2.4-150400.60.2.x86_64
ruby3.1-3.1.4-150500.44.10.x86_64
ruby3.1-rubygem-passenger-6.0.14-150500.110.7.x86_64
ruby3.1-devel-3.1.4-150500.44.10.x86_64
```

* Information from the browser network analysis
In the browser's network analysis, I can see that all requests were completed without errors

* If you move the mouse pointer along the left edge, a narrow green bar appears and the browser displays a link, but the associated text is not visible.

**Comment by hennevogel** [comment]
dupplicate of #15721
