### ISSUE TITLE
Editing of package files is broken after update

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/open-build-service#15721]
# Issue Description
I've update a local obs installation to latest unstable version. Editing any file shows an incomplete ui (you cannot save). 

Expected Result
============
The ui should not be broken

Further Information
===============
* A link to an OBS instance showing the issue
The server is question is private

* Exact server version (in case a private instance is used)
```
$ rpm -qa | grep obs | grep '\-2\.'
obs-common-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.noarch
obs-bundled-gems-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.x86_64
system-user-obsservicerun-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.noarch
obs-tests-appliance-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.noarch
system-user-obsrun-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.noarch
obs-signd-2.8.3-150500.2.5.x86_64
obs-worker-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.noarch
obs-api-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.noarch
obs-server-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.noarch
obs-api-deps-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.x86_64
obs-cloud-uploader-2.11~alpha.20240229T172358.65f0f30df-150500.16552.1.noarch
```
```
$ rpm -qa | grep ruby3.1
libruby3_1-3_1-3.1.4-150500.44.10.x86_64
ruby3.1-rubygem-rack-2.2-2.2.8.1-150500.39.1.x86_64
ruby3.1-rubygem-gem2rpm-0.10.1-150500.70.1.x86_64
ruby3.1-rubygem-rack-2.2.4-150400.60.2.x86_64
ruby3.1-3.1.4-150500.44.10.x86_64
ruby3.1-rubygem-passenger-6.0.14-150500.110.7.x86_64
ruby3.1-devel-3.1.4-150500.44.10.x86_64
```

* Information from the browser network analysis
In the browser network analyze I can see  that the request to https://<myhost>/assets/webui/cm2/codemirror-file-f2021167fa83ad911963803472d81162331cfc67a957f472a68094349d1ebf4e.js returns error 404. 

* Inspecting the files on the server
Looking at the server into `/srv/www/obs/api/public/assets/webui/cm2' shows that the requested file is not present. 

* Attempt to update outdated assets
I tried to force an update of the precompiled assets, but this fails as shown below:
```
/srv/www/obs/api # RAILS_ENV="production" bin/rails  assets:clean
rails aborted!
Sprockets::Error: unknown compressor: terser

Tasks: TOP => assets:clean
(See full trace by running task with --trace)
```
the same call with `--trace`
```
RAILS_ENV="production" bin/rails  assets:clean --trace
** Invoke assets:clean (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:clean
rails aborted!
Sprockets::Error: unknown compressor: terser
/usr/lib64/obs-api/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/compressing.rb:82:in `js_compressor='
/usr/lib64/obs-api/ruby/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/railtie.rb:199:in `build_environment'
/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.8/lib/rails/railtie.rb:226:in `public_send'
/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.8/lib/rails/railtie.rb:226:in `method_missing'
/usr/lib64/obs-api/ruby/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:20:in `environment'
/usr/lib64/obs-api/ruby/3.1.0/gems/sprockets-4.2.1/lib/rake/sprocketstask.rb:43:in `cached'
/usr/lib64/obs-api/ruby/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:45:in `manifest'
/usr/lib64/obs-api/ruby/3.1.0/gems/sprockets-4.2.1/lib/rake/sprocketstask.rb:148:in `with_logger'
/usr/lib64/obs-api/ruby/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:73:in `block (2 levels) in define'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/airbrake-9.4.3/lib/airbrake/rake.rb:17:in `execute'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/usr/lib64/obs-api/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.8/lib/rails/command.rb:51:in `invoke'
/usr/lib64/obs-api/ruby/3.1.0/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => assets:clean
```

**Comment by hennevogel** [comment]
All of this very much depends on how you updated from what. BTW we do no support unstable, it's called that for a reason. Expect it to break at any time, expect the need to roll back and forth to fix things and occasional some manual tasks. You have been warned... :)

We don't ship the things you need to build assets with the RPMs as we build assets in the package build. It sounds to me like you might have some old manifests laying around for some reason. They are called `public/.sprockets-manifest-SOMEHASH.json`. You should delete all of them that *do not* belong to the `obs-api` package you have installed.

**Comment by rhabacker** [comment]
> All of this depends a lot on how you updated from what.

This was an update from Leap 15.4 to 15.5 with zypper, nothing special.

> Expect it to break at any time.

I know - but it can also help obs developers to get early indications of hidden problems. 

> Expect to have to keep rolling back to fix things. 

I solved the problem by removing the `api/public` folder, reinstalling the obs-api package and restarting the obs service 

> We don't ship the things needed to build assets with the RPMs, as we build the assets with the package.

This info is helpful because it means that rake commands from the `assets` namespace will not work and this error message is misleading. Can these commands be removed from the --trace list in this case ? 

> They are called public/.sprockets-manifest-SOMEHASH.json. You should delete all files that do not belong to the obs-api package you installed.

Yes, I did that in principle (see above). 

To avoid this kind of problem in the future, couldn't the obs-api package delete them itself during an update ?

**Comment by rhabacker** [comment]
Something like
```
rpm -qf  /srv/www/obs/api/public/assets/.sprockets-manifest* | grep "not owned" | gawk '{ print $2 }' | xargs rm
```
 in the postinstall section of the obs-api package ?

**Comment by rhabacker** [comment]
> That is the definition of _update_. Install new files, remove old files. The problem is something goes wrong during RPM update sometimes, nobody knows why.

I can confirm something like this:  on updating from `obs-api-2.11~alpha.20240304T135806.137790246-150500.16571.1.noarch` to `obs-api-2.11~alpha.20240306T140535.9e326b654-150500.16581.1.noarch`  I get 
```
warning: file /srv/www/obs/api/public/assets/.sprockets-manifest-069b2d9ede9df43699579bf2b5018c28.json: remove failed: No such file or directory
```
