### ISSUE TITLE
OBS tries to load rpmlint_log from disabled repo

### ISSUE THREAD

**Issue by jcronenberg** [openSUSE/open-build-service#15768]
# Issue Description
When going to https://build.opensuse.org/package/show/server:dns/unbound it shows an error that it can't load rpmlint_log from 15.4. The 15.4 repo is disabled so likely there isn't a rpmlint_log.

Expected Result
============
No Error

How to Reproduce
===============
1. Be logged in with beta features enabled
1. Go to https://build.opensuse.org/package/show/server:dns/unbound
1. See error toast at the top

Further Information
===============
![image](https://github.com/openSUSE/open-build-service/assets/54934253/7e5463cf-fe09-4c75-8651-72ceeb654e50)

**Comment by cryptomilk** [comment]
Same for me on my home repo
