### ISSUE TITLE
After installing obs on opensuse15.5, the web page cannot be opened.

### ISSUE THREAD

**Issue by viikei** [openSUSE/open-build-service#15783]
# Issue Description
After installing obs on opensuse15.5, the web page cannot be opened.
OS: openSUSE Leap 15.5
OBS Depository: https://download.opensuse.org/repositories/OBS:/Server:/2.10/15.5/OBS:Server:2.10.repo
OBS Version: 2.10.22

1、Go To the websit:
![image](https://github.com/openSUSE/open-build-service/assets/62841836/17038f5a-98ae-4a0c-aa75-bc267a2bfa5e)

2、Click on the "[The OBS web interface](https://build.xos.com/)"

![image](https://github.com/openSUSE/open-build-service/assets/62841836/1835c18e-7cba-4d66-b6bb-a36c2839476c)

Note: How to solve it, thank you very much!!!!!!

**Comment by viikei** [comment]
I am an ordinary user of openSUSE. When I send an email to you requesting assistance, I am told that I must be a member to do so. Additionally, if I describe my issue in the email, it gets rejected. Please assist.

**Comment by danidoni** [comment]
> I am an ordinary user of openSUSE. When I send an email to you requesting assistance, I am told that I must be a member to do so. Additionally, if I describe my issue in the email, it gets rejected. Please assist.

Send you problem [here](https://lists.opensuse.org/archives/list/buildservice@lists.opensuse.org/)

**Comment by hennevogel** [comment]
@viikei if you have problems accessing the mailing list, here is their help page: https://en.opensuse.org/openSUSE:Mailing_lists_subscription

**Comment by shafeipaozi** [comment]
> # Issue Description
> After installing obs on opensuse15.5, the web page cannot be opened. OS: openSUSE Leap 15.5 OBS Depository: https://download.opensuse.org/repositories/OBS:/Server:/2.10/15.5/OBS:Server:2.10.repo OBS Version: 2.10.22
> 
> 1、Go To the websit: ![image](https://private-user-images.githubusercontent.com/62841836/311907902-17038f5a-98ae-4a0c-aa75-bc267a2bfa5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTQ5NDksIm5iZiI6MTcyMDA5NDY0OSwicGF0aCI6Ii82Mjg0MTgzNi8zMTE5MDc5MDItMTcwMzhmNWEtOThhZS00YTBjLWFhNzUtYmMyNjdhMmJmYTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEyMDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MjBmYTIyNTkwNzA5YmE4M2I0ZTVkMGE1NGIzZTgxMDk2Yzg0NmQzMmYzMDBiYzNkM2U2ZWFkMjdjYzJlMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vWPgbpyRcyRI0tOvTW15E0Zc68IeDTXYm-awIPs8qBo)
> 
> 2、Click on the "[The OBS web interface](https://build.xos.com/)"
> 
> ![image](https://private-user-images.githubusercontent.com/62841836/311907851-1835c18e-7cba-4d66-b6bb-a36c2839476c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTQ5NDksIm5iZiI6MTcyMDA5NDY0OSwicGF0aCI6Ii82Mjg0MTgzNi8zMTE5MDc4NTEtMTgzNWMxOGUtN2NiYS00ZDY2LWI2YmItYTM2YzI4Mzk0NzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEyMDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwZjUyY2Q4YzIwOGVhNGZiNjI0NTg3MGQ5YjA4NjA1OGNhZDM4YTM1N2IzNGZlYzUyOTYxYjdhMzlkZmJhMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-qf3gc4Ybpf4Hi7vQzbMrP5zxa6ciFEwIeVwrg4VMFM)
> 
> Note: How to solve it, thank you very much!!!!!!

Hello, have you solved it? I also encountered this problem and I couldn't find your post on the forum!
