### ISSUE TITLE
Factories Needed for Spec 

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#1584]
- [X]  Christian:  admin_user
- [X] Christian: Configuration factory
- [X]  Christian: Remote project factory
- [X]  Björn: package factory
- [X]  Björn: AttribType factory
- [X]  Björn: AttribNamespace factory
- [X]  Henne: ProjectLogEntry
- [X]  Henne: Flag
- [X]  Björn: Attrib factory
- [X]  Björn: WatcheProject factory
- [X]  Moisés: deleted_user
- [X]  Björn DownloadRepository factory
- [X]  Moisés: Group
- [X]  Moisés: Relationship Factory
- [x]  Björn: StatusMessage factory
- [x]  Björn: ReleaseTarget factory
- [x]  Björn: RepositoryArchitecture factory
- [x]  Björn: PathElement factory
- [x] Moisés: StatusHistory factory
- [x]  Björn: BsRequest factory
- [x]  Björn: BsRequestActions factory

**Comment by bgeuken** [comment]
I don't think we use this anymore
=> closing
