### ISSUE TITLE
cant update

### ISSUE THREAD

**Issue by powl999** [openSUSE/open-build-service#15866]
For security issues, please refer to [SECURITY.md](https://github.com/openSUSE/open-build-service/blob/master/SECURITY.md).

Any content related problems of our public instance build.opensuse.org, like not building packages or distribution setup should
get reported either on the mailing lists or in the [openSUSE Bugzilla](https://bugzilla.opensuse.org).

Having problems with the OBS command line interface osc? It has its own issue tracker here: https://github.com/openSUSE/osc

Having problems with the obs-build tool that controls the build process? It has its issue tracker here: https://github.com/openSUSE/obs-build

Good to go? Then please remove these lines above, including this one, and help us understand your issue by answering the following:

# Issue Description
<html>Dependency resolution failed:<br/><br/>the installed latte-dock-20230312.git.a0a4911-696.15.x86_64 requires &apos;qt5qmlimport(org.kde.plasma.private.taskmanager.0) &gt;= 1&apos;, but this requirement cannot be provided
the installed latte-dock-20230312.git.a0a4911-696.15.x86_64 requires &apos;qt5qmlimport(org.kde.plasma.private.volume.0) &gt;= 1&apos;, but this requirement cannot be provided
the to be installed plasma6-workspace-devel-6.0.2-2.1.x86_64 requires &apos;cmake(Plasma) &gt;= 6.0.2&apos;, but this requirement cannot be provided</html>
Expected Result
============
should install
How to Reproduce
===============
1. Go to '...'discover
2. Click on '....'update

Further Information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)

**Comment by danidoni** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are not a way to request support from us for some specific instance or packaging issues.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members.

Thank you for your consideration.
