### ISSUE TITLE
Searching for new packages does not work

### ISSUE THREAD

**Issue by hwoarang** [openSUSE/open-build-service#1594]
Hi,

I am reporting here what has already been reported in the list
https://lists.opensuse.org/opensuse-buildservice/2016-02/msg00057.html
so we don't forget.

New packages such as 'firewalld' or 'python-slip' and possibly others do not turn up when searching for them in the web UI but they appear in searches when using the 'osc' tool.

**Comment by mdeniz** [comment]
Is this still valid?

**Comment by hennevogel** [comment]
sounds like an out of sync search index. happens from time to time...
