### ISSUE TITLE
Hermes is no longer fed with update streams

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#1596]
For the osc collab plugin we rely on the hermes feed at
https://hermes.opensuse.org/feeds/25545,25547,55386,55387,55388.rdf

Since Feb 25, this feed no longer gets updates, which means the plugin is no longer informed about package changes.

**Comment by adrianschroeter** [comment]
got solved again

**Comment by hennevogel** [comment]
How?
