### ISSUE TITLE
Accepting an already accepted SR fails but does a forward anyway

### ISSUE THREAD

**Issue by ismail** [openSUSE/open-build-service#1602]
Case in point: https://build.opensuse.org/request/show/365862

DimStar accepted the submit request before me, but not knowing this I clicked "Accept" anyway and resulted in an OBS error saying "can't change state from accepted to..." but it created a Factory forward anyway: https://build.opensuse.org/request/show/365871

Here is the original forward SR from DimStar: https://build.opensuse.org/request/show/365865

**Comment by hennevogel** [comment]
This is fixed by 91e8cf59e12ad0433a0ee0d25e535a039f164315
