### ISSUE TITLE
Download logfile

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#1603]
The "Download logfile" button in webui used to redirect to the api. This transfered the entire raw logfile to be processed local.

Now it just redirects to the same webui page, which just shows the tail of logfile.

**Comment by mmohring** [comment]
You closed this issue. Which commit fixes it ?

**Comment by hennevogel** [comment]
Get some new glasses, he referenced a close issue ;-)

**Comment by coolo** [comment]
@mmohring  this issue is not closed - it's open
@hennevogel the referenced issue is closed as duplicate to this one

in the other issue is more information meanwhile :)

**Comment by ChrisBr** [comment]
> this redirected page only does something meaningful if you're logged in - for anonymous you're just redirected back. So either rawlog needs to be accessible for anonymous or you remove the download logfile link for anonymous
> 
> We do not want to remove access for anonymous (if anonymous access is enabled explicit). So it is fine to open this specific route. Or better point to the /public route in anonymous case. This should have the check for anonymous configuration already.

Ahh got it, the anonymous login was the missing part! Thanks, will look into it!
