### ISSUE TITLE
New frontend: Combine the two text boxes when reviewing SRs

### ISSUE THREAD

**Issue by asdil12** [openSUSE/open-build-service#16049]
**Currently we have two text boxes - one for entering a reason for accepting/declining a SR, and one for commenting:**
![image](https://github.com/openSUSE/open-build-service/assets/725608/e7ee8109-42c0-4c8d-958e-71e8105c72ab)

**It would be better to have only one box, like we have on github or gitea:**
![image](https://github.com/openSUSE/open-build-service/assets/725608/3d80e093-3b56-4e51-b88b-d17d08dceb1b)

**Comment by hellcp-work** [comment]
Worth noting, GitHub and Gitea only allow you to close a PR from that box, merging a PR doesn't have the option to leave a comment besides the merge commit text which is seperate

**Comment by rubhanazeem** [comment]
It has been addressed in #16960
