### ISSUE TITLE
dead lock issue between scheduler and signer

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#1606]
We observed a deadlock issue, both processes (signer and scheduler) were flock'ing the same status job file and just hang. It seems this can happen when the job gets signed and also aborted/killed on the worker at the same time (because it just became obsolete).

**Comment by mlschroe** [comment]
Sorry, it can't happen that way (unless there's a bug in the kernel). A deadlock can only occur if the processes try to lock multiple different files in a cycle. If it's the same status file, no deadlock can happen, as at least one process gets the lock. (lsof is your frind for the next time...)
