### ISSUE TITLE
Project copy with binaries rebuilds the project anyway

### ISSUE THREAD

**Issue by tuminoid** [openSUSE/open-build-service#1608]
Steps:
 - Have a project which has packages in succeeded and is in stable state
 - Issue: `osc api -X POST "/source/<targetproject>?cmd=copy&project=<sourceproject>&withbinaries=1&noservice=1`

Expected:
A newly created project is created, that is not rebuilding packages and mirrors source project state, with binaries.

Actual:
Rebuild happens for the project, as if binaries were not copied along with sources.

Issue:
Some meta files are not copied, and thus packages are scheduled for rebuild.

**Comment by adrianschroeter** [comment]
IMHO you can create the target project first and set it to build disabled. Of course packages may enforce building, so if this is not enough we talk some build flag extension to enforce build-disabled.

**Comment by tuminoid** [comment]
How does a package enforce building? What controls it?

**Comment by adrianschroeter** [comment]
A build-enable flag in a package is more important then a project build-disable flag.

**Comment by tuminoid** [comment]
The build enable flag is an issue, so that route is no go.

Is it correct that backend won't copy meta files along with sources and binaries?

After copy, in `/srv/obs/build/<prj>/<repo>/<arch>`, files `<pack>/.meta.success`, `:full/<pack>.meta`, `:meta/<pack>` seem to be missing. Putting them in place seems to help (most of the time), but is it correct?

**Comment by adrianschroeter** [comment]
right, we need to copy the meta files as well.

**Comment by mlschroe** [comment]
Hopefully fixed with commit d6506726a27fd883751215129d622a7bdcabe342 in master.

**Comment by kkeil** [comment]
This is not working, tested with yesterdays unstable appliance. The copied project starts building after the copy was finished, trigger reason was "new build".
