### ISSUE TITLE
Revoke requests created by different user

### ISSUE THREAD

**Issue by laenion** [openSUSE/open-build-service#16105]
# Issue Description
In https://build.opensuse.org/request/show/926201 you can seen an automatically generated request to submit the development project to Factory, however - as dimstar mentioned in the comments - it was already accepted from another source and thus declined.

The submit request however continued appearing on the submit request screen as being able to be superseeded, but I didn't want to do that, because from its context nothing really superseeded that request. On the other hand I wasn't able to revoke the request from the web interface either, so it kept hanging there for two years.

Only recently I discovered thanks to @Vogtinator that I _do_ have the permissions to revoke it: from the command line with `osc rq revoke 926201`.

Expected Result
============
I would have expected that I'm able to revoke the request from the web interface even when I'm not the originator, but do have the permissions to do so.

How to Reproduce
===============
1. Open any project where you have maintainer permissions
2. Check whether there are any pending submit requests by other users
3. Check whether you can Revoke the request from the web interface

**Comment by adrianschroeter** [comment]
you should only have permission to revoke it when you have maintainer rights in the source.

you should *NOT* have this permission if you only have maintainer rights in the target.
The reason is that revoke is an agreement that the submission is wrong. The target must not be able to do that.

Is this the case in your situation?

**Comment by laenion** [comment]
Yes, I'm a maintainer of the source package (and only of the source package - the target was Factory).
