### ISSUE TITLE
rake docker:build fails because of root access rights on frontend container.

### ISSUE THREAD

**Issue by gl-yziquel** [openSUSE/open-build-service#16114]
# Issue Description

I just checked out master (f60852d85abc4e8dbd168822f6adbd647345e538) on github's open-build-service, looked at CONTRIBUTING.md and, accordingly, ran `rake docker:build`.

It fails because, in the `frontend` container, the `rake dev:bootstrap RAILS_ENV=development` command that issued via docker compose expects to write a file in `config/database.yml` copied from the homonymous (with `.example` suffix) without the sufficient access rights to create the file. Only `root` may write, but not `frontend`.

The CONTRIBUTING.md instructions fail because of that.
 
Expected Result
============

The `rake docker:build` command should succeed, and the `config/database.yml` file in the `frontend` container should be correctly scaffolded.

How to Reproduce
===============

1. Clone the git repo on github called `open-build-service`
2. Initialise the git submodules.
3. run `rake docker:build`

Further Information
===============

I am running docker rootless. But I doubt this is the reason for the failure.

**Comment by hennevogel** [comment]
The setup is supposed to be run as user. How did you run this, please share the exact steps. Additionally share the content of `docker-compose.override.yml` and the output of `id -u` of the user you ran this with.

**Comment by danidoni** [comment]
@gl-yziquel can you share how did you run this so we can debug it a bit more?

**Comment by gl-yziquel** [comment]
> @gl-yziquel can you share how did you run this so we can debug it a bit more?

Not enough time, unfortunately. If I find time to come back to it (which I really want), I'll give out more info. Meanwhile, if the bug report is not precise enough, feel free to close it.

**Comment by danidoni** [comment]
> Not enough time, unfortunately. If I find time to come back to it (which I really want), I'll give out more info. Meanwhile, if the bug report is not precise enough, feel free to close it.

Alright, feel free to open it again when you have the time!
