### ISSUE TITLE
Parts of login button unclickable when viewing a source file

### ISSUE THREAD

**Issue by aspiers** [openSUSE/open-build-service#1616]
This seems to be a fairly simple CSS bug which makes it hard (or maybe even impossible) to log in from `.../package/view_file/...` URLs using the mouse.

Steps to reproduce:

1. Ensure you are logged out of https://build.opensuse.org/
2. Visit https://build.opensuse.org/package/view_file/Cloud:OpenStack:Master/openstack-neutron/0001-L3-agent-migration-should-only-choose-enabled-agent.patch?expand=1
3. Click the green "Log In" text to get the Log In drop-down dialog
4. Move the mouse so that its X coordinate is within the width of the green "Log In" button, and its Y coordinate is within the lines of the patch file.
5. The mouse should now be within the "Log In" button, but clicking will not activate the button.

Happens in Chrome and Firefox.  Using either inspector shows that the mouse focus is being stolen by the lines of the file, which suggests maybe some CSS z-index or transparency issue.

**Comment by aspiers** [comment]
I have traced this down to a `z-index: 2` which is being set for each `<pre>` line of code under `<div class="CodeMirror-code">`.  If you disable that z-index property, the problem goes away.

**Comment by bgeuken** [comment]
Thanks for digging into this:+1: It should be fixed with #1644. Probably deployed on Thursday

**Comment by aspiers** [comment]
Thanks!
