### ISSUE TITLE
Request show redesign does not display whitespace changes

### ISSUE THREAD

**Issue by eliroca** [openSUSE/open-build-service#16180]
# Issue Description
Request show redesign does not display whitespace changes like before.

Expected Result
============
I like that in the old version it is clear what's changed on a line, highlighting even whitespace changes.

Screenshots
==========
![image](https://github.com/openSUSE/open-build-service/assets/42994510/297c917e-c04e-4c4f-8e32-eb293d80f91a)
![image](https://github.com/openSUSE/open-build-service/assets/42994510/2bdb4afa-07ad-4868-90af-227329b2a378)

**Comment by eduardoj** [comment]
In our public instance, whitespace changes are **not** highlighted both out of beta and inside beta.

The behaviour described in the issue happens in our internal instance.

**Comment by rubhanazeem** [comment]
It has been addressed in #16938

**Comment by eliroca** [comment]
Awesome, thank you!
