### ISSUE TITLE
Bad Fedora:40 standard dod repo url

### ISSUE THREAD

**Issue by rncbc** [openSUSE/open-build-service#16224]
For security issues, please refer to [SECURITY.md](https://github.com/openSUSE/open-build-service/blob/master/SECURITY.md).

Any content related problems of our public instance build.opensuse.org, like not building packages or distribution setup should
get reported either on the mailing lists or in the [openSUSE Bugzilla](https://bugzilla.opensuse.org).

Having problems with the OBS command line interface osc? It has its own issue tracker here: https://github.com/openSUSE/osc

Having problems with the obs-build tool that controls the build process? It has its issue tracker here: https://github.com/openSUSE/obs-build

Good to go? Then please remove these lines above, including this one, and help us understand your issue by answering the following:

# Issue Description

Expected Result
============

How to Reproduce
===============

Further Information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)

**Comment by rncbc** [comment]
simply put, on https://build.opensuse.org/projects/Fedora:40/meta,  I see :

	url="https://dl.fedoraproject.org/pub/fedora/linux/development/40/Everything/..."

leads to a 404 (Not Found)...

shouldn't it be:
	
	url="https://dl.fedoraproject.org/pub/fedora/linux/releases/40/Everything/..."

instead?

**Comment by eduardoj** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are not a way to request support from us.

However there is a vibrant community of OBS developers and admins that support each other with developing and operating the OBS. They meet online in a the OBS IRC chat (irc://irc.libera.chat/openSUSE-buildservice) or on the [OBS mailing list](https://lists.opensuse.org/archives/list/buildservice@lists.opensuse.org/)).

Over there you can ask questions if you have trouble understanding something, you can seek advice and mingle with the OBS operator community.

Thank you for your consideration.

**Comment by adrianschroeter** [comment]
On Mittwoch, 29. Mai 2024, 16:37:22 CEST Rui Nuno Capela wrote:
> simply put, on https://build.opensuse.org/projects/Fedora:40/meta,  I see :
> 
> 	url="https://dl.fedoraproject.org/pub/fedora/linux/development/40/Everything/..."
> 
> leads to a 404 (Not Found)...
> 
> shouldn't it be:
> 	
> 	url="https://dl.fedoraproject.org/pub/fedora/linux/releases/40/Everything/..."
> 
> instead?

meanwhile yes, it was setup during development phase.

fixed that now.

-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH, Frankenstraße 146, 90461 Nürnberg, Germany
(HRB 36809, AG Nürnberg) Geschäftsführer: Ivo Totev
