### ISSUE TITLE
GET /source/{project_name}/{package_name}?view=info errors out but returns a HTTP 200 on error

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#16233]
# Issue Description

The route `GET /source/{project_name}/{package_name}?view=info` only appears to work for spec files. However, instead of erroring out with a `400` for non-spec packages, it returns a `200` with a payload indicating the error:
```ShellSession
$ osc api -H "/source/openSUSE:Factory/spack-image?view=info"
DEBUG: ----------------------------------------
DEBUG: GET https://api.opensuse.org/source/openSUSE:Factory/spack-image?view=info
DEBUG: send: b'GET /source/openSUSE:Factory/spack-image?view=info HTTP/1.1\r\nHost: api.opensuse.org\r\nAccept-Encoding: identity\r\nuser-agent: osc/1.7.0\r\nAccept: application/xml\r\n\r\n'
DEBUG: reply: 'HTTP/1.1 200 OK\r\n'
DEBUG: header: Date: Fri, 31 May 2024 12:25:13 GMT
DEBUG: header: Server: Apache/2.4.51 (Linux/SUSE)
DEBUG: header: Strict-Transport-Security: max-age=31536000
DEBUG: header: cache-control: private, no-transform
DEBUG: header: referrer-policy: strict-origin-when-cross-origin
DEBUG: header: x-permitted-cross-domain-policies: none
DEBUG: header: x-xss-protection: 1; mode=block
DEBUG: header: x-opensuse-runtimes: {"view":null,"db":3.5785000324249268,"backend":0}
DEBUG: header: x-request-id: 998cf85f-09d9-4684-870b-583f182ad4ee
DEBUG: header: x-opensuse-apiversion: 2.11~alpha.20240531T090908.8a4ff22f0
DEBUG: header: x-download-options: noopen
DEBUG: header: x-runtime: 0.016000
DEBUG: header: x-frame-options: SAMEORIGIN
DEBUG: header: x-content-type-options: nosniff
DEBUG: header: x-powered-by: Phusion Passenger(R)
DEBUG: header: content-type: text/xml
DEBUG: header: cache-control: no-cache
DEBUG: header: content-length: 206
<sourceinfo package="spack-image" rev="5" vrev="5" srcmd5="521f44faa87e9871fdeb3b9d92e8e18c" verifymd5="521f44faa87e9871fdeb3b9d92e8e18c">
  <error>no file found for build type 'spec'</error>
</sourceinfo>
```

Expected Result
============

The build service should return a `400` or another error code as it cannot provide the requested info.

**Comment by eduardoj** [comment]
After taking a look, changing the returning code to 400 depends very much on the API design.

There are more cases where an error code could be returned. I'm not aware of all of them, but doing a few tests I could trigger this similar response, also returing a 200 code:
```xml
<sourceinfo package="aut" srcmd5="d41d8cd98f00b204e9800998ecf8427e">
  <error>no source uploaded</error>
</sourceinfo>
```

If we want to change the HTTP error code returned, we should take in account all cases. 

For now, let's stay with this API design and mark this issue as a feature instead of a bug.

**Comment by mlschroe** [comment]
It returns valid information, i.e. all the attributes of the sourceinfo elements. So the request succeeds and should return code 200. It also returns the result of the recipe parsing, which resulted in an error. But that's not an error of the request.

**Comment by dcermak** [comment]
While maybe technically correct, it makes this API route highly inconvenient to use, as a 200 doesn't mean that it'll contain the information that you need.

**Comment by mlschroe** [comment]
Depends on what you need. I mainly need the srcmd5 from the view=info query, and it is present. It just returns info about the source state, the error from parsing the recipe is part if the info.

**Comment by dcermak** [comment]
> Depends on what you need. I mainly need the srcmd5 from the view=info query, and it is present. It just returns info about the source state, the error from parsing the recipe is part if the info.

My primary use case is to obtain the extended package information, like package name & version.

Despite that, this route has a bigger issue: it will return a 200 even for non-existent packages:
```ShellSession
$ osc api -H "/source/SUSE:SLFO:Main:Build/helm?view=info&parse=1"
DEBUG: ----------------------------------------
DEBUG: GET https://api.opensuse.org/source/SUSE:SLFO:Main:Build/helm?view=info&parse=1
DEBUG: send: b'GET /source/SUSE:SLFO:Main:Build/helm?view=info&parse=1 HTTP/1.1\r\nHost: api.opensuse.org\r\nAccept-Encoding: identity\r\nuser-agent: osc/1.7.0\r\nAccept: application/xml\r\n\r\n'
DEBUG: reply: 'HTTP/1.1 200 OK\r\n'
*snip*
<sourceinfo package="helm">
  <error>404 package 'helm' does not exist</error>
</sourceinfo>
$ # while the actual package doesn't exist
$ osc api "/source/SUSE:SLFO:Main:Build/helm"
Server returned an error: HTTP Error 404: package 'helm' does not exist
package 'helm' does not exist
```

**Comment by dcermak** [comment]
For the record, this appears to be some kind of peculiarity of the SLFO:Main:Build project. Querying a non-existent package in Factory yields the expected error:
```ShellSession
$ osc api "/source/openSUSE:Factory/foobar?view=info&parse=1"
Server returned an error: HTTP Error 404: Not Found
Package not found: openSUSE:Factory/foobar
```
If I'd have to guess, I'd blame `scmsync`
