### ISSUE TITLE
Very long list of projects to select on Notifications page

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#16235]
# Issue Description

Some users report a long list of projects to select from the notifications page. This has appeared after recent changes to the notifications page.

After changing the filter to, say, show only the comments, scrolling down until finding the "Apply" button, makes the page unusable.

Expected Result
============
Changing and applying filters in the notification page is usable.

How to Reproduce
===============
1. Go to https://build.opensuse.org/my/notifications
2. Click on "Comments"
3. Scroll down to click the "Apply" button

**Comment by eduardoj** [comment]
> It also leads to performance problems in that case. See
> 
> https://obs-measure.opensuse.org/d/Gpp3B1Pik/measurements-per-action?orgId=1&var-Action=Webui::Users::NotificationsController%23index&var-beta=All

Fixed in #16243.

**Comment by hennevogel** [comment]
The last bit of performance work was done in #16257
