### ISSUE TITLE
Attempt to edit news item ends in 500

### ISSUE THREAD

**Issue by smithfarm** [openSUSE/open-build-service#16308]
# Issue Description
Configuration -> Manage News -> little edit button on any news item -> BOOM (Error 500)

Expected Result
============
Editing dialog is displayed instead of BOOM (Error 500)

**Comment by hennevogel** [comment]
Are you talking about IBS?

**Comment by smithfarm** [comment]
> Are you talking about IBS?

Yeah, nevermind, it's been fixed in the meantime.

**Comment by smithfarm** [comment]
Fixed by the latest redeploy.
