### ISSUE TITLE
Unabled to delete project in home:user namespace

### ISSUE THREAD

**Issue by ddiss** [openSUSE/open-build-service#16328]
# Issue Description
I cannot delete a project in my home:user namespace:
https://build.opensuse.org/project/show/home:ddiss:bsc1226031_aa_policy_unpack_tw
I was able to request deletion via https://build.opensuse.org/request/show/1180328 but I'm not able to accept the request via web UI or `osc rq accept 1180328` (`HTTP Error 403: Forbidden`).

The project was created using the kernel-source `./scripts/osc_wrapper upload` helper script, with `ddiss` user credentials. The script can be found at:
https://github.com/openSUSE/kernel-source/blob/stable/scripts/osc_wrapper

Expected Result
============
I should be able to delete the project.

How to Reproduce
===============
1. `git clone https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git`
1. `export LINUX_GIT="$(realpath linux)"`
1. `git clone https://github.com/opensuse/kernel-source`
1. `cd kernel-source && git checkout origin/stable`
1. `./scripts/tar-up.sh`
1. `./scripts/osc_wrapper upload home:<user>:kernel_source_obs_test`
1. attempt to delete the `home:<user>:kernel_source_obs_test` project

`scripts/osc_wrapper` uses open build service credentials from oscrc.

**Comment by Werkov** [comment]
I wonder if this would work if `home:<user>` project existed.

**Comment by ddiss** [comment]
> I wonder if this would work if home:<user> project existed.

Good point, will try creating that and then reproducing

**Comment by danidoni** [comment]
> Good point, will try creating that and then reproducing

You should be able to delete your projects now.

**Comment by ddiss** [comment]
> > Good point, will try creating that and then reproducing
> 
> You should be able to delete your projects now.

Thanks, I created `home:ddiss` and was subsequently able to delete `home:ddiss:bsc1226031_aa_policy_unpack_tw`. Is it dependent on `home:<user>` existence, or was it just a coincidence with the build.opensuse.org roll out of your fix?

**Comment by danidoni** [comment]
> Thanks, I created `home:ddiss` and was subsequently able to delete `home:ddiss:bsc1226031_aa_policy_unpack_tw`. Is it dependent on `home:<user>` existence, or was it just a coincidence with the build.opensuse.org roll out of your fix?

My fix would have allowed you to delete that project without creating your home project. But anyway, problem solved, right?

**Comment by ddiss** [comment]
> My fix would have allowed you to delete that project without creating your home project.

Ah okay, great.

> But anyway, problem solved, right?

Yes - thanks again!
