### ISSUE TITLE
Support for Ubuntu 16.04 and forthcoming Debian releases requires SHA2 signing support

### ISSUE THREAD

**Issue by danimo** [openSUSE/open-build-service#1648]
For details, see https://juliank.wordpress.com/2016/03/15/clarifications-and-updates-on-apt-sha1/

ref: https://github.com/owncloud/client/issues/4596

/cc @adrianschroeter

**Comment by jnweiger** [comment]
If I read https://wiki.debian.org/Teams/Apt/Sha1Removal correcty, instrummenting obs_signer to run gpg with --digest-algo SHA256 might be sufficient.

**Comment by jktjkt** [comment]
I wasn't aware of this bugreport, which is why I opened https://github.com/openSUSE/obs-sign/issues/5 .

**Comment by hennevogel** [comment]
Which is totally the right place for this bug report...
