### ISSUE TITLE
Rendering of patches broken in OBS Web UI

### ISSUE THREAD

**Issue by mwilck** [openSUSE/open-build-service#16503]
# Issue Description
`+` lines (additions) are rendered incorrectly in the Web UI for newly added patches.

![Screenshot](https://github.com/user-attachments/assets/5bcb9b93-c085-4b2a-aa39-829f9a6d0c94). See the line starting with `static int` in the screenshot below.

Expected Result
============

The diff in the screenshot should be rendered like this:
```
++++++ hplip-pserror-c99.patch (new)
--- hplip-pserror-c99.patch
+++ hplip-pserror-c99.patch
@@ -0,0 +1,17 @@
+prnt/pserror.c: Replace an implicit int with an explicit int
+
+Submitted upstream: <https://bugs.launchpad.net/hplip/+bug/1997875>
+
+diff --git a/prnt/hpps/pserror.c b/prnt/hpps/pserror.c
+index 114d7e1b5fa364fb..493b49c27917a7e6 100644
+--- a/prnt/hpps/pserror.c
++++ b/prnt/hpps/pserror.c
+@@ -24,7 +24,7 @@ extern char *program ;       /* Defined by main program, giving program name */
+ void message(int flags, char *format, ...)
+ {
+   va_list args ;
+-  static column = 0 ;         /* current screen column for message wrap */
++  static int column = 0 ;     /* current screen column for message wrap */
+   char msgbuf[MAX_MESSAGE] ;  /* buffer in which to put the message */
+   char *bufptr = msgbuf ;     /* message buffer pointer */
+ 

```

How to Reproduce
===============

See https://build.opensuse.org/request/show/1187590/changes

**Comment by Vogtinator** [comment]
Works for me here, not using the request redesign:

![Bildschirmfoto_20240716_082539](https://github.com/user-attachments/assets/b44ec4ca-7b81-4b62-be44-e9c61078f187)
