### ISSUE TITLE
Issue by creating osc build specfile | Illegal Char - rc1 of Release | setting ReleaseVer not possible with rpmbuild

### ISSUE THREAD

**Issue by torsten-online** [openSUSE/open-build-service#16511]
Hi,

Hint: This is not a major obs problem/issue - its more about working together with OBS! Thanks

I tried to build up a new supported release of Crowdsec for OpenSUSE Leap Micro and Tumbleweed, because latest version is not supported by the vendor at the moment.

There was before a "ongoing" release project - from this I just created my first OSC Branch:

https://build.opensuse.org/package/show/home:torsten:crowdsec/crowdsec

When I try to build up the old Version - based on this - I get a ReleaseVer Issue with rpmbuild:

````
  4s] WARNING could not set SOURCE_DATE_EPOCH, ensure mtime is in $TOPDIR/SOURCES/_scmsync.obsinfo or BUILD_CHANGELOG_TIMESTAMP is set in /.buildenv
[    4s] WARNING could not set SOURCE_DATE_EPOCH, ensure BUILD_RELEASE is set in /.buildenv
[    4s] + exec rpmbuild -ba --define '_srcdefattr (-,root,root)' --nosignature --undefine _enable_debug_packages /home/abuild/rpmbuild/SOURCES/crowdsec.spec
[    4s] error: line 3: Illegal char '-' (0x2d) in: Version:        1.6.3-rc1
[    4s] 
[    4s] dynabeat failed "build crowdsec.spec" at Wed Jul 17 01:02:21 UTC 2024.
[    4s] 
```` 

I can't solve this - and its maybe also my missing OBS/rpmbuild Knowledge. It will be very helpful if someone can look deeper into the specfile to make it compatible to the opensuse buildsystem.

ITs creating release every time with the branch name and not whats definied at the rpm specfile, thats curious for me and maybe a "missing knowledge" problem together with opensuse buildsystem?

I just know its not a problem or issue of the obs - its more about missing knowledge of the builders.

Just googling doesnt help. So, if anyone knows how to solve that rpmbuild problem, it will be very helpful to get a working release of Crowdsec for OpenSuSE Latest Releases! 

Thanks

Have A lot Of Fun
Torsten

**Comment by torsten-online** [comment]
Hi,

the chat support for opensuse packaging is awesome, so the solution was:

`````

**Comment by adrianschroeter** [comment]
in general this is a rpm ruling which limits you here. You should use 1.6.3~rc1  (a tilde), so rpm would also handle 1.6.3 newer than this pre candidate.
