### ISSUE TITLE
broken url on wiki page

### ISSUE THREAD

**Issue by yvs2014** [openSUSE/open-build-service#16533]
# Issue Description
trying to find out meta-configuration examples came around a broken url

Expected Result
============
some example at the link

How to Reproduce
===============
1. Go to [OBS Major Release HOWTO](https://github.com/openSUSE/open-build-service/wiki/OBS-Major-Release-HOWTO)
2. Click on 'Get our [stable project meta example](https://github.com/openSUSE/open-build-service/blob/master/dist/stable_project_meta.xml.example)' (or a couple next urls after that one)
3. See [404 - page not found](https://github.com/openSUSE/open-build-service/blob/master/dist/stable_project_meta.xml.example) error message

**Comment by eduardoj** [comment]
The link is now fixed. Thanks for reporting the issue!
