### ISSUE TITLE
page title for requests should be more informative

### ISSUE THREAD

**Issue by aspiers** [openSUSE/open-build-service#1655]
For example, the HTML page `<title>` for https://build.opensuse.org/request/show/379272 is:

```
Request 379272 - openSUSE Build Service
```

but that really doesn't tell the user much at all.  A better title would be

```
Cloud:OpenStack:Master / openstack-neutron - Request 379272 - openSUSE Build Service
```

**Comment by bgeuken** [comment]
As coolo mentioned in 1799, there can be multiple request targets, packages and even projects. That would be the tricky part.

**Comment by jengelh** [comment]
For most people, single-package SRs are the norm (also because openSUSE:Factory only takes those). At least let's try to accomodate them for the time being.
