### ISSUE TITLE
Web UI does not show that package is a link

### ISSUE THREAD

**Issue by sreeves** [openSUSE/open-build-service#1656]
Compare the webui for 
https://build.suse.de/package/show/Devel:Desktop:SLE12:SP2/gnome-control-center
That shows as a link and in the "Source Files" section gives the "show unmerged sources" option

versus

https://build.suse.de/package/show/Devel:Desktop:SLE12:SP2:Next/gnome-control-center
It does not show as a link and does not give the option to "show unmerged ..."
You can use "osci ls -u Devel:Desktop:SLE12:SP2:Next gnome-control-center" to verify it's a link to the openSUSE.org:GNOME:Next gnome-control-center package

**Comment by hennevogel** [comment]
Don't know how the later one is setup but it's not a branch. There is `linktobranch` in osc to *fix* this situation...

**Comment by DimStar77** [comment]
The working one points to a 'local' package whereas the package not showing link info has a _link pointing to a remote OBS

I can reproduce  the same on my own OBS instance, where link to openSUSE.org:* do not show correctly in the webui

**Comment by sreeves** [comment]
This is still not showing correctly as a link and there is another problem. Compare the two links...
https://build.suse.de/package/show/Devel:Desktop:SLE12:SP2/evince
https://build.suse.de/package/show/Devel:Desktop:SLE12:SP2/gnome-control-center

in the web gui gnome-control-center shows as a link but evince does not.
Looking at them with "osci list Devel:Desktop:SLE12:SP2 <package-name"  shows they are both links. This is without even linking to a remote OBS instance like the original problem.

**Comment by mdeniz** [comment]
Is this still valid?

**Comment by JanZerebecki** [comment]
Duplicate of #3948?

**Comment by hennevogel** [comment]
Duplicate of #673
