### ISSUE TITLE
Hermes RSS feed no longer contains proper data

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#1658]
Also reported at hermes : https://github.com/openSUSE/hermes/issues/3

But the root cause is more likely a change in the OBS side of things.

For a couple days now, the hermes feed used for the collab plugin
https://hermes.opensuse.org/feeds/25545,25547,55386,55387,55388.rdf

no longer contains valid entries.

The articles no longer contain info about who, what package / project.

This kills all workflows based on 'osc collab'

**Comment by hennevogel** [comment]
Whats the use of duplicating the issue? :-)

**Comment by coolo** [comment]
not a hermes problem. there are no events arriving there

**Comment by coolo** [comment]
we see this in hermes apache log:

GATEWAY-IP - - [13/May/2016:13:05:14 +0200] "GET /index.cgi?rm=notify&_type=OBS_SRCSRV_COMMIT&files=Modified:%0A%20%20_patchinfo%0A%0A&package=patchinfo&project=
openSUSE:Maintenance:5088&rev=3&time=1463137467&user=AndreasStieger HTTP/1.1" 403 1042 "-" "BSRPC 0.9.1"

And we only allow the old IP of the old HW source server. So this got broken by migrating source server to VM.

What is interesting though is that this collab thingy is the only thing keeping hermes alive - so possibly this should migrate to a OBS solution.

**Comment by coolo** [comment]
I asked @darix and he said white listing that IP is good enough for the time being -> hermes feeds should roll again

**Comment by DimStar77** [comment]
the feed 'rolls' -  but is stille empty

**Comment by hennevogel** [comment]
hermes is dead
