### ISSUE TITLE
maintenance request handling with embargo date set seems to have changed behaviour

### ISSUE THREAD

**Issue by bugfinder** [openSUSE/open-build-service#16609]
with the old code we were able to approve the request just the delayed job handling the actual stat change delayed the action until the date had passed.
with the new code, we can no longer approve the request as long as the embargo date has not passed.

is this an intended change ?

**Comment by hennevogel** [comment]
> is this an intended change ?

Most likely not. I just refactored there a bit in #14047. What happens if you approve the request?

**Comment by hennevogel** [comment]
And we are talking IBS right?

**Comment by darix** [comment]
i linked you the request in chat. and if we try to `osc approve` the request we get told "you can not touch this because embargo"

**Comment by hennevogel** [comment]
How do you accept the request?

**Comment by hennevogel** [comment]
BTW the delayed job you mentioned only ever triggers on requests that have an `approver` set. The request @darix shared does not.

**Comment by darix** [comment]
because we can not approve the request as it gets denied with http 400 "request is under embargo"

**Comment by hennevogel** [comment]
If you are not telling me what *exactly* you do, what *exactly* happens and what *exactly* you expect to happen I will not be able to debug this...
