### ISSUE TITLE
app/views/webui/configuration/index.html.haml missing user registration enable/disable

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#16717]
Version: obs-server-2.11~alpha.20240717T133612.5d1eecb47-150600.17151.1.noarch on Leap 15.6

# Issue Description

Using `osc api /configuration -e`, it's possible to edit:

```
<configuration>
  <title>OBS@a9</title>
  <description>!!</description>
  <name>private</name>
  <download_on_demand>on</download_on_demand>
  <enforce_project_keys>on</enforce_project_keys>
  <anonymous>off</anonymous>
  <registration>allow</registration>
  <default_access_disabled>off</default_access_disabled>
  <allow_user_to_create_home_project>on</allow_user_to_create_home_project>
  <disallow_group_creation>off</disallow_group_creation>
  <change_password>on</change_password>
  <obs_url>https://unconfigured.openbuildservice.org</obs_url>
…
```

but when that URI is opened using the web interface instead, is missing a _lot_ of checkboxes, such as Enable/Disable Registration, Access Enabled/Disabled, Group creation, etc.

Expected Result
============
Show the checkboxes for disallowing unregsitered/anonymous access.

How to Reproduce
===============
1. Install obs-server
2. Go to /configuration with firefox

**Comment by hellcp-work** [comment]
Modifying all the fields is not currently possible without modifying the `options.yml` file first. I added all the possible options that I could into the configuration page in #16790, but for things like `registration` and `anonymous`, that will have to wait until we can resolve https://trello.com/c/aLHCqDQD/192-improve-the-way-we-configure-obs
