### ISSUE TITLE
no $CARCH & custom variables('macroses') ignoration in sources urls [ Arch Linux ]

### ISSUE THREAD

**Issue by AlexTalker** [openSUSE/open-build-service#1671]
Hello!

I've been trying your amazing system, thanks for such great thing.

But I've failed to build package since $CARCH is not declared.

Then I've tried to rewrite the package but seems like if I set in sources anything other than PKGBUILD-declared variables($pkgbase,$pkgver, $pkgname...) OBS just ignore it and so sources downloading on package building stage when no internet connection is available.

Also seems like $source_i686 and $source_x86_64 is not usable too but they must be since so declared architecture-depend sources.

How could I resolve that?

Project is here:
https://build.opensuse.org/package/show/home:alextalker:aur/firefox-aurora

https://www.archlinux.org/pacman/PKGBUILD.5.html
https://www.archlinux.org/pacman/makepkg.8.html#_environment_variables

**Comment by hennevogel** [comment]
Please don't request support here. We have several places where users help each others, like the mailing list or the IRC channel. http://openbuildservice.org/support/

**Comment by AlexTalker** [comment]
https://features.opensuse.org/320952
Hope this was what you want.
