### ISSUE TITLE
Superseding failed: Supersed a request requires a 'superseded_by' parameter with the request id

### ISSUE THREAD

**Issue by mcepl** [openSUSE/open-build-service#16832]
# Issue Description

When I am creating SR via web interface (python313), I got “Superseding failed: Supersed a request requires a 'superseded_by' parameter with the request id.” How does it even make sense, when the request was created by OBS Web UI?

I have tried to create SR, which is now https://build.opensuse.org/request/show/1199398 (submited with `osc sr`), via the Web UI.

Expected Result
============
new SR

How to Reproduce
===============
1. no reliable reproducer, happened when I just clicked the submit request link in the diff tab

**Comment by eduardoj** [comment]
#16854 could have helped to mitigate this issue. Closing.

@mcepl please feel free to re-open the issue if you face it again
