### ISSUE TITLE
Authentication is slow

### ISSUE THREAD

**Issue by dmach** [openSUSE/open-build-service#16867]
# Issue Description
Osc tests use OBS in a container.
The OBS instance has no login proxy and relies on authenticating using username and password.
There's also no built-in cookie support in OBS.
Every request gets denied with 401 first and is repeated with credentials.
The first (denied) request completes almost instantly.
The second (authenticated) request takes at least 0.2s.
This adds big overhead to the testing times.

If the delay is there for a security reason to prevent brute-force attacks, it would be great to have an option to remove the delay in testing environments.

Expected Result
============
Authenticated requests with no overhead.

How to Reproduce
===============
1. Setup an OBS instance without login proxy
2. Run `osc -A ... who -H`
3. See `X-Runtime:` value - it should be way lower than `0.2`, probably somewhere around `0.05`

**Comment by eduardoj** [comment]
> 2\. Run `osc -A ... who -H`

This osc command translates to an HTTP request to this API endpoint `"/search/person?match=%40login%3D%27Admin%27"`

Could you confirm if you suffer from this delay also with the rest of the osc commands in your tests, or only with this endpoint?

**Comment by dmach** [comment]
> > 2. Run `osc -A ... who -H`
> 
> This osc command translates to an HTTP request to this API endpoint `"/search/person?match=%40login%3D%27Admin%27"`
> 
> Could you confirm if you suffer from this delay also with the rest of the osc commands in your tests, or only with this endpoint?

It is all the endpoints.
When I try this with `api.opensuse.org`, then the result is `x-runtime: 0.017677`.
It's most likely that fast because I authenticate with a session cookie instead of a password.

**Comment by hennevogel** [comment]
Hm, we talked about this privately, haven't we? You still have questions about this?

**Comment by dmach** [comment]
> Hm, we talked about this privately, haven't we? You still have questions about this?

We talked about how to switch OBS into auth proxy mode and that works fine.

This is a generic bug report (unrelated to my osc test setup) that OBS adds 0.2 seconds to every request in instances using the default settings (== do not run in the auth proxy mode). From that perspective, it's a bug that should be fixed. If it's a feature, it should be explained and documented.

**Comment by hennevogel** [comment]
> OBS adds 0.2 seconds to every request in instances using the default settings 

There is no such thing happening. A request might take longer as it's actually doing something as opposed to a request that fails authentication but that's it.

**Comment by dmach** [comment]
> There is no such "delay" happening in OBS. A request might take longer as it's actually doing something as opposed to a request that fails authentication, but that's it.

You're not paying attention to what I wrote in https://github.com/openSUSE/open-build-service/issues/16867#issuecomment-2363531930 - the numbers clearly indicate that the 0.2s overhead is related to auth and nothing else.

**Comment by hennevogel** [comment]
> You're not paying attention to what I wrote in https://github.com/openSUSE/open-build-service/issues/16867#issuecomment-2363531930 - the numbers clearly indicate that the 0.2s overhead is related to auth and nothing else.

I don't doubt that, but your theory is that there is code in the API that would introduce this delay on purpose right? There is not...
