### ISSUE TITLE
enable/disable buttons missing in Project => Repositories WebUI view

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#1687]
It seems that in the current git master in the Project Repositories view the Flags graphics are empty. When opening the Webbrowsers Pageinfo view, the graphics icons_sprite.png is not shown anymore compared to the older versions prior 24.03.2016.

It worked in git master as of 24.03.2016.

**Comment by adrianschroeter** [comment]
Yep, happens also in our test instance: https://build-test.opensuse.org/project/repositories/home:adrianSuSE

Good spot! I don't deploy therefore today ....

**Comment by mmohring** [comment]
Your public test instance is a good idea. Will cross check next time with that test system when I report bugs.

**Comment by bgeuken** [comment]
Reverting e4bdbcca24d48eefbd3018b5b48ba0f5ad0b8f09 fixed it on my system. @hennevogel can you have a look?

**Comment by adrianschroeter** [comment]
The package build breaks now since something creates a broken symlink:

From the obs-server package build in build-test.opensuse.org:

[  249s] calling /usr/lib/rpm/brp-suse.d/brp-25-symlink
[  249s] INFO: relinking /srv/www/obs/api/app/assets/images/icons -> ../icons (was ../icons/)
[  249s] ERROR: link target doesn't exist (neither in build root nor in installed system):
[  249s]   /srv/www/obs/api/app/assets/images/group.png -> /srv/www/obs/api/app/assets/images/icons/publish_enabled_blue.png

**Comment by mmohring** [comment]
Adrian, you were faster :) Same problem here.

**Comment by hennevogel** [comment]
I don't know nothing about the package builds :-)

**Comment by adrianschroeter** [comment]
On Donnerstag, 7. April 2016, 04:11:35 wrote Henne Vogelsang:
> I don't know nothing about the package builds :-)

sorry, but this is too easy ...

The package is not creating these links, the brp scripts are just the
messenger here.

You should be able to reproduce by calling

 bundle exec rake assets:precompile RAILS_ENV=production RAILS_GROUPS=assets

and check for app/assets/images/group.png

**Comment by adrianschroeter** [comment]
@mdeniz I dunno if henne gets to this today, could you maybe also have a look?

I consider the revert the changes otherwise, since it is really blocking us atm.

thanks

**Comment by mmohring** [comment]
I have reverted the change to see if that git snapshot is otherwise working fine. It does.

@hennevogel can you explain why you renamed the image files ?

**Comment by hennevogel** [comment]
Awesome, symlinks in assets. Which genius came up with this? :-)

**Comment by bgeuken** [comment]
You are free to fix it;-)
