### ISSUE TITLE
WebUI Rebuild Time "check" button results in "404: Not Found"

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#1691]
For example:

Goto Page `Projects > OBS:Server:Unstable > Rebuild Time of SLE_12/x86_64` and click "check" button.

Happens in git master as well a b.o.o.

**Comment by bgeuken** [comment]
Does this still happen?

I followed your description and landed here: https://build.opensuse.org/project/rebuild_time/OBS:Server:Unstable?arch=x86_64&repository=SLE_12

No 404 for me

**Comment by mmohring** [comment]
Press the "check" button below the graphics, then comes the 404.

**Comment by bgeuken** [comment]
Should have read more properly^^

**Comment by bgeuken** [comment]
#1700 should fix the button

**Comment by mmohring** [comment]
Thanks.
