### ISSUE TITLE
WebUI Sign up appears but not working if anonymous off

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#1693]
In case in the OBS configuration we have:

`<anonymous>off</anonymous>`
`<registration>allow</registration>`

then the "New here? Sign up!" window appears in upper right corner of the starting Page WebUI, but when clicking sign up you get the error message "No anonymous access. Please log in!"

**Comment by eduardoj** [comment]
This is already fixed. Reproducing it results in this error message: 'Could not save the registration, details: Login must be given, Login must have more than two characters, and Password can't be blank'. Closing.

Please reopen if still applies.
