### ISSUE TITLE
[webui] User Management cannot create new user

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#1697]
IIRC there was a way to create users in `<API>/users`. I cannot find this anymore. The only way I found to create a user is to be logged in as super user and directly go to `<API>/user/register_user` at the moment.

**Comment by hennevogel** [comment]
The link to it is hidden wrongly hidden behind an `else` in [the view](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/views/webui/user/index.html.haml#L33)

**Comment by mmohring** [comment]
I did not see this. I was searching where it was and when it got removed :)

**Comment by mmohring** [comment]
I moved it into the if part and it worked.

**Comment by mmohring** [comment]
I have created a pull request for the fix  in #1698 .

**Comment by mmohring** [comment]
@hennevogel can you please check the pull request ?

**Comment by mdeniz** [comment]
Fixed in #1698

**Comment by mmohring** [comment]
Thanks for merging.
