### ISSUE TITLE
[webui] plotters on /monitor page exchanged

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#1699]
The two plotters on the [webui] /monitor page for the schedule and for the worker statistics are now exchanged and transparent.

**Comment by mmohring** [comment]
For current git master as of yesterday.

**Comment by bgeuken** [comment]
With exchanged you mean they swapped places?

And the graphs are not stacking anymore. That's right.

**Comment by bgeuken** [comment]
I figured the wrong labels now. I am going to fix this soon.

**Comment by mmohring** [comment]
You are correct, they do not stack anymore.

**Comment by bgeuken** [comment]
Just to gather some feedback, did you find the old, stacking graph more intuitive or the new one?

**Comment by mmohring** [comment]
The "Active Worker Graphics" is more intuitive if stacked because you have a 3rd information: the complete number of workers as the upper line if *not all* workers are busy or idle. For the "Packages scheduled for building" both variants (stacked or overlapped) are fine for me.

**Comment by mmohring** [comment]
Fixed in issue #1759 .
