### ISSUE TITLE
container-build can't use local images

### ISSUE THREAD

**Issue by msirringhaus** [openSUSE/open-build-service#16991]
# Issue Description
I have a repo with a container-image build that works fine. Additionally, I have other packages that should build more container-images, using the first one as a base.
https://build.opensuse.org/package/show/home:MSirringhaus:containers/leap_mozbuild

This image uses `FROM opensuse/distrobox-leap:latest`, which exists here:
https://build.opensuse.org/package/show/home:MSirringhaus:containers/distrobox-leap-image

The frontend shows:
```
blocked: waiting for dod resources to appear: container:opensuse/distrobox-leap:latest 
```
while `osc buildinfo -d home:MSirringhaus:containers leap_mozbuild openSUSE_Leap15_6_containerfile x86_64` shows:
```
expand args: container:opensuse/distrobox-leap:latest
--- now doing normal dependencies
added container:opensuse-distrobox-leap-latest@home:MSirringhaus:containers/openSUSE_Leap15_6_containerfile because of (direct):container:opensuse/distrobox-leap:latest
```

So somehow frontend and backend are in disagreement here?

The backend seems to find the image, but the build doesn't start.

Expected Result
============
Containers build with the local image from the repo as a base-image.

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of OBS developers and admins that support each other with developing and operating the OBS. They meet online in a the OBS IRC chat (irc://irc.libera.chat/openSUSE-buildservice) or on the [OBS mailing list](https://lists.opensuse.org/archives/list/buildservice@lists.opensuse.org/)).

Over there you can ask questions if you have trouble understanding something, you can seek advice and mingle with the OBS operator community.

Thank you for your consideration.

**Comment by dcermak** [comment]
This looks like a bug in the scheduler to be honest: it falsely looks for the container in the DOD repo `openSUSE:Registry` and ignores that the correct image is already found in the previous path entry.
