### ISSUE TITLE
The notification toolbar is not shown anymore

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#17012]
# Issue Description
The notification toolbar is now shown anymore

Expected Result
============
When you click on a notification, it should send you to the subject of the notification and a notification toolbar should appear at the top of the page, allowing you to mark that notification as read, or go back to the notifications listing.

How to Reproduce
===============
1. Go to [any of your notifications](https://build.opensuse.org/my/notifications)
2. Click on any of them
3. See no notification toolbar at the top of the page

**Comment by eduardoj** [comment]
I confirmed that the notification toolbar still appears on the following types of notifications:
- Roles Granted
- Roles Revoked
- Requests non-beta
- Comments non-beta

I'm taking a look at the rest of the cases and will fix them.
