### ISSUE TITLE
User.last_logged_in_at gets not updated anymore

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#1704]
We don't have information in DB when a user did something the last time.

Might got disabled since the original implementation did an update on every operation which slowed down us a lot. So, we do not have to be that exact, but knowing the day would be fine.

**Comment by hennevogel** [comment]
Can you please elaborate what you mean by 'did something the last time'?

**Comment by bgeuken** [comment]
Fixed in a67355804a729615c7d327f530cf51c54c209f4f
