### ISSUE TITLE
Only Incoming requests shown by default

### ISSUE THREAD

**Issue by hramrach** [openSUSE/open-build-service#17092]
# Issue Description
Only Incoming requests shown by default

Expected Result
============
Outgoing requests shown

How to Reproduce
===============
1. Go to a project or package
2. Click on Requests

Request list is shown with a select set to 'Incoming'

Further Information
===============

build.opensuse.org (likely a beta feature)

**Comment by hennevogel** [comment]
Can you explain why you expect outgoing requests to be shown by default?

**Comment by hramrach** [comment]
Can you explain why you expect outgoing requests to NOT be shown by default?

**Comment by hennevogel** [comment]
Because for most people/projects they are less important than incoming requests

**Comment by hramrach** [comment]
I am submitting changes to packages I do not maintain.

**Comment by eduardoj** [comment]
After #17196 being deployed, the situation with this issue has improved.

@hramrach, could you please confirm this works for you?

**Comment by eduardoj** [comment]
@hramrach, I close the issue. Feel free to re-open it if the provided fix doesn't fit your needs.
