### ISSUE TITLE
Broken rendering in SR diffs with longer lines

### ISSUE THREAD

**Issue by danishprakash** [openSUSE/open-build-service#17126]
![image](https://github.com/user-attachments/assets/9f971cec-5be9-432d-ad0b-c31cf7fc8a26)

Reference SR - https://build.opensuse.org/request/show/1224845

**Comment by hennevogel** [comment]
@hellcp-work sounds like eyecatchers fallout?

**Comment by hellcp-work** [comment]
I think this might have always been broken, it's browser dependent

**Comment by hellcp-work** [comment]
It's a duplicate of #8172
