### ISSUE TITLE
kiwi metadata packages don't lead to unresolvable

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#1712]
https://build.opensuse.org/package/view_file/openSUSE:Leap:42.2:Rings:1-MinimalX/Test-DVD-x86_64/PRODUCT-x86_64.kiwi has
  \<repopackage name="skelcd-openSUSE" medium="0" removearch="src,nosrc" onlyarch="x86_64"/>

Initially I didn't have skelcd-openSUSE in the project but Test-DVD-x86_64 wasn't shown as unresolvable. It even tried to build until kiwi failed due to the missing package. Now that I added skelcd-openSUSE the DVD blocks for it. Looks fishy ...

**Comment by adrianschroeter** [comment]
this is wanted, because you can configure kiwi to ignore missing packages....

**Comment by lnussel** [comment]
but the kiwi file in this case doesn't do that, right? so obs shouln't either IMO
