### ISSUE TITLE
In maintenance incident, links to a maintenance release request lead to unrelated request

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/open-build-service#1729]
Seen several times (also by @mkubecek): In a maintenance incident view, e.g. [openSUSE:Maintenance:4966](https://build.opensuse.org/project/show/openSUSE:Maintenance:4966), the link labeled "1 release request" in the upper right area links to an [unrelated request](https://build.opensuse.org/request/show/390618) while the correct request is a [different one](https://build.opensuse.org/request/show/390286). The [request list](https://build.opensuse.org/project/requests/openSUSE:Maintenance:4966) of incident is correct, also no part of the work-flow is affected.

**Comment by hennevogel** [comment]
@adrianschroeter number thingee?

**Comment by adrianschroeter** [comment]
yep, fixed.

**Comment by mkubecek** [comment]
The links are correct now. Thank you.

**Comment by andreasstieger** [comment]
3559c278a1fe5be2c5570b77ed96d58f96a68439 thanks
