### ISSUE TITLE
anacron run on battery

### ISSUE THREAD

**Issue by Konfekt** [openSUSE/open-build-service#1731]
There's a cron job

/etc/cron.hourly/0anacron

that only start if `on_ac_power` shows that the computer is on AC.

Is this package installing it? It seems to me it uses a` systemd` service. Do you have an idea where it comes from?

The issue is that the question whether to start anacron jobs on battery or not is better left to the user (for example, a daily backup should run unconditionally).

**Comment by adrianschroeter** [comment]
This tracker is about the OBS code itself, not about any content of packages it is hosting.
