### ISSUE TITLE
Failure to install addons in GRASS 7.0.3 on SuSE 13.2 

### ISSUE THREAD

**Issue by larsf1960** [openSUSE/open-build-service#1749]
installing addons through g.extension on GRASS fails; i.e from the addons repository.

Errors underneath.

In short two errors show up:

1. r.area:  "fatal error: grass/gis.h: no such file...

2. r.viewshed.cva: python: can't open file '/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/tools/mkhtml.py': [Errno 2]

I have tried under my ordinary user; and as root; same errors both ways.

Regards
LarsF

PS GRASS7.03; on linux SUSE 13.2. 64 bit. GRASS installed from OSGEO repository.

Noted by Martin Landa: "

----------------------------------------ERRORMESSAGES-------------------------------------------------------------------
r.area first:

(Sat Apr  9 23:40:06 2016)
g.extension -s --verbose extension=r.area svnurl=http://svn.osgeo.org/grass/grass-addons/grass7
Fetching <r.area> from GRASS-Addons SVN repository (be patient)...
A    r.area/main.c
A    r.area/r.area.html
A    r.area/Makefile
 U   r.area
Sjekket ut revisjon 68236.
mkdir -p /tmp/tmpfy5Lnl/r.area/bin
mkdir -p /tmp/tmpfy5Lnl/r.area/etc
mkdir -p /tmp/tmpfy5Lnl/r.area/docs/html
mkdir -p /tmp/tmpfy5Lnl/r.area/docs/man
mkdir -p /tmp/tmpfy5Lnl/r.area/docs/man/man1
test -d OBJ.x86_64-pc-linux-gnu || mkdir -p OBJ.x86_64-pc-linux-gnu
gcc  -O2 -I/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/include -I/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/include -DPACKAGE=\""grassmods"\" -I/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/include -I/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/include -DRELDIR=\"/tmp/tmpfy5Lnl/r.area\" -o OBJ.x86_64-pc-linux-gnu/main.o -c main.c
Compiling...
main.c:20:23: fatal error: grass/gis.h: Ingen slik fil eller
filkatalog
 #include <grass/gis.h>
                       ^
compilation terminated.
make: *** [OBJ.x86_64-pc-linux-gnu/main.o] Error 1
ERROR: Compilation failed, sorry. Please check above error messages.
/opt/grass/include/Make/Compile.make:32: recipe for target 'OBJ.x86_64-pc-linux-gnu/main.o' failed
(Sat Apr  9 23:40:10 2016) Command finished (3 sec)
(Sat Apr  9 23:41:39 2016)

-------------------------------------------------------------------------------------------------------------r.viewshed.cva----------------------------------------------------------------------

r.viewshed.cva

g.extension -s --verbose extension=r.viewshed.cva svnurl=http://svn.osgeo.org/grass/grass-addons/grass7
Fetching <r.viewshed.cva> from GRASS-Addons SVN repository (be patient)...
A    r.viewshed.cva/r.viewshed.cva.html
A    r.viewshed.cva/Makefile
A    r.viewshed.cva/r.viewshed.cva.py
Sjekket ut revisjon 68236.
mkdir -p /tmp/tmpxrnpo6/r.viewshed.cva/bin
mkdir -p /tmp/tmpxrnpo6/r.viewshed.cva/etc
mkdir -p /tmp/tmpxrnpo6/r.viewshed.cva/docs/html
mkdir -p /tmp/tmpxrnpo6/r.viewshed.cva/docs/man
mkdir -p /tmp/tmpxrnpo6/r.viewshed.cva/docs/man/man1
mkdir -p /tmp/tmpxrnpo6/r.viewshed.cva/scripts
/usr/bin/install -c  r.viewshed.cva.py /tmp/tmpxrnpo6/r.viewshed.cva/scripts/r.viewshed.cva
if [ "/tmp/tmpxrnpo6/r.viewshed.cva/scripts/r.viewshed.cva" != "" ] ; then GISRC=/tmp/grass7-larsf-24831/gisrc GISBASE=/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass PATH="/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/bin:/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/bin:/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/scripts:$PATH" PYTHONPATH="/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/etc/python:/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/gui/wxpython:$PYTHONPATH" LD_LIBRARY_PATH="/tmp/tmpxrnpo6/r.viewshed.cva/bin:/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/bin:/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/scripts:/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/lib:/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/lib:/opt/grass/lib" LC_ALL=C /tmp/tmpxrnpo6/r.viewshed.cva/scripts/r.viewshed.cva --html-description < /dev/null | grep -v '</body>\|</html>' > r.viewshed.cva.tmp.html ; fi
Compiling...
python: can't open file '/home/abuild/rpmbuild/BUILDROOT/gra
ss-7.0.3-2.12.x86_64/opt/grass/tools/mkhtml.py': [Errno 2]
No such file or directory
make: *** [/tmp/tmpxrnpo6/r.viewshed.cva/docs/html/r.viewshe
d.cva.html] Error 2
ERROR: Compilation failed, sorry. Please check above error messages.
VERSION_NUMBER=7.0.3 VERSION_DATE=2016 \
        python /home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/tools/mkhtml.py r.viewshed.cva > /tmp/tmpxrnpo6/r.viewshed.cva/docs/html/r.viewshed.cva.html
/opt/grass/include/Make/Html.make:7: recipe for target '/tmp/tmpxrnpo6/r.viewshed.cva/docs/html/r.viewshed.cva.html' failed
rm r.viewshed.cva.tmp.html
(Sat Apr  9 23:41:43 2016) Command finished (3 sec) nstall addons through g.extension on GRASS; But I'm unable to install anything, i.e from the addons repository.

Errors underneath.

In short two errors show up:

1. r.area:  "fatal error: grass/gis.h: no such file...

2. r.viewshed.cva: python: can't open file '/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/tools/mkhtml.py': [Errno 2]

I have tried under my ordinary user; and as root; same errors; both ways.

I must say I do wonder if somebody has hardcoded some paths?

Regards
LarsF

PS GRASS7.03; on linux SUSE 13.2. GRASS installed from OSGEO repository. This was 9.april 2016. Later upgrades of GRASS shows the same error.

From Martin Landa: 
"there is no -I /opt/grass in gcc flags. Please contact OpenSuse
packager. It's not bug in GRASS but in packaging for OpenSuse. Martin
-- 
Martin Landa
http://geo.fsv.cvut.cz/gwiki/Landa
http://gismentors.cz/mentors/landa"

----------------------------------------ERRORMESSAGES-------------------------------------------------------------------
r.area first:

(Sat Apr  9 23:40:06 2016)
g.extension -s --verbose extension=r.area svnurl=http://svn.osgeo.org/grass/grass-addons/grass7
Fetching <r.area> from GRASS-Addons SVN repository (be patient)...
A    r.area/main.c
A    r.area/r.area.html
A    r.area/Makefile
 U   r.area
Sjekket ut revisjon 68236.
mkdir -p /tmp/tmpfy5Lnl/r.area/bin
mkdir -p /tmp/tmpfy5Lnl/r.area/etc
mkdir -p /tmp/tmpfy5Lnl/r.area/docs/html
mkdir -p /tmp/tmpfy5Lnl/r.area/docs/man
mkdir -p /tmp/tmpfy5Lnl/r.area/docs/man/man1
test -d OBJ.x86_64-pc-linux-gnu || mkdir -p OBJ.x86_64-pc-linux-gnu
gcc  -O2 -I/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/include -I/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/include -DPACKAGE=\""grassmods"\" -I/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/include -I/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/include -DRELDIR=\"/tmp/tmpfy5Lnl/r.area\" -o OBJ.x86_64-pc-linux-gnu/main.o -c main.c
Compiling...
main.c:20:23: fatal error: grass/gis.h: Ingen slik fil eller
filkatalog
 #include <grass/gis.h>
                       ^
compilation terminated.
make: *** [OBJ.x86_64-pc-linux-gnu/main.o] Error 1
ERROR: Compilation failed, sorry. Please check above error messages.
/opt/grass/include/Make/Compile.make:32: recipe for target 'OBJ.x86_64-pc-linux-gnu/main.o' failed
(Sat Apr  9 23:40:10 2016) Command finished (3 sec)
(Sat Apr  9 23:41:39 2016)

-------------------------------------------------------------------------------------------------------------r.viewshed.cva----------------------------------------------------------------------

r.viewshed.cva

g.extension -s --verbose extension=r.viewshed.cva svnurl=http://svn.osgeo.org/grass/grass-addons/grass7
Fetching <r.viewshed.cva> from GRASS-Addons SVN repository (be patient)...
A    r.viewshed.cva/r.viewshed.cva.html
A    r.viewshed.cva/Makefile
A    r.viewshed.cva/r.viewshed.cva.py
Sjekket ut revisjon 68236.
mkdir -p /tmp/tmpxrnpo6/r.viewshed.cva/bin
mkdir -p /tmp/tmpxrnpo6/r.viewshed.cva/etc
mkdir -p /tmp/tmpxrnpo6/r.viewshed.cva/docs/html
mkdir -p /tmp/tmpxrnpo6/r.viewshed.cva/docs/man
mkdir -p /tmp/tmpxrnpo6/r.viewshed.cva/docs/man/man1
mkdir -p /tmp/tmpxrnpo6/r.viewshed.cva/scripts
/usr/bin/install -c  r.viewshed.cva.py /tmp/tmpxrnpo6/r.viewshed.cva/scripts/r.viewshed.cva
if [ "/tmp/tmpxrnpo6/r.viewshed.cva/scripts/r.viewshed.cva" != "" ] ; then GISRC=/tmp/grass7-larsf-24831/gisrc GISBASE=/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass PATH="/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/bin:/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/bin:/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/scripts:$PATH" PYTHONPATH="/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/etc/python:/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/gui/wxpython:$PYTHONPATH" LD_LIBRARY_PATH="/tmp/tmpxrnpo6/r.viewshed.cva/bin:/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/bin:/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/scripts:/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/lib:/home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/lib:/opt/grass/lib" LC_ALL=C /tmp/tmpxrnpo6/r.viewshed.cva/scripts/r.viewshed.cva --html-description < /dev/null | grep -v '</body>\|</html>' > r.viewshed.cva.tmp.html ; fi
Compiling...
python: can't open file '/home/abuild/rpmbuild/BUILDROOT/gra
ss-7.0.3-2.12.x86_64/opt/grass/tools/mkhtml.py': [Errno 2]
No such file or directory
make: *** [/tmp/tmpxrnpo6/r.viewshed.cva/docs/html/r.viewshe
d.cva.html] Error 2
ERROR: Compilation failed, sorry. Please check above error messages.
VERSION_NUMBER=7.0.3 VERSION_DATE=2016 \
        python /home/abuild/rpmbuild/BUILDROOT/grass-7.0.3-2.12.x86_64/opt/grass/tools/mkhtml.py r.viewshed.cva > /tmp/tmpxrnpo6/r.viewshed.cva/docs/html/r.viewshed.cva.html
/opt/grass/include/Make/Html.make:7: recipe for target '/tmp/tmpxrnpo6/r.viewshed.cva/docs/html/r.viewshed.cva.html' failed
rm r.viewshed.cva.tmp.html
(Sat Apr  9 23:41:43 2016) Command finished (3 sec)

**Comment by hennevogel** [comment]
This is not a support forum. Please ask questions about using the OBS on our mailing list or IRC channel -> http://openbuildservice.org/support/
