### ISSUE TITLE
period suffices in package names are not handled correctly in maintenance requests

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/open-build-service#1758]
When doing a maintenance request, periods / suffixes in package names are not handled correctly when viewing the diff.

E.g. 

```
FOOPROJECT/FOOPACKAGE
FOOPROJECT/FOOPACKAGE1.5
```

`osc mr FOOPROJECT FOOPACKAGE FOOPACKAGE1.5 openSUSE:Maintenance`

Request diff is not shown, message:

`The diff call for /source/FOOPROJECT/FOOPACKAGE1?cmd=diff&expand=1&filelimit=10000&orev=0&rev=[...]&view=xml&withissues=1 failed: package 'FOOPACKAGE1' does not exist`

Note the conversion from `FOOPACKAGE1.5` to `FOOPACKAGE1`.

**Comment by adrianschroeter** [comment]
should be solved
