### ISSUE TITLE
Unresolvable deps in ubuntu 16.04, but builds fine locally

### ISSUE THREAD

**Issue by dequis** [openSUSE/open-build-service#1766]
Hi, I can't understand why I'm getting unresolvable deps errors in the following package

https://build.opensuse.org/project/monitor/home:jgeboski?blocked=0&building=0&dispatching=0&finished=0&pkgname=purple-facebook&scheduled=0&signing=0&succeeded=0

>nothing provides libpurple-dev, nothing provides libzephyr4

In a local VM with a newly installed ubuntu 16.04 the same source package built without issues. I don't get why it doesn't work in OBS.

All the previous ubuntu versions work fine, too.

**Comment by adrianschroeter** [comment]
On Samstag, 30. April 2016, 19:50:01 wrote dx:
> Hi, I can't understand why I'm getting unresolvable deps errors in the following package
> 
> https://build.opensuse.org/project/monitor/home:jgeboski?blocked=0&building=0&dispatching=0&finished=0&pkgname=purple-facebook&scheduled=0&signing=0&succeeded=0
> 
> >nothing provides libpurple-dev, nothing provides libzephyr4

libpurple-dev does not exist in xenial (not checked the otehr one).

> In a local VM with a newly installed ubuntu 16.04 the same source package built without issues. I don't get why it doesn't work in OBS.

well, who provides this package there and where does it come from?

> All the previous ubuntu versions work fine, too.
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/openSUSE/open-build-service/issues/1766

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imend�rffer, Jane Smithard, Graham Norton, HRB 21284 (AG N�rnberg) 
 
Maxfeldstra�e 5                         
90409 N�rnberg 
Germany

**Comment by dequis** [comment]
I see it here though

http://packages.ubuntu.com/xenial/libpurple-dev

**Comment by Conan-Kudo** [comment]
@dequis It's in universe. You'll need to edit your project's meta to change from "standard" to "universe".

**Comment by dequis** [comment]
Oh, nice, didn't know about that. It worked, thanks a lot!

**Comment by adrianschroeter** [comment]
Hm, just for the record, I looked on the same url yesterday and it wasn't shown .. hm ..
