### ISSUE TITLE
Autosubmit disable on a pkg level

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#1770]
25/19:11 < va> zaitor: so what's the magic for disabling autosubmit?
25/19:13 < zaitor> va: add openSUSE:DisableAutoSubmit   true - in https://build.opensuse.org/attribs/X11:Wayland

Would be nice to have a way to do this not at the project level, but only for specific packages.

**Comment by adrianschroeter** [comment]
This is a script by the openSUSE people. It is not part of OBS, so please report this to the factory maintainers who are responsible for this.

Defining this attribute on package level would just work from OBS side.

**Comment by coolo** [comment]
and of course the attribute in the package is respected
