### ISSUE TITLE
Cannot login or manage users created with a space (OBS 2.6, 2.7RC)

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/open-build-service#1771]
On my private OBS 2.6 instance, a user has created a username with a space in it. Unfortunately, that user cannot log in with that user, and I can't (as Admin) delete it. It throws 404 errors every time.

**Comment by Conan-Kudo** [comment]
This is still a problem with OBS 2.6.99 (OBS 2.7 RC).

**Comment by bgeuken** [comment]
Duplicate or related with #1064

**Comment by Ana06** [comment]
@openSUSE/open-build-service do we want to create users whose login has spaces? The main problem with that is that the home project would also have an space and we don't allow project names with spaces. So to support that we would have to replace the spaces somehow in the home project name. I think it would be much easier to just forbid that the name has spaces. It is anyway strange to have a login with spaces.

**Comment by Ana06** [comment]
The problem with spaces is now different as when this was open, it is not possible anymore to create user with spaces (fails because of the problem with the project).

**Comment by saraycp** [comment]
@Conan-Kudo please let us know if you still have problems with this and will try to find a solution.

Since 2.6 is no longer maintained and the login can't contain spaces anymore, we are going to close this issue. Please, feel free to re-open it if needed.
