### ISSUE TITLE
soundtouch package for Fedora 23 is obsolete

### ISSUE THREAD

**Issue by SeeLook** [openSUSE/open-build-service#1786]
Hi!
My project:
https://build.opensuse.org/package/show/home:seelook/nootka
depends on soundtouch library
but Fedora 23 build crashes due to mismatch of soundtouch version. It works fine with fresh install of Fedora 23 but crashes after upgrade.
Actually Fedora 23 has soundtouch version 1.9.4 but OBS seems to have 1.4.

Could You fix it please.

**Comment by adrianschroeter** [comment]
On Samstag, 7. Mai 2016, 14:48:44 wrote SeeLook:
> Hi!
> My project:
> https://build.opensuse.org/package/show/home:seelook/nootka
> depends on soundtouch library
> but Fedora 23 build crashes due to mismatch of soundtouch version. It works fine with fresh install of Fedora 23 but crashes after upgrade.
> Actually Fedora 23 has soundtouch version 1.9.4 but OBS seems to have 1.4.
> 
> Could You fix it please.

Fedora 23 was with 1.4 released.They made a version upgrade later in their
update channel. So you need to build against "update" repo instead of "standard".

> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/openSUSE/open-build-service/issues/1786

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imend�rffer, Jane Smithard, Graham Norton, HRB 21284 (AG N�rnberg) 
 
Maxfeldstra�e 5                         
90409 N�rnberg 
Germany

**Comment by SeeLook** [comment]
Thank You for the clue.
Truth to be told I'm not a master of OSB.
I deleted Fedora 23 repo and created a new one with "update" path, so there is an entry in meta:
```xml
<repository name="Fedora_23">
    <path project="Fedora:23" repository="update"/>
    <arch>i586</arch>
    <arch>x86_64</arch>
  </repository>
```
Unfortunately it is still built against standard repository path.

**Comment by adrianschroeter** [comment]
okay, the mirror which we configured to use was out-of-date. Changed that and it looks good to me now:

# osc buildinfo home:seelook/nootka Fedora_23            x86_64 | grep soundtouch
  <bdep name="soundtouch-devel" version="1.9.2" release="3.fc23" arch="x86_64" project="Fedora:23" repository="update" />

**Comment by adrianschroeter** [comment]
grmbl, hopefully readable now:

`
# osc buildinfo home:seelook/nootka Fedora_23            x86_64 | grep soundtouch
<bdep name="soundtouch-devel" version="1.9.2" release="3.fc23" arch="x86_64" project="Fedora:23" repository="update" />
`

**Comment by adrianschroeter** [comment]
not .. but you should get an idea when running it. It lists version .9 now.

**Comment by adrianschroeter** [comment]
btw, this is IMHO still a breakage in fedora updates when former binaries don't run anymore. Maybe you should report that there.

**Comment by SeeLook** [comment]
IMHO as well. libsoundtouch from the package changes its API - it couldn't occur during Fedora 23 life-cycle. 
I will try to fix it another way.
Thanks a lot!
