### ISSUE TITLE
latest_commits empty

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#1787]
We have an update crawler that is meant to submit updates from e.g. 42.1 to
42.2. For this purpose there is code to read the latest_commit feed to avoid
having to query all packages. Now when I tried to reactivate the bot the feed
seems to be emtpy though e.g.
```
$ osc api /project/latest_commits/openSUSE:Leap:42.1:Update
  <feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en-US">
    <id>tag:api.opensuse.org,2013-11-22:/project/latest_commits/openSUSE:Leap:42</id>
    <link rel="self" type="application/atom+xml" href="https://api.opensuse.org/project/latest_commits/openSUSE:Leap:42.1:Update"/>
    <title>Commits for openSUSE:Leap:42.1:Update</title>
  </feed>
```

**Comment by coolo** [comment]
Now that you mention it my RSS feed for O:F stopped 17 days ago - with https://build.opensuse.org/request/show/391240

So OBS got broken

**Comment by adrianschroeter** [comment]
hm, we are currently running code from 14.04. due to various breakages afterwards. Will check after update.

**Comment by adrianschroeter** [comment]
It seems the src server is not emitting COMMIT events anymore. I do so other, rep server related ones in source server log, but no SRCSRV_*  ones.

**Comment by adrianschroeter** [comment]
k, not the source server ....

**Comment by adrianschroeter** [comment]
root cause was a too large commit comment again. limited also for delete package operation.
So, issue fixed, but we have hughe backlog.

**Comment by DimStar77** [comment]
Does this happen to also solve https://github.com/openSUSE/hermes/issues/3 ?

**Comment by coolo** [comment]
in a couple of days, yes :)

**Comment by DimStar77** [comment]
@coolo the herme related issue had been filed already in march - which was more than the 20 days ago when 'your' feed stopped working.. that's why I was doubting this a bit

**Comment by coolo** [comment]
right. the most this can fix is the complete lack of source server data on hermes - not the content of it

**Comment by mmohring** [comment]
If I call this for my OBS, I get:

`> osc api /project/latest_commits/OBS:Server:Unstable
<about>
  <title>Open Build Service API</title>
  <description>API to the Open Build Service</description>
  <revision>2.7.50.git.20160506</revision>
</about>`

and not the commits. Its the code from git commit 0674eb4755e3f8e7d8d8f718f71cdfddfa1cc699 .

**Comment by mmohring** [comment]
E.e. it returns the data from osc api about .

From logfile:

`[b8c4c924-d9df-41cf-9b3f-896de400c9f7] [20243:320823.95] Started GET "/project/latest_commits/OBS:Server:Unstable" for 192.168.0.32 at 2016-05-12 16:34:58 +0200
[b8c4c924-d9df-41cf-9b3f-896de400c9f7] [20243:320823.95] Processing by Webui::FeedsController#commits as ATOM
[b8c4c924-d9df-41cf-9b3f-896de400c9f7] [20243:320823.95]   Parameters: {"project"=>"OBS:Server:Unstable"}
[b8c4c924-d9df-41cf-9b3f-896de400c9f7] [20243:320823.95] Redirected to https://api.testobs.com/
`

**Comment by adrianschroeter** [comment]
@mmohring it works usualy, but there was one event on build.opensuse.org which broke it.

We fixed this event and made sure it can't happen again. But you can't reproduce this on your instance easily.

**Comment by coolo** [comment]
I had to do a lot of manual tweaks to get this rolling again after so many days of outage ;(

**Comment by bgeuken** [comment]
@coolo Thanks for taking care of this:+1:
