### ISSUE TITLE
apache error_log: cannot load such file -- phusion_passenger

### ISSUE THREAD

**Issue by yimingsir** [openSUSE/open-build-service#1795]
opensuse 13.2
obs 2.6.9
Every setup is ok. Service start ok. But when open https://localhost, page show  500: Internal Server Error. apache error_log:

> App 5888 stderr: 

App 5888 stderr: /usr/lib64/passenger/5.0.15/bin/passenger-config:32:in `require'

App 5888 stderr: : 

App 5888 stderr: cannot load such file -- phusion_passenger

App 5888 stderr:  (

App 5888 stderr: LoadError

App 5888 stderr: )

App 5888 stderr:        from /usr/lib64/passenger/5.0.15/bin/passenger-config:32:in `<main>'

how to fix it? thanks.

**Comment by adrianschroeter** [comment]
On Donnerstag, 12. Mai 2016, 01:36:30 wrote yimingsir:
> opensuse 13.2
> obs 2.6.9
> Every setup is ok. Service start ok. But when open https://localhost, page show  500: Internal Server Error. apache error_log:
> 
> > App 5888 stderr: 
> App 5888 stderr: /usr/lib64/passenger/5.0.15/bin/passenger-config:32:in `require'
> App 5888 stderr: : 
> App 5888 stderr: cannot load such file -- phusion_passenger
> App 5888 stderr:  (
> App 5888 stderr: LoadError
> App 5888 stderr: )
> App 5888 stderr:        from /usr/lib64/passenger/5.0.15/bin/passenger-config:32:in `<main>'
> App 5920 stdout: 
> App 5928 stdout: 
> 
> how to fix it? thanks.

ruby2.3-rubygem-passenger is installed?

but this is actually not a support forum here, please go to the mailing list to followup...

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imend�rffer, Jane Smithard, Graham Norton, HRB 21284 (AG N�rnberg) 
 
Maxfeldstra�e 5                         
90409 N�rnberg 
Germany

**Comment by adrianschroeter** [comment]
ruby2.1-   for OBS 2.6 of course.

**Comment by yimingsir** [comment]
rpm -qa | grep passenger
ruby2.1-rubygem-passenger-5.0.15-15.1.x86_64
rubygem-passenger-apache2-5.0.15-15.1.x86_64
rubygem-passenger-5.0.15-15.1.x86_64

I have installed ruby2.1-rubygem-passenger.
