### ISSUE TITLE
Include package name in HTML title for /request/show

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#1799]
```
curl -s https://build.opensuse.org/request/show/395910 | grep '<title>'
    <title>Request 395910 - openSUSE Build Service</title>
```
It would be nice if it also showed the package name (python3-traceback2 in this case) in the title so that I don't necessarily have to scroll to know what the SR was about.

**Comment by coolo** [comment]
what package name to choose for a multiple actions request that included renames?

**Comment by jengelh** [comment]
I do not have an answer to that. Maybe you can use "(multiple)" as a placeholder. My focus was on "simple" 1-package submits.

**Comment by bgeuken** [comment]
Maybe the first two or three package names followed by some dots?

JFYI We have a similar request for the webui: #1655

**Comment by adrianschroeter** [comment]
this request is for the webui as well, the metioned URL is not an api request. So duplicated of #1655
