### ISSUE TITLE
qt5ct plugin broke as of openSUSE Tumbleweed (20160517) 

### ISSUE THREAD

**Issue by two-dogs** [openSUSE/open-build-service#1814]
I have been using the plugin with cinnamon to render a variety of kf5 apps for quite a while, it just worked.
As of last snapshot update the plugin does not function, when working the plugin forces qt5 over gtk and the outcome is obvious. 
Info on desktop and plugin https://gist.github.com/anonymous/d416a285f6d246af84723e23edb23eed 

A temp fix was set in motion, according to 
DimStar> (for now I triggered a rebuild of qt5ct - will be part of the 0519 snapshot)

A permanent fix would require a mod to a spec file, 
DimStar> # so we need to hardcode libQt5Gui5 version
DimStar> %requires_eq libQt5Gui5

fyi: osc maintainer qt5ct => Xrevan86

**Comment by adrianschroeter** [comment]
This tracker is about OBS code, please use bugzilla.opensuse.org for bugreports for packages.
