### ISSUE TITLE
Uncaught exception: NoMaintenanceReleaseTarget

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#1821]
To reproduce:
1. Load the test fixtures
2. Login as admin user (king)
3. Visit /project/show/BaseDistro
4. Click on "Submit as update" link and submit
=> "Maintenance incident request contains no defined release target project for package Pack3"

app/models/bs_request_action_maintenance_incident.rb:38:in `get_releaseproject'
app/models/bs_request_action.rb:543:in`block in create_expand_package'
activerecord (4.2.5.2) lib/active_record/relation/delegation.rb:46:in `each'
activerecord (4.2.5.2) lib/active_record/relation/delegation.rb:46:in`each'
app/models/bs_request_action.rb:514:in `create_expand_package'
app/models/bs_request_action.rb:891:in`expand_targets'
app/models/bs_request_action_maintenance_incident.rb:216:in `expand_targets'
app/models/bs_request.rb:1107:in`block in expand_targets'
activerecord (4.2.5.2) lib/active_record/relation/delegation.rb:46:in `each'
activerecord (4.2.5.2) lib/active_record/relation/delegation.rb:46:in`each'
app/models/bs_request.rb:1106:in `expand_targets'
app/models/bs_request.rb:947:in`sanitize!'
app/models/bs_request.rb:62:in `save!'
app/controllers/webui/project_controller.rb:134:in`block in new_incident_request'

**Comment by hennevogel** [comment]
@bgeuken Why is this a bug? Because the test fixtures are incomplete?
