### ISSUE TITLE
AutoCleanup attribute doesn't work

### ISSUE THREAD

**Issue by tuminoid** [openSUSE/open-build-service#1823]
In OBS 2.6 (at least, quickly tested build.opensuse.org), setting OBS:AutoCleanup attribute does nothing. No matter what date you set it, there is no requests created, nor cleanup is triggered. You can see there is an OBS:AutoCleanup attribute, edit it, etc, but nothing happens.

**Comment by kkeil** [comment]
Did you add the <cleanup_after_days>3</cleanup_after_days> via the new /configuration API call ?
If this variable is empty or <= 0 the feature is disabled.
Please note, the job to add the request is only running ones a day.

**Comment by tuminoid** [comment]
Is that properly supported in 2.6? It is not in `configurations.xml` by default. Also `/configurations` API endpoint isn't documented in apidocs. I can call `osc api -X GET /configurations`, but not `osc api -X POST /configurations -f newconfig.xml` with 2.6.

options.yml.example stuff was removed from master, but not in 2.6 branch.
https://github.com/openSUSE/open-build-service/commit/361214ded876e4d11f54e2463b359303c5faf590

**Comment by kkeil** [comment]
Yes it is working in 2.6 (tested on 2.6.9),  the PUT method need to be used so the commands are:
`osc api -X GET /configuration > myconfig.xml` and
`osc api -X PUT /configuration -f myconfig.xml`
This interface was already in the 2.5 series.
 [48b008](https://github.com/openSUSE/open-build-service/commit/48b00893e56625fd5304bc9a8fece58ba46fc49d)

**Comment by tuminoid** [comment]
Tested it and looked the code, and it seems the same value is used for both purposes: upon branching, it sets the attribute for autocleanup, when the request is created. When autocleanup then triggers, its used for determining how quickly you need to respond to submit request. Double use for two different purposes.

**Comment by bgeuken** [comment]
The interface surely could be improved. Though it seems to work as expected. =>  Closing

Thanks Karsten for jumping in.

Related issues:
  #1824
  #1830
