### ISSUE TITLE
Have hooks associated with submit requests

### ISSUE THREAD

**Issue by DStape** [openSUSE/open-build-service#1828]
When a submit request is made to a given project, some pre-configured script(s) could be executed. These scripts could, for example, perform some kind of checking on the submit request that's been made. If the requirements programmed into the script are not satisfied, the submit request could be automatically declined.

**Comment by hennevogel** [comment]
You can do that with polling. Done for the openSUSE distributions with the [factory plugin](https://github.com/openSUSE/osc-plugin-factory) for the command line client.

**Comment by hennevogel** [comment]
And I doubt we will ever run user defined scripts in the context of the server. This would need to run in another isolated process (like build). A bit much work just to switch from poll to push...

**Comment by DStape** [comment]
Thank you for the quick response.

OK, I'll take a look at that plugin and will close the issue.
