### ISSUE TITLE
KVM workers expose host processor count, constraints not obeyed

### ISSUE THREAD

**Issue by tuminoid** [openSUSE/open-build-service#1831]
When a KVM based worker is limited to 1 CPU by `OBS_WORKER_JOBS=1`, it still exposes processor count of the host system:
```
$ cat /srv/obs/workers/idle/x86_64:obsworker-small:1
...
      <flag>xsaveopt</flag>
    </cpu>
    <processors>48</processors>
    <memory>3072</memory>
    <disk>6144</disk>
  </hardware>
```

This processors value is used to enforce constraints, and thus the constraint of 12 cpus will not prevent job from building on a such worker, even it is limited to 1 CPU on the KVM instance.

Notably the `memory` and `disk` attributes are coming from the KVM, and not from the host, which is the right behaviour.

Worker cmdline for reference:
```
usr/bin/perl -w ./bs_worker --hardstatus --kvm --root /mnt/workerdisk/srv/obs-worker/tmp/d-small/root_1 --statedir /mnt/workerdisk/srv/obs/run/d-small/worker/1 --id obsworker-small:1 --reposerver XXX:5252 --jobs 1 --cachedir /mnt/workerdisk/srv/obs/worker-small/cache/d-small --cachesize 100000 --vm-kernel /usr/lib/obs/worker/kernel.kvm --vm-initrd /usr/lib/obs/worker/initrd.kvm --vmdisk-rootsize 6144 --vmdisk-filesystem ext3 --vmdisk-clean --tmpfs --device /mnt/workerdisk/srv/obs-worker/tmp/d-small/root_1/root --vm-memory 3072 --cleanup-chroot
```

**Comment by kaltsi** [comment]
A new constraint type 'jobs' could handle this. It also works with chroot workers: #1859

**Comment by adrianschroeter** [comment]
pull request from kaltsi to support also jobs has been merged to master

**Comment by tuminoid** [comment]
@adrianschroeter you are aware that `jobs` constraint does not fix the real issue right? Using `jobs` constraint you can definitely limit it to the right hosts, but you are still exposing wrong number of processors for KVM jobs, and everybody using `processors` is still broken.
