### ISSUE TITLE
WebUI <apiurl>/project/status/<project> 500: Internal Server Error

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#1833]
When you select with current git master in the WebUI the tab => Status, you get a 500: Internal Server Error. Git commit caabd480a46fe1c7f36f71f396d6318228e8a344

First few lines from the logfile:

`[36910ced-3114-48a8-bc18-de8875fc422d] [19401:10.94] Started GET "/project/status/XXX" for 192.168.0.32 at 2016-05-26 21:32:08 +0200
[36910ced-3114-48a8-bc18-de8875fc422d] [19401:10.95] Processing by Webui::ProjectController#status as HTML
[36910ced-3114-48a8-bc18-de8875fc422d] [19401:10.95]   Parameters: {"project"=>"XXX"}
[36910ced-3114-48a8-bc18-de8875fc422d] [19401:11.04] Completed 500 Internal Server Error in 88ms (ActiveRecord: 13.8ms | Backend: 0.0ms | XML: 0.0ms)
[36910ced-3114-48a8-bc18-de8875fc422d] [19401:11.05] 
ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'bs_requests.number' in 'order clause': SELECT bs_requests.id, bs_requests.state, bs_request_actions.target_project, bs_request_actions.target_package FROM `bs_requests` INNER JOIN `bs_request_actio
ns` ON `bs_request_actions`.`bs_request_id` = `bs_requests`.`id` WHERE `bs_requests`.`state` IN ('new', 'review', 'declined') AND `bs_request_actions`.`type` = 'submit'  ORDER BY `bs_requests`.`number` ASC):
  mysql2 (0.4.2) lib/mysql2/client.rb:107:in `_query'
  mysql2 (0.4.2) lib/mysql2/client.rb:107:in `block in query'
  mysql2 (0.4.2) lib/mysql2/client.rb:106:in `handle_interrupt'
  mysql2 (0.4.2) lib/mysql2/client.rb:106:in `query'
`

**Comment by mmohring** [comment]
Sorry, git commit of git master is c4204237a597874199061c68f752afe70e38170f

**Comment by mmohring** [comment]
The db migrations are up to date, e.g. I had made a

`RAILS_ENV=production rake db:migrate`

**Comment by mdeniz** [comment]
Hi @mmohring you should have the column `number` in the table `bs_requests`, is added in this migration [20160321105300_request_counter.rb](https://github.com/openSUSE/open-build-service/blob/master/src/api/db/migrate/20160321105300_request_counter.rb) and an index changed for this column in this other one [20160518105300_uniq_number_index.rb](https://github.com/openSUSE/open-build-service/blob/master/src/api/db/migrate/20160518105300_uniq_number_index.rb), those are the latest migrations.

**Comment by mmohring** [comment]
@mdeniz  My last version from where I upgraded was from <revision>2.7.51.git20160518.b696773</revision>. This version did not show the error. If I understood correctly, there was no migration in the meantime. The old version did not show this exception, the new one does.

**Comment by mmohring** [comment]
This was committed at 19.05. So a DB migration should happen when I call rake db:migrate. But it does not.

**Comment by mdeniz** [comment]
Can you run a
```
rake db:migrate:redo VERSION= 20160321105300
rake db:migrate:redo VERSION= 20160518105300
```
to force  a re-run on those migrations and see what happen?

**Comment by mdeniz** [comment]
Optionally you can search for those migrations records at `schema_migrations` table

**Comment by mmohring** [comment]
I forced a redo of those migrations like you propose. E.g.:

- I shut down API and API delay job
- ran the two migrations you say above by hand
- restarted API

I get the output of the two migrations that they are run. Then it works, no 500. Stays the question why the two migrations were not called when running `RAILS_ENV=production rake db:migrate` automatically. I know for sure that the last migration that was correctly run was 20160321104000_add_k1om.rb .

**Comment by mmohring** [comment]
When I deployed 2.7.51.git20160518.b696773, migration 20160321105300 was also not run. But WebUI => Project => Status does not make a 500 error there.

**Comment by mdeniz** [comment]
No clear idea right now, usually migrations are not re-run if the first time they run some exception  popped out... but if you say that you didn't notice that... :scream:

**Comment by mdeniz** [comment]
Anyway... Can we close this issue?

**Comment by mmohring** [comment]
I dont know. Why are those migrations not run ? Then comes the 500 error.

**Comment by mmohring** [comment]
To make it clear: it started with 2.7.51.git20160518.b696773. Running `RAILS_ENV=production rake db:migrate` did not run migration 20160321105300. I had reset my database to the backup there. The second migration is also not run when updating to current git master.

**Comment by mmohring** [comment]
You should be able to reproduce this with b.o.o, it runs also 2.7.51.git20160518.b696773 according to api about.

**Comment by mmohring** [comment]
I went back to 2.7.51.git20160518.b696773, and restored by DB backup from this version. I updated to git master. `RAILS_ENV=production rake db:migrate` worked and ran the new migration. I dont know what happened in the first time. So I close this.

**Comment by mdeniz** [comment]
Ok, perfect. Thank you so much Martin!

**Comment by mmohring** [comment]
The migration 20160321105300_request_counter.rb was changed 3 times according to git. If you had used a version in the middle, then it the migration is not performed correctly and the final version is never run.

**Comment by mdeniz** [comment]
Nice. Now we know what maybe happened to you :smile:

**Comment by mmohring** [comment]
Yes, good to know. I hate it if there is no explanation and potential random behavior. I usually test exactly, and also the code should not behave randomly :-)

**Comment by hennevogel** [comment]
@adrianschroeter never ever [change existing migrations](http://guides.rubyonrails.org/active_record_migrations.html#changing-existing-migrations) please...

**Comment by adrianschroeter** [comment]
you have to when the old code fails....

**Comment by mmohring** [comment]
@adrianschroeter I was not complaining. I just wanted to know how this could happen. I ran into the risk of a weekly testing.

**Comment by hennevogel** [comment]
@adrianschroeter when the old code fails then mitigate this in a new migration. 8ec39958dc6c and 876b13157 of 20160321105300_request_counter.rb will just never run once I have executed 8167d4a5cd

**Comment by adrianschroeter** [comment]
@hennevogel you would also need to write special code then to deal with half broken update .. 

however, they should run again, since they failed in between (on some instances), so they are not marked as successfull.
