### ISSUE TITLE
[openbuildservice.org] Bad download link

### ISSUE THREAD

**Issue by vyskocilm** [openSUSE/open-build-service#1883]
Hi,

the link at http://openbuildservice.org/download/ points at non existent URL
http://download.opensuse.org/repositories/OBS:/Server:/2.7/images/iso/obs-server.x86_64.install.iso

I assume the correct one is this one
http://download.opensuse.org/repositories/OBS:/Server:/2.7/images/iso/obs-server.x86_64.iso

**Comment by mdeniz** [comment]
Hey @vyskocilm , 

It really belongs to the https://github.com/openSUSE/obs-landing repo, we will fix it. 

Many thanks

**Comment by mdeniz** [comment]
Fixed!
