### ISSUE TITLE
Introduce repository_controller

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#1889]
While migrating save_distribution tests I encountered several problems. After discussion with @hennevogel we agreed that we should introduce an webui/repositories_controller.rb which should implement CRUD actions. We should move following actions to the new controller:

- save_distributions (:create)
- save_repository (:create)
- add_repository_from_default_list (:new)
- add_repository
- (move_path) (:edit, :update)
- (remove_path_from_target) (:edit / :update)
- (remove_target) (:edit / :update)

**Comment by ChrisBr** [comment]
@mdeniz cc

**Comment by mdeniz** [comment]
I agree!!! :smile:

**Comment by ChrisBr** [comment]
@mdeniz Currently I'm working on it ...

**Comment by bgeuken** [comment]
@ChrisBr That's done, right?

**Comment by hennevogel** [comment]
It is...
