### ISSUE TITLE
[api] xsd schemas

### ISSUE THREAD

**Issue by KostyaSha** [openSUSE/open-build-service#190]
Trying to work with xsd and got error:
parsing a schema...
[ERROR] src-resolve.4.2: Error resolving component 'xs:number'. It was detected that 'xs:number' is in namespace 'http://www.w3.org/2001/XMLSchema', but components from this namespace are not referenceable from schema document 'file:/xsd/buildhistory.xsd'. If this is the incorrect namespace, perhaps the prefix of 'xs:number' needs to be changed. If this is the correct namespace, then an appropriate 'import' tag should be added to 'file://xsd/buildhistory.xsd'.
  line 22 of file://xsd/buildhistory.xsd

[ERROR] src-resolve: Cannot resolve the name 'xs:number' to a(n) 'type definition' component.
  line 22 of file://xsd/buildhistory.xsd

[ERROR] src-resolve: Cannot resolve the name 'xs:number' to a(n) 'simpleType definition' component.
  line 22 of file://xsd/buildhistory.xsd

[ERROR] src-resolve: Cannot resolve the name 'xs:number' to a(n) 'simpleType definition' component.
  line 25 of file://xsd/buildhistory.xsd

[ERROR] src-resolve: Cannot resolve the name 'xs:number' to a(n) 'simpleType definition' component.
  line 26 of file://xsd/buildhistory.xsd

Failed to parse a schema.

Please check whether this messages are right.

**Comment by bgeuken** [comment]
@mlschroe @adrianschroeter Can we either solve or close this issue?:-)

**Comment by mdeniz** [comment]
@mlschroe @adrianschroeter ping!

**Comment by adrianschroeter** [comment]
xmllint --schema buildhistory.xsd buildhistory.xml

validates for me.
