### ISSUE TITLE
[build service]Unable to build LLVM 3.8 for Debian 8: internal bug

### ISSUE THREAD

**Issue by Sunderland93** [openSUSE/open-build-service#1902]
Hello. I tried to build LLVM 3.8 on Debian 8, for 2 days. But build VM produces errors "No space left on disk" and "Out of memory". Log's attached https://www.dropbox.com/s/l5v6jd8h92jfr81/build_amd64.log?dl=0 https://www.dropbox.com/s/esvpoln08s9kjcp/build_i386.log?dl=0

**Comment by bgeuken** [comment]
A link to your project would be nice;-) You might need some [constraints](http://openbuildservice.org/help/manuals/obs-reference-guide/cha.obs.build_job_constraints.html) to get a build host that has enough resources for your build job.

**Comment by Sunderland93** [comment]
Here is my project https://build.opensuse.org/package/show/home:Sunderland93:graphics-drivers/llvm

**Comment by bgeuken** [comment]
Your build might need a decent amount of memory and disk space which is not provided by all of our build hosts. To trigger a rebuild: Click on the "debian_8.0" link (the build target) and then click on "trigger rebuild".

However it might be a good idea to add a _contraints file first to prevent this from happening again.

Here it is documented how you can do so: http://openbuildservice.org/help/manuals/obs-reference-guide/cha.obs.build_job_constraints.html
