### ISSUE TITLE
[Arch Linux] Broken build image

### ISSUE THREAD

**Issue by ItachiSan** [openSUSE/open-build-service#1903]
As in title.

**The long story**
I tried to build a personal AUR package, as I would like to give to users the possibility to fetch my packages instead of building them locally.
I started to set-up stuff and I got up to this point:
https://build.opensuse.org/package/show/home:ItachiSan:archlinux/gettext-java
so, as it is supposed to be, now it should build properely.
But, in fact...
https://build.opensuse.org/package/live_build_log/home:ItachiSan:archlinux/gettext-java/Arch_Extra/x86_64

For some reason, the build image is missing some library (`liblz4.so.1`, included in *lz4*, direct dependency of **systemd**).

I hope that the base build image for Arch Linux packages will be fixed soon.

**Comment by ItachiSan** [comment]
The bug is reproducible: I tryed to add a community package (*python-six*) and it failed to build:
https://build.opensuse.org/package/live_build_log/home:ItachiSan:archlinux/python-six/Arch_Extra/i586

**Comment by bgeuken** [comment]
Did you try to add liblz4-1 as (build) dependency? At least on my (openSUSE) system it's not a requirement of systemd.

**Comment by ItachiSan** [comment]
The dependency is *pacman*-related; the command inside the chroot (I suppose it's a chroot) fails as *pacman* doesn't have that library.

**Comment by ItachiSan** [comment]
Added to *obs-build*, see OpenSUSE/obs-build#276

**Comment by bgeuken** [comment]
Glad to see it's solved already. Thanks much for the patch!
