### ISSUE TITLE
Broken ArchLinux package signatures

### ISSUE THREAD

**Issue by ItachiSan** [openSUSE/open-build-service#1907]
Recently, Arch packages signatures have been readded to the build server (see 32384a5).

The database signature works properely, but the package one does not.
I discussed on the ArchLinux general mailing list and this popped out:
https://lists.archlinux.org/pipermail/arch-general/2016a-July/041531.html
The actual signature added to the database (specifically, the *desc* file of each package) contains newlines, which pacman does not recognise, as it expects *%PGPSIG%* to be on a single line.
To fix the problem, newlines should be removed.
I am not sure, but maybe it can be done in this line:
https://github.com/openSUSE/open-build-service/blob/master/src/backend/bs_mkarchrepo#L93
but I have no knowledge of perl, so I sincerely don't know.

**Comment by ItachiSan** [comment]
I've created a quick fix (not dirty, also...!) that is present here: #1908
Maybe not the fanciest thing, but works and it's my first time with Perl. :stuck_out_tongue: 
On server side, you should run the *bs_mkarchrepo* for all the existent Arch repositories to have the signature fixed.

**Comment by mlschroe** [comment]
Merged, thanks!
