### ISSUE TITLE
validation_failed (400) Element project has extra content: download

### ISSUE THREAD

**Issue by abrgitlab** [openSUSE/open-build-service#1912]
I try to migrate from old OBS and have a problem with migrating projects.
I did not setup old OBS, so I am newby. I try to install new OBS from zypper repository. But I tested vmdk image and it works fine.
When I try to create new repository on my new OBS I've got this error:
BuildService API error: validation_failed (400)
project validation error: Element project has extra content: download

This is configuration which works both on old OBS and OBS from vmdk image. But doesn't work on the new OBS. Why?
There's project config I try to add:
```
<project name="Ubuntu:14.04:main">
  <title/>
  <description/>
  <person userid="Admin" role="maintainer"/>
  <download baseurl="http://repo.devbanki.ru/ubuntu/" metafile="Packages" mtype="debmd" arch="x86_64"/>
  <build>
    <disable/>
  </build>
  <publish>
    <disable/>
  </publish>
  <repository name="universe">
    <arch>x86_64</arch>
  </repository>
  <repository name="main">
    <arch>x86_64</arch>
  </repository>
</project>
```

**Comment by bgeuken** [comment]
We've updated the download on demand feature in 2.7. That included [stylechanges](75a2034186677c12fc5d6083254b8c74f7bfce52) of the xml.

It used to be an experimental feature, thus we did not provide an automatic upgrade of old DoD configurations.

The new xml format is documented here:
http://openbuildservice.org/help/manuals/obs-reference-guide/cha.obs.concepts.html#concept_dod
