### ISSUE TITLE
2.8: prefix based webui: assets not found

### ISSUE THREAD

**Issue by matwey** [openSUSE/open-build-service#1921]
Hello,

I am running `obs-api-2.7.0-4.1.noarch`, and I tried to configure OBS to run with base prefix `/obs`.
I've configured Passanger as described here: https://www.phusionpassenger.com/library/deploy/apache/deploy/ruby/
Then I also reconfigured `api_relative_url_root` in `config/options.yml`
I use bento webui theme.

However, some assets are not found when webui running.
Those are:
- `images/gradient-dark-nav-*.png`
- `images/icons_sprite-*.png`
- `images/gradient-light-*.png`

As far as I understand they are referenced from `webui/application.css`, where `image-url(X)` expands into `/assets/image/`.

**Comment by matwey** [comment]
Hello?

**Comment by matwey** [comment]
The issue is stil present in 2.8

**Comment by mdeniz** [comment]
This is related to #2948, see there the reason of closing this one.
