### ISSUE TITLE
/pulic route does not allow access to sources / patches

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#1940]
In the past, it was possible to get raw patches from OBS without logging in, example address:

https://api.opensuse.org/public/source/GNOME:Apps/giggle/giggle-gtksourceview38.patch?rev=9f2b455c0e11ca5a67b9c58b2b2b70d4

This is no longer possible: only the non-public route works.

Having to login in order to be able to receive the raw patch does not make us very 'open' to other projects

**Comment by DimStar77** [comment]
Urgh - it's browser detection that messes in here:
getting the same URL using curl works

**Comment by hennevogel** [comment]
Works without the rev parameter and format=xml for me

**Comment by DimStar77** [comment]
with 'format=xml' I'd expect an XML document to be served; so if anything, this is just even more confusing

**Comment by mdeniz** [comment]
Was fixed by #2098
