### ISSUE TITLE
Context sensitive help for issue trackers

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/open-build-service#1946]
For OBS and IBS I operate an OBS-bugzilla integration script and would like to have one or two lines of information displayed in a osc sr comment and in a webUI sr page, such as

```
This OBS uses bnc# markers from SR comments to update bugzilla entries.
For more details see http://en.opensuse.org/...
```

However, hardcoding this in osc and webui is not nice, as people rarely update their osc and might operate it with other OBS installations where the comment does not apply, so the cleanest approach to solve this would be to have `osc sr` query an API URL from OBS to fetch the extra message.
And there would need to be some way (API or config-file) for an admin or someone with write-permissions to SR-target project metadata to configure the message (which does not change often).

**Comment by hennevogel** [comment]
We know which issue trackers are enabled on the OBS instance. `osc` can query this too via the [API](https://api.opensuse.org/apidocs#2) (please create a seperate feature for this in the [osc project](https://github.com/openSUSE/osc))

What exactly is the message you want to have displayed?

**Comment by bmwiedemann** [comment]
> What exactly is the message you want to have displayed?

something like
```
This OBS uses bnc# markers from SR comments to update bugzilla entries.
For more details see http://en.opensuse.org/OBS-bugzilla-integration
```

To tell people, that this exists and where they can find further information about it. E.g. the wiki page would have a link to https://github.com/bmwiedemann/obsbugzilla/

**Comment by bmwiedemann** [comment]
Maybe worth noting that this is a different thing than https://api.opensuse.org/apidocs#2 which links from OBS to issue-trackers. But my tool links from bugzilla to OBS.

**Comment by hennevogel** [comment]
Ah so this is build.opensuse.org/bugzilla.opensuse.org specific. Sorry this won't go into the app as it's only useful for this care. If you need people to know that you have to find another way...
