### ISSUE TITLE
"Request got superseded by" link is broken

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/open-build-service#1954]
Clicking on the link results in the same request being opened again, but the right ID as GET parameter (https://build.opensuse.org/request/show/412321?id=412322)

Example: https://build.opensuse.org/request/show/412321

**Comment by coolo** [comment]
works for me

**Comment by Vogtinator** [comment]
Did you click on the link in the "Request History"?

**Comment by bgeuken** [comment]
That seems wrong

**Comment by bgeuken** [comment]
Guess what. It's another BsRequest number bug:(
