### ISSUE TITLE
AppStream Metadata is no longer published / or incomplete

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#1957]
Examples:

GNOME:Factory: http://download.opensuse.org/repositories/GNOME:/Factory/openSUSE_Factory/repodata/?P=*appdata.xml.gz

While inspecting this package, there is only one single application registered;

looking at the produced binaries of different packages, there are certainly some missing (e.g. evolution)

This results in zypper losing information about package/application relations

**Comment by DimStar77** [comment]
Seems once again this brp-extrac-appdata stuff is broken... it would be ooooh so easy if the publisher would just start appstream-builder to prouced fully validated AppStream metadata

**Comment by DimStar77** [comment]
1 issue found so far: brp-extract-appdata seems to produce %{name}.appdata.xml files - OBS looks for *-appdata.xml files (dot vs dash)

**Comment by mlschroe** [comment]
It would be ooh so easy if you wouldn't break the brp script so often...

**Comment by DimStar77** [comment]
oh - so we just ignore the fact that all is broke; great... 

or why did you just close this? (yes, I started looking into the brp-script to see what goes wrong... this script certainly needs some love)

**Comment by DimStar77** [comment]
I'll just revert brp-extract-appdata to rev 36 in X11:common:Factory - that's the last version submitted by @mls - so none of 'my' breakages will be in brp-extract-appdata.

We know it still won't work afterwards, but assigning @mls as the sole maintainer of this script will give us at least somebody that knows what he does, never breaks it and fixes all issues.

**Comment by mlschroe** [comment]
I closed it because the filename is wrong as you already found out, that's why there is nothing in the repository appdata files. There's nothing to fix on my side.

(And don't expect me to maintain that script.)

**Comment by DimStar77** [comment]
There are two ways to fix the wrong file name:
- Fix it in OBS site - having the file called NAME.appdata.xml allows people to getbinaries and run appdata validation tools over the file; this is not possible on NAME-appdata.xml
- Fix the script to procue again NAME-appdata.xml files; with the drawback mentioned above.

**Comment by mlschroe** [comment]
(And my ooh so easy remark was directed at your oooh so easy comment about using appstream-builder in the publisher, which you already know is a no go.

**Comment by k0da** [comment]
@DimStar77 https://github.com/openSUSE/open-build-service/pull/1779

**Comment by hennevogel** [comment]
Hey peepz do :green_heart: each other, this is just stupid software :-)

Is the brp-script fixed now?

**Comment by mlschroe** [comment]
Hey, if there's a technical reason to also look for NAME.appdata.xml I'll certainly change the code to also look for that name.

**Comment by DimStar77** [comment]
(the "oh so" was obvious from my end.. and I agree I should have skipped it; I formally apologize for that)

**Comment by mlschroe** [comment]
@k0da: sorry about missing that pull request.

**Comment by mlschroe** [comment]
But it needs to support both the old and the new names, which it currently doesn't do.

**Comment by k0da** [comment]
brp-extract-appdata still needs love, and implement all of those modifications are done by appstream-glib

**Comment by k0da** [comment]
I didn't care about old format. I've being told it doesn't work reliably.

**Comment by k0da** [comment]
My status working on AppData was only gnome-shell extensions was missing

**Comment by mlschroe** [comment]
ok, we now support both the old and the new naming styles. Will be deployed next week. Thanks guys!
