### ISSUE TITLE
Arch repo _pubkey

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#1965]
It seems that the `_pubkey` is not published to Arch repos. This makes it hard for users to find the key to verify against.

**Comment by mlschroe** [comment]
Tell me where to put it and I'll change the code.

**Comment by hennevogel** [comment]
The [arch docu](https://wiki.archlinux.org/index.php/Pacman/Package_signing) says wherever you want

**Comment by mlschroe** [comment]
Ok, then fixed.
