### ISSUE TITLE
Make _pubkey available in the UI

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#1966]
Every build/repo is signed by some key (/source/$PROJECT/_pubkey). This should be displayed somewhere in the UI.

**Comment by mlschroe** [comment]
(Only if it's configured that way. You can also run OBS without package signing. Also keep in mind that finding the correct pubkey is an expensive operation)

**Comment by hennevogel** [comment]
Can I ask the backend if a signer is running?

**Comment by mlschroe** [comment]
You mean running as in configured? Nope, not yet.

**Comment by adrianschroeter** [comment]
we should create anyway a new api call providing the right public key, the project it is comming from and some more meta data (creation date, certificate...). Would be in first place a source server api call, but forwarded by the api.

**Comment by hennevogel** [comment]
This is done in the meanwhile...
