### ISSUE TITLE
Triggering services from the UI

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#1971]
There is a backend call to trigger services

```
Suse::Backend.post("/source/@project/@package?cmd=runservice&user=@user")
```

This should be callable from `PackageController#show`. 

![screenshot from 2016-07-28 13-44-57](https://cloud.githubusercontent.com/assets/514785/17211445/ddec87de-54c9-11e6-9222-0c744d8a2c2d.png)

**Comment by bgeuken** [comment]
@Ana06 As said, might be a fun thing to do and a good way to get familiar with OBS
