### ISSUE TITLE
Wrong .spec file built instead of none

### ISSUE THREAD

**Issue by afaerber** [openSUSE/open-build-service#1974]
On build.opensuse.org I have a package (_link) cross-epiphany-gcc6 that contains a cross-epiphany-gcc6-bootstrap.spec but no cross-epiphany-gcc6.spec (yet).

**Expected:** "excluded" for all repos, for lack of .spec file.

**Observed:** "succeeded", apparently built from the -bootstrap.spec file instead.

Possibly related to OBS supporting per-repository specfile suffixes, but my "bootstrap" is not the name of a repository.

**Comment by marcus-h** [comment]
On 2016-07-31 03:37:34 -0700, Andreas Färber wrote:
> On build.opensuse.org I have a package (_link) cross-epiphany-gcc6 that contains a cross-epiphany-gcc6-bootstrap.spec but no cross-epiphany-gcc6.spec (yet).
> 
> **Expected:** "excluded" for all repos, for lack of .spec file.
> 
No, because there is a spec file. In general, there is no relation
between the spec file name and the package name (obs package). If
there are multiple spec files, the following is tried (a bit simplified
(for details see findfile in bs_srcserver)):
- <pkg>-<repo>.spec
- <pkg>.spec
- c1.spec (if <pkg> = <c1>.<c2>. ... .<cn>)
- *.spec (if there is exactly one file that ends with ".spec")
- try to find a match based on <pkg> and <repo>

> **Observed:** "succeeded", apparently built from the -bootstrap.spec file instead.
> 
> Possibly related to OBS supporting per-repository specfile suffixes, but my "bootstrap" is not the name of a repository.

**Comment by coolo** [comment]
So you can only expect excluded if there are *more* than 1 spec files and none matches the algorithm above.

**Comment by afaerber** [comment]
@coolo The gcc6 package does have more than 1 .spec file.

@marcus-h I'm not a Perl expert... Is it caused by this src/backend/bs_srcserver:findfile snippet?

```
  # try again without last components
  if ($packid =~ /^(.*?)\./) {
    return $files{"$1.$ext"} if $files{"$1.$ext"};
  }
```

To me that looks like your &lt;c1&gt;.&lt;c2&gt; case with dots (\\.), whereas there were no additional dots in my case. Also I assume =~ modifies $packid before the two greps below?

Could you confirm whether stripping `-bootstrap` is expected behavior or not?

Anyway, my point was that it does not really make sense to me to build the same .spec file in two different packages in the same project. I.e., would it be possible for findfile to check when in foo-bar package for an algorithm-resulting foo.spec file whether there is a foo sibling package and then skip returning foo.spec inside foo-bar?

**Comment by marcus-h** [comment]
On 2016-08-01 03:22:18 -0700, Andreas Färber wrote:
> @coolo The gcc6 package does have more than 1 .spec file.
> 
> @marcus-h I'm not a Perl expert... Is it caused by this src/backend/bs_srcserver:findfile snippet?
> 
> ```
>   # try again without last components
>   if ($packid =~ /^(.*?)\./) {
>     return $files{"$1.$ext"} if $files{"$1.$ext"};
>   }
> ```
> 
> To me that looks like your &lt;c1&gt;.&lt;c2&gt; case with dots (\\.), whereas there were no additional dots in my case.

The package name "cross-epiphany-gcc6" has no dot (".") - so this doesn't
match.

> Also I assume =~ modifies $packid before the two greps below?
> 
In the context above, =~ doesn't modify $packid (its right hand side
is just a pattern match (no substitution etc.)).

> Could you confirm whether stripping `-bootstrap` is expected behavior or not?
> 
Hmm it depends on the number of spec files in your package and their names.
Can you post a link to your package?

**Comment by afaerber** [comment]
https://build.opensuse.org/package/show/home:a_faerber:epiphany/cross-epiphany-gcc6

By now I [added the cross-epiphany-gcc6.spec](https://build.opensuse.org/package/rdiff/home:a_faerber:epiphany/gcc6?linkrev=base&rev=2) - originally I forgot to add it and was caught by surprise that it was "building" or "succeeded" despite my error.

**Comment by afaerber** [comment]
Sorry, I notice that I screwed up the description above, the original issue description had it correct though.

I am demonstrating it here:
https://build.opensuse.org/package/show/home:a_faerber:branches:devel:gcc/cross-epiphany-gcc6
As one can see on the [repo pages](https://build.opensuse.org/package/binaries/home:a_faerber:branches:devel:gcc/cross-epiphany-gcc6?repository=openSUSE_Factory), cross-epiphany-gcc6 package is (unexpectedly?) building cross-epiphany-gcc6-bootstrap.spec for lack of cross-epiphany-gcc6.spec.

**Comment by adrianschroeter** [comment]
building the spec file no matter which name is a wanted behaviour as long as it is definite which one.

So what is still open to discuss here?

**Comment by marcus-h** [comment]
On 2016-08-01 11:23:09 -0700, Andreas Färber wrote:
> Sorry, I notice that I screwed up the description above, the original issue description had it correct though.
> 
> I am demonstrating it here:
> https://build.opensuse.org/package/show/home:a_faerber:branches:devel:gcc/cross-epiphany-gcc6
> As one can see on the [repo pages](https://build.opensuse.org/package/binaries/home:a_faerber:branches:devel:gcc/cross-epiphany-gcc6?repository=openSUSE_Factory), cross-epiphany-gcc6 package is (unexpectedly?) building cross-epiphany-gcc6-bootstrap.spec for lack of cross-epiphany-gcc6.spec.
> 
That's the "expected" result (wrt. to the findfile algorithm): it is the
only spec file that contains the package name.

**Comment by afaerber** [comment]
Thanks for confirming, closing it as intentional behavior then.
