### ISSUE TITLE
API server incorrectly determines account state

### ISSUE THREAD

**Issue by myungjoo** [openSUSE/open-build-service#1976]
There is a case where OBS API server (`src/api/app/controllers/application_controller.rb`) determines the state of an account incorrectly and says a confirmed user is not confirmed:

```
inactive_user(User is registered but not in confirmed state. Your account is a registered account, but it is in a not active state.):
```

This is because the LINE209 of `src/api/app/controllers/application_controller.rb` is incorrect:
```
    if @http_user.state == User::STATES['confirmed']
      logger.debug "USER found: #{@http_user.login}"
      @user_permissions = Suse::Permission.new(@http_user)
      return true
    end
```
where `@http_user.state` is `'confirmed'`, not '2' when this code is invoked by osc meta or web browser: `https://SERVERNAME/source/PROJECTNAME/_config`.

This could be simply mended by modifying the conditions as follows:
```
    if @http_user.state == 'confirmed'
```

However, the question here is whether such modification is safe or not. If there are cases where `@http_user.state` is integer, we should somehow "unify" the usage or make an OR statement here.

**Comment by adrianschroeter** [comment]
Do you run a 2.7 branch with a database migrated to git master?

**Comment by myungjoo** [comment]
Yes, I'm running github's 2.7 branch and the database was initialized by `$ rake db:setup`.

I've installed the server with `$ make install`; however, there could be files that were migrated from git master(or  2.7 branch) as I once executed `rails s` before running `make install`.

**Comment by myungjoo** [comment]
I've got what's wrong in the setup. The DB (mysql) contents were contaminated like adrianschroeter has suspected. Thanks!
