### ISSUE TITLE
Compatibility with DataTables. (using deprecated function)

### ISSUE THREAD

**Issue by myungjoo** [openSUSE/open-build-service#1978]
It appears that the current OBS code using DataTables (e.g., `src/api/app/assets/javascripts/webui/application/project.js`) is not compatible with the current DataTables.

So, I'd like to suggest to update Gemfile to specify the version of (a bit old) DataTables

OR

Let the DataTables using code to add a function supporting the recent DataTables. For example, in `project.js':
```
function renderProjectsTable(length) {
    length = (typeof length === "undefined") ? 25 : length;
    var projects = main_projects;
    if (!$('#excludefilter').is(":checked"))
        projects = projects.concat(excl_projects);
    var projecturl = $("#projects_table_wrapper").data("url");
    $("#projects_table_wrapper").html('<table cellpadding="0" cellspacing="0" border="0" class="display" id="projects_table"></table>');
    $("#projects_table").dataTable({"aaData": projects,
        "bPaginate": true,
        "aoColumns": [
            {
                "sTitle": "Name",
                "mData": function (obj) {
                    // Supports recent DataTables
                    var url = projecturl.replace(/REPLACEIT/, obj[0]);
                    return '<a href="' + url + '">' + obj[0] + '</a>';
                },
                "fnRender": function (obj) {
                    // Deprecated in recent DataTables
                    var url = packageurl.replace(/REPLACEIT/, obj.aData);
                    return '<a href="' + url + '">' + obj.aData + '</a>';
                }
            },
            { "sTitle": "Title" },
        ],
        "iDisplayLength": length,
        "bStateSave": true
    });
}
```

If the latter is appropriate, please review the related pull request.

**Comment by mdeniz** [comment]
Hey @myungjoo, I think that for the moment is better to fix a gem version of jquery-datatables-rails (maybe to 1.12.2) instead of dealing with this issue now and more future issues that can appear. If someday we refactor the UI then we will be doing deeper changes on that.

What do you thing?

**Comment by bgeuken** [comment]
Going to be solved once we've upgraded to rails 5, which includes us useing dataTables 3.4 https://github.com/openSUSE/open-build-service/pull/1979#issuecomment-238145939.

**Comment by mdeniz** [comment]
Ok @bgeuken, I will merge my PR to solve this right now because I guess that upgrading to rails 5 can take a while...
