### ISSUE TITLE
Builds are randomly failing in OBS

### ISSUE THREAD

**Issue by ronisbr** [openSUSE/open-build-service#1983]
Hi guys!

Today, many of my buildings in OBS are randomly failing with this message:

```
connect to src-opensuse:5353: Connection timed out

gave up after 10 failed build attempts...
```

or this one

```
received truncated answer

gave up after 9 failed build attempts...
```

Is it a known problem or am I doing something wrong? By the way, I have already triggered a rebuild in all the packages and I am still seeing those failures.

**Comment by adrianschroeter** [comment]
this is not a support portal for any running instance of OBS.

(but it got fixed on build.opensuse.org in case you speak about that one)
