### ISSUE TITLE
save repository does not work for some repos

### ISSUE THREAD

**Issue by lethliel** [openSUSE/open-build-service#1986]
save remote repos over interconnect

**Comment by hennevogel** [comment]
This is not fixed with 3815422644b4e176b905e8d26708c9fa5ab23914

**Comment by hennevogel** [comment]
```
irb(main):012:0> "some dots?dots*dots".sub("!\"#$%&'()*+,./:;<=>?@[\\]^`{|}~", '_')
=> "some dots?dots*dots"
```

**Comment by ChrisBr** [comment]
@hennevogel yes, sadly I also found that out this morning ...
And yes, tests are awesome :+1: 

https://github.com/openSUSE/open-build-service/pull/2053

It worked with one character and I just quickly adapted it to match for several character, which didn't work! Once again, tests are awesome, even when you're in a hurry :smile:
