### ISSUE TITLE
Can't list maintenance_release requests

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#1988]
coolo@nohostname#~>osc rq list openSUSE:Leap:42.1:Update -s accepted -t maintenance_release
invalid argument: 'acceptinfo_opackage'

The argument is not sent by osc from what I can say, so it looks like some API vs. src server thing

**Comment by marcus-h** [comment]
On 2016-08-07 08:42:40 -0700, Stephan Kulow wrote:
> coolo@nohostname#~>osc rq list openSUSE:Leap:42.1:Update -s accepted -t maintenance_release
> invalid argument: 'acceptinfo_opackage'
> 
> The argument is not sent by osc from what I can say, so it looks like some API vs. src server thing
> 
Hmm this looks like an "ancient" osc version. It should work with
osc >= 0.152.

**Comment by coolo** [comment]
hmm, now that you say it -  osc is an alias to some git checkout I don't update very often. I didn't realize that. Sorry for the noise then, it works with /usr/bin/osc

**Comment by vpereira** [comment]
Debian Jessie has  osc == 0.149.
