### ISSUE TITLE
delete requests refer to Factory sources

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#1990]
When looking at a delete request for 42.2 in the web ui, e.g. https://build.opensuse.org/request/show/390237

The links for the individual files in the package (like the spec file) point to Factory instead of 42.2 which of course throws an error in this case.

**Comment by lnussel** [comment]
should be trivial to fix. anyone?

**Comment by krauselukas** [comment]
@hennevogel @lnussel I think we can close this, since meanwhile we are not linking to the files anymore and instead showing a diff 
![Screenshot_2020-08-05 Request 805839 (review)(1)](https://user-images.githubusercontent.com/22001671/89427049-1561e180-d73b-11ea-914e-2d5c2121e9b4.png)
