### ISSUE TITLE
list of delete requests doesn't show package name

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#1991]
When listing delete requests no package name is shown, e.g.
https://build.opensuse.org/project/requests/openSUSE:Leap:42.2

So the list is a bit of limited use. Maybe a package name could be forged into the source column, even though that column doesn't make sense for delete requests?

**Comment by lnussel** [comment]
![delete](https://cloud.githubusercontent.com/assets/722232/19388365/8bcc25e8-921f-11e6-9a52-4804f65e9dd4.png)

**Comment by lnussel** [comment]
This was actually fixed without anyone closing the ticket

**Comment by hennevogel** [comment]
stealth fixes!
