### ISSUE TITLE
Search error in https://software.opensuse.org

### ISSUE THREAD

**Issue by mbrig-co** [openSUSE/open-build-service#1993]
What the hell is this?

![fireshot capture 104 - software opensuse org_ error_ - https___software opensuse org_search](https://cloud.githubusercontent.com/assets/11582342/17507196/9de9cab2-5e23-11e6-9c58-73a22b1f8c49.png)

**Comment by coolo** [comment]
first of all an issue of software-oo not to catch 500s

**Comment by mbrig-co** [comment]
Is it not an issue?

**Comment by adrianschroeter** [comment]
at least not an OBS code issue. software-o-o repo is responsible for this.
