### ISSUE TITLE
Web-UI: Search for packages in projects include full project path

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/open-build-service#1996]
Search for "system" in Base:System.

Result: All packages match

Expected: Only packages with "system" in the name, like "systemd" should match

**Comment by coolo** [comment]
because jquery datatables queries the HTML content (and that's a link to the package) not what you see.

**Comment by hennevogel** [comment]
You can limit that of course. https://datatables.net/manual/data/orthogonal-data#HTML-5

**Comment by coolo** [comment]
my google foo failed me for this

**Comment by mdeniz** [comment]
This looks like got fixed, please reopen if still valid for you.
