### ISSUE TITLE
OBS does not take 'BuildConflicts:' into account when building dependency tree

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#2004]
There is a package in multimedia:libs (vlc) that specifies in the .spec file: BuildConflicts: pkgconfig(libavutil) >= 55 (similar to what configure declines to build with.

RPM knows that well, once OBS setup the buildroot, the build fails with:

> ## I have the following modifications for vlc.spec:
> ## ----- building vlc.spec (user abuild)
> ---
> - exec rpmbuild -ba --define '_srcdefattr (-,root,root)' --nosignature --define '_build_create_debug 1' /home/abuild/rpmbuild/SOURCES/vlc.spec
>   error: Failed build dependencies:
>   pkgconfig(libavutil) >= 55 conflicts with vlc-2.2.4-0.x86_64
> 
> zeus failed "build vlc.spec" at Wed Aug 10 16:29:56 UTC 2016.

It would be nice if OBS could pre-detect this before firing off the build, chosing either a different set of packages (if possible) or mark the package unresolvable.

**Comment by DimStar77** [comment]
oh - I see this is working now?

```conflict for provider of pkgconfig(libgit2-glib-1.0) >= 0.24.4, (provider libgit2-glib-devel is conflicted by the build config)```

that's gitg in GNOME:Factory, which has a buildConflicts in place for this very case

**Comment by mlschroe** [comment]
Yes, BuildConflict handling was enabled with commit bc17ea36c41855f33069e72a400b434734a9026d from Fri Dec 2 16:27:30 2016.
