### ISSUE TITLE
Fedora 24 packages need updating

### ISSUE THREAD

**Issue by highperformancecoder** [openSUSE/open-build-service#2005]
Currently the package home:hpcoders1/minsky fails to build with Fedora 24. The symptom is an internal compiler failure:

`[  389s] /usr/lib/ecolab/include/TCL_obj_base.h:191:52: internal compiler error: in assign_temp, at function.c:961`
`[  389s]      template <class T> operator T() {return get<T>();}`
`[  389s]     `                                                ^
`[  390s] Please submit a full bug report,`
`[  390s] with preprocessed source if appropriate.`

However, the package builds fine on bog standard Fedora 24.

With obs, gcc reports

`/var/tmp/build-root/Fedora_24-x86_64/usr/bin/gcc -v`
`gcc version 6.1.1 20160510 (Red Hat 6.1.1-2) (GCC)`

But with the latest Fedora 24, gcc reports:
`gcc version 6.1.1 20160621 (Red Hat 6.1.1-3) (GCC) `

Clearly, there is a bug that has been addressed in Fedora, but this needs to be backported into the OBS packages for Fedora 24.

**Comment by adrianschroeter** [comment]
You need to build against Fedora:24/update repository instead of /standard to get the updates. You can change this in your project meta.
