### ISSUE TITLE
[production][webui/repositories#create] ActiveXML::Transport::Error: <status code="400">
  <summary>repository openSUSE_Tumbleweed listed...

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2019]
webui/repositories#create threw this 0 times

<pre>
ActiveXML::Transport::Error: &lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;repository openSUSE_Tumbleweed listed more than once&lt;/summary&gt;
&lt;/status&gt;

</pre>

[https://build.opensuse.org/project/save_repository?project=home%3Azain1989linux](https://build.opensuse.org/project/save_repository?project=home%3Azain1989linux)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/57b0876257c379000c000003)

**Comment by adrianschroeter** [comment]
New repository controller (or project model) tries to create multiple times the same repo. Should be catched in model and database already actually.

**Comment by bgeuken** [comment]
One thing I noticed (maybe related) while testing is: After branching another user's package, my branched package has all repositories but on the add repositories page all checkboxes were unchecked.

That's how the meta looked, before and after:

before:
```
  <repository name="xUbuntu_14.04">
    <path project="home:rubdos:thebounty" repository="xUbuntu_14.04"/>
    <arch>i586</arch>
    <arch>x86_64</arch>
  </repository>
```

after enabling ubuntu 14.04 checkbox:
```
  <repository name="xUbuntu_14.04">
    <path project="home:rubdos:thebounty" repository="xUbuntu_14.04"/>
    <path project="Ubuntu:14.04" repository="standard"/>
    <arch>i586</arch>
    <arch>x86_64</arch>
  </repository>
```

**Comment by hennevogel** [comment]
@bgeuken that is correct. Your fork does not build against Ubuntu:14.04. It builds against home:rubdos:thebounty that builds against Ubuntu:14.04.

**Comment by adrianschroeter** [comment]
should be solved now
