### ISSUE TITLE
home project creation is not checking for delete home

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2022]
The rails code is implicit creating home projects if they don't exist on login since OBS 2.7.  This is a problem when the project got deleted before: An undelete is not possible anymore afterwards. 
Users need to undelete the wanted packages manualy and need to re-setup their project config (meta and build config. GPG keys are also lost).

=> The webui code needs to check if a home project existed before and needs to offer to undelete it instead.

**Comment by adrianschroeter** [comment]
May be solved via https://github.com/openSUSE/open-build-service/issues/3130 .... not sure if the implicit home project creating does this check as well?

**Comment by hennevogel** [comment]
What exactly do you mean by implicit? If I delete my home project on the next login I get a "Create Home Project" link which leads to:

![Screenshot from 2019-08-22 15-35-00](https://user-images.githubusercontent.com/514785/63519009-783e7680-c4f2-11e9-98e3-889144cb0dc8.png)

**Comment by adrianschroeter** [comment]
oh, good ... i remember that webui once did it automatically (not a good idea, since we want to be able to create users without home project). So consider it as solved, if there is no special code anymore.
