### ISSUE TITLE
[production][webui/request#show] ActiveRecord::StatementInvalid: Mysql2::Error: Data too long for column 'key' at row 1: INSERT IN...

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#2025]
webui/request#show threw this 0 times

<pre>
ActiveRecord::StatementInvalid: Mysql2::Error: Data too long for column &#39;key&#39; at row 1: INSERT INTO `cache_lines` (`key`, `project`, `package`, `created_at`) VALUES (&#39;project_or_package_link/homeproject=jordimassaguerpla/package=golang-github-shurcool-sanitized_anchor_name.openSUSE_Leap_42.1_Update/project=home:jordimassaguerpla:branches:OBS_Maintained:golang-github-shurcool-sanitized_anchor_name/rev=/short=false/trim_to=40&#39;, &#39;home:jordimassaguerpla:branches:OBS_Maintained:golang-github-shurcool-sanitized_anchor_name&#39;, &#39;golang-github-shurcool-sanitized_anchor_name.openSUSE_Leap_42.1_Update&#39;, &#39;2016-08-11 11:21:53&#39;)
</pre>

[https://build.opensuse.org/request/show/418346](https://build.opensuse.org/request/show/418346)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/57ac5fdd3e7f9b000c000000)

**Comment by hennevogel** [comment]
This is happening frequently now

**Comment by eduardoj** [comment]
Already checked that this isn't logged in Errbit any more in the last year. Please reopen if it happens again.
