### ISSUE TITLE
OBS produces incomplete AppStream metainfo

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#2027]
OBS' way of merging .appdata.xml files has a small issue (resulting in the validator marking the files invalid)

the files are currently being created as AppStream metainfo version 0.8 (which is good), but they lack a mandatory 'origin' for version 0.8 as can be seen by trying to validate a file:

> appstream-util validate-relax --nonet /var/cache/zypp/raw/GNOME\:Apps/repodata/*appdata.xml.gz
> /var/cache/zypp/raw/GNOME:Apps/repodata/029205a603e534d328f12406959bffb2bf643ba37e63be6ebc9e7a705a5e72fa-appdata.xml.gz: FAILED:
> • tag-missing           : metadata version is v0.8 and origin attribute is missing
> Validation of files failed

The header of the .xml.gz currently is:
> <?xml version="1.0" encoding="UTF-8"?>
> <components version="0.8">

in order to be valid, it should be:
> <?xml version="1.0" encoding="UTF-8"?>
> <components version="0.8" origin="appdata">

(the origin we publish is preferrably some 'project related data', but is actually not that important: libzypp's appdata installer replaces it at install time with the repo name the user chose)

**Comment by adrianschroeter** [comment]
fixed with https://github.com/openSUSE/open-build-service/pull/2038
