### ISSUE TITLE
Attrib factory not valid by default

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#2028]
I wanted to create a `attrib_value` factory. However, I would need to specify 

`
factory :attrib_value do
    attrib
end
`
to create a valid attrib_value which doesn't work because `Attrib` validates presence of Package or Project. For now I created an empty factory which I just build and pass into my `attrib` instance

```
let!(:update_attrib) { create(:attrib, project: project, attrib_type: update_attrib_type, values: [attrib_value]) }
```

The problem is probably that `attrib` has polymorphic association to Package/Project, so we need to think about how we want to handle this in factories.

**Comment by hennevogel** [comment]
I would say you pick one of the associations by default and create it in the `attrib` factory. Like you do it for other factories which depend on the existence of associations.

Either I care about what the `attrib_value`'s `attrib` is associated with in my test, then I set it.

Or I don't, then I don't set it and the default works.

**Comment by hennevogel** [comment]
Deal?

**Comment by bgeuken** [comment]
Seems to be solved by now:
```ruby
x = FactoryGirl.create(:attrib)
=> #<Attrib id: 2, attrib_type_id: 23, package_id: nil, binary: nil, project_id: 2>
x.valid?
=> true
```
