### ISSUE TITLE
No status mails on obs-test

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#2030]
I received the last mail on obs-test on 04/14/2016 07:30 PM.

**Comment by ChrisBr** [comment]
After discussions with @adrianschroeter, seems like we have no network connection on the server which runs the script. He will start discussion with services team.

**Comment by mdeniz** [comment]
Is this still valid?

**Comment by ChrisBr** [comment]
No, works see https://lists.opensuse.org/obs-tests/2017-11/
