### ISSUE TITLE
Repository binarylist is broken for repository using DoD

### ISSUE THREAD

**Issue by tuminoid** [openSUSE/open-build-service#2061]
Getting a binarylist of `Ubuntu:16.04` from build.opensuse.org:

```
$ osc -A https://api.opensuse.org/ -X GET /build/Ubuntu:16.04/standard/x86_64/_repository
...
  <binary filename="zsh-common.deb" size="3170342" mtime="1469569341" />
  <binary filename="pool/main/z/zsh/zsh-dbg_5.1.1-1ubuntu2_amd64.deb" size="" mtime="" />
```

First entry is correct (all entries from `Ubuntu:14.04` look like that and they are downloadable), but the latter entry is just broken, and cannot be downloaded using the full path given, nor just the filename. Size and mtime entries are broken as well, so the backend is not handling them correctly either.

```
$ osc -A https://api.opensuse.org api -X GET /build/Ubuntu:16.04/standard/x86_64/_repository/pool/main/z/zsh/zsh-doc_5.1.1-1ubuntu2_all.deb
Server returned an error: HTTP Error 404: Not Found

$ osc -A https://api.opensuse.org api -X GET /build/Ubuntu:16.04/standard/x86_64/_repository/zsh-doc_5.1.1-1ubuntu2_all.deb
Server returned an error: HTTP Error 404: no such binary 'zsh-doc_5.1.1-1ubuntu2_all.deb'
no such binary 'zsh-doc_5.1.1-1ubuntu2_all.deb'
```

Ubuntu 16.04 is served over DoD, so either DoD or API is handling some paths incorrectly.

This is easy to reproduce by trying to mirror the Ubuntu:16.04/standard/x86_64 with `obs_mirror_project` tool.

**Comment by marcus-h** [comment]
On 2016-08-22 03:32:20 -0700, Tuomo Tanskanen wrote:
> Getting a binarylist of `Ubuntu:16.04` from build.opensuse.org:
> 
> ```
> $ osc -A https://api.opensuse.org/ -X GET /build/Ubuntu:16.04/standard/x86_64/_repository
> ...
>   <binary filename="zsh-common.deb" size="3170342" mtime="1469569341" />
>   <binary filename="pool/main/z/zsh/zsh-dbg_5.1.1-1ubuntu2_amd64.deb" size="" mtime="" />
> ```
> 
> First entry is correct (all entries from `Ubuntu:14.04` look like that and they are downloadable), but the latter entry is just broken, and cannot be downloaded using the full path given, nor just the filename. Size and mtime entries are broken as well, so the backend is not handling them correctly either.
> 
> ```
Hmm I wouldn't call this "broken" (IMHO, just dod semantics)
Just explicitly query for the binary names (instead of paths):

GET /build/Ubuntu:16.04/standard/x86_64/_repository?view=names

Then, the name provided by the filename attribute can be used to download
the binary etc. For dod packages, the size and mtime values are not
necessarily known (it depends on whether the metadata provide these
information or not).

> This is easy to reproduce by trying to mirror the Ubuntu:16.04/standard/x86_64 with `obs_mirror_project` tool.
> 
Hmm probably the tool isn't using the "view=names" query (I haven't
checked it yet...)

**Comment by tuminoid** [comment]
Hi @marcus-h. Using `?view=names` sure gives me more sane looking list, but those files without `size` and `mtime` (which formerly had full paths), cannot be downloaded still.

```
$ osc -A https://api.opensuse.org api -X GET /build/Ubuntu:16.04/standard/x86_64/_repository?view=names
...
  <binary filename="xserver-xorg-video-vesa-lts-utopic.deb" size="" mtime="" />
...
 
$ osc -A https://api.opensuse.org api -X GET /build/Ubuntu:16.04/standard/x86_64/_repository/xserver-xorg-video-vesa-lts-utopic.deb > file.deb
Server returned an error: HTTP Error 404: no such binary 'xserver-xorg-video-vesa-lts-utopic.deb'
no such binary 'xserver-xorg-video-vesa-lts-utopic.deb'
```

**Comment by marcus-h** [comment]
On 2016-08-23 01:19:24 -0700, Tuomo Tanskanen wrote:
> $ osc -A https://api.opensuse.org api -X GET /build/Ubuntu:16.04/standard/x86_64/_repository/xserver-xorg-video-vesa-lts-utopic.deb > file.deb
> Server returned an error: HTTP Error 404: no such binary 'xserver-xorg-video-vesa-lts-utopic.deb'
> no such binary 'xserver-xorg-video-vesa-lts-utopic.deb'

Arghs yes... should be fixed by PR #2067. As a workaround you can simply
omit the bin suffix. For instance,
GET /build/Ubuntu:16.04/standard/x86_64/_repository/xserver-xorg-video-vesa-lts-utopic
should do the trick.

**Comment by tuminoid** [comment]
@marcus-h I patched the mirror script to remove the `.deb` suffix from filename, along with `?view=names` and then it worked fine. All the local filenames were without `.deb` suffix too, which might still be problem with PR #2067 (if I understand correctly what it does).

**Comment by marcus-h** [comment]
On 2016-08-26 03:05:02 -0700, Tuomo Tanskanen wrote:
> @marcus-h I patched the mirror script to remove the `.deb` suffix from filename, along with `?view=names` and then it worked fine. All the local filenames were without `.deb` suffix too, which might still be problem with PR #2067 (if I understand correctly what it does).
> 
Hmm just from your description I assume you directly removed the ".deb"
suffix from the "fname" variable, right? Something like this should
do the trick:

diff --git a/dist/obs_mirror_project b/dist/obs_mirror_project
index 7cfe49a..022d7cf 100755
--- a/dist/obs_mirror_project
+++ b/dist/obs_mirror_project
@@ -225,6 +225,7 @@ puts ""
 filelist = Document.new(process)
 filelist.elements.each("binarylist/binary") { |binary| 
   fname  = binary.attributes["filename"]
+  binname = fname.sub(/\.[^.]+$/, '')
   fsize  = binary.attributes["size"]
   fmtime = binary.attributes["mtime"]
   puts "Process: #{fname} (#{fsize})"
@@ -254,13 +255,13 @@ filelist.elements.each("binarylist/binary") { |binary|
   end
 
   puts "  download:
-  osc -A #{apiurl} api -m GET /build/#{proj}/#{repo}/#{arch}/_repository/#{fname} > #{dest}/build/#{proj}/#{repo}/#{arch}/:full/#{fname}" if verbose
+  osc -A #{apiurl} api -m GET /build/#{proj}/#{repo}/#{arch}/_repository/#{binname} > #{dest}/build/#{proj}/#{repo}/#{arch}/:full/#{fname}" if verbose
   if trialrun
     puts "  trialrun: skip download"
   else
     # re-try download 3 times
     for i in 0..2
-      unless system("osc -A #{apiurl} api -m GET /build/#{proj}/#{repo}/#{arch}/_repository/#{fname} > #{dest}/build/#{proj}/#{repo}/#{arch}/:full/#{fname}")
+      unless system("osc -A #{apiurl} api -m GET /build/#{proj}/#{repo}/#{arch}/_repository/#{binname} > #{dest}/build/#{proj}/#{repo}/#{arch}/:full/#{fname}")
         puts "  retry #{i}: download failure" if verbose
         puts "  failure: download failure" if i == 2
         next

**Comment by tuminoid** [comment]
I was rather wondering does PR #2067 remove suffix from the binarylist xml, so the `obs_mirror_project` can no longer do workaround like this.

**Comment by marcus-h** [comment]
On 2016-08-26 04:46:08 -0700, Tuomo Tanskanen wrote:
> I was rather wondering does PR #2067 remove suffix from the binarylist xml, so the `obs_mirror_project` can no longer do workaround like this. 
> 
No. The binarylist is generated by the "getbinarylist_repository" function.
PR #2067 only changes "getbinary_repository" (it just adds an additional
lookup for a dod package), which is used to deliver the requested binary.

**Comment by tuminoid** [comment]
Ok, sorry for the noise then :)

**Comment by adrianschroeter** [comment]
Seems to be solved
