### ISSUE TITLE
bs_request_counter not set correctly after updating to OBS 2.7.1

### ISSUE THREAD

**Issue by srinidhibs** [openSUSE/open-build-service#2068]
Post migrating to OBS 2.7.1, we were not able to submit any packages. In production.log, we saw:

``
ActiveRecord::RecordNotUnique (Mysql2::Error: Duplicate entry '14370' for key 'index_bs_requests_on_number': INSERT INTO `bs_requests` (`state`, `commenter`, `creator`, `description`, `updated_at`, `number`, `created_at`) VALUES ('...
``

After digging around a bit, I found that `assign_number` method from src/api/app/models/bs_request.rb:

```ruby
  def assign_number
     return if self.number
     # to assign a unique and steady incremental number. Using MySQL auto-increment
     # mechanism is not working on clusters.
     sql = BsRequest.connection
     r = sql.execute("SELECT counter FROM bs_request_counter FOR UPDATE").first
     if r.nil?
     ...
     end

     # do an atomic increase of counter
     sql.execute("UPDATE bs_request_counter SET counter = counter+1")
     self.number = r[0]
  end
```

The last line `self.number = r[0]` suggests that `counter` column of `bs_request_counter` should contain the number which will be used for **next** submit request. But looking at [20160321105300_request_counter.rb](https://github.com/openSUSE/open-build-service/blob/master/src/api/db/migrate/20160321105300_request_counter.rb) migration has:

```ruby
class RequestCounter < ActiveRecord::Migration
  def self.up
    ...
    
    # set counter
    lastreq = BsRequest.all.order(:id).last
    if lastreq
      BsRequest.connection.execute "INSERT INTO bs_request_counter(counter) VALUES('#{lastreq.id}')"
    end
  end
...
end
```

In our case, this caused `bs_request_counter` to contain the last request ID in our system. Hence, raising `ActiveRecord::RecordNotUnique` exception.

I had to use Rails console to manually increment the `counter` column of `bs_request_counter` table to resolve this issue.

**Comment by bgeuken** [comment]
Solved with new 2.7 release
