### ISSUE TITLE
Name "Build::Kiwi::urlmapper" used only once: possible typo at ./bs_worker line 2490.

### ISSUE THREAD

**Issue by srinidhibs** [openSUSE/open-build-service#2084]
In OBS 2.7, when starting workers, following message is printed:

    Name "Build::Kiwi::urlmapper" used only once: possible typo at ./bs_worker line 2490.

Would this cause any feature to not work?

**Comment by M0ses** [comment]
This is only a warning as the perl interpreter assumes a typo. $urlmapper  gets defined in   
build/Build/Kiwi.pm line 27
`our $urlmapper;` 
and is also used below
