### ISSUE TITLE
_service:download_url:*.tar.bz2 is not deleted although the _service is gone

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#2085]
See https://build.opensuse.org/package/show/games/astromenace which is especially annoying as https://build.opensuse.org/request/show/423509 bots decline submissions because of this bug.

**Comment by Mailaender** [comment]
Yet another case: https://build.opensuse.org/request/show/423720
```
osc --version
0.155.0
```

**Comment by hennevogel** [comment]
Deleting a service will not delete it's result and it shouldn't...

**Comment by adrianschroeter** [comment]
deleting a service must delete the result, but you still have it defined on project level...

**Comment by Mailaender** [comment]
Do we need to and something to https://build.opensuse.org/project/prjconf/games then?

**Comment by Mailaender** [comment]
Note: https://build.opensuse.org/package/show/games/astromenace the bogus _service tarball has no delete button so this is still a blocker for me.
