### ISSUE TITLE
Clicking (xx tasks) which then becomes Home of $Username loads very slowly

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#2086]
https://build.opensuse.org/user/show/Mailaender has a very slow response time. This seems to be independent from how many tasks a user has and it is also slow outside the rush hours. As it is the most important view, it might pay off to optimize it or separate it.

**Comment by hennevogel** [comment]
This is not independent of the number of requests as you can see when you look at someone else [user page](https://build.opensuse.org/user/show/hennevogel). It also depends on caching, a second request is faster. However you are right that this is something that should be more optimized...

**Comment by hennevogel** [comment]
Tracked in #2201 now
