### ISSUE TITLE
Change xUbuntu to Ubuntu

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/open-build-service#2089]
Here is already a distro named "[Xubuntu](http://xubuntu.org/)" so the **xUbuntu** in OBS may confuse some people like me. If we call these Ubuntu, then every one knows without misunderstanding.

Reasons:

1. Here is already a "[Xubuntu](http://xubuntu.org/)" distro.
2. Not all ubuntu based distros call "xUbuntu", like Linux mint, elementary OS, Ubuntu GNOME.
3. The term "xUbuntu" is not well known. I never heard this before.

**Comment by adrianschroeter** [comment]
we need a term which matches all the ubuntu flavors, including KUbuntu, EduBuntu and friends. Or other people will be confused how they can build for them. (Ubuntu has AFAIK no real name for the code stream vs product shipment).

I am open for a different name, but it must be clear that all spins are supported.

**Comment by guoyunhe** [comment]
How about:

1. Ubuntu_Family
2. Ubuntu_And_Flavours

On the OBS website, you can just add some text to tell that OBS supports Kubuntu, Lubuntu, etc. But if it uses xUbuntu, people may think that it only support the Ubuntu flavour Xubuntu. The name is almost same.

I think any name is better than xUbuntu.

**Comment by zyx** [comment]
I know this issue has been closed, but I also find the xUbuntu terminology extremely confusing. Relying on mere capitalization to distinguish two different concepts is practically _asking_ for confusion.
