### ISSUE TITLE
chroot worker changes machine firewall rules

### ISSUE THREAD

**Issue by luizluca** [openSUSE/open-build-service#2103]
Hello,

I have a small OBS installation where workers uses OBS_VM_TYPE="none". On this system, I have problems with firewall when a RPM package is build. The package contains this call on post/postun:

`rcSuSEfirewall2 try-restart || :`

The result is that main machine firewall is reloaded with empty rules (from the chroot env). The same happens with "osc build". Would it be possible to avoid iptables changes? ip netns?

**Comment by lethliel** [comment]
chroot is a non secure build environment. Please use either KVM or XEN to prevent this behavior. (this is a linux limitation. Not an obs one)
