### ISSUE TITLE
May I contribute service scripts for Ubuntu?

### ISSUE THREAD

**Issue by myungjoo** [openSUSE/open-build-service#2111]
I have been running OBS in my Ubuntu 14.04 machine and some collegues are going to use OBS in 16.04.

However, the current OBS mainline does not have service scripts (i.e., dist/* ) for Ubuntu 14.04 (I didn't investigate whether they (the current dist/*) are compatible with 16.04, yet).

I would like to upload the service scripts for Ubuntu in this git repo (and my collegues want to use it via github.com/openSUSE, not via my persional git).

If I may share such files, may I simply create `dist/ubuntu/` and put service files there?

**Comment by adrianschroeter** [comment]
Yes, but please as pull requests to git master.

Please use our mailing list opensuse-buildservice@opensuse.org for questions like this and for coordination. The issues on github are supposed for tracking existing problems. 

thanks!

**Comment by adrianschroeter** [comment]
In case you provide ubuntu build descriptions we can also enable the build for obs server for ubuntu. But that means someone needs also to package all the dependencies (esp. the rubygems).

**Comment by leemgs** [comment]
FYI. Please, refer to https://tracker.debian.org/pkg/open-build-service for Ubuntu/Debian distribution.
