### ISSUE TITLE
How to install obs 2.7 on Ubuntu 16.04 X64?

### ISSUE THREAD

**Issue by leemgs** [openSUSE/open-build-service#2113]
I have been trying to build obs 2.7 on Ubuntu 16.04 X64. I seems that we need to apply for some patches to support Ubuntu 16.04 X64 distribution as well as OpenSUSE 12/13 distribution. I have got the some build errors in case that I tried to execute "make install" command on Ubuntu 16.04. Below is  how to build obs 2.7 on Ubuntu 16.04 X64. (**In progress**)

###  Method1: How to use  'make'  and apache2

* 0. install prerequisites

```
sudo apt update
sudo apt install build-essential
sudo apt install perl libjson-xs-perl libsocket-msghdr-perl libbssolv-perl libfile-sync-perl libmodule-build-perl
sudo apt install ruby ruby-dev libldap2-dev ruby-bundler ruby-rails rake 

sudo apt install mysql-server libmysqlclient-dev
sudo apt install libsasl2-dev libxslt1-dev
sudo apt install memcached
```

* 1. Let's synchronize the script languages's version for obs 2.7. 

```
u16.04$> sudo ln -s /usr/bin/rake    /usr/bin/rake.ruby2.3
u16.04$> sudo ln -s /usr/bin/rails   /usr/bin/rails.ruby2.3
u16.04$> sudo ln -s /usr/bin/ruby    /usr/bin/ruby.ruby2.3
```

* 2. Let's to apply the below patches for Ubuntu 16.04

```
diff --git a/Makefile b/Makefile
index 8f48f47..e9f4eed 100644
--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,4 @@
-all:
+apidocs:
        make -C docs/api/api apidocs
 
 install:
```

* 3. Let's try to run "make" command
```
u16.04$> make apidocs
u16.04$> make install 
```

### Method2: How to use standalone rake server

* 1. Starting OBS back-end (written by perl): 
```
#Back-end Source Server(5352) , Repository Server (5252)
cd src/backend
cp BSConfig.pm.template BSConfig.pm
su -c ./bs_srcserver
su -c ./bs_repserver
```

* 2. Starting OBS front-end (wirtten by Ruby on Rails)
```
cd ../../
cd src/api
cp config/database.yml.example config/database.yml
cp config/options.yml.example  config/options.yml
bundle install
sudo gem install rdoc-data 
sudo rdoc-data --install 
# Executing rake inside the bundle using bundle exec
bundle exec rake db:setup    ( or rake db:setup)
```

* 3.  run rails server (standalone web service)
```
# Start the rails server in a different port using "rails s -p <port number>" command instead of just "rails s
rails s -p 4000
firefox http://myobs.mooo.com:4000/   (id: Admin, password: opensuse)
```

**Comment by leemgs** [comment]
\CC: @myungjoo

**Comment by adrianschroeter** [comment]
Thanks a lot for trying to get OBS server on further systems. However, we (as existing development team) won't put much effort here due to our SUSE focus. However, we are happy to take pull requests with adaptions for further distros. But please create these pull request to git master branch first, we can consider a backport afterwards.

**Comment by leemgs** [comment]
> But please create these pull request to git master branch first, we can consider a backport afterwards.

Yes. I will submit a PR as soon as I completely evaluate the normal operation of OBS on Ubuntu 16.04.
