### ISSUE TITLE
Enable contrib & non-free for Debian 8

### ISSUE THREAD

**Issue by Sunderland93** [openSUSE/open-build-service#2114]
Hello. It is possible to enable Contrib and Non-Free repositories for Debian 8 project? Here is my home project https://build.opensuse.org/project/show/home:Sunderland93

**Comment by hennevogel** [comment]
Please ask questions about using the openSUSE instance on the [openSUSE mailinglist](mailto:opensuse-buildservice@opensuse.org) and not here.  Thanks
