### ISSUE TITLE
Services prefer _service file of unmerged sources over the one from merged sources

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#2115]
I've branched a package that has a _service file. After that the sources of the original package got updated (version changed from 1.1.1 to 1.1.2). My branched (and merged) _service file also got updated to use version 1.1.2. Though running the services still created _service:download_url:prometheus-1.1.1.linux-amd64.tar.gz instead of the correct 1.1.2 one.

It seems _service files of unmerged sources are used when they are present.

**Comment by bgeuken** [comment]
Package can be found here: https://build.opensuse.org/package/show/home:bgeuken:branches:home:justlest:prometheus/prometheus

**Comment by adrianschroeter** [comment]
yes, this is on purpose. Triggereing all linking packages would just create too much load on obs and on the upstream servers.
