### ISSUE TITLE
webui can't handle .yaml suffixed files

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2125]
The webui fails showing source files with .yaml suffix.

Example:

 https://build.opensuse.org/package/view_file/home:adrianSuSE:snappy/git/snapcraft.yaml

**Comment by bgeuken** [comment]
Adrian pointed out that this might be a routing issue (having a .yaml or .yml suffix in the url). Might be a good starting point to investigate.

**Comment by bgeuken** [comment]
So it also happens with .json files.
