### ISSUE TITLE
webui does not show .txt files any more

### ISSUE THREAD

**Issue by afaerber** [openSUSE/open-build-service#2126]
Similar to #2125 but instead of an error just an empty page:

https://build.opensuse.org/package/view_file/hardware/raspberrypi-firmware/config-rpi3.txt?expand=1
https://build.opensuse.org/package/view_file/hardware/bcm43xx-firmware/brcmfmac43362-sdio-cubietruck.txt?expand=1

Other extensions such as .sh, .conf, .changes, .spec seem fine.

**Comment by bgeuken** [comment]
Thanks for the report. I'll close it as duplicate of #2125 though

**Comment by afaerber** [comment]
Confirming fixed. Thanks, Björn!
