### ISSUE TITLE
More information in build log view

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#2130]
When evaluating build failures I use the status view
https://build.opensuse.org/project/status/openSUSE:Leap:42.2

To to check whether it's a simple transient build fail that just needs retriggering I click on the build log. To be able to judge from there whether a rebuild is safe I need more information:
- whatdependson information to figure out what other packages might get triggered
- jobhistory to see how long the build will take and whether the package failed before

So would be nice if the build log view had tabs or links to show that information. Right now I have to use osc.

**Comment by ChrisBr** [comment]
@lnussel the whatdepends on is deployed to production. Please provide some feedback if this works for you...

**Comment by lnussel** [comment]
works for me. Maybe move it to the bottom since build log page scrolls there by default?

**Comment by lnussel** [comment]
close?

**Comment by ChrisBr** [comment]
yep
