### ISSUE TITLE
review state=new has no date

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#2132]
$ osc api /request/418553?withhistory=1
..
`<review state="new" by_package="blobwars" by_project="games">`
...
`
=> since there is no date it's hard to write a tool that reminds about open requests

**Comment by adrianschroeter** [comment]
Not so easy as it looks, since we need to take care about backward compability ... but using the created_at instead of updated_at for when attribute is a bug in any case

**Comment by bgeuken** [comment]
Just checked with a new request in build.opensuse.org. Seems that we are setting a when attribute now.
In addition #2379 ensures that a reasonable timestamp is used.
