### ISSUE TITLE
Description textfield of Submit Requests is too small

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#2134]
It would be good if one could increase the field, or the whole dialog.

**Comment by jesus-montano** [comment]
this issue refers to this?


![submit1](https://user-images.githubusercontent.com/48233860/57336406-01b46f00-70e3-11e9-9874-bb9e1dd24b2a.png)
![submit2](https://user-images.githubusercontent.com/48233860/57336417-0c6f0400-70e3-11e9-8f37-1b60ac1094ff.png)

**Comment by bgeuken** [comment]
No, that issue was about the old UI. And in both UIs the field can now be increased. Either this got solved meanwhile or I missed it back than.

=> closing
