### ISSUE TITLE
P0 to P4 labels for issues

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#2146]
In [CONTRIBUTING.md](https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md) it is said:

> We are using priority labels from P0 to P4 for our issues

But there are only **P1**, **P2** and **P3** [labels](https://github.com/openSUSE/open-build-service/labels). 

@hennevogel @adrianschroeter do I update the [CONTRIBUTING.md](https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md)? Or do we want to create the missing labels?

**Comment by adrianschroeter** [comment]
we can create P4 for unimportant bugs, but I don't think we have a usecase for P0.

We should maybe document the classification of them there though. It is from my POV:

 P1 - Critical issue. Interrupt other longer running work to fix it.
 P2 - Important issue. Should be scheduled soon.
 P3 - Normal issue.
 P4 - Less then normal issue. Take it in a lazy minute.

@bgeuken @ChrisBr @M0ses @Ana06 @mschnitzer @lethliel    does this make sense to you?

**Comment by adrianschroeter** [comment]
forget me .. I see we have a definition already :)

**Comment by adrianschroeter** [comment]
So, let's create a P4. We can also create a P0, but such things run usually outside of the normal workflows ....

**Comment by bgeuken** [comment]
Let's remove the p0 from the contribution doc. At least for me it's to much tight to a bugzilla p0, which we never will have.

**Comment by bgeuken** [comment]
We have a p4 label now

**Comment by Ana06** [comment]
I'll remove the P0 from the [CONTRIBUTING.md](https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md) then.
