### ISSUE TITLE
Observation with AppStream metadata

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#2148]
If I remember correctly, the AppStream producing code for OBS has been updated to publish version 0.8 metadata (with an origin entry)

Looking at for example
http://download.opensuse.org/repositories/GNOME:/Apps/openSUSE_Factory/repodata/5a534a7e6ad5106e31deba43c6454f0855ff8728523020474d94015f3fb7d8b3-appdata.xml.gz (link will be invalud shortly, update the hash as needed) shows that this is correct and that file starts with:

```
<?xml version="1.0" encoding="UTF-8"?>
<components origin="appdata" version="0.8">

```

If one is to check an appdata inside repositories/home: though, this is not the case
e.g.: http://download.opensuse.org/repositories/home:/darix:/darktable:/master/openSUSE_Tumbleweed/repodata/b8a796d7f3ee1692f1eb02aca528390937ba4bec782d2301e44accb726227413-appdata.xml.gz (again, hash will be changing)

```
<?xml version="1.0" encoding="UTF-8"?>
<components version="0.6">
```

**Comment by mlschroe** [comment]
The version/origin is taken from the first collected element. For the darktable project, there are no elements, thus the version defaults to 0.6. We probably should not write a appdata file in that case, would that work for you?

**Comment by mlschroe** [comment]
hmm, actually there is a darktable.appdata.xml file, but it doesn't end in the generated repo metadata. Investigating...

**Comment by mlschroe** [comment]
Oh my. The new .appdata.xml files no longer have an enclosing <components> element. You've got to be kidding me!

**Comment by mlschroe** [comment]
(This also means no version info. This sucks.)

**Comment by mlschroe** [comment]
What do you do if a package contains more than one component?

**Comment by mlschroe** [comment]
Eeek. You just concatenate. See feeciv-gtk3. That's not even valid xml! Please fix your tool!

**Comment by mlschroe** [comment]
(In the meantime I've added a workaround to the publisher so that we get at least some appdata info. But that won't help with packages like freeciv-gtk3.)
