### ISSUE TITLE
Git services ran in parallel it seems

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#2156]
In https://build.opensuse.org/package/revisions/devel:openQA/openQA you can see that something triggers always 2 commits per github action (let's assume github triggers the action twice for whatever reason). But what happens is that the sources get broken by this as there seem to be 2 gits running in parallel:

Files could not be expanded: Command failed(1): "From git://github.com/os-autoinst/openQA\n - [deleted] (none) -> origin/auto_duplicate_double_grabs\nerror: cannot lock ref 'refs/remotes/origin/master': Unable to create '/var/cache/obs/7dfStqRQ1y1f/git-cache/openQA.git/.git/refs/remotes/origin/master.lock': File exists.\n\nAnother git process seems to be running in this repository, e.g.\nan editor opened by 'git commit'. Please make sure all processes\nare terminated then try again. If it still fails, a git process\nmay have crashed in this repository earlier:\nremove the file manually to continue.\n ! eecfa04..0b78fc5 master -> origin/master (unable to update local ref)\n"

**Comment by adrianschroeter** [comment]
hm, even when there are multiple runs it should not fail IMHO. second process should wait and continue...
Frank, any opinion?

(this is actually more an issue for obs-service-tar_scm then obs)

**Comment by M0ses** [comment]
hmm, we tested it and it worked well. But maybe this behavior changed with git version updates. I will take care of it.

**Comment by M0ses** [comment]
@coolo Have you seen this error often?

**Comment by M0ses** [comment]
This is not a open-build-service problem - this is a problem in obs-service-tar_scm - which should be fixed with the new refactored code:

https://github.com/M0ses/obs-service-tar_scm/commits/nextRev

which locks the repositories.
