### ISSUE TITLE
/monitor graph error on Ubuntu 16.04

### ISSUE THREAD

**Issue by leemgs** [openSUSE/open-build-service#2161]
I have recently installed the latest version of OBS on Ubuntu 16.04 LTS X64.  However, I met the error from the https://192.168.1.2:4434/monitor such as the below picture. Anyone know a package name that  generates the monitoring image in https://192.168.1.2:4434/monitor webpage? It will be helpful to me in order to generate the image normally on Ubuntu 16.04. 

![monitor-obs](https://cloud.githubusercontent.com/assets/82404/18672117/c49ff882-7f81-11e6-9720-4e45d87645bb.jpg)

**Comment by adrianschroeter** [comment]
It seems your background (obsdelayedjobs) are not running. Sorry, but we have currently no one taking care about installations on non SUSE systems of OBS.

**Comment by leemgs** [comment]
> It seems your background (obsdelayedjobs) are not runnin

Thank you so much. I have solved the issue thanks to your hint. 

Below is my solution for ubuntu 16.04.
First, modify /etc/init.d/obsapidelayed appropriately. 
Second,  install "libgd-graph-perlpackage" package
Third, change default script from dash to bash
