### ISSUE TITLE
Rename "branch package" to "fork package"

### ISSUE THREAD

**Issue by techtonik** [openSUSE/open-build-service#2170]
Fork becase more or less common verb for that https://en.wikipedia.org/wiki/Fork_(software_development)

**Comment by bgeuken** [comment]
Not sure if we want to change this, given that OBS users are used to that terminology. And it's not that uncommen either.

**Comment by mmohring** [comment]
Branch is also common, in the sense of revision control branching https://en.wikipedia.org/wiki/Branching_(version_control) it is even more common.

**Comment by techtonik** [comment]
Yes, but branching is specific feature for version control, and there is no version control here, right? I can not checkout and branch OBS files to test them offline. And usually in Git you "create a branch in a project" locally, but when you actually copy in under different name, it is "fork of a project".

**Comment by baby-gnu** [comment]
> And usually in Git you "create a branch in a project" locally, but when you actually copy in under different name, it is "fork of a project".

Bzr and launchpad use the branch terminology.

I always found “fork” very rude, you fork a project when you can't work with its community for whatever reason (I think about OpenOffice/LibreOffice, MySQL/MariaDB), I personally dislike the use of “fork” on github.

Regards.

**Comment by techtonik** [comment]
Right. It is not possible to merge OBS branches back, isn't it?

**Comment by baby-gnu** [comment]
According to http://vimeo.com/30845184 you can submit your branch back.

**Comment by hennevogel** [comment]
We gain nothing from rewording this and, as other have explained, 'branch' is also a correct term. Sorry but we have more pressing things to do that bring more value for our users.

Thanks for your report anyway :-)
