### ISSUE TITLE
On branch confirmation dialog, show what exactly will happen

### ISSUE THREAD

**Issue by techtonik** [openSUSE/open-build-service#2171]
It is strange to see confirmation dialog as if I am not forking it into my own home dir that is for experiments. It would be nice to see some info where this will be forked.

**Comment by bgeuken** [comment]
@techtonik You want to see where a package is going to be branched, if you do so? Or are you talking of a missing status message after a package got branched happened?

**Comment by techtonik** [comment]
I want to see where a package will be forked, yes, like in GitHub. I don't remember missing any status messages.
