### ISSUE TITLE
On repository removal, show full path in dialog

### ISSUE THREAD

**Issue by techtonik** [openSUSE/open-build-service#2172]
When repository is removed, dialog proposes to remove repository 'openSUSE_13.1' and it is unclear if it will be removed from my home or from forked project as well.

**Comment by adrianschroeter** [comment]
forked projects will break, but repos not removed there, since you don't have write access there usually.

**Comment by techtonik** [comment]
If repo won't be removed from forked projects, why they'll break?

**Comment by eduardoj** [comment]
Since the migration of the repositories page into the new web UI in #6471, the user now has the ability to delete either the whole repository or only a path. @techtonik can you please check if this issue still applies?

**Comment by techtonik** [comment]
I am not sure what my use case was. Right now repo removal looks like this:

![image](https://user-images.githubusercontent.com/515889/63691891-11ce9680-c819-11e9-8d12-8cba6b595373.png)

I am closing this, because I don't use OBS and can not give more info.
