### ISSUE TITLE
Move monitor to independent infrastructure

### ISSUE THREAD

**Issue by techtonik** [openSUSE/open-build-service#2173]
https://build.opensuse.org/monitor now shows this:
```
<status code="maintainance">
<summary>
Sorry, api.opensuse.org is down at the moment. If the situation persists, check the opensuse-buildservice@opensuse.org mailinglist.
</summary>
<details/>
</status>
```
Together will all site pages. Usually status pages are placed on separate domains/server to explains and track maintenance windows and outages https://status.github.com/

**Comment by adrianschroeter** [comment]
This is not OBS code related, since this the fallback page of the http proxy. the content is a pure lie though, it is not a planned maintenance, but some internal bug.

**Comment by techtonik** [comment]
So your recommendation is to ignore that, or there is some better place to report the issue?
