### ISSUE TITLE
Problems with services after switching to docker (cleanup/locking/permissions)

### ISSUE THREAD

**Issue by M0ses** [openSUSE/open-build-service#2180]
Currently there are three major Problems with the "services in docker" implementation
1. Different ownership in shared volumes. (workaround)
2. No locking of cache directories.
3. Cleanup of docker containers seems not to work reliable (happens again)
4. home dir for user obsservicerun is not created in docker container but needed for source_validator.

**Comment by M0ses** [comment]
About 1.:

All directories with wrong ownership had  the date 10/24/2016. I fixed the ownership in the cache directory an ran a service again. The newly created directory had the right permissions, so I think this where only some leftovers from yesterday

**Comment by M0ses** [comment]
```
Files could not be expanded: error: failed to create directory %{_topdir}: /home/obsservicerun/rpmbuild: Permission denied 
```

**Comment by aspiers** [comment]
Maybe worth splitting these into separate issues?

**Comment by M0ses** [comment]
@aspiers ATM its easier for me to keep track in one issue - maybe I will split out the locking issue and link it here

**Comment by M0ses** [comment]
About 1.: Should be fixed with

https://github.com/openSUSE/open-build-service/pull/2182

**Comment by M0ses** [comment]
About 2. https://github.com/M0ses/obs-service-tar_scm/commit/a0ff93810a1e07685ccb9ab773b80d43d7f9aa10

About 3. https://github.com/openSUSE/open-build-service/issues/2166

About 4. fixed in new docker containers
