### ISSUE TITLE
Reuse debian/ files from source distribution

### ISSUE THREAD

**Issue by techtonik** [openSUSE/open-build-service#2181]
https://github.com/haecker-felix/gradio already got all necessary `debian/` files.

But I don't see how to reuse them from:
https://en.opensuse.org/openSUSE:Build_Service_Debian_builds

It looks like they should recommitted anew. It would be nice it OBS could detect those file from archives and show that it will use them (if Debian based target is added). In particular, the file list could contain entries:
```
v4.0.1.tar.gz/debian/control
v4.0.1.tar.gz/debian/rules
```
with last parts of path grayed out to show that these files are non-editable and are inside of the archive.

**Comment by Conan-Kudo** [comment]
@techtonik You can use a source service to extract all files in the debian/ subdir. Then OBS will use it automatically, I think.

**Comment by hennevogel** [comment]
It will. Please ask question about using the OBS on the mailinglist and not here in the issues...

**Comment by techtonik** [comment]
@Conan-Kudo why OBS don't do this automatically?
