### ISSUE TITLE
Error 500 when trying to delete packages

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#2185]
https://build.opensuse.org/package/remove/home:Mailaender:branches:Java:packages/aether Trying to clean up as suggested in https://bugzilla.opensuse.org/show_bug.cgi?id=963323#c11 but the interface is buggy and won't let me.

**Comment by mschnitzer** [comment]
@Mailaender is this still valid?

**Comment by Mailaender** [comment]
No, I guess this may be related to the general performance problems of the build.opensuse.org installation and not a reproducible error.
