### ISSUE TITLE
Status page

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#2186]
To check whether parts of it's infrastructure are down (and when they may be available again) also metrics like API response time as shown on https://status.github.com/ might be interesting, because it feels super slow at times and I would like to know if there are rush hours to avoid.

**Comment by hennevogel** [comment]
We are already using a (HA) proxy in front of the server that will tell you when something behind it is down. I doubt that rush ours will be because of API response times but because of many builds which you can track at the bottom of https://build.opensuse.org/monitor...

**Comment by hennevogel** [comment]
Okay, I guess this is enough for you. If not please tell us :-)

**Comment by Mailaender** [comment]
Okay, I didn't know that lot's of builds on OBS also effect the local `osc build` commands etc. but that makes sense as those also query the same API I guess.
