### ISSUE TITLE
Hardcoded url to software.opensuse.org

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2190]
The webui shows on all installations a "Download package" URL to software.opensuse.org. Since instances beside build.opensuse.org don't have a software.o.o installation we need either to adapt the URL or don't show the link there.

The code is in:

 src/api/app/views/webui/theme/bento/webui/package/_extra_actions.html.erb

**Comment by smithfarm** [comment]
This just bit me today.

**Comment by bgeuken** [comment]
Fixed with #2698
