### ISSUE TITLE
binary built for fedora gives "Illegal instruction"

### ISSUE THREAD

**Issue by bill-auger** [openSUSE/open-build-service#2194]
i have a problem building for fedora for a few weeks now - running the binary gives "Illegal instruction (core dumped)"

the opensuse package built from the same tarball and .spec file still are ok as well as the arch and deb packages

the application itself compiles and runs fine on a fedora system so i am now trying to get osc to package a debug build but i can not get fedora packages to build locally with osc (issue #2195)

**Comment by bill-auger** [comment]
ok i can not explain this but today i clicked on "trigger rebuild" on the build log web page and the rebuilt package is working

**Comment by lethliel** [comment]
ok. If it works again this issue will be closed.

**Comment by bill-auger** [comment]
yes i left this open just in case anyone wanted to follow up on it and because i plan to rebuild again in a few days - i was intending to close the issue then if everything is still good
