### ISSUE TITLE
[production][webui/repositories#index] NoMethodError: undefined method `each_with_index' for nil:NilClass

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2200]
webui/repositories#index threw this 0 times

<pre>
NoMethodError: undefined method `each_with_index&#39; for nil:NilClass
</pre>

[https://build.opensuse.org/repositories/home:cschweingruber](https://build.opensuse.org/repositories/home:cschweingruber)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/57f51e4acd53000006000000)

**Comment by bgeuken** [comment]
The old errbit link isn't working anymore. Here is a new one: https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/599a18743853dc00066713e1

**Comment by bgeuken** [comment]
Still happening: http://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/599a18743853dc00066713e1

**Comment by eduardoj** [comment]
Already checked that this isn't logged in Errbit any more in the last year. Please reopen if it happens again.
