### ISSUE TITLE
Horrible performance: User page takes 66 seconds to load

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#2201]
Practically I can't open my request list - it's consistently _very_ slow. the inital get of /user/show/coolo takes 66 seconds.

And even user/show/dimstar (which does not show any requests) loads 11 seconds. This needs fixing!

**Comment by coolo** [comment]
this morning it took woooping 156 seconds to load. I practically can't work at all ;(

**Comment by bgeuken** [comment]
@mdeniz Could you have a look at this?

I will do as well, once I am in the office. Though I fear this won't be an adhoc fix, but a rewrite of how we fetch requests for users. So it might take a few days. Unless there is a bug hidden somewhere;-)

**Comment by mdeniz** [comment]
Ok, I will

**Comment by bgeuken** [comment]
So, apparently the All requests tab also stopped working. Users will just see 'No results'.

Coolo also told me that some vm the code is running on (api?) was under heavy load when he checked it. Might also add to the slowness.

**Comment by bgeuken** [comment]
I did an rcapache2 reload now and the page load for my user is down to 10 seconds (Coolo added me to the d:l:r:e maintainers).
'All requests' tab obviously still broken and we might want refactor how we handle those data. @adrianschroeter ?

Things that would come to my mind would be eg. using pagination, caching, enhance SQL queries, ... ?

**Comment by adrianschroeter** [comment]
IMHO the approach to offer "All Requests" in a view is just a workaround for other lacking functionalities.

People use it to learn what happened to their requests, but this should get handled different from my POV. 

However, I would suggest to drop the "All Requests" tab in first place to verify that this is really the root cause of the problem. We need to think how to handle the usecase "to see my last processed requests" in a better way then. Or load it only on request, but not by default on the "my work" page.

I would also verify that the backend got not involved in that page in the meantime (maybe due to some refactoring).

**Comment by coolo** [comment]
there is another problem anyway - 'all requests' is empty. Not knowing for how long though, as I never used this tab. So if noone noticed this so far, that tab can't be that important :)

**Comment by bgeuken** [comment]
Well, it can't be that long since I checked that one durning the rails 5 upgrade. And I always used that one when I looked up older (closed) SRs.

**Comment by coolo** [comment]
just to keep you informed. After the hot removal of the build status icon, the page seems to be easier to cache. I have now on first fetch this morning 60 seconds and on second try 10.5 seconds. It's still slow though

**Comment by mschnitzer** [comment]
As a first step, we removed the build results icon from the requests table: https://github.com/openSUSE/open-build-service/pull/2260

**Comment by coolo** [comment]
Just to keep you uptodate now that #2260 is officially deployed: 36 seconds on first run, 27 on reload

**Comment by mdeniz** [comment]
Nice we will improve that with the server side pagination #2269 :smile:

**Comment by coolo** [comment]
I'm now at 21 seconds on first load, 5 seconds on reload. I'm afraid this is considered normal OBS performance :(

**Comment by coolo** [comment]
I'm back to 38 seconds. What did you do? ;(
