### ISSUE TITLE
bs_service trites to chown /srv and /srv/obs

### ISSUE THREAD

**Issue by Artox** [openSUSE/open-build-service#2213]
When running the obs source service without root privileges, I encounter this error int the log preventing startup:
failed to chown /srv/obs to 498:496
unable to create /srv/obs

EDIT: apparently I didn't trace it, something evil is going on

**Comment by adrianschroeter** [comment]
Please tell us also how you deployed your instance.

**Comment by Artox** [comment]
> Please tell us also how you deployed your instance.
it is inside a docker container, that still needs some work. It should be reproducible by running
`sudo -u obsservicerun /usr/lib/obs/server/bs_service`

**Comment by adrianschroeter** [comment]
and this docker container is  created using our packages? OBS 2.7 ones? which base distro?

sudo is not a supported start method for these services.

**Comment by Artox** [comment]
> and this docker container is created using our packages?

Its been a while but I got around to this once more.
So this is inside a opensuse 42.2 docker container where the obs-2.8 packages are installed.
This is how bs_repserver is launched:
```
[program:bs_repserver]
command=/usr/lib/obs/server/bs_repserver
stdout_logfile=/srv/obs/log/rep_server.log
redirect_stderr=true
user=obsrun
```

And at some point that applications tries to chown outside of its work place:
failed to chown /srv/obs to 495:493
failed to chown /srv/obs to 495:493
unable to create /srv/obs

> sudo is not a supported start method for these services.
Right. Reading a comment at the end of bs_repserver:
# create bsdir before root privileges are dropped

So I guess thats a safety measure to make sure folders exist.
And this way it has to be started as root, not obsrun.

**Comment by pseiler** [comment]
@adrianschroeter I faced a similiar issue. I installed OBS 2.10 on a SLES15 SP1 with the preferred repository and the installer ```/usr/lib/obs/server/setup-appliance.sh --force```

After this _obsservice.service_ didn't want to start because of missing directory rights.
This was in the log:
```cannot write to rundir '/srv/obs/run'```

I had to do ```chmod g+w :/srv/obs/run``` to get it working.

The reason is that the user _obsservicerun_ had no write rights at _/srv/obs/run_ directory.

**Comment by adrianschroeter** [comment]
@M0ses IIRC you fixed that latetly, right?

**Comment by M0ses** [comment]
@adrianschroeter This commit should fix it 
https://github.com/openSUSE/open-build-service/commit/4ccba50040

**Comment by adrianschroeter** [comment]
On Dienstag, 10. Dezember 2019, 10:31:49 CET Frank Schreiner wrote:
> @adrianschroeter This commit should fix it 
> https://github.com/openSUSE/open-build-service/commit/4ccba50040

ah, already backported to 2.10 branch ..

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer
