### ISSUE TITLE
Database dead lock on project creation

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2217]
source#update_project_meta threw this 2 times

<pre>
Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction
</pre>

[https://api.opensuse.org/source/home:suse-cloud-ci:rpm-packaging-sles12-Newton-d0af323e427dc47959d8443e511ae86b38ac4d5e/_meta](https://api.opensuse.org/source/home:suse-cloud-ci:rpm-packaging-sles12-Newton-d0af323e427dc47959d8443e511ae86b38ac4d5e/_meta)"

[See this exception on Errbit](http://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/57f123dcae616e0009000000)

**Comment by adrianschroeter** [comment]
We crash quite a lot due to database deadlocks. It seems this is new since 1-2 weeks. The linked issue is just an example, you can find many more dead lock crashes on repository modification operations.

This is currently blocking automated testing infrastructure.

**Comment by hennevogel** [comment]
@adrianschroeter which automated testing infrastructure?

**Comment by hennevogel** [comment]
@adrianschroeter and how is this new? We have a lot of deadlocks since quite some time...

**Comment by bgeuken** [comment]
IIRC we tackled that back then. Right now there is just one deadlock tracked in errbit (in active job).
