### ISSUE TITLE
[production][webui/request#set_incident] NameError: uninitialized constant Webui::RequestController::APIExcetion
Did you mean?  APIException

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#2221]
webui/request#set_incident threw this 0 times
<pre>
NameError: uninitialized constant Webui::RequestController::APIExcetion
Did you mean?  APIException
</pre>
[https://build.opensuse.org/request/set_incident](https://build.opensuse.org/request/set_incident)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/57fbadb7cc218f0009000000)

**Comment by bgeuken** [comment]
Fixed by Adrian in 8751e3c6e10dba4df0f8afdc56aed1ecab53ee28
