### ISSUE TITLE
How status icon of obs services  is generated in  ./monitor?

### ISSUE THREAD

**Issue by leemgs** [openSUSE/open-build-service#2226]
I can not suddenly see some icons (e.g., repserver, srcserver) to monitor the obs services activity after updating the existing /usr/lib/obs/ using the up-to-date obs version in order to evaluate the latest features. I want to know  how  this icons are showed in ./monitor webpage. Anyone that can give me a hint to solve this issue? 

![obs-service-normal2](https://cloud.githubusercontent.com/assets/82404/19260431/603dd726-8fc4-11e6-8a2e-0f31259cf694.jpg)

**Comment by adrianschroeter** [comment]
It is a feature for OBS 2.8. It is not available in current stable OBS 2.7.

**Comment by adrianschroeter** [comment]
Please don't open tickets for such support question, but use our opensuse-buildservice@opensuse.org mailing list (or IRC) instead.
