### ISSUE TITLE
web interface does not allow to show/edit .changes

### ISSUE THREAD

**Issue by hramrach** [openSUSE/open-build-service#2227]
at https://build.suse.de/package/show/home:michals:SLE11-SP4/kernel-source
the .changes files uploaded by osc do not have the link to view/edit the file.

There is a link to download which returns a file of some type not recognized by Firefox (probably application/octet-stream - firefox says it's a BIN file).

This means it's pretty much impossible to view the file directly in the web browser. 

As a workaround you can download it an view it locally or install some browser hack to view files of unrecognized types.

**Comment by hennevogel** [comment]
This is not a problem with the OBS but with the content therein. Please contact your SUSE OBS admins. If you don't know how you can contact me at hvogel@suse.com and I will tell you :-)

**Comment by hramrach** [comment]
Actually, it's a problem with OBS or its settings.

.changes is commonly uploaded to OBS so it should know to treat it as text

The file itself is fine
