### ISSUE TITLE
[webui] Request diff only shown for one package

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/open-build-service#2242]
Request maintenance submission request `436112` contains diffs in two packages.
`osc request show 436112 -d` shows the diffs.
The Web UI only shows one: https://build.opensuse.org/request/show/436112
This seems to be a regression over previous releases.

**Comment by hennevogel** [comment]
@adrianschroeter, @mlschroe some fallout from the diff/slot problems?

**Comment by adrianschroeter** [comment]
On Mittwoch, 2. November 2016, 10:09:58 CET wrote Henne Vogelsang:
> @adrianschroeter, @mlschroe some fallout from the diff/slot problems?

well, works for me also in the webui. Just that the webui has all diffs collapsed
in the second tap. And you need to click on them.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imend�rffer, Jane Smithard, Graham Norton, HRB 21284 (AG N�rnberg) 
 
Maxfeldstra�e 5                         
90409 N�rnberg 
Germany

**Comment by andreasstieger** [comment]
SR#436112 shows correctly now.
But here is a broken one: https://build.opensuse.org/request/show/438015
Two packages in request, only one tab shown.

**Comment by adrianschroeter** [comment]
I see ... given that it works for osc, it is more likely that it is a webui caching issue.

**Comment by hennevogel** [comment]
@adrianschroeter the diffs on the second tab for tor.changes/tor.spec are empty.

![screenshot from 2016-11-03 11-15-20](https://cloud.githubusercontent.com/assets/514785/19962187/d5699400-a1b6-11e6-943a-27f19c2048d7.png)

**Comment by hennevogel** [comment]
Same for [438015](https://build.opensuse.org/request/show/438015)...

**Comment by Vogtinator** [comment]
This seems to be even worse now, I created a maintenance request for several packages and it only shows one tab in the WebUI, so it seems like only one package is submitted: https://build.opensuse.org/request/show/439550

**Comment by hennevogel** [comment]
This is a codemirror problem. If you click into the field that should show you the patch, it'll appear....

**Comment by andreasstieger** [comment]
I would like to stress that this is **not** the previously problem where all the tabs would be present, just the code would not be folded from the second tab onwards. Instead, the tab is missing entirely!

See https://build.opensuse.org/request/show/441879

3 actions:

    maintenance_incident: home:adrianSuSE:branches:OBS_Maintained:libarchive/libarchive.openSUSE_13.2_Update@d1a52d5de4ad558acbbb0a0b1ec97b1a -> openSUSE:Maintenance (release in openSUSE:13.2:Update)
    maintenance_incident: home:adrianSuSE:branches:OBS_Maintained:libarchive/libarchive.openSUSE_Leap_42.1_Update@c21faf196ec4c9374b17567f4d748454 -> openSUSE:Maintenance (release in openSUSE:Leap:42.1:Update)
    maintenance_incident: home:adrianSuSE:branches:OBS_Maintained:libarchive/libarchive.openSUSE_Leap_42.2_Update@c11ac637c5d2edd7073a16d514446d0a -> openSUSE:Maintenance (release in openSUSE:Leap:42.2:Update)

Only one tab shown:

![screenshot_20161128_130306](https://cloud.githubusercontent.com/assets/2847525/20667721/0e8b754c-b56b-11e6-8699-cf8315769add.png)

**Comment by hennevogel** [comment]
This is because the tab is hidden when initializing the editor and therefor the diff area has no dimensions. Once the tab is shown the editor needs to be refreshed.

**Comment by hennevogel** [comment]
@andreasstieger yeah just following this down into the rabbit hole :-)

**Comment by hennevogel** [comment]
This is now also monkey patched on build.opensuse.org/build.suse.de

**Comment by DimStar77** [comment]
Adrian suggested I raise it here as a follow-up, as it might be related.

Sample: https://build.opensuse.org/request/show/442628

The shown 'diff' implies 2 patches added, one changed. In fact though there is on patch renamed, which means I should see also 'one patch deleted' (osc rq show -d does show it)

**Comment by hennevogel** [comment]
It's not related at all and the issue is now tracked in #2397
