### ISSUE TITLE
Package maintainer dialog is misleading when maintainers are submitting themselves

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#2253]
Many projects such as https://build.opensuse.org/project/show/science have a peer review system where 4 eyeballs are "required" (or at least desired) even if the submitter has maintainer rights. If the submitter is the only maintainer, the dialog should not be displayed, because otherwise the package will never get reviewed until the submitter lets out a sigh and self-accepts.

**Comment by coolo** [comment]
can't you just ignore the warning?

**Comment by Mailaender** [comment]
Now that I know that the dialog is very often just misleading I check the package users page manually, which is a pain as the web UI loads so slowly.

**Comment by coolo** [comment]
the request page is supposed to show the package maintainers - unfortunately this functionality is majorly broken

**Comment by hennevogel** [comment]
So the only thing that isn't working as it's supposed to is tracked in #2236
