### ISSUE TITLE
Build troubles on Ubuntu16.10 host

### ISSUE THREAD

**Issue by X0rg** [openSUSE/open-build-service#2254]
> Ubuntu:16.10 and Debian:Next (aka testing) distributions are available now.

- [ ] First of all, I can't enable **Debian:Next** host:  
![screenshot](https://cloud.githubusercontent.com/assets/2873785/19626381/ba5c8eee-9930-11e6-9368-7a546c8af8fd.png)
- [ ] After enabling **Ubuntu:16.10** host, xUbuntu_16.10 status stays unresolvable:  
`have choice for pkg-config needed by libglib2.0-dev: pkgconf pkg-config, have choice for pkg-config needed by libpango1.0-dev: pkgconf pkg-config, have choice for pkg-config needed by libfontconfig1-dev: pkgconf pkg-config, have choice for pkg-config needed by libatk1.0-dev: pkgconf pkg-config, have choice for pkg-config needed by libgtk-3-dev: pkgconf pkg-config, have choice for pkg-config needed by libdbus-1-dev: pkgconf pkg-config, have choice for adwaita-icon-theme needed by libgtk-3-0: lubuntu-icon-theme adwaita-icon-theme`

I use the same package for Debian (7.0) and Ubuntu (14.04 to 16.04) repos, but it works for them. It fails on 16.10 only.

**Comment by lethliel** [comment]
can you provide the project and package?

**Comment by adrianschroeter** [comment]
Debian:Next is not part of the simple list on purpose. It is a rolling release which is known to be broken from time to time. However, it might be that your issue is already solved.

Can you retest and post the link to the build log in case it still fails?

**Comment by X0rg** [comment]
@lethliel: of course.
The project is [CPU-X](https://build.opensuse.org/project/show/home:X0rg).
The package is [cpu-x](https://build.opensuse.org/package/show/home:X0rg/cpu-x).

@adrianschroeter: ok, I understand.
I can trigger a rebuild, but it stays unresolvable. There isn't log: [State of Repository xUbuntu_16.10 for home:X0rg / cpu-x](https://build.opensuse.org/package/binaries/home:X0rg/cpu-x?repository=xUbuntu_16.10).

**Comment by adrianschroeter** [comment]
unresolvable has been fixed in base distro

**Comment by X0rg** [comment]
Great, thank you so much!
