### ISSUE TITLE
Repositories configuration broken since a LONG time

### ISSUE THREAD

**Issue by stoecker** [openSUSE/open-build-service#2274]
The configuration page to disable and enable repositories is still broken. I hoped that this may be fixed after another bug-report here (didn't find it, sorry) was closed as resolved, but nothing is fixed on build.opensuse.org some months later.

E.g. here https://build.opensuse.org/repositories/home:dstoecker/gsoap Leap_42.1 is shown as active, but in reality it is disabled. Somehow the parent project settings still aren't correctly handled.

I always edit the meta file by hand to get what I want. That setup screen worked perfectly about 2 years ago.

Does it really need multiple years to fix such a simple bug?

**Comment by coolo** [comment]
it is shown as disabled here

**Comment by mmohring** [comment]
Dito here, all builds disabled except openSUSE Leap 42.1 on x86_64 for your link. I was usings the WebUI as well as command line client since the flags were fixed. And I tested the fixes, it were multiple commits.

**Comment by mmohring** [comment]
Webbrowser or OBS caching issue ?

**Comment by stoecker** [comment]
mmohring: "all builds disabled except openSUSE Leap 42.1 on x86_64 for your link."

That's what I wrote. 42.1 (x86_64) is shown as enabled, but you can clearly see, that it is actually disabled, when you go to the Overview.

home:dstoecker has:
    <disable/>
    <enable arch="x86_64" repository="openSUSE_13.2"/>
    <enable arch="x86_64" repository="openSUSE_Leap_42.1"/>
gsoap has:
    <disable/>
    <disable arch="x86_64" repository="openSUSE_13.2"/>

The disable in gsoap overrides the parent, but it seems that is ignored for the display. The 13.2 disable is superfluos ATM, but when not there, then also 13.2 would be shown as enabled - you can clearly see that when using mouse-over - then it tells you that the default would be enabled (is disabled in reality).

**Comment by mmohring** [comment]
But each of the displays of project and package repo build settings are the same in the WebUI repo settings and in the xml meta data. While the overview page as well as the monitor page show the results of the project repos build setting which is then overwritten by the package repo build settings. So to sum it up the repo flags view shows the respective flags for project and package, while project overview as well at the project monitor and dito package overview and package monitor show the effective result of applying project flags *and* package flags over each other.

**Comment by mmohring** [comment]
So your settings should result in gsoap builds switched off, which it does. E.g. Package flags overwrite Project flags.

**Comment by mmohring** [comment]
Sorry, now I see it. The WebUI shows the package build flag "on" in the WebUI repo flags view, while it is off and also shown "off" in the overview and in the monitor in project and package views as it should be.

**Comment by mmohring** [comment]
The problems is in the file: src/api/app/models/flag.rb, in function def default_status. In case that for type package that all_flag is set it is still overwritten by same_flag from the project. This should only happen if there is no all_flag from the package as in your case. I open an issue.

**Comment by mmohring** [comment]
I haved opened #2275

**Comment by adrianschroeter** [comment]
I don't see the problem in home:dstoecker/gsoap . All views in webui I found and also the backend are showing it as disabled. Anything what I missed?

**Comment by adrianschroeter** [comment]
k, coolo showed the issue to me. It is the one single icon on this page:

 https://build.opensuse.org/repositories/home:dstoecker/gsoap

build flags table -> openSUSE_Leap_42.1 -> x86_64

**Comment by stoecker** [comment]
NOTE: That issue also happens in a similar way when you enable/disable whole target distributions and/or whole processor types.

**Comment by mmohring** [comment]
There is a patch in #2283 for review to fix this bug.

**Comment by mmohring** [comment]
Please take a look into your projects/package, fix #2283  is merged and also deployed in build.o.o. So https://build.opensuse.org/repositories/home:dstoecker/gsoap should now be correct.

**Comment by stoecker** [comment]
The fix is only partial.

For 13.2/64 it correctly displays disabled, but when using mouseover it says "Take default (enable)". Correct would be "Take default (disable)". Same is true for the All/All button, which also should shows disable as default (probably for a different reason).

**Comment by mmohring** [comment]
That is another place to fix. Its really the WebUI logic not working. I am on it.

**Comment by mmohring** [comment]
I have prepared a fix for the WebUI coloring as well as the wrong defaults correction in 2292. I will add some test cases for the defaults computation, and then submit my next patch.

**Comment by adrianschroeter** [comment]
so we can assume that this to be fixed.. thanks a lot Martin!
