### ISSUE TITLE
[WebUI] package flags still incorrectly displayed

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#2275]
The OBS WebUI still displays the package build flags incorrectly in the package repository view in some cases, where package flags shall overwrite project flags.

**Comment by mmohring** [comment]
src/api/app/models/flag.rb.
In function def default_status, Lines 58-74

In case that for type package that all_flag is set it is still overwritten by same_flag from the project. This should only happen if there is no all_flag from the package. E.g. all_flag is set from the package. same_flag is matching from the project. Then the current default is same_flag from the project. But it should be all_flag from the package.

**Comment by mmohring** [comment]
We have another case that we have a matching same_flag from the package. I think this is currently handled in
src/api/app/mixins//get_flags.rb 
In function def get_flags(flag_type)

Anyway this is confusing and should also be handled also correctly in src/api/app/models/flag.rb .

**Comment by mmohring** [comment]
I will write now a patch for this.

**Comment by adrianschroeter** [comment]
thanks :)

**Comment by adrianschroeter** [comment]
But please with test case to understand your change. test/unit/build_flag_test.rb should be helpful here.

**Comment by mmohring** [comment]
@adrian: will work also on a test cases. The two files seem to not limit this to the WebUI, so can this also affect the API ? IIRC @hennevogel worked on this the last time ?

**Comment by coolo** [comment]
test/unit/build_flag_test.rb does not test flag calculation itself, it only tests the flags itself.

get_flags is only tested in spec/controllers/webui/project_controller_spec.rb - which kind of shows the problem: it's not tested for packages *at all*.

**Comment by mmohring** [comment]
@coolo thanks for the hints. So what we need is a fixed calculation of the flags which is the same in the API as it is in the backend. I am currently playing with it to get all the cases that can happen. Is it correct that the status monitor output in the WebUI comes from the backend, so there we see what the backend is computing ?

**Comment by mmohring** [comment]
I have a fixed version of default_status, which is all needed to make the WebUI work correctly. I have made the testcases manually via API calls and checked the WebUI, as well as using the WebUI to set the test cases.

Now I will look into writing the test suite test cases.

@adrianschroeter @coolo do you want the test cases in the test suite in a separate pull request ?

**Comment by mmohring** [comment]
I have created pull request #2283 for a fix and some tests.
