### ISSUE TITLE
Files could not be expanded: 400 remote error: /bs/service/26348 not writable for me at /usr/lib/obs/server/bs_service line 115. 

### ISSUE THREAD

**Issue by mhogomchungu** [openSUSE/open-build-service#2280]
I tried to make a new release for my project SiriKali[1][2] and the build process fails with an error that is on the title of this bug report.

An browser image with the error is below.

[1] https://mhogomchungu.github.io/sirikali/
[2] https://build.opensuse.org/package/show/home:mhogomchungu/sirikali

![screenshot_20161029_140927](https://cloud.githubusercontent.com/assets/3496115/19829136/e4b5d532-9de1-11e6-8442-723e7168e7ec.png)

**Comment by hennevogel** [comment]
@M0ses have you fixed this?

**Comment by M0ses** [comment]
Root cause fixed since Saturday. Run "osc service rr" for the affected packages.
