### ISSUE TITLE
Find and fix n + 1 queries

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#2287]
N + 1 queries are SQL queries that scale with the number of objects that are queried for. Those usualy can be done with 2 queries by using eager loading and alike. Have a look at the [rails guide](http://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations) for a better explanation.

One tool that is often used in rails to find those is [bullet](https://github.com/flyerhzm/bullet).

http://railscasts.com/episodes/372-bullet

**Comment by hennevogel** [comment]
So bullet finds n+1 queries for the OBS code? :-)

**Comment by adrianschroeter** [comment]
Can we integrate this into our test suite run?

**Comment by eduardoj** [comment]
Maybe this is what we need:

https://github.com/flyerhzm/bullet#run-in-tests

**Comment by bgeuken** [comment]
> Maybe this is what we need:
> https://github.com/flyerhzm/bullet#run-in-tests

Nice!
That could be the next step. Assuming we want this. Though it might make sense to fix the n + 1 queries first, if this causes our test suite to fail.

**Comment by bgeuken** [comment]
By now we run bullet in our dev environment to be able to identify n + 1 queries. We also solved a bunch of them already.

I think we don't need this issue to track the n + 1 query state any longer.
