### ISSUE TITLE
repository download link path is not requested from backend.

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#229]
The webui constructs the download path itself instead of asking the backend. Therefore special mappings, like with official openSUSE projects do not get applied. Example of a broken link:

https://build.opensuse.org/project/repository_state?project=openSUSE%3A12.2%3AUpdate&repository=standard

**Comment by mdeniz** [comment]
@adrianschroeter this is still alive?

**Comment by eduardoj** [comment]
It seems that it is not still alive. Closing. Please reopen if it happens again.
