### ISSUE TITLE
dod repos with GA+update channels stalled with "blocked: downloadimg xxx dod packages"

### ISSUE THREAD

**Issue by seife** [openSUSE/open-build-service#2296]
What I'm trying to do:
* SMT mirrors SLES12-SP1 plus all modules / extensions
* OBS 2.7.2 should use the SMT GA+update via DoD repos to build KIWI images

The issue was described on the mailing list: https://lists.opensuse.org/opensuse-buildservice/2016-11/msg00000.html

What seems to happen is: the DoD service is sorting repo priority differently than the build repo, leading to "unresolvable" packages.

A workaround is, to add the DoD repos explicitly in the correct order to the "images" repo of the project building the KIWI images:

      <repository name="images">
        <path project="Infrastructure:KIWI" repository="SLES12"/>
        <path project="home:seife:dodsles12" repository="server-upd"/>
        <path project="home:seife:dodsles12" repository="sdk-upd"/>
        <path project="home:seife:dodsles12" repository="cloud-upd"/>
        <path project="home:seife:dodsles12" repository="server-prod"/>
        <path project="home:seife:dodsles12" repository="sdk-prod"/>
        <path project="home:seife:dodsles12" repository="cloud-prod"/>
        <arch>x86_64</arch>
      </repository>

*BUT* this is a major PITA, because with this it is no longer possible to build images for different releases in the same project.

**Comment by mlschroe** [comment]
That's not how DoD works. There is no repo ordering involved at all.

**Comment by seife** [comment]
Well, it really does not work. Or my 22 packages would not be in state blocked.

**Comment by seife** [comment]
So it is supposed to not work? NOTABUG?

**Comment by mlschroe** [comment]
I know. But it must be something different. You need to find out why the download doesn't work / is stalled.

**Comment by mlschroe** [comment]
Well, it works for us ;)

**Comment by seife** [comment]
Do you have a setup similar than mine?
* with lots of DoD repos which carry different versions of the same packages?
* doing KIWI builds from it?

Why is the output of "osc buildinfo" indicating different repos than what the dodcheck wants to download?

Why is the adding of the repos to the "image" repo working around the issue?

I'm really trying to find out, but am pretty lost right now.
