### ISSUE TITLE
Provide full user name on bs_request show page (no mouseover)

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#2302]
Longer project and packages pathes are shortened by replacing parts of the name with '...'. This makes it quite hard to read them. One can still hover over the link to see a tooltip with the full path.

This also breaks the search functionality for requests on the user home page (reported in #2303 ).

Example from the bs request page:

"Submit package home:cool...tensions / rubygem-r...tionpack (revision 2) to package devel:lan...tensions / rubygem-r...tionpack"

taken from https://build.opensuse.org/request/show/437796

**Comment by shyukri** [comment]
Is it OK to wrap:
```
% if action[:type] == :submit %>
              <b>Submit
                <%= project_or_package_link project: action[:sprj], package: action[:spkg], rev: action[:srev] %>
                to
                <%= project_or_package_link project: action[:tprj], package: action[:tpkg] %>
              </b>
```
with `toggle_sliced_text()` ?

**Comment by hennevogel** [comment]
this is not happening anymore...

![Screenshot 2023-05-09 at 17-25-58 Request 437796 (revoked)](https://github.com/openSUSE/open-build-service/assets/514785/26e05799-5699-44b7-9b5c-c16b36f5da5e)
