### ISSUE TITLE
Shortening package and project names breaks search for bs requests

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#2303]
On the /user/show page users can view bs requests they are associated to. Path names that are to long get shortened by replacing parts with '...'.
This breaks the search functionality, since search uses the replaced strings, eg. one can search for '...' and get many results. 

Expected behaviour: Search uses the unshortened name of package and projects.

**Comment by hennevogel** [comment]
this is fixed in the meantime
