### ISSUE TITLE
[webui]Cross-Site Request Forgery Warning in app/controllers/webui/webui_controller.rb

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#2307]
I have updated my pull request #2292 , and now get this error, but not from me. I did not change the file in my pull request:

[Security issue from Hakiri](https://hakiri.io/projects/24a4980a727941/stacks/beceb185080072/builds/51376429f87882/warnings/d7d6dfabe9fe4f): protect_from_forgery should be configured with 'with: :exception' in app/controllers/webui/webui_controller.rb

**Comment by bgeuken** [comment]
Thanks for the report. I am currently looking at it.

**Comment by bgeuken** [comment]
Turns out we added [our own code](2188c059b67b82171d0e28ef59f77e62d22a09d8) to cause a ActionController::InvalidAuthenticityToken to be raised. So this is a false positive.
