### ISSUE TITLE
osc picks the wrong project ot build in and then refuses to build

### ISSUE THREAD

**Issue by hramrach** [openSUSE/open-build-service#2310]
After checking out a package and changing to its directory "osc build" says:

ppc64le is not a valid arch for the repository openSUSE_Tumbleweed

The configured build targets in OBS are

  <repository name="openSUSE_Tumbleweed">
    <path project="openSUSE:Factory" repository="snapshot"/>
    <arch>i586</arch>
    <arch>x86_64</arch>
  </repository>
  <repository name="openSUSE_Leap_42.2">
    <path project="openSUSE:Leap:42.2" repository="standard"/>
    <arch>x86_64</arch>
    <arch>i586</arch>
  </repository>
  <repository name="openSUSE_Factory_PowerPC">
    <path project="openSUSE:Factory:PowerPC" repository="standard"/>
    <arch>ppc64</arch>
    <arch>ppc64le</arch>
  </repository>
  <repository name="openSUSE_Factory_ARM">
    <path project="openSUSE:Factory:ARM" repository="standard"/>
    <arch>armv7l</arch>
    <arch>aarch64</arch>
  </repository>

so it has one configured with the correct architecture.

**Comment by mmohring** [comment]
Please give the osc command line where it complains.

**Comment by marcus-h** [comment]
On 2016-11-09 05:58:49 -0800, hramrach wrote:
> After checking out a package and changing to its directory "osc build" says:
> 
> ppc64le is not a valid arch for the repository openSUSE_Tumbleweed
> 
That's "correct" (wrt. osc's repo + arch guessing algo).

> The configured build targets in OBS are
> 
>   <repository name="openSUSE_Tumbleweed">
>     <path project="openSUSE:Factory" repository="snapshot"/>
>     <arch>i586</arch>
>     <arch>x86_64</arch>
>   </repository>

This repo has no ppc64le arch. Just specify the repo:
"osc build openSUSE_Factory_PowerPC" (then it'll build against
openSUSE_Factory_PowerPC ppc64le, if ppc64le is your hostarch).
If you don't want to rely on/be fooled by osc's "magic" argument
guessing, the best is to run
"osc build <repo> <arch> <specfile/build descr>".

**Comment by marcus-h** [comment]
So I think we can close this issue (if not, please reopen).
Btw., the best is to report osc issues in openSUSE/osc (https://github.com/openSUSE/osc/issues/new).

**Comment by hramrach** [comment]
the command is "osc build"

and the repo *does* have ppcle

<repository name="openSUSE_Factory_PowerPC"> <path project="openSUSE:Factory:PowerPC" repository="standard"/> <arch>ppc64</arch> <arch>ppc64le</arch> </repository>

**Comment by hramrach** [comment]
hm, and I cannot find any way to reopen issues

**Comment by mmohring** [comment]
As Marcus explains above you have to tell osc which arch and repo to use:

osc build <some options> openSUSE_Factory_PowerPC ppc64le <spec file>

Then it should work to build for ppc64le target.
