### ISSUE TITLE
"Download package" link not working.

### ISSUE THREAD

**Issue by sowani** [openSUSE/open-build-service#2314]
Hi,

I've setup a PhantomJS build at https://build.opensuse.org/package/show/home:asowani/PhantomJS which passes successfully and an RPM package is created. Strangely, when I click on "Download package" link, I get "No data for home:asowani / PhantomJS" error message. I can see that my packages are present at https://build.opensuse.org/package/binaries/home:asowani/PhantomJS?repository=SLE_12_SP1, still the link between "Download package" and this location is missing. I expected that this will happen automatically. I checked with the OBS Forum (https://forums.opensuse.org/showthread.php/520911-Baffled-by-quot-Download-package-quot-option-setup) and they advised to open a bug for this. Can somebody have a look at this problem?

Thanks,
Atul.

**Comment by adrianschroeter** [comment]
OBS just links to software.opensuse.org. Please report this here: https://github.com/openSUSE/software-o-o
