### ISSUE TITLE
Improve Accept/Decline buttons

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#2327]
Moved from https://github.com/openSUSE/obs-build/issues/306 .

It sometimes happens that we reviewers do not position our mice accurately enough and hit the wrong button in the review view (e.g. https://build.opensuse.org/request/show/440116 ).

Please consider adding some spacing between the "Approve" and "Disregard" buttons. 4em seems like a reasonable value; alternatively, right-aligning the Disregard button might also work.

Cc @DimStar77 
![rt](https://cloud.githubusercontent.com/assets/8861948/20262887/852e8a0c-aa64-11e6-84f6-d22cebeb403f.png)

@hennevogel also suggested to colorize the buttons, which I would also agree on (but rather for looks than effect), but would have made a separate ticket for. (But maybe it's better to do it all in one?)

**Comment by DavidKang** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve Accept/Decline buttons](https://trello.com/c/igSO40eE/134-improve-accept-decline-buttons)
