### ISSUE TITLE
OBS can crash when thinking sphinx is not working

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#2343]
I just accepted some requests, which failed with a 500. After that I can still see the open requests, but the diff changed and now shows an error message.

https://build.opensuse.org/request/show/439989
https://build.opensuse.org/request/show/437796
https://build.opensuse.org/request/show/437797

I checked the source packeages and they don't have any files... -> https://build.opensuse.org/package/show/home:coolo:branches:devel:languages:ruby:extensions/rubygem-redis-rack
I guess that is a result of the failed request acceptance.

**Comment by bgeuken** [comment]
@adrianschroeter Do we have any hotfixes applied that could have caused this?

**Comment by adrianschroeter** [comment]
This is the general problem that we crash in some situations when the thinking sphinx daemon is not answering (eg. if it down, the index is broken or the database schema has changed). rubygem-thinking_sphinx is hooking in to activerecord models, runs there on changes, but can also lead to crashing active record operations.

We should protect us better against these kind of crashes, eg by ignoring the error when a project or package get destroyed and not aborting the api operation.

This is the backtrace for this problem: http://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/582d6053fe5294000a000014

We have two hotfixes applied atm, but they have not anything todo with this issue.

**Comment by eduardoj** [comment]
The link to the Errbit backtrace leads to a non existent page. I don't remember to have issues with thinking sphinx on last months.

Closing the issue. Feel free to open it if it still applies.

**Comment by adrianschroeter** [comment]
On Montag, 7. Oktober 2019, 17:36:37 CEST Eduardo J. wrote:
> The link to the Errbit backtrace leads to a non existent page. I don't
> remember to have issues with thinking sphinx on last months.
> 
> Closing the issue. Feel free to open it if it still applies.

running a search without a running sphinx daemon does not lead to a 500 
anymore?

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by eduardoj** [comment]
@adrianschroeter:

> running a search without a running sphinx daemon does not lead to a 500 anymore?

Yes, it leads to a 500. In the logs will be shown something like:
```
Completed 500 Internal Server Error in 267ms (ActiveRecord: 20.3ms | Backend: 0.0ms)

ThinkingSphinx::ConnectionError (Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1' (115)):

app/controllers/webui/search_controller.rb:169:in `search'
app/controllers/webui/search_controller.rb:7:in `index'
```
Considering that the sphinx daemon is part of OBS, and OBS doesn't work without a sphinx daemon, a 500 error is enough. Isn't it?

**Comment by adrianschroeter** [comment]
On Montag, 7. Oktober 2019, 19:18:43 CEST Eduardo J. wrote:
> @adrianschroeter:
> > running a search without a running sphinx daemon does not lead to a 500
> > anymore?
> Yes, it leads to a 500. In the logs will be shown something like:
> ```
> Completed 500 Internal Server Error in 267ms (ActiveRecord: 20.3ms |
> Backend: 0.0ms)
> 
> ThinkingSphinx::ConnectionError (Error connecting to Sphinx via the MySQL
> protocol. Can't connect to MySQL server on '127.0.0.1' (115)):
> 
> app/controllers/webui/search_controller.rb:169:in `search'
> app/controllers/webui/search_controller.rb:7:in `index'
> ```
> Considering that the sphinx daemon is part of OBS, and OBS doesn't work
> without a sphinx daemon, a 500 error is enough. Isn't it?

well, a proper error page would be nicer ("search is down atm, admin is 
notified"). A 500 is always seen as a crash.

(not that it is super critical)

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by hennevogel** [comment]
For all exceptions we do not catch we display our [500](https://build.opensuse.org/500.html)  page...

**Comment by adrianschroeter** [comment]
On Montag, 7. Oktober 2019, 21:13:58 CEST Henne Vogelsang wrote:
> For all exceptions we do not catch we display our
> [500](https://build.opensuse.org/500.html)  page...

which gives no hint about the reason. it is just a crash for the user.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by hennevogel** [comment]
> which gives no hint about the reason.

Well the user can't do anything about it anyway. But sure, this could be extended with more meta data...

**Comment by adrianschroeter** [comment]
On Dienstag, 8. Oktober 2019, 09:20:09 CEST Henne Vogelsang wrote:
> > which gives no hint about the reason.
> 
> Well the user can't do anything about it anyway. But sure, this could be
> extended with more meta data...

the user might be the admin or the user can create a better bug report wich 
can be solved more easily when giving something more then just "crash" as 
output ..

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer
