### ISSUE TITLE
Web-Frontend: List of involved projects do not show projects for role ' Bugowner' 

### ISSUE THREAD

**Issue by coogor** [openSUSE/open-build-service#2363]
I noticed some projects I used to maintain do not show up anymore in my list of involved projects. When x-checking, role there is 'bugowner'. So either the role was changed, or bugowner projects are not displayed anymore (See: https://build.opensuse.org/package/show/network:telephony/hylafax+ )

**Comment by ChrisBr** [comment]
involved_projects / involved_packages does only include the role maintainer!

@adrianschroeter do we want to change that?

**Comment by eduardoj** [comment]
This issue should be fixed with the roll-out of the [User Profile page redesign](https://openbuildservice.org/2021/03/29/user-profile-redesign/). Closing.
