### ISSUE TITLE
WebUi regression in display of https://build.opensuse.org/user/show/username

### ISSUE THREAD

**Issue by plinnell** [openSUSE/open-build-service#2381]
Clicking on the type column has no effect, unlike recently.  This is a regression from prior behavior and is important for factory reviewers, as we want to see "release" type sorted before "submit" types.

**Comment by bgeuken** [comment]
I am sorry but I can't reproduce this. Please double check.

**Comment by bgeuken** [comment]
Closing for now. Please let us know when this happens again.
