### ISSUE TITLE
Crash when content type header is not set

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2396]
We have a regression (since rails 5 update?) that a number of hand written scripts talking to the api are not working anymore. They don't set any Content-type header (like osc is doing)  which leads to a crash here:

actionpack-5.0.0.1/lib/action_dispatch/http/parameters.rb:63→ parse_formatted_parameters
actionpack-5.0.0.1/lib/action_dispatch/http/request.rb:366→ block in POST
rack-2.0.1/lib/rack/request.rb:57→ fetch
rack-2.0.1/lib/rack/request.rb:57→ fetch_header

seems to be a regression in actionpack which we do need to fix there (or to workaround in api).

**Comment by hennevogel** [comment]
@adrianschroeter it would be very nice if you tell us what the scripts are doing so we have a chance to reproduce it :-)

**Comment by adrianschroeter** [comment]
I don't have the scripts either, this is from various reports of other teams.

Christian fixed it in rails meanwhile.
