### ISSUE TITLE
During package build all tests complain about for example Capybara::ElementNotFound: Unable to find field "Username" and others

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#2403]
Its looks like the current git master when running the testsuite all WebUI:: tests fail with lots of errors like Capybara::ElementNotFound:  Capybara::ElementNotFound: Unable to find field "Username" and others.

**Comment by mmohring** [comment]
Take a look at: https://build.opensuse.org/package/show/OBS:Server:Unstable/obs-server .

**Comment by hennevogel** [comment]
This is only during package build...

**Comment by mmohring** [comment]
What do you mean with package build ? It happens when the WebUI:: Testsuite starts: 
`
[  908s] Webui::AddRepoTest
[  933s] Starting test backend...    Testcase publish error
[  933s]     Testcase publish error
[  933s] done
[  933s]   test_add_default                                                SKIP (22.94s)
`
After that all test cases fail with current git master. It is not of course in the github ran tests.

**Comment by mmohring** [comment]
Git commit 4f74812e0b7c1040cded7375050c883d8b871884 seemed to have worked.

**Comment by mmohring** [comment]
When I install this version and start it, I get a "500: Internal Server Error" .

**Comment by mmohring** [comment]
When I remove /srv/www/obs/api/config/crawler-user-agents.json, then the OBS deployment works, no "500: Internal Server Error" and the also the WebUI testsuite works.

**Comment by mmohring** [comment]
@adrianschroeter can you take a look ?

**Comment by bgeuken** [comment]
@mmohring The _service file was using a wrong url for fetching that file. That was crashing the tests

**Comment by mmohring** [comment]
I see it now working. It also crashed the installation of an OBS. I consider it fixed and close this issue.
