### ISSUE TITLE
CentOS 7 Bareword "Archive::Tar::Constant::FILE" not allowed

### ISSUE THREAD

**Issue by k0da** [openSUSE/open-build-service#2415]
perl -wc bs_dodup
Bareword "Archive::Tar::Constant::FILE" not allowed while "strict subs" in use at build/Build/Archrepo.pm line 83.
Compilation failed in require at build/Build/Repo.pm line 50.
BEGIN failed--compilation aborted at bs_dodup line 25.

**Comment by k0da** [comment]
BuildRequire perl-Archive-Tar solves an issue

**Comment by mlschroe** [comment]
Actually a problem in obs-build, fixed with commit f6de6a5883b1ef56827cd3d41b09dc185f5db6f3
