### ISSUE TITLE
Macro in Requires(pre) not evaluated

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#2416]
I found the following in vsftpd.spec:
` Requires(pre):  %{_sbindir}/useradd`
The buildconfig has
`FileProvides: /usr/sbin/useradd shadow`

So that should pull in shadow but it doesn't work. Replacing %{_sbindir} with /usr/sbin directly helps. So looks like OBS doesn't expand the macro properly.

**Comment by adrianschroeter** [comment]
and where is %_sbindir defined? do you in prjconf ?

It can't work if it is only defined inside of some rpm package.

**Comment by lnussel** [comment]
do'h
