### ISSUE TITLE
Warn maintainers about expiring keys

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#2443]
Add a re-occurring background job that warns project maintainers if a project key is expiring in less than 14 days.

**Comment by adrianschroeter** [comment]
hm, we do auto extending in most cases these days. So warning them will confuse a lot people.

**Comment by hennevogel** [comment]
Okay. In which cases we don't do auto extending?

**Comment by adrianschroeter** [comment]
When the admin configured it that way ... the sign app can be any script or program doing it's own decisions.

**Comment by hennevogel** [comment]
okay let's close this
