### ISSUE TITLE
Periodically run rspec without VCR

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#2445]
Travis has an option to run ['cron' like jobs](https://docs.travis-ci.com/user/cron-jobs/) now. We should make use of this feature to run our rspec test suite without VCR against a realy backend.

**Comment by coolo** [comment]
I was curious and tried to run the tests without VCR :)

I get 167 failures, 232 cassettes no longer created and 5700 paths no longer touched. I assume the failures are the real problem though, the rest is stale data that doesn't hurt.

**Comment by eduardoj** [comment]
Since we use CircleCI instead of Travis we should make use of [scheduled jobs](https://circleci.com/docs/2.0/configuration-reference/#schedule).

**Comment by coolo** [comment]
As in https://github.com/openSUSE/open-build-service/pull/5386? Just close this issue here
