### ISSUE TITLE
don't compile assets build time

### ISSUE THREAD

**Issue by k0da** [openSUSE/open-build-service#2448]
Compiling assets build time, doesn't have much sense, the step could be easily moved into source tarball creation.

Compiling assets brings too much dependencies

**Comment by coolo** [comment]
these dependencies *are* the assets mostly.

**Comment by k0da** [comment]
it makes a build not reproducible

**Comment by adrianschroeter** [comment]
no, we won't move it since the tar ball would not be reproducable then.

You may want to work on the ruby tools responsible for this, but the current situation is reproducable enough for us.
