### ISSUE TITLE
obs-api pulls ruby2.1

### ISSUE THREAD

**Issue by k0da** [openSUSE/open-build-service#2470]
OBS:Server:2.7/Leap_42.1 obs-api package pulls ruby2.1 which breaks passenger
[Thu Dec 15 20:49:21.614390 2016] [core:notice] [pid 517] AH00094: Command line: '/usr/sbin/httpd-prefork -f /etc/apache2/httpd.conf -D SYSCONFIG -D SSL -C PidFile /var/run/httpd.pid -C Include /etc/apache2/sysconfig.d/'
/usr/lib64/ruby/2.1.0/x86_64-linux-gnu/rbconfig.rb:7:in `<module:RbConfig>': ruby lib version (2.1.2) doesn't match executable version (2.1.8) (RuntimeError)
	from /usr/lib64/ruby/2.1.0/x86_64-linux-gnu/rbconfig.rb:5:in `<top (required)>'
	from /usr/lib64/ruby/2.1.0/rubygems.rb:8:in `require'
	from /usr/lib64/ruby/2.1.0/rubygems.rb:8:in `<top (required)>'
	from <internal:gem_prelude>:1:in `require'
	from <internal:gem_prelude>:1:in `<compiled>'

zypper al ruby2.1 prior installing obs-api solves issue

**Comment by adrianschroeter** [comment]
We have solved this in unstable branch, I hope...

**Comment by bgeuken** [comment]
Please re-open if this is still an issue. Thanks:-)
