### ISSUE TITLE
Interface to get the right(tm) public key

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2472]
The backend delivers the pubkey and some meta information using 

 /source/$PROJECT/_keyinfo

The api should allow access to it. The webui could offer the key download via it and tell from which project it is coming from. Also the used algorithm is available.

**Comment by hennevogel** [comment]
So the backend already does this?

**Comment by adrianschroeter** [comment]
since one hour :)

**Comment by hennevogel** [comment]
heh okay

**Comment by evanrolfe** [comment]
@adrianschroeter thanks!

**Comment by adrianschroeter** [comment]
Note that there can be also a sslcert next to the pubkey in some projects.

**Comment by lnussel** [comment]
so is this done?

**Comment by hennevogel** [comment]
yes it is
