### ISSUE TITLE
webui is not handling invalid package meta data from user on save, but is crashing

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2474]
webui/package#save_meta threw this 1 times
<pre>
ActiveXML::Transport::Error: &lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;repoid &#39;home:antergos:branches:devel:tools:building&#39; is illegal&lt;/summary&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/package/save_meta/home:antergos/lightdm-webkit2-greeter](https://build.opensuse.org/package/save_meta/home:antergos/lightdm-webkit2-greeter)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/58578e77249bcd0007000000)

**Comment by eduardoj** [comment]
It looks the same as #3732, already closed. So closing this one.
