### ISSUE TITLE
[production][request#show] ArgumentError: string contains null byte

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#2493]
request#show threw this 12 times
<pre>
ArgumentError: string contains null byte
</pre>
[https://api.opensuse.org/request/446602?withfullhistory=1](https://api.opensuse.org/request/446602?withfullhistory=1)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/585a9ae3842d48000d000003)

**Comment by coolo** [comment]
I removed this element - a python string POSTed within osc plugin

#<HistoryElement::RequestPriorityChange id: 2331299, type: "HistoryElement::RequestPriorityChange", op_object_id: 559502, 
created_at: "2016-12-21 15:08:11", user_id: 39704, 
      description_extension: "moderate => important", comment: "r\u0000\u0000\u0000a\u0000\u0000\u0000i\u0000\u0000\u0000s\u0000\u0000\u0000i\u0000\u0000\u0000n\u0000\u0000\u0000g\u0000\u0000\u0000 
\u0000\u0000\u0000p\u0000\u0000\u0000r\u0000\u0000\u0000i\u0000\u0000\u0000o\u0000\u0000">]>

This should be blocked from validating.

**Comment by eduardoj** [comment]
Already checked that:
* "ArgumentError: string contains null byte" has not been logged in Errbit in the last year.
* The link https://api.opensuse.org/request/446602?withfullhistory=1 is not valid any more, returns 404.
* The exception on Errbit has been deleted.

Please reopen if it happens again.

**Comment by coolo** [comment]
please note that the api.opensuse.org URL is only 404 if you access it with a browser. osc has no problem rendering
