### ISSUE TITLE
Files could not be expanded: Command failed(128): "fatal: Couldn't find remote ref xxx\n"

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/open-build-service#2499]
At https://build.opensuse.org/package/show/home:rhabacker:branches:windows:mingw:win32:KF529/mingw32-kauth I got the mentioned error. The _service file does not contains any '\n after the revision xxx.
A local osc build does not show this error.

**Comment by lethliel** [comment]
At the moment everything looks fine. Can you confirm?

**Comment by rhabacker** [comment]
I applied a temporary workaround. See earlier revision having the bug  https://build.opensuse.org/package/rdiff/home:rhabacker:branches:windows:mingw:win32:KF529/mingw32-kauth?linkrev=base&rev=3

**Comment by lethliel** [comment]
the error message is misleading. It just means, that on the first run with the _service file there was no ref v5.29.0 on git.kde.org for kauth. So the expanded diff cannot work.
