### ISSUE TITLE
Failure to connect ro port 5152 despite active service

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#2501]
In OBS 2.7.51:
```
$ osc r -v
standard             i586       blocked:  interconnect error: connect to niw-build01.netitwork.de:5152: Connection refused
```
But the service is running (on the same host as bs_sched) and is reachable.
```
niw-build01# telnet niw-build01.netitwork.de 5152
Trying 2a01:4f8:162:73ab::58c6:b4a0...
telnet: connect to address 2a01:4f8:162:73ab::58c6:b4a0: Connection refused
Trying 88.198.180.160...
Connected to niw-build01.netitwork.de.
Escape character is '^]'.
^]
telnet> Connection closed.

# ss -alntp|grep -i 5152
LISTEN     0      128          *:5152                     *:*                   users:(("bs_service",pid=26463,fd=3))
```

**Comment by adrianschroeter** [comment]
just works here. Is the service server actually attempted to reach? Or is this just an old state?
Maybe you have service dispatcher configured, but do not run it?

**Comment by jengelh** [comment]
How is service dispatcher configured? How is it enabled? Does BSConfig.pm's
```
our $serviceserver = "http://$hostname:5152/";
```
just set it, or enable it? It does not say.
The servicedispatch process really runs, but sits idle.
The only thing that happens on 5152 is that something asks it for status every now and then.
```
14:25:16.077323 IP 88.198.180.160.56596 > 88.198.180.160.5152: Flags [P.], seq 1:112, ack 1, win 342, options [nop,nop,T
S val 731156587 ecr 731156587], length 111
E...kT@.@..3X...X...... ...9..u}...V.c.....
+..k+..kGET /serverstatus HTTP/1.1
Host: niw-build01.netitwork.de:5152
User-Agent: BSRPC 0.9.1
Connection: close

```
```
14:24 niw-build01:/srv/obs/log # cat servicedispatch.log 
2017-01-03 14:21:05: [14036] bs_servicedispatch started
waiting for an event...
```
So it would appear srcserver never ever contacts it and `/srv/obs/log/src_server.log` also has no indication that it ever did anything with 5152. Which makes the "interconnect error: ... connection refused" ever more puzzling.

**Comment by marcus-h** [comment]
On 2017-01-03 05:28:07 -0800, jengelh wrote:
> How is service dispatcher configured? How is it enabled? Does BSConfig.pm's
> ```
> our $serviceserver = "http://$hostname:5152/";
> ```
> just set it, or enable it? It does not say.
> The servicedispatch process really runs, but sits idle.

You need to tell the bs_srcserver to use it via something like
```
our $servicedispatch = 1;
```

(the question is if you really need/want to use this service)

> So it would appear srcserver never ever contacts it and `/srv/obs/log/src_server.log` also has no indication that it ever did anything with 5152. Which makes the "interconnect error: ... connection refused" ever more puzzling.
> 
Is the bs_service host reachable from the bs_srcserver host and did
you set the correct $serviceserver in the BSConfig.pm of bs_srcserver host?
What's the output of
```
curl http://<srcserver_host>:5352/source/<project>/<your blocked package>
```

**Comment by jengelh** [comment]
```
# curl http://localhost:5352/source/home:jengelh:leap42.2/w3m
<directory name="w3m" rev="2" vrev="2" srcmd5="f04eaae8044c983a1640dcdf70e13294">
  <linkinfo project="home:jengelh:tumbleweed" package="w3m" error="home:jengelh:tumbleweed/w3m: service error:  interconnect error: connect to niw-build01.netitwork.de:5152: Connection refused" />
  <entry name="_link" md5="8e7ef8231a1d6966882276e939c2c30d" size="84" mtime="1483449320" />
</directory>
```
It's still not clear where this error comes from. It seems like this is stored/cached somewhere and it shouldn't be.

**Comment by jengelh** [comment]
```
" xsrcmd5="6cb64ab9cc96627a31cc01054d68dd57">
    <error>service error:  interconnect error: connect to niw-build01.netitwork.de:5152: Connection refused</error>
  </serviceinfo>
  <entry name="0001-allow-to-configure-the-accept-option-for-bad-cookies.patch" md5="35f83dfb9a844dc95aefa7f6312b23b8" size="1535" mtime="1480693020" />
  <entry name="0001-handle-EXDEV-during-history-file-rename.patch" md5="468a37366aa1cf3af2a608786130f116" size="1962" mtime="1480693021" />
  <entry name="0001-implements-simple-session-management.patch" md5="ea43a927c8a1fcd35cd560fb567dacd3" size="5635" mtime="1480693021" />
  <entry name="0001-w3mman-don-t-show-invalid-characters-bsc-950800.patch" md5="f5cf1ffa59d3459ee0f15588951c8584" size="1131" mtime="1480693021" />
  <entry name="_link" md5="15e4372e1d4efb0c0689f94ce3ed19df" size="137" mtime="1481585160" />
  <entry name="_service" md5="1f03735ae4c1a806f9fd5aac005f6c74" size="607" mtime="1480693021" />
  <entry name="w3m-0.5.3.git20161120.tar.xz" md5="1eb3e674d7f9b45522a02c5df56bea5c" size="1143848" mtime="1480693022" />
  <entry name="w3m-jng-prefs.diff" md5="5373b2ba0faeae4b8ce8f828556112af" size="3908" mtime="1411421269" />
  <entry name="w3m.changes" md5="b9c86606a72b2dc9b97f1a8acd5d0b23" size="23677" mtime="1480693022" />
  <entry name="w3m.spec" md5="87e347b6aba54ec5d7cda4c3296e5aa0" size="3973" mtime="1481585159" />
</directory>
```

**Comment by jengelh** [comment]
foo knows what went wrong here. I reenabled `our $serviceserver` because apparently it will just hang without, made sure `obsservice` _and_ `obsservicedispatch` were restarted, restarted srcserver, and kicked the package (remove/add _service file) and then it magically sent something large over port 5152. Maybe everything was stuck on an old srcmd5 and did not want to move without a change. Anyway, really terrible experience and bad error reporting there :-(
