### ISSUE TITLE
We need a proper handling of MissingParameterError exception in webui

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2511]
webui/package#live_build_log threw this 0 times
<pre>
ActionController::UrlGenerationError: No route matches {:action=&gt;&quot;logfile&quot;, :arch=&gt;&quot;x86_64&quot;, :controller=&gt;&quot;build&quot;, :package=&gt;&quot;codelite&quot;, :project=&gt;#&lt;Project id: 121305, name: &quot;home:fusion809&quot;, title: &quot;Brenton Horne&#39;s OBS repository&quot;, description: &quot;fusion809&#39;s repository of source files primarily i...&quot;, created_at: &quot;2016-02-08 07:15:57&quot;, updated_at: &quot;2017-01-01 18:35:58&quot;, remoteurl: nil, remoteproject: nil, develproject_id: nil, delta: true, kind: &quot;standard&quot;, url: nil&gt;, :repository=&gt;nil} missing required keys: [:repository]
</pre>
[https://build.opensuse.org/package/live_build_log/home:fusion809/codelite/openSUSE_42.2/x86_64](https://build.opensuse.org/package/live_build_log/home:fusion809/codelite/openSUSE_42.2/x86_64)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/586a8d64ad0063000a000003)

**Comment by adrianschroeter** [comment]
Some commits make more use of required_parameters function in webui. This just creates a crash on missing parameters which is filling errbit.

We should have a proper error handling (eg. flash error popup and go back to the former page?) instead.

**Comment by DavidKang** [comment]
Should be fixed with #2967
