### ISSUE TITLE
Add debian/ubuntu aarch64 and armv7l (armhf) qemu crosscompile

### ISSUE THREAD

**Issue by mibofra** [openSUSE/open-build-service#2524]
There is a possibility to set up the project configuration of a debian/ubuntu used as repository (like this one https://build.opensuse.org/project/prjconf/Debian:Next , used in OBS local appliance, and it can retrive with DoD all the armv7l packages needed) to use qemu on a x86_64 worker to build armhf (armv7l) and aarch64 packages (as is already done in OpenSUSE Factory, for example: https://build.opensuse.org/project/prjconf/openSUSE:Factory:ARM). Or it isn't added because you have encountered some issues try enabling it?

**Comment by adrianschroeter** [comment]
It is just no one is investing time to maintain a proper configuration for debian qemu builds. In any case, not a OBS source problem, you may want to work on it and promote your config on the mailing list.
