### ISSUE TITLE
Hide repositories if they are not used for a package

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#2529]
I think it's better to not show repositories in the repository list of the package view, if a repository is not used. This doesn't bring me any information. It just fills the page.

![bildschirmfoto 2017-01-05 um 11 35 38](https://cloud.githubusercontent.com/assets/8287131/21677637/43441a30-d33b-11e6-9f57-a90ba8168584.png)

**Comment by bgeuken** [comment]
I think it's valid to show repositories that got disabled for a certain package or architecture.

**Comment by adrianschroeter** [comment]
You can argue in both ways at least. But what about to sort it in a way that the building ones are on top at least? (just an idea)

**Comment by bgeuken** [comment]
I changed my mind. It would be nicer to not show disabled repos by default, but allow users to make them visible if they want to, eg. via a 'show disabled builds' link.
