### ISSUE TITLE
can branch new source package into locked incicent

### ISSUE THREAD

**Issue by msmeissn** [openSUSE/open-build-service#2537]
I can branch -M a new source package in a "locked" incident....

**Comment by adrianschroeter** [comment]
you mean into an incident where only packages are locked, but not yet the project? (due to running release request)?

**Comment by msmeissn** [comment]
yes,. correct. the new package appears and starts building

**Comment by adrianschroeter** [comment]
that is more or less a wanted change with the new locking. What would you expect here?

I would not like to have code which checks also all packages for a warning at least ...

**Comment by adrianschroeter** [comment]
works as designed. will need to rediscuss if this is causing problems.
