### ISSUE TITLE
Build service webui changes line endings resulting in broken patches

### ISSUE THREAD

**Issue by sreeves** [openSUSE/open-build-service#254]
In IBS SUSE:SLE-11-SP3:GA/beagle patch bnc806669-disable_firefox_plugin.patch unfortunately contains mixed line ending styles. Editing that patch via the webui changes the line endings without any visual indication of different line endings or warning on save. This causes the patch to no longer apply which breaks the build.

**Comment by bgeuken** [comment]
This seems to be an edge case, having windows and linux line endings. It probably happened when a linux user edited a windows patch (before uploading to OBS) or vice versa.

I think it's fair to say that users have to convert such a file manually. Sorry:-)

Closing as wontfix
