### ISSUE TITLE
rpmlint rendering issue

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2552]
We introduced a regression which breaks the rpmlint error reporting in last weeks. Happens on build.o.o and also on the test instance with current code. Example link:

https://build-test.opensuse.org/package/show/home:adrianSuSE/gcc5

click on rpmlint tab, you will see plain xml.

**Comment by ChrisBr** [comment]
Probably introduced by bdfb287c880f2b60718348471b06e3b74fd020c6

**Comment by ChrisBr** [comment]
btw, monkey patched on build.o.o
