### ISSUE TITLE
Error 500 on repository delete

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#2590]
I tried to delete EOL repositories from https://build.opensuse.org/project/show/games:tools both via https://build.opensuse.org/project/meta/games:tools and https://build.opensuse.org/repositories/games:tools but it never does anything. Sadly the error message contains 0 hints.

**Comment by adrianschroeter** [comment]
You tried via webui?
IIRC it has not handling for dealing with depending repositories. But @hennevogel did start to look into this...

**Comment by adrianschroeter** [comment]
Use "osc meta prj -e -f ..." for now

**Comment by Mailaender** [comment]
> You tried via webui?

Yes.

> Use "osc meta prj -e -f ..." for now

```
osc meta prj -e -f games:tools
Sending meta data...
BuildService API error: 500
```

:/

**Comment by hennevogel** [comment]
@Mailaender so it never does anything or it errors? Which one is it? :-)

**Comment by Mailaender** [comment]
Both. Try it yourself. It will always give out a generic error 500 and save or change nothing.

**Comment by adrianschroeter** [comment]
There were a number of broken database entries (repositries without a matching project and path_elements without matching repositories).

We usually have the mysql constraints to protect us here, but they did not exist on production system :(

Fixed all (~40) database entries and add the constraints to protect is in future of broken code....
