### ISSUE TITLE
503 response for openSUSE:13.1 (64 bits) and openSUSE:42.1 (32 bits)

### ISSUE THREAD

**Issue by polmr** [openSUSE/open-build-service#2593]
Hi, I have a private OBS with several projects. They have configured  a bunch of different repositories. All of the sudden, x86_64 arch for openSUSE 13.1 is failing. the interface reports: "The repository setup is broken: build not possible". I'm having the same problem with openSUSE 42.1 i586. I've been able to catch a line in scheduler_x86_64.log saying:
```
repo openSUSE.org:openSUSE:13.1/standard: 503 remote error: Service Temporarily Unavailable
repository 'openSUSE.org:openSUSE:13.1/standard' is unavailable
```
Is there something wrong in my local configuration or is there a failure in openSUSE.org in those particular repos/architectures ?

**Comment by polmr** [comment]
Fixed after rebooting. I wonder why ...

**Comment by adrianschroeter** [comment]
well, remote might not have been reachable, but it should recover automatically.

We would need more logs from backend and ideally a way to reproduce (maybe by cutting the network temporary).

Sorry, can't help much with these informations.
