### ISSUE TITLE
rpmlint results not shown anymore

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#2596]
https://build.opensuse.org/request/show/452118
The right hand side ("rpmlint results") shows "" (this is different from "No rpmlint log" seen _otherwise_ sometimes), but the build _definitely_ has a rpmlint.log that is not empty.

**Comment by adrianschroeter** [comment]
Might be a regression in rpmlint layout fix? @ChrisBr can you have a look?

**Comment by ChrisBr** [comment]
Fixed in #2666 and monkey patched on build.o.o
