### ISSUE TITLE
'Trigger services' gives error

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#2598]
When I click the new 'trigger services' link, I'm redirected to the package/show route, which will give me this error: "Could not expand files, source service running". No joking! I just triggered it, but why is it an error? Wouldn't it be more sensible to make this an information flash and show the unexpanded sources instead?

**Comment by adrianschroeter** [comment]
On Dienstag, 24. Januar 2017, 04:36:19 CET wrote Stephan Kulow:
> When I click the new 'trigger services' link, I'm redirected to the package/show route, which will give me this error: "Could not expand files, source service running". No joking! I just triggered it, but why is it an error? Wouldn't it be more sensible to make this an information flash and show the unexpanded sources instead?

yes, but it makes maybe sense to implement the fallback in the backend.
Means, we would need a tryexpand=1 parameter which is falling back to
avoid an error handling and second request to the backend.



-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imend�rffer, Jane Smithard, Graham Norton, HRB 21284 (AG N�rnberg) 
 
Maxfeldstra�e 5                         
90409 N�rnberg 
Germany

**Comment by mlschroe** [comment]
Nah, just don't overengineer. Just catch the error and do a second request.

**Comment by adrianschroeter** [comment]
k, the webui should show the situation that a service is currently running. And either update automatically or offer a reload button in that situation.

**Comment by ChrisBr** [comment]
Except the reload it seems to be fixed in c553930c62de7ad22a0e3a9a3665711381f96003
