### ISSUE TITLE
[Arch Linux] appending to the dependency array doesn't work

### ISSUE THREAD

**Issue by z3ntu** [openSUSE/open-build-service#2616]
~~PKGBUILD: https://build.opensuse.org/package/view_file/home:z3ntu/razer-drivers/PKGBUILD (see line 27)~~ I updated it on obs for testing, say if you want the one that doesn't work
Build log: https://build.opensuse.org/package/live_build_log/home:z3ntu/razer-drivers/Arch_Extra/x86_64

**Comment by mlschroe** [comment]
True. Fixed with commit d0823a35095ef67a7bf1b15c8f65650a8603ecb1, to be deployed soon.

**Comment by z3ntu** [comment]
This commit isn't online yet, right...? But thanks :)

**Comment by z3ntu** [comment]
Found it 👍 https://github.com/openSUSE/obs-build/commit/d0823a35095ef67a7bf1b15c8f65650a8603ecb1

**Comment by z3ntu** [comment]
Seems to work now 😄 https://build.opensuse.org/package/live_build_log/home:z3ntu/razer-drivers/Arch_Extra/x86_64
