### ISSUE TITLE
Timeouts on build.opensuse.org webui

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#2617]
https://build.opensuse.org/request/show/427869

Either the connection is severed after a timeout (yielding a blank browser page without an URL), or the webpage does appear but print """Timeout while diffing /source/openSUSE:Factory/gcc5?cmd=diff&orev=d608a792e58f489810547b6cb6d736ff&rev=35840e1b8cf5649d1de007d7691ab77f&view=xml&withissues=1""".

**Comment by adrianschroeter** [comment]
hm, works for me now, most likely because the diff cache exists now. We might have a load problem back then...
