### ISSUE TITLE
webui is crashing when modifing user roles and the user lacks permission for it

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2618]
webui/package#remove_role threw this 0 times
<pre>
Package::WritePermissionError: No permission to modify package &#39;devtodo&#39; for user &#39;puzel&#39;
</pre>
[https://build.opensuse.org/package/remove_role/utilities/devtodo](https://build.opensuse.org/package/remove_role/utilities/devtodo)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/588cf67c9f3d10000d000000)

**Comment by adrianschroeter** [comment]
most likely an issue when the login timed out.

**Comment by bgeuken** [comment]
The checkboxes for changing the roles are disabled when a user doesn't have permissions for doing so. So the only way, by now, to create this exception would be to manipulate the html.
Which we don't support.

=> closing
