### ISSUE TITLE
Link to "add repository page" vanished in package view

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2622]
We used to have a link to add repositories in the build result view when no repo is defined in the project.
The link still exists on project level, but not in package show page.

While this sounds nice-to-have, it breaks currently our appliance testing and should be fixed soon therefore.

Found by @M0ses in kanku.

**Comment by M0ses** [comment]
Hints:

* I think the link should be (and gets) generated in [_no_repositories.html.erb](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/views/webui/package/_no_repositories.html.erb#L3)
* I see the text including the "build targets" link in the html source but it is not shown (neither in firefox nor in chromium) on the page
* I´m wondering why it is not found by rspec/capybara.
