### ISSUE TITLE
Editing linked packages via the web UI causes unresolvable merge conflicts

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#2628]
which also can't easily or automatically be repaired from the command line:

```
matthias@mPad-X230 ~/E/O/h/lutris> osc up
Link "home:Mailaender:branches:games:tools/lutris" cannot be expanded:
 could not apply patch 'project.diff'
Use "osc repairlink" to fix merge conflicts.

matthias@mPad-X230 ~/E/O/h/lutris> osc repairlink
BuildService API error: source link never worked
```

I always end up deleting the _link and re-uploading all files.

**Comment by adrianschroeter** [comment]
first of all, don't use old plain links with project.diff, but use branches it helps a lot on merging.
(osc linktobranch if you want to convert your (not yet broken) sources).

On the other hand, trying to repair manually and failing is not really an OBS bug ;)

It is quite normal that you get conflicts and when using branches OBS behaves like any other SCM tool (it even uses the same tools in background like diff3).

**Comment by Mailaender** [comment]
How do I fork a package in a branch of my choice the correct way?
