### ISSUE TITLE
Package automation

### ISSUE THREAD

**Issue by surias** [openSUSE/open-build-service#2640]
hi,I am working in IBM.How to integrate IBM's AIX operating system to the Open Build Service as like other linux distributions.

**Comment by adrianschroeter** [comment]
90% of the work is done when you add the support to the build script. We can do the rest easily afterwards (or helping you). Have a look here how to do it for the build script:

 https://github.com/openSUSE/obs-build/blob/master/HOWTO.add_another_format

But please use our mailing list for such kind of questions in future.

**Comment by bgeuken** [comment]
Our mailing list -> opensuse-buildservice@opensuse.org ;-)

We are also reachable via IRC: irc://irc.opensuse.org/opensuse-buildservice

**Comment by surias** [comment]
Hi,In our Company already we are using RPM packaging format.Actually my question is how to run the OBS in the AIX platform for packaging.

**Comment by adrianschroeter** [comment]
You still need to have a way how to run a new aix instance (or do a chroot like setup) for each build. That must be implemented in the build script as well.

You can maybe misuse the preinstallimage support for that by providing a manual created AIX image.

The OBS server part will be really easy to add for us, when you can provide us a patched build script which builds a single package by manually calling.

**Comment by adrianschroeter** [comment]
I suppose you can't install the AIX base system via rpm, right? Therefore the preinstallimage ...

**Comment by surias** [comment]
hi am a fresher in packaging. can you say simply how to get AIX support to
the open build service?
