### ISSUE TITLE
server side source services did not run when linked project was updated

### ISSUE THREAD

**Issue by luizluca** [openSUSE/open-build-service#2647]
Hello,

I have a local OBS instance running without problems. I created a project in order to build nvidia packages for tumbleweed. I just replicated all packages from (https://build.opensuse.org/package/show/X11:Drivers:Video) into new packages inside my project using links like this:
```
<link project='openSUSE.org:X11:Drivers:Video' package='nvidia-gfxG04'/>
```
I also created a project source service conf (_project) in order to overwrite source service from package that are "disabled":
```
<services>
  <service name="download_files" mode="trylocal"/> 
</services>
```
It works nicely when I run "osc service remoterun" following a rebuild. However, I got a problem when the linked packaged updated nvidia version. I was expecting that OBS would trigger its source service (including the project one) and download the files whenever the linked project got updated. However, it did not happened. I could only fix the packages when I manually called "osc service remoterun".

Did I do something work or was OBS expected to run its "project level" source service when the linked packaged got updated?

**Comment by luizluca** [comment]
BTW, I'm using 2.7.3-1 version from build.opensuse;org for SLE12

**Comment by adrianschroeter** [comment]
we don't trigger services of linked packages on purpose because this would create to much load easily and your instance could be handled like an DoS attacker.

I think it should be needed in your case also if you would use either branches or (if you have no local modifications) just use the project link to use the sources from remote.

**Comment by luizluca** [comment]
@adrianschroeter , I see. A bunch of packages trying to download a remote file at the same time would be a mess.

Nvidia packages are in public build.opensuse.org but without source tar, with a configured source service (but also disabled) and absent source tar. My local project simply undo the disable part, letting OBS download and build them.

It would be nice to have a source service trigger that would only launch when source download service provides a missing spec source file (with a long random wait window in order to reduce DDOS behavior).  I'll implement that on a cron job with osc but it would be nice to have it directly on server.
