### ISSUE TITLE
build target

### ISSUE THREAD

**Issue by surias** [openSUSE/open-build-service#2650]
when am using own OBS,am trying to build target but it shows "Sorry, you are not authorized to this NilClass." what it means how to rectify

**Comment by adrianschroeter** [comment]
Can you tell us your exact version and the way how you try to create the "build target" ?

**Comment by surias** [comment]
AIX version 6

**Comment by lethliel** [comment]
Please don't start with the open-build-service for a new format. 
To be able to build AIX packages the new format needs to be added to the underlying build script first:

https://github.com/openSUSE/obs-build

Here you can find a Howto on new formats: https://github.com/openSUSE/obs-build/blob/master/HOWTO.add_another_format

If you need help implementing a new format  please refer to the mailing list:
opensuse-buildservice@opensuse.org
Link to archive: https://lists.opensuse.org/opensuse-buildservice/
