### ISSUE TITLE
webui cuts some logfiles

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2651]
We noticed that some logfiles get cut in webui logfile (reported as used to work). Not sure what the trigger is (new kiwi, mutibuild, ...).
osc, api and download shows them correctly.

Observed only for kiwi builds so far, but in multiple OBS instances.

Example:

https://build.opensuse.org/package/live_build_log/openSUSE:Factory:ARM/JeOS:E20-efi.aarch64/images/aarch64

**Comment by adrianschroeter** [comment]
I am going to fix our OBS appliances to see if it dependends maybe on newer kiwi

**Comment by bgeuken** [comment]
btw. raw build log is complete: https://build.opensuse.org/build/openSUSE:Factory:ARM/images/aarch64/JeOS:E20-efi.aarch64/_log

**Comment by ChrisBr** [comment]
Fixed and monkey patched on build.o.o
