### ISSUE TITLE
Add Repositary

### ISSUE THREAD

**Issue by surias** [openSUSE/open-build-service#2653]
how to add repositary in my owm OBS

**Comment by surias** [comment]
![capture](https://cloud.githubusercontent.com/assets/25523085/22724326/6c5dc4f0-edeb-11e6-9577-5b3c79e65905.PNG) 
it is showing like this the options are disabled.Plz help me to add repositary to my own OBS

**Comment by adrianschroeter** [comment]
Please do not use the issue tracker as support interface. Please go to our mailing list instead.
