### ISSUE TITLE
creating repositary

### ISSUE THREAD

**Issue by surias** [openSUSE/open-build-service#2660]
![capture](https://cloud.githubusercontent.com/assets/25523085/22776149/96e4f04c-eed4-11e6-9576-f48886257c90.PNG)
after clicking the interconnect in our own OBS.In the repositary of my project shows that "No repositary found"
![capture1](https://cloud.githubusercontent.com/assets/25523085/22776235/e7722264-eed4-11e6-972e-a75787742a56.PNG)
how can i create repositary such as ubundo,PowerKVM etc

**Comment by adrianschroeter** [comment]
Do you listen when I told you to use mailing list instead?

I am really happy to help you with AIX build support, but don't misuse our tracker :/

**Comment by surias** [comment]
okey

**Comment by surias** [comment]
how to add distributions

[image: Inline image 1]

**Comment by surias** [comment]
how can i add new repositary other than opensuse
