### ISSUE TITLE
Buildresults view is incorrect

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#2673]
While packaging something I noticed a mismatch between packages shown in the project overview page and the project monitor page.

The first one is correct, the other isn't.

This happened after deleting some of the packages.
While writing this I realize that the buildresults on the project overview is also wrong, eg. "Succeeded: 6" when there are only 3 packages.

Project overview:
  https://build.opensuse.org/project/show/home:bgeuken:branches:OBS:Server:Unstable

Project monitor page:
  https://build.opensuse.org/project/monitor/home:bgeuken:branches:OBS:Server:Unstable

**Comment by bgeuken** [comment]
@openSUSE/open-build-service Looks like a regression caused by the buildresult changes we've made

**Comment by hennevogel** [comment]
The package buildresults discard dangling results (Package.repositories is authoritative) while the project one does not. See PR #2654 for a discussion about this. 

We will need to find a way to tell people about this in the future...
