### ISSUE TITLE
obs in AIX

### ISSUE THREAD

**Issue by surias** [openSUSE/open-build-service#2702]
hi,
In IBM already jenkins is used to building the package.We are trying to use OBS for package building in AIX platform.In jenkins we can able connect AIX machine with jenkins and packaging can be done. Similarly,is there any way to connect our machine and build the package.

**Comment by adrianschroeter** [comment]
yes

**Comment by surias** [comment]
can u tell me how will you connect our AIX machine to your open build service? if it is possible please help me to build the package in the AIX platform.
