### ISSUE TITLE
The OBS service is ignoring one of my Prefer rules

### ISSUE THREAD

**Issue by Zenitur** [openSUSE/open-build-service#2706]
Sorry for my bad English. I have a small repository with Qt 5 for SLES 11 and 12. There is it: https://build.opensuse.org/project/show/home:linux4humans:qt5.6 For SLES 11, Qt 5 asks libXCB >= 1.4, so I had upgrade xorg-x11-libxcb and xorg-x11-libX11. Qt 5 was successfully built.

![default](https://cloud.githubusercontent.com/assets/3435752/23079857/3b31f9a8-f581-11e6-80ba-3ea301c4e4dd.png)

Today I decide to switch packages like "xorg-x11-libX11-devel" to "libX11-devel". In upstream, it was switched between openSUSE 12.2 and 12.3 in X11:Xorg repository. This is a part of SPEC file for openSUSE 12.2:

` %package devel`
` Summary: Development files for the Core X11 protocol library`
` Group: Development/Libraries/C and C++`
` Requires: libX11-6 = %version`
` Requires: libX11-xcb1 = %version`
` # O/P added for 12.2`
` Provides: xorg-x11-libX11-devel = 7.6_%version-%release`
` Obsoletes: xorg-x11-libX11-devel < 7.6_%version-%release`

So if any package asks xorg-x11-libX11-devel, libX11-devel will be installed. I have been switch xorg-x11-libX11 to libX11-6 in my repository. When I saw error "have choice between xorg-x11-libX11-devel and libX11-devel". I clicked this:

![-1](https://cloud.githubusercontent.com/assets/3435752/23079875/4d2c76d8-f581-11e6-8a53-014f504b8fa6.png)

And type this:

![-2](https://cloud.githubusercontent.com/assets/3435752/23079900/65c70fa0-f581-11e6-8487-99359e298828.png)

When I pressed Apply, "have choice" disappeared and compilation starts. But OBS starts using only libxcb-devel and ignoring libX11-devel.

![-4](https://cloud.githubusercontent.com/assets/3435752/23079914/7546af6c-f581-11e6-8b5f-6729d895ecc9.png)
![-5](https://cloud.githubusercontent.com/assets/3435752/23079924/8075f76c-f581-11e6-9f9a-709555d125df.png)

Why OBS is using one of parameters and ignoring another? I tried to add:

![-3](https://cloud.githubusercontent.com/assets/3435752/23079955/9f98cbba-f581-11e6-871e-f1fe5221b42c.png)

It did't help. It looks like a bug.

**Comment by adrianschroeter** [comment]
Prefer is only for choice errors. You might be more successful with "Substitute" rules if the package is directly BuildRequied.

Use "osc buildinfo -d ..." to see why exactly a package got chosen.
