### ISSUE TITLE
Expanding review comments scrolls

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#2708]
https://build.opensuse.org/request/show/455298 is just an example - you will find thousands. The repo-checker bot adds the error as review comment. Which is shortened with [+] in the review box. If you expand that, the comment is expanded, but the page also scrolls to the top.

**Comment by bgeuken** [comment]
@mdeniz Looks like a regression of #2594 and probably easy to fix:-)

**Comment by jberry-suse** [comment]
Rather annoying. Now that I have working OBS development environment I have fixed.

**Comment by jberry-suse** [comment]
Should be closeable now that the change has been accepted.

**Comment by bgeuken** [comment]
Awesome! Thanks a lot:-)
