### ISSUE TITLE
Ghost downloaded files prefixed with _service stay

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#2709]
When a _service file is removed and a submit request is issued the target repository keeps the _service_name-version.tar.gz which is often redundant to the real name-version.tar.gz I just uploaded and will result in rejection by automated bot accounts. A simple workaround is to change one file via the web interface. I usually just add 1 second to the .changes file stamp. This seems to trigger a cleanup that otherwise is impossible to achieve. It should be done automatically on submit request accept.

**Comment by adrianschroeter** [comment]
seems to be a problem of source copy using noservice=1 in backend?

**Comment by adrianschroeter** [comment]
I am not able to reproduce it (see home:adrianSuSE uranium.new)

So, please reopen when you have reproduced it on build.opensuse.org .
