### ISSUE TITLE
[backend] build job doesn't pick the latest spec produced by services

### ISSUE THREAD

**Issue by k0da** [openSUSE/open-build-service#2714]
Issue/Feature description
====================
in case there are multiple spec files produces by different services, built doesn't pick the latest

Expected result
============
Latest processed spec must be used

How to Reproduce
===============
1. use tar_scm service to clone and tar sources
2. extract spec file from the same repository
3. run set_version service on it

Further information
===============
https://build.opensuse.org/package/live_build_log/home:k0da:scm_test/scm_test/openSUSE_Leap_42.2/x86_64

_service reproducer
```
<services>
  <service name="tar_scm">
      <param name="url">https://github.com/k0da/scm_test.git</param>
      <param name="scm">git</param>
      <param name="extract">scm_test.spec</param>
      <param name="revision">master</param>
  </service>
  <service name="set_version">
  </service>
</services>
```

**Comment by adrianschroeter** [comment]
works for me .... seems it does not for you since you specify the filename with different suffix in your spec file so it can't match?

Please fix that and reopen in case it is still broken for you.

**Comment by k0da** [comment]
there is another spec is generated with correct version specified. It just didn't picked by build job
https://build.opensuse.org/package/view_file/home:k0da:scm_test/scm_test/_service:set_version:tar_scm:scm_test.spec?expand=1

**Comment by k0da** [comment]
and for some reason I can't reopen issue

**Comment by adrianschroeter** [comment]
I see, fixed in build script and deployed

**Comment by adrianschroeter** [comment]
(the build failure in your package is due to lacking compression service)

**Comment by k0da** [comment]
@adrianschroeter thank you.. This example is just to show a bug.. Sure, compression is needed
