### ISSUE TITLE
Track statistics on the openSUSE staging process to gain feedback on changes

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/open-build-service#2724]
My [hackweek project](https://hackweek.suse.com/15/projects/track-statistics-on-the-opensuse-staging-process-to-gain-feedback-on-changes) is looking to provide a variety of statistics and metrics relating to the staging workflow on OBS. I've spent some time setting up a local OBS, obs_factory engine, looking through the database structure, and reviewing tools designed to present metrics.

At this point it seems prudent to run some things past those more familiar with OBS to see what sort of solution might be of interest.

The biggest hurdle seems to be trying to create timeseries information from event data by walking the events backwards from the known state (ie current) to find states of interest. At some point whatever solution is built will need access to the relevant data to do some aggregation and store intermediate results that can then be drawn on for presenting to the user.

There are currently some graphs and such on the status page (using flot I believe) which could be a basis for further graphs, but it seems like using one of the pre-existing tools might be more useful and allow for future work to present other information of interest. One such tool is [Metabase](/metabase/metabase) which I have been exploring locally. The one requirement of such tools is that data is either fed to them or they have access to the source. Is read access to ~5 tables of interest relating to requests something feasible for such a project? Alternatively, I can write something that polls and scrapes data using the APIs into local storage that can then be used for presentation, but this seems like unnecessary extra work.

For those interested, a bit more on the topic of generating timeseries data. As an example of what I am talking about. Consider presenting a graph of the request backlog against Factory over time or the number of empty stagings over time. There is event information for when requests are staged since reviews are added, and when removed (either the request declined (since the unstage event is not recorded after a decline), new review opened and previous accepted [new staging], or request is accepted). Assuming one has a known state from which to start it would seem possible to walk this event history and annotate states of interest. Given that the current state can be queried which indicates what requests are currently in a staging that provides a starting point. Assuming the script can be stopped anytime it encounters an annotation again (or other mechanism) the job can be run on some timely basis to annotate the desired information.

A totally different approach could be to poll in the fashion of monitoring software where the metric of interest is queried live repeatedly and stored in a timeseries database for later presentation. This approach is far simpler, but suffers from having to add load to OBS internally or externally to poll the information and cannot backfill the data. As such it seems preferable to walk the event tree.

Some questions:

- Does it make sense to place something of this nature into OBS itself or a separate project? Originally I was thinking obs_factory, but it seems this might be well suited as a simple cron script and some metrics presentation software setup.
- Can I get read access to the following tables (or in leu of that perhaps a partial db dump)?
  - bs_requests
  - bs_request_actions
  - events
  - reviews
  - comments might be interesting for looking for certain leaper responses
- Is there anything existing that I am not aware of that should be looked at?

I look forward to your thoughts.

**Comment by hennevogel** [comment]
Please do no misuse the github issues as discussion forum. This is for requesting specific new features or bugfixes. If you want to discuss things use our mailing list or approach us next time, okay? :-)

Regarding time series data (for more metrics) we are already planing of introducing [Influx Data](https://www.influxdata.com/) for that. If you want to discuss this further (like details, timeline etc) or want to 'use' this for the 'obs_factory' engine or want to do something else for some specific OBS instance (like the openSUSE one) please do so on the mailing list. 

See you there :-)

**Comment by jberry-suse** [comment]
Each project has their own preference. After re-reading the issue template it does not make any reference to discussion, but I am going to guess that it is intended to fall under "questions". I'll start a thread on the mailing list.
