### ISSUE TITLE
Build status table missing a row

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/open-build-service#2725]
Somehow images/local is missing from the build status, both ```osc results``` and the Web UI do not show it.
The WebUI specifies an incorrect rowspan for the images label, which screws up the table layout.

It's shown correctly for the branch source.

Link: https://build.opensuse.org/package/show/home:Vogtinator:branches:openSUSE:Factory/knewstuff

Screenshot:

![](https://i.imgur.com/6yEoraz.png)

**Comment by adrianschroeter** [comment]
Known regression, see https://github.com/openSUSE/open-build-service/pull/2654

**Comment by adrianschroeter** [comment]
more and more people are running into this -> P2

**Comment by adrianschroeter** [comment]
backend should report it in excluded state here due to the fact that only a number of projects are allowed to use it.

You need to remove it in any case to get your source building

**Comment by Vogtinator** [comment]
> backend should report it in excluded state here due to the fact that only a number of projects are allowed to use it.
> You need to remove it in any case to get your source building

This is just a package that was still laying around from some tests and I noticed this bug while deleting it

**Comment by hennevogel** [comment]
This is true for all architectures the backend has no buildresults for. For instance if there is an architectures enable but you have no worker for it...

**Comment by adrianschroeter** [comment]
no, it would be in scheduled or failed.

This case is only when projects are limited via certain architecture via limit_projects in backend config.
