### ISSUE TITLE
changing _service in _linked package does not work

### ISSUE THREAD

**Issue by seife** [openSUSE/open-build-service#2727]
Running OBS 2.7.3

How to reproduce:

osc linkpac systemsmanagement:crowbar:3.0 crowbar-core home:seife
osc co home:seife crowbar-core
cd crowbar-core
osc up -e
vi  _service # enable services, change e.g. git repo
osc commit

Result: service will not run remotely
osc service rr

seife@vbox-seife:~/buildservice/home:seife/crowbar-core> osc service rr
Server returned an error: HTTP Error 404: Not Found
could not trigger service run for project 'home:seofe' package 'crowbar-core'
&lt;status code="404"&gt;
  &lt;summary&gt;no source service defined!&lt;/summary&gt;
  &lt;details&gt;404 no source service defined!&lt;/details&gt;
&lt;/status&gt;

the check here https://github.com/openSUSE/open-build-service/blob/master/src/backend/bs_srcserver#L332 fails, leading to the 404.

If I issue an "osc linktobranch" in my repo, the service immediately starts executing.
I'd rather have a plain link+diff instead of a branch.

**Comment by adrianschroeter** [comment]
services are not suppose to work on non branches. They only work on not expanded sources and it would be way to much overhead to rerun them for all links when changing the base.

Works as designed...
