### ISSUE TITLE
Add a button to refresh incoming reviews/requests

### ISSUE THREAD

**Issue by ismail** [openSUSE/open-build-service#2729]
I'd like to have https://build.opensuse.org/user/show/namtrac open all day and the only way to see if there's any new incoming review or request I have to refresh the whole page. It would be nice if there were two refresh buttons to refresh reviews/requests without reloading the whole page.

**Comment by mschnitzer** [comment]
Or probably some Ajax request that automatically reloads the content every 30 seconds? @ismail would that be better?

**Comment by ismail** [comment]
@mschnitzer If it's ok for the server load, that works even better.

**Comment by hennevogel** [comment]
constant polling is crazy. please don't do that.

**Comment by mschnitzer** [comment]
@hennevogel why should a refresh of 30 seconds of a certain data be crazy? That's an acceptable time frame. It should not load the whole page again but just some data. Many web service behave like this that you have a background service. Cannot really imagine this will harm us.

**Comment by ChrisBr** [comment]
@ismail quick workaround: change the number of pagination

e.g from 
``Show 25 entries``
to
``Show 10 entries``

This will trigger a new AJAX call reloading the table.

**Comment by ChrisBr** [comment]
@ismail done in #2842, will be available after the next deployment of master!
