### ISSUE TITLE
Suse::Validator fails for controller specs

### ISSUE THREAD

**Issue by evanrolfe** [openSUSE/open-build-service#2734]
Issue/Feature description
====================
The method [ApplicationController.validate_action](https://github.com/evanrolfe/open-build-service/blob/feature%2Frefactor_and_test_about_controller/src/api/app/controllers/application_controller.rb#L73) will fail for rspec controller tests. This happens because controller specs do not render views by default, so the `content` passed to [Suse::Validator.validate](https://github.com/evanrolfe/open-build-service/blob/feature%2Frefactor_and_test_about_controller/src/api/lib/opensuse/validator.rb#L68) is an empty string which causes the method to raise an error.

A work-around is to add `render_views` to the controller spec but if a developer in the future writes a controller spec and does not know that they have to add `render_views` to make it work, they could spend a lot of time trying to figure this out as I did yesterday..

So I think we have a couple options to fix this:
1. Tell Suse::Validator.validate not to run if its run from a controller specs. (Not sure if we can specify only controller specs here? We might have to disable it for ALL tests which would not be ideal because we want it to fail in feature specs for example).
2. Make it so all controller specs call `render_views`

Expected result
============
`Suse::Validator.validate` does not raise an exception when called from a controller spec.

How to Reproduce
===============
1. Create an API controller which calls the `validate_action` class method on a response
2. Create a controller spec which queries the controller
3. Run the spec, you will get this error:
```
     # Suse::ValidationError:
     #   Document is empty, not allowed for about
     #   ./lib/opensuse/validator.rb:99:in `validate'
```

**Comment by adrianschroeter** [comment]
We want to have the validator running at least for API calls to ensure that we don't break the rendering or have a not matching schema.

But you may disable it for rspec as long no api calls get tested there (only webui).

**Comment by evanrolfe** [comment]
I'm going to close this issue since the work around is fine for the meantime. If I have some spare time in the future I will look at implementing a better solution to this again.
