### ISSUE TITLE
Support variables in _service files

### ISSUE THREAD

**Issue by lbeltrame** [openSUSE/open-build-service#2739]
The KDE team in openSUSE uses a lot of _service files during the normal package development. Usually these refer to upstream software that provides multiple packages with the same version (e.g., 16.08). When upstreams release a new version, these versions are bumped.

In our project configuration we have already some variables pointing to these versions. What it would be nice is to allow them to be used in _service files, so that a single change in the prjconf propagates to all _service files avoiding checking out 100+ packages just to change one version string.

cc @Vogtinator (Fabian Vogt)

**Comment by adrianschroeter** [comment]
Can you draw a bit more concrete example with variable names and how to change them?

Without knowing any details, this sounds to me like you want to write a kde specific service and use them in your project. If it is okay to adapt these changes during buildtime (they don't change buildrequires directly) you could just host this service in your project.

**Comment by adrianschroeter** [comment]
alternative solution would be to provide these macros via some base package and just consume it? (no need of services then)

**Comment by lbeltrame** [comment]
Indeed, here's a more clear example:

In one of our projects (prjconf):

```rpm
Macros:
%_with_qt56      0
%_without_lang 0
%_kapp_version 17.03.50
:Macros

%if 0%{?suse_version} > 1320
Macros:
%_with_qt56      1
:Macros
%endif
```

And a typical _service is 

```xml
<services>
  <service name="tar_scm">
    <param name="url">git://anongit.kde.org/akonadi-search.git</param>
    <param name="scm">git</param>
    <param name="versionformat">17.03.60git.%ci~%h</param>
  </service>
  <service name="recompress">
    <param name="file">*.tar</param>
    <param name="compression">xz</param>
  </service>
  <service name="set_version" />
</services>
```

Note the version in `versionformat`. What we'd like to have is populate that with the content from the prjconf, in this case `%_kapp_version`.

**Comment by adrianschroeter** [comment]
we found a solution on IRC via an own service like drawn in project home:adrianSuSE:branches:KDE:Unstable:Framework

**Comment by jfkw** [comment]
Is the mentioned solution https://build.opensuse.org/package/show/KDE:Unstable:Frameworks/obs-service-kde AKA `set_version_to`?

**Comment by Vogtinator** [comment]
Yep. You can look at the other packages in the project for example _service files.
