### ISSUE TITLE
"unresolvable: nothing provides <NULL>" build issue

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/open-build-service#2759]
Hi
today I recognized that the build state of https://build.opensuse.org/package/show/windows:mingw:win32/mingw32-umbrello-installer shows "unresolvable: nothing provides <NULL>". I checked that everything with the package is okay.

**Comment by mlschroe** [comment]
We switched to another dependency parser which was to strict and refused to parse spec file dependencies that contained two '==' signs. Now changed back to the old parser and your packages build again.

Thanks for the report.
