### ISSUE TITLE
build repository names with "+" included yield "Internal server error 500" when trying to access build logs

### ISSUE THREAD

**Issue by okurz** [openSUSE/open-build-service#2773]
Issue/Feature description
====================

Using `osc meta prj -e` I added repositories to my project with a '+' included in the name. This seems to work until I wanted to access the build logs over the webui clicking on "Failed" which gave me an "Internal server error 500". Changing the repository to a name without the '+', e.g. by replacing with '_' fixed that.

Expected result
============

Either '+' should be disallowed from entering (xml check) or the links on the web ui should work.

How to Reproduce
===============
1. create project
2. create repository with '+' in name
3. add a package which fails build in this repository
4. submit to OBS
5. try to access "Failed" link over webui on the repository

**Comment by ChrisBr** [comment]
@okurz which instance? I can't find logs neither in external nor internal OBS :/

PR #2865 could be related though.

**Comment by okurz** [comment]
see for yourself: https://build.opensuse.org/package/live_build_log/home:okurz:test_obs_issue_2773/medo/openSUSE_Tumbleweed+foo/x86_64 . I created this test project with a repo with "+" in the name. From https://build.opensuse.org/package/show/home:okurz:test_obs_issue_2773/medo# one can try to access the build log of the package which yields the URL above with the according server error.

**Comment by simotek** [comment]
Issue also happens with a + in the package name
  * https://build.opensuse.org/package/live_build_log/home:simotek:patterns/patterns-devel-C-C++/openSUSE_Tumbleweed/x86_64

**Comment by mschnitzer** [comment]
Should be fixed with 491b375

This fix will be applied soon on production (build.opensuse.org)
