### ISSUE TITLE
Failed to create the attribute with error 403

### ISSUE THREAD

**Issue by nilxam** [openSUSE/open-build-service#2782]
Issue/Feature description
====================
As part of factory-staging group, I've the rights in openSUSE:Factory:Staging project, in the past, I've no problem creating a attribute, however I got error 403 now, which affects executing the factory staging tool. I tried api call too, the complete error message below,

<pre>
mlin@rana:~> osc -d api -X POST /source/openSUSE:Factory:Staging/_attribute/openSUSE:LockedBy -T fake_lock
POST https://api.opensuse.org/source/openSUSE:Factory:Staging/_attribute/openSUSE:LockedBy
Server returned an error: HTTP Error 403: Forbidden
Date: Thu, 09 Mar 2017 07:57:40 GMT
Server: Apache/2.4.23 (Linux/SUSE)
Strict-Transport-Security: max-age=31536000
Cache-Control: no-cache
Vary: Accept-Encoding
X-XSS-Protection: 1; mode=block
X-Opensuse-Runtimes: {"view":1.0777139686979353,"db":44.57578399999999,"backend":0,"xml":0.081272}
X-Request-Id: 3de017b5-488d-485a-a977-56631b6c1504
X-Opensuse-APIVersion: 2.7.51.git20170308.8cb06cb
X-Runtime: 0.087399
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Opensuse-Errorcode: not_authorized
X-Powered-By: Phusion Passenger 5.0.30
Status: 403 Forbidden
Content-Type: application/xml; charset=utf-8
Connection: close
Transfer-Encoding: chunked
 
<status code="not_authorized">
  <summary>You are not authorized to create this Attrib.</summary>
</status>
 
You are not authorized to create this Attrib.
</pre>

Expected result
============
No 403 error if I've the proper rights.

How to Reproduce
===============
Doing a api call to create a attribute.

**Comment by adrianschroeter** [comment]
This is an attribute which is granted to the maintainers, maxlin-factory is a maintainer.

Also the error message is incomplete since it does not tell which attribute (one can post multiple)

**Comment by lnussel** [comment]
we urgently need this fixed. staging work is not possible with that bug

**Comment by hennevogel** [comment]
This should work now again.
