### ISSUE TITLE
Fedora_24 builds failing

### ISSUE THREAD

**Issue by highperformancecoder** [openSUSE/open-build-service#2798]
Issue/Feature description
====================
Fedora_24 builds complaining of the following message from rpm:

/usr/bin/rpmdb: error while loading shared libraries: liblua-5.3.so: cannot open shared object file: No such file or directory

Further information
===============
* A link to an OBS instance showing the issue

https://build.opensuse.org/package/live_build_log/home:hpcoder1/TkTable/Fedora_24/i586

All my Fedora_24 builds fail for exactly the same reason. They built correctly in the past. Fedora_25 builds are fine.

* Exact server version (in case a private instance is used)

**Comment by adrianschroeter** [comment]
Fedora released a new rpm package to update tree requiring new libs ... added a special rule for update repo for Fedora 24
