### ISSUE TITLE
Source Service tar_scm problem: Files could not be expanded: service error: UnboundLocalError: local variable 'changesauthor' referenced before assignment 

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#2802]
I am reporting this here because it works on osc but not when run in the server. I dont use the docker container on the server side.

Error Message one the Server Side:

Files could not be expanded: service error: UnboundLocalError: local variable 'changesauthor' referenced before assignment 

with the current revision 0.7 of obs-service-tar_scm from openSUSE:Tools. Old version 0.6 works.

I just tested the old _service file from the package obs-server. below.  Local Source Service with osc works on the same _service file. I guess from the error message its something with the changesgenerate.

`<services>`

  `<service` name="tar_scm">
    `<param` name="versionformat">2.7.51.git%cd.%h</param>
    `<param` name="url">git://github.com/openSUSE/open-build-service.git</param>
    `<param` name="scm">git</param>
    `<param` name="changesgenerate">enable</param>
  `</service>`
  ...
`</services>`

From the error message I would guess its a problem in obs-service-tar maybe ?

**Comment by mmohring** [comment]
Submitted it also as tar_scm issue https://github.com/openSUSE/obs-service-tar_scm/issues/140

**Comment by ChrisBr** [comment]
So we can close this one, no?
