### ISSUE TITLE
Problems with uploading files for a package

### ISSUE THREAD

**Issue by TheAssassin** [openSUSE/open-build-service#2805]
Issue/Feature description
====================
I found two issues with the package file upload.

1. `+` characters in file names is replaced by a space, unless you explicitly provide a name
1. Files downloaded using the download option are renamed to `_service`, regardless of whether you explicitly provide a name or not

Expected result
============
1. The `+` character should not be decoded as a space, but stay in the file name
1. Downloaded files should either use the name the user provides, or accept the server name (e.g. by looking at the `Content-Disposition` header or by using the URL component)

How to Reproduce
===============
1. Upload a file with one or more `+`es in its name
1. Use the file downloader to download a file

Further information
===============
The problem occurs quite often when you have to deal with Debian packages, since they use `+` a lot to name their files. This kind of behavior is usually caused by a URL decoder accepting `+` as a space.
I have had these problems with Chromium 56 on Ubuntu Xenial, I haven't got to testing with other browsers. I am not sure if that has any influence on the first bug.

**Comment by adrianschroeter** [comment]
this got fixed
