### ISSUE TITLE
Files could not be expanded: service error: See 'docker run --help'.

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/open-build-service#2806]
Issue/Feature description
====================
After updating file _service at [1] and [2] with a valid git tag at the below mentioned project an error message "Files could not be expanded: service error: See 'docker run --help'." is displayed in the obs web ui and no compressed tar ball is generated.

Expected result
============
The tar_scm service should create a compressed tar ball according to the content of the _service file.

How to Reproduce
===============
Open [1] or [2]

Further information
===============
* https://build.opensuse.org/package/show/windows:mingw:win32/mingw32-umbrello [1]
* https://build.opensuse.org/package/show/windows:mingw:win64/mingw64-umbrello [2]
* local osc build works

**Comment by mschnitzer** [comment]
Hey, thanks for the issue report. @adrianschroeter is currently working on it.  Should be fixed soon :-)

**Comment by mschnitzer** [comment]
Seems that it is fixed now. Can you verify that @rhabacker ?

**Comment by rhabacker** [comment]
I can confirm that building now works again. Thanks for your support.
