### ISSUE TITLE
Users of branches of hidden projects

### ISSUE THREAD

**Issue by jpwhiting** [openSUSE/open-build-service#281]
When branching a package from a hidden project the only users on the new project are the person who branched. Later when submitting a package back to the original project, other users who could accept the submission aren't able to since they can't access the branch project.  A fix is on jpwhiting open-build-service 2.3 branch that fixes the issue by adding all users of the project as readers on the branched project when it is created.
https://github.com/jpwhiting/open-build-service/commit/b78d29a4f8112620014faa9ce381b78a690e4105

**Comment by vpereira** [comment]
not reproducible anymore. I was able to run through the steps described and see the diff. 

@jpwhiting Thank you for the detailed description!
