### ISSUE TITLE
[backend] worker build code cannot be loaded anymore

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#2856]
The following happens with current git master when booting a worker:

Mär 17 17:54:42 neptun obsworker[13907]: Run 16 obsworker using /tmp/ 
Mär 17 17:54:42 neptun obsworker[13907]: Type of obsworker is KVM virtual machine
Mär 17 17:54:44 neptun obsworker[13907]: Fetching initial worker code from http://api.blabla.com:5252
Mär 17 17:54:44 neptun obsworker[13907]: chmod: cannot access 'bs_worker': No such file or directory

So the workers build code cannot be loaded anymore. I think this has to do with commit: ba27c91351878bc297ec4baba0bd488a2f3b568d:

[backend] only allow plain files in cpio_sender    
No devices, sockets, directories, symlinks please...

Does build code not contain symlinks ?

**Comment by mmohring** [comment]
Going back to git commit b7407126ecb3661b90e27cb0eda36e122ca40ea5 worked.

**Comment by adrianschroeter** [comment]
fixed again
