### ISSUE TITLE
Refactor UnregisteredUser error messages

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#2868]
Error messages look really ugly. Let's look at the sign up error when you keep all fields blank:

![screenshot at 2017-03-21 08-44-53](https://cloud.githubusercontent.com/assets/8287131/24137142/c4547a5e-0e12-11e7-85a3-affb7e98d1f2.png)

There is absolutely no structure and is nothing what we should show the user. We should just show relevant information like:
```
* Please provide a password
* Please provide a username
* Please provide an email
```

Currently, everything is shown to the user (even things he has no influence in; for example `password_hash_type`)

See here for reference: 
https://github.com/openSUSE/open-build-service/blob/ca026f81b20709156ead8e3859fab66259bac38a/src/api/app/models/unregistered_user.rb#L61

**Comment by Ana06** [comment]
We should also remove the `.` at the end of our custom messages. For example: https://github.com/openSUSE/open-build-service/blob/ca026f81b20709156ead8e3859fab66259bac38a/src/api/app/models/user.rb#L63

**Comment by mschnitzer** [comment]
@Ana06 it depends how you want to display them. If you list them as in my example above, you don't need `.` at the end.

**Comment by Ana06** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix 2868: Refactor UnregisteredUser error message](https://trello.com/c/DX5xzNrp/316-fix-2868-refactor-unregistereduser-error-message)
