### ISSUE TITLE
[production][webui/package#update_build_log] ActionController::ParameterMissing: param is missing or the value is empty: repository

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#2883]
webui/package#update_build_log threw this 0 times
<pre>
ActionController::ParameterMissing: param is missing or the value is empty: repository
</pre>
[https://build.opensuse.org/package/update_build_log/office:goldendict/goldendict-master?arch=i586&amp;offset=0;&amp;initial=1&amp;_=1490149221269](https://build.opensuse.org/package/update_build_log/office:goldendict/goldendict-master?arch=i586&amp;offset=0;&amp;initial=1&amp;_=1490149221269)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/58d1df72d29534000d000000)

**Comment by hennevogel** [comment]
How is this a bug? :-)

**Comment by DavidKang** [comment]
Should be fixed with #2967
