### ISSUE TITLE
Backport fix to 2.8

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2898]
Please backport fix 491b3752ffff08ae25a80f9488462ce60767ccf7 to 2.8 branch.

Can't be just cherry-picked due to conflicts in test suite, not sure if we need that

**Comment by adrianschroeter** [comment]
@DavidKang can you do that?

**Comment by DavidKang** [comment]
@adrianschroeter, sure 😄

**Comment by DavidKang** [comment]
@adrianschroeter, done
