### ISSUE TITLE
Wrong repository errors in monitor

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2907]
Issue description
==============
Irritating and wrong errors reported for repository state appears. The errors seem not to be part of the _result file from the backend. I see such errors for example here (but also elsewhere):

 https://build.opensuse.org/project/monitor/home:adrianSuSE:NewProduct

Mouse over the repository state (the lorry) shows >20 lines of errors. Most errors seem not even to be possible in this project.

There are no repository errors when checking the backend data:

 osc api /build/home:adrianSuSE:NewProduct/_result

Expected result
============

Show the matching errors only

Further information
===============
* Wild guess, a caching issue mixing up results from other projects.

**Comment by ChrisBr** [comment]
@adrianschroeter can't reproduce, please provide a screenshot!

**Comment by hennevogel** [comment]
![screenshot from 2017-03-29 11-29-12](https://cloud.githubusercontent.com/assets/514785/24447957/f4e1dab6-1472-11e7-9504-a26ae8c672db.png)

**Comment by mdeniz** [comment]
This is closed thanks to #2929 2929
