### ISSUE TITLE
Internal representation for OBS's Kiwi Image files

### ISSUE THREAD

**Issue by mdeniz** [openSUSE/open-build-service#2918]
We are facing the design of the internal representation for a [Kiwi file](https://doc.opensuse.org/projects/kiwi/doc/#sec.description.config.xml) inside the OBS (see an example [here](https://build.opensuse.org/package/view_file/home:cbruckmayer/studio-13.2/config.kiwi)).

Kiwi files will live inside packages as they come and will be stored in the backend as a normal file, that is the authoritative storage for building images. Beside that, we want to able the user to manage and operate on Kiwi representations easily and as fast as possible.

The solution we decided to propose is to represent the Kiwi file internally as ActiveRecord models stored in the database. So, each time a Kiwi file is created/updated in the app (via API or WebUI) we need to parse it and create/replace all the objects related to that. And the outcome of this internal representation will be a  Kiwi file built at save time from the main model.

## Basic structure of models

The structure we plan to have live inside the namespace `Kiwi` and will look like:

```ruby
module Kiwi
  class Image < ActiveRecord::Base
    belongs_to :container, class_name: '::Package'
    has_one :description
    has_many :repositories
    has_many :packages
    # many more sections relationships here
    ...
  end

  # It needs to have a column named "xml" of type TEXT
  # to store the original section chunk
  class Section < ActiveRecord::Base
    belongs_to :image

    def to_xml
      xml
    end
  end

  # Each section is represented with a Section subclass model
  class Description < Section
  end

  # many more sub-classes of Section here
  ...
end
```

That way we can have a parser method in the `Kiwi::Image` class, something like:

```ruby
module Kiwi
  class Image < ActiveRecord::Base
    ...
    def parse!(file)
      # It recognizes each section in file and creates instances of the sections
      # filled with each chunk of the xml file
      description = Description.new(xml: xml_chunk_for_description)
      # many more assignations here
      ...
    end
    ...
  end
end
```

So, a possible controller can do:

```ruby
class Webui::KiwiImagesController < Webui::WebuiController
  ...
  def show
    @image = Kiwi::Image.find_or_initialize_by(filename: params[:file],
                                               project: params[:project],
                                               package: params[:package])
    if @image.new_record?
      # load the file from the backend (not shown here) and then parse it
      @image.parse!(file_loaded_from_backend)
    end
  end
  ...
end
```

## Incremental implementation

As we want a structure flexible enough to grow in terms of implementation. We have decided to start having the main section models (description, profiles, preferences, users group, drivers, repositories and packages) as just holders for each xml part of the whole file. That will be implemented in the `Kiwi::Section` model.

So, we will not parse the inner parts of those sections, but we will store the plain XML as text in the model that can be pasted directly to the final file.

From that base we can implement how it should work on each section incrementally having already a builder for the whole XML file from the beginning.

The sub-classes of `Kiwi::Section` we are going to implement will override the `to_xml` method with the proper generation of the xml based on the models it will have related.

## Details to decide

* Having a global `order` column in `Kiwi::Section` to allow recreating the file as close as it was before, or just not having any order at all and create the file consistently in our way
* In a point of time we will need to represent [other stuff](https://doc.opensuse.org/projects/kiwi/doc/#chap.description) not only the Kiwi file. How?
* What technology should we use to parse the xml file? (XPath, Nokogiri)
* What technology should we use to build the xml file? (XML Builder, handcrafted)
* How to validate the original file in order to be sure that we parse a proper Kiwi file? (we have the RNG schema [here](https://github.com/openSUSE/kiwi/blob/master/modules/KiwiSchema.rng))

Note: We already started to discuss this internally.

**Comment by evanrolfe** [comment]
As discussed in moises's [gist](https://gist.github.com/mdeniz/74d943812a360451309fe09c8f3fe8bf) I dont think we should duplicate the xml contents across the backend file and frontend database.

**Comment by bgeuken** [comment]
> Having a global order column in Kiwi::Section to allow recreating the file as close as it was before, or just not having any order at all and create the file consistently in our way
AFAIK, the order doesn't matter, except for repositories. And there it is just implicit. So we could either say that we only guarantee a fixed priority of repositories when the 'priority' attribute is used. Or we set priorities first time we parse an xml.

I would vote for the first option.

> In a point of time we will need to represent other stuff not only the Kiwi file. How?
I don't think we can answer this yet, unless we already know what we are required to do with thos additional files.

> What technology should we use to parse the xml file? (XPath, Nokogiri)
We might want to either take what OBS already uses, or the solution that is has the best performance and well maintained.
The more critical part might be to parse the XML in an effective way. It's easy to make this a performance nightmare. Shall we use the XMLHash lib?

> How to validate the original file in order to be sure that we parse a proper Kiwi file? (we have the RNG schema here)
We might want to validate what OBS creates as well.

**Comment by bgeuken** [comment]
Regarding the creation of kiwi xml files: One possible problem I see is that the kiwi version we create the xml for varies. If the xml's schemaversion is older than the one KIWI expects, KIWI will update the xml using it's [XSL files](https://github.com/openSUSE/kiwi/tree/master/xsl). But if we create to new schema, there will be projects with KIWI versions that can not read our xml.

For now this might not be a problem, as long as we only change simple things that don't change (repositories). But if this involves more changes or even covering newer KIWI features, we might have to think about covering different schemas

**Comment by evanrolfe** [comment]
@bgeuken thats a good point about kiwi schema versions. Maybe we dont need to handle different versions right now but definitely something to keep in mind that we will probably have to support different versions in the future.

Regarding the parsing of XML. I dont think thats a costly operation because the the kiwi files are never that big are they? The parsing should be able to finish in 10's of milliseconds time? Or am I wrong on that?

**Comment by bgeuken** [comment]
@evanrolfe It's more about how the xml get's parsed than it's size. If we use XPath, each element (or group of elements) get's 
fetched one by one. So the xml get's parsed multiple times, which makes it slow.

With (SAX)[https://en.wikipedia.org/wiki/Simple_API_for_XML#Benefits] you serialize over the xml. Just read the wikipedia article I attached. It's much better than any explanation I could give:-)

**Comment by ChrisBr** [comment]
@evanrolfe however, if we don't store it in the frontend, we need to parse it on every request.

Also: Do we want to represent some parts with objects we already have in our db. Like it was in @mdeniz proposal with ``has_many :repositories`` 

For example:

```xml
...
    <repository type="rpm-md" >
        <source path='obsrepositories:/'/>
    </repository>
    <repository type='rpm-md'>
      <source path='obs://home:cbruckmayer:fosdem/openSUSE_Leap_42.2'/>
    </repository> 
...
```

We parse now out home:cbruckmayer:fosdem so we have to query by name e.g. 
```
Repository.find_by(name: 'home:cbruckmayer:fosdem')
```
because then we have again relations based on strings. It's not a problem, just wanted to point it out!

**Comment by evanrolfe** [comment]
> It's more about how the xml get's parsed than it's size. If we use XPath, each element (or group of elements) get's fetched one by one. So the xml get's parsed multiple times, which makes it slow.

I did a quick speed test of using XmlHash to parse a kiwi xml file and it took 8 ms to parse the entire file. So I dont think speed is an issue?

https://gist.github.com/evanrolfe/ef2406b652031d59b00cf203191caae1

We can just memoize the parsed xml hash in the kiwi image class so we dont parse the xml multiple times i.e.

```ruby
module Kiwi
  class Image
    attr_reader :xml_string

    def initialize(xml_string)
      @xml_string = xml_string
    end

    def repositories
      @repositories ||=
        parsed_xml['repository'].map |repository_xml|
          Repository.find_by(path: repository_xml['source']['path'])
        end
    end

    private

    def parsed_xml
      @parsed_xml ||= Xmlhash.parse(xml_string)
    end
  end
end
```

**Comment by marcus-h** [comment]
On 2017-03-29 07:37:56 -0700, Moisés Déniz Alemán wrote:
> The solution we decided to propose is to represent the Kiwi file internally as ActiveRecord models stored in the database. So, each time a Kiwi file is created/updated in the app (via API or WebUI) we need to parse it and create/replace all the objects related to that. And the outcome of this internal representation will be a  Kiwi file built at save time from the main model.
> 
Hmm I'm not sure if I understand it correctly: is it possible that a

curl -X PUT -T config.kiwi https://<api>/source/<prj>/<pkg>/config.kiwi

results in a different backend file (the md5s of the local config.kiwi
and the one that is stored in the backend differ)? If so, this sounds
scary...

A few questions/potential "issues":
- does the internal representation preserve comments?
- is the document order preserved? (if not, this might result in
  "merge" conflicts when updating a osc working copy)
- it is possible that the api "misses" some changes to a kiwi file
  (e.g. a kiwi file can be created/modified by the backend via
  a _link or a source copy)

IMHO, it would be much easier (and maybe less error prone?) to fetch
the kiwi file from the backend and encapsulate it in some nice
looking ActiveRecord-like object, which internally operates on the
xml...

**Comment by evanrolfe** [comment]
> IMHO, it would be much easier (and maybe less error prone?) to fetch
the kiwi file from the backend and encapsulate it in some nice
looking ActiveRecord-like object, which internally operates on the
xml...

My thoughts exactly. Though with a much better explanation!

**Comment by coolo** [comment]
to be precise: XMLHash is using the same parsing library than Nokogiri (as used in ActiveXML). The difference is that Nokogiri/ActiveXML is creating a DOM tree and ActiveXML is using xpath to query elements, which is really slow if done in a hot place.

XMLHash is not creating a DOM tree, but creates a ruby hash - so querying elements becomes native ruby.

**Comment by hennevogel** [comment]
> IMHO, it would be much easier (and maybe less error prone?) to fetch the kiwi file from the backend and encapsulate it in some nice looking ActiveRecord-like object, which internally operates on the xml...

We are already doing this. It's called [ActiveXML](https://github.com/openSUSE/open-build-service/tree/master/src/api/lib/activexml) :-)

**Comment by mdeniz** [comment]
> IMHO, it would be much easier (and maybe less error prone?) to fetch the kiwi file from the backend and encapsulate it in some nice looking ActiveRecord-like object, which internally operates on the xml...

Yes, sure. That was also my starting point when we discussed it. I didn't want to store things in the DB... 

So, we can not to store the objects in the DB and parse the file each time. Just having the objects as a representation in memory. That way we can avoid the need of being in sync with the backend.

Thanks @marcus-h. That's why we are here in "public" discussing this 😄 we wanted to see more POVs.

**Comment by adrianschroeter** [comment]
Please keep also the various ways of specification for one repository URL in mind. eg. using http://download... (which is possibly mapped by the backend) instead of obs://. Also repositories to remote instance (eg. obs://openSUSE.org:openSUSE:Tools/openSUSE_42.1).

You may loose information here when you just use a Repository object.

JFYI, You could use the (safe and fast) backend parser, or directly the build script parser to find all repositories, but that won't help you to edit the file later on (on the other hand all supported formats would be supported directly when reading the file.). 
You could test this via "obs_admin --parse-build-desc ..." if you want to have a look.

**Comment by mdeniz** [comment]
@adrianschroeter 

> You may loose information here when you just use a Repository object.

We are not going to represent Kiwi stuff with actual OBS models, we will use new models for it... Kiwi::Repository for instance that will hold the information that a Kiwi file can have, nothing more, nothing less, so we are not going to loose anything I hope 😄.

I will take a look at the backend parser. But I guess we need something  in our code... if not we will end up parsing the result of the backend parser instead of the actual kiwi file.
