### ISSUE TITLE
lintian: allow selecting a vendor profile package- or project-wide

### ISSUE THREAD

**Issue by Artox** [openSUSE/open-build-service#2926]
Occasionally lintian checks can be extremely strict and very cumbersome to deal with.
Especially so when they are marked non-overridable by Debian.

If there is a good reaso not to adhere to these defaults, a sane solution appears to be creating a custom vendor profile for lintian (see [https://lintian.debian.org/manual/section-3.3.html](url)).

Now it would be great if there was a way to specify the --profile argument in project config and have it passed on to the lintian invocation in build-recipe-dsc.

Sample invocation:
`lintian --profile solidrun/main -i abc.changes`

Are there any ideas how this could be implemented?

**Comment by adrianschroeter** [comment]
lintian is just executed with whatever defaults it is packaged.

You need to modify the packaging of the lintian package there. (I do not really see value to extend build script to support profiles, since the default is a policy decision. But we could add that when requesting in the build script tracking)

**Comment by Artox** [comment]
This issue has been closed for a while, but I have come up with a more complete solution now, that might be worth sharing:

lintian defaults to profiles by/for a named vendor. By default, the only installed vendor is "debian". So lintian searches for: `/usr/share/lintian/profiles/debian/main.profile`.

The vendor is chosen from the symlink `/etc/dpkg/origins/default`, which is **not** owned by any package, and usually points to a file called _debian_ in the same directory.

The solution now is to create a package containing:

- `/etc/dpkg/origins/<name>`
- `/etc/dpkg/origins/default`
- `/usr/share/lintian/profiles/<name>/main.profile`

Finally install it using `Support: <package>` as part of the project config.
