### ISSUE TITLE
API interface for DoD has invalid error handling

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2942]
Issue/Feature description
====================
It seems not to be possible anymore to add DoD repositories. The api just delivers a 422 without a proper error message. I have tried to add
`
     <download arch="x86_64" url="http://ftp.unierlangen.de/mirrors/Mageia/distrib/cauldron/x86_64/media/core/release" repotype="rpm-md"/>
`
which passes the schema validation at least.

From the server log file:

F, [2017-04-07T07:03:27.114332 #5669] FATAL -- : [fc6e0cf7-7d02-4b82-bac6-a2988076e47b] [5669:1766.18] ActiveRecord::RecordNotSaved (Failed to replace download_repositories because one or more of the new records could not be saved.):
F, [2017-04-07T07:03:27.114412 #5669] FATAL -- : [fc6e0cf7-7d02-4b82-bac6-a2988076e47b] [5669:1766.18]   
F, [2017-04-07T07:03:27.114459 #5669] FATAL -- : [fc6e0cf7-7d02-4b82-bac6-a2988076e47b] [5669:1766.18] app/models/project/update_from_xml_command.rb:315:in `update_download_repositories'
[fc6e0cf7-7d02-4b82-bac6-a2988076e47b] app/models/project/update_from_xml_command.rb:196:in `update_repository_without_path_element'

Expected result
============
We should never report a 422 in the api, this means the error handling broke. Maybe we should report them to errbit.

**Comment by adrianschroeter** [comment]
@evanrolfe not sure if it was your refactoring but you moved the code at least ;)

**Comment by adrianschroeter** [comment]
ah, it was indeed not a valid repotype ... rpm-md instead of rpmmd.

Nevertheless the error reporting needs to get fixed.

**Comment by evanrolfe** [comment]
@adrianschroeter can you give us more details on how to recreate this bug? like which API endpoint is not working?

**Comment by adrianschroeter** [comment]
Just try to define a DoD repo with invalid repotype via the api.

Try to add the line above to any of your projects. Hm, you need to be admin for that, so try it on your local installation or via test case.

**Comment by hennevogel** [comment]
Here is a backtrace about this:

https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/58e680183e19a0000d000000

**Comment by evanrolfe** [comment]
Here is a patch from adrian to create a test case from adrian:
https://gist.github.com/evanrolfe/294f77044eb4e25384618069f94eab36

**Comment by hennevogel** [comment]
Fixed in b1cef3f782cc147d34f16db7c92f1de665a76a44
