### ISSUE TITLE
remote_project_name migration needs backend running

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#2944]
Issue/Feature description
====================
Another problem with the [change repositories remote_project_name to not null migration](https://github.com/openSUSE/open-build-service/blob/master/src/api/db/migrate/20170306084558_change_repositories_remote_project_name_to_not_null.rb) on line 30.

```
duplicate_repos.each(&:destroy)
```

will trigger a `before_destroy` from `Repository` that will trigger a `store` of it's `Project` to the backend. The backend will most likely not run during migrations and writing a `Project` needs a logged in user.

Expected result
============
The migration works without the backend.

How to Reproduce
===============
1. create a duplicated repo
2. stop all OBS processes 
3. `bundle exec rake db:migrate`

**Comment by evanrolfe** [comment]
> The migration works without the backend.
I must be missing some knowledge here, but why we would expect the migrations to run without the backend?

**Comment by adrianschroeter** [comment]
the backend might be on a different server which is not online during the update.

In case we really needed to write the backend we created delayed jobs therefore. But your fix just avoiding this here should be fine here, since the backend never accepted such a setup anyway.
