### ISSUE TITLE
webui: colorize more state texts

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#2945]
Issue/Feature description
====================
Do some more colorization of states
E.g. https://build.opensuse.org/request/show/483210 in the upper right corner of the main content box, there is "In state XYZ".

Color "accepted" in "In state accepted" as green,
color "revoked" in "In state revoked" as red, like superseded.

**Comment by adrianschroeter** [comment]
not sure if just picking a color here is still a nice UI, but we could highlight the state somehow ...

**Comment by ChrisBr** [comment]
@adrianschroeter what is the conclusion of this one? Do we want to add more color?

**Comment by bgeuken** [comment]
I would say yes. It doesn't harm and makes it easier to distinguish between different request states.

**Comment by bgeuken** [comment]
Done with #4917
