### ISSUE TITLE
webui: Wipe does not stay on page

### ISSUE THREAD

**Issue by afaerber** [openSUSE/open-build-service#2950]
Issue/Feature description
====================

On a repository page, selecting the "Delete built binaries" link returns to the corresponding project page, where it shows the message "Triggered wipe binaries for ... successfully."

Expected result
============

Instead of returning to the package page, it should stay on the repository page, so that further wipes can be performed immediately.

How to Reproduce
===============
1. In the Web interface, go to a package with successfully built packages.
2. Go to some repository page via the build status on the right.
3. Select "Delete built binaries" for one of the architectures in that repository.
4. Watch being redirected from /package/binaries/... to /package/show/...

Further information
===============
* E.g., https://build.opensuse.org/package/show/home:a_faerber:Kernel:HEAD:arm/kernel-obs-build

**Comment by ChrisBr** [comment]
@adrianschroeter do we want that?

**Comment by adrianschroeter** [comment]
@ChrisBr yes, sounds logical to me.

**Comment by ChrisBr** [comment]
Implemented in #3030, will be available after the next deployment.
