### ISSUE TITLE
webui: Add wipe feature for all architectures

### ISSUE THREAD

**Issue by afaerber** [openSUSE/open-build-service#2951]
Related to issue #2950, it would be handy if the page /package/binaries/_projectname_/_packagename_?repository=_name_ would have a link "Delete built binaries" not just per architecture, but also one covering all architectures.

Test case: In the openSUSE instance, deleting binaries for an `openSUSE_Factory_ARM` repository for all of aarch64, armv7l and armv6l in one go, rather than having to load the binaries page three times and click the respective links three times (one step vs. six steps today).

**Comment by ny826** [comment]
isuue not appear please help

**Comment by ChrisBr** [comment]
Implemented in #3030, will be available after the next deployment.
