### ISSUE TITLE
srcserver: not using proxy configuration

### ISSUE THREAD

**Issue by luizluca** [openSUSE/open-build-service#2958]
Since upgrade from 2.7 to 2.8, srcserver stopped to use my proxy configuration.

From what I investigated, srcserver reads proxy conf from /srv/obs/configuration.xml.
The configuration there is good. I added a print to confirm that the value got here:
https://github.com/openSUSE/open-build-service/blob/master/src/backend/bs_srcserver#L106

However, wget (from /usr/lib/obs/service/download_files) does not get it.

I workaround it adding my proxy definition to /etc/obs/services/download_files.

How to Reproduce
===============
1. use srcservice to download something from http://
2. configure a proxy at /srv/obs/configuration.xml
3. do the download.

The result is that OBS will try to download directly and not through the proxy.

I'm using OBS packages from build.opensuse.org in a SLES12SP2 machine:
obs-service-tar_scm-0.6.1.1473925745.c5264bb-1.1.noarch
obs-signd-2.3.0-1.3.x86_64
obs-worker-2.8-1.3.noarch
obs-service-format_spec_file-20140825-1.13.noarch
obs-service-source_validator-0.6+git20160531.fbfe336-5.3.noarch
obs-service-verify_file-0.1.1-33.1.noarch
obs-service-recompress-0.3.1+git20160217.7897d3f-2.2.noarch
obs-service-set_version-0.5.3-4.2.noarch
obs-source_service-2.8-1.3.noarch
obs-common-2.8-1.3.noarch
obs-service-regex_replace-0.1-3.1.noarch
obs-server-2.8-1.3.noarch
obs-api-2.8-1.3.noarch
obs-service-download_files-0.5.1.git.1455712026.9c0a4a0-69.1.noarch
obs-productconverter-2.8-1.3.noarch

I installed obs-service-download_files from obs://build.opensuse.org/openSUSE:Tools because it was not available on SLES12.

**Comment by lethliel** [comment]
You should set the system proxy configuration for the services in /etc/sysconfig/proxy

https://en.opensuse.org/openSUSE:Build_Service_private_installation#You_need_to_use_a_Proxy_.2F_Firewall_to_get_out_of_your_company

The obs services do not get the configuration from the obs-server

**Comment by luizluca** [comment]
I did that. Proxy at sysconfig was fine since the beginning. My workaround is simply copyng into /etc/obs/services/download_files the lines from /etc/profile.d/profile.sh that defines proxy env based on /etc/sysconfig/proxy.
