### ISSUE TITLE
Webui branches into home project always

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#3024]
Issue/Feature description
====================

Webui branching of a package is not allowing to specify the target project and is not using the default branch target, but always branches into home project now. This is causing also the problem that the repositories get not setup according to the source project anymore.

Expected result
============
Use default branch target like with branching with osc (home:$user:branches.$source_project).

An optional target project could get specified.

**Comment by adrianschroeter** [comment]
Erm, I saw this at @Ana06 place, but I can not reproduce this .... Ana, can you check and either describe a way or close this please?

**Comment by Ana06** [comment]
@adrianschroeter what I showed you was when branching a package in my home project, as @ChrisBr just told me, this is the expected behaviour in that case. So, it seems to be a misunderstanding and that it is working. Sorry for the mess. :confounded:
