### ISSUE TITLE
[dist] packaging and make -C dist test failures

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#3027]
Since git commit 152d8970f4359b3f0521dc923b51615529467f01, e.g. when files from dist were moved to the ./sysvinit/ and other subfolders, we have failing:

make -C dist test

and

also the rpm packaging of the rc scripts is failing. Like:

`error: File not found: /home/abuild/rpmbuild/BUILDROOT/obs-server-2.8.51.20170421.152d8970f-999.1.x86_64/usr/sbin/rcobsdispatcher`
`error: File not found: /home/abuild/rpmbuild/BUILDROOT/obs-server-2.8.51.20170421.152d8970f-999.1.x86_64/usr/sbin/rcobspublisher`
...

**Comment by mmohring** [comment]
It seems the Makefile was not completely updated for the rc scripts.

**Comment by hennevogel** [comment]
@leemgs can you have a look please?

**Comment by mmohring** [comment]
Cloud we please keep the make interface like:
-make test
-make install
So if there was a change in dist, put all into the the dist/Makefile. Call dist/sysvinit/Makefile from there.

**Comment by leemgs** [comment]
> make -C dist test

Could you run the below commands after applying the PR https://github.com/openSUSE/open-build-service/pull/3028
$ sudo make -C dist/sysvinit test
$ sudo make -C dist test 

> also the rpm packaging of the rc scripts is failing. Like:

Please, modify the existing folder from **./dist** to **./dist/sysvinit** in case of Sys V init
(And, in case of systemd, ./dist/systemd folder)

**Comment by mmohring** [comment]
@hennevogel  @leemgs How do we want to support systemd vs. systemv packaging ? Some distros, like openSUSE, would support both. So before moving on with this fixing here, what is the plan ?

**Comment by leemgs** [comment]
In short, 
* for systemd, keep the ./dist/systemd/ folder. 
* for systemv, keep the ./dist/sysvinit/ folder. 

By supporting the two folders in OBS mainline, I think that  Linux distribution packagers can choose one between ./dist/systemd and ./dist/sysvinit for their own Linux distributions.

**Comment by mmohring** [comment]
I wanted to say not to break the existing make interfaces for make install and make test. They are called from many places. I also asked not to fix this in the global Makefile but in the local ones, e.g. dist/Makefile and its subdirectories. There are multiple other places from where make -C <directory> install, test etc. is called, not only from the global Makefile, e.g. .spec file, travis, ...

**Comment by adrianschroeter** [comment]
We need indeed a concept here first where we want to go and how.

I am very much in favor to have only one set of scripts and we don't need to support systemv init scr ipts anymore on the server. (The worker might be different).

It is fine to do this step by step, means only converting selected services.

But we can't break the packages and appliances in an intermediate step. So we should install either the systemv variant _OR_ the systemd service file.

Also we need to agree how we want to do logging esp. for the backend services. journal vs dedicated files.

**Comment by M0ses** [comment]
@mmohring AFAIK the commits which have issued this problem should have been reverted. Please feel free to leave a comment here if I`m wrong and I will reopen this issue.

**Comment by M0ses** [comment]
This should be the PR which fixes this issue:

https://github.com/openSUSE/open-build-service/pull/3033/files
