### ISSUE TITLE
API crashes when checking out _pattern via remote link

### ISSUE THREAD

**Issue by dirkmueller** [openSUSE/open-build-service#303]
iosc co openSUSE.org:systemsmanagement:crowbar:2.0 _pattern
A    openSUSE.org:systemsmanagement:crowbar:2.0
A    openSUSE.org:systemsmanagement:crowbar:2.0/_pattern
Server returned an error: HTTP Error 500: Internal Server Error

**Comment by ChrisBr** [comment]
Just checked, doesn't crash but returns now

```
Server returned an error: HTTP Error 401: Unauthorized
```

I guess this is fine, closing...

cc @dirkmueller @hennevogel
