### ISSUE TITLE
"Trigger Rebuild" triggers rebuilding of original packages for linked projects

### ISSUE THREAD

**Issue by kjhman21** [openSUSE/open-build-service#3066]
Issue/Feature description
====================
In the 'live_build_log' page, there is a button "Trigger Rebuild".
This button should trigger rebuild of the current package that I am looking at, but it triggers the original package of the linked project.
Please check out section "How to Reproduce".

First of all, since I am a newbie, I am not sure this is fixed or not.
We are using OBS-2.7.4 in our internal server.
I also searched issues in this repository, I could not find issues related to this.
If you know this is fixed or not, please tell me.

After my inspection, I found code below:
https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/package.rb#L1348

> Backend::Connection.post("/build/#{URI.escape(project.name)}?cmd=#{command}&#{permitted_params.to_h.to_query}")

At that line, "project.name" always indicates P1 even if I sees live log of A1 in P2.

I think project name should be brought from params.

I also have the code fixed this issue using parameters of backend_build_command(), but I am not sure this is right way.

Please tell me this is bug or not. If it is a bug, I will upload my patch.

Thanks.

Expected result
============
"Trigger rebuild" should triggers A1 in P2 if I see that package.

How to Reproduce
===============
1. Project P1 has Package A1
2. Project P2 has Package B2
3. Project P2 links P1. This means P2 has A1 as an inherited package.
4. If I clicks "Trigger rebuild" in the live_build_log page of A1 in P2, OBS triggers rebuild of A1 in P1.

Further information
===============
We are using obs-2.7.3 in the internal server.

**Comment by ChrisBr** [comment]
The correct link to the code is
https://github.com/openSUSE/open-build-service/blob/2.7/src/api/app/models/package.rb#L1348

Sorry, but I can't reproduce :/
The project.name is the project associated with the package set in:
https://github.com/openSUSE/open-build-service/blob/2.7/src/api/app/controllers/webui/package_controller.rb#L1070

This is exactly the same code as in master (except the follow_multibuild). So if this would be wrong, it would be wrong on many other places :/

Can you maybe put some debug code in ``backend_build_command`` to print out the package and package.project. And maybe also put some debug code in ``require_package`` in package_controller.

**Comment by kjhman21** [comment]
Did you 'trigger rebuild' an inherited package?

I think instance of A1 is created for P1 not P2 if P2 has A1 as an inherited package.

I inserted debug code at line 1348.
https://github.com/openSUSE/open-build-service/blob/2.7/src/api/app/models/package.rb#L1348

logger.error "MyP=#{project.name}, ParamP=#{params[:project]}"

The result was:
MyP=P1, ParamP=P2.

Please check once again. Thanks.

**Comment by ChrisBr** [comment]
@kjhman21 ahh got it! So the projects are linked (e.g. you have a BaseProject and a BaseProject:Update project). So in the case of an inherited package it does not exist in the db for BaseProject:Update, it just links to BaseProject. So this is intended behaviour!

**Comment by kjhman21** [comment]
In this case, "trigger rebuild" of package P1 in BaseProject:Update triggers P1 in BaseProject. Is this intended behavior? 

Then, how can we trigger rebuild for P1 in BaseProject:Update using webui?

**Comment by ChrisBr** [comment]
It is the same package ;)

**Comment by kjhman21** [comment]
But, they can have different build result or buildlog for various reasons such as different project config, different rpms.

**Comment by bgeuken** [comment]
We addressed this now in #3284

**Comment by kjhman21** [comment]
Thank you very much @bgeuken. I thought that this issue was ignored. 
I am really happy that this issue will be fixed. :)

**Comment by ChrisBr** [comment]
@kjhman21 yeah, sorry for the misunderstanding :(

**Comment by kjhman21** [comment]
This OBS community seems a closed community. I don't know well about open source projects, but I heared that open source projects have to be open to anyone even for newbies.

I wrote three issues because I'm using OBS in my company, but I haven't received careful answers. Two issues were closed even though I hadn't got enough answers.
Please take care newbies' questions even if their questions seem to be useless.

Thanks for reading my complaint.

**Comment by bgeuken** [comment]
Well, I agree OBS is not the most newbie friendly environment since it's quite large and complex. We frequently go through new created issues, but it can happen that something slips through. Appoligies for that.

In general if you want to make yourself heard or desire a more direct feedback don't hesitate to join us in IRC (irc://irc.opensuse.org/opensuse-buildservice).

**Comment by adrianschroeter** [comment]
@kjhman21 sorry, yes, it was a mistake to close the issue, but you could have reopened it also asking for a second opinion ;)

Please be aware that there is also a commercial offer of support, in case you need that: http://openbuildservice.org/support/   or drop me a mail directly.

**Comment by kjhman21** [comment]
Thanks for hearing my complaints and writing responses. :)

@adrianschroeter, I'm sorry I'm not very aware of Github. I think that I had no permission to reopen it.

Anyway, two closed issues are sufficient to be closed, but please check this out.
https://github.com/openSUSE/open-build-service/issues/2204

I have not started to implement this, but I think similar feature will be very helpful. 
I have a plan to implement this in near future.
