### ISSUE TITLE
`osc rq wipe` returns error 500

### ISSUE THREAD

**Issue by lchiquitto** [openSUSE/open-build-service#3074]
Issue description
====================

`osc rq wipe $rid` returns "HTTP Error 500: Internal Server Error".

Expected result
============

Request should be wiped.

How to Reproduce
===============

In the internal instance of the Build Service, RR#61504 is something we would like to wipe, so:

`iosc rq wipe -m obsolete 61504`

**Comment by mschnitzer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Issue #3074](https://trello.com/c/vd3TCeXS/384-fix-issue-3074)

**Comment by mschnitzer** [comment]
It seems to be fixed in #3079 but I would like to raise a question: Does it sometimes work or is it the first time you use this command?

**Comment by lchiquitto** [comment]
@mschnitzer It was the first time I asked the IBS admins to use it, but it seems to fail consistently at least for this request ID.

**Comment by mschnitzer** [comment]
OK, thanks for confirming that.
