### ISSUE TITLE
Cannot change project meta with download on demand configured

### ISSUE THREAD

**Issue by mlschroe** [openSUSE/open-build-service#3084]
How to Reproduce
===============
```
$ osc meta prj Univention:4.1 -e
<change something>
Sending meta data...
BuildService API error: project_save_error (400)
Arch has already been taken
```

This works if the download on demand section is removed.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Project meta changes for DoD projects broken](https://trello.com/c/eNega5Ec/344-project-meta-changes-for-dod-projects-broken)

**Comment by mlschroe** [comment]
Fixed meanwhile.
