### ISSUE TITLE
BUILD_FLAVOR set to "" for mulitbuild packages

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#3111]
Reference package:
https://build.opensuse.org/package/show/openSUSE:Factory/installation-images:Kubic

This used to build just fine and since recently (I'd query buildhist, but osc is not working at the moment) this started failing

This being a multibuild package, BUILD_FLAVOR should be set to "Kubic", yet, the build log contains:

```
[  134s] I have the following modifications for installation-images.spec:
[  135s] 21c21
[  135s] < %if "@BUILD_FLAVOR@" == ""
[  135s] ---
[  135s] > %if "" == ""
[  135s] 26c26
```

It thus appears as if BUILD_FLOAVOR is being set to "" for those builds, which further down in the .spec is excluded from building (intentionally)

**Comment by ChrisBr** [comment]
Seems like this commit is related
https://github.com/openSUSE/obs-build/commit/83be5905c8a3daf49f1ae8849ae6fceb56242cd3

@M0ses @leemgs

**Comment by mlschroe** [comment]
Yeah, I broke that on Friday by mistake (I deployed the worker from the 2.8 tree)
