### ISSUE TITLE
OBS should create changes file templates with "Author Name <author@example.email>" instead of just email address for authors

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/open-build-service#3112]
Issue/Feature description
====================
Currently, the OBS does not generate changes entries with full authorship information. Instead, it makes only entries with email addresses. This is inconsistent with how other distributions (Fedora, Red Hat, Debian, Ubuntu, etc.) set up changelog entries. OBS needs to be able to fill out proper authorship information.

Expected result
============
Changes entries include author name and email address for author field.

How to Reproduce
===============
1. Create package
2. Add empty .changes file
3. Generate template entry

Further information
===============
* This is reproducible on build.opensuse.org as well as any private OBS instance.

**Comment by plinnell** [comment]
osc vc and ~.oscrc with a proper full name should be able to add this as well.

**Comment by ChrisBr** [comment]
@plinnell @Conan-Kudo can we close this one?

**Comment by Conan-Kudo** [comment]
@ChrisBr Uh, why? It doesn't support this at all currently.

**Comment by ChrisBr** [comment]
```
osc vc and ~.oscrc with a proper full name should be able to add this as well.
```
?

**Comment by Conan-Kudo** [comment]
@ChrisBr I think he means it `osc` needs to be able to do this too, as it currently cannot.

**Comment by ChrisBr** [comment]
ah got it!

**Comment by ChrisBr** [comment]
For osc please add a issue to https://github.com/openSUSE/osc

**Comment by marcus-h** [comment]
On 2017-05-19 05:39:11 -0700, Neal Gompa (ニール・ゴンパ) wrote:
> @ChrisBr I think he means it `osc` needs to be able to do this too, as it currently cannot.
> 
Well it works in some sense...

mailaddr="foo bar foo@bar" osc vc

or to make this the default

osc config <apiurl> mailaddr "foo bar foo@bar"
osc vc

But the current "policy" is mail address only. If you want to change it,
the best is to discuss this on the factory ml.

**Comment by Conan-Kudo** [comment]
Hah, I'd forgotten I'd filed this issue when I fixed this a while ago...
