### ISSUE TITLE
[dist] systemd units are not installed by default

### ISSUE THREAD

**Issue by k0da** [openSUSE/open-build-service#3117]
systemd unit files are not installed by default and hence are not packaged within obs-server package

**Comment by bgeuken** [comment]
@M0ses IIRC you have been looking at systemd scripts for OBS. Could you have a look at this one?

**Comment by M0ses** [comment]
@k0da : This is only partly correct. 

```
frank@t460p:~/prj/open-build-service> grep SERVICE dist/Makefile 
SYSTEMD_SERVICE_FILES := obsdeltastore
```

Unfortunatly migration is stuck ATM

**Comment by dmarcoux** [comment]
Still true?

**Comment by hennevogel** [comment]
no
