### ISSUE TITLE
Login form appears to come out of Search form

### ISSUE THREAD

**Issue by sknorr** [openSUSE/open-build-service#3118]
Issue/Feature description
====================

Tiny UX enhancement thingie: the OBS login form appears directly under the search form. Because both are also roughly the same color, it looks as though they are connected.

Expected result
============
Login form should be clearly distinct from search form.

Below [1] is a five-minute CSS hack (apply via your browser's webdev toolbox) that moves the form lower and adds an arrow:

![Screenshot](https://cloud.githubusercontent.com/assets/5476547/26149527/ea8b82c0-3afa-11e7-9d46-53ab9d823aa7.png)

However, I did not bother to fix the animation for the login form. Also, the Log in link should probably toggle the overlay, whereas now, it can only open but not close it.

How to Reproduce
===============
1. open OBS homepage
2. click Log in at the top of the page

[1]
```
#login-form {
border-radius: 5px;
margin-top: 40px;
opacity: 1;
}

#login-form::before {
content: '';
display: block;
border-width: 0 20px 15px 20px;
border-color: #333 transparent;
border-style: solid;
position: absolute;
top: -16px;
right: 17px;
}
```

**Comment by faraazahmad** [comment]
![screenshot from 2017-09-28 01-59-02](https://user-images.githubusercontent.com/19265077/30936246-d62aa9e6-a3f0-11e7-92fc-f5b7c08490ee.png)


I have adjusted the `top` property. What should i use to make that triangle, SVG will be fine?

**Comment by faraazahmad** [comment]
I have made the above changes and in the JS file, 'open-build-service/src/api/app/assets/javascripts/webui/application/bento/script.js', I found this

```
$('#login-trigger').click(function() { // display login form
    var offsetSubheader = $('#subheader').offset(); // get position of #subheader
    var posX = parseInt(offsetSubheader.left) + $('#subheader').width() - $('#login-form').width(); // calculate position for login-form
    $('#login-form').css('left', posX).slideDown('fast', function() { // slide down and set position in callback
       var rbPos = $('.position-br').offset();
       x1 = posX; // left
       x2 = rbPos.left; // right
       y1 = offsetSubheader.top; // top
       y2 = rbPos.top; // bottom
      $('#username').focus();
    });
```
I suppose i have to change slideDown() to slideToggle().
Ami I right?

**Comment by parasitecruncher** [comment]
#4669

**Comment by Ana06** [comment]
I think @srivatsav1998 is working on this

**Comment by parasitecruncher** [comment]
@Ana06  Sorry, I didn't notice @srivatsav1998 PR because it wasn't referenced here.

**Comment by Ana06** [comment]
@parasitecruncher it was not referenced, it would have been strange that you noticed. Maybe we should add that people should commenting in an issue before working on it in the contributing guide... or in the template when open a PR... :thinking:

**Comment by srivatsav1998** [comment]
Why is this issue still open? Is there something left?

**Comment by hennevogel** [comment]
nope :)
