### ISSUE TITLE
obs-api rpm package: /srv/www/obs/api/public is broken

### ISSUE THREAD

**Issue by matwey** [openSUSE/open-build-service#3134]
Issue/Feature description
====================

Hello, I am using obs-api-2.8-1.5.noarch from OBS:Server:2.8 and I found that there some issue when RPM is being packaged. ```/srv/www/obs/api/public``` is generated at the package build time, but ```asset_path()``` function result may depend on the value of ```RAILS_RELATIVE_URL_ROOT``` environment variable. For instance, in the case when Passanger is configured to run application with prefixed url

```
        ## https://www.phusionpassenger.com/library/deploy/apache/deploy/ruby/
        Alias /obs "/srv/www/obs/api/public"
        <Location /obs>
                PassengerBaseURI /obs
                PassengerAppRoot /srv/www/obs/api
                PassengerMinInstances 2
        </Location>
```

This leads to broken links to images and styles in OBS API WebUI.

Expected result
============

There should be a clear way to regenerate ```/srv/www/obs/api/public``` content using end-user configuration.
```/srv/www/obs/api/public``` has to be marked as config, nocheck in the RPM spec file to allow different versions of the files.

**Comment by hennevogel** [comment]
The RPM is not meant to be used with any other configuration than inside the package, sorry. If you want to 'regenerate' the public dir you can [precompile your assets](http://guides.rubyonrails.org/asset_pipeline.html#precompiling-assets) again.
