### ISSUE TITLE
[production][webui/project#save_meta] ActiveRecord::RecordInvalid: Validation failed: Name must not start with '_' or contain any of th...

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3140]
webui/project#save_meta threw this 0 times
<pre>
ActiveRecord::RecordInvalid: Validation failed: Name must not start with &#39;_&#39; or contain any of these characters &#39;:/&#39;
</pre>
[https://build.opensuse.org/project/save_meta/home:hennevogel:test](https://build.opensuse.org/project/save_meta/home:hennevogel:test)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59241633cb55c9000a000000)

**Comment by hennevogel** [comment]
This happens when you save a repository with an illegal name. It's not populated to the UI, but it should be.

**Comment by adrianschroeter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix crash on invalid meta data edit](https://trello.com/c/IiYr1WUD/356-fix-crash-on-invalid-meta-data-edit)
