### ISSUE TITLE
API: fetching remote repos using http_proxy fails

### ISSUE THREAD

**Issue by luizluca** [openSUSE/open-build-service#3143]
Issue/Feature description
====================
My private instance is behind a http proxy. Most things work, but not adding a new repo.
load_external_url (api/lib/activexml/transport.rb) do checks for proxy conf in env variables and in CONFIG['proxy']. At least for SLES12, apache does not get proxy variables from env. Also, CONFIG['proxy'] is difficult to trace where should it come from for a non-dev. I managed to set it adding proxy to config/options.yml but config/options.yml.example never ever mentioned that it could setup proxy. It would be really nice if it could retrieve proxy settings from /srv/obs/configuration.xml and not from a second source of config

Expected result
============
- proxy config should be set only once, all OBS services should use it

My OBS is using obs-api-2.8.1-1.2.noarch running in a SLES12SP2.

**Comment by hennevogel** [comment]
You can set a system wide proxy in `/etc/sysconfig/proxy` and it will be used by the OBS too.

**Comment by luizluca** [comment]
@hennevogel , as I said "at least for SLES12, apache does not get proxy variables from env". Maybe systemd is restricting what env vars gets to each service. I do have /etc/sysconfig/proxy defined, even before obs was installed.

On SLES12, OBS simply can't rely on env vars for proxy settings. I'm OK with it. The problem is that the alternative way to define it is both hidden (not mentioned in example config and, this way, not "grep-able") and duplicated (as the admin must set it both at config/options.yml and /srv/obs/configuration.xml)

I guess the issue remains.
