### ISSUE TITLE
Handle redirection to not existing repo better

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#3151]
Issue/Feature description
====================

* Clicking on "Go to download repository" can lead to a 404 error when the repository never gots published. This is the case the case for the default branch repositories for example.

Expected result
============

Either not showing the link when not available or have a general warning when publish is disabled that the content might not exists or would be outdated.

**Comment by dmarcoux** [comment]
This is still happening as of today.
