### ISSUE TITLE
Add ability to subscribe to a Submit Request.

### ISSUE THREAD

**Issue by simotek** [openSUSE/open-build-service#3157]
In some cases people other then the original author wish to receive email notifications about changes to a submit request, currently you can somewhat achieve this by adding a comment but it would be nice if there was a "Subscribe" button somewhere on the form.

**Comment by adrianschroeter** [comment]
Indeed.... On technical level this belongs to the notification system and not to the request data, since the user wouldn't have a role in the request.

We are going to work on the notification system and will re-visit this.

**Comment by coolo** [comment]
I'd suggest to treat such subscriptions as silent comments - within the notification system as adrian says.

**Comment by hennevogel** [comment]
this is possible now in the watchlist...
