### ISSUE TITLE
GPG Signing issue in Vagrant setup

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3163]
When a package status gets set to 'signing', it will never end cause of this error in the backend:
```
gpg: DSA key 1222FD6A requires a 256 bit or larger hash
gpg: signing failed: General error
sign failed: 512 - checking digest
gpg: DSA key 1222FD6A requires a 256 bit or larger hash
gpg: signing failed: General error
sign failed: 512 - checking digest
gpg: DSA key 1222FD6A requires a 256 bit or larger hash
gpg: signing failed: General error
sign failed: 512 - checking digest
gpg: DSA key 1222FD6A requires a 256 bit or larger hash
gpg: signing failed: General error
sign failed: 512 - checking digest
```

**Comment by mschnitzer** [comment]
Solved by @hennevogel

**Comment by heikojansen** [comment]
I find the same entries im my signer.log after replacing an expired gpg key.
This happens on an installation directly on openSUSE 13.1 (yes, old but not publicly accessible) with no vagrant involved. Can you tell me what was changed to solve the problem? Maybe it will work for me, too.

**Comment by heikojansen** [comment]
Hmm, ok, I just removed the DSA subkey and now the packages are successfully signed using the main RSA key. Whatever...

**Comment by hennevogel** [comment]
@heikojansen both setups are completely different. If you still have problems, open a new issue please. TIA
