### ISSUE TITLE
crash in the keydialog

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#3178]
webui/projects/public_key#key_dialog threw this 0 times
<pre>
NameError: undefined local variable or method `project&#39; for #&lt;#&lt;Class:0x007fb80fb5f800&gt;:0x007fb80fb5e018&gt;
Did you mean?  @project
</pre>
[https://build.opensuse.org/projects/home:gustawho/public_key/key_dialog](https://build.opensuse.org/projects/home:gustawho/public_key/key_dialog)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59304451430225000a000003)

**Comment by hennevogel** [comment]
Already addressed in #3177
