### ISSUE TITLE
Allow to specify commit messages when changing files

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3179]
As a user, I'd like to specify commit messages when I change any file. (like on GitHub)

**Comment by adrianschroeter** [comment]
yes ... and it would be good to be able to modify multiple files and commit the change with the comment then.

**Comment by rhabacker** [comment]
Adding a commit message field to the editor for single files seems not to be complicated:
```
diff --git a/src/api/app/views/shared/_editor.html.haml b/src/api/app/views/shared/_editor.html.haml
index 390bfda93..20d576e7f 100644
--- a/src/api/app/views/shared/_editor.html.haml
+++ b/src/api/app/views/shared/_editor.html.haml
@@ -7,6 +7,7 @@
     .toolbar
       %span{ style: 'float: left' }
         %input.tools.buttons.small.save.inactive{ id: "save_#{uid}", type: 'button', value: 'Save' }/
+        %input.tools.buttons{ id: "save_text_#{uid}", style: 'background: transparent', type: 'text', size: '80', value: '' }/
         %input.tools.buttons.undo{ id: "undo_#{uid}", onclick: "editors[#{uid}].Undo(this);", style: 'background: transparent', type: 'button', value: 'undo' }/
         %input.tools.buttons.redo{ id: "redo_#{uid}", onclick: "editors[#{uid}].Redo(this);", style: 'background: transparent', type: 'button', value: 'redo' }/
       %span{ style: 'float: right' }

```

**Comment by rhabacker** [comment]
Then in https://github.com/openSUSE/open-build-service/blob/master/src/api/app/assets/javascripts/webui/application/cm2/use-codemirror.js#L44 the value from the commit message text input field need to be stored into data['comment'].
The bigger problem here seems to be recreating the assets at the obs virtual box image, which fails :-(

**Comment by rhabacker** [comment]
> The bigger problem here seems to be recreating the assets in the obs virtual box image, which fails :-(

see https://github.com/openSUSE/open-build-service/issues/7716 for a related bug report

**Comment by hennevogel** [comment]
@rhabacker I guess you are looking for our [development environment](https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md#how-to-setup-an-obs-development-environment)?

**Comment by rhabacker** [comment]
> @rhabacker I guess you are looking for our [development environment](https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md#how-to-setup-an-obs-development-environment)?

Thanks for this pointer.  After digging into the related docs and getting familiar with this type of development I was able to create related patches for 2.9 (https://github.com/rhabacker/open-build-service/commit/7cf7d8c74f5e94d45ab72c9564f27c723960ce4e) and master (https://github.com/rhabacker/open-build-service/commit/d3d219462df462c291598c4cabbc6064266d8d80). The latter needs a rebase for webui(1) from the 2.9 patch, which will follow soon.
