### ISSUE TITLE
Comments page is broken

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3180]
Hi,

not sure if the page is even used since I never seen a dedicated comment page (just found this page in the routes.rb).

Anyways, when pointing my browser to a comments page URL, it throws an error:
https://build.opensuse.org/comments/package/home:mschnitzer/pawncc

From my dev instance I get the following stacktrace:
```
Missing template comments/show_package_comments, application/show_package_comments with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :haml]}. Searched in: * "/vagrant/src/api/app/views" * "/usr/lib64/ruby/gems/2.4.0/gems/peek-mysql2-1.1.0/app/views" * "/usr/lib64/ruby/gems/2.4.0/gems/peek-dalli-1.1.3/app/views" * "/usr/lib64/ruby/gems/2.4.0/gems/peek-0.2.0/app/views" * "/usr/lib64/ruby/gems/2.4.0/gems/kaminari-0.17.0/app/views"
```

**Comment by bgeuken** [comment]
That seems to be (mainly) an API route. Thus it doesn't have any html representation. I've created a patch that will default the format to xml. So users won't see a blank page anymore.
Just in case anyone ends up there.
