### ISSUE TITLE
webui: rework diff textboxes in /request/show

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#3186]
On a request like https://build.opensuse.org/request/show/498680

Observed result
============
The textbox containing fluxbox.changes (or fluxbox.spec) is over 200 lines in size. The horizontal scrollbar is only at the end of this textbox, which means you either need to be lucky to have an input device with horizontal scrolling ability (which so far is limited to touchpads and expensive mice), or painstakingly scroll down the 200 lines, scroll right with the bar, and then move up again...

Expected result
=============
Something better to handle spec files with long lines. Maybe just setting the textbox to do wrapping; or to limit it to 25…30 lines (meaning it gains a vertical scrollbar).
[opensuse-review-team]

**Comment by ChrisBr** [comment]
@jengelh deployed to build.o.o, please have a look and provide feedback, thanks!

**Comment by ChrisBr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add vertical scrolling to codemirror diff #3186](https://trello.com/c/oI3EmWZl/488-add-vertical-scrolling-to-codemirror-diff-3186)

**Comment by jengelh** [comment]
works
