### ISSUE TITLE
osc build returning HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by highperformancecoder** [openSUSE/open-build-service#3198]
Issue/Feature description
====================

osc build scidavis.spec openSUSE_Tumbleweed

returns

Server returned an error: HTTP Error 401: Unauthorized

Other projects and distros also fail with the same error message

Expected result
============

The package should build.

How to Reproduce
===============
Try to build a package

**Comment by adrianschroeter** [comment]
not reproducable here, you may have used the wrong URL (not pointing to api.opensuse.org).

**Comment by highperformancecoder** [comment]
On Mon, Jun 05, 2017 at 10:56:56PM -0700, Adrian Schröter wrote:
> not reproducable here, you may have used the wrong URL (not pointing to api.opensuse.org).
> 
> 

On further investigation, it looks like you might have switched off
http support within the last few days, and my .oscrc file had recorded a
way outdated password, so https was not working for me.

Fixed by changing the password in the .oscrc file.

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------
