### ISSUE TITLE
webui: Make "source change" in jobhistory clickable

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#3199]
It would be nice if the "source change" item of the job history page would be clickable and shows
directly the diff to the former build result. This is useful when a source change leads to a different
build result (eg. failing) and the user want's to see the change which may have caused this.

Issue/Feature description
====================

* Show diff of source changes from jobhistory page

**Comment by bgeuken** [comment]
That's has been done by now :smile:
