### ISSUE TITLE
ppc64le workers keep on dying (blocking TW staging process)

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#3218]
The ppc64le workers keep on dying and need to be restarted, something which requires action by OBS admins (generally we need to do it about every week by now)

If to many workers die, this blocks the TW staging process, which is (still) building ppc64le (for now - if there can't be found a solution, ppc64le will have to go out of staging)

Instead of 'sending our ppc community away', I'd rather have a fix/analysis to understand why those workers keep on dying

Looking at the monitor graphs of OBS, this worker dying must have started somewhat end of March

**Comment by adrianschroeter** [comment]
they are running TW and having these problems therefore .... can I hand it back to you? ;)

Created a bugreport for kernel people now and closing this issue.

https://bugzilla.opensuse.org/show_bug.cgi?id=1043414

**Comment by DimStar77** [comment]
yes you can - that bug report was pretty  much what I was hoping to get out of this :) you promised me that one
