### ISSUE TITLE
[feature] Allow 'multibuild' to be disabled per prj

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#3227]
Multibuilds are an interesting concept and I do like it a lot - but it causes a problem for the products using rings.

I'll use a package of mine as a practical example (I did not convert it to multibuild yet, knowing of this problem.

* libproxy - and libproxy-plugins

libproxy lives in ring1 (basic library dependencies) and libproxy-plugins lives in ring2 (full KDE and GNOME extensions on top of libproxy, which uses a plugin model)

now, with multibuild, I could not have libproxy builtin ring1 and libproxy:plugins in ring2 - they would only go together.

My proposal would be a way to specify ring0/1/2 that multibuild is NOT to be considered (which would easily make for libproxy:plugins not to be built for ring1); but this then still lacks a good idea to ensure libproxy:plugins can be built in ring2 (preferably it would link to ring1/libproxy - we could then add some extra information into the _link to tell it what @BUILD_FLAVOR@ to use for this package

**Comment by DimStar77** [comment]
to make it clear: in a project where 'multibuild' is disabled (e.g the rings), we would need a way to build a specific flavor of the package (e.g. libproxy - flavor "" in ring1, libproxy - flavor 'plugins' in ring2)

**Comment by DimStar77** [comment]
This has actually been implemented as we can easily disable a flavor in a project using excludebuild nowadays (which is already used in Factory ring0/ring1)

Accepting this as a working solution

**Comment by hennevogel** [comment]
thanks @DimStar77 💐
