### ISSUE TITLE
Forwarding Requests during accepting does not handle validations

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3236]
When you forward a request to the devel project while accepting it, the controller code does calls `.save!` on the created `BsRequest` without handling possible failed validations.

webui/request#changerequest threw this 0 times
<pre>
ActiveRecord::RecordInvalid: Validation failed: Bs request actions is invalid
</pre>
[https://build.opensuse.org/request/changerequest](https://build.opensuse.org/request/changerequest)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/594099682a65a4000a000000)

**Comment by eduardoj** [comment]
The exception on Errbit has been deleted. Duplicate of #3730.
