### ISSUE TITLE
submit package link does not fill in changelog diff

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#3249]
Issue/Feature description
====================

Using the "Submit Pakage" link in a devel project pops up a dialog
with an empty description. When using osc sr on the command line on
the other hand the text gets pre-filled with the diff of the
.changes file which is very convenient.

Expected result
============

pre-fill text with information from .changes file as osc does

**Comment by ChrisBr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[webui] Submit package does not fill in changelog diff](https://trello.com/c/SNwG066t/498-webui-submit-package-does-not-fill-in-changelog-diff)
