### ISSUE TITLE
[AppImage] "latest" zsnyc symlink does not get correct name

### ISSUE THREAD

**Issue by probonopd** [openSUSE/open-build-service#3280]
Issue/Feature description
====================

http://download.opensuse.org/repositories/home:/probono/AppImage/leafpad-0.8.18.1-12.1.glibc2.4-x86_64.AppImage.zsync gets generated, and it is (wrongly) symlinked to http://download.opensuse.org/repositories/home:/probono/AppImage/leafpad-0.8.18.1-latest-x86_64.AppImage.zsync .This is not useful since it still hardcodes parts of the version number despite supposedly being a version-agnostic "latest" URL.

Expected result
============

It is symlinked to leafpad-latest-x86_64.AppImage.zsync

How to Reproduce
===============
1. When I want to use AppImageUpdate with AppImages on OBS
2. and the AppImage in question was generated using "ingredients: packages" in the `appimage.yml`
3. the `latest` zsync URL still contains parts of the version number, making updates impossible using AppImageUpdate

Further information
===============
* https://build.opensuse.org/package/view_file/home:probono/LeafpadFromRPM/appimage.yml?expand=1

**Comment by adrianschroeter** [comment]
fixed on the home:* project backend only for now.. will get deployed on the other backends later.
