### ISSUE TITLE
[AppImage] files get named wrongly

### ISSUE THREAD

**Issue by probonopd** [openSUSE/open-build-service#3281]
Issue/Feature description
====================

AppImage files get named wrongly when converted from RPM

Expected result
============
Given this [`appimage.yml`](https://build.opensuse.org/package/view_file/home:probono/VLC/appimage.yml?expand=1), the resulting AppImage should be named `VLC-$VERSION-$ARCH.AppImage`

How to Reproduce
===============
1. Use https://build.opensuse.org/package/view_file/home:probono/VLC/appimage.yml?expand=1
2. Look at https://build.opensuse.org/package/binaries/home:probono/VLC?repository=AppImage
3. The AppImage is (wrongly) called `libqt4-x11-$VERSION-$ARCH.AppImage`

Further information
===============
* https://build.opensuse.org/package/view_file/home:probono/VLC/appimage.yml?expand=1

**Comment by adrianschroeter** [comment]
fixed in build-pkg2appimage scipt.

The package name guessing got broken, this is fixed now.

But in general it is kind of a heuristic when the appimage name does not match to rpm name, maybe we should make this a failure actually (VLC vs. vlc  in this case)
