### ISSUE TITLE
webui: my reviews are missing reviews by_package

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#3282]
osc my rq shows 10 requests:

Examples:
```
505567  State:review     By:AndreasStieger When:2017-06-21T21:14:01
        maintenance_release: openSUSE:Maintenance:6846/update-test-trivial.openSUSE_Leap_42.3_Update -> openSUSE:Leap:42.3:Update/update-test-trivial.6846
        maintenance_release: openSUSE:Maintenance:6846/patchinfo ->             openSUSE:Leap:42.3:Update/patchinfo.6846
        Review by Group      is new:       qam-openqa(openqa-maintenance)  

504636  State:review     By:jberry_factory When:2017-06-19T20:11:46
        submit:          openSUSE:Factory/perl-Mojolicious@69 ->            openSUSE:Leap:42.3
        Review by Package    is new:       devel:languages:perl/perl-Mojolicious

```

Webui agrees with the number, saying I have 10 tasks.

But /user/show/coolo shows 6 open reviews and nothing else. What is missing are all the 'Review by Package'. I only have group reviews in the list.

This is quite problematic as the leap development process adds reviews to the devel project maintainer - and I only get to know about them once I get a reminder

**Comment by adrianschroeter** [comment]
https://trello.com/c/xZHgXfGA/374-fix-review-list-in-user-page

**Comment by ChrisBr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [webui: my reviews are missing reviews by_package #3282](https://trello.com/c/wYIMBNEf/441-webui-my-reviews-are-missing-reviews-bypackage-3282)

**Comment by ChrisBr** [comment]
@coolo can you please check, it is deployed now!

**Comment by coolo** [comment]
I have no reviews by_package meanwhile, sorry :)

**Comment by coolo** [comment]
ok, I reviewed the state and there are still things odd.

coolo@cleopatra#~>osc my rq | grep State: | wc -l
20

is in alignment with
'coolo (20 tasks) | Home Project | Logout'

But I get 7 reviews and 11 requests displayed. 

https://build.opensuse.org/request/show/508683 is in the list - which is what this issue is about. But 509338 is not, which is a by_project review. 

So the numbers are still at odd

**Comment by ChrisBr** [comment]
@coolo I will have a look at it

**Comment by ChrisBr** [comment]
It's not a but, it's a feature :smile: Request 509338 is created by you, so this is not listed in the review table. However, the task number does not reflect that (it counts the created by you requests). The mismatch between tasks and table should be fixed with the next deployment. 

See also our discussion in https://github.com/openSUSE/open-build-service/pull/3347/files#r125452004
