### ISSUE TITLE
In KIWI builds ignore any repository configured with `imageonly` attribute

### ISSUE THREAD

**Issue by davidcassany** [openSUSE/open-build-service#3288]
Issue/Feature description
====================

With the latest KIWI version repositories can be configured inside the description XML file with a new `imageonly` attribute (see SUSE/kiwi#377). In order to be capable to use that feature inside the build service it would be needed to ignore for the build environment configuration any repository marked with this `imageonly` attribute.

Expected result
============

The build service ignores any defined repository inside the kiwi file that contains `imageonly="true"`. As those repositories should not be taken into account for the image build.

How to Reproduce
===============
1. Given this repository configuration in the config.xml file:
```xml
<repository type="rpm-md" imageonly="true" alias="Leap_update">
  <source path="obs://openSUSE:Leap:42.2:Update/standard">
</repository>
<repository type="rpm-md" alias="Leap">
  <source path="obs://openSUSE:Leap:42.2/standard">
</repository>
```
2. Then running `osc buildinfo images` should list only the "Leap" repository and not the "Leap_update", as it should not be used for the image built.

Further information
===============
This feature is related to SUSE/kiwi#393 and SUSE/kiwi#395

**Comment by bgeuken** [comment]
@mlschroe Seems to be something for you guys:-)

**Comment by mlschroe** [comment]
Actually it's for the obs-build component and not obs itself.

**Comment by davidcassany** [comment]
@mlschroe sorry I though the repository evaluation was not part of the obs-build, I thought obs-build was just a script to launch KIWI when all packages and repositories are already resolved and set.

Shall we open a new issue in obs-build to track it at the right place?

**Comment by mlschroe** [comment]
All the recipe parsing (e.h. the kiwi xml parsing) is done in the obs-build package. This makes it very easy to support new build types, it's just one place to change.

Regarding the issue, it's already fixed in obs-build.  (And actually also deployed in OBS)

**Comment by davidcassany** [comment]
@mlschroe 👍 Thanks much!
