### ISSUE TITLE
Nothing provides "ffmpeg"

### ISSUE THREAD

**Issue by Sunderland93** [openSUSE/open-build-service#3292]
See https://build.opensuse.org/package/show/home:Sunderland93/synfigstudio

FFmpeg is a dependency of one of the binary packages, which needed to build Synfig Stuido for Debian 9

**Comment by andreasstieger** [comment]
That's not a bug in obs, it's simply a packaging/usage issue. If your target does not provide ffmpeg, you do not have ffmpeg. Cease requiring it, or provide it, or make the target (paths) provide it.

**Comment by Sunderland93** [comment]
> If your target does not provide ffmpeg, you do not have ffmpeg.

This is the reason - Debian 9 in OBS does not provide FFmpeg. Why?

**Comment by adrianschroeter** [comment]
ffmpeg is currently blacklisted in download on demand due to legal issues. We are not allowed to re-distribute it, sorry.
