### ISSUE TITLE
[AppImage] Provide download page

### ISSUE THREAD

**Issue by probonopd** [openSUSE/open-build-service#3302]
Issue/Feature description
====================

It would be nice if OBS would provide download links for AppImages too, like for other package types.

![](http://openbuildservice.org/help/manuals/obs-best-practices/images/download_page_screenshot.png)

Expected result
============

http://software.opensuse.org/download.html?project=home:probono&package=QtQuickApp should exist and show an AppImage icon and an AppImage download link for each architecture

How to Reproduce
===============
1. When I to to http://software.opensuse.org/download.html?project=home:probono&package=QtQuickApp
2. given that an AppImage for QtQuickApp exists in home:probono
3. I currently get "No data for home:probono / QtQuickApp"

Further information
===============
* http://software.opensuse.org/download.html?project=home:probono&package=QtQuickApp

**Comment by hennevogel** [comment]
@probonopd this is not OBS. This is another application, [software.o.o](https://github.com/openSUSE/software-o-o) please report your bugs/feature requests over there. Thanks

**Comment by probonopd** [comment]
Thanks @hennevogel and sorry for having posted this in the wrong project. Opened new ticket in openSUSE/software-o-o.
