### ISSUE TITLE
[AppImage] make searchable

### ISSUE THREAD

**Issue by probonopd** [openSUSE/open-build-service#3303]
Issue/Feature description
====================

It would be useful if there was an easy way to search for AppImages on OBS.

Expected result
============

Being able to search for specific or all (if empty search term entered) AppImages on OBS.

How to Reproduce
===============
1. When I want to search for AppImages
2. I go to http://software.opensuse.org/search, click the "advanced" icon, select AppImage from the dropdown
3. Doesn't find anything (e.g., leafpad)

Further information
===============
* http://software.opensuse.org/search?utf8=%E2%9C%93&q=leafpad&search_devel=false&search_devel=true&search_unsupported=false&baseproject=OBS%3AAppImage

![screenshot_20170627_234540](https://user-images.githubusercontent.com/2480569/27611527-c66507be-5b92-11e7-944a-0e2e5436ff88.png)

**Comment by hennevogel** [comment]
@adrianschroeter why is `OBS:AppImage` a Distribution?

**Comment by hennevogel** [comment]
@probonopd this is not OBS. This is another application, [software.o.o](https://github.com/openSUSE/software-o-o) please report your bugs/feature requests over there. Thanks

**Comment by adrianschroeter** [comment]
@hennevogel well, why not? It is one default build target, similar like kiwi or snapcraft or ... images.

**Comment by probonopd** [comment]
Thanks @hennevogel and sorry for having posted this in the wrong project. Opened new ticket in openSUSE/software-o-o.

**Comment by hennevogel** [comment]
@probonopd don't worry, be happy 😇
