### ISSUE TITLE
[production][delayed_job#Delayed::PerformableMethod] SMTP To address may not be blank: []

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#3316]
delayed_job#Delayed::PerformableMethod threw this 357 times
<pre>
SMTP To address may not be blank: []
</pre>

[See this exception on Errbit](http://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5953cf61ec8774000c3a79b4)

**Comment by adrianschroeter** [comment]
This happened a few hundred times ... We have also reports about missing mails ... maybe this is the cause?

**Comment by adrianschroeter** [comment]
A second similar(same?) listing http://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5953810bec877400063a6877

**Comment by hennevogel** [comment]
Duplicate of #3315
