### ISSUE TITLE
/etc/init.d/obsapidelayed restart will stop searchd for 1 hour

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3338]
[obsapidelayed](https://github.com/openSUSE/open-build-service/blob/master/dist/obsapidelayed#L73) says `searchd got started by clockd` but [the clock](https://github.com/openSUSE/open-build-service/blob/master/src/api/config/clock.rb#L50) says `every(1.hour, 'reindex sphinx')`

So searchd is off for 1 hour (+ time of the jobs already in the delayed job queue) when you stop this service.

**Comment by eduardoj** [comment]
@hennevogel, this should be fixed with #3753.
