### ISSUE TITLE
SPEC_REL in kiwi image filenames

### ISSUE THREAD

**Issue by KostyaSha** [openSUSE/open-build-service#334]
I can't disable SPEC_REL for kiwi file names.
I use globally for projects 

```
Release: <SPEC_REL>.<B_CNT>
```

and set 

```
%if "_repository" == "images" 
Release: <CI_CNT>.<B_CNT>
```

but scheduler still creates job file with SPEC_REL in it.
'osc  buildinfo -d images' has no such field...
'osc buildconfig' has Release: without SPEC_REL

**Comment by vpereira** [comment]
closed. if you think that it's not fixed or it's a necessary feature, feel free to re-open it!

thank you!
