### ISSUE TITLE
EventMailer: incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3344]
delayed_job#Delayed::PerformableMethod threw this 1 times
<pre>
incompatible character encodings: UTF-8 and ASCII-8BIT
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/595a3d2613741000069a6332)

**Comment by ChrisBr** [comment]
Duplicate of https://github.com/openSUSE/open-build-service/issues/3415

@hennevogel can we somehow prohibit to not create the same erribit issue again and again?
