### ISSUE TITLE
[production][delayed_job#Delayed::PerformableMethod] no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3349]
delayed_job#Delayed::PerformableMethod threw this 8 times
<pre>
no implicit conversion of String into Integer
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/595b17afcebbdb000b3a0700)

**Comment by evanrolfe** [comment]
I've been trying to re-create this error both locally and on production but cannot manage it.

The error comes from `IssueTracker.update_issues_github` which is called from a delayed job started by clock.rb. It then calls .to_s on [line 250](https://github.com/evanrolfe/open-build-service/blob/master/src/api/app/models/issue_tracker.rb#L250):

```ruby
issue = Issue.find_by_name_and_tracker(js["number"].to_s, name)
```

The issue tracker that is causing this error is the one with id 48:

```
<IssueTracker 
  id: 48,
  name: "osc",
  kind: "github",
  description: "OBS CLI Issues",
  url: "https://api.github.com/repos/openSUSE/osc/issues",
  show_url: "https://github.com/openSUSE/osc/issues/@@@",
  regex: "osc#(\\d+)",
  user: nil,
  password: nil,
  label: "osc\#@@@",
  issues_updated: "2017-07-19 07:40:26",
  enable_fetch: true
>
```

When I try to recreate this error locally I can see the json response from github contains the number attribute as the code expects it:
```
{
  "url"=>"https://api.github.com/repos/openSUSE/obs-build/issues/369",
  "repository_url"=>"https://api.github.com/repos/openSUSE/obs-build",
  "labels_url"=>"https://api.github.com/repos/openSUSE/obs-build/issues/369/labels{/name}",
  "comments_url"=>"https://api.github.com/repos/openSUSE/obs-build/issues/369/comments",
  "events_url"=>"https://api.github.com/repos/openSUSE/obs-build/issues/369/events",
  "html_url"=>"https://github.com/openSUSE/obs-build/issues/369",
  "id"=>243232455,
  "number"=>369,
  "title"=>"[Debian] Support for newer source formats is needed",
  ...
}
```

Also when I run this in the rails console on production it works fine:
```ruby
tracker = IssueTracker.find(48)
tracker.update_issues_github
```

So I'm not really sure why this error is occuring..

**Comment by mmohring** [comment]
I see the same issue here. In my test system and in the production machine.

**Comment by mmohring** [comment]
Can it be the 302 code, and you get redirected to https://api.github.com/repos/openSUSE/osc/issues ? I see this also in my logfiles.

**Comment by hennevogel** [comment]
Github has a rate limit on their API for non-authenticated users. It'll return 

```{
  "message": "API rate limit exceeded for YOURIP. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}```

when you hit the limit. I don't see us authenticating in any way so it's very likely we hit this often.

**Comment by mmohring** [comment]
@hennevogel you seem to have got #3480 merged. Was it an attempt to fix the issue here ? Anyway, this fix causes new problems reported in #3515 .

**Comment by hennevogel** [comment]
For the record: This has nothing to do with #3480 or #3515

**Comment by mmohring** [comment]
Yes, understood. I have written it in #3515 already that this has nothing to do with it.

**Comment by mmohring** [comment]
@hennevogel is there a way to find out which issue tracker is actually pulled and reports a failure in the logfile (apart from adding a debug log into the code) ?

**Comment by hennevogel** [comment]
@mmohring It's multiple ones. But always github...

**Comment by eduardoj** [comment]
Closing the issue given that:
* The exception on Errbit doesn't exist any more.
* There is no exception on Errbit found searching with the string `PerformableMethod` in the last year.

Please reopen if it happens again.
