### ISSUE TITLE
ActiveJob queing

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3351]
Some of your delayed jobs we schedule with `Delayed::Job.delay` some we schedule with `ActiveJob.perform_later`. Both use different default settings, especially the name for the default queue.

`DJ.delay` uses `Delayed::Worker.default_queue_name` which is **quick** and `AJ.perform_later` used **default**.

We should use one default queue...

**Comment by mdeniz** [comment]
IIRC this is already implemented, right? Closing it, if I was wrong, please reopen 😄

**Comment by hennevogel** [comment]
jupp
