### ISSUE TITLE
Build cannot deal with files with spaces and quotes in the name.

### ISSUE THREAD

**Issue by waterlan** [openSUSE/open-build-service#3361]
Issue/Feature description
====================
Build cannot deal with files with spaces and quotes in the name.
I uploaded a package update for dos2unix 7.3.5. All builds are failing. Dos2unix 7.3.5 has improved handling of files with spaces and quotes in the name. The test suite contains such a file name "dos 'txt.txt". The build chokes on it. See for instance https://build.opensuse.org/package/live_build_log/Base:System/dos2unix/openSUSE_Leap_42.2/x86_64

I see that the build tries to do something like this:
find -type f | xargs chmod -x

The solution is to add option -print0 to find, and -0 to xargs.
find -type f -print0 | xargs -0 chmod -x

Expected result
============
A succeeding build.

How to Reproduce
===============
build dos2unix-7.3.5 spec (request 508399)

Further information
===============
* A link to an OBS instance showing the issue
https://build.opensuse.org/package/live_build_log/Base:System/dos2unix/openSUSE_Leap_42.2/x86_64

* Exact server version (in case a private instance is used)

**Comment by DimStar77** [comment]
There is no error in OBS - the error itself is in the .spec file, where a command was used that does not support it

> find . -type f | xargs chmod -x

can't cope with file names with spaced and quotes. The bug is in the packaging / spec file, not OBS

**Comment by waterlan** [comment]
Thanks DimStar77.
