### ISSUE TITLE
[api] migration produces an error - 20170704125123

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#3376]
Issue/Feature description
====================
When calling

$ RAILS_ENV=production bundle exec rails.ruby2.4 db:migrate

on git master commit 5221ec524aeb735d45e6f6ec0c959a1ed7898ee9, an error occurs:

== 20170704125123 RemoveLockVersionFromEvents: reverting ======================
-- add_column(:events, :lock_version, {:default=>0, :null=>false}) rails aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method "to_sym" for {:default=>0, :null=>false}:Hash
Did you mean?  to_s to_set
bin/rails:4:in require
bin/rails:4:in `<main>`
NoMethodError: undefined method "to_sym" for {:default=>0, :null=>false}:Hash
Did you mean?  to_s to_set
bin/rails:4:in "require"
bin/rails:4:in `<main>`
Tasks: TOP => db:migrate:down
(See full trace by running task with --trace)

Expected result
============
Migration passes without error

How to Reproduce
===============
Use git commit 5221ec524aeb735d45e6f6ec0c959a1ed7898ee9 and run from older versions before this migration was added.

Further information
===============

**Comment by evanrolfe** [comment]
@mmohring I can only reproduce that error by running `rake db:rollback`, `db:migrate` works fine for me locally and it also worked fine when we deployed to production yesterday. However I'm pretty sure this PR should fix it:

https://github.com/openSUSE/open-build-service/pull/3377

**Comment by mmohring** [comment]
@evanrolfe You might be right. I wanted also to try out current git master, but this fails in the testsuite, see  #3378. So I will try it out again once git master works and your patch is applied. By your comment, I will not look into this further and wait.

**Comment by mmohring** [comment]
@evanrolfe I tried again with an older database and an older OBS like the version you were using until yesterday in b.o.o and the migrations worked. I have checked, the migrations in question were not changed in git after the first commit. So I close this for now.
