### ISSUE TITLE
[api] - testsuite setup failure

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#3378]
Issue/Feature description
====================

In order to fix issue #3376, I tried current git master to see if there were any changes. But current git master 162e6031b7ff5b64e15e3a295bfbcade601bd9b8 also fails, with the database setup in the api testsuite:

[  201s] config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:
[  201s] 
[  201s]   * development - set it to false
[  201s]   * test - set it to false (unless you use a tool that preloads your test environment)
[  201s]   * production - set it to true
[  201s] 
[  201s] DEPRECATION WARNING: ActiveSupport.halt_callback_chains_on_return_false= is deprecated and will be removed in Rails 5.2. (called from <top (required)> at /home/abuild/rpmbuild/BUILD/open-build-service-2.8.51.git20170707/src/api/config/initializers/new_framework_defaults.rb:23)
[  201s] rake aborted!
[  201s] NoMethodError: undefined method `[]' for nil:NilClass

Expected result
============

The [api] testsuite setup should not make the above error.

How to Reproduce
===============

See your b.o.o OBS:Server:Unstable obs-server package

Further information
===============

You can see this in the logfile of b.o.o OBS:Server:Unstable obs-server package.

**Comment by mmohring** [comment]
Hopefully fixed with #3404 .

**Comment by mmohring** [comment]
It is fixed with #3404, so I close this for now.

**Comment by bgeuken** [comment]
Thanks for the update:-)

Closing then
