### ISSUE TITLE
[worker] Linux version parsing may fail

### ISSUE THREAD

**Issue by afaerber** [openSUSE/open-build-service#3383]
Issue/Feature description
====================
If `/proc/version` includes "Linux version 4.4.72-default" then no version XML element is returned by the worker to the server. This leads to constraints not being satisfied and build jobs not getting scheduled on that worker.
On other machines that follow the 4.4.x-y-default pattern it does work as expected.

Expected result
============
The worker should return a version XML element to the server.

How to Reproduce
===============
Ask me or Rudi.
The kernel with such a version string was reportedly the result of a local `osc build`.

Further information
===============
* IBS

**Comment by mschnitzer** [comment]
I have not checked this and where the error occurs but I think it's backend related, not?
