### ISSUE TITLE
Dirty flag not shown on project/show

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#3386]
While project/monitor shows if a repo is dirty, the project/show box of build infos does not show this. This is very confusing, because you never know if the published flag is correct or not.

How to reproduce:
look at a project/show
trigger a package for rebuild
watch project/show only updating arch by arch to building, but never be dirty

**Comment by bgeuken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dirty flag not shown on project/show](https://trello.com/c/ljEfmdvk/462-dirty-flag-not-shown-on-project-show)

**Comment by ChrisBr** [comment]
@coolo this is deployed to build.o.o! Please provide some feedback :smile:
