### ISSUE TITLE
Attempt to delete group results in "Internal error 500"

### ISSUE THREAD

**Issue by lchiquitto** [openSUSE/open-build-service#3393]
Issue/Feature description
====================

If a Build Service administrator attempts to delete a group with `iosc api -X DELETE /group/$name`, error 500 is returned. If a !administrator tries the same, a 403+500 combo is returned.

Expected result
============

The group is deleted (or perhaps *disabled*).

How to Reproduce
===============

Run against the internal instance of the Build Service: `osc api -X DELETE /group/qam-casp`

**Comment by mlschroe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Delete group results in error 500](https://trello.com/c/YqXv5hBH/461-delete-group-results-in-error-500)

**Comment by sriemer** [comment]
Might be related. I get the same issue when trying to delete a package from a PTF project on the internal build service. That blocks me from building kernel PTFs as only kernel-source is built but not kernel-default. So please give this high priority. TIA

**Comment by mschnitzer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) P11: Delete group results in error 500](https://trello.com/c/NxDbyPbC/560-3-p11-delete-group-results-in-error-500)
