### ISSUE TITLE
Provide github command line workflow compatibility mode

### ISSUE THREAD

**Issue by celan** [openSUSE/open-build-service#3409]
Many people are used to the git/github workflow for every day use. When switching between osc and git commands it's annyoing and you tend to make mistakes or you are simply slower. Therefore I suggest a compatibility mode like bash has for line editing where you can switch between vi and emacs mode.

**Comment by hennevogel** [comment]
Sounds like you want to make a feature request for osc over at https://github.com/openSUSE/osc
