### ISSUE TITLE
[production][] incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3415]
threw this 7 times
<pre>
incompatible character encodings: UTF-8 and ASCII-8BIT
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/596c81669414f5000a07ad0d)

**Comment by coolo** [comment]
User-Agent: Emacs Elfeed 2.2.0

eat that vim users! :)

**Comment by eduardoj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [P8: (5) Incompatible character encodings: UTF-8 and ASCII-8BIT](https://trello.com/c/5JZRTzZg/706-p8-5-incompatible-character-encodings-utf-8-and-ascii-8bit)
