### ISSUE TITLE
repository delete request is not fully processed

### ISSUE THREAD

**Issue by olafhering** [openSUSE/open-build-service#3418]
As a followup to [https://lists.opensuse.org/opensuse-buildservice/2017-07/msg00024.html](https://lists.opensuse.org/opensuse-buildservice/2017-07/msg00024.html):

The SRs 510894..510898 are in state accepted since `2017-07-17T09:47:25`. All repositories are removed from the project. But packages are still being built for 13.1/13.2, which means SRs 510896/510897 are not fully processed.

As a workaround I added a non-existant Requires for 13.1/13.2 to prevent building for these hidden repositories.
`obs results -v devel:languages:ocaml ocaml`

**Comment by hennevogel** [comment]
Seems like the repository delete has not reached the backend. Fallout of all the outtakes maybe?

**Comment by mdeniz** [comment]
Not reproducible, closing it, if it is still valid for you please reopen. Thanks.
