### ISSUE TITLE
[production][project#new_incident_request] Maintenance incident request contains no defined release target project for package systemd-mini....

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#3420]
project#new_incident_request threw this 19 times
<pre>
Maintenance incident request contains no defined release target project for package systemd-mini.openSUSE_Leap_42.3
</pre>
[https://build.opensuse.org/project/new_incident_request](https://build.opensuse.org/project/new_incident_request)"

[See this exception on Errbit](http://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/597076d053661e000612099b)

**Comment by hennevogel** [comment]
This is a project configuration error. 

```
Maintenance incident request contains no defined release target project for package systemd-mini.openSUSE_Leap_42.3
```

why isn't this exception handled?

**Comment by ChrisBr** [comment]
@hennevogel this is the question :) We should handle this exception.

**Comment by hennevogel** [comment]
Does not happen anymore...
