### ISSUE TITLE
Missing icon to download files in project

### ISSUE THREAD

**Issue by rogeroberholtzer** [openSUSE/open-build-service#3431]
Issue/Feature description
====================
The Web interface to OBS (https://build.opensuse.org) no longer has an icon in the Actions box that allows one to download a file. The Remove icon is still present.

Expected result
============
An icon that allows downloading an item should be present.

How to Reproduce
===============
1. Log in.
2. Go to a package.
3. Try to download a file via the icon in the Actions box.

Further information
===============
* For example: https://build.opensuse.org/package/show/home:rogeroberholtzer:kernel/dc_photocell

**Comment by ChrisBr** [comment]
and deployed to build.o.o
