### ISSUE TITLE
scheduler cannot cope with boolean dependencies

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#3457]
A package (libquvi-scripts, a script collection, lua language) can basically be loaded by any library, linking luaxx

the script collection depends on luasocket for the right lua version (the script collection can't know the lua version, as the 'caller' decides this).

So, the 'best' way was basically to require luaXY-luascript if libluaX_Y was installed, like this:

```
Requires: (lua51-luasocket if liblua5_1-5)
Requires: (lua52-luasocket if liblua5_2-5)
Requires: (lua53-luasocket if liblua5_3-5)
```

This is a new rpm 4.13 feature and works as expected on the workstation side (not sure yet if zypper gets it right, rpm at least does)

on OBS, though, this casues issues if anything requires 'my package' in the chain, resulting in:

> nothing provides (lua51-luasocket if liblua5_1-5) needed by libquvi-scripts, nothing provides (lua52-luasocket if liblua5_2-5) needed by libquvi-scripts, nothing provides (lua53-luasocket if liblua5_3-5) needed by libquvi-scripts

**Comment by mlschroe** [comment]
Whoa, which project/package is this?

**Comment by mlschroe** [comment]
(Rich dependencies should certainly work in OBS)

**Comment by mlschroe** [comment]
Oh, there was a compile time switch missing in perl-BSSolv. Now fixed and deployed. You'll need to rebuild your package with the boolean dependency though, so that the dependency gets parsed correctly. Please reopen if it still doesn't work.
