### ISSUE TITLE
github integration doesn't work with multiple tokens

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#3470]
triggering package builds via github doesn't work if multiple tokens are used. I already have a fix but due to lack of github CLA it won't be accepted:
https://github.com/github/github-services/pull/1218

Please take it and submit if you have CLA. I claim no rights on it.

**Comment by hennevogel** [comment]
@adrianschroeter?

**Comment by adrianschroeter** [comment]
I have the same problem, not CLA signed yet, still  in review by legal.

Don't expect a solution soon....

**Comment by ChrisBr** [comment]
As https://github.com/github/github-services/pull/1218 is merged, we can close this one!
