### ISSUE TITLE
[WebUI] - currently a browser reload causes a style sheet problem breaking UI

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#3491]
Issue/Feature description
====================
Currently the WebUI of b.o.o is borked when you reload a page.

Expected result
============
Normal WebUI with style sheet.

How to Reproduce
===============
Go to a b.o.o page and type f5 in your browser.

Further information
===============
Anywhere on b.o.o

**Comment by mmohring** [comment]
I had the same some time ago. I fixed it by:

1. deleting  all ./api/app/assets + ./api/public/assets directories with rm -rf
2. reinstalling the from the deployment or rpm packages
3. restart apache

You can see the error in production.log, where the page loads which should return 304 now return 404 for some assets. I guess this has to do with some old assets present which did not get deleted with the install.

**Comment by mmohring** [comment]
You can see this in log/apache_access.log on your server, not in log/production.log as I said the the post before.

**Comment by mmohring** [comment]
@adrianschroeter can you please take a look ?

**Comment by hennevogel** [comment]
or just restarting apache...
