### ISSUE TITLE
extend `whatdependson` to dependency project

### ISSUE THREAD

**Issue by marguerite** [openSUSE/open-build-service#352]
Quote Henne's reply on opensuse-buildservice ML:
- So how can I check package dependency in this project against a
  package in its dependency project?
- You can't. builddepinfo isn't inherited. Sounds like a feature we could
  implement

This feature has some values in the real world, eg:
- Porting Pakman:Multimedia packages to ffmpeg 2.0 in Packman:Essentials instead of ffmpeg_oldabi or ffmpeg1 (0.7~1.0 series).
- Porting packages in GNOME:Apps to gstreamer-1_0 in openSUSE:Factory

**Comment by vpereira** [comment]
This feature request will be closed. if you feel that you can improve it or you need it, please re-open it!

thank you!
