### ISSUE TITLE
Local _multibuild changes are not honored

### ISSUE THREAD

**Issue by darix** [openSUSE/open-build-service#3523]
... and the error message is pretty much useless.

```
$ cat _multibuild 
<multibuild>
  <package>postgresql95</package>
  <package>postgresql96</package>
</multibuild>
$ ob-42.3 -M postgresql10
Building pgaudit.spec for openSUSE_Leap_42.3/x86_64
Scanning the following dirs for local packages: ../rpms/42.3
Getting buildinfo from server and store to $PWD/.osc/_buildinfo-openSUSE_Leap_42.3-x86_64.xml
Server returned an error: HTTP Error 400: Bad Request
remote error: did not get project back from src server
```

a better error message would have been:

"unknown flavor 'postgresql10'. known flavors are: postgresql95, postgresql96"

now we add postgresql10 locally:

```
$ osc diff | cat
Index: _multibuild
===================================================================
--- _multibuild (revision 9e69bf4f33d5970416c7fdff9b74949e)
+++ _multibuild (working copy)
@@ -1,4 +1,5 @@
 <multibuild>
   <package>postgresql95</package>
   <package>postgresql96</package>
+  <package>postgresql10</package>
 </multibuild>
```

yet the error message remains the same. normally local changes are forward to the OBS and then taken into account for the evaluation. this paradigm is broken here.

Can this be fixed?

**Comment by hennevogel** [comment]
Please report problems with osc in the osc repo -> https://github.com/openSUSE/osc

**Comment by adrianschroeter** [comment]
This is not (only) osc, the buildinfo post needs to get extended for this.

But this belongs also to the open feature of filtered multibuild containers. In first place a design question...

**Comment by lethliel** [comment]
fixed with commit https://github.com/openSUSE/open-build-service/pull/6460/commits/198bca3b223328487efaf3674d777348d46214c9
