### ISSUE TITLE
Depfu PR's fail because of now following the git cop message schema

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#3529]
Issue/Feature description
====================
The depfu service uses this commit schema:
> Upgrade gem to version 42

Which results in this failure: 

>   Commit Body Presence Warning. Use minimum of 1 line (non-empty).
>   Commit Subject Prefix Error. Use: /\A(?!\s)(\[api\])?(\[backend\])?(\[ci\])?(\[dist\])?(\[doc\])?(\[webui\])? [a-zA-Z]/.

Expected result
============
Either change gitcop or the depfu commit message. I wasn't involved in either of that so I don't know what makes more sense or is more feasible ...

cc @hennevogel @Ana06

**Comment by hennevogel** [comment]
Addressed in #3525

**Comment by Ana06** [comment]
@ChrisBr @hennevogel @bgeuken 

why not changing the depfu commit message instead of changing git-cop? I would say that all commit should be tagged, also the ones from depfu :thinking:

**Comment by ChrisBr** [comment]
@Ana06  Depfu is not our under control as it is a service. AFAIK it is not possible to customize the commit message.

**Comment by Ana06** [comment]
@ChrisBr 
> @Ana06 Depfu is not our under control as it is a service. AFAIK it is not possible to customize the commit message.
ok

**Comment by bgeuken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Depfu PR's fail because of now following the git cop message schema #3529](https://trello.com/c/ZeclX0hn/494-depfu-prs-fail-because-of-now-following-the-git-cop-message-schema-3529)
