### ISSUE TITLE
Wrong ldap logging message

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3542]
If ldap mode is set to "on", you'll get a kinda warning message in the server log file:
```
Someone tried to register with "ldap_mode" turned on
```

when you access the `/users/login` route.

Nothing what harms us but should be fixed. Not a big deal. The check is done in `src/api/app/models/unregistered_user.rb` on line 12. If you refactor that one, try to also move the logging message to a controller instead of a model. It's really ugly :/

**Comment by ChrisBr** [comment]
Why is it better to have it in a controller?

**Comment by mschnitzer** [comment]
@ChrisBr it doesn't make any sense to log messages in a model if you call a method with a `?` mark. Why should a model be responsible for logging? I think this is the controller's task.

**Comment by ChrisBr** [comment]
Why should logging be a controller tasks?

It is only a debugging log so I would say it is fine...

**Comment by bgeuken** [comment]
I agree with Christian.

**Comment by bgeuken** [comment]
And in this case I don't think the logging makes much sense. Whoever is able to read the log, would also know that this server runs in LDAP mode. What's the point in telling this via a debug message.
One line below we raise an exception, which probably pop up in the log  as well.

I would consider removing these debug messages. It looks like they were only used while implementing this feature.

**Comment by bgeuken** [comment]
In any case I doubt we need to track this here. If someone wants to update the logging message or drop it, he can do it right away.
