### ISSUE TITLE
Misleading error message when LDAP server connect fails

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3545]
Just ran into this issue: I set up an LDAP server and OBS always threw me this error message into my face:
```
Not bound as Manager: Can't contact LDAP server
```

I debugged the code and inspected the elements. In the end I figured out that the problem was that the LDAP server can not be reached since SSL was enabled and I did not set up SSL. Maybe rephrasing this error message to something more useful is better and leave the Manager part aside. This distracted me a lot and I thought it's something wrong with my setup.

Example:
```
Cannot reach LDAP server $address on port $port
```

//Edit: Just double checked, there are a bit more error messages and the last one actually says that the connection fails. But since you're getting spammed, this should be a bit more visible. Instead of spamming 15 times (this is the amount of times the server tries to connect to one of the configured LDAP servers) "Manager is not bound", just say that the connection failed.

**Comment by bgeuken** [comment]
First of all, this is just some logging. We can easily change it.

```
Not bound as Manager: Can't contact LDAP server
```

The second part comes from the ldap gem. I would keep it.

The first part could be rephrased to "Failed to establish connection for user 'Manager'" (Manager is just the user's login name).

>  Instead of spamming 15 times (this is the amount of times the server tries to connect to one of the configured LDAP servers) "Manager is not bound",

This mainly happens during the initial setup. And it seems reasonable there. I wouldn't add any workarounds to only show it once within a certain timeframe.

> just say that the connection failed.

Well, that's what the logging output said, can't contact LDAP server ;-)

**Comment by bgeuken** [comment]
And since this is something that can be done in 5 minutes we don't have to track it here:-)
