### ISSUE TITLE
No emojis in comments. Scandalous!

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3547]
comments#create threw this 0 times
<pre>
Mysql2::Error: Incorrect string value: &#39;\xF0\x9F\x99\x86&#39; for column &#39;body&#39; at row 1: INSERT INTO `comments` (`body`, `created_at`, `updated_at`, `user_id`, `commentable_type`, `commentable_id`) VALUES (&#39;🙆&#39;, &#39;2017-08-08 13:15:38&#39;, &#39;2017-08-08 13:15:38.400795&#39;, 142, &#39;Project&#39;, 412)
</pre>
[https://build.opensuse.org/comments](https://build.opensuse.org/comments)"

~~[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5989b97aa8653800064f84d0)~~

~~[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5acb7126b6b7e400060a7b65)~~

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b3792fe1e111a0006749bc6)

**Comment by PVince81** [comment]
From my experience you'd need to switch the Mysql/MariaDB config to use 4-byte unicode and also adjust the collation of all existing tables in a migration
