### ISSUE TITLE
Un-catched exception: The target project openSUSE:Leap:42.1:NonFree is not accepting requests

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3548]
threw this 0 times
<pre>
The target project openSUSE:Leap:42.1:NonFree is not accepting requests because: Please submit to openSUSE:Factory:NonFree or openSUSE:Leap:42.1:Update:NonFree
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5985997d0e17e80006da1db7)

**Comment by mschnitzer** [comment]
OK... This is includes A LOT of refactoring. It's not as easy as it sounds. I'll gonna postpone this.

**Comment by eduardoj** [comment]
Duplicate of #6910. Closing.
