### ISSUE TITLE
[production][request#changerequest] Render and/or redirect were called multiple times in this action. Please note that you may only c...

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3549]
request#changerequest threw this 0 times
<pre>
Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like &quot;redirect_to(...) and return&quot;.
</pre>
[https://build.opensuse.org/request/changerequest](https://build.opensuse.org/request/changerequest)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5985997f0e17e80014da1db7)

**Comment by bgeuken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Render and/or redirect were called multiple times #3549](https://trello.com/c/OMtPciCD/492-render-and-or-redirect-were-called-multiple-times-3549)
