### ISSUE TITLE
incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3550]
threw this 2 times
<pre>
incompatible character encodings: UTF-8 and ASCII-8BIT
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59881fb0178744000e940a26)

**Comment by hennevogel** [comment]
This happens when rendering emails

**Comment by ChrisBr** [comment]
duplicate of https://github.com/openSUSE/open-build-service/issues/3550
(which you created :smile: )
