### ISSUE TITLE
'Edit account' save button on profile pages removes admin privileges

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3566]
An admin can either edit themselves via the `Configuration` or at their profile page. If the admin updates themselves over the profile page, the admin rights get revoked since it posts to the action `#save` without the `globalrole` param.

**Comment by adrianschroeter** [comment]
Uh, do you know if 2.8 branch is also affected?

**Comment by mschnitzer** [comment]
@adrianschroeter confirmed for master and 2.8

**Comment by adrianschroeter** [comment]
k, I think, I know the reason for the problems of two users then ...

**Comment by bgeuken** [comment]
I'll have a look at this
