### ISSUE TITLE
_multibuild files uploaded to build disabled package not recognized

### ISSUE THREAD

**Issue by darix** [openSUSE/open-build-service#3573]
during a cleanup i disabled building for a complete project

while fixing one package i ran into the bug that local _multibuild files are not recognized until you commit them. now the problem is that with a build disabled package the files are still not recognized for local builds. you need to enable building of the package before you can have a successful local build.

**Comment by adrianschroeter** [comment]
sounds like a duplicate of your #3523 report, no?

**Comment by darix** [comment]
no.

it is related but not the same.

**Comment by lethliel** [comment]
fixed with commit https://github.com/openSUSE/open-build-service/pull/6460/commits/198bca3b223328487efaf3674d777348d46214c9
