### ISSUE TITLE
backend: RPC call from scheduler to srcserver should have a timeout

### ISSUE THREAD

**Issue by bugfinder** [openSUSE/open-build-service#3579]
just seen that the OBS back-home schedulers for i586 and x86_64 were basically idling.
caused by a long running RPC call (one for each of the schedulers).

running async RPC requests:
- src-opensuse:5352: 1 running, 657/0 waiting

the process ran for almost 10h

from bs_serverstatus on src-server:
R  32429 32288 GET (192.168.2.5)      /getprojpack?view=storable&withsrcmd5&withdeps&withrepos&withconfig&withremotemap&arch=x86_64&partition=back-home&project=home:favogt:branches:openSUSE:Factory:Live&package=livecd-openSUSE

**Comment by adrianschroeter** [comment]
well, if that call takes 10h something else is broken, should be quite fast when running just for one package ...

**Comment by adrianschroeter** [comment]
bug in simple xml parser of build script, fixed now.
