### ISSUE TITLE
Review list no longer sortable by 'source'

### ISSUE THREAD

**Issue by toabctl** [openSUSE/open-build-service#3582]
Issue/Feature description
====================
Some weeks ago it was possible to sort a review list (eg https://build.opensuse.org/project/requests/devel:languages:python ) by "Source". Now clicking on "Source" does noting.
The problem is that eg for devel:languages:python, the only way to see incoming review requests (from home to d:l:p) is to sort by source. Otherwise you also see the huge list of requests which go to openSUSE:Factory.

Expected result
============
Clicking on the different table headers sort the table

How to Reproduce
===============
1. Click on any table header

**Comment by hennevogel** [comment]
@ChrisBr maybe your package changes?

**Comment by ChrisBr** [comment]
@evanrolfe I'm right that review tables are now also AJAX table, right? Because before the package/request table were no AJAX table which made it possible to filter by it....

**Comment by ChrisBr** [comment]
@toabctl workaround: you can also search now by source, enter in the search box ``home`` which would filter only for home projects. Hope that helps!

**Comment by ChrisBr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Review list no longer sortable by 'source' #3582](https://trello.com/c/Mo9tKD7G/487-review-list-no-longer-sortable-by-source-3582)
