### ISSUE TITLE
Mysql2::Error: Data too long for column 'body' at row 1: INSERT INTO `comments`

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3584]
comments#create threw this 5 times
<pre>
Mysql2::Error: Data too long for column &#39;body&#39; at row 1: INSERT INTO `comments` (`body`, `created_at`, `updated_at`, `user_id`, `commentable_type`, `commentable_id`) VALUES (&#39;&lt;!-- RepoChecker state=seen result=failed --&gt;\n\n## x86_64\n\n### [install check &amp; file conflicts](/package/view_file/openSUSE:Factory:Staging/dashboard/repo_checker)\n\n```\ncan\&#39;t install ruby2.4-rubygem-fluentd-0.14.20-10.1.x86_64:\n  nothing provides rubygem(ruby:2.4.0:ruby_dig:0.0) &gt;= 0.0.2 needed by ruby2.4-rubygem-fluentd-0.14.20-10.1.x86_64\ncan\&#39;t install ruby2.4-rubygem-quiet_assets-1.1.0-1.1.x86_64:\n  package ruby2.4-rubygem-quiet_assets-1.1.0-1.1.x86_64 requires rubygem(ruby:2.4.0:railties) &lt; 5.0, but none of the providers can be installed\n  nothing provides rubygem(ruby:2.4.0:actionpack) = 4.2.8 needed by ruby2.4-rubygem-railties-4_2-4.2.8-1.1.x86_64\n    (we have ruby2.4-rubygem-actionpack-5_0-5.0.5-15.1.x86_64)\n    (we have ruby2.4-rubygem-actionpack-4_2-4.2.9-26.1.x86_64)\n  nothing provides rub
</pre>
[https://api.opensuse.org/comments/project/openSUSE:Factory:Staging:adi:298](https://api.opensuse.org/comments/project/openSUSE:Factory:Staging:adi:298)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/598b73496f06a10006fbdad1)

**Comment by hennevogel** [comment]
`Comment` should have a validation for `body` length so we can tell our users instead of crashing...

**Comment by jberry-suse** [comment]
What is the length limit so I can enforce that on the bot instead of the power of two I picked?

**Comment by mschnitzer** [comment]
@jberry-suse the maximum length is set to 65535 chars.
