### ISSUE TITLE
EventMailer: Requests from remote projects

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3587]
When submitting packages from remote projects to local projects `EventMailer` tries to generate a diff but that fails in a [access check](../blob/master/src/api/app/models/bs_request_action.rb#L922) because the it uses

```
Package.find_by_project_and_name(source_project, source_package)
```

which returns nil for remote projects. It the wanders off into the `if sp.nil?` and tries `User.-current.can_modify_project?` which fails miserably because there is no user logged in during delayed jobs.

**Comment by adrianschroeter** [comment]
I doubt take the anonymous user for delayed job ...

**Comment by hennevogel** [comment]
@adrianschroeter it all boils down to this question:

Should you be able to deny source_access to projects that define remote instances.

So should you be able to deny source access to a project like `openSUSE.org` if you create an interconnect?

**Comment by adrianschroeter** [comment]
No, it is up to the remote instance to decide if it delivers the source or not. 

Therefore a simple

 User.current ||= User.find_by_login(User.nobody_login)

in the job should solve this. The only problem here might be that this also hides sources in the target which are read protected. But you would check there against all people who receive the event.

However, we can ignore this for now and just stay on the secure side with the nobody user.

**Comment by bgeuken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [EventMailer: Requests from remote projects #3587](https://trello.com/c/jfdhpxuy/484-eventmailer-requests-from-remote-projects-3587)

**Comment by hennevogel** [comment]
@bgeuken's patch isn't working
