### ISSUE TITLE
DoD repository breakes dependency resolution (unresolvable: nothing provides)

### ISSUE THREAD

**Issue by m407** [openSUSE/open-build-service#3589]
Issue/Feature description
====================
On self-hosted OBS (v2.8.2) instance dependant packages can not be built if in Meta DoD repository is configured. OBS gives "unresolvable: nothing provides"

Expected result
============
Successful buliding of **package1** and **package2** (BuildRequires: package1)

How to Reproduce
===============

1. Used latest [OBS Appliance 2.8.2](http://openbuildservice.org/download/)
2. Update **zypper up && zupper dup from openSUSE:Tools**
3. Create tesing project **testing** with  meta:
```
<project name="testing">
  <title/>
  <description/>
  <person userid="Admin" role="maintainer"/>
  <repository name="openSUSE_Leap_42.3">
    <path project="openSUSE:Leap:42.3" repository="standard"/>
    <arch>x86_64</arch>
  </repository>
</project>

```
4. Create package1 with package1.spec:

```
Name:           package1
Version:        1.0.0
Release:        0
License:        BSD-2-Clause
Summary:        Package1 pack
Group:          Development/Languages/NodeJS
BuildArch:      noarch

%description
%prep
%build
%install
%files
%changelog

```
5. Create package2 with package2.spec:
```
Name:           package2
Version:        1.2.0
Release:        0
License:        BSD-2-Clause
Summary:        Package1 pack
Group:          Development/Languages/NodeJS
BuildArch:      noarch

BuildRequires:     package1

%description
%prep
%build
%install
%files
%changelog
```
6.  Both packages are bult successfully
7. Add to repository section of meta:
```
 <download arch="x86_64" url="http://download.opensuse.org/repositories/devel:/languages:/nodejs/openSUSE_Leap_42.3/" repotype="rpmmd"/>
```
8. From now on you will get `unresolvable: nothing provides package1` for package2

**Comment by adrianschroeter** [comment]
please don't build inside of a repository which is also doing DoD, this is not supported.
