### ISSUE TITLE
User requests table displays incorrect created date, but sorts correctly

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/open-build-service#3598]
Issue/Feature description
====================

![image](https://user-images.githubusercontent.com/22943929/29294741-87bbae7e-8116-11e7-8158-ca5c523ae06a.png)

Note the `Created` column:

- `2 hours`
- `13 minutes`
- `3 hours`
- `32 minutes`

If one opens the individual requests the created dates make sense given the order.

Expected result
============

The values in the `Created` column would accurately display the real values

How to Reproduce
===============

Visit `/user/show/<user>`.

**Comment by ChrisBr** [comment]
Thanks for reporting, will have a look into it!

**Comment by ChrisBr** [comment]
@jberry-suse I'm really wondering how this could happen and was not able to reproduce :cry: 
Could you please include the next time when you experience it a screenshot of the whole table (so that I can also see the other colums) and maybe even the request id/number. Would make it a lot easier to debug. Thanks!

**Comment by jberry-suse** [comment]
Will do. I have seen it before, but it seems intermittent. I forgot to mention that in the original bug.

**Comment by jberry-suse** [comment]
It happened again.

![image](https://user-images.githubusercontent.com/22943929/29382851-98f8b1a4-8293-11e7-9c61-e2f9818e6fbf.png)

I extracted the HTML table: https://gist.github.com/jberry-suse/f567bb3132f22729e8057bdcfbe879ff which should give you all the details.

**Comment by jberry-suse** [comment]
Full page reloads resulted in same list.

**Comment by ChrisBr** [comment]
@jberry-suse thanks a lot for the detailed response :+1: :+1: :+1: 
Looks like it is a caching issue :cry: We will deploy a fix within the next few hours!

**Comment by ChrisBr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix request timestamp caching](https://trello.com/c/wf4NaNrm/497-fix-request-timestamp-caching)
