### ISSUE TITLE
[production][active_job#UpdatePackagesIfDirtyJob] undefined method `update_packages_if_dirty' for 88256:Integer

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#3605]
active_job#UpdatePackagesIfDirtyJob threw this 197 times
<pre>
undefined method `update_packages_if_dirty&#39; for 88256:Integer
</pre>

[See this exception on Errbit](http://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/598eb56f34e036001071443a)

**Comment by hennevogel** [comment]
@evanrolfe and me think this was an error in a monkey patch. We've never called this method on the job argument...
