### ISSUE TITLE
Have more diverse set of image template icons

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#3609]
Issue/Feature description
====================

Since some months we have the image template page[*] which allows users to provide templates and clone them from that page.

As for right now most templates have the same (default) image icon to present their appliance. It would be nice to change this. Either by encouraging them to update this, like some notification / hint inthe ui. Or by providing a set of default icons, eg. a default icon for server apps, virtual image configurations, cloud, Desktop, etc.

Of course one option doesn't rule out the other and there might be additional things we could do.

[*] https://build.opensuse.org/image_templates

Expected result
============

Have more diverse icons for image templates.

**Comment by hellcp** [comment]
Maybe as a replacement for this, class name for fontawesome? It would provide more options than we could ever create.

**Comment by hennevogel** [comment]
The icons are content not code. Send submit requests that change `_icon` in the template projects...
