### ISSUE TITLE
Comments using markdown codeblock should not have html entities escaped

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/open-build-service#3619]
Issue/Feature description
====================

A picture is worth a thousand words.

![image](https://user-images.githubusercontent.com/22943929/29373071-a53236b4-8272-11e7-8797-1786ee6d1f6d.png)

The same input was used in both cases, but one was wrapped by 
```
\```
```

Expected result
============

Expect both to properly display `>=` instead of `&gt;=`. The effects nearly all of the `repo-checker` comments.

![image](https://user-images.githubusercontent.com/22943929/29373169-f021f510-8272-11e7-92c3-b3f91af22447.png)

How to Reproduce
===============

Post comment describe above.

**Comment by hennevogel** [comment]
We need to escape user input, especially `<` and `>`, otherwise you can do XSS attacks. You can wrap this into a `<pre>` if you need the output unaltered.

**Comment by jberry-suse** [comment]
I understand XSS having done extensive web development, but that is not really the issue here. Looks like `<pre>` makes it through. Every tool has it own unique formatting rules and OBS does not seem to document them or at least not prominently like a link under the comment field.

**Comment by hennevogel** [comment]
Yeah well, some time....
