### ISSUE TITLE
[production][repositories#index] undefined method `each_with_index' for nil:NilClass

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#3642]
repositories#index threw this 0 times
<pre>
undefined method `each_with_index&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/repositories/home:lachs0r:mandelbulber2](https://build.opensuse.org/repositories/home:lachs0r:mandelbulber2)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/599a18743853dc00066713e1)

**Comment by eduardoj** [comment]
Seems to be related to #2200

**Comment by bgeuken** [comment]
Yep, looks like a duplicate. I've updated the errbit link in the other PR. The old one wasn't working anymore
