### ISSUE TITLE
[production][active_job#IssueTrackerUpdateIssuesJob] execution expired

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#3647]
active_job#IssueTrackerUpdateIssuesJob threw this 5 times
<pre>
execution expired
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/599adc073e66930006a9c9c9)

**Comment by hennevogel** [comment]
This happens when `IssueTracker.private_fetch_issues` takes too long to fetch all the issues. It's an exception that can occur and we can not do much about it I think.

**Comment by bgeuken** [comment]
> hennevogel commented
> This happens when IssueTracker.private_fetch_issues takes too long to fetch all the issues. It's an exception that can occur and we can not do much about it I think.
--

Okay. Then let's close it.
