### ISSUE TITLE
webui build log crashes on not existing (multibuild) package container

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#3677]
Issue/Feature description
====================

Clicking on a monitor page on status element forwards to the build log. webui just reports a 500 if the package disappeared meanwhile. This can happen easily given that there is alway a time difference between source change and build result recalculation.

Expected result
============

Getting told that the package does not exist (anymore) and getting forwarded back.

How to Reproduce
===============
Just use any build log for any multibuild container which does not exist. For example:

 https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Live/livecd-x11:asd/images/i586

**Comment by eduardoj** [comment]
I reproduced the steps and got this flash message: "Couldn't find package 'livecd-x11:asd' in project 'openSUSE:Factory:Live'. Are you sure it exists?"

Closing. Please reopen if the issue still applies.
