### ISSUE TITLE
[production][package#branch] <status code="400">
  <summary>home:scalpel4k/libmypaint: package 'libmypaint' does not exist</su...

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3684]
package#branch threw this 0 times
<pre>
&lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;home:scalpel4k/libmypaint: package &#39;libmypaint&#39; does not exist&lt;/summary&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/package/branch](https://build.opensuse.org/package/branch)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59a061bee896f000065bd5ba)

**Comment by mschnitzer** [comment]
Seems to be the same as for #3683

**Comment by hennevogel** [comment]
It's the same 'issue'. Just the message from the backend is different...

https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5995b7a6a7f61700069a035b

**Comment by hennevogel** [comment]
Okay we are going to track all `Package.branch` exceptions in #3734 now
