### ISSUE TITLE
[production][package#save] Mysql2::Error: Data too long for column 'description' at row 1: UPDATE `packages` SET `updated_at...

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3685]
package#save threw this 0 times
<pre>
Mysql2::Error: Data too long for column &#39;description&#39; at row 1: UPDATE `packages` SET `updated_at` = &#39;2017-08-25 12:35:50.179541&#39;, `description` = &#39;[...]
</pre>
[https://build.opensuse.org/package/save/xxx/check](https://build.opensuse.org/package/save/xxx/check)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a466743dfd75b00060b6944)

**Comment by mschnitzer** [comment]
We should validate this.

**Comment by eduardoj** [comment]
Fixed with #3715.
