### ISSUE TITLE
[production][images#show] Not found

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3686]
images#show threw this 0 times
<pre>
Not found
</pre>
[https://build.opensuse.org/kiwi_images/5](https://build.opensuse.org/kiwi_images/5)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/599789c6d082a3000f04e63a)

**Comment by mschnitzer** [comment]
This https://github.com/openSUSE/open-build-service/blob/master/src/api//app/controllers/webui/webui_controller.rb#L278 should definitely not be an exception. Instead render a 404 error.

**Comment by ChrisBr** [comment]
Fixed and deployed with https://github.com/openSUSE/open-build-service/pull/3710
