### ISSUE TITLE
Accept delete request of pkg with depending devel package definitions impossible

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#3687]
I created a setup in my home project to demonstrate the issue

Project: home:dimstar
package1: pkg
package2: pkg-sub (has pkg set as devel package)

A delete request against pkg is filed (rq 519110), but can't be accepted (also not using osc rq accept -f)

In this setup it is pretty simply for me to work around the issue, as I can change the meta config of pkg-sub; but I've seen cases where packages across projects had my packages set as devel, which means I can't delete them unless I get the other user to change his meta data)

**Comment by DimStar77** [comment]
> osc rq accept 519110 -m ok -f
```
HTTP Error 400: Bad Request
delete_error
Package is used by following packages as devel package: home:dimstar/pkg-sub
```

**Comment by DimStar77** [comment]
This is hitting quite often and is really annoying - especially as TW is also managed by more people; can we somehow get to a solution that allows to delete a package forcibly?

**Comment by eduardoj** [comment]
Try deleting the package directly on the server, with the `force` option: `osc rdelete home:dimstar pkg -f`.

For details on more options: `osc rdelete -h`

Closing. Please reopen if this solution is not complete.
