### ISSUE TITLE
[production][] The target project openSUSE:Leap:42.1:NonFree is not accepting requests because: Please submit to...

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3692]
threw this 0 times
<pre>
The target project openSUSE:Leap:42.1:NonFree is not accepting requests because: Please submit to openSUSE:Factory:NonFree or openSUSE:Leap:42.1:Update:NonFree
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59a4dda24277810006e79483)

**Comment by mschnitzer** [comment]
This should not raise an exception...

**Comment by DavidKang** [comment]
Duplicate in #3548
