### ISSUE TITLE
Add $HOME to service environment

### ISSUE THREAD

**Issue by Jellyfrog** [openSUSE/open-build-service#3694]
Issue/Feature description
====================
We have a custom service that excepts $HOME to be set so it knows where to cache files
However, running for example `printenv` gives me:

```
CONSOLE=/dev/console
LC_ALL=POSIX
OBS_SERVICE_APIURL=https://private-obs
REDIRECT=/dev/tty1
COLUMNS=100
OBS_SERVICE_PROJECT=Foo:bar
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUNLEVEL=3
PWD=/srv/obs/service/107387/src
DAEMON=/usr/lib/obs/server/bs_service
PREVLEVEL=
LINES=37
SHLVL=2
OBS_SERVICE_PACKAGE=foo-bar
LC_CTYPE=en_US.UTF-8
_=/usr/bin/printenv
```

Expected result
============
Expected `HOME=/usr/lib/obs` to be present in the env

How to Reproduce
===============
1. Add for example: `printenv ; exit 1` to a service
2. Trigger the service
3. Check the latest *\*_serviceerror*-file in */srv/obs/trees/Foo:bar/foo-bar/*

Further information
===============
```
obs-common-2.8.2-1.2.noarch
obs-api-2.8.2-1.2.noarch
obs-signd-2.3.0-1.3.x86_64
obs-source_service-2.8.2-1.2.noarch
obs-server-2.8.2-1.2.noarch
obs-productconverter-2.8.2-1.2.noarch
```

**Comment by adrianschroeter** [comment]
/usr/lib/obs would not be writable and therefore misleading.

Seems your service need a config file to set this, eg. to /var/cache/$something , but not that you need to create the directory there and change ownership.
