### ISSUE TITLE
Nonexistant "zombie" multibuild packages get rebuilt

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/open-build-service#3696]
To create zombie packages:

1. Create a _multibuild container with some packages
2. Link the container to build the various packages without _multibuild
3. Delete the _multibuild file

The result is that the original _multibuild container packages are still shown everywhere and even being built if deps change.

Example: https://build.opensuse.org/project/monitor/home:favogt:branches:openSUSE:Factory:Live

**Comment by mlschroe** [comment]
Yes, a multibuild->non-multibuild transaction was not handled correctly in the source server. Fixed with commit dcabad7dc8043dad013565bb690decdf8699209c.
