### ISSUE TITLE
[production][package#rpmlint_log] <status code="400">
  <summary>unknown request: GET:/build/system:snappy/&lt;font&gt;&lt;font&gt;...

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3699]
package#rpmlint_log threw this 9 times
<pre>
&lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;unknown request: GET:/build/system:snappy/&amp;lt;font&amp;gt;&amp;lt;font&amp;gt;openSUSE_Leap_42.3&amp;lt;/font&amp;gt;&amp;lt;/font&amp;gt;/x86_64/snapd/rpmlint.log&lt;/summary&gt;
  &lt;details&gt;400 unknown request: GET:/build/system:snappy/&amp;lt;font&amp;gt;&amp;lt;font&amp;gt;openSUSE_Leap_42.3&amp;lt;/font&amp;gt;&amp;lt;/font&amp;gt;/x86_64/snapd/rpmlint.log&lt;/details&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/package/rpmlint_log?project=system%3Asnappy&amp;package=snapd&amp;repository=%3Cfont%3E%3Cfont%3EopenSUSE_Leap_42.3%3C%2Ffont%3E%3C%2Ffont%3E&amp;architecture=x86_64](https://build.opensuse.org/package/rpmlint_log?project=system%3Asnappy&amp;package=snapd&amp;repository=%3Cfont%3E%3Cfont%3EopenSUSE_Leap_42.3%3C%2Ffont%3E%3C%2Ffont%3E&amp;architecture=x86_64)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59a527804277810006e79570)

**Comment by ChrisBr** [comment]
Looks like some script generates a wrong URL. The malformed parameter is:
```
repository=<font><font>openSUSE_Leap_42.3</font></font>
```

**Comment by lnussel** [comment]
rpmlint.opensuse.org does @kraih wrote the code

**Comment by kraih** [comment]
The repo is [here](https://github.com/openSUSE/build-check-statistics). I'll take a look when i've got some time.

**Comment by bgeuken** [comment]
Doesn't seem to be a bug in OBS. Thus closing
