### ISSUE TITLE
Favicon is not rendered

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3707]
A user just pointed out, that the favicon is no longer rendered on `build.opensuse.org`.

**Comment by mschnitzer** [comment]
Input from the user: The bug was probably introduced within one `2.8.x` release. It works for him on his 2.7.4 instance.

**Comment by ChrisBr** [comment]
It is only the case on build.o.o. On local and dev instances it works fine so seems it is something with our deployment. And btw, it is already broken since a loooong time!

**Comment by eduardoj** [comment]
Fixed. It was a deployment configuration issue.
