### ISSUE TITLE
[production][active_job#AcceptRequestsJob] wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3708]
active_job#AcceptRequestsJob threw this 4 times
<pre>
wrong number of arguments (given 2, expected 1)
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59a6121584aa620008b7ca66)

**Comment by eduardoj** [comment]
Closing the issue given that:
* The exception on Errbit doesn't exist any more.
* There is no exception on Errbit found searching with the string `AcceptRequestsJob` in the last year.

Please reopen if it happens again.
