### ISSUE TITLE
[production][package#submit_request] Mysql2::Error: Data too long for column 'description' at row 1: INSERT INTO `bs_requests` (`descr...

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3729]
package#submit_request threw this 0 times
<pre>
Mysql2::Error: Data too long for column &#39;description&#39; at row 1: INSERT INTO `bs_requests` (`description`, `creator`, `state`, `commenter`, `created_at`, `updated_at`, `number`) VALUES (&#39;- Bump version: 9.10.5 → 9.10.6\r\n  \r\n  \r\n- Added boot descriptions for SLE15 on ppc\r\n  \r\n  \r\n- Added boot descriptions for SLE15 on s390\r\n  \r\n  \r\n- Bump version: 9.10.4 → 9.10.5\r\n  \r\n  \r\n- Added handling of formatoptions attribute\r\n  \r\n  Custom disk format options passed in the formatoptions\r\n  attribute were not handled. In addition options with a\r\n  value passed to qemu were handled in the wrong way.\r\n  This commit addresses both problems and Fixes #463\r\n  \r\n  \r\n- s/sles/openSUSE/\r\n  \r\n  \r\n- copy SLE15 files for Leap 15\r\n  \r\n  \r\n- add Leap 15 macros\r\n  \r\n  \r\n- leap_version is deprecated. use sle_version+is_openuse instead\r\n  \r\n  \r\n- Added azure integration test build to obs status\r\n  \r\n  \r\n- Bump version: 9.10.3 → 9.10.4\r\n  \r\n  
</pre>
[https://build.opensuse.org/package/submit_request/Virtualization:Appliances:Builder/python-kiwi](https://build.opensuse.org/package/submit_request/Virtualization:Appliances:Builder/python-kiwi)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59a699d91adc940006afc2a4)

**Comment by hennevogel** [comment]
We should validate this...

**Comment by eduardoj** [comment]
The exception on Errbit doesn't exist any more. Already fixed with #3867.
