### ISSUE TITLE
Project delete may modify project meta in backend before delete

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#3735]
Issue/Feature description
====================

Project restore may not restore the exact same project meta, if a repository builds against the same project. The restored project will point to "deleted" repository instead.

Expected result
============

Restore the same project meta, which existed when the project delete was executed..

How to Reproduce
===============
1. Create project A with repo B and C
2. Repo B need to have repo C in path
3. delete and undelete project.

Further information
===============
* This is caused by automatic store in Repository model, leading to a project meta PUT before DELETE operation

Example (The repository `home_Admin_project_abc_openSUSE_Leap_15.0` will be gone after `undelete`:
![issue](https://user-images.githubusercontent.com/1102934/51912364-708f7700-23d4-11e9-81d2-74303fd6401f.png)

**Comment by adrianschroeter** [comment]
@mdeniz this is mostly fixed, right?

So we should either close or adapt it (IIRC it still modifies the project meta before storing, so we recover with a deleted path entry?)

**Comment by mdeniz** [comment]
Yes, it leaves the source paths to the **deleted** path and then deletes the actual project, when it is going to be recovered that is the last status of the meta.

Closing it or changing it... I guess is up to you 👍

**Comment by adrianschroeter** [comment]
k, then we should fix the last bit of regression (the deleted path storage)

**Comment by adrianschroeter** [comment]
it becomes worse meanwhile again, it stores even with removed user/group roles and removed one repository out of two. The keeps to be a time eater and is a show stopper for a stable OBS release.

**Comment by hennevogel** [comment]
@adrianschroeter please keep an eye on this one

**Comment by adrianschroeter** [comment]
much better indeed. Data gets restored.

However, there is still a spurious second commit on undelete. Lacks comment and seems to have no actual changes (in my example), but should be avoided. Unsure if there can be a change in second commit.

Testcase showing the problem: https://github.com/openSUSE/open-build-service/pull/7024
