### ISSUE TITLE
[production][delayed_job#Delayed::PerformableMethod] undefined method `index' for #<ThinkingSphinx::RakeInterface:0x00000005d03a90>

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3737]
delayed_job#Delayed::PerformableMethod threw this 160 times
<pre>
undefined method `index&#39; for #&lt;ThinkingSphinx::RakeInterface:0x000000062ff430&gt;
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59a836306180760014d02073)

**Comment by mmohring** [comment]
I have noticed that the /usr/bin/searchd is not starting up in current git master with the new version of rubygem-thinking-sphinx. This causes a 500 when you make a search in the WebUI.

**Comment by eduardoj** [comment]
This issue should be fixed with #3741

Regarding /usr/bin/searchd not starting up, that should be fixed with #3753
