### ISSUE TITLE
[api][delayed_job] - /usr/bin/searchd not starting up anymore

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#3744]
Issue/Feature description
====================
Running a search from the WebUI does not work with current git master of today, sphinx daemon no starting up by delayed jobs.

Expected result
============
Search should work, sphinx daemon should start up automatically by delayed jobs.

Further information
===============
* /usr/bin/searchd is not started anymore.
* starting /usr/bin/searchd by hand on the command line works, then search in WebUI works again

Can this be related to issue #3737 ?

**Comment by mmohring** [comment]
With the current git master I have also updated to the new rubygem-thinking-sphinx 3.4.1.

**Comment by mschnitzer** [comment]
Regarding #3737: I'm pretty sure this is completely unrelated.

I also don't think 739b1b6 is the root cause. Could you check if there are any errors in `/var/log/sphinx` or in the log file of OBS?

**Comment by mmohring** [comment]
@mschnitzer I am not saying this is related to the OBS code. It seems related to the update of rubygem-thinking-sphinx to 3.4.1. The /var/log/sphinx has no new lines, only the exit message from the last shutdown of OBS, seems because it does not start up in v 3.4.1. I will check the production.log.

**Comment by mmohring** [comment]
I see this line in the production.log:

I, [2017-09-04T12:58:21.683382 #2278]  INFO -- : [2278:60.30] 2017-09-04T12:58:21+0200: [Worker(delayed_job.2 host:api pid:2278)] Job FullTextSearch#index_and_start (id=2989212) (queue=quick) RUNNING
E, [2017-09-04T12:58:11.646288 #2272] ERROR -- : [2272:50.40] 2017-09-04T12:58:11+0200: [Worker(delayed_job.1 host:api pid:2272)] Job FullTextSearch#index_and_start (id=2989212) (queue=quick) FAILED (0 prior attempts) with NameError: undefined local variable or method `logger' for #<FullTextSearch:0x000000063425c8 @result=nil>

**Comment by mmohring** [comment]
I can start the searchd from rubygem-thinking-sphinx 3.4.1 with:

$ su -m -c"/usr/bin/searchd --pidfile --config /srv/www/obs/api/config/production.sphinx.conf" wwwrun

Then it works.

**Comment by mmohring** [comment]
git commit b08c5efcd1963de25245d63a804d1d34277d3c83 seems to fix it.
