### ISSUE TITLE
dangling symlinks: obs-server/README.SETUP and obs-api/README.SETUP (obs 2.8.3)

### ISSUE THREAD

**Issue by c-hoeger** [openSUSE/open-build-service#3746]
Issue/Feature description
====================

both README.SETUP files are dangling symlinks on 2.8.3:

    vagrant@buildservice:~> less /usr/share/doc/packages/obs-server/README.SETUP
    /usr/share/doc/packages/obs-server/README.SETUP: No such file or directory
    vagrant@buildservice:~> ls -al /usr/share/doc/packages/obs-server/README.SETUP
    lrwxrwxrwx 1 root root 12 Sep  4 08:46 /usr/share/doc/packages/obs-server/README.SETUP -> ../README.md
    vagrant@buildservice:~> ls -al /usr/share/doc/packages/obs-api/README.SETUP
    lrwxrwxrwx 1 root root 12 Sep  4 08:48 /usr/share/doc/packages/obs-api/README.SETUP -> ../README.md
    vagrant@buildservice:~>

**Comment by hennevogel** [comment]
We never came around to do this and don't support 2.8 anymore since a long time. Sorry...
