### ISSUE TITLE
[production][active_job#IssueTrackerFetchIssuesJob] end of file reached

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#3752]
active_job#IssueTrackerFetchIssuesJob threw this 1 times
<pre>
end of file reached
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59adad0af107930006424c80)

**Comment by hennevogel** [comment]
never happened again...
