### ISSUE TITLE
[production][repositories#create_image_repository] Validation failed: Name images is already used by a repository of this project.

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3757]
repositories#create_image_repository threw this 12 times
<pre>
Validation failed: Name images is already used by a repository of this project.
</pre>
[https://build.opensuse.org/project/create_image_repository?project=home%3Asergey-safarov](https://build.opensuse.org/project/create_image_repository?project=home%3Asergey-safarov)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59a978dcd66401001427043d)

**Comment by hennevogel** [comment]
Just click a thousand times on the checkbox for any repository. Why isn't this catched?

**Comment by bgeuken** [comment]
I guess we should abort the previously made request. Though that's easier said than done

**Comment by bgeuken** [comment]
Duplicate of  #4048
