### ISSUE TITLE
New feature: Search for "submit request" by ID

### ISSUE THREAD

**Issue by SergioAtSUSE** [openSUSE/open-build-service#3759]
Feature description
====================

Having a known submit request ID, when I want to search for it, the only way to do that is typing the url on https://build.opensuse.org/request/show/XXXX, where XXXX is the submit request ID.

Expected result
============

The search box provides results of the submit request that matches this ID.

Further information
===============
* Existing submit request: https://build.opensuse.org/request/show/521097
* Current search result by ID: https://build.opensuse.org/search?search_text=521097

**Comment by ChrisBr** [comment]
Just add the hash # in front of the number and it will redirect you to the link :smile: 
https://build.opensuse.org/search?search_text=#521097
