### ISSUE TITLE
Preinstall packages with <LUA> scripts - > script not runnable

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#3774]
While debugging some 'fun' issues, I came across the following problem:

- In general, system-user-root should be put into the Preinstall section of prjconf (we shuld really have it as early as possible)
- The main part of this package is the LUA based post script, so we also need to add system-user-root to Runscripts

with this setup, though, the chroot setup fails, as it tries to feed the LUA script to bash, as the build log contains:

```
[   11s] .init_b_cache/scripts/system-user-root.pre: line 1: syntax error near unexpected token `('
[   11s] .init_b_cache/scripts/system-user-root.pre: line 1: `if not posix.access("/etc", "f") then'
```

I created a test-project / package to visualize this:

https://build.opensuse.org/package/live_build_log/home:dimstar:bug/FOO/openSUSE_Tumbleweed/x86_64

The various scripts in system-user-root all look like this:

```
%pre -p <lua>
[...]
```

**Comment by hennevogel** [comment]
You want to open this report over at https://github.com/openSUSE/obs-build
