### ISSUE TITLE
Publisher penalty too cruel

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#3776]
We have a OBS instance here that basically builds a single repository with tons of ISOs - let's call them SLE. 

Most of the day the publisher has nothing to do but syncing these ISOs somewhere else. But it refuses to do so and just says 'not yet'. This is hurting our dead lines massively and is pretty nonsense too as there is no other publish event to worry about in that time waiting.

**Comment by adrianschroeter** [comment]
On Donnerstag, 7. September 2017, 13:04:09 CEST wrote Stephan Kulow:
> We have a OBS instance here that basically builds a single repository with tons of ISOs - let's call them SLE. 
> 
> Most of the day the publisher has nothing to do but syncing these ISOs somewhere else. But it refuses to do so and just says 'not yet'. This is hurting our dead lines massively and is pretty nonsense too as there is no other publish event to worry about in that time waiting.

we need to handle the penalty not repository wide for product/appliance builds, but per project/repo/container

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by coolo** [comment]
and then? still idling around saying 'not yet' if one container exceeded some magic number?

**Comment by JPerkster** [comment]
We've been hit by this throttling mechanism. We ended up removing the multiplier and as a secondary kicker, we cron'd a restart of the obspublisher service if the publisher log shows "Sleeping" to bypass it.

**Comment by coolo** [comment]
Can we please get rid of this?

**Comment by coolo** [comment]
As we yesterday and again today do nothing but waiting for a long sleep in the publisher - THIS IS HURTING!!!

**Comment by adrianschroeter** [comment]
we will definitive not block all other publishing, including maintenance updates just for factory ....

I see no other way atm as to implement the publish penalty per product.

Are you sure that you don't have another problem btw, there was no publish event in last 50 minutes on main and stage backends in last  ~ 50 minutes ....

**Comment by coolo** [comment]
Factory doesn't publish at all and Factory:ToTest publishes at maximum once a day -
 the publisher penalty is a nop for Factory. This is what I'm waiting for -
 literally all day long: https://build.suse.de/project/show/SUSE:SLE-15:GA:TEST

**Comment by mlschroe** [comment]
You're complaining about publishing in IBS, right? Rudi has tweaked the penalty for some time now by deleting the "* 5" part. I think we should also do this for OBS (or make this a config option).

I'm pretty much against completely removing it.

I'm also not sure what you're complaining about - it's not our fault that publishing SLE-15 without any penalty takes over an hour.

**Comment by coolo** [comment]
It's not about the hour it takes - it's about planning the release process. It takes an hour if it works on first try, it takes 6 if it needs 2 tries to publish - and sleeps 5 of them.

**Comment by hennevogel** [comment]
@coolo maybe you have a proposal how to do it differently while making sure "not to block all other publishing, including maintenance updates just for factory"

**Comment by coolo** [comment]
IMO the easiest tweak is to reduce the wait times seen every time the publisher waits for events.

**Comment by coolo** [comment]
So if the publisher is busy, he keeps waiting 5 hours for next factory publishing - if factory is the only project, there is no point waiting. No matter how long

**Comment by adrianschroeter** [comment]
On Mittwoch, 25. Oktober 2017, 14:00:21 CEST wrote Stephan Kulow:
> So if the publisher is busy, he keeps waiting 5 hours for next factory publishing - if factory is the only project, there is no point waiting. No matter how long

if it is the only project on this backend at all, you are right.

if there are more, even when they are not publishing right now, there is still a point,
since you want to give them a bit higher chance before blocking them 
again for hours.

In the end this is just a an emergency handler for overloaded infrastructure
and the problem is most likely somewhere else.

It turned out that the problem in your case seems to be the non atomic
release of products btw ...

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany
