### ISSUE TITLE
[production][package#remove_file] <status code="403">
  <summary>package '_product:openSUSE-dvd5-dvd-i586' is read-only if a '_prod...

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#3777]
package#remove_file threw this 0 times
<pre>
&lt;status code=&quot;403&quot;&gt;
  &lt;summary&gt;package &#39;_product:openSUSE-dvd5-dvd-i586&#39; is read-only if a &#39;_product&#39; package exists&lt;/summary&gt;
  &lt;details&gt;403 package &#39;_product:openSUSE-dvd5-dvd-i586&#39; is read-only if a &#39;_product&#39; package exists&lt;/details&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/package/remove_file/home:aplanas:branches:openSUSE:Factory/_product:openSUSE-dvd5-dvd-i586?filename=openSUSE-dvd5-dvd-i586.kiwi](https://build.opensuse.org/package/remove_file/home:aplanas:branches:openSUSE:Factory/_product:openSUSE-dvd5-dvd-i586?filename=openSUSE-dvd5-dvd-i586.kiwi)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59b003954684900006e2c344)

**Comment by bgeuken** [comment]
Apparently we show the 'remove file' link inside of _product:* package containers. Clicking this button to remove the file then fails with a 500.

To reproduce it create a _product file, go into one of the automatically created _product:* packages and try to remove a file there.
