### ISSUE TITLE
[production][patchinfo#save] undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#3778]
patchinfo#save threw this 0 times
<pre>
undefined method `each&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/patchinfo/save](https://build.opensuse.org/patchinfo/save)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59b107fb82f3bf0006edd48d)

**Comment by hennevogel** [comment]
does not happen anymore...
