### ISSUE TITLE
[production][request#index] undefined method `each' for "new,declined":String

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#3779]
request#index threw this 1 times
<pre>
undefined method `each&#39; for &quot;new,declined&quot;:String
</pre>
[https://build.opensuse.org/request?view=collection&amp;format=xml&amp;user=cbruckmayer&amp;review_states=new%2Cdeclined](https://build.opensuse.org/request?view=collection&amp;format=xml&amp;user=cbruckmayer&amp;review_states=new%2Cdeclined)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59b11d4682f3bf0006edd491)

**Comment by ChrisBr** [comment]
This was used wrong by me, it is reviewstates and not review_states. I'm currently working anyway on this!
