### ISSUE TITLE
[feature request] Please enable the multilib repo for Archlinux

### ISSUE THREAD

**Issue by anish** [openSUSE/open-build-service#378]
Some packages like wine need 32bit as well as 64 bit binaries built on a 64 bit machine. This can't be done in Arch without using the multilib enabled versions of gcc that are not available in core/extra but are only available in [multilib], effectively preventing the use of OBS for such packages

**Comment by maz-1** [comment]
I have created a multilib repo with packages grabbed from Archlinux community repo.
https://build.opensuse.org/project/show/home:mazdlc:multilib
I have successfully built wine with this repo.

**Comment by vpereira** [comment]
looks like this isn't valid anymore. if you feel that there is any missing action here, please re-open it!

thank you!

**Comment by a1batross** [comment]
Re-opening, as I can't build app using SDL2, FreeType and fontconfig. 
Just shows "unresolvable" status with "nothing provides lib32-sdl2, lib32-fontconfig, lib32-freetype2"

**Comment by vpereira** [comment]
hi @a1batross  sure we can, however it sounds like it's a configuration issue and not a feature request that have to implemented in code.. would you mind to ask it in our mailing list or irc channel?

**Comment by a1batross** [comment]
Yeah, thanks, I will ask later.
