### ISSUE TITLE
/request/show has wrong URL targets for source file hyperlinks

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#3787]
https://build.opensuse.org/request/show/522383 shows that the source project of the request is `devel:languages:python/python-rply`. However, when attempting to click the `Added python-rply.spec` link, it want to load a different source project, `https://build.opensuse.org/package/view_file/home:TheBlackCat:branches:devel:languages:python/python-rply/python-rply.spec?rev=2`. This seems wrong.

**Comment by adrianschroeter** [comment]
something for next spring

**Comment by coolo** [comment]
you are too honest :)

**Comment by eduardoj** [comment]
Yesterday the link to the changes of `devel:languages:python/python-rply` in https://build.opensuse.org/request/show/522383 redirected to `https://build.opensuse.org/package/view_file/home:TheBlackCat:branches:devel:languages:python/python-rply/python-rply.spec?rev=2`. But not today. Today it seems that it is fixed.

Do we have some other example of this failure?

**Comment by jengelh** [comment]
appeared again on https://build.opensuse.org/request/show/530395

**Comment by ChrisBr** [comment]
After debugging with @mlschroe it turned out that this is a caching bug in the backend. Assigning to the backend team...

**Comment by DavidKang** [comment]
@mlschroe, have we some news about this issue?

**Comment by mlschroe** [comment]
This is fixed since a while.
