### ISSUE TITLE
Diff sometimes doesn't work correctly

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3790]
Issue description
====================
I think the diff of files is sometimes not correct.

See:
- https://build.opensuse.org/request/show/523073 [see: changes file (line 17 and 23) and spec file (line 9)]

There are lines marked as changed but they didn't. I also have seen this in another request but didn't find it anymore.

In case the files are dropped after accepting the request, have a look at the attached screenshot.
![screenshot at 2017-09-11 13-56-34](https://user-images.githubusercontent.com/8287131/30273401-2231bcc6-96f9-11e7-92ff-f71397b126c2.png)

Expected result
============
Diff works correctly

How to Reproduce
===============
Not sure when this occurs.

**Comment by eduardoj** [comment]
> Not sure when this occurs.

This happens when the lines differs only by spaces. Not sure if we should close the issue, or maybe make it more clear when the lines differ only by spaces.

**Comment by mschnitzer** [comment]
OK I agree. Since I have seen this two times today from different people, I thought this is an error in the backend but I verified it and there is indeed a difference.

So => no issue
