### ISSUE TITLE
[production][project#show] <status code="400">
  <summary>unknown request: GET:/build/Maemo:Mer:0.15:HW:Freerunner/_result</...

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#3791]
project#show threw this 4 times
<pre>
&lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;unknown request: GET:/build/Maemo:Mer:0.15:HW:Freerunner/_result&lt;/summary&gt;
  &lt;details&gt;400 unknown request: GET:/build/Maemo:Mer:0.15:HW:Freerunner/_result&lt;/details&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/project/show/Maemo:Mer:0.15:HW:Freerunner](https://build.opensuse.org/project/show/Maemo:Mer:0.15:HW:Freerunner)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59b67a195dea6a0006dd8034)

**Comment by hennevogel** [comment]
This is fixed in 26a5dd50b75dae94df07e88b97b93c484323f554
