### ISSUE TITLE
[webui] - job history source access error for source service based packages

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#3800]
Issue/Feature description
====================

When you call the new function in the jobs history to access the source with the provided link there, then you get an error from the backend. Concrete example from b.o.o below with obs-service package using a source service.

Expected result
============

For source services, this should work as for normal packages. It seems to work for normal non source service based packages.

How to Reproduce
===============

1. E.g. go to job history for "OBS:Server:Unstable" with pkg "obs-server", link:
    https://build.opensuse.org/packages/obs-server/job_history/OBS:Server:Unstable/openSUSE_42.3/x86_64
2. click on the field "Source Change"
3. You get an error linke this:
`Error getting diff: OBS:Server:Unstable/obs-server/19d77dd3df94a7a283864428d47b63e8: not in repository. Either not existing or misconfigured server setting for '$nosharedtrees' setting in BSConfig.pm
`

**Comment by mmohring** [comment]
I have a package which had no source services in the past and then changed to source service. Then the old entries work, but (all?) changes when using a source service in the history cause this similiar error message.

**Comment by ChrisBr** [comment]
Thanks for reporting, we already recognized it and disabled it for now on build.o.o
https://github.com/openSUSE/open-build-service/pull/3803
@evanrolfe is working on a fix asap.

**Comment by mmohring** [comment]
@evanrolfe I was guessing you would deactivate it in b.o.o. I have seen the comment in the new patch there was mistakenly not been used srcmd5. I was too lazy to check what is called with osc when you diff to the last version from the history :)
