### ISSUE TITLE
Kiwi image editor: default package group requires patternType="onlyRequired"

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#3828]
Issue/Feature description
====================
I imported an image with
```
<packages type="image">
    <package name="aaa_base-extras"/>
</packages>
```
On the kiwi image show page there are no packages listed. The problem is that the default package group requires to look like ``` <packages type="image" patternType="onlyRequired">```. However, according to kiwi documentation it defaults to onlyRequired if there is no pattern specified (https://doc.opensuse.org/projects/kiwi/doc/#sec.descriptions.using-patterns). So in my opinion we should also include these packages. Also we should consider to include packages if the type is image without checking the pattern type (maybe include the pattern in the package information?).

Expected result
============
Packages of a package group type image without a pattern / different pattern are included in the package#show.

**Comment by DavidKang** [comment]
resolved in PR #3882
