### ISSUE TITLE
Kiwi image editor: Adding the same repository is possible

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#3829]
Issue/Feature description
====================
Adding the same repository several times is possible. There should be a validation that it is only possible to add the same repository once to the image.

When starting a build, kiwi will fail with
```
Specified repo alias 'openSUSE_Leap_42\.2\@home\:cbruckmayer\:oSC17' not unique across active repositoriesSep-14 10:06:23 <3> : KIWI exited with error(s)
```

Expected result
============
You get an error message that this repository already exists.

How to Reproduce
===============
1. Go to a image
2. Add a repository (e.g. obs://home:cbruckmayer:oSC17/standard)
3. Add the same repository from step 2 again
4. Check the resulted kiwi file

**Comment by mdeniz** [comment]
Kiwi documentation doesn't say that the duplication of the alias is a problem... see https://doc.opensuse.org/projects/kiwi/doc/#sec.description.repository

@adrianschroeter / @mlschroe can you say if this is something coming from the backend or the kiwi itself?

But, anyway we should fix it with a validation.

**Comment by adrianschroeter** [comment]
well, you would need to ask kiwi developers, but it is IMHO quite obvious that it is a problem, because zypp needs a uniq identifier.

**Comment by mdeniz** [comment]
The problem is that the documentation is incomplete in this regard and for sure the issue is that obviously we have to ensure the uniqueness of the alias...
