### ISSUE TITLE
Kiwi image editor: Repository wizards uses wrong type

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#3830]
Issue/Feature description
====================
Adding repositories with the repository wizard ("Basic Mode") will add repositories with type ``apt-deb``. It should be ``rpm-md`` otherwise kiwi will fail building.

Expected result
============
Adding repositories with wizard will use the correct type (``rpm-md``). Also the expert mode should default to ``rpm-md`` (I'm unsure if it is even possible to use any other type except ``rpm-md``.

**Comment by ChrisBr** [comment]
```
vmx//var/cache/kiwi/zypper/repos/openSUSE_Leap_42\.2\@home\:cbruckmayer\:oSC17.repo]
[   68s] Sep-14 10:24:50 <1> : Adding bootstrap zypper service: openSUSE_Leap_42\.2\@home\:cbruckmayer\:oSC17
[   68s] Sep-14 10:24:50 <1> : EXEC [/usr/bin/zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /usr/src/packages/KIWIROOT-vmx//var/cache/kiwi/zypper/repos --solv-cache-dir /usr/src/packages/KIWIROOT-vmx//var/cache/kiwi/zypper/solv --cache-dir /usr/src/packages/KIWIROOT-vmx//var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.2278 --no-gpg-checks --root "/usr/src/packages/KIWIROOT-vmx" addrepo -f --type apt-deb "file:///usr/src/packages/SOURCES/repos/home:cbruckmayer:oSC17/openSUSE_Leap_42.2" openSUSE_Leap_42\.2\@home\:cbruckmayer\:oSC17 2>&1]
[   68s] Sep-14 10:24:50 <3> : zypper: Specified type is not a valid repository type:
[   68s] [|] Unknown repository type 'apt-deb'
```

After discussion with @mdeniz he said that the type doesn't matter as it will get replaced by the backend anyway to ``rpm-md``. This is not true see the above error message from kiwi.

https://build.opensuse.org/package/live_build_log/home:cbruckmayer:oSC17/appliance/images/x86_64

**Comment by mdeniz** [comment]
Wasn't me who said that... @adrianschroeter was who said that to me in a private conversation 🤔 

@mlschroe / @adrianschroeter Can you ensure us what is the right value for source paths starting with obs://

Thanks!

**Comment by adrianschroeter** [comment]
the replacement happens only for obsrepositories:/ IIRC.

We need to use the right one other wise (rpm-md for rpms and apt for debian).

We can ignore the other types as they are not used by the build script.

**Comment by adrianschroeter** [comment]
btw, we don't replace it but overwrite it via the kiwi parameters. there should be also a --add-repotype= in the command line. Can you check if the right one is used?

**Comment by adrianschroeter** [comment]
we can change the code to use rpm-md always, since we also prepared it with createrepo before.

On the other hand, using apt with rpm won't work outside of OBS. so we should not have a wrong default in any case ....
