### ISSUE TITLE
Duplicated results returned by "osc sm"

### ISSUE THREAD

**Issue by lchiquitto** [openSUSE/open-build-service#3836]
Issue/Feature description
====================

When two or more projects link to the same base project, `osc sm $package` can return duplicated results. Example from our internal Build Service instance:

```
$ iosc sm apache2
(...)
SUSE:SLE-12-SP1:Update/apache2
SUSE:SLE-12-SP2:Update/apache2 <==
SUSE:SLE-12-SP2:Update/apache2 <==
```

According to @adrianschroeter, "The problem here is that we have two starting points where one is including 
also the content of the other one." and the solution would be to implement filtering on the API side.

While the issue as reported here might look cosmetic only, a more serious side effect is that "osc mbranch" will fail to setup the source project's metadata when duplicated projects are returned. It attempts to branch the same package again, fails, and never gets to the point of configuring build settings and repositories in the project's metadata.

Expected result
============

No duplicated results.

**Comment by adrianschroeter** [comment]
well, it was one possible solution ;)

nevertheless: https://github.com/openSUSE/open-build-service/issues/3836

applied on production.

**Comment by lchiquitto** [comment]
@adrianschroeter You rock. Many thanks.

**Comment by adrianschroeter** [comment]
got merged
