### ISSUE TITLE
Unresolvable CentOS_7 build on build.opensuse.org

### ISSUE THREAD

**Issue by tumic0** [openSUSE/open-build-service#3839]
GPXSee (https://build.opensuse.org/package/show/home:tumic:GPXSee/gpxsee) CentOS_7 builds are since a few days unresolvable because of:
`have choice for font(:lang=en) needed by fontconfig: abattis-cantarell-fonts bitmap-console-fonts ...`
The spec file has not changed.

P.S.: Maybe this is not the right place where to report this issue, but there is no other bug reporting link on build.opensuse.org than the OBS one...

**Comment by mmohring** [comment]
Hi, I have a similar issue here: https://build.opensuse.org/project/monitor/home:MartinMohring:KIWI-NG:image, for the CentOS 7 target, dito. Did the resolver get changed on b.o.o ?

**Comment by mmohring** [comment]
I think this is because CentOS 7 got updated to CentOS 7.4. I have compared the two locally, they show exactly the behavior described.

**Comment by bgeuken** [comment]
You can 'fix' this by adding a ``` Prefer: abattis-cantarell-fonts ``` or ``` Prefer: bitmap-console-fonts ``` to tell OBS which package it should use when in doubt.

Like @mmohring said, this might have been caused by a change of the config of one of the projects you build against.

Essentially within your project you have your local project conf and on top of them all the project confs of the projects you build against. 

Eg. when you check the meta file you will see that for Leap 42.3, you build against home:MartinMohring:KIWI-NG:Appliance and openSUSE:Leap:42.3.
That means that the project conf of those two and the local one are used (for dependency resolution, etc.).

```
  <repository name="openSUSE_Leap_42.3">
    <path project="home:MartinMohring:KIWI-NG:Appliance" repository="openSUSE_Leap_42.3"/>
    <path project="openSUSE:Leap:42.3" repository="standard"/>
    <arch>x86_64</arch>
  </repository>
```

**Comment by tumic0** [comment]
Where can I set those values? I'm afraid, that it only can be made by the OpenSUSE build service admins. And even if not, it makes no sense to do so per project, as everyone building GUI applications for CentOS is IMHO facing the same issue...

**Comment by cryol** [comment]
@tumic0 
At me a similar problem, has appeared in day of exit CentOS 7.4.
Occurs if fonts are used in the package.

It helped to solve:
On https://build.opensuse.org/project/prjconf/your_project_name (Project Configuration Page) add
```
Prefer: font(:lang=en)
Prefer: dejavu-sans-fonts
```
Try it.

**Comment by bgeuken** [comment]
> tumic0 commented
> Where can I set those values?

In the project conf, like [here](https://build.opensuse.org/project/prjconf/home:tumic:GPXSee).

> I'm afraid, that it only can be made by the OpenSUSE build service admins

You are right, in some cases it makes sense to fix such things in the upstream project. In such a case you can find the maintainers of a project via the [users tab](https://build.opensuse.org/project/users/CentOS:CentOS-7).

As it seems this is Adrian. So we can even ping him here

@adrianschroeter As it seems there are some Prefer statements needed for the [Centos 7.4](https://build.opensuse.org/project/show/CentOS:CentOS-7) project (see intial issue description). Could you have a look at this?

**Comment by tumic0** [comment]
Tanks @cryol, it works. However I still think that this should be fixed globaly...

**Comment by adrianschroeter** [comment]
done
