### ISSUE TITLE
https redirects to http on missing / insertion code

### ISSUE THREAD

**Issue by msmeissn** [openSUSE/open-build-service#3847]
Issue/Feature description
====================
getting a https URL
https://download.opensuse.org/repositories/KDE:Extra/openSUSE_Leap_42.3/KDE:Extra.repo
redirects to http
http://download.opensuse.org/repositories/KDE:/Extra/openSUSE_Leap_42.3/KDE:Extra.repo

Expected result
============
It should redirect to the fixed https URL not the fixed http URL:
 
https://download.opensuse.org/repositories/KDE:/Extra/openSUSE_Leap_42.3/KDE:Extra.repo

How to Reproduce
===============
1. curl https://download.opensuse.org/repositories/KDE:Extra/openSUSE_Leap_42.3/KDE:Extra.repo
2. redirects to http://download.opensuse.org/repositories/KDE:/Extra/openSUSE_Leap_42.3/KDE:Extra.repo

Further information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)

**Comment by hennevogel** [comment]
Sorry, this is the wrong place. download.opensuse.org is something opensuse specific. please report your problem to admin@opensuse.org
