### ISSUE TITLE
create .repo files with "https" URLs

### ISSUE THREAD

**Issue by msmeissn** [openSUSE/open-build-service#3848]
Issue/Feature description
====================
The .repo files served by the OBS currently have "http" URLs inside, but should have "https" these days.

$ curl https://download.opensuse.org/repositories/KDE:/Extra/openSUSE_Leap_42.3/KDE:Extra.repo
[KDE_Extra]
name=Additional packages maintained by the KDE team (openSUSE_Leap_42.3)
type=rpm-md
baseurl=http://download.opensuse.org/repositories/KDE:/Extra/openSUSE_Leap_42.3/
gpgcheck=1
gpgkey=http://download.opensuse.org/repositories/KDE:/Extra/openSUSE_Leap_42.3/repodata/repomd.xml.key
enabled=1

Expected result
============
Should have https URLs.

How to Reproduce
===============
1. Get a generated .repo file over https
2. get back https  in the .repo file

**Comment by adrianschroeter** [comment]
configuration changed.

**Comment by msmeissn** [comment]
I dont see it changed externally?

**Comment by msmeissn** [comment]
either not deployed or not working.

**Comment by kiamlaluno** [comment]
I am getting an error message from zypper, when I use the https:// URL of the repository. I need to add repositories using http://.

**Comment by msmeissn** [comment]
what error message?

but yes, zypper addrepo https:/.... will currently have troubles if you do this

**Comment by kiamlaluno** [comment]
Running `sudo zypper addrepo https://download.opensuse.org/repositories/devel:languages:php/openSUSE_Leap_42.3/devel:languages:php.repo`, for example, I get the following error message.

> Download (curl) error for 'https://download.opensuse.org/repositories/devel:languages:php/openSUSE_Leap_42.3/devel:languages:php.repo': Error code: Bad URL Error message: Protocol http not supported or disabled in libcurl

To be sure it was enabled, I ran `curl https://www.drupal.org`, which didn't return me any error message.

Also, the output of `zypper info libssl43` and `zypper info libcrypto41` are respectively the following ones.

```
Information for package libssl43:
---------------------------------
Repository     : oss
Name           : libssl43
Version        : 2.5.3-6.1
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 360.0 KiB
Installed      : Yes
Status         : up-to-date
Source package : libressl-2.5.3-6.1.src
Summary        : An SSL/TLS protocol implementation
Description    :
    LibreSSL is an open-source implementation of the Secure Sockets Layer
    (SSL) and Transport Layer Security (TLS) protocols. It derives from
    OpenSSL and intends to provide a more secure implementation.
```



```
Information for package libcrypto41:
------------------------------------
Repository     : oss
Name           : libcrypto41
Version        : 2.5.3-6.1
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 2.0 MiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : libressl-2.5.3-6.1.src
Summary        : An SSL/TLS protocol implementation
Description    :
    The "crypto" library implements a wide range of cryptographic
    algorithms used in various Internet standards. The services provided
    by this library are used by the LibreSSL implementations of SSL, TLS
    and S/MIME, and they have also been used to implement SSH, OpenPGP,
    and other cryptographic standards.
```

**Comment by pjessen** [comment]
See also https://progress.opensuse.org/issues/28343
as well as https://progress.opensuse.org/news/40
As for using https links - the current mirror structure does not support https, isn't that going to be a problem?  I can see mirrorbrain has multiple sources for a .repo file, but apparently it's not being used.

**Comment by msmeissn** [comment]
mirrorbrain needs https support. some of the mirrors support https, but mirrorbrain needs to handle it.

not sure about repo files.

**Comment by Mailaender** [comment]
> As for using https links - the current mirror structure does not support https, isn't that going to be a problem?

I am currently running into trouble as following the instructions from https://software.opensuse.org//download.html?project=devel%3Alanguages%3AR%3Areleased&package=rstudio do not work at all:

```
sudo zypper addrepo https://download.opensuse.org/repositories/devel:languages:R:released/openSUSE_Tumbleweed/devel:languages:R:released.repo
Fehler beim Download (curl) für 'https://download.opensuse.org/repositories/devel:languages:R:released/openSUSE_Tumbleweed/devel:languages:R:released.repo':
Fehlercode: ' Bad URL'
Fehlermeldung: 'Protocol "http" not supported or disabled in libcurl'
```

Replacing the `https` with `http` is a workaround that works for me. I assume curl doesn't like the redirects. This should be fixed as it is very irritating.

**Comment by TomyLobo** [comment]
@adrianschroeter it seems your configuration change has since either been reverted or it was never effective.
For example, this file contains only http links:
https://download.opensuse.org/repositories/devel:/tools:/scm/SLE_12_SP3/devel:tools:scm.repo

The packages can stay on HTTP, since they're authenticated using the GPG key.
However, I would suggest for the GPG key to be transferred via HTTPS in order to provide an additional layer of authentication.

As it is now, anyone who can execute a man-in-the-middle attack on your connection to OBS can spoof the delivered key and the delivered packages, and thus basically run arbitrary code on a computer.
All that is required here is access to any part of the connection between your computer and OBS or a successful DNS spoofing attack.

If the user then runs "zypper install" and autorefresh redownloads the key and repo metadata, they will be prompted to accept a new key.
Now if I see that message on a machine where I'm sure I already confirmed it, I will get suspicious and investigate. However, if this is indeed the first time I add the repo or if I was a less experienced user, I might not connect the dots.
Non-interactive software, like [Chef](https://github.com/chef/chef/issues/6374) may even, because they cannot ask a user for confirmation, automatically import the key using the `--gpg-auto-import-keys` flag.

**Comment by tacerus** [comment]
> I would suggest for the GPG key to be transferred via HTTPS in order to provide an additional layer of authentication.

This would definitely be of advantage.

> Non-interactive software, like https://github.com/chef/chef/issues/6374 may even, because they cannot ask a user for confirmation, automatically import the key using the --gpg-auto-import-keys flag.

It's unfortunately extremely common practice. I sometimes prefer to download the GPG key over HTTPS using a `curl` + `rpm --import` script before invoking `zypper`, but it's not convenient - especially now with minimal containers not shipping with `curl` or not having a connection to arbitrary internet hosts.

>  Can you put the keys on (non-mirrored if need be) https?

Would appreciate an update on this as well!
