### ISSUE TITLE
Retry LDAP connections when closed

### ISSUE THREAD

**Issue by evanrolfe** [openSUSE/open-build-service#3861]
Issue/Feature description
====================
When the LDAP  server closes the connection to the rails app, `UserLdapStrategy` does not know about this. So when UserLdapStrategy tries to connect with a closed connection, instead of re connecting it just returns "Unauthorized". This has been reported in the mailing list here:

https://lists.opensuse.org/opensuse-buildservice/2017-09/msg00074.html

It seems that it is this commit that removes the code that retries the connection so we should probably add this code back in. (This also needs to be applied to 2.8).

Master: https://github.com/openSUSE/open-build-service/commit/db44312746793b8dc46651af48de231f827d0cc6

2.8: https://github.com/openSUSE/open-build-service/commit/44df33c09e52f93011ca0aafc8e314b58790eb85

Expected result
============
If the ldap connection is closed then `UserLdapStrategy` so re connect to LDAP.

How to Reproduce
===============
1. Follow this [wiki guide](https://github.com/openSUSE/open-build-service/wiki/Installing-a-local-LDAP-server) to setup a local ldap server with OBS
2. In the rails console, authenticate with the LDAP user you created (and leave the console open):
```
UserLdapStrategy.find_with_ldap('YOUR_LDAP_USER', 'YOUR_LDAP_PASSWORD'')
```
3. In another console, restart the LDAP server to close the existing connection to `UserLdapStrategy`:
```
sudo systemctl restart slapd
```
4. Now back in console from step 2 re-run the `find_with_ldap` method:
```
irb(main):002:0> UserLdapStrategy.find_with_ldap('Admin', 'opensuse')
Looking for Admin using ldap
Search for dc=local (sn=Admin)
Search failed:  error -1: Can't contact LDAP server
```

**Comment by bgeuken** [comment]
Fixed witg #3873
