### ISSUE TITLE
[ci] problem with running WebUI testsuite in the obs-server package

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#3865]
Issue/Feature description
====================
The WebUI testsuite fails since a couple of days in multiple tests on b.o.o and also when run locally.

Expected result
============
WebUI testsuite should not fail.

How to Reproduce
===============
Automatically run with every commit. Look at b.o.o OBS:Server:Unstable / obs-server logfile.

Further information
===============
Seems to happen since around commit 9ce8a9e3d77ee5b60f483e448f2faba45575613c .

**Comment by mmohring** [comment]
This error seem to have been independent of the code commits. As @bgeuken points out in #3895 it had an external code piece as reason, the crawler-user-agents.json. As a consequence it is now versioned inside OBS code. So problem fixed with the merge of #3895.

**Comment by mmohring** [comment]
@bgeuken you should also merge this into 2.8 branch, the same happens there. Please take a look at https://build.opensuse.org/package/view_file/OBS:Server:2.8/obs-server/_service , any new fetch will trigger it there too.

**Comment by bgeuken** [comment]
Good point:+1: We'll backport this with #3899
