### ISSUE TITLE
Implement tests if obsapidelayed is started correctly in openqa test cases

### ISSUE THREAD

**Issue by M0ses** [openSUSE/open-build-service#3879]
The problem in obsapidelayed startup (https://github.com/openSUSE/open-build-service/pull/3875) was not detected by openqa test.

A test case which checks if obsapidelayed started correctly (e.g. systemctl status obsapidelayed) would have been useful.

**Comment by hennevogel** [comment]
openQA test are maintainer here: https://github.com/os-autoinst/os-autoinst-distri-obs

I've added your issue there...
