### ISSUE TITLE
request: 446602 does not include <history> element for <priority> change

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/open-build-service#3897]
Issue/Feature description
====================

Somehow a request `priority` was changed, but not `history` record was recorded.

Expected result
============

A `history` record would be present.

How to Reproduce
===============

`osc api '/request/446602?withfullhistory=1'`

**Comment by bgeuken** [comment]
There are some [raiseprioirty](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/bs_request.rb#L448) calls that set the request priority, but don't create a history element.

btw. they set themto the lowest of all associated bs_request actions.
@adrianschroeter Is that the correct behaviour? I would think that it should be the highest instead.

**Comment by bgeuken** [comment]
We are going to [track](https://github.com/openSUSE/open-build-service/pull/3994/files#diff-d476b59ba5326de67e0c155e8e226d6fR1192) automatic priority changes. That probably covers the prio change you encountered.

@adrianschroeter JFYI

**Comment by bgeuken** [comment]
This should be fixed with #3994. At least it was the only possible cause for this issue that I found. If this still appears, please let us know.

**Comment by jberry-suse** [comment]
@bgeuken To be clear, this only works going forward and does not apply to historical requests?

**Comment by bgeuken** [comment]
@jberry-suse Right, all requests prior to the fix won't have that history element.
