### ISSUE TITLE
[production][] incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#3905]
threw this 5 times
<pre>
incompatible character encodings: UTF-8 and ASCII-8BIT
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59c38189884a5900062a967c)

**Comment by bgeuken** [comment]
This is thrown by app/views/event_mailer/request_create.text.erb:8

**Comment by evanrolfe** [comment]
Closing this as we already had an issue for this error: https://github.com/openSUSE/open-build-service/issues/3415
