### ISSUE TITLE
WebUI-Comments aren't properly escaped

### ISSUE THREAD

**Issue by m4z** [openSUSE/open-build-service#3912]
Greetings,

when commenting on project (and probably package) pages in the OBS WebUI (I posted [here](https://build.opensuse.org/project/show/systemsmanagement:saltstack)), it seems special characters aren't properly encoded. When I tried to comment something containing:
```foo <bar>```

my whole comment was truncated to:
```foo ``` (unsure about whether the last space was actually in there).

When I manually edited my post to contain:
```foo &lt;bar&gt;```
it worked fine, but I don't enjoy escaping manually very much. (c;

**Comment by mschnitzer** [comment]
Thanks for reporting a bug. We'll take care of this.

**Comment by m4z** [comment]
Thanks!

(From the replies I received to my comments, it seems the mail notifications are not truncated.)

**Comment by ChrisBr** [comment]
This is intended behavior to avoid XSS. If you want to add code, please wrap it into an ```<pre>```

**Comment by m4z** [comment]
1. I wouldn't call that "code", I was posting a snippet of zypper output containing the standard ```name <mail address>``` format.
2. Why truncate instead of removing potentially dangerous characters?
3. What you describe doesn't seem to work either, as tested [here](https://build.opensuse.org/project/show/home:m4z), I posted:
```
This is a test:
<pre>foo <bar></pre>
Does it work?
```
…and the resulting page source looks like this:
```
<p>This is a test:
<pre>foo </pre>
Does it work?</p>
```

**Comment by hennevogel** [comment]
@m4z it's not truncated. it's simply not rendered. `<p>` is rendered as we are sure what it does, `<bar>` could be anything including malicious code in a component, hence we don't allow it...

**Comment by m4z** [comment]
Hmm, ok, that's kind of non-intuitive (and I didn't get that from the comments above). 

Also, note the ```text/html``` part of the mail (which is shown by default in gmail) is… scrubbed:
```
----==_mimepart_59d4f166dc189_1aaa444f8030284
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

Visit https://build.opensuse.org/project/show/home:m4z

Hendrik Vogelsang wrote in project home:m4z:

<bar> isn't truncated, <bar> isn't rendered

-- 
Configure notifications at https://build.opensuse.org/user/notifications
openSUSE Build Service (https://build.opensuse.org/)

----==_mimepart_59d4f166dc189_1aaa444f8030284
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>
Visit <a href="https://build.opensuse.org/project/show/home:m4z">https://build.opensuse.org/project/show/home:m4z</a>
</p>
<p>
Hendrik Vogelsang
wrote in project home:m4z:
</p>
<div></div>

<br>
--
<br>
Configure notifications at <a href="https://build.opensuse.org/user/notifications">https://build.opensuse.org/user/notifications</a>
<br>
openSUSE Build Service
(<a href="https://build.opensuse.org/">https://build.opensuse.org/</a>)
<br>

----==_mimepart_59d4f166dc189_1aaa444f8030284--
```

**Comment by jengelh** [comment]
There are more bugs of this kind :-/
Writing sed substitutables like like `@PARENT_TAG@`, when made _inside triple-backtick_ blocks, are also not escaped, leading to `@PARENT_TAG(failedurlhere)@`.
