### ISSUE TITLE
No operation when press [Save] button after modifying content in [Meta] tab

### ISSUE THREAD

**Issue by leemgs** [openSUSE/open-build-service#3916]
Issue/Feature description
====================

It's strange. It seems that OBS does not execute appropriate operation
after pressing "Save"button in "Meta" menu. I have tried to update the contents of "Meta" tab as follwoing:

How to Reproduce
===============

1) https://website > Open Build Service > Projects > Fedora:custom_platform > Meta
2) Modify the existing contents.
3) Press "Save".

However, I have got error with "Save" button with read color becuase the save operation was failed.
Anyone that experienced similar issue? 

```
$ ls -al /srv/obs/projects/
drwxr-xr-x  2 obsrun obsrun  4096  Sep 28 17:34 Fedora:custom_platform.pkg
-rw-r--r--  1 obsrun obsrun   162  Sep 28 17:34 Tizen:custom_platform.xml
```

Further information
===============

```
$ ps -ef | grep Passenger
obsrun   17303     1  0 18:47 ?        00:00:04 Passenger RubyApp: /srv/www/obs/api (development)
obsrun   21248     1  0 19:06 ?        00:00:00 Passenger RubyApp: /srv/www/obs/api
```

**Comment by ChrisBr** [comment]
This happens when the meta is invalid. However, it seems to be a bug that there is no flash reporting the error.

**Comment by ChrisBr** [comment]
Actually I just tried to save an invalid meta and I got a flash message reporting what is wrong!
![screenshot from 2017-09-28 15-16-22](https://user-images.githubusercontent.com/3799140/30968605-25e9fe2c-a460-11e7-899e-1cdafd29d96f.png)

Please provide some more information :smile:

**Comment by leemgs** [comment]
I could not see the flash message. Could you tell me on what I have to check to enable the flash message function? Any hint will be helpful to me.

**Comment by ChrisBr** [comment]
@leemgs the flash messages are enabled by default so no need to enable it. Mabye something with your browser?

**Comment by ChrisBr** [comment]
@leemgs ok, so one problem I could imagine is that you provide a wrong repository path. See https://github.com/openSUSE/open-build-service/issues/3989, this will raise an UnknownObject exception. Could you please provide your meta file?

**Comment by leemgs** [comment]
> Could you please provide your meta file?

@ChrisBr . Here is my meta file. 

* Meta
```
<project name="Tizen:Mobile">
  <title>Mobile profile for Base 2 experiments</title>
  <description>For test and experiments only</description>
  <person userid="Admin" role="maintainer"/>
  <build>
    <enable/>
    <disable arch="i586"/>
    <disable arch="armv7l"/>
    <enable arch="x86_64"/>
  </build>
  <publish>
    <disable arch="i586"/>
    <disable arch="armv7l"/>
  </publish>
  <debuginfo>
    <enable/>
    <disable arch="i586"/>
    <disable arch="armv7l"/>
  </debuginfo>
  <useforbuild>
    <disable arch="i586"/>
    <disable arch="armv7l"/>
  </useforbuild>
  <repository name="standard" rebuild="local">
    <path project="Tizen:Base" repository="standard"/>
    <path project="Tizen:Base2" repository="standard"/>
    <arch>x86_64</arch>
    <arch>i586</arch>
    <arch>armv7l</arch>
  </repository>
</project>
```

**Comment by ChrisBr** [comment]
Deployed to build.o.o
