### ISSUE TITLE
Kiwi image editor: Saving destroys structure of kiwi file

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#3931]
Issue/Feature description
====================
When saving in the kiwi image editor, it will destroy the ordering of the different sections in the original kiwi file (e.g. repository and package sections). This is bad as it creates a huge diff.

This happens in ``kiwi/image.rb#to_xml``

```
    ...
    doc.xpath("image/packages").remove
    xml_packages = package_groups.map(&:to_xml).join("\n")
    image.first_element_child.after(xml_packages)

    doc.xpath("image/repository").remove
    xml_repos = repositories_for_xml.map(&:to_xml).join("\n")
    image.first_element_child.after(xml_repos)

    # Reparser for pretty printing
    Nokogiri::XML(doc.to_xml, &:noblanks).to_xml
    ....
```

Expected result
============
We shouldn't remove the sections and then add it after the first child. We should just replace the section with the new section to preserve the order of the sections.

**Comment by adrianschroeter** [comment]
https://trello.com/c/WtHP0Z5m/558-avoid-unnecessary-xml-layout-changes-in-kiwi-editor

**Comment by bgeuken** [comment]
@ChrisBr That's solved by now, is it?

**Comment by ChrisBr** [comment]
Yep, fixed!
