### ISSUE TITLE
[production][bs_requests#index] undefined method `draw' for nil:NilClass

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#3937]
bs_requests#index threw this 0 times
<pre>
undefined method `draw&#39; for nil:NilClass
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59d3457cd4f2130006ae7191)

**Comment by mschnitzer** [comment]
I can absolutely not reproduce it. This error occured two times. Both packages were AppImage Templates.

Here's the link to the other exception: https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a74648d5c0a62001418663c

**Comment by hennevogel** [comment]
let's close it then...

**Comment by c-hoeger** [comment]
According to @hennevogel , we might see the same issue, see attached files.

[obs-ajax-error.mov.zip](https://github.com/openSUSE/open-build-service/files/2607601/obs-ajax-error.mov.zip)
![obs-ajax-error](https://user-images.githubusercontent.com/4416051/48897610-cbdc4080-ee4a-11e8-9bbd-bca8cd115f8d.png)
