### ISSUE TITLE
OBS can't parse URL with '?=&' symbols

### ISSUE THREAD

**Issue by paulcarroty** [openSUSE/open-build-service#3944]
Issue/Feature description
====================
Trying to get the latest Firefox release from `https://download.mozilla.org/?product=firefox-beta-latest&os=linux64&lang=en-US`. 

Expected result
============
Tarball is expected, but I got no files.

How to Reproduce
===============
1. Push 'Add file' button
2. Insert the URL
3. Error

Further information
===============
* A link to an OBS instance showing the issue
https://build.opensuse.org/package/show/home:paulcarroty/firefox-beta

**Comment by ChrisBr** [comment]
Hmm, could also be a bug in the related source service...

**Comment by adrianschroeter** [comment]
It looks like the webui is generating a wrong _service file, correct? Or do you speak about a different issue?

**Comment by paulcarroty** [comment]
@adrianschroeter @ChrisBr the OSB UI doesn't encode XML symbols correctly, for example look this [thread](https://stackoverflow.com/questions/7818928/how-to-encode-symbols-in-xml).

P.S. I fixed this issue by editing _service manually: 

```xml
<services>
  <service name="download_url">
    <param name="host">download.mozilla.org</param>
    <param name="protocol">https</param>
    <param name="path">?product=firefox-beta-latest&amp;os=linux64&amp;lang=en-US</param>
    <param name="filename">firefox-beta-latest.tar.bz2</param>
  </service>
</services>
```
