### ISSUE TITLE
Allow `osc build` to work against /public by relaxing access restrictions

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/open-build-service#3946]
Issue/Feature description
====================

As described in detail in openSUSE/osc#342 the goal is to allow for CI package builds using `osc build` to ensure nothing breaks the package builds as accomplished in openSUSE/osc-plugin-factory#1126 (instead of manual `rpm` commands). The core problem is that two API calls made during `osc build` are not available on `/public`. The reason a user cannot be used is that travisci, rightfully so, hides the secret variables (password in this case) during runs against pull requests to avoid malicious changes to extract password. Obviously a throw away account could be used, but really is not a proper solution.

Unless there are strong reasons allowing the two API calls to be accessed via `/public` would seem a clear and simple solution. If source checkouts are allowed via `/public` it seems only reasonable that one could build what one cloned.

Expected result
============

Anonymous builds via `/public` work out of box.

How to Reproduce
===============

1. `osc checkout` package via `/public`
2. run `osc service disabledrun`
3. run `osc build`

Further information
===============

See travisci logs from failure: https://travis-ci.org/openSUSE/osc-plugin-factory/jobs/271036941.

**Comment by adrianschroeter** [comment]
/public is unstable api only supposed for interconnect. Don't misuse it for more since we don't redirect to mirrors there and I may need to block users when they misuse the bandwitdh.

**Comment by adrianschroeter** [comment]
Offline build is supposed to be done via plain "build" script using the sources from src.rpm's .

**Comment by jberry-suse** [comment]
Misuse would imply the usage of `/public` is clearly defined which I have yet to come across, but nerveless so be it. As for "offline build" the use case wants to be able to perform a _local_ service run and build. The build represents a new build that OBS has not yet performed as a pre-checkin test as part of CI so running the build script from a src.rpm is not a solution. Having a proper anonymous setup seems more than reasonable. The alternative is that I create an OBS user whos password is exposed to all via CI setup and thus open to abuse. Is that preferred?

**Comment by jberry-suse** [comment]
This is on the level of password protecting a make file. I can anonymously access the source used to build a package, but running the build functionality arbitrarily requires credentials???

If `/public` is not actually "public" as the name would imply it would make more sense to call it `/interconnect` and perhaps requiring a API key or credentials. But really, why is the "open" build service hosting open source package sources requiring sign up to access data? That's like the controversial companies that requiring sign-up before downloading a driver or sdk only here the source itself is public and even 90% of the way to being able to build anonymously.

**Comment by jberry-suse** [comment]
We are talking about providing anonymous access to two API calls. This should require at most two lines of code change unless something is amiss.

**Comment by jberry-suse** [comment]
Discovered that #399 is a similar request and had someone else looking for the same thing in openSUSE/osc#342.

Not sure why OBS team finds the idea of running `osc build` locally on an open source package without having to register on OBS such a wrong idea. For CI it is critical as only other option is throw away accounts which isn't particularly nice for OBS or us. Literally just a API permission issue.

**Comment by hennevogel** [comment]
> Not sure why OBS team finds the idea of running osc build locally on an open source package without having to register on OBS such a wrong idea

We don't, we simply don't have anonymous access. Yes the interconnect might better be called `/interconnect` and yes making it possible to require auth for interconnect would be a cool feature.

But that doesn't change that we don't have the concept of anonymous access currently...

**Comment by jberry-suse** [comment]
Which, of course, is the basis for this request (ie providing anonymous access). If not objectionable then why is this issue closed?

**Comment by coolo** [comment]
#399 is the real feature request - allowing to build against /public is a workaround.

**Comment by jberry-suse** [comment]
The mentioned request would be even nicer to have, but fail to understand why one would build the more extravagant thing when rejecting the near trivial approach.
