### ISSUE TITLE
`docker-compose up` fails for frontend

### ISSUE THREAD

**Issue by evanrolfe** [openSUSE/open-build-service#3949]
Issue/Feature description
====================
When running `rake docker:build` and then `docker-compose up` on a machine with no docker images or containers the frontend container exits when i run `docker-compose up`. It gives this message:

```
frontend_1  | 09:05:02 web.1     | A server is already running. Check /obs/src/api/tmp/pids/server.pid.
frontend_1  | 09:05:02 web.1     | Exiting
```

I've checked tmp/pids/server.pid and that file does not exist afterwards.

Expected result
============
The frontend container starts the rails server.

How to Reproduce
===============
1. `rake docker:build`
2. `docker-compose up`
3. see the output from the frontend container: it exits.

**Comment by evanrolfe** [comment]
If i do `docker-compose run frontend /bin/bash -l` and try running each of the commands from the Procfile manually from bash then they run fine:
```
web: bundle exec rails server
delayed: bundle exec script/delayed_job.api.rb run
clock: bundle exec clockworkd --log-dir=log -l -c config/clock.rb run 
search: bundle exec rake ts:rebuild NODETACH=true
```

**Comment by evanrolfe** [comment]
Ok it seems to work if I have all the other containers running (backend, cache, db, worked) and then I start the frontend container specifically with: `docker-compose up frontend`. Maybe the frontend container relies on something from the backend which hasn't started yet?

**Comment by hennevogel** [comment]
Either the file is there, or not. This has nothing to do with docker. If you kill a container (by calling `docker-compose kill something` or by pressing `CTRL+c` often enough) it might leave the file behind. In that case, remove it.
