### ISSUE TITLE
API /comments/project/$project causes 500

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/open-build-service#3955]
Issue/Feature description
====================

While testing repo-checker comment truncation I was posting comments on `home:jberry` that were truncated to `65535` bytes. After doing so the `osc api '/comments/project/home:jberry'` caused a 500 error. Removing the comment resolved the issue.

The comment displayed was significantly shorter than the one posted for example one was just over `15630` bytes. It is not possible to see the pre-formatted version so this included the majority of displayed text. Regardless that is a significantly shorter than the limit.

- not sure why this would not occur during normal operation on staging projects (unless something magical relating to `home:` projects)
- one would expect the api to work when the comment can be displayed via web

Expected result
============

API not crash

How to Reproduce
===============

1. post a long comment on `$project` (limiting to `60000` instead of limit seems to cause crash as well)
2. `osc api '/comments/project/$project`

Likely causes issues on other entities that can have comments, but I have not checked.

Further information
===============

Related to #3584 and subsequent fixes after that.

**Comment by jberry-suse** [comment]
I would also expect to be able to see the full length allowed instead of a further truncated message. I understand based on implementation that the emails will be further truncated by a variable amount (meh), but at least the display should be the same. If not then the limit should be lowered to something that can actually be handled and repo-checker can be changed to use that.

**Comment by jberry-suse** [comment]
It seems that even if I limit length to `5000` the message is truncated beyond the truncation to `5000`. That certainly would not be the expected behavior. At least the `500` error is not produced.

**Comment by saraycp** [comment]
Testing with texts with 65535 bytes it seems this error is not happening anymore.
Please re-open in case you face the same problem again.
