### ISSUE TITLE
[production][comments#create] Mysql2::Error: Incorrect string value: '\xB4\x07\x00\x00#\x00...' for column 'body' at row 1: INS...

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3956]
comments#create threw this 3 times
<pre>
Mysql2::Error: Incorrect string value: &#39;\xB4\x07\x00\x00#\x00...&#39; for column &#39;body&#39; at row 1: INSERT INTO `comments` (`body`, `created_at`, `updated_at`, `user_id`, `commentable_type`, `commentable_id`) VALUES (&#39;&lt;\0\0\0!\0\0\0-\0\0\0-\0\0\0 \0\0\0R\0\0\0e\0\0\0p\0\0\0o\0\0\0C\0\0\0h\0\0\0e\0\0\0c\0\0\0k\0\0\0e\0\0\0r\0\0\0 \0\0\0s\0\0\0t\0\0\0a\0\0\0t\0\0\0e\0\0\0=\0\0\0s\0\0\0e\0\0\0e\0\0\0n\0\0\0 \0\0\0r\0\0\0e\0\0\0s\0\0\0u\0\0\0l\0\0\0t\0\0\0=\0\0\0f\0\0\0a\0\0\0i\0\0\0l\0\0\0e\0\0\0d\0\0\0 \0\0\0-\0\0\0-\0\0\0&gt;\0\0\0\n\0\0\0\n\0\0\0�\0\0#\0\0\0#\0\0\0 \0\0\0x\0\0\08\0\0\06\0\0\0_\0\0\06\0\0\04\0\0\0\n\0\0\0\n\0\0\0#\0\0\0#\0\0\0#\0\0\0 \0\0\0[\0\0\0i\0\0\0n\0\0\0s\0\0\0t\0\0\0a\0\0\0l\0\0\0l\0\0\0 \0\0\0c\0\0\0h\0\0\0e\0\0\0c\0\0\0k\0\0\0 \0\0\0&amp;\0\0\0 \0\0\0f\0\0\0i\0\0\0l\0\0\0e\0\0\0 \0\0\0c\0\0\0o\0\0\0n\0\0\0f\0\0\0l\0\0\0i\0\0\0c\0\0\0t\0\0\0s\0\0\0]\0\0\0(\0\0\0/\0\0\0p\0\0\0a\0\0\0c\0\0\0k\0\0\0a\0\0\0g\0\0\0e\0\0\0/\0\0\0v\0\0\0i\0\0\0e\0\0\0w\0\0\0_\0\0\0f\0\0\0i\0\0\0l
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59d6b154a54f39000ac78e4e)

**Comment by mschnitzer** [comment]
Related to issue #3955

**Comment by hennevogel** [comment]
Rather #4049
