### ISSUE TITLE
[production][package#branch] <status code="400">
  <summary>home:soes/jabref: project 'home:soes' does not exist</summary>
</s...

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3957]
package#branch threw this 1 times
<pre>
&lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;home:xxx/xxx: project &#39;home:xxx&#39; does not exist&lt;/summary&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/package/branch](https://build.opensuse.org/package/branch)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59d500f2a1f35a0006d6a43c)

**Comment by mschnitzer** [comment]
First it should not raise an exception and second, it should throw a 404 error and not 400...

**Comment by adrianschroeter** [comment]
The errbit is away :/

not sure about the error code, 400 might be okay when this is during branch creation. However, changing error codes is a potential api change, so please don't do this is easily.

In any case the webui should not crash, but given that the errbit is away we just may need to close this ..

**Comment by evanrolfe** [comment]
Here is the same exception from errbit:
https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a654c02cd83b60006d605e0

**Comment by evanrolfe** [comment]
Here is a trello card for this bug. These errors occur regularly and it would be quite simple to fix so I would like to get this fixed sooner rather than later.

https://trello.com/c/2Q63pS6O/1306-webuipackagecontrollerbranchpackage-handles-errors-from-backend

**Comment by hennevogel** [comment]
Okay we are going to track all `Package.branch` exceptions in #3734 now
