### ISSUE TITLE
trigger_rebuild GET fails

### ISSUE THREAD

**Issue by jayvdb** [openSUSE/open-build-service#3985]
Issue/Feature description
====================
Clicking on the Trigger rebuild link on pages like https://build.opensuse.org/package/binaries/home:jayvdb:poco/poco?repository=Fedora_Rawhide result in a POST.

If the Trigger link is opened in a new tab, a 404 message is shown.

Expected result
============
The link provided should work correctly as a GET request.

If the trigger page can only function as a POST:
* it target URL should report a nice error message explaining GET is not supported.
* the webui should hide the URL that the Trigger link will POST to.

How to Reproduce
===============
1. Open https://build.opensuse.org/package/binaries/home:jayvdb:poco/poco?repository=Fedora_Rawhide
2. Copy the URL under a "Trigger" link
3. Paste the URL to a new tab or window.

Possible related to https://github.com/openSUSE/open-build-service/issues/1560

**Comment by mschnitzer** [comment]
I'd say it's completely unrelated to the issue you mentioned. Could you please describe what you mean with `the webui should hide the URL that the Trigger link will POST to.` ?

**Comment by hennevogel** [comment]
not sure what you want to do here. link's won't always work in a new tab.
