### ISSUE TITLE
webui: job_history table sorting has strange sorting 

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#3986]
The default is sorting alphabetically md5sums, which doesn't make *any* sense - and if you sort by time the sort order is August, October, September - also alphabetically by month, which makes *little* sense.

https://build.opensuse.org/packages/curl/job_history/openSUSE:Factory:Staging:C/standard/i586

**Comment by adrianschroeter** [comment]
On Mittwoch, 11. Oktober 2017, 10:52:50 CEST wrote Stephan Kulow:
> The default is sorting alphabetically md5sums, which doesn't make *any* sense - and if you sort by time the sort order is August, October, September - also alphabetically by month, which makes *little* sense.
> 
> https://build.opensuse.org/packages/curl/job_history/openSUSE:Factory:Staging:C/standard/i586

right, it is a history, so it shouldn't be sorted at all ...

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany
