### ISSUE TITLE
service in progress is no http error

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#3996]
If you commit to a package in a Factory devel package and try to submit request it right afterwards (as CI systems like to do - or just very fast humans  like yours truely :), you usually get:

"Server returned an error: HTTP Error 400: service in progress"

That you can't SR if the service is running, is all fair - but it's not a client error. As such 400 is wrong - it is not a 'bad request'. Either the API should wait itself for the service to complete - or throw a 504 'Backend not ready in time'. Which would give osc at least a chance to wait client side.

**Comment by kobliha** [comment]
+1 Please fix it, thanks in advance

**Comment by lslezak** [comment]
BTW this makes many YaST SR to Factory fail, then we have to manually restart the Jenkins job.

We can improve it in out scripts but it should be handled transparently by OBS/OSC. Ideally the SR should not be blocked by the service run.

**Comment by adrianschroeter** [comment]
On Donnerstag, 12. Oktober 2017, 09:59:24 CEST wrote Stephan Kulow:
> If you commit to a package in a Factory devel package and try to submit request it right afterwards (as CI systems like to do - or just very fast humans  like yours truely :), you usually get:
> 
> "Server returned an error: HTTP Error 400: service in progress"
> 
> That you can't SR if the service is running, is all fair - but it's not a client error. As such 400 is wrong - it is not a 'bad request'. Either the API should wait itself for the service to complete - or throw a 504 'Backend not ready in time'. Which would give osc at least a chance to wait client side.

We have a wait command which can be used if you have this use case. Actually "osc ci" is doing that after commit
to wait for the service.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by lslezak** [comment]
How can we use that feature in our scripts? See https://ci.opensuse.org/job/yast-installation-control-master/74/console for an example failure. Any suggestions how to improve that workflow?

**Comment by lslezak** [comment]
If I got it right we should  run (in this case)
```shell
osc service wait 'YaST:Head' 'yast2-installation-control'
```
before executing `osc sr ...`.

Is it safe to call it even when the package is not changed in the devel project? E.g. it has been committed earlier.

**Comment by adrianschroeter** [comment]
yes, it is.

**Comment by mlschroe** [comment]
There are many opinions on what statuscode to return for "in progress". I kind of like "409" meaning resource conflict.

**Comment by lslezak** [comment]
JFYI: I have added `osc service wait` in https://github.com/openSUSE/packaging_rake_tasks/pull/42

**Comment by adrianschroeter** [comment]
okay, so closing this one here.
