### ISSUE TITLE
[production][public#binary_packages] undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#4001]
public#binary_packages threw this 0 times
<pre>
undefined method `each&#39; for nil:NilClass
</pre>
[link removed]

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59df0635975ab3000eac098b)

**Comment by bgeuken** [comment]
That doesn't seem to happen anymore
