### ISSUE TITLE
It's possible to answer on outdated comments

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#4015]
Issue/Feature description
====================
It was probably intended to be this way but I don't see the point in it. The problem is, if you're superseding a request, you have the option to show the comments from the old request. This feature is really cool but there is also the option to still answer on them. You don't want to always expand the "outdated comments" tab to check if some by accident answered in that section just because there are 2 comment fields (the one for the old request and the one from the current).

Expected result
============
I'd expect to only continue discussions as before (so with the comment field for the current request) or always show the old comments and tag them somehow, but please get rid of the two commenting fields. It's just weird.

How to Reproduce
===============
1. Create two requests
2. Comment on one
3. Supersede the request you were commenting on

**Comment by ChrisBr** [comment]
I don't think this is a bug. Look at how github does it, there you can also comment on outdated comments.
