### ISSUE TITLE
DataTables warning when listing reviews for a group containing a period

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/open-build-service#4021]
Issue/Feature description
====================

When accessing the review list for group _maintenance-opensuse.org_ via WebUI on https://build.opensuse.org/group/show/maintenance-opensuse.org, the following errors are shown:

```
DataTables warning: table id=reviews_in_table - Ajax error. For more information about this error, please see http://datatables.net/tn/7
DataTables warning: table id=requests_in_table - Ajax error. For more information about this error, please see http://datatables.net/tn/7
DataTables warning: table id=all_requests_table - Ajax error. For more information about this error, please see http://datatables.net/tn/7
```

The errors seem to relate to this particular group. It is the only group throwing this error, and the only with a _._ in it.

Expected result
============

No error shown. 6 reviews, or none, depending on current reviews.

How to Reproduce
===============
1. Visit https://build.opensuse.org/group/show/maintenance-opensuse.org when this group has open reviews

Further information
===============
* https://build.opensuse.org/group/show/maintenance-opensuse.org

**Comment by ChrisBr** [comment]
@andreasstieger thanks for reporting, this seems indeed a problem with the group name!

**Comment by ChrisBr** [comment]
@andreasstieger and deployed to build.o.o
