### ISSUE TITLE
RabbitMQ sees users as ids

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#4026]
```
2017-10-16 16:02:15:979: Message published

Exchange:     pubsub
Routing keys: [<<"opensuse.obs.project.comment">>]
Payload: 
{"project":"home:coolo","commenters":[36,5],"commenter":5,"comment_body":"test"}
```

While the project and the comment are strings, the users are given as user ids. As the OBS API has no way to retrieve the user name from these IDs, they need to be mapped.

**Comment by adrianschroeter** [comment]
internal IDs should not get exposed via the api by design ...
