### ISSUE TITLE
[production][delayed_job#SendEventEmailsJob] undefined method `watched_projects' for nil:NilClass

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#4040]
delayed_job#SendEventEmailsJob threw this 14 times
<pre>
undefined method `watched_projects&#39; for nil:NilClass
</pre>

[See this exception on Errbit](http://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59e88083586c520006e569cf)

**Comment by coolo** [comment]
fixed - I take the freedom
