### ISSUE TITLE
Delayed Job Migrations

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#4045]
delayed_job#EventNotifyBackendJob threw this 39 times
<pre>
uninitialized constant EventNotifyBackendJob
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59e867dd586c520006e569ba)

**Comment by hennevogel** [comment]
Whenever we delete `ActiveJobs` from the code base we should also write a migration that drops them from the delayed job table

**Comment by mdeniz** [comment]
Oops my fault I guess 😞
