### ISSUE TITLE
Include osc-plugin-factory integration tests in CI

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/open-build-service#4047]
Per #1207 (Provide local OBS setup, base data creation, test harness, and initial set of tests) I have created tests that run against real OBS instance using the docker setup provided. Given that tools are one of the biggest consumers from OBS perspective it seems beneficial to run their tests to see if breaking changes are made an ensure the tools are updated accordingly.

Alternatively, I will likely end up creating a special branch or trigger to run tests anytime commits are made to OBS. It seems better to have OBS team be aware of breakages before they are introduced rather than reacting afterwards. Similarly, I plan to suggests the same for `osc` which has made internal changes that end up breaking the tools.

If there is consensus that this is of interest I will create a PR once everything is sorted out on our end. Currently, still need to workaround #3946, but `opensuse-releaseteam-travis` I created never succeeds in authenticating.

**Comment by hennevogel** [comment]
So you want to add another test suite to the OBS test matrix on travis? Did I understand this correctly?

**Comment by hennevogel** [comment]
Regarding the *tests against real OBS instance*, have you seen our [openQA test suite](https://github.com/os-autoinst/os-autoinst-distri-obs)?

**Comment by jberry-suse** [comment]
Yes, another matrix entry that would run head of `osc-plugin-factory` repo integration tests. I had not seen the openQA tests, but from what I can tell they do not produce a Factory-like setup, I see for building a basic package and such. For even a basic review bot to run we need `openSUSE:Factory` setup with relevant repos and such, all review groups and users, devel project, devel package, maintainers set properly, etc. The other blocker being that the previous vagrant development setup would not run on travis, but the docker setup should. Combining everything together it brings up docker-based OBS, re-creates facsimile of Factory and related, then runs tests.

For OBS run it should be able to use the OBS already booted directly in travis (which I imagine based on original PR will eventually we switched over to docker one as well).

**Comment by adrianschroeter** [comment]
sorry, we won't test external code here, but you could provide test cases for the api calls you do to ensure that the OBS code is not breaking.

**Comment by jberry-suse** [comment]
The bots and tools touch the majority of the OBS API interface. As such duplicating our code to have a static version in OBS seems a bit wasteful. I understand you do not want to be responsible for external code, but my thought was as one of the biggest consumers you have a large, real-world test suite to help catch unintended changes and breakages. I would understand that if you make an intentional change that breaks our tools you could mark the broken tests to be skipped until resolved. The principal idea being possible to catch issues on OBS end and notify us when there is something we need to handle.

If OBS is not interested in running integration tests with biggest consumer then I will likely setup a travis build to run either daily or on every commit to OBS to do exactly that. The tests should be run it is just a question of if OBS would like some responsibility in breaking changes.

From your response I will assume this issue should be closed and I will have to setup a trigger.

**Comment by hennevogel** [comment]
> have a large, real-world test suite to help catch unintended changes and breakages. 

We already have that, twice. Feel free to extend one of those suites to cover your use cases. But dropping your test suite into our lap isn't going to fly, sorry.

> catch issues on OBS end and notify us when there is something we need to handle rather than finding out once deployed. 

You could also involve yourself into the deployment of the reference servers obs_factory engine (which is already dropped into our lap) to make sure your CI cycle is somewhere in there 🙃

**Comment by jberry-suse** [comment]
> We already have that, twice. Feel free to extend one of those suites to cover your use cases. But dropping your test suite into our lap isn't going to fly, sorry.

Not dropping in lap, but seems to be the attitude I get from OBS. Integration tests are common and heavily used in places like Google. It helps teams not walk on eachother's toes and keeps the end result more stable.

> You could also involve yourself into the deployment of the reference servers obs_factory engine (which is already dropped into our lap) to make sure your CI cycle is somewhere in there 🙃

This all predates me and from what I understand, being ruby and tied to OBS the goal was to have OBS team take it over not the other way around. It will end up in my integration tests since `osc-plugin-factory` obviously depends on it.
