### ISSUE TITLE
👋🏿 utf8mb in comments

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#4049]
request#request_command threw this 41 times
<pre>
Mysql2::Error: Incorrect string value: &#39;\xE1draig...&#39; for column &#39;reason&#39; at row 1: UPDATE `reviews` SET `state` = &#39;declined&#39;, `reason` = &#39;Output of check script:\nSource validator failed. Try \&quot;osc service localrun source_validator\&quot;\n  (E) coreutils-testsuite.keyring mentioned in spec file does not exist.\n  (E) coreutils-testsuite-8.27.tar.xz mentioned in spec file does not exist.\n  (E) coreutils-testsuite-8.27.tar.xz.sig mentioned in spec file does not exist.\n  gpg: no need for a trustdb check with `always\&#39; trust model\n  gpg: Signature made Thu Mar  9 06:46:02 2017 CET using RSA key ID 306037D9\n  gpg: Good signature from \&quot;P�draig Brady &lt;P@draigBrady.com&gt;\&quot; [unknown]\n  gpg:                 aka \&quot;P�draig Brady &lt;pbrady@redhat.com&gt;\&quot; [unknown]\n  gpg:                 aka \&quot;P�draig Brady &lt;pixelbeat@gnu.org&gt;\&quot; [unknown]\n  - package has baselibs.conf: (unchanged)\n  \n&#39;, `reviewer` = &#39;factory-auto&#39;, `updated_at` = &#39;2017-08-16 08:17:50.605240&#39; WHERE `reviews`.`id` = 1551137
</pre>
[https://api.opensuse.org/request/517144?newstate=declined&amp;by_group=factory-auto&amp;cmd=changereviewstate](https://api.opensuse.org/request/517144?newstate=declined&amp;by_group=factory-auto&amp;cmd=changereviewstate)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5993ffaf088db60006de1113)

**Comment by hennevogel** [comment]
those fields (or all fields?) should be utf8mb...

**Comment by bgeuken** [comment]
Solved by #5419
