### ISSUE TITLE
[production][project#save_meta] SUSE:SLE-12:SP3

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#4051]
project#save_meta threw this 66 times
<pre>
SUSE:SLE-12:SP3
</pre>
[https://build.opensuse.org/project/save_meta/devel:languages:erlang](https://build.opensuse.org/project/save_meta/devel:languages:erlang)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59d3c162ce3923000836ddd9)

**Comment by adrianschroeter** [comment]
not handled validation failure when referencing a not existing project in repository config

**Comment by ChrisBr** [comment]
Duplicate of https://github.com/openSUSE/open-build-service/issues/3916
