### ISSUE TITLE
invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#4052]
threw this 4 times
<pre>
invalid byte sequence in UTF-8
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59d462e98de82d0006f82a3e)

**Comment by hennevogel** [comment]
Maybe related to #4049?

**Comment by eduardoj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [P9: (5) SendEventEmailsJob: invalid byte sequence in UTF-8](https://trello.com/c/ctkz55s9/707-p9-5-sendeventemailsjob-invalid-byte-sequence-in-utf-8)

**Comment by eduardoj** [comment]
The issue was closed without intention. Reopening.

**Comment by hennevogel** [comment]
This was handled in #4785

**Comment by ismail** [comment]
FWIW osc sr from Archiving/unrar still fails with the same error.

**Comment by bgeuken** [comment]
> hennevogel commented 13 days ago
>
> This was handled in #4785

This was just some code to re-raise the exception for debugging it. It wasn't fixing the issue.


#4845 was deployed last Wednesday and fixes the source diff encoding (convertin it to UTF-8 if it's invalid encoding).

@ismail Could you check if you can do submit requests now?

**Comment by ismail** [comment]
@bgeuken Somebody else was already able to submit unrar, so I guess this is fixed. Thanks!

**Comment by bgeuken** [comment]
Great!

=> closing
