### ISSUE TITLE
Project undelete seems to lead to broken database

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#4060]
Our consistency check found a number of inconsitent project and package meta data this weekend. The common pattern was that the project got undeleted, but projects or package entries where missing. Also the undelete operation itself seems to be kind of broken, because the history has no login set and most likely no comment (the backend default text is inside). 

Example is    

  home:rexut:Factory:ftdi-eeprom ftdi-eeprom

package. haven't checked the log files.

(There where also the lost package objects of maintenance releases again, but may be unrelated).

**Comment by DavidKang** [comment]
@adrianschroeter, this is still valid?

**Comment by hennevogel** [comment]
Seems very related to #3735

**Comment by hennevogel** [comment]
I guess it is...
