### ISSUE TITLE
Bug in Firefox, Chrome, Edge, Windows 10, 8.1 in OBS

### ISSUE THREAD

**Issue by bittin** [openSUSE/open-build-service#4071]
Hello, when i try to click on the distro links for RHEL, SUSE, Ubuntu etc in the latest browsers on Windows on OBS on this page: https://software.opensuse.org/download.html?project=home:ailin_nemui:irssi-test;package=irssi it does not work as intended for me, so i had to open up links on a RHEL machine to get the rpm i wanted maybe something for you too look into

**Comment by hennevogel** [comment]
software.opensuse.org is another application. Please report issues over there -> https://github.com/openSUSE/software-o-o
