### ISSUE TITLE
Test case "check comments on remote projects" fails

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#408]
The test case "check comments on remote projects" fails after I added some package to the fixtures.

So far, this test went to a package on a remote instance which does not exist. So the project web page appeared and showed the error. The test added the comment to the local project then. 

Now the package exists and the webui shows jsut an empty page because it is a remote instance. The adding a comment function is crashing now.

**Comment by hennevogel** [comment]
I guess we can close this...
