### ISSUE TITLE
[production][package#submit_request_dialog] no implicit conversion of nil into String

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#4094]
package#submit_request_dialog threw this 4 times
<pre>
no implicit conversion of nil into String
</pre>
[https://build.opensuse.org/package/submit_request_dialog/home:Vogtinator:branches:KDE:Applications/konqueror?revision=3](https://build.opensuse.org/package/submit_request_dialog/home:Vogtinator:branches:KDE:Applications/konqueror?revision=3)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59f5d3f072f936000c61f781)

**Comment by hennevogel** [comment]
does not happen anymore
