### ISSUE TITLE
[production][search#bs_request] wrong number of arguments (given 7, expected 3)

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#4096]
search#bs_request threw this 1 times
<pre>
wrong number of arguments (given 7, expected 3)
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59f9861aa8432a000b3a65fd)

**Comment by hennevogel** [comment]
does not happen anymore
