### ISSUE TITLE
Failed authorization for modifying projects throws exception

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#4102]
project#remove_role throws this while it shouldn't. It should inform the user and move on.
<pre>
No permission to modify project &#39;home:kalabiyau:ruby&#39; for user &#39;digitaltomm&#39;
</pre>
[https://build.opensuse.org/project/remove_role/home:kalabiyau:ruby?userid=sandrew](https://build.opensuse.org/project/remove_role/home:kalabiyau:ruby?userid=sandrew)"

~~[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59fadc89fe0a33000645d7f0)~~

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b51caf92647670006e70a80)

**Comment by eduardoj** [comment]
How to Reproduce
===============
1. Create a package as `user1`.
1. Add user `user2` as a mantainer.
1. In other browser enter as `user2` and stay on the page of users of the package. You will see the remove icon of the `user1`. Stay there.
1. In the browser with `user1` remove `user2` as mantainer, and make it reader.
1. As `user2` click on the remove icon of the `user1`.
1. See error 500.

**Comment by eduardoj** [comment]
Fixed. After trying to reproduce the error, this message is shown, without any 500 error:
```Sorry, you are not authorized to update this Package.```
