### ISSUE TITLE
[security issue] AppImage update information URLs use HTTP instead of HTTPS

### ISSUE THREAD

**Issue by TheAssassin** [openSUSE/open-build-service#4106]
AppImages built on OBS contain update information by default, which is good since it allows users to update the AppImages with little effort.
However, the link is HTTP by default. Due to the lack of a good and secure trust model within AppImageUpdate's system based on the AppImages' signatures (which would allow the authentication of the packages sent by OBS, as they're signed with OBS's key IIRC), using HTTPS is basically a must to ensure the authenticity of the files fetched from the server (at least to some extent).

I suggest to change the URLs to use HTTPS immediately, and rebuild all the existing AppImages on OBS which are using HTTP (I assume that's all of them at the moment).

Link with examples: https://download.opensuse.org/repositories/home:/nandub:/MyAppImages/AppImage/

We will soon be working on a verification based on the key the signature of an AppImage was created with before the update, which provides a similar method of verification traditional package management uses.

AppImage project links:

  - https://github.com/AppImage/AppImageUpdate/issues/16
  - https://github.com/AppImage/AppImageKit/issues/175
  - https://github.com/AppImage/AppImageKit/issues/175#issuecomment-341565275

P.S.: I don't understand why they're served via HTTP at all, I assume it's for APT etc., who can't work with HTTPS repositories unless an additional "transport" package is installed.
At least for AppImage only repositories, a redirection to HTTPS by default seems like a good idea, especially for first-time downloads. MITM is still possible, but it looks better, and when using HTTP 301 redirects, browsers will cache the redirection and at least some potential MITM attacks can be prevented. I don't know how much effort it is to implement this, but I'd love to see such a feature.

**Comment by bgeuken** [comment]
@adrianschroeter @mlschroe Could you have a look at this?

**Comment by adrianschroeter** [comment]
not strictly an OBS code issue, but changed in build-pkg2appimge.

However, relying on SSL means every CA and every mirror can manipulate data, so it is not really a good idea for download content. But this can only be solved when we can encode some secure identifier as part of the URL.

**Comment by TheAssassin** [comment]
Soon AppImageUpdate will be able to verify the GPG signatures, so that'll harden the security. In the meanwhile, using HTTPS instead of HTTP is way more secure than it was previously. Thanks a lot for fixing this so quickly.
