### ISSUE TITLE
Diff view: jQuery selector for certain filenames broken

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/open-build-service#4129]
Certain filenames are not escaped properly before using them as CSS selectors, which breaks the diff view of requests with those filenames as part of the diff.

Example: https://build.opensuse.org/request/show/540357

From kapptemplate on, the diff views are broken as ```kapptemplate-17.08.3.tar.xz/src/templates/C++/akonadiserializer/akonadi_serializer_%{APPNAMELC}.desktop``` gets converted into a apparently broken jQuery selector as the console shows:

```
Syntax error, unrecognized expression: #diff_view_kapptemplate-17_08_3_tar_xz_src_templates_C___akonadiserializer_akonadi_serializer_%{APPNAMELC}_desktop_diff_action_47_submit_0_6_placeholder
```

**Comment by coolo** [comment]
I guess using the (escaped) filename directly was a bad idea - using the md5 digest of it might be more portable

**Comment by Vogtinator** [comment]
Still happens: https://build.opensuse.org/request/show/616489

**Comment by perlpunk** [comment]
Is this still an issue?
I tested locally with a file `testfile_%{FOO}.txt` and the diff view seems to be fully functional:
![obs-diff](https://user-images.githubusercontent.com/688850/83284266-c64c7d00-a1dc-11ea-95db-99f954a4998e.png)

**Comment by hennevogel** [comment]
please reopen if you still see problems

Thanks @perlpunk for checking

**Comment by Vogtinator** [comment]
I can confirm that it's fixed: https://build.opensuse.org/package/rdiff/KDE:Applications/kapptemplate?linkrev=base&rev=109
