### ISSUE TITLE
[production][package#submit_request] Mysql2::Error: Data too long for column 'payload' at row 1: INSERT INTO `events` (`eventtype`, `p...

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#4146]
package#submit_request threw this 0 times
<pre>
Mysql2::Error: Data too long for column &#39;payload&#39; at row 1: INSERT INTO `events` (`eventtype`, `payload`, `created_at`, `updated_at`) VALUES (&#39;Event::RequestCreate&#39;, &#39;{\&quot;author\&quot;:\&quot;xenonpk\&quot;,\&quot;description\&quot;:\&quot;- Update to version 0.0.4~git20171118:\\r\\n  * Fix cond_variable timeout\\r\\n  * Bump CMake requirement\\r\\n  * Implement savedata delete op\\r\\n  * Fix fs::dir (const begin/end)\\r\\n  * Fix cellMsgDialog\\r\\n  * cellSaveData fixes\\r\\n  * Minor fix (cellGame)\\r\\n  * Implement _sys_prx_load_module_by_fd\\r\\n  * RSX: Rewrite frame limit\\r\\n  * Optimize cpuid\\r\\n  * Fix command line args\\r\\n  * Add supporters\\r\\n  * ALSA audio backend fixes\\r\\n  * Implement set_ideal_processor_core (linux)\\r\\n  * Fire callback in cellSearchInitialize\\r\\n  * Fix bug in sys_spu_thread_group_create (#3734)\\r\\n  * Bump version to 0.0.4\\r\\n  * GUI: Style fix for Kuroi (Dark)\\r\\n  * Fixes commit count on GIT-VERSION\\r\\n  * Fix off by one error in trophies (#3715)\\r\\n  * F
</pre>
[https://build.opensuse.org/package/submit_request/home:xenonpk/rpcs3](https://build.opensuse.org/package/submit_request/home:xenonpk/rpcs3)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a10a20652fc66000670fa4d)

**Comment by evanrolfe** [comment]
Fixed by https://github.com/openSUSE/open-build-service/pull/4184
