### ISSUE TITLE
New LDAP support inconsistencies

### ISSUE THREAD

**Issue by c-hoeger** [openSUSE/open-build-service#4147]
Some when in 2.8, ldap support was changed in a way that now there's no mix of ldap and non-ldap accounts possible anymore. This leads into the following inconsistencies:

1. Bootstrapping a server e.g. using deployment automation: Now since there's no default Admin account available anymore directly after deployment, it is not possible to configure obs using e.g. curl: *curl --insecure -0 --user 'Admin:PASSWORD' -X PUT -T /srv/obs/configuration-custom.xml https://buildservice.example.com/configuration*
2. Although not usable, there's still the user Admin in the list of users. Not sure what to do with that account now. If the intention is to have this user created into the ldap server, I fear that this is a no-go in most situations.

I would vote for bringing back the old behavior where both ldap and non-ldap users were possible.

**Comment by Ana06** [comment]
@adrianschroeter any update here? :thinking:

**Comment by bgeuken** [comment]
We re-added this in [2.9.2](https://github.com/openSUSE/open-build-service/blob/2.9/ReleaseNotes-2.9.2#L23): `Admins can now mark user to be managed locally instead via LDAP`

Please check our [admin guide](https://openbuildservice.org/help/manuals/obs-admin-guide/obs.cha.administration.html#_obs_ldap_configuration). If you find that there is still something missing, please let us know.

**Comment by c-hoeger** [comment]
This is completely unrelated to the problem this issue describes.

**Comment by seife** [comment]
Carsten, please read the fine admin manual ;-)

https://openbuildservice.org/help/manuals/obs-admin-guide/obs.cha.administration.html#_obs_ldap_configuration

You can give "any" user the admin role from the command line. This user can then create the "Admin" user and give him the administrator role. The Admin can then remove the admin bit from "any" user.

The only thing that did not work for me is changign the password of a local user after creation, but some years ago it worked with
``` LOGIN="Admin"
 echo -n "newpassword" > file
 osc api -X POST -T file /person/$LOGIN?cmd=change_password```

**Comment by c-hoeger** [comment]
> You can give "any" user the admin role from the command line. This user can then create the "Admin" user and give him the administrator role. The Admin can then remove the admin bit from "any" user.

Yes, I know. Our internal obs admin is called obs-admin. But there's still this now superfluous user called "Admin". During the deployment this user is NOT LOCAL and this it would need to exist in LDAP.

Anyway, I solved this problem already in creating an additional Admin called obs-admin in the deployment and I can live with that useless user called Admin.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make first logged in user admin (instead of 'Admin')](https://trello.com/c/zM1UGM5a/1362-make-first-logged-in-user-admin-instead-of-admin)

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make first logged in user admin (instead of 'Admin')](https://trello.com/c/zM1UGM5a/1362-make-first-logged-in-user-admin-instead-of-admin)
