### ISSUE TITLE
projects with api -X POST /source/prj/cmd=freezelink called are not frozen and can not be checked out

### ISSUE THREAD

**Issue by dirkmueller** [openSUSE/open-build-service#4164]
Issue/Feature description
====================

Calling 

  osc  api  -X  POST /source/someproject?cmd=freezelink

on a project doesn't cause the project to be frozen anymore and any attempt to check it out causes an error message:

osc co home:suse-cloud-ci:rpm-packaging-sles12-Master-10668f025da71fe73305265a8b89d09882e6dae7
A    home:suse-cloud-ci:rpm-packaging-sles12-Master-10668f025da71fe73305265a8b89d09882e6dae7
  BuildService API error: missing rev attribute in _files:
  <directory count="1">
    <entry name="python-os-client-config" />
  </directory>

Expected result
============

Freezelink command actually freezes the project and the project can be checked out

**Comment by adrianschroeter** [comment]
can not reproduce it atm...

**Comment by dirkmueller** [comment]
still works for me:

```
$ osc co home:suse-cloud-ci:rpm-packaging-sles12-Master-1f5051cecdd1d848f4eb236a25e4f58303009aa9
A    home:suse-cloud-ci:rpm-packaging-sles12-Master-1f5051cecdd1d848f4eb236a25e4f58303009aa9
BuildService API error: missing rev attribute in _files:
<directory count="3">
  <entry name="openstack-dashboard" />
  <entry name="openstack-mistral" />
  <entry name="python-keystoneauth1" />
</directory>
```

also, there is still no freezes file

**Comment by mlschroe** [comment]
Sorry, can't reproduce. What osc version is this?

**Comment by mlschroe** [comment]
Are you running osc inside a directory with a weird osc state?
