### ISSUE TITLE
bs_mergechanges is missing Date/Parse.pm

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/open-build-service#4176]
Issue description
====================

when opening
https://build.opensuse.org/package/live_build_log/home:bmwiedemann:reproducible:test/binutils/openSUSE_Tumbleweed/x86_64

Actual result
==========

```
running diff3 on binutils.spec
running merge tool on binutils.changes
Can't locate Date/Parse.pm in @INC (you may need to install the Date::Parse module) (@INC contains: . ./build /usr/lib/perl5/site_perl/5.18.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.18.2 /usr/lib/perl5/vendor_perl/5.18.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.18.2 /usr/lib/perl5/5.18.2/x86_64-linux-thread-multi /usr/lib/perl5/5.18.2 /usr/lib/perl5/site_perl .) at ./bs_mergechanges line 31.
BEGIN failed--compilation aborted at ./bs_mergechanges line 31.
running diff3 on binutils.changes
```

Expected result
============
OBS should not show such an internal error

Notes
=====
there is probably a
```
Requires: perl(TimeDate)
```
missing somewhere, but it already is in dist/obs-server.spec for obs-worker and obs-server packages

**Comment by mlschroe** [comment]
It's missing on obs-server.spec...

**Comment by adrianschroeter** [comment]
The build log error comes indeed from source server where the dependency is lacking.
Fixed now.
