### ISSUE TITLE
keyring changes should be displayed as red too

### ISSUE THREAD

**Issue by ismail** [openSUSE/open-build-service#4182]
Recently OBS started to show deleted files with red which is very good for usability.: ![obs](https://user-images.githubusercontent.com/4255/33555627-6a0bb890-d901-11e7-824e-ced41f9896e3.png) 

I suggest also showing *.keyring file changes as red because keyring is used to check for package's cryptographic integrity and any changes to that file requires extra attention. 

Hence I think it would be useful to use red or some similar color for changes to *.keyring files too.

**Comment by mschnitzer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mark changes to *.keyring files in requests](https://trello.com/c/K0ZK9p2O/1259-mark-changes-to-keyring-files-in-requests)

**Comment by adrianschroeter** [comment]
How do you use *.keyring files?
IMHO this is something what is a convention by some packagers, but there is no relation to OBS mechanics, is it?

**Comment by ismail** [comment]
When you add a keyring file as source, (if enabled in the project configuration) osc build validates the signature against the keyring. I wouldn't say it's totally unrelated to OBS mechanics.

**Comment by Ana06** [comment]
I understand that this is important... but using colors for this... :thinking: Maybe we can come up with a better solution. configurable filters maybe? :bowtie:

**Comment by ChrisBr** [comment]
@Ana06 what is a 
>  configurable filters

And what is wrong with using colors? There is still the text (changed, added ...) so it shouldn't be an issue in regards of accessibility!

**Comment by adrianschroeter** [comment]
@ismail how do you verify exactly? Using a source service?

**Comment by ismail** [comment]
@adrianschroeter I am not sure how this is handled but for example 

> devel:libraries:c_c++/qpdf

project validates the signature during osc build:

> havana ~/obs/devel:libraries:c_c++/qpdf > osc build
Run source service: /usr/lib/obs/service/format_spec_file --outdir /havana/obs/devel:libraries:c_c++/qpdf/tmpkpDh6l.format_spec_file.service
Run source service: /usr/lib/obs/service/source_validator --outdir /havana/obs/devel:libraries:c_c++/qpdf/tmpFw39Gb.source_validator.service
gpg: assuming signed data in '/suse/idoenmez/obs/devel:libraries:c_c++/qpdf/qpdf-8.0.0.tar.gz'
gpg: Signature made Sun Feb 25 22:02:49 2018 CET
gpg:                using RSA key 8A75D10998012C7E
gpg: Good signature from "Jay Berkenbilt <ejb@ql.org>" [unknown]
gpg:                 aka "Jay Berkenbilt <qjb@debian.org>" [unknown]
Building qpdf.spec for openSUSE_Factory/x86_64

**Comment by adrianschroeter** [comment]
On Dienstag, 27. Februar 2018, 09:42:28 CET wrote İsmail Dönmez:
> @adrianschroeter I am not sure how this is handled but for example 
> 
> > devel:libraries:c_c++/qpdf
> 
> project validates the signature during osc build:
> 
> > havana ~/obs/devel:libraries:c_c++/qpdf > osc build
> Run source service: /usr/lib/obs/service/format_spec_file --outdir /havana/obs/devel:libraries:c_c++/qpdf/tmpkpDh6l.format_spec_file.service
> Run source service: /usr/lib/obs/service/source_validator --outdir /havana/obs/devel:libraries:c_c++/qpdf/tmpFw39Gb.source_validator.service
> gpg: assuming signed data in '/suse/idoenmez/obs/devel:libraries:c_c++/qpdf/qpdf-8.0.0.tar.gz'
> gpg: Signature made Sun Feb 25 22:02:49 2018 CET
> gpg:                using RSA key 8A75D10998012C7E
> gpg: Good signature from "Jay Berkenbilt <ejb@ql.org>" [unknown]
> gpg:                 aka "Jay Berkenbilt <qjb@debian.org>" [unknown]
> Building qpdf.spec for openSUSE_Factory/x86_64
> 
> 

Ah, in "files present and referenced" .... obvious ...


-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by ismail** [comment]
Let's close this as wontfix on it's 6-year anniversary.
