### ISSUE TITLE
feature: allow to disable comment feature per project/package

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#4192]
The comment feature of OBS is a great thing, but in projects like openSUSE:Factory it is 'misused'

People keep on writing package bugs into the comments there, which tend to not be seen by anybody (every now and then I catch some in my inbox, but the comments there are definitively not on the highest todo of all the mails OBS sends me)

It would be great if openSUSE:Factory (and certainly other projects too) could disable the feature to have comments posted on the project and its packages, preferably with a custom 'denied' message, instructing the poster to use either the mailing lists or bugzilla, depending on the nature of the comment they intended to post.

**Comment by vpereira** [comment]
would it be disabled as well for requests? If yes, it could break the openQA notifications..

**Comment by DimStar77** [comment]
> would it be disabled as well for requests? If yes, it could break the openQA notifications..

definitively not - on SR the comments are more than welcome and a much used tool

**Comment by coolo** [comment]
if you think this will stop users from using the proper forums to report problems, check the issue +2 from this :)

**Comment by plusky** [comment]
Just leaving humble usecase - I am getting notifications for i.e comments in ttps://build.opensuse.org/package/show/openSUSE:Factory/csound as I am one of maintainers of csound's devel project - which is annoying.

**Comment by Vogtinator** [comment]
Can we please get this implemented alongside a proper "Report bug" button for packages in oS:F? My inbox would be happy.

**Comment by hennevogel** [comment]
@Vogtinator disabling comments as maintainer is on the plate for the [content moderation feature](https://featmap.copyleft.dev/link/5ac3e6c2-a30b-44f9-b554-407f27b9e86d) we currently work on.

And what is a proper "Report bug" button for packages in oS:F? Can you please open a separate issue about this?

**Comment by Vogtinator** [comment]
> And what is a proper "Report bug" button for packages in oS:F? Can you please open a separate issue about this?

Previously, packages on OBS had a "report bug" button which led to bugzilla with prefilled text. It appears that disappeared?

**Comment by Vogtinator** [comment]
> That's simply because factory project doesn't seem to have bugowners, and that's a check that's done before displaying that button.

It could behave like osc and traverse the devel pkg link.

**Comment by hennevogel** [comment]
@Vogtinator Can you please open a separate issue about this so we can discuss this not in a completely unrelated issue?

**Comment by Vogtinator** [comment]
> @Vogtinator Can you please open a separate issue about this so we can discuss this not in a completely unrelated issue?

Of course: https://github.com/openSUSE/open-build-service/issues/14987
