### ISSUE TITLE
Bug with Album view in Digikam 5.7

### ISSUE THREAD

**Issue by elhennig** [openSUSE/open-build-service#4194]
Please rebuild Digikam 5.7 with the latest fixes from Git to fix a problem that occurs with the album view and QT 5.9.3:
See https://bugs.kde.org/show_bug.cgi?id=387373

**Comment by mschnitzer** [comment]
Hey,

thanks for reporting an issue to our repository. Unfortunately, we cannot directly help you in this regard. We're just maintaining the code of OBS and deploy the newest version. You'd have to got to the maintainer of this package or leave a comment to it: https://build.opensuse.org/package/show/KDE:Unstable:Extra/digikam

But it seems that they were already working on it. I'd just wait till it gets released in the distribution.

**Comment by elhennig** [comment]
Thanks for your hint. I just did not know if contacting the maintainer directly was the right was to report bugs for single packages.
