### ISSUE TITLE
Changed tar.gz file is not showing up in request

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#4203]
When creating a submit request with a `tar.gz` file that has changed, it is not showing up that it has been changed in the `request#show` page.

Example: https://build.opensuse.org/request/show/555928 (just have a look at the source and the target - the tar.gz file differs in both so it should show up in the request)

This is either a frontend or a backend bug. Not sure yet.

**Comment by mlschroe** [comment]
Seems to be a backend issue. Removing Frontend.

**Comment by mlschroe** [comment]
Fixed with commit 3a5d5b8f6308d888846a376b828682f474973011
