### ISSUE TITLE
[production][source#update_project_meta] Mysql2::Error: Data too long for column 'description' at row 1: UPDATE `projects` SET `descriptio...

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#4214]
source#update_project_meta threw this 159 times
<pre>
Mysql2::Error: Data too long for column &#39;description&#39; at row 1: UPDATE `projects` SET `description` = &#39;requests:\n- {author: maxlin_factory, id: 549491, package: ghc-binary-conduit, type: submit}\n- {author: maxlin_factory, id: 549492, package: ghc-binary-orphans, type: submit}\n- {author: maxlin_factory, id: 549493, package: ghc-binary-search, type: submit}\n- {author: maxlin_factory, id: 549494, package: ghc-binary-tagged, type: submit}\n- {author: maxlin_factory, id: 549495, package: ghc-bindings-DSL, type: submit}\n- {author: maxlin_factory, id: 549496, package: ghc-biocore, type: submit}\n- {author: maxlin_factory, id: 549497, package: ghc-bitarray, type: submit}\n- {author: maxlin_factory, id: 549498, package: ghc-bitcoin-script, type: submit}\n- {author: maxlin_factory, id: 549499, package: ghc-blaze-bootstrap, type: submit}\n- {author: maxlin_factory, id: 549500, package: ghc-blaze-builder, type: submit}\n- {author: maxlin_factory, id: 549501, package: ghc-blaze-html, type: sub
</pre>
[https://api.opensuse.org/source/openSUSE:Leap:15.0:Staging:adi:4/_meta?force=1](https://api.opensuse.org/source/openSUSE:Leap:15.0:Staging:adi:4/_meta?force=1)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a272daf705b150010cff78f)

**Comment by hennevogel** [comment]
@jberry-suse are you trying other fields now for passing around data?

**Comment by jberry-suse** [comment]
Nope. That has been part of the tooling for ages as you will find that yaml data in all staging project descriptions.

**Comment by jberry-suse** [comment]
Seems like something the tools should try and prevent, but curious if something changed as we've had stagings with several thousand requests which should dwarf anything normally.

**Comment by hennevogel** [comment]
does not happen anymore
