### ISSUE TITLE
[production][images#import_from_package] no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#4215]
images#import_from_package threw this 0 times
<pre>
no implicit conversion of String into Integer
</pre>
[https://build.opensuse.org/package/1389819/kiwi_images/import_from_package](https://build.opensuse.org/package/1389819/kiwi_images/import_from_package)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a2a6e9be8fe96000dd7da5d)

**Comment by ChrisBr** [comment]
@DavidKang 
> The reason for this error is because we only permit one `preferences` group into the kiwi file, having more than one will return an array of hash. If I remember well, we say that we only allow 1 `preferences` group but I don't remember well with wich conditions

**Comment by ChrisBr** [comment]
@DavidKang what do you mean with conditions?

**Comment by DavidKang** [comment]
@ChrisBr, I wrote this comment for myself 😸 but basically is to take a look at the model `preference` and look what are importing and also the structure of the `xml`.

**Comment by adrianschroeter** [comment]
The multiple preference sections are default in leap 15, one preference for each profile.

So this could be considered as part of the profile selector card.

https://trello.com/c/mxB6Sx8N/1378-kiwi-editor-support-profile-selection

**Comment by adrianschroeter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [KIWI Editor: Support Profile Selection](https://trello.com/c/mxB6Sx8N/1378-kiwi-editor-support-profile-selection)
