### ISSUE TITLE
Impossible to aggregate multibuild flavors

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#4245]
As part of the Tumbleweed/Leap staging process, packages from Ring0 (openSUSE:Factory:Rings:0-Bootstrap) are aggregated (on demand, only when ring 0 is built) to the various staging projects into 'bootstrap-copy', which is then used as base to build against.

Recently, glibc was migrated to be a _multibuild package and now builds flavor 'i686' instead of the old link with top-patch (so a cleaner solution, for sure)

Unfortunately, glibc:i686 is not possible to be aggregated into the Staging projects (which makes the staging projects no longer to have glibc-32bit, which is intentionally only built as part of the i686 flavor)

* osc aggregatepac openSUSE:Factory:Rings:0-Bootstrap glibc:i686 fails (meta not found)
* Adding glibc:686 to the xml file manually results in no failure, but also not in the binaries being copied
* glibc itself is aggregated, but does not include the flavor i686

**Comment by DimStar77** [comment]
> Adding glibc:686 to the xml file manually results in no failure, but also not in the binaries being copied

This method actually should work (as more tests showed); so we can at least work around the issue for now

**Comment by hramrach** [comment]
Still impossible.

**Comment by hramrach** [comment]
possibly fixed in https://github.com/openSUSE/osc/pull/1009
