### ISSUE TITLE
Diff truncation notification appears after request got accepted

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#4269]
Issue description
====================

After accepting requests some of them start showing the diff truncation notification. Before the request got accepted, there was not message shown.

Expected result
============

The message is shown either before and after the request get's accepted or not at all.

Further information
===============

The request were I have seen this: https://build.opensuse.org/request/show/559283

**Comment by hennevogel** [comment]
I don't think this happens anymore...
