### ISSUE TITLE
Build ISO and VMX images together - as a result only ISO

### ISSUE THREAD

**Issue by Mexit** [openSUSE/open-build-service#4291]
KIWI config:
`<type image="vmx" firmware="uefi" format="vdi" ... />`
`<type image="iso" firmware="uefi" primary="true" hybrid="true" ... />`

Build for vmx (as a result, I get ISO)
`[  145s] running kiwi system build for vmx...`
`[  146s] [ INFO    ]: 15:30:14 | --> Selected build type: iso`
`[  146s] [ INFO    ]: 15:30:14 | Setup root directory: /usr/src/packages/KIWI-vmx/build/image-root`
 
And then ISO again
`[ 1597s] running kiwi system build for iso...`
`[ 1598s] [ INFO    ]: 15:54:26 | --> Selected build type: iso`
`[ 1598s] [ INFO    ]: 15:54:26 | Setup root directory: /usr/src/packages/KIWI-iso/build/image-root`

Full build log: [log.txt](https://github.com/openSUSE/open-build-service/files/1601128/log.txt)

**Comment by hennevogel** [comment]
Yes this is how OBS operates. One build description produces one binary. You need two kiwi config files for different types. You can achieve this by using a local link with a patch applied.  See for instance 

* https://build.opensuse.org/package/show/OBS:Server:Unstable/OBS-Appliance
* https://build.opensuse.org/package/show/OBS:Server:Unstable/OBS-Appliance-qcow2
