### ISSUE TITLE
[production][package#branch] <status code="400">
  <summary>service error: Command failed(128): &quot;Cloning into '/var/cache...

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#4355]
package#branch threw this 0 times
<pre>
&lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;service error: Command failed(128): &amp;quot;Cloning into &#39;/var/cache/obs/xP0i31dBfI2S/out/tmp7KQOkj/leafpad&#39;...\nfatal: unable to access &#39;https://github.com/oluc/leafpad.git/&#39;: Could not resolve host: github.com\n&amp;quot;&lt;/summary&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/package/branch](https://build.opensuse.org/package/branch)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a5a12a0dec4d2000936d0b4)

**Comment by evanrolfe** [comment]
I will close this issue because we already have an issue for this error:
https://github.com/openSUSE/open-build-service/issues/3957
