### ISSUE TITLE
Inconsistency in open requests

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#4361]
Issue/Feature description
====================
The overview page of hardware:RC-Model project is showin two open requests atm, but there are none listed when clicking on the link. osc also shows none open atm

Expected result
============
Either list the open ones or don't show them as open.

How to Reproduce
===============
1. Go to https://build.opensuse.org/project/show/hardware:RC-Model
2. Click on the "2 open requests" on top right
3. none are listed on next page.

**Comment by Ana06** [comment]
@adrianschroeter we need another way to reproduce this, that requests doesn't apear anymore

**Comment by vpereira** [comment]
as we cannot reproduce it, we are going to close it. Feel free to re-open it if necessary.

thank you!

**Comment by coolo** [comment]
https://build.opensuse.org/project/show/openSUSE:Factory:Staging:adi:3 has 9 open requests (by_project) - none is shown on the next page

**Comment by vpereira** [comment]
```osc rq ls -a openSUSE:Factory:Staging:adi:3``` cannot find it either..
No results for project openSUSE:Factory:Staging:adi:3

**Comment by coolo** [comment]
Neither does ``osc review list -P openSUSE:Factory:Staging:adi:3`` - and still they are there :)
