### ISSUE TITLE
comments POST event broken

### ISSUE THREAD

**Issue by nilxam** [openSUSE/open-build-service#4362]
Issue/Feature description
====================
comments POST event to a project fails to work and returned error 500. Although the comment has created.

Expected result
============
Should not given error 500.

How to Reproduce
===============
> $ osc api -X POST /comments/project/openSUSE:Leap:15.0:Staging:adi:172 -d '1234567890'
Server returned an error: HTTP Error 500: Internal Server Error
> 
> Request: https://api.opensuse.org/comments/project/openSUSE:Leap:15.0:Staging:adi:172
> Headers:
> status: 500 Internal Server Error
> x-request-id: 6194cc6a-dc30-481c-a050-886b269a4c70
> x-powered-by: Phusion Passenger 5.1.11
> connection: close
> strict-transport-security: max-age=31536000
> content-length: 131
> server: Apache/2.4.23 (Linux/SUSE)
> x-runtime: 0.337284
> date: Wed, 17 Jan 2018 09:32:28 GMT
> content-type: application/xml; charset=utf-8

And at the openSUSE:Leap:15.0:Staging:adi:172 the comment was created indeed.

**Comment by bgeuken** [comment]
Seems we have a regression / bug in our rabbitmq setup. For now we disabled rabbitmq. So commenting should work again.

@coolo JFYI^

**Comment by bgeuken** [comment]
This got solved by now. The culprit was a bug in a gem we used (https://github.com/ruby-amqp/bunny/issues/539).
