### ISSUE TITLE
OBS reports incorrect time stamp of a file

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#4365]
OBS reports an old timestamp even though the file was clearly modified at a
later time:

    $ osc api /source/openSUSE:Leap:15.0/000product|grep multibuild
    <entry name="_multibuild" md5="6a45cb1f74561b3c0c6874c057e9ae8e" size="131" mtime="1509707869" />
    $ date -d @1509707869
    Fri Nov  3 12:17:49 CET 2017
    $ osc log -r 92 openSUSE:Leap:15.0/000product|cat
    ----------------------------------------------------------------------------
    r92 | repo-checker | 2018-01-10 00:57:03 | 7955980ae19d41f633e4b50885a98ab7 | unknown | 

    Automatic update
    ----------------------------------------------------------------------------
    osc rdiff -c 92 openSUSE:Leap:15.0/000product|lsdiff
    _multibuild
    dvd.group
    openSUSE-dvd5-dvd-x86_64.kiwi
    unsorted.yml

**Comment by adrianschroeter** [comment]
well, the timestamp of file just says that a file with this name and this content was uploaded before in OBS. We share the sources of all package instances, so it might have existed very well before and just got re-used.

You should may use the timestamp of the commit entry instead?

**Comment by lnussel** [comment]
I thought mtime refers to modification time :) It's confusing but if that is the expected behavior, fine with me. Now that I know it I can handle it.
