### ISSUE TITLE
[webui] request role addition does not show who would get the permission

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#4375]
Sample request: https://build.opensuse.org/request/show/567466

This request was created using:
> osc requestmaintainership Novell:NTS:Unstable group:factory-maintainers

Most likely the webui does not consider that I could ask for permission for a group to a project - and consequently cant find out who would get access

**Comment by bgeuken** [comment]
AFAIK this got fixed with #4732 :smiley:
