### ISSUE TITLE
Arch_Extra nothing provides libidn2

### ISSUE THREAD

**Issue by rickrich** [openSUSE/open-build-service#4382]
Since approximately Nov, 2017 I get:

     "unresolvable Arch_Extra nothing provides libidn2"

Link is: https://build.opensuse.org/package/show/home:rickrich:gnome-manual-duplex/gnome-manual-duplex#

It used to work for all three repositories Debian, Redhat, and Arch.

**Comment by hennevogel** [comment]
Please do not report problems with content in specific instances here. We use github only for development. If you need something from the openSUSE folks, tell them that at
opensuse-buildservice+subscribe@opensuse.org or admin@opensuse.org

http://openbuildservice.org/support/
