### ISSUE TITLE
External ID doesn't get created by Cloud Upload feature

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#4393]
When I click the `Cloud Upload` link on OBS, there is no external id created for my user.

![screenshot at 2018-01-23 13-12-27](https://user-images.githubusercontent.com/8287131/35275238-62262dd0-003f-11e8-84cb-7f6398fe2391.png)

**Comment by Ana06** [comment]
@mschnitzer what do you mean with _external id created for my user_? 🤔
