### ISSUE TITLE
SourceController#delete_package Mysql2::Error: Deadlock found

### ISSUE THREAD

**Issue by evanrolfe** [openSUSE/open-build-service#4394]
Issue/Feature description
====================
The following error gets raised sometimes on production when SourceController#delete_package is called:

```
Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction: DELETE FROM `package_issues` WHERE `package_issues`.`package_id` = 2927514
```

Expected result
============
Either the request handles a deadlock gracefully or we do not lock the package_issues table at all in the first place.

How to Reproduce
===============
https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a6740b0c5e14a000661a8d9

Further information
===============
This is where the error is being raised:
https://github.com/openSUSE/open-build-service/blob/master/src/api/app/controllers/source_controller.rb#L269

**Comment by vpereira** [comment]
hi we aren't seeing it in production anymore. If you see it happening again, please feel free to re-open it!

thank you!
