### ISSUE TITLE
[production][distributions#show] undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by evanrolfe** [openSUSE/open-build-service#4403]
distributions#show threw this 26 times
<pre>
undefined method `[]&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/project/dashboard/openSUSE:Leap:42.2](https://build.opensuse.org/project/dashboard/openSUSE:Leap:42.2)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a466951dfd75b00140b6731)

**Comment by mschnitzer** [comment]
@evanrolfe  This is not a bug in the frontend but in the OBS factory engine. It already has been reported: https://github.com/openSUSE/obs_factory/issues/105
