### ISSUE TITLE
[production][delayed_job#BsRequestActionWebuiInfosJob] undefined method `can_modify_project?' for nil:NilClass

### ISSUE THREAD

**Issue by evanrolfe** [openSUSE/open-build-service#4404]
delayed_job#BsRequestActionWebuiInfosJob threw this 11 times
<pre>
undefined method `can_modify_project?&#39; for nil:NilClass
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a6a28032aeadb0006f60554)

**Comment by hennevogel** [comment]
this does not happen anymore

**Comment by Ana06** [comment]
@hennevogel it does happen, we got this error in Errbit 1 hour ago :sob:

**Comment by hennevogel** [comment]
Okay but this problem is not for juniors as this touches authorization code...
