### ISSUE TITLE
[production][search#bs_request] wrong number of arguments (given 2, expected 3)

### ISSUE THREAD

**Issue by evanrolfe** [openSUSE/open-build-service#4406]
search#bs_request threw this 0 times
<pre>
wrong number of arguments (given 2, expected 3)
</pre>
[https://api.opensuse.org/search/request?limit=100&amp;match=%28state%5Bcontains%28%22new+review%22+%40name%29%5D%29+and+review%5B%40by_group%3D%22factory-auto%22%5D](https://api.opensuse.org/search/request?limit=100&amp;match=%28state%5Bcontains%28%22new+review%22+%40name%29%5D%29+and+review%5B%40by_group%3D%22factory-auto%22%5D)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a6a7defbdb43b000bbd3aba)

**Comment by hennevogel** [comment]
does not happen anymore
