### ISSUE TITLE
[production][request#changerequest] <status code="400">
  <summary>bad link: conflict in file gdm.spec</summary>
</status>


### ISSUE THREAD

**Issue by evanrolfe** [openSUSE/open-build-service#4408]
request#changerequest threw this 1 times
<pre>
&lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;bad link: conflict in file gdm.spec&lt;/summary&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/request/changerequest](https://build.opensuse.org/request/changerequest)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a61cbeb0c3f0b0006a14032)

**Comment by hennevogel** [comment]
Does not happen anymore...
