### ISSUE TITLE
MQ events for accepted/declined reviews and review-related state changes

### ISSUE THREAD

**Issue by peti** [openSUSE/open-build-service#4413]
It would be great if OBS could generate an MQ event for every submitted review. Currently, we have `obs.request.review_wanted`, but there's no equivalent event to receive when those requested reviews come in.

Furthermore, it would be great if the `obs.request.state_change` event could be generated when a request goes from REVIEW state into NEW, i.e. when all requested reviews have been submitted.

Both of these events are useful for monitoring a set of maintenance or release requests that need to be accepted as quickly as possible.

**Comment by adrianschroeter** [comment]
This is a bug and regression, and in current sprint ;)

 https://trello.com/c/v1vd3EI4/686-p11-5-notifications-for-request-state-was-changed-do-not-seem-to-work

**Comment by coolo** [comment]
note that this issue is about more: also review state changes - you don't want a mail for that (especially if you have tons of bots as reviewers :), but other bots want to digest the MQ event

**Comment by coolo** [comment]
Generating the event isn't hard, but refactoring the code that handles reviews to be sane will be a tough ride
