### ISSUE TITLE
feature request: Show GnuPG fingerprint of package signing keys in OBS

### ISSUE THREAD

**Issue by jowagner** [openSUSE/open-build-service#4419]
(Posting here as openFATE says "There are currently no products open for new features." when trying to create a new feature request.)

Issue/Feature description
====================

According to https://lists.opensuse.org/opensuse-announce/2008-01/msg00010.html , the new signing keys for packages are auto-generated by the build service and users are told to check on http://build.opensuse.org whether they want to trust the project.

However, the name of a project is not sufficient to verify a key. The fingerprint needs to be checked by the user (or signed by another trusted GnuPG user). 

Expected result
============

The OBS should display the key ID and full fingerprint, for example on the "Overview" or on a new tab "Keys". If creating a new tab it could also show the full public key and provide key management functionality for the project owner.

When googling the key ID or fingerprint, the project page on the build service site should be one of the top results.

How to Reproduce
===============

1. Try to add http://download.opensuse.org/repositories/mozilla/openSUSE_Leap_42.3/ as a repository to OpenSUSE Leap 42.3
2. YaST2 warns about an untrusted GnuPG key
3. Google the key ID
4. Find a forum post pointing to the opensuse announcement linked above
5. Try to find the key fingerprint on https://build.opensuse.org/project/show/mozilla

Further information
===============
* https://build.opensuse.org/project/show/mozilla

**Comment by hennevogel** [comment]
The functionality is there...

![screenshot from 2018-02-05 16-13-17](https://user-images.githubusercontent.com/514785/35811844-cee986c4-0a8f-11e8-8116-6f2453543758.png)

**Comment by jowagner** [comment]
The google cache item from the 13th of January confirms that the link was there. No idea why I didn't see it. However, it would still be better if the link would work without javascript. Search engines try to follow for example https://build.opensuse.org/projects/mozilla/public_key/key_dialog but this gives 404 Not Found.

**Comment by hennevogel** [comment]
I agree that it would be an improvement if this would be accessible for search engines. Can you open a new issue about this please? Thanks

**Comment by jowagner** [comment]
Yes, but not before Wednesday. - JJ

**Comment by hennevogel** [comment]
That's quite alright JJ. Thank you!

**Comment by jowagner** [comment]
Today, the link is gone again:
![obs-mozilla-overview-without-gpg-key](https://user-images.githubusercontent.com/5215253/35913617-2e0d4730-0bf8-11e8-94b2-0536629d5e39.png)

**Comment by jowagner** [comment]
What's your preference on changing issue titles? May I change it to
  
  "GPG key / certificate link sporadically missing on OBS project overview tab" ?

The fingerprint visibility is now better covered by issue #4457.
