### ISSUE TITLE
[production][main#index] <status code="400">
  <summary>projid 'home:_ch3rub' is illegal</summary>
</status>


### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#4429]
main#index threw this 1 times
<pre>
&lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;projid &#39;home:_ch3rub&#39; is illegal&lt;/summary&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/](https://build.opensuse.org/)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a6bf3f9e48f39000bd20b35)

**Comment by mschnitzer** [comment]
This should not raise an exception.

**Comment by eduardoj** [comment]
Already checked that this isn't logged in Errbit any more in the six months. Please reopen if it happens again.

**Comment by coolo** [comment]
well, I assume _ch3rub didn't try to login since then :)
