### ISSUE TITLE
Delete depending comments?

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#4446]
For me it would make sense to delete all depending comments when the parent has been deleted. Have a look at the picture:

![cascaded_comment_deletion](https://user-images.githubusercontent.com/8287131/35795833-cd3ad5ba-0a5a-11e8-9f5c-628706d37184.png)

So if the top comment has been deleted but it has replies, we create a new comment with the `_Nobody_` user to still keep the depending comments. I'm not really a fan of this and I'd prefer to delete also all depending comments because they no longer make sense. I know some softwares that also act like that and I find it the better approach.

**Comment by hennevogel** [comment]
> I'm not really a fan of this

Sorry but your argument has to be better than this.

The reason to do it this way was that we wanted emulate a technical mailing list instead of *social* comments. It's also a matter of protecting against abuse.

1. I post a negative comment
2. You reply
3. I delete my initial comment
4. I post the negative comment again
5. GOTO 1

**Comment by Ana06** [comment]
@mschnitzer 

> For me it would make sense to delete all depending comments when the parent has been deleted

why? the other comments are not deleted, I would leave it exactly as it is.

**Comment by bgeuken** [comment]
> mschnitzer commented
>
> I'm not really a fan of this and I'd prefer to delete also all depending comments because they no longer make sense. 

That depends. It can well be that there was a follow up discussion that provides valuable information.

**Comment by bgeuken** [comment]
Let's keep this as is.
