### ISSUE TITLE
Search via title does not work

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#4451]
Issue description
====================

Searching for a package title doesn't seem to work.

Expected result
============

I can find packages via their title.

How to Reproduce
===============
1. Create a package and set a title
2. Search for the title (enable the title checkbox and search)
=> The package is not shown in the search result

Further information
===============
* Found while testing #4133 (happens with and without the code from the PR)

**Comment by bgeuken** [comment]
I am surprised that this is a feature. Isn't that what the 'title' checkbox is used for?

**Comment by hennevogel** [comment]
maybe ;-)
