### ISSUE TITLE
feature request: make GPG key fingerprint visible to search engines

### ISSUE THREAD

**Issue by jowagner** [openSUSE/open-build-service#4457]
Issue/Feature description
====================

The GPG key fingerprint of an OBS project is only accessible through a JavaScript link. The link that search engines see results in 404 Not Found. 

Expected result
============

The link should also work without JavaScript so that search engines will index the fingerprints. Users who want to verify the fingerprint when displayed in a package manager as an untrusted key are likely to google the key to see whether it is listed on trusted websites.

The easiest fix imho is to include the key fingerprint in the overview tab. The pop up window can then stay as it is. (The other information in it is unlikely to be used as a search query.)

How to Reproduce
===============

Load the page from the google search page cache and find the link with ctrl+f GPG Key. (Without css and javascript, this is a bit difficult to find.) Hover over the link to check its destination and try to follow it.

Further information
===============
* https://build.opensuse.org/project/show/mozilla

Issue #4419 indicates that whether or not the link is displayed for the same project may change from day to day.

**Comment by jowagner** [comment]
Issue #4598 indicates that whether or not the link is displayed depends on the role of the user logged in.

**Comment by CoderJolly** [comment]
Can someone pls give a little more understanding or insight regarding this issue ?

**Comment by hennevogel** [comment]
@CoderJolly maybe you can tell us what exactly you do not understand?

**Comment by dmarcoux** [comment]
With the PR #9156 merged, this isn't an issue anymore. The GPG key fingerprint is on its own page now.
