### ISSUE TITLE
Project status view thinks file conflicts happen since Unix Epoch

### ISSUE THREAD

**Issue by saschpe** [openSUSE/open-build-service#446]
For example https://build.opensuse.org/project/status?utf8=%E2%9C%93&project=openSUSE%3AFactory&filter_devel=devel%3Alanguages%3Apython&limit_to_fails=false&include_versions=false&include_versions=true&commit=Filter+results has:

" OpenLP 	devel:languages:python 	Different changes in devel project (since almost 44 years)
conflict in file OpenLP.changes"

44 years ago :-)

**Comment by bgeuken** [comment]
I checked some of the projects. All the timestamps seem to be sane so I assume this got fixed meanwhile.

Please reopen if this still appears somewhere.
