### ISSUE TITLE
Email notifications arrive 20 hours late

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#4473]
```
Received: by api.opensuse.org (Postfix, from userid 30)
	id 1924936DD6; Fri,  9 Feb 2018 04:04:20 +0000 (UTC)
Date: Thu, 08 Feb 2018 07:53:17 +0000
```

**Comment by coolo** [comment]
```
Received: by api.opensuse.org (Postfix, from userid 30)
	id 3A5D436DD6; Fri,  9 Feb 2018 08:31:19 +0000 (UTC)
Date: Thu, 08 Feb 2018 08:54:09 +0000
```

**Comment by evanrolfe** [comment]
I'm looking into this..

**Comment by coolo** [comment]
As @bgeuken implied this was a ruby 2.5 regression yesterday, I looked back into my inbox

Fine on wednesday night:
```
Received: by api.opensuse.org (Postfix, from userid 30)
	id E4E0336DD5; Wed,  7 Feb 2018 22:40:19 +0000 (UTC)
Date: Wed, 07 Feb 2018 22:40:15 +0000
```

Already heavily dealyed on thursday morning - just unnoticed at that point:

```
Received: by api.opensuse.org (Postfix, from userid 30)
	id 5306836DD6; Thu,  8 Feb 2018 10:23:36 +0000 (UTC)
Date: Thu, 08 Feb 2018 00:53:40 +0000
```

**Comment by bgeuken** [comment]
Thanks for clarifying.

Deployment of ruby2.5 was yesterday at 1:15pm CET

**Comment by bgeuken** [comment]
Related PRs: #4476 #4474

**Comment by bgeuken** [comment]
We've applied #4479 now to build.opensuse.org and the queue is decreasing now slowly. A rough guess is that in about 10 hours all scheduled jobs are processed and mails got send.

**Comment by bgeuken** [comment]
The send mail queue is empty now. Closing.
