### ISSUE TITLE
failing branches not rolled back

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/open-build-service#448]
https://build.suse.de/project/monitor/Devel:Cloud:mingw32
shows a "mingw32-cross-gcc-c++" package in "broken" state since I did
iosc branch openSUSE.org:windows:mingw:win32 mingw32-cross-gcc-c++ Devel:Cloud:mingw32

where the source package was not existing.
I tried
osc rdelete Devel:Cloud:mingw32 mingw32-cross-gcc-c++
and ctrl-shift-r to flush cache
but it remains there even after a day.

**Comment by mdeniz** [comment]
Ping! Is this issue still valid?

**Comment by bmwiedemann** [comment]
Seems to be good now.
I was able to delete the broken package now and also it did not create a new (broken) package with the branch command.
