### ISSUE TITLE
API+Webui Merge

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#450]
### Affiance - Bind what belongs together.
- [x] Merge Coolos hackweek progress into master
- [x] Document what changes for OBS admins and hackers. Especially where all the config options are now & where they could be before. The new structure of the app, how to hack on and how to test it.
- [x] Deploy master to build-test.opensuse.org and pound on it
- [x] Make a milestone release
- [x] Inform the OBS admins we know about the change, ask them to help
### Marriage - Conflate what belongs together.
- [x] Organize a test coverage sprint so we can be sure that nothing breaks when we merge.
- [x] Re-factor all WEBUI controllers to use API models
- [x] Get rid of all the WEBUI models, moving things we need into the API models.
- [x] Setup a standardized authorization system
- [x] Merge WEBUI/API login
### Honeymoon - Enjoy together.
- [ ] Come up with a new layout for the HTML views. One that's using an mobile first front-end framework (most likely getbootstrap.com) and a design pattern library (most likely pattern-lab.info)
- [ ] Get rid of the sub-domains (build.o.o, api.o.o) for the reference server and maybe even version the API (something like /api/v2/about)

**Comment by mdeniz** [comment]
This is issue is almost outdated.., we are facing those leftovers in a "close" future maybe 😄
