### ISSUE TITLE
Commenting leads to error 500 crash atm

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#4522]
Issue/Feature description
====================

Creating any comment leads to an error 500 atm.  Also further operations creating notifications are breaking now.
(Lot's of SSL related errors in errbit)

Expected result
============

Comment created

How to Reproduce
===============
1.Try to create a comment in your home project

**Comment by adrianschroeter** [comment]
Rabbit-MQ support is disabled for now to avoid this error.

**Comment by hennevogel** [comment]
And enabled again. I'll create a card in the backlock for better recovery.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RabbitMQ Connection Recovery](https://trello.com/c/idaIsuAO/1333-rabbitmq-connection-recovery)
