### ISSUE TITLE
Not possible to download rpmlint.log file

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#4548]
Issue/Feature description
====================
IIRC it was possible to download the rpmlint.log file in the past (otherwise it would be useless to be in the binaries list)
https://build.opensuse.org/package/binaries/OBS:Server:Unstable/obs-server?repository=SLE_12_SP3

I assume it got introduced by https://github.com/openSUSE/open-build-service/pull/4458

Expected result
============
There is a download link for the rpmlint.log

How to Reproduce
===============
1. Go to e.g. https://build.opensuse.org/package/binaries/OBS:Server:Unstable/obs-server?repository=SLE_12_SP3
2. Download link for rpmlint log is missing

**Comment by ChrisBr** [comment]
After talking with @mdeniz, this was like already not possible before the refactoring.
I think we should either drop the rpmlint.log then or make it possible to download!

@adrianschroeter is there a reason why it is not possible to download the rpmlint.log?

**Comment by adrianschroeter** [comment]
On Donnerstag, 22. Februar 2018, 10:39:44 CET wrote Christian Bruckmayer:
> Issue/Feature description
> ====================
> IIRC it was possible to download the rpmlint.log file in the past (otherwise it would be useless to be in the binaries list)
> https://build.opensuse.org/package/binaries/OBS:Server:Unstable/obs-server?repository=SLE_12_SP3
> 
> I assume it got introduced by https://github.com/openSUSE/open-build-service/pull/4458

Not sure if that is a regression, but there is no need not to allow it. rpmlint.log files are usually small
(even smaller then the build log)

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany
