### ISSUE TITLE
Can't mark text in source files in Firefox

### ISSUE THREAD

**Issue by jonsger** [openSUSE/open-build-service#4549]
Issue/Feature description
====================
When I wanted to mark text in the source file (e.g. spec files) viewer of OBS within Firefox, that doesn't work. The marked text doesn't go into the "copy buffer" of your middle mouse key.

Expected result
============
The marked text should go into your "copy buffer" as it's the case in Chromium.

How to Reproduce
===============
1. Launch Firefox
2. Open the source viewer of OBS package (e.g. https://build.opensuse.org/package/view_file/openSUSE:Leap:15.0/hello/hello.spec?expand=1)
3. Mark text in the source view section
4. Click to some text accepting field, like your terminal or a new tab in Firefox, with your middle mouse key (scroll wheel)

Further information
===============
* https://build.opensuse.org is used
* Firefox 58.0.2 on openSUSE Tumbleweed
* This works as intended in Chromium 64.0 on openSUSE Tumbleweed

**Comment by hennevogel** [comment]
If you have problems with firefox on some specific page, talk to the firefox maintainer. There is nothing we can do about firefox.

**Comment by jonsger** [comment]
This issue is still around. Even in the new editor which is part of the public beta.

@hennevogel How can you be sure that this is a problem of Firefox? Copy & Paste with middle mouse click works always in Firefox, even on OBS. The only exception is the source viewer.
