### ISSUE TITLE
Arch Core, Arch Extra and Arch Community are not different versions of Arch Linux

### ISSUE THREAD

**Issue by gojpdchx** [openSUSE/open-build-service#4559]
Issue description
====================
Page affected: `https://build.opensuse.org/project/add_repository_from_default_list/project_name_here`

On the "Add Repositories to <project name>" page, Arch Core, Arch Extra and Arch Community are listed as different "versions" of Arch Linux.

On the same page, other Linux distributions such as Ubuntu, Fedora and openSUSE are fine because they have different versions:
Ubuntu: 16.04, 16.10, 17.04 ...
Fedora: 25, 26, 27, Rawhide
openSUSE: Leap 42.2, Leap 42.3, Tumbleweed ...

However, Arch Linux uses a rolling release model. It does not have a version.
In addition, `[core]`, `[extra]` and `[community]` are the binary repositories of Arch Linux.

Expected result
============
Combine the three checkboxes (Arch Core, Arch Extra and Arch Community) into a single one called "Arch Linux".
When a user wants to build on Arch Linux, he/she only need to check a single checkbox, just like other distributions (openSUSE, Fedora, etc.). The three repositories should then be enabled.

How to Reproduce
===============
1. Create a new project / Go to an existing project homepage
2. Click on the "Repositories" tab
3. Click "Add repositories"
4. Note the presence of three checkboxes for Arch Core, Arch Extra and Arch Community.

Further information
===============
The aforementioned issue can be reproduced on `https://build.opensuse.org/`.

**Comment by adrianschroeter** [comment]
you still want to have a choice whom to trust IMHO. So, you want to be able to select core only or include more repos. And we have only the version mechanism here..

Keep in mind that any contributor in these repos there can have an influence on your package build. If he is evil on purpose he is even most likely to sneak in via the right provides, even you don't have "buildrequired" his package.

So, I see no solution here. Feel free to use always the community repo if you don't care.
