### ISSUE TITLE
Why do we have an AUTHORS file?

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#4568]
Why do the have an AUTHORS file? It has 66 entries, but OBS has 132 contributors... Is it used? Should we update it? :confused:

**Comment by adrianschroeter** [comment]
On Freitag, 23. Februar 2018, 16:37:33 CET wrote Ana María Martínez Gómez:
> Why do the have an AUTHORS file? It has 66 entries, but OBS has 132 contributors... Is it used? Should we updated? :confused: 

We could use for listing the contributors classified, eg. active main contributors, former main contributors,
thanks to companies or one-time contributors providing a larger piece.

Or we can drop, no strong opinion here.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by Ana06** [comment]
If there is no any important reason to use it, I would personally drop it. All our contributors are important, I don't like to classify them. :green_heart: But the Author file is some in some places in the code. :thinking: 

@openSUSE/open-build-service what do you think?

**Comment by bgeuken** [comment]
I think / guess this is identical to a contributors list. It's just not up to date.

I am also against distinguishing between types of contribution.

**Comment by Ana06** [comment]
@bgeuken 

> I think / guess this is identical to a contributors list. It's just not up to date.

Why do we need to duplicate it? can we then remove it?

**Comment by eduardoj** [comment]
As far as i know the AUTHORS file should contain all the contributors to the code.

If it is not updated I prefer not to have it.

My only concern would be that removing that file could remove some contributor to the code that doesn't appear as a commiter in the commit log. I'm thinking in the case of first committers to the repo, befor it was moved to github.

**Comment by Ana06** [comment]
@eduardoj 

> If it is not updated I prefer not to have it.

even if it was updated, I do not want to keep it updated.

> My only concern would be that removing that file could remove some contributor to the code that doesn't appear as a commiter in the commit log. I'm thinking in the case of first committers to the repo, before it was moved to github.

That's right. This file was introduced on 5th Nov, it has while Github say by this time there were only 35 contributors. But the problem is that this was added with `Added AUTHORS file as another step to propper licensing.` and I doubt this is correct. It doesn't say what code every of this persons wrote. We don't even know if they wrote any code. Or it could be that it has been completely deleted for example. There is one user: `tux <tux@einherjer.suse.de>`, it has no name, only a suse email, I doubt it is possible to find out who he is...

**Comment by eduardoj** [comment]
@Ana06 

> This file was introduced on 5th Nov, it has while Github say by this time there were only 35 contributors.

Sorry. What do you mean?

**Comment by Ana06** [comment]
@eduardoj 

> Sorry. What do you mean?

What a mess! :see_no_evil: 

This file was introduced on 5th Nov. It has 66 entries, while Github say that by this time there were only 35 contributors.

clear now? :smile:

**Comment by eduardoj** [comment]
@Ana06 

> clear now? :smile:

Much better. :+1:

> This file was introduced on 5th Nov.

Well, the file was introduced on 5th Nov 2010, with 54 contributors. By that time there were 35 contributors, having a look at Github. So it seems that from the beginning there were some contributors not included in the commits in git, added to the AUTHORS file.

I repeat mysefl: my only concern would be that removing that file could remove some contributor to the code that doesn't appear as a commiter in the commit log.

**Comment by Ana06** [comment]
@openSUSE/open-build-service what should we then do with the Authors file? :thinking:

**Comment by hennevogel** [comment]
just drop it
