### ISSUE TITLE
Provide notification option for project/package comments for bugowners

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/open-build-service#4590]
Issue/Feature description
====================

On `/user/notifications` `bugowner` can be set for some:

![image](https://user-images.githubusercontent.com/22943929/36766461-9beeb60e-1bfb-11e8-8b68-99c69da1edfc.png)

but not for project/package comments:

![image](https://user-images.githubusercontent.com/22943929/36766452-94f71c56-1bfb-11e8-9929-1e265ef7caf2.png)

Expected result
============

Desired that `bugowner` be an option for project/package comments.

Further information
===============

This is primarily of use for IBS in which only `bugowners` are set for SLE packages and there is not the concept of devel projects. The `repo-checker` thus posts comments directly on the packages, but short of including a reference to all `bugowner` users the notifications are never sent.

**Comment by coolo** [comment]
Implemented as https://github.com/openSUSE/open-build-service/pull/5819
