### ISSUE TITLE
Split number of requests into incoming/outgoing

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#4602]
As a maintainer of larger projects, like GNOME:Factory, the number of 'open requests' can become increasingly large, which in itself is not alarming.

This is, for example, a moment view into openSUSE:Factory:
![screenshot from 2018-03-01 12-31-32](https://user-images.githubusercontent.com/532559/36843717-113de20e-1d50-11e8-8733-df745bc8883b.png)

It would be helpful if the number of open requests could be split into how many are incoming (those are usually things the project maintainer have to worry for, to make things moving) and outgoing (somebody else has to review/accept them, I merely need to monitor them for declines/comments)

**Comment by jesus-montano** [comment]
can I check this Issue?

**Comment by dmarcoux** [comment]
> can I check this Issue?

@jesus-montano, sure go ahead. Let us know if you need help.

**Comment by jesus-montano** [comment]
I was doing Research in the application and in the code, but I haven't understood how to create requests, and how or where was display the alert example, someone can orient me about how create requests?

**Comment by jesus-montano** [comment]
how can I modify the frontend because in the repository that I watched only was API and backend?

**Comment by dmarcoux** [comment]
Everything under [src/api](https://github.com/openSUSE/open-build-service/tree/master/src/api) is the frontend application, which is a Rails application in front of a Perl application located under [src/backend](https://github.com/openSUSE/open-build-service/tree/master/src/backend) referred to as the backend.

Excerpt from the [README.md](https://github.com/openSUSE/open-build-service/blob/master/README.md) file

>The backend implements all the core functionality (i.e. building packages). The frontend provides a web application and XML API for interacting with the backend

Be sure to go through the [CONTRIBUTING.md](https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md) file to know how to contribute. It helps new contributors from all levels.

**Comment by jesus-montano** [comment]
Thank you I will review it
