### ISSUE TITLE
API for appliances

### ISSUE THREAD

**Issue by hellcp** [openSUSE/open-build-service#4605]
Issue/Feature description
====================
The same way distributions have their API for getting binaries, appliances should also have that possibility.

Expected result
============
Appliances get set of types of images and are made into XML file as well as particular built binaries get their XML for all available images (just like distro/app binaries)

How to Reproduce
===============
Can't reproduce something that doesn't yet exist ;)

How distro/apps do it
https://api.opensuse.org/public/distributions
https://api.opensuse.org/search/published/binary/id?match=project=%27openSUSE%3ATools%27+and+name=%27osc

Further information
===============
It would make it much easier for software-o-o to show all the binaries instead of relying on flawed method:
https://github.com/openSUSE/software-o-o/blob/master/app/controllers/download_controller.rb#L10

**Comment by hennevogel** [comment]
`/image_templates` exists by now
