### ISSUE TITLE
POST _buildinfo ignores BuildConflicts

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/open-build-service#4609]
POSTing a specfile with _buildinfo gives different result than GET with the same spec file on the server.

$ osc buildinfo openSUSE:Factory java-1_8_0-openjdk standard x86_64 | grep java- 
<buildinfo project="openSUSE:Factory" repository="standard" package="java-1_8_0-openjdk" downloadurl="http://download.opensuse.org/repositories">
  <specfile>java-1_8_0-openjdk.spec</specfile>
  <file>java-1_8_0-openjdk.spec</file>
  <subpack>java-1_8_0-openjdk</subpack>
  <subpack>java-1_8_0-openjdk-accessibility</subpack>
  <subpack>java-1_8_0-openjdk-debuginfo</subpack>
  <subpack>java-1_8_0-openjdk-debugsource</subpack>
  <subpack>java-1_8_0-openjdk-demo</subpack>
  <subpack>java-1_8_0-openjdk-demo-debuginfo</subpack>
  <subpack>java-1_8_0-openjdk-devel</subpack>
  <subpack>java-1_8_0-openjdk-devel-debuginfo</subpack>
  <subpack>java-1_8_0-openjdk-headless</subpack>
  <subpack>java-1_8_0-openjdk-headless-debuginfo</subpack>
  <subpack>java-1_8_0-openjdk-javadoc</subpack>
  <subpack>java-1_8_0-openjdk-src</subpack>
  <bdep name="java-1_8_0-openjdk-devel" version="1.8.0.161" release="1.1" arch="x86_64" project="openSUSE:Factory" repository="standard" />
  <bdep name="java-1_8_0-openjdk" version="1.8.0.161" release="1.1" arch="x86_64" project="openSUSE:Factory" repository="standard" />
  <bdep name="java-1_8_0-openjdk-headless" version="1.8.0.161" release="1.1" arch="x86_64" project="openSUSE:Factory" repository="standard" />
$ osc buildinfo openSUSE:Factory java-1_8_0-openjdk standard x86_64 java-1_8_0-openjdk.spec | grep java- 
<buildinfo project="openSUSE:Factory" repository="standard" package="java-1_8_0-openjdk" downloadurl="http://download.opensuse.org/repositories">
  <subpack>java-1_8_0-openjdk</subpack>
  <subpack>java-1_8_0-openjdk-accessibility</subpack>
  <subpack>java-1_8_0-openjdk-demo</subpack>
  <subpack>java-1_8_0-openjdk-devel</subpack>
  <subpack>java-1_8_0-openjdk-headless</subpack>
  <subpack>java-1_8_0-openjdk-javadoc</subpack>
  <subpack>java-1_8_0-openjdk-src</subpack>
  <bdep name="java-10-openjdk-devel" version="10.0.0.0~45" release="1.1" arch="x86_64" project="openSUSE:Factory" repository="standard" />
  <bdep name="java-10-openjdk" version="10.0.0.0~45" release="1.1" arch="x86_64" project="openSUSE:Factory" repository="standard" />
  <bdep name="java-10-openjdk-headless" version="10.0.0.0~45" release="1.1" arch="x86_64" project="openSUSE:Factory" repository="standard" />

**Comment by mlschroe** [comment]
Fixed with commit 35d00717607ea1b47ed6b97c9614f948404ccdc7
