### ISSUE TITLE
Results grid styling is off when searching through all projects

### ISSUE THREAD

**Issue by savornicesei** [openSUSE/open-build-service#4610]
Hi all,

Issue/Feature description
====================
Results table with "Include home projects" option extends the screen and an horizontal scroll bar is displayed even if there's no long project  name. 

Expected result
============
Results table should not break page styling and show horizontal scroll bar.

How to Reproduce
=============== 
2. Go to [https://build.opensuse.org](https://build.opensuse.org) using Firefox 52.6, 64-bit on an OpenSUSE Leap 42.3
3. search for "mono"
4. The results grid looks fine (the css width property for html table with id: projects_table is 921px
5. Click on "Include home projects"
6. You're redirected to [https://build.opensuse.org/project?show_all=true](https://build.opensuse.org/project?show_all=true)
7. Check the results table. It now extends beyond th right margin of the screen; horizontal scroll bar is shown. The width of the HTML table with id: projects_table is now 1524px. 

Best,
Simo

![obs_bad](https://user-images.githubusercontent.com/917232/36950170-c5ea6bf8-1ffa-11e8-992a-6afe08c67848.png)
![obs_good](https://user-images.githubusercontent.com/917232/36950171-c61246f0-1ffa-11e8-9fcf-9818c1836a88.png)

**Comment by eduardoj** [comment]
After switching to the new web UI this doesn't happen any more. Closing.

![Peek 2020-02-14 16-27_search_projects](https://user-images.githubusercontent.com/24919/74544313-39402980-4f47-11ea-8119-e3038b5ecc4b.gif)
