### ISSUE TITLE
live build log repeats logs instead of appending linearly

### ISSUE THREAD

**Issue by etam** [openSUSE/open-build-service#4625]
Issue/Feature description
====================
Live build log, when updating appends parts of logs, that were already displayed. This makes the web page grow rapidly.

Expected result
============
Live build log should be updated linearly.

How to Reproduce
===============
Watch any live build log on build.opensuse.org

**Comment by hennevogel** [comment]
hey @etam can you elaborate what you mean? That the log is appended to the bottom of the page is on purpose. The reason to do this is that most people want to search the log afterward (for a failure or whatnot).

**Comment by coolo** [comment]
Henne, look at a live build log linked from /monitor - it looks like the last 2K of the log are constantly appended. So it does move, but it repeats lines *a lot*.

**Comment by adrianschroeter** [comment]
yep, given that it does not happen with osc points to the webui instead of worker.

**Comment by mlschroe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Live build log repeats logs instead of appending linearly](https://trello.com/c/uAxuTjVZ/1342-live-build-log-repeats-logs-instead-of-appending-linearly)
