### ISSUE TITLE
OBS 2.8 is unable to resolve dependencies between packages built in OBS for Ubuntu 18.04 builds

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/open-build-service#4643]
Issue description
====================
I'm trying to do package builds with my internal OBS 2.8 system against Ubuntu 18.04.

We have our setup such that we have an `Internal:BuildRoot` project that provides a few packages that our packages can depend on at build-time. The project doesn't publish, but it is set up to be usable for build roots so that useful sets of macros and such are available.

In dependent projects that need packages from here, we do something like this:

```xml
  <repository name="xUbuntu_18.04">
    <path project="Internal:BuildRoot" repository="xUbuntu_18.04"/>
    <path project="openSUSE.org:Ubuntu:debbuild" repository="Ubuntu_18.04"/>
    <path project="openSUSE.org:Ubuntu:18.04" repository="universe"/>
    <arch>x86_64</arch>
  </repository>
```

For every other distribution, this results in when a spec file requires one of the packages in there, it is able to successfully resolve it and start the build. However, when we're targeting Ubuntu 18.04, I get the following from the OBS resolver instead: `nothing provides packager-env`. The `packager-env` is a virtual name provided by a package called `packager-env-obs`, and in other distribution targets, this works.

The failure also affects `osc build`, presumably because it relies on the OBS service to define the build root in the `buildinfo`...

Expected result
============
The package requesting the buildroot-only Ubuntu 18.04 packages build successfully.

How to Reproduce
===============
1. Set up a project that has packages that are set to not be published but are usable for builds for Ubuntu 18.04
2. Set up another project that pulls it in through the meta for the Ubuntu 18.04 target
3. Push a package into the dependent project that requires a package from the first project, and see it mark it as unresolvable

Further information
===============
* OBS server package version: `2.8.4-4.31`

**Comment by Conan-Kudo** [comment]
Actually, this is much worse than I feared. OBS 2.8 can't resolve dependencies between packages it has built in even the same project for Ubuntu 18.04!

**Comment by adrianschroeter** [comment]
yes, OBS 2.8 is not support the new package format. Please use OBS 2.9 for Ubuntu 18.04.
