### ISSUE TITLE
Basic auth dialog in webui

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#4649]
Issue description
====================

In the last days I got a couple of times a basic auth popup in OBS.
I don't remember what I was doing when this occured before. This time I was editing the xml file of an image and pressed the save button when suddenly a authentication dialog appeared.
After I reloaded the page I was logged out.

Expected result
============

I do not get logged out and I don't get this doalog.

How to Reproduce
===============

I don't know :confused: 

![basic_auth_error](https://user-images.githubusercontent.com/968949/37398512-1857d05c-277f-11e8-8d7f-c47709d81106.png)

**Comment by hennevogel** [comment]
CSRF protection somehwere? Next time, save the logs from that day :nerd_face:

**Comment by bgeuken** [comment]
After I opened this issue I have not seen this anymore. Before it happened a couple of times during the week :confused: 

Anyway, if it happens again we can reopen this
