### ISSUE TITLE
README.UPDATERS has no mention of ./script/migrate_devel_projects

### ISSUE THREAD

**Issue by srinidhibs** [openSUSE/open-build-service#465]
A new script was added in 2.3 release called ./script/migrate_devel_projects, but there was no mention of this in either ReleaseNotes or README.UPDATERS.

While assisting a fellow OBS admin on IRC, I found this new migration in 2.4 release:

``` ruby
$ cat src/api/db/migrate/20120407173644_remove_devel_project.rb
class RemoveDevelProject < ActiveRecord::Migration
  class DbPackage < ActiveRecord::Base; end
  def up
    packs = DbPackage.where("develproject_id is not null").all

    unless packs.empty?
      puts packs.inspect
      raise "Migrate to 2.3 first and run ./script/migrate_devel_projects"
    end

    execute("alter table db_packages drop FOREIGN KEY db_packages_ibfk_2")
    remove_column :db_packages, :develproject_id

  end

  def down
  end
end
```

Now, if an admin has already updated from OBS 2.3 to OBS 2.4, how will the admin go back to 2.3 in order to run that script. I understand that this check might be put in place if someone is upgrading their API from 2.2 or older version, directly to 2.4. But, IMO, it still must be mentioned in README.UPDATERS.

**Comment by mdeniz** [comment]
Closing this old issue, if still valid please reopen it
