### ISSUE TITLE
libieee.a not found on ARM OpenSUSE projects

### ISSUE THREAD

**Issue by highperformancecoder** [openSUSE/open-build-service#4687]
Issue/Feature description
====================
Recent ARM builds of openSUSE_Factory_ARM failing with

/usr/lib64/gcc/aarch64-suse-linux/7/../../../../aarch64-suse-linux/bin/ld: cannot find -lieee

Expected result
============

The project should build, or at very least find libieee.a, which is a standard library as part of glibc.

How to Reproduce
===============

Further information
===============
See the project https://build.opensuse.org/package/live_build_log/home:hpcoder1/ecolab/openSUSE_Factory_ARM/aarch64

**Comment by coolo** [comment]
this is a problem of the arm port not of the build service (most likely at least). So please email either https://lists.opensuse.org/opensuse-arm/ or https://lists.opensuse.org/opensuse-packaging/
