### ISSUE TITLE
Diff expansion fails sometimes

### ISSUE THREAD

**Issue by saschpe** [openSUSE/open-build-service#470]
https://build.opensuse.org/request/show/206505 the patch file shows both "+" and "-" and expansion/collapsing is broken. I strongly assume the hash in <a ..id="collapse__0001-QDeclarativeRepeaterCrashFix_kde#311871_patch_diff_action_0_maintenance_release_0_2" collides with http://www.w3.org/TR/html401/types.html#type-name

**Comment by bgeuken** [comment]
To me this seems to be a backend issue. In backend/bs_srcserver there is a handlelinks function which produces the "conflict in file kdebase4-workspace.spec" error message.

@mlschroe @M0ses Can you have a look at this?

**Comment by adrianschroeter** [comment]
should be solved via the acceptinfo functionality (added that earlier this year). this is only fixing this for requests getting accepted since then, but should be good enough.
=> closing.

**Comment by bgeuken** [comment]
Actually I saw that recently (within the last 6 months)
