### ISSUE TITLE
regression in time to display webui "binaries" page since new layout

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/open-build-service#4736]
Since the introduction of the new layout on the binaries page (combining both details and download link for each package), it takes several seconds to load this page for packages containing a lot of subpackages. 

I noticed this on IBS / SUSE:SLE-15:GA

**Comment by ChrisBr** [comment]
The packages in questions are ``SUSE:SLE-15:GA/iptables/standard`` or ``SUSE:SLE-15:GA/gperftools/standard``

**Comment by adrianschroeter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Build result page takes long time to load](https://trello.com/c/ScRyypVQ/1385-build-result-page-takes-long-time-to-load)
