### ISSUE TITLE
[production][] undefined method `can_modify_project?' for nil:NilClass

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#4746]
This is caused because we set ``User.current = nil`` on several places.
We should always set ``User.current = User.find_nobody!`` because in the code we often assume that there is an user object.

**Comment by Ana06** [comment]
@ChrisBr 

> This is caused because we set User.current = nil on several places.
We should always set User.current = User.find_nobody! because in the code we often assume that there is an user object.

Or maybe looking for a more robust solution. Like never returning `nil` even if it is assign :thinking:

**Comment by ChrisBr** [comment]
> Or maybe looking for a more robust solution. Like never returning nil even if it is assign, similarly as how we do with current_login

Isn't that what I proposed? 
Anyway, this is nothing we should change easily as it could have a lot of side effects, especially in the API...
We already fixed a lot of these errors with the refactoring of src/api/app/jobs/bs_request_action_webui_infos_job.rb. Not sure how many of these errors are still happening but I guess not that many. So if there aren't many in Errbit anymore I'm fine with closing this one.

**Comment by Ana06** [comment]
@ChrisBr 
> Isn't that what I proposed?

Not exactly, you speak about setting it, and I about returning it... :thinking: 

> Anyway, this is nothing we should change easily as it could have a lot of side effects, especially in the API...
> We already fixed a lot of these errors with the refactoring of src/api/app/jobs/bs_request_action_webui_infos_job.rb. Not sure how many of these errors are still happening but I guess not that many. So if there aren't many in Errbit anymore I'm fine with closing this one.

You can close the issue if it is solved, but I think it is still worthwhile to change the `User.current` behaviour... :thinking:

**Comment by hennevogel** [comment]
meanwhile we set nobody in delayed jobs...
