### ISSUE TITLE
regression on patchinfo editor

### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#4764]
In the build.opensuse.org and build.suse.de, I'm not able to add new issues via the patchinfo editor.

Please use as example the following patchinfo:

https://build.opensuse.org/patchinfo/show/openSUSE:Maintenance:7951/patchinfo

Please try to add an issue. It fires a get to ``` https://build.opensuse.org/patchinfo/new_tracker?issues%5B%5D=boo%23123456``` via AJAX and it returns a 404 error.

**Comment by bgeuken** [comment]
@vpereira JFYI this should be fixed now
