### ISSUE TITLE
osc service remoterun operates on outdated sources (product builder)

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#4768]
This issue has already been discussed with @adrianschroeter, filing it here for completeness/reference

Take this setup into consideration:

openSUSE:Factory/000product (product builder, lead package)
   branched to
openSUSE:Factory:PowerPC/000product (PPC build, same product specification, minor adjustments in the .product file and local .group files)

All (well, most) other packages in openSUSE:Factory:PowerPC are inherited through a project link

Whenever a checkin happens to openSUSE:Factory (using our staging scripts), the last steps include
* Set the version in openSUSE:Factory/000product/openSUSE.product to $date
* trigger service run of 000product in all :Ports (i.e. :ARM, :PowerPC and :zSystems)

With the new product builder, though, the 000product in e.g. :PowerPC has the service run executed but it is not taking the changes in .product of openSUSE:Factory/000product into account (meaning, the version in the kiwi files produced does not change).

**Comment by Ana06** [comment]
@DimStar77 what staging script? @adrianschroeter are you already fixing this? :confused:

**Comment by DimStar77** [comment]
> what staging script?

The tooling we use to manage the worklows (osc plugin) - http://github.com/openSUSE/opensuse-release-tools

**Comment by coolo** [comment]
services and links don't go well together in general :(

It's not so much about product file, the service is running on the sources of the package not the expanded sources (as users would expect). So before running the service you need to commit the expanded sources into :PowerPC

**Comment by coolo** [comment]
But if in any way possible, service trigger should do that

**Comment by DimStar77** [comment]
> But if in any way possible, service trigger should do that

Right - this issue is about a fix to the actual problem to behave as one would expect.

**Comment by coolo** [comment]
if I understand @mlschroe correctly, the actual change in the backend is small. But we'd need a test case.

@Ana06, can you help?

**Comment by michelmno** [comment]
From a discussion in ML https://lists.opensuse.org/opensuse-factory/2018-09/msg00020.html I understand this issue is the reason why openSUSE:Factory:PowerPC snapshot is not kept in sync with openSUSE:Factory.

When could we have a correction of this issue ?

**Comment by adrianschroeter** [comment]
On Dienstag, 11. September 2018, 09:20:24 CEST wrote Michel Normand:
> From a discussion in ML https://lists.opensuse.org/opensuse-factory/2018-09/msg00020.html I understand this issue is the reason why openSUSE:Factory:PowerPC snapshot is not kept in sync with openSUSE:Factory.
> 
> When could we have a correction of this issue ?

well, it is not "an issue", it is a design decission.

The best solution would be to maintain a product definition 
at the same place. So the "openSUSE" product files would be
maintained in one package as it belongs together.

A branch needs a manual update atm.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by coolo** [comment]
We're talking about this 'manual update' not doing what users expect: to update the service files of *expanded* sources. Instead it runs on outdated sources.

**Comment by adrianschroeter** [comment]
should be solved with https://github.com/openSUSE/open-build-service/pull/6285
