### ISSUE TITLE
bcntsynctag not working

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#4770]
bcntsynctag doesn't seem to be working, any idea here?

```
$ osc meta pkg openSUSE:Leap:15.0:Images livecd-leap-gnome
<package name="livecd-leap-gnome" project="openSUSE:Leap:15.0:Images">
  <title>openSUSE Live Images</title>
  <description>The package contains huge ISOs</description>
  <bcntsynctag>live</bcntsynctag>
</package>
$ osc meta pkg openSUSE:Leap:15.0:Images opensuse-leap-image
<package name="opensuse-leap-image" project="openSUSE:Leap:15.0:Images">
  <title/>
  <description/>
  <bcntsynctag>live</bcntsynctag>
</package>
$ osc ls -b openSUSE:Leap:15.0:Images livecd-leap-gnome
standard/x86_64
images/x86_64
 _statistics
 openSUSE-Leap-15.0-GNOME-Live-x86_64-Build11.2-Media.iso
 openSUSE-Leap-15.0-GNOME-Live-x86_64-Build11.2-Media.iso.sha256
 openSUSE-Leap-15.0-GNOME-Live-x86_64-Build11.2-Media.packages
 openSUSE-Leap-15.0-GNOME-Live-x86_64-Build11.2-Media.report
 openSUSE-Leap-15.0-GNOME-Live-x86_64-Build11.2-Media.verified
$ osc ls -b openSUSE:Leap:15.0:Images opensuse-leap-image
standard/x86_64
images/x86_64
 _statistics
 opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.docker.containerinfo
 opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.docker.obsbinlnk
 opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.docker.tar.xz
 opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.docker.tar.xz.sha256
 opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.packages
 opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.report
 opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.verified
```

**Comment by adrianschroeter** [comment]
On Donnerstag, 29. März 2018, 17:45:06 CEST wrote Ludwig Nussel:
> bcntsynctag doesn't seem to be working, any idea here?
> 
> ```
> $ osc meta pkg openSUSE:Leap:15.0:Images livecd-leap-gnome
> <package name="livecd-leap-gnome" project="openSUSE:Leap:15.0:Images">
>   <title>openSUSE Live Images</title>
>   <description>The package contains huge ISOs</description>
>   <bcntsynctag>live</bcntsynctag>
> </package>
> $ osc meta pkg openSUSE:Leap:15.0:Images opensuse-leap-image
> <package name="opensuse-leap-image" project="openSUSE:Leap:15.0:Images">
>   <title/>
>   <description/>
>   <bcntsynctag>live</bcntsynctag>
> </package>
> $ osc ls -b openSUSE:Leap:15.0:Images livecd-leap-gnome
> standard/x86_64
> images/x86_64
>  _statistics
>  openSUSE-Leap-15.0-GNOME-Live-x86_64-Build11.2-Media.iso
>  openSUSE-Leap-15.0-GNOME-Live-x86_64-Build11.2-Media.iso.sha256
>  openSUSE-Leap-15.0-GNOME-Live-x86_64-Build11.2-Media.packages
>  openSUSE-Leap-15.0-GNOME-Live-x86_64-Build11.2-Media.report
>  openSUSE-Leap-15.0-GNOME-Live-x86_64-Build11.2-Media.verified
> $ osc ls -b openSUSE:Leap:15.0:Images opensuse-leap-image
> standard/x86_64
> images/x86_64
>  _statistics
>  opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.docker.containerinfo
>  opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.docker.obsbinlnk
>  opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.docker.tar.xz
>  opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.docker.tar.xz.sha256
>  opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.packages
>  opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.report
>  opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.verified
> ```

this is no proof, since the scheduler state is also "outdated".

will keep an eye on it ...

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by adrianschroeter** [comment]
On Donnerstag, 29. März 2018, 17:57:16 CEST wrote Adrian Schröter:
> On Donnerstag, 29. März 2018, 17:45:06 CEST wrote Ludwig Nussel:
> > bcntsynctag doesn't seem to be working, any idea here?
> > 
> > ```
> > $ osc meta pkg openSUSE:Leap:15.0:Images livecd-leap-gnome
> > <package name="livecd-leap-gnome" project="openSUSE:Leap:15.0:Images">
> >   <title>openSUSE Live Images</title>
> >   <description>The package contains huge ISOs</description>
> >   <bcntsynctag>live</bcntsynctag>
> > </package>
> > $ osc meta pkg openSUSE:Leap:15.0:Images opensuse-leap-image
> > <package name="opensuse-leap-image" project="openSUSE:Leap:15.0:Images">
> >   <title/>
> >   <description/>
> >   <bcntsynctag>live</bcntsynctag>
> > </package>
> > $ osc ls -b openSUSE:Leap:15.0:Images livecd-leap-gnome
> > standard/x86_64
> > images/x86_64
> >  _statistics
> >  openSUSE-Leap-15.0-GNOME-Live-x86_64-Build11.2-Media.iso
> >  openSUSE-Leap-15.0-GNOME-Live-x86_64-Build11.2-Media.iso.sha256
> >  openSUSE-Leap-15.0-GNOME-Live-x86_64-Build11.2-Media.packages
> >  openSUSE-Leap-15.0-GNOME-Live-x86_64-Build11.2-Media.report
> >  openSUSE-Leap-15.0-GNOME-Live-x86_64-Build11.2-Media.verified
> > $ osc ls -b openSUSE:Leap:15.0:Images opensuse-leap-image
> > standard/x86_64
> > images/x86_64
> >  _statistics
> >  opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.docker.containerinfo
> >  opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.docker.obsbinlnk
> >  opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.docker.tar.xz
> >  opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.docker.tar.xz.sha256
> >  opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.packages
> >  opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.report
> >  opensuse-leap-15.0-image.x86_64-2.8.0-Build1.3.verified
> > ```
> 
> this is no proof, since the scheduler state is also "outdated".
> 
> will keep an eye on it ...

build is failed now;)

sorry, still not a proof...

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by lnussel** [comment]
yeah I tried changing the name to mixed case like the lives but that failed. back to lowercase now

**Comment by lnussel** [comment]
it's actually two different cicnt so this can't work
