### ISSUE TITLE
[webui][api] project/pulse/<projectname> empty

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#4771]
Issue/Feature description
====================
The new "pulse" tab is always empty in my OBS for all projects

Expected result
============
For example in b.o.o: https://build.opensuse.org/project/pulse/OBS:Server:Unstable

How to Reproduce
===============
1. install OBS version with support for the new project log tab
2. goto the pulse tab
3. log is empty

Further information
===============
* I am using the version which supports the "pulse" tab
* For some reason, the database TABLE `project_log_entries` in my OBS has no entries

**Comment by mmohring** [comment]
I had checked the code in the request #4498 from @hennevogel . It seems to be based on the existing code using the DB TABLE project_log_entries. Because in my OBS this table is empty, my project log is empty. In my OBS, this table also stays empty when you change a project.

**Comment by bgeuken** [comment]
@mmohring Your instance is based on the master branch, right?

**Comment by hennevogel** [comment]
> In my OBS, this table also stays empty when you change a project.

How do you change it?

**Comment by mmohring** [comment]
@bgeuken @hennevogel any news here ? Is there a trick to "activate" the logging ?

**Comment by hennevogel** [comment]
@mmohring for certain `Event`s (basically those in [event.rb](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/event.rb)) a [delayed job](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/jobs/create_project_log_entry_job.rb) is created that creates the `ProjectLogEntry` for the `Event`.

Sounds like your delayed jobs are not running or stuck?

**Comment by mmohring** [comment]
> Sounds like your delayed jobs are not running or stuck?

I see the delayed jobs are running, from the **production.log** entries. Mailer and Issue Tracker jobs are regularily called, as well as jobs with queue default and quick called.

How can I see if jobs are **stuck** ? How do I see if the delayed jobs for `ProjectLogEntry` are called ?

**Comment by hennevogel** [comment]
You can look only at those with

```ruby
Delayed::Job.where("handler like '%ProjectLogEntry%'")
```

**Comment by Ana06** [comment]
@mmohring did you manage to fix it or do we still have this issue? :thinking:

**Comment by mmohring** [comment]
@Ana06 @hennevogel I did not manage to fix it. I intent do a fresh test install to see if it happens then. It seems that in some very rare cases there are a few entries in new projects in my failing instance. If the history entries are not there, are they gone forever ? What DB table do I have to look for the history entries ?

**Comment by hennevogel** [comment]
@mmohring `history_elements`

**Comment by mmohring** [comment]
@Ana06 @hennevogel I have decided to try with a fresh install. I will use git master, with a version after the OBS Factory was integrated.

**Comment by hennevogel** [comment]
If you still have a problem then, we can re-open this :)
