### ISSUE TITLE
[webui] Logout in OBS always redirects to home page.

### ISSUE THREAD

**Issue by srivatsav1998** [openSUSE/open-build-service#4773]
Issue/Feature description
====================
While on a prjoect page, and if you logout of OBS, you will be redirected to the home page instead of refreshing the current project page.

Expected result
============
Current viewing page should be refreshed.

How to Reproduce
===============
1. Login to your OBS account and go to any project.
2. Now logout of the OBS and you will be redirected to the homepage.

**Comment by Ana06** [comment]
:+1: a PR would be really welcome :wink:

**Comment by srivatsav1998** [comment]
A PR for this issue has been placed. Please review it.

**Comment by srivatsav1998** [comment]
This issue is solved with PR #4774. Hence closing the issue.
