### ISSUE TITLE
[ci] rubocop runs with ruby 2.1 parser

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#4808]
Issue/Feature description
====================
Rubocop runs either with the ``.ruby-version``, ``Gemfile.lock`` or as configuration
```
AllCops:
  TargetRubyVersion: 2.5
```

Neither is set by OBS so rubocop uses 2.1 parser which does raise Lint/Syntax errors which is not possible to disable (e.g. disallows ``<<~`` heredoc).

Setting TargetRubyVersion to 2.5 resulted in basically a violation in almost every file, so I wanted to create an issue first.

Expected result
============
We use ruby parser 2.5 in rubocop

How to Reproduce
===============
1. Add ``<<~`` somewhere in the code and run rubocop
or
1. Add ``TargetRubyVersion: 2.5`` and run rubocop to see all the violations

**Comment by Ana06** [comment]
We should change it :+1:

**Comment by dmarcoux** [comment]
Is there a reason for not using `.ruby-version`?

**Comment by ChrisBr** [comment]
@dmarcoux nope, just work ;) As said, setting it to 2.5 will basically complain about some violation in every file so quite some work (especially to review).

**Comment by dmarcoux** [comment]
@ChrisBr: Do you refer to this violation `Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.`? According to this [GitHub issue](https://github.com/bbatsov/rubocop/issues/3284) and the [source](https://github.com/bbatsov/rubocop/blob/44c3ba0a37aed4fe748f01dfacab03b4f88f11fe/lib/rubocop/cop/style/frozen_string_literal_comment.rb#L14), it is in every file and active with Ruby 2.3+. It's however easily fixable with `rubocop --auto-correct`.

I would like to be assigned to this issue. I already started to look into this.

**Comment by Ana06** [comment]
@dmarcoux 

> @ChrisBr: Do you refer to this violation Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.? According to this GitHub issue and the source, it is in every file and active with Ruby 2.3+. It's however easily fixable with rubocop --only Style/FrozenStringLiteralComment --auto-correct. The cop Style/FrozenStringLiteralComment can also be disabled. However, this cop is designed to help upgrade to Ruby 3.0. Frozen string may be defaults then.

In my opinion it should be fixed and not disabled. But regarding style rules we allow all contributors to raise concerns. It is explain in the Wiki: https://github.com/openSUSE/open-build-service/wiki/Code-Style So, I hope nobody complains about a rule to help updating to Ruby 3, but it could happens :wink:
