### ISSUE TITLE
setrelease not working

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#4812]
POST https://api.opensuse.org/source/openSUSE:Leap:15.0:Images/opensuse-leap-image?cmd=release&setrelease=Snapshot13.2

$ osc ls -b openSUSE:Leap:15.0:Images:ToTest/opensuse-leap-image
_statistics
opensuse-leap-15.0-image.x86_64-2.8.0-Build4.2.docker.containerinfo
opensuse-leap-15.0-image.x86_64-2.8.0-Build4.2.docker.obsbinlnk
opensuse-leap-15.0-image.x86_64-2.8.0-Build4.2.docker.tar.xz
opensuse-leap-15.0-image.x86_64-2.8.0-Build4.2.docker.tar.xz.sha256
opensuse-leap-15.0-image.x86_64-2.8.0-Build4.2.packages
opensuse-leap-15.0-image.x86_64-2.8.0-Build4.2.report
opensuse-leap-15.0-image.x86_64-2.8.0-Build4.2.verified

**Comment by lnussel** [comment]
worked for other images in the repo

$ osc ls -b openSUSE:Leap:15.0:Images:ToTest/livecd-leap-x11
_statistics
openSUSE-Leap-15.0-Rescue-CD-x86_64-Snapshot13.2-Media.iso
openSUSE-Leap-15.0-Rescue-CD-x86_64-Snapshot13.2-Media.iso.sha256
openSUSE-Leap-15.0-Rescue-CD-x86_64-Snapshot13.2-Media.packages
openSUSE-Leap-15.0-Rescue-CD-x86_64-Snapshot13.2-Media.report
openSUSE-Leap-15.0-Rescue-CD-x86_64-Snapshot13.2-Media.verified

**Comment by Vogtinator** [comment]
This seems to be only implemented for RPMs and KIWI products:

https://github.com/openSUSE/open-build-service/blob/e916c2bc2606d37129085e3ca8ba482768172981/src/backend/bs_repserver#L2211

Ping, this blocks Leap 15 docker images.

**Comment by adrianschroeter** [comment]
We can add support for them here, but you are aware that these containers don't go the ftp servers at all anymore? They go to the registry, thus the filename does not matter at all. I assume you want to have it tagged there instead?

**Comment by Vogtinator** [comment]
> We can add support for them here, but you are aware that these containers don't go the ftp servers at all anymore? They go to the registry, thus the filename does not matter at all. I assume you want to have it tagged there instead?

They're pulled over rsync from the backend to openQA.

**Comment by adrianschroeter** [comment]
On Montag, 16. April 2018, 10:32:41 CEST wrote Fabian Vogt:
> > We can add support for them here, but you are aware that these containers don't go the ftp servers at all anymore? They go to the registry, thus the filename does not matter at all. I assume you want to have it tagged there instead?
> 
> They're pulled over rsync from the backend to openQA.

Shouldn't that be changed as well to test in the same way as the user will get it?

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by Vogtinator** [comment]
> Shouldn't that be changed as well to test in the same way as the user will get it?

The docker image needs to be mirrored to openQA for reproducible test runs.

Alternatively, the oS registry needs to support multiple versions of any given image and keep them for a limited time.

**Comment by adrianschroeter** [comment]
On Montag, 16. April 2018, 11:03:23 CEST wrote Fabian Vogt:
> > Shouldn't that be changed as well to test in the same way as the user will get it?
> 
> The docker image needs to be mirrored to openQA for reproducible test runs.
> 
> Alternatively, the oS registry needs to support multiple versions of any given image and keep them for a limited time.

We plan to drop these tar balls entirely in the backend in future to avoid disk space waste.
OBS itself will provide a registry server interface instead.

So you will anyway need to cache/store them local in future. Why not just use
"docker export" then on your side?

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by Vogtinator** [comment]
> So you will anyway need to cache/store them local in future. Why not just use
"docker export" then on your side?

Not that easy - rsync.pl needs to get to images for other than x86_64 as well. Currently that's not possible with any tooling (docker always pulls the current arch and skopeo doesn't support multiarch at all). It's currently only possible because OBS doesn't do multiarch at all, so not futureproof either.

In any case, it would require substantial changes to rsync.pl for this to work.

**Comment by adrianschroeter** [comment]
On Montag, 16. April 2018, 14:10:34 CEST wrote Fabian Vogt:
> It's currently only possible because OBS doesn't do multiarch at all, so not futureproof either.

that might change this week already ...

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by Vogtinator** [comment]
> that might change this week already ...

Yup, that means currently copying tars around is not only the easiest, but also the only possible way without inventing new tools.

**Comment by adrianschroeter** [comment]
On Montag, 16. April 2018, 14:49:14 CEST wrote Fabian Vogt:
> > that might change this week already ...
> 
> Yup, that means currently copying tars around is not only the easiest, but also the only possible way without inventing new tools.

But you got that we plan not to generate these tar balls at all anymore in not too far future?

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by Vogtinator** [comment]
> But you got that we plan not to generate these tar balls at all anymore in not too far future?

Yes, but that should wait until a proper solution is available.

**Comment by lnussel** [comment]
note that the image shouldnt be published anywhere until openqa said it's good. the fact it built in obs doesn't mean we want to publish it.

**Comment by adrianschroeter** [comment]
On Montag, 16. April 2018, 16:40:29 CEST wrote Ludwig Nussel:
> note that the image shouldnt be published anywhere until openqa said it's good. the fact it built in obs doesn't mean we want to publish it.

it gets only published to the registry.* instances when the flag is on. But OBS itself will provide it itself
as another registry server most likely (but that part is not in stone yet)

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by Vogtinator** [comment]
Would "osc getbinaries" still work? If not, I'm against that feature.

How would local builds against it work?

**Comment by mlschroe** [comment]
Yes, getbinaries will still be able to download the tar ball. It's just not stored that way and will be generated just for the download. This change will take a couple of weeks. The next step is to push multiarch images to the registry, which will happen this week.

**Comment by adrianschroeter** [comment]
however, that would break the setrelease as well most likely. 

Right now, I am against in extending support for docker tar balls here before we have the storage sorted out.

**Comment by adrianschroeter** [comment]
jfyi, parts of this is solved in https://github.com/openSUSE/open-build-service/pull/5486

**Comment by lnussel** [comment]
what is the status here?

**Comment by mlschroe** [comment]
Closed.
