### ISSUE TITLE
Set_bugowner notificactions miss group name

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#4818]
@mlschroe refused to accept the incident report during lunch, so I'm follwing up here:

set_bugowner requests to groups miss the name of the group in the email notification. If my ruby knowledge doesn't fail me it's because in 1f0e01d4bb966b64b8a1749888640b37835411a8 there is one space too much accessing a['group']

**Comment by DavidKang** [comment]
Handled in PR #4822
