### ISSUE TITLE
Should we disable flickering tests?

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#4826]
I wonder if it is a good idea to keep flickering tests running. They make that we have to restart the test suite many times to ensure that it passes. I would better create an issue and skipping them. Once they are fixed we enable them again.

It is not only a problem in the PRs, but also really confusing for new comers. I've received several email from new contributors asking what are they doing wrong when they got failures from flickering test.

Should we do this as default? Any reason to keep this annoying tests? :thinking:

**Comment by hennevogel** [comment]
When the flicker in green they actually test something. If you disable them they never test anything.

**Comment by Ana06** [comment]
@hennevogel 

> When they flicker in green they actually test something. If you disable them they never test anything.

yes, but can we trust a broken test? And even if it is useful sometimes, is it worthwhile? :thinking:

**Comment by ChrisBr** [comment]
@Ana06 we also have now rspec-retry enabled for feature tests

https://github.com/openSUSE/open-build-service/pull/4779

If there are other tests failing, let me know and we could e.g. add a label ``:flaky`` to these tests to also retry three times.

**Comment by bgeuken** [comment]
No, we should fix them :smile:

**Comment by eduardoj** [comment]
@Ana06 

> Is everybody fine with retrying the flickering test until they are fixed as @ChrisBr suggests?

Yes from my side. I'm not happy to have a flickering test, but, without having another alternative test, it should always fail when introducing code that is not desired. I prefer to have a flickering test than not to have anything.

**Comment by Ana06** [comment]
@eduardoj 

> I prefer to have a flickering test than not to have anything.

Well, @ChrisBr suggestion is to retry the test 3 times, so that it doesn't fail anymore. So it would be flickering anymore. :rofl:

**Comment by ChrisBr** [comment]
Actually, I don't remember that we have that many flickering tests the last few months ... 

We also have now the build insights in place which could help to see which tests often fail

https://circleci.com/build-insights/gh/openSUSE/open-build-service/master

**Comment by bgeuken** [comment]
> Is everybody fine with retrying the flickering test until they are fixed until they are fixed as @ChrisBr suggests?

We already use the retry gem...

Of course we should still solve tests that fail every now and then. Though this gem makes it harder to spot them.

**Comment by coolo** [comment]
Perhaps you should take a look at https://github.com/zenazn/volkswagen

**Comment by hennevogel** [comment]
Guess time answered this...
