### ISSUE TITLE
/about route displays wrong revision in development

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#4830]
Issue/Feature description
====================
The ```/about``` route displays the wrong revision in development mode. This is because the revision is set during package build in the ``environment.rb``.

See:
https://github.com/openSUSE/open-build-service/blob/master/src/api/config/initializers/02_apiversion.rb#L2

Expected result
============
``/about`` route shows correct revision in development mode.

**Comment by bgeuken** [comment]
@ChrisBr AFAIK we would have to constantly fetch / parse the commit revision from git. Do we have any use case for this in development mode?
If not I would just not show a revision.

**Comment by ChrisBr** [comment]
Fixed in https://github.com/openSUSE/open-build-service/pull/4955
