### ISSUE TITLE
New live log indicator show "finished" when the build failed

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#4840]
Issue/Feature description
====================
This is a little bit confusing as the build actually failed. 

![image](https://user-images.githubusercontent.com/3799140/38603830-fb05f762-3d6e-11e8-9ca4-7f8f121d209c.png)

Expected result
============
Should be red and display that the build failed

@DavidKang I'm not sure if this can be easily fixed as I don't know if we have this information in the JS...

cc @lnussel @coolo

**Comment by adrianschroeter** [comment]
On Mittwoch, 11. April 2018, 10:00:53 CEST wrote Christian Bruckmayer:
> Issue/Feature description
> ====================
> This is a little bit confusing as the build actually failed. 
> 
> ![image](https://user-images.githubusercontent.com/3799140/38603830-fb05f762-3d6e-11e8-9ca4-7f8f121d209c.png)
> 
> Expected result
> ============
> Should be red and display that the build failed
> 
> @DavidKang I'm not sure if this can be easily fixed as I don't know if we have this information in the JS...

The build result state (succeeded/failed) is in the details element during the code="finished" time frame.

But it might be also enough to change the interface to some neutral look, like "runninig", "not running"...

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by mdeniz** [comment]
This is showing the status of the log, not the status of the build... the expected result is that is says "finished" like it says "running" instead of "building".

But if this is misleading for you we can think about it. I don't know if we want to show the status of the build here.

**Comment by ChrisBr** [comment]
@mdeniz I know but we already got this feedback :)

So then what about the suggestion from @adrianschroeter

**Comment by adrianschroeter** [comment]
On Mittwoch, 11. April 2018, 10:26:09 CEST wrote Moisés Déniz Alemán:
> This is showing the status of the log, not the status of the build... the expected result is that is says "finished" like it says "running" instead of "building".
> 
> But if this is misleading for you we can think about it. I don't know if we want to show the status of the build here. 

I think the missleading part is the green color and the green hook which looks like success.

Changing that to something neutral may make Ludwig happy ;)

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by mlschroe** [comment]
completed?

**Comment by mlschroe** [comment]
But I agree with Adrian that it's the color that makes it misleading.

**Comment by hennevogel** [comment]
You can also avoid any of the words that are used for build status to make this even more clear. 

http://www.thesaurus.com/browse/finished?s=t

* complete
* done
* concluded
* ended

**Comment by coolo** [comment]
I like ended - but we still need a colour to it. google suggests https://www.urbanog.com/City-Color-Dual-Ended-Contour-Brush-CCF07_103_57284.html - but it's sold out

**Comment by hennevogel** [comment]
:thought_balloon: sometimes I would like to smoke what @coolo smokes...
