### ISSUE TITLE
Unicode in package not represented right in webui

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#4841]
https://build.opensuse.org/request/show/595511 :
```
   + Add W504 warning for checking that a break doesn���t happen after
```
.changes file as seen from osc command-line has the U+2018 sign correct:
```
   + Add W504 warning for checking that a break doesn’t happen after
```

**Comment by bgeuken** [comment]
Actually it's intended. But we can make it a bit less restrictive.
