### ISSUE TITLE
Rubocop /dist/ directory excluded

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#4852]
Issue/Feature description
====================
For some reason (probably because of many violations) the /dist/ directory is excluded from rubocop. However, we run rubocop from the root directory mainly to also check e.g. clouduploader and openQA tests. We should fix these violations and include this directory.

Expected result
============
Rubocop checks /dist/ dir

cc @Ana06

**Comment by dmarcoux** [comment]
@ChrisBr @Ana06 I will take care of this and regenerate `.rubocop_todo.yml`.
