### ISSUE TITLE
webui binary view for multibuild not working

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#4854]
See eg.

https://build.opensuse.org/package/binaries/openSUSE:Leap:15.0/000product:openSUSE-dvd5-dvd-x86_64/images

It shows 000 product instead of the requested 000product:openSUSE-dvd5-dvd-x86_64

**Comment by coolo** [comment]
same problem as in #4802

**Comment by adrianschroeter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix multibuild binary view](https://trello.com/c/Ihi8rRMj/1384-fix-multibuild-binary-view)

**Comment by hennevogel** [comment]
So duplicate of  #4802
