### ISSUE TITLE
Setting gnome-keyring be default in osc.

### ISSUE THREAD

**Issue by philo-math** [openSUSE/open-build-service#4875]
Issue/Feature description
====================
Gnome-keyring should be enabled by default while asking for user name and to store password.
So I suggest the following features to be added: 
* To enable the keyring setting by default
* To ask the user about his/her preference during the first configuration setup.

Expected result
============
It would provide user a choice on whether to save his/her password in plain text or using keyring.

Further information
===============
* My operating System: output of `cat /etc/*-release`

> DISTRIB_ID=LinuxMint
> DISTRIB_RELEASE=18.3
> DISTRIB_CODENAME=sylvia
> DISTRIB_DESCRIPTION="Linux Mint 18.3 Sylvia"
> NAME="Linux Mint"
> VERSION="18.3 (Sylvia)"
> ID=linuxmint
> ID_LIKE=ubuntu
> PRETTY_NAME="Linux Mint 18.3"
> VERSION_ID="18.3"
> HOME_URL="http://www.linuxmint.com/"
> SUPPORT_URL="http://forums.linuxmint.com/"
> BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
> VERSION_CODENAME=sylvia
> UBUNTU_CODENAME=xenial

* I installed osc using `sudo apt install osc` (Though I need to install python-keyring later, which should be installed with the osc package as a dependency)

(Please pardon me if I have missed something. It's my first issue to any project)

**Comment by lethliel** [comment]
Thank you for opening your first issue. But there is a separate repository for osc related stuff.
Please report the issue there: https://github.com/openSUSE/osc/issues
