### ISSUE TITLE
[webui] patchinfo web editor removes message element

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/open-build-service#4895]
Issue/Feature description
====================

When editing a patchinfo that has an optional message element, the web patchinfo editor removes the element.

Expected result
============

Do not remove the message element

How to Reproduce
===============
1. When I want to edit a patchinfo
2. and the patchinfo contains a message element
3. the patchinfo element is removed without feedback.

The web UI could either support editing the message, or leave it in place, or note that the patchinfo contains elements that the web UI cannot handle.

Further information
===============
* https://github.com/openSUSE/open-build-service/blob/master/docs/api/api/patchinfo.rng#L69
* https://build.opensuse.org/package/rdiff/openSUSE:Maintenance:8024/patchinfo?linkrev=base&rev=4

Low prio, if any, since we hardly ever use this element.

**Comment by adrianschroeter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Patchinfo editor removes data](https://trello.com/c/1afq4N5z/1409-patchinfo-editor-removes-data)
