### ISSUE TITLE
be more aggressive in killing build jobs

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#4909]
I just wasted a whole day waiting for staging that was seemingly building a kernel (openSUSE:Leap:15.0:Staging:C/kernel-default/standard/x86_64). After 11 hours I discovered that it got stuck after 2.7 hours already while writing the rpms. Sending sysrq yielded no output at all.

Can obs please kill such jobs earlier? I mean it didn't produce any log output for hours!

**Comment by lnussel** [comment]
at this point in time of the release cycle I need to get stuff done no matter what workaround is needed for that. wasting a day thinking that everything is building sucks.

I also filed https://bugzilla.opensuse.org/show_bug.cgi?id=1090748 for the one case where sysrq worked so far.

**Comment by adrianschroeter** [comment]
BuildFlag: logidlelimit:$seconds

can be configured in prjconf now (and can be adapted for specific repos and/or architectures)
