### ISSUE TITLE
500 errors on main/sitemap_packages/*

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#4922]
Issue description
====================

Any request under https://build.opensuse.org/main/sitemap_packages/, produces a 500 error. I tried with a few different categories like `opensuse`, `home` and `test`.

Expected result
============

Display the sitemap for the category of packages.

How to reproduce
===============

1. Visit https://build.opensuse.org/main/sitemap_packages/opensuse
2. The 500 error page is displayed

Further information
===============

The errors must have been caught by Errbit, so if someone from the team could link them (if it's possible to access them), it would be great. I tried to reproduce it locally without success.

**Comment by coolo** [comment]
The URL is https://build.opensuse.org/main/sitemap_packages/show?category=opensuse

**Comment by dmarcoux** [comment]
@coolo Oh yes, I overlooked [params[:category]](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/controllers/webui/main_controller.rb#L60). Still, I believe it should not produce an error. I plan on taking the sitemap code out of `webui/main_controller.rb`. I will address it then.

**Comment by coolo** [comment]
what happens: it gets opensuse as :action - so I guess stricter routes are the key to avoid the 500 :)

**Comment by coolo** [comment]
it worked for google when I introduced it. perhaps they don't care about standards - as noone else does either :)

**Comment by dmarcoux** [comment]
According to [this page](https://support.google.com/webmasters/answer/183668?hl=en), the sitemaps can be tested before submitting them. This would be a way to see if these endpoints are really needed or not.

**Comment by hennevogel** [comment]
@coolo https://www.youtube.com/watch?v=HWgUBFOCxB0

**Comment by coolo** [comment]
Just checked and the sitemap submitted 281.548 URLs in google - only 7.779 are indexed though. and there are some 404 within the sitemap to e.g sitemap_project_packages

**Comment by hennevogel** [comment]
Should be simple to fix the routes :-)
