### ISSUE TITLE
Fix redirect issues on server

### ISSUE THREAD

**Issue by in1t3r** [openSUSE/open-build-service#4929]
Issue/Feature Description
====================
Trivial but annoying.
Your comment in description of github project mention http://openbuildservice.org
And your server do not redirect to the 443 port for https://openbuildservice.org 

Expected Result
============
If you already use lets encrypt you should have on server side redirect with 301 for requests to port 80 and update the project description with the https url. :)  

How to Reproduce
===============
Open browser where you haven't visited openbuildservice.org
Page will either not load or have a really long loading also if you are using the letsencrypt its normal to redirect to the HTTPS after all we all want more safe internet. :)

**Comment by hennevogel** [comment]
We are now redirecting all traffic to https
