### ISSUE TITLE
GPG signing issue on build.opensuse.org science:

### ISSUE THREAD

**Issue by cfelder** [openSUSE/open-build-service#4937]
Hi, we get errors on gpg signature checks using the science: repositories (e.g. on Ubuntu 17.04, Ubuntu 18.04). Some time ago we also got errors that the key uses weak encryption (SHA1)
```
W: GPG error: http://download.opensuse.org/repositories/science:/gr-framework/xUbuntu_18.04  Release: The following signatures were invalid: D1DD7ACD6D68A0B43081B15801DB7302943D8BB8
E: The repository 'http://download.opensuse.org/repositories/science:/gr-framework/xUbuntu_18.04  Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```
Is there anything we can do from our side or do you have to replace the science: signing key?

**Comment by hennevogel** [comment]
Talk to the [science project maintainers](https://build.opensuse.org/project/users/science) to renew their key.
