### ISSUE TITLE
Fix top of the page navigation

### ISSUE THREAD

**Issue by hellcp** [openSUSE/open-build-service#4954]
**Is your feature request related to a problem? Please describe.**
Majority of project/package navigation is on the top of the page (tabs)

**Describe the solution you'd like**
Create "go to the top of the page" button to make it easier to navigate tabs

**Describe alternatives you've considered**
Tabs on the bottom, maybe?
Tabs scrolling with viewpoint?

**Comment by dmarcoux** [comment]
You can go to the top of the page with the keyboard by pressing `Home`.
