### ISSUE TITLE
Provide meta og tags for various pages

### ISSUE THREAD

**Issue by hellcp** [openSUSE/open-build-service#4957]
**Is your feature request related to a problem? Please describe.**
When I get links from people, about something on OBS on IRC, I get message from bot, saying what exactly that link links to. When I'm using OBS links on any other platform however, that functionality would require me to write a bot for every chat app I use. Most of them however support embeding links with meta og tags.

**Describe the solution you'd like**
I would like OBS to provide useful information to see what is inside the link before I click it.

**Additional context**
Github provides sizable feedback from link:
![example](https://user-images.githubusercontent.com/30577011/39719561-df4f554c-5239-11e8-8018-ff6d297300c8.png)

**Comment by SDBowen** [comment]
I can help on this one.

For links to a specific request, the request's title, description, and creator's icon can be included in the og metadata tags.

How should the tags in the various project sections (Overview, Repositories, etc..) be handeled? I think the title can be similar to the current page titles (section and project name), and the description would be the project description from the Overview. 

What about the og:image for these pages? Maybe the OBS or SUSE logo?

**Comment by hellcp** [comment]
Agreed on suggested title and description content. When it comes to image, it would be nice to get user avatars in case of user links, but otherwise OBS logo would work :D

**Comment by hennevogel** [comment]
> How should the tags in the various project sections be handeled?

I don't think we need metadata for all the tabs in Package/Project. The show action should be enough.

> Maybe the OBS or SUSE logo?

The OBS is an open source project used by many projects other than SUSE/openSUSE. So OBS logo for Package/Project, submitter avatar for Requests sound about right.

**Comment by hellcp** [comment]
@hennevogel it would be nice to have a fallback for lack of metadata for all the remaining views.

Actually, maybe I could challenge this even more, what if depending on build results in different views, it changed colour of OBS logo and theme colour tag (like the one used in openSUSE.org), this could be later applied to favicon in the browser tabs, so you get to know that your build failed from just looking at a tab of log (favicons can be changed dynamically with some js).

**Comment by hennevogel** [comment]
>  build results in different views, it changed colour of OBS logo and theme colour tag 

As build results are currently only manually polled it makes little sense I guess. But we are exploring currently if we are going to change this to a pub/sub/message architecture. I would wait for this.

**Comment by SDBowen** [comment]
OK, going to get the show actions working and go from there!
