### ISSUE TITLE
Multibuild: Wrong Download link (404 error)

### ISSUE THREAD

**Issue by afaerber** [openSUSE/open-build-service#4985]
# Issue Description
For multibuild packages the Web interface's Download link is lacking the multibuild component, leading to error 404 on download attempt.

Expected Result
============
Clicking on the file's Download link should start the download.

How to Reproduce
===============
1. Go to a multibuild-enabled package: https://build.opensuse.org/package/show/openSUSE:Factory:ARM:Live/JeOS
2. Click on the 'images' repo link of any of the non-first Build Results, e.g. 'JeOS:JeOS-efi.aarch64' (https://build.opensuse.org/package/binaries/openSUSE:Factory:ARM:Live/JeOS:JeOS-efi.aarch64/images)
3. If there are no Download links, only Details, log in
4. You should now see a Download link next to the files, such as 'openSUSE-Tumbleweed-ARM-JeOS-efi.aarch64-2018.05.11-Build1.1.raw.xz (336 MB)'
5. Click on that 'Download' link (https://api.opensuse.org/build/openSUSE:Factory:ARM:Live/images/aarch64/JeOS/openSUSE-Tumbleweed-ARM-JeOS-efi.aarch64-2018.05.11-Build1.1.raw.xz)
6. Observe an ugly XML snippet showing:
```
<status code="404"><script/><summary>openSUSE-Tumbleweed-ARM-JeOS-efi.aarch64-2018.05.11-Build1.1.raw.xz: No such file or directory</summary><details>404 openSUSE-Tumbleweed-ARM-JeOS-efi.aarch64-2018.05.11-Build1.1.raw.xz: No such file or directory</details></status>
```
7. Copy and change the download URL, replacing /JeOS/ with /JeOS:JeOS-efi.aarch64/ path component (https://api.opensuse.org/build/openSUSE:Factory:ARM:Live/images/aarch64/JeOS:JeOS-efi.aarch64/openSUSE-Tumbleweed-ARM-JeOS-efi.aarch64-2018.05.11-Build1.1.raw.xz), and observe the download working.

Further Information
===============

* Originally observed on SUSE's internal instance, but reproducible also on public openSUSE instance

**Comment by afaerber** [comment]
Still with us.

**Comment by Ana06** [comment]
@afaerber thanks for such detailed issue! :heart_eyes: 

@DavidKang and I are working on fixing it :wink:
