### ISSUE TITLE
Unsafe parameter value in link_to href in app/views/shared/_involved_users.html.erb

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#499]
A Cross Site Scripting vulnerability was found by Code Climate around line 45 in app/views/shared/_involved_users.html.erb.

https://codeclimate.com/repos/527f396c89af7e4ed206fbeb/security/836aa2f315c5b76a92ab280d61866d9a

**Comment by hennevogel** [comment]
We don't use the params in the link anymore.
