### ISSUE TITLE
Do not send Travis CI build notifications for forks

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#5012]
**Is your feature request related to a problem? Please describe.**
When working on a fork of the project, if Travis CI is enabled on that fork, it will send build notifications to IRC. This is unneeded.

**Describe the solution you'd like**
Travis CI build notifications for a fork of the project are not sent to IRC. It should be configured in `.travis.yml`. It must not prevent forks from using Travis CI.

**Describe alternatives you've considered**
I checked if it is possible to disable build notifications for forks in `.travis.yml`, but it isn't. See [this issue for details](https://github.com/travis-ci/travis-ci/issues/329).

**Additional context**
Here's a [possible solution](https://github.com/mozilla/build-tools/commit/c13a2978e0869219295013eeb52cf52227ab45ec) to this. It is simple and concise.

**Comment by dmarcoux** [comment]
Closed in #5515, we don't have notifications anymore.

**Comment by coolo** [comment]
the solution is interesting :)
