### ISSUE TITLE
IDEA: get statistics from OBS for a numbers.o.o page

### ISSUE THREAD

**Issue by knurpht** [openSUSE/open-build-service#5021]
Actually there's no real problem, but it's something which would be nice to have for the community on a numbers.opensuse.org page f.e.

**Comment by bgeuken** [comment]
There are some few numbers on [metrics.opensuse.org](https://metrics.opensuse.org/d/cqzJSqWik/obs-main?orgId=1).

We started a few weeks ago with adding Application Health Monitoring to OBS. So this is for now just a test balloon.

Do you have any particular stats in mind that you would be interested in?

**Comment by hennevogel** [comment]
I guess not.. :-)
