### ISSUE TITLE
[webui] some 'finished' or 'unchanged' results of successful builds never change to 'succeeded'

### ISSUE THREAD

**Issue by quicktrick** [openSUSE/open-build-service#5035]
# Issue Description
After the successful build some 'finished' or 'unchanged' results never change to 'succeeded', preventing building of dependent packages.

Expected Result
============
'finished' or 'unchanged' results of successful builds should change to 'succeeded'.

Examples
============
1. 
https://build.opensuse.org/package/show/home:quicktrick/hyperscan
https://build.opensuse.org/packages/hyperscan/job_history/home:quicktrick/openSUSE_Tumbleweed/x86_64
so the dependent package is blocked: https://build.opensuse.org/package/show/home:quicktrick/rspamd

2.
Look at the `openSUSE_Tumbleweed` `x86_64` result (right column, bottom line).
https://build.opensuse.org/package/show/home:quicktrick:branches:security/fail2ban
https://build.opensuse.org/packages/fail2ban/job_history/home:quicktrick:branches:security/openSUSE_Tumbleweed/x86_64

**Comment by adrianschroeter** [comment]
we had serious performance problems on the backends, it is mostly solved now.
