### ISSUE TITLE
[production][delayed_job#ProjectDoProjectReleaseJob] No permission to modify project 'home:lenovo-lico:lico-dep:5.1:el7' for user 'bgeuken'

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#5043]
delayed_job#ProjectDoProjectReleaseJob threw this 16 times
<pre>
No permission to modify project &#39;home:lenovo-lico:lico-dep:5.1:el7&#39; for user &#39;bgeuken&#39;
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5ab07ab869936e000cf97934)

**Comment by gassyfeve** [comment]
This is a private project. Sure you could not modify it.

**Comment by hennevogel** [comment]
Sure it's correct. The questions is why is this job scheduled if the user has no permission?

**Comment by hennevogel** [comment]
Does not happen anymore...
