### ISSUE TITLE
[production][] Mysql2::Error: Field 'binary_release' doesn't have a default value: INSERT INTO `binary_releases`...

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#5051]
threw this 168 times
<pre>
Mysql2::Error: Field &#39;binary_release&#39; doesn&#39;t have a default value: INSERT INTO `binary_releases` (`repository_id`, `release_package_id`, `binary_name`, `binary_version`, `binary_arch`, `binary_disturl`, `binary_releasetime`, `medium`) VALUES (1216868, 2569532, &#39;container:SLE-12-SP3-Container-Base&#39;, &#39;1.0.0&#39;, &#39;noarch&#39;, &#39;obs://build.opensuse.org/SUSE:Templates:Images:SLE-12-SP3:Base/images/932a92cca0b55af3ca0c46733ae4e853-SLE-12-Container-Base&#39;, &#39;2018-03-09 19:58:53&#39;, &#39;my_container.x86_64-1.0.0-Build4.103.docker.tar.xz&#39;)
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5aa2e783ab2581001400b1b1)

**Comment by hennevogel** [comment]
Duplicate of #4953

**Comment by adrianschroeter** [comment]
On Montag, 28. Mai 2018, 16:49:47 CEST wrote Henne Vogelsang:
>  threw this 168 times
> <pre>
> Mysql2::Error: Field &#39;binary_release&#39; doesn&#39;t have a default value: INSERT INTO `binary_releases` (`repository_id`, `release_package_id`, `binary_name`, `binary_version`, `binary_arch`, `binary_disturl`, `binary_releasetime`, `medium`) VALUES (1216868, 2569532, &#39;container:SLE-12-SP3-Container-Base&#39;, &#39;1.0.0&#39;, &#39;noarch&#39;, &#39;obs://build.opensuse.org/SUSE:Templates:Images:SLE-12-SP3:Base/images/932a92cca0b55af3ca0c46733ae4e853-SLE-12-Container-Base&#39;, &#39;2018-03-09 19:58:53&#39;, &#39;my_container.x86_64-1.0.0-Build4.103.docker.tar.xz&#39;)
> </pre>
> 

this is fixed with the container maintenance branch

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany
