### ISSUE TITLE
Link (https://api.opensuse.org/distributions) to list of available build targets is broken at the openSUSE Wiki

### ISSUE THREAD

**Issue by fusion809** [openSUSE/open-build-service#5058]
# Issue Description
At the openSUSE Wiki there is [an article](https://en.opensuse.org/openSUSE:Build_Service_supported_build_targets) listing available build targets. It is presently outdated, not just in terms of the available supported distributions (e.g. Fedora 28 and Ubuntu 18.04 support is available but not listed, although that is simple for me to add to it so by the time you look at it that will likely be fixed) but also the link to the OBS API page that is meant to display an up-to-date list of available build targets (https://api.opensuse.org/distributions) is dead. So I'm here to ask for the correct link so I can edit this article myself and add the corrected link. 

I had a conversation in the #opensuse-buildservice IRC channel that suggested I should file this as an issue here. If I am incorrect in filing it here, I'm sorry for wasting your time. 

Thanks for your time,
Brenton

**Comment by coolo** [comment]
/distributions is only 404 (or dead as you say) if accessed from a browser. If you try with curl, you get a permission denied error - as it requires authentification. The link you want is https://api.opensuse.org/public/distributions

**Comment by adrianschroeter** [comment]
please don't use /public route, it is for internal use only and may go away.

We can make usual /distributions world readable if anonymous mode is enabled.

**Comment by adrianschroeter** [comment]
however, this is not a very readable XML .... question is if we should not list it in a better (non XML) form in the webui....

**Comment by hennevogel** [comment]
We really need to get rid of the openSUSE wiki pages. There is so much outdated stuff in there...

**Comment by Ana06** [comment]
@hennevogel 

> We really need to get rid of the openSUSE wiki pages. There is so much outdated stuff in there...

should we just drop the wiki page? :thinking:

**Comment by bgeuken** [comment]
You can view this file in the browser by setting the format to xml (add ?format=xml to the url). I've fixed the link and added a reference to the target list we have on our add repo page.
