### ISSUE TITLE
Ubuntu 18.04 reports "nothing provides package" when built in private OBS instance

### ISSUE THREAD

**Issue by polmr** [openSUSE/open-build-service#5059]
# Issue Description
I have configured an OBS private instance on an openSUSE Leap 42.3. Ubuntu 18.04 does not seem to recognize packages built with it when searching for dependencies. I've tried to reduce the problem to a minimum: 
In this scenario I have two packages: `father01` and `son01` within a project with repositories Ubuntu 16.04 & Ubuntu 18.04 configured. `son01` depends on `father01` (Build-Depends: `father01`, ...). `father01` builds ok for both repositories, but `son01` builds ok for 16.04 and fails for 18.04: it states "unresolvable" status -> `nothing provides father01`. 

Expected Result
============
Ubuntu 18.04 building of `son01` should be able to resolve the built `father01`

How to Reproduce
===============
I attach a zip with the contents of [both packages](https://github.com/openSUSE/obs-build/files/2027847/testPackages.zip)

**Comment by adrianschroeter** [comment]
I can not reproduce this here with a remote instance. Do you have an older OBS? Do you have played with useforbuild flags maybe?

**Comment by polmr** [comment]
Hi @adrianschroeter , `Use for Build Flag` is enabled for all repos. For the record: Publish Flag is not. But in any case the configuration is the same for Ubuntu 16.04 and 18.04. I have the latest OBS available in a private OBS instance installed on an OpenSUSE 42.3 using the OBS repo http://download.opensuse.org/distribution/leap/42.3/repo/oss/
```
$rpm -qa obs-server
obs-server-2.8.4-4.12.noarch
$zypper search -s obs-server
S  | Name       | Type       | Version    | Arch   | Repository                                                  
---+------------+------------+------------+--------+-------------------------------------------------------------
i+ | obs-server | package    | 2.8.4-4.12 | noarch | 2.8 version of the Open Build Service Server (openSUSE_42.3)
```

**Comment by adrianschroeter** [comment]
yes, OBS 2.8 is not support the new package format. Please use OBS 2.9 for Ubuntu 18.04. (you may can get away with just the new build package for the new compression, but not supported official).

**Comment by polmr** [comment]
Thanks @adrianschroeter !
One quick question ... If I update the repo from `2.8` to `2.9` and update the corresponding packages ... is it likely to work? or would you recommend an installation from scratch?
