### ISSUE TITLE
Tizen creation proposal into https://build.opensuse.org/project/

### ISSUE THREAD

**Issue by leemgs** [openSUSE/open-build-service#5069]
Deall all, 

Can we add Tizen (https://www.tizen.org/) software platform distribution such as the existing Linux distributions?
* https://build.opensuse.org/project/
![obs](https://user-images.githubusercontent.com/82404/40873039-f9f54d66-6693-11e8-9fa2-bab1890216ec.png)

When I try to append Tizen distribution directly at https://build.opensuse.org/project/new, I meet the below error message.  It seems that only administrator can do this activity. 
`Error: Admin rights are required to change projects using remote resources`
 
* Proposed configuration setting
```bash
<project name="Tizen:5.0">
  <title>Tizen 5.0 Release</title>
  <description>Tizen:5.0</description>
  <person userid="adrianSuSE" role="maintainer"/>
  <person userid="tizen" role="maintainer"/>
  <build>
    <disable/>
  </build>
  <publish>
    <disable/>
  </publish>
  <debuginfo>
    <disable/>
  </debuginfo>
  <repository name="unified">
    <download arch="x86_64" url="http://download.tizen.org/releases/weekly/tizen/unified/latest/repos/standard/packages/" repotype="rpmmd">
    </download>
    <download arch="armv7l" url="http://download.tizen.org/releases/weekly/tizen/unified/latest/repos/standard/packages/" repotype="rpmmd">
    </download>
    <download arch="aarch64" url="http://download.tizen.org/releases/weekly/tizen/unified/latest/repos/standard/packages/" repotype="rpmmd">
    </download>
    <path project="home:tizen:5.0" repository="base"/>
    <arch>x86_64</arch>
    <arch>armv7l</arch>
    <arch>aarch64</arch>
  </repository>
  <repository name="base">
    <download arch="x86_64" url="http://download.tizen.org/releases/weekly/tizen/base/latest/repos/x86_64/packages/" repotype="rpmmd">
    </download>
    <download arch="armv7l" url="http://download.tizen.org/releases/weekly/tizen/base/latest/repos/arm/packages/" repotype="rpmmd">
    </download>
    <download arch="aarch64" url="http://download.tizen.org/releases/weekly/tizen/base/latest/repos/arm64/packages/" repotype="rpmmd">
    </download>
    <arch>x86_64</arch>
    <arch>armv7l</arch>
    <arch>aarch64</arch>
  </repository>  
</project>

```

**Comment by leemgs** [comment]
@adrianschroeter PTAL

**Comment by adrianschroeter** [comment]
On Samstag, 2. Juni 2018, 11:39:10 CEST wrote Geunsik Lim:
> Deall all, 
> 
> Can we add Tizen (https://www.tizen.org/) software platform distribution such as the existing Linux distributions?
> * https://build.opensuse.org/project/

yes, we can, but ...

...
> <project name="Tizen:5.0">
..
>     <download arch="x86_64" url="http://download.tizen.org/releases/weekly/tizen/unified/latest/repos/standard/packages/" repotype="rpmmd">

this sounds a bit questionable, is 5.0 already released? Why is the directory named weekly 
then?

Also, can you point me to some https cert or GPG key so that we can verify the
downloaded binaries?

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by hennevogel** [comment]
please tell us if you still want this...
