### ISSUE TITLE
put incremental diff link into new request

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#5084]
following up on #3915 requests that are superseded have link to a diff to the new, superseding requests. From a reviewer's perspective however it would be better to have the link in the new request, as that is what the reviewer looks at.

Eg. https://build.opensuse.org/request/show/610110

**Comment by mlschroe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Have incremental diff link into new request](https://trello.com/c/jFBsE1I0/1455-have-incremental-diff-link-into-new-request)
