### ISSUE TITLE
OBS doesn't treat _link files properly for submit requests

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#5109]
# Issue Description
Today I had the following situation while processing maintenance update requests:

I've created a submission from `SUSE:SLE-15:GA/yast2-pkg-bindings-devel-doc` to `openSUSE:Leap:15.0`. The source package contains a `_link` file pointing to `yast2-pkg-bindings`. The problem is, when you accept that request (so that a new maintenance incident gets created), the sources don't get copied over to the incident - only the patchinfo is present. It seems OBS doesn't understand `_link` files in the maintenance process.

Normally, when you accept this request, you'd have a maintenance incident (e.g.: https://build.opensuse.org/project/show/openSUSE:Maintenance:6005) which contains a package called `patchinfo` and at least one more package called `$source_package_name.$target_distro` like in the [example link](https://build.opensuse.org/project/show/openSUSE:Maintenance:6005), but with the package I used to submit (`SUSE:SLE-15:GA/yast2-pkg-bindings-devel-doc`) you only have the `patchinfo` present.

I hope this was detailed enough.

Expected Result
============
Source package gets copied over in the new incident.

How to Reproduce
===============
You *must* have a maintenance setup, otherwise - for normal submission - it works as expected.

1. Create an SR: `osc sr SUSE:SLE-15:GA/yast2-pkg-bindings-devel-doc openSUSE:Leap:15.0`
2. Accept this request
3. Check what packages are present in the new incident

Further Information
===============
* Ask me, if you need help reproducing it

**Comment by mschnitzer** [comment]
Another good example is this request: https://build.opensuse.org/request/show/614320

The created maintenance project (https://build.opensuse.org/project/show/openSUSE:Maintenance:8300) doesn't have any sources.

**Comment by JanZerebecki** [comment]
Probably also the same issue: when source and destination of a submit request are the same except the _link, then OBS refuses to create the request.

**Comment by adrianschroeter** [comment]
for the original issue: This is a wanted behaviour but the original packages with local link should define their main package as devel package. That way you branch already the right package and avoid the wrong submission.

So more a setup issue.

@JanZerebecki your issue is different, please create an own issue with a reproducer please.
