### ISSUE TITLE
OBS 2.9.3 can't handle RPM 4.14 rich dependencies

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/open-build-service#5110]
# Issue Description
One of the packages I'm building attempts to retrieve `composer` in
Fedora 28 on my self-hosted OBS (v2.9.3), but I get the following
error:

```
cannot parse dependency (php-composer(composer/ca-bundle) >= 1.0 with
php-composer(composer/ca-bundle) < 2) from composer, cannot parse
dependency (php-composer(composer/semver) >= 1.0 with
php-composer(composer/semver) < 2) from composer, cannot parse
dependency (php-composer(composer/spdx-licenses) >= 1.2 with
php-composer(composer/spdx-licenses) < 2) from composer, cannot parse
dependency (php-composer(psr/log) >= 1.0 with php-composer(psr/log) <
2) from composer, cannot parse dependency
(php-composer(seld/cli-prompt) >= 1.0 with
php-composer(seld/cli-prompt) < 2) from composer, cannot parse
dependency (php-composer(seld/jsonlint) >= 1.4 with
php-composer(seld/jsonlint) < 2) from composer, cannot parse
dependency (php-composer(seld/phar-utils) >= 1.0 with
php-composer(seld/phar-utils) < 2) from composer
```

Expected Result
============
`composer` deps to resolve, and package to build

How to Reproduce
===============
1. Create a project
2. Add Fedora 28 as target distribution
3. Create a package that has `BuildRequires: composer`
4. Note the unresolvable state that returns instead of starting to build

Further Information
===============
* `obs-server` version-release: 2.9.3-49.1
* `perl-BSSolv` version-release: 0.34.0-1.12

**Comment by mlschroe** [comment]
What's the version of the 'build' package?

**Comment by Conan-Kudo** [comment]
```
build:~ # rpm -q build
build-20180111-1.4.noarch
```

**Comment by mlschroe** [comment]
Hmm, I think this is too old. Try the 'build' package from OBS:Server:Unstable.

**Comment by mlschroe** [comment]
(I.e. you need commit 34b5bfdcaa3e262f54d197a9972ebecb53c2fb77)

**Comment by Conan-Kudo** [comment]
On my test instance, I upgraded `build`, but it didn't help. I thought this is `perl-BSSolv` output, and not `obs-build`?

**Comment by mlschroe** [comment]
perl-BSSolv is just the messenger, please do not shoot it ;)

Is your Fedora 28 repo a download on demand repo?

**Comment by mlschroe** [comment]
Or do you interconnect with api.opensuse.org?

**Comment by Conan-Kudo** [comment]
@mlschroe It's fueled by api.opensuse.org interconnect superpowers ;)

**Comment by mlschroe** [comment]
This was caused because of outdated data on api.opensuse.org. Now fixed.

**Comment by kanarip** [comment]
> perl-BSSolv is just the messenger, please do not shoot it ;)
> 
> Is your Fedora 28 repo a download on demand repo?

Running OBS:Server:Unstable, and with a Fedora 28 DoD repo, this issue seems unresolved... any hints?
