### ISSUE TITLE
Can't build simple docker example in devel namespace

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#5112]
Following the examples given in recent blog posts of the OBS team, I can build a docker image in home:coolo:branches - but when I do the very same in devel:openQA it results in broken state: repository url 'http://download.opensuse.org/update/leap/42.3/oss/' cannot be handled

Note that I didn't touch the Dockerfile yet - this seems to be a rather suprising mismatch between the schedulers

**Comment by bgeuken** [comment]
Sounds like a backend bug

@M0ses ^

**Comment by M0ses** [comment]
fixed - see it building
