### ISSUE TITLE
Release Target is being released without a trigger

### ISSUE THREAD

**Issue by mkrawiec** [openSUSE/open-build-service#5113]
I recently learned about the `osc release` mechanism, the way I understand it to work by reading the official docs ([here](https://github.com/openSUSE/obs-docu/blob/34036c9f584cfbc6bb1df9cf60c51730d4435bf2/xml/obs_product_building.xml#L56)) is that when I have a devel project, the only way to release it to the release project is by `osc release`. 

It looks like this is how it works, however I noticed that overnight the repo triggered itself and released the changes (in this case service run triggered via web interface and file changed via web interface) without me triggering it. Is this a bug or a feature?

EDIT: This release shows up as revision committed at 2018-06-10 00:38 UTC, at which time I was most definitively sleeping ;)

**Comment by hennevogel** [comment]
yes this is expected behavior...
