### ISSUE TITLE
Nobody shouldn't have a homepage

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#5118]
Is it expected that the `_nobody_` user has a [homepage](https://build.opensuse.org/user/show/_nobody_)? It is not a normal user...

![image](https://user-images.githubusercontent.com/16052290/41229631-00dcc66e-6d7d-11e8-8875-a60def51a9c3.png)

**Comment by coolo** [comment]
Why shouldn't nobody not have no homepage if anyone can't have none?

**Comment by Ana06** [comment]
because nobody is not anyone. :rofl:  It is an special user we are using when there is not user logged in. It is really strange that if I log in, after a time because of any reason I get logged out and I click home, then it takes me to nobody home.... :thinking:

**Comment by coolo** [comment]
but nobody is not involved in any packages!

**Comment by Ana06** [comment]
@coolo 

> but nobody is not involved in any packages!

another reason why he doesn't need a home :rofl:

**Comment by ChrisBr** [comment]
I'm with @coolo, I don't see the point to implement code for this corner case. It is not a big issue ...

**Comment by Ana06** [comment]
@coolo 

> but nobody is not involved in any packages!

it is not true anymore :rofl: 

![image](https://user-images.githubusercontent.com/16052290/41232432-a08ae39a-6d86-11e8-993b-f75abc8c976c.png)

@ChrisBr 

> I'm with @coolo, I don't see the point to implement code for this corner case. It is not a big issue ...

Also not a big effort to implement it... I find it really confusing

**Comment by ChrisBr** [comment]
> Also not a big effort to implement it... I find it really confusing

Why? I'm really against introducing and maintaining corner case code for this...

**Comment by coolo** [comment]
I think nobody can have a home project, but what is missing here is a: "your session is expired, redirecting to /" error. Introducing a "You're a nobody, go away" doesn't sound fair to users.

**Comment by ChrisBr** [comment]
What is the state of this issue?

**Comment by hennevogel** [comment]
let's close this
