### ISSUE TITLE
Dockerfile cannot map repository

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#5130]
As I'm missing any kind of documentation on what is supported in Dockerfile, I just file everything I find strange as issue.

I have RUN zypper ar -f -G "https://download.opensuse.org/repositories/devel:/openQA:/Leap:/42.3/openSUSE_Leap_42.3" devel_openqa in devel:openQA and it's 'broken' as obs can't map this one. 

You can't seriously tell me that obs needs to be patched for every repo I need to add, right?

**Comment by M0ses** [comment]
This is a different issue than you reported - The scheduler didn't recalculate O:S:U

I`m working on your issue, a bit more patience please :-).

**Comment by mlschroe** [comment]
That's because you used 'https:' instead of 'http:'.

**Comment by mlschroe** [comment]
you need to use the 'official' url.

**Comment by coolo** [comment]
Well, you mean the url that the backend expects. Because if you click on 'Download repository' on https://build.opensuse.org/project/repository_state/devel:openQA:Leap:42.3/openSUSE_Leap_42.3 you end up on exactly the URL I gave.

**Comment by eduardoj** [comment]
Fixed in #9380. Closing.
