### ISSUE TITLE
Reviewers: Error message when a user doesn't exist is not clear

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#5152]
# Issue Description
I tried to add a reviewer on a request but the API responds with `400 bad request` and the WebUi says `Unable add review to '617333': Validation failed: Reviews is invalid`. @coolo later found out that the username was wrong.

The message `Validation failed: Reviews is invalid` doesn't say that. It should be more verbose.

Expected Result
============
Error message shows the actual error.

How to Reproduce
===============
1. Create a request
2. Request a review from a non-existent user

**Comment by coolo** [comment]
Can you try with his real accout name AndreasStieger ?

**Comment by coolo** [comment]
"Reviews is invalid" makes me believe that this is an autogenerated text :)

**Comment by mschnitzer** [comment]
@coolo oh well, thanks... It works.

"Reviews is invalid" is a Rails auto-generated message. I'll work on a fix and propose a PR later.

**Comment by coolo** [comment]
I kind of disagree with the 'good first issue' - the code responsible is pretty well hidden in the exception handling :)
