### ISSUE TITLE
creating _aggregate file from Web frontend broken

### ISSUE THREAD

**Issue by coogor** [openSUSE/open-build-service#5168]
Following up on http://bugzilla.novell.com/show_bug.cgi?id=1097179 : 
Trying to add a file to a project via webfrontend.
Description says:
The filename is taken from the uploaded file if none is provided. Alternatively, if only a filename is provided, a new empty file is created (i.e. touched).

The result is:
Error while creating '_aggregate' file: Document is empty, not allowed for aggregate. 

So, seems there is no chance to get this set up from the web frontend...

**Comment by hennevogel** [comment]
Upload a _aggregate file with the correct content? :-)
