### ISSUE TITLE
Instructions for new rspec tests are outdated

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#5176]
The spec/README says to run

```
docker-compose run --rm frontend bundle exec rake db:fixtures:load RAILS_ENV=test
docker-compose run --rm frontend script/start_test_backend
```

But this has several problems when I try to run it as specified

database does not exist, need to db:create first

then it says memcached can't start - have to set -e NO_MEMCACHED=1

Then BSSolv and other perl modules are missing to start it. At that point I gave up

**Comment by coolo** [comment]
Oh, I forgot: the default config wants to access backend:3200 - but that is forbidden by webmock

**Comment by coolo** [comment]
I would like to fix https://travis-ci.org/coolo/open-build-service/jobs/394604017 but I can't :(

**Comment by ChrisBr** [comment]
Yup, we should fix that :+1:
