### ISSUE TITLE
[packages] travis commit lets OBS package builds fail

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#5201]
# Issue Description
Commit 09dfe253d2c74838502b49eb5f4a77d489d2fcd7 causes the package builds to fail

Expected Result
============
Before the commit, the package builds worked

How to Reproduce
===============
1. Use commit aa0c1fcbc87b15eb77fcbafaf51a6836b771f88e
2. Package this source
3. Build works
4. Do the same with current git master of commit 09dfe253d2c74838502b49eb5f4a77d489d2fcd7 or later does not work

Further Information
===============
* See logfile of O:S:U on obs-server on b.o.o: [here](https://build.opensuse.org/package/live_build_log/OBS:Server:Unstable/obs-server/SLE_12_SP3/x86_64)

**Comment by hennevogel** [comment]
We get notifications about packages failing to build, thanks anyway :)

**Comment by mmohring** [comment]
I know, but I wanted to tell which change caused it.
