### ISSUE TITLE
[api] current git master apidelayed job and db migrations fails

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#5222]
When installing the current git master, and you call RAILS_ENV="production" rails.ruby2.5 db:migrate:with_data, then you get an error. Dito when you start the apidelayed jobs.

Expected Result
============
Both should not error out.

How to Reproduce
===============
1. Install new git master
2. cd /srv/www/obs/api/db/migrate
3. RAILS_ENV="production" rails.ruby2.5 db:migrate:with_data

rails aborted!
LoadError: cannot load such file -- rubocop/rake_task
/srv/www/obs/api/lib/tasks/dev.rake:82:in `block (3 levels) in <top (required)>'
/srv/www/obs/api/lib/tasks/dev.rake:81:in `block (2 levels) in <top (required)>'
/srv/www/obs/api/lib/tasks/dev.rake:80:in `block in <top (required)>'
/srv/www/obs/api/lib/tasks/dev.rake:6:in `<top (required)>'
/srv/www/obs/api/Rakefile:7:in `<top (required)>'
bin/rails:4:in `require'
`bin/rails:4:in `\<main\>'`
(See full trace by running task with --trace)

Also starting the apidelayed jobs fails.
1. rcobsapidelayed start
redirecting to systemctl start obsapidelayed.service
Job for obsapidelayed.service failed because the control process exited with error code. See "systemctl status obsapidelayed.service" and "journalctl -xe" for details.

Further Information
===============
* This happens with git master fb44389b2438ec6ed6627e48bd5cadf5e44cd15d
* Rest of the OBS System works
* Due to obsapidelayed.service not correctly started, the search daemons do not run causing the WebUI search to fail

**Comment by mmohring** [comment]
rcobsapidelayed start makes the same error as the db migration:

Jun 26 21:08:07 api obsapidelayed[1334]: delayed_job.1040: process with pid 1633 started.
Jun 26 21:08:14 api obsapidelayed[1334]: delayed_job.1050: process with pid 1661 started.
Jun 26 21:08:14 api obsapidelayed[1334]: ..done
Jun 26 21:08:18 api obsapidelayed[1334]: Starting OBS searchd daemon rails aborted!
Jun 26 21:08:18 api obsapidelayed[1334]: LoadError: cannot load such file -- rubocop/rake_task
Jun 26 21:08:18 api obsapidelayed[1334]: /srv/www/obs/api/lib/tasks/dev.rake:5:in `<top (required)>'
Jun 26 21:08:18 api obsapidelayed[1334]: /srv/www/obs/api/Rakefile:7:in `<top (required)>'
Jun 26 21:08:18 api obsapidelayed[1334]: bin/rails:4:in `require'
Jun 26 21:08:18 api obsapidelayed[1334]: bin/rails:4:in `<main>'
Jun 26 21:08:18 api obsapidelayed[1334]: (See full trace by running task with --trace)
Jun 26 21:08:18 api obsapidelayed[1334]: ..failed

**Comment by mmohring** [comment]
There is no rake_task in the git.

**Comment by coolo** [comment]
Also fixed with #5228

**Comment by mmohring** [comment]
Checked ad5379e1c954ec9d01f4fee6ae197005721340be, works.
