### ISSUE TITLE
Broken search for disturl in search page

### ISSUE THREAD

**Issue by M0ses** [openSUSE/open-build-service#5232]
# Issue Description
Searching for disturl's of multibuild container results in search page is broken

Expected Result
============
Find and redirect to the correct source version of the package/container

How to Reproduce
===============
1. Go to https://build.opensuse.org/search
2. Enter a multibuild disturl of a container 
   (e.g. obs://build.opensuse.org/devel:CaaSP:1.0/container/023e3a387f20a6134d7ce9bbb5f4a8a5-opensuse-tumbleweed-image:docker)
3. See error "Sorry, this disturl does not compute... "

Further Information
===============
* Search for "obs://build.opensuse.org/devel:CaaSP:1.0/container/023e3a387f20a6134d7ce9bbb5f4a8a5-opensuse-tumbleweed-image" works

**Comment by hennevogel** [comment]
Multibuild. The new remote package. Oh well...
