### ISSUE TITLE
[production][staging_projects#show] wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#5233]
staging_projects#show threw this 55 times
<pre>
wrong number of arguments (given 1, expected 0)
</pre>
[https://api.opensuse.org/project/staging_projects/openSUSE:Factory/D?format=json](https://api.opensuse.org/project/staging_projects/openSUSE:Factory/D?format=json)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b334d78d3a63b00061f3267)

**Comment by DimStar77** [comment]
Started happening this morning, June 27 2018 - 10:40 CEST

**Comment by vpereira** [comment]
```
$ osc api '/about'
<about>
  <title>Open Build Service API</title>
  <description>API to the Open Build Service</description>
  <revision>2.10~alpha.20180627T093554.891fc35b0</revision>
  <last_deployment>2018-06-27 08:37:33 +0000</last_deployment>
  <commit>891fc35b01436703e03f28a7cfd70f99c2e12f4b</commit>
</about>
```

**Comment by DavidKang** [comment]
@DimStar77, we are working on it.

**Comment by vpereira** [comment]
it is fixed now. thank you @DavidKang
