### ISSUE TITLE
[production][package#submit_request_dialog] invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#5236]
package#submit_request_dialog threw this 8 times
<pre>
invalid byte sequence in UTF-8
</pre>
[https://build.opensuse.org/package/submit_request_dialog/devel:languages:perl:autoupdate/perl-Cpanel-JSON-XS?revision=7](https://build.opensuse.org/package/submit_request_dialog/devel:languages:perl:autoupdate/perl-Cpanel-JSON-XS?revision=7)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b3381457333f10006c429fb)

**Comment by ChrisBr** [comment]
Problem is the gsub in commit_message in 
```
  def commit_message(target_project, target_package)
    result = ''
    changes_files.each do |changes_file|
      source_changes = PackageFile.new(package_name: name, project_name: project.name, name: changes_file).content
      target_changes = PackageFile.new(package_name: target_package, project_name: target_project, name: changes_file).content
      result << source_changes.try(:chomp, target_changes)
    end
    # Remove header and empty lines
    result.gsub!('-------------------------------------------------------------------', '')
    result.gsub!(/(Mon|Tue|Wed|Thu|Fri|Sat|Sun) ([A-Z][a-z]{2}) ( ?[0-9]|[0-3][0-9]) .*/, '')
    result.gsub!(/^$\n/, '')
    result
  end
```

https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/package.rb#L362

**Comment by ChrisBr** [comment]
API apparently works as osc is formatting the changes file itself and it does not happen server side.

**Comment by bmwiedemann** [comment]
here is a hexdump of the the relevant section of the .changes file
```
00001e50  2e 0a 20 20 20 20 20 20  20 20 20 20 20 20 69 2e  |..            i.|
00001e60  65 2e 20 64 65 63 6f 64  65 20 22 ed a0 81 ed b0  |e. decode ".....|
00001e70  82 5c 78 7b 31 30 32 30  34 7d 22 0a 20 20 20 20  |.\x{10204}".    |
```

vim shows the `ed a0 81 ed b0 82` bytes as two chars: `<d801><dc02>`

**Comment by eduardoj** [comment]
Exception not found in Errbit any more. Closing.
