### ISSUE TITLE
staging dashboard: make openQA optional

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#5237]
The staging dashboard so far requires some reply from openQA. In order to bootstrap projects it would be nice if the could be made optional, so when it comes to the testing stage just skip it. Maybe use some attributes on the project to allow configuring such aspects?

**Comment by lnussel** [comment]
concrete, I'd like to get https://build.opensuse.org/project/staging_projects/openSUSE:Backports:SLE-15 somewhat operational :)

**Comment by JanZerebecki** [comment]
With the new staging implementation this seems to work now. Docs: https://openbuildservice.org/help/manuals/obs-best-practices/cha.obs.best-practices.webuiusage.html#staging_how_to

**Comment by coolo** [comment]
with the old one as well :)
