### ISSUE TITLE
GET /source/<project>/_attribute/<attribute> returns all attributes

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/open-build-service#5240]
# Issue Description

Rather than return a specific attribute as [documentation indicates](https://build.opensuse.org/apidocs/index#32) `GET /source/<project>/_attribute/<attribute>` returns all attributes.

Expected Result
============
Would work as documented.

How to Reproduce
===============

`osc api /source/openSUSE:Factory/_attribute/OSRT:Config`

Further Information
===============

Broke lovely move to depend on this with workaround in openSUSE/openSUSE-release-tools#1598.

**Comment by jberry-suse** [comment]
Either recently broken or was hotfixed on IBS as this works there.

**Comment by coolo** [comment]
Thanks for the report, there simply was no test case that not *more* is returned
