### ISSUE TITLE
[production][request#global_command] illegal parameter type to User#can_modify_project?: NilClass

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#5243]
request#global_command threw this 22 times
<pre>
illegal parameter type to User#can_modify_project?: NilClass
</pre>
[https://api.opensuse.org/request?cmd=create](https://api.opensuse.org/request?cmd=create)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b34962caa96340006d718c1)

**Comment by DimStar77** [comment]
happens since this morning, reproducibly when creating a new SR, like e.g.

```osc sr GNOME:Apps gnucash openSUSE:Factory -m 'Update to 3.2'```

**Comment by bgeuken** [comment]
This is solved now. Was caused by a broken hotfix. Sorry for that
