### ISSUE TITLE
package#submit_request - Mysql2::Error: Data too long for column 'payload'

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#5245]
package#submit_request threw this 2 times
<pre>
Mysql2::Error: Data too long for column &#39;payload&#39; at row 1: INSERT INTO `events` (`eventtype`, `payload`, `created_at`, `updated_at`) VALUES (&#39;Event::RequestCreate&#39;, &#39;{\&quot;author\&quot;:\&quot;mvarlese\&quot;,\&quot;description\&quot;:\&quot;- Update to 18.02.2; some of the changes are:\\r\\n  * Added function to allow releasing internal EAL resources on exit\\r\\n  * Added igb, ixgbe and i40e ethernet driver to support RSS with flow API\\r\\n  * Updated i40e driver to support PPPoE/PPPoL2TP\\r\\n  * Added MAC loopback support for i40e\\r\\n  * Added support of run time determination of number of queues per i40e VF\\r\\n  * Updated mlx4/mlx5 driver\\r\\n  * Added NVGRE and UDP tunnels support in Solarflare network PMD\\r\\n  * Added AVF (Adaptive Virtual Function) net PMD\\r\\n  * Added feature supports for live migration from vhost-net to vhost-user\\r\\n  * Updated the AESNI-MB PMD\\r\\n  * Updated the DPAA_SEC crypto driver to support rte_security\\r\\n  * Added New eventdev Ordered Packet Distribution Library (OP
</pre>
[https://build.opensuse.org/package/submit_request/network/dpdk](https://build.opensuse.org/package/submit_request/network/dpdk)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b30e46eb1f00a0009d50e77)

**Comment by eduardoj** [comment]
It seems it happens again.

**Comment by eduardoj** [comment]
Exception not found in Errbit any more. Closing.
