### ISSUE TITLE
[production][distributions#show] undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#5249]
distributions#show threw this 11 times
<pre>
undefined method `name&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/project/dashboard/openSUSE:Backports:SLE-15](https://build.opensuse.org/project/dashboard/openSUSE:Backports:SLE-15)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b2b6becdc0e52000a16269a)

**Comment by DavidKang** [comment]
Could be because they don't have `rings`?

**Comment by coolo** [comment]
very likely
