### ISSUE TITLE
CircleCI: Unable to join IRC channel #opensuse-buildservice

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#5310]
# Issue Description
CircleCI is sometimes unable to join IRC channel #opensuse-buildservice.

Expected Result
============
CircleCI is able to join IRC channel #opensuse-buildservice

How to Reproduce
===============
1. Create a pull request
2. Wait for CircleCI to run
3. It will either be able or unable to join IRC channel #opensuse-buildservice

Further Information
===============
One example with the error: https://circleci.com/gh/openSUSE/open-build-service/2847

**Comment by ChrisBr** [comment]
@hennevogel IIRC you wanted to look into that, right?

**Comment by hennevogel** [comment]
I did not get around to do that...

**Comment by ChrisBr** [comment]
> I did not get around to do that...

Do you get around to do it soon? IIRC the last time I checked I did not have permissions to do the change ...

**Comment by coolo** [comment]
I created a ticket

>Hi Stephan,

>Thanks again for bringing this to our attention. I was able to reproduce this with both oftc and freenode. It looks like for some reason those networks (and I assume others) are refusing our IRC connection.

>The 504 timeout comes from our API service which attempts to connect to IRC in order to send a notification.

>I escalated this issue, but I do not have an ETA for a resolution. Let me know if you run into any other issues in the meantime.

**Comment by dmarcoux** [comment]
@coolo: Is the issue public? If so, I would link to it here.

**Comment by coolo** [comment]
Not public

**Comment by dmarcoux** [comment]
CircleCI doesn't notify IRC anymore. We agreed to deactivate this last week. It was changed in the web interface [here](https://circleci.com/gh/openSUSE/open-build-service/edit#hooks)
