### ISSUE TITLE
A job is scheduled for a long time despite free workers

### ISSUE THREAD

**Issue by jirislaby** [openSUSE/open-build-service#5334]
Ok, so this is a long-standing issue I was asking about on various IRC channels and it still continues to happen without any resolution. So let's track it here.

# Issue Description
We have a project openSUSE:Factory:zSystems and there is gcc8 in a "scheduled" state for quite some time. Despite there were/are free s390x builders according to the status page, the job was not built in the past week yet.

Expected Result
============
gcc8 is built

How to Reproduce
===============
1. Go to https://build.opensuse.org/package/show/openSUSE:Factory:zSystems/gcc8

**Comment by adrianschroeter** [comment]
I suspect that there were no free workers that met the constraints of the package (16G disk and 4G memory). I don't see a bug here.
