### ISSUE TITLE
[webui] new package submission diff from devel to Factory links to the original home: project

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/open-build-service#5336]
# Issue Description

A [submission](https://build.opensuse.org/request/show/621687) of a [new package](https://build.opensuse.org/package/show/devel:libraries:c_c++/libredwg) from a [devel project](https://build.opensuse.org/project/show/devel:libraries:c_c++) to (in this case) [openSUSE:Factory](https://build.opensuse.org/project/show/openSUSE:Factory) contains in the diff view [links to a third project](https://build.opensuse.org/package/view_file/home:AndreasStieger/libredwg/libredwg-rpmlintrc?rev=3) - the `home:` project the project was originally submitted from. 

Expected Result
============

Web UI diff viewer links to devel project files only, not to home project.

How to Reproduce
===============
1. make a new package in a home: project
2. submit to devel project
3. accept to devel project
3. delete package in home: project
4. submit package from devel project to Factory
5. examine factory submission diff
6. click on a diffable file

Further Information
===============
* [SR#621687](https://build.opensuse.org/request/show/621687) from [devel:libraries:c_c++/libredwg](https://build.opensuse.org/package/show/devel:libraries:c_c++/libredwg) to [openSUSE:Factory](https://build.opensuse.org/project/show/openSUSE:Factory)
* Links to [home:[...]](https://build.opensuse.org/package/view_file/home:AndreasStieger/libredwg/libredwg.keyring?rev=3)

**Comment by coolo** [comment]
I assume this is a consequence of the source diff cache in the backend - and just for display

**Comment by coolo** [comment]
#3787 is related if not the same

**Comment by mlschroe** [comment]
This is fixed since a while.
