### ISSUE TITLE
OBS not building for Ubuntu/Debian

### ISSUE THREAD

**Issue by jfha73** [openSUSE/open-build-service#534]
Hey guys,

I have the following files on my private OBS appliance:

debian.changelog
debian.control
debian.rules
debian.copyright
mypackage_version.dsc
mypackage_version.tar.gz

But I keep getting this error:

dpkg-source: error: cannot fstat file /usr/src/packages/SOURCES.DEB/mypackage_version.tar.gz: No such file or directory

And when I add a second source package like mypackage_version.tar.bz2 it says it has too many source files and needs only one.

I don't understand this behavior.

Thanks.

![obs](https://f.cloud.github.com/assets/534716/1756027/1d94e2e8-666e-11e3-8a11-a6435382df52.jpg)

**Comment by mschnitzer** [comment]
Probably a backend issue - not sure (even if it's still valid or not).

**Comment by vpereira** [comment]
closed for now, as OBS is able to build packages for debian and ubuntu. If you have any doubt about how to use OBS, please let's talk about it in our mailing list.

thank you!
