### ISSUE TITLE
Install check fails when package upgrade changes directory to symlink

### ISSUE THREAD

**Issue by hramrach** [openSUSE/open-build-service#5344]
[  404s] Wrote: /home/abuild/rpmbuild/SRPMS/go1.6-1.6.4-lp150.25.1.src.rpm
[  707s] Wrote: /home/abuild/rpmbuild/RPMS/armv7hl/go1.6-1.6.4-lp150.25.1.armv7hl.rpm
[  711s] Wrote: /home/abuild/rpmbuild/RPMS/armv7hl/go1.6-doc-1.6.4-lp150.25.1.armv7hl.rpm
[  711s] Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.KcIUiB
[  711s] + umask 022
[  711s] + cd /home/abuild/rpmbuild/BUILD
[  711s] + cd go
[  711s] + /usr/bin/rm -rf /home/abuild/rpmbuild/BUILDROOT/go1.6-1.6.4-lp150.25.1.arm
[  712s] + exit 0
[  712s] ... checking for files with abuild user/group
[  713s] ... running 00-check-install-rpms
[  713s] ... installing all built rpms
[  713s] Preparing packages...
[  713s] go1.6-1.6.4-lp150.25.1.armv7hl
[  723s] error: unpacking of archive failed on file /usr/lib/go/1.6/src/archive: cpio: File from package already exists as a directory in system
[  723s] error: go1.6-1.6.4-lp150.25.1.armv7hl: install failed
[  723s] go1.6-doc-1.6.4-lp150.25.1.armv7hl
[  724s] error: go1.6-1.6.4-lp150.10.1.armv7hl: erase skipped
[  724s] failed to install rpms, aborting build

Upon package content inspection it turns out that /usr/lib/go/1.6/src/archive changed from directory in old package to symlink in new package.

Expected Result
============
install check works

How to Reproduce
===============
Rebuild go1.6 (source) with go1.6 (upstream binary distribution)

Presumably a different test could be crafted

Further Information
===============
https://build.opensuse.org/package/show/home:michals:arduino/go1.6
https://build.opensuse.org/project/monitor/home:michals:test?arch_x86_64=1&building=1&defaults=0&repo_openSUSE_Tumbleweed=1

**Comment by coolo** [comment]
that's how rpm works (and fails) and that's what the check is testing. You need to fix your package to cope with upgrades.

**Comment by hramrach** [comment]
Do you mean that rpm updates the files in-place without any means of rollback if the installation fails?
