### ISSUE TITLE
[production][] undefined method `can_modify?' for nil:NilClass

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#5351]
threw this 6 times
<pre>
undefined method `can_modify?&#39; for nil:NilClass
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b4127641e40e80006f13a2e)

**Comment by coolo** [comment]
261 times by now

**Comment by coolo** [comment]
@eduardoj please have a look at 7168 - perhaps this is enough?

**Comment by eduardoj** [comment]
@coolo:

> @eduardoj please have a look at 7168 - perhaps this is enough?

Not happening in 8 days, most probably since 7168 was deployed. Closing. Thanks!
