### ISSUE TITLE
Can I use open build service to cross-build docker images for ARM on x86 machine ?

### ISSUE THREAD

**Issue by Zied-Guesmi** [openSUSE/open-build-service#5353]
Maybe it's not related directly to OBS but I would like to know if I can use obs to build docker images for ARM architectures (Raspberry pi) on a x86 server. If not, are you thinking about supporting it ?

**Comment by hennevogel** [comment]
@Zied-Guesmi I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
