### ISSUE TITLE
Package rebuilds triggered without (explicit) request

### ISSUE THREAD

**Issue by fscheiner** [openSUSE/open-build-service#5358]
During a `yum update` in a CentOS6 VM I noticed a new package revision for a package created by myself and built on the OBS. As I didn't rebuild this package since more than a year ago, I started to wonder why this has happened and what exactly has actually happened.

## Details ##

Checking the available information (build logs and directory listings of download.opensuse.org) I recognized that this seems to have happened for the CentOS_CentOS-6 packages:

rebuild took place on 2018-07-04:

* [CentOS_CentOS-6 gtransfer with gt dep build log i586](https://build.opensuse.org/package/live_build_log/home:frank_scheiner:gtransfer_with_gt_dep/gtransfer/CentOS_CentOS-6/i586)
* [CentOS_CentOS-6 gtransfer with gt dep build log x86_64](https://build.opensuse.org/package/live_build_log/home:frank_scheiner:gtransfer_with_gt_dep/gtransfer/CentOS_CentOS-6/x86_64)
* [CentOS_CentOS-6 gtransfer w/o gt dep build log i586](https://build.opensuse.org/package/live_build_log/home:frank_scheiner:gtransfer_without_gt_dep/gtransfer/CentOS_CentOS-6/i586)
* [CentOS_CentOS-6 gtransfer w/o gt dep build log x86_64](https://build.opensuse.org/package/live_build_log/home:frank_scheiner:gtransfer_without_gt_dep/gtransfer/CentOS_CentOS-6/x86_64)

...and the CentOS_7 packages:

rebuild took place on 2018-05-12:

* [CentOS7 gtransfer with gt dep build log x86_64](https://build.opensuse.org/package/live_build_log/home:frank_scheiner:gtransfer_with_gt_dep/gtransfer/CentOS_7/x86_64)
* [CentOS7 gtransfer w/o gt dep build log x86_64](https://build.opensuse.org/package/live_build_log/home:frank_scheiner:gtransfer_without_gt_dep/gtransfer/CentOS_7/x86_64)

...and the ScientificLinux_7 packages:

rebuild took place on 2018-05-04:

* [ScientificLinux_7 gtransfer with gt dep build log x86_64](https://build.opensuse.org/package/live_build_log/home:frank_scheiner:gtransfer_with_gt_dep/gtransfer/ScientificLinux_7/x86_64)
* [ScientificLinux_7 gtransfer w/o gt dep build log x86_64](https://build.opensuse.org/package/live_build_log/home:frank_scheiner:gtransfer_without_gt_dep/gtransfer/ScientificLinux_7/x86_64)

... resulting in new package revisions for these OSes available for download. All other OS specific packages available on [A](https://build.opensuse.org/package/show/home:frank_scheiner:gtransfer_with_gt_dep/gtransfer) and [B](https://build.opensuse.org/package/show/home:frank_scheiner:gtransfer_without_gt_dep/gtransfer) were (correctly!) build on 2017-04-20.

The same thing (even at the same three dates!) happened to the tgftp packages available on [C](https://build.opensuse.org/package/show/home:frank_scheiner:gtransfer_with_gt_dep/tgftp) and [D](https://build.opensuse.org/package/show/home:frank_scheiner:gtransfer_without_gt_dep/tgftp).

****

I was definitely not logged into the OBS on July 4th of 2018 (and I actually don't remember any logins in May) and have definitely not requested a rebuild of my packages on July 4th 2018 at about 01:56:37 UTC 2018. I also have no reason to consider my OBS account being compromised.

So the question is, what could trigger such (automatic) rebuilds? And did other OBS users face similar issues recently?

**Comment by coolo** [comment]
https://build.opensuse.org/packages/gtransfer/build_reason/home:frank_scheiner:gtransfer_with_gt_dep/CentOS_CentOS-6/i586 - the centos repo was updated.

**Comment by fscheiner** [comment]
@coolo: 
I see. Didn't knew this _build_reason_ functionality. Are these automatic rebuilds a new feature, as I didn't notice such rebuilds during the time I'm using OBS (since 2012)?

And the reason why this only affected the OSes I listed above is a (mis)configuration on my side? Or asked differently, why didn't this happen for the other OSes, too (assuming that changes in RHEL predate a repo change of the centos repo)?

**Comment by coolo** [comment]
automatic rebuilds is basically *the* feature of obs. If you want to avoid automatic rebuild you actually have to read docu - there is not even a UI for it:
https://en.opensuse.org/openSUSE:Build_Service_Concept_build_scheduling_strategies

**Comment by fscheiner** [comment]
It's not that I want to avoid automatic rebuilds, they were just unexpected in my case (the two packages mentioned above are just `noarch` packages).

Even more unexpected as those automatic rebuilds don't seem to happen for the other OSes or OS repositories (i.e. `CentOS_CentOS-5`, `RHEL_7`, `RedHat_RHEL-5`, `RedHat_RHEL-6`, `SLE_10_SDK`, `SLE_11`, `ScientificLinux_6`) for a reason unknown to me right now. Don't these repos get updated, too over time, just like e.g. `CentOS_CentOS-6`?

**Comment by coolo** [comment]
I can't say, this is done by the admins of build.oo on request
