### ISSUE TITLE
docker image build fails as "unresolvable" when specifying a package version with zypper

### ISSUE THREAD

**Issue by SergioAtSUSE** [openSUSE/open-build-service#5359]
# Issue Description

When building a docker image on OBS using docker build, using zypper to install packages available on the repositories, it is not possible to specify the package version.

When specifying the version, the build fails as unresolvable in OBS, but works building locally, and works building an image, running a container from that image and installing the package specifying the version.

See an example here: https://build.opensuse.org/package/show/home:SLindoMansilla:branches:openSUSE:Templates:Images:42.3/bug_zypper_in_package-version

When the package version is not specified, it works.

See an example here: https://build.opensuse.org/package/show/home:SLindoMansilla:branches:openSUSE:Templates:Images:42.3/gedit.jupiter

Expected Result
============

I would like to specify the specific package version so I can be sure that I am labeling the image properly after the package version used. I would expect my build to fail when the version is really not available to force me change the version number for the package and the image tag. But when the version specified is available, it should not complaint as unresolvable.

How to Reproduce
===============

1. Open https://build.opensuse.org/image_templates
2. Create a new **Container built using docker tool**
3. Use this Docker file
    ```Dockerfile
    #!BuildTag: my_container
    FROM opensuse:42.3

    RUN zypper --gpg-auto-import-keys ref
    RUN zypper --non-interactive install --force-resolution gedit-3.20.2-3.24

    ENTRYPOINT [ "/bin/bash" ]
    ```
4. See error `nothing provides gedit-3.20.2-3.24` (the version exists, it is instalable locally and is the version installed when not specifying the version.

Further Information
===============
* https://build.opensuse.org

**Comment by mlschroe** [comment]
Yes, the dockerfile parser in OBS can't do all the magic zypper does, because it does not have the repository metadata like zypper. So it can't tell if you're looking for a package with name `gedit-3.20.2-3.24` or a package `gedit` with version `3.20.2-3.24`.

Please use the unambiguous `gedit=3.20.2-3.24`.

**Comment by SergioAtSUSE** [comment]
That works :smiley: thanks!
