### ISSUE TITLE
Inability to build CentOS appliance: nothing provides kiwi-image:iso

### ISSUE THREAD

**Issue by pda14** [openSUSE/open-build-service#5360]
# Issue Description
Adding default centos-07.0-JeOS description to OBS project results in unresolvable project state.  Error message is `nothing provides kiwi-image:iso`

Expected Result
============
Something other than "unresolvable" state, maybe even successful build :)

How to Reproduce
===============
1. Create new project, create package, add repositories to build against(including kiwi).
`  <repository name="images">
    <path project="openSUSE.org:Virtualization:Appliances:Builder" repository="CentOS_7"/>
    <path project="openSUSE.org:CentOS:CentOS-7" repository="standard"/>
    <arch>x86_64</arch>
  </repository>`
2. Add centos-07.0-JeOS.kiwi to package, replace default repository entries with `<source path="obsrepositories:/"/>.` Comment out unneeded image types. Choose iso image type.
3. See error `nothing provides kiwi-image:iso`

Further Information
===============
Private server version is 2.9.3
There's public project i found with somehow similar problem with Ubuntu image. [https://build.opensuse.org/package/show/devel:kanku:images/ubuntu-xenial-JeOS#](url)

I know that kiwi-image:iso dependency can be found in [http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/openSUSE_Leap_42.3/](url) but if i add this repo then there will be another dependency problems related to CentOS and openSUSE packages conflict(Package X obsoletes package Y, etc...)

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
