### ISSUE TITLE
Branch and stay in revision is broken

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#5365]
When being in a package revision, for example [server:database/mongodb rev 52](https://build.opensuse.org/package/show/server:database/mongodb?rev=52), and clicking branch and stay in current revision:

![image](https://user-images.githubusercontent.com/16052290/42681996-908bb714-8689-11e8-9241-5dcaa418c46d.png)

it is branching the newest revision, instead of the one I selected:

![image](https://user-images.githubusercontent.com/16052290/42682065-c71c17f6-8689-11e8-8ccf-ba665b8a946f.png)

**Comment by coolo** [comment]
No, the revision is 52:
https://build.opensuse.org/package/view_file/home:ammartinez:branches:server:database/mongodb/_link?expand=0

The webui is very bad in displaying such infos though

**Comment by Ana06** [comment]
@coolo 

> The webui is very bad in displaying such infos though

then we should change this... it is really confusing :confused:

**Comment by ederag** [comment]
Trying to branch https://build.opensuse.org/package/show/KDE:Applications/okular?rev=71#
`More options>Stay on current revision (#71)`
The resulting repo contains the last files, not the 71 ones.
(on the gui as well as in the locally checked out repo)
So at least in this case there is an issue deeper than just gui display.
