### ISSUE TITLE
[webui] gravatars loaded from a non-secure page, giving mixed (insecure) display content warning

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/open-build-service#5388]
# Issue Description

The build service web ui references user avatars from gravatar. It does so via an explicit `http://` URL. In many Browsers including Mozilla Firefox this throws a mixed content warning.

Expected Result
============

Do not reference the gravatar images using an explicit URL scheme. Use a protocol relative URI, e.g. `<img src="//example.com/image.png"`

How to Reproduce
===============
1. Go to main page (via HTTPS)
2. Navigate to any page showing a gravatar
3. Check mixed content warning

Further Information
===============
* https://build.opensuse.org/

`Loading mixed (insecure) display content “http://www.gravatar.com/avatar/6x?s=20&d=wavatar” on a secure page`

**Comment by ChrisBr** [comment]
cc @eduardoj 
there was also a error / warning in openQA
