### ISSUE TITLE
infinite build for badhost

### ISSUE THREAD

**Issue by KostyaSha** [openSUSE/open-build-service#540]
When time missmatch obsworker showed as available for obs server, it accept builds but then fail to send build results with "rpc error". Dispatcher constantly assign this job again to this worker, so it livelock...

**Comment by mlschroe** [comment]
There was a bug in the badhost handling, now fixed.

**Comment by KostyaSha** [comment]
:) thanks

**Comment by KostyaSha** [comment]
Could you link to commit that fixed it?
