### ISSUE TITLE
Mysql2::Error: WSREP has not yet prepared node for application use

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#5413]
monitor#update_building threw this 12 times
<pre>
Mysql2::Error: WSREP has not yet prepared node for application use: COMMIT
</pre>
[https://build.opensuse.org/monitor/update_building](https://build.opensuse.org/monitor/update_building)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b3f39d411a89f000630250b)

**Comment by hennevogel** [comment]
deadlock fallout. no need for an issue as this will change all the time until you have figured out the deadlock...
