### ISSUE TITLE
Mysql2::Error: Deadlock: wsrep aborted transaction

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#5414]
package#update_build_log threw this 11 times
<pre>
Mysql2::Error: Deadlock: wsrep aborted transaction: COMMIT
</pre>
[https://build.opensuse.org/package/update_build_log/home:Mister_Magister:branches:OBS:AppImage:Templates/AppImageTemplate/AppImage.arm/armv7l?status=building&amp;offset=527847%3B&amp;initial=0&amp;_=1530869355419](https://build.opensuse.org/package/update_build_log/home:Mister_Magister:branches:OBS:AppImage:Templates/AppImageTemplate/AppImage.arm/armv7l?status=building&amp;offset=527847%3B&amp;initial=0&amp;_=1530869355419)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b3f39b911a89f0006302505)

**Comment by hennevogel** [comment]
We really do not need to track the deadlocks in issues. The message and involved stuff will just always be different....
