### ISSUE TITLE
[production][public#binary_packages] undefined method `project' for nil:NilClass

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#5418]
public#binary_packages threw this 1 times
<pre>
undefined method `project&#39; for nil:NilClass
</pre>
[https://api.opensuse.org/public/binary_packages/home:lukho:copyq/CopyQ](https://api.opensuse.org/public/binary_packages/home:lukho:copyq/CopyQ)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b519ce9d08da0000ccd4d07)

**Comment by hennevogel** [comment]
does not happen anymore...
