### ISSUE TITLE
Missing BuildRequires in a chroot

### ISSUE THREAD

**Issue by pda14** [openSUSE/open-build-service#5424]
# Issue Description
OBS doesn't determine BuildRequires if .spec file contains strings below: (it's a [grub2](http://vault.centos.org/7.5.1804/os/Source/SPackages/grub2-2.02-0.65.el7.centos.2.src.rpm) from CentOS.)
>%ifarch %{efi_arch}
>BuildRequires:	pesign >= 0.99-8
>%endif

%efi_arch macro defined in a separate file. Such %ifarch condition makes build unsuccessful because pesign package missing in a chroot. I'm not saying about problem where packages with same name has different arch, seems like its limitation.

How to Reproduce
===============
1. Uncomment strings with 32-bit BuildRequires
2. Build
3. See error about missing pesign in a chroot.

Further Information
===============
Build will be successful If i explicitly define arches instead of macro.
Server version is 2.9.3

**Comment by coolo** [comment]
the scheduler only evaluates macros it knows about - from the project config. It won't open files of other packages for that.
