### ISSUE TITLE
[production][] SSL_connect returned=1 errno=104 state=SSLv3 read server hello A: unknown alert type

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#5426]
threw this 10 times
<pre>
SSL_connect returned=1 errno=104 state=SSLv3 read server hello A: unknown alert type
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b3ab293b7de8000103052ba)

**Comment by coolo** [comment]
at that day (it's been a while) rabbitmq was down

**Comment by eduardoj** [comment]
Right. Closing.
