### ISSUE TITLE
[production][project#create] <status code="400">
  <summary>projid 'home:in4ops:_todo' is illegal</summary>
</status>


### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#5428]
project#create threw this 0 times
<pre>
&lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;projid &#39;home:in4ops:_todo&#39; is illegal&lt;/summary&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/project/create](https://build.opensuse.org/project/create)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b4f5399bf3c6d0006e8211c)

**Comment by coolo** [comment]
Same as https://github.com/openSUSE/open-build-service/issues/4429

**Comment by coolo** [comment]
Oh wait - not quiet
