### ISSUE TITLE
api route: /project/staging_projects/$PROJCT?format=json: no more 'package'

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#5465]
Since recently ( noticed it today around lunch time CEST ) , the api call

/project/staging_projects/openSUSE:Factory?format=json

no longer contains the 'package: $name' line in the provided json file. This is interpreted by the release manager's staging scripts; having this attribute removed from the provided json file breaks those scripts.

A potential source for the error being introduced could be https://github.com/openSUSE/open-build-service/pull/5440

**Comment by coolo** [comment]
I guess we need to know what fields are expected in the JSON so we can hardwire this in a test

**Comment by hennevogel** [comment]
Cool. U-Boot APIs!

![U-Boot APIs](https://user-images.githubusercontent.com/514785/43159841-c8a61632-8f83-11e8-842c-3797194e745f.gif)

**Comment by nilxam** [comment]
FYI the similar issue appears on staging check command, `package` tag is lost from `obsolete_requests`.

    File "/home/maxlin_factory/.osc-plugins/osc-staging.py", line 437, in do_staging 
      CheckCommand(api).perform(prj, opts.old)
    File "/home/maxlin_factory/.osc-plugins/osclib/check_command.py", line 128, in perform
      print('\n'.join(self._check_project(project)))
    File "/home/maxlin_factory/.osc-plugins/osclib/check_command.py", line 110, in _check_project
      report.extend(self._report(info, True))
    File "/home/maxlin_factory/.osc-plugins/osclib/check_command.py", line 49, in _report
      report.append('   - %s: %s' % (r['package'], r['state']))
    KeyError: 'package'

**Comment by bgeuken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix the json API for staging project controller](https://trello.com/c/vyKFRvi8/1481-fix-the-json-api-for-staging-project-controller)
