### ISSUE TITLE
DataTables warning on users/tasks page

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#5472]
# Issue Description
When accessing https://build.opensuse.org/user/tasks, I get a Datatables warning and nothing is loaded in the incoming requests tab. See the attached screenshot for the exact message.

Expected Result
============
There is no warning and the incoming requests tab contains the expected data.

How to Reproduce
===============
1. Go to https://build.opensuse.org/user/tasks
2. See error

Further Information
===============
This is similar to #4021. I assume #5455 might fix this issue.

![error-1](https://user-images.githubusercontent.com/1102934/43189098-17b99740-8ff6-11e8-9184-3b5d919d1c47.png)

**Comment by coolo** [comment]
No, unrelated to this PR - the error you see is a 500 on the server side.

**Comment by coolo** [comment]
See [errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b575573592b0f0006e233b5)
