### ISSUE TITLE
[dist] obsapidelayed fails when starting clockworkd

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#5489]
# Issue Description
The obsapidelayed script has a hardcoded path to clockworkd: CLOCKWORKD=/usr/lib64/obs-api/bin/clockworkd. If you change this to reflect the new bundle_gem install path, then you get another error: 

Jul 26 14:10:52 api obsapidelayed[24046]: Starting OBS api clock daemon bundler: failed to load command: /usr/lib64/obs-api/ruby/2.5.0/bin/clockworkd (/usr/lib64/obs-api/ruby/2.5.0/bin/clockworkd)
Jul 26 14:10:52 api obsapidelayed[24046]: LoadError: cannot load such file -- /usr/lib64/obs-api/ruby/2.5.0/gems/clockwork-2.0.3/bin/clockworkd
Jul 26 14:10:52 api obsapidelayed[24046]:   /usr/lib64/obs-api/ruby/2.5.0/bin/clockworkd:23:in `load'
Jul 26 14:10:52 api obsapidelayed[24046]:   /usr/lib64/obs-api/ruby/2.5.0/bin/clockworkd:23:in `<top (required)>'
Jul 26 14:10:52 api obsapidelayed[24046]: ..failed

Expected Result
============
obsapidelayed script should work as before the change to bundled gems

How to Reproduce
===============
1. rcobsapidelayed start
2. systemctl status obsapidelayed.service

Step two shows above error log from the start script.

Further Information
===============
* Happens since introduction of obs-bundled-gems
* Lastest git master d8c5e6af9ab51dd8dccadc457a56934f836f6772 has of course not touched dist/obsapidelayed file, so it still fails.

**Comment by mmohring** [comment]
The rest rest of this new OBS starts up and works correctly as far as I can see. We still have those rspec testsuite failures though, you might have noticed them in b.o.o OBS:Server:Unstable/obs-server .

**Comment by coolo** [comment]
That slipped my tests on build-test

**Comment by mmohring** [comment]
I was wondering why the bin dirs were missing in some gems, but I did not see they got all deleted in the bundling .spec file.

**Comment by mmohring** [comment]
Will test this next.

**Comment by mmohring** [comment]
Has also spotted the problem you fixed, so I run now "rm -rf %{buildroot}%_libdir/obs-api/ruby/*/gems/diff-lcs-*/bin". Hope it works now.

**Comment by mmohring** [comment]
Works now fine. @coolo have left you a comment in your change.
