### ISSUE TITLE
[production][search#index] undefined method `start_with?' for nil:NilClass

### ISSUE THREAD

**Issue by saraycp** [openSUSE/open-build-service#5510]
search#index threw this 1 times
<pre>
undefined method `start_with?&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/search?name=1&amp;package=1&amp;project=1](https://build.opensuse.org/search?name=1&amp;package=1&amp;project=1)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b58a73a4f520500063c6460)

**Comment by saraycp** [comment]
It seems Package.exists_by_project_and_name method is calling striping_multibuild_suffix without package name. Lines 169 and 227 are involved.

**Comment by coolo** [comment]
Rather special case

**Comment by saraycp** [comment]
This is happening again frequently

**Comment by coolo** [comment]
This is definitely not the same issue. The old one was in the search controller, this is in a delayed job. The underlying methods are called in both cases with invalid objects, but that's about it.
