### ISSUE TITLE
[production][project#new_incident_request] Maintenance incident request contains release target project Publishing with invalid project kind...

### ISSUE THREAD

**Issue by saraycp** [openSUSE/open-build-service#5512]
project#new_incident_request threw this 0 times
<pre>
Maintenance incident request contains release target project Publishing with invalid project kind &quot;standard&quot; (should be &quot;maintenance_release&quot;) for package xmlcharent
</pre>
[https://build.opensuse.org/project/new_incident_request](https://build.opensuse.org/project/new_incident_request)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b5dc54c33ccdc000cc98ea5)

**Comment by Ana06** [comment]
@saraycp 

> 0 times

:roll_eyes: ?

**Comment by DavidKang** [comment]
@Ana06, this issue was created through Errbit

**Comment by hennevogel** [comment]
Does not happen anymore...
