### ISSUE TITLE
[production][] Failed to forward BsRequest: 625921, error: Validation failed: Bs request actions is invalid, Bs ...

### ISSUE THREAD

**Issue by saraycp** [openSUSE/open-build-service#5518]
threw this 0 times
<pre>
Failed to forward BsRequest: 625921, error: Validation failed: Bs request actions is invalid, Bs request actions Type has already been taken, params: &lt;ActionController::Parameters {&quot;utf8&quot;=&gt;&quot;✓&quot;, &quot;authenticity_token&quot;=&gt;&quot;2Zxq9WEr04JwVEVisYUaEfM3PJ4UiqZ//ub4rP1D3viOgWYQAv3BpgvWQpSOBOd+owO4xuMeRhL82ZKt1+GLSw==&quot;, &quot;reason&quot;=&gt;&quot;It&#39;s fine now, I&#39;d say.\r\n\r\nI submitted some more minor changes to KUA, I&#39;ll just apply them directly here as well afterwards...&quot;, &quot;number&quot;=&gt;&quot;625921&quot;, &quot;accepted&quot;=&gt;&quot;Accept request&quot;, &quot;forward_devel_0&quot;=&gt;&quot;openSUSE:Factory_#_umbrello&quot;, &quot;controller&quot;=&gt;&quot;webui/request&quot;, &quot;action&quot;=&gt;&quot;changerequest&quot;} permitted: false&gt;, request: #&lt;BsRequest id: 1098664, description: nil, creator: &quot;wolfi323&quot;, state: &quot;review&quot;, comment: nil, commenter: &quot;wolfi323&quot;, superseded_by: nil, created_at: &quot;2018-07-28 13:53:20&quot;, updated_at: &quot;2018-07-28 13:53:21&quot;, accept_at: nil, priority: &quot;moderate&quot;, number: 625932, updated_when: nil&gt;
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b5c7552de051e00060836bf)

**Comment by hennevogel** [comment]
@eduardoj  didnt you fix this?

**Comment by eduardoj** [comment]
@hennevogel:

> @eduardoj didnt you fix this?

Nops. It seems it is still opened here: https://github.com/openSUSE/open-build-service/issues/3730#issuecomment-406249568

I would close this issue here and merge the exceptions in Errbit (those after searching for "error: Validation failed: Bs request actions is invalid"). It is the same issue as described in #3730.

**Comment by saraycp** [comment]
Ok, so I close this, I have merged with the others in Errbit:

https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5ac32f5a502aca0014049e5e
