### ISSUE TITLE
[webui] Multiple file upload mechanism to implement

### ISSUE THREAD

**Issue by MikhailKasimov** [openSUSE/open-build-service#5526]
Hello!

**Is your feature request related to a problem? Please describe.**

When user uploads ```.spec``` + ```.changes``` + ```main body.tar.gz``` via build.opensuse.org webui, he is able to upload these files step-by-step, and this increases ```Revision``` counter. And it is rather inconvenient.

![add_file_-_opensuse_build_service_-_2018-08-01_11 33 48](https://user-images.githubusercontent.com/7167300/43515509-5c3e4ab0-958b-11e8-89f9-defea74e95fe.png)

**Describe the solution you'd like**

To give a ```+``` button to generate upload-fields in amount that user needs (e.g. three for ```.spec``` + ```.changes``` + ```main body.tar.gz``).

```Revision``` counter should consider this as a single, not multiple, action.

![add_file_-_opensuse_build_service_add_button](https://user-images.githubusercontent.com/7167300/43515637-b13d9642-958b-11e8-937e-bcb8131b9374.png)

**Describe alternatives you've considered**
Described method seems to be the most convenient.

Please, consider! Thanks!

**Comment by hellcp** [comment]
Isn't that a duplicate of #242?

**Comment by MikhailKasimov** [comment]
Closed as dup of https://github.com/openSUSE/open-build-service/issues/242
