### ISSUE TITLE
Irrelevant SRs are offered to be superseded by SR in web UI

### ISSUE THREAD

**Issue by afaerber** [openSUSE/open-build-service#555]
Imagine the following _link setup: ~:X11:XOrg -> X11:XOrg -> openSUSE:Factory

When I attempt to submit from my home branch to the devel project, then pending SRs from devel project to Factory are listed with the option for my SR to supersede them.

![screenshot](https://f.cloud.github.com/assets/309527/1931996/816d6752-7ec6-11e3-869e-3d5722006a29.png)

Expected: Only SRs to the (devel) project I am submitting to should be listed, in this case none.

**Comment by sebix** [comment]
Related: On build.opensuse.org I'm offered to supersede declined requests.

**Comment by coolo** [comment]
that's by design - so your marking the followup. declined requests are not final

**Comment by vpereira** [comment]
@coolo and @afaerber  does it still relevant? I tried to reproduce it, but I wasn't successful here. What I did, in a local instance.

- created userA and userB
- Created a devel project. copied openSUSE:Factory hello there.

As userA:

- branched devel:hello package. Did some change and submit. then changed again. Got a dialog to supersede the first request. accepted. first request is superseded. The other request is open.

As userB:

- branched the deve:hello package. did a change, submit, no dialog asking me to supersede a request from userA. Now I see two open requests, one from userA and other from userB.

**Comment by afaerber** [comment]
@vpereira Haven't seen it in a while, but am not making so many SRs anymore and this was a rather rare constellation.

**Comment by coolo** [comment]
@vpereira your scenario is not the same. userA submits from devel to openSUSE:Factory and userB submits *to* devel.

**Comment by coolo** [comment]
cool - write a feature test :)

**Comment by vpereira** [comment]
worked as expected. Thank you @afaerber  and @coolo for the help and time.
