### ISSUE TITLE
rake docker:test:minitest issues with createrepo_c

### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#5553]
trying to run ```rake docker:test:minitest``` I'm still getting the following issue:

```
Can't exec "/usr/bin/createrepo_c": No such file or directory at ./bs_publish line 131.
/usr/bin/createrepo_c: No such file or directory
Can't exec "/usr/bin/createrepo_c": No such file or directory at ./bs_publish line 131.
/usr/bin/createrepo_c: No such file or directory
publish failed for BaseDistro3/BaseDistro3_repo :     createrepo failed again: 256
Can't exec "/usr/bin/createrepo_c": No such file or directory at ./bs_publish line 131.
/usr/bin/createrepo_c: No such file or directory
Can't exec "/usr/bin/createrepo_c": No such file or directory at ./bs_publish line 131.
/usr/bin/createrepo_c: No such file or directory
publish failed for home:Iggy/10.2 :     createrepo failed again: 256
Can't exec "/usr/bin/createrepo_c": No such file or directory at ./bs_publish line 131.
/usr/bin/createrepo_c: No such file or directory
Can't exec "/usr/bin/createrepo_c": No such file or directory at ./bs_publish line 131.
/usr/bin/createrepo_c: No such file or directory
```
anything that I should update locally?

**Comment by vpereira** [comment]
after rebase on master, I cannot run the tests, because all rake docker:test:* are gone.. looking https://github.com/openSUSE/open-build-service/wiki/Development-Environment-Tips-&-Tricks, nothing about it, so now I have no clue how to test it locally again :/

**Comment by coolo** [comment]
Hmm, I run minitest outside of docker (and I guess @adrianschroeter does too :)

But that's of course only second best - but using the docker: tasks locally was neither recommended as it's messing with your git checkout's permissions.

I'm looking into providing a minitest target for dev containers.

**Comment by coolo** [comment]
Please give the PR a shove
