### ISSUE TITLE
nothing provides jade with Ubuntu 18.04 with obs 2.9 version.

### ISSUE THREAD

**Issue by wb0716** [openSUSE/open-build-service#5554]
When I try to build my package using Ubuntu 18.04 repository with obs 2.9 version. there is an error:
nothing provides jade.
I checked the packages.gz file, there is no dependency relation with jade packages.

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
