### ISSUE TITLE
[production][] Failed to create Event : "REPO_PUBLISHED": {"buildid"=>"1533558961", "project"=>"home:cheusov", "...

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#5564]
threw this 73 times
<pre>
Failed to create Event : &quot;REPO_PUBLISHED&quot;: {&quot;buildid&quot;=&gt;&quot;1533558961&quot;, &quot;project&quot;=&gt;&quot;home:cheusov&quot;, &quot;repo&quot;=&gt;&quot;openSUSE_Leap_42.2&quot;} LEFT Event::RepoPublished payload_keys :buildid # {&quot;buildid&quot;=&gt;&quot;1533558961&quot;}
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b684dd0bc4e980006d138ee)

**Comment by dmarcoux** [comment]
Hypothesis: Whenever the backend adds new attribute(s) to an event, the frontend will throw this error.

**Comment by hennevogel** [comment]
So mls was trying some code changes on production. Which added this new `buildid` thing. Then there is code in [Event::Base](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/event/base.rb#L127) which raises an exception when this happens.

I don't think this exception is a good idea....

**Comment by hennevogel** [comment]
@coolo remember why this is there?

**Comment by adrianschroeter** [comment]
because storing incomplete events is a bad idea, you can sort this out afterwards.

bigger question to me is why this got not catched by the UpdateNotificationEvents.new.perform in the integration test suites. they should see published repos actually...

**Comment by coolo** [comment]
This exception is there exactly to catch the current case: align backend and API's view on what payload an event should have

**Comment by adrianschroeter** [comment]
okay, let's rephrase, it is bad to process events where the code is not understanding all parts, you can not sort this out afterwards ;)

**Comment by dmarcoux** [comment]
With this exception, we throw exceptions whenever we deploy changes to some events in the backend.

**Comment by coolo** [comment]
*exactly*

**Comment by coolo** [comment]
nonsense. you first have to deploy a frontend that is prepared for it before you can deploy a backend providing it.

**Comment by dmarcoux** [comment]
Well forget my previous comment, you're right @coolo. I had a look at the code again. This issue is pointless then.

**Comment by hennevogel** [comment]
> you first have to deploy a frontend that is prepared for it before you can deploy a backend providing it.

Heh so we crash the app and keep users from doing what they want to do (e.g. getting emails, receiving events on the bus etc.) because we have no deployment strategy between the the frontend & backend team? Great stuff! :+1: 

Sorry but that is not how we work here :smile:

**Comment by hennevogel** [comment]
I propose we log **and** send an exception **and** continue instead.

**Comment by adrianschroeter** [comment]
yes, we crash, because we don't know if we would do something bad.

never ever continue and break stuff if you don't know about it. 

As said before, it is more important to find out why the integration checks did not detect this problem (or was the api in git master already prepared for the attribute?)

**Comment by dmarcoux** [comment]
@adrianschroeter We still would have logs of what happened since Errbit would receive the exceptions and the people in the bug/demolition squads will notice it.

**Comment by hennevogel** [comment]
> never ever continue and break stuff if you don't know about it.

Nothing breaks. The app continues to work like it always worked. This is just an extra key.

> As  said before, it is more important to find out why the integration checks did not detect this problem (or was the api in git master already  prepared for the attribute?)

The deployed API version doesn't know about this payload key that the backend sends. The backend feature was deployed before the API changes where merged. Again, nothing would have happened if we would ignore (&warn about) extra payload keys...

**Comment by adrianschroeter** [comment]
The point is that key and payload must be kept until it gets fixed. They must not get removed, nor wrong data must be written into the database (would be a showstopper for packtrack stuff for example, but also very bad for notifications). It is of course okay if the webui still works, but everything behind the event processing which may depends on the data must get blocked.

My understanding was that this was not only a deployment issue, but it was also in git first in the backend and the ruby part is still not merged (https://github.com/openSUSE/open-build-service/pull/5544), is that correct?
In this situation our test suite has to report this situation.

**Comment by hennevogel** [comment]
> The point is that key and payload must be kept until it gets fixed.

Until what get's fixed? Nothing is broken. The backend works, the frontend works. 

> They must not get removed

The Events always get removed (**and** they are not even created in the situation we had).

> nor wrong data must be written into the database

To not write wrong data into the database we have validations.

> It is of course okay if the webui still works, but everything behind the event processing which may depends on the data must get blocked.

Everything behind the *event processing* (I guess you talk about OBS external tools that listen to our message bus?) will also not expect this new attribute (they can't know about this attribute, it's not even merged) and if it's omitted, then what is the problem?

> My understanding was that this was not only a deployment issue, but it was also in git first in the backend and the ruby part is still not merged (#5544), is that correct?

Yes that is correct.

> In this situation our test suite has to report this situation.

Yes this would have been nice, but this is not what we are discussing here...
