### ISSUE TITLE
[webui] Architecture '2' is invalid when clicked package dependency link in the binary details

### ISSUE THREAD

**Issue by nilxam** [openSUSE/open-build-service#5593]
# Issue Description
With current OBS, clicked package dependency link in the package details page results `Architecture '2' is invalid` error if the binary is x86_64 build, it shows `Architecture '1' is invalid` if it's i586 build, the `arch` param is different now than before, the link uses `arch=2` instead of 'arch=x86_64' in my case. The `Architecture` number seems according to the ordering of repo setup thus it depends project setup.

Expected Result
============
No error and shows dependency package's information.

How to Reproduce
===============
1. Go to build results page
2. Click on any binary's details link, eg. 'https://build.opensuse.org/package/binary/openSUSE:Factory/acpi/standard/x86_64/acpi-1.7-4.13.x86_64.rpm' for acpi Factory built
3. Clicked link if any in `Required by`

Further Information
===============
* A link to an OBS instance showing the issue

https://build.opensuse.org/package/binary/openSUSE:Factory/acpi/standard/x86_64/acpi-1.7-4.13.x86_64.rpm

**Comment by DavidKang** [comment]
@nilxam, thanks for reporting it, we will take care of it.
