### ISSUE TITLE
[production][source#get_file] Security warning: an embedded <script> tag on another site requested protected JavaScript. If you...

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#5614]
source#get_file threw this 2 times
<pre>
Security warning: an embedded &lt;script&gt; tag on another site requested protected JavaScript. If you know what you&#39;re doing, go ahead and disable forgery protection on this action to permit cross-origin JavaScript embedding.
</pre>
[https://build.opensuse.org/source/mozilla:Factory/MozillaThunderbird/suse-default-prefs.js?rev=5306ce3fbbf7e6aaf55d6492b4534668](https://build.opensuse.org/source/mozilla:Factory/MozillaThunderbird/suse-default-prefs.js?rev=5306ce3fbbf7e6aaf55d6492b4534668)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b6d0efc150542000ae128cd)

**Comment by bgeuken** [comment]
The forgery protection kicks in because the url ens with `.js`. That causes it to be interpreted as a request for a js response instead of our standard XML.

We probably can hardcode the response format, since this is only expected to reply with XML (well, with file from the backend actually).

**Comment by bgeuken** [comment]
Took a bit longer because of #5574
