### ISSUE TITLE
Tags of containers are inconsistent and have to be known sometimes

### ISSUE THREAD

**Issue by celan** [openSUSE/open-build-service#5625]
Containers in the registry may have the "latest" tag or the version from the kiwi file. This is inconsistent.

If the version is taken from the kiwi file it cannot be looked up and has to documented and changed every now and then. This is inconvenient.

**Comment by ChrisBr** [comment]
cc @M0ses @mlschroe @adrianschroeter please have a look

**Comment by adrianschroeter** [comment]
the tags are defined by the tool building the containers (kiwi, docker or podman), so it needs to be discussed there.

(We have two more features in the queue to define additional tags in OBS only though).

**Comment by celan** [comment]
What is the timeline? What are the feature IDs? This is blocking openQA development for containers.

**Comment by adrianschroeter** [comment]
as said before openQA should use image id (the sha256sum) from the container instead to have a uniq identifier, similar to the publish id out of the rpm-md meta data.

The image id will also be part of the pack track data.
