### ISSUE TITLE
[production][search#bs_request] undefined method `shift' for :qname:Symbol

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#5629]
search#bs_request threw this 0 times
<pre>
undefined method `shift&#39; for :qname:Symbol
</pre>
[https://api.opensuse.org/search/request?match=action%2Ftarget%5B%40project%3D%22openSUSE%3AMaintenance%22%5D](https://api.opensuse.org/search/request?match=action%2Ftarget%5B%40project%3D%22openSUSE%3AMaintenance%22%5D)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b6bb8f50031d2000ac2bc1f)

**Comment by saraycp** [comment]
It tries to perform a search request via osc but, it fails when parsing the `match` parameter as xpath.

It happened only once and the code that parses it is quiet old (strange that it fails now). I wasn't able to find examples for osc searchs like the one used in this case. For these reasons I think that the input could be bad-formed.

I'll close this and please reopen it if something similar happens in the future.
