### ISSUE TITLE
[production][package#dependency] undefined method `name' for "standard":String

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#5630]
package#dependency threw this 2 times
<pre>
undefined method `name&#39; for &quot;standard&quot;:String
</pre>
[https://build.opensuse.org/package/dependency/openSUSE:Leap:15.1/virtualbox?arch=x86_64&amp;dependant_name=kernel-default&amp;dependant_project=openSUSE%3ALeap%3A15.1&amp;dependant_repository=standard&amp;filename=virtualbox-guest-kmp-default-5.2.10_k4.12.14_lp151.15-lp151.4.6.x86_64.rpm&amp;repository=standard](https://build.opensuse.org/package/dependency/openSUSE:Leap:15.1/virtualbox?arch=x86_64&amp;dependant_name=kernel-default&amp;dependant_project=openSUSE%3ALeap%3A15.1&amp;dependant_repository=standard&amp;filename=virtualbox-guest-kmp-default-5.2.10_k4.12.14_lp151.15-lp151.4.6.x86_64.rpm&amp;repository=standard)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b71d0a360f1ac00064ea303)

**Comment by hennevogel** [comment]
@dmarcoux told you so 😜

**Comment by dmarcoux** [comment]
@hennevogel Stop nagging me :smile:. I'll fix it! (damn)

**Comment by dmarcoux** [comment]
Regression from my changes in #5601

**Comment by hennevogel** [comment]
Don't worry, the return-value-dance is something every OBS developer has to go through....
