### ISSUE TITLE
the /public/binary_packages/:project/:package doesn't work with remote repositories

### ISSUE THREAD

**Issue by Fishwaldo** [openSUSE/open-build-service#564]
Hi,
The binary packages API (AppDirectory?) doesn't display the actual package download links if you have a private OBS instance that has a connection to a remote repository. Looking through the controller code, it appears to just iterate over the local Distributions and doesn't take into account remote "Distributions". I guess it should adopt something like /distributions/include_remotes API?

this is on a 2.4 install.... I had a quick look at the current code on github, and that seems to suffer the same shortfall

**Comment by eduardoj** [comment]
As 2.4 is not supported anymore I will close this. Please, feel free to open it if this is still happening in a supported version.
