### ISSUE TITLE
Could not enable Beta feature with a proxy accounts

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#5667]
# Issue Description
Beta feature, couldn't be enabled if you have a proxy account.

Expected Result
============
Clicking in `edit your account` should open the dialog or having a link in User#show view to enable and disable this feature.

How to Reproduce
===============
1. Go to your user page
2. Click on `Edit your account`

**Comment by hennevogel** [comment]
hehe that's what you get for :spaghetti: :hankey:
