### ISSUE TITLE
Need a distributted build system

### ISSUE THREAD

**Issue by qiangzhao** [openSUSE/open-build-service#5674]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Can we make OBS as a distributed system? Now more and more people are using OBS to contribute code all over the world. When people accessing it from European cities like Nuremberg and Prague, it is fast enough. but when we access it from Beijing, sometimes It will be another story. 
So, If we can provide a server here which can join the OBS cluster and works as a minion, Can you make it accomplish to compile locally?  and we also hope these depended packages for the building will be synchronized before build time.

**Describe alternatives you've considered**
If there's not enough disk space or bandwidth for every package，I think we can sync the code and build-env of the package which has already built locally. say, 1) an empty server at the start; 2) if a people request to build a special package, the code and env will sync locally at this time. 3) after that, code and env update nightly.

Thanks so much for taking care of this.

**Comment by adrianschroeter** [comment]
We won't distribute the cluster which builds our criticial parts for trust and security reasons, but nothing stops you to setup an OBS instance at your location.

Check how to setup project links and rebuild triggers. You can have a setup where you maintain the sources in our main instance for sharing your work, but having builds in your local instance by using a project link to the official instance.

So, you would work still in public, but have local build results.

Does that sound good enough?

**Comment by qiangzhao** [comment]
Yes, it's good enough. 
but how to setup a local instance and how to use a project link to the official instance? Is there any document? or a virtual machine image is much better of course. Thanks!
