### ISSUE TITLE
A very strange question

### ISSUE THREAD

**Issue by qiangzhao** [openSUSE/open-build-service#5675]
When I run:
1) osc -A https://api.opensuse.org co Base:System/plymouth
2) cd Base:System/plymouth
3) osc build
It always returns a warning:
Run source service: /usr/lib/obs/service/format_spec_file --outdir /root/Base:System/plymouth/tmpABJcDU.format_spec_file.service
Run source service: /usr/lib/obs/service/source_validator --outdir /root/Base:System/plymouth/tmpJLr46X.source_validator.service
grep: Unmatched ( or \(
(W) openSUSE: projects only allow 'disabled', 'buildtime', 'explicit' or 'localonly' services.
Run source service: /usr/lib/obs/service/format_spec_file --outdir /root/Base:System/plymouth/tmpGICMAG.format_spec_file.service
Run source service: /usr/lib/obs/service/source_validator --outdir /root/Base:System/plymouth/tmpZUU4wB.source_validator.service
grep: Unmatched ( or \(
(W) openSUSE: projects only allow 'disabled', 'buildtime', 'explicit' or 'localonly' services.
Building plymouth.spec for openSUSE_Factory/x86_64

With a careful search we didn't find any un-matched "(", Some of my colleague also can't find the reason, while other package doesn't have this problem.
Could you please kindly help me? So many thanks!

**Comment by marcus-h** [comment]
On 2018-08-17 22:38:49 -0700, QiangZhao wrote:
> Run source service: /usr/lib/obs/service/source_validator --outdir /root/Base:System/plymouth/tmpZUU4wB.source_validator.service
> grep: Unmatched ( or \(
> (W) openSUSE: projects only allow 'disabled', 'buildtime', 'explicit' or 'localonly' services.
> Building plymouth.spec for openSUSE_Factory/x86_64
> 
You are probably using an "old" version of the obs-service-source_validator
package. In particular, your version seems to miss commit
398046d8adc03a723ec5b382cd584215b0cb5881 [1].

[1] https://github.com/openSUSE/obs-service-source_validator/commit/398046d8adc03a723ec5b382cd584215b0cb5881

**Comment by qiangzhao** [comment]
Sorry, I'm such a newbie with OBS detailed knowledge. I'm still no ideas about how to fix "miss commit 398046d8adc03a723ec5b382cd584215b0cb5881".  I have searched all the files inside this project, only Base:System/plymouth/.osc/_files has records of files with md5 number, should I add the missing record here? Could you please guild me a little detailed, Thanks so much for taking your time!

**Comment by marcus-h** [comment]
On 2018-08-18 08:00:47 -0700, QiangZhao wrote:
> Sorry, I'm such a newbie with OBS detailed knowledge. I'm still no ideas about how to fix "miss commit 398046d8adc03a723ec5b382cd584215b0cb5881".

What's the output of "rpm -q obs-service-source_validator"?

**Comment by qiangzhao** [comment]
I'm using Fedora now, So I don't have this package in my system.

**Comment by qiangzhao** [comment]
But other packages don't have this problem when building offline.
Thanks!

**Comment by qiangzhao** [comment]
and when other people build in their system(SLE and openSUSE), the result is the same.
Thanks!

**Comment by marcus-h** [comment]
On 2018-08-18 08:53:29 -0700, QiangZhao wrote:
> I'm using Fedora now, So I don't have this package in my system.
> 
Does a "/usr/lib/obs/service/source_validator" file exist on your system?
If so, which package provides this file?

**Comment by qiangzhao** [comment]
Sorry, It's my mistake. I have 
obs-service-source_validator-0.6+git20170719.d4384e5-100.1.noarch

**Comment by marcus-h** [comment]
On 2018-08-19 04:50:11 -0700, QiangZhao wrote:
> Sorry, It's my mistake. I have 
> obs-service-source_validator-0.6+git20170719.d4384e5-100.1.noarch
> 
This version does not have the mentioned commit. You could get an
updated version from the openSUSE:Tools project [1].

[1] http://download.opensuse.org/repositories/openSUSE:/Tools/
