### ISSUE TITLE
staging dashboard does not show all openqa failures in staging_projects view

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#5683]
# Issue Description

https://build.opensuse.org/project/staging_projects/openSUSE:Leap:15.1 seems to only display actually failed openqa jobs with direct link. A project may be openqa failed due to incomplete jobs too though. In that case the staging project is correctly shown red with failed state but the links in the right column are missing. Instead the green checkmark is shown.

**Comment by saraycp** [comment]
@lnussel let's see if I understood correctly...

Checking Test `E` in https://build.opensuse.org/project/staging_projects/openSUSE:Leap:15.1/E
we can see that some OpenQA job _soft-failed_ (they are in blue). However, a green checkmark (:heavy_check_mark: ) is shown in the general view[1].

Do you suggest that we show the links to those _soft-failed_ tests instead of the green checkmark in the general view[1]? In other words, showing both _failed_ and _soft-failed_ ones as direct links?

[1] https://build.opensuse.org/project/staging_projects/openSUSE:Leap:15.1

**Comment by lnussel** [comment]
No, not related to softfail. Meanwhile I had retriggered the incomplete jobs and then they succeeded. This is really about the state 'failed' vs 'incomplete' reported by openQA.

**Comment by Ana06** [comment]
@lnussel can you provide as a case where this happen? url or screenshot? :pray:

**Comment by lnussel** [comment]
Here is a reproducer: https://build.opensuse.org/project/staging_projects/openSUSE:Leap:15.1

**Comment by lnussel** [comment]
This is transient, so you need to check right now :)

**Comment by saraycp** [comment]
Well, that's what we have discovered after some debug.

On the left side of the following image we see that `A` failed, in red. (It is checking openQA overall state). However, a green checkmark is shown on the right (It is checking each test state):

![dashboard-1](https://user-images.githubusercontent.com/2581944/44528657-62815000-a6ea-11e8-891d-37cc4ac9051d.png)

Then, when we click on `A` we see a failure link for `gnome` in red:

![dashboard-2](https://user-images.githubusercontent.com/2581944/44528729-8c3a7700-a6ea-11e8-8667-24a1d455cb99.png)

If we open that link, we see `Result: incomplete` and all the tests' results are `none`.
![dashboard-3](https://user-images.githubusercontent.com/2581944/44529210-d2dca100-a6eb-11e8-9bb2-b8163f4cd4b7.png)

So, the green checkmark is shown when there are not failing tests in openQA and, in this case,  `none` results are not considered as failures. We can see this at: https://github.com/openSUSE/open-build-service/blob/751521c58e7e3d9118d40904550d8478404e7769/src/api/app/models/obs_factory/openqa_job.rb#L99


Should we then consider `none` results as failure? Maybe only when the whole test is finished and incomplete?

@coolo, @adrianschroeter What do you think?

**Comment by lnussel** [comment]
if none means "incomplete" I'd say yet, that is a failure

**Comment by adrianschroeter** [comment]
agreed.

In the new check system we will have an explicit definition which checks are required to be run. So this will define this more clearly and will be in control of the target project owner. JFYI.

**Comment by saraycp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Take into account 'incomplete' tests from OpenQA in the new Status API feature](https://trello.com/c/T1Bzd3PB/1543-take-into-account-incomplete-tests-from-openqa-in-the-new-status-api-feature)

**Comment by coolo** [comment]
Hi everyone (¡he vuelto!), the card doesn't really make sense - as the openQA status will be interpreted in the openQA glue code (which is not planned to be maintained by frontend team). The status API is not supposed to know about openQA nor about its job states.

And @adrianschroeter's last comment doesn't make sense either - as the openQA job did run, but it's result was taken as success.

This must be a regression though, as incomplete jobs were definitely dark red in previous versions - but I don't think it has priority to fix if the status API is now upon horizon (and A is correctly marked as failed, so no chance of accepting a failed staging)

**Comment by adrianschroeter** [comment]
rating down based on coolos comment regarding the status api.

**Comment by coolo** [comment]
https://github.com/openSUSE/openSUSE-release-tools/blob/master/rabbit-openqa.py#L137 maps incomplete to failed status
