### ISSUE TITLE
[production][delayed_job#BsRequestAutoAcceptJob] No permission to revoke request 624627

### ISSUE THREAD

**Issue by mdeniz** [openSUSE/open-build-service#5703]
delayed_job#BsRequestAutoAcceptJob threw this 183 times
<pre>
No permission to revoke request 624627
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b7d087ad4e1e40014018958)

**Comment by hennevogel** [comment]
Sounds like another occurrence of `DelayedJob` without `User.current` being `nobody`...
