### ISSUE TITLE
No results searching for `python-abimap`

### ISSUE THREAD

**Issue by saraycp** [openSUSE/open-build-service#5710]
# Issue Description
Searching in https://build.opensuse.org for `python-abimap` there aren't any results. However `python-abimap` exits as you can see in https://build.opensuse.org/package/show/devel:languages:python/python-abimap

Expected Result
============
Searching for `python-abimap` we should see a result like
« package devel:languages:python / python-abimap»

How to Reproduce
===============
1. Go to https://build.opensuse
2. Type `python-abimap` in the search text field
3. No results given.

Further Information
===============
* Search URL:  https://build.opensuse.org/search?utf8=%E2%9C%93&search_text=python-abimap&commit=Submit+Query&issue_tracker=bnc&issue=&project=1&package=1&name=1&attrib_type_id=
* The same happens with `python-aniso8601` but not with `python-appdirs`, for example. Both should give results under `devel:languages:python`.

**Comment by saraycp** [comment]
It also happened with other recent packages, then @mdeniz realized that the search index was out of date and regenerated it.

Now the search works.

**Comment by dmarcoux** [comment]
@mdeniz How is the search index regenerated?

**Comment by hennevogel** [comment]
And why was is out of date?

**Comment by saraycp** [comment]
I wrote a Wiki page with the steps to follow:
https://github.com/openSUSE/open-build-service/wiki/OBS-Search

**Comment by dmarcoux** [comment]
Nice work on the wiki page. One more question, why is the rake task not running sometimes?
