### ISSUE TITLE
[production][images#import_from_package] undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#5738]
images#import_from_package threw this 2 times
<pre>
undefined method `[]&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/package/3617204/kiwi_images/import_from_package](https://build.opensuse.org/package/3617204/kiwi_images/import_from_package)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b851b63cbed410006086f73)

**Comment by DavidKang** [comment]
Still happening

**Comment by hennevogel** [comment]
Does not happen anymore...
