### ISSUE TITLE
[production][bs_requests#index] undefined method `icon' for #<#<Class:0x00007f9270bc8d38>:0x00007f92710ca6b0>

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#5756]
bs_requests#index threw this 6 times
<pre>
undefined method `icon&#39; for #&lt;#&lt;Class:0x00007f9270bc8d38&gt;:0x00007f92710ca6b0&gt;
</pre>
[https://build.opensuse.org/projects/devel:languages:ruby:extensions/packages/rubygem-rails-5.2/requests](https://build.opensuse.org/projects/devel:languages:ruby:extensions/packages/rubygem-rails-5.2/requests?draw=2&amp;columns%5B0%5D%5Bdata%5D=0&amp;columns%5B0%5D%5Bname%5D=&amp;columns%5B0%5D%5Bsearchable%5D=true&amp;columns%5B0%5D%5Borderable%5D=true&amp;columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B1%5D%5Bdata%5D=1&amp;columns%5B1%5D%5Bname%5D=&amp;columns%5B1%5D%5Bsearchable%5D=true&amp;columns%5B1%5D%5Borderable%5D=true&amp;columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B2%5D%5Bdata%5D=2&amp;columns%5B2%5D%5Bname%5D=&amp;columns%5B2%5D%5Bsearchable%5D=true&amp;columns%5B2%5D%5Borderable%5D=true&amp;columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B3%5D%5Bdata%5D=3&amp;columns%5B3%5D%5Bname%5D=&amp;columns%5B3%5D%5Bsearchable%5D=true&amp;columns%5B3%5D%5Borderable%5D=true&amp;columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B4%5D%5Bdata%5D=4&amp;columns%5B4%5D%5Bname%5D=&amp;columns%5B4%5D%5Bsearchable%5D=true&amp;columns%5B4%5D%5Borderable%5D=true&amp;columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B5%5D%5Bdata%5D=5&amp;columns%5B5%5D%5Bname%5D=&amp;columns%5B5%5D%5Bsearchable%5D=true&amp;columns%5B5%5D%5Borderable%5D=true&amp;columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B6%5D%5Bdata%5D=6&amp;columns%5B6%5D%5Bname%5D=&amp;columns%5B6%5D%5Bsearchable%5D=true&amp;columns%5B6%5D%5Borderable%5D=false&amp;columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&amp;order%5B0%5D%5Bcolumn%5D=0&amp;order%5B0%5D%5Bdir%5D=desc&amp;start=0&amp;length=25&amp;search%5Bvalue%5D=&amp;search%5Bregex%5D=false&amp;dataTableId=all_requests_table&amp;type=all&amp;state=accepted&amp;_=1535537500020)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b867161cae53e0008cd893c)

**Comment by bgeuken** [comment]
This is going to be fixed with #5751

**Comment by ChrisBr** [comment]
This is still happening

**Comment by saraycp** [comment]
It seems an 'icon' helper is missing. I'll try to fix it.

**Comment by saraycp** [comment]
It may be related to https://github.com/openSUSE/open-build-service/pull/5747 :worried:

**Comment by dmarcoux** [comment]
Weird because the `icon` helper is still present: https://github.com/FortAwesome/font-awesome-sass/blob/624630d08a4bd3b4b25d8bbac8a21a344538eb3c/lib/font_awesome/sass/rails/helpers.rb
