### ISSUE TITLE
[production][source_project#delete] Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`obs_product...

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#5757]
source_project#delete threw this 0 times
<pre>
Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`obs_production`.`packages`, CONSTRAINT `packages_ibfk_4` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`)): DELETE FROM `projects` WHERE `projects`.`id` = 433574
</pre>
[https://api.opensuse.org/source/home:mgerstner:Factory?comment=remove+test+copy](https://api.opensuse.org/source/home:mgerstner:Factory?comment=remove+test+copy)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b8560433c9568000a3751cf)

**Comment by dmarcoux** [comment]
The [constraint](https://github.com/openSUSE/open-build-service/blob/8e2a39caa362abd584cfe8e9839c68ff7152c21a/src/api/app/models/package.rb#L1514) is on `Package`.

I tried to reproduce the error by creating a project with a package. I then ran the command `osc api --method=DELETE 'source/home:dmarcoux:test-project?comment=remove+test+copy'`. It worked... so I'm not sure how it happened.

**Comment by hennevogel** [comment]
Doing it twice, at the same time, in different threads? :-)

**Comment by hennevogel** [comment]
Does not happen anymore...
