### ISSUE TITLE
Docker container build can't resolve dependency

### ISSUE THREAD

**Issue by cornelius** [openSUSE/open-build-service#5776]
# Issue Description

I created a new project via the [template page](https://build.opensuse.org/image_templates) selecting the "Container built using docker tool" based on Leap 42.3. Then I added a statement `RUN zypper in apache2` to the Dockerfile and built the container locally with Docker. All works fine. The build service fails with an error, though: "nothing provides apache2".

Expected Result
============

A successful build of the container equivalent what happens when I run `docker build` locally.

Further Information
===============
* https://build.opensuse.org/package/show/home:cschum:branches:openSUSE:Templates:Images:42.3/docker-container#

**Comment by adrianschroeter** [comment]
the template switched lately to a base image which lacks the repository definitions ... added them there now.
