### ISSUE TITLE
Image templates for Leap 15

### ISSUE THREAD

**Issue by cornelius** [openSUSE/open-build-service#5778]
It would be great to add templates for Leap 15 to the image templates page (https://build.opensuse.org/image_templates) so that users can build images for the current openSUSE Leap version.

**Comment by adrianschroeter** [comment]
yes, but the current submitted templates are not supported in our editor atm :/
We have it on our list to enhance it ...

**Comment by jolz** [comment]
+1
I do not want to set up new images based on 42.3  
Please write some blog / wiki text how to start with up-to-date-images....

**Comment by adrianschroeter** [comment]
We have 15.0 templates meanwjile
