### ISSUE TITLE
[production][package#show] undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by saraycp** [openSUSE/open-build-service#5786]
package#show threw this 1 times
<pre>
undefined method `[]&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/package/show/home:duwe:branches:Kernel:HEAD/kernel-default](https://build.opensuse.org/package/show/home:duwe:branches:Kernel:HEAD/kernel-default)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b8f8beefe4eac0014218d70)

**Comment by ChrisBr** [comment]
I monkey patched this one, it is because of the removing of ActiveXML by @coolo
