### ISSUE TITLE
Build results state is not correct on maintenance incidents page

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#5791]
# Issue Description
On the maintenance incidents page, it seems that the page shows incorrect result states. All incidents have a red `!` as a symbol but the incidents are properly locked and succeed in building.

Expected Result
============
If everything is ok on one incident, the incidents should have a green checkmark as always.

How to Reproduce
===============
1. Go to https://build.opensuse.org/project/maintenance_incidents/openSUSE:Maintenance

**Comment by mschnitzer** [comment]
It was a mistake on my side - never mind.

**Comment by andreasstieger** [comment]
Noticed today,.. incidents that should be green (or are green) are shown as red in the overview page

**Comment by krauselukas** [comment]
I'm going to work on it
