### ISSUE TITLE
mails are all sent as obs-email@opensuse.org

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#580]
It was never the plan to leave that hardcoded - but someone needs to write the config option for it.

**Comment by mdeniz** [comment]
Already implemented by https://github.com/openSUSE/open-build-service/commit/001abc0749ddb3c1868aba39f02199c67303f490#diff-ad8a2753aa86f7e8d0873b7a6e8fdc54
Closing this old issue, thanks
