### ISSUE TITLE
[production][] Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction: UPDATE `groups...

### ISSUE THREAD

**Issue by saraycp** [openSUSE/open-build-service#5809]
threw this 1 times
<pre>
Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction: UPDATE `groups` SET `updated_at` = &#39;2018-09-07 07:54:55.074114&#39; WHERE `groups`.`id` = 4
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b922ecfaeec99000a3566c5)

**Comment by saraycp** [comment]
Something similar happened in the past:
https://github.com/openSUSE/open-build-service/issues/3520

**Comment by hennevogel** [comment]
Everytime the deadlocks occur it's because of a different set of circumstances. The exception just looks the same. I don't think it makes sense to create issues for them...
