### ISSUE TITLE
migrate_options_yml is problematic

### ISSUE THREAD

**Issue by bugfinder** [openSUSE/open-build-service#5825]
- dir api/config is usually mode 755 owned by root
- api/config/options.yml is owned by root
usually I'd call rake tasks only with wwwrun user (with run_in_api wrapper) ...
okay, once I got around that, migration ran.

diffing options.yml.bkp and options.yml, I see that:
- all comments are being removed
- I do not even know the syntax to re-add the comments
- looks like all quoting is gone, might be an issue but not in my case

**Comment by hennevogel** [comment]
I guess for the permissions and how you deal with that (run_in_api) there is no solution. `run_in_api` is just a workaround that help you to not forget that you are root...

No idea about the comments, @bgeuken? Maybe it's enough to document this in the release notes.

> looks like all quoting is gone, might be an issue but not in my case

It's not an issue.
