### ISSUE TITLE
request diff xml elements are breaking some tools

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#5843]
The request diff in xml form have suddenly the xml version at the wrong place.

Most likely due to the commits dropping ActiveXML, but this is currently breaking some tools.
build.opensuse.org is old enough not to show this breakage yet.

Example:
```
# osc api -X POST "/request/123?cmd=diff&view=xml"
<request id="123" actions="0"><?xml version="1.0"??>
<action type="maintenance_incident">

```

**Comment by vpereira** [comment]
> Most likely due to the commits dropping ActiveXML, but this is currently breaking some tools.
> build.opensuse.org is old enough not to show this breakage yet.

Hi Adrian,

I see the same issue here:

```osc api -X POST  "/request/635203?cmd=diff&view=xml" ```

```
<request id="635203" actions="0"><?xml version="1.0"??>
```

**Comment by vpereira** [comment]
@coolo the problem was in ```src/api/app/controllers/request_controller.rb#188``` do you think that we have it anywhere else?

**Comment by coolo** [comment]
I don't think we have many places left to concat xml :)
