### ISSUE TITLE
Multibuild always builds all variants, no way to disable single repositories

### ISSUE THREAD

**Issue by stoecker** [openSUSE/open-build-service#5852]
In OBS _multibuild is used a lot to build postgres packages. That's actually fine, but the multibuild system seems not to have a feature, that I can disable certain builds for certain plattforms. e.g. postgres 10 makes no sense for 42.x, whereas 93 variants make no sense for >= 15.0. But I can't disable the build for these repositories individually like I can do for normal packages.

Example: https://build.opensuse.org/package/show/Application:Geo/osml10n

**Comment by adrianschroeter** [comment]
That is true, but we should not include build repositories in _multibuild definition, because the source must be project agnostic.

We could think about how to disable a multibuild flavor in package meta data, but I am really not a friend of this due to the implications.

You used already version specific buildrequires so the unresolvable state is actually the expected ones.

So what is actual the problem here? Just that you get unresolvables in the UI?

**Comment by stoecker** [comment]
Yes. Looking at e.g. [https://build.opensuse.org/project/monitor?utf8=%E2%9C%93&commit=Filter%3A&failed=1&unresolvable=1&broken=1&blocked=1&dispatching=1&scheduled=1&building=1&finished=1&signing=1&locked=1&deleting=1&pkgname=&repo_openSUSE_Leap_15_0=1&repo_openSUSE_Leap_42_3=1&repo_openSUSE_Tumbleweed=1&arch_aarch64=1&arch_armv7l=1&arch_i586=1&arch_ppc64=1&arch_ppc64le=1&arch_s390x=1&arch_x86_64=1&project=Application%3AGeo&defaults=0] the unresolvables make the majority of entries. This overview is my main tool to check if the project is building fine or not. The goal is to fix all issues. When a certain number of issues can never be fixed that makes the overview useless.

OTOH there may be projects where build is not unresolvable, but will fail. In these cases useless building will waste resources.

**Comment by adrianschroeter** [comment]
sure, but multibuild is most likely just the wrong tool then. Either entire source is working or not. You could still work with local links if you need specific modifications, like build flags, for each build.

**Comment by stoecker** [comment]
Hmm. Multibuild is actually MUCH better than the previous solutions, so no - it is the right tool. I also don't want to disable each individually.

Essentially I want something like this:
<multibuild>
  <package disable="openSUSE_Leap_15.0,openSUSE_Tumbleweed">postgresql96</package>
  <package disable="openSUSE_Leap_42.3">postgresql10</package>
</multibuild>

**Comment by adrianschroeter** [comment]
That would make the source not project agnostic anymore. The repos can have different names in any project, so, no that is a no-go.

The only way I see atm would be to extend the package meta, but this would have quite some implications. So, doable, but not really a fan of that.

**Comment by coolo** [comment]
but if this is linked into another project with different repositories, it won't work anymore - this is what adrian means 'project agnostic'

**Comment by stoecker** [comment]
Your suggestion is

`<disable repository="openSUSE_Leap_42.3" package="osml10n:postgresql10" />`

in package meta then?

Would also be fine as long as multiple entries can be specified for one repository.

**Comment by stoecker** [comment]
A solution in the spec file would also be ok.

Like
```
%if 0%{?suse_version} >= 1500
mark as not buildable
%endif
```

**Comment by adrianschroeter** [comment]
On Freitag, 14. September 2018, 09:08:06 CEST wrote Dirk Stöcker:
> A solution in the spec file would also be ok.
> 
> Like
> ```
> %if 0%{?suse_version} >= 1500
> mark as not buildable
> %endif
> ```

you can achieve this with

%if 0%{?suse_version} >= 1500
ExclusiveArch: notme
%endif

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by adrianschroeter** [comment]
it is a misusage of ExlusiveArch and leads to "excluded" and not to "disabled", but should be enough in your case.

So closing this, since extending package meta would be really intrusive and I don't see a strong enough reason here atm.

**Comment by stoecker** [comment]
It seems the build service already supports this correctly. I did following based on your proposal and it does exactly what I requested (not setting exlucded, but it completely drops these build sources).

```
%if 0%{?suse_version} < 1500 && %{pgname} == "postgresql10"
ExclusiveArch:  do_not_build
%endif
%if 0%{?suse_version} == 1500 && %{pgname} == "postgresql93"
ExclusiveArch:  do_not_build
%endif
%if 0%{?suse_version} == 1500 && %{pgname} == "postgresql94"
ExclusiveArch:  do_not_build
%endif
%if 0%{?suse_version} == 1500 && %{pgname} == "postgresql95"
ExclusiveArch:  do_not_build
%endif
```

Could this please be documented in the multibuild documentation, so it is no longer secret knowledge?

**Comment by coolo** [comment]
you don't see a strong reason? It's like the 9th user or so to ask for this feature :(

**Comment by stoecker** [comment]
As a programmer I agree with Adrian - there is a useful solution so no additional work required :-)

It only needs to be documented properly, e.g. here: https://openbuildservice.org/help/manuals/obs-reference-guide/cha.obs.multibuild.html

**Comment by adrianschroeter** [comment]
On Freitag, 14. September 2018, 10:55:05 CEST wrote Dirk Stöcker:
> As a programmer I agree with Adrian - there is a useful solution so no additional work required :-)
> 
> It only needs to be documented properly, e.g. here: https://openbuildservice.org/help/manuals/obs-reference-guide/cha.obs.multibuild.html

I am a bit shy to document a misusage of ExclusiveArch ...

wondering if we may should introduce an OBS special tag (eg. #!ExcludeBuild) instead ...

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by stoecker** [comment]
It's not new. This is what is above the block I added:

```
%define pgname @BUILD_FLAVOR@
%if "%{pgname}" == ""
%define         pgname postgresql
ExclusiveArch:  do_not_build
%endif
```

**Comment by adrianschroeter** [comment]
sure, but still a misusage ;)

**Comment by mlschroe** [comment]
coolo: I don't get your last comment:

adrian: You need something that makes rpmbuild abort the build (independent of OBS). `ExclusiveArch: some_error_message` is not a bad way to do this. `%{error: foo}` does not work in older rpm versions.

**Comment by adrianschroeter** [comment]
I think coolo has staging projects in mind, but this is a different issue IMHO.

**Comment by adrianschroeter** [comment]
@mlschroe: right, it would be something OBS specific like the mentioned   #!ExcludeBuild  tag.

**Comment by mlschroe** [comment]
You misunderstood, this is not OBS specific!
