### ISSUE TITLE
[bootstrap] User navigation breaks too early in a new row

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#5856]
# Issue Description
![image](https://user-images.githubusercontent.com/3799140/45537848-ba9d0500-b805-11e8-89ca-361cb3855e4e.png)

See image. My name is not too long but as soon as I have > 100 issues, the personal navigation breaks. 

Expected Result
============
Break later

**Comment by bgeuken** [comment]
Fixed by @hellcp with #5894 :green_heart:
