### ISSUE TITLE
[production][package#view_file] incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#5857]
package#view_file threw this 3 times
<pre>
incompatible character encodings: ASCII-8BIT and UTF-8
</pre>
[https://build.opensuse.org/package/view_file/home:StefanBruens:branches:Printing/urw-base35-fonts/urw-base35-fonts.changes?expand=1](https://build.opensuse.org/package/view_file/home:StefanBruens:branches:Printing/urw-base35-fonts/urw-base35-fonts.changes?expand=1)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b99962eb8f0ea00140fcbbd)

**Comment by hennevogel** [comment]
Does not happen anymore...

**Comment by hennevogel** [comment]
Does not happen anymore...
