### ISSUE TITLE
[production][source#package_command] Mysql2::Error: Duplicate entry

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#5860]
source#package_command threw this 2 times
<pre>
Mysql2::Error: Duplicate entry &#39;home:apersaud:branches:devel:languages:python:numeric&#39; for key &#39;projects_name_index&#39;: INSERT INTO `projects` (`name`, `title`, `description`, `created_at`, `updated_at`) VALUES ...
</pre>
[https://api.opensuse.org/source/devel:languages:python:numeric/python-uncertainties?cmd=branch](https://api.opensuse.org/source/devel:languages:python:numeric/python-uncertainties?cmd=branch)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b8f5186fe4eac0006218d85)

**Comment by dmarcoux** [comment]
Missing validation on projects

**Comment by hennevogel** [comment]
Does not happen anymore...
