### ISSUE TITLE
[production][staging_projects#index] comparison of BsRequest with BsRequest failed

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#5873]
staging_projects#index threw this 103 times
<pre>
comparison of BsRequest with BsRequest failed
</pre>
[https://build.opensuse.org/project/staging_projects/openSUSE:Factory](https://build.opensuse.org/project/staging_projects/openSUSE:Factory)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b9e0ec689299f00140e91ad)

**Comment by nilxam** [comment]
FYI https://github.com/openSUSE/openSUSE-release-tools/issues/1696

**Comment by hennevogel** [comment]
Did not happen anymore since september...
