### ISSUE TITLE
Bootstrap views are flickering in Chrome (on some pages)

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#5939]
Some of our pages flicker (in Chrome) when js events are triggered / elements on the page are updated. This is because the right scrollbar is appearing and disappearing in a split second.

Pages where I have noticed this:

* Requests tab
* Attributes tab
* Package binaries page

I guess more, if not all pages are effected.

One way to reproduce is by going to the requests tab and select one of the dropdowns.

**Comment by Ana06** [comment]
Revisions as well
