### ISSUE TITLE
Bootstrap Package File Box

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#5949]
There are a couple of problems with the responsive datatable implementation. Especially for the file list boxes. If there is a file with a long enough name that would overflow it will trigger moving the actions down. 

![screenshot from 2018-09-28 16-04-27](https://user-images.githubusercontent.com/514785/46213203-42bbf800-c338-11e8-9e3c-01fb0db2264d.png)

I don't think this should ever happen if you have enough vertical screen space.

And if the file is ridiculously long everything breaks down.

![screenshot from 2018-09-28 16-10-29](https://user-images.githubusercontent.com/514785/46213524-0c32ad00-c339-11e8-9de7-09668698b891.png)

**Comment by hennevogel** [comment]
https://build.opensuse.org/package/show/home:hennevogel:pshow/progress

**Comment by hellcp** [comment]
Adding `table-responsive` class to that table fixes the issue, by introducing scrollbar, that's probably the easiest way to approach it from bootstrap pov
![screenshot from 2018-09-28 23-48-18](https://user-images.githubusercontent.com/30577011/46235091-05c42580-c379-11e8-9957-0535f2c624c7.png)
