### ISSUE TITLE
broken "check the rebuild time for this architecture"

### ISSUE THREAD

**Issue by KostyaSha** [openSUSE/open-build-service#595]
Go to https://build.opensuse.org/project/repository_state/openSUSE:Factory/standard
press "Check the rebuild time for this architecture"
"Could not collect infos about repository 98/x86_64"

**Comment by hennevogel** [comment]
Works for me 
![screenshot from 2015-02-03 15 12 05](https://cloud.githubusercontent.com/assets/514785/6021563/0c37510e-abb7-11e4-9108-9e8cd2b2e42b.png)

**Comment by KostyaSha** [comment]
Btw, choose jobs to some value and press check -> 404
