### ISSUE TITLE
Bootstrap - Broken Submit Package - Supersede Request 

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#5951]
# Issue Description
On the `package#show` page, when clicking on`Submit Package`, the `Supersede Request` section of the modal is broken. The checkbox is not clickable and the layout is wrong.

It works in the old UI, so it's clearly a Bootstrap UI bug.

Expected Result
============
I expect to be able to use the `Supersede Request` section from the `Submit Package` modal.

How to Reproduce
===============
1. Submit a request to a project by clicking on `Submit Package`.
2. Try to supersede the first request by clicking on `Submit Package` and checking the checkbox of the `Supersede Request` section.
3. It doesn't work and the layout is wrong.

Further Information
===============
![broken-submit-request-supersede](https://user-images.githubusercontent.com/1102934/46247156-8598d100-c407-11e8-87e2-f8a54a5cce41.png)

**Comment by Conan-Kudo** [comment]
The checkbox works when you tab to it and press the spacebar to select it. So it's just not clickable or something is covering it somehow...

**Comment by dmarcoux** [comment]
Thank you @Conan-Kudo for the added information. I didn't think about doing it this way.

**Comment by dmarcoux** [comment]
PR from @hellcp: #5956
