### ISSUE TITLE
Support SSO

### ISSUE THREAD

**Issue by hellcp** [openSUSE/open-build-service#5957]
**Is your feature request related to a problem? Please describe.**
OBS uses weird configuration for logging into openSUSE infrastructure, which is annoying, considering that when logging into any other openSUSE Service, like bugzilla or wiki, build service will log out of the session of OBS and vice versa.

**Describe the solution you'd like**
As there have been some plans laid down about having [Ipsilon](https://ipsilon-project.org/) by @Conan-Kudo it would be nice to start doing work that would allow for SSO integration with that.

**Describe alternatives you've considered**
Definitely not use https://build.opensuse.org/ICSLogin/auth-up anymore, it doesn't look secure whatever it's doing, some apache redirections and stuff, not cool

**Additional context**
![screenshot_2018-10-01 please login - opensuse org](https://user-images.githubusercontent.com/30577011/46269247-3a360e00-c540-11e8-8830-ea3d14555653.png) I hate the look of this page as well :P

**Comment by Conan-Kudo** [comment]
My suggestion would be to support OpenID Connect. This extension to OAuth2 adds Authentication information and gives you the ability to handle authorization information to process for privilege control. [Ipsilon](https://ipsilon-project.org/) supports providing an OIDC endpoint for applications and services, and this is an ideal way to work.

> [Ipsilon](https://ipsilon-project.org/) by @Conan-Kudo 

To make it abundantly clear, I did not write Ipsilon. That honor goes to @puiterwijk. I'm just working on packaging Ipsilon for openSUSE to potentially use as the future SSO platform to replace the awful existing one.

**Comment by hennevogel** [comment]
> considering that when logging into any other openSUSE Service, like bugzilla or wiki, build service will log out of the session of OBS and vice versa.

If that is so, it's a bug. One you should report. 

>  it doesn't look secure whatever it's doing, some apache redirections and stuff, not cool

Have you considered, that you not knowing what is going on, is not the best basis for requesting a feature replacing the part you know next to nothing about? :wink: 

What we are using is already just a normal SSO solution using the [CAS](https://en.wikipedia.org/wiki/Central_Authentication_Service) pattern. Nothing fancy. Neither weird, nor awful.

So what is left is to support some other protocol/pattern, like OAuth2, because you have a specific need for this in your setup. Do you?

**Comment by hellcp** [comment]
@hennevogel shot in the dark, one that didn't pay off :D

**Comment by hennevogel** [comment]
@hellcp if you really get logged out of all services by logging into another then please report this to admin@opensuse.org so we can figure out what is going on. TIA

**Comment by Conan-Kudo** [comment]
> So what is left is to support some other protocol/pattern, like OAuth2, because you have a specific need for this in your setup. Do you?

Fedora prefers OpenID Connect over the alternatives for applications (though Ipsilon does support a multitude of AuthN+AuthZ mechanisms). I prefer it for its simplicity to use and better usability for mobile apps and such.

**Comment by yakatz** [comment]
> What we are using is already just a normal SSO solution using the [CAS](https://en.wikipedia.org/wiki/Central_Authentication_Service) pattern. Nothing fancy. Neither weird, nor awful. Definitely secure.

Is there any documentation for how to set up something like this? We would love to use CAS for our instance, but I couldn't find the documentation.

**Comment by andrewshadura** [comment]
@hellcp-work, have a look at my PR, in theory it supports any omniauth strategy.

**Comment by andrewshadura** [comment]
Most code there should be easily rebasable, I just haven’t had time to work on it. We currently run 2.10 in production with this patch set applied, and we have a couple of more changes on top I will submit soon.
