### ISSUE TITLE
Hit enter in a dialog input cancels it

### ISSUE THREAD

**Issue by mdeniz** [openSUSE/open-build-service#5959]
# Issue Description
In bootstrap version of the UI when hitting enter in an input field of a modal dialog it closes it instead of sending it (aka main action, Accept or Delete)

Expected Result
============
When enter is hit inside an input field of a dialog the main action is performed.

How to Reproduce
===============
With beta program enabled:
1. Go to https://build.opensuse.org/package/show/OBS:Server:Unstable/obs-server
2. Click on Branch package
3. Write inside the "Branch package name" and hit enter
4. See how the dialog is canceled instead of sent to Accept

**Comment by ChrisBr** [comment]
@mdeniz can we close this one?

**Comment by mdeniz** [comment]
Sure!
