### ISSUE TITLE
Bootstrap: Wrong icon size for mobile devices on main page

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#5974]
The icons on the news and latest updates sidebar are not scaling on smaller devices (screenshot was taken on my tablet (Samsung Galaxy S2 8", 1536x2048 pixels) ).

![screenshot_20181001-221705c](https://user-images.githubusercontent.com/968949/46335023-75ab0800-c626-11e8-8b74-dee9c4987eca.png)

**Comment by dmarcoux** [comment]
We need to have a CSS media rule for this, so it will change the size of icons depending on the screen size. Something along those lines: https://stackoverflow.com/a/29299793

**Comment by coolo** [comment]
I find https://stackoverflow.com/a/31352309 more practical.

**Comment by ChrisBr** [comment]
JFYI: it works on my iPhone

![image](https://user-images.githubusercontent.com/3799140/46336693-dbe65980-c62b-11e8-8ae5-faf8d80b88c9.png)

**Comment by eduardoj** [comment]
> JFYI: it works on my iPhone

In my android phone works too, without the icon problem @bgeuken pointed out.

**Comment by saraycp** [comment]
Also fine in my phone. I think the problem is medium-size screens / tablets.

**Comment by hennevogel** [comment]
It is never the device. The web is fluid. It is always just some [responsive breakpoint](https://responsivedesign.is/strategy/page-layout/defining-breakpoints/).
