### ISSUE TITLE
[mobile] Attributes table needs scrolling

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#5984]
# Issue Description
![image](https://user-images.githubusercontent.com/3799140/46337471-e0137680-c62d-11e8-8b1f-dad67d19758f.png)

Tested with iPhone 8

**Comment by mdeniz** [comment]
In mine it works, if you drag it horizontally it scrolls...

**Comment by eduardoj** [comment]
> In mine it works, if you drag it horizontally it scrolls...

In mine works too, but the horizontall scroll bar is not shown at the beginning, like the picture @ChrisBr put. The horizontal scrollbar is not obvious. :thinking:

**Comment by ChrisBr** [comment]
But it should also be smaller IMHO
