### ISSUE TITLE
[mobile] Breadcrumbs are gone on mobile

### ISSUE THREAD

**Issue by mdeniz** [openSUSE/open-build-service#5989]
# Issue Description
Main navigation behind the burger button is broken. The breadcrumbs disappear. Tested in mobile Xiaomi Mi 5S Plus

![image](https://user-images.githubusercontent.com/11314634/46338554-c0318200-c630-11e8-9eb4-92f261fa0338.png)

Expected Result
============
Breadcrumbs is shown properly

How to Reproduce
===============
1. Go to the main page on a mobile device
2. Click on the burger icon 
4. See the bug

**Comment by ChrisBr** [comment]
That the links are too close together is tracked here: https://github.com/openSUSE/open-build-service/issues/5977

**Comment by mdeniz** [comment]
Changed the issue to not cover the links @ChrisBr

**Comment by DavidKang** [comment]
This was resolved :smile_cat:
