### ISSUE TITLE
possible stuck with job files

### ISSUE THREAD

**Issue by KostyaSha** [openSUSE/open-build-service#603]
issue: "gcc" status building, can't connect to log output, stuck for a long time.
Probably problem in uri ip that doesn't belong to src/rep/workers.

```
<jobstatus code="building">
  <starttime>1390497371</starttime>
  <workerid>worker2:1</workerid>
  <hostarch>x86_64</hostarch>
  <uri>http://10.6.136.54:42264</uri>
  <jobid>6d1f905005afab7f74aec3510611ca00</jobid>
</jobstatus>
```

Resolved: `rm -rf jobs/*/*`, restart scheduler.
Solution: use hostname instead ip?

**Comment by vpereira** [comment]
closed. if you think that still a problem, please feel free to re-open it!

thank you!
