### ISSUE TITLE
search not working properly

### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#6030]
searching for ```OBS:Test``` cannot find an existing project: https://build.opensuse.org/project/show/OBS:Test. Looking the searchd query log, there are many more found results than the number of results displayed

```
api:/srv/www/obs/api/log # grep OBS:Test production.searchd.query.log
[Fri Oct  5 09:03:23.984 2018] 0.003 sec 0.003 sec [ext2/2/ext 14 (0,20)] [`package_core`, `project_core] @(name) OBS:Test
[Fri Oct  5 09:20:25.631 2018] 0.003 sec 0.003 sec [ext2/2/ext 14 (0,20)] [`package_core`, `project_core] @(name) OBS:Test
[Fri Oct  5 09:20:48.872 2018] 0.001 sec 0.001 sec [ext2/2/ext 6 (0,20)] [project_core] @(name) OBS:Test
[Fri Oct  5 09:21:12.756 2018] 0.002 sec 0.002 sec [ext2/2/ext 77 (0,20)] [project_core] @(name,title,description) OBS:Test
```

**Comment by vpereira** [comment]
![screenshot_2018-10-05_12-57-35](https://user-images.githubusercontent.com/37418/46531676-5d452280-c89e-11e8-9ab7-e330f593fd05.png)

that's the whole results searching from ```OBS:Test``` looking the [log file](http://sphinxsearch.com/docs/current/plain-log-format.html), it was found more than 100

**Comment by saraycp** [comment]
@vpereira I think this is the problem. https://github.com/openSUSE/open-build-service/wiki/Troubleshooting

I'll resolve it!

**Comment by vpereira** [comment]
Hi @saraycp 

It's worth a try!

however looking the ```production.searchd.query.log``` looks like there are more results being found than being displayed

**Comment by saraycp** [comment]
Done! now `OBS:Test` appears in the search result. The search index was out of date since 2nd of October. 

![search_obs_test](https://user-images.githubusercontent.com/2581944/46532648-10634b00-c8a2-11e8-93a2-eceb1267235c.png)

This is the log output now:
![log_output](https://user-images.githubusercontent.com/2581944/46532840-d0e92e80-c8a2-11e8-9bcb-bb7ac550257c.png)

**Comment by ChrisBr** [comment]
Seems resolved

**Comment by dmarcoux** [comment]
I moved the troubleshooting page that @saraycp linked into the troubleshooting section of the main deployment page: https://github.com/openSUSE/open-build-service/wiki/Deployment-of-build.opensuse.org#search. This way, everything is on the same page.
