### ISSUE TITLE
Status API: need a way to retrieve current repo id

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#6035]
I get an event if a repo is published, but I have no way to retrieve the current repo build id on startup of my bot.

**Comment by adrianschroeter** [comment]
You can get it for the entire repository or do you speak about single product builds here?

The buildid is the internal publish_id:

```
# osc api /published/openSUSE:Tools/openSUSE_Factory?view=status
<status code="succeeded">
  <starttime>1538660976</starttime>
  <endtime>1538660980</endtime>
  <buildid>1533135199</buildid>
</status>

```

**Comment by coolo** [comment]
That will do - please make sure there is a reference to this route in the status api documentation.

**Comment by adrianschroeter** [comment]
Done here: https://github.com/openSUSE/open-build-service/pull/6048
