### ISSUE TITLE
Use bootstrap styling for editor

### ISSUE THREAD

**Issue by hellcp** [openSUSE/open-build-service#6042]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to scroll up or down to change a setting in CodeMirror. Also, it breaks in many ways on mobile

**Describe the solution you'd like**
Use bootstrap's sticky-top and create sticky-bottom based on that to move elements of the interface to be always in viewpoint. Move some settings which are in view now, out of view to accommodate mobile editing.

**Additional context**
Some mockups
![screenshot from 2018-10-06 13-12-48](https://user-images.githubusercontent.com/30577011/46570742-9bf3df00-c969-11e8-8775-cc495cf9900a.png)
![screenshot from 2018-10-06 13-13-38](https://user-images.githubusercontent.com/30577011/46570746-b2019f80-c969-11e8-8b94-291c18ccd481.png)

**Comment by saraycp** [comment]
Your proposal looks great! :heart_eyes: Thanks! We could bear in mind for future sprints.

**Comment by Ana06** [comment]
@hellcp looks like you have some work done already, can you share it (PR or branch)? :cupid:

**Comment by hellcp** [comment]
@Ana06 There were way too many issues with that. Mainly js issues, which I didn't even start to solve. Also settings dropdown hid after clicking select and buttons (and modal will be annoying in the long run). I might come back to that when I have time to properly fix all the issues that might pop up.

**Comment by Ana06** [comment]
@hellcp ok! :wink: Should we assign this issue to you? It sounds like you plan/would like to work on it. I don't think we are in a hurry to implement this, so there is no time pressure.
