### ISSUE TITLE
[beta] feedback: excessive UI padding in Users tab (and maybe others)

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/open-build-service#6049]
In the new UI, the padding for .td seems excessive. You already have 150% line-heights, and then there is another 150%rem of padding (top 75% and bottom 75%). This wastes a lot of space and makes it more difficult to read. I would suggest having TH with current, extra padding, but reducing padding of all TD, like it seems it was done in the file list.

![now](https://user-images.githubusercontent.com/1211498/46603847-9b3b8400-caf4-11e8-95a2-e892f1a56376.png)

vs. 0 padding,

![0padding](https://user-images.githubusercontent.com/1211498/46603858-a42c5580-caf4-11e8-8ca0-777bc0650b0c.jpg)

Maybe reducing padding to 25%?

PS. Thank you for the redesign. Overall, the UI feels a lot more modern. :+1:

**Comment by dmarcoux** [comment]
Thank you @AdamMajer for your feedback. 

I think the padding needs to be somewhat between the current padding and no padding at all.

**Comment by hellcp** [comment]
Something that should probably applied to all tables, `.table-sm` class, limits that padding.
