### ISSUE TITLE
Editor doesn't always show underscores

### ISSUE THREAD

**Issue by sleep-walker** [openSUSE/open-build-service#605]
As you can see on screenshot of https://build.opensuse.org/package/view_file/devel:languages:python/python-botocore/python-botocore.spec?rev=19
here http://www.enlightenment.org/ss/e-5312ebbc0fcf64.74552608.png , some underscores are not shown. Check python_sitelib on last few lines.

**Comment by hennevogel** [comment]
Fixed in #843
