### ISSUE TITLE
Can't create status check for Leap staging projects

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#6051]
It works fine for IBS stagings, but for some reason I get a 404 when doing the same on Leap:15.1

```
coolo@e120#openSUSE-release-tools>cat t
<check><url>https://openqa.opensuse.org/tests/765814</url><state>success</state><name>rescue_system@64bit</name></check>
coolo@e120#openSUSE-release-tools>osc api -X POST -T t /status_reports/published/openSUSE:Leap:15.1:Staging:D/images/reports/1538726035
Server returned an error: HTTP Error 404: Not Found
```

Curious me found this in the log:

```
ActionController::RoutingError (No route matches [POST] "/status_reports/published/openSUSE:Leap:15.1:Staging:D/images/reports/1538726035"):
```

This is the route to match:
`POST                /status_reports/published/:project_name/:repository_name/reports/:report_uuid(.:format) status/checks#update`

-> no idea what's wrong

**Comment by hennevogel** [comment]
@dmarcoux would be awesome if you could look into this. @coolo is trying to use the status api...

**Comment by DavidKang** [comment]
I think is because the `contraints` is missing for thoses routes

**Comment by hennevogel** [comment]
Sorry @dmarcoux I did not realize that @mdeniz is bug-squad.
