### ISSUE TITLE
Bootstrap - Package#edit still available (outside the modal)

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#6061]
# Issue Description
We forgot that the package#edit view is still available directly and it isn't using Bootstrap. Our users don't go there unless they know the URL.

Expected Result
============
We should redirect our users to the package overview and open the modal. Another solution is to make a Bootstrap version of the page.

How to Reproduce
===============
1. Go to https://build.opensuse.org/package/edit/home:dmarcoux/pass-otp
2. See old UI when it should be the new UI

**Comment by mdeniz** [comment]
This issue is not an issue really.

We added the new UI for the beta users, but for who are not in the beta program this is still valid.
