### ISSUE TITLE
What browsers are we supporting?

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#6063]
It is not clear to me what browser OBS should support. I think this should be documented. @openSUSE/open-build-service  any ideas/opinions?

**Comment by hellcp** [comment]
https://getbootstrap.com/docs/4.1/getting-started/browsers-devices/ ;)
I doubt there is any other component in OBS that would prevent support for newer devices

**Comment by Ana06** [comment]
@hellcp 

> https://getbootstrap.com/docs/4.1/getting-started/browsers-devices/ ;)
I doubt there is any other component in OBS that would prevent support for newer devices

There are other things that could make it uncompatible not Bootrstrap related. For example someone being tempted to use Javascript backtick, which is great but not compatible with Internet Explorer... :sob:
