### ISSUE TITLE
Confusing icon conflicting with Bootstrap one

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#6080]
I find this cross to the left in the alert message really confusing:

![image](https://user-images.githubusercontent.com/16052290/46743595-b3a0cf80-cca9-11e8-93e1-a2950318291a.png)

I have clicked several times trying to close the alert, confusing it with the close button, which is in the right and built-in in the Bootstrap alert. 

The question is, should we change it by another icon or should we just remove all the icons that appear to the left? Bootstrap have different colors for different kind of alert, so I would just remove all. Someone against it @openSUSE/open-build-service?

**Comment by dmarcoux** [comment]
I would go with the `Announcement` icons from https://obs-patterns.netlify.com/content/icons.html for icons of the flash messages.

**Comment by Ana06** [comment]
@dmarcoux 

> I would go with the Announcement icons from https://obs-patterns.netlify.com/content/icons.html for icons of the flash messages.

but the problem would be the same if you use the delete one there! this is not deleting anything and does not add any useful information.

**Comment by mdeniz** [comment]
I wouldn't remove the colors. As color blind people may have problems with it. Better to have an icon for every single case.

**Comment by coolo** [comment]
It should be noted that *most* colour blind people will still see different colours there - just differents ones than @Ana06 (https://ux.stackexchange.com/a/99240)

Bootstrap recommends using expressive texts and use the colour only as support. The announcement alert icon sounds like a good compromise to me though.

**Comment by Ana06** [comment]
But this icon is even confusing for people who can see it ... At least we should consider a different alternative that is not so similar to Bootstrap one

**Comment by coolo** [comment]
"this icons" == fa-remove?

**Comment by saraycp** [comment]
I agree, we need, at least, better icons for that. I think @dmarcoux proposal is using:
![announcements_icons](https://user-images.githubusercontent.com/2581944/46980263-5c996100-d0d4-11e8-86e3-000359d6f0bd.png)
and I like it. Please have a look to this PR:  #6100
