### ISSUE TITLE
[production][feeds#notifications] ActionView::Template::Error

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#6087]
feeds#notifications threw this 1 time
<pre>
ActionView::Template::Error
</pre>
[https://build.opensuse.org/user/feed/UcDUYtMjzx5AvEhyzDzs9H9Y](https://build.opensuse.org/user/feed/UcDUYtMjzx5AvEhyzDzs9H9Y)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5bc061921e8cf30014bb89fa)

**Comment by coolo** [comment]
this is spams errbit pretty heavily. And it's an easy fix: the request differ needs to catch missing projects and packages

**Comment by hennevogel** [comment]
> And it's an easy fix

Strange, it seems the PR you've sent didn't make it ;-)

**Comment by coolo** [comment]
I'm not on vacation!

**Comment by hennevogel** [comment]
The exception is gone and did not happen anymore since 21 days...
