### ISSUE TITLE
Don't use primary and secondary colors for icons that are supposed to be green and blue

### ISSUE THREAD

**Issue by hellcp** [openSUSE/open-build-service#6091]
# Issue Description
When end user decides to theme OBS, they might face the issue of checkmarks being in their primary brand colour, which might not necessarily be green, which is a colour of success (which I guess is the point, checkmarks should probably be green). There are some other issues, related to secondary colour, mainly info icons, which again might be in a different colour than blue.

Expected Result
============
info and success colours are used for symbolising success and info metaphores.

Further Information
===============
Noticed the issue with:
* Main -> News -> info-circle text-secondary
* Package -> Show -> Build Result -> success text-primary
* Package -> Repositories -> fa-check text-primary
* Package -> Users -> fa-plus-circle text-primary

**Comment by dmarcoux** [comment]
Thank you again @hellcp! This is a valid concern and we will address it.

As a note to ourselves, don't forget to update the [OBS Pattern Library](https://github.com/openSUSE/obs-patterns).

**Comment by bgeuken** [comment]
This also applies for some of the links and labels we color like the links for build states. We currently use text-primary to color them green / text-danger to color them red.

**Comment by bgeuken** [comment]
That should be solved #6154
