### ISSUE TITLE
Cannot watch more than 20 commits in openSUSE:Factory/glibc page

### ISSUE THREAD

**Issue by Zenitur** [openSUSE/open-build-service#6094]
# Issue Description
I open https://build.opensuse.org/package/revisions/openSUSE:Factory/glibc?showall=1 page, then press "Show all". I didn't see all the commits, but only 20 last commits!

Expected Result
============
I didn't see all the commits, but only 20 last commits!

How to Reproduce
===============
1. Go to 'https://build.opensuse.org/package/revisions/openSUSE:Factory/glibc'
2. Click on 'Show all'
3. Scroll down to 'the end of page'
4. See error "the last revision is 205, not 1"

**Comment by dmarcoux** [comment]
Thank you for your report. This is a regression and it was introduced in https://github.com/openSUSE/open-build-service/pull/5473. I am fixing this ASAP.
