### ISSUE TITLE
[beta] Trigger rebuild button can be accidentally triggered when trying to download logfile 

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/open-build-service#6099]
In the new Beta version, when viewing the logs while logged, the buttons for "Download logfile" and "Trigger Rebuild" are next to each other. This can cause unnecessary rebuilds by accident.

* Please move the other wide of the window, and/or
* Add confirmation to rebuild trigger.

Either is OK and better than current state.

Any preferences?

**Comment by coolo** [comment]
For reference: old and new

![old](https://user-images.githubusercontent.com/1067203/46993411-5bd1f080-d10f-11e8-91d3-d6fdfa4149ca.png)

![new](https://user-images.githubusercontent.com/1067203/46993443-8754db00-d10f-11e8-8953-36f090d4a917.png)

I disagree with the solution to confirm - rebuilding especially failed packages is a very common action, a confirm dialog would get in my workflow a lot.

I wonder if the green button just isn't too clickable :)

**Comment by coolo** [comment]
Perhaps this is just old habits of clicking the most right link?

**Comment by AdamMajer** [comment]
On 2018-10-16 6:54 a.m., Stephan Kulow wrote:
> Perhaps this is just old habits of clicking the most right link?

The buttons are just very close. In old version, they at least were on separate lines. So, maybe
have the rebuild button on the right side of the window? Is that ok?

**Comment by coolo** [comment]
I find this a little overreacting to a potential problem - and the middle of the buttons are even further away in the new UI.

**Comment by dmarcoux** [comment]
I don't agree with having buttons so far apart from each other. Maybe in addition to my previous comment, we could increase the distance a bit between the buttons.

**Comment by DavidKang** [comment]
Looking into it, I think we could separate a little bit the buttons and also change the colour of `Trigger rebuild' to orange

**Comment by dmarcoux** [comment]
I like your suggestion @DavidKang
