### ISSUE TITLE
The actual binaries published in the repository aren't always reflected in the web ui.

### ISSUE THREAD

**Issue by plater** [openSUSE/open-build-service#6123]
I had libmlt binaries present in my home:plater's Tumbleweed and Factory repositories published 28-Sep-2018 09:54 although the web ui was showing the newly built versions. This caused critical problems in attempting to fix this bug:
https://bugzilla.opensuse.org/show_bug.cgi?id=1068792#c116
Reported in:
https://bugzilla.opensuse.org/show_bug.cgi?id=1112615

I would expect the web ui to reflect the version published in the repository or to give an error if they differ.

You will note that the newly built binaries had days to publish and if I disable publishing I religiously disable the build first. In the case of home:plater/libmlt publishing has never been disabled.
You will also note from bug 1068792 starting at comment 113 I built three different libmlt packages over a period of 3 days and the reporter was only seeing the 28-Sep-2018 09:54 libmlt 6.10.0-118.1.x86_64 which was built prior to me deleting home:plater/libmlt and rebranching it.

How to Reproduce
===============
Don't know how it happened but ghost packages have been a problem for a long time See:
https://bugzilla.opensuse.org/show_bug.cgi?id=725211 and
https://bugzilla.opensuse.org/show_bug.cgi?id=958899

**Comment by trevorsandy** [comment]
**Similar behaviour in my project**

Although my publish flag is set to on, my latest build (v2.3.7 published on 25-03-2019) is not reflected in the repository. 

![Screenshot - 27_03_2019 , 14_25_09](https://user-images.githubusercontent.com/13388970/55079583-c020b500-509c-11e9-8b23-d3098515610b.png)

The latest build does exist and can be downloaded from within the access controlled area of the project however. Clicking the 'Download' link in the image below does retrieve the correct build.

![Screenshot - 27_03_2019 , 14_20_16](https://user-images.githubusercontent.com/13388970/55079673-eb0b0900-509c-11e9-8b15-18840afb09c1.png)

But when I click the 'Go to download repository' link, the location presented shows the old build asset and last modified date.

![Screenshot - 27_03_2019 , 14_21_56](https://user-images.githubusercontent.com/13388970/55079799-36bdb280-509d-11e9-9e36-9235def8f01f.png)

The build asset presented is the previous build, not the latest.

![Screenshot - 27_03_2019 , 14_22_36](https://user-images.githubusercontent.com/13388970/55079936-7b494e00-509d-11e9-8864-b5cee91a498c.png)

For my Arch Extra build, the repository asset is even older (v2.3.3) than the previous build (v2.3.6).

![Screenshot - 27_03_2019 , 14_39_37](https://user-images.githubusercontent.com/13388970/55080454-79cc5580-509e-11e9-8d0d-afda0f9091d4.png)
![Screenshot - 27_03_2019 , 14_39_57](https://user-images.githubusercontent.com/13388970/55080455-7a64ec00-509e-11e9-8e30-d509550b8626.png)
![Screenshot - 27_03_2019 , 14_40_23](https://user-images.githubusercontent.com/13388970/55080457-7a64ec00-509e-11e9-8f0e-96033a616641.png)
![Screenshot - 27_03_2019 , 14_48_55](https://user-images.githubusercontent.com/13388970/55081085-7eddd480-509f-11e9-9c78-9fdb584bd397.png)

It does not make sense for me to publish the AC'd link to the correct build so I am not able to expose access to my latest build. 

Please advise.

Cheers,

**Comment by plater** [comment]
This is a very irritating transient problem, the allegedly published binaries in the web ui and shown in osc result must be verified as the same as the ones in the actual repository.

**Comment by coolo** [comment]
See https://github.com/openSUSE/open-build-service/issues/7281

**Comment by trevorsandy** [comment]
Stephan, 

Many thanks for your guidance explained in #7281. I was thrown off by the 'Success' status.

![Screenshot - 27_03_2019 , 16_45_33](https://user-images.githubusercontent.com/13388970/55092073-34198800-50b2-11e9-8099-d34c51d64f85.png)

I now understand the Success status only pertains to the build job while the clock icon shows the publishing status is pending.

![Screenshot - 27_03_2019 , 16_48_11](https://user-images.githubusercontent.com/13388970/55092196-69be7100-50b2-11e9-849a-71bcc04a86b4.png)

And the truck icon indicates it's completion.

![Screenshot - 27_03_2019 , 16_47_28](https://user-images.githubusercontent.com/13388970/55092218-72af4280-50b2-11e9-9b3c-a7cea812e2d4.png)

Cheers,

**Comment by plater** [comment]
@hennevogel so this bug remains forever or did I miss the fix that prevents the binaries shown as published by the web ui and osc result from being different from the ones in the physical repository?
