### ISSUE TITLE
add file listing for rpms

### ISSUE THREAD

**Issue by KostyaSha** [openSUSE/open-build-service#613]
Feature request. 
Like in koji when click on built rpm it make sense to show file list.
https://build.opensuse.org/package/binary/OBS:Server:2.5/rubygem-rdoc?arch=x86_64&filename=rubygem-rdoc-4.0.1-5.1.x86_64.rpm&repository=openSUSE_13.1
http://koji.fedoraproject.org/koji/rpminfo?rpmID=4292064

**Comment by dmarcoux** [comment]
The PR #13419 was reverted in #13455.
