### ISSUE TITLE
Searching for just a version kills OBS

### ISSUE THREAD

**Issue by dmacvicar** [openSUSE/open-build-service#6130]
# Issue Description

If your search string is just "1", the code does a search for any package where the version starts with "1". This currently kills OBS (the query on Factory takes over 2 hours).

Expected Result
============

API should forbid searches that affect the stability of the service eg. reject searches with no package name component (and return the proper HTTP code, like _400 Bad Request_).

How to Reproduce
===============
Call the API specifying a `starts-with(@versrel ... ` clause, without a clause on `@name`.

Further Information
===============

* https://github.com/openSUSE/software-o-o/issues/404

**Comment by vpereira** [comment]
it looks like it was fixed with: https://github.com/openSUSE/open-build-service/pull/6131
