### ISSUE TITLE
[production][results#show] No route matches {:action=>"index", :controller=>"webui/main"}

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#6146]
results#show threw this 1 times
<pre>
No route matches {:action=&gt;&quot;index&quot;, :controller=&gt;&quot;webui/main&quot;}
</pre>
[https://build.opensuse.org/peek/results](https://build.opensuse.org/peek/results)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5bd640fe822b300010071285)

**Comment by hennevogel** [comment]
the exception is gone...
