### ISSUE TITLE
Truck icon in the new frontend does not shown if built package is published or only built.

### ISSUE THREAD

**Issue by SergioAtSUSE** [openSUSE/open-build-service#6159]
# Issue Description

Truck icon in the new frontend is not shown as expected.
![image](https://user-images.githubusercontent.com/25484865/47778587-799a7a80-dcf7-11e8-9713-ce295c85d3d2.png)

Expected Result
============
Expected the icons from the old frontend:
![image](https://user-images.githubusercontent.com/25484865/47778623-8e770e00-dcf7-11e8-890f-9c9cc46daa04.png)

How to Reproduce
===============
1. With beta program activated.
2. Let OBS Build a package.
3. Enable more than one repository.
4. Enable publish only for one of them
5. See confusing truck about publish status.

Further Information
===============
* https://build.opensuse.org/package/show/home:SLindoMansilla:branches:openSUSE:Leap:15.0/openQA

**Comment by ChrisBr** [comment]
Hm, it is, see the one lorry is flipped?

![image](https://user-images.githubusercontent.com/3799140/47780004-c764b200-dcfa-11e8-9190-53c944161c3e.png)

But I understand your confusion, it is hard to recognize and also hard to remember which direction is published and which is unpublished...

**Comment by dmarcoux** [comment]
We will need to update obs-patterns if we change the icon.

**Comment by bgeuken** [comment]
Let's use a different icon for that, eg. a lorry with an empty loading area. I guess it's not possible to adjust the existing font awesome icon? Maybe we could get this by stacking a white square on top of it... :thinking:

**Comment by ChrisBr** [comment]
>  Maybe we could get this by stacking a white square on top of it... 

I would prefer to not do a 'hack' like this....

What about this:

![image](https://user-images.githubusercontent.com/3799140/47783498-21697580-dd03-11e8-9d1b-74ef044a295e.png)

Please note that this would switch the `dolly-flatbed` to be used for unpublished instead of publishing but I think the loading truck gets the essence better of the publishing process. What do you think?
