### ISSUE TITLE
[production][] invalid date

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#6160]
threw this 82 times
<pre>
invalid date
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5bc866fe11d642000692f860)

**Comment by bgeuken** [comment]
```bash
/PROJECT_ROOT/app/models/binary_release.rb:207→ strptime
/PROJECT_ROOT/app/models/binary_release.rb:207→ indentical_to?
/PROJECT_ROOT/app/models/binary_release.rb:65→ block (2 levels) in update_binary_releases_via_json
/PROJECT_ROOT/app/models/binary_release.rb:43→ each
/PROJECT_ROOT/app/models/binary_release.rb:43→ block in update_binary_releases_via_json
```
It seems that the "buildtime" value returned from the backend (via GET /notificationpayload/:notification) is invalid / not parsable with the method we currently use. This started to happen on Thursday, 18th of October.

@mlschroe Was there some backend check that could have caused this? I checked the frontend code but there wasn't any changes recently.

**Comment by Ana06** [comment]
@bgeuken I think that it is `nil` and the problem is not in the backend, but in our code. It was introduced in https://github.com/openSUSE/open-build-service/commit/e9f6f907bc6af777fe244745baf3d5067c17ca4d#diff-49563098f1992cafd3f7c8195f53a383

**Comment by Ana06** [comment]
As this code changed, the exception is now different, and this issue is now tracked in https://github.com/openSUSE/open-build-service/issues/6240
