### ISSUE TITLE
Request help to clarify several CVEs on 2.7.4 release.

### ISSUE THREAD

**Issue by alee-ccu** [openSUSE/open-build-service#6166]
Hi,
Thank you for making `open-build-service`. I am trying to get version `2.7.4` package maintained in Debian. I noticed there are several CVEs opened and got fixed. I've cherry-pick some fixes. However, all of these are fixed in 2.9.x, but I cannot find all fixes arrived in 2.7.x version:
  https://github.com/openSUSE/open-build-service/commits/2.7

The `open-build-service` package version `2.7.4-3` are still marked as CVE affected on Debian BTS:
 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903797
 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911797
 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903796

May I request help from upstream to inspect these CVEs and determine it's affected or not?
Thanks again for making `open-build-service`.

**Comment by ChrisBr** [comment]
IIRC non of these vulnerabilities got fixed in 2.7.

We only support the last version (2.9) and best effort for previous version (2.8), please upgrade to 2.9.

Hope that helps :+1:

**Comment by alee-ccu** [comment]
Ah, that doesn't help Debian stable though. It seems to be a risky to spent a lot of efforts to get it and all it's depends packaged into Debian. And then out of support from upstream and will get drop from Debian due to security reason.

Do you have any plan on Long Term Support version or how long the version `2.9` will be supported?

**Comment by hennevogel** [comment]
> Do you have any plan on Long Term Support version

Nope, sorry.

> or how long the version 2.9 will be supported?

Until the next version, which is usually after a year.
