### ISSUE TITLE
*-32bit packages stopped to build for some packages

### ISSUE THREAD

**Issue by Zenitur** [openSUSE/open-build-service#6172]
# Issue Description
A year ago, I'd built Glibc 2.17 for SLES 11. There is it:
https://build.opensuse.org/package/show/home:linux4humans:sle11_software:glibc/glibc

Now I'd build Glibc 2.12 for this distro.
https://build.opensuse.org/package/show/home:linux4humans:temp/glibc

It sucessfully builds, but there is no glibc-32bit package. First, I checked my baselibs.conf. There is no error there. Second, I'd look at my previous package. I found only an old glibc-32bit-2.17-4.**52**.1 package, however the main package has 2.17-4.**53**.1 version.
https://download.opensuse.org/repositories/home:/linux4humans:/sle11_software:/glibc/SLE_11_SP4/x86_64/

It looks like *-32bit packages stopped to build at some moment.

Expected Result
============
*-32bit packages must to appear

How to Reproduce
===============
1. Go to 'https://build.opensuse.org/package/show/home:linux4humans:temp/glibc'
2. Click on 'Make a branck'
3. Scroll down to 'Build results'
4. See error "no glibc-2.12-32bit-x86_64 package"

Further Information
===============
* A link to an OBS instance showing the issue
https://build.opensuse.org/package/show/home:linux4humans:temp/glibc

* Exact server version (in case a private instance is used)

**Comment by coolo** [comment]
this is a problem specific to the glibc package (of sle11 even) - the 32bit package is built only from glibc.i686 you created in your first project but not in your second

**Comment by Zenitur** [comment]
P.S. Also there is a strange error:

![-29](https://user-images.githubusercontent.com/3435752/47962117-323f2180-e04a-11e8-8268-f87d915b58cd.png)
