### ISSUE TITLE
 inconsistent messages when changing my email address 

### ISSUE THREAD

**Issue by jnweiger** [openSUSE/open-build-service#618]
Version: https://pmbs.links2linux.de/ as of today (not sure how to find its
version number)

Reproduce: 
 - log in
 - click your username
 - click 'Edit your account'
a popup opens with Name: ... and E-Mail ....
 - enter an invalid E-Mail Address without an @ character.
 - press OK.

The next screen has both a success and an error message:

In green:
 'User data for user 'jnweiger' successfully updated. '
and in red:
 'Email must be a valid email address.'
![bug-868417_pmbs_email_change_invalid](https://f.cloud.github.com/assets/1108546/2428699/1aac7d0e-ac58-11e3-992a-f66496959786.png)

**Comment by hennevogel** [comment]
So this isn't an issue in 2.5 or later...
