### ISSUE TITLE
[beta] Comments section squishes authors

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/open-build-service#6183]
Names of comment's authors are squished. Maybe move them where there are nick handles and use them there instead?

For example, see,

https://build.opensuse.org/package/show/devel:libraries:c_c++/boost

![screen](https://user-images.githubusercontent.com/1211498/47999750-ccaf6b80-e103-11e8-9af1-550083ea575c.png)

**Comment by dmarcoux** [comment]
This happens when somehow the user avatars are not rendered, so the `alt` of the user avatar image is then displayed.

**Comment by bgeuken** [comment]
Let's render some default image or icon if the avatar image was not found.

**Comment by DavidKang** [comment]
It seems fixed
![screenshot_2018-11-30 show devel libraries c_c boost - opensuse build service](https://user-images.githubusercontent.com/1212806/49296223-f2882000-f4b7-11e8-995c-0fcdd28d5b7f.png)

Please, reopen this issue if still valid.

**Comment by dmarcoux** [comment]
@DavidKang I would reopen this. I would go with @bgeuken's proposal.

**Comment by hennevogel** [comment]
Especially as gravatar is on the blacklist of many ad-blockers...
