### ISSUE TITLE
osc build with _multibuild does not as expected

### ISSUE THREAD

**Issue by darix** [openSUSE/open-build-service#6199]
1. osc does not upload the _multibuild file as it does with the spec file, neither does osc tell the backend which flavor we want to build. which renders the change adrian did useless
2. no route in the backend exists that would handle this

FWIW ... I already had some issues about this:

https://github.com/openSUSE/open-build-service/issues/3573
https://github.com/openSUSE/open-build-service/issues/3523

Other multibuild isssues still open:

https://github.com/openSUSE/open-build-service/issues/3026
https://github.com/openSUSE/open-build-service/issues/4245

**Comment by darix** [comment]
Another issue ... osc getbinaries on project level does not grab all flavors

**Comment by lethliel** [comment]
> Another issue ... osc getbinaries on project level does not grab all flavors

@darix: Can you open an issue in the osc repo for this? 
This is related to https://github.com/openSUSE/osc/issues/338

**Comment by lethliel** [comment]
fixed with https://github.com/openSUSE/open-build-service/commit/198bca3b223328487efaf3674d777348d46214c9

Please open a new issue for the osc getbinaries bug
