### ISSUE TITLE
Improve logging in either scheduler or src_server: scheduler complains about "bad config" often

### ISSUE THREAD

**Issue by jsjhb** [openSUSE/open-build-service#620]
scheduler logs something like
vdrdevel/openSUSE_12.3: bad config (openSUSE.org:openSUSE:12.3:Update)
build is not possible for that project, until either
- a submission to the project happens, or
- the scheduler is restarted, or
- obs_admin --deep-check-project is run on that project.

Please see also:
http://lists.opensuse.org/opensuse-buildservice/2013-11/msg00011.html
and ff.

Can the logging in bs_sched be improved to shed light on the actual cause?
It might also be a originating from src_server, as there the project config is downloaded.

**Comment by mlschroe** [comment]
Fixed IMHO.
