### ISSUE TITLE
[bootstrap] Unresolvable build result hoover flaky

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#6200]
See screenshot

![peek 2018-11-07 14-57](https://user-images.githubusercontent.com/3799140/48135633-c3f29d00-e29d-11e8-8b3e-496b8e419b5d.gif)

From https://build.opensuse.org/package/show/graphics:darktable:master/darktable

reported by @darix

**Comment by coolo** [comment]
Looks like a dark table to me :)

**Comment by ChrisBr** [comment]
@coolo :man_facepalming:
