### ISSUE TITLE
Disable forced export LC_ALL=C

### ISSUE THREAD

**Issue by glixx** [openSUSE/open-build-service#6211]
All packages except Debian were packaged wrong with LC_ALL=C
In logs:
invalid utf-8 encoding in Basenames
How to disable it?

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.

**Comment by glixx** [comment]
tar.gz was created in Windows.
repacking in Linux solved issue.
