### ISSUE TITLE
Embed shortening URLs for sharing of every page

### ISSUE THREAD

**Issue by mcepl** [openSUSE/open-build-service#6213]
**Is your feature request related to a problem? Please describe.**
Sharing of URLs like https://build.opensuse.org/package/show/devel:languages:python/python-distorm3 is quite problematic. They are just so damned long.

**Describe the solution you'd like**
Would it be possible to have on every OSB page have a link to share with some shortened URL? Could we have openSUSE shortener (https://os.something)?

**Describe alternatives you've considered**
Of course, some public shortener (e.g., https://is.gd or https://da.gd/ ) could do, but it seems unfair to burden them with our own junk.

**Comment by hennevogel** [comment]
they are made to be burdened with your junk, right? So use them 🤠

**Comment by mcepl** [comment]
@hennevogel that's not the point: that discussion about the burden was only about having our own shortener, not about the main point of this issue: having the official short links (whatever shortener we use) on every OSB page.
