### ISSUE TITLE
Login from https://build.opensuse.org/ICSLogin/auth-up doesn't redirect on success

### ISSUE THREAD

**Issue by unguul** [openSUSE/open-build-service#6218]
A successful login attempt at https://build.opensuse.org/ICSLogin/auth-up does not redirect anywhere or display a "successful authentication" message.

Expected Result
============

I expect to be redirected to where I came from 
OR
be redirected to the homepage
OR
See a message of type "You're now logged in!"

How to Reproduce
===============
1. Go to https://build.opensuse.org/ICSLogin/auth-up
2. Fill in credentials
3. Click "Log in" button
4. Notice the uncertainty of whether something happened or not

Further Information
===============
* Apologies if this is not the correct place for me to report this.

**Comment by vpereira** [comment]
Hey @unguul 

The issue was fixed, you are going to be redirected to the right place (however without the flash message notification).

thank you for your feedback!
