### ISSUE TITLE
Adding existing project as a staging project does not work

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#6236]
When I want to add an existing project as a staging project it is not allowed and I get the message ``Name already taken``. 

Is this what should be expected? I think if the project already exists and it is not added to an existing staging workflow already it should be possible. If it is already assigned to an existing staging workflow we should show an error.

**Comment by bgeuken** [comment]
Is there a good reason to not the edit actions on the show page. The additional 'actions' column might eat some space, but I think there is enough space.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback](https://trello.com/c/K9U6WlG1/1655-address-feedback)
