### ISSUE TITLE
[production][] Trying to send frame through a closed connection. Frame is [#<AMQ::Protocol::MethodFrame:0x00007f...

### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#6249]
threw this 54 times
<pre>
Trying to send frame through a closed connection. Frame is [#&lt;AMQ::Protocol::MethodFrame:0x00007fe8e9d71b60 @payload=&quot;\x00&lt;\x00(\x00\x00\x06pubsub\x14opensuse.obs.metrics\x00&quot;, @channel=1&gt;, #&lt;AMQ::Protocol::HeaderFrame:0x00007fe8e9d70fa8 @payload=&quot;\x00&lt;\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x98\x00\x18application/octet-stream\x02\x00&quot;, @channel=1&gt;, #&lt;AMQ::Protocol::BodyFrame:0x00007fe8e9d70f58 @payload=&quot;login,access_point=webui value=1&quot;, @channel=1&gt;]
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5beaf096532fb8001468226b)

**Comment by coolo** [comment]
same as #6247 (as linked in errbit)
