### ISSUE TITLE
[production][project#show] <status code="400">
  <summary>/usr/local/sbin/bssign: 256</summary>
</status>


### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#6283]
project#show threw this 7 times
<pre>
&lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;/usr/local/sbin/bssign: 256&lt;/summary&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/project/show/home:hschaa:bnc441511](https://build.opensuse.org/project/show/home:hschaa:bnc441511)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5bed421e59e3bc000a502f1f)

**Comment by vpereira** [comment]
it still happens, however just for the case where the user isn't logged in. @adrianschroeter, any idea why?

**Comment by Ana06** [comment]
It is actually more than 7 times, many more :rofl:

**Comment by adrianschroeter** [comment]
that error seems to be okay (apart from the message), because that user has no master home project anmore. So he has no key anymore.

**Comment by adrianschroeter** [comment]
Why is that P1? Is there data corruption?

**Comment by adrianschroeter** [comment]
the webui should handle the situation without crashing

**Comment by bgeuken** [comment]
@adrianschroeter This happens for quite some home projects. Is this something that the syncing script could fix?

... and whyx don't they don't have a home project anymore? That sounds bad

**Comment by coolo** [comment]
note that all the crashes were triggered by spider bots (or developers :)

**Comment by dmarcoux** [comment]
So somehow, this started on November 15th and we only need to handle the errors correctly?

**Comment by mlschroe** [comment]
Should be fixed with that backend commit.
