### ISSUE TITLE
Broken navigation in 'home' view package lists

### ISSUE THREAD

**Issue by ajaissle** [openSUSE/open-build-service#629]
When in 'home' view and having more than 15 involved or owned packages, the navigation to the next page is not working. 'Involved Projects' is not affected.

Picture 1: 15 entries are displayed, but the number of entries displayed seems malformed ('Showing 1 to 015 of 38 entries') . We can not navigate through the list with the 'next' and 'previous' buttons.
![obs-home-1](https://f.cloud.github.com/assets/2892835/2524215/eef344b6-b4dd-11e3-9817-278be812f2a7.png)

Picture 2: We are changing the number of entries ('Show "10/25/50/100" entries'), the display works.
![obs-home-2](https://f.cloud.github.com/assets/2892835/2524216/f3435312-b4dd-11e3-9492-044f00885c41.png)

Picture 3: We can navigate to the next page(s) again, too.
![obs-home-3](https://f.cloud.github.com/assets/2892835/2524217/f6b43804-b4dd-11e3-9521-b4bb9b60609e.png)

**Comment by hennevogel** [comment]
See also #610

**Comment by bgeuken** [comment]
This doesn't happen anymore. Please reopen if you still see this issue somewhere.
