### ISSUE TITLE
Where does thin come from?

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#6310]
I see this when starting my docker:

`frontend_1  | 13:39:48 mailcatcher.1 | /usr/lib64/ruby/gems/2.5.0/gems/thin-1.5.1/lib/thin/server.rb:104: warning: constant ::Fixnum is deprecated`

I wonder where `thin` is coming from. :thinking: I don't see that it is being required in the Gemfile. Has someone any clue? :female_detective:

**Comment by hennevogel** [comment]
Like foreman tells you, from https://github.com/sj26/mailcatcher :-) We start it so you can see mails on :1080
