### ISSUE TITLE
[bootstrap] User request page

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#6464]
![selection_020](https://user-images.githubusercontent.com/3799140/49453578-b9b3b800-f7e3-11e8-9bf4-95440db79591.png)

No bugs but some small improvements:
* The number in the tab of open requests could be a label instead of parantheses
* I think default number of 25 requests per table might be too big as a table row has more space which required more spacing than before (see screenshot 25 fitted on one page).

Before

![selection_021](https://user-images.githubusercontent.com/3799140/49453680-e9fb5680-f7e3-11e8-83f8-3cbd3190a73e.png)

**Comment by bgeuken** [comment]
Nice idea:smiley:

**Comment by bgeuken** [comment]
I wrote a patch that would set the default on this page to 10, but now I have some doubts. Reducing this here will mostly affect power users and requires them to increase the requests shown per page whenever they access it. (Assuming they don't already do that by setting it from 25 to 50 or 100).

**Comment by bgeuken** [comment]
We could free some space by moving the refresh icon somewhere else.

**Comment by coolo** [comment]
I don't think 10 or 25 makes much of a difference. You normally don't work in this view, but get an overview here.
