### ISSUE TITLE
Bootstrap monitor is a downgrade from bento

### ISSUE THREAD

**Issue by hellcp** [openSUSE/open-build-service#6470]
# Issue Description
It certainly looks nicer but when it comes to functionality, there are some things that need improvements.
  * When clicking in unresolvable, the reason for why it is unresolvable is no longer stated (~~at least on mobile~~ confirmed everywhere)
  * With projects larger than 100 packages, there's no way to see all the packages listed at once anymore 
  * Table doesn't expand in y axis, so there are two scrollbars on mobile, which is awful to navigate
  * Reloading page erases filters, would be nice to see js reload button as a replacement for keeping filters and reloading results

Expected Result
============
Better monitoring experience for projects

**Comment by ChrisBr** [comment]
@hellcp thanks for your feedback although downgrade is a little hard ... :wink: 

 >When clicking in unresolvable, the reason for why it is unresolvable is no longer stated ( confirmed everywhere)

Works for me. Which browser do you use?

![selection_023](https://user-images.githubusercontent.com/3799140/49517415-71a49c00-f89c-11e8-9845-148af95f5a9e.png)

This works exactly as on the build result on package / project sidebar:
![selection_024](https://user-images.githubusercontent.com/3799140/49517472-8ed96a80-f89c-11e8-9f04-cd9b08d49eda.png)

> With projects larger than 100 packages, there's no way to see all the packages listed at once anymore

Honestly, I don't really think that this is an issue but I fixed it here: https://github.com/openSUSE/open-build-service/pull/6473

> Table doesn't expand in y axis, so there are two scrollbars on mobile, which is awful to navigate
 
I will look into it but probably not this sprint.

> Reloading page erases filters, would be nice to see js reload button as a replacement for keeping filters and reloading results

Feature request for the future ...

**Comment by ChrisBr** [comment]
Although scrolling with tooltip seems to be a problem

![monitor-scrolling](https://user-images.githubusercontent.com/3799140/49522375-d6192880-f8a7-11e8-8960-efa67ccfe156.gif)

**Comment by hellcp** [comment]
Firefox 62.0, that's weird, I don't get tooltips in monitor
![peek 2018-12-05 21-56](https://user-images.githubusercontent.com/30577011/49543582-eac1e480-f8d8-11e8-835f-03b9e78f7fac.gif)
![peek 2018-12-05 21-58](https://user-images.githubusercontent.com/30577011/49543584-eac1e480-f8d8-11e8-9f04-1381dfefd100.gif)
(I certainly have problem with unclicking them, but that's irrelevant)

**Comment by coolo** [comment]
I don't get the popups either in chromium - this is really a killer ;(

**Comment by coolo** [comment]
And it would be really good if the filters were preselected if you go to /monitor, because that's what they are by default: all enabled. Because I really need to see all !succeeded.

**Comment by adrianschroeter** [comment]
Also the active jobs are not anymore highlighted (was done via dark background), so it is quite hard to spot what is not finished (also because of the pagination)

**Comment by adrianschroeter** [comment]
There are more states then building, also scheduled, dispatching, finisghed, signing and blocked states. Looks quite chaotic atm to me and hard to distinguish.

There is also a speed issue btw, the page for openSUSE:Tools is loading in 40 seconds, while the osc command for the entire project returns in 1 sec.

**Comment by adrianschroeter** [comment]
Maybe short cut buttons for predefinied filters (Failing (for failed, broken, unresolvable) and Active for the active ones) might be a workaround.

**Comment by coolo** [comment]
> 
> There is also a speed issue btw, the page for openSUSE:Tools is loading in 40 seconds, while the osc command for the entire project returns in 1 sec.

I assume because all these links to live build logs are rendered in the view?

bento:
X-Opensuse-Runtimes: {"view":2877.2093819014513,"db":93.10403800000002,"backend":682.247355}

bootstrap:
X-Opensuse-Runtimes: {"view":43299.104148083614,"db":78.32499100000001,"backend":1536.217524}

**Comment by ChrisBr** [comment]
> I don't get the popups either in chromium - this is really a killer ;(

Hm, checked with

Chrome Version 62.0.3202.94 
Chromium Version 68.0.3440.84 / Version 70.0.3538.110
Firefox 60.0.1 / 63.0.3 

and works for me. I will approach you later on to check ...

**Comment by ChrisBr** [comment]
For now I will disable the client side search again:
https://github.com/openSUSE/open-build-service/pull/6543

**Comment by hennevogel** [comment]
everything is addressed right?

**Comment by coolo** [comment]
Well, no.  But I opened a new issue for the rest

**Comment by hennevogel** [comment]
awww, you're so sweet :cat2:

**Comment by coolo** [comment]
![so funny](https://ljdchost.com/ihvIdCV.gif)
