### ISSUE TITLE
[production][project#monitor] No route matches {:action=>"index", :controller=>"webui/repositories", :format=>"html"}, missing ...

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#6481]
project#monitor threw this 2 times
<pre>
No route matches {:action=&gt;&quot;index&quot;, :controller=&gt;&quot;webui/repositories&quot;, :format=&gt;&quot;html&quot;}, missing required keys: [:project]
</pre>
[https://build.opensuse.org/project/monitor?utf8=%E2%9C%93&amp;commit=Filter%3A&amp;succeeded=1&amp;failed=1&amp;unresolvable=1&amp;broken=1&amp;blocked=1&amp;dispatching=1&amp;scheduled=1&amp;building=1&amp;finished=1&amp;signing=1&amp;locked=1&amp;deleting=1&amp;pkgname=&amp;repo_Containers_Leap_15_0=1&amp;arch_i586=1&amp;arch_x86_64=1&amp;project=openSUSE%3Ainfrastructure&amp;defaults=0](https://build.opensuse.org/project/monitor?utf8=%E2%9C%93&amp;commit=Filter%3A&amp;succeeded=1&amp;failed=1&amp;unresolvable=1&amp;broken=1&amp;blocked=1&amp;dispatching=1&amp;scheduled=1&amp;building=1&amp;finished=1&amp;signing=1&amp;locked=1&amp;deleting=1&amp;pkgname=&amp;repo_Containers_Leap_15_0=1&amp;arch_i586=1&amp;arch_x86_64=1&amp;project=openSUSE%3Ainfrastructure&amp;defaults=0)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c0803c1eb1487000818450a)

**Comment by bgeuken** [comment]
This was fixed by #6491
