### ISSUE TITLE
New webui: Allow to copy unresolvable errors

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#6483]
**Is your feature request related to a problem? Please describe.**
I'm testing the new design since some weeks now and I'd really love, if you could make it like before (or maybe even better) that I'm able to copy 'unresolvable' errors into my clipboard. I run many times over the situation where I have to C&P errors or even want a full list of errors myself on my second screen, so that I can work through them, but this always requires the cursor to be on the build status element.

The solution with the message box before was good, but also had the disadvantage to be cut off when the errors get too long (which already happened quite a lot to me).

**Describe the solution you'd like**
Maybe when clicking the build status 'unresolvable', you'll get to the build log page and instead of seeing the log, you'll get the 'unresolvable' errors listed in the text field?

**Describe alternatives you've considered**
As said, I considered to suggest the old solution with the message box, but this won't work for longer error messages.

**Comment by bgeuken** [comment]
Since a [short time](https://github.com/openSUSE/open-build-service/pull/6217/commits/c7b12243547f882a316774eb065a8b71314d8801) it's possible to make the tooltip stick by clicking on the link. And then you can copy & paste the message.

I agree it's not the most intuitive / visible feature. Especially since it wasn't there at the beginning of our bootstrap theme. Please give it a try and let us know it solves your issue.

**Comment by mschnitzer** [comment]
OK, I was using an old version of OBS where it wasn't possible, but it seems to work like you've described on build.opensuse.org.

Anyways, it solves the issue, but still I'd suggest to have it at a different place as it gets really messy when the errors get too long.

**Comment by Ana06** [comment]
Is this fixed? should we close the issue?

**Comment by Ana06** [comment]
I guess no answer is also an answer :wink: @mschnitzer in case this wasn't fixed feel free to reopen it with more information
