### ISSUE TITLE
bootstrap: /project/monitor load time regression

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#6554]
To avoid #6470 getting too big, this is a fork: the performance of the project monitor is a massive regression compared to bento.

old webui loading https://build.opensuse.org/project/monitor/openSUSE:Tools is on my computer
22s with 4s server side rendering.

new webui loading https://build.opensuse.org/project/monitor/openSUSE:Tools is on my computer
54s with 37s server side rendering.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve Monitor Page Performance](https://trello.com/c/Pj3pWPd3/1625-improve-monitor-page-performance)
