### ISSUE TITLE
[bootstrap] Group member remove button shown if you don't have permissions

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/open-build-service#6564]
![selection_010](https://user-images.githubusercontent.com/3799140/49794723-8a97cc00-fd38-11e8-8dc5-caf703d9f7f4.png)

Although I'm not member of the Group. If I click I get an error message...

**Comment by bgeuken** [comment]
Duplicate of #6521 
I attached your screenshot to the other issue
