### ISSUE TITLE
monitor page looses the icons in front of repository name

### ISSUE THREAD

**Issue by darix** [openSUSE/open-build-service#6567]
Those icons e.g. tell me things like

- "repository not created yet"
- "publishing"
- "published"

All this is lost after the migration to bootstrap.

Before:
![example](https://user-images.githubusercontent.com/1102934/49800067-e2d5ca80-fd46-11e8-9f05-c6d3e141d2b4.png)

Now:
![now](https://user-images.githubusercontent.com/1102934/49800060-dea9ad00-fd46-11e8-9439-ff166dac82a4.png)

**Comment by ChrisBr** [comment]
Thanks, I will have a look into it!
