### ISSUE TITLE
[beta] Project link regression

### ISSUE THREAD

**Issue by ggardet** [openSUSE/open-build-service#6581]
In beta webui, Project link is a single link, whereas with old webui, multiple links are available to access parent projects.
E.g.: https://build.opensuse.org/project/monitor/openSUSE:Factory:ARM?arch_aarch64=1&building=1&defaults=0&repo_standard=1 had links to openSUSE, openSUSE;Factory and openSUSE:Factory:ARM.
Now, it is only openSUSE:Factory:ARM.

**Comment by dmarcoux** [comment]
Thank you again @ggardet for your feedback. We are already tracking this in #6532, so I will close this issue.
