### ISSUE TITLE
Ana is too polite to say, but the repositories flag code is horribly slow

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#6595]
I'm not Ana, but we're looking into it :)

**Comment by dmarcoux** [comment]
In Bootstrap, right? I guess, but just making sure.

**Comment by coolo** [comment]
Kind of - it's in ruby :)

**Comment by dmarcoux** [comment]
Duh, my bad. I meant it's for the Bootstrap UI that you are doing this? Because I guess it would involve too many changes for the old UI (instance variables and such...)

**Comment by coolo** [comment]
yeah, it's tricky - the old webui is horribly slow too, but changing all of the functions is a little over the top. So we're cloning the controller code.

**Comment by bgeuken** [comment]
No wonder given how we [juggle around](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/flag.rb#L77) with the flags:unamused:

**Comment by coolo** [comment]
master (openSUSE:Tools):
Completed 200 OK in 38121ms (Views: 23979.7ms | ActiveRecord: 4044.2ms | Backend: 0.0ms)

after a couple of minutes hacking:
Completed 200 OK in 9725ms (Views: 9045.9ms | ActiveRecord: 319.4ms | Backend: 0.0ms)

Saved 74.5% - and we're not yet done :bowtie:
