### ISSUE TITLE
[Bootstrap] Decrease in useability of the current Beta web UI

### ISSUE THREAD

**Issue by mcepl** [openSUSE/open-build-service#6597]
# Issue Description
I have switched to the BETA of OBS web interface and most things I don't care about, but I see clear and unequivocal worsening of the useability in replacing "tabs" in the top of each section on package pages and overview of requests pages.

In the previous version I could see immediately the state of my requests queues, now I have to use mouse to get the data.

In the previous version I could immediately go to all requests of each package, now I have to search for the tiny button in the corner of the page.

Expected Result
===============

Swift overview of the situation

Observed Result
===============

I have to search for tiny arrow with a mouse to get same information, and even to click on it.

How to Reproduce
===============

1. Go to https://build.opensuse.org/project/show/home:mcepl or https://build.opensuse.org/project/show/home:mcepl

2. See error

**Comment by coolo** [comment]
I'm afraid I don't know what you're talking about. Could you do perhaps attach screenshots of what you're looking at?

**Comment by mcepl** [comment]
![snimek z 2018-12-14 00-43-08](https://user-images.githubusercontent.com/198999/49974638-8fc46900-ff3a-11e8-9c6d-ed3684eaeae5.png)

Tell me without much playing with a mouse, how many rejected requests I have?

**Comment by coolo** [comment]
But this is not https://build.opensuse.org/project/show/home:mcepl, no?

**Comment by coolo** [comment]
I honestly have no idea what page that is. The title says 'tasks for mcepl', but 'tasks for coolo' looks like this (and makes it pretty obvious how many declined requests I have):

![screencapture-build-opensuse-org-user-tasks-2018-12-14-06_34_06](https://user-images.githubusercontent.com/1067203/49984936-615e8200-ff6a-11e8-9847-390e246f525b.png)

**Comment by mcepl** [comment]
> But this is not https://build.opensuse.org/project/show/home:mcepl, no?

It is https://build.opensuse.org/user/tasks

**Comment by dmarcoux** [comment]
Are you blocking Javascript? Do you have some errors in the Web Developer Tools on Firefox (especially in the console tab)?

I'm also on Firefox (63.0.3) and using Tumbleweed and I cannot reproduce the issue. I'm on the snapshot of `2018-12-03`

**Comment by mcepl** [comment]
![snimek z 2018-12-14 12-52-19](https://user-images.githubusercontent.com/198999/50002045-27f43980-ff9f-11e8-9aa4-73c328db3ccc.png)

I don't think there is anything significant there. Plenty of CSS warnings, but that's seems to be it.

**Comment by mcepl** [comment]
```
matej@milic: ~$ cat .mozilla/firefox/r7f7tog2.default/chrome/userContent.css 
@-moz-document domain(build.opensuse.org) {
html, body {
        background-color: #02d35f !important;
    }
}

@-moz-document domain(build.suse.de) {
html, body {
        background-color: yellow !important;
    }
}
matej@milic: ~$
```
Just a hack to distinguish quickly two OBS instances.

**Comment by mcepl** [comment]
Yup, me too. Thanks for resolving the mystery.
