### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by gitgitwhat** [openSUSE/open-build-service#6598]
# Issue Description
Hosting a private VM based OBS instance.  Provisioned with 8 cores, 32 GB RAM, 64 GB disk.  I'm trying to create binary only packages for all the major distros (Arch, CentOS, Debian, etc) so I interconnected with the openSUSE OBS instance then added repositories for the distros I want to target.  I then created a super simple .spec file just to test the build process and the workers kicked off.  Pretty soon they all start failing and any action I now try to perform throws either a 500 error or a "no space left on device" message. 

linux:~ # df
Filesystem     1K-blocks    Used      Available    Use%    Mounted on
devtmpfs        16454728       0        16454728   0%       /dev
tmpfs              16473152       0        16473152   0%       /dev/shm
tmpfs              16473152   17480    16455672   1%       /run
tmpfs              16473152       0        16473152   0%       /sys/fs/cgroup
/dev/sda1       2562068    2412212  0                100%   /
tmpfs              3294632         0        3294632     0%       /run/user/0

/proc/kcore is massive 

-r--------   1 root          root       140737477885952 Dec 12 13:39 kcore

What is going on?

Further Information
===============
* Exact server version:  obs-server.x86_64-2.9.5-Build1.2.install.iso

**Comment by coolo** [comment]
well, /proc/kcore is 128TB basically on all x86_64 machines - it's all virtual memory. But don't worry, it's only virtual :)

And /dev/sda1 is full - if my math doesn't fail me it's just 2GB?

**Comment by gitgitwhat** [comment]
Right.  Not sure why it only shows 2GB when it was setup to have 64GB in ESXi.  

Did I miss a step during installation?  Is there a way to extend the file system to use all the available space (if it can even see it)?

**Comment by gitgitwhat** [comment]
Well not sure why but it could see the full 64GB but wasn't letting me extend.  Seems like it is a VMware issue as Google has other reports of similar behavior.  Had to boot into gparted which successfully extended sda1.
