### ISSUE TITLE
Bento: package/show looks rather strange

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#6602]
I guess these confirmations shouldn't appear there?

![screencapture-build-opensuse-org-package-show-obs-server-unstable-obs-server-2018-12-13-10_02_26](https://user-images.githubusercontent.com/1067203/49927572-7d0c4e80-febe-11e8-8e42-d9f82114b893.png)

**Comment by ChrisBr** [comment]
Fixed https://github.com/openSUSE/open-build-service/pull/6604 & https://github.com/openSUSE/open-build-service/pull/6600
