### ISSUE TITLE
main page mixes 'home project' with 'user home' 

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#6605]
The icon 'Your Home' has the title 'Go to your home project', but it goes to /user/show/Admin

**Comment by dmarcoux** [comment]
To be consistent with the old UI, only the title needs to be updated.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback/Issues](https://trello.com/c/70G5o6TN/1636-address-feedback-issues)
