### ISSUE TITLE
[beta] webui problem in some statistics pages - No statistics exist for this build

### ISSUE THREAD

**Issue by ggardet** [openSUSE/open-build-service#6606]
For some (mutlibuild?) packages, the statistics page from beta webui returns:  ```No statistics exist for this build```
E.g.: https://build.opensuse.org/package/statistics/openSUSE:Factory:ARM:Live/JeOS:LXQT-efi.aarch64/images/aarch64

whereas old webui shows stats properly.

**Comment by coolo** [comment]
https://github.com/openSUSE/open-build-service/pull/5931 bound statistics to a package in the database - which makes it impossible to access stastics of multibuild flavors :(

**Comment by ggardet** [comment]
> #5931 bound statistics to a package in the database - which makes it impossible to access stastics of multibuild flavors :(

That's bad. Any enhancement possible? How was it handled previously?

**Comment by coolo** [comment]
the old webui parses the XML in the view.

**Comment by ggardet** [comment]
> #5931 bound statistics to a package in the database - which makes it impossible to access stastics of multibuild flavors :(

That's bad. Any enhancement possible? How was it handled previously?
