### ISSUE TITLE
wrong Flag validations break logic

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#6615]
We shouldn't allowed to have more than one Flag for the same repository, type (confusingly known as flag), architecture, project/package, independent from the status. We are even failing to catch the cases with the same status (which the validation is not allowing but it is only run on create). 

That is breaking the logic of the repositories page (remove flag doesn't expect another flag to exist), may be doing something different as what rendered (frontend takes the first but the backend may not) and it makes no sense to have more than one flag. :see_no_evil: 

There are many cases in our production instance were this happens (I would say that at least in some of them not intentionally), so this requires data migration.

**Comment by mmohring** [comment]
Hi, can you give some more background here ? The last time this issue came up I struggled with the fact what API, WebUI and Backend are doing with flags. I tried to make the API code do the same as the Backend is interpreting flags. And wrote the tests for this. So what is not working this time ?

**Comment by coolo** [comment]
https://build.opensuse.org/project/meta/home:interstar001:Icinga2

```
  <debuginfo>
    <disable arch="aarch64"/>
    <disable arch="ppc64le"/>
    <disable arch="ppc64le"/>
    <disable arch="s390x"/>
  </debuginfo>
```

**Comment by coolo** [comment]
`<build><disable/><enable/></build>` is also considered valid - which breaks the logic. And I believe it should be forbidden.

**Comment by coolo** [comment]
Or https://build.opensuse.org/package/meta/openSUSE:Maintenance:1678/kdelibs4.openSUSE_12.3_Update
```
 <build>
    <enable repository="openSUSE_12.3_Update_ports"/>
    <enable repository="openSUSE_12.3_Update_standard"/>
    <enable repository="openSUSE_12.3_Update_ports"/>
    <enable repository="openSUSE_12.3_Update_standard"/>
    <enable repository="openSUSE_12.3_Update_ports"/>
    <enable repository="openSUSE_12.3_Update_standard"/>
    <enable repository="openSUSE_12.3_Update_ports"/>
    <enable repository="openSUSE_12.3_Update_standard"/>
    <enable repository="openSUSE_12.3_Update_ports"/>
    <enable repository="openSUSE_12.3_Update_standard"/>
    <enable repository="openSUSE_12.3_Update_ports"/>
    <enable repository="openSUSE_12.3_Update_standard"/>
    <enable repository="openSUSE_12.3_Update_ports"/>
    <enable repository="openSUSE_12.3_Update_standard"/>
    <enable repository="openSUSE_12.3_Update_ports"/>
    <enable repository="openSUSE_12.3_Update_standard"/>
    <enable repository="openSUSE_12.3_Update_ports"/>
    <enable repository="openSUSE_12.3_Update_standard"/>
    <enable repository="openSUSE_12.3_Update_ports"/>
    <enable repository="openSUSE_12.3_Update_standard"/>
  </build>
