### ISSUE TITLE
[production][] Invalid path parameters: Invalid encoding for parameter: devel:languages:php:php53++[+���������+]

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#6618]
threw this 3 times
<pre>
Invalid path parameters: Invalid encoding for parameter: devel:languages:php:php53++[+���������+]
</pre>
[https://build.opensuse.org/project/show/devel:languages:php:php53++[+%C0%EA%F2%E8%E2%E0%F6%E8%FF+]](https://build.opensuse.org/project/show/devel:languages:php:php53++[+%C0%EA%F2%E8%E2%E0%F6%E8%FF+])"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c084f9b886b8a00160855df)

**Comment by Ana06** [comment]
It looks like the parameter is invalid. I think this should fail.
