### ISSUE TITLE
[beta] links in linked projects point to package in parent project

### ISSUE THREAD

**Issue by ggardet** [openSUSE/open-build-service#6621]
In beta webui, if you go to https://build.opensuse.org/project/show/openSUSE:Leap:15.1:ARM and click any package inherited from parent project, you will end up in package from ```openSUSE:Leap:15.1```, not ```openSUSE:Leap:15.1:ARM```. 
Which is wrong, as we should display this package in context of current project.

**Comment by ggardet** [comment]
The same applies when I click on 'Branch package' link. It branches parent package instead of current package, so repos config in branched project is not right.

**Comment by Ana06** [comment]
This seems to be fixed. I'll close the issue. Please reopen it if the issue is still there @ggardet :wink:

**Comment by coolo** [comment]
@Ana06 go to https://build.opensuse.org/project/show/openSUSE:Leap:15.1:ARM -> 'Inherited Packages' -> 0ad and you end up in https://build.opensuse.org/package/show/openSUSE:Leap:15.1/0ad while the user expects to stay in :ARM
