### ISSUE TITLE
Comments don't like thing like tags:

### ISSUE THREAD

**Issue by jobermayr** [openSUSE/open-build-service#663]
Try to add a comment like this:

```
<constraints>
  <hardware>
    <disk>
      <size unit="G">8</size>
    </disk>
    <memory>
      <size unit="G">3</size>
    </memory>
  </hardware>
</constraints>
```

**Comment by hellcp** [comment]
As opposed to github issues, obs comments with xml inside become empty (with just a style class inside for syntax highlighting). This is plain wrong.
Try inserting
```xml
<constraints>
  <hardware>
    <disk>
      <size unit="G">8</size>
    </disk>
    <memory>
      <size unit="G">3</size>
    </memory>
  </hardware>
</constraints>
```
inside the obs comment, it becomes:
![Screenshot from 2019-08-21 10-02-26](https://user-images.githubusercontent.com/30577011/63413824-d25c1080-c3fa-11e9-8bd8-2273090680e5.png)
in html:
```
<pre><code class="xml">
</code></pre>
```
Before syntax highlighting, we need to be able to even post any xml code inside the comments ;)

**Comment by hennevogel** [comment]
They are in the database, just not rendered because it would mean to define which tags to allow...

**Comment by hellcp** [comment]
Looking into the code, I don't see why not, instead of rendering:

```ruby
def preprocess(fulldoc)
  ...
  # sanitize the HTML we get
  Sanitize.fragment(fulldoc, Sanitize::Config.merge(Sanitize::Config::RESTRICTED,
                                                    elements: Sanitize::Config::RESTRICTED[:elements] + ['pre'],
                                                    remove_contents: true))
end
```
do:

```ruby
def block_html(raw_html)
  # sanitize the HTML we get
  Sanitize.fragment(raw_html, Sanitize::Config.merge(Sanitize::Config::RESTRICTED,
                                                    elements: Sanitize::Config::RESTRICTED[:elements] + ['pre'],
                                                    remove_contents: true))
end
```
Which removes all of the not allowed html elements from the part of the comment which would get interpreted literally, while keeping stuff inside markdown, which is escaped by the redcarpet.

**Comment by hennevogel** [comment]
Go for it :)
