### ISSUE TITLE
[beta] Sort in 'Changed' column is broken

### ISSUE THREAD

**Issue by ggardet** [openSUSE/open-build-service#6640]
In new webui, sort in 'Changed' column is broken as it sort in alphabetical order. It should be more clever as old webui.

**Comment by dmarcoux** [comment]
Which page are you referring to exactly&

**Comment by ggardet** [comment]
@dmarcoux all project pages! ;)
You can see it easily here: https://build.opensuse.org/project/show/openSUSE:Factory:ARM

**Comment by dmarcoux** [comment]
Understood :slightly_smiling_face:, this might also be a problem in the package pages. Thank you for the feedback!

**Comment by ggardet** [comment]
> Understood slightly_smiling_face, this might also be a problem in the package pages. Thank you for the feedback!

Yes, it is also a problem on package page, but I guess the code is shared?

**Comment by dmarcoux** [comment]
Yes, the tables share code.
