### ISSUE TITLE
remote project link events do not work when local links exists

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#666]
In a setup rebuilding an entire project from remote, where the remote project has a local package link the notification of the linking package is not emitted.

This is at least true for source services, we can see that behaviour with OBS:Server:Unstable project. When obs-server gets updated, the linking package obs-api-deps stays in blocked (waiting for source service) forever, while obs-server gets it's status updated.

**Comment by mlschroe** [comment]
IMHo fixed. Reopen if not.
