### ISSUE TITLE
singing failure should become build failure

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#667]
We never make signing failures fatal atm, they always get retried. But we have some errors which are fatal and can not recover with retries. These are for example old signing keys which are not suitable for SSL signing.

Therefore we always collect permanent hanging jobs in signing which blocks the publish of the entire project.

IMHO we should just add some lines to the build log in that situation and turn the build state into failed.

**Comment by mlschroe** [comment]
Not suitable SSL keys are now build failures.

**Comment by KostyaSha** [comment]
@mlschroe had no time to look, but usually it better support strategy pattern and allow choosing options.
