### ISSUE TITLE
Allow editing comments

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#6674]
I would like to be allowed to correct my mistakes in comments in OBS. At the moment I need to delete the comment and write a new one, losing markdown. :angry: An edit option would be wonderful :cupid:

**Comment by coolo** [comment]
It would be good to have this - and also to offer updating the comments by the API (and don't include email notifications, as workaround for #4484)

**Comment by Ana06** [comment]
great job @pk12! :tada: although https://github.com/openSUSE/open-build-service/pull/10148 only enable this for the webui and not for the API as @coolo suggested. I think we should reopen this issue.

**Comment by pk12** [comment]
Thank you @Ana06! I think it makes sense too.
