### ISSUE TITLE
Form data that depend on autocomplete results are not properly updated

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#6677]
Expected Result
============
OBS dialogs that use more advanced autocompletion features, like having input fields that depend on the autocomplete results, are not working properly.

How to Reproduce
===============
1. Go to repository page of a project
2. Click on 'Add from a Project'
3. Enter a project (e.g. home:foo:bar) and select it from the dropdown
4. Update the project name to another valid project (e.g. home:foo)
5. Hit enter (the focus should still be on the input field)

=> The created repositories name refers to home:foo:bar instead of home:foo. Also the created path element might be wrong.

Further Information
===============
* This happens because we don't handle the 'autocompletechange' events correctly

**Comment by Ana06** [comment]
This is a corner case, it is not even easy to reproduce. While it would be nice to fix this, it is IMO not a priority.

**Comment by hennevogel** [comment]
Let's not do it then...
