### ISSUE TITLE
Arch build workers down?

### ISSUE THREAD

**Issue by pbek** [openSUSE/open-build-service#6692]
Thank you for the marvelous openSUSE Build Service! It is tremendously useful! I use and love it for building QOwnNotes!

# Issue Description

Since a month or so I only get the error message `have choice for iptables needed by systemd: iptables iptables-nft` when I try to build for Arch Linux.
Arch users of QOwnNotes are sad because they have to start compile the application themselves.

Expected Result
============
Builds happily happening again. :)

How to Reproduce
===============
1. Go to <https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop>
2. Click on `Arch` or `Arch_Extra`
3. See error message `have choice for iptables needed by systemd: iptables iptables-nft`

Further Information
===============
* I haven't found any useful information on `have choice for iptables needed by systemd: iptables iptables-nft` in search engines...

**Comment by hawkeye116477** [comment]
Just click `advanced`, then `project config` and write `Prefer: iptables` and I hope that should be good now :smile:.

**Comment by pbek** [comment]
@hawkeye116477, thank you very much! It worked after I added it to <https://build.opensuse.org/project/prjconf/home:pbek:QOwnNotes>! Makes me happy!

I don't know if this is the right place to ask, but do you know what the difference between `Arch` and `Arch_Extra` is? Back then `Arch` didn't build QOwnNotes (just `Arch_Extra` did), now it seems fine too.

**Comment by hawkeye116477** [comment]
@pbek `https://wiki.archlinux.org/index.php/official_repositories#Stable_repositories`
