### ISSUE TITLE
[production][repositories#index] No route matches {:action=>"release_repository_dialog", :controller=>"webui/project", :format=>"h...

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#6712]
repositories#index threw this 0 times
<pre>
No route matches {:action=&gt;&quot;release_repository_dialog&quot;, :controller=&gt;&quot;webui/project&quot;, :format=&gt;&quot;html&quot;, :project=&gt;#&lt;Project id: 110, name: &quot;openSUSE:Factory&quot;, title: &quot;The next openSUSE distribution&quot;, description: &quot;Any user who wishes to have the newest packages th...&quot;, created_at: &quot;2005-01-01 00:00:01&quot;, updated_at: &quot;2017-11-30 07:44:15&quot;, remoteurl: nil, remoteproject: nil, develproject_id: nil, delta: false, kind: &quot;standard&quot;, url: nil, required_checks: [], staging_workflow_id: nil&gt;, :repository=&gt;&quot;images&quot;}
</pre>
[https://build.opensuse.org/repositories/openSUSE:Factory](https://build.opensuse.org/repositories/openSUSE:Factory)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c3331343c2e470008f7f040)

**Comment by coolo** [comment]
Looks related to #6708 :(

**Comment by ankitkataria** [comment]
Since I made the previous PR, could I look into this?

**Comment by coolo** [comment]
I created a reverting PR - as the issue you fixed is plainly invalid :(

But you can look into creating a test case to cover the view breaking - if you want to.

**Comment by ankitkataria** [comment]
I thought the route wasn't required. :disappointed: . I took the issue by word and didn't check if it was actually valid. I'll take care of this from my next contributions.

**Comment by coolo** [comment]
No worries - this was basically a trap :(

**Comment by Ana06** [comment]
@coolo as your revert PR is merged, this can be closed, right?
