### ISSUE TITLE
[beta] New frontend disappearing comments

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/open-build-service#6723]
# Issue Description
Having more than 3 levels of comments causes the comments not to be shown.

Expected Result
============
I can see all the comments and replies.

How to Reproduce
===============
1. reply to 3rd level comment
2. see no reply - *poof*

Further Information
===============
* https://build.opensuse.org/package/show/devel:languages:nodejs:staging/nodejs11

**Comment by coolo** [comment]
Spot the missing level == 3 :)

```
    - if level < 3
      - comment.children.each do |children|
        = render partial: 'webui2/webui/comment/content', locals: { comment: children, commentable: commentable, level: level + 1 }

- if level > 3
  - comment.children.each do |children|
    = render partial: 'webui2/webui/comment/content', locals: { comment: children, commentable: commentable, level: level + 1 }
```
