### ISSUE TITLE
webui does not display link to "show unmerged sources" if package is linked

### ISSUE THREAD

**Issue by jsjhb** [openSUSE/open-build-service#673]
at least with 2.5.1 if a package is linked from somewhere, there is no link displayed in the webui: source file section of package overview.

**Comment by hennevogel** [comment]
This isn't a problem in the webui. Package.backend_package has no links_to_id set in this case.

**Comment by vpereira** [comment]
I still see it in master. How to reproduce it:

Have your server linked to openSUSE.org 

```<remoteurl>https://api.opensuse.org/public</remoteurl>```

create a package in your home, with a link, i.e: 

```<link project='openSUSE.org:openSUSE:Factory' package='gcc'/>```

results: 
no information about link, no "merge/unmerged source view" 

![screenshot from 2018-06-28 09-32-07](https://user-images.githubusercontent.com/37418/42019750-3c61fde4-7ab6-11e8-81f2-544bca5b7881.png)

**Comment by DimStar77** [comment]
This is still happending - e.g. 
https://build.opensuse.org/package/show/filesystems:ceph/ceph-iscsi
was just recently converted to be a linked package - but there is no indication thereof on the webui (confused the maintainer)

**Comment by hennevogel** [comment]
does not happen anymore
