### ISSUE TITLE
New tracker request: jira.suse.de

### ISSUE THREAD

**Issue by rsalevsky** [openSUSE/open-build-service#6734]
**Is your feature request related to a problem? Please describe.**
Similar to #6718 I would like to request to add support for jira.suse.de ass a issue tracker. For example issue SCRD-5753 should be automatically recognized as a issue and mapped to https://jira.suse.de/browse/SCRD-5753.

**Describe the solution you'd like**
All projects in jira.suse.de should be automatically added as issue tracker in OBS. The API for getting all projects in Jira is https://jira.suse.de/rest/api/2/project as logged in user (only the key is of interested). If possible the summary of an issue can be fetched via https://jira.suse.de/rest/api/2/issue/SCRD-5753?fields=summary.

**Describe alternatives you've considered**
Alternatively if we can't fetch a list of project automatically we could maintain a list of project manually and update them regularly. Right now the list is CA, CAPNA, CTNRFEAT, JIRA, KUBECORE, KUBEHA, KUBESVCS, PR, PM, RMCT, SLE, SCPL, SCPM, SCRD.

**Comment by coolo** [comment]
this does not map to what issue trickers are. you would need to write jsd#SCRD-5753 in your changes

**Comment by adrianschroeter** [comment]
jira.suse.de is also a private instance, so we shouldn't add that into common code base.

But what we want to have is support for reading jira tickets, so it can be configured by the OBS admins.

**Comment by coolo** [comment]
it would be really great if the concept of the issue trackers was extended to cover this (through an API used on our own instance), so we could detect PM-27272 automatically as jira link.

**Comment by adrianschroeter** [comment]
You can already right now define a regexp catching PM-27272 which redirects to http://coolo.de/blahfasel/27272 for example. But monitoring the state of the ticket is a different thing.

Or did I misunderstand your point?

**Comment by coolo** [comment]
well, possibly not. We'd have to see if we can automatically construct a regexp matching all our jira projects and set it automatically.

**Comment by bmwiedemann** [comment]
Just found that "SLE-15" is now a valid jira-ID, too - and it gets mentioned a lot in changes entries. Means more complexity.

**Comment by coolo** [comment]
hence we'll not do that, but rely on jsd# - at least that's the current state of discussion

**Comment by adrianschroeter** [comment]
On Dienstag, 29. Januar 2019, 12:58:54 CET Stephan Kulow wrote:
> https://github.com/openSUSE/open-build-service/issues/6734#issuecomment-4585
> 14338

we rely on jsc# (not jsd#) meanwhile

-- 

Adrian Schroeter
SUSE Linux Products GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
email: adrian@suse.de

**Comment by adrianschroeter** [comment]
closing this here since it speaking about internal stuff. feel free to contact me for internal setup and topics.
