### ISSUE TITLE
[production][search#bs_request] wrong number of arguments (given 7, expected 3)

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#6736]
search#bs_request threw this 0 times
<pre>
wrong number of arguments (given 7, expected 3)
</pre>
[https://api.opensuse.org/search/request?match=%28%28review%5B%40by_group%3D%27opensuse-review-team%27+and+%28%40state%3D%27new%27%29%5D%29+and+action%2F%40type%3D%27submit%27%29+and+%28action%2Ftarget%2F%40project%3D%27openSUSE%3AFactory%27+or+action%2Fsource%2F%40project%3D%27openSUSE%3AFactory%27%29and+state%2F%40name%3D%27review%27](https://api.opensuse.org/search/request?match=%28%28review%5B%40by_group%3D%27opensuse-review-team%27+and+%28%40state%3D%27new%27%29%5D%29+and+action%2F%40type%3D%27submit%27%29+and+%28action%2Ftarget%2F%40project%3D%27openSUSE%3AFactory%27+or+action%2Fsource%2F%40project%3D%27openSUSE%3AFactory%27%29and+state%2F%40name%3D%27review%27)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c34b827a2784200157316ff)

**Comment by Ana06** [comment]
there are several errors related to `search#bs_request `

**Comment by coolo** [comment]
yeah, the osc maintainer was experimenting with invalid xpaths. Unless there are security concerns (that I can't see), this is really low prio to fix.
