### ISSUE TITLE
Building for Arch i586 causes unresolvable error "nothing provides..."

### ISSUE THREAD

**Issue by gitgitwhat** [openSUSE/open-build-service#6739]
# Issue Description
I'm building a binary-only package for various distros but am having trouble with Arch.  Arch x86_64 builds without issue.  Trying to target anything other than x86_64 produces an unresolvable error and it says that "nothing provides ..." for the dependencies.  I have two different projects to keep the builds separate.  The proper repositories are set for each project.  The only difference between the x86_64 PKGBUILD and the one for i586 is the 'arch=' line.  I've tried arch=('i586'), arch=('i686') and arch=('any') but without success.

The two dependencies are sqlite3 and curl.
depends=('sqlite3' 'curl')

Is there a different way to reference dependencies for 32-bit builds when building in a 64-bit environment?

I'm able to build i586 packages for Debian, Ubuntu, RHEL 6, CentOS 6 and Tumbleweed without issues.

Expected Result
============
A package that targets 32-bit Arch.

Further Information
===============
Private instance installed with obs-server.x86_64-2.9.5-Build1.2.install.iso

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
