### ISSUE TITLE
Creating a delete request says 'Accept'

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#6765]
I find this 'Accept' quite confusing, as I'm not accepting a request but creating one.

![screencapture-build-opensuse-org-package-show-opensuse-factory-rubygem-archive-tar-minitar-2019-01-15-07_52_11](https://user-images.githubusercontent.com/1067203/51163603-95df9980-189a-11e9-900e-eed6e02ab676.png)

**Comment by dmarcoux** [comment]
I agree. This is shared among multiple modals: https://github.com/openSUSE/open-build-service/blob/0b8ac511398d27c5d0c74319cb40a9b1a9925d8d/src/api/app/views/webui2/shared/_dialog_action_buttons.html.haml#L3

We could keep `Accept` as the default String for the button and another String can be provided (when calling the partial) to override the default one. What do you think?

**Comment by CoderJolly** [comment]
Is this issue assigned or free ? If not, i would like to work upon it

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback/Issues](https://trello.com/c/70G5o6TN/1636-address-feedback-issues)
