### ISSUE TITLE
Flag refactoring broke maintenance_incident accept

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#6766]
At least some maintenance requests can not be accepted anymore saying just 

400
invalid_record
Flags is invalid

Example request in build.o.o is 666064

Maintenance is blocked because of this.

**Comment by coolo** [comment]
No, you're wrong. Fixing the flag validation uncovered very old bugs.

**Comment by adrianschroeter** [comment]
nevertheless these bugs must be fixed since this is blocking our workflow atm.

**Comment by coolo** [comment]
we obviously have no test case for this workflow - good opportunity to fix that in rspec :)
