### ISSUE TITLE
Ruby code is not interpreted correctly

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#6807]
# Issue Description
Your ruby code is not parsed correctly.

Expected Result
============
I don't see it anymore.

How to Reproduce
===============
1. Go to a maintenance incident on the internal build service
2. scroll down

Further Information
===============
See screenshot.
![ruby_code](https://user-images.githubusercontent.com/8287131/51483148-aa3efd00-1d98-11e9-8b4c-686dff357aa5.png)

**Comment by bgeuken** [comment]
> 1. Go to a maintenance incident on the internal build service

Internal build service you say... @coolo is it you again? :clown_face:
