### ISSUE TITLE
Save max shown packages per project and max shown files per package

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#6811]
**Is your feature request related to a problem? Please describe.**

For maintenance it is important to see more than 10 files per package and more than 10 packages per project, as we usually have many packages in one incident (like channel files) and often packages with more than 10 files.

I always have to change the maximum shown packages for every incident. As this is annoying, as I have to do this almost every time, it would be really great, when my configuration could just be saved for me in the background via Ajax.

**Describe the solution you'd like**

Save the amount of shown packages and projects in the background for a user when they change it.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by srinidhibs** [comment]
I was trying to figure out the best way to store user preferences and now I see that #7427 by @bgeuken has been merged. Does that mean, this issue can be closed?

**Comment by mschnitzer** [comment]
I personally would have said the pagination count should be stored permanently.

**Comment by bgeuken** [comment]
There isn't a "permanent" option. We could add a very high number instead. But let's try it out with 2 days for now.
