### ISSUE TITLE
Failed to open TCP connection to backend:5352 

### ISSUE THREAD

**Issue by AnkushMalik** [openSUSE/open-build-service#6814]
Hi everyone,

I want to contribute to OBS but I am having some trouble with starting development environment.
I followed all the steps mentioned in [CONTRIBUTING.md](https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md), and built dev environment without any issue.

But on starting env, I got the following response error:
![image](https://user-images.githubusercontent.com/13421233/51532149-66fe9000-1e65-11e9-8084-269f2e1d2a5c.png)

- log:

![image](https://user-images.githubusercontent.com/13421233/51532229-9f05d300-1e65-11e9-92c1-f5f51fa7a4ff.png)

![image](https://user-images.githubusercontent.com/13421233/51532192-87c6e580-1e65-11e9-9e14-dc610bfa589c.png)

Please guide me Accordingly 🙂.

**Comment by dmarcoux** [comment]
How did you launch your development environment? With `docker-compose up`?

For example, when I run `docker-compose up`, I have the following Docker containers running:

```bash
$ docker ps

CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                            NAMES
34a2959eaa18        openbuildservice/frontend    "foreman start -p 30…"   23 hours ago        Up 4 seconds        0.0.0.0:1080->1080/tcp, 0.0.0.0:3000->3000/tcp   open-build-service_frontend_1
eeb003484912        openbuildservice/backend     "/obs/contrib/start_…"   3 months ago        Up 9 seconds                                                         open-build-service_worker_1
3860466ca170        openbuildservice/memcached   "/usr/sbin/memcached…"   5 months ago        Up 14 seconds       0.0.0.0:11211->11211/tcp                         open-build-service_cache_1
5749960bfd88        openbuildservice/backend     "/obs/contrib/start_…"   5 months ago        Up 17 seconds                                                        open-build-service_backend_1
ca36674360a4        openbuildservice/mariadb     "/usr/lib/mysql/mysq…"   5 months ago        Up 19 seconds       0.0.0.0:3306->3306/tcp                           open-build-service_db_1
```

Do you have the same containers running? It seems like your backend container is not running.

**Comment by hennevogel** [comment]
Hey @AnkushMalik, welcome. Quick question, are you mac os? :smile:

**Comment by coolo** [comment]
@dmarcoux he linked the failure of the backend_1 container as well - that seems to be the root cause

**Comment by AnkushMalik** [comment]
@dmarcoux  already checked that, all containers are running.

@hennevogel Yes

**Comment by AnkushMalik** [comment]
Ok 👍. 
I believe this should be mentioned in the contributing.md 🙂.

**Comment by bgeuken** [comment]
@mlschroe I know you already said it's not easy to change, but I think this issue proves once more that it would be worth it:smiley:

**Comment by adrianschroeter** [comment]
the change is easy, it will just break a lot of otehr stuff.

**Comment by adrianschroeter** [comment]
btw, IIRC there is also a case sensitive filesystem on MacOS, just the default one is not.

**Comment by bgeuken** [comment]
> AnkushMalik commented 10 hours ago
> Ok . I believe this should be mentioned in the contributing.md .

It's actually [mentioned](https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md#how-to-setup-an-obs-development-environment) there, but easy to overlook given the amount of text we have in this guide.
I've opened a [PR](#6830) that highlights that this note is for MacOS and Windows users.

**Comment by bgeuken** [comment]
> adrianschroeter commented 18 seconds ago
> the change is easy, it will just break a lot of otehr stuff.

In other words it's hard to change :wink:

**Comment by hennevogel** [comment]
@AnkushMalik did you get anywhere or did this stop you from contributing? :fearful:

**Comment by AnkushMalik** [comment]
Nope, just installed opensuse in my old pc :smile:

**Comment by DavidKang** [comment]
@AnkushMalik, good to know!

**Comment by hennevogel** [comment]
I've opened [openSUSE/obs-build#492])(https://github.com/openSUSE/obs-build/pull/492) for discussion about this now...
