### ISSUE TITLE
New Flag validation is harmful

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#6823]
The new Flag uniqness validation leads to broken operations (eg. project copy) when the source had duplicates. Leaving inconstent data and blocked workflows.

Keep also in mind that we have plenty of frozen projects which must not get touched (neither in db nor in source), so a migration is no solution and leads to more inconsistent data.

Working with these project must be still possible.

I have disabled the check on production for now to unblock teams, so just P2 for now.

**Comment by adrianschroeter** [comment]
On Mittwoch, 23. Januar 2019, 13:47:56 CET Stephan Kulow wrote:
> The migrations is done and the migration was done in a way that doesn't
> matter to the backend. So please specify the exact nature of the problem,
> the flag validation will have to stay.

the changes are not written to the backend and it can't. when ever
the api reads/recreates meta from back it fails now and leaves inconsistent 
projects. Can happen at least for copy, undelete and read from remote, but not
sure that it is limited to that.

-- 

Adrian Schroeter
SUSE Linux Products GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
email: adrian@suse.de

**Comment by coolo** [comment]
Why would we want to save it to the backend if the information is the same? 

But on copy and undelete we have to filter duplicates - for read it doesn't matter as the validation only happens when creating the objects.

**Comment by adrianschroeter** [comment]
On Mittwoch, 23. Januar 2019, 14:40:36 CET Stephan Kulow wrote:
> Why would we want to save it to the backend if the information is the same?

It will be reported as different on consistency checks.

But as I said before, you must not store it to the backend, since the projects
can also be frozen.

> But on copy and undelete we have to filter duplicates - for read it doesn't
> matter as the validation only happens when creating the objects.

please note that these are only examples, no guarantee for completness.

-- 

Adrian Schroeter
SUSE Linux Products GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
email: adrian@suse.de
