### ISSUE TITLE
[production][source_attribute#show] private method `render_main_attributes' called for #<Project:0x00007f498be01f38>
Did you mean?  r...

### ISSUE THREAD

**Issue by saraycp** [openSUSE/open-build-service#6824]
source_attribute#show threw this 4 times
<pre>
private method `render_main_attributes&#39; called for #&lt;Project:0x00007f2f019abd20&gt;
Did you mean?  render_attribute_axml
</pre>
[https://api.opensuse.org/source/openSUSE:Factory:RISCV/java-12-openjdk/_attribute?with_project=1](https://api.opensuse.org/source/openSUSE:Factory:RISCV/java-12-openjdk/_attribute?with_project=1)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c471a7130a5c1000d3089b5)

**Comment by coolo** [comment]
Same as https://github.com/openSUSE/open-build-service/issues/6819

**Comment by DavidKang** [comment]
It's duplicated #6819
