### ISSUE TITLE
Download link broken/unaivailable for _multibuild

### ISSUE THREAD

**Issue by ggardet** [openSUSE/open-build-service#6847]
In openSUSE:Factory:ARM:Live I am not able to download mutlibuild images.
It is the same as old closed issue https://github.com/openSUSE/open-build-service/issues/4985 apparently.

Expected Result
============
Download link should just work.

How to Reproduce
===============
Go to https://build.opensuse.org/package/binaries/openSUSE:Factory:ARM:Live/JeOS:JeOS-beagle/images and try to download the *.raw.xz file.
You get a 404 error.

Further Information
===============
* A link to an OBS instance showing the issue: https://build.opensuse.org/package/binaries/openSUSE:Factory:ARM:Live/JeOS:JeOS-beagle

**Comment by adrianschroeter** [comment]
please verify if 2.9 is affected as well, we will need a fix there as well then
