### ISSUE TITLE
Combined Repository i586+x86_64 and ppc/arm does not work for Factory

### ISSUE THREAD

**Issue by stoecker** [openSUSE/open-build-service#686]
I'm not sure if this is an issue in OBS itself or in the OBS installation build.opensuse.org or an configuration issue, so I report it here.

Creating joined repositories worked like a charm until recently:
<pre>
  &lt;repository name="openSUSE_Factory"&gt;
     &lt;path project="openSUSE:Factory:NonFree" repository="standard"/&gt;
     &lt;path project="openSUSE:Factory" repository="ports"/&gt;
     &lt;arch&gt;i586&lt;/arch&gt;
     &lt;arch&gt;x86_64&lt;/arch&gt;
     &lt;arch&gt;ppc64&lt;/arch&gt;
   &lt;/repository&gt;
</pre>

It still works fine for 13.1, but not anymore for Factory. The repos are unable to resolve any packages for building.

See e.g. here https://build.opensuse.org/project/show/Application:Geo

Please fix that, so it's possible to have a unique name for the outside downloads again instead of these crude workarounds to have them separated with "_ARM" or "_Ports".

**Comment by mlschroe** [comment]
That's because the ports repo is a base repo (it does not have a 'path' set), and only contains ppc/arm/arch. Not a bug.
