### ISSUE TITLE
Keep the popup open in project/monitor page 

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#6868]
If selecting from the Status filter popup it closes after every click, but I usually want to select multiple values, which is very annoying

**Comment by bgeuken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve monitor page filtering](https://trello.com/c/K4bWxRiS/1035-improve-monitor-page-filtering)

**Comment by bgeuken** [comment]
This was fixed with #6878
