### ISSUE TITLE
Invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#6872]
threw this 11 times
<pre>
invalid byte sequence in UTF-8
</pre>

~[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d3ef14282c14400087c7214)~

[See this exception on Errbit](https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/5d3ef14282c14400087c7214)

**Comment by eduardoj** [comment]
Related to #5236. This happens when sending emails. From the Errbit backtrace:

```
[...]
/PROJECT_ROOT/app/jobs/send_event_emails_job.rb:19→ send_email
/PROJECT_ROOT/app/jobs/send_event_emails_job.rb:10→ block in perform
/GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/relation/delegation.rb:85→ each
/GEM_ROOT/gems/activerecord-6.0.2.2/lib/active_record/relation/delegation.rb:85→ each
/PROJECT_ROOT/app/jobs/send_event_emails_job.rb:5→ perform
[...]
```

**Comment by eduardoj** [comment]
This exception still happens in Errbit. Reopening.

**Comment by eduardoj** [comment]
"Invalid byte sequence in UTF-8" happened sending emails and rendering rpmlint log files. Both errors were merged in Errbit. The issue in rpmlint log files was fixed.

I opened this issue for tracking the error sending emails: #15877.
