### ISSUE TITLE
GET /source/<project>/<package>/_history provide option to include verifymd5

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/open-build-service#6881]
The basis of the leaper bot (and upcoming origin manager openSUSE/openSUSE-release-tools#1643) is to compare sources against projects where the packages may originate to help manage the process. Long-story short due to the way `srcmd5` behaves with `_link` vs `verifymd5` (excludes `_link` from md5) and the project structure of `SUSE:SLE-...` the `verifymd5` must be used to get an accurate comparison. The problem is that when looking through potential origins to determine the source the revision history must be consulted. Unfortunately the history only includes `srcmd5` and thus requires a follow-up query for each revision to obtain the `verifymd5`. This is rather slow and suboptimal.

What would be much more desirable would be an option to include `verifymd5` or always include it.

The current code can be seen in [`manager_42.py`](https://github.com/openSUSE/openSUSE-release-tools/blob/7d1fa2f262f86817ad9d0863c82f614a41c9b69f/manager_42.py#L250-L275).

In the meantime the new code will have to carry on this additional query.

**Comment by coolo** [comment]
As the verifymd5 is not stored atm (and migrating all existing revisions in all projects would be a long journey), having a route that returns the required infos and implements proper caching in the backend is the easier route.

So if I get the python code right, you want to know if a package existed with a specific verifymd5. How about:

`/source/$PRJ/$PKG/_history?view=filtered&verifymd5=$THEONE&limit=5&deleted=1` ?

**Comment by jberry-suse** [comment]
Either should work for our use-case.

**Comment by jberry-suse** [comment]
For future use in potential web interface it might be useful to know the location of the commit relative to others. Something like 4 commits behind from SLE..., etc.

**Comment by coolo** [comment]
@adrianschroeter read! "... is to compare sources against projects where the packages may originate ..."

**Comment by adrianschroeter** [comment]
well, but there is no single origin, it may be the combination of many packages when you use the verifymd5.

**Comment by jberry-suse** [comment]
All the relevant bits are shown in the linked to code which retrieves the singular `verifymd5` for each revision of a package. The use-case for the information is a separate topic, but needless to say it is necessary.

An example of what the code would do:

```
osc api /source/openSUSE:Factory/libgarcon/_history
```

```xml
<revisionlist>
....
  <revision rev="27" vrev="1">
    <srcmd5>f82deb2ec83d87291fbe6fb6442e82f8</srcmd5>
    <version>0.4.0</version>
    <time>1425892004</time>
    <user>dimstar_suse</user>
    <comment>Xfce 4.12</comment>
    <requestid>289374</requestid>
  </revision>
  <revision rev="28" vrev="1">
    <srcmd5>27db6879d5c7528a9051788c2f687b52</srcmd5>
    <version>0.6.1</version>
    <time>1503592896</time>
    <user>dimstar_suse</user>
    <comment>1</comment>
    <requestid>512212</requestid>
  </revision>
  <revision rev="29" vrev="1">
    <srcmd5>067ec9895d6b3909f0e6bf57365f06e4</srcmd5>
    <version>0.6.2</version>
    <time>1546946846</time>
    <user>dimstar_suse</user>
    <comment></comment>
    <requestid>662521</requestid>
  </revision>
</revisionlist>
```

```
osc api '/source/openSUSE:Factory/libgarcon?view=info&rev=f82deb2ec83d87291fbe6fb6442e82f8'
```

```xml
<sourceinfo package="libgarcon" rev="f82deb2ec83d87291fbe6fb6442e82f8" srcmd5="f82deb2ec83d87291fbe6fb6442e82f8" verifymd5="f82deb2ec83d87291fbe6fb6442e82f8">
  <filename>libgarcon.spec</filename>
</sourceinfo>
```

what would be desired instead

```xml
  <revision rev="27" vrev="1">
    <srcmd5>f82deb2ec83d87291fbe6fb6442e82f8</srcmd5>
    <verifymd5>f82deb2ec83d87291fbe6fb6442e82f8</verifymd5>
    <version>0.4.0</version>
    <time>1425892004</time>
    <user>dimstar_suse</user>
    <comment>Xfce 4.12</comment>
    <requestid>289374</requestid>
  </revision>
```

Does not seem like that should be a problem.

@coolo 's suggestion is to do essentially what our code does, which is to stop at a match. As such OBS could do that to avoid having to do more `verifymd5` lookups than is necessary. I image just doing the lookups is simpler to code, but the suggestion would be more efficient.

Down the road knowing how many revision back the match was found would be important, as such the alternative call would need to provide that or perhaps also include an option to add them to `_history` as suggested. Our code can use the best call depending on situation.

**Comment by coolo** [comment]
As discussed in IRC: the verifymd5 only differs from the srcmd5 if there are links. And if there are links, we can only *guess* what the proper verifymd5 is based on *current* target link. So it's pretty wasteful to even query it.

I guess there were reasons to do that (it was part of my initial manager_42), but I can't think of any. So the python code as existant doesn't serve any purpose that I would understand (and I'm free to say that as I'm the author :). So the conclusion is: forbid links in origin projects - and check HEAD for linked packages only.

Did I summarize this correctly @jberry-suse ? If so, please close this one.

**Comment by mlschroe** [comment]
But that won't work, you can't look in the past and find out what the verifymd5 was at commit time if the package has a _link, as the verifymd5 depends on the sources of the package the link points to. And for non-link packages, the verifymd5 is simply the sourcemd5. (Hmm, except for services.)

**Comment by mlschroe** [comment]
(Should have refreshed the page, I didn't see coolo's answer)

**Comment by jberry-suse** [comment]
I ran into an active case of having links in history while testing for `yast2-update` package. Otherwise, I had built everything to use srcmd5 for the reasons above. @coolo informed me that the links were a mistake and remove from SLE-15-SP1 so it was unfortunate I ran into them.
