### ISSUE TITLE
Monitor filtering "forgets" the selected shown entries

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#6883]
1. Go to Monitor page
2. Select 10 entries per page
3. Use the filtering options
4. Apply filter

=> The shown entries switched to the default again.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback/Issues](https://trello.com/c/70G5o6TN/1636-address-feedback-issues)
