### ISSUE TITLE
Contributions graph in user profile page

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#6892]
It would nice to have a contributions graph in the user profile page in OBS, similar to what I have [in my profile](https://github.com/Ana06) in Github:

![image](https://user-images.githubusercontent.com/16052290/52124489-a37e7880-2629-11e9-8dd9-268de0794a59.png)

It is a nice way to check what someone did and to recognise contributions, which may also increased incontributions and the use of OBS. :bulb: 

This may need some design to decide what exactly need to be counted and how to display it.

Related to https://github.com/openSUSE/open-build-service/issues/931 and https://github.com/openSUSE/open-build-service/issues/428

**Comment by jayvdb** [comment]
This would be very helpful for me.  I have company support to do some OBS packaging, but my boss wants some evidence I did stuff, and my accepted task list isnt public.

I see xhr happening on `/user/tasks` and `/project/requests/foo` , which might be suitable for building client side analytics.  Is there any documentation for those, or a better API for that type of info from the backend?

**Comment by coolo** [comment]
@Ana06 forced me to put this here:

![screencapture-localhost-3000-user-show-coolo-2019-05-14-16_54_08](https://user-images.githubusercontent.com/1067203/57708150-27a0bd00-7669-11e9-9d39-8ea14ea872a7.png)
![screencapture-localhost-3000-user-show-dimstar-2019-05-14-16_54_47](https://user-images.githubusercontent.com/1067203/57708163-2d969e00-7669-11e9-987c-b163075db3c9.png)
