### ISSUE TITLE
Cannot clear the 'commenter' flag.

### ISSUE THREAD

**Issue by hramrach** [openSUSE/open-build-service#6899]
There is an option to enable notification when you are 'commenter' of a package or project. While this is nice there is no way to remove the 'commenter' flag once you have written a comment somewhere. Even after your comment is deleted you remain 'commenter'

Expected Result
============

You can remove 'commenter' status manually from objects or it is removed when all your comments on the object are deleted.

How to Reproduce
===============

Enable commenter notification

Write a comment somewhere

Delete the comment

There is no comment by you but you are still 'commenter'

Further Information
===============

build opensuse.org

**Comment by coolo** [comment]
hmm, the commenter field is not persistent - if there are no comments from you or comments mentioning you, you aren't commenter. As such I don't think your 'how to reproduce' is complete.

**Comment by hramrach** [comment]
I sometimes receive strange notifications from OBS for something really old which I don't remember anymore but going through the last few I did indeed find a comment when looking really carefully.

This works as expected, sorry about the noise.

It might be nice to implement a footer in the OBS mails which would tell you why you get the e-mail as bugzilla does to make such search easier but that's another issue.
