### ISSUE TITLE
[production][project#index] No route matches {:action=>"requests", :controller=>"webui/project", :project=>nil}, possible unm...

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#6925]
project#index threw this 1 times
<pre>
No route matches {:action=&gt;&quot;requests&quot;, :controller=&gt;&quot;webui/project&quot;, :project=&gt;nil}, possible unmatched constraints: [:project]
</pre>
[https://build.opensuse.org/project/list_public](https://build.opensuse.org/project/list_public)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c5b68661c8a2300084e3051)

**Comment by hennevogel** [comment]
This happens if you visit this url in beta.

**Comment by coolo** [comment]
To shortcut this for everyone else: the crash is in `app/views/webui2/webui/project/_breadcrumb_items.html.haml:16` - this really isn't a project to breadcrumb.
