### ISSUE TITLE
ajax 404 error (build results and rpmlint log) for accepted requests

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#6927]
After accepting a request I noticed an error in the browser console (see attached screenshot).

In the build result box it correctly shows "No build results available".

Note that this (the accepted) request got forwarded. Might an edge case there. This happens for old and new UI, but could be related to recent changes...

![2019-02-07_11-07](https://user-images.githubusercontent.com/968949/52404174-a9aca300-2ac8-11e9-84fe-ea05ef189bb6.png)

**Comment by eduardoj** [comment]
I tried to reproduce this on the new UI, accepting a request that gets forwarded to other project, and didn't see any error.

**Comment by bgeuken** [comment]
Let's close it then. If it happens again, we can have another look.
