### ISSUE TITLE
?nextstatus=404 renders old UI design

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#6933]
Expected Result
============
When ?nextstatus=404 is in the URL, the old design is shown even if you have activated the new UI design.

How to Reproduce
===============
1. Join the beta program
2. Open: https://build.opensuse.org/project/show/devel:languages:ruby:extensions?nextstatus=404 => renders old UI design
3. Open: https://build.opensuse.org/project/show/devel:languages:ruby:extensions => renders new UI design

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback/Issues](https://trello.com/c/70G5o6TN/1636-address-feedback-issues)
