### ISSUE TITLE
[production][group#update] undefined method `value' for nil:NilClass

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#6935]
group#update threw this 0 times
<pre>
undefined method `value&#39; for nil:NilClass
</pre>
[https://api.opensuse.org/group/openstack-developers](https://api.opensuse.org/group/openstack-developers)"

~[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c5d46de399c64000c23139d)~

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d6cf950c7b48d000db006ef)

**Comment by hennevogel** [comment]
did not happen anymore for a year...
