### ISSUE TITLE
[production][] Invalid path parameters: Invalid encoding for parameter: devel:languages:php:php53++[+���������+]

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#6939]
threw this 0 times
<pre>
Invalid path parameters: Invalid encoding for parameter: devel:languages:php:php53++[+���������+]
</pre>
[https://build.opensuse.org/project/show/devel:languages:php:php53++[+%C0%EA%F2%E8%E2%E0%F6%E8%FF+]](https://build.opensuse.org/project/show/devel:languages:php:php53++[+%C0%EA%F2%E8%E2%E0%F6%E8%FF+])"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c5c92534d332a0008850032)

**Comment by hennevogel** [comment]
I guess we should just ignore this exception.

**Comment by eduardoj** [comment]
The parameter is invalid. This should fail.
