### ISSUE TITLE
Request Repository Deletion Modal

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#6944]
# Issue Description
![bug](https://user-images.githubusercontent.com/1102934/52482132-be646600-2bb0-11e9-934f-e6ed286d5f51.png)

Expected Result
============
I expect the modal to display the form correctly, not on only half of the available space.

How to Reproduce
===============
1. Login as a non-admin user
2. Go on the repositories page of a project which you cannot edit
3. Request the deletion of a repository
4. See the form taking only half of the available space in the modal

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback/Issues](https://trello.com/c/70G5o6TN/1636-address-feedback-issues)
