### ISSUE TITLE
OpenStack "qcow" Leap 42.3 Image is Missing

### ISSUE THREAD

**Issue by ryan-rs** [openSUSE/open-build-service#6949]
# Issue Description
The [openSUSE-Leap-42.3-OpenStack.x86_64.qcow2](http://download.opensuse.org/repositories/Cloud:/Images:/Leap_42.3/images/openSUSE-Leap-42.3-OpenStack.x86_64.qcow2\) is no longer available. 

Expected Result
============
The image should be present.

How to Reproduce
===============
1. In a browser navigate to 'http://download.opensuse.org/repositories/Cloud:/Images:/Leap_42.3/images/openSUSE-Leap-42.3-OpenStack.x86_64.qcow2'

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support for specific instances from us.

Please talk to the maintainers of the [Cloud:Images](https://build.opensuse.org/project/users/Cloud:Images) project if you are missing something.

Thank you for your consideration.

**Comment by adrianschroeter** [comment]
this is actually a code bug. fix is on the way

**Comment by ryan-rs** [comment]
@adrianschroeter @hennevogel Verified that fix worked. Thanks!
