### ISSUE TITLE
Project Monitor: Close previous popup 

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#6950]
It gets a little messy really quick:

![screencapture-build-opensuse-org-project-monitor-opensuse-factory-2019-02-09-07_23_02](https://user-images.githubusercontent.com/1067203/52517450-cd442a80-2c3b-11e9-8b3f-ec25c4e3323e.png)

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback/Issues](https://trello.com/c/70G5o6TN/1636-address-feedback-issues)

**Comment by dmarcoux** [comment]
This happens for all pages where we have popovers. Another example is the build results.

**Comment by coolo** [comment]
it gets even more interesting there - as you can reload the build result but the popup stays, the popup will lose the relationship to the parent and if you scroll, it moves to 0x0

**Comment by dmarcoux** [comment]
> it gets even more interesting there - as you can reload the build result but the popup stays, the popup will lose the relationship to the parent and if you scroll, it moves to 0x0

Oh wow... hahaha. What a time to be alive!
