### ISSUE TITLE
Package#show only uses timeago on first page

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#6951]
On first page of the file list it says '7 minutes ago':

![screencapture-build-opensuse-org-package-show-opensuse-factory-live-livecd-tumbleweed-x11-2019-02-09-15_35_08](https://user-images.githubusercontent.com/1067203/52522053-a825db00-2c80-11e9-9618-391d98ad74c2.png)

On second page it says '2019-02-09', which is decimal for '7 minutes ago'

![screencapture-build-opensuse-org-package-show-opensuse-factory-live-livecd-tumbleweed-x11-2019-02-09-15_35_16](https://user-images.githubusercontent.com/1067203/52522049-a1976380-2c80-11e9-8f46-3c1ddcc8ccae.png)

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback/Issues](https://trello.com/c/70G5o6TN/1636-address-feedback-issues)
