### ISSUE TITLE
[production][package#buildresult] undefined local variable or method `collapsed_repositories' for #<#<Class:0x00000000083c3d88>:0x0...

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#6955]
package#buildresult threw this 7 times
<pre>
undefined local variable or method `collapsed_repositories&#39; for #&lt;#&lt;Class:0x00000000083c3d88&gt;:0x00007f6a8f93d0e0&gt;
</pre>
[https://build.opensuse.org/package/buildresult?switch=true&amp;project=OBS%3AServer%3AUnstable%3ATestGithub%3APR-6947&amp;package=obs-server&amp;index=&amp;show_all=false](https://build.opensuse.org/package/buildresult?switch=true&amp;project=OBS%3AServer%3AUnstable%3ATestGithub%3APR-6947&amp;package=obs-server&amp;index=&amp;show_all=false)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c614ec85daac40008e027c5)

**Comment by dmarcoux** [comment]
It's not happening anymore. It happened during deployment. I think the frontend was running on the previous version and it wasn't sending the requested data (collapsed repositories) to the backend, which then caused this error.
