### ISSUE TITLE
[beta] Some build results are missing

### ISSUE THREAD

**Issue by ggardet** [openSUSE/open-build-service#6957]
# Issue Description
Check: https://build.opensuse.org/package/show/openSUSE:Leap:15.1:ARM/python3-base
On old webui aarch64 and armv7l are shown, but on new webui, only aarch64 is shown.

Expected Result
============
armv7l should be shown on new webui too.

How to Reproduce
===============
Check: https://build.opensuse.org/package/show/openSUSE:Leap:15.1:ARM/python3-base
On old webui aarch64 and armv7l are shown, but on new webui, only aarch64 is shown.

Further Information
===============
* Link: https://build.opensuse.org/package/show/openSUSE:Leap:15.1:ARM/python3-base

**Comment by dmarcoux** [comment]
Thank you @ggardet for reporting this.
