### ISSUE TITLE
[obs_factory] Build status caching too agressive

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#6959]
The caching of the build results added lately helps a lot, but there are corner cases when the backend changes the build status without the API getting notifications about it. One such case is caching repos in state=dirty and then the scheduler clears the flag without seeing the need to do anything. In such a case (and there will be more, but this one is easy to explain) the API cache will stay stale as 'building'.

My suggestion is to invalidate the cache when visiting the #show page of the staging project, so there is a way for the (educated) user to work arond the corner cases.

**Comment by coolo** [comment]
(in the name of sbehlert, who refuses to create a github account himself :)

**Comment by darix** [comment]
IMHO ... if the backend changes a state ... it should send a notification to the api. even if it didnt need to do any actual work.

**Comment by coolo** [comment]
That's possibly true, but I forgot to mention: it's urgent as it blocks behlert from accepting stagings

**Comment by bgeuken** [comment]
> **[darix](/darix) ** commented [2 hours ago](#issuecomment-462330435)
>
> IMHO ... if the backend changes a state ... it should send a notification to the api. even if it didnt need to do any actual work.

I agree. Though last time I proposed this I was told that this wouldn't be conform with the OBS architecture; The backend supposedly doesn't push to the rails frontend.

**Comment by hennevogel** [comment]
We already do this -> 56339456942fe65f039b94093eadd83faa48f9c3

**Comment by adrianschroeter** [comment]
On Montag, 11. Februar 2019, 16:20:17 CET Björn Geuken wrote:
> > **[darix](/darix) ** commented [2 hours ago](#issuecomment-462330435)
> > 
> > IMHO ... if the backend changes a state ... it should send a notification
> > to the api. even if it didnt need to do any actual work.
> I agree. Though last time I proposed this I was told that this wouldn't be
> conform with the OBS architecture; The backend supposedly doesn't push to
> the rails frontend.

the frontend has a permanent open listening stream, but this is no difference 
timing wise.

If the workflow requires updated data it must ensure on it's own that the data 
is current. See the sources_changed handling.

-- 

Adrian Schroeter
SUSE Linux Products GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
email: adrian@suse.de

**Comment by bgeuken** [comment]
> We already do this -> [5633945](https://github.com/openSUSE/open-build-service/commit/56339456942fe65f039b94093eadd83faa48f9c3)

The commit is already deployed on IBS (or at least the currently built packages include the patch). @eduardoj  We should check if sending events, e.g. delayed jobs got stuck.

**Comment by hennevogel** [comment]
Sorry maybe I wasn't clear enough: If we are discussing cache expiration via events, and you say someone said we shouldn't do this, I say we already do.

**Comment by hennevogel** [comment]
I have disabled the [failed_results](https://gist.github.com/hennevogel/8b09f5a107cdca8b03ebdfcbe2f4e4a7) cache on IBS now so you peepz can work @coolo

**Comment by hennevogel** [comment]
Now the questions are

1. how can we expire the cache in the case coolo described (@mlschroe can you send a build event in this case, even if there is nothing to do?)
2. What other cases can there be and how to handle those

**Comment by hennevogel** [comment]
> My suggestion is to invalidate the cache when visiting the #show page of the staging project, so there is a way for the (educated) user to work arond the corner cases.

This would fix Staging projects, fine, but this is a general cache. I don't like this solution.

**Comment by hennevogel** [comment]
BTW the commit coolo is talking about is 0c564a566f2678aad336c23f26ed5651c5eb7f34 from #6817

**Comment by bgeuken** [comment]
> Sorry maybe I wasn't clear enough: If we are discussing cache expiration via events, and you say someone said we shouldn't do this, I say we already do. This commit was just an example. I don't think it relates (directly) to the issue.

Looking at [clockwork](https://github.com/openSUSE/open-build-service/blob/master/src/api/config/clock.rb#L17) and the [backend call](
https://github.com/openSUSE/open-build-service/blob/master/src/api/lib/backend/api/server.rb#L29) it seems that we poll the backend every 17 seconds and create events out of it.

Anyway, I didn't want to create a side discussion. Sorry for that.

**Comment by hennevogel** [comment]
> it seems that we poll the backend every 17 seconds and create events out of it.

Yes this is how events pass from the backend to the frontend.

**Comment by bgeuken** [comment]
> 1. how can we expire the cache in the case coolo described (@mlschroe can you send a build event in this case, even if there is nothing to do?)

For now that seems like the right way to go. There would still be a 1 to 17 second window until the cache invalidates, but it would already improve things.

If we want to go one step further we could think about allowing the backend to push to the frontend. This would require some syncing code that allows the frontend to check if it has the newest state (as in state of the build state).

**Comment by coolo** [comment]
> This would fix Staging projects, fine, but this is a general cache. I don't like this solution.

Sure, this was more about introducing a workaround. And note that this works in 99% - and the 17 seconds aren't the problem, but if the staging project settles to build at the wrong moment (as far as users fetching the page into cache is concerned), the build status stays forever.

**Comment by hennevogel** [comment]
> Sure, this was more about introducing a workaround.

We have a workaround. The cache is disabled. Let's concentrate on how to fix this.

**Comment by hennevogel** [comment]
@mlschroe ping

**Comment by hennevogel** [comment]
we've discussed this offline and are working up a solution...
