### ISSUE TITLE
[production][comments#create] Invalid id given: '%''{version}'```

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#6960]
comments#create threw this 5 times
<pre>
Invalid id given: &#39;%&#39;&#39;{version}&#39;```
</pre>
[https://build.opensuse.org/comments](https://build.opensuse.org/comments)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c617bb695b37e00085b77e5)

**Comment by coolo** [comment]
Visiting https://build.opensuse.org/request/show/673332 still crashes. 

According to errbit, the body is
```
"```'%''{version}'```\r\n\r\nwhy not use ```'%%{version}'``` as everyone else does?"

**Comment by dmarcoux** [comment]
I could reproduce it locally with a comment having a quote right after the first group of backticks.

**Comment by dmarcoux** [comment]
A possible solution would be to rescue from the error raised in `CodeRay` and then return everything as the user typed it. I'm not really happy with this, but it seems like once we are in `block_code`, it's already too late to get this right. `RedCarpet` parses anything following 3 backticks as the language for the block when it's on the same line. `CodeRay` tries then to do syntax highlighting for a language which doesn't make sense (in our case <code>%''{version}'```</code>, as you can see from @coolo's comment about the comment's body). This is obviously wrong and the parser should simply ignore it. This is what GitHub does. I will need to check if it's possible to do something before we reach `block_code`.

Possible solution:
```ruby
    def block_code(code, language)
      begin
        language ||= :plaintext
        CodeRay.scan(code, language).div
      # Sadly, we cannot use something more specific than 'ArgumentError'
      # https://github.com/rubychan/coderay/blob/d38502167541a1cd1b505a0e468e0098e3ae7538/lib/coderay/helpers/plugin_host.rb#L200-L217
      rescue ArgumentError
        CodeRay.scan("```#{language}#{code}", :plaintext).div unless language == :plaintext
      end
    end
```

**Comment by hennevogel** [comment]
How about creating an issue with coderay? Hooray open source!

**Comment by dmarcoux** [comment]
@hennevogel This is what I would do normally, but the repository is pretty much unmaintained. Just look at the issues and pull requests.

**Comment by hennevogel** [comment]
I guess it's time to revert this then an use something maintained? :man_shrugging:

**Comment by dmarcoux** [comment]
I will revert the changes.

**Comment by eduardoj** [comment]
Visiting https://build.opensuse.org/request/show/673332 still returns an 500 exception. Reopening.
