### ISSUE TITLE
[production][request#changerequest] undefined method `can_be_modified_by?' for nil:NilClass

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#6968]
request#changerequest threw this 0 times
<pre>
undefined method `can_be_modified_by?&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/request/changerequest](https://build.opensuse.org/request/changerequest)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c6219b7ef83cd0008b7119a)

**Comment by eduardoj** [comment]
#8403 was a duplicate of this one, and has been solved. Closing.
