### ISSUE TITLE
[production][package#submit_request_dialog] Security warning: an embedded <script> tag on another site requested protected JavaScript. If you...

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#6969]
package#submit_request_dialog threw this 0 times
<pre>
Security warning: an embedded &lt;script&gt; tag on another site requested protected JavaScript. If you know what you&#39;re doing, go ahead and disable forgery protection on this action to permit cross-origin JavaScript embedding.
</pre>
[https://build.opensuse.org/package/submit_request_dialog/home:czerw:branches:systemsmanagement:terraform/terraform?revision=3](https://build.opensuse.org/package/submit_request_dialog/home:czerw:branches:systemsmanagement:terraform/terraform?revision=3)"

~[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c61e84ffcd349000e2ad31e)~

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5ea8e0042ec8e2001595749d)

**Comment by saraycp** [comment]
How I reproduced it: 

- Go to any package show page
- Open Submit Package link in a new tab

Doing so in the old UI it shows JavaScript code. In the new UI it shows a blank page but it raises an error that we get on Errbit.

The modal for _Submit Package_ is not exactly the same kind of modal we are using for _Branch Package_ (this link doesn't get the same error), for example. I believe that using the same kind of modal will fix it.

**Comment by saraycp** [comment]
It's addressed on this PR: #7467

**Comment by eduardoj** [comment]
Still happens in Errbit.

**Comment by eduardoj** [comment]
It doesn't happen anymore. I tried to reproduce it without success. Closing.
