### ISSUE TITLE
Request creation as anonymous user

### ISSUE THREAD

**Issue by digitaltom** [openSUSE/open-build-service#697]
Request creation is possible as anonymous user, request will be created by user "_Nobody_". 

How to reproduce: 
* I am logged in and visit my project page
* My session times out
* I click on 'Submit package' 
* The submission gets done as user "_Nobody_" 

Expected: An error saying that package submission is not possible as anonymous user.

**Comment by hennevogel** [comment]
This leads to an ActionController::InvalidAuthenticityToken exception now
