### ISSUE TITLE
[production][staging_projects#index] undefined method `dashboard' for nil:NilClass

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#6972]
staging_projects#index threw this 2 times
<pre>
undefined method `dashboard&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/project/staging_projects/openSUSE:Leap:15.1:SLE-workarounds](https://build.opensuse.org/project/staging_projects/openSUSE:Leap:15.1:SLE-workarounds)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c62e881b3ff7e00081682f9)

**Comment by DavidKang** [comment]
We removed this routes in #8981
