### ISSUE TITLE
[beta] 'linking project' broken in new webui

### ISSUE THREAD

**Issue by ggardet** [openSUSE/open-build-service#6979]
# Issue Description
`linking project` does not work on https://build.opensuse.org/project/show/openSUSE:Factory:ARM
If link is open in a new tab: https://build.opensuse.org/project/linking_projects/openSUSE:Factory:ARM it returns error 500 (but it the same in old webui).

Expected Result
============
Should not error.

How to Reproduce
===============
1. Go to https://build.opensuse.org/project/show/openSUSE:Factory:ARM
2. click on `linking project`
3. Get nothing (or error 500 if open in a new tab)

**Comment by dmarcoux** [comment]
Thank you @ggardet for reporting this.

This issue happens in the webui2/Bootstrap version.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback/Issues](https://trello.com/c/70G5o6TN/1636-address-feedback-issues)
