### ISSUE TITLE
package/add_person/ is not bootstrap

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#6989]
If you add a user from the users tab, you get a popup - but if you put an invalid user account there, you end up on package/add_person, which is not bootstrap.

**Comment by dmarcoux** [comment]
Same thing for project, you end up on project/add_person.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback/Issues](https://trello.com/c/70G5o6TN/1636-address-feedback-issues)

**Comment by vpereira** [comment]
> An easy fix is to check if the user is in the array (from the response) of the AJAX call to user/autocomplete. If not, the form can be submitted. Otherwise, the button `Accept` is disabled, we highlight the autocomplete and display a message like `This user doesn't exist`.

Should it not be the opposite @dmarcoux ? I would implement it like: 

while the array returned by the autocomplete is empty, the button 'Accept' is disabled. What do you think?

**Comment by dmarcoux** [comment]
@vpereira I like it. What I wrote should be inverted (my bad). Your suggestion is written in a better and more concise way :slightly_smiling_face:

**Comment by vpereira** [comment]
The only issue is that the user still able to submit the form pressing the enter key, no?

what do you think @dmarcoux @hennevogel ?

**Comment by vpereira** [comment]
The only issue is that the user still able to submit the form pressing the enter key, no?

what do you think @dmarcoux @hennevogel ?
