### ISSUE TITLE
c&p of collapsible text can cause the text to collapse

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#6994]
1. Go to the request show page of a request that has history elements (bootstrap enabled).
2. Uncollapse the text of one history element.
3. Select some text and copy it.

=> Once in a while this triggers a click event that causes the text to collapse.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback/Issues](https://trello.com/c/70G5o6TN/1636-address-feedback-issues)
