### ISSUE TITLE
osc diff -r... file is not limited to that file

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/open-build-service#6996]
I would like to diff only one file in between revisions, not the entire revision's all files.

How to Reproduce
-----------------------

    osc co server:proxy squid
    cd server:proxy/squid
    osc diff -r177:178 squid.changes

See the .spec file changes too

**Comment by hennevogel** [comment]
Please report this bug to the osc project -> https://github.com/openSUSE/osc
