### ISSUE TITLE
staticlinks not working with new iso names

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#6997]
openSUSE:Leap:15.1:ARM has

Repotype: staticlinks

But there is no current symlink on http://download.opensuse.org/ports/aarch64/distribution/leap/15.1/iso/

Probably the regexp here doesn't match: https://github.com/openSUSE/open-build-service/blob/master/src/backend/bs_publish#L979

**Comment by juliogonzalez** [comment]
This surely explains https://lists.opensuse.org/opensuse-buildservice/2019-02/msg00013.html and shows that it's not a problem with the product definition, but with the names for Leap 15 and SLE15, as far as we can see at Uyuni, SUSE Manager and https://build.opensuse.org/project/prjconf/systemsmanagement:sumaform:images:libvirt

**Comment by michelmno** [comment]
I do not understand the status of this issue:
 * What is wrong with the name for Leap 15 ?
 * as today 20190502 it seems there are static links for Leap15.1 arm project in http://download.opensuse.org/ports/aarch64/distribution/leap/15.1/iso/

BUT, I do not have static links for Leap15.1 ppc64le isos:
http://download.opensuse.org/ports/ppc/distribution/leap/15.1/iso/  that has *ppc64le-Build249.2-Media.iso* but no *-ppc64le-Media.iso" despite the presence of staticlinks in prjconf set before publising of last Build 249.2

**Comment by michelmno** [comment]
as per @dirkmueller , there is a special script for ports to be modified.

**Comment by Vogtinator** [comment]
@michelmno The difference between PowerPC and ARM is that :ARM has `Repotype: staticlinks` in `:ToTest`, while PowerPC has it in `:PowerPC`. It might just work it's set in `:PowerPC:ToTest` instead.

**Comment by adrianschroeter** [comment]
it works now again.

(you mixed many problems here and switched over from one script mechanism to a generic solution. The scripts were not prepared for that and you won't get the -Current links via that you insisted on in the past). 

However, this is not an OBS code base issue, so better use the admin route the next time.
