### ISSUE TITLE
[production][delayed_job#IssueTrackerUpdateIssuesJob] Net::ReadTimeout

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#7005]
delayed_job#IssueTrackerUpdateIssuesJob threw this 326 times
<pre>
Net::ReadTimeout
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c641176adaef4000c5c944e)

**Comment by bgeuken** [comment]
> /usr/lib64/ruby/2.5.0/net/http.rb:1213→ get
**/PROJECT_ROOT/app/models/issue_tracker.rb:133→ update_issues_cve**
/PROJECT_ROOT/app/models/issue_tracker.rb:153→ update_issues
/PROJECT_ROOT/app/jobs/issue_tracker_update_issues_job.rb:5→ perform
/GEM_ROOT/gems/activejob-5.2.2/lib/active_job/execution.rb:39→ block in perform_now

 The CVE issue tracker fetches a new tarball when there was an update. URL is http://cve.mitre.org/data/downloads/allitems.xml.gz

For unknown reason this stalls after some time. I tried fetching it with wget from our api host and there it gets stuck around 84%. Within OBS this causes either a Net::Timeout or a Zlib::BufError.

**Comment by bgeuken** [comment]
@bugfinder pointed out that this might be caused by cve.mitre.org blocking / limiting the access. The code checks the 'Last-Modified' time of the response header first, before requesting the tarball.
It might be that at times we still exceed some threshold they set.

**Comment by hennevogel** [comment]
Can't do anything about this, let's close this.
