### ISSUE TITLE
Chrome with disabled cache renders project monitor beta view improperly

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#7007]
The project monitor is not usable for typical tasks. It shows way less information, is not usable via keyboard and needs additional mouse clicks. Since it also forgets the settings the clicks needs even to be repeated on every page refresh.

Some examples on the realtive simple OBS:Server:Unstable project (we have larger and more complex projects though):
![screenshot_20190219_105333](https://user-images.githubusercontent.com/1067148/53006224-1878ed00-3435-11e9-87c8-61191670a87c.png)

You see that just two states of the entire project fit on the screen at all. When I scroll down by keyboard:

![screenshot_20190219_105758](https://user-images.githubusercontent.com/1067148/53006292-39414280-3435-11e9-8211-1d4d40d06e61.png)

I can not find a package on second page by keyboard (yes, via additional click in the search box it works). However also that screen is quite inefficient:

![screenshot_20190219_105918](https://user-images.githubusercontent.com/1067148/53006386-68f04a80-3435-11e9-81a6-68cc5e0a69e1.png)

- broken spacing
- repositories visible which should not be visible since no single build result matching the filter
- The inverted background is only on blocked state, but it should be on all non-final states

**Comment by Ana06** [comment]
@adrianschroeter can you double check if all the issues you mention are still there? There has been some improvements in this page lately (they are already deployed)

**Comment by adrianschroeter** [comment]
the spacing seems to have improved, the rest is still there.

Another issue is also that I can not navigate to the repositories on the right via keyboard btw. Worked before and this is also even more important now since the less content is on the page now (font size seems to be larger and more space needed in the state cells).

**Comment by bgeuken** [comment]
This is how the same project (OBS:Server:Unstable) looks for me:

![2019-02-19_13-02](https://user-images.githubusercontent.com/968949/53013698-b2956100-3446-11e9-97b2-12dc102e6dcc.png)

Could you post your version of chrome? Please also tell us If you had to do anything specific to get to this state.

**Comment by adrianschroeter** [comment]
![screenshot_20190219_131804](https://user-images.githubusercontent.com/1067148/53014447-ce016b80-3448-11e9-980d-7699b6528fb8.png)

It is the initial view when going to that url. (directly from chrome history). It is google-chrome-stable-72.0.3626.109-1.x86_64 (google version) on Tumbleweed.

**Comment by adrianschroeter** [comment]
so exact steps:
* chrome has maximized window on 1800x1080 screen
* creating new tab in chrome
* entering project monitor url

**Comment by coolo** [comment]
this url: https://build.opensuse.org/project/monitor/OBS:Server:Unstable - right?

**Comment by coolo** [comment]
ah, sorry - it's in your screenshot. I've got @bgeuken's version though here.

**Comment by coolo** [comment]
ah - shift-f5!!

**Comment by bgeuken** [comment]
> **[coolo](/coolo) ** commented [4 hours ago](#issuecomment-465109026)
> ah - shift-f5!!

Ah, true. Seems indeed a caching issue:

Calling ctrl + r uses the cache => page looks fine

Calling ctrl + R does not use the cache => page looks broken

btw, triggering a re-rendering of the table, e.g. by slightly changing the screensize "fixes" it.
Firefox is not affected.

**Comment by Ana06** [comment]
@adrianschroeter @bgeuken @coolo is this still an issue? It seems fine for me now.

We should anyway discuss redesigning this page.

**Comment by coolo** [comment]
Yes, still broken.

**Comment by Ana06** [comment]
I see. This may be a datatable bug. IMO we should completely redesign the page instead of fixing bugs in datatables. We have already invested a lot of time and effort in solving the bugs and it is still not working perfectly. Even if everything worked perfectly, using a table for render this information doesn't seem to be the best option.

**Comment by vpereira** [comment]
> Another issue is also that I can not navigate to the repositories on the right via keyboard btw. Worked before and this is also even more important now since less content is visible now (font size seems to be larger and more space needed in the state cells).

Hi @adrianschroeter , I'm investigating the cache issue. I'm ablet to reproduce it in production, but not in development. In the meantime, regarding the keyboard navigation. I'm able to navigate through the table with TABs.. does it solve your issue regarding keyboard navigation?

**Comment by vpereira** [comment]
> Ah, true. Seems indeed a caching issue:
> 
> Calling ctrl + r uses the cache => page looks fine
> 
> Calling ctrl + R does not use the cache => page looks broken
> 
> btw, triggering a re-rendering of the table, e.g. by slightly changing the screensize "fixes" it.
> Firefox is not affected.

Interesting with "Control + Shift + r" on chrome, it still uses something from cache (screenshot)

![Screenshot_2019-07-24_12-36-05](https://user-images.githubusercontent.com/37418/61787317-d6067280-ae0f-11e9-818c-160355722229.png)

**Comment by vpereira** [comment]
compiling the assets in development and adding long package names helped me to trigger it

![Screenshot_2019-07-24_13-30-24](https://user-images.githubusercontent.com/37418/61790426-6f855280-ae17-11e9-8ebc-8f3850a4cb3e.png)

**Comment by vpereira** [comment]
Removing the `.text-nowrap` from the table worked for me https://github.com/openSUSE/open-build-service/blob/master/src/api/app/views/webui2/webui/project/monitor.html.haml#L18 however the table header looks funny now. Maybe when you do a "soft refresh" the datatable doesn't run again and therefore the auto resizing gets confused?

![Screenshot_2019-07-24_14-53-31](https://user-images.githubusercontent.com/37418/61795200-2935f080-ae23-11e9-8f7c-4d63bd253ee8.png)

**Comment by bear454** [comment]
There are still issues with this page, especially with fewer build targets. It makes no sense to me that in this view, the project names are wrapped:

![image](https://user-images.githubusercontent.com/108494/63043299-cd3e1500-be80-11e9-8ba6-3e88fc432409.png)

**Comment by vpereira** [comment]
revisiting this issue today, I wasn't able to reproduce it again. @adrianschroeter if you have problems here again, please reopen this issue. Thanks!
