### ISSUE TITLE
group review needs one more step

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#7026]
I have to review requests as member of the leap-reviewers groups. For my account specifically there is no review open. The updated UI no requires me to explicitly select leap-reviewers even though there is nothing to do for any other role I have. The not relevant UI should not be displayed IMO.

![leap-reviewers](https://user-images.githubusercontent.com/722232/53244485-52532900-36ab-11e9-91f7-58a68846e6f5.gif)

**Comment by coolo** [comment]
You have a different problem I assume. Your 'my decision' tab actually has actions, no? Because you're a target maintainer and/or submitter. The issue here is that the first tab has nothing to do.

**Comment by fcrozat** [comment]
My "problem" is still relevant to the issue title, and is a regression compared to the previous UI.
And as long as there are pending reviews, "my decision" tab is useless.

**Comment by coolo** [comment]
Not really. If you're submitter, you can revoke - if you're target maintainer you can decline. Those decisions might be rare, but not useless to have. In Ludwig's case the tab was really empty.

**Comment by coolo** [comment]
See https://user-images.githubusercontent.com/1067203/57966151-c7529980-794e-11e9-98ac-6f6161afcf1b.png for my experiments to solve the dilemma - by avoiding tabs for reviews and merging it with comments and history.
