### ISSUE TITLE
RFE: Support synchronizing distribution configs and using cached data for when interconnect is down

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/open-build-service#7027]
**Is your feature request related to a problem? Please describe.**
Whenever the public openSUSE Build Service is broken for any reason, the API interconnect used by private OBS instances (including my own) breaks. While it doesn't happen too often, it's frustrating when it does happen, because it means that nothing can build until things are fixed.

**Describe the solution you'd like**
I want interconnects to be more stable from the private instance side by synchronizing the configurations locally and caching the downloaded data aggressively. In the event the interconnect isn't working, if the project being accessed has been synchronized before and has been cached, then it should continue working as if the interconnect was still working properly.

**Describe alternatives you've considered**
Cloning and rebuilding/hosting all the distribution projects locally is not an option, as that requires a ton of resources that I don't typically have.

**Additional context**
For the last hour or so, the interconnect was down and everything was failing across the board. It was frustrating to watch as things were failing and there's nothing I could do to work around it. I'd really like this to not be a problem with the next release...

**Comment by laf0rge** [comment]
I consider this a very important topic, as we've had numerous problems every so often with some kind of network outage breaking builds.  

Also, the entire idea of running a self-hosted OBS instance is to be independent and self-contained for a variety of reasons, including avoiding single points of failures (which are always bad).

The question to me is: How can one "mirror" a distribution from build.opensuse.org in a way that one has a local cache (e.g. via a rsync cron-job once per day).  This would allow local builds in case of network outages, and it would likely also significantly reduce the API load on build.opensuse.org.

**Comment by hennevogel** [comment]
> I want interconnects to be more stable from the private instance side by synchronizing the configurations locally and caching the downloaded data aggressively. 

This is just HTTP, what keeps you from doing this?

**Comment by laf0rge** [comment]
> This is just HTTP, what keeps you from doing this?

If it's that simple: great. I guess what us mere users of this software are lacking is some kind of pointers or rough guidance how this can be achieved.  If somebody says "rsync those file XYZ and serve them locally" or whatever, that's of course a no-brainer to do.  *if* you know what to do...

**Comment by osmith42** [comment]
@hennevogel thanks for the reply in the related thread:
https://lists.opensuse.org/archives/list/buildservice@lists.opensuse.org/message/ERDWJPJCDI6OM3CZXOVQJLTMMVIBBHC4/

So for "Download on Demand" repositories like Debian:12 or any other of the non openSUSE distros we don't really need to go through the openSUSE API.

**Comment by hennevogel** [comment]
@laf0rge what level of independence / autonomy are looking for? :)

**Comment by laf0rge** [comment]
@hennevogel thanks for follow-up and asking.
Note: @osmith42 and I are both associated with the Osmocom self-hosted OBS installation, so if he has found a post on the ML helping along, no immediate need for you to duplicate information here.

In general, I think we (and I'd assume anyone else running a self-hosted OBS) would want to be able to build packages for a variety of different distributions (like version of Debian, Ubuntu, Raspbian, CentOS, OpenSuse, ...) in a way that there is no build-time dependency to build.opensuse.org.  So whether build.opensuse.org is currently reachable, or whether there's some reliability problem on the server side or some kind of internet/routing problem, it should not hinder the self-hosted instance from building packages.

At the same time, one of course wants to benefit from the work on the "distribution definition' only happening once, i.e. inherit that from build.opensuse.org.

So some kind of setup where everything needed in terms of "building packages against a distribution" should be locally cached/synced.  If there's some kind of network or outage of build.opensuse.org, the self-hosted instance just  runs with whatever it has available, even if over time it is outdated.  Once network is back again (and e.g. a cron job runs), any updates in "distribution definition" are synced over.

When I say "distribution definition" I'm using it as my own language (not familiar with the OBS term) for "anything required to build a third-party package against that distribution" - in whatever form that may be, whether that's the packge feeds, metadata, project config, buildroot-fs, or whatever is needed.

I hope it's now clear what I would consider the desired situation.  I of coruse understand that I have no right to demand that things are implemented the way I see them.  I'm just asking if this or something like this is possible, and if so, how.  If that hasn't been documented yet, I think not just Osmocom but various other self-hosted OBS users would benefit.  If it's not possible, some pointers as to what would need to be developed/added might be useful.  We're definitely willing to contribute if it's within grasp of people with relatively minor exposure to the OBS codebase so far.

**Comment by hennevogel** [comment]
Like I have written on the mailing list: Just host whatever you want to build against yourself with [download on demand repository setup](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.concepts#concept_dod). Sync `prjconf` in whatever frequency you deem appropriate (like @adrianschroeter said some projects change more frequently). And then you're done.
