### ISSUE TITLE
Problem branching a package to another project and name

### ISSUE THREAD

**Issue by weberhofer** [openSUSE/open-build-service#704]
With the current online-version I'd like to branch a project:
home:weberho:BACKPORTS:webserver> osc branch openSUSE:Evergreen:11.4 openssl.289 home:weberho:BACKPORTS:webserver openssl
This results in "Server returned an error: HTTP Error 400: Bad Request
branch target package already exists: home:weberho:BACKPORTS:webserver/openssl"

When I now create a package having the same name as the target name, the project suddenly appears and contains all files of the original package.

**Comment by hennevogel** [comment]
Sounds like a sync issue (backend/frontend out of sync). Please report if this happens again...
