### ISSUE TITLE
Staging Workflow Configure UX

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#7052]
Staging Workflow > Configure could be improved. It's not intuitive that to create a staging project, you have to go to "Configure" in the Staging Workflow

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback](https://trello.com/c/K9U6WlG1/1655-address-feedback)

**Comment by hennevogel** [comment]
One thing is that when you are creating or coping a staging project, you have to enter manually the full path for the project, like blah:blubb:blabber. Maybe this should be an autocompletion or maybe assuming the workflow main project as base path would be better?

**Comment by DavidKang** [comment]
Addressed in PR #7308
