### ISSUE TITLE
Expand image is not really visible

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#7055]
**Is your feature request related to a problem? Please describe.**
The "expand content"- graphic for requests is not really visible and it looks wrongly aligned. Maybe add some text there as well to make it clear that you can expand descriptions.

First, I didn't expect this to expand anything, tbh. I just found it out by clicking it and even this was something I just have seen by coincidence.

**Describe the solution you'd like**
Improve the visibility of the expand button.

**Additional context**
![request](https://user-images.githubusercontent.com/8287131/53489022-4347ee80-3a90-11e9-84e4-27b8efd732c3.png)

**Comment by Ana06** [comment]
@mschnitzer can you please give us more details what you mean with _not really visible and it looks wrongly aligned_? What would you expect instead?

**Comment by mschnitzer** [comment]
@Ana06 I'm talking about the arrow that points downwards and stands for 'expanding'. It's not really obvious and my first thought was it comes from the description of the submission. And the 3 dots don't seem to be aligned correctly. I'm not sure if it was intended to put them there.

**Comment by Ana06** [comment]
@mschnitzer 
> I'm talking about the arrow that points downwards and stands for 'expanding'. It's not really obvious and my first thought was it comes from the description of the submission.

What would you expect instead?

>  And the 3 dots don't seem to be aligned correctly. I'm not sure if it was intended to put them there.

I would say that the three dots are in the text... It can not be seen in your image as you removed that part. Can you maybe point us to an example (a link to a request where this happens)?

**Comment by mschnitzer** [comment]
> What would you expect instead?

Maybe a link in brackets after the first part of the description that states `(click to expand)` or something like that. At least something that makes it more highlighted.

> I would say that the three dots are in the text... It can not be seen in your image as you removed that part. Can you maybe point us to an example (a link to a request where this happens)?

The three dots haven't been removed from the screen. It's at the right side. Otherwise you could open up request `190844` on the internal build service to view another example.

**Comment by DavidKang** [comment]
@mschnitzer, something like this should be fine:

![Screenshot_2019-04-22 Request 2 (review)](https://user-images.githubusercontent.com/1212806/56495723-ecdab780-64f6-11e9-8819-1516346ae635.png)

**Comment by mschnitzer** [comment]
@DavidKang 1a solution

**Comment by DavidKang** [comment]
Handled in PR #7411
