### ISSUE TITLE
[backend] missing config in BSConfig.pm.template

### ISSUE THREAD

**Issue by totoroliu** [openSUSE/open-build-service#706]
There are several $BSConfig::configs used in backend scripts,
but not existed in BSConfig.pm.template.

Some of them were existed in old versions of BSConfig.pm.template:
$BSConfig::powerhosts
$BSConfig::powerpkgs
(not sure if they are deprecated)

The list of missing configs are:
$BSConfig::checkclientconnectivity
$BSConfig::dispatch_adjust
$BSConfig::dispatch_constraint
$BSConfig::extradeltarepos
$BSConfig::extramacros
$BSConfig::getbinariesproxyserver
$BSConfig::getbinariesproxyserver_cachesize
$BSConfig::markfileorigins
$BSConfig::masterdispatcher
$BSConfig::maxmetahardlink
$BSConfig::new_full_handling
$BSConfig::nokiwitree
$BSConfig::notification_namespace
$BSConfig::powerhosts
$BSConfig::powerpkgs
$BSConfig::prp_ext_map
$BSConfig::publishedhook
$BSConfig::publishedhook_use_regex
$BSConfig::publishprogram
$BSConfig::publishredirect
$BSConfig::sched_maxserverload
$BSConfig::secure_sandboxes
$BSConfig::service_wrapper
$BSConfig::signer_maxchild
$BSConfig::signer_maxchild_flavor
$BSConfig::updateinfo_fromoverwrite
$BSConfig::usesolvstate
$BSConfig::workerpartitionservers

**Comment by vpereira** [comment]
hi, looking in the repository, I'm able to find it https://github.com/openSUSE/open-build-service/blob/master/src/backend/BSConfig.pm.template, therefore, issue is resolved. If you feel that something is missing, please re-open it!

thank you!
