### ISSUE TITLE
[api] Download logfile not working when ldap_mode is on

### ISSUE THREAD

**Issue by totoroliu** [openSUSE/open-build-service#708]
When "**ldap_mode**" is "**off**" (using db for login),
no matter the user is login or not login,
the user is always able 
to left-click "**Download logfile**" link to view full raw logfile or
to right-click "**Download logfile**" link to save the full raw logfile on computer.
The URL will change
from
```
/package/live_build_log/<project>/<pakcage>/<repository>/<arch>
```
to
```
/build/<project>/<repository>/<arch>/<package>/_log
```
.

However,
after I turn on ldap_mode,
no matter the user is login or not login,
when the user left-click "Download logfile" link,
it only refreshes the same page (showing the same live_build_log webpage)
instead of displaying the raw logfile.
The URL stays 
```
/package/live_build_log/<project>/<pakcage>/<repository>/<arch>
```

From api production.log,
when ldap_mode is on,
it seems ApplicationController is not able to get "USER" (always returns empty string):
```
ApplicationController::AuthenticationRequiredError User '' did not provide a password /srv/www/obs/api/app/controllers/application_controller.rb:242:in `extract_user'
```

**Comment by JLahti** [comment]
This is fixed with https://github.com/openSUSE/open-build-service/pull/844

**Comment by bgeuken** [comment]
I assume that this is truly fixed:-) Please re-open if that is not the case
