### ISSUE TITLE
[production][package#show] Not Found

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#7080]
package#show threw this 15 times
<pre>
Not Found
</pre>
[https://build.opensuse.org/package/show/openSUSE:Factory:ARM/ghc-imagesize-conduit](https://build.opensuse.org/package/show/openSUSE:Factory:ARM/ghc-imagesize-conduit)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c77ffe89467720014b2d939)

**Comment by hennevogel** [comment]
@dmarcoux fallout from the 404 thing?

**Comment by bgeuken** [comment]
Looks like it:/

**Comment by bgeuken** [comment]
It's actually not a regression. Just some noise in errbit. Users still see the same 404 view like before.

**Comment by dmarcoux** [comment]
Thank you @bgeuken for taking care of it.
