### ISSUE TITLE
UI: Display message from review addition above review decision

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/open-build-service#7088]
Various tools utilized by the release team add various reviews for various reasons. When the selected reviewers come to the request it is not always clear why their review is being requested and as such what aspect of the request they should be reviewing. The problem is further aggravated on maintenance requests since the multi-action nature means even more people are involved in a single request and the reviews may be for individual actions.

Most recently with the rebuilt from scratch origin-manager the reason for adding the reviews is included as a message when the review is added. Other tools do this to some degree and could be enhanced as needed. Unfortunately it is all to easy to miss the message when performing the review since the web UI does not indicate which history item (with message) related to which review.

Long-story short, the most straight-forward solution would seem to be to display the message that was used when adding the review above the prompt for a decision on the review.

An example request where this would be handy: [request #680478 for openSUSE:Leap:15.1/pfstools](https://build.opensuse.org/request/show/680478).

![image](https://user-images.githubusercontent.com/22943929/53661816-f34f6000-3c26-11e9-9ac7-2542e91e2d4a.png)

Something more along the following:

![image](https://user-images.githubusercontent.com/22943929/53662132-c51e5000-3c27-11e9-8036-0260dce5633d.png)

From the XML one can see the information is all there just not presented.

```xml
<review state="new" when="2019-03-01T12:27:43" who="origin-manager" by_group="leap-reviewers">
  <comment>Changing to a lower priority origin.</comment>
</review>
```

This is a simple scenario, if I login with `jberry_factory` I would also get the tab for my maintainer review and for multi-action requests where reviews are added by package a single user may have multiple reviews.

This solution is generic and thus should be helpful outside of release team.

**Comment by coolo** [comment]
I regrouped the review field into the history of it in #6225 - but this requires now heavy rebasing :)

**Comment by bgeuken** [comment]
I like the idea:+1:

I always found it strange to get review requests for the d:l:r:e group without anyone telling you what was actually expected from you.
