### ISSUE TITLE
[production][feeds#notifications] home:marxin:branches:games

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#7094]
feeds#notifications threw this 2 times
<pre>
home:marxin:branches:games
</pre>
[https://build.opensuse.org/user/feed/zRFTiGbGQKCx7dd6VUuSpY8g](https://build.opensuse.org/user/feed/zRFTiGbGQKCx7dd6VUuSpY8g)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c7a0e1d7c8af20008465952)

**Comment by coolo** [comment]
Up to 50 times - this really deserves attention. And I claim it's easy to fix for new comers: the feed route doesn't catch if events refer to deleted projects. The feed could either just ignore those events - or mention the error.

**Comment by bgeuken** [comment]
> Up to 50 times - this really deserves attention

It's a lot of times, but so far it only affects 4 home projects.
I'll have a look. Shouldn't take long to fix.

**Comment by coolo** [comment]
it's mostly branches - that disappear quickly

**Comment by coolo** [comment]
Up to 1496 times

**Comment by eduardoj** [comment]
Still happens in Errbit.

**Comment by coolo** [comment]
The reason it's still happening is you filter target projects, but branches are source projects.

The crash is about https://build.opensuse.org/request/show/699560 - and as you can see the target is alive and kicking
