### ISSUE TITLE
REPO?view=status should signal that it's dirty

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7114]
Currently we have some glitch in the staging dashboard that if we change the staging project content, it takes a while until the scheduler sets the buildid of the repository to inprogress - but before it did, we trust the old buildid's status checks. This means the staging project stays acceptable even though it's content changed.

Discussing with @mlschroe the view=status should report the dirty flag (set on changes), so that the staging dashboard can ignore the buildid (or the buildid is prepended with a dirty- right away?)

**Comment by coolo** [comment]
@mlschroe now that a month passed, perhaps you might have a look?

**Comment by mlschroe** [comment]
This is now done.

**Comment by coolo** [comment]
will pick this up soonish
