### ISSUE TITLE
Some flash messages have the wrong type

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#7124]
We have a few actions in which we use the wrong flash message type, mostly when creating/updating. It is currently using `:notice` while it should use `:success`. I've noticed that in a few Bootstrap-related PRs lately and instead of always pointing it out, we should fix it once and for all.

I expect flash messages to have the right type depending on their context. So when creating/updating, it should be `:success`, for informational messages `:notice` and `:error` when something bad happens.

Searching in all the controllers and changing the type, then adapting the specs should be what we need to do to close this issue.

**Comment by bgeuken** [comment]
Some of them (package controller) are already solved in #6911 Just in case someone starts working on this right away
