### ISSUE TITLE
[production][package#live_build_log] undefined method `name' for "openblas:serial":String

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#7133]
package#live_build_log threw this 6 times
<pre>
undefined method `name&#39; for &quot;openblas:serial&quot;:String
</pre>
[https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:Gcc7/openblas:serial/standard/x86_64](https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:Gcc7/openblas:serial/standard/x86_64)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c80df2fb721730008044209)

**Comment by bgeuken** [comment]
I dived a little bit into this... It seems that this happens in case of inherited multibuild packages (a project links to another project that has multi build packages).

The reason why `@package` is not set is probably [this](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/controllers/webui/package_controller.rb#L1138). I didn't have the time to verify this and find a solution. Someone else has to take over:wink:

**Comment by dmarcoux** [comment]
@bgeuken I updated the link in your comment so that it points to that line in that specific commit (in case the file changes). This can be done by pressing `y`, it will change the URL when viewing a file on GitHub.

**Comment by coolo** [comment]
This is unrelated to project links - mutlibuild logs are broken in general, e.g. https://build.opensuse.org/package/live_build_log/openSUSE:Factory/000product:openSUSE-Addon-NonOss-ftp-ftp-i586_x86_64/images/local

**Comment by vpereira** [comment]
> This is unrelated to project links - mutlibuild logs are broken in general, e.g. https://build.opensuse.org/package/live_build_log/openSUSE:Factory/000product:openSUSE-Addon-NonOss-ftp-ftp-i586_x86_64/images/local

what is broken here @coolo ? Could you provide more information?

Thanks!

**Comment by coolo** [comment]
Same crash?

Note that this still works on build.suse.de, so it must be a rather fresh regression.

**Comment by coolo** [comment]
But let me bisect this for you: 81731ea3c4fa2801de202fb78410e33e82b290e0 added 

```
--- a/src/api/app/views/webui2/webui/package/_breadcrumb_items.html.haml
+++ b/src/api/app/views/webui2/webui/package/_breadcrumb_items.html.haml
@@ -1,6 +1,6 @@
 = render partial: 'webui/project/breadcrumb_items'
-%li.breadcrumb-item
-  = link_to @package, package_show_path(@project, @package)
+%li.breadcrumb-item.text-word-break-all
+  = link_to truncate(@package.name, length: 50),
```

And for multibuild `@package` is a string -> crash boom bang!

The change from @package to @package.name seems safe to revert as .to_s would call .name anyway
