### ISSUE TITLE
[production][feeds#notifications] undefined method `realname' for nil:NilClass

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#7134]
feeds#notifications threw this 10 times
<pre>
undefined method `realname&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/user/feed/DrpwJsUjm9rbXAEvJkKFncNK](https://build.opensuse.org/user/feed/DrpwJsUjm9rbXAEvJkKFncNK)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c80db5fb7217300080441fe)

**Comment by bgeuken** [comment]
To summarize this... The rss feed controller is relying on the [event](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/notification.rb#L7) code, but stores it's own event payload.
Because of that #6879 broke the RSS feeds.

**Comment by hennevogel** [comment]
This is not happening anymore...
