### ISSUE TITLE
migrate from circle ci 1.0 to circle ci 2.0

### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#7135]
Warning: Starting March 15, 2019, all jobs referencing 1.0 in their configuration will cease to run. In order to continue building your project, you must update your configuration file to 2.0.

More information: https://circleci.com/sunset1-0/

**Comment by dmarcoux** [comment]
We already use CircleCI 2.0: https://github.com/openSUSE/open-build-service/blob/854f68eb08aed3950db976b96ae36c51c4894af6/.circleci/config.yml#L1

**Comment by coolo** [comment]
and we always did: https://github.com/openSUSE/open-build-service/commit/d3c263a861199197f589172de4b79ce39838d590

**Comment by vpereira** [comment]
I'm getting it on 2.9 branch (yes we maintain it) but afaik we just have travis enabled for that? @dmarcoux

**Comment by dmarcoux** [comment]
Yes... https://github.com/openSUSE/open-build-service/blob/2.9/.travis.yml

I wouldn't bother migrating the `2.9` branch to CircleCI. The Travis setup still works there.
