### ISSUE TITLE
Error getting diff: tar:

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7148]
On https://build.opensuse.org/package/show/openSUSE:Tools/openSUSE-release-tools is a link called 'Files Changed' linking to 
https://build.opensuse.org/package/rdiff/openSUSE:Tools/openSUSE-release-tools?linkrev=base&rev=695 (most likely different revision if you read it :)

This only redirects back to the package/show with the error flash
"Error getting diff: tar:" - this is not really useful.

**Comment by coolo** [comment]
The same happens in requests: https://build.opensuse.org/request/show/684536

Which makes reviewing such requests basically impossible (setting to P2). As I already left beta, I can tell you it's not related to bootstrap. I assume it's related to obs_scm service used - as this is common to both.

**Comment by hennevogel** [comment]
Please do not set priority labels without talking to us first...

**Comment by hennevogel** [comment]
Requesting a diff from the backend fails with: `<summary>tar: </summary>`

**Comment by coolo** [comment]
I believe https://github.com/openSUSE/open-build-service/pull/7206 is supposed to fix this

**Comment by mlschroe** [comment]
Yes.
