### ISSUE TITLE
[production][request#show] undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7164]
request#show threw this 14 times
<pre>
undefined method `name&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/request/show/684243](https://build.opensuse.org/request/show/684243)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c878ae5f0a89200086524f2)

**Comment by coolo** [comment]
This somehow affects all requests from https://build.opensuse.org/project/requests/TestLinux

**Comment by coolo** [comment]
I was forced to leave beta - such crashes in your code just don't receive the required attention and I'm actually required to use the build service :(

**Comment by hennevogel** [comment]
@coolo maybe we have something else to do? :-)

**Comment by coolo** [comment]
I'm hopeful that this something else is writing feature tests for the webui

**Comment by dmarcoux** [comment]
It's not occurring anymore, I just checked again all the requests which caused this exception. Somehow no user was returned on this line when doing `User.find_by(login: review[:who])` and it crashes in the helper method.

https://github.com/openSUSE/open-build-service/blob/93ac2948b9eccc8a9756d2c87329bb229f758beb/src/api/app/views/webui2/webui/request/_review_tab.html.haml#L5
