### ISSUE TITLE
Frontend crash on viewing request

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/open-build-service#7174]
# Issue Description
Server returns error code 500

Expected Result
============
I see request.

How to Reproduce
===============

  1. Login to build.opensuse.org
  2. Go to https://build.opensuse.org/request/show/684655
  3. See error

(markdown on GitHub seems to be broken in preview without filler between lists)

  1. Logout
  2. https://build.opensuse.org/request/show/684655
  3. No error
  4. Login
  5. See error

`osc rq show -i 684655` works without issues.

Further Information
===============
* Possible related to permissions. I have project permissions for devel:libraries:c_c++ but not package permissions.

**Comment by Ana06** [comment]
Thank for the report @AdamMajer This is already tracked on https://github.com/openSUSE/open-build-service/issues/7164 We are on it :wink:

**Comment by coolo** [comment]
Leave beta as workaround
