### ISSUE TITLE
Missing validation for project in Staging:Workflow

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#7175]
From `src/api/app/models/staging/workflow.rb`:

```ruby
 parent = Project.find_or_initialize_by(name: "#{project.name}:Staging:#{letter}")
```

which is called in an after create. But it is not compulsory to have a project (at least there is not validation) which causes:

`undefined method `name' for nil:NilClass`

Solution: Add the validation and not allow to have an staging workflow without a project and fixed everything this breaks.

**Comment by ibrahimelbanna** [comment]
@Ana06 can i work on it ?

**Comment by dmarcoux** [comment]
@ibrahimelbanna Sure, go ahead.

**Comment by manishnagdewani96170** [comment]
@dmarcoux IS this issue closed or can I also work on it?

**Comment by dmarcoux** [comment]
@manishnagdewani96170 Sure, go ahead. We never heard back from @ibrahimelbanna.
