### ISSUE TITLE
Autocompletion in Add review is broken

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#7185]
The suggestions of projects in the "Add a reviewer to request" appear under the modal, which made it completely unusable:

![image](https://user-images.githubusercontent.com/16052290/54346406-41139180-4645-11e9-820f-9a3072d9bff3.png)

## How to reproduce

1. Go to a request
2. Click the link add a review
3. Select type Package in the modal
4. Write the beginning of a project name

**Comment by dmarcoux** [comment]
The styling of the autocomplete inputs are also different from what we do normally: https://obs-patterns.netlify.com/molecules/autocomplete.html

**Comment by Ana06** [comment]
IT happens for other fields and not only for project
