### ISSUE TITLE
nothing provides MACRO

### ISSUE THREAD

**Issue by hramrach** [openSUSE/open-build-service#7199]
# Issue Description

Requires: %(shell command) results in empty Requires considered by OBS
Required(pre): %(shell command) results in package changing to unresolvable state due to "nothing provides MACRO"

Expected Result
============

All require types are interpreted same. For my use case I prefer the empty Requires: because I can ensure the requirements are fulfilled by other means besides OBS parsing my spec file.

**Comment by hramrach** [comment]
Has a workaround which also resolves problem with empty requires:

%define package_requires        %(rpm -q --queryformat '[%%{REQUIREFLAGS:deptype},%%{REQUIRENEVRS}\n]' %kernel_package_name | grep -vE 'rpmlib,|interp,' | grep -E 'manual,' | sed -e 's/.*,//' | tr '\n' ' ')
%define package_requires_pre    %(rpm -q --queryformat '[%%{REQUIREFLAGS:deptype},%%{REQUIRENEVRS}\n]' %kernel_package_name | grep -vE 'rpmlib,|interp,' | grep -E 'pre,' | sed -e 's/.*,//' | tr '\n' ' ')
%define package_requires_preun  %(rpm -q --queryformat '[%%{REQUIREFLAGS:deptype},%%{REQUIRENEVRS}\n]' %kernel_package_name | grep -vE 'rpmlib,|interp,' | grep -E 'pre,' | sed -e 's/.*,//' | tr '\n' ' ')
%define package_requires_post   %(rpm -q --queryformat '[%%{REQUIREFLAGS:deptype},%%{REQUIRENEVRS}\n]' %kernel_package_name | grep -vE 'rpmlib,|interp,' | grep -E 'pre,' | sed -e 's/.*,//' | tr '\n' ' ')
%define package_requires_postun %(rpm -q --queryformat '[%%{REQUIREFLAGS:deptype},%%{REQUIRENEVRS}\n]' %kernel_package_name | grep -vE 'rpmlib,|interp,' | grep -E 'pre,' | sed -e 's/.*,//' | tr '\n' ' ')

%if 0%{?package_requires}
Requires:       %package_requires
%endif
%if 0%{?package_requires_pre}
Requires(pre):  %package_requires_pre
%endif
%if 0%{?package_requires_preun}
Requires(preun):%package_requires_preun
%endif
%if 0%{?package_requires_post}
Requires(post): %package_requires_post
%endif
%if 0%{?package_requires_postun}
Requires(postun):%package_requires_postun
%endif

**Comment by mlschroe** [comment]
Wrong component, the parser is actually in the obs-build repository. Anyway, fixed with commit fc5da5e04ebfaf714e342334cf8c4f7ebdee289d in that repo.

**Comment by hramrach** [comment]
[/openSUSE/obs-build/commit/fc5da5e04ebfaf714e342334cf8c4f7ebdee289d](url) Thanks
