### ISSUE TITLE
 Change Admin e-mail -> blank page submission

### ISSUE THREAD

**Issue by T1loc** [openSUSE/open-build-service#721]
When I try to change the admin email (root@localhost) by : xxx.yyy@domain-xxx.com
I get a blank page after the submission

Step to reproduce : 
Admin config -> Edit your profile -> change the email
return url :  https://obs.xxxxx.com/user/save

I can provide an admin user for test (pm on irc)

**Comment by hennevogel** [comment]
Please provide the logs when this happens. I can't reproduce it

**Comment by hennevogel** [comment]
Please reopen if this still happens for you...
