### ISSUE TITLE
Add a white background to flash messages when scrolling

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#7216]
**Is your feature request related to a problem? Please describe.**
I just discovered that the flash messages now follow the screen, when I scroll down, but I think it can be improved.

**Describe the solution you'd like**
Maybe don't make the background of the area between the start of the flash and to the top of the browser transparent. I would simply hide the text which is in between when scrolling. In my opinion it looks not good when you scroll down.

Please have a look on the screens. They should clarify what I mean (and yes, I used real gimp skills on these)

**Screenshot**

This is how it looks right now:
![service-running](https://user-images.githubusercontent.com/8287131/54532269-aa6a0c00-4987-11e9-8840-93b8d82e5035.png)

I would expect it to look like that:
![service-running-2](https://user-images.githubusercontent.com/8287131/54532554-4a279a00-4988-11e9-9270-8b2715834699.png)

**Comment by Ana06** [comment]
I personally find it ok as it is already. think we are using Bootstrap classes, so this seems to be the default behavior.

**Comment by Ana06** [comment]
I personally find it ok as it is already. I would rather stop it from moving, but I think we are already using Bootstrap classes, so this seems to be the default behavior.

**Comment by Ana06** [comment]
I am personally not sure if it should stay when you scroll. @bgeuken it seems you implemented this, do you remember the reason for it?

**Comment by saraycp** [comment]
I'm trying different options. Some GIFs to have a clearer idea:

**Right now**

![non_top_sticky_flash](https://user-images.githubusercontent.com/2581944/56495359-d3853b80-64f5-11e9-8fd1-45e36d112f7a.gif)

**Sticky on the top**

![top_sticky_flash](https://user-images.githubusercontent.com/2581944/56495442-092a2480-64f6-11e9-8711-ff4deac51cb8.gif)

**Sometimes we have more than one flash box. We should also decide how to do it.**

![2_top_sticky_flash](https://user-images.githubusercontent.com/2581944/56495553-645c1700-64f6-11e9-8fa9-fe6e81b21ffb.gif)

**Comment by coolo** [comment]
:+1: - ignore the rare case of 2 flashes

**Comment by saraycp** [comment]
@coolo, even if we ignore the case of 2 flashes, we also have the announcement box that looks a behaves like a flash box. Taking this into account, PR #7435 is my proposal.

Could you please have a look?

Result:

![flash_on_scroll](https://user-images.githubusercontent.com/2581944/56509666-e44ea500-6527-11e9-9150-1e93e119ff52.gif)

**Comment by mschnitzer** [comment]
Thinking about it a little more, I would even now tend to say that it should not follow at all. Normally, you read it once and then you want to follow up with what you're doing. In that case, if the box is following you, you probably get annoyed by it and want it to go away as it might hide content of the page. Sure, you can click the cross, but is it really necessary?

In the case it will stay, please make sure to add at least some kind of padding between two flashes, but the background should not be transparent between them. I would rather create a div element, apply the greyish background and then place the flashes inside that div.

**Comment by coolo** [comment]
the reason the flash follows is because it can be triggered by ajax functions in the middle of the screen - having them on top is only partially useful then.

**Comment by mschnitzer** [comment]
That explains it, but maybe Bootstrap Toasts are better in that case. Anyways, changing it now completely is not necessary I would say. The suggestion of Saray is already quite good, I'd just like to see some greyed-out space (like I described in my last comment) between >1 flashes.
