### ISSUE TITLE
Thinking Sphinx is not starting automatically

### ISSUE THREAD

**Issue by jsjhb** [openSUSE/open-build-service#722]
after a server restart one has to manually start Thinking Sphinx to have the search function working:
cd /srv/www/obs/api
RAILS_ENV="production" rake ts:start

Can you please start this service automatically?
Adrian mentioned, that clockworkd should start that automatically, but for my installation this was not started for more than 4 days.

**Comment by eduardoj** [comment]
This should be fixed with #3753.

Please, reopen if you are still having issues.
