### ISSUE TITLE
all OBS instance's (sub)project names/titles have been modified -- semicolons removed, digits missing, etc.

### ISSUE THREAD

**Issue by pgnd** [openSUSE/open-build-service#7231]
My OBS instance's subproject view

    https://build.opensuse.org/project/subprojects/home:pgnd

as of this morning appears to have been modified -- without my interaction.

Here's what I now see:

    https://i.imgur.com/Df669w5.png

The project names have had colons/digits stripped.

Instead of (as usual, as of a coupole of days ago when I last checked ...)

  "devel:gcc8", "devel:gcc9", "devel:go", etc etc

now, I see:

  "develgcc8", "develdcc--", "develgo" , ...

The relevant _links_ appear, so far, to still be ok.

The page code, OTOH, *does* show the colon(s)
```
<td class='project_name'><a href="/project/show/home:pgnd:devel:gcc8">devel:gcc8</a></td>
```
In IRC a 'font issue' is suggested.  Here, fwiw, the display issue's the same in Chrome & Firefox.

**Comment by jengelh** [comment]
Note how the input box to the right of "Watchlist" exceeds the darkgray bar, and how "pgnd" in the lower left is both green and gray, as is the "an openSUSE project" in the very last line of the HTML page. In that line, the p and j is also cut off. This does not look like an OBS issue, but more of a rendering error across the whole system (given you said in IRC it occurs with both firefox and chromium).

**Comment by pgnd** [comment]
Even here^^ on github, the "devel:gcc8", "devel:gcc9", "devel:go", referenced above, display correctly ...

**Comment by pgnd** [comment]
fyi,

the 'problem' goes away if I *disable* pages' ability to "choose their own fonts" ... and the colons/digits magically re-appear

**Comment by pgnd** [comment]
Here's the 'font analysis' for selected text on the OBS page, as provided by Firefox extension, "Font Finder (revived)" (https://addons.mozilla.org/en-US/firefox/addon/font-inspect/):

CASE: Using Local, *non*-site fonts, display OK
```
Inspecting: https://build.opensuse.org/project/subprojects/home:pgnd
Color 	

    color: #000000
    color: rgb(0, 0, 0)
    background-color: #000000
    background-color: rgba(0, 0, 0, 0)

Font 	

    font-family (stack): sans-serif, "Lucida Grande", Arial, "DejaVu Sans", Verdana
    Font being rendered:
    System Default
    100.0%
    font-size: 12.8px

Spacing 	

    line-height: 15.55px
    vertical-align: top
    letter-spacing: normal
    word-spacing: 0px

Decoration / Transformation 	

    font-weight: 400
    font-style: normal
    font-variant: normal
    text-transform: none
    text-decoration: none
    text-align: start
    text-indent: 0px

Element Details 	

    Element Type: td
    Element ID: Not Applicable
    Element Class: project_title
```



CASE: Using *site* fonts, display problem as reported
```
Inspecting: https://build.opensuse.org/project/subprojects/home:pgnd
Color 	

    color: #006699
    color: rgb(0, 102, 153)
    background-color: #000000
    background-color: rgba(0, 0, 0, 0)

Font 	

    font-family (stack): "Lucida Grande", Arial, "DejaVu Sans", Verdana, sans-serif
    Font being rendered:
    Lucida Grande
    100.0%
    font-size: 12.8px

Spacing 	

    line-height: 15.55px
    vertical-align: baseline
    letter-spacing: normal
    word-spacing: 0px

Decoration / Transformation 	

    font-weight: 400
    font-style: normal
    font-variant: normal
    text-transform: none
    text-decoration: underline
    text-align: start
    text-indent: 0px

Element Details 	

    Element Type: a
    Element ID: Not Applicable
    Element Class: 
```

**Comment by coolo** [comment]
Try `fc-match 'Lucida Grande'`

It is served by Roboto-Regular.ttf here.

**Comment by pgnd** [comment]
> Try fc-match 'Lucida Grande'

It's been here, and in use, 'forever' ...
```
fc-match 'Lucida Grande'
  Lucida Grande.ttf: "Lucida Grande" "Regular"
```

also, after a quick check -- these font-display issues occur across all of the OBS site -- not surprisingly not just on the display of 'my' instance.

and, double-checked & verified that it occurs on (a) multiple machines, and (b) in both Firefox & Chrome.

**Comment by coolo** [comment]
So your font is broken - I don't understand what you expect to happen.

**Comment by pgnd** [comment]
Broken?  Across 10+ machines?  I don't think so.

As far as 'expect' ... not much at all.  Feel free to fix your problems without help.

**Comment by dmarcoux** [comment]
> Try `fc-match 'Lucida Grande'`
> 
> It is served by Roboto-Regular.ttf here.

Same for me and I don't have such issues either. I run _openSUSE Tumbleweed_ with the snapshot `20190226`.

So it really seems to be an issue with the font.

My suggestion would be to check if it's properly installed. The package providing this font on my system is `google-roboto-fonts`. I looked it up with the following command:
```
zypper se --provides usr/share/fonts/truetype/Roboto-Regular.ttf
```

You can install the package with:
```
sudo zypper in google-roboto-fonts
```

Please let me know if this fixes your issue.
