### ISSUE TITLE
Requests that are staged can be accepted

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#7251]
When this happens they would still be staged in the staging project and it's not visible that the request state changed to 'accepted'.

Expected Result
============

In my opinion it should not be allowed to manually accept a staged request. (And if for some reason we need this to be possible, it should be handled better, e.g. notify users and unstage the request).

**Comment by coolo** [comment]
This relates to https://github.com/openSUSE/open-build-service/issues/7376

**Comment by hennevogel** [comment]
This is #7376 now
