### ISSUE TITLE
[beta] webui: use standard monospace font

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#7253]
I just joined the beta webui programme on build.opensuse.org, and now find what coolo had already hinted at in https://github.com/openSUSE/open-build-service/pull/6599#issuecomment-446847192 that the beta webui is using a second set of CSS files that also need adjustment, that is, specifying "font-family: monospace", overrding SFMono and so on.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback](https://trello.com/c/KybHivS4/1686-address-feedback)

**Comment by dmarcoux** [comment]
Since the PR fixing this was reverted, I'm re-opening this issue.

**Comment by dmarcoux** [comment]
Closing this after discussing with @eduardoj. He created a new issue to better reflect what we aim to achieve regarding fonts. This will include a monospace font.

**Comment by jengelh** [comment]
But I don't want any (arbitrary) monospace font someone else chose, I want the page to use the preference set forth in the browser settings.

**Comment by coolo** [comment]
look for other means to achieve it, e.g. by following
https://support.mozilla.org/en-US/kb/change-fonts-and-colors-websites-use#w_custom-fonts

Just because you have proper fonts setup, doesn't mean websites like OBS can rely on it to be fine in general.
