### ISSUE TITLE
[beta] webui: add collapse to default in /request/show

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#7256]
In a view like https://build.opensuse.org/request/show/687171 , the beta webui has two buttons, labeled "Expand all" and "Collapse all".
Do you think it is worthwhile having a third one, "Collapse to default" that restores the view to when the page was first opened? (Expand everything minus tarball content) I cannot see myself needing it at this point, so I am just putting it here for the record.

**Comment by bgeuken** [comment]
I don't think it's necessary. We only expand *.changes and *.spec by default. That's just two files (except in some edge cases where we have multiple specs).
Let's stick with supporting the default case, and for requests with many *.spec files one can still use the collapse all.
