### ISSUE TITLE
[beta] webui: extend diff background marking to the right

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#7257]
Concerns the diff view as present on e.g. https://build.opensuse.org/request/show/687180

Current state:
![bk](https://user-images.githubusercontent.com/8861948/54755297-fdd99580-4be5-11e9-8148-38015ec1d857.png)

Is it possible to extend the pastel red/green background of diff lines towards the right edge, so that it does not look so staggered? E.g.
![bk2](https://user-images.githubusercontent.com/8861948/54755465-47c27b80-4be6-11e9-8b99-7d3171cc75e6.png)

**Comment by jengelh** [comment]
It just occurred to me that the current practice actually makes useless trailing whitespace visible, so I'd leave it at that, unless the differ starts highlighting such totally differently (which is probably too much work).

**Comment by Ana06** [comment]
@jengelh 

> It just occurred to me that the current practice actually makes useless trailing whitespace visible, so I'd leave it at that, unless the differ starts highlighting such totally differently (which is probably too much work).

I am not sure if I understand. Would you like to leave it as it is currently (in that case we should close the issue) or do you want to change it to highline the whole line and in that case what role play the spaces?

**Comment by jengelh** [comment]
Now that I have had 27 days to work with and ponder about it, I find that having a switch to be able to use ways would be really cool.

**Comment by hennevogel** [comment]
> I find that having a switch to be able to use both ways would be really cool.

No sorry we are not going to introduce settings for this. Let's close this.
