### ISSUE TITLE
[beta] webui: request forwarding not enabled by default

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#7265]
Observed:
![bk](https://user-images.githubusercontent.com/8861948/54863787-5f684400-4d4d-11e9-91f6-3fc9b4564428.png)
( https://build.opensuse.org/request/show/687826 )

Expected:
Default enable the "forward to ..." checkbox like the old webui did.

**Comment by jengelh** [comment]
Something visually similar occurs on addrole requests:
![bk](https://user-images.githubusercontent.com/8861948/54916893-d3941a80-4efa-11e9-8b7d-c77661520c4b.png)
However, the checkbox has no effect: Even if it is not checked, the role is added. Which makes perfectly sense for addrole requests. Though the checkbox is practically redundant, I like the explicitness, but this checkbox should be marked as unchangable and always-on.

**Comment by bgeuken** [comment]
The add user as maintainer checkbox is only for submit requests. We shouldn't show it in other cases.
The reason for this checkbox / feature is that users that submit a new package, or update an existing one, can be made package maintainer right away.

**Comment by bgeuken** [comment]
> However, the checkbox has no effect: Even if it is not checked, the role is added.

I couldn't reproduce this. For submit requests we would show this checkbox and only add users as maintainer when the checkbox is marked.
For 'add role' request the checkbox was hidden.

Please let me know if I am missing something.
