### ISSUE TITLE
Login box on staging workflow is by default being shown

### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#7271]
![Screenshot_2019-03-25_14-24-49](https://user-images.githubusercontent.com/37418/54923130-e530ee80-4f09-11e9-89c9-957347e20059.png)

**Comment by bgeuken** [comment]
Here is an example of this: [staging project](https://build.opensuse.org/staging_workflows/6).

This isn't an issue on development machines. So it might be related to the proxy code or views

**Comment by Ana06** [comment]
I think this is not a Boostrap issue, as it is only related o staging workflow, isn't it?

**Comment by coolo** [comment]
it appears on all pages that are bootstrap exclusive. You normally don't see it as you see bento if not logged in.
