### ISSUE TITLE
Project#new view is not migrated to Bootstrap

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#7278]
# Issue Description
We migrated the Project views to the Bootstrap UI, but Project#new view is still using the old UI.

Expected Result
============
The Project#new view should be migrated to Bootstrap or deleted. We already use modals in the Project#subprojects view to do the same (creating subprojects is like creating projects). We need to align these views. I believe we should get rid of the modals.

How to Reproduce
===============
1. Go to https://build.opensuse.org/project/new
2. See the old UI

Further Information
===============
I found this out when clicking on the `Create Home` link at the top right.

![project-new-bootstrap](https://user-images.githubusercontent.com/1102934/55004991-89369a80-4fdb-11e9-81e5-81b2ebfa34aa.png)

**Comment by hennevogel** [comment]
Why would we migrate this view if we do not make use of it in workflows of the new ui?

**Comment by dmarcoux** [comment]
The link `Create home` should display a modal when clicked, so I guess we can flag this issue as a bug.

**Comment by coolo** [comment]
What would you expect the user to give when creating his home? Why not simply create it?

**Comment by dmarcoux** [comment]
Looking into this, we do have an [`after_create` callback on the `User` model](https://github.com/openSUSE/open-build-service/blob/0fe6bca879f9740886a77ae9e8ff5fcf38582bcb/src/api/app/models/user.rb#L107), but it depends on the configuration whether a user is allowed or not to create home project. So with this in mind, we need to adapt this `Create home` and I will do so based on my previous comment.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback](https://trello.com/c/KybHivS4/1686-address-feedback)

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback Sprint 59](https://trello.com/c/8I2pIzPH/1703-address-feedback-sprint-59)
