### ISSUE TITLE
Ubuntu_Next_universe installing packages from wrong repository

### ISSUE THREAD

**Issue by rdimesio** [openSUSE/open-build-service#7286]
Ubuntu_Next_universe should currently be for 19.04 (disco), but it is using packages from 18.10 (cosmic). Examples:
SDL2: version in 19.04 universe repository is 2.0.9, but OBS installs 2.0.8 in the build environment 
vkd3d: version in 19.04 universe repository is 1.1, but OBS installs 1.0 in the build environment
If I try to specify the correct version in the .dsc file, both produce a "nothing provides..." unresolvable error.

**Comment by hennevogel** [comment]
@adrianschroeter is this still an issue?

**Comment by rdimesio** [comment]
This seems to be fixed now; packages installed are the correct versions for eoan.
