### ISSUE TITLE
Random image from gravatar is shown for a group

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7289]
This is just wrong - there are 5 members in that group:

![screencapture-build-opensuse-org-request-show-688294-2019-03-28-06_46_50](https://user-images.githubusercontent.com/1067203/55133333-9a8bbe00-5125-11e9-982a-39db0c72b797.png)

**Comment by hennevogel** [comment]
Gravatar...

**Comment by coolo** [comment]
There is no gravatar for qam-openqa

**Comment by dmarcoux** [comment]
The coolo invasion begins!!! Run away :smile:. But seriously, it should be a random image from Gravatar.

**Comment by coolo** [comment]
So I corrected the issue title

**Comment by Ana06** [comment]
I doubt @coolo's picture is a random image from Gravatar... :eyes:

**Comment by Ana06** [comment]
the group's email is @coolo's email. That's why the picture is from @coolo. This is not a bug, it is a feature. This was a design decision, you can change the group avatar in the Gravatas account. @hennevogel are we up to discuss this again or should we close the issue?

**Comment by coolo** [comment]
I set coolo@suse.de as email to the group expecting a contact point on https://build.opensuse.org/group/show/qam-openqa (where it's not shown) - not for it to be used as group picture.

**Comment by coolo** [comment]
And for the record: my initial report was 'my image is shown for a group'. I consider this a misfeature, I removed the email now - which shows it like all other groups: with a different picture of me in black&white :)

**Comment by hennevogel** [comment]
> I set coolo@suse.de as email ... expecting a contact point not for it to be used as group picture.

But it is. If you want a different picture but the same email use some wildcard local parts like `coolo+qam-openqa@suse.de` or whatnot...
