### ISSUE TITLE
'Add X as maintainer' displayed for !submit requests

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7297]
I first spotted it in add_role requets, where it's just funny (I didn't try what happens if you accept the add_role request *and* check the box).

But https://build.opensuse.org/request/show/686832 is a delete request for a project - and adding the requesting user as maintainer won't work. I will try now though :)

This is an issue in both UIs:

Bento:
![checkbox-old](https://user-images.githubusercontent.com/1102934/56967607-d4574680-6b61-11e9-8ded-db808cc98986.png)

Bootstrap:
![checkbox](https://user-images.githubusercontent.com/1102934/56965569-e20acd00-6b5d-11e9-88bb-2069a9100e75.png)

**Comment by coolo** [comment]
Accepting with checkbox crashed - no suprise there :)

**Comment by Ana06** [comment]
Is this only Bootstrap related?

**Comment by dmarcoux** [comment]
> Is this only Bootstrap related?

I checked and it's an issue in both UIs. I added a screenshot for the Bento UI.

**Comment by coolo** [comment]
But it's a regression due to the bootstrap sprint - not sure how you define the label.

**Comment by dmarcoux** [comment]
It seems like it has been an issue for ~6 years in the Bento UI, according to [git blame](https://github.com/openSUSE/open-build-service/blame/44b427be89941c9ff6bb015df7d47a22e65ca842/src/api/app/views/webui/request/show.html.erb#L105).

**Comment by coolo** [comment]
'it seems' is english for 'it could be true unless coolo proves me wrong', right?

https://github.com/openSUSE/open-build-service/blame/293d163f30493ccca46afff2938ab9382f822659/src/api/app/views/webui/request/show.html.erb#L106

**Comment by dmarcoux** [comment]
It's more like I looked for 2 minutes :smile:
