### ISSUE TITLE
Flash messages move to the right when we open a modal

### ISSUE THREAD

**Issue by saraycp** [openSUSE/open-build-service#7298]
# Issue Description

If we have a flash message in the page and we open a modal, the flash element seems to move to the right (or adds an extra padding/margin on the left).

How to Reproduce
===============
1. Go to a package show page
2. Add a file to a package, so a flash message is shown on the top on the show page. 
3. Click on 'Branch package'
4. The flash message has moved to the right

![Screenshot-2019-3-28 test_package_2](https://user-images.githubusercontent.com/2581944/55216731-d3976180-51fd-11e9-8922-7008fae80836.png)

**Comment by bgeuken** [comment]
I think we should consider [bootstrap's toasts](https://getbootstrap.com/docs/4.3/components/toasts/) for flash messages for ajax responses. I didn't really look into this, but on first glance this looks like what we need.

**Comment by hennevogel** [comment]
toasts are cool but they have no positioning, not sure how that would help.

**Comment by saraycp** [comment]
> for flash messages for ajax responses

I guess we are not talking about the same thing. In this case, there was already a flash in the page and then I opened a modal that made the flash box to move to the right.

It seems it's a well known issue in bootstrap. Fix is coming soon... :smile:
