### ISSUE TITLE
Unable to delete _product* generated packages from my project in IBS

### ISSUE THREAD

**Issue by sreeves** [openSUSE/open-build-service#730]
I branched the _product package from SUSE:SLE-12:GA into my project and it created the ~80 auto generated subpackages (_product:*) in my project as well. I submitted my fix and attempted to delete them. Only the _product packages can be deleted. All the others are stuck in my project and give a error on attempting deletion - "404 package '_product:SLED-release' does not exist in project 'home:sreeves1:branches:SUSE:SLE-12:GA'"

I am guessing if I copied my other desired packages into a temp location, then deleted the project, recreated the project, re branched my other packages and copied the changes back in this would delete the unwanted _product* leftovers - but I don't really want to do that.

**Comment by andreas-schwab** [comment]
This is probably the same issue as 916

**Comment by adrianschroeter** [comment]
right, fixed in git master
