### ISSUE TITLE
Long comments with no whitespaces break the UI

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#7302]
This was reported by Manuel.

When adding a long text with no whitespace, like [here](https://build.opensuse.org/project/show/home:bgeuken:branches:OBS:Server:Unstable), the comment box get's pushed far to the right and breaks the overall style of the page (the package table).

**Comment by coolo** [comment]
Reactive UI - it racts to stupid comments :)

**Comment by hennevogel** [comment]
What is keeping us from using word-break by default?

**Comment by coolo** [comment]
At least to me you need to explain this. word-break in my book is 'how to break between words' - but in the example given there is just one huge word.

**Comment by coolo** [comment]
ok, my book was only telling half the story. 'break-all' breaks words. 

But it only does if there is a width given - and that's the reason my experiments failed to make any difference. And another reason is comments already use break-all: 81731ea3c4fa2801de202fb78410e33e82b290e0

So the question is rather: how to enforce a max width on cards in bootstrap.

**Comment by hennevogel** [comment]
width is always given, this is on a grid inside a fixed width container.

**Comment by Ana06** [comment]
Is this a real world bug? I mean, do we have comments without not spaces or is this just a corner case that could theoretically happen?

**Comment by DavidKang** [comment]
For me, this is a corner case, but this could maybe happen with very long project names and also depending and the size of the screen/browser (desktop, tablet, ...)

**Comment by bgeuken** [comment]
> Ana06 commented 9 days ago
> Is this a real world bug? I mean, do we have comments without not spaces or is this just a corner case that could theoretically happen?

> bgeuken commented 28 days ago
> This was reported by Manuel.

Yes, it's a real problem:wink: It might not happen so often, but some of the maintenance / release related project use bots that report their findings via comments.
In the case that Manuel reported was that a bot commented with a long comma separated list without whitespaces.

So it's an edge case, but since it completely messes up the view it's important enough to fix this.

**Comment by coolo** [comment]
we should fix the bot to include whitespace behind the comma too :)
