### ISSUE TITLE
package#dependency view is not migrated to Bootstrap

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#7319]
# Issue Description
The package#dependency view is not migrated to Bootstrap

Expected Result
============
I expect the package#dependency view to be migrated to Bootstrap

How to Reproduce
===============
1. After joining the beta program, go to the package#binary view (one [example]( https://build.opensuse.org/package/binary/openSUSE:Factory:Staging:H/000release-packages:openSUSE-MicroOS-release/standard/x86_64/openSUSE-MicroOS-release-1-8.1.x86_64.rpm))
2. Click on one of the links under the `Required by` or `Provided by` columns
3. See the package#dependency view from the old UI

Further Information
===============
Reported by @coolo on IRC.

**Comment by saraycp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Last card] Address feedback/issues](https://trello.com/c/9QtsFies/1097-last-card-address-feedback-issues)

**Comment by saraycp** [comment]
@coolo, @dmarcoux  PR  #7417 is my proposal, please have a look.
