### ISSUE TITLE
Enable Bootstrap UI automatically for Bootstrap feature specs

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#7322]
**Is your feature request related to a problem? Please describe.**
To newcomers, it can be easy to overlook the wiki when wanting to run feature specs, especially the Bootstrap ones. They would then miss that we need to prepend `BOOTSTRAP=1` to the usual `bundle exec rspec some_feature_spec.rb`. This should be automated for specs which are obviously Bootstrap feature specs, so anything under [src/api/spec/bootstrap](https://github.com/openSUSE/open-build-service/tree/master/src/api/spec/bootstrap).

**Describe the solution you'd like**
Running Bootstrap feature specs which are under _src/api/spec/bootstrap_ automatically runs them with Bootstrap enabled (so without having to use `BOOTSTRAP=1`)

**Describe alternatives you've considered**
I don't see another solution to this problem.

**Comment by coolo** [comment]
Can we just get rid of !bootstrap quickly and ignore? Please! :)

**Comment by dmarcoux** [comment]
Thinking more about this, I agree with you @coolo. We profit more by spending on time migrating views than addressing this issue (which is only temporary).
