### ISSUE TITLE
OBS does not respect _constraints

### ISSUE THREAD

**Issue by marxin** [openSUSE/open-build-service#7323]
In the following [project](https://build.opensuse.org/package/show/home:marxin:branches:devel:gcc-v2/gcc9), I have following constraints:

```
<constraints>
  <hardware>
    <disk>
      <size unit="G">16</size>
    </disk>
    <physicalmemory>
      <size unit="G">4</size>
    </physicalmemory>
    <processors>4</processors>
  </hardware>
  <overwrite>
    <conditions>
      <arch>x86_64</arch>
      <arch>ppc64le</arch>
      <arch>s390x</arch>
      <arch>aarch64</arch>
    </conditions>
    <hardware>
      <memory>
        <size unit="G">8</size>
      </memory>
      <processors>8</processors>
    </hardware>
  </overwrite>
</constraints>
```

However on ```x86_64``` I'm given following machine:
https://build.opensuse.org/package/live_build_log/home:marxin:branches:devel:gcc-v2/gcc9/openSUSE_Factory/x86_64

```
[   11s] /usr/bin/qemu-kvm -nodefaults -no-reboot -nographic -vga none -cpu host -object rng-random,filename=/dev/random,id=rng0 -device virtio-rng-pci,rng=rng0 -runas qemu -net none -kernel /var/cache/obs/worker/root_2/.mount/boot/kernel -initrd /var/cache/obs/worker/root_2/.mount/boot/initrd -append root=/dev/disk/by-id/virtio-0 rootfstype=ext4 rootflags=noatime ext4.allow_unsupported=1 kpti=off pti=off spectre_v2=off panic=1 quiet no-kvmclock elevator=noop nmi_watchdog=0 rw rd.driver.pre=binfmt_misc console=ttyS0 init=/.build/build -m 7250 -drive file=/var/cache/obs/worker/root_2/root,format=raw,if=none,id=disk,cache=unsafe -device virtio-blk-pci,drive=disk,serial=0 -drive file=/var/cache/obs/worker/root_2/swap,format=raw,if=none,id=swap,cache=unsafe -device virtio-blk-pci,drive=swap,serial=1 -serial stdio -chardev socket,id=monitor,server,nowait,path=/var/cache/obs/worker/root_2/root.qemu/monitor -mon chardev=monitor,mode=readline -smp 3
```

The machine has only 3 cores.

**Comment by mlschroe** [comment]
The info it sends is:
```
    <processors>8</processors>
    <jobs>3</jobs>
    <memory>7250</memory>
    <swap>2000</swap>
    <disk>20500</disk>
```
So there are 8 processors.

**Comment by marxin** [comment]
How are you ```jobs``` calculated so that I end up with 3?

**Comment by mlschroe** [comment]
It's not calculated, it's how the worker is set up.

**Comment by mlschroe** [comment]
I don't think a constraints on the processors makes sense, as they are shared between worker instances. I'll talk with Adrian about his ideas in regard to jobs and processors (he wrote that part of the code).

**Comment by marxin** [comment]
@hennevogel Well, this is not a Feature, but a Bug.

**Comment by adrianschroeter** [comment]
just require "jobs" instead of "processors" in constraints if you mean that ;)

**Comment by marxin** [comment]
> just require "jobs" instead of "processors" in constraints if you mean that ;)

All right, that would work. Can you please document it in:
https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.build_job_constraints.html#id-1.5.10.13.12.4
?
Thanks

**Comment by adrianschroeter** [comment]
On Donnerstag, 16. April 2020, 14:35:20 CEST wrote marxin:
> > just require "jobs" instead of "processors" in constraints if you mean that ;)
> 
> All right, that would work. Can you please document it in:
> https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.build_job_constraints.html#id-1.5.10.13.12.4
> ?

It is listed there as an example, but not explicit described ...

The full documentation of it is the schema file though:

https://build.opensuse.org/apidocs/constraints.rng

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by marxin** [comment]
> It is listed there as an example, but not explicit described ...

I see. So can you please document it. It's helpful information.

**Comment by marxin** [comment]
@adrianschroeter 

Can you please explain the meaning of **jobs** and how is that typically related to **processors**?

**Comment by adrianschroeter** [comment]
On Freitag, 17. April 2020, 14:07:01 CEST wrote marxin:
> @adrianschroeter 
> 
> Can you please explain the meaning of **jobs** and how is that typically related to **processors**?

it is not really related, jobs are the decision of the OBS admin how many parallel jobs
should be executed in parallel.

Usually it makes sense to be based on processors, but there is no fixed rule.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany
