### ISSUE TITLE
Session login should redirect to / 

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7333]
If you login through ichain route, you end up being redirected to login page - which creates the impression your password is wrong. Took me a while to realize everything was fine - as there are no links away from the page you have to change the URL manually.

How to reproduce:

- Visit build.opensuse.org
- (Logout)
- Login with wrong credentials
- You end up on https://build.opensuse.org/ICSLogin/auth-up with "
The username/password combination you entered is invalid. "
- Enter your correct credentials
- You end up on https://build.opensuse.org/ICSLogin/auth-up without flash but prompting for password again
- Be puzzled, but realize that visting build.opensuse.org has you logged in

**Comment by coolo** [comment]
I can no longer reproduce this with the new theme

**Comment by vpereira** [comment]
thank you @coolo
