### ISSUE TITLE
[beta] webui: multi-package submit requests do not always show diff

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#7336]
1. Open https://build.opensuse.org/request/show/691346 with beta webui
2. Switch away from codec2 to another package in the request
3. Observe
![z](https://user-images.githubusercontent.com/8861948/55587548-e0e7ab00-572b-11e9-94a2-094958f27b4f.png)
The ffmpeg-2.changes diff box is empty. This should not be.

4. Doing two single clicks on the `ffmpeg-2.changes` head to collapse and re-expand the diff box makes the contents show.

**Comment by coolo** [comment]
duplicating #7313
