### ISSUE TITLE
Staging a request should allow restaging

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7342]
If I stage a request into a staging project that already contains the package link from a previous (superseded) request, it currently crashes (with an error reported to the user).

It should instead update the link.

**Comment by hennevogel** [comment]
Duplicate of #7345?

**Comment by coolo** [comment]
No. 7345 is about 2 requests in review - this one is about one of them already being in superseded. And in 7345 you get a confusing error, here you get a crash.

**Comment by coolo** [comment]
#7443 would most likely be the fix

**Comment by hennevogel** [comment]
This was addressed in  #8582 right?

**Comment by coolo** [comment]
Can we have a verifying test case please?

**Comment by coolo** [comment]
at least it's working. But I don't rely on an actual supersede - I'm deleting the old manual and select the new one. But the select won't crash if there is already a link. It won't clean it up, but will add a _link - which is good enough for now.

So let's close this for now and get back to the test case if it's broken (and I'm sure it will)
