### ISSUE TITLE
Error on unselecting of gone packages

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7347]
If a package is deleted from a staging project, you get an error when unselecting:

```
coolo@f102#~>tosc api -X DELETE -T /tmp/x /staging/openSUSE:Factory/staging_projects/openSUSE:Factory:Staging:C/staged_requests
Server returned an error: HTTP Error 400: Bad Request
Error while unassigning requests: Could not delete packages oxygen5-icon-theme.
```

But as a matter of fact, the request is unstaged afterwards. Repeating it gives:

```
<status code="invalid_request">
  <summary>Error while unassigning requests: Requests with number 903 not found. </summary>
</status>
```

(which is a bug report in itself, as the request with number 903 very well exists, but is not selected there).

**Comment by eduardoj** [comment]
This was fixed in #8460. Closing.
