### ISSUE TITLE
Unable to copy&paste package list

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7364]
The package lists given in https://build-test.opensuse.org/staging_workflows/1 can't be copy&pasted.

They appear as seperated package names, but if you copy&paste they end up as 
`SUSEConnectaaa_baseboostboost-defaultsbtrfsprogscmakecurldoxygenexpatfipscheck`

Looks like because they are just spans that add spacing because they are .bade

In obs_factory you can copy&paste (to command line usage) resulting in:
`SUSEConnect aaa_base boost boost-defaults btrfsprogs cmake curl doxygen expat fipscheck`

**Comment by dmarcoux** [comment]
I checked for [`openSUSE:Factory` in `obs_factory`](https://build.opensuse.org/project/staging_projects/openSUSE:Factory) and it's also copying&pasting without spaces between packages.

Nevertheless, I agree that it's useful.

**Comment by coolo** [comment]
I might have been lucky - because if there is a review icon next to the request it is pasted as a space

**Comment by dmarcoux** [comment]
Adding a non-breaking space after each package's name doesn't work... it's simply ignored when copying&pasting, even though it's clearly in the view. It surprises me...

**Comment by coolo** [comment]
Can we ignore this until everything is working? It's still somewhat nice to have, but it depends on browsers, terminals and whatnot, so it really requires a lot of research for a corner use case.

**Comment by dmarcoux** [comment]
Yes, I talked with @eduardoj about it today and as I explained in our stand-up, I was stuck. This isn't a priority right now, so I'll unassign myself.

**Comment by hennevogel** [comment]
Works for me, includes avatar alt's though. Guess this should be enough...
