### ISSUE TITLE
Package url is too prominent

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#7365]
**Is your feature request related to a problem? Please describe.**
I personally think the package url's are too prominent (see screen).

**Describe the solution you'd like**
I think it's better when you put the link in the action list (the list where you have the option to branch, submit, edit, etc. that package) below. Next to the title doesn't look good - but it's just my personal opinion, maybe you have better ideas.

**Describe alternatives you've considered**
/

**Additional context**
![rack](https://user-images.githubusercontent.com/8287131/55673262-fed91b00-58a5-11e9-8409-76f597af472a.png)

**Comment by saraycp** [comment]
@mschnitzer PR #7418 is my proposal, please check.

**Comment by saraycp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Last card] Address feedback/issues](https://trello.com/c/9QtsFies/1097-last-card-address-feedback-issues)

**Comment by mschnitzer** [comment]
> ![](https://camo.githubusercontent.com/193766a3b9959c5f4ed5cd8cf3251d015e839d51/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [[Last card] Address feedback/issues](https://trello.com/c/9QtsFies/1097-last-card-address-feedback-issues)

Looks good 👍

**Comment by mschnitzer** [comment]
> @mschnitzer PR #7418 is my proposal, please check.

Looks good! 👍
