### ISSUE TITLE
[production][images#autocomplete_binaries] <status code="400">
  <summary>repoid is empty</summary>
</status>


### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#7368]
images#autocomplete_binaries threw this 46 times
<pre>
&lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;repoid is empty&lt;/summary&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/kiwi_images/36356/autocomplete_binaries?term=Qt&amp;repositories%5B%5D=obs%3A%2F%2FPersonal_Leap15.0%2F](https://build.opensuse.org/kiwi_images/36356/autocomplete_binaries?term=Qt&amp;repositories%5B%5D=obs%3A%2F%2FPersonal_Leap15.0%2F)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5ca88594c405120008d4af75)

**Comment by hennevogel** [comment]
Well, where is the bug? That we record this exception?

**Comment by DavidKang** [comment]
Well, I didn't go too deep in this exception but regarding that is an autocomplete coming from the WebUI and If every time that we will search for a binary we will raise this exception, so for me it's a bug or at least something to have in account. But if you don't consider that is a bug, we can close it.

**Comment by bgeuken** [comment]
The bug ~~is~~ was that it returned a 400, which caused errbit to track it. That got solved meanwhile.

=> closing
