### ISSUE TITLE
UI: [beta] Monitor page pagination broken

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/open-build-service#7372]
# Issue Description
Clicking on Next page gets me a Type error on console

Expected Result
============
See 2nd page

How to Reproduce
===============
1. Go to https://build.opensuse.org/project/monitor/home:adamm:boost_test?arch_x86_64=1&defaults=0&failed=1&repo_openSUSE_Tumbleweed=1
3. Scroll down to bottom
2. Click on Next
4. See error in console

   TypeError: g is undefined

Of course that is not so helpful. It would be better if there was an option to run unminified frontend via some sort of preferences option

I can workaround the problem by clicking on 1 and then 2

**Comment by Ana06** [comment]
As said in [#7007](https://github.com/openSUSE/open-build-service/issues/7007#issuecomment-484089672), I would go for a redesign of the page instead of fixing bugs.

**Comment by bgeuken** [comment]
@AdamMajer Is this still an issue? I tried to reproduce it and it seems fine now.

**Comment by hennevogel** [comment]
I guess not...
