### ISSUE TITLE
Requests manually accepted need to be handled

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7376]
If an user accepts a staged request manually, it needs to be treated as untracked request.

**Comment by coolo** [comment]
because it's no longer part of the staging project, but the sources are in it. User errors happen

**Comment by coolo** [comment]
If you remove accepted requests from staging projects automatically, you can simplify #7373 actually - just accepting will do.

**Comment by coolo** [comment]
I think the easier and more logic approach is to forbid accepting requests in staging. Because in the long run we also want to get rid of the by_project review to stop requests from being ready.

**Comment by DimStar77** [comment]
> I think the easier and more logic approach is to forbid accepting requests in staging. Because in the long run we also want to get rid of the by_project review to stop requests from being ready.

As an RM I sometimes NEED to accept a request; would I 'just' need to unselect it first before accepting (that would be acceptable - in the old dashboard I basically also had to unselect it to not mess up things)

**Comment by coolo** [comment]
Well, the options are:
- auto-unselecting on accept
- require manual unselect to make it force acceptable

Basically: we require force accept on backlog and on normal accept on ready - but we don't require force accept on staged requests, because you can always put them back into the backlog first. And it's the smaller mess IMO

**Comment by fcrozat** [comment]
Fine with me

**Comment by coolo** [comment]
as #8941 is merged, this should be resolved
