### ISSUE TITLE
[production][package#rpmlint_log] param is missing or the value is empty: architecture

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#7413]
package#rpmlint_log threw this 4 times
<pre>
param is missing or the value is empty: architecture
</pre>
[https://build.opensuse.org/package/rpmlint_log?project=home%3Ahennevogel&amp;package=retroarch&amp;repository=openSUSE*](https://build.opensuse.org/package/rpmlint_log?project=home%3Ahennevogel&amp;package=retroarch&amp;repository=openSUSE*)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5caefcc8c3c21600105d2a02)

**Comment by hennevogel** [comment]
I happens if you do a right click -> open in new tab on the RPM Lint "tab" in the build results box on Package#show.

**Comment by hennevogel** [comment]
can't do anything about this...
