### ISSUE TITLE
Unable to copy project that has packages with _service files

### ISSUE THREAD

**Issue by marquiz** [openSUSE/open-build-service#743]
The "POST /source/<project>?cmd=copy" API command fails to copy packages that have _service files. These packages will end up in broken state with an error like:

<pre>
Sources could not be expanded: home:marquiz:tmp_copy/tree/5d9e9f1d001718bc486c208cdebcb3f1: not in repository. Either not existing or misconfigured server setting for '$nosharedtrees' setting in BSConfig.pm
</pre>

"Normal" packages, i.e. packages without _service file(s) are copied fine, just as expected.

Some deployment details:
- OBS server version: 2.4.6
- '$nosharedtrees' setting in BSConfig.pm: 2

**Comment by mdeniz** [comment]
Closing this old issue, if still valid please reopen, thanks.
