### ISSUE TITLE
[BUG] [WEBSITE] I removed myself from my home project

### ISSUE THREAD

**Issue by user5145** [openSUSE/open-build-service#7433]
# Issue Description
OBS website allows me to delete myself from my home project.

Expected Result
============
It should not be possible nor to remove an admin if there is only one

How to Reproduce
===============
it was 2 months ago when i tried to learn it to build pulseaudio and it happened so I don't remember, but it should be somehow like this
1. Go to 'project users -> privileges'
2. Click on 'remove user or something like that'
3. Try to add yourself back or edit your home project

Further Information
===============
![Screenshot from 2019-04-22 14-36-45](https://user-images.githubusercontent.com/16629139/56501007-654c7300-650d-11e9-99da-b795991141da.png)
![Screenshot from 2019-04-22 14-50-49](https://user-images.githubusercontent.com/16629139/56501154-0d623c00-650e-11e9-80d5-0fa4051919d1.png)
* I still can create subprojects :)

edit: spelling

**Comment by coolo** [comment]
did you try 'Add user'?

**Comment by user5145** [comment]
Yes
![Screenshot from 2019-04-22 17-03-21](https://user-images.githubusercontent.com/16629139/56507102-93877e00-6520-11e9-8f39-b75c3e52fb20.png)

**Comment by mschnitzer** [comment]
@adrianschroeter or @hennevogel will for sure grant you access again.

**Comment by user5145** [comment]
That would be nice but i think it's more important to not let anyone do this mistake again by making the website able to detect this kind of situation.

**Comment by mschnitzer** [comment]
Sure, that's probably something they want to work on.

**Comment by adrianschroeter** [comment]
added you as maintainer to your home project again.

Btw, you should have been able to solve this using 

 osc meta prj -e $project

and adding yourself as maintainer. This is explicit allowed in the mode we run build.opensuse.org

**Comment by user5145** [comment]
Thanks, It seems to be working fine :)
