### ISSUE TITLE
Request in superseeded state shouldn't have approve button

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#7442]
It is not possible to change the state of a request which is not in review state (for example superseded). In those case there shouldn't be an approve button or it should be disabled:

Related to:

![image](https://user-images.githubusercontent.com/16052290/56580009-dfdec680-65d1-11e9-99f9-3782075b8dc5.png)

Related to https://github.com/openSUSE/open-build-service/issues/7263

**Comment by hennevogel** [comment]
The whole form shouldn't be there.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback](https://trello.com/c/KybHivS4/1686-address-feedback)

**Comment by dmarcoux** [comment]
This issue isn't in Bootstrap only.
