### ISSUE TITLE
Wrong mail notifications received

### ISSUE THREAD

**Issue by vinzv** [openSUSE/open-build-service#7455]
# Issue Description
I received a notification email about [some SR](https://build.opensuse.org/request/show/693968):

> Visit https://build.opensuse.org/request/show/693968
> 
> Stasiek Michalski wrote in request 693968:
> 
> Factory submission: [[SR#697504](https://build.opensuse.org/request/show/697504)](https://build.opensuse.org/request/show/697504)
> 
> -- 
> Configure notifications at https://build.opensuse.org/user/notifications
> openSUSE Build Service (https://build.opensuse.org/)
> 

I don't think I'm eligible to get that as I'm in none of the teams regarding this SR.

**Comment by hennevogel** [comment]
Can you forward me the full raw copy of the email (including all headers) to hvogel@opensuse.org please?

**Comment by vinzv** [comment]
Sure, done.

**Comment by hennevogel** [comment]
Can't figure it out. Have you previously been a member of any of the groups?

**Comment by vinzv** [comment]
Nope. In the meantime I have been receiving some more mails, but only a few.

**Comment by hennevogel** [comment]
Can you bounce them too please?

**Comment by vinzv** [comment]
Sure. Just forwarded 6 emails to you.

**Comment by hennevogel** [comment]
Can't reproduce and I also don't see anything in the logs. Might be a MTA problem in between. Sorry we can't help you with this.

**Comment by vinzv** [comment]
It's alright. In the meantime it didn't occur anymore... ¯\_(ツ)_/¯
