### ISSUE TITLE
Create values for all the repos in the project in YMP

### ISSUE THREAD

**Issue by hellcp** [openSUSE/open-build-service#7458]
# Issue Description
YMPs generated as part of backend work don't specify distributions for which the repos are created, this allows for adding repos and installing software from a different distribution, which might cause issues for users (unexpected upgrades to a different distros and such). 

Expected Result
============
[YaST checks for correct distro if distversion is set in group tag](https://github.com/yast/yast-metapackage-handler/blob/master/schema/foo.xml#L3) which could be used for ensuring that correct repo is added, instead of relying on user's ability to read.

How to Reproduce
===============
Example OBS generated YMP:
https://software.opensuse.org/ymp/openSUSE:Factory/standard/plasma-nm5.ymp?base=openSUSE%3AFactory&query=plasma-nm5

**Comment by mlschroe** [comment]
We would need to define a "base product" in the project configs, as that's what YaST uses to match.

**Comment by mlschroe** [comment]
(This gets horrible with SLE, of course, where you have a code stream and lots of different products on top of it.)

**Comment by hellcp** [comment]
Well, it's pretty awful, but it would be safer for end users. I guess SLE would need to have that defined for every product.

**Comment by letsfindaway** [comment]
:+1:  I would really like this feature as clicking on the wrong 1-click-Installer is one of the most common causes for beginners to heavily disturb their system - and probably go away from openSUSE.

**Comment by mlschroe** [comment]
Now done. YMP's for openSUSE Tumbleweed already contain the correct distversion, we'll need to set it for openSUSE Leap as well.

**Comment by adrianschroeter** [comment]
On Mittwoch, 13. November 2019, 14:55:01 CET Michael Schroeder wrote:
> Now done. YMP's for openSUSE Tumbleweed already contain the correct
> distversion, we'll need to set it for openSUSE Leap as well.

done for 15.2 and 15.1 now as well

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by hellcp** [comment]
Thank you guys, outstanding work. This makes a world of difference, just so we don't have to deal with broken (wrongly upgrades) systems all the time :D

**Comment by adrianschroeter** [comment]
On Mittwoch, 13. November 2019, 15:18:48 CET Stasiek Michalski wrote:
> Thank you guys, outstanding work. This makes a world of difference, just so
> we don't have to deal with broken (wrongly upgrades) systems all the time
> :D

I wonder if you should remove the fallback to use groups where no
distversion is set in YaST now. At least for 15.2 and Tumbleweed.

Because there are plenty base distros in OBS without a distversion defined
and it does not make much sense to add it there, since they don't have YaST 1-
Click.

But a ymp file from eg. Fedora 12 distro would still screw your Leap 15.2 
installation ....

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by hellcp** [comment]
There are no YMP files for distros without YaST though, as long as we got openSUSE/SUSE distributions covered, we should be fine

**Comment by adrianschroeter** [comment]
On Mittwoch, 13. November 2019, 15:31:52 CET Stasiek Michalski wrote:
> There are no YMP files for distros without YaST though, as long as we got
> openSUSE/SUSE distributions covered, we should be fine

OBS is creating it for any repo. Yes, you can not use it most likely on eg 
Fedora. But when you are on openSUSE and click on a YMP link to Fedora you 
still have the original problem.

Therefore, I would always expect a distversion now in Factory and 15.2.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by hellcp** [comment]
Ah yeah, we don't really show that in software-o-o, but I can see that being problematic. Although not having a fallback might be an issue for other vendors using YMP, because not every vendor does distro split.
