### ISSUE TITLE
Mentioning two users in a comment doesn't seem to work

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#7463]
# Issue Description
In submission 187890 (on the internal instance) I tried to mention two people in the comment section. The first was recognized, the second wasn't.

Expected Result
============
The second user would have been recognized.

How to Reproduce
===============
1. Go to request 187890 (internal)
2. Check the comment section

Screenshot:

![bug](https://user-images.githubusercontent.com/1102934/56722298-1427c380-6747-11e9-8e0d-e312126d312b.png)

**Comment by dmarcoux** [comment]
I added a screenshot. This issue happens on both UIs.

**Comment by coolo** [comment]
Note that the rendering and the CCing of comment emails is independent code. So even if they aren't rendered as user links, they might still be getting email. Unfortunately the other way around is true too :)
