### ISSUE TITLE
rebuild only relevent platforms of update of "build related" file/data

### ISSUE THREAD

**Issue by petrovr** [openSUSE/open-build-service#7485]
Web interface:
(1) Let a project maintain package.spec (for SUSE platforms).
(2) Let package adds to build a new "external" platform FOO. Ax external platform FOO is not build . Project has to add package-FOO.spec if is build is rpm based. Dunno for other cases.

Update of (1) or (2) triggers rebuild of all platforms. Expected is update of (1) or (2) to rebuild only relevant platforms.

Remark: update of "set version" is out of scope as this is specific to (1) or (2). Actually is common to both.

Documentation for "Scheduling and Dispatching" is quite limited. 

It seems to me with use of command line client ( see https://lists.opensuse.org/opensuse-buildservice/2006-09/msg00133.html ) defect could be avoided. 
Unfortunately is some case use of  command line is not possible.

**Comment by petrovr** [comment]
Perhaps #2104 is similar.

I'm my case (pkixssh project) build process is relative fast but issue is with time for regression tests.
Test are required to check usability on different processors. Even with restricted tests (only X.509 related) "time for testing" is ten times as "build time".

**Comment by hennevogel** [comment]
The build descriptions are just another source file, there is no distinction between them and let's say your tar-ball or patch. What's the problem with maintaining two package containers?

**Comment by hennevogel** [comment]
No answer since April...

**Comment by petrovr** [comment]
You find a way do not improve quality of project.
Anyway issue is doubling.
