### ISSUE TITLE
Binary Search API 413: search limit reached

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/open-build-service#7496]
# Issue Description

Search binary with short keywords like `php` will result in error 413: search limit reached.

Expected Result
============
API could limit the result to 100 or something but still return some results.

How to Reproduce
===============
search `php` for `openSUSE:Factory`:

```
curl -u xxx:yyy "https://api.opensuse.org/search/published/binary/id?match=contains-ic%28%40name%2C+%27php%27%29+and+path%2Fproject%3D%27openSUSE%3AFactory%27"
```

result:

```
<status code="413">
  <summary>search limit reached</summary>
  <details>413 search limit reached</details>
</status>
```

Further Information
===============

All keywords that will cause 413 errors:

* php
* test
* 0ad
* vi
* qt
* id3

**Comment by coolo** [comment]
providing account passwords in public reports is uncool

**Comment by guoyunhe** [comment]
Can OBS provide SQL based search API instead of XML based? XML query speed is really slow and cause a lot of failures.

**Comment by coolo** [comment]
the binaries are not in a database supporting SQL

**Comment by guoyunhe** [comment]
But if they are XML, it can be imported into a SQL database. Is the XML file available for download?

**Comment by coolo** [comment]
I think I just shut my mouth - since https://github.com/openSUSE/open-build-service/pull/9150 the data is in sqlite

**Comment by guoyunhe** [comment]
Is it deployed in build.opensuse.org ? How could I utilize the new backend in my request?

**Comment by adrianschroeter** [comment]
it is deployed

**Comment by adrianschroeter** [comment]
you can increase the limit by specifing a "limit" cgi parameter setting it to  new limit.

This is a backend search (search happens to run using sqlite), but the real limit is the xml rendering and amount if data. However, try to play with the limit parameter.

But from my POV this was also before not an issue, if you use the limit param, so closing it.

Feel free to reopen, in case of problems.

**Comment by guoyunhe** [comment]
I tried:

```
curl -u user:pass "https://api.opensuse.org/search/published/binary/id?match=contains-ic%28%40name%2C+%27php%27%29+and+path%2Fproject%3D%27openSUSE%3AFactory%27&limit=100"
```

But it still gives me the same error:

```xml
<status code="413">
  <summary>search limit reached</summary>
  <details>413 search limit reached</details>
</status>
```

Is here anything wrong with my query?

**Comment by guoyunhe** [comment]
My test with "php" keyword:

- limit=0 : success
- limit=1 : failed
- limit=10 : failed
- limit=100 : failed
- limit=1000 : failed

**Comment by adrianschroeter** [comment]
On Freitag, 3. April 2020, 09:40:46 CEST wrote Guo Yunhe:
> My test with "php" keyword:
> 
> - limit=0 : success

yep, that does disable the limit.

> - limit=1 : failed
> - limit=10 : failed
> - limit=100 : failed
> - limit=1000 : failed

count how many matches you get and you kno the limit which would have worked ;)

however, usually it is better to have a more specific query, since no
one really ready 1000 search results ...

And we may have better interfaces for tracking stuff, if that is what 
you actually want to do.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by guoyunhe** [comment]
My main wish is to improve the performance of search API. Currently it takes 5+ seconds for some keywords like php. Maybe the SQL database can be better indexed. Or using MariaDB/Postgres instead of SQLite for better performance. This can improve user experience of software.opensuse.org and tools like opi.

**Comment by adrianschroeter** [comment]
On Freitag, 3. April 2020, 09:51:44 CEST wrote Guo Yunhe:
> My main wish is to improve the performance of search API. Currently it takes 5+ seconds for some keywords like php. Maybe the SQL database can be better indexed. Or using MariaDB/Postgres instead of SQLite for better performance. This can improve user experience of software.opensuse.org and tools like opi.

well, it is not the search algorithm which takes that time, but rendering the result and transfering it.

For software.o.o I think it would make more sense to think how you could achieve 
the best result for the user first. I doubt he wants to read through that result.

Maybe searching for a pattern first or only in the official devel projects
to get the more important results. And only on a special "give me everything"
link searching really everywhere. And IMHO it is okay then when it takes a bit 
longer...

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany
