### ISSUE TITLE
New UI: diff highlighting gets partially removed when switchting between tabs

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#7500]
# Issue Description
When there's a submission with several packages, the diff highlighting gets partially removed when switching between tabs. This means, the color highlighting is there, but the background color is gone.

Expected Result
============
It should not get removed (even if I would say removing the background color from diffs looks better ;-) )

How to Reproduce
===============
1. Go to request 188253 on our internal build service
2. Switch between tabs)

**Comment by coolo** [comment]
the code of #7436 needs to reapply 939833e2b32c9091817ade24eead5c5beebeea88 - quite a detail actually :)
