### ISSUE TITLE
Empty summary of incidents causes the maintenance overview page to show brackets: {}

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#7505]
# Issue Description
When incidents have an empty summary, the maintenance overview page shows a (I guess) placeholder: `{}`

Expected Result
============
Maybe render: `$incident_number: no summary` instead of `$incident_number: {}`

How to Reproduce
===============
1. Go to https://build.opensuse.org/projects/openSUSE:Maintenance/maintenance_incidents
2. Find incident `9485` for an example

**Comment by saraycp** [comment]
Addressed on this PR: #7501
