### ISSUE TITLE
Unneeded checkbox in decision box for "Add Role" requests

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#7511]
# Issue Description

For a `Add role` request, a reviewer has a checkbox to add the submitter as maintainer in the decision box as you can see in the screenshot below.

![checkbox](https://user-images.githubusercontent.com/1102934/56962467-eaabd500-6b56-11e9-85f4-182ad5b4a4a8.png)

Expected Result
============
I expect the decision box to not have a checkbox to add the submitter as a maintainer. It isn't needed.

How to Reproduce
===============
1. Submit a `Add role` request to a project
2. Login as a reviewer and check the request
3. See the checkbox in the decision box.

**Comment by coolo** [comment]
I don't have as fancy screenshot paintings, but I reported it earlier :)
https://github.com/openSUSE/open-build-service/issues/7297

**Comment by dmarcoux** [comment]
Oh I didn't find it in my search. I'll close this issue and add my fancy screenshot paintings in the other issue :smile:
