### ISSUE TITLE
Large diffs usually timeout with error 408

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#752]
https://build.opensuse.org/package/rdiff/home:derselbst/stuntrally?opackage=stuntrally&oproject=games&rev=5 takes forever to load and will error in the end. For submit requests this sometimes resolves itself after several minutes when you hit refresh in the browser. It will then just omit the diff for the tarballs. That should be the default for file sizes above a certain threshold if the servers are too weak. It is also often not very interesting as you can't review all the changes to the code manually and only care for changes in .spec on OBS anyway.

**Comment by mdeniz** [comment]
IIRC this is fixed, if still valid please reopen, thanks.
