### ISSUE TITLE
Adding a user to a group even if he/she is already a member ends up in an exception

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#7546]
# Issue Description
When trying to add a user to a group even he/she is already part of that group will throw an exception in the WebUI.

Expected Result
============
A propper error message is shown.

How to Reproduce
===============
1. Create a group
2. Add a user
3. Add the same user again

**Comment by dmarcoux** [comment]
Thank you @mschnitzer for reporting this issue!

I had a look and this happens in the Bootstrap UI only. In the Bento UI, adding the same user is simply ignored.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback](https://trello.com/c/KybHivS4/1686-address-feedback)
