### ISSUE TITLE
[production] XML checker issue -  matching backend changes by Adrian  blocking PTF release into a repository

### ISSUE THREAD

**Issue by HaraldMuellerNey** [openSUSE/open-build-service#7548]
Issue in SUSE internal BS instance. Adrian made a change in the backend to allow  using two releasetargets. One for the actual target project:repository and one  providing the reference to the required channel file.

The change is working - see iosc meta prj PTF:15617

Doing the same in PTF:17571 is failing in XML checker (osc and web ui) with error:
  interleaving release targets

Project PTF:17571 is setup as needed besides missing the second release target for SLES-Server 12 SP3 x86_64, which should look like this:

    <repository name="SUSE_Updates_SLE-SERVER_12-SP3_x86_64" rebuild="local">
      <releasetarget project="PTF:Release:6620053" repository="SLES_12_SP3_BCL-x86_64" trigger="manual"/>
      <releasetarget project="SUSE:Updates:SLE-SERVER:12-SP3:x86_64" repository="update"/>
      <path project="SUSE:Updates:SLE-SERVER:12-SP3:x86_64" repository="update"/>
      <arch>x86_64</arch>
      <arch>i586</arch>
    </repository>

The first release target describes in which PTF:Release repository the
RPMs will end up on manual release:

    project="PTF:Release:6620053" repository="SLES_12_SP3_BCL-x86_64"

the second additional release target to match the channel file of SLES
12 SP3 to fetch the RPMs from the right build repository.

**Comment by HaraldMuellerNey** [comment]
My understanding Adrian enforced the project config meta on the server working around the XML checker and the checker never has been adapted.

**Comment by bgeuken** [comment]
This might be related to 3a55349327f239fa2802ceaf2e31441031d8e6c8, according to @adrianschroeter.
We'll have a look on this together tomorrow.

**Comment by adrianschroeter** [comment]
The solution for Haralds issue is simple, just allowing it in the schema. But this has some consequences. Björn and me will have a look tomorrow together.

**Comment by HaraldMuellerNey** [comment]
Do you have an update, I have a customer waiting

**Comment by HaraldMuellerNey** [comment]
Fix is getting deployed soon-ish.

**Comment by HaraldMuellerNey** [comment]
We got the project meta saved - fixed.
