### ISSUE TITLE
Submit request form is not pre-filled with target project

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#7551]
As far as I remember this form used to be filled out with the target project. This was at least the case when the source project was branched from another one.

How to Reproduce
===============
1. Branch a project
2. Edit the sources
3. Submit the project

=> The target project field is empty

**Comment by hennevogel** [comment]
There is one more place on `/package/rdiff`

**Comment by danidoni** [comment]
> There is one more place on `/package/rdiff`

I've taken care of this in #9029
