### ISSUE TITLE
project monitor page in bootstrap mode: apply filter breaks display all

### ISSUE THREAD

**Issue by bugfinder** [openSUSE/open-build-service#7555]
please try this:

go to project monitor page
https://build.opensuse.org/project/monitor/openSUSE:Tools

on the #entries selector select "Show ALL entries"
deselect one architecture from the "Architecture" drop-down
(actually any change in the selections would do).
click on "Apply Filter"

you will get a table of
Showing 1 to 0-1 of 75 entries

showing you .... exactly nothing, an empty table.

**Comment by bgeuken** [comment]
Just tried it out with PR #7553 and that one fixes this as well.
