### ISSUE TITLE
[production][image_templates#index] You cannot call create unless the parent is saved

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#7564]
image_templates#index threw this 46 times
<pre>
You cannot call create unless the parent is saved
</pre>
[https://build.opensuse.org/image_templates](https://build.opensuse.org/image_templates)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5cd07c6a6e12e0000d300d73)

```ruby

/GEM_ROOT/gems/activerecord-5.2.3/lib/active_record/associations/collection_association.rb:352→ _create_record
--
/GEM_ROOT/gems/activerecord-5.2.3/lib/active_record/associations/has_many_association.rb:124→ _create_record
/GEM_ROOT/gems/activerecord-5.2.3/lib/active_record/associations/association.rb:190→ create
/GEM_ROOT/gems/activerecord-5.2.3/lib/active_record/associations/collection_proxy.rb:350→ create
/PROJECT_ROOT/app/models/user.rb:125→ create_home_project



```

**Comment by bgeuken** [comment]
The template page is accessible again. So I'll remove the p2 label

**Comment by coolo** [comment]
where does this come from? Hopefully not from the User.current changes?

**Comment by dmarcoux** [comment]
> where does this come from? Hopefully not from the User.current changes?

No because they aren't deployed yet. It happened during our planning meeting. I tried to access the page while being logged-in with my user and it was stuck loading.

**Comment by coolo** [comment]
but the exception in errbit happened the last time 17 hours ago - so it's not the same problem

**Comment by bgeuken** [comment]
The reason for the failure is that the home projects base on the user's `login` but the validations for both differ. User names that start with `.`, `:` or `_` cause the home project creation to crash.

We could tighten the user login validation, but that would log out LDAP users with a name that matches.
In build.o.o we have 12 users with a name that starts with `_`. Though their last login is years ago.
The other option would be to add a valid character to the home project name, if needed. Disadvantage here would be that the home project name would become a bit less predictable and we might have to adapt some code.
