### ISSUE TITLE
Intermittent 404 error when branching kernel-source

### ISSUE THREAD

**Issue by michal42** [openSUSE/open-build-service#757]
I often get
- osc -A ibs rdelete -f -r -m. home:michal-m:kernel-sle12
- rm -rf home:michal-m:kernel-sle12/kernel-source
- osc -A ibs -H bco SUSE:SLE-12:GA kernel-source home:michal-m:kernel-sle12

-- POST https://api.suse.de/source/SUSE:SLE-12:GA/kernel-source?cmd=branch&target_project=home%3Amichal-m%3Akernel-sle12
send: 'POST /source/SUSE:SLE-12:GA/kernel-source?cmd=branch&target_project=home%3Amichal-m%3Akernel-sle12 HTTP/1.1\r\nAccept-Encoding: identity\r\nContent-length: 0\r\nHost: api.suse.de\r\nUser-agent: osc/0.145git\r\nConnection: close\r\nContent-type: application/x-www-form-urlencoded\r\n\r\n'
reply: 'HTTP/1.1 404 Not Found\r\n'
header: Date: Fri, 15 Aug 2014 12:25:21 GMT
header: Server: Apache/2.2.12 (Linux/SUSE)
header: X-Frame-Options: SAMEORIGIN
header: X-XSS-Protection: 1; mode=block
header: X-Content-Type-Options: nosniff
header: X-Opensuse-APIVersion: 2.5.51.git20140801.f830e40
header: X-Opensuse-Errorcode: not_found
header: X-Opensuse-Runtimes: {"view":1.461338,"db":128.75166399999998,"backend":15460.424534999996,"xml":0.384272}
header: Vary: Accept-Encoding
header: Cache-Control: no-cache
header: X-Request-Id: cfd157fe-6c54-40f7-9ea2-8663c37805b3
header: X-Runtime: 17.203996
header: X-Powered-By: Phusion Passenger 4.0.40
header: Status: 404 Not Found
header: Content-Type: application/xml; charset=utf-8
header: Connection: close
header: Transfer-Encoding: chunked
Server returned an error: HTTP Error 404: Not Found
<status code="404">
  <summary>

package 'kernel-docs' does not exist</summary>

  <details>404 package 'kernel-docs' does not exist</details>
</status>

Sometimes the error complains about kernel-ec2. It's easy to reproduce for me, it happens in about 1/3 of attempts. Note that the first command deletes the whole branch project, so this is different than issue 737

**Comment by vpereira** [comment]
Hi @michal42 , repeating your steps, 10 times, I couldn't reproduce it. Are you still facing these problems?

**Comment by vpereira** [comment]
I'm closing it. if you can reproduce it @michal42 feel free to ping me!
