### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#7579]
We want to improve the accessibility of the Bootstrap UI.

Improvements:
  - Contrast (Color blind and visually impaired users)
  - Font size
  - Focus (for users relying on keyboard navigation)

Resources:
  - https://webaim.org/
  - Browser extension: https://addons.mozilla.org/en-US/firefox/addon/wave-accessibility-tool/

_Note: This is quite basic, we need to research this topic._

**Comment by hennevogel** [comment]
Not sure it makes sense to track this in an issue. How do you solve this? When is it done?
