### ISSUE TITLE
Can't add remote url to new package

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7596]
#globalwritethrough must die

How to reproduce:

- create new package
- add file
- pick https://raw.github.com/openSUSE/open-build-service/master/.gitignore as remote url (no other options)
- Save

->  `Error while creating '' file: Can't use an undefined value as a HASH reference at /usr/lib/obs/server/BSSrcServer/Service.pm line 300..`

In the test suite it looks like this if not using cassettes to hide backend bugs:

```
Webui::PackageController
  POST #save_file
    as ajax request
      uploading a file from remote URL
        should respond with status code :ok (200) (FAILED - 1)

Failures:

  1) Webui::PackageController POST #save_file as ajax request uploading a file from remote URL should respond with status code :ok (200)
     Failure/Error: it { expect(response).to have_http_status(expected_success_status) }
       expected the response to have status code :ok (200) but it was :bad_request (400)
     Shared Example Group: "tests for save_file action" called from ./spec/controllers/webui/package_controller_spec.rb:550
     # ./spec/controllers/webui/package_controller_spec.rb:520:in `block (5 levels) in <top (required)>'
```

The following works around the bug, but I'm not this is really the fix:

```
@@ -297,7 +297,7 @@ sub runservice {
     };
     $ev->{'linksrcmd5'} = $lxservicemd5 if $lxservicemd5;
     $ev->{'projectservicesmd5'} = $projectservicesmd5 if $projectservicesmd5;
-    $ev->{'oldsrcmd5'} = $oldfilesrev->{'srcmd5'} if %$oldfiles && $oldfilesrev;
+    $ev->{'oldsrcmd5'} = $oldfilesrev->{'srcmd5'} if $oldfiles && %$oldfiles && $oldfilesrev;
     mkdir_p("$eventdir/servicedispatch");
     my $evname = "servicedispatch:${projid}::${packid}::$rev->{'srcmd5'}::$servicemark";
     $evname = "servicedispatch:::".Digest::MD5::md5_hex($evname) if length($evname) > 200;
lines 1-25/25 (END)
```

**Comment by coolo** [comment]
@mlschroe @M0ses 

it affects all services not just remote url:
```
coolo@cleopatra#frontend-base>osc ci
Sending    Dockerfile
Transmitting file data .Server returned an error: HTTP Error 400: Bad Request
Can't use an undefined value as a HASH reference at /usr/lib/obs/server/BSSrcServer/Service.pm line 300.
```

**Comment by dirkmueller** [comment]
hello?

**Comment by fcrozat** [comment]
We can't move SR to staging since this morning on SLE15 SP2 because of this.

**Comment by adrianschroeter** [comment]
Coolo, do you have a test case which is not webui specific?

Or can you tell what the webui rspec test case sends exactly to the src server?

I can not reproduce this with osc and it works with webui as well when I specify a file name. Please not that filenames with a leading dot are not allowed and this is the error I see when using your URL.

**Comment by coolo** [comment]
See Dirk's issue

**Comment by adrianschroeter** [comment]
k @dirkmueller @fcrozat  you should be fine now. (the webui code sending wrong filenames is independend)
