### ISSUE TITLE
Long repo names overflow

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#76]
* in the watchlist
* in shared/_buildresult_box.html.erb

**Comment by aosthof** [comment]
This bug is still pretty annoying, any plans to fix that in the near future?

**Comment by hennevogel** [comment]
I've experimented a bit about this in the bratwurst theme but have not come to a very good conclusion yet. Especially with copying the text...

**Comment by aosthof** [comment]
Just a guess, would it be possible to split the project name string at the ':' and do a line break if the name is too long? Wouldn't be optimal, but better than not being able to determine the project at all. BTW, what is the bratwurst theme? ;)

**Comment by hennevogel** [comment]
You can even make it appear right with a negative letter-spacing. And you can cover some of the copy&paste use cases. But not all use cases and definitely not  for all browsers. This needs more work and testing.

Bratwurst is our new theme for OBS 3.0, as opposed to bento which is our current theme. :-)

**Comment by aosthof** [comment]
OK, fair enough. Thanks for looking into this.

**Comment by bgeuken** [comment]
fixed (for project watchlist and package files)
