### ISSUE TITLE
Deleted a package, trying to branch it again results in error

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#761]
```
osc linkpac home:jengelh:branches:devel:libraries:c_c++/giflib home:Mailaender:branches:games:tools 
Sending meta data...
Server returned an error: HTTP Error 404: Not Found
home:Mailaender:branches:games:tools/giflib
```

The web interface claims "Package 'giflib' already exists in project 'home:Mailaender:branches:games:tools'" but Package "giflib" not found in project "home:Mailaender:branches:games:tools" https://build.opensuse.org/project/show/home:Mailaender:branches:games:tools?nextstatus=404

**Comment by hennevogel** [comment]
I guess this is resolved as the repo is gone...
