### ISSUE TITLE
BsRequestPermissionCheck.cmd_setpriority_permissions changes

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#7619]
Currently changing the priorities is only allowed if you can write the target project. This should be allowed independently of this.

**Comment by coolo** [comment]
Let's see - this can become a mess pretty quickly :)

**Comment by hennevogel** [comment]
A mess for whom? `BsRequest.priority` only has influence on sorting (for us)...

**Comment by bgeuken** [comment]
This might break how some maintainers or maintainer groups use the prioritization feature right now.
We should at least be verbal about this change, or make this configurable per project.

I would prefer the latter, but that of course means more conditions, more code to maintain, etc. .

**Comment by bgeuken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BsRequestPermissionCheck.cmd_setpriority_permissions changes #7619](https://trello.com/c/lPvyXXFN/1113-bsrequestpermissioncheckcmdsetprioritypermissions-changes-7619)

**Comment by coolo** [comment]
> A mess for whom? `BsRequest.priority` only has influence on sorting (for us)...

It has an impact on sorting of reviews, e.g. on the (overlong) legal queue. If every submitter had a say if her update is more important than others, I can't say how this would work out. Right now it's the release manager to say what is more important.

And maintenance speaks with two voices as well. For release requests they have a bot running calculating a complex formula based on load and queue size and what not to define the priority and on incident requests they now suddenly believe the submitter knows it best? *Doubtful face*

**Comment by hennevogel** [comment]
>  they now suddenly believe the submitter knows it best?

I've asked 3 times now, the answer remained *yes*. Can you please clarify with the release managers if they want to block this?

**Comment by hennevogel** [comment]
Offline discussions with @coolo: It's okay for release managers.

**Comment by adrianschroeter** [comment]
the origin logic was that only initial setting was allowed to the creator IIRC. So it was possible to set it but avoids priority fights ....
