### ISSUE TITLE
Markdown: Email support is not working

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#7632]
# Issue Description
When naming an email in the comment section, it doesn't get interpreted as such.

Expected Result
============
A link to 'mailto:$email' gets created.

How to Reproduce
===============
1. Go to internal submission sr#193240
2. See in the comment section

**Comment by coolo** [comment]
I'm afraid there is simply no way to write an email link in obs :)

`<manuel@example.com>` *should* work but is just eaten as HTML tags, `[manuel@example.com](mailto:manuel@example.com)` should link, but is eaten as user reference (there is already an issue about that one)

**Comment by Ana06** [comment]
@coolo 

> there is already an issue about that one

which one?

**Comment by coolo** [comment]
> which one?

mschnitzer doesn't create *that* many issues - #7539

**Comment by eduardoj** [comment]
This was fixed a while ago. Email support is working with these alternatives:
- `manuel@example.com`
- `<manuel@example.com>`
- `[manuel@example.com](mailto:manuel@example.com)`

I also checked that the in the comment section of the internal submission sr#193240 the email is correctly rendered.

Closing.
