### ISSUE TITLE
Come up with a set of fonts that we want to use and also deliver them

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#7635]
**Is your feature request related to a problem? Please describe.**
We prefer to define a fixed group of fonts that we also deliver, than to rely on a fixed group of fonts or the font configured in the browser. This way the aspect of the page will be more homogeneous.

**Describe the solution you'd like**
Deliver our own fixed group of fonts that are used in the web UI.

**Describe alternatives you've considered**
None.

**Additional context**
Related to issue #7253 and PR #7589.

**Comment by dmarcoux** [comment]
We took a decision regarding this and it's in the [pattern library](https://obs-patterns.netlify.com/atoms/typography.html):

> After some research, we decided to stick with the Native font stack as we want to rely on system fonts
