### ISSUE TITLE
Comments are not wrapped properly. 

### ISSUE THREAD

**Issue by cyphar** [openSUSE/open-build-service#7653]
# Issue Description
In most languages, you would expect that text is wrapped on word boundaries rather than on character boundaries -- but OBS comments now are wrapped on character boundaries resulting in hard-to-read comments.

This boils down to a `word-break: break-all;` CSS rule.

Expected Result
============
Text should be broken on word boundaries.

How to Reproduce
===============
1. Make a comment on a SR.
2. Note that the text is wrapped at character boundaries instead of word boundaries.

![issue example](https://user-images.githubusercontent.com/2888411/58707974-c7946f80-83f9-11e9-9940-9372841d7a5e.png)

**Comment by dmarcoux** [comment]
Thank you @cyphar for reporting this. I verified and this happens only in the Bootstrap UI.

Here's a link to a [long comment](https://build.opensuse.org/project/show/home:dmarcoux:obs-dev#comment-984274) to see this live.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback (Sprint 60)](https://trello.com/c/h3HkOuTp/1171-address-feedback-sprint-60)

**Comment by saraycp** [comment]
Exactly, `word-break: break-all;` seems to be the guilty. Please go to https://github.com/openSUSE/open-build-service/pull/7802 to read explanation and proposed solution.
