### ISSUE TITLE
[production][package#view_file] Requiring user, but found nobody

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#7718]
package#view_file threw this 0 times
<pre>
Requiring user, but found nobody
</pre>
[https://build.opensuse.org/package/view_file/home:ammartinez:branches:games/pmars/pmars.changes](https://build.opensuse.org/package/view_file/home:ammartinez:branches:games/pmars/pmars.changes)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5cf8a44790b77600129ee417)

**Comment by coolo** [comment]
Very strange problem - it's crashing in a line it shouldn't even reach and only in @Ana06's branch - I tried several other changes files.

**Comment by coolo** [comment]
```
irb(main):003:0> User.find_by_login('_nobody_').can_modify_package?(Package.get_by_project_and_name('home:ammartinez:branches:games','pmars'))
=> true
```

Sneaky @Ana:
![screencapture-build-opensuse-org-project-users-home-ammartinez-2019-06-13-14_41_58](https://user-images.githubusercontent.com/1067203/59433298-82a10d80-8de9-11e9-9c12-f7eddf56ef18.png)

**Comment by ana** [comment]
@Ana06 ^

**Comment by coolo** [comment]
sorry :)

**Comment by coolo** [comment]
Anyway, that relationship is gone now - and it's the only in the database. Adding nobody as maintainer should be forbidden - but unfortunately it still works.

And https://build.opensuse.org/user/show/_nobody_ shows that guy is pretty active :(
