### ISSUE TITLE
Project Links: Datatables Search Box Inheritance

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#772]
1) open the project page with a linked project
2) type into "Search:" something, i.e "kernel-def"
3) see "No matching records found", understand that I actually need to
go to "inherited packages"
4) switch to "inherited packages"
5) my "kernel-def" disappears, and I need to type it again.

**Comment by mdeniz** [comment]
Now the search boxes of both datatables are in sync.
