### ISSUE TITLE
Remember the number of shown items

### ISSUE THREAD

**Issue by tux93** [openSUSE/open-build-service#7724]
Currently the default number of shown items within a project / package is 10.

When a user selects a higher number and then reloads the page or navigates to a different project / package the number of shown items is reset to 10.

I'd like to either see the default number of shown items increased or the user selected number remembered so one does not have to select it every single time.

![image](https://user-images.githubusercontent.com/1749593/59262903-6d3caf80-8c40-11e9-9a21-90e2f733908c.png)

![Screenshot_2019-06-11_11-59-28](https://user-images.githubusercontent.com/1749593/59262923-72016380-8c40-11e9-8a73-1d8f1a666a0b.png)

**Comment by dmarcoux** [comment]
Thank you @tux93 for creating this issue.

I had a look and you are right, the number of shown entries isn't saved for the table in the `Sources Files` section on the package overview page. So this has to be fixed.

However, for the list of packages on the project overview page, the number of shown entries is saved. Reloading the page keeps the selection (if the default was changed). This selection is saved for 2 days. Do you think we should increase this to a longer period of time?

**Comment by tux93** [comment]
> This selection is saved for 2 days. Do you think we should increase this to a longer period of time?
That's good to know, maybe it would make sense to keep it until the user logs out / is logged out if possible? If not, 2 days seems good enough.

**Comment by dmarcoux** [comment]
>  it would make sense to keep it until the user logs out / is logged out

I created an issue to track this.
