### ISSUE TITLE
Confusion around how the state of datatables is saved

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#7726]
**Is your feature request related to a problem? Please describe.**
The state of datatables is saved for [2 days](https://github.com/openSUSE/open-build-service/blob/de99887b0331a8cf7a02ec650fc96c8145c32ef2/src/api/app/assets/javascripts/webui2/datatables.js#L11) (at the time of writing), but it's confusing to users since they don't have a way to know this beside looking at the code.

**Describe the solution you'd like**
Clear the state of datatables when a user logs out. Explain that this is happening.

**Describe alternatives you've considered**
I don't really see another way to achieve this.

**Additional context**
I created this following [a comment](https://github.com/openSUSE/open-build-service/issues/7724#issuecomment-500786985) from @tux93.

**Comment by hennevogel** [comment]
>  I don't really see another way to achieve this.

Save them forever?

**Comment by dmarcoux** [comment]
> > I don't really see another way to achieve this.
> 
> Save state forever?

This would be possible according. This is from the [official documentation](https://datatables.net/reference/option/stateDuration):

> The value 0 is a special value as it indicates that the state can be stored and retrieved indefinitely with no time limit.
