### ISSUE TITLE
[beta] webui: default to 25 entries rather than 10

### ISSUE THREAD

**Issue by simotek** [openSUSE/open-build-service#7734]
The new beta UI defaults to 10 items in a list where as the old one is 25, when working on larger packages like the kernel or rpm with over 100 files lists of 10 files is too small to work with practically, where as on a 1920x1080 screen 25 items will fit nicely without needing to scroll, similar for the list of packages in a project.

https://build.opensuse.org/package/show/Base:System/rpm

**Comment by dmarcoux** [comment]
Good point and this is easy to change.
