### ISSUE TITLE
"session/new" is not migrated to bootstrap

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#7739]
When a login fails and we are not under a proxy we end up into the 'session#new', which page was not migrated to bootstrap.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback (Sprint 60)](https://trello.com/c/h3HkOuTp/1171-address-feedback-sprint-60)

**Comment by DavidKang** [comment]
Addressed on PR #7782
