### ISSUE TITLE
Workers part of /monitor suboptimal

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7742]
I think the workers part of the monitor page deserves a little more love - the progress bars have rather dull colours and the font is too tiny to read (while it was enlarged everywhere else during bootstrap port).

And it doesn't take all available space and shows a rather strange '#' for non building workers. I was quite confused what it's about before I switched back to old webui to verify.

![screencapture-build-opensuse-org-monitor-2019-06-12-18_28_01](https://user-images.githubusercontent.com/1067203/59369336-83ca3000-8d40-11e9-82ea-f7bf25c2f343.png)
![screencapture-build-opensuse-org-monitor-2019-06-12-18_29_48](https://user-images.githubusercontent.com/1067203/59369339-8462c680-8d40-11e9-8228-fc2254e31c92.png)

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback (Sprint 60)](https://trello.com/c/h3HkOuTp/1171-address-feedback-sprint-60)

**Comment by dmarcoux** [comment]
Instead of always displaying 5 workers per row, we should use a [flex](https://getbootstrap.com/docs/4.3/utilities/flex/) container.
