### ISSUE TITLE
It should be forbidden to add relationships with nobody 

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7749]
Nobody doesn't do any good, so relationships need to be forbidden.

**Comment by saraycp** [comment]
@coolo, could you please give an example?

**Comment by coolo** [comment]
This should be impossible:
![](https://user-images.githubusercontent.com/1067203/59433298-82a10d80-8de9-11e9-9c12-f7eddf56ef18.png)

Nobody should have no relationship and no group membership (actually it shouldn't exist, but that's a too far stretched goal for now)

Relationship already validates:
```
validates :user, presence: {
```

But it needs to also validate that user is no nobody.
