### ISSUE TITLE
Request#show performance issue

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#7752]
Visiting a request with many individual diffs for files is very slow, so slow that the browser warns you about a slow running script.

**Comment by hennevogel** [comment]
After looking into performance my suspicion is that this problem is in the [function](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/assets/javascripts/webui2/packages.js#L17-L22) that refreshes the editors.

**Comment by hennevogel** [comment]
Guess I was wrong. Removing this whole function locally didn't change anything.

**Comment by coolo** [comment]
and the performance is worse than with bento? I didn't notice it

**Comment by coolo** [comment]
The numbers are obvious, the graphs only point out that bootstrap relayouts. I assume that's because it's responsive? 

bento:
![Screenshot_20190613_185505](https://user-images.githubusercontent.com/1067203/59451974-03253580-8e0d-11e9-8184-f990cc55f7ac.png)

bootstrap:
![Screenshot_20190613_185636](https://user-images.githubusercontent.com/1067203/59451981-07515300-8e0d-11e9-9941-3959d602af16.png)

**Comment by DavidKang** [comment]
@hennevogel, I guess is because of this [function](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/views/webui2/webui/request/show.html.haml#L96-L100)

**Comment by dmarcoux** [comment]
To reproduce this locally:

1. Branch the package `kernel-source` from Factory with the OBS interconnect, so `openSUSE.org:openSUSE:Factory`.
2. Submit a request to another project.
3. Go on the request#show page of this request
4. The page is slow

**Comment by dmarcoux** [comment]
[I found the culprit](https://github.com/openSUSE/open-build-service/blob/ed1d1e56b53065af0eb2f8d96ce9bc4698012df5/src/api/app/views/webui2/shared/_editor.html.haml#L56-L57)

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback (Sprint 60)](https://trello.com/c/h3HkOuTp/1171-address-feedback-sprint-60)
