### ISSUE TITLE
obs 2.5.3: setting KVM root and swap size via /etc/sysconfig/obs-server does not work

### ISSUE THREAD

**Issue by msrex** [openSUSE/open-build-service#776]
When you change the settings OBS_VM_DISK_AUTOSETUP_ROOT_FILESIZE in /etc/sysconfig/obs-server it has no impact.

It could be caused by the variable names being changed / different from the past - I noticed in some places the size was referred to as VMDISK_SWAPSIZE and VMDISK_ROOTSIZE. Setting these in /etc/sysconfig/obs-server did not work.

I was able to get it changed by editing the hard-coded default in /usr/lib/obs/server/build/build-vm.

**Comment by adrianschroeter** [comment]
this got fixed in master branch
