### ISSUE TITLE
[publisher]  with `repodata/app-icons.tar: Cannot detect compression type`

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#7774]
# Issue Description
When updating to the new createrepo_c from O:S:U/createrepo_c, the publisher runs into an error for example on SLE12:SP3 targets when they create a repodata/app-icons.tar. The old version of createrepo worked. Since OBS needs a patched createrepo_c, I report the error for OBS publisher and not for createrepo_c.

Expected Result
============
New createrepo_c, especially when its from O:S:U, should of course work for OBS.

How to Reproduce
===============
1. Build the new O:S:U/createrepo_c
2. Install in you OBS backend server
3. Restart publisher
4. Build a SLE target which produces a repodata/app-icons.tar file
5. Look into the publisher logfile

Further Information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)

**Comment by mlschroe** [comment]
Well, it's a createrepo_c bug with needs to be fixed in the upstream code base. I'll patch the createrepo_c in O:S:U in the meantime.

**Comment by mlschroe** [comment]
Frank, could you please push the `0004-createrepo_c_tar_comp.patch` patch to upstream?

**Comment by mmohring** [comment]
OK. Thank you. For a non insider its sometimes hard to detect if this was a bug in OBS or in one of the called pkgs.

**Comment by mmohring** [comment]
I have now installed this fixed createrepo_c. Works now. So I close this issue.
