### ISSUE TITLE
Single CodeMirror instances are too small

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#7799]
# Issue Description
Following the changes in #7790, all CodeMirror instances are rather small. This isn't an issue on a page which has multiple instances, such as the request overview page. However, for the package file page, which has a single CodeMirror instance, this is quite annoying.

Expected Result
============
I expect a file to be completely displayed in a CodeMirror instance when it's the only one on a page.

How to Reproduce
===============

1. Be part of the beta program
2. Go to a page which has only one CodeMirror instance (example: https://build.opensuse.org/package/view_file/openSUSE:Factory/helm-mirror/helm-mirror.spec?expand=1)
3. See small CodeMirror instance

Further Information
===============

Bento:
![Screenshot_2019-06-20 openSUSE Build Service](https://user-images.githubusercontent.com/1102934/59875551-55340100-93a1-11e9-841c-5f2599f3194e.png)

Bootstrap:
![bootstrap](https://user-images.githubusercontent.com/1102934/59875559-582ef180-93a1-11e9-8de1-506e0bfd6ced.png)

**Comment by dmarcoux** [comment]
This is also an issue on pages where multiple CodeMirror instances are present. However for pages which have multiple CodeMirror instances in read-only mode, like the request overview page (request#show), we shouldn't use CodeMirror to display diffs. We should use something like [diff2html](https://diff2html.xyz/).

**Comment by hellcp** [comment]
The reason for this is https://github.com/openSUSE/open-build-service/pull/7790/files#diff-43ba76d11ecad92709bacf239b9e8c92L4 however I can tell that this won't work well if you want a few instances of codemirror with scrolling. The easiest solution I can see is adding h-100 to every instance where the editor should be full-height

**Comment by dmarcoux** [comment]
> The reason for this is https://github.com/openSUSE/open-build-service/pull/7790/files#diff-43ba76d11ecad92709bacf239b9e8c92L4

Yep.

> The easiest solution I can see is adding h-100 to every instance where the editor should be full-height

This should work on pages which only have one instance. We could also apply `h-auto`.

**Comment by dmarcoux** [comment]
I tried both proposals on `package#view_file` view, which has one CodeMirror instance. Here's [one example](https://build.opensuse.org/package/view_file/home:dmarcoux/rustup.rs/rustup.rs.spec?expand=1).

This is how the CodeMirror instance is displayed based on the class we use (in addition to `CodeMirror` and `cm-s-bootstrap`):
- Current:
![Screenshot_2019-06-26 openSUSE Build Service](https://user-images.githubusercontent.com/1102934/60175347-a0239d80-9813-11e9-918a-e140b6cf227f.png)

- With `h-100`:
![Screenshot_2019-06-26 openSUSE Build Service(1)](https://user-images.githubusercontent.com/1102934/60175479-ff81ad80-9813-11e9-8bfd-7c38fa0cbbb0.png)

- With `h-auto`:
![Screenshot_2019-06-26 openSUSE Build Service(2)](https://user-images.githubusercontent.com/1102934/60175487-04466180-9814-11e9-9b30-1ae9cd6e7604.png)

As you can see, the bar with all the controls is in the middle of the CodeMirror instance, but this is only because of how the screenshot is taken. When you use the page, the bar moves up and down as you scroll, so it's not an issue. It seems like both proposals work. I would suggest using `h-auto` since this is what the [official documentation recommends](https://codemirror.net/demo/resize.html). We would do it in a different way since it causes issue as we saw in #7790. The result would still be the same, the CodeMirror instance would take the space it needs.
