### ISSUE TITLE
Missing packages for download

### ISSUE THREAD

**Issue by tumic0** [openSUSE/open-build-service#7804]
The "Download package" [link](https://software.opensuse.org//download.html?project=home%3Atumic%3AQtPBFImagePlugin&package=QtPBFImagePlugin) on my [QtPBFImagePlugin](https://build.opensuse.org/package/show/home:tumic:QtPBFImagePlugin/QtPBFImagePlugin) project leads to a page on software.opensuse.org that states, that there are no data for download. But all the packages were successfully built and are accessible using the build results links.

Note that on a sibling project of QtPBFImagePlugin - [GPXSee](https://build.opensuse.org/package/show/home:tumic:GPXSee/gpxsee) - the link works as expected.

**Comment by hennevogel** [comment]
If you have problem with software.o.o please report bugs there -> https://github.com/openSUSE/software-o-o/

HINT: software.o.o is about binary packages. Not OBS container packages names. 

https://software.opensuse.org//download.html?project=home%3Atumic%3AQtPBFImagePlugin&package=qt5-qtpbfimageformat

**Comment by tumic0** [comment]
According to what you say, the "link problem" is definitely in OBS, not in software.o.o. The link in OBS is simply wrong as it is "pointing" to a wrong destination. But there are evidently more bugs in OBS/OBS integration with software.o.o. - OBS does not properly work with projects that generate packages with different names for different distributions. The package you have pointed out is only for Fedora, but the OBS project generates also packages for other distros which do not exist on software.o.o. For example all the packages for OpenSUSE that are named "libqt5-qtpbfimageformat".

The missing packages at software.o.o might of course be the result of some software.o.o bug rather than OBS not passing them properly, but as the libqt5-qtpbfimageformat package is part of OpenSUSE (the project is a source project for OpenSUSE Factory) this might maybe deserve more attention than simply closing the issue without any real investigation...

**Comment by hennevogel** [comment]
I'm sure it will receive real investigation if you report it to the proper people. That are the people that take care of software.o.o
