### ISSUE TITLE
Repo has old packages

### ISSUE THREAD

**Issue by glixx** [openSUSE/open-build-service#7817]
Repository has old packages always. After rebuilding old packages do not replace by new ones if they have same file names. At least for Arch Linux, deb.

Workaround: increase rel tag. It changes file name.

**Comment by vpereira** [comment]
there is some delay between package build and package publishing, normally related with server load... if you wipe the binaries before rebuild it, does it get published faster?

**Comment by glixx** [comment]
Few days is delay?

If to delete binaries, they will be old again.

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support for a specific instance from us. If you have problems with build.opensuse.org please report them to admin@opensuse.org

Thank you for your consideration.

**Comment by adrianschroeter** [comment]
this is about the missing release number handling support for debian and archlinux. So it is a feature request.

**Comment by glixx** [comment]
Yes. RPM is ok.

**Comment by nickbroon** [comment]
Is this a duplicate of #834?

**Comment by hennevogel** [comment]
yeah it is, thanks
