### ISSUE TITLE
missing "show last build results" in ui

### ISSUE THREAD

**Issue by dirkmueller** [openSUSE/open-build-service#7819]
# Issue Description

Monitor project page in the "new Beta" ui is missing the "Last time results:" checkbox (or some equivalent). which makes it very much less useful. At least I'm not able to find it in the new UI.

The feature itself still seems to be there by adding &lastbuild=1

Expected Result
============

Some way in the new UI to show the last build results like the old UI provided via a checkbox.

Further Information
===============
* A link to an OBS instance showing the issue (tested in IBS)

**Comment by dmarcoux** [comment]
Just to be sure, are you referring to this checkbox?

![project-monitor](https://user-images.githubusercontent.com/1102934/60254910-16390a80-98cf-11e9-973a-2a8dd263c562.png)

**Comment by dirkmueller** [comment]
yeah, exactly.
