### ISSUE TITLE
Building for Xenial don't work on OBS

### ISSUE THREAD

**Issue by hawkeye116477** [openSUSE/open-build-service#7823]
# Issue Description
Welcome! Just like in title, building for Ubuntu 16.04 don't work on `build.opensuse.org`. After some time I only see message `400 remote error: http //archive.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.4.0-151.178_amd64.deb connect to archive.ubuntu.com 80 timeout (worker was lamb66:2)`.

Expected Result
============
No error, successful build :smile:.

Further Information
===============
* A link to an OBS instance showing the issue: https://build.opensuse.org/package/live_build_log/home:hawkeye116477:waterfox/waterfox/xUbuntu_16.04/x86_64

**Comment by lethliel** [comment]
@hawkeye116477 It is building now. It seems that there was a problem with the reachability of archive.ubuntu.com.
