### ISSUE TITLE
.spec file view in new UI does not use available space

### ISSUE THREAD

**Issue by toabctl** [openSUSE/open-build-service#7825]
# Issue Description

Using the new (beta) UI and looking at a .spec file (eg. https://build.opensuse.org/package/view_file/home:tbechtold:branches:devel:languages:python/python-Sphinx/python-Sphinx.spec?expand=1 ) shows that the vertical space is not used.
This is with Firefox 67.0 from openSUSE Tumbleweed.

See attached screenshot:

![obs-file-view](https://user-images.githubusercontent.com/276317/60329207-3086ed00-9990-11e9-97fa-cf2b2a22ee56.png)

Expected Result
============
I would expect that the vertical space is used which makes it simpler to read the file.

**Comment by dmarcoux** [comment]
Thank you @toabctl for reporting this. We already have an issue tracking this: #7799.
