### ISSUE TITLE
New tracker request: Generic GitHub issues

### ISSUE THREAD

**Issue by tux93** [openSUSE/open-build-service#7826]
According to older Versions of the [Packaging Patches guidelines](https://en.opensuse.org/index.php?title=openSUSE:Packaging_Patches_guidelines&oldid=132192#Current_set_of_abbreviations) page on the openSUSE wiki there used to be a generic tracker for GitHub Issues

It would be nice to get it back, possibly with the same syntax (gh#Org/Project#1234)

**Comment by adrianschroeter** [comment]
the support has been merge meanwhile.
