### ISSUE TITLE
OBS 2.10 beta no login at frontpage

### ISSUE THREAD

**Issue by mgoppold** [openSUSE/open-build-service#7829]
# Issue Description
there is no login at the front page after upgrade to 2.10 beta (openSUSE 15.1) 

hint: open a project and in the comment section there is "Login required, please login or signup in order to comment"

Expected Result
============
easier way to reach Signup / Login 

Further Information
===============
* basically I follow the instructions from [For Updaters from OBS 2.9 to OBS 2.10](https://github.com/openSUSE/open-build-service/blob/2.10/dist/README.UPDATERS)
* Note 1 ended with "rake aborted!" on the old (42.3) and new (15.1) System
 `rake aborted!
LoadError: cannot load such file -- single_test/tasks
/srv/www/obs/api/Rakefile:12:in '<top (required)>'`

**Comment by coolo** [comment]
So your UI doesn't look like https://build-test.opensuse.org/ ?

**Comment by mgoppold** [comment]
Unfortunately, no

![obs-2 10b-frontpage](https://user-images.githubusercontent.com/8797894/60416366-f0b54500-9bdd-11e9-972c-5a2f76d7d3b5.png)

There is nor Sign up / Login above the RSS

**Comment by coolo** [comment]
I see. Somehow the else got lost in

```
  - if User.session
    = render partial: 'layouts/webui2/logged_in_user_navigation'
  - elsif CONFIG['kerberos_mode']
    = link_to 'Log In', session_new_path
  - elsif CONFIG['proxy_auth_mode'] == :on && CONFIG['proxy_auth_register_page'].present?
    = render partial: 'layouts/webui2/login_form', locals: { signup_url: "#{CONFIG['proxy_auth_register_page']}?%22",
                                                             form_url: CONFIG['proxy_auth_login_page'],
                                                             options: { method: :post, enctype: 'application/x-www-form-urlencoded' },
                                                             proxy: true }
  - elsif can_register
    = render partial: 'layouts/webui2/login_form', locals: { signup_url: user_signup_path,
                                                             form_url: session_create_path,
                                                             options: { method: :post },
                                                             proxy: false }

**Comment by mgoppold** [comment]
I can't a difference to my /srv/www/obs/api/app/views/layouts/webui2/_personal_navigation.html.haml nor to master. 

What did you mean?

**Comment by mgoppold** [comment]
Ok, one cup of coffee later, i compare the old ui .../webui/_personal_navigation.html.haml with the new .../webui2/_personal_navigation.html.haml and see the missing else ...
