### ISSUE TITLE
OBS 2.10 beta build hang on signing (gpg: signing failed: Invalid IPC response)

### ISSUE THREAD

**Issue by mgoppold** [openSUSE/open-build-service#7836]
# Issue Description

#6233 is stil alive

Expected Result
============
publish obs-sign > eb16d4f with 2.10 beta

**Comment by adrianschroeter** [comment]
v2.5.3 is now released and copied to 2.10 staging.

**Comment by mgoppold** [comment]
Sorry, but this is not sufficient.  
There is an open pull request https://github.com/openSUSE/obs-sign/pull/19 that fixes this issue.

**Comment by mgoppold** [comment]
@adrianschroeter Did you notice my last comment? (unfortunately) I cannot reopen this issue.
