### ISSUE TITLE
[beta] webui; browser search no longer searches spec files.

### ISSUE THREAD

**Issue by simotek** [openSUSE/open-build-service#7837]
In the old UI you could use the browsers find functionality  to search through a spec file, this no longer works as the browser only finds the currently visible words.

To replicate:
1. Go to: https://build.opensuse.org/package/view_file/system:install:head/patterns-base/patterns-base.spec?expand=1
2. Use firefox's search to look for the string "base"
3. Notice you get around 4 results but none of the results around line 380 (and others) until you scroll down to that line.

**Comment by coolo** [comment]
Side effect of #7799

**Comment by hennevogel** [comment]
We'll track this in #7799
