### ISSUE TITLE
[beta] WebUI: editor is tiny

### ISSUE THREAD

**Issue by simotek** [openSUSE/open-build-service#7838]
The Editor in the obs webui is now tiny it can't even display the whole of a spec files license on a 1920x1280 screen. The editor should be atleast big enough vertically that you can scroll down and have it take up almost the entire screen

![tiny editor area](https://user-images.githubusercontent.com/3827011/60484123-6fda7400-9cd7-11e9-8d4b-d4d1e1ae98e7.png)

**Comment by coolo** [comment]
As I mentioned in the previous issue: dup of #7799
