### ISSUE TITLE
Project screen should allow easy detection of link vs no-link package

### ISSUE THREAD

**Issue by scarabeusiv** [openSUSE/open-build-service#786]
As per $SUBJ. There should be straight and obvious way to detect what packages are not links in my devel project.

Ie. for us it should be used to detect what packages still need to be submitted to Factory or identify ones that should not be in the devel project at all.

**Comment by hennevogel** [comment]
We could use labels.

![screenshot from 2015-01-14 16 01 03](https://cloud.githubusercontent.com/assets/514785/5740801/2ce37ac8-9c07-11e4-9ea9-2a897f9a6419.png)
