### ISSUE TITLE
Publish an archive with all the specs in the projects

### ISSUE THREAD

**Issue by hellcp** [openSUSE/open-build-service#7864]
**Is your feature request related to a problem? Please describe.**
Pinging API just to check something in the subset of specs turns out to be pretty annoying. 

**Describe the solution you'd like**
It would be nice to have an archive with all the specs used to create packages in a particular project, just like Fedora does it: https://src.fedoraproject.org/lookaside/rpm-specs-latest.tar.xz

**Comment by coolo** [comment]
that doesn't sound like a feature of the build service but rather an opensuse service
