### ISSUE TITLE
Wiping binaries from multibuild flavors redirects to wrong flavor

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7866]
Go to binaries list of Package:Flavor, wipe for one architecture and you'll get redirected to the binaries list of Package with a flash saying binaries for architecture X were wiped.

I almost got an heart attack seeing no binaries left - before I noticed it's the wrong package/flavor I'm looking at.

**Comment by hramrach** [comment]
Also reported as #7156
