### ISSUE TITLE
[typo] Typo on welcome page

### ISSUE THREAD

**Issue by letsfindaway** [openSUSE/open-build-service#7869]
# Issue Description
The start page https://build.opensuse.org has a minor typo:

> Users of any distribution can search **their** for built packages for their distribution.

Expected Result
============
> Users of any distribution can search **there** for built packages for their distribution.

How to Reproduce
===============
1. Go to https://build.opensuse.org
2. See error

Sorry, it's really a minor issue. But after discovering it I always stumple across it when opening this page ;-)

**Comment by DavidKang** [comment]
@letsfindaway, thanks :smiley:

**Comment by vpereira** [comment]
That's just in the reference server

**Comment by hennevogel** [comment]
changed. next time please report issues with build.opensuse.org to admin@opensuse.org
