### ISSUE TITLE
Please produce InRelease files for debian repositories

### ISSUE THREAD

**Issue by julian-klode** [openSUSE/open-build-service#7879]
# Issue Description
Debian repositories do not contain InRelease files (clearsigned Release) files, only detached Release.gpg signatures. We might want to drop support for those soon, and it's already annoying for users because it fetches InRelease first, fails, and falls back to fetching the other files (tons of round trips for no changes).

Expected Result
============
Debian repositories contain clearsigned InRelease files in addition or instead of Release and Release.gpg files.

**Comment by mlschroe** [comment]
Ok, we'll add support for InRelease. Thanks for the heads-up!

**Comment by mlschroe** [comment]
Fixed with commit c12e7c95589dd1cae5707e869ccc946fac2398ac
