### ISSUE TITLE
[production][repositories#create_flag] Validation failed: Flags Duplicated flags

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#7893]
repositories#create_flag threw this 6 times
<pre>
Validation failed: Flags Duplicated flags
</pre>

~[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d256e7a606b78000893973d)~

[See this exception on Errbit](https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/5d256e7a606b78000893973d)

**Comment by eduardoj** [comment]
This still occurs. Reopening.
