### ISSUE TITLE
ISO gen, pupet/vagarnt-box-gen as "Packages" 

### ISSUE THREAD

**Issue by necrose99** [openSUSE/open-build-service#792]
1) I have contributed Tm's (QT/Langs)  to upstream , however his rural German internet is flaky. (so he says) OBS-online project page likely simpler just since thier is no create iso 
2) if he'd use github over... SF.net....... or the OBS -online might save him a shit ton of workload..... 
let the OBS service push to Sf.net.... as well as Git...... 

update package SRC >>>> deb-pkg/s>>>  Mini Live CD packages in live-spec /rescue-live-spec> refresh/remaster Debian iso 
kick to SF.net  (basically his works like Acroinis but often faster and LZMA image out... ) 
RPM >>>> SF.net page.... 
however as a ISO package type  one could roll their own mini rescue disk clonezilla +  toys etc. (or Known Live CD maintainers to do easier IE knoppix to auto-regenerate etc and Better CI...) 
regen a demo for vbox quemu etc cloud hosting...... 
(still trying to wrap my head around CI despite having limited programing skills , from a sys-admin view  CI makes good sense.... (CI IE Travis/Jenkins ,  buldbot    OBS-integrations..https://github.com/Spike-Pentesting/App-witchcraft..) 

so I will need to use Other means...... 
In mycase   Just fire up the Spike-pentesting Linux distro in vagrant/Vbox 
Send commands to update cleanup convert to OVF.......... FTP publish-push 
Keep a public Demo-vbox up to date weekly....  however not sure if theirs a gentoo/sabayon kiwi spec. though obs runs quite fine on gentoo....

I'm new to obs , anyhow its a ****suggestion box enhancement ****
I was tinkering with OBS online didn't see option to regen an  ISO.... 
figured it worth a mention....

**Comment by hennevogel** [comment]
Creating ISO images is possible via [KIWI](https://en.opensuse.org/Portal:KIWI)
