### ISSUE TITLE
Monitoring Plot loose Timeframe mode on reload

### ISSUE THREAD

**Issue by frispete** [openSUSE/open-build-service#7928]
Reproduce:
/monitor: switch to 1 hour; reload page -> plots show 1 day mode, but Timeframe chooser shows 1 hour still.

Expected:
Keep the plots in the selected Timeframe mode.

**Comment by vpereira** [comment]
hi @frispete is that a duplicate of https://github.com/openSUSE/open-build-service/issues/4952 ?

**Comment by frispete** [comment]
> hi @frispete is that a duplicate of #4952 ?

Yes, sure. Damn, Ff.

Wouldn't `<form autocomplete="off">` fix that for Ff as well?

**Comment by hennevogel** [comment]
Duplicate of #4952 

please continue there..
