### ISSUE TITLE
New UI breaks project navigation

### ISSUE THREAD

**Issue by Kieltux** [openSUSE/open-build-service#7935]
# Issue Description
The new UI breaks the navigation in projects.

Expected Result
============
With the old UI you could navigate in projects with clicking on parts of project name (subprojects e.g.).

Old UI: Parts of the project is selectable to navigate in a project (here: switch to home:kieltux)

![obsOldUI_PartsOfthewholeProjectisSelectable](https://user-images.githubusercontent.com/6629537/61396184-71a35a80-a8c7-11e9-9e1a-12512d9e567b.jpg)

New UI: You could not navigate in a project. You can only select in this example
home:Kieltux:branches:devel:openSUSE:Factory. 

With the old UI you could go back to home:Kieltux
![obsNewUI_onlythewholeProjectisSelectable](https://user-images.githubusercontent.com/6629537/61396271-a3b4bc80-a8c7-11e9-8631-c96327cf4f45.jpg)

**Comment by vpereira** [comment]
AFAIR this not an error but an improvement. I think the old way of navigation didn't always worked as expected. I will look into that.

**Comment by mschnitzer** [comment]
I would also prefer if the old way gets implemented again. It allows to easily navigate between projects.
