### ISSUE TITLE
code editor window much too small to be useful

### ISSUE THREAD

**Issue by seife** [openSUSE/open-build-service#7936]
# Issue Description
The editor window, e.g. when editing a spec file in the web ui is not high enough to be useful. There is no handle to resize it.

Expected Result
============
The editor window using as much screen space as possible

How to Reproduce
===============
1. Go to https://build.opensuse.org/package/view_file/home:seife/tuxcursors/tuxcursors.spec?expand=1
2. Look at the screen.

![image](https://user-images.githubusercontent.com/2597362/61437199-c7feb080-a93c-11e9-923c-93eeb071eb42.png)

Further Information
===============

In my private instance, i hacked this into the spec file %install section to fix the issue:

```
# Link the assets without hash to make them accessible for third party tools like the pattern library
pushd $RPM_BUILD_ROOT/srv/www/obs/api/public/assets/webui2/
ln -sf application-*.js application.js
### seife start
NAME="`echo webui2-*.css`"
if [ $(grep -c ";height:300px;" "$NAME") != 1 ]; then
        echo "ERROR: cannot patch webui2.css"
        exit 1
fi
sed -i -e 's/;height:300px;/;height:auto;/' "$NAME"
gzip -c "$NAME" > "$NAME".gz
### seife end
ln -sf webui2-*.css webui2.css
popd
```

Result:

![image](https://user-images.githubusercontent.com/2597362/61437452-67bc3e80-a93d-11e9-9f20-5cb8f755622d.png)

A proper soluion would probably require to patch the CodeMirror gem, and I did not know how to do that with the bundle_gem service...

**Comment by DavidKang** [comment]
Thanks for reporting the issue.
Duplicated #7799
