### ISSUE TITLE
_pattern from stone age (wrong changed date displayed in package list)

### ISSUE THREAD

**Issue by cboltz** [openSUSE/open-build-service#7950]
# Issue Description

https://build.opensuse.org/project/show/KDE:KDE3 (sort by "changed", oldest first) shows that `_pattern` was last changed `over 49 years ago`

I know that OBS exists for quite a while, but I still doubt that it (and the KDE3 _pattern) already existed when the first humans landed on the moon ;-)

![kde3-pattern](https://user-images.githubusercontent.com/146882/61589227-4199d700-aba7-11e9-9554-b2b2ca16eebe.png)

Expected Result
============

A more correct date, probably `almost 5 years ago` as shown on https://build.opensuse.org/package/show/KDE:KDE3/_pattern

How to Reproduce
===============
1. Go to https://build.opensuse.org/project/show/KDE:KDE3
2. Click on "changed" to sort by change date, oldest first
3. Read the change date for `_pattern`

**Comment by Ana06** [comment]
@cboltz 

> I know that OBS exists for quite a while, but I still doubt that it (and the KDE3 _pattern) already existed when the first humans landed on the moon ;-)

:rofl:

**Comment by hennevogel** [comment]
Please do not attach priority labels by yourself. This is the work of you PO :-)

**Comment by vpereira** [comment]
The issue isn't even bootstrap related.

![Screenshot_2019-07-22_12-48-58](https://user-images.githubusercontent.com/37418/61627066-2bf7e080-ac7f-11e9-8159-4e6cc97ff417.png)

@Ana06 to try it locally is easier. In the development environment you can leave the beta project, then you can `osc copypac` the package and locally check if it's bootstrap or not. If yon need any help to setup your development environment, feel free to drop us a message in the irc or mailing list.

**Comment by vpereira** [comment]
That's not an issue in the code. The issue is that this package was never updated, therefore the `Updated_at` is nil. To reproduce it add a package locally, set the field `updated_at` to nil, reload the page and you will have it. Wondering if it's that a fallback from Datatables 

![Screenshot_2019-07-22_13-18-06](https://user-images.githubusercontent.com/37418/61628754-79764c80-ac83-11e9-8866-ed817a0f5382.png)

**Comment by vpereira** [comment]
```
$ rails c
irb(main):009:0> include  ActionView::Helpers::DateHelper
=> Object
irb(main):011:0> time_ago_in_words(0)
=> "over 49 years"
```

**Comment by vpereira** [comment]
That happens just with `_pattern` projects:

In production:

```
Package.where(updated_at: nil).pluck(:title)
```
```
["Patterns", "Patterns", "Patterns", "Patterns", "Patterns", "Patterns", "Patterns", "Patterns", "Patterns", "Patterns", "Patterns", "Patterns", "Patterns", "Patterns", "Patterns"]
```

If I'm not wrong we are not allowed to create `_pattern` packages through the webui but just through the API.. do you think that we are missing something in the API @adrianschroeter ?

**Comment by vpereira** [comment]
As talked with @adrianschroeter the issue is that the packages were manually imported. No bug.
