### ISSUE TITLE
Binary information is wrong

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#7951]
According to OBS, `ruby-build-20190401-lp151.1.1.src.rpm` requires and provides nothing (https://build.opensuse.org/package/binary/devel:languages:ruby:extensions/ruby-build/openSUSE_Leap_15.1/x86_64/ruby-build-20190401-lp151.1.1.src.rpm):

 
![image](https://user-images.githubusercontent.com/16052290/61595650-0d9bd180-abfa-11e9-8ea2-a45363924399.png)

But this is not true:

```
ana@localhost:~/github> rpm -qf $(which ruby-build) 
ruby-build-20190401-lp151.1.1.noarch
ana@localhost:~/github> rpm -q --requires ruby-build
/usr/bin/env
automake
bash
bison
curl
gcc
gdbm-devel
gperf
graphviz
libffi-devel
libjpeg-devel
openssl-devel
readline-devel
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
tk-devel
ana@localhost:~/github> rpm -q --provides ruby-build
ruby-build = 20190401-lp151.1.1

```

The information in the binary page is wrong. :sob:

**Comment by Ana06** [comment]
Not sure if this is related with the Bootstrap migration as I can't leave the beta anymore

**Comment by coolo** [comment]
your url points to the src.rpm which indeed does not require or provide anything. So don't compare it with the noarch.rpm

**Comment by coolo** [comment]
https://build.opensuse.org/package/binary/devel:languages:ruby:extensions/ruby-build/openSUSE_Leap_15.1/x86_64/ruby-build-20190401-lp151.1.1.noarch.rpm is the url for the noarch rpm you checked

**Comment by Ana06** [comment]
:see_no_evil:
