### ISSUE TITLE
[API] Creating submit request with multiple packages fails when at least one is unchanged

### ISSUE THREAD

**Issue by lethliel** [openSUSE/open-build-service#7964]
# Issue Description
Creating a submit request using the api on project level fails when one of the packages
does not contain a change.

API URL used: `POST /request?cmd=create&addrevision=1`

Expected Result
============
The not changed package should be just skipped and the submit request should be created.
Regarding to @adrianschroeter this should be the case right now. 

How to Reproduce
===============
1. osc branch openSUSE:Tools osc
2. osc branch openSUSE:Tools build
3. osc co <branch>
4. Make a change in *one* of the packages
5. osc sr on prj dir

Further Information
===============
Issue in osc github repo: https://github.com/openSUSE/osc/issues/605
We will let the user know that he needs to drop the unchanged packages from the branch with this PR: https://github.com/openSUSE/osc/pull/611

**Comment by lethliel** [comment]
This is the xml that gets submitted: 

```
<request> 
    <action type="submit"> 
        <source project="home:mstrigl:branches:openSUSE:Tools" package="build" /> 
        <target project="openSUSE:Tools" package="build" /> 
        <options></options> 
    </action>
    <action type="submit"> 
        <source project="home:mstrigl:branches:openSUSE:Tools" package="osc" />
        <target project="openSUSE:Tools" package="osc" /> 
        <options></options> 
    </action> 
    <state name="new"/> 
    <description></description> 
</request>
```

**Comment by adrianschroeter** [comment]
erm, the skipping of not modified packages might only happen when you submit an entire project and let the api expand. Can you verify that it happens then also?

**Comment by adrianschroeter** [comment]
`<request> 
    <action type="submit"> 
        <source project="home:mstrigl:branches:openSUSE:Tools" package="build" /> 
        <target project="openSUSE:Tools"/> 
    </action> 
    <state name="new"/> 
    <description></description> 
</request>`

**Comment by adrianschroeter** [comment]
btw, sending empty <options> might work, but makes not really sense ....

**Comment by lethliel** [comment]
will try the submitting of the entire project

**Comment by lethliel** [comment]
It works. osc side needs to be changed. This can be closed.

**Comment by lethliel** [comment]
Mhh. In former times 
`/source/home:mstrigl:branches:openSUSE:Tools/build` for example had no entry element.

In osc we check if a package has entry elements to see if something has changed. (This is a pretty ugly hack, but needed as we decide the target_project per package)

**Comment by hennevogel** [comment]
You can have all situations:

`_link` file and unchanged files (default for branching): 

```xml
<directory name="marco" rev="1" vrev="1" srcmd5="358ad3a1e9109ed5b235ecced3ef9d9e">
  <linkinfo project="home:hennevogel:yadda" package="marco" srcmd5="ff7eada703a91966b2e39360e30e771d" baserev="ff7eada703a91966b2e39360e30e771d" xsrcmd5="2c843feb1c3068fc3cbb1e29b7f99a65" lsrcmd5="358ad3a1e9109ed5b235ecced3ef9d9e" />
  <entry name="_link" md5="463cf400d6e4fd3405cf23d502f0759b" size="129" mtime="1563968015" />
  <entry name="tenor.gif" md5="d7291d1c581af711eb83d07ba56b8cc2" size="33212" mtime="1563967964" />
</directory>
```

`_link_` file and changed files:

 ```xml
<directory name="marco-link-with-files" rev="2" vrev="2" srcmd5="95e79d5a79f2680255d4d8fb97d74faa">
  <linkinfo project="home:hennevogel:yadda" package="marco"   srcmd5="ff7eada703a91966b2e39360e30e771d" baserev="ff7eada703a91966b2e39360e30e771d"   xsrcmd5="0bc538d6dcbf018590cb645005ee9e47" lsrcmd5="95e79d5a79f2680255d4d8fb97d74faa" />
  <entry name="_link" md5="818125b707065b039839170a04fd1895" size="131" mtime="1563968244" />
  <entry name="tenor.gif" md5="6f5902ac237024bdd0c176cb93063dc4" size="12" mtime="1563968244" />
</directory>
```

Only a `_link` file (default for linkpac):

```xml
<directory name="marco-link" rev="1" vrev="1" srcmd5="463a2083cbad124881faf22f29bb52fc">
  <linkinfo project="home:hennevogel:yadda" package="marco" srcmd5="ff7eada703a91966b2e39360e30e771d" xsrcmd5="e6ff8af22a7bf50982663e55b32e2eab" lsrcmd5="463a2083cbad124881faf22f29bb52fc" />
  <entry name="_link" md5="1073406ace3a60021fa7a3113e0c1094" size="453" mtime="1563968106" />
</directory>
```

**Comment by lethliel** [comment]
@hennevogel Yes. So the code in osc makes only sense for linkpac...
I will look into the osc code tomorrow. I think we can simplify the code there quite a lot.

**Comment by lethliel** [comment]
Ok. This needs to be fixed in osc. This can definitively be closed.
