### ISSUE TITLE
Changelog checker reports bogus out-of-sequence changelog entries

### ISSUE THREAD

**Issue by shundhammer** [openSUSE/open-build-service#7973]
## Problem

Submit request get denied by a bot that claims the changelog not to be in sequence.

## Example

https://build.opensuse.org/request/show/718127#request_history

Change log:

```change log
-------------------------------------------------------------------
Mon 22. Jul 15:20:45 CEST 2019 - shundhammer@suse.de

- Update to V1.6:
  - Packages view
  - Unpackaged files view
  - Performance improvements
  - Bug fixes

-------------------------------------------------------------------
Wed Nov  7 21:32:14 CET 2018 - shundhammer@suse.de

- Update to V1.5:
  - Breadcrumbs navigation
  - File details panel
  - Package manager support for rpm, dpkg, pacman
  - Switchable different main window layouts
  ```

# Possible Cause

We experimented with this some time ago and found that this check script does not parse timestamps with different time zones correctly. It seems to be confused with CET vs. CEST. The only thing that appears to work reliably seems to be UTC timestamps.

# Problem History

I reported this problem personally during the hack week of 2018, and **nothing whatsoever happened inbetween**.

This problem sabotages my work. Until this is fixed, I am not going to resubmit my QDirStat Open Source project to Factory again. Let it remain an embarrassment that Debian, Ubuntu, Fedora and whatnot manage to have the latest version while openSUSE will remain at an outdated version:

QDirStat Versions in Distros: [![Packaging Status](https://repology.org/badge/tiny-repos/qdirstat.svg)](https://repology.org/metapackage/qdirstat/versions)

**Comment by coolo** [comment]
The problem is not the timezone, but your strange formatting of the date. "22. Jul" is possibly german formatting, but we expect "Mon Jul 22".

**Comment by coolo** [comment]
https://build.opensuse.org/request/show/718435 - dann klappt's auch mit dem Nachbarn

**Comment by shundhammer** [comment]
Thanks, Coolo!
