### ISSUE TITLE
bs_service: cannot write to rundir '/srv/obs/run'

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/open-build-service#7984]
After installing obs from http://download.opensuse.org/repositories/OBS:/Server:/2.10/openSUSE_15.1/ the service obsservice could not be started. 

Expected Result
============
The service should start instead

How to Reproduce
===============
1. open ssh shell to obs server
2. run as root
`rcobsservice start`
3. run 
```
rcobsservice status

● obsservice.service - OBS source service server
   Loaded: loaded (/usr/lib/systemd/system/obsservice.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2019-07-29 12:24:50 CEST; 1h 7min ago
 Main PID: 2671 (code=exited, status=13)

Jul 29 12:24:50 lxserver29 systemd[1]: Started OBS source service server.
Jul 29 12:24:50 lxserver29 systemd[1]: obsservice.service: Main process exited, code=exited, status=13/n/a
Jul 29 12:24:50 lxserver29 systemd[1]: obsservice.service: Unit entered failed state.
Jul 29 12:24:50 lxserver29 systemd[1]: obsservice.service: Failed with result 'exit-code'.
```
Running the related service by hand with 

` /usr/lib/obs/server/bs_service --logfile src_service.log`

returns the message

`cannot write to rundir '/srv/obs/run'`

Further Information
===============
Changing  the following lines in  /usr/lib/obs/server/BSStdServer.pm
from 
```
   mkdir_p($rundir);
-  die("cannot write to rundir '$rundir'\n") unless POSIX::access($rundir, POSIX::W_OK);
```
to
```
   mkdir_p($rundir);
+  my $login = getpwuid($<);
+  die("cannot write to rundir '$rundir' as user '$login'\n") unless POSIX::access($rundir, POSIX::W_OK);
```
returns 

`cannot write to rundir '/srv/obs/run' as user 'obsservicerun`

The reason is that /srv/obs/run does not have required access rights for user 'obsservicerun'
```
ls /srv/obs -al | grep run 
drwxr-xr-x  2 obsrun        obsrun  4096 Jul 29 13:36 run
```
* Exact server version (in case a private instance is used)
obs-api-2.10-lp151.10.1.noarch
obs-service-download_url-0.1.1-lp151.2.1.noarch
obs-bundled-gems-2.10-lp151.10.1.x86_64
obs-service-verify_file-0.1.1-lp151.2.1.noarch
obs-common-2.10-lp151.10.1.noarch
obs-api-deps-2.10-lp151.10.1.x86_64
obs-worker-2.10-lp151.10.1.noarch
obs-signd-2.5.3-lp151.2.1.x86_64
obs-server-2.10-lp151.10.1.noarch

**Comment by M0ses** [comment]
did you run obsstoragesetup?

**Comment by rhabacker** [comment]
The service for obsstoragesetup has been enabled and started by setup-appliance.sh
```
 rcobsstoragesetup status
● obsstoragesetup.service - OBS storage setup
   Loaded: loaded (/usr/lib/systemd/system/obsstoragesetup.service; enabled; vendor preset: disabled)
   Active: active (exited) since Mon 2019-07-29 12:24:50 CEST; 1 day 2h ago
 Main PID: 2640 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/obsstoragesetup.service

Jul 29 12:24:49 xxx systemd[1]: Starting OBS storage setup...
Jul 29 12:24:50 xxx obsstoragesetup[2640]: OBS Storage Autosetup is not enabled in sysconfig, skipping!
Jul 29 12:24:50 lxserver29 systemd[1]: Started OBS storage setup.
```
and running by hand returns:
```
xxx:/srv/obs/log # obsstoragesetup
OBS Storage Autosetup is not enabled in sysconfig, skipping!
```

**Comment by rhabacker** [comment]
In /etc/sysconfig/obs-server there is an indication that this service is only required in specific situations:
```
## Path:        Applications/OBS
## Description: Enable storage auto configuration
## Type:        ("yes" | "")
## Default:     ""
## Config:      OBS
#
# WARNING: this may destroy data on your hard disk !
# This is usually only used on mass deployed worker instances
#
OBS_STORAGE_AUTOSETUP=""
```

**Comment by M0ses** [comment]
I fully agree - being dependent on obsstoragesetup to run obsservice is not an good idea.
I guess the original idea was to be able to change OBS_BASE_DIR
