### ISSUE TITLE
setup-appliance.sh fail to find systemd services

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/open-build-service#7995]
Running setup-appliance.sh from an OBS 2.10 installation on openSUSE 15.1 shows several error messages like
```
obsdodup: unknown service
```
The reason is that setup-appliance.sh uses `chkconfig` to determine the state of recommended and optional services, which fails for systemd services like obsdodup.

Additional informations
* Exact server version (in case a private instance is used)
obs-api-2.10-lp151.10.1.noarch
obs-service-download_url-0.1.1-lp151.2.1.noarch
obs-bundled-gems-2.10-lp151.10.1.x86_64
obs-service-verify_file-0.1.1-lp151.2.1.noarch
obs-common-2.10-lp151.10.1.noarch
obs-api-deps-2.10-lp151.10.1.x86_64
obs-worker-2.10-lp151.10.1.noarch
obs-signd-2.5.3-lp151.2.1.x86_64
obs-server-2.10-lp151.10.1.noarch

**Comment by rhabacker** [comment]
This issue was fixed by the commits 94023b0 and a90c85f.

**Comment by hennevogel** [comment]
Thanks @rhabacker :bouquet:
