### ISSUE TITLE
Counter for Package Revisions

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#8001]
Context:

![revisions](https://user-images.githubusercontent.com/1102934/62201395-a0b9d180-b387-11e9-9c8a-deee7ccd6254.png)

**Is your feature request related to a problem? Please describe.**

As you can see in the screenshot above, we display a counter as `(123)`. This is not consistent with other counters throughout the interface. 

**Describe the solution you'd like**

It should be like this:
![counter](https://user-images.githubusercontent.com/1102934/62201413-a8797600-b387-11e9-9373-ef0fcc33286b.png)

**Describe alternatives you've considered**
Nothing, it's already something we've solved for other pages.

**Comment by coolo** [comment]
Just a warning: please don't get carried away adding it to the tab. Calculating the number of revisions is super expensive - at least if you don't add a new API into the backend.

**Comment by dmarcoux** [comment]
My idea is to change the `(123)` in the page to use the counter. Your comment made me realize that I wasn't clear on this. So the counter is **NOT** to be in the tab.

**Comment by vpereira** [comment]
@dmarcoux AFAIK we just use the `bootstrap` tag if the issue was introduced by bootstrap, which I think it wasn't the case. What do you think?

**Comment by dmarcoux** [comment]
You are right. It's my old habit from having to juggle between the old and new UIs. Now that the Bootstrap UI is the default one, we don't really need the Bootstrap label I guess.

**Comment by vpereira** [comment]
It is good to track it to see if the bug was introduced by bootstrap. Then we track it to the "Address issues" in trello.. otherwise it's just a regular bug
