### ISSUE TITLE
How to add cross site navbar for build.o.o

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/open-build-service#8003]
Hi, I have made a [Bootstrap 4 based theme](https://github.com/openSUSE/opensuse-theme-chameleon) for openSUSE websites. It has been used in wikis. Now I am adding this theme to more other sites. Is here a way to add the theme and a cross site navbar to build.opensuse.org ? Thanks!

**Comment by hennevogel** [comment]
The openSUSE instance is just one of many OBS instances. We don't have any theming capabilities in the way we've set up our frontend for now. This would be the prerequisite for theming the openSUSE instance in any special way. There is the issue #6311 about this.
