### ISSUE TITLE
kiwi image build: missing "recommends" is a fatal error

### ISSUE THREAD

**Issue by seife** [openSUSE/open-build-service#8008]
# Issue Description

Building a kiwi image, I get the following (from osc buildinfo -d. private obs instance)

```
  <error>unresolvable: nothing provides libwebkit2gtk3 = 2.20.3 needed by libwebkit2gtk3-lang</error>
...
added libwebkit2gtk3-lang@SLES12-SP4/standard because of libwebkit2gtk-4_0-37:libwebkit2gtk3-lang
```

Now this is an issue that could be solved by adding the SLED repos (which contain the -lang package, SLES only contains the library package)
But libwebkit2gtk only recommends the -lang package, so this should IMVHO not be a fatal error:

```
# rpm -qp --recommends /srv/www/htdocs/repo/SUSE/Products/SLE-SERVER/12-SP4/x86_64/product/x86_64/libwebkit2gtk-4_0-37-2.20.3-2.23.8.x86_64.rpm
libwebkit2gtk3-lang
```

Expected Result
============
The image builds, even if packages that are only recommended are not available on any repository

**Comment by seife** [comment]
Reproducer: https://build.opensuse.org/package/show/home:seife:kiwitest/SLES_12SP4_liveiso1

**Comment by mlschroe** [comment]
No, it has to be fatal. We want reproducible builds.

**Comment by mlschroe** [comment]
Also note that the `-lang` package is there, the library package is missing...

**Comment by seife** [comment]
No, there is an old -lang package in GA/SLED, the matching library pacakge would be in UPDATE/SLED. But update/SLED is not in the Image (on purpose, as no SLED content is really wanted).

A useful OBS setup is:
* symlink all available modules from your SMT repo share together into $SLES_VERSION/standard, so that they do not need additional disk spakce
* add :Update repos as dod repos

This easily triggers the error I showed with the "strange" config in the reproducer image.

There are more possible useful build service setups than what you are running on build.o.o.

**Comment by mlschroe** [comment]
If you don't want SLED content, why do you use that GA/SLED repo? I don't think it makes sense to have GA packages without update packages.

**Comment by seife** [comment]
See my previous comment about a symlinked "all things together GA" repo in order to save complexity/space.

**Comment by mlschroe** [comment]
Yes, I read that. But I think this is only sane if you also use all update repos. You really don't want that old packages with missing security updates go into the image.
