### ISSUE TITLE
regression in deleterequest --accept-in-hours

### ISSUE THREAD

**Issue by olafhering** [openSUSE/open-build-service#8010]
This command used to work, now it reports this error in two independent instances:

````
prj/pkg $  osc dr --accept-in-hours=1 -m 'some message'
Server returned an error: HTTP Error 400: Bad Request
Auto accept time is in the past
````

Fails also with value `two`, works with value `three`.

**Comment by dmarcoux** [comment]
I believe this should be reported in [osc](https://github.com/openSUSE/osc).

**Comment by hennevogel** [comment]
Please report osc bugs to the osc developers -> https://github.com/openSUSE/osc
