### ISSUE TITLE
Viewing spec files through a letterbox is not good

### ISSUE THREAD

**Issue by moozaad** [openSUSE/open-build-service#8018]
# Issue Description
Viewing spec files is difficult when it is limited to 300px. On a 1080p monitor that is 1/3 of the usable screen space.
On a 1440p monitor it's the difference between seeing 15 lines vs 65 lines at a time.

Expected Result
============
The data you want to see should fill the screen as much as possible.

How to Reproduce
===============
1. Go to https://build.opensuse.org/package/view_file/shells/zsh/zsh.spec?expand=1
2. Realise viewing only 15 lines at a time is a bad idea ;)

Further Information
===============
Can be overridden by removing this style.
.CodeMirror {
    height: 300px;
}

**Comment by DavidKang** [comment]
@moozaad, thanks for reporting the issue :smile_cat:
