### ISSUE TITLE
[Arch Linux] Inconsistent with mirror

### ISSUE THREAD

**Issue by hawkeye116477** [openSUSE/open-build-service#8026]
# Issue Description
Welcome! When I push new version on OBS and it's published, then when I want to install package, then it shows me old version (I did synchronization with pacman) and I can't also redownload old version. That's because it looks for version in mirror, then it tries to download it from `download.opensuse.org`, but that version got replaced by new, so it can't download.

Expected Result
============
I can fix that by replacing Server with `https://downloadcontent.opensuse.org`, but would be good if this will work also with `https://download.opensuse.org`, so it should download new version directly from `https://downloadcontent.opensuse.org` if mirror hadn't new version or it should download old version from mirror

Further Information
===============
* A link to an OBS instance showing the issue `https://build.opensuse.org/package/show/home:hawkeye116477:waterfox/waterfox-alpha-kde`

**Comment by hennevogel** [comment]
If you have problems with the download infrastructure please contact the openSUSE admins -> admin@opensuse.org
