### ISSUE TITLE
the contribution graph is gone in OBS

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#8027]
Where is the contribution graph in OBS? :angry: :sob: :sob: :rage:  Why has been it removed without any information/notice? It was announced in Twitter: https://twitter.com/obshq/status/1131488246117163008 and although I saw a PR to give the chance to disable it, I haven't seen any reason why this has been done. Every feedback I'd heard about this feature was really positive. I would appreciate an explanation.

**Comment by hennevogel** [comment]
We have put it behind an OPS switch in #7940 and it got disabled on build.o.o because of privacy concerns which SUSE has to evaluate.
