### ISSUE TITLE
email in OBS is @please-enter-an-email-address 

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#8028]
I think that `ammartinez@please-enter-an-email-address` is not my email :rofl: 
![image](https://user-images.githubusercontent.com/16052290/62426290-24a2ef00-b6e3-11e9-8968-6763b1ee28e2.png)

I think this is related to https://secure-www.novell.com/selfreg/jsp/protected/manageAccount.jsp being down, but OBS should handle this in a better way (don't show any email would be better than `ammartinez@please-enter-an-email-address`)

**Comment by hennevogel** [comment]
> I think that ammartinez@please-enter-an-email-address is not my email rofl

It is now after the system automatically removed your suse.com address. You have to change it at that URL.

**Comment by Ana06** [comment]
I had already changed it

**Comment by hennevogel** [comment]
Might be, I'm not super familiar with that process. Just change it again, log in again and it will change.
