### ISSUE TITLE
Internal error (500) when accepting a deletion request

### ISSUE THREAD

**Issue by krig** [openSUSE/open-build-service#803]
I got the automated email to delete an unused project after a certain time, and when I went to the page for the request and clicked accept, I got a 500 response telling me to look for this issue on github. Didn't find it, so now I am making a new issue. :)

The request in question is 256772.

The email was sent Wed, 15 Oct 2014 19:40:55 +0200

Text from email:

Actions:
- delete project home:KGronlund:branches:home:ikeydoherty

To REVIEW against the previous version:
   osc request show --diff 256772

To ACCEPT the request:
   osc request accept 256772 --message="reviewed ok."

To DECLINE the request:
   osc request decline 256772 --message="declined for reason xyz (see ... for background / policy / ...)."

To REVOKE the request:
   osc request revoke 256772 --message="retracted because ..., sorry / thx / see better version ..."

**Comment by hennevogel** [comment]
Thanks for the report. This was a problem with the search indexing.
