### ISSUE TITLE
cannot build LUKS-encrypted images with kiwi

### ISSUE THREAD

**Issue by aspiers** [openSUSE/open-build-service#8046]
# Issue Description

It is currently impossible to build a LUKS-encrypted image via kiwi inside OBS.

https://osinside.github.io/kiwi/working_with_kiwi/xml_description.html#common-attributes-of-the-type-element says of the `<type>` element:

> `luks`: Supplying a value will trigger the encryption of the partitions using the LUKS extension and using the provided string as the password. Note that the password must be entered when booting the appliance!

and IIUC image building via kiwi is fully supported by OBS, in which case in theory this should be possible.

However it seems that the default `kernel-obs-build` kernel used by OBS workers is missing some crypto kernel module which `cryptsetup` needs in order to be able to encrypt the image.

Expected Result
============

OBS kiwi successfully builds a LUKs-encrypted image when the `.kiwi` file contains `<type ... luks="password" ...>`.

How to Reproduce
===============
1. Set up a package to build kiwi images, e.g. via https://build.opensuse.org/image_templates
2. Add the `luks` attribute to the `<type>` element
3. Add `Support: cryptsetup` to the `prjconf` to ensure it's present in the build environment.
4. Watch the build fail with something like

```
[  172s] [ INFO    ]: 19:02:06 | --> Creating LUKS map
[  172s] [ DEBUG   ]: 19:02:06 | EXEC: [cryptsetup -q --key-file /tmp/tmp9b0nflsp luksFormat /dev/mapper/loop0p3]
[  172s] [  160.217506] device-mapper: table: 254:3: crypt: unknown target type
[  172s] [ DEBUG   ]: 19:02:06 | EXEC: Failed with stderr: device-mapper: reload ioctl on   failed: Invalid argument
[  172s] Failed to setup dm-crypt key mapping for device /dev/mapper/loop0p3.
[  172s] Check that kernel supports aes-xts-plain64 cipher (check syslog for more info).
[  172s] , stdout: (no output on stdout)
[  172s] [ ERROR   ]: 19:02:06 | KiwiCommandError: cryptsetup: stderr: device-mapper: reload ioctl on   failed: Invalid argument
[  172s] Failed to setup dm-crypt key mapping for device /dev/mapper/loop0p3.
[  172s] Check that kernel supports aes-xts-plain64 cipher (check syslog for more info).
```

Further Information
===============
* Example failure: https://build.opensuse.org/package/live_build_log/home:aspiers:branches:SUSE:Templates:Images:SLE-15/kiwi-templates-SLES15-JeOS-Apache:OpenStack-Cloud/images/x86_64

**Comment by aspiers** [comment]
OK thanks to tips from @dirkmueller I managed to get past this kernel module problem - turns out it needed `dm-crypt`. Not sure whether it was necessary to add `aes-x86_64` or `aesni_intel` but I've kept them in for now:

- https://build.opensuse.org/package/rdiff/home:aspiers:branches:Kernel:stable/kernel-obs-build?opackage=kernel-obs-build&oproject=Kernel%3Astable&rev=5

However now it's failing later on with

```
[  154s] [ DEBUG   ]: 08:41:25 | EXEC: [chroot /tmp/kiwi_mount_manager.xezgg2pw grub2-install --skip-fs-probe --directory /usr/lib/grub2/i386-pc --boot-dire
[  155s] [ DEBUG   ]: 08:41:25 | EXEC: Failed with stderr: Installing for i386-pc platform.
[  155s] grub2-install: error: attempt to install to encrypted disk without cryptodisk enabled. Set `GRUB_ENABLE_CRYPTODISK=y' in file `/etc/default/grub'.
[  155s] , stdout: (no output on stdout)
[  155s] [ ERROR   ]: 08:41:25 | KiwiCommandError: chroot: stderr: Installing for i386-pc platform.
[  155s] grub2-install: error: attempt to install to encrypted disk without cryptodisk enabled. Set `GRUB_ENABLE_CRYPTODISK=y' in file `/etc/default/grub'.
[  155s] , stdout: (no output on stdout)
```

**Comment by aspiers** [comment]
Added this to `config.sh` and it worked!

```
# Enable encrypted disk
echo "GRUB_ENABLE_CRYPTODISK=y" >>/etc/default/grub
```

So I guess the only remaining task is to submit the `kernel-obs-build` tweak to the kernel team.

**Comment by aspiers** [comment]
Just booted a VM using the image and it works great (although you have to input the encryption key twice, once at grub and once during boot up - is that expected?)

**Comment by aspiers** [comment]
Just confirmed that it was not necessary to add `aes-x86_64` or `aesni_intel` to `kernel-obs-build` - I have removed them and it still built fine.

**Comment by aspiers** [comment]
Also confirmed that it's not necessary to have `cryptsetup` in the `.spec` file's `Requires` or `BuildRequires`, or in any of the `.kiwi` file's `<packages>` sections.

**Comment by hennevogel** [comment]
So is there anything that isn't working? :-)

**Comment by aspiers** [comment]
Yes:

1. kernel-obs-build is broken. Fix submitted: http://kerncvs.suse.de/gitweb/?p=kernel-source.git;a=commit;h=1756301c1b54e19dd8c61a26e0f2660b2e3e1f16
2. Documentation didn't mention required grub tweak. Fix submitted: https://github.com/OSInside/kiwi/pull/1162

**Comment by eduardoj** [comment]
Hi @aspiers. It seems https://build.opensuse.org/package/live_build_log/home:aspiers:branches:SUSE:Templates:Images:SLE-15/kiwi-templates-SLES15-JeOS-Apache:OpenStack-Cloud/images/x86_64 builds successfully. Can we close this issue then?

**Comment by aspiers** [comment]
Yeah I think so.
