### ISSUE TITLE
webUI submit request has misleading button text

### ISSUE THREAD

**Issue by olafhering** [openSUSE/open-build-service#806]
https://build.opensuse.org/request/show/256710

This autosubmit above gave me three buttons: "Accept review", "Decline review" and the usual "Add comment".

Its all but clear that "Decline review" actually means I'm able to decline the whole thing. Instead it suggests what it has something to do with the review process. So I used "Accept review" to add my blurb to the SR.

Please reword the text in the two buttons.

**Comment by hennevogel** [comment]
![screenshot from 2015-01-14 15 23 44](https://cloud.githubusercontent.com/assets/514785/5740196/64fd4b92-9c01-11e4-9ef9-dd67586f3d57.png)

* **Accept Review** means +1 and the request continues
* **Decline Review** means -1 and the request stops
