### ISSUE TITLE
[production][project#status] undefined local variable or method `c' for #<#<Class:0x000055d77fdbc868>:0x00007febb1e8e000>

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#8075]
project#status threw this 0 times
<pre>
undefined local variable or method `c&#39; for #&lt;#&lt;Class:0x000055d77fdbc868&gt;:0x00007febb1e8e000&gt;
</pre>
[https://build.opensuse.org/project/status/openSUSE:Factory?utf8=%E2%9C%93&amp;project=openSUSE%3AFactory&amp;limit_to_fails=false&amp;include_versions=true&amp;filter_devel=All+Packages&amp;commit=Filter+results](https://build.opensuse.org/project/status/openSUSE:Factory?utf8=%E2%9C%93&amp;project=openSUSE%3AFactory&amp;limit_to_fails=false&amp;include_versions=true&amp;filter_devel=All+Packages&amp;commit=Filter+results)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d50726fc0122b0008110a3b)

**Comment by danidoni** [comment]
I'll close this as it was reported before, [here](https://github.com/openSUSE/open-build-service/issues/6909)
