### ISSUE TITLE
No "Save" button on page top useful for big files

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/open-build-service#8088]
With obs 2.9, the file editor had a "Save" button at the top of the view, which was now moved under the editor. This is especially annoying for larger files, as you always have to scroll down completely to save the file.

It would also be helpful to have a "Save" button at the top.

**Comment by hennevogel** [comment]
You have an [END] key for a reason :wink: See the reasoning for this change in [#7924](https://github.com/openSUSE/open-build-service/pull/7924#issuecomment-512265806)...

**Comment by rhabacker** [comment]
> You have an [END] key for a reason wink See the reasoning for this change in [#7924]
Thanks for this pointer. Is there a help popup window or link available to get a list of all configured shortcuts or at least an info message (e.g. on the right of the redo button) to get an idea that this feature exists ?

**Comment by dmarcoux** [comment]
We didn't add this shortcut. It's a built-in shortcut in all browsers.

**Comment by rhabacker** [comment]
I see. Therefore it does not work if the cursor is in the editor widget :-(
