### ISSUE TITLE
markdown support for project description

### ISSUE THREAD

**Issue by rdmitry** [openSUSE/open-build-service#810]
Currently comments in OBS webui supports markdown. It wold be nice to have markdown support for project description: it can contains ulr, lists or other useful information.

**Comment by hennevogel** [comment]
The difference between comments and project descriptions is that comments are a webui only thing. Rendering markdown on the web is easy and looking good, rendering markdown in XML or on the commandline isn't.

**Comment by hellcp** [comment]
Projects like https://github.com/ttscoff/mdless might help with that issue, I wouldn't say it looks bad, but it's an additional dependency ;)

**Comment by hennevogel** [comment]
Not sure how you think this could help?

**Comment by hellcp** [comment]
I mean, rendering markdown in cli isn't impossible, I would think with bash and many other shells offering wide text formatting options as well as many terminal emulators offering link highlighting and opening in the browser, adding a markdown functionality would contribute to usefulness of the project/package descriptions in osc and any alternative frontends to obs (whole one of them).

**Comment by hennevogel** [comment]
Rendering markdown is not the 'issue'. It's using one markup format (Markdown) inside another markup format (XML).

**Comment by hellcp** [comment]
Right, I apparently willfully ignored the entire point, I will look around to see how it's being done in other implementations :D
