### ISSUE TITLE
Changing repositories not possible if not project maintainer

### ISSUE THREAD

**Issue by sebix** [openSUSE/open-build-service#8110]
# Issue Description
I can't enable/disable builds anymore at the Repositories page of packages, e.g. https://build.opensuse.org/repositories/devel:languages:python/python-Cerberus
Clicking on the icons has no result.
In the browser's javascript console I see:
14:17:56.517 SyntaxError: An invalid or illegal string was specified commandline_frame.js:15463
    listenForCounters perf.ts:167
    ts commandline_frame.ts:379
    Webpack 3

Expected Result
============
it works

How to Reproduce
===============
1. Go to a package you are allowed to edit
2. Click on Repositories
3. Click any icon to enable/disable builds

**Comment by hennevogel** [comment]
>  Clicking on the icons has no result.

Can explain this a bit more. What exactly happens?

>  In the browser's javascript console I see:

What browser are you using?

**Comment by sebix** [comment]
> > Clicking on the icons has no result.
> 
> Can explain this a bit more. What exactly happens?

Nothing. With Firefox and Chromium
> 
> > In the browser's javascript console I see:
> 
> What browser are you using?

This is with firefox.

**Comment by hennevogel** [comment]
> Nothing. With Firefox and Chromium

Are you logged in?

**Comment by sebix** [comment]
> > Nothing. With Firefox and Chromium
> 
> Are you logged in?

Yes. And I am maintainer (and bugowner) of the packages

**Comment by hennevogel** [comment]
Works for me on all browsers and various packages. The javascript errors you see do not come from our javascript, guess they are from an extension. Try with [firefox safe mode](https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode) or a different browser.

**Comment by hennevogel** [comment]
Sometimes this can also happen for firefox if you've updated the package while it was running.

**Comment by jdelvare** [comment]
Same problem here trying to change the repositories of Base:System/dmidecode with the web frontend. I don't even get any error in the console, just nothing happens when I click on the icons.

**Comment by hennevogel** [comment]
Same problem as in what? You get the same errors in the javascript console?

**Comment by jdelvare** [comment]
Same problem as in "I'm not able to change the package's repositories using the web UI".
No, I do not see the same errors in the javascript console, as I said I do not see any error at all.

**Comment by hennevogel** [comment]
> nothing happens when I click on the icons

The icons do not even turn into spinners?

If you reload your tab are you still logged in when this happens?

**Comment by jdelvare** [comment]
Icon does not change.
Yes, if I reload I'm still logged in.

**Comment by hennevogel** [comment]
Alright with the help @jdelvare I was able to reproduce this. If you are only package maintainer and _not_ project maintainer you are not allowed to change this. This has nothing to do with javascript.

**Comment by sebix** [comment]
Thanks for the debugging, I can confirm that I'm able to change repos in my own projects
