### ISSUE TITLE
New user interface: hard to distinguish success/failure

### ISSUE THREAD

**Issue by msvec** [openSUSE/open-build-service#8116]
# Issue Description
In the new interface it is rather hard to distinguish between "succeeded" and "failed" as the two colors are rather close or the background makes it hard to distinguish between the two.

For example in this overview I don't see any difference, unless I expect the screen closely:
https://build.opensuse.org/project/monitor/LibreOffice:6.3

**Comment by dmarcoux** [comment]
Here's an example:
![Screenshot_20190819_162846](https://user-images.githubusercontent.com/1102934/63273635-9dd34200-c29e-11e9-862d-88af2e292ee3.png)

@msvec If you don't mind answering, do you happen to be colorblind? I am asking because I believe some tones of green and red can be seen as the same for certain types of colorblindness.

**Comment by msvec** [comment]
@dmarcoux Actually I am partly :) E.g. in your screenshot I can see the distinction, but it's rather small and not easy to spot on the first view as it was in the design before.

**Comment by vpereira** [comment]
hi @msvec , thank you for your issue, sorry for the inconvenience. Could you tell me if this issue used to happen in the old UI too? I mean, was literally ported from the old UI, with more padding and bigger fonts, but I suspect that both wouldn't affect it.

**Comment by dmarcoux** [comment]
@msvec and @vpereira I added a screenshot from the old UI in my [first comment](https://github.com/openSUSE/open-build-service/issues/8116#issuecomment-522601887) to compare.

**Comment by msvec** [comment]
Actually in the previous design it was easier to differentiate the red / green colors. I can't tell what exactly is causing the difference, though.

**Comment by dmarcoux** [comment]
The tones of red and green changed in the new UI. They seem to be worse for certain colorblindness.

**Comment by krauselukas** [comment]
@msvec hi, could you maybe compare the screenshots in this PR https://github.com/openSUSE/open-build-service/pull/8146 and tell us if the changes brings improvement for you? :) Unfortunately the review app doesn't show this page, please let me know if the screenshots are not sufficient to tell if it helps or not.

**Comment by hennevogel** [comment]
https://obs-reviewlab.opensuse.org/krauselukas-issue_8116/project/monitor/home:Admin

**Comment by msvec** [comment]
It's not really better, the old UI (as shown in the screenshot above) in comparison feels easier to differentiate between the two colors.

**Comment by krauselukas** [comment]
@msvec I updated the PR and removed the zebra stripes completly from the tables. Would be great if you could check again if that brings at least some improvement for you. The only thing that differs now from the old webui, would be the color tone.

**Comment by msvec** [comment]
Actually, I guess the stripes were fine :) Can you do a comparison similar to the one in PR #8146, current design with stripes and the old colors+tone?

**Comment by krauselukas** [comment]
@msvec I will create a comparison for you tommorrow, meanwhile you maybe could have a look into https://github.com/openSUSE/open-build-service/pull/8165 would be interested in your feedback

**Comment by aspiers** [comment]
It's great to fix issues for the color blind, and I am definitely in favour of doing that.  At first I was concerned that this introduces a regression, because I often found the zebra stripes really useful, especially on wide tables.  Now that they are gone, on the surface it seems too easy for the eye to accidentally shift up or down a row while tracking from left to right.  However I just discovered that mouse-over introduces a single zebra stripe for the whole column, so I guess that is good enough.

**Comment by krauselukas** [comment]
@aspiers thanks for your feedback!

**Comment by msvec** [comment]
I think the stripes were actually fine, what matters more seems to be the color tone (see the comments above). I agree that stripes generally help.

**Comment by vpereira** [comment]
> Now that they are gone, on the surface it seems too easy for the eye to accidentally shift up or down a row while tracking from left to right.

@aspiers 

To avoid this, use one (or many) of the Filter options that we have to reduce the numbers of displayed rows. That's much better than zebra. 

> I think the stripes were actually fine, what matters more seems to be the color tone (see the 

@msvec 

Unfortunately the combination of gray background with green and red fonts aren't the best choice for color blindness. We looked around and spent some time researching about the topic to come up with a better solution. 

We are planing to refactor this view in a way that we are able to get rid of such wide table, stay tuned!

**Comment by msvec** [comment]
@vpereira, I'd still like to get back the old colors :) Let's see (per comment https://github.com/openSUSE/open-build-service/issues/8116#issuecomment-524080068)

**Comment by vpereira** [comment]
> @vpereira, I'd still like to get back the old colors :) Let's see (per comment [#8116 (comment)](https://github.com/openSUSE/open-build-service/issues/8116#issuecomment-524080068))

if you mean [this](https://user-images.githubusercontent.com/1102934/63280082-7a15f900-c2aa-11e9-9884-c26e74514bd0.png) I agree with you!
