### ISSUE TITLE
[production][project#destroy] undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#8119]
project#destroy threw this 8 times
<pre>
undefined method `name&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/project/destroy](https://build.opensuse.org/project/destroy)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d568eda346022000d1934e0)

**Comment by lethliel** [comment]
affected projects:

home:mstrigl:Staging:A
home:mstrigl:Staging:B
home:lethliel:Staging:A
home:lethliel:Staging:B

UI throws internal 500

**Comment by DavidKang** [comment]
Doesn't happens since 8 months, reopen it needed.
