### ISSUE TITLE
Overflowing comment on SR page

### ISSUE THREAD

**Issue by jonsger** [openSUSE/open-build-service#8130]
## Issue Description
On a submit request page there is an overflowing comment, which doesn't fit to the comment box.

![obs_overflowing_box](https://user-images.githubusercontent.com/3876790/63269165-fbaf5c00-c295-11e9-9707-4c37f64031bb.png)

## Expected Result
Comment is wrapped to stay inside the white box.

## How to Reproduce
1. Go to https://build.opensuse.org/request/show/724382#status-history-6992272
2. Set your browser width (e.g. in Responsive Design Viewer) to:
* 1500px or
* 1200px or
* 820px

## Further information
* tested in recent Firefox and Chrome

**Comment by dmarcoux** [comment]
Thank you @jonsger for reporting this.

**Comment by hennevogel** [comment]
@vpereira another case of `hyphens: auto` not doing the job?
