### ISSUE TITLE
Impossible to set OBS:QualityCategory in Attributes tab

### ISSUE THREAD

**Issue by hellcp** [openSUSE/open-build-service#8143]
# Issue Description
OBS:QualityCategory is impossible to set

Expected Result
============
It's possible to set a quality category for projects

How to Reproduce
===============
1. Go to Attributes tab in a project
2. Select OBS:QualityCategory in the dropdown
3. Click Add
![Screenshot from 2019-08-21 08-00-55](https://user-images.githubusercontent.com/30577011/63406376-fe22ca80-c3e9-11e9-9cc6-bfb493a65a66.png)

**Comment by coolo** [comment]
Hmm, the webui should have offered a select box there

**Comment by dmarcoux** [comment]
Thank you @hellcp for reporting this. I can reproduce the issue.
