### ISSUE TITLE
Horizontal scroll on monitor page shows the info behind a highlighted row

### ISSUE THREAD

**Issue by saraycp** [openSUSE/open-build-service#8183]
# Issue Description
Horizontal scroll on monitor page shows the info behind a highlighted row.

![Show home SCabreraPadron   openSUSE Build Service(3)](https://user-images.githubusercontent.com/2581944/63776122-0a72c000-c8e1-11e9-8aac-22fad441d8cc.png)

Expected Result
============
Use an opaque color for highlighted rows, instead of Bootstrap semi-transparent color. 

How to Reproduce
===============
1. Go to 'https://build.opensuse.org/project/monitor/OBS:Server:Unstable'
2. Move horizontal scroll a bit
3. Mouse over package names
4. See error: in rows where the state cells are not empty, the info is shown behind the package name.

Further Information
===============
https://getbootstrap.com/docs/4.0/content/tables/#hoverable-rows

**Comment by vpereira** [comment]
with chrome if I'm not logged in I see other problems:

![Screenshot_2019-08-27_16-24-44](https://user-images.githubusercontent.com/37418/63779656-36913f80-c8e7-11e9-8787-c43c6c7e0fd6.png)
![Screenshot_2019-08-27_16-24-23](https://user-images.githubusercontent.com/37418/63779658-3729d600-c8e7-11e9-8af2-9f5e1d496da9.png)

**Comment by vpereira** [comment]
in a smaller screen I see like that with the mouse over the package name:

![Screenshot_2019-08-27_16-25-30](https://user-images.githubusercontent.com/37418/63779778-693b3800-c8e7-11e9-9954-58aee8235266.png)

**Comment by hennevogel** [comment]
This is because of the [FixedColumns](https://datatables.net/extensions/fixedcolumns/) extension to datatables. The sticky colums is basically another table rendered on top of the other.

**Comment by hennevogel** [comment]
If you move your mouse to the right (the second table beneath the first column) you get the other row highlighted.

**Comment by hennevogel** [comment]
Here is what you can do until we arrive at a redesign of this page:

0. remove the FixedColumns extension for datatables, it's causing too much trouble for little gain
1. Hide the link to this page on everything below the `md` breakpoint inside our app
2. if people arrive in this page from outside of our app: do not render the table, tell them to enable 'desktop mode' in their browser

**Comment by vpereira** [comment]
I would suggest something different to end with this wide table with horizontal scroll:

1) One table per repository (in the page https://build.opensuse.org/project/monitor/OBS:Server:Unstable, you would have one table for SLE_12_SP4, SLE-15, containers and etc)

2) If everything is green in a repository, the table is collapsed, as in https://status.opensuse.org/ (thanks @danidoni) 

what do you think @hennevogel ?

**Comment by hennevogel** [comment]
> what do you think @hennevogel ?

I think you understand what our users are doing with that data. Then you help them do it with the interface.

This is not something you can just do in between other things. That is why we have this on the radar in our planing process -> https://trello.com/c/hsJ76Nwk and are going to address a redesign in the future.

**Comment by saraycp** [comment]
Focusing on this exact issue, the problem is the background color of the row highlight. A few days ago it was opaque white, however, now it's highlighted with a semi-transparent gray color.

To fix exactly that, should be enough with #8184 and redesigning if for sure a TODO.
