### ISSUE TITLE
_constraints issue with 'local' worker arch

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#8192]
It's clearly a special case, but the setup is as follows:

openSUSE:Factory/000product - as a product this is built on 'arch local' on back-main (typhoon workers) - those are chroot workers, sufficient space for the whole FTP tree. Generally, we have no disk constraint issue there

000product is inherited into the staging areas - (e.g. openSUSE:Factory:Staging:A) - where we build the same product (a limited set thereof, e.g. no FTP tree) - in Staging, the product is built 'normally' on the x86_64 workers ('local' is not a configured arch in staging)

Now, there we have the issue that the 'x86_64' workers are many - but not all are capable of building an entire DVD (space consumption is usually ~ 20GB there)

So, we tried to set a _constraints file, requesting 21GB HDD space - this works perfectly fine for staging, no worker picking up the job that should not. But since the paackage is inherited from openSUSE:Factory, the smae _constraints file is also in the package in openSUSE:Factory - where the 'local' arch workers (i.e. pythoon1) does not have any disk information exported and OBS thus finds no worker capable of handlling the product build.

I tried with a constraint with exception, but that seemed not to work (even though @adrianschroeter was of the opinion that this should be going in the right direction)

The _constraints file used contained:

```
<?xml version="1.0"?>
<constraints>
  <overwrite>
    <conditions>
      <arch>x86_64</arch>
    </conditions>
    <hardware>
      <disk>
        <size unit="G">21</size>
      </disk>
    </hardware>
  </overwrite>
</constraints>

```

**Comment by adrianschroeter** [comment]
constraints like disk space can not get be guaranteed with local/chroot builds. It won't work by design, since another job may eat the disk space or memory after the build has started.

So, sorry, I see no way there.

**Comment by Vogtinator** [comment]
There has to be at least a way to not match chroot workers then though, without having to mention those explicitly.

**Comment by adrianschroeter** [comment]
On Mittwoch, 8. April 2020, 14:35:45 CEST wrote Fabian Vogt:
> There has to be at least a way to not match chroot workers then though, without having to mention those explicitly.

true, but this would be in clear contradiction to "local" workers then ;)

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany
