### ISSUE TITLE
multibuild package create multiple -debugsource packages with varying content

### ISSUE THREAD

**Issue by msmeissn** [openSUSE/open-build-service#8194]
# Issue Description

When building a _multibuild package with debuginfo enabled, multiple MAIN-debugsource packages will be built, one for every flavor.

The content however will be different, depending on what has been built within the package.

This is confusing for maintenance, as we deliver multiple MAIN-debugsource packages with the very same RPM name, but different content.

Expected Result
============

Seperate -debugsource packages per flavor.

How to Reproduce
===============
1.
   osc getbinaries openSUSE:Factory postgresql10:libs standard x86_64 --debug
   osc getbinaries openSUSE:Factory postgresql10 standard x86_64 --debug

2. Compare size and content of the postgresql10-debugsource-.... 
3. there should not be 2 different size / content packages.

Further Information
===============
* openSUSE:Factory postgresql10

**Comment by mlschroe** [comment]
It also builds different .src.rpm. The solution is to use a different package name in the flavors.

I.e. it's a packaging bug...
