### ISSUE TITLE
[production][delayed_job#FullTextIndexJob] Guardfile /srv/www/obs/api/db/sphinx/production/ts---all.tmp exists already

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#8200]
delayed_job#FullTextIndexJob threw this 361 times
<pre>
Guardfile /srv/www/obs/api/db/sphinx/production/ts---all.tmp exists already
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d64ddbb6b60fd000e1d6129)

**Comment by dmarcoux** [comment]
See this section on how to fix this: https://github.com/openSUSE/open-build-service/wiki/Deployment-of-build.opensuse.org#search

We send this exception to Errbit when this guardfile couldn't be created. It means that the search is not indexing.

**Comment by danidoni** [comment]
Ok, I'll close this then.
