### ISSUE TITLE
[production][source_attribute#update] undefined method `elements' for #<String:0x00007f1fed7d7918>

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#8221]
source_attribute#update threw this 0 times
<pre>
undefined method `elements&#39; for #&lt;String:0x00007f1fed7d7918&gt;
</pre>
[https://api.opensuse.org/source/openSUSE:Leap:15.2:Images/_attribute/OSRT:ToTestManagerConfig](https://api.opensuse.org/source/openSUSE:Leap:15.2:Images/_attribute/OSRT:ToTestManagerConfig)"

[See this exception on Errbit](http://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d69144824569a0008135820)

**Comment by coolo** [comment]
(User error combined with missing input validation)

**Comment by eduardoj** [comment]
Exception not found in Errbit any more. Closing.
