### ISSUE TITLE
bad line truncation of legend on graphs at the bottom of status page

### ISSUE THREAD

**Issue by bugfinder** [openSUSE/open-build-service#8222]
if you look at the bottom of https://build.opensuse.org/monitor
the lines are truncated:
800
  00
600
  00
[...]

while this should probably be "80.000" or "80k" or something, but wrapping after exactly 3 digits counting from the left is misleading
is
8
000
000
then 8 million ?

**Comment by coolo** [comment]
https://github.com/flot/flot/blob/master/API.md#customizing-the-axes has an example for a custom tick formatter that could be used basically as is :)
