### ISSUE TITLE
[production][comments#create] undefined method `find' for nil:NilClass

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#8232]
comments#create threw this 1 times
<pre>
undefined method `find&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/comments](https://build.opensuse.org/comments)"

[See this exception on Errbit](http://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d6cf51bc7b48d000db006ec)

**Comment by coolo** [comment]
According to errbit, it's still happening

**Comment by hennevogel** [comment]
Yes it is
