### ISSUE TITLE
repo in broken state on rsync.opensuse.org

### ISSUE THREAD

**Issue by JanZerebecki** [openSUSE/open-build-service#8258]
The published repo for devel:tools:building on rsync.opensuse.org and other mirrors were missing the 3 files that don't contain repomd from
https://download.opensuse.org/repositories/devel:/tools:/building/SLE_12_SP4/repodata/ .

E.g. missing were:
0c0756914cc9005dd97a89aa4f3edc3f55343533276cf6a3230f26df2356474b-primary.xml.gz
21f31e346e28fa999ef2928726b9f574d645138623b1ad27e94c13333aabed78-filelists.xml.gz
c7071c9313f1209367bd9be572e0b0959121791d79bb1c9cc8f9aa673af78b3c-other.xml.gz
but present were only:
repomd.xml
repomd.xml.asc
repomd.xml.key

We triggered a rebuild, but that didn't help.

This was also reported as https://progress.opensuse.org/issues/56042 . A few days after the problem was noticed, I checked again and it fixed itself.

Any idea where/why such a problem might occur? How to avoid it happening in the future??
For when it happens again:
Is there a way to find if the problem is on the OBS side? Is there a way to pinpoint more precisely where the problem occurs (where it is between OBS and rsync.opensuse.org)?

**Comment by adrianschroeter** [comment]
this has nothing to do with repo state and OBS, it could be a staging server issue though. However, nothing what we can fix in OBS code.

**Comment by JanZerebecki** [comment]
So who maintains the staging server and where to file bug reports about it? Or where to read its source code and how to debug it? Same question about rsync.opensuse.org? I thought issues here could also be about configuration of build.opensuse.org.

**Comment by JanZerebecki** [comment]
I found https://code.opensuse.org/heroes/salt/blob/production/f/pillar/id/widehat_infra_opensuse_org.sls which explains at least the rsync.o.o part.

**Comment by hennevogel** [comment]
openSUSE: admin@opensuse.org
