### ISSUE TITLE
[production][trigger#rebuild] undefined method `match?' for nil:NilClass

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#8262]
trigger#rebuild threw this 5 times
<pre>
undefined method `match?&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/trigger/rebuild](https://build.opensuse.org/trigger/rebuild)"

[See this exception on Errbit](http://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d6d1dafc7b48d0008b006d3)

**Comment by hennevogel** [comment]
did not happen anymore for a year
