### ISSUE TITLE
[production][feeds#notifications] home:thardeck:branches:Archiving:Backup

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#8263]
feeds#notifications threw this 49 times
<pre>
home:thardeck:branches:Archiving:Backup
</pre>
[https://build.opensuse.org/user/feed/rbL2pDhXiQswGmikSxiFCRkD](https://build.opensuse.org/user/feed/rbL2pDhXiQswGmikSxiFCRkD)"

[See this exception on Errbit](http://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d691ea624569a000d13581d)

**Comment by dmarcoux** [comment]
Duplicate of #7094
