### ISSUE TITLE
`view_file` javascript: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#8273]
threw this 1456 times
<pre>
Cannot read property &#39;value&#39; of null
</pre>
[https://build.opensuse.org/package/view_file/home:metakcahura:kernel/linux-clear/PKGBUILD?expand=0](https://build.opensuse.org/package/view_file/home:metakcahura:kernel/linux-clear/PKGBUILD?expand=0)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5d69314124569a000813582d/problems/5d6fb8964d64e7000df428e6)

**Comment by hennevogel** [comment]
BTW I guess this also has something to do with the second most popular exception on that page:

[document.getElementById(...) is null](https://errbit-opensuse.herokuapp.com/apps/5d69314124569a000813582d/problems/5d6fb72f4d64e70008f428d0)

**Comment by danidoni** [comment]
I think we need to add sourcemaps into the asset pipeline to properly debug this kind of stuff, otherwise it is impossible to track the errors back to the source code.

**Comment by hennevogel** [comment]
Alright, then I turn this off before we have this.

**Comment by hennevogel** [comment]
Blocked by #8283

**Comment by dmarcoux** [comment]
Removed @danidoni as assignee since it's blocked.
