### ISSUE TITLE
backend: publisher: re-enqueue after failure not working

### ISSUE THREAD

**Issue by bugfinder** [openSUSE/open-build-service#8276]
project linked against OBS, flaky network sometimes returning truncated answers:

2019-09-05 09:41:40: [5464]  publishing home:oertel:branches:openSUSE.org:Base:System/openSUSE_Leap_15.1
publish failed for home:oertel:branches:openSUSE.org:Base:System/openSUSE_Leap_15.1 : 400 remote error: received truncated answer  
waiting for an event...

and not retried automatically for hours, immediately retried and working after publisher restart

**Comment by mlschroe** [comment]
Fixed, I guess.
