### ISSUE TITLE
<access> in prjmeta is rejected

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#828]
When attempting to add <access><disable/></access> to the prjmeta with osc, the API returns:

BuildService API error: change_project_protection_level (403)
admin rights are required to raise the protection level of a project (it won't be safe anyway)

I am doing the operation using my admin-enabled account. In addition, it should say _why_ exactly it is not supposed to be safe.

**Comment by mdeniz** [comment]
Ping, this is still valid?

**Comment by jengelh** [comment]
Seems fixed one way or another in obs-server-2.8.51.git20170714-3592.3.noarch.

**Comment by mdeniz** [comment]
Ok, closing, many thanks
