### ISSUE TITLE
buildservice at build.o.org broken

### ISSUE THREAD

**Issue by dirkmueller** [openSUSE/open-build-service#8280]
osc branch openSUSE:Leap:15.2 python3 openSUSE:Leap:15.2:ARM python3
BuildService API error: failed to branch: Can't use an undefined value as a HASH reference at /usr/lib/obs/server/BSSrcServer/Service.pm line 300.

**Comment by coolo** [comment]
Yeah, but since may: https://github.com/openSUSE/open-build-service/issues/7596

**Comment by hennevogel** [comment]
so a duplicate...
