### ISSUE TITLE
Delete route /staging/home:mstrigl/workflow returns nothing

### ISSUE THREAD

**Issue by lethliel** [openSUSE/open-build-service#8286]
# Deleting a staging workflow returns nothing
Using the API to delete a staging workflow for a project works, but returns nothing.
DELETE https://api.opensuse.org/staging/home:mstrigl/workflow 

Expected Result
============
This should be returned according to the documentation:
```
<status code="ok">
    <summary>Ok</summary>
</status>

```
How to Reproduce
===============
1. create a staging
2. osc api -X DELETE /staging/home:mstrigl/workflow
3. See no return

**Comment by vpereira** [comment]
@lethliel the fix is already online!
