### ISSUE TITLE
[production][project#maintained_projects] undefined method `tab' for #<#<Class:0x0000562831f58138>:0x00007f925d8ef228>
Did you mean?  tap
 ...

### ISSUE THREAD

**Issue by krauselukas** [openSUSE/open-build-service#8287]
project#maintained_projects threw this 29 times
<pre>
undefined method `tab&#39; for #&lt;#&lt;Class:0x0000562831f58138&gt;:0x00007f925d8ef228&gt;
Did you mean?  tap
               tag
</pre>
[https://build.opensuse.org/project/maintained_projects/home:mauricioph](https://build.opensuse.org/project/maintained_projects/home:mauricioph)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d6fdd1a4d64e70008f4294a)

**Comment by DavidKang** [comment]
handled in PR #8313
