### ISSUE TITLE
[production][repositories#create] Mysql2::Error: Duplicate entry '589114-Arch-' for key 'projects_name_index': INSERT INTO `reposit...

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#8330]
repositories#create threw this 5 times
<pre>
Mysql2::Error: Duplicate entry &#39;589114-Arch-&#39; for key &#39;projects_name_index&#39;: INSERT INTO `repositories` (`db_project_id`, `name`) VALUES (589114, &#39;Arch&#39;)
</pre>
[https://build.opensuse.org/project/save_repository?project=home%3Aopensesu](https://build.opensuse.org/project/save_repository?project=home%3Aopensesu)"

~[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d9d957bdb118c0008ab758d)~

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5f568ad1844c0600087d8696)

**Comment by eduardoj** [comment]
Exception not found any more in Errbit. Closing.

**Comment by eduardoj** [comment]
Still happens. Reopening.

**Comment by coolo** [comment]
It's likely that it's the same story as the reproducer for https://github.com/openSUSE/open-build-service/issues/6012
