### ISSUE TITLE
rdiff action needs to be refactored

### ISSUE THREAD

**Issue by saraycp** [openSUSE/open-build-service#8347]
While merging the code on webui2 to webui, we found that rdiff action on package controller calls  `submit_request_dialog`, an action that should be removed and point to `render_dialog` which should be moved also.

We'll have to figure out how to get rid of this old code and  use the partial `submit_request_dialog` instead.

**Comment by eduardoj** [comment]
This got refactored time ago. The partial `submit_request_dialog` got removed. See #9541. Closing.
