### ISSUE TITLE
linking_packages method needs to be refactored

### ISSUE THREAD

**Issue by saraycp** [openSUSE/open-build-service#8348]
While merging the code on webui2 to webui, we found that `linking_packages` action on package controller calls  `render_dialog` which should be moved also.

We'll have to figure out how to get rid of this old code.

**Comment by dmarcoux** [comment]
We must not move `render_dialog`. It needs to be deleted. This issue has to be closed. Let's talk in the stand-up about this. There are misunderstandings in the team regarding `render_dialog`.
