### ISSUE TITLE
Exclude requests which are `ready`

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#8355]
In the staging workflow, it should be possible to exclude requests which are `ready`.

To reproduce, create a staging workflow for a project (`home:Admin` for example) and have a request open for this project.

Then run this command (by adapting it to your project name and request ID):
```
osc api staging/PROJECT_NAME/excluded_requests -X POST -d "<excluded_requests><request number='REQUEST_ID' description='invalid request' /></excluded_requests>"
```

This will fail:
```
Server returned an error: HTTP Error 400: Bad Request
Excluding requests for #<Staging::Workflow:0x00007f1eea77f410> failed: Request : Number can't be blank and Request is not a number.
```

**Comment by coolo** [comment]
I guess this all comes down to the fact that it was never defined what the purpose of excluding a request is.
