### ISSUE TITLE
Delete from staging project not working

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8364]
Testing https://github.com/openSUSE/osc/pull/631 I did:

```
coolo@f102#osc>tosc ps request delete openSUSE:Factory -s openSUSE:Factory:Staging:A -r 1771
Request 1771 deleted from openSUSE:Factory:Staging:A
```

And you can see on https://build-test.opensuse.org/staging_workflows/1/staging_projects/openSUSE:Factory:Staging:A

```
History
Unstaged request #1771 for package python-lxml submitted by coolo
```

But you can also see 
```
 Untracked requests	#1771 (review)
```

Making A unacceptable. And as A is not back in the backlog, I can't do *anything* with it now. 
This blocks testing osc command

**Comment by vpereira** [comment]
Hey @coolo , I wasn't able to reproduce it. I followed your steps and looks like my Staging Project is right, however I see your issue in the `build-test` instance. Would you mind to try to reproduce it in master? 

![Screenshot_2019-10-07_08-58-30](https://user-images.githubusercontent.com/37418/66290870-a9c3a380-e8e0-11e9-9bca-4827b3a0e5e3.png)

**Comment by coolo** [comment]
this appears to be a duplicate of #7344
