### ISSUE TITLE
https://openbuildservice.org/ does not list SUSE as using it

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#8370]
https://openbuildservice.org/ lists some companies using OBS but not SUSE!?

**Comment by dmarcoux** [comment]
The code for https://openbuildservice.org/ is at https://github.com/openSUSE/obs-landing. I opened the issue for you there.

**Comment by coolo** [comment]
you can actually transfer issues - no need to close. Look at the right bottom of the PR page

**Comment by dmarcoux** [comment]
Oh, I didn't know.
