### ISSUE TITLE
publisher not publishing to stageserver (at least for rsync-target)

### ISSUE THREAD

**Issue by jsjhb** [openSUSE/open-build-service#8384]
# Issue Description
publisher fails publishing, when stageserver is defined. The variable
`our $stageserver = 'rsync://192.168.22.23/repos';`
is defined in BSConfig.pm, the target is available, but in publisher.log the following is logged, and publishing fails:

```
2019-09-18 15:09:56: [16127] publishing userweb/openSUSE_Leap_15.1
    fetched 0 patterns
    running createrepo
    running rsync to rsync://192.168.22.23/repos at Wed Sep 18 15:09:58 2019
Use of uninitialized value $args[2] in exec at /usr/lib/obs/server/bs_publish line 134.
```
Then the stdout of a call to 'rsync' is printed, hinting an erroneous composition of the rsync command line, and
```
rsync error: syntax or usage error (code 1) at options.c(2356) [client=3.1.3]
publish failed for userweb/openSUSE_Leap_15.1 :     rsync failed at Wed Sep 18 15:09:58 2019: 256
    syncing database (6 ops)
```

The command line is composed in bs_publish at line 1472, it errors out in 134.

I did not touch the configuration for the stage server for quite a while, and according to logs, publishing stopped around Jul 16th, when I updated the server from OBS 2.9 to 2.10.
As soon as I do not define stageserver, publishing succeeds by putting the files in the local repos directory. 

Expected Result
============
A working publishing locally and to the stageserver :-)
publishing should succeed in rsync'ing the repos to the defined rsync-target.

How to Reproduce
===============
1. define stageserver in BSConfig.pm
2. restart obspublisher
3. look in /srv/obs/log/publisher.log

Further Information
===============
https://buildhost.botter.cc
https://buildhost.jacobs-university.de
both run 2.10-lp151.10.1 from OBS Server 2.10, both on openSUSE Leap 15.1

**Comment by mlschroe** [comment]
Yes, commit a76f858df524d557738f7d71c921858ceba3b4c2 is bad.

Please add
```
our $rsync_extra_options = "--whole-file";
```
to your BSConfig.pm as a workaround until this is fixed.
