### ISSUE TITLE
Login page does not redirect anywhere useful

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#8399]
When you go to a page like https://build.opensuse.org/request/show/727947 , there is a orange box further below saying """Login required, please [login] in order to comment""". login is a hyperlink leading to https://build.opensuse.org/session/new . When logging in via this mask, the same page (`/session/new`) is displayed again, making it look like the login had failed at first.

Expected:
On successful login, have `/session/new` redirect somewhere elsewhere —- anywhere is good, frontpage included. Better would be to make the link at the bottom of a `/request/show` have a return URL (`/session/new?return=/request/show/727947` or so)

**Comment by coolo** [comment]
very similiar to https://github.com/openSUSE/open-build-service/issues/7333 but not exactly the same

**Comment by vpereira** [comment]
it is related with our authentication sever

**Comment by coolo** [comment]
https://github.com/openSUSE/apache2-mod_auth_memcookie/blob/master/samples/login_post.php#L154 - it plainly redirects to the referer it seems

**Comment by coolo** [comment]
that's at least the way it's supposed to work with ichain

**Comment by hennevogel** [comment]
fixed now in the openSUSE login proxy.
