### ISSUE TITLE
[production][request#changerequest] undefined method `can_be_modified_by?' for nil:NilClass

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#8403]
request#changerequest threw this 0 times
<pre>
undefined method `can_be_modified_by?&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/request/changerequest](https://build.opensuse.org/request/changerequest)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d841bed5efab9000bf4823b)

**Comment by eduardoj** [comment]
Handled in #8412.
