### ISSUE TITLE
Complaint workers count differs among CLI and web interface

### ISSUE THREAD

**Issue by marxin** [openSUSE/open-build-service#8404]
Web interface reports:
https://build.opensuse.org/package/show/mozilla:Factory/MozillaFirefox
`waiting for 4 compliant workers`

While CLI reports:
```
osc checkconstraints  mozilla:Factory MozillaThunderbird openSUSE_Factory_pure x86_64 | wc -l
70
```

**Comment by hennevogel** [comment]
Duplicate of #8397
