### ISSUE TITLE
Can I switch to the old design on build.opensuse.org?

### ISSUE THREAD

**Issue by Zenitur** [openSUSE/open-build-service#8415]
I have a baby duck syndrome and can't work with the new design.

**Comment by highperformancecoder** [comment]
I wouldn't mind the option of switching back. The large font design makes it very hard to handle a lot of distros and projects as the information is across multiple web screens

**Comment by vpereira** [comment]
No. If you have concrete issues, please feel free to open issues about it. If you want to discuss about other things please use the mailing list or the irc channel as described here https://openbuildservice.org/support/
