### ISSUE TITLE
expose build type as macro

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#8441]
The distro has prjconf settings to ignore certain requirements that block packages from getting installed on normal systems, like systemd-mini:

     # break dependency of the -mini packages: they are valid for OBS, but not for end-user-installation
     Ignore: systemd-mini:this-is-only-for-build-envs

That is only meant to be applied to actual package builds though. Kiwi builds are not supposed to pull those packages in but do so right now. So would be good if those lines could be conditional based on build type. Just matching on %_repository won't work as developers branching packages or images would get different repo names.

**Comment by mlschroe** [comment]
Kiwi builds ignore all "Ignore" lines, i.e. it doesn't make sense to add a conditional here.
