### ISSUE TITLE
[Kubernetes] Benefits on deploy OBS on kubernetes?

### ISSUE THREAD

**Issue by TommyLike** [openSUSE/open-build-service#8442]
**Is your feature request related to a problem? Please describe.**

Hey guys
     Recently we need to deploy a OBS cluster for our system. Since our previous services are all deployed in kubernetes. therefore we want to try this on that way. 

**Question**:
   Has anyone tried to build a product OBS system on kubernetes? Is there any advantages or disadvantages for this?
  I found someone is asking about the native scheduling support on kubernetes, therefore I wonder if it already has been tested and verified.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by adrianschroeter** [comment]
We are evaluating it, but github issues is not the way to track it. You will need in any case KVM nesting which will cause a slow down.

**Comment by TommyLike** [comment]
@adrianschroeter  thanks, but it depends on the engine that the cluster use, right?

**Comment by hennevogel** [comment]
@TommyLike you want to discuss this on https://lists.opensuse.org/opensuse-buildservice/

**Comment by TommyLike** [comment]
@hennevogel  thanks, will do!
