### ISSUE TITLE
webui does not show open reviews via groups

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#846]
The open reviews for a user do not include reviews which are assigned to the users group or project.
(api and osc are showing all of them)

This is in first place in app/modules/user.rb's  involved_reviews method only used by webui. The open question to me is if we may should show them in seperate lists not only into one merged together.

**Comment by coolo** [comment]
I don't get that report. I see the reviews I have open for factorying-staging, just as the opensuse-review-team sees their reviews.

**Comment by adrianschroeter** [comment]
okay, I see some group resolution code in BsRequestCollection. So let's close this and ask lars to show the issue again ....

**Comment by adrianschroeter** [comment]
Coolo, do you really see the requests in "Incoming Reviews" when you are part of the group?

**Comment by adrianschroeter** [comment]
JFYI, there is code in   extend_query_for_user(user)    to look also for all groups, but it does not work for LarsMB for some reason.

In any case, I do not see code which also looks for reviewies via package/project maintainers here in any case.

However, hand over to henne :)

**Comment by coolo** [comment]
my "incoming reviews" are full of reviews for factory-staging, yes

**Comment by bgeuken** [comment]
I can't reproduce the issue. 

Also the involved code changed quite a bit and [seems to cover that case](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/user.rb#L655). If this is still happening, please reopen.
