### ISSUE TITLE
mouseover for unresolvable packages

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#8462]
The mouse over/click in the package view for unresolvable does not work anymore:
https://build.opensuse.org/package/show/openSUSE:Leap:15.2/mkvtoolnix

![unresolvable](https://user-images.githubusercontent.com/722232/65770141-b8b69300-e135-11e9-82c9-268c04812661.gif)

**Comment by hennevogel** [comment]
Works for me on Firefox/Chromium. 

![Peek 2019-09-27 15-34](https://user-images.githubusercontent.com/514785/65773354-70e73a00-e13c-11e9-9d3c-4071b7b9743b.gif)

Are you using some js blocker or something?

**Comment by lnussel** [comment]
something tampermonkey. *sigh*

**Comment by lnussel** [comment]
thanks!
