### ISSUE TITLE
Repotype: staticlinks creates duplicate file name links

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/open-build-service#8488]
Currently some kiwi appliances like `openSUSE-MicroOS.x86_64-16.0.0-kvm-and-xen-Snapshot20190926.qcow2` generate symlinks like

```
openSUSE-MicroOS.x86_64-kvm-and-xen.qcow2
openSUSE-MicroOS.x86_64-kvm-and.qcow2
openSUSE-MicroOS.x86_64-kvm.qcow2
openSUSE-MicroOS.x86_64-and.qcow2
```

AFAICT that's not caused by the regex itself, but rather that `createrepo_staticlinks` iterates over the links it just created and creates links to them...

**Comment by vmoutoussamy** [comment]
Just for the record, JeOS is affected on https://download.opensuse.org/distribution/leap/15.1/jeos/ and https://download.opensuse.org/tumbleweed/appliances/

**Comment by eduardoj** [comment]
Handled in #8490.
