### ISSUE TITLE
/project/status limits not properly applied

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#850]
I make extensive use of /proect/status (for openSUSE:Factory), usually with the two checkboxes

* Ignore packages with pending requests to openSUSE:Factory
* Limit to currently failing packages

ticked.

There is a small error in case the failure is in a 'linked' package inside the project: even if there is a SR pending against the main package, it is listed as 'failed'. Surprisingly, though, it also notes that an SR is pending for the same.

(current example:
Error java-1_7_0-openjdk-bootstrap 	openSUSE:Factory 	Fails for 12 days: Unknown build failure
Request 281385 to openSUSE:Factory )

**Comment by hennevogel** [comment]
> a 'linked' package inside the project

Can you elaborate what you mean?

**Comment by DimStar77** [comment]
My usecase: use the status page to get an overview of packages in need of work, due to failures.

Let's assume, currently the package java-1_7_0-openjdk-bootstrap fails to build.
This package itself is only a link to java-1_7_0-openjdk inside openSUSE:Factory (so never gets a request on its own)

Setting the status view to limit to failing packages, but excluding packages with pending submissions, should not show java-1_7_0-openjdk-bootstrap once a submission to java-1_7_0-openjdk is pending.

The system does SEE that there was a request (as could be seen in my current example: the status view DID show request 281385 as pending)

**Comment by hennevogel** [comment]
Sorry, it isn't something obvious and I can't read this part of the project controller without seriously thinking about suicide...

**Comment by DimStar77** [comment]
> I can't read this part of the project controller without seriously thinking about suicide...

That's not something we'd want to risk of course

**Comment by bgeuken** [comment]
Didn't test it, myself, but it seems hiberis fixed this already.

=> closing

**Comment by DimStar77** [comment]
I'd be surprised to see this fixed already without anybody explicitly looking at this - but for lack of a current test case I also won't reopen the issue for now
