### ISSUE TITLE
Signature verification failed for file 'repomd.xml'

### ISSUE THREAD

**Issue by dsamx** [openSUSE/open-build-service#8500]
I am building packages in a project and have a test server where the project repo is added so I can install the package immediately with zypper and test it.

I often get the following issue when I want to refresh the repository:

> Signature verification failed for file 'repomd.xml' from repository 'home:myhome'.

    Note: Signing data enables the recipient to verify that no modifications
    occurred after the data were signed. Accepting data with no, wrong or
    unknown signature can lead to a corrupted system and in extreme cases even
    to a system compromise.

    Note: File 'repomd.xml' is the repositories master index file. It ensures
    the integrity of the whole repo.

    Warning: This file was modified after it has been signed. This may have been
    a malicious change, so it might not be trustworthy anymore! You should not
    continue unless you know it's safe.

So whatever OBS created is invalid. I cannot fix it by rebuilding a package (though that creates new repo data).
I also cannot disable the signature verification because then the message is that the repo meta data is invalid.
Please investigate the correctness of the repo generation.
If I don't change the repo and wait one day then the meta data is often correct all of a sudden.

**Comment by AdamMajer** [comment]
This looks like a clock mismatch?

@dsamx do you still see this issue? I would be interested if this is TZ related.

**Comment by dsamx** [comment]
I have not seen it for a longer time now. Clock sync or timezone sounds plausible though I never would have guessed that.
It may be that the OBS server used European or universal timezone and the client system the other way round, which have a difference of 1-2 hours depending on summer time. Thinking of it, waiting for a longer time sometimes seemed to fix the issue, so it could have been that.

**Comment by adrianschroeter** [comment]
it seems the clock on the signing server was off back then ...
