### ISSUE TITLE
setrelease should handle '.sha256' files

### ISSUE THREAD

**Issue by ggardet** [openSUSE/open-build-service#8502]
# Issue Description
Since https://github.com/openSUSE/open-build-service/pull/5486 `setrelease` is supported for kiwi images.
The problem is the `.raw.xz` filename in `.sha256` file is not updated.
E.g. http://download.opensuse.org/ports/aarch64/tumbleweed/images/openSUSE-Tumbleweed-ARM-E20-efi.aarch64-2019.09.16-Snapshot20190925.raw.xz.sha256

But I think it would break the signature. So, not sure how to handle this properly.

Expected Result
============
The `.raw.xz` filename in `.sha256` file should match.

(Currently the filename is missing the `.xz` extension inside the `.sha256` file, but this will be fixed in kiwi: https://github.com/OSInside/kiwi/issues/1223)

**Comment by adrianschroeter** [comment]
it would mean to rewrite .sha256 files and also to resign them. I don't see how we should do so in an efficiant way during release.

sorry, a "WON'TFIX" for me in bugzilla terminology.

**Comment by coolo** [comment]
Then setrelease needs to block if it will obviously not work.

**Comment by adrianschroeter** [comment]
it is working, is coping the files out and you don't want to be blocked. just the verification needs an adapted filename.

**Comment by coolo** [comment]
but what kind of verification is that if you need to know a fake name?

**Comment by adrianschroeter** [comment]
On Montag, 7. Oktober 2019, 15:29:09 CEST Stephan Kulow wrote:
> but what kind of verification is that if you need to know a fake name?

it is not a fake name, it is the original one ;)

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by coolo** [comment]
You know how verification works, right?

**Comment by adrianschroeter** [comment]
On Montag, 7. Oktober 2019, 16:12:31 CEST Stephan Kulow wrote:
> You know how verification works, right?

And you understood that .sha256 files are build artefacts and not publisher 
files, right?

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by coolo** [comment]
that's why I'm saying: setrelease should just block to run on things it can't handle.
