### ISSUE TITLE
Build results: "unresolvable", "broken" and "failed" links green on hover

### ISSUE THREAD

**Issue by cboltz** [openSUSE/open-build-service#8516]
# Issue Description

In the build results (both the box on the right side of a package page, and on the monitor page), the links for "failed", "broken" and "unresolvable" are displayed as red text. However, when you hover these links, they become green (and underlined). Given that the red color indicates a failure, the links should not become green on hover.

Expected Result
============
The link text should stay red (and get underlined) if you hover them.

How to Reproduce
===============
1. Go to https://build.opensuse.org/package/show/home:cboltz/diffuse (or any package page with a build failure)
2. In the "build results" box, over your mouse over the "unresolvable" links
3. See the link becoming green

You'll see the same behaviour on https://build.opensuse.org/project/monitor/home:cboltz (I assume it's using the same CSS, therefore reporting it in the same bugreport.)

**Comment by AshNaz87** [comment]
I have completed the fix, but don't have access rights

**Comment by hennevogel** [comment]
hey @AshNaz87 you don't have access rights for what exactly? See our documentation on [how to contribute code](https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md#how-to-contribute-code) :smile: Looking forward to your pull request!

**Comment by dmarcoux** [comment]
Fixed in #9132
