### ISSUE TITLE
genservicemark: servicemark collisions if projects gets deleted and recreated with the same name

### ISSUE THREAD

**Issue by gollub** [openSUSE/open-build-service#852]
We found something funny: when one deletes a project and recreates it with the same name (this might even apply for packages) the (remote) source-services runs result in "old" generated sources.

Steps to reproduce:

1. Create project Debug:foo
2. Create package Debug:foo/peng
3. Add a _service file like this one:
```
<services>
<service name="git_buildpackage">
  <param name="url">https://github........git</param>
  <param name="revision">master</param>
</service>
</services>
```
(no additional files - or at least none which not going to change .. to reproduce this issue. This source-service also provide the build-desc. To reproduce this with another source-service make sure your build-desc is not getting changed/updated)
4. Commit the _service file
5. Change something on the e.g. git-repo to the sources changes
6. trigger remote service run
7. repeat step 5 and 6 several times
8. delete the Debug:foo project
9. create the Debug:foo project
10. Add the same service-file as in step 3
11. Commit _service file

Expected result: the resulting sources generated/represent the latest master branch.
Actual result: ... instead an older revision of the sources are generated/presented.

I suspect the issue sits here:
https://github.com/openSUSE/open-build-service/blob/master/src/backend/bs_srcserver#L323

The servicemark string of this example would look like this:
```
sourceservice/Debug:foo/peng1aeeffbc1785364bf02da12fdbea7b5fc  _service
````

Which is basically:

```
"sourceservice/Debug:foo/peng"$REV"aeeffbc1785364bf02da12fdbea7b5fc  _service"
```

Only the $REV would change in this scenario ....since the $REV gets reset when deleting the project and getting recreated ... this string is not getting unique.

**Comment by mlschroe** [comment]
Fixed. Thanks for the report!
