### ISSUE TITLE
Unstaging revoked requests gives 403

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8522]
Testing #8507 on build-test I noticed that unstaging a request not in `review` gives a misleading response. It returns a 403, but funnily enough still unstage it from the staging project. 

```
coolo@f102#~>tosc request revoke 1760 -m oops
Result of change request state: ok
coolo@f102#~>tosc ps request delete openSUSE:Factory -s openSUSE:Factory:Staging:A -r 1760
Server returned an error: HTTP Error 403: Forbidden
The request is not in state new or review
coolo@f102#~>tosc -d ps request delete openSUSE:Factory -s openSUSE:Factory:Staging:A -r 1760
DELETE https://api-test.opensuse.org/staging/openSUSE:Factory/staging_projects/openSUSE:Factory:Staging:A/staged_requests
Server returned an error: HTTP Error 400: Bad Request
```

**Comment by vpereira** [comment]
Hi, @coolo coolo, what would be the expected behavior? To forbid revoking a bs_request if it's staged (intrusive, maybe touching the bs_request state machine) or unstage the request anyway (but then not touching the reviews associated with the request) ?

**Comment by coolo** [comment]
The expected behavior is that developers can revoke requests, but they stay staged - but make the staging project unacceptable. That part works.

But the staging manager needs to be able to supersede the request with another one - or remove the package all together. I didn't try superseding yet (due to other issues this is currently broken), but for removing I had to apply a workaround. The expected behavior for that is that the the connection to the staging project is lost, the 'unstaged' event is tracked in history *and* that the sources are cleaned.

**Comment by vpereira** [comment]
@coolo could you please take a look on #8566 ?
