### ISSUE TITLE
Allow to stage an excluded request in one step

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8525]
If I exclude a request, I do so to ease managing the backlog. But once I have free staging projects, I would like to give it a 2nd chance. To do so right now, I need to:

1. remove from excluded requests

1. stage into project of choice

because if I skip to step 2, I'll get:
```
Server returned an error: HTTP Error 400: Bad Request
Assigning requests to openSUSE:Factory:Staging:B failed: Request 114 not found in Staging for project openSUSE:Factory.
```

(which is yet another misleading error, I'd file an issue for this but I prefer if this is solved within the context of this very issue)

I would prefer if I could ACK that it's currently excluded (to avoid races between 2 staging managers, where one excludes a request from backlog and another selects it into a project) and have `add --unignore`

**Comment by coolo** [comment]
Loosely related to #7360

**Comment by vpereira** [comment]
even it's a feature, the issue described while you are skipping the step 1, should be an issue (bug) per se, right? 

The message `Server returned an error: HTTP Error 400: Bad Request
Assigning requests to openSUSE:Factory:Staging:B failed: Request 114 not found in Staging for project openSUSE:Factory.` should go and instead we should say that the request cannot be staged while excluded.

**Comment by coolo** [comment]
That's why I mean with
> (which is yet another misleading error, I'd file an issue for this but I prefer if this is solved within the context of this very issue)

**Comment by dmarcoux** [comment]
Small title edit to be extra clear in terms of the staging workflow glossary.
