### ISSUE TITLE
No cheap way to get the list of staging projects

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8534]
`/staging/openSUSE:Leap:15.2/staging_projects` includes tons of informations for all staging projects, but there is no way to just get the list of staging projects.

I'd suggest that /staging_projects just returns an index and for details you need to query .../staging_projects/...:A

**Comment by coolo** [comment]
`tosc api /staging/openSUSE:Factory/staging_projects` takes 24.8 seconds now

**Comment by coolo** [comment]
`duration=23374.02 view=19766.09 db=3564.14 backend=8674.27`

**Comment by hennevogel** [comment]
This is loosely connected to #8534

**Comment by coolo** [comment]
yes, I think the API should be reevaluated in general.
