### ISSUE TITLE
Searching for a recent created project doesn't return any match

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#8541]
# Issue Description
Search indexes seems not to be updated just after every object (project, package, ...) has been created. This results in no matches searching by their names, just after they have been created.

Now it is needed to wait for the reindexing proccess, that occurs each hour, for that project to be found in the search.

Expected Result
============
Searching for the project that has been just created, returns it as match, without waiting so much as for the next hourly reindex.

How to Reproduce
===============
1. Got to https://build.opensuse.org/
1. Create a project.
1. Search by the name of that project in the search box placed in the upper right corner.
1. See no matches.

Further Information
===============
* Thinking Sphinx: https://freelancing-gods.com/thinking-sphinx/
* Definition of our indexes: https://github.com/openSUSE/open-build-service/tree/master/src/api/app/indices/
* Enabled matches_regex for MySql by jamespearson · Pull Request #36800: https://github.com/rails/rails/pull/36800

**Comment by hennevogel** [comment]
This was fixed in #8558
