### ISSUE TITLE
'entry' vs 'request' in staging APIs

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8542]
/staging_projects has `<entry id=` and /excluded_requests has `<request id=`. I see no reason why this would be different - and I prefer `<request/>`

**Comment by vpereira** [comment]
@coolo we have the `entry` to other elements too, i.e `missing_reviews` and `broken_packages`. Any strong opinion/suggestion about them?

**Comment by coolo** [comment]
everything reprenting a request should be `request` - and for broken_package entry could be fine, but then I wonder why it's

```
  <missing_checks count="2">
    <missing_check name="openqa:cryptlvm" state="pending" required="true"/>
    <missing_check name="installcheck" state="pending" required="true"/>
  </missing_checks>
```

Either it's entry there too - or it's `broken_packages/broken_package`

**Comment by hennevogel** [comment]
Everything that is a request should be `<request...>`, everything that is a package should be `<package...>`.
