### ISSUE TITLE
unexpected metadata removal

### ISSUE THREAD

**Issue by pgajdos** [openSUSE/open-build-service#8543]
I issued a reqms:
https://build.opensuse.org/request/show/736010
which was accepted, then I tried:
```
$ osc linkpac openSUSE:Factory ilmbase graphics ilmbase
Sending meta data...
Done.
Server returned an error: HTTP Error 403: Forbidden
Insufficient permissions to store file in package ilmbase, project graphics
Creating _link... $
```
which removed me from metadata again. Marcus then added me manually, the osc linkpac above removed me as well.

**Comment by adrianschroeter** [comment]
osc bug. fixed here: https://github.com/openSUSE/osc/pull/648
