### ISSUE TITLE
maintenance_incident requests not listed

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#858]
https://build.opensuse.org/project/requests/openSUSE:Maintenance when selecting "maintenance_incident" for display doesn't display anything.

$ osc rq list -t maintenance_incident -s new,review openSUSE:Maintenance

lists several

**Comment by hennevogel** [comment]
The webui is calling Project.request_ids_by_class which is using a user dependent BsRequestCollection (only showing maintenance_incident when you have a role in the source). osc is using /search/request with xpath...
