### ISSUE TITLE
[Help] Setup up OBS worker environment on Centos

### ISSUE THREAD

**Issue by TommyLike** [openSUSE/open-build-service#8585]
# Issue Description
I need to deploy the obs worker on a centos7.6(aarch64) environment, but it seems that all of the packages are based on openSUSE release, is there any guide or method on how to install the obs worker and it's dependencies on centos?

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
