### ISSUE TITLE
[production][meta#update] Mysql2::Error: Duplicate entry '2280904-6' for key 'arch_repo_index': INSERT INTO `repository_arc...

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#8587]
meta#update threw this 0 times
<pre>
Mysql2::Error: Duplicate entry &#39;2280904-6&#39; for key &#39;arch_repo_index&#39;: INSERT INTO `repository_architectures` (`repository_id`, `architecture_id`, `position`) VALUES (2280904, 6, 1)
</pre>
[https://build.opensuse.org/projects/home:IGonzalezSosa:branches:YaST:Head/meta](https://build.opensuse.org/projects/home:IGonzalezSosa:branches:YaST:Head/meta)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5da6d2c00ddb2e0008241051)

**Comment by eduardoj** [comment]
Exception not found in Errbit any more. Closing.
