### ISSUE TITLE
After package is converted to muiltbuild old links are still being created by IBS

### ISSUE THREAD

**Issue by gyr** [openSUSE/open-build-service#8589]
lvm2 request (https://build.suse.de/request/show/202990) was accepted in SLE-15-SP2. It converted it in an multibuild package, however, the links for both, lvm2-clvm and device-mapper, were automatically created by IBS after the request has been accepted. The links needed to be deleted manually later on.

Expected Result
============
After a package has been converted to multibuild, package links should not be created by IBS

**Comment by coolo** [comment]
This sounds like https://github.com/openSUSE/openSUSE-release-tools/issues/1594

**Comment by hennevogel** [comment]
The OBS does not convert anything. Please discuss this in the openSUSE-release-tools thread.
