### ISSUE TITLE
[production][] Cannot read property 'mData' of undefined

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#8591]
threw this 19 times
<pre>
Cannot read property &#39;mData&#39; of undefined
</pre>
[https://build.opensuse.org/package/users/openSUSE:Leap:15.1:Images/opensuse-leap-image](https://build.opensuse.org/package/users/openSUSE:Leap:15.1:Images/opensuse-leap-image)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5d69314124569a000813582d/problems/5da881a4bc234c0008915b4c)

**Comment by coolo** [comment]
this basically hits all /package/users pages if the project defines something - 100% reproducible

**Comment by eduardoj** [comment]
After fixing #8681 it doesn't happen anymore. Closing.
