### ISSUE TITLE
Changelog API

### ISSUE THREAD

**Issue by lkocman** [openSUSE/open-build-service#8609]
**Is your feature request related to a problem? Please describe.**
As a release manager I'd like to have an easy way to see what rpms changed (added, removed, version changed, noarch -> arch, arch -> noarch, moved within products).  Especially on projects with multiple Service Pack inheritance such as SLE.

**Describe the solution you'd like**
I already had a brief conversation about this with Coolo and he told me OBS is the right place to implement this. I'd really like to have a diff against latest BUILD. And possibly also latest published milestone, latest released GA...

**Describe alternatives you've considered**

We're currently manually maintaining list of accepted submissions (not even on RPM level) https://confluence.suse.com/display/SUSELinuxEnterpriseServer12SP5/Build+status+SLE+12+SP5 
time-wise this is expensive, and doesn't really cover maintenance updates.

We can use partially also xcdchck, but that doesn't that is not convenient to process and is available late in the process.

**Additional context**
We should consider using similar changelog dump structure and format as compose-changelog https://pagure.io/compose-utils as most of OEMs are already familiar with.

**Comment by adrianschroeter** [comment]
sorry, this is not something what I can discuss here. Please open a bugzilla or jira issue instead.
