### ISSUE TITLE
Failed to resolve "product_flavor(openSUSE) needed by openSUSE-release" in Dockerfile based container build (Tumbleweed)

### ISSUE THREAD

**Issue by okurz** [openSUSE/open-build-service#8629]
since some days containers in OBS using the Dockerfile fail to fail to resolve due to

```
have choice for product_flavor(openSUSE) needed by openSUSE-release: openSUSE-release-appliance-custom openSUSE-release-appliance-docker openSUSE-release-appliance-hyperv openSUSE-release-appliance-kvm openSUSE-release-appliance-openstack openSUSE-release-appliance-vagrant openSUSE-release-appliance-vmware openSUSE-release-appliance-wsl openSUSE-release-ftp
```

If I set `Prefer: openSUSE-release-appliance-docker` in the project config I get

```
error running container: error creating container for [/bin/sh -c obs-docker-support --install]: time="2019-10-27T15:23:32Z" level=error msg="systemd cgroup flag passed, but systemd support for managing cgroups is not available
```

e.g. in https://build.opensuse.org/package/live_build_log/home:okurz:container/yamllint/containers/x86_64

This is reproducible also when creating a new project based on the wizard following https://build.opensuse.org/image_templates selecting "Templates using openSUSE Tumbleweed", "Container built using docker tool".

By comparison, a container built based on Leap 15.1 seems fine: https://build.opensuse.org/package/show/home:okurz:branches:openSUSE:Templates:Images:15.1/container_test

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.

**Comment by Vogtinator** [comment]
This is not a support request, this is actually a valid report and a dup of https://github.com/openSUSE/obs-build/issues/487.
