### ISSUE TITLE
Changing arch build targets for repositories does not work properly when changing more than one repository

### ISSUE THREAD

**Issue by yaccz** [openSUSE/open-build-service#863]
Changing arch build targets for repositories does not work properly when changing more than one repository

1. open repositories for project.
2. click edit repository, make a change and save
3. click edit repository that's show below the previous one, make a change

You can't save now because the first button has been enabled instead of relevant one.

Workaround: reload the page after every edit.

**Comment by hennevogel** [comment]
![screenshot from 2015-02-16 14 49 35](https://cloud.githubusercontent.com/assets/514785/6212965/0d4ca2ea-b5eb-11e4-81b7-24930b36cf0b.png)

Both forms on that page have the same id and action.
