### ISSUE TITLE
[EPIC] Support external test runners to run checks (e.g. Jenkins)

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#8632]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to easily run tests of a package build on OBS that **fail** the actual build or at least prevent the result from being published.

I am for instance maintaining a bunch of virtual images, that cannot be tested in OBS at all: I rely on an external Jenkins pipeline. It is triggered on each rebuild and tests the resulting boxes. Unfortunately, a pipeline failure does not propagate back to OBS, so as long as the image builds (even if it won't even boot) it will show up as green on OBS and it will overwrite the last good state.

**Describe the solution you'd like**
Something like a configurable webhook, that OBS polls on a successful build and waits for a certain amount of time for a response. If the webhook reports back a success, then everything continues as it currently does, but if it reports back a failure, then the build gets reaped and disappears.

It would be really nice if the webhook could report back some additional information, e.g. an URL to the build result.

**Describe alternatives you've considered**
Running Jenkins (or any other CI system) that listens for url changes to the published repository and runs the builds then. This can be extended via simple bots that report failures on OBS, but that does not fix the issue that broken builds get published and overwrite the old working builds.

**Comment by hennevogel** [comment]
This is already in the making. https://build.opensuse.org/apidocs/index -> Status Checks

**Comment by dcermak** [comment]
I guess this will be announced when it is done, right? And do you have a rough ETA?

**Comment by hennevogel** [comment]
Once this goes out of beta, we'll announce it yes. No ETA, sorry.
