### ISSUE TITLE
Version 2.10 downloads version 2.9.51 and it won't start after installation

### ISSUE THREAD

**Issue by jfha73** [openSUSE/open-build-service#8647]
Hey guys,

I just downloaded the latest version of OBS appliance but instead of saying 2.10, it says 2.9.51, also, after I installed it on a Virtual Machine it won't pass starting the OBS API Setup service, I waited for about 10 min, but it just didn't move.

Any idea what can be causing this?

I'm using VMWare Fusion (fro Mac), VM has 8 cores, 16GB of RAM, 200GB of HDD, which has always worked for me, but not this time.

Thanks.

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
