### ISSUE TITLE
Error 403 Forbidden when Create a project inside my own home branch 

### ISSUE THREAD

**Issue by andykimpe** [openSUSE/open-build-service#866]
create new package on

https://build.opensuse.org/project/new_package/home:andykimpe:avidemux

Name: twolame

Title:  twolame

Description: twolame source centos 6 rpmfusion

click save

redirect https://build.opensuse.org/package/save_new/home:andykimpe:avidemux

403: Forbidden

Sorry but you don't have the necessary permissions for this request. We think it's best if you try to start again from the home page.
Responsive image
In case of emergency...

Let's be honest, we're both not perfect (yet!). But don't despair, as free software project we're commited to work together and collaborate. Here is how we do that.
...we help each other out

On IRC and on the mailing list there is a vibrant community of developers, admins and users that support each other.
...we tell us about problems

In the unfortunate event you've hit a bug in the OBS we depend on you to report them on GitHub.
...we better ourselves

You have an idea how to make OBS better, faster, stronger? Those ideas we call feature and we track them in openFATE.

ps : last night around 21h GMT it functioned fine if he had change between then and now I commend you to remove

**Comment by andykimpe** [comment]
using osc 100% work https://build.opensuse.org/package/live_build_log/home:andykimpe:avidemux/twolame/CentOS_6/i586

this problem seems to come from the web interface only use the osc command works perfect

the insue 865 seems to come from the same problem  https://github.com/openSUSE/open-build-service/issues/865

**Comment by coolo** [comment]
memcached crashed

**Comment by darix** [comment]
JFYI: twolame might not be allowed on build.opensuse.org see: https://en.opensuse.org/openSUSE:Build_Service_application_blacklist

**Comment by andykimpe** [comment]
lol https://build.opensuse.org/package/show?project=home%3Aaevseev&package=ffmpeg
