### ISSUE TITLE
internal error configuring Azure

### ISSUE THREAD

**Issue by bear454** [openSUSE/open-build-service#8675]
# Issue Description

Browsing to https://build.suse.de/cloud/azure/configuration produces a flash:

> There has been an internal error. Please try again.

And redirects back to the prior page.

Expected Result
============

I am allowed to configure my Azure credentials.

How to Reproduce
===============
1. Go to https://build.suse.de/package/binaries/SUSE:SLE-12-SP5:GA/SLES12-SP5-Azure:Basic-On-Demand/images
2. Click on 'Cloud Upload'
3. Under the 'Microsoft Azure' button, click the link 'Configure your credentials _here_'

Further Information
===============
* A link to an OBS instance showing the issue: https://build.suse.de/
* Exact server version: 20191104T130500.a2548ae589

**Comment by dmarcoux** [comment]
Hey @bear454, could you reproduce this on the [public instance of OBS](https://build.opensuse.org/)?

**Comment by eduardoj** [comment]
I can reproduce this error in the public instance of OBS.

**Comment by dmarcoux** [comment]
Let's close this then.
