### ISSUE TITLE
Strange review reason for moving to backlog

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8679]
When moving requests back into backlog (by unstaging), the staging project review is accepted with
```  
<review state="accepted" when="2019-10-09T12:30:53" who="coolo" by_project="openSUSE:Factory:Staging:adi:135">
    <comment>Moved back to project "openSUSE:Factory"</comment>
    <history who="coolo" when="2019-11-08T10:22:39">
      <description>Review got accepted</description>
      <comment>Moved back to project "openSUSE:Factory"</comment>
    </history>
  </review>
```

It's not moving project - nor moving *back* to openSUSE:Factory, as a matter of fact it never left openSUSE:Factory

**Comment by eduardoj** [comment]
What about `Unstaged from project "openSUSE:Factory:Staging:adi:135"`?

**Comment by coolo** [comment]
Yes, an improvement. [currently](https://build.opensuse.org/request/show/720312#status-history-6954538) we use 'Removing from openSUSE:Leap:15.2:Staging:A, re-evaluation needed' - but that's possibly a lie as well, so your text is good
