### ISSUE TITLE
[production][] $(...).popover is not a function

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#8682]
threw this 127 times
<pre>
$(...).popover is not a function
</pre>
[https://build.opensuse.org/request/show/739109#comment-1080034](https://build.opensuse.org/request/show/739109#comment-1080034)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5d69314124569a000813582d/problems/5da87ed0bc234c0008915b49)

**Comment by saraycp** [comment]
We are not paying attention to this kind of JavaScript errors for now.
I close this issue.
