### ISSUE TITLE
[Arch Linux] bs_mkarchrepo: OBS doesn't identify packages with compression algorithms other than GZ and XZ

### ISSUE THREAD

**Issue by 86423355844265459587182778** [openSUSE/open-build-service#8683]
Issue Description
============
When OBS creates the repository for Arch Linux, only `*.pkg.tar.gz` and `*.pkg.tar.xz`will be identified and included in the repository.
If one uses other compression algorithms when packaging (e.g. ZSTD, [supported by Pacman 5.2](https://www.phoronix.com/scan.php?page=news_item&px=Arch-Linux-Pacman-5.2-Released)), OBS will still be able to package, but the user has to manually download the package because it will not be included (listed) in the repository (`*.db`) file.

How to Reproduce
===============
1. Create a package on OBS
2. Use a compression algorithms other than GZ and XZ for packaging, e.g. using `export PKGEXT=".pkg.tar.zst"` in the PKGBUILD
3. After OBS finishes packaging and publishing the repository, see that the `*.db` file does not contain the built package
4. However, in `https://build.opensuse.org/package/binaries/home:someuser/somepackage/somerepo`, you can see that `_buildenv` and `*.pkg.tar.zst` are present and can be downloaded manually

Further Information
===============
* I guess [Line 53](https://github.com/openSUSE/open-build-service/blob/master/src/backend/bs_mkarchrepo#L53) in `/src/backend/bs_mkarchrepo` may be causing this issue. It should probably be adjusted to accept all valid suffixes accepted by makepkg (see https://www.archlinux.org/pacman/makepkg.conf.5.html for details).
* OBS instance showing the issue: https://build.opensuse.org

**Comment by pasbi** [comment]
Is this fixed?
https://github.com/openSUSE/open-build-service/commit/9e0f917b9b2e0f0318382bb4493d31184087277e#diff-6c6de7f4e998c7229fe32ce15b2d60f6

**Comment by adrianschroeter** [comment]
Arch Linux xz support is a feature of OBS 2.11. We could maybe backport it to 2.10.2, but it is not an issue in our production instance.

**Comment by 86423355844265459587182778** [comment]
@pasbi 
Yeah, I can confirm that this bug is fixed by 9e0f917, and this bug can no longer be reproduced on  `build.opensuse.org`.
