### ISSUE TITLE
[production][staging_projects#show] undefined method `staging_projects' for nil:NilClass

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8686]
staging_projects#show threw this 0 times
<pre>
undefined method `staging_projects&#39; for nil:NilClass
</pre>
[https://api.opensuse.org/staging/openSUSE:Leap:15.1/staging_projects/O](https://api.opensuse.org/staging/openSUSE:Leap:15.1/staging_projects/O)"

[See this exception on Errbit](http://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5dc590e4cd4ef600088339ac)

**Comment by coolo** [comment]
api-test does not crash, but returns a strange error:

```
coolo@cleopatra#osc-plugin-factory>tosc api /staging/openSUSE:Factory/staging_projects/O
Server returned an error: HTTP Error 404: Not Found
Couldn't find Project with [WHERE (projects.id not in (0)) AND `projects`.`staging_workflow_id` = ? AND `projects`.`name` = ?]

**Comment by saraycp** [comment]
> api-test does not crash, but returns a strange error:
> 
> ```
> coolo@cleopatra#osc-plugin-factory>tosc api /staging/openSUSE:Factory/staging_projects/O
> Server returned an error: HTTP Error 404: Not Found
> Couldn't find Project with [WHERE (projects.id not in (0)) AND `projects`.`staging_workflow_id` = ? AND `projects`.`name` = ?]
> ```

This seems not to be related to this issue, I'll create a new issue just for this.
