### ISSUE TITLE
Inconsistency between Red Hat 6 and CentOS 6 images

### ISSUE THREAD

**Issue by scantor** [openSUSE/open-build-service#869]
I've been tracking which patch level of RH6 and CentOS 6 are being used for builds at build.opensuse.org, and it looks like they've diverged in that RH6 has been bumped past 6.5 and is pulling in OpenSSL 1.0.1e while CentOS 6 builds are still pulling in OpenSSL 1.0.0, which was originally shipped.

This is fairly significant because packages built on top of 1.0.1e don't run on top of 1.0.0 (the converse is not the case), so having them diverge creates some support problems for projects using the service to provide packages.

Could these be brought into sync, or is this an intentional difference?

**Comment by mdeniz** [comment]
Ping, is this still valid?

**Comment by scantor** [comment]
I think they converged at some point, but well, it's been 2.5 years. I would have to take a look when I get a chance.

**Comment by mdeniz** [comment]
I will close it then, if you find it again just reopen this, many thanks!.
