### ISSUE TITLE
Revert the creation of wrong local links

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8693]
https://github.com/openSUSE/open-build-service/pull/8660 was merged despite I gave quite clear feedback that it's wrong.

If you can't create local links correctly, then just don't, but don't require the client to reverse engineer what you did and fix it. In doubt, add the wanted local links to the staged_request XML.

**Comment by vpereira** [comment]
please @coolo, could you please describe what we should improve there? There is nothing to revert, because before we weren't taking the local links into account. So probably either update this issue or we close it?

**Comment by coolo** [comment]
Right. I prefer 'no taking local links into account' over 'random local links' - so there is something to revert.

**Comment by vpereira** [comment]
I don't see how the local links from the "target package" are "random local links". Do you have any concrete step that we should change here to create the right links without becoming too "Factory" specific?

**Comment by coolo** [comment]
@adrianschroeter @mlschroe can you please advise the team here?
