### ISSUE TITLE
[production][] Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#8701]
threw this 68 times
<pre>
Cannot read property &#39;top&#39; of undefined
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5d69314124569a000813582d/problems/5dc95e7300da160008192ff4)

**Comment by saraycp** [comment]
We are not paying attention to this kind of JavaScript errors for now.
I close this issue.
