### ISSUE TITLE
[api] ThinkingSphinx::SphinxError

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#8707]
# Issue Description
When I create a new Project with the current git master OBS code, I get a Internal Server Error 500.

Expected Result
============
Updating to the current git master with the new indexing should work seemless.

How to Reproduce
===============
1. Install pre sphinx search update mode OBS API
2. Start OBS
3. Create Project
4. Works
5. Update to any git master with new sphinx mode
6. Start OBS
7. Create another Project
8. Internal Server error

Further Information
===============
* Worked with git master 8b6367de59
* Works not with the current git masters like 73a07c2348
* I start the api support scripts with systemctl start obs-api-support.target

**Comment by mmohring** [comment]
`

 $ osc -A https://APIURL meta prj -F CentOS:CentOS-7.7.xml CentOS:CentOS-7.7

Sending meta data...
Server returned an error: HTTP Error 500: Internal Server Error

Request: https://APIURL/source/CentOS%3ACentOS-7.7/_meta
Headers:
status: 500 Internal Server Error
x-request-id: 7f659e0d-2b3e-4053-a9d6-d63326e5cd38
x-powered-by: Phusion Passenger 6.0.1
connection: close
content-length: 131
server: Apache
x-runtime: 0.194706
cache-control: public
date: Tue, 12 Nov 2019 10:26:08 GMT
content-type: application/xml; charset=utf-8`

**Comment by mmohring** [comment]
`
F, [2019-11-12T10:26:08.904140 #3128] FATAL -- : [7f659e0d-2b3e-4053-a9d6-d63326e5cd38] [3128:1377.44] ThinkingSphinx::SphinxError (index 'project_core' does not support INSERT (enabled=1) - REPLACE INTO project_core (id, `name`, `title`, `description`, `sphinx_internal_id`, `sphinx_internal_class`, `sphinx_deleted`, `project_id`, `attrib_type_ids`, `issue_ids`, `linked_count`, `activity_index`, `links_to_other`, `is_devel`, `updated_at`) VALUES (85, 'CentOS:CentOS-7.7', 'CentOS 7.7', 'CentOS 7.7 base project. Currently CentOS 7.7. ', 21, 'Project', 0, 21, (), (), 0, 0, 0, 0, 0)):
F, [2019-11-12T10:26:08.904291 #3128] FATAL -- : [7f659e0d-2b3e-4053-a9d6-d63326e5cd38] [3128:1377.44]   
F, [2019-11-12T10:26:08.904409 #3128] FATAL -- : [7f659e0d-2b3e-4053-a9d6-d63326e5cd38] [3128:1377.44] app/mixins/populate_sphinx.rb:5:in `populate_sphinx'
[7f659e0d-2b3e-4053-a9d6-d63326e5cd38] app/models/project/update_from_xml_command.rb:41:in `run'
[7f659e0d-2b3e-4053-a9d6-d63326e5cd38] app/models/project.rb:585:in `update_from_xml!'
[7f659e0d-2b3e-4053-a9d6-d63326e5cd38] app/controllers/source_project_meta_controller.rb:71:in `block in update'
[7f659e0d-2b3e-4053-a9d6-d63326e5cd38] app/controllers/source_project_meta_controller.rb:65:in `update'
[7f659e0d-2b3e-4053-a9d6-d63326e5cd38] config/initializers/wrap_parameters.rb:38:in `call'

`

**Comment by eduardoj** [comment]
Sphinx indices were changed. To solve your issue please apply the command mentioned in the Release notes: https://github.com/openSUSE/open-build-service/blob/e19ac4ddfa2cf29fce38154fd9a63199c8057e31/ReleaseNotes-2.11#L32-L35

**Comment by adrianschroeter** [comment]
On Dienstag, 12. November 2019, 11:56:53 CET Martin Mohring wrote:
> `
> F, [2019-11-12T10:26:08.904140 #3128] FATAL -- :
> [7f659e0d-2b3e-4053-a9d6-d63326e5cd38] [3128:1377.44]
> ThinkingSphinx::SphinxError (index 'project_core' does not support INSERT
> (enabled=1) - REPLACE INTO project_core (id, `name`, `title`,
> `description`, `sphinx_internal_id`, `sphinx_internal_class`,
> `sphinx_deleted`, `project_id`, `attrib_type_ids`, `issue_ids`,
> `linked_count`, `activity_index`, `links_to_other`, `is_devel`,
> `updated_at`) VALUES (85, 'CentOS:CentOS-7.7', 'CentOS 7.7', 'CentOS 7.7
> base project. Currently CentOS 7.7. ', 21, 'Project', 0, 21, (), (), 0, 0,
> 0, 0, 0)): F, [2019-11-12T10:26:08.904291 #3128] FATAL -- :
> [7f659e0d-2b3e-4053-a9d6-d63326e5cd38] [3128:1377.44] F,
> [2019-11-12T10:26:08.904409 #3128] FATAL -- :
> [7f659e0d-2b3e-4053-a9d6-d63326e5cd38] [3128:1377.44]
> app/mixins/populate_sphinx.rb:5:in `populate_sphinx'
> [7f659e0d-2b3e-4053-a9d6-d63326e5cd38]
> app/models/project/update_from_xml_command.rb:41:in `run'
> [7f659e0d-2b3e-4053-a9d6-d63326e5cd38] app/models/project.rb:585:in
> `update_from_xml!' [7f659e0d-2b3e-4053-a9d6-d63326e5cd38]
> app/controllers/source_project_meta_controller.rb:71:in `block in update'
> [7f659e0d-2b3e-4053-a9d6-d63326e5cd38]
> app/controllers/source_project_meta_controller.rb:65:in `update'
> [7f659e0d-2b3e-4053-a9d6-d63326e5cd38]
> config/initializers/wrap_parameters.rb:38:in `call'

hm, apart from the crash, it is not a good design that we need to wait for
sphinx operations at all on generic OBS api operations (like modify meta or 
sources). I have no numbers about the slow down though ...


-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by mmohring** [comment]
> Sphinx indices were changed. To solve your issue please apply the command mentioned in the Release notes:
> 
> https://github.com/openSUSE/open-build-service/blob/e19ac4ddfa2cf29fce38154fd9a63199c8057e31/ReleaseNotes-2.11#L32-L35

I you have to stop the API and API support scripts, so this does not work on the fly. 
But it worked, tnx.

**Comment by eduardoj** [comment]
> I you have to stop the API and API support scripts, so this does not work on the fly.
> But it worked, tnx.

It shouldn't be needed to stop and start the API support scripts. The `ts:rebuild` task takes a while until it starts reindexing. After that (the index is rebuilt and the indexing starts) the error should not happen any more, even before finishing the indexing.

> I was looking for comments in dist/README.UPDATERS, and did not look into the Release Notes. Sorry.

No problem. I guess we put in `dist/README.UPDATERS` only information regarding upgrades between mayor release versions, and not to the last unstable version. Thanks for your feedback.

**Comment by dmarcoux** [comment]
Closed since the issue is resolved.
