### ISSUE TITLE
can not supersede maintenance request

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/open-build-service#871]
osc sr -s 288448 openSUSE:13.2:Update
WARNING:
WARNING: Project does not accept submit request, request to open a NEW maintenance incident instead
WARNING:
Server returned an error: HTTP Error 400: Bad Request
Superseded by Superseded_by should be set

**Comment by bmwiedemann** [comment]
also
> osc mr -s 288448 openSUSE:13.2:Update
osc mr: no such option: -s
Try 'osc help mr' for info.

**Comment by bmwiedemann** [comment]
It seems, that in spite of the error, SRs were created - pretty confusing

**Comment by bgeuken** [comment]
Please reopen if this is still an issue
