### ISSUE TITLE
Impossible to stage new packages

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8712]
I guess it's all my fault for not requesting changes when PRs are wrong, but just commenting and relying on developers to act sane.

But despite https://github.com/openSUSE/open-build-service/pull/8660#discussion_r342500163 the PR was merged without any such spec (or even testing) - and __of course__ it's broken.

```
GET https://api-test.opensuse.org/request/865?withfullhistory=1
POST https://api-test.opensuse.org/staging/openSUSE:Factory/staging_projects/openSUSE:Factory:Staging:A/staged_requests
Server returned an error: HTTP Error 404: Not Found
Date: Wed, 13 Nov 2019 09:36:23 GMT
Server: Apache
Strict-Transport-Security: max-age=31536000
Cache-Control: no-cache
Vary: Accept-Encoding
Referrer-Policy: strict-origin-when-cross-origin
X-Permitted-Cross-Domain-Policies: none
X-XSS-Protection: 1; mode=block
X-Opensuse-Runtimes: {"view":3.8929651491343975,"db":13.111703097820282,"backend":0}
X-Request-Id: a29baac7-ce82-4d05-b490-d87e2e3955ac
X-Opensuse-APIVersion: 2.11~alpha.20191113T100419.2c03dde8da
X-Download-Options: noopen
X-Runtime: 0.071354
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Opensuse-Errorcode: unknown_package
X-Powered-By: Phusion Passenger 6.0.4
Status: 404 Not Found
Cache-Control: public
Content-Type: application/xml; charset=utf-8
Connection: close
Transfer-Encoding: chunked


b'<status code="unknown_package">\n  <summary>openSUSE:Factory/nodejs-underscore</summary>\n</status>\n'
openSUSE:Factory/nodejs-underscore
```

And @dmarcoux, sorry if my language is not optimistic - I'm not.

**Comment by vpereira** [comment]
please don't assume the PR was closed without any testing. If you read the PR, the specs would be written later, specially because it would touch the same files which we were touching in a different PR..

**Comment by coolo** [comment]
Hi @vpereira!

I don't assume the PR did not get testing for 'if the target package does not yet exist' (quoting from my comment), I know for a fact. Hint: it's broken.

And your contribution guide link is about code reviews, I'm not reviewing your code - I'm reviewing your deliverable as customer. And it's broken. No need to hide anything about it.

**Comment by vpereira** [comment]
in my development environment

stage:

```
1b5faf2e0933:~/osc # dosc -v ps request add home:Admin -s home:Admin:Staging:A -r 2
makeurl: http://frontend:3000 ['staging', 'home:Admin', 'staging_projects', 'home:Admin:Staging:A', 'staged_requests'] []
WARNING: SSL certificate checks disabled. Connection is insecure!
Request 2 added to home:Admin:Staging:A
```

unstage:

```
1b5faf2e0933:~/osc # dosc -v ps request delete home:Admin -s home:Admin:Staging:A -r 2
makeurl: http://frontend:3000 ['staging', 'home:Admin', 'staging_projects', 'home:Admin:Staging:A', 'staged_requests'] []
WARNING: SSL certificate checks disabled. Connection is insecure!

Request 2 deleted from home:Admin:Staging:A
1b5faf2e0933:~/osc # 
```

**Comment by vpereira** [comment]
> And your contribution guide link is about code reviews, I'm not reviewing your code - I'm reviewing your deliverable as customer. And it's broken. No need to hide anything about it.

Not sure if you really believe that those values are something that we just care on review, but not in bug requests: 

Be respectful to each other: We are in this together!
Be humble: Reviews aren't about showing off (Example: "I'm not sure - let's look it up.")
Be explicit: People don't always understand your intentions online.
Be careful about the use of sarcasm: Everything we do is public; what seems like good-natured kidding to you and a long-time friend, might come off as mean and unwelcoming to a person new to the project

**Comment by coolo** [comment]
> in my development environment
> 
How it looks in your test instance, you can see above.

**Comment by vpereira** [comment]
Hi @coolo!

**Be explicit: People don't always understand your intentions online.**

Please start to give more information about 

a) what you are trying to do (we don't use your osc plugging, we don't test it)
b) what is the setup that you have (maybe i will have to replicate a specific environment to be able to reproduce it)
c) how to reproduce it? Better in an isolated way (without having to setup your plugging)

**Comment by coolo** [comment]
You see the API calls above.

Staging request 865 into A on api-test:

```
GET https://api-test.opensuse.org/request/865?withfullhistory=1
POST https://api-test.opensuse.org/staging/openSUSE:Factory/staging_projects/openSUSE:Factory:Staging:A/staged_requests
```

**Comment by coolo** [comment]
confirmed as fixed on api-test, thanks
