### ISSUE TITLE
[production][workflows#show] No route matches {:action=>"show", :controller=>"webui/project", :id=>"28", :project=>nil}, possi...

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8714]
workflows#show threw this 1 times
<pre>
No route matches {:action=&gt;&quot;show&quot;, :controller=&gt;&quot;webui/project&quot;, :id=&gt;&quot;28&quot;, :project=&gt;nil}, possible unmatched constraints: [:project]
</pre>
[https://build.opensuse.org/staging_workflows/28](https://build.opensuse.org/staging_workflows/28)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5dccb46703a7750008ba90ff)

**Comment by coolo** [comment]
There are 4 such staging workflows in the database - all of them have 'test' as staging-manager group. I don't see why project_id can be NULL

**Comment by coolo** [comment]
'test' group is exclusive to @lethliel btw

**Comment by eduardoj** [comment]
This happens when creating a staging workflow for a project that already has one. Working on it.
