### ISSUE TITLE
osc rq list --exclude-target-project => results in error

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#872]
osc rq list --exclude-target-project results in a server error 400:

> osc -d rq list GNOME:Next rygel --exclude-target-project=GNOME:Next
> GET https://api.opensuse.org/search/request?match=%28state%2F%40name%3D%27declined%27+or+state%2F%40name%3D%27new%27+or+state%2F%40name%3D%27review%27%29+and+%28action%2Ftarget%2F%40project%3D%27GNOME%3ANext%27+or+submit%2Ftarget%2F%40project%3D%27GNOME%3ANext%27+or+action%2Fsource%2F%40project%3D%27GNOME%3ANext%27+or+submit%2Fsource%2F%40project%3D%27GNOME%3ANext%27%29+and+%28action%2Ftarget%2F%40package%3D%27rygel%27+or+submit%2Ftarget%2F%40package%3D%27rygel%27+or+action%2Fsource%2F%40package%3D%27rygel%27+or+submit%2Fsource%2F%40package%3D%27rygel%27%29+and+%28not%28action%2Ftarget%2F%40project%3D%27GNOME%3ANext%27+or+submit%2Ftarget%2F%40project%3D%27GNOME%3ANext%27%29%29
> Server returned an error: HTTP Error 400: Bad Request
> Date: Wed, 04 Mar 2015 10:49:30 GMT
> Server: Apache/2.2.12 (Linux/SUSE)
> Strict-Transport-Security: max-age=31536000
> X-Frame-Options: SAMEORIGIN
> X-XSS-Protection: 1; mode=block
> X-Content-Type-Options: nosniff
> X-Opensuse-APIVersion: 2.6.51.git20150223.782706b
> X-Opensuse-Errorcode: illegal_xpath_error
> X-Opensuse-Runtimes: {"view":9.332220000000001,"db":0.638817,"backend":0,"xml":0}
> Vary: Accept-Encoding
> Cache-Control: no-cache
> X-Request-Id: 2483934d-23bc-42c9-8770-6b95e86ab6f5
> X-Runtime: 0.024348
> X-Powered-By: Phusion Passenger 4.0.53
> Status: 400 Bad Request
> Content-Type: application/xml; charset=utf-8
> Set-Cookie: _session_id=d32fc2be46170cc78ec3c45b569ad517; path=/; expires=Thu, 05 Mar 2015 10:49:30 -0000; HttpOnly
> Connection: close
> Transfer-Encoding: chunked

<status code="illegal_xpath_error">
  <summary>

illegal token: ':or'</summary>

</status>

illegal token: ':or'

**Comment by DimStar77** [comment]
(the same issue had been reported against osc already, but Marcus meant it's likely a backend change causing this)
https://github.com/openSUSE/osc/issues/112

**Comment by marcus-h** [comment]
On 2015-03-04 02:51:40 -0800, Dominique Leuenberger wrote:
> (the same issue had been reported against osc already, but Marcus meant it's likely a backend change causing this)
s/backend/api/
At least it worked some time ago (I haven't had a look at the xpath_engine
code yet).

**Comment by coolo** [comment]
for those not speaking hex, I'll translate it :)

match=(state/@name='declined' or state/@name='new' or state/@name='review') and (action/target/@project='GNOME:Next' or submit/target/@project='GNOME:Next' or action/source/@project='GNOME:Next' or submit/source/@project='GNOME:Next') and (action/target/@package='rygel' or submit/target/@package='rygel' or action/source/@package='rygel' or submit/source/@package='rygel') and (not(action/target/@project='GNOME:Next' or submit/target/@project='GNOME:Next'))

**Comment by DimStar77** [comment]
osc rq list without --exlclude target looks 'exactly' the same, minus the last 'and (not([...]))' part

**Comment by mdeniz** [comment]
I tried to reproduce the error but wasn't able. Closing it, if still valid for you please reopen.
