### ISSUE TITLE
Repotype: vagrant creates invalid version

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#8721]
# Issue Description

We have recently discovered that some of the Kubic/MicroOS vagrant boxes have a broken version entry in the json file that is generated by the publisher.

For example:
- http://download.opensuse.org/tumbleweed/appliances/boxes/openSUSE-MicroOS.x86_64-Kubic.json, `version: "kubeadm.20191112"`
- http://download.opensuse.org/tumbleweed/appliances/boxes/openSUSE-MicroOS.x86_64.json, `version: "ContainerHost.20191112"`

on the other hand:
- http://download.opensuse.org/tumbleweed/appliances/boxes/openSUSE-MicroOS.x86_64-Vagrant.json has the "correct" `version: "16.0.0.20191112"` (correct in the sense that this is the one I would have expected all json files to have).

This is an issue, because these boxes are thereby **not** consumable by Vagrant. With the following `Vagrantfile`:
``` ruby
Vagrant.configure("2") do |config|
  config.vm.box = "openSUSE-MicroOS.x86_64.json"
  config.vm.box_url = "http://download.opensuse.org/tumbleweed/appliances/boxes/openSUSE-MicroOS.x86_64.json"
end
```
and runing: `vagrant up`, you'll get this error:
``` ShellSession
dan@Boreas:/tmp/test:[0]> vagrant  up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Box 'openSUSE-MicroOS.x86_64.json' could not be found. Attempting to find and install...
    default: Box Provider: libvirt
    default: Box Version: >= 0
==> default: Loading metadata for box
'http://download.opensuse.org/tumbleweed/appliances/boxes/openSUSE-MicroOS.x86_64.json'
    default: URL: http://download.opensuse.org/tumbleweed/appliances/boxes/openSUSE-MicroOS.x86_64.json
A version of the box you're loading is formatted in a way that
Vagrant cannot parse: 'ContainerHost.20191112'. Please reformat the version
to be properly formatted. It should be in the format of
X.Y.Z.
dan@Boreas:/tmp/test:[1]>
```

The three boxes should actually have the same version, because they come from the same package: [openSUSE-MicroOS](https://build.opensuse.org/package/show/openSUSE:Factory/openSUSE-MicroOS).

Expected Result
============
The `version` field should be ideally equal in all produced json files. At least it **must** be a valid version and not contain strings, as Vagrant otherwise chokes on the json file and makes the boxes unusable.

**Comment by dcermak** [comment]
Any updates on this? This is currently preventing us from publishing the Vagrant boxes of Kubic and ContainerHost and makes these boxes unusable on download.opensuse.org on top of that.

@mlschroe Could you please take a look? I believe you wrote the backend.

**Comment by mlschroe** [comment]
It tries to guess the version from the box url. Seems I need to make some regexes a bit stricter.

**Comment by mlschroe** [comment]
So it's because your profile names contain a '-' character, which is kindof unexpected. I can add a workaround.

**Comment by mlschroe** [comment]
Ok, seems to work now.

**Comment by dcermak** [comment]
@sysrich @Vogtinator FYI:

> So it's because your profile names contain a '-' character, which is kindof unexpected. I can add a workaround.

**Comment by dcermak** [comment]
> Ok, seems to work now.

Thank you for the quick fix!
