### ISSUE TITLE
project xml schema mentions non existant attributes `created` and `updated`

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#8725]
# Issue Description

The API [documentation/schema](https://build.opensuse.org/apidocs/project.rng) of the project xml element mentions the optional `created` and `updated` attributes.

I have tried setting them (both via the webUI and the API), but they are not retained by OBS, it appears to forget them immediately.

Expected Result
============

I would have guessed that the `created` and `updated` elements would be set automatically and writing them would result in an error. Or that OBS rejects invalid dates (it currently does not). It is also odd that the value written to the field is simply discarded.

Further Information
===============
* A link to an OBS instance showing the issue: build-test.opensuse.org

**Comment by coolo** [comment]
I updated the title to map to the real problem

**Comment by dcermak** [comment]
So the docs are wrong?

**Comment by coolo** [comment]
Well, wrong is such a strong word - they are outdated by a decade :)

In 6bd223409c15078beafa11e48ef6127418cd58eb the code still matched the schema - but XML validation was disabled shortly after and d580c3ff05cb75d13c9f8b067b7e4eb81a020ced removed these attributes only from the code.

**Comment by adrianschroeter** [comment]
in any case it must not be possible to set them via the api. so it is good that they are not visible anymore, we should just cleanup the schema.

**Comment by dcermak** [comment]
Am I correct in the assumption that both attributes are also no longer used in the [package element](https://build.opensuse.org/apidocs/package.rng)?

**Comment by coolo** [comment]
right
