### ISSUE TITLE
It shouldn't be possible to stage the same package name twice

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8730]
As packages are linked, they overwrite each other - so having 2 requests for the same target package is plainly impossible. Still the API doesn't catch it and happily tracks 2 requests for the same package in the same staging project.

**Comment by coolo** [comment]
![screencapture-build-test-opensuse-org-staging-workflows-1-staging-projects-openSUSE-Factory-Staging-adi-17-2019-11-18-12_16_08](https://user-images.githubusercontent.com/1067203/69049284-cd116080-09ff-11ea-8f3c-4010a0f13917.png)

**Comment by eduardoj** [comment]
We will work on returning an error.

**Comment by coolo** [comment]
We just had the case again and there is a `:bad_request` returned - but the request is still staged. This is in some sense even worse
