### ISSUE TITLE
Excluded request api is having 'number' - everywhere it's 'id'

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8732]
docs/api/api/create_excluded_requests.xml has
```
<excluded_requests>
  <request number='33' description='invalid request'/>
</excluded_requests>
```

For the sake of consistency, this should be `id=`

**Comment by coolo** [comment]
Just noticed that staging requests also requires `<requests><number>` - as discussed in https://github.com/openSUSE/open-build-service/issues/8542#issuecomment-5415715 I assume it should be `<requests><request>` - shall I create an extra issue for that?

**Comment by eduardoj** [comment]
Nops. Nice that you tell this here. One issue is enough.
