### ISSUE TITLE
Backlog link in staging dashboard link to staging group

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/open-build-service#8745]
On staging dashboard, the "backlog" link goes to https://build.opensuse.org/group/show/factory-staging, which is not really useful. Somethink like https://build.opensuse.org/staging_workflows/136/excluded_requests but for "backlog" request would be great.

**Comment by hennevogel** [comment]
Why are those not useful? Because the incoming requests for this group is what possibly needs to be staged right?

**Comment by fcrozat** [comment]
I wasn't precise enough: it goes to the "Group members" tab of factory-staging, which is not useful at all. At minimum, following the backlog link should go directly to the "incoming reviews" tab (and this tab lists not only the backlog, including "excluded / ignored" submissions (without any UI to distinguish them) making it not really useful.

**Comment by hennevogel** [comment]
thank you @fcrozat :smile:

**Comment by dmarcoux** [comment]
When the PR linked above is merged, the `Backlog` link on a staging workflow page will then go to the `Incoming Reviews` tab of a group. @fcrozat, would that be enough to close this issue?

**Comment by fcrozat** [comment]
> When the PR linked above is merged, the `Backlog` link on a staging workflow page will then go to the `Incoming Reviews` tab of a group. @fcrozat, would that be enough to close this issue?

yes, this is perfect !
