### ISSUE TITLE
Project log history for staging projects incorrect

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8748]
https://build.opensuse.org/staging_workflows/136/staging_projects/openSUSE:Leap:15.2:Staging:A says:

- Unstaged request #749300 for package fwupd submitted by coolo-factory
- Staged request #749311 for package ceph submitted by coolo-factory
- Staged request #749300 for package fwupd submitted by coolo-factory
- Staged request #749174 for package python-PyJWT submitted by coolo-factory
- Staged request #745366 for package python-ecdsa submitted by coolo-factory
- Staged request #749299 for package curl submitted by coolo-factory
- Staging project created about 2 months ago by coolo

Point is: none of these requests was submitted by coolo-factory

**Comment by DavidKang** [comment]
Right, `coolo-factory` was who staged/unstaged the requests.
