### ISSUE TITLE
Staging dashboard redundant project name

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#8787]
Looking at the staging dashboard of 15.2 the screen is pretty busy and certainly costs brain power to digest. More than the old one.
![staging](https://user-images.githubusercontent.com/722232/69709243-59590d00-10fd-11ea-8c41-b237077a6e58.png)

There is a headline stating "Staging for openSUSE Leap 15.2". But then all rows in the table have openSUSE:Leap:15.2 again. Looks redundant, eg "A" should be sufficient.

**Comment by DavidKang** [comment]
@lnussel, we added the full name of the project on purpose, because it is possible to add as `staging project` other projects that are not a subproject of `openSUSE:Leap:15.2`.

**Comment by coolo** [comment]
Can you make a special case for the staging projects as we use it? How about a staging nick name for every staging?

**Comment by hennevogel** [comment]
Well we can certainly cover the case of subprojects and use only `Staging:A`. I doubt it helps much with the busy factor of this page...

**Comment by coolo** [comment]
Well, I think it does a big difference: 
 
Before:
![screencapture-file-space-Downloads-Staging-SP2-html-2019-11-27-15_52_53](https://user-images.githubusercontent.com/1067203/69733800-38f57680-112e-11ea-8114-4e31eb509432.png)

With taken the old approach:
![screencapture-file-suse-coolo-Downloads-Staging-for-SUSE-SLE-15-SP2-GA-SUSE-Internal-OBS-Instance-html-2019-11-27-15_52_22](https://user-images.githubusercontent.com/1067203/69733808-401c8480-112e-11ea-9db0-a1c64cb518a1.png)

**Comment by lnussel** [comment]
absolutely :+1:

**Comment by hennevogel** [comment]
We can just display the tile/description and you can set there whatever you want.
