### ISSUE TITLE
Patchinfo allows duplicated issues

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#8798]
# Issue Description
Creating or editing a patchinfo allows the same issue (kde#123456 i. e.) to be introduced more than once.
![Screenshot from 2019-11-27 14-09-57](https://user-images.githubusercontent.com/24919/69725933-a9e16200-111f-11ea-9465-51af89f809ea.png)

Expected Result
============
Entering an already entered issued should not be allowed.

How to Reproduce
===============
1. Create a project.
1. Click on 'Create Patchinfo'.
1. Scroll down to 'Issues'.
1. Enter `kde#123456` and click on 'Add issues'.
1. Repeat the previous step a couple of times.
1. Click on the 'Save' button.

Either the issue should not be allowed to be entered after clicking in 'Add issues', or clicking in 'Save' should result in an error, with some message like 'Issue duplicated'.

Further Information
===============

**Comment by dmarcoux** [comment]
Submitting at once the same issue multiple times removes the duplicates which were entered by the user. However, as described in the issue, it's possible to add the same issue multiple times by adding them one by one.
