### ISSUE TITLE
Allow to add duplicated review in a request

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#8799]
# Issue Description
In a request, we can add a review for the same requester (user, group, project or package) more than once.
![Screenshot_2019-11-27 Request 8 (review)(1)](https://user-images.githubusercontent.com/1212806/69726289-82d76000-1120-11ea-9367-8e9b5da21bad.png)

Expected Result
============
Don't allow to add again the same review if it already exists an open review.

How to Reproduce
===============
1. Go to a request
2. Click on 'Add a review'
3. Fill the form and click on 'Accept'
3. Repeat step 2 and 3
4. See the duplicated review

**Comment by hennevogel** [comment]
Why not?

**Comment by DavidKang** [comment]
I don't see the benefit or use case to have 2 or more open reviews at the same time for the same person.

**Comment by hennevogel** [comment]
Well that doesn't mean there is one. I don't see the harm and no one complained. I would leave it be...

**Comment by DavidKang** [comment]
okey, then I will close the issue :slightly_smiling_face:
