### ISSUE TITLE
staging workflow does not show complete build fail information if it was failed on multiple archs

### ISSUE THREAD

**Issue by nilxam** [openSUSE/open-build-service#8802]
# Issue Description
A package build failed on x86_64 and i586(example here is mbedtls), dashboard only only listed `i586 build failed`.

<pre>
maxlin_factory@tigercity:~/osc-plugin-factory> osc r openSUSE:Leap:15.2:Staging:D mbedtls
standard             i586       failed
standard             x86_64     failed
</pre>

The `broken_packages` entry only listed i586 arch for mbedtls maybe it's the root cause here.

    maxlin_factory@tigercity:~/osc-plugin-factory> osc api /staging/openSUSE:Leap:15.2/staging_projects/openSUSE:Leap:15.2:Staging:D?requests=1\&status=1
    <staging_project name="openSUSE:Leap:15.2:Staging:D" state="failed">
      <staged_requests count="16">
        <request id="750327" type="submit" creator="origin-manager" state="review" package="djvulibre" superseded_by="" updated="2019-11-27T06:10:42Z"/>
        <request id="750348" type="submit" creator="origin-manager" state="review" package="yast2-firstboot" superseded_by="" updated="2019-11-27T06:10:45Z"/>
        <request id="750349" type="submit" creator="origin-manager" state="review" package="libstorage-ng" superseded_by="" updated="2019-11-27T06:10:47Z"/>
        <request id="750350" type="submit" creator="origin-manager" state="review" package="yast2-ntp-client" superseded_by="" updated="2019-11-27T06:10:51Z"/>
        <request id="750351" type="submit" creator="origin-manager" state="review" package="yast2-pkg-bindings" superseded_by="" updated="2019-11-27T06:10:53Z"/>
        <request id="750352" type="submit" creator="origin-manager" state="review" package="installation-images" superseded_by="" updated="2019-11-27T06:10:59Z"/>
        <request id="750353" type="submit" creator="origin-manager" state="review" package="autoyast2" superseded_by="" updated="2019-11-27T06:11:02Z"/>
        <request id="750354" type="submit" creator="origin-manager" state="review" package="linuxrc" superseded_by="" updated="2019-11-27T06:11:05Z"/>
        <request id="750355" type="submit" creator="origin-manager" state="review" package="yast2-registration" superseded_by="" updated="2019-11-27T06:11:08Z"/>
        <request id="750356" type="submit" creator="origin-manager" state="review" package="yast2-bootloader" superseded_by="" updated="2019-11-27T06:11:11Z"/>
        <request id="750357" type="submit" creator="origin-manager" state="review" package="yast2-network" superseded_by="" updated="2019-11-27T06:11:14Z"/>
        <request id="750358" type="submit" creator="origin-manager" state="review" package="yast2-installation" superseded_by="" updated="2019-11-27T06:11:16Z"/>
        <request id="750359" type="submit" creator="origin-manager" state="review" package="yast2-storage-ng" superseded_by="" updated="2019-11-27T06:11:20Z"/>
        <request id="750360" type="submit" creator="origin-manager" state="review" package="yast2-add-on" superseded_by="" updated="2019-11-27T06:11:23Z"/>
        <request id="750361" type="submit" creator="origin-manager" state="review" package="yast2" superseded_by="" updated="2019-11-27T06:11:26Z"/>
        <request id="750473" type="submit" creator="origin-manager" state="review" package="kdepim-runtime" superseded_by="" updated="2019-11-27T06:11:28Z"/>
      </staged_requests>
      <untracked_requests count="0"/>
      <obsolete_requests count="0"/>
      <missing_reviews count="0"/>
      <building_repositories count="0"/>
      <broken_packages count="1">
        <package package="mbedtls" project="openSUSE:Leap:15.2:Staging:D" state="failed" repository="standard" arch="i586"/>
      </broken_packages>
      <checks count="1">
        <check name="installcheck" required="true">
          <state>success</state>
          <short_description/>    <url>https://botmaster.suse.de/go/tab/build/detail/Leap.Staging.D/42/Checks/1/Repo.Checker#tab-console</url>
        </check>
      </checks>
      <missing_checks count="1">
        <check name="openqa:cryptlvm" state="pending" required="true"/>
      </missing_checks>
    </staging_project>

Expected Result
============
If package build failed on multiple archs, dashboard should shows that in the Problems session

How to Reproduce
===============
1. Go to https://build.opensuse.org/staging_workflows/136
2. See *Problems* session of openSUSE:Leap:15.2:Staging:D , there is `mbedtls: failed (i586)`
3. Click https://build.opensuse.org/package/show/openSUSE:Leap:15.2:Staging:D/mbedtls , it build failed on both x86_64 and i586 actually.

**Comment by coolo** [comment]
This is a regression caused by https://github.com/openSUSE/open-build-service/pull/8521 fixing https://github.com/openSUSE/open-build-service/issues/7362

**Comment by coolo** [comment]
I'm afraid the PR's logic needs to be reverted - especially the missing API output hurts.
