### ISSUE TITLE
Editing issue_tracker list not possible

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#881]
It seems impossible to edit the issue_tracker list and deactivate the enable-fetch values.
I observe, with build.opensuse.org:
```
> osc api /issue_trackers >x
> osc api -T x /issue_trackers
Server returned an error: HTTP Error 404: Not Found
```
What I would have expected: 403 Permission Denied.

I observe, with a personal instance where I have admin right:
```
Server returned an error: HTTP Error 404: Not Found
```
What I would have expected: let it succeed.

**Comment by bgeuken** [comment]
Looks like osc defaults to PUT requests for write operations (see osc help api). That's okay for changing existing trackers. For creating new ones you need to use PUT.

To create a new issue you would run this as POST request:
  api  -X POST -T some_file /issue_trackers
Updating an existing tracker would be send as PUT:
  api  -X PUT -T some_file /issue_trackers/$some_tracker_name

Note that changes to issue trackers are processed via delayed jobs. That means changes don't apply immediately but once delayed jobs queue got processed.
