### ISSUE TITLE
Edit  / Delete option in staging

### ISSUE THREAD

**Issue by aginies** [openSUSE/open-build-service#8829]
On the new staging web page (SLE15SP2), there are two new options which are not really safe on the Web page:
Edit and also Delete the Staging.
Of course clicking on this can cause a lot of trouble, especially the delete one, so it would be nice that there is a confirmation dialog box, or maybe this option should be remove from the main page or hidden somewhere else...
Error can be done by human.

**Comment by hennevogel** [comment]
Edit

![Screenshot from 2020-04-21 15-19-21](https://user-images.githubusercontent.com/514785/79870606-84613780-83e3-11ea-8e79-f1c22501296c.png)

and delete

![Screenshot from 2020-04-21 15-18-57](https://user-images.githubusercontent.com/514785/79870553-71e6fe00-83e3-11ea-9e71-e0a18a8c5d56.png)

What exactly do you miss?

**Comment by hennevogel** [comment]
I guess we can close this...
