### ISSUE TITLE
[production][request#show] Invalid id given: CapabilityBoundingSet=```

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#8853]
request#show threw this 4 times
<pre>
Invalid id given: CapabilityBoundingSet=```
</pre>
[https://build.opensuse.org/request/show/754580](https://build.opensuse.org/request/show/754580)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5dee2a5c2236a400085c1673)

**Comment by coolo** [comment]
Same as https://github.com/openSUSE/open-build-service/issues/8822 - errbit is just unusable since spammed with javascript

**Comment by vpereira** [comment]
It is not a bug. There was some tool which was crawling obs (reading some pages and submitting it) and some how it was setting the wrong read fields while trying to submit it back.

**Comment by coolo** [comment]
No, fixed in https://github.com/openSUSE/open-build-service/pull/8937
