### ISSUE TITLE
Version comparison for project status page is off

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#887]
On the project status page https://build.opensuse.org/project/status?project=openSUSE%3AFactory , one may find an entry's summary like "New upstream 1.2 is available". Such a summary will be shown even when the Version: line in the .spec file carries the string "1.2.g3". The reason for this is that the version comparison is done using ruby's version logic, which considers 1.2.g3 older than 1.2, which is opposite to what rpm and zypper vcmp would yield.
I ask for correction.

**Comment by ChrisBr** [comment]
@adrianschroeter you rejected the PR back then, can we close this issue?

**Comment by hennevogel** [comment]
sure
