### ISSUE TITLE
[production][patchinfo#new_tracker] undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#8872]
patchinfo#new_tracker threw this 7 times
<pre>
undefined method `each&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/patchinfo/new_tracker?project=home%3Aenavarro_suse%3Atest](https://build.opensuse.org/patchinfo/new_tracker?project=home%3Aenavarro_suse%3Atest)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5df391a22cefbb000820b149)

**Comment by eduardoj** [comment]
The exception happens when introducing a duplicated issue in the "Edit Patchinfo" page.

**Comment by dmarcoux** [comment]
Oh, it's surely due to the changes in #8858.
