### ISSUE TITLE
Icon urls returned via the /distributions route result in 404 errors

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#8884]
The `/distributions` route returns urls for icons for each distribution, but unfortunately all urls that I tried result in 404 errors. The icons work via the webUI, so maybe some setting is outdated?

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
