### ISSUE TITLE
Allow search for requests

### ISSUE THREAD

**Issue by celan** [openSUSE/open-build-service#889]
Currently submit and other requests cannot be directly searched in the Build Service search field. Something like "r#47111" might be sensible.

**Comment by coolo** [comment]
I have a chromium search (whatever it is called exactly) - if I type rq 47111 in my chromium, it expands to https://build.opensuse.org/request/show/%s

**Comment by hennevogel** [comment]
Regardless of that, requests and their data should be searchable

**Comment by ChrisBr** [comment]
@celan you can search for ```#NUMBER`` and it will redirect to the request show page.
E.g. ```#535868```
