### ISSUE TITLE
[Archlinux] update OBS for new zstd change, now packages end with *.pkg.tar.zst

### ISSUE THREAD

**Issue by mmetak** [openSUSE/open-build-service#8895]
As the title says arch recently changes the package compression to `zstd` and now packages end with `.pkg.tar.zst`.

https://lists.archlinux.org/pipermail/arch-dev-public/2019-December/029739.html

Does this mean that all these lines `my @binsufs = qw{rpm deb pkg.tar.gz pkg.tar.xz};` have to be edited to add `pkg.tar.zst`? And also `pkg\.tar\.gz|pkg\.tar.xz`?

**Comment by pfactum** [comment]
I guess due to this transition all the Arch build are completely broken.

**Comment by mmetak** [comment]
@pfactum https://github.com/openSUSE/open-build-service/pull/8907  ;-)

**Comment by mmetak** [comment]
@adrianschroeter Hello. What about all these lines? Shouldn't they also be updated?
If not, then please just ignore this post. thanx

https://github.com/openSUSE/open-build-service/blob/50c4158ebf1f7f729d8d4e7734eec527090ef861/src/backend/bs_mkarchrepo#L53
https://github.com/openSUSE/open-build-service/blob/10c70d2a9030a1cc14ccdb9165d57994f49980e8/src/backend/BSSched/BuildJob/Import.pm#L27
https://github.com/openSUSE/open-build-service/blob/d9a6712acc627458dfb3edde05ae239c8138565c/src/backend/bs_publish#L1890
https://github.com/openSUSE/open-build-service/blob/da76ed63fcb793d468a42fcbf7dfafdd136258fd/src/backend/BSSched/BuildJob/Aggregate.pm#L34
https://github.com/openSUSE/open-build-service/blob/da76ed63fcb793d468a42fcbf7dfafdd136258fd/src/backend/BSSched/BuildJob/Aggregate.pm#L37
https://github.com/openSUSE/open-build-service/blob/50c4158ebf1f7f729d8d4e7734eec527090ef861/src/backend/BSSched/BuildJob/Package.pm#L27
https://github.com/openSUSE/open-build-service/blob/3aae1fee42fe92c4b47ca0149d82ab494ec0382e/src/backend/bs_signer#L469
https://github.com/openSUSE/open-build-service/blob/3aae1fee42fe92c4b47ca0149d82ab494ec0382e/src/backend/bs_signer#L550
https://github.com/openSUSE/open-build-service/blob/db1ed775fb88d9bcab137f7c6c8837f6f88c31a2/src/backend/BSSched/BuildResult.pm#L66
https://github.com/openSUSE/open-build-service/blob/bf38a01831554ec7b267109c519101553bba2ba7/src/backend/BSSched/BuildRepo.pm#L96
https://github.com/openSUSE/open-build-service/blob/d9a6712acc627458dfb3edde05ae239c8138565c/src/backend/bs_repserver#L2386

**Comment by adrianschroeter** [comment]
yes and quite much more (also libarchive, build, perl-BSSolv, osc). However, all is live now, except one minor thing to publish also zst archives.

**Comment by mmetak** [comment]
@adrianschroeter Thank you very much for keeping archlinux support working in OBS.! ;-)

**Comment by mmetak** [comment]
@adrianschroeter One more question. The built packages are still `.pkg.tar.xz` and I assume that's because OBS sources `/etc/makepkg.conf` from `pacman` package? That file was not updated at the time when it's equivalent in `devtools` was which is what all arch devs use to build packages. [Reported here.](https://bugs.archlinux.org/task/64995) So I imported the modified pacman package into my project to try it out and packages are failing with this error:

```
[  555s] ### VM INTERACTION START ###
[  558s] [  523.350047] sysrq: SysRq : Power Off
[  558s] [  523.365710] reboot: Power down
[  558s] ### VM INTERACTION END ###
[  558s] build: extracting built packages...
[  559s] ARCHPKGS/ffmpeg-1:4.2.2-1-x86_64.pkg.tar.zst
[  559s] OTHER/_statistics
ffmpeg-1:4.2.2-1-x86_64.pkg.tar.zst: zstdcat No such file or directory
ffmpeg-1:4.2.2-1-x86_64.pkg.tar.zst: GLOB(0x562fdbd91ea8): not an arch package file
```

**Comment by adrianschroeter** [comment]
On Montag, 13. Januar 2020, 16:21:44 CET mmetak wrote:
> @adrianschroeter One more question. The built packages are still `.pkg.tar.xz` and I assume that's because OBS sources `/etc/makepkg.conf` from `pacman` package? That file was not updated at the time when it's equivalent in `devtools` was which is what all arch devs use to build packages. [Reported here.](https://bugs.archlinux.org/task/64995) So I imported the modified pacman package into my project to try it out and packages are failing with this error:
> 
> ```
> [  555s] ### VM INTERACTION START ###
> [  558s] [  523.350047] sysrq: SysRq : Power Off
> [  558s] [  523.365710] reboot: Power down
> [  558s] ### VM INTERACTION END ###
> [  558s] build: extracting built packages...
> [  559s] ARCHPKGS/ffmpeg-1:4.2.2-1-x86_64.pkg.tar.zst
> [  559s] OTHER/_statistics
> ffmpeg-1:4.2.2-1-x86_64.pkg.tar.zst: zstdcat No such file or directory
> ffmpeg-1:4.2.2-1-x86_64.pkg.tar.zst: GLOB(0x562fdbd91ea8): not an arch package file

some servers lacked still zstdcat tooling ... fixed ...

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by mmetak** [comment]
For the most everything seems to be working now, except package signatures are not generated. But, those were broken for pacman a long time ago anyway. @adrianschroeter looks like this line needs updating?

https://github.com/openSUSE/open-build-service/blob/3aae1fee42fe92c4b47ca0149d82ab494ec0382e/src/backend/bs_signer#L550

@pfactum Seems like that issue I reported for pacman won't be fixed even though it's such a trivial thing to do. I'll just leave the patched pacman package in my project page and use that for now.

**Comment by pfactum** [comment]
@mmetak I've ended up with this instead: https://build.opensuse.org/package/show/home:post-factum:supplemental/pacman-tuning plus `Required:` thingie in the project config.

**Comment by adrianschroeter** [comment]
We could offer an option in prjconf for a different compression.
Not so sure that it makes sense, since it increases load on our servers (esp mirror servers due to increased size) while the decompression speed of zstd does not really count for us ;)

**Comment by pfactum** [comment]
@adrianschroeter the increase in size is quite small, although it is non-zero of course. Also, regarding decompression speed, using zstd really counts since built packages can be (and sometimes definitely are) used as prerequisites to build other packages.
