### ISSUE TITLE
[production][comments#create] Invalid id given: https://build.opensuse.org/package/show/home:adkorte/xtables-geoip```

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#8919]
comments#create threw this 4 times
<pre>
Invalid id given: https://build.opensuse.org/package/show/home:adkorte/xtables-geoip```
</pre>
[https://build.opensuse.org/comments](https://build.opensuse.org/comments)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5e14fbe7d844f700080cea00)

**Comment by vpereira** [comment]
It is not a bug. There was some tool which was crawling obs (reading some pages and submitting it) and some how it was setting the wrong read fields while trying to submit it back.
