### ISSUE TITLE
[testsuite] build failure on factory/tumbleweed

### ISSUE THREAD

**Issue by bugfinder** [openSUSE/open-build-service#8934]
looks like the error message has changed with recent versions:

[  263s] ValidatorTest
[  263s]   test_assert_xml                                                 PASS (0.00s)
[  263s]   test_validator                                                  FAIL (0.01s)
[  263s]         Expected /Premature end of data in tag link/ to match "link validation error: 1:22: FATAL: EndTag: '</' not found".
[  263s]         test/unit/validator_test.rb:46:in `test_validator'
[  263s]         test/test_helper.rb:117:in `block in __run'
[  263s]         test/test_helper.rb:117:in `map'
[  263s]         test/test_helper.rb:117:in `__run'

code:
    request.env['RAW_POST_DATA'] = '<link test="invalid">'
    exception = assert_raise Suse::ValidationError do
      Suse::Validator.validate 'link', request.raw_post.to_s
    end
    assert_match(/Premature end of data in tag link/, exception.message)

should probably allow both variants of the error message.

**Comment by hennevogel** [comment]
I have no idea why we are even checking the error messages....
