### ISSUE TITLE
OBS 2.6 API not working on openSUSE 13.2 (passenger regression: libeio1 1.1.5 vs. 1.0.0+1411117990)

### ISSUE THREAD

**Issue by gollub** [openSUSE/open-build-service#894]
When installing OBS:2.6 on a stock openSUSE 13.2 installation a more recent libeio1 package gets installed (1.11.5)- compared to the version on the OBS 2.6 appliance (1.0.0+1411117990).

This more recent library causes the passenger to stuck when rendering any API request or WebUI page.

Downgrading to the OBS:2.6/libeio1 seems to mitigate the issue on openSUSE 13.2.

**Comment by adrianschroeter** [comment]
sorry, but 12.3 is really out of support and my interest ...

**Comment by adrianschroeter** [comment]
ah, sorry, the original mail spoke about 12.3, but you had 13.2 in mind ...

**Comment by adrianschroeter** [comment]
the newer libeio1 comes from an openSUSE 13.2 maintenance update, can you please create a bugzilla report for that instead?

**Comment by adrianschroeter** [comment]
hm, can you try to recompile rubygem-passenger against the maintenance update?

I can reconfigure OBS:Server:Unstable to do so if you want....

**Comment by darix** [comment]
for the record: we have 2 packages providing libeio1 one is part of libeio and the other one is coming out of Enlightenments ecore package.

my proposal would be to build with intree libeio instead of our extra package.

**Comment by gollub** [comment]
Verified that the in-tree libeio from devel:languages:ruby:extensions solves the problem for me:
```
build7:~ # rpm -qi ruby2.1-rubygem-passenger-5.0.6-3.1.x86_64
Name        : ruby2.1-rubygem-passenger
Version     : 5.0.6
Release     : 3.1
Architecture: x86_64
Install Date: Fri 03 Apr 2015 11:15:35 AM UTC
Group       : Development/Languages/Ruby
Size        : 29652849
License     : MIT and GPL-2.0
Signature   : DSA/SHA1, Thu 02 Apr 2015 02:31:38 PM UTC, Key ID 9af0c9a20e9af123
Source RPM  : rubygem-passenger-5.0.6-3.1.src.rpm
Build Date  : Thu 02 Apr 2015 02:30:32 PM UTC
Build Host  : cloud102
Relocations : (not relocatable)
Vendor      : obs://build.opensuse.org/devel:languages:ruby
URL         : https://www.phusionpassenger.com/
Summary     : A fast and robust web server and application server for Ruby, Python
Description :
A modern web server and application server for Ruby, Python and Node.js,
optimized for performance, low memory usage and ease of use.
Distribution: devel:languages:ruby:extensions / openSUSE_13.2
build7:~ # 
build7:~ # rpm -q --changelog ruby2.1-rubygem-passenger-5.0.6-3.1.x86_64 | head
* Thu Apr 02 2015 mrueckert@suse.de
- use intree libebio as well. our system copy seems to be broken.
[...]
```

**Comment by darix** [comment]
for fun and giggles to ```rpm -qi libeio1``` and you will notice why it broke.

**Comment by adrianschroeter** [comment]
I have updated the passenger package in OBS:Server:2.6 now to workaround this issue.
