### ISSUE TITLE
email address, real name shown publicly with no warning or opt out

### ISSUE THREAD

**Issue by ITwrx** [openSUSE/open-build-service#8940]
I'm not too happy that the email and name i used to create my microfocus account is being shown publicly on my open build service profile with no warning during sign up that this would happen (IIRC) or without any options regarding privacy given in the "edit profile" page. I just checked the TOS and PP and there is no mention of this information leakage requirement. I don't want my email address or other private info plastered all over the place, because someone else thinks it's SOP. 

This is the exact kind of "shtuff" i feared would happen when i was redirected to microfocus(?!) to fill out a nosey, 20th century form when i was *trying to sign up for the OBS*. All those required fields are annoying, to put it mildly. Microfocus doesn't need users' real names to use the OBS. I don't want to be redirected to any owner company's website to use the OBS anyways. I would rather have created a separate account for the OBS if this (albeit somewhat minor) datamining and disclosure was the cost.

This kind of antiquated, corporate stance towards users/community members makes openSUSE and SUSE look bad, IMHO.

Thanks

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support or discuss with us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

In your case it would probably best to report this to the [openSUSE admins](mailto:admin@opensuse.org) who take care of this instance...

Thank you for your consideration.

**Comment by ITwrx** [comment]
ok, but i don't see how this isn't in the source code of the OBS. the OBS redirects me to microfocus and the OBS source code is displaying my account details. 

Also, this repo sends mixed messages in regards to support related issues. When you create an issue it has "support" as one of the options. Then, when you choose that, it tells you that this repo is not for support, but still lets you create the issue. 

I would suggest removing the support related issue template if this repo doesn't want any support related issues reported here. It might be helpful to define what should be done when the OBS works in a way differently than desired, if this repo doesn't want those issues reported as bugs.

By you giving me the OBS admins' email address it makes me think that you believe the OBS has settings for what is displayed, but i doubt(ed) that is the case, and thus the bug report.

I will email the admins regarding this issue.

thanks
