### ISSUE TITLE
[production][feeds#notifications] string contains null byte

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#8953]
feeds#notifications threw this 271 times
<pre>
string contains null byte
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5de4d803558bbf000d8b9f0e)

**Comment by danidoni** [comment]
Can I close this? We're not seeing new instances of this errros since 6 months ago

**Comment by danidoni** [comment]
We talked offline and I'm closing it
