### ISSUE TITLE
frontend accessible on docker bridge ip

### ISSUE THREAD

**Issue by rickysarraf** [openSUSE/open-build-service#8958]
# Issue Description
Thank you for the [awesome and fully automated](https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md#how-to-setup-an-obs-development-environment) developer setup of open-build-service.

This report is only a feedback to mention the correct frontend url.
The document mentions that the frontend is accessible at: localhost:3000
Whereas it actually is accessible over the docker network ip, which for example in my case, is: 172.19.0.1:3000

As I understand it, the default docker configuration will create a docker bridge with network assigned in the class `172.XX.XX.XX`. Maybe the guide should mention that in a generalized way.

Expected Result
============
Add correct pointer to what address the frontend would be accessible at.

How to Reproduce
===============
1. Follow the [contribution guide](https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md#how-to-setup-an-obs-development-environment)
2. Complete the setup
3. Access localhost:3000

**Comment by hennevogel** [comment]
Thank you for your nice feedback :bouquet: You are right, this should be http://0.0.0.0:3000 instead

**Comment by hennevogel** [comment]
Does that work for you?

**Comment by rickysarraf** [comment]
Thank you for the quick reply. Yes. http://0.0.0.0:3000 works perfect. I just now did a `netstat` to check on what all IPs is the service running and I see it running on `127.0.0.1:3000` too. And trying it out, right now, worked. The frontend was accessible on the localhost address too.

So, I guess we can close this report as is without any change? Or change it to what you proposed.

Thanks.

**Comment by vpereira** [comment]
Normally the server takes sometime to accept incoming requests.
