### ISSUE TITLE
Cannot create home project

### ISSUE THREAD

**Issue by mobusby** [openSUSE/open-build-service#899]
I am unable to create a "home project".  Upon trying to create a new project I am brought to this page.
![image](https://cloud.githubusercontent.com/assets/7889558/6888226/114b1af0-d62c-11e4-8eca-32d271a6bcd7.png).

Filling out the form and clicking "Create Project" results in this page. 
![image](https://cloud.githubusercontent.com/assets/7889558/6888239/52c0a9be-d62c-11e4-8a3f-28da44bab5f6.png)

**Comment by hennevogel** [comment]
memcache died on the reference server. it's fixed now, try again :-)
