### ISSUE TITLE
Create .changes from vcs

### ISSUE THREAD

**Issue by hellcp** [openSUSE/open-build-service#8998]
Instead of relying on .changes files, some should be able to opt to use changes automatically generated from vcs revision information (time, packager and summary). This could be implemented avoiding the current script that changes .changes to rpm changelog.

**Comment by Conan-Kudo** [comment]
How would you want this to work? There's a whole lot of semantics and behaviors that need to be defined for generating changelogs from a version control system...

**Comment by hennevogel** [comment]
The [obs-service-tar_scm](https://github.com/openSUSE/obs-service-tar_scm/blob/888e79c03fa4a8b3aef514176ae77c3dcdcba991/tar_scm.service.in#L148) already does this...

**Comment by Conan-Kudo** [comment]
@hennevogel I'm not surprised that you brought that up, but `tar_scm` does it quite wrong. It clobbers authorship when generating changes from history. I assume @hellcp is talking about Dist-VCS/packaging VCS with OBS, which would mean that the changesets in the VCS are actually about changes to packaging files being submitted to OBS.

**Comment by hennevogel** [comment]
> `tar_scm` does it quite wrong

You would have to report a bug to this service then, sorry.

>  I assume @hellcp is talking...

@hellcp maybe you want to elaborate?

**Comment by hellcp** [comment]
Sure, I was talking about OBS's own VCS to be used for this purpose, so .changes wouldn't exist in the VCS, but would instead be generated from VCS revisions before the spec is used by obs-build (and actually directly submitted into rpmspec, instead of going through building it into .changes file before including it in rpmspec).

**Comment by adrianschroeter** [comment]
On Dienstag, 28. Januar 2020, 11:19:56 CET Stasiek Michalski wrote:
> Sure, I was talking about OBS's own VCS to be used for this purpose, so .changes wouldn't exist in the VCS, but would instead be generated from VCS revisions before the spec is used by obs-build (and actually directly submitted into rpmspec, instead of going through building it into .changes file before including it in rpmspec).

the .changes files are documentation for the user who installs the package.

And you must be able to rework past entries therefore.

So it is not really possible to bring this together with any commit messages IMHO

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by hellcp** [comment]
If only there was a commonly used VCS which allows for amending past commit messages >:T
