### ISSUE TITLE
disturl srcmd5 vs verifymd5

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#900]
The disturl currently contains the srcmd5:
https://github.com/openSUSE/open-build-service/blob/master/src/backend/bs_sched#L774

Would it make more sense to use the verifymd5?

**Comment by mlschroe** [comment]
No, the verifymd5 does not contain the link chain information.

**Comment by adrianschroeter** [comment]
the srcmd5 neither ... or is it actually the xsrcmd5 here?

**Comment by mlschroe** [comment]
Of course it's the xsrcmd5 for links (aka the srcmd5 when you use expand=1).
