### ISSUE TITLE
Prefill Submit Request at bottom of "Has a link diff" again

### ISSUE THREAD

**Issue by stoecker** [openSUSE/open-build-service#9018]
Issue/Feature Description
====================
Before the last update the submit request was prefilled, it no longer is.

Expected Result
============
Prefill the request

How to Reproduce
===============
1. Have a package with a diff to the parent package.
2. Click on "Has a link diff" on right side
3. Scroll to the end
4. Click on "Submit to ...parent name..."
5. Have the submit request

The request should have prefilled target project and target package and also in case of existing request the chance to select supersede.

Before this was implemented, it vanished with last UI rework.

Further Information
===============
* A link to an OBS instance showing the issue: https://build.opensuse.org

**Comment by hennevogel** [comment]
Duplicate of #8616
