### ISSUE TITLE
only first diff tab is populated

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#902]
Dominique reports that the webui is not showing the diff in all request action tabs anymore. In this example only the first tab shows a diff:

https://build.opensuse.org/request/show/293797

**Comment by hennevogel** [comment]
?

![screenshot from 2015-04-07 13 20 36](https://cloud.githubusercontent.com/assets/514785/7022139/ff87f960-dd28-11e4-9f67-50fe9f3b39b3.png)
![screenshot from 2015-04-07 13 20 55](https://cloud.githubusercontent.com/assets/514785/7022138/ff847132-dd28-11e4-8274-f48a34848a0f.png)

**Comment by DimStar77** [comment]
@hennevogel seems the diff of the 'tarball' is working in the later tabs - but not the actual .spec and .changes files (which are more interesting to the reviewer)

**Comment by DimStar77** [comment]
actually, nowadays this has improved, and the diff is being shown - albeit in a non-styled, expandable inputbox

**Comment by ChrisBr** [comment]
@DimStar77 is this still a problem?

**Comment by bgeuken** [comment]
I went through a dozen of requests and couldn't find that issue, which of course is no proof that it doesn't happen anymore.
But given that it's such an old issue, it seems safe to assume it got solved by now.

If it still appears, please re-open:-)

**Comment by adrianschroeter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New card template](https://trello.com/c/UW3TcuoS/1408-new-card-template)
