### ISSUE TITLE
OBS no longer properly calculates buildroot content

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#9020]
somewhen in the last 26 hours, a change in OBS resulted in a lot of broken builds, that used to work.

Example:
openSUSE:Factory nodejs10 standard x86_64 (current build result as of writing this issue: succeeded)
As one can observe from the build log, gcc-c++ was pulled in (it's explicit in the spec file, inside a condition)

Without changes to the package, a rebuild of this very same source now fails to build (observed in multiple stagings, like https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:J/nodejs10/standard/x86_64) with the error

```
[   54s] error: Failed build dependencies:
[   54s] 	gcc-c++ is needed by nodejs10-10.18.1-2.2.x86_64
```

So, yes, gcc-c++ is marked in the spec as mandatory and rpmbuild knows it too. OBS forgot to pull it in.

This currently blocks pretty much all stagings (there are multiple packages affected in similar ways; the common denominator seems to be BuildRequires in conditional blocks

**Comment by hennevogel** [comment]
Please do not attach priority labels yourself...

**Comment by hennevogel** [comment]
@adrianschroeter is working on it already

**Comment by hennevogel** [comment]
Fixed. See https://lists.opensuse.org/opensuse-buildservice/2020-01/msg00089.html
