### ISSUE TITLE
obsapisetup script removes external_frontend_* options

### ISSUE THREAD

**Issue by kaltsi** [openSUSE/open-build-service#903]
Is this a bug or intentional behavior? The obsapisetup script is replacing all external_frontend_\* options with frontend_\* options here:

https://github.com/openSUSE/open-build-service/blob/master/dist/obsapisetup#L109

**Comment by dmarcoux** [comment]
It's now in [dist/setup-appliance.sh](https://github.com/openSUSE/open-build-service/blob/38059b89c68d103cb23d1c0c53d255f6d5cf4752/dist/setup-appliance.sh#L217-L219)

@openSUSE/obs-frontend, does someone know about this?
