### ISSUE TITLE
Not able to update Attributes in webui

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#904]
Attempting to add/remove an attribute using the webui is declined with:
"Sorry you're not allowed to delete this Attrib"

I can perfectly do the same using osc, so there is no permission issue (attempting to remove the LockedBy attribute on home:dimstar for example)

The most common issue when prj maintainers are affected by this is when they want to disable FactoryAutoSubmission, but can't,due to this issue.

**Comment by hennevogel** [comment]
JFYI API and Webui go through different permission checks...

**Comment by ChrisBr** [comment]
I can reproduce this on buil.o.o but not on my local dev machine ...
@hennevogel can you confirm that?

**Comment by hennevogel** [comment]
I haven't looked into this

**Comment by hennevogel** [comment]
This is going to be solve with #2778

**Comment by adrianschroeter** [comment]
solved
