### ISSUE TITLE
The new responsive layout takes way too much space and is unintuitive

### ISSUE THREAD

**Issue by hellcp** [openSUSE/open-build-service#9056]
Bootstrap dropdowns in navbars were created for the exact usecase as visible here, dropdowns on desktops and expandable lists in hamburger on smaller screens. The currently implemented layout in OBS however makes navigation confusing, considering two identical drawers (aside from content) are expanded from the exact same side of screen and they take up way too big chunk of the screen for effectively 3 links. Please consider using dropdowns in navbar instead.

https://getbootstrap.com/docs/4.4/components/navbar/#supported-content

**Comment by hennevogel** [comment]
Just because something is technical possible doesn't mean you have to use it. We are also on the way to extend the menu. And BTW we just switched away from dropdowns so this is intentional. Bear with us for a while please :bear:

**Comment by hellcp** [comment]
I can understand not wanting dropdowns in many other places, due to their questionable responsiveness, but the navbar is the ideal place to use them, because of how bootstrap handles them there.
