### ISSUE TITLE
Revert start page

### ISSUE THREAD

**Issue by coogor** [openSUSE/open-build-service#9092]
I'm participating in the beta program.
Recently the main screen after login changed: Now there is on the upper right corner an icon with the avatar, next to a symbolic stack showing the open requests.
In the old screen there was a line containing the requests, profile/projects and home project. I could jump there with one click. Now I have to select the avatar and from there to the projects/home project. This is more to click and reduces the efficiency. Can we get the old screen back?
Thanks!

**Comment by hennevogel** [comment]
You can leave the [beta program](https://openbuildservice.org/2018/10/04/the-beta-program/) :wave:

**Comment by coogor** [comment]
> You can leave the [beta program](https://openbuildservice.org/2018/10/04/the-beta-program/) wave Thanks for your feedback.
That would just mean I get the reduced efficiency later.....

**Comment by coolo** [comment]
Perhaps you try next time to phrase your feedback differently - e.g. that you miss the direct link to your home project in the beta view. Asking for a revert is not feedback considered constructive

**Comment by hennevogel** [comment]
@coogor we are exploring a different navigation with the side menu in the beta program. It's not finished and set in stone yet. That is why this is in the beta program. Rest assured that we'll do the right thing and listen to your feedback.

**Comment by coogor** [comment]
@hennevogel Thank you - I trust you understood what I wanted to say.
