### ISSUE TITLE
publisher doesn't cleanup old files for Leap 15.2

### ISSUE THREAD

**Issue by lkocman** [openSUSE/open-build-service#9097]
Hello team,

we did receive a request to cleanup  Leap 15.2 files in pontifex2:/srv/ftp/pub/opensuse/distribution/leap/15.2/repo/oss/

https://progress.opensuse.org/issues/62546

Seems like that publisher is not calling rsync with --delete.  To my knowledge the expectation is to have only the latest files. Can you please fix this as the data is growing and there is no regular cleanup happening?

Thank you

**Comment by lnussel** [comment]
it's the publish_distro scripts on pontifex. OBS actually lacks features to keep old rpms around for while.
