### ISSUE TITLE
The user's username does not show up anywhere once you opt in the Public Beta Program

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#9100]
# Issue Description
When opting in into the Beta program, the user's username stops showing up anywhere on the UI.

Expected Result
============
The user's username should show up. Maybe in the sliding right menu, near the top.

How to Reproduce
===============
1. Go to 'https://build.opensuse.org/' and log in.
2. See your username on the top part of the screen, just below the watchlist.
3. Click on your username and opt in the Public Beta Program
4. Go to any other page than the profile page. The user's username does not show up anywhere else.

**Comment by dmarcoux** [comment]
As you wrote, the username is displayed on the user profile page. It's also displayed on the users page of a project/package, on the request#show page, on the group#show page, and probably more pages (I didn't check everywhere).

You would want to show the username in the navigation bar? I don't see why it's beneficial to do so. I should know my username, I wrote it to log in. Other websites like Trello, GitHub and GitLab also do not display the username of the logged-in user in the navigation bar and this is fine.

**Comment by danidoni** [comment]
> You would want to show the username in the navigation bar? I don't see why it's beneficial to do so. I should know my username, I wrote it to log in. Other websites like Trello, GitHub and GitLab also do not display the username of the logged-in user in the navigation bar and this is fine.

Fair enough, closing.
