### ISSUE TITLE
Add role request dialog misses option for groups

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#9111]
![Screenshot from 2020-02-20 17-31-22](https://user-images.githubusercontent.com/514785/74956750-dfd47080-5406-11ea-8baf-38e6d7e4a686.png)

`BsRequestActionAddRole` supports it.

**Comment by vmoutoussamy** [comment]
Since group maintainer should IMHO be recommended as much as possible for SLE, this issue is valuable.
