### ISSUE TITLE
osc api https://api.opensuse.org/source/Base:System/dbus-1/dbus-1.spec returns file not found

### ISSUE THREAD

**Issue by simotek** [openSUSE/open-build-service#9113]
# Issue Description
The obs api is not returning certain file's instead reporting `Server returned an error: HTTP Error 404: dbus-1.spec  no such file`

Expected Result
============
Return the contents of the file

How to Reproduce
===============
1. Run `osc api https://api.opensuse.org/source/Base:System/dbus-1/dbus-1.spec` 

Further Information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)

**Comment by hennevogel** [comment]
The package is a link. Append `?expand=1`
