### ISSUE TITLE
/architecture route refers to non-existent /configuration route

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#9119]
The `GET /architecture` route refers to a `/configuration` route: https://build.opensuse.org/apidocs/index which supposedly can be used to get the list of supported architectures.

However that route is neither documented, nor working on build.opensuse.org.

**Comment by adrianschroeter** [comment]
On Freitag, 21. Februar 2020, 15:22:04 CET Dan Čermák wrote:
> The `GET /architecture` route refers to a `/configuration` route: https://build.opensuse.org/apidocs/index which supposedly can be used to get the list of supported architectures.
> 
> However that route is neither documented, nor working on build.opensuse.org.

it works on api.opensuse.org

It is documented in 

  docs/api/api/configuration.rng



-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by dcermak** [comment]
> it works on api.opensuse.org

Not for me:
``` ShellSession
$ curl --user $OBS_USERNAME:$OBS_PASSWORD "https://api.opensuse.org/configuration"
<html><body>You are being <a href="https://api.opensuse.org/">redirected</a>.</body></html>
```

> It is documented in docs/api/api/configuration.rng

Unfortunately this document is not linked in `api.txt`.
