### ISSUE TITLE
Showing request with missing packages

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#912]
Showing request with missing packages leads to a ActiveXML::Transport::NotFoundError which isn't catched

**Comment by bgeuken** [comment]
I created a submit request and deleted the source package afterwards. As a result the the request got revoked. There is also a red message "The diff call for /source/home:bgeuken/node_exporter?cmd=diff&expand=1&filelimit=10000&orev=0&rev=3&view=xml&withissues=1 failed: package 'node_exporter' does not exist", but that seems to be fine.

=> solved and therefore closing
