### ISSUE TITLE
Dynamic BuildRequires are not re-evaluated automatically

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/open-build-service#9123]
# Issue Description

If package `A` generates dependency on `(b >= 0.9.0 with b < 0.10.0)` provided by package `B-0.9.x` and then package `B` gets upgraded to `0.10.x` and I push a change (e.g. update of version) to package `A`, its dependencies (dynamic ones) are not re-evaluated automatically so the package stays in state `unresolvable`

Expected Result
============

Dynamic BuildRequires are evaluated every time when:

* Commit is pushed in VCS
* Any package (or their dependencies) which are mentioned directly as BuildRequires in spec are changed

Further Information
===============

You can see such issues in my https://build.opensuse.org/project/show/home:ignatenkobrain:rust from time to time and I use `osc wipebinaries --unresolvable` which forces OBS to re-evaluate BRs and this works fine as work-around but very annoying. (Thanks @lethliel and @adrianschroeter for this workaround).

I am not sure about current algo, but if OBS does not implement multiple levels of generated BRs (yes, you are supposed to run rpmbuild -br and install them, and repeat to get BRs until all of them will be satisfied), you don't need to re-trigger re-evaluation of dynamic BRs if indirect dependencies change (the ones which were generated in `%generate_buildrequires`. Might be some perf improvement.

**Comment by mlschroe** [comment]
This should work much better with commit 5687d92cb3bd0729d34408e3385fbe831d426c92.

**Comment by ignatenkobrain** [comment]
@mlschroe do you know when this will be deployed on build.opensuse.org?

**Comment by mlschroe** [comment]
It should be already deployed. And we're going to update OBS to the current masterbranch in the next two days.
