### ISSUE TITLE
CPU features in constraints should work in AND mode

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/open-build-service#9124]
# Issue Description

In `<hardware><cpu>…`, if I mention several `<flag>`, they work in OR more, which means having any of these flags will satisfy constraint. I believe that for 99% of cases this is not desirable and OBS should rather make sure to satisfy all of them at the same time.

Expected Result
============

OBS treats multiple CPU flags in constraints as all mandatory at once.

Further Information
===============

Myself I can't really imagine case where you'd want to use anything like `sse4_1 OR sse4_2`.

**Comment by mlschroe** [comment]
I think @lethliel fixed that in commit 3df977be67a9ad95f87d49dbd48af1cebe958335
