### ISSUE TITLE
/configuration.xml route contains undocumented element api_url

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#9126]
# Issue Description

The route `GET /configuration.xml` returns a `<configuration>` element that contains an entry `<api_url>` which is not defined in the schema (configuration.rng). This is at least the case on build.opensuse.org.

Expected Result
============

The `<api_url>` element should not be present.

How to Reproduce
===============

The following command should not produce any output:
``` ShellSession
$ curl --user $OBS_USERNAME:$OBS_PASSWORD "https://api.opensuse.org/configuration.xml" 2> /dev/null |grep api_url
  <api_url>https://api.opensuse.org</api_url>
```

Further Information
===============
* configuration.xml schema: https://build.opensuse.org/apidocs/configuration.rng
* the `<api_url>` element is also imho pretty pointless, as you need to know the api url, to even **retrieve** this info...

**Comment by hennevogel** [comment]
It's rather that `configuration.rng` should include this attribute...

**Comment by dcermak** [comment]
> It's rather that `configuration.rng` should include this attribute...

I have honest doubts about the usefulness of the `<api_url>` element in a reply from the API, which you'll only get if you actually know the api URL already. So why even include this?

**Comment by hennevogel** [comment]
Well it's there, people use it. We can talk about the usefulness somewhere else.

**Comment by coolo** [comment]
the api_url is not for users, but for the backend - who gets pushed /configuration when it changes
