### ISSUE TITLE
run product converter on automatic branch merges

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#913]
for _product containers that are branches the product converter is not run automatically if the branch target is updated. Therefore branched products stay at old versions.

**Comment by adrianschroeter** [comment]
we have basically two options here:

* re-run product converter in all linking packages
* offer an api command (maybe like service remote run) to re-run the product converter

Michael, any opinion here?

**Comment by mlschroe** [comment]
It's the same as with services (and we actually want to merge the two implementations). They also do not get re-run. It's not a bug.

**Comment by lnussel** [comment]
I filed it as feature request ...
