### ISSUE TITLE
Unreadable package names on project#monitor

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#9145]
# Issue Description
On the `project#monitor` page, the datatable is quite unusable right now since the package names are unreadable.

Expected Result
============
I expect the package names to be readable.

How to Reproduce
===============
1. Go to any project#monitor page with many repositories
2. See unreadable package names

Further Information
===============
This was reported by @DimStar77 on IRC. Here's a good example of what's going wrong: https://build.opensuse.org/project/monitor/home:dimstar:Factory

**Comment by DimStar77** [comment]
Also note that the DB is not filled up all the way to the right - The last repositories do not contain information (on https://build.opensuse.org/project/monitor/home:dimstar:Factory)
