### ISSUE TITLE
Login newly brings user to the landing page

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#9149]
Situation: I am on any request review page (e.g. https://build.opensuse.org/request/show/757447)

When using the login box at the top right, in the past, my browser remained on the displayed requets/show page and I could 'continue my workflow' directly.

Since recently, when loggin in, I end up on https://build.opensuse.org and then have to navigate back to where I was just before logging in

**Comment by dmarcoux** [comment]
I can reproduce this in production, but not in the development environment... This is weird. Could it be something related to the proxy?

**Comment by hennevogel** [comment]
Yeah I think I know what is going on. Just recently I fixed this for `/session/new` in #9035
