### ISSUE TITLE
Creating / Associating bugowner request with new package creation

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/open-build-service#9152]
Currently, we can't assign bugowner to a package, until it is created, ie until submit request for it is accepted.

It would be very helpful to allow creating bugowner request for packages which are not existing in a project. This way, we could stage those requests along the submit request with the code and have both requests accepted at the same time (and potentielly, have some reviews to ensure we can't accept package creation if corresponding bugowner information is not available.

**Comment by hennevogel** [comment]
How about just always set the submitter as bugowner for new packages?

**Comment by adrianschroeter** [comment]
that would break openSUSE setup, bugowner is by default only used in SLE.

**Comment by fcrozat** [comment]
> How about just always set the submitter as bugowner for new packages when accepting stagings.

this is not always the submitter which is the bugowner (we often have to import various Factory packages to fulfill build dependencies for a new package).

And it won't solve the issue when a group is used for new package bugownership

**Comment by coolo** [comment]
the staging accept command could client side read comments out of the submit request and mangle the meta without a request.

The staging accept (API side) would need to be clever enough to accept the bugowner request only after the package is created. And a staging project would not be acceptable if it contains bugowner requests for packages that aren't created in the same staging project.

**Comment by fcrozat** [comment]
> the staging accept command could client side read comments out of the submit request and mangle the meta without a request.
> 
> The staging accept (API side) would need to be clever enough to accept the bugowner request only after the package is created. And a staging project would not be acceptable if it contains bugowner requests for packages that aren't created in the same staging project.

this would allow to enforce "every package needs a bugowner" SLE rule. This would be great.

**Comment by hennevogel** [comment]
> the staging accept command could client side read comments out of the submit request and mangle the meta without a request.

I guess this is something for your tooling then.
