### ISSUE TITLE
Refresh button in repository view drags a white rectangle with it hiding repositories

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#9157]
# Issue Description

The refresh button in the view showing the current build states of a package appears to now move if you scroll down to always be in the view. However, this drags a white rectangle behind it down too, which doesn't look too great (and more like a bug imho):
![Screenshot_2020-02-28 vagrant](https://user-images.githubusercontent.com/45594031/75544814-03aa3e80-5a25-11ea-8c3b-8d329372a17f.png)

Expected Result
============
The refresh button should not move at all or not have the white background behind it.

How to Reproduce
===============
1. Go to any package with a few repositories (e.g. https://build.opensuse.org/package/show/Virtualization:vagrant/vagrant)
2. Scroll down a bit so that the refresh button would be outside of the visible portion of your screen

**Comment by DavidKang** [comment]
Addressed in PR #9147
