### ISSUE TITLE
Deleting _product leaves undeletable _product:* around

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/open-build-service#916]
Deleting the _product meta package from a project doesn't delete the autogenerated _product:* packages, and it is impossible to delete them manually.  Workaround is to remove all *.product files from _product first, which triggers a product converter run, and only then remove the _product meta package.

**Comment by adrianschroeter** [comment]
works for me(aka test suite)... how did you remove the package? Using "osc rdelete ... _product" ?

**Comment by andreas-schwab** [comment]
See build.suse.de/home:Andreas_Schwab:arm64.  I've used osc rm _product.  It looks like the real issue is that the directory entries are left behind.

**Comment by adrianschroeter** [comment]
k, sources got removed, but api object not. test suite did only check for sources.

fixed in git master and 2.6 branch now
