### ISSUE TITLE
Arch Linux choice handling bug

### ISSUE THREAD

**Issue by rilian-la-te** [openSUSE/open-build-service#917]
I want to build some GTK+ packages for Arch:Extra and hit this:
```
have choice for ca-certificates needed by glib-networking: ca-certificates ca-certificates-utils
```
For now, packages marked as unresolvable, but it builds OK on actual Arch Linux.

**Comment by adrianschroeter** [comment]
looks actually more like a packaging bug ... should -utils really provide the main package?
nevertheless workarounded via a prefer rule for now

**Comment by rilian-la-te** [comment]
how I can do it for now (prefers workaround)? I does not found about it in a doc...
