### ISSUE TITLE
Linked _product doesn't trigger productconvert

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/open-build-service#919]
If _product is a link the update of the origin doesn't trigger a productconvert run.  For example,  openSUSE:Factory:{ARM,PowerPC}/_product link to openSUSE:Factory/_product, and openSUSE:Factory:{ARM,PowerPC}/_product:openSUSE-release are out of date wrt. the expanded product description.

**Comment by adrianschroeter** [comment]
That is correct and we lately discussed this behaviour. In short, we do not want to do this automatically, but we added support  for doing it manualy by calling "osc service remoterun <PROJECT> _product".

However, this is not yet deployed, but will be soon.

**Comment by k0da** [comment]
It seems you can't do service runs on a _link

POST https://api.opensuse.org/source/openSUSE:Factory:PowerPC/_product?cmd=runservice
ERROR:totest-manager.py:HTTP Error 404: Not Found
