### ISSUE TITLE
Enabling "Go to download repository" link

### ISSUE THREAD

**Issue by markkp** [openSUSE/open-build-service#920]
I'm running a private instance of obs-server-2.6.2-1.1 from the appliance download. I hope I'm missing something, but I can't figure out how to enable the "Go to download repository" in the "State of repository" page for my project builds.  I looked through all the documentation I could find, but didn't get anywhere.

**Comment by adrianschroeter** [comment]
Most likely the download mirror URL is not configured.

You can do so by using

 osc api -e /configuration

and setting the "download_url" element with the proper starting URL.

But please use mailing list or IRC in future for support questions and not github issues.
