### ISSUE TITLE
AppImage: version `GLIBC_2.25' not found

### ISSUE THREAD

**Issue by anki-code** [openSUSE/open-build-service#9207]
Hello!

The [fish shell](https://github.com/fish-shell/fish-shell/issues/6475) uses Open Build Service to create AppImage (https://build.opensuse.org/package/binaries/shells:fish:nightly:master/fish/AppImage) but when we tried to run `fish.AppImage` on CentOS 7.7 we've got an error:
```
python3: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_fishOKHG4Z/usr/lib64/libpython3.6m.so.1.0)
```
The AppImage developers comment this case:
> glibc 2.25 is from 2017-02-05, which means that this AppImage will not run on systms that ship an earlier version of glibc. For it to work on earlier distributions, you would need to build on a build host that has an earlier version of glibc. I don't know how to configure OBS so that it uses an earlier base system for the build, seemingly they have updated it.

Could you please help to resolve this and build AppImage with lower versions of glibc?

For example [PEP 571 recommend manylinux2010](https://www.python.org/dev/peps/pep-0571/) Docker image.

Thanks!

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.

**Comment by adrianschroeter** [comment]
actually we have also the "reference server" label here for such kind of requests where it is about te base configuration.

Try to use the tempate based on SLE 12-SP4 for a lower glibc version:

 https://build.opensuse.org/package/show/home:rfparedes:branches:OBS:AppImage:Templates:SLE:12-SP4/AppImageTemplate
