### ISSUE TITLE
WebUI comments don't link https URLs

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#921]
See https://build.opensuse.org/request/show/304945 for example.

**Comment by ChrisBr** [comment]
Hmm, I see that it's still not working on the provided link.
Nevertheless, I tried it with 37b5a675e6ca539c726866dbfbc20dddaecd1272 and it worked for me (see screenshot).

![OBS Comments](http://paste.opensuse.org/19911544)

@hennevogel any idea?

**Comment by Mailaender** [comment]
Looks like it does not work properly in indented/answering comments.

**Comment by ChrisBr** [comment]
@Mailaender Ahh, thanks! You're right :)

**Comment by hennevogel** [comment]
This is also addressed in #967

**Comment by hennevogel** [comment]
which is merged
