### ISSUE TITLE
Off-canvas overlaps modals

### ISSUE THREAD

**Issue by saraycp** [openSUSE/open-build-service#9216]
# Issue Description

Being in the Beta Program on small and medium-sized screens, when we open the `Places` menu and click on a link that opens a modal, i.e. `Delete Project`, the modal keeps behind the off-canvas.

When the navigation bar is at the bottom, the off-canvas contains an `X` so you can close it and continue working. However, when the navigation bar is on the top, there isn't any `X` and it makes it impossible to interact with the modal.

Expected Result
============
All off-canvas should be removed as soon as a modal is open.

![overlap_canvas_modal](https://user-images.githubusercontent.com/2581944/76520188-bdac9c00-6462-11ea-83cf-3b16a7b953a1.gif)

**Comment by dmarcoux** [comment]
Adjusting the `z-index` of the modals and the menu will fix this.

Another issue with `z-index`:
![tab-scrollbar](https://user-images.githubusercontent.com/1102934/76532906-914f4a80-6477-11ea-87bd-7e79fba1a5fc.png)
