### ISSUE TITLE
Files could not be expanded: service daemon error

### ISSUE THREAD

**Issue by alanbortu** [openSUSE/open-build-service#922]
I am attempting to build a package and got this error

**Files could not be expanded: service daemon error:
400 remote error: /usr/lib/obs/server/call-service-in-lxc.sh service parameter file is not defined**

Screenshot: http://paste.opensuse.org/view/raw/52430285

Content of spec file: http://paste.opensuse.org/view/simple/43580995
Conetent of service file: http://paste.opensuse.org/view/simple/27497035

**Comment by hennevogel** [comment]
Looks good to me now. Still an issue for you  @alanbortu?

**Comment by marec2000** [comment]
Same issue here - problem is file verfication. On local builds it works but when uploading to build server the error apperas as mentioned by alanbortu. Is sha256 no longer supported on server builds?

**Comment by marcus-h** [comment]
On 2015-06-27 05:29:07 -0700, marec wrote:
> Is sha256 no longer supported on server builds?
> 
It's still supported, but the service definition file is
incomplete. SR#310161 should fix this - (see also
http://lists.opensuse.org/opensuse-buildservice/2015-06/msg00007.html).

**Comment by adrianschroeter** [comment]
merged, thank you .. will be deployed asap
