### ISSUE TITLE
[Beta webui] project monitor page show no package

### ISSUE THREAD

**Issue by ggardet** [openSUSE/open-build-service#9222]
Currently on build.opensuse.org, the beta webui does not show any package on project monitor page, whereas standard webui shows it.
E.g: https://build.opensuse.org/project/monitor/openSUSE:Factory:ARM?arch_local=1&defaults=0&repo_images=1&succeeded=1

**Comment by hennevogel** [comment]
It shows all packages that are `succeeded` as per your request.
