### ISSUE TITLE
Bizzarre UX: Three different scrolling sidebars from one side

### ISSUE THREAD

**Issue by hellcp** [openSUSE/open-build-service#9227]
# Issue Description
Three different sidebar types now happen to scroll out of the right side of the interface on the main page. This is a horrible UX. There is no spacial association of any part of the interface, and even worse, no hierarchy.

Expected Result
============
Single type of a scrolling sidebar from any given side of the screen.

**Comment by danidoni** [comment]
@hellcp can you provide some screenshots, please?

**Comment by hellcp** [comment]
![Screenshot from 2020-03-16 12-54-08](https://user-images.githubusercontent.com/30577011/76756036-4427ed00-6785-11ea-8fb2-a05d2b47c7b9.png)
![Screenshot from 2020-03-16 12-53-58](https://user-images.githubusercontent.com/30577011/76756039-45591a00-6785-11ea-951d-a3ef41417166.png)
![Screenshot from 2020-03-16 12-53-47](https://user-images.githubusercontent.com/30577011/76756041-45591a00-6785-11ea-8ad4-e3ed97909bb4.png)

**Comment by hennevogel** [comment]
what do you think is horrible about it? :-)

**Comment by danidoni** [comment]
I think I know what you mean by spatial association. You mean like browser tabs, right?

![Screenshot from 2020-03-17 09-46-01](https://user-images.githubusercontent.com/2650/76839087-2e720080-6835-11ea-8c79-76a69d64db1b.png)

The tab and the page you are browsing are connected visually.

**Comment by hellcp** [comment]
There is some indication as to which sidebar is expanded, but I know multiple sidebars expanding from the same side of the screen with multiple different contexts aren't a good idea. You do want the user to associate certain actions with certain gestures, this goes against that idea, because multiple split things happen in one place.

**Comment by hennevogel** [comment]
> multiple split things happen in one place

Not sure what you mean by this, can you elaborate? `split things`?

**Comment by hellcp** [comment]
Multiple sidebars with separate functionality from the same side of the screen

**Comment by hennevogel** [comment]
by now there is only one sidebar expanding...
