### ISSUE TITLE
Project auto complete is very slow

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#927]
If you start typing you already lost, because it freezes your browser:

![image](https://cloud.githubusercontent.com/assets/756669/7670938/0a49a4f2-fcb9-11e4-80a5-084442411d7f.png)

This feature may be helpful in the end, but not when typing `home:` and it starts iterating over all >30.000 user projects. I also guess this is also a performance bottleneck on the server side.

Better turn it off?

**Comment by bgeuken** [comment]
The current implementation sends one large array with all matching project names.

We could limit the results to a reasonable amount, eg. 100. Or we could use something like pagination and send the matching project names in small chunks when they are needed.

@hennevogel What do you say henne?

**Comment by ChrisBr** [comment]
Fixed in #1011
