### ISSUE TITLE
"Tasks" link goes to wrong address

### ISSUE THREAD

**Issue by sysrich** [openSUSE/open-build-service#9275]
# Issue Description
As seen on build.opensuse.org right now (24 March 2020) the 'Tasks' link in the top right of the WebUI goes to https://build.opensuse.org/users/$USER/notifications

Expected Result
============
Tasks link should go to https://build.opensuse.org/my/tasks

How to Reproduce
===============
1. Go to https://build.opensuse.org
2. Click on 'Tasks'
3. See 500 error because it's not going to a valid URL

**Comment by hennevogel** [comment]
It's not going to the wrong address. The new page crashes. We are on it.

**Comment by DavidKang** [comment]
In this deliverable we changed the 'Task' to show the notifications. That only affects the users that are in Beta. The case, is that in our database we have some data with wrong information.
We are currently working on fixing it.

Thanks for reporting the issue.

**Comment by hennevogel** [comment]
The page is functional now.
