### ISSUE TITLE
Overflowing text and buttons in notification view

### ISSUE THREAD

**Issue by krauselukas** [openSUSE/open-build-service#9276]
The text of the notification description and the done button overflow the card body on certain screen sizes.

<img src="https://user-images.githubusercontent.com/22001671/77455572-4d0a6580-6dfa-11ea-8f39-e466a64f60bd.png" width=300></img>
![Screenshot_2020-03-24 openSUSE Build Service(1)](https://user-images.githubusercontent.com/22001671/77455577-4da2fc00-6dfa-11ea-9607-155b0e8becd5.png)

How to reproduce:

1. Go to ```users/:user_login/notifications```
2. Scale viewport to a mobile screen size

**Comment by DavidKang** [comment]
@krauselukas, I couldn't reproduce it.

**Comment by krauselukas** [comment]
@DavidKang for me it's still happening, both on firefox and chrome

**Comment by DavidKang** [comment]
@krauselukas, I can reproduce it. Is because it is not breaking the words "home:krau....".
