### ISSUE TITLE
New notification screen does not show own requests

### ISSUE THREAD

**Issue by coogor** [openSUSE/open-build-service#9283]
In the Beta program there is a new screen to handle submit requests.
The new inbox does not show SR where you are the maintainer yourself. You see them only under 'all requests'
Example: https://build.opensuse.org/request/show/788012 
Submit package home:DocB:Orthanc / orthanc to package graphics / orthanc
Does not show up in Inbox!

**Comment by hennevogel** [comment]
Thanks for the report! Duplicate of #9282
