### ISSUE TITLE
Relayout /notifications

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#9304]
Present:
![old](https://user-images.githubusercontent.com/8861948/77890766-481d3a00-7270-11ea-8046-dc50ee26320c.png)

The filter box creates a huge unused space below it.
Remove it and replace by a horizontal link group, something like
![new](https://user-images.githubusercontent.com/8861948/77890829-5d926400-7270-11ea-8055-88c892686686.png)

**Comment by DavidKang** [comment]
Handled in PR [9356](https://github.com/openSUSE/open-build-service/pull/9356)
