### ISSUE TITLE
Notifications' Inbox/Done

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#9314]
# Issue Description
Whenever my notifications' inbox is empty, it's not clear if something is wrong or not. When looking at the code, it's clear that we simply display nothing whenever there are no notifications. This is the same for the `Inbox` and the `Done`.

Expected Result
============
A message to let the user know that there are no notifications should suffice.

How to Reproduce
===============
1. Go to the notifications' page.
2. See an empty box if you have no notifications.

Further Information
===============
![inbox](https://user-images.githubusercontent.com/1102934/78119438-b563d300-7408-11ea-8e73-5d04062ef6c3.png)

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback](https://trello.com/c/pBDrUXfB/1871-address-feedback)
