### ISSUE TITLE
debian architecture-specific dependencies not evaluated properly

### ISSUE THREAD

**Issue by Artox** [openSUSE/open-build-service#932]
It looks like architecture-specific dependencies such as
Depends:
 libegl1-mesa-dev [any-arm],
are not properly evaluated. In my test-case it is simply skipped, and then missing during the build.

I created a sample package here: https://github.com/Artox/deb-pkg_hellworld
and the actual build-log is available here: https://obs.gbps.io/package/live_build_log/home:Catwich/helloworld/Debian_Wheezy/armv7l

Like you can see, libegl1-mesa-dev is not being installed.

**Comment by dmarcoux** [comment]
@mlschroe Is this still an issue? If not, let's close this issue.

**Comment by mlschroe** [comment]
Oh wow, this fell of the radar.

I think the reason for this is that OBS doesn't know 'arm', it uses 'armel', 'armhf', and 'arm64' as architectures. I'll investigate what 'arm' should match.

**Comment by mlschroe** [comment]
OK, so 'arm' is the now obsolete debian arm architecture. We could reserve a scheduler architecture for it, but I don't think this is needed anymore.

So I'm closing this, please reopen if you need it.
