### ISSUE TITLE
User signup with a dot (".") in the username causes 500 Internal Server Error on next login

### ISSUE THREAD

**Issue by tomaspinho** [openSUSE/open-build-service#933]
This was detected on OBS 2.6 stable running on OpenSUSE 13.1.
A gem update was forced on the host after install to make sure everything was running smoothly.

Attached logs for reference:

[dbeaebae-7bf4-4557-8450-c9ad8134267d] [2059:1243.21] Started POST "/user/do_login" for 2001:690:2100:82::16 at 2015-05-29 15:42:18 +0100
[dbeaebae-7bf4-4557-8450-c9ad8134267d] [2059:1243.21] Processing by Webui::UserController#do_login as HTML
[dbeaebae-7bf4-4557-8450-c9ad8134267d] [2059:1243.21]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"3gbwRqa1pBGxVz51f5c7eiHx1nSwrcPSXwu
7Q7rYqN4=", "return_to_path"=>"/", "username"=>"tomas.pinho", "password"=>"[FILTERED]", "commit"=>"Log In"}
[dbeaebae-7bf4-4557-8450-c9ad8134267d] [2059:1243.21] Anonymous request to /
[9c0e5862-1097-4f5c-8f8a-1778c4260ff4] [2074:1083.09] Started POST "/person/tomas.pinho/login" for ::1 at 2015-05-29 15:42:18 +0100
[9c0e5862-1097-4f5c-8f8a-1778c4260ff4] [2074:1083.10] 
ActionController::RoutingError (No route matches [POST] "/person/tomas.pinho/login"):
  actionpack (4.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.6) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.6) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  hoptoad_notifier (2.4.11) lib/hoptoad_notifier/user_informer.rb:12:in `call'
  railties (4.1.6) lib/rails/engine.rb:514:in `call'
  railties (4.1.6) lib/rails/application.rb:144:in `call'
  railties (4.1.6) lib/rails/railtie.rb:194:in `public_send'
  railties (4.1.6) lib/rails/railtie.rb:194:in `method_missing'
  passenger (5.0.8) lib/phusion_passenger/rack/thread_handler_extension.rb:89:in `process_request'
  passenger (5.0.8) lib/phusion_passenger/request_handler/thread_handler.rb:155:in `accept_and_process_next_request'
  passenger (5.0.8) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  passenger (5.0.8) lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
  passenger (5.0.8) lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'

**Comment by hennevogel** [comment]
Which version is this? This is fixed in abc1e65f53f20264085226a378d22190c337ce3f

**Comment by tomaspinho** [comment]
You're probably right as this is the version on the official SUSE repositories. It's most likely older than the fix. 

We probably won't be installing from source so I thought I'd just point the out in case you get others with the same issue.

**Comment by hennevogel** [comment]
Maybe, depends on what you mean by "official SUSE repositories" :-)

**Comment by hennevogel** [comment]
Let us know if this is still a problem with newer versions...
