### ISSUE TITLE
[DOM] Found 2 elements with non-unique id

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#9331]
Visiting https://build.opensuse.org/project/show/home:coolo with the console open gives me a warning about id=description and id=project 

Beta is disabled

**Comment by eduardoj** [comment]
Sorry, what do you mean by "with the console"? What browser are you using?

**Comment by coolo** [comment]
chromium

![Screenshot_20200402_213415](https://user-images.githubusercontent.com/1067203/78293941-c0faeb00-7529-11ea-887f-ca6daa5bbfae.png)
