### ISSUE TITLE
OBS Local Setup Documentation Bugs

### ISSUE THREAD

**Issue by kjammer8** [openSUSE/open-build-service#934]
I found two bugs in this page:

http://openbuildservice.org/help/manuals/obs-best-practices/cha.obs.best-practices.localsetup.html

I am following instructions for "4.2 OBS 1 click install on openSUSE 13.1".

Bug #1:

http://openbuildservice.org/help/manuals/obs-best-practices/cha.obs.best-practices.localsetup.html

Section 4.2

This section explains, how you can install OBS on top of openSUSE 13.1. Open your web browser and go to that URL: http://download.opensuse.org/repositories/openSUSE:/Tools/openSUSE_13.1/OBS_Server.ymp

This URL is a 404.  I think a mirror is available here:

http://ftp.uni-stuttgart.de/opensuse-buildservice/OBS:/Server:/2.5/openSUSE_13.1/OBS_Server.ymp

Bug #2:

Section 4.2 as well

To initialize fresh database, page says to run `rake:dbsetup/migrate...` for each of `/srv/www/obs/api` and `/srv/www/obs/webui`.  However, only the first path exists:

```
linux-t02g:/srv/www/obs # find . -type f -name Rakefile
./api/Rakefile
```

Trying to run `sudo RAILS_ENV="production" rake db:migrate` on `/srv/www/obs/webui` returns an error.

Bug #3:

Should `/srv/www/obs/api/` be owned by lighttpd or wwwrun?  The documentation says to use lighttpd, but that user does not exist in this VM image.

**Comment by hennevogel** [comment]
We track our documentation in it's own repo. I've copied your issue over to https://github.com/openSUSE/obs-docu/issues/13
