### ISSUE TITLE
Wrong file name for files with same content/hash

### ISSUE THREAD

**Issue by ismail** [openSUSE/open-build-service#9352]
https://build.opensuse.org/package/show/hardware:boot/raspberrypi-firmware shows two "raspberry-firmware.changes" file, identical in size. But in reality there are two different files:

sisyphus ~/work/obs/hardware:boot/raspberrypi-firmware > sha1sum *.changes
8b484e2bf0ad6dabdfe12eaab73e403e73d1a4bd  raspberrypi-firmware-config.changes
8b484e2bf0ad6dabdfe12eaab73e403e73d1a4bd  raspberrypi-firmware.changes

... with same content & hash. Probably this results in showing the wrong filename for the -config variant.

**Comment by ismail** [comment]
This looks fine now, did something change on the server side?

**Comment by krauselukas** [comment]
Thanks for the report @ismail, I can reproduce it. Could be related to the caching, need to check it first though

**Comment by ismail** [comment]
There seems to be a wide-spread issue with numbers not updating which smells like a caching issue. Like my tasks is stuck at "11" even though I have some hundred SRs in the queue.

**Comment by danidoni** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cache bugs](https://trello.com/c/lZxR7wrx/1369-cache-bugs)
