### ISSUE TITLE
OBS Staging workflow unoperational

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#9353]
Since this afternoon, I noticed a few issues related to the staging workflows (literally stopping all stagnig efforts):

* New requests sent to openSUSE:Factory do not get the appropriate reviews added (factory-staging/factory-auto/licensedigger) and end up straight in state new
* Things I still see in the backlog (from earlier, that had the right reviews): running staging adi results in an error 500 when a request should go into an adi project
* Visually: https://build.opensuse.org/project/users/openSUSE:Factory shows no maintainers / reviewers ticked (osc meta prj openSUSE:Factory seems correct though)

**Comment by DimStar77** [comment]
The issue must have started after ```2020-04-08T11:06:37``` (timestamp as provided by osc rq show, presumably UTC) - sr#792409 was the last one seen against Factory that got the reviews properly assigned

**Comment by hennevogel** [comment]
we found the root cause and are working on a fix

**Comment by hennevogel** [comment]
You can read up on what happened in our blog. Sorry for the inconvenience.

https://openbuildservice.org/2020/04/08/post-mortem/
