### ISSUE TITLE
Flash messages are rendered over the "Places" menu

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#9363]
# Issue Description
The flash message rendered when logging out is being placed on top of the "Places" menu.
With my UX designer hat on this is a bit ugly.

Expected Result
============
It should not cover the actions in the "Places" menu.

How to Reproduce
===============
1. Log into OBS
2. Ensure you  are in the Beta program.
3. Click on 'Notifications' on the top of the black navigation bar to go to the new Notifications screen.
4. Open the "Places" menu and Log out.
5. See the flash appearing on top of the menu.

![Screenshot_20200409_134143](https://user-images.githubusercontent.com/2650/78892212-40784500-7a69-11ea-8f00-9beb1c311787.png)

NOTE: This will happen on smaller screen sizes, for example when you use the browser's inpector and place it on your right.

**Comment by dmarcoux** [comment]
Another z-index issue. Since we got and still get such issues, we should verify again all those z-index. I probably picked a wrong value in my last fix some weeks ago.

**Comment by tux93** [comment]
This is currently also happening with the user drop down  
![Screenshot_2020-08-28_14-00-20](https://user-images.githubusercontent.com/1749593/91558683-18fe1800-e937-11ea-84e0-2a141110c1c8.png)

**Comment by dmarcoux** [comment]
Thank you @tux93 for reporting this issue.
