### ISSUE TITLE
Number of Tasks (top right) unrelated to actual number of tasks open

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#9364]
OBS currently shows wrong information.

See screenshot:
![Screenshot from 2020-04-09 14-58-57](https://user-images.githubusercontent.com/532559/78897593-b634de80-7a72-11ea-8e8f-abc2c6f4f8e9.png)

top right show ```275 Tasks``` - but the number of open reviews and requests to handle is far from that count

(this is quite minor, of course; from what I see, the actually listed requests are correct, just the count in the top right is wrong, possibly outdated/wrongly cached(?))

**Comment by coolo** [comment]
This is rather recent regression - for me it's 5 vs 7

**Comment by coolo** [comment]
The numbers are off even per tab - 2 incoming requests shows 1 and all together are supposed to be 7

![screencapture-build-opensuse-org-my-tasks-2020-04-12-11_18_10](https://user-images.githubusercontent.com/1067203/79065264-63943600-7caf-11ea-92e2-c1e863a80686.png)

**Comment by hennevogel** [comment]
Let's track this in #9352
