### ISSUE TITLE
github tracker

### ISSUE THREAD

**Issue by bnavigator** [openSUSE/open-build-service#9395]
# Issue Description

Hi, I noticed `osc api /issue_trackers` includes an entry for generic github issues (again?).

```
  <issue-tracker>
    <name>gh</name>
    <kind>github</kind>
    <description>Generic github tracker</description>
    <url>https://www.github.com</url>
    <show-url>https://github.com/@@@</show-url>
    <regex>(?:gh|github)#(\w+\/\w+#\d+)</regex>
    <label>gh#@@@</label>
    <enable-fetch>false</enable-fetch>
  </issue-tracker>
```

This would close #7826.

However the regex could need some improvement. Organization and repository names can include  `-` besides the `\w` class. (And possibly more characters?) Look at the name of this very repository right here: open**-**build**-**service.

Expected Result
============
`gh#openSUSE/open-build-service#7826` creates a valid link to #7826

Real live examples
==============
`gh#davidhalter/jedi#1543` links correctly in https://build.opensuse.org/request/show/794384
`gh#dalthviz/python-language-server#1` is not picked up in 
https://build.opensuse.org/request/show/794386

**Comment by adrianschroeter** [comment]
shoudl be fine now on production.

**Comment by adrianschroeter** [comment]
https://github.com/openSUSE/open-build-service/pull/9397 for git

**Comment by weberhofer** [comment]
Have added it to the documentation at https://en.opensuse.org/openSUSE:Packaging_Patches_guidelines#Current_set_of_abbreviations
