### ISSUE TITLE
Make OBS website search in Name + Title + Description by default

### ISSUE THREAD

**Issue by trmdi** [openSUSE/open-build-service#9409]
Mentioned website: https://build.opensuse.org/search
Currently it only searches in Name, it will not return the expected result in many cases.
For example, if you search for "firefox global menu"
+ search in Name (by default currently): no package
+ search in Name + Title + Description: return some packages

So it would be nice if you set all of these options by the default.

**Comment by hennevogel** [comment]
Given how long we have the current default, that our main audience is packagers (and not end users) and that you can, if you want to, search in titles and descriptions, I don't think it makes sense to change the default.

End user search is supposed to happen on something like https://software.opensuse.org

**Comment by trmdi** [comment]
> End user search is supposed to happen on something like https://software.opensuse.org

I can't find any way to get a result if I search for "firefox global menu" in this site.
Where should I report it?
