### ISSUE TITLE
apache error.log cannot load such file -- phusion_passenger

### ISSUE THREAD

**Issue by dasdeniz** [openSUSE/open-build-service#942]
obs 2.6.2 opensuse 13.2 image from raw.xz
after adding to `/etc/apache2/vhosts/obs.conf` : 

    SetEnv SSL_CERT_FILE /srv/obs/certs/server.pem
as directed in this issue:  Internal Error 500 after initial install #905
still have this in apache error.log:
```
App 17508 stderr: WARN: Unresolved specs during Gem::Specification.reset:
App 17508 stderr:
App 17508 stderr:       rake (>= 0.8.1)
App 17508 stderr: WARN: Clearing out unresolved specs.
App 17508 stderr: Please report a bug if this causes problems.
App 17508 stderr: /usr/lib64/passenger/5.0.6/bin/passenger-config:32:in `require'
App 17508 stderr: : cannot load such file -- phusion_passenger (
App 17508 stderr: LoadError)
App 17508 stderr: 	from /usr/lib64/passenger/5.0.6/bin/passenger-config:32:in `<main>'
App 17572 stdout:
```

you don't even have to point a browser to `https://<fqdn>/` to see this error.

**Comment by doccaz** [comment]
Same problem hereAlready tried the workaround as well, no progress.

**Comment by adrianschroeter** [comment]
the error message does not sound SSL related. Are you sure that you have configured the right ruby for passenger?

/etc/apache2/conf.d/mod_passenger.conf

also be sure that ruby2.3-rubygem-passenger is installed (for OBS 2.7. it needs to be ruby2.1 for 2.6)

**Comment by doccaz** [comment]
Weird thing is, passenger-status shows everything okay (with active processes waiting), Apache lists the module as being loaded, and gem lusts the module as correctly installed. Yesterday I tried deleting the whole /srv/OBS directory  and ran the setup script in /usr/lib/OBS. It's working now. Perhaps there is something being done in the script that I missed?

**Comment by adrianschroeter** [comment]
sorry, can't fix something without a reproducer.

**Comment by doccaz** [comment]
Just to close off the thread: I managed to go past this problem by starting all over and running the setup-appliance.sh script instead of doing everything manually :)
