### ISSUE TITLE
[feature] folder as sources

### ISSUE THREAD

**Issue by damianatorrpm** [openSUSE/open-build-service#9423]
**Is your feature request related to a problem? Please describe.**
I would like to replace git workflow completely with OBS.

**Describe the solution you'd like**
OBS already has re-visioning per package.
The current scheme is 
```
foo.tar.gz
foo.spec
```

It would be very handy for smaller code adjustments to foo 
this to be possible:
```
foo/   #this is the uncompressed source directory instead of tar.gz
foo.spec

1) using OBS web editor navigate to foo/main.cpp
2) make changes to foo/main.cpp
3) OBS service compresses foo/ directory.
4) OBS builds foo.
```

**Comment by hennevogel** [comment]
Good news, there is a service providing exactly this functionality. https://github.com/openSUSE/obs-service-tar_scm#obs_scm

**Comment by damianatorrpm** [comment]
@hennevogel I have trouble though adding a folder to a package. The webUI has only add file.

**Comment by hennevogel** [comment]
This is not usable through the web interface. You should look into the command line client. If you need more help, there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members.

**Comment by damianatorrpm** [comment]
@hennevogel I understand although I think it should be possible via the webUI.
I will try to add folders via osc than and maybe at some point open a feature request for "Add folder"
Thanks!
