### ISSUE TITLE
[production][notifications#index] undefined method `commentable' for nil:NilClass

### ISSUE THREAD

**Issue by saraycp** [openSUSE/open-build-service#9424]
notifications#index threw this 1 times
<pre>
undefined method `commentable&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/my/notifications](https://build.opensuse.org/my/notifications)"

**Comment by saraycp** [comment]
After investigating a bit, I think this happened when a comment was deleted during the time gap between an event creation and its corresponding notification creation (what is performed by a job a few minutes later).

However, it seems this no longer happens since this condition was introduced:
https://github.com/openSUSE/open-build-service/pull/9447/commits/929f1c26820e6edd6ce368f0649e088b0cea9df7#diff-d13560640ce0b1194a939caa8d54a79fR40

I close the issue.

**Comment by dmarcoux** [comment]
This is happening again. [See the exception on Errbit](https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/606993a084bf46055ba488a8).

**Comment by saraycp** [comment]
The last error was caused by only one _Comment for Request Notification_ that was associated with a Comment (notifiable) that didn't exist anymore.

First of all, I removed the affected Notification, so the user can access the Notifications page without any problem and we no longer get the error.

After my research I can say:

If the user removed the Comment after the Notification was created, the Notification should have been removed too, since we have this line in the [Comment model](https://github.com/openSUSE/open-build-service/commit/722ded162f58d976fd12734b75cf798eb21e4904#diff-4dd354307e5161407a24287136777333e1900263ff52e321507a662f60a5ca7bR86):

```
has_many :notifications, as: :notifiable, dependent: :delete_all
```

If the user removed the Comment before the Notification was created (the creation is done in a Delayed Job), the creation should have been prevented in [this line](https://github.com/openSUSE/open-build-service/blob/24f771660eb294faf4bc893f3b40f8b1e85769ff/src/api/app/services/notification_service/notifier.rb#L45).

```
return false unless notifiable_exists?
```

What happened then? Was there a connection problem with the database? Was the Comment removed in the tiny time gap between we check if it exists and we create the Notification?

**Comment by saraycp** [comment]
This happened again. A comment was deleted but the notification pointing to it wasn't.
It should have been deleted according to [this line](https://github.com/openSUSE/open-build-service/blob/4bf3e1b36a1ce147be343c2d145fc66a91d7a668/src/api/app/models/project.rb#L66).

I removed the affected notification manually.

This is the latest Errbit entry about this issue: https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/647f1a5784bf4605485b65b2
