### ISSUE TITLE
[production][search#index] Record IDs found by Sphinx but not by ActiveRecord : 5259490, 5250055

### ISSUE THREAD

**Issue by saraycp** [openSUSE/open-build-service#9436]
search#index threw this 40 times
<pre>
Record IDs found by Sphinx but not by ActiveRecord : 681698, 682295, 682304
</pre>
[https://build.opensuse.org/search?name=1&amp;package=1&amp;page=4&amp;project=1&amp;search_text=rpm-packaging](https://build.opensuse.org/search?name=1&amp;package=1&amp;page=4&amp;project=1&amp;search_text=rpm-packaging)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5e8279f957ce55000f1b5b83)

**Comment by marxin** [comment]
The bug annoying, please fix it. Happens also for `systemd` search string.

**Comment by dcermak** [comment]
And when searching for `emacs` as well.

**Comment by dmarcoux** [comment]
The fix is going live in our upcoming maintenance window. It will be tomorrow (August 26th, between 8am and 10am CEST).

**Comment by marxin** [comment]
Thanks for the fix!
