### ISSUE TITLE
[Beta] web UI is missing links on Project page

### ISSUE THREAD

**Issue by ggardet** [openSUSE/open-build-service#9437]
# Issue Description
Beta web UI is missing links on 'Project' page:
* Create Patchinfo
*  GPG Key / SSL Certificate
* Edit Project
* Delete Project

Expected Result
============
Those links should be there.

How to Reproduce
===============
1. Enable beta program
2. Go to a project page where you have admin rights
3. No links to edit project descritpion, etc.

Further Information
===============
* A link to an OBS instance showing the issue: https://build.opensuse.org

**Comment by dmarcoux** [comment]
The links have been moved under a menu named `Actions` on some pages and this was documented in [one of our blog posts](https://openbuildservice.org/2020/03/24/notifications-redesign/), in the *Menus, Menus Everywhere!* section. However, I realize that we did a poor job in sharing this with users who didn't read that blog post (which I guess is most people).

This is how it looks for me in my home project:
![actions](https://user-images.githubusercontent.com/1102934/80082990-61ef2b80-8555-11ea-8c03-b7c9c1354933.png)

**Comment by ggardet** [comment]
Ah ok, thanks! :)
TBH, sometimes I read the blog posts, sometimes I don't, in a very random pattern! ;)

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve communication for changes, especially for users who don't read the blog.](https://trello.com/c/KvWqo70v/1374-improve-communication-for-changes-especially-for-users-who-dont-read-the-blog)

**Comment by dmarcoux** [comment]
> Ah ok, thanks! :)
> TBH, sometimes I read the blog posts, sometimes I don't, in a very random pattern! ;)

Even if some users don't read the blog posts, we need to somehow better present what changed. I'm closing the issue, but I created a card in our Trello board. It is linked just above this comment.

Thank you for your feedback :)
