### ISSUE TITLE
[production][delayed_job#SendEventEmailsJob] undefined method `enabled?' for #<EventSubscription:0x00007f7ef80fb490>

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#9459]
delayed_job#SendEventEmailsJob threw this 0 times
<pre>
undefined method `enabled?&#39; for #&lt;EventSubscription:0x00007f7ef80fb490&gt;
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5ea83af4cc710f00082439f9)

**Comment by hennevogel** [comment]
This was during a deployment...
