### ISSUE TITLE
OBS build issue with link project

### ISSUE THREAD

**Issue by Gyeongmin** [openSUSE/open-build-service#947]
Hello

I have following scenario in OBS.

OBS  has two projects "A" and "A:link". Project "A" has link for project "A:link"

I have a package P1 which is dependent on many packages P2 ,P3,p4...P100 etc. This package is present in both projects "A" and "A:link". Whenever a dependent package P2 or P3 etc is submitted to project "A:link" then package (P1) build happens in both projects "A" and "A;Link"

I don't want building package P1 in project "A" when its dependent package is submitted to link project "A:link"

is there a way to solve this.  Any information on this is highly appreciated.

Please let me know if i can provide any more detils.

**Comment by hennevogel** [comment]
Package links can have a revision (osc linkpac -r). Project links can be frozen (see the openSUSE:Factory staging projects on the reference server.

And in the future please don't use issues as support forum. If you are having difficulties understanding something in OBS seek out the community at our IRC channel or mailing list. Thank you in advance!

http://openbuildservice.org/support/

**Comment by adrianschroeter** [comment]
use "osc setlinkrev" to freeze the package links
