### ISSUE TITLE
buildinfo wrong for kiwi builds with buildtime services

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/open-build-service#9507]
When running `osc build` for a kiwi image which uses buildtime services, this fails because those services did not get installed.

To reproduce:

```
> osc co Virtualization:containers:images:openSUSE-Tumbleweed/opensuse-tumbleweed-image
> cd Virtualization:containers:images:openSUSE-Tumbleweed/opensuse-tumbleweed-image
> osc build -M docker -l container x86_64
> grep obs-service .osc/_buildinfo-container-x86_64.xml
  <bdep name="obs-service-kiwi_metainfo_helper" noinstall="1" version="0.0" release="2.4" arch="noarch" project="openSUSE:Tumbleweed" repository="standard"/>
  <bdep name="obs-service-kiwi_label_helper" noinstall="1" version="0.0" release="1.4" arch="noarch" project="openSUSE:Tumbleweed" repository="standard"/>
```

It can be seen that those got put into the kiwi image expansion instead of the sysdeps one, so they have noinstall="1".

The reason for this is that the `obs-service-FOO` dependencies are added to `$pdata->{'info'}->{'dep'}`:

https://github.com/openSUSE/open-build-service/blob/c5ffd88054c2f8db0f4ff7d9432fa3126361788f/src/backend/bs_repserver#L3308

which the kiwi handler treats as image deps:

https://github.com/openSUSE/open-build-service/blob/c5ffd88054c2f8db0f4ff7d9432fa3126361788f/src/backend/BSSched/BuildJob/KiwiImage.pm#L325

It should probably push to `$cgi->{'add'}` instead.

**Comment by mlschroe** [comment]
No, they should go to `$info->{'buildtimeservice'}` instead of `$info->{'dep'}`...

**Comment by Vogtinator** [comment]
Confirmed fixed on build.o.o
