### ISSUE TITLE
_buildinfo ignores add parameter for Dockerfile builds

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/open-build-service#9508]
`osc api /build/home:favogt:dockerfilemeta/containers/x86_64/some-meta-container/_buildinfo?add=thisdoesnotexist | grep thisdoesnotexist`

The output is empty. This means that `osc build -x foo -x bar` has no effect.
This is especially annoying in combination with https://github.com/openSUSE/open-build-service/issues/9507, as this workaround is no longer effective.

**Comment by AdamMajer** [comment]
Any update on this? This is breaking most of the local container builds.

**Comment by mlschroe** [comment]
Dumb question: is this really a regression? Nobody changed anything in the build job creation code the last months.

**Comment by Vogtinator** [comment]
AFAIK it never actually worked.

**Comment by mlschroe** [comment]
Thanks for confirming this. Fixing...

**Comment by mlschroe** [comment]
https://github.com/openSUSE/open-build-service/pull/9860

**Comment by mlschroe** [comment]
Sorry for fixing this that late, I somehow missed those two bug reports. I now picked them up while going through the open issues list...

**Comment by AdamMajer** [comment]
@mlschroe Thank you for the fix

**Comment by Vogtinator** [comment]
Yep, thanks! Please tell when the fix is deployed and I'll test it.

**Comment by Vogtinator** [comment]
Apparently it was deployed and I can confirm that it's working now.
