### ISSUE TITLE
[production][package#buildresult] undefined method `buildresult' for nil:NilClass

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#9514]
package#buildresult threw this 54 times
<pre>
undefined method `buildresult&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/package/buildresult?project=openSUSE%3AFactory%3AStaging%3Aadi%3A41&amp;package=&amp;index=0&amp;show_all=false](https://build.opensuse.org/package/buildresult?project=openSUSE%3AFactory%3AStaging%3Aadi%3A41&amp;package=&amp;index=0&amp;show_all=false)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5eb00e00f48ca5000dee35da)

**Comment by dmarcoux** [comment]
This has to be related to #9466.

**Comment by saraycp** [comment]
It happens when it is a deletion request.
