### ISSUE TITLE
Apidocs Broken

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#952]
Most of the apidocs example links don't work anymore, except those where by accident the real API responds. This is because the apidocs tool (restility) does not know about linking files in sub-directories. 

@adrianschroeter is it possible that we switch to some other tool like [helphelp](https://github.com/SUSESTUDIO/studio-help) or is there more involved. We're not completely sure...

@cornelius  Or can you tell restility to prepend a path for an XmlResult?

**Comment by cornelius** [comment]
I haven't touched restility for something like a decade, so I'm pretty sure it doesn't listen to me anymore, if I try to tell it something ;-)

**Comment by adrianschroeter** [comment]
@hennevogel sure, whatever works.

Of course we prefer simpler solutions with little dependencies and a good maintenance track ...

**Comment by hennevogel** [comment]
@adrianschroeter can you please what the current solution provides? So far we have discovered

* api documentation (app/controllers/webui/apidocs_controller.rb)
* api example validation (test/unit/schema_test.rb)
* general XML validation (lib/opensuse/validator.rb)

anything else?

**Comment by adrianschroeter** [comment]
The api documentation could also be very well provided by openbuildservice.org web site very well. IMHO there is no need to keep code in OBS just to provide this in every instance. We could link to the central site.
We just should automate the api docu generation somewhere then.

regardings schema_test and validator are using Nokogiri or plain "jing" IIRC, so they are out of scope here.

**Comment by kaltsi** [comment]
If you want to fix this easily, just add the "apidocs/" part to the generated links here:

https://github.com/openSUSE/open-build-service/blob/master/docs/api/restility/lib/rest_htmlprinter.rb#L129

@html.a( "Example", "href" => "apidocs/"+example )

and same for the schema here:

https://github.com/openSUSE/open-build-service/blob/master/docs/api/restility/lib/rest_htmlprinter.rb#L133

In a related note the obs-server.spec file has two useless apidocs and schema related lines:

https://github.com/openSUSE/open-build-service/blob/master/dist/obs-server.spec#L356

By appending those two lines to environment.rb, you achieve nothing. The environment.rb already sets apidocs_location and schema_location before those two lines are appended. So they are not effective.
