### ISSUE TITLE
[production][pulse#show] Security warning: an embedded <script> tag on another site requested protected JavaScript. If you...

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#9521]
pulse#show threw this 16 times
<pre>
Security warning: an embedded &lt;script&gt; tag on another site requested protected JavaScript. If you know what you&#39;re doing, go ahead and disable forgery protection on this action to permit cross-origin JavaScript embedding.
</pre>
[https://build.opensuse.org/projects/home:danimo/pulse](https://build.opensuse.org/projects/home:danimo/pulse)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5ea8e0042ec8e2001595749d)

**Comment by vpereira** [comment]
https://github.com/openSUSE/open-build-service/issues/6969

**Comment by eduardoj** [comment]
Duplicated of #6969. Reopening the former and closing this one.
