### ISSUE TITLE
[production][] <status code="400">
  <summary>home:M0ses:Perl/perl-Sys-MemInfo: project 'home:M0ses:Perl' does n...

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#9533]
threw this 1 times
<pre>
&lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;home:M0ses:Perl/perl-Sys-MemInfo: project &#39;home:M0ses:Perl&#39; does not exist&lt;/summary&gt;
&lt;/status&gt;

</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5eb268dc472cb400161d7d7d)

**Comment by eduardoj** [comment]
Exception not found in Errbit any more. Closing.
