### ISSUE TITLE
OBS frontend Beta: move 'save' button

### ISSUE THREAD

**Issue by coogor** [openSUSE/open-build-service#9537]
When editing a file in OBS, the 'save' button is at the bottom of the page.

Please move it next to the 'Undo/Redo' buttons in the top bar: first one needs to scroll down to save, then up again to jump to the build results (for example). This is not really efficient.

Thank you!

**Comment by simotek** [comment]
Agreed, this is especially bad for long .changes files

**Comment by hennevogel** [comment]
We rather emphasize reviewing the changes and adding commit messages.

**Comment by hennevogel** [comment]
Thanks for reporting this anyway :+1:

**Comment by simotek** [comment]
@hennevogel then can we consider this as a request to have a save button positioned in some way where we do not need to scroll through 20k lines of changelog before seeing it then?

**Comment by hennevogel** [comment]
Not sure what you expect?

It'll be at the bottom, near the commit message field. To encourage reviewing what you did and leaving a message about it.

If you edit a 20k line changelog it's even more important I guess. Everyone has [HOME] and [END] keys on their keyboards, many input devices have some fast scrolling feature etc.

**Comment by coogor** [comment]
The entry about the last change is at th top of the changes file, not at the bottom. there is no need to scroll down.
Same when you do a change in the spec file.
Scrolling down is monkey entertainment, but not ergonomic

**Comment by simotek** [comment]
> Not sure what you expect?
> 
maybe the commit dialog / save button could float at the bottom of the window, I think that would make a nicer user experience.

> It'll be at the bottom, near the commit message field. To encourage reviewing what you did and leaving a message about it.
> 
> If you edit a 20k line changelog it's even more important I guess. Everyone has [HOME] and [END] keys on their keyboards, many input devices have some fast scrolling feature etc.

In the 20 years i've used various web based ui's i've never really needed to use the [END] button so the thought never crossed my mind, but I will use the end button for now :-) (Firefox with a mouse + scroll wheel which is my usual method doesn't have any fast scroll).
