### ISSUE TITLE
Bad redirect

### ISSUE THREAD

**Issue by I-Cat** [openSUSE/open-build-service#9539]
For security issues, please refer to [SECURITY.md](https://github.com/openSUSE/open-build-service/blob/master/SECURITY.md).

Having problems with the OBS command line interface osc? It has its own issue tracker here: https://github.com/openSUSE/osc

Having problems with the obs-build tool that controls the build process? It has its issue tracker here: https://github.com/openSUSE/obs-build

Good to go? Then please remove these lines above, including this one, and help us understand your issue by answering the following:

# Issue Description

Expected Result
============

How to Reproduce
===============
1. Go to       https://build.opensuse.org/stage/package/show?package=apache2-mod_asn&project=Apache%3AMirrorBrain
2. See error

Further Information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)

**Comment by dmarcoux** [comment]
Hello @I-Cat,

Could you tell us how you got that URL? Beside the URL, we have no information at all. Please fill out the various sections (Expected Result, Further Information, etc...) in the issue template.

**Comment by eduardoj** [comment]
Not enough information to identify an issue. Closing.
