### ISSUE TITLE
[production][package#show] undefined method `project_release_request_path' for #<#<Class:0x00007f7df5c8da00>:0x00007f7df5c8b...

### ISSUE THREAD

**Issue by krauselukas** [openSUSE/open-build-service#9547]
package#show threw this 0 times
<pre>
undefined method `project_release_request_path&#39; for #&lt;#&lt;Class:0x00007f7df5c8da00&gt;:0x00007f7df5c8b7c8&gt;
Did you mean?  project_new_release_request_path
</pre>
[https://build.opensuse.org/package/show/devel:languages:python/python-yamllint](https://build.opensuse.org/package/show/devel:languages:python/python-yamllint)"

[See this exception on Errbit](http://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5ebba7eb30c74a00085ec1d5)

**Comment by dmarcoux** [comment]
This happened during the deployment of the changes from #9536 . It occurred only once and it was 12 seconds after a deployment. The URL in the exception doesn't reproduce the issue. I'm closing this.
