### ISSUE TITLE
Can't disable notifications for groups.

### ISSUE THREAD

**Issue by simotek** [openSUSE/open-build-service#9556]
#9502 Issue Description
When I attempt to stop getting notifications for one of the groups in SUSE's internal build service the change isn't applied.

Expected Result
============
No longer receiving 1000 emails a day from various parts of obs.

How to Reproduce
===============
1. Go to 'Your Profile'
2. Click on 'Change your notifications' (Bottom Left)
3. Unselect Groups that you don't want notifications from
4. Notice a spinner next to the Group name, and the box is unchecked
5. Refresh page
6. Box is now checked again and Still getting emails.

**Comment by hennevogel** [comment]
Request URL: https://build.opensuse.org/my/subscriptions
Request Method:PUT
Remote Address:[2001:67c:2178:8::162]:443
Status Code: 404
