### ISSUE TITLE
SP4-debuginfo channels adding SP3-debuginfo build-repositories in maintenance-incidents

### ISSUE THREAD

**Issue by bbrunner** [openSUSE/open-build-service#957]
When we start a maintenance-update where also a debuginfo-channel for SP4 is added, it automatically adds the debuginfo-channel for SP3 as build-repository, but not the SP4 one. As workaround we have to manually branch the debuginfo-channels to the incident and the correct repos are added.

**Comment by adrianschroeter** [comment]
Is this still an issue? (call me if it is :)

**Comment by bbrunner** [comment]
Looks like that it's already fixed. Thank you :)
