### ISSUE TITLE
SR from Beta-GUI not covering all elements

### ISSUE THREAD

**Issue by coogor** [openSUSE/open-build-service#9585]
I had done a smaller change via the BETA-GUI for OBS.
As last step I entered the .changes file, made an entry, scrolled down some 100 lines and saved the entry.
Then I used the back-button on the browser to return to the project overview. From there I used the 'Has a link diff', on this page I used 'Submit to factory': Now the pop-up catched the text from the changes file, but did not include the changes file itself in the SR.
As a result, the SR got declined:
https://build.opensuse.org/request/show/807940

My guess is that 'Has a link diff' does not update the diff every time it is called. So when using the back button of the browser, the last change was not catched in the 'link diff'.

**Comment by hennevogel** [comment]
"Has a link diff" points to a specific revision. If you use your browser back button and the browser cache is fresh, it'll point to the one that was rendered when you visited the page.

Nothing we can do about this, sorry.
