### ISSUE TITLE
Repository flag are "stacked"

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#9586]
# Issue Description
The repositories flag in small viewports are "stacked" instead of be one below the other:

![Screenshot_2020-05-21 openSUSE Build Service](https://user-images.githubusercontent.com/1212806/82556698-8c3f0380-9b6a-11ea-83af-5766941b7349.png)

Expected Result
============
Repositories flag box one below the other:

![Screenshot_2020-05-21 Open Build Service(1)](https://user-images.githubusercontent.com/1212806/82557111-5d755d00-9b6b-11ea-943b-cea086f62ab6.png)

Further Information
===============
This happened after the upgrade to bootstrap 4.5. In upstream there is also an [open issue](https://github.com/twbs/bootstrap/issues/30852)

**Comment by eduardoj** [comment]
The issue upstream got fixed a couple of weeks after this issue was reported.

We are using an updated version of Bootstrap. This issue doesn't happen any more. Closing.
