### ISSUE TITLE
Incomplete requests when filtering for user

### ISSUE THREAD

**Issue by bergmannf** [openSUSE/open-build-service#959]
When retrieving `requests` using the `/request` endpoint, it is possible to obtain incomplete requests:

1. Use the `/request`-endpoint.
2. Supply the parameters: `login=<name>` and `view=collection`.
3. Will return requests that contain only *one* `review`-node (even if the request should have multiple ones).

**Comment by adrianschroeter** [comment]
This is caused the way how the xpath search is implemented here. It is using joins to limit the search results. That is fine for searching, but for rendering the request it must not be limited. Esp. since this can be cached and might affect also other search queries.

**Comment by bgeuken** [comment]
Looks to me like this isn't an issue any longer. The [code](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/bs_request.rb#L245) uses active record relations now, not xpath, and [my test](https://github.com/bgeuken/open-build-service/tree/issue_959) also passed.

@adrianschroeter Am I missing something?

**Comment by adrianschroeter** [comment]
@bgeuken This is about the xpath search and not about the special view of the requests. /search/request route.

**Comment by adrianschroeter** [comment]
eg /search/request with some review/@by_user=SOMEONE while it has also another person and ideally also some group or project as reviewer in addtion.

**Comment by adrianschroeter** [comment]
@bgeuken please extend your test also with roles=reviewer so that the code filters by reviewers. Might also create the problem via that route (not checked the code though)

**Comment by bgeuken** [comment]
I've updated the tests: https://github.com/openSUSE/open-build-service/pull/1635

This indeed seems to be solved. We also checked the created SQL, which looks fine.
Thus closing
