### ISSUE TITLE
Move actions back to their previous location

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/open-build-service#9593]
**Is your feature request related to a problem? Please describe.**
Project/package actions used to be under project/package description, which is nice and clear. But now they are in the navbar within a dropdown/sidebar. It is hard to find and requires one more click. Navbar should only contain global actions, not page actions. Take GitHub as example, fork and pull request buttons are in the page content, not in the navbar, not in a dropdown.

**Describe the solution you'd like**
Move it back to where it was.

**Describe alternatives you've considered**
Some other design similar to GitHub.

**Additional context**

**Comment by hennevogel** [comment]
Actions are now merged to the sidebar

**Comment by guoyunhe** [comment]
Well, the sidebar design seems worse...

**Comment by hennevogel** [comment]
Feel free to give us qualified feedback about it...
