### ISSUE TITLE
Flickering Image Template feature test on mobile

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#9598]
feature tests for mobile fails often in circleci with:

```
Failure/Error: expect(page).to have_field('target_package', with: kiwi_package)
  expected to find field "target_package" that is not disabled but there were no matches
./spec/features/beta/webui/image_templates_spec.rb:67:in `block (3 levels) in <top (required)>'
```

Link: [Circle-CI container](https://circleci.com/gh/openSUSE/open-build-service/43214#tests/containers/2)

**Comment by hennevogel** [comment]
You find flickering specs on circle now.

https://app.circleci.com/insights/github/openSUSE/open-build-service/workflows/test_all/tests?branch=master&reporting-window=last-30-days
