### ISSUE TITLE
Error 500 showing up

### ISSUE THREAD

**Issue by jfha73** [openSUSE/open-build-service#960]
Hey guys,

I just downloaded the latest version of the OBS, installed it and when I tried to run it for the very first time, it showed me an Error 500, I checked the logs and saw this:

AH00557: httpd2-prefork: apr_sockaddr_info_get() failed for linux
AH00558: httpd2-prefork: Could not reliably determine the server's fully qualif$
[Mon Jun 29 15:00:16.218519 2015] [mpm_prefork:notice] [pid 9521] AH00163: Apac$
[Mon Jun 29 15:00:16.218548 2015] [core:notice] [pid 9521] AH00094: Command lin$
App 9597 stdout:
App 9597 stderr:  --> Compiling passenger_native_support.so for the current Rub$
App 9597 stderr:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 9597 stderr:      Warning: compilation didn't succeed. To learn why, read t$
App 9597 stderr:      /tmp/passenger_native_support-1qzi88u.log
App 9597 stderr:  --> Downloading precompiled passenger_native_support.so for t$
App 9597 stderr:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disabl$
App 9597 stderr:      # tar xzf rubyext-ruby-2.1.3-x86_64-linux.tar.gz
App 9597 stderr:      # rm -f rubyext-ruby-2.1.3-x86_64-linux.tar.gz
App 9597 stderr:      Checking whether downloaded binary is usable...
App 9597 stderr:      # /usr/bin/ruby.ruby2.1 -I. test.rb
App 9597 stderr:      /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb$
App 9597 stderr:        from /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_req$
App 9597 stderr:        from test.rb:2:in `<main>'
App 9597 stderr:      Binary is not usable.
App 9597 stderr:  --> Continuing without passenger_native_support.so.
App 9597 stderr: WARN: Unresolved specs during Gem::Specification.reset:
App 9597 stderr:       rake (>= 0.8.1)
App 9597 stderr: WARN: Clearing out unresolved specs.
App 9597 stderr: Please report a bug if this causes problems.
App 9597 stderr: This command requires the Phusion Passenger agent to be installed
App 9635 stdout:
App 9643 stdout:

I tried doing a 'gem install passenger' and 'passenger-config install-agent' but it still shows the 500 Error.

Any ideas?

**Comment by adrianschroeter** [comment]
sorry, but this is not a support forum here. Please use our mailing list and provide some more informations, like how you installed (git/rpm packages/appliance, config settings). And most important which doc you followed. the README.SETUP?
