### ISSUE TITLE
Missing signature for GCP images

### ISSUE THREAD

**Issue by smarlowucf** [openSUSE/open-build-service#9606]
# Issue Description
There was a breaking change to move the inline signature out of the checksum file. This change broke the GCE images as they no longer have any signature. The checksum is not signed inline and there is no .asc file available. The changes in question I think are here https://github.com/openSUSE/open-build-service/commit/3a37174f12875d887f710a1756b09c444cafa530. It doesn't seem to account for GCE images which are tarballs (.tar.gz).

Expected Result
============
GCE images would have a .asc signature file available similar to the other images.

How to Reproduce
===============

Further Information
===============
* Private instance
* 2.9

**Comment by mlschroe** [comment]
Adrian already fixed that in commit fc54f7ae0cbbc3e0f36e49a73e9c52394ed44159
