### ISSUE TITLE
Installation Emulators:/Wine:/Debian/Debian_10/

### ISSUE THREAD

**Issue by saziburrahman** [openSUSE/open-build-service#9633]
Hello,

I was trying to install veil framework from GitHub that time I faced GPG error. All time showing this massage ->
“
Hit:1 https://dl.winehq.org/wine-builds/debian buster InRelease                                                                       
Get:3 https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Debian_10 ./ InRelease [1,549 B]                             
Err:3 https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Debian_10 ./ InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DFA175A75104960E
Hit:2 http://kali.cs.nctu.edu.tw/kali kali-rolling InRelease
Reading package lists... Done
W: GPG error: https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Debian_10 ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DFA175A75104960E
E: The repository 'https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Debian_10 ./ InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

”

From this error I found your site link  -> https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Debian_10 ./

Here I am not understanding which file I need to download and how to install those file on my kali linux in virtual machine.

I am new on Linux can you help me please?

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
