### ISSUE TITLE
publish packages and report file

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#9662]
`.packages` and `.report` files are not published:

https://build.opensuse.org/package/binaries/openSUSE:Leap:15.2:MicroOS:ToTest/openSUSE-MicroOS:RaspberryPi/images
vs
https://download.opensuse.org/repositories/openSUSE:/Leap:/15.2:/MicroOS:/ToTest/images/

see also #9040

**Comment by dmarcoux** [comment]
This is a direct consequence of #9571

**Comment by mlschroe** [comment]
The commit has been reverted for now.
