### ISSUE TITLE
apidocs shows most_active instead of most_active_(projects|packages)

### ISSUE THREAD

**Issue by perlpunk** [openSUSE/open-build-service#9671]
# Issue Description

https://build.opensuse.org/apidocs/index#164 shows:
`GET /statistics/most_active?type=<type>&limit=<limit>`

Expected Result
============
It should instead document `most_active_projects` and `most_active_packages`

Also the schema and examples for it are outdated. For example, there is no `update_count` in the result.

**Comment by perlpunk** [comment]
Created #9672

**Comment by DavidKang** [comment]
Handled in PR #9672
