### ISSUE TITLE
project.rng docs are missing documentation of many elements

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#9680]
# Issue Description

The documentation of the project [`_meta`](https://build.opensuse.org/apidocs/project.rng) is missing the documentation of plenty of elements used by the `openSUSE:Tumbleweed` project on https://build.opensuse.org. It has the following elements in the repository section that are documented nowhere:
- archfilter
- download
- pubkey

**Comment by dcermak** [comment]
Bump on this one? I'd really like to add these properly to my API wrapper, but without any documentation or ruby knowledge, that is impossible to pull off.

**Comment by adrianschroeter** [comment]
https://github.com/openSUSE/open-build-service/pull/9933

(you would need to check the backend and build script code, not ruby for these build topics)
