### ISSUE TITLE
Cant edit rpmlintrc file in Web-UI

### ISSUE THREAD

**Issue by coogor** [openSUSE/open-build-service#970]
For project https://build.opensuse.org/package/show/home:DocB:branches:devel:languages:python:Factory/otr-verwaltung
I added a simple rpmlintrc file, according to https://en.opensuse.org/openSUSE:Packaging_checks#Building_Packages_despite_of_errors
I can enter the edit mode for this file, but I cant save it - save button does not turn red after a change in the file.

**Comment by ChrisBr** [comment]
Fixed in #1015
