### ISSUE TITLE
route POST /source/<project>/<package>?cmd=createSpecFileTemplate appears to be impossible to use?

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#9707]
# Issue Description

The route `POST /source/<project>/<package>?cmd=createSpecFileTemplate` appears to be impossible to use: if I invoke it on a package that has no spec file, then I get this error back:
```xml
<status code="not_found">
  <summary>&lt;status code="404"&gt;
  &lt;summary&gt;more.spec: no such file&lt;/summary&gt;
  &lt;details&gt;404 more.spec: no such file&lt;/details&gt;
&lt;/status&gt;
</summary>
</status>
```
but if I create the spec file and call the route, then I get this error:
```xml
<status code="spec_file_exists">
  <summary>SPEC file already exists.</summary>
</status>
```

Expected Result
============
It should be possible to use the route.

How to Reproduce
===============
1. create a project & package `${project}/${package}`
2. run: `curl --user ${CREDENTIALS} -X POST "${obs_url}/source/${project}/${package}?cmd=createSpecFileTemplate"` and observe the first error
3. run: `curl --user ${CREDENTIALS} -X PUT "${obs_url}/source/${project}/${package}/${package}.spec" -d "nothing to see"`
2. re-run `curl --user ${CREDENTIALS} -X POST "${obs_url}/source/${project}/${package}?cmd=createSpecFileTemplate"` and observe the second error

Further Information
===============
* Tested on OBS 2.10.5

**Comment by dcermak** [comment]
Could be related to https://github.com/openSUSE/open-build-service/commit/5b55c89fa23241f635cee2c401f98728490024d6 as told to me by `}-Tux-{` on irc.

**Comment by hennevogel** [comment]
It is

**Comment by dcermak** [comment]
So just remove this route then? No offense intended, but as it has been broken since 2011, I highly doubt that it is actually being used by anyone at this point.

**Comment by hennevogel** [comment]
That would also be my preferred solution :smile:

**Comment by dcermak** [comment]
:+1:  from me, no need to keep broken routes around.

**Comment by saraycp** [comment]
This endpoint is marked as "deprecated" in the new [API documentation](https://build.opensuse.org/apidocs-new/#/Sources%20-%20Packages/post_source__project_name___package_name__cmd_createSpecFileTemplate). We close this issue.
