### ISSUE TITLE
[production][main#index] Validation failed: Name is illegal

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#9718]
main#index threw this 13 times
<pre>
Validation failed: Name is illegal
</pre>
[https://build.opensuse.org/](https://build.opensuse.org/)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5e62e3f98a4607000af66bae)

**Comment by hennevogel** [comment]
This is #9922
