### ISSUE TITLE
Search for openSUSE:Leap:15.2 triggers 500: internal server error 

### ISSUE THREAD

**Issue by lkocman** [openSUSE/open-build-service#9747]
Search for openSUSE:Leap:15.2 triggers 500: internal server error 

Expected Result
============
Should return results matching my search filter

How to Reproduce
===============
1. Go to build.opensuse.org
2. Enter openSUSE:Leap:15.2 # doesn't happen with e.g. openSUSE
3. Click on Search

Further Information
===============
* Client was openSUSE TW with firefox
* I was logged in OBS

**Comment by DavidKang** [comment]
Duplicated of #9436 

Thanks for reporting the issue.
