### ISSUE TITLE
Initial database setup broken

### ISSUE THREAD

**Issue by M0ses** [openSUSE/open-build-service#9762]
From /srv/www/obs/api/log/db_migrate.log

```
[strong_migrations] DANGER: Lock timeout is longer than 10 seconds: 86400
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Duplicate entry '1-DelegateRequestTarget' for key 'index_attrib_types_on_attrib_namespace_id_and_name'
/srv/www/obs/api/db/data/20200527135426_request_delegate_attribute.rb:9:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry '1-DelegateRequestTarget' for key 'index_attrib_types_on_attrib_namespace_id_and_name'
/srv/www/obs/api/db/data/20200527135426_request_delegate_attribute.rb:9:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
Mysql2::Error: Duplicate entry '1-DelegateRequestTarget' for key 'index_attrib_types_on_attrib_namespace_id_and_name'
/srv/www/obs/api/db/data/20200527135426_request_delegate_attribute.rb:9:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate:with_data
(See full trace by running task with --trace)
```

IMHO this commit broke it:

https://github.com/openSUSE/open-build-service/pull/9616

**Comment by hennevogel** [comment]
Are you addings seeds _and_ running migrations? Where is this from?

**Comment by saraycp** [comment]
>  Where is this from?

This is the key question.

A few weeks ago, we fixed a typo in the version of the migration and changed the version in the `data_migrations` table, manually. I'm not sure if it's the same situation, but we can check.

Is the log entry recent? When was the last deployment in that instance?

**Comment by M0ses** [comment]
This is from booting a fresh image - tested in kanku.

**Comment by M0ses** [comment]
It is done by setup-appliance.sh which is started by obsapisetup.

https://github.com/openSUSE/open-build-service/blob/master/dist/setup-appliance.sh#L284

obsapisetup is run on each startup of the appliance
