### ISSUE TITLE
"Show link diff" button missing

### ISSUE THREAD

**Issue by gmbr3** [openSUSE/open-build-service#9763]
Recently,  the show link diff button (which usually appears below "Links to */*") has disappeared from the options at build.opensuse.org. 

I was part of the beta program when I noticed it, however leaving the beta program has no effect and the button still doesn't appear.

**Comment by DavidKang** [comment]
Hi @gmbr3, thanks for reporting the issue. Could you provide us more information?

Thanks :slightly_smiling_face:

**Comment by gmbr3** [comment]
![Screenshot_20200616-110329_Chrome~2](https://user-images.githubusercontent.com/22273154/84761314-2dca4100-afc1-11ea-8de9-08b35882115a.jpg)

After branching a package, you can monitor changes you have made when compared with the upstream version by using the show link diff button. This has recently disappeared. It should be in the shown place.

**Comment by badshah400** [comment]
Seems to have disappeared again as of today (beta program).

![image](https://user-images.githubusercontent.com/3532467/85957917-c41f3f00-b991-11ea-99dc-c5c2c8343a7e.png)
