### ISSUE TITLE
Content of *.sha256 files are different than the filename when current_milestone macro is used

### ISSUE THREAD

**Issue by ismail** [openSUSE/open-build-service#9787]
Say we have 

> %define current_milestone GMC

in project meta and macro. This gives me a sha256 file named:

> SLE-15-SP2-Online-x86_64-GMC-Media3.iso.sha256

but the content of that file is:

> d57a699d7b6b56feaa683a539624be5589e2ea42fad13b9e06062db2d4bf3c56  SLE-15-SP2-Online-x86_64-Build209.2-Media3.iso.sha256

The right content would be:

> d57a699d7b6b56feaa683a539624be5589e2ea42fad13b9e06062db2d4bf3c56  SLE-15-SP2-Online-x86_64-GMC-Media3.iso.sha256

**Comment by mlschroe** [comment]
Fixed.
