### ISSUE TITLE
regression: osc up throws Error 400 Bad request on openSUSE:Factory

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/open-build-service#9849]
# Issue Description
When running `osc up` on a checkout of openSUSE:Factory, it now fails with Error 400 with no changes on the client side.

Expected Result
============
osc should be able to update Factory packages again

How to Reproduce
===============
1. cd $checkout_of_opensuseFactory
2. osc up
3. See Error 400

Further Information
===============
osc -v shows the failing request as `makeurl: https://api.opensuse.org ['source', 'openSUSE:Factory'] ['view=info', 'package=telepathy-mission-control', [...41000 chars here...] 'package=perl-Test-LongString', 'package=python-scour']`

**Comment by bmwiedemann** [comment]
[full osc-up-factory.log](https://github.com/openSUSE/open-build-service/files/4841221/osc-up-factory.log.txt)

**Comment by marcus-h** [comment]
On 2020-06-27 13:44:37 -0700, Bernhard M. Wiedemann wrote:
> # Issue Description
> When running `osc up` on a checkout of openSUSE:Factory, it now fails with Error 400 with no changes on the client side.
>
Hmm this looks a bit strange:

marcus@linux:~> Q=
marcus@linux:~> for i in $(seq 0 2000); do Q[i]="package=foo$i"; done
marcus@linux:~> IFS="&"
marcus@linux:~> curl -v -u Marcus_H "https://api.opensuse.org/source/openSUSE:Factory?view=info&${Q[*]}"
...

produces the expected result (status 200). Replacing the 2000 with 2500
results in the unexpected (IMHO) status 400. Increasing it to 3000 results
in the expected 414 (which osc can handle).

**Comment by bmwiedemann** [comment]
And this has still been working some days ago, so must have been from server-side changes.
I'm using this for my reproducible-builds work all the time.

**Comment by bmwiedemann** [comment]
I added a `--http1.1` and diffed the response header outputs of 2500 and 3000

```bash
#!/bin/bash
for n in 2000 2500 3000 ; do
  Q=
  for i in $(seq 0 $n); do Q[i]="package=foo$i"; done
  oldIFS=$IFS
  IFS="&"
  curl --http1.1 -v "https://api.opensuse.org/public/source/openSUSE:Factory?view=info&${Q[*]}" > curl11-$n.log 2>&1
  IFS=$oldIFS
done
```

```diff
-< HTTP/1.1 400 Bad request
+< HTTP/1.1 414 Request-URI Too Long
 < Date: Sun, 28 Jun 2020 13:22:46 GMT
 < Server: Apache
+< Vary: accept-language,accept-charset
 < Strict-Transport-Security: max-age=31536000
-< content-length: 90
-< cache-control: no-cache
-< content-type: text/html
-< Connection: close
+< Upgrade: h2
+< Connection: Upgrade, close
+< Accept-Ranges: bytes
+< Content-Type: text/html; charset=utf-8
+< Content-Language: en
+< Expires: Sun, 28 Jun 2020 13:22:46 GMT
```

and 2500 with 2000 :
```diff
-< HTTP/1.1 400 Bad request
+< HTTP/1.1 200 OK
 < Date: Sun, 28 Jun 2020 13:22:46 GMT
-< Server: Apache
+< Server: Apache/2.4.33 (Linux/SUSE)
 < Strict-Transport-Security: max-age=31536000
-< content-length: 90
+< cache-control: private, no-transform
+< referrer-policy: strict-origin-when-cross-origin
+< x-permitted-cross-domain-policies: none
+< x-xss-protection: 1; mode=block
+< x-opensuse-runtimes: {"view":null,"db":5.451267235912383,"backend":0}
+< x-request-id: 86c9792b-0a8a-45f3-bcc5-0c0794794b9d
+< x-opensuse-apiversion: 2.11~alpha.20200626T105729.b82393f628
+< x-download-options: noopen
+< x-runtime: 0.041008
+< x-frame-options: SAMEORIGIN
+< x-content-type-options: nosniff
+< x-powered-by: Phusion Passenger 6.0.4
+< content-type: text/xml
 < cache-control: no-cache
-< content-type: text/html
-< Connection: close
+< content-length: 207920
```

**Comment by adrianschroeter** [comment]
on server side the limit got *increased* to 40000, so exceeding this leads to a 414. But before it should happen way earlier already...

I set it now to 50000

**Comment by mcepl** [comment]
Doesn’t seem like it helped much: ``osc up`` on ``devel:languages:python`` still doesn’t work (Error 400).

**Comment by ismail** [comment]
Ok so it's haproxy returning the 400, from the haproxy docs:

```
HAProxy may emit the following status codes by itself :

  Code  When / reason
   [...]
   400  for an invalid or too large request
   [...]
```

So, all we can do is increase `tune.bufsize` and that'll help bigger requests go.

**Comment by ismail** [comment]
Workarounded by setting the header limit to 30k, which is lower than haproxy's `tune.bufsize` and let us return 414 instead of 400 which osc handles properly.

**Comment by darix** [comment]
I mean we could also up the bufsize. the question is though ... wouldnt POST be a better request verb for such large requests?

I mean strictly speaking ... you can even have a request body with a GET request. Maybe we should use that?

**Comment by bmwiedemann** [comment]
I think, POST is the wrong verb for a read-only data retrieval operation. And I have never seen anybody use a request body in a GET request. E.g. `curl --data foo` automatically switches to POST. 
`curl -X GET --data foo=bar http://aw.zq1.de/cgi-bin/public/testenv` does force it into a GET request, but then it is not understood by perl's `CGI::param` function on the server side.

Is there anything that does not work with a 30k request limit?

**Comment by mcepl** [comment]
Why to stick with GET at all? For API backwards compatibility sake there should be a GET synonym, but it should be POST IMHO (and/or the processing should be done server-side, so the command is really something like ``GET ls devel:languages:python`` not the huge list of packages).

**Comment by ismail** [comment]
Guys please open a proper feature request instead of writing here. The original issue is resolved.
