### ISSUE TITLE
optionally provide gpg pubkey to spec files

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#9854]
In order to build custom installation medias in forked projects, one needs to make the gpg signkey of the project available to eg. installation-images and skelcd. For the main distro openSUSE-build-key does that. When branching installation-images it would be nice if it would pick up the key automatically too. So maybe something analogous to #needssslcertforbuild would be useful?

**Comment by lnussel** [comment]
hit this again, @mls? :)

**Comment by sysrich** [comment]
This would be really nice to have addressed...
