### ISSUE TITLE
Can I set a special directory for rpm package reading on OBS_REPO_SERVER?

### ISSUE THREAD

**Issue by GeorgeCao-hw** [openSUSE/open-build-service#9868]
# Issue Description
I want to use a high-performance disk for rpm reading/writing. Can I configure it?

Expected Result
============
All rpm package can be placed in a special folder on the high-performance disk.

How to Reproduce
===============
How to configure parameters? Thanks.

**Comment by adrianschroeter** [comment]
this is an issue tracker and not a support tool. please use the normal channels (ml or IRC) for this.

**Comment by hennevogel** [comment]
Yeah, there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members.

**Comment by GeorgeCao-hw** [comment]
OK, thanks. @adrianschroeter @hennevogel
