### ISSUE TITLE
Incorrect expansion of some macros

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#987]
prjconf of home:jengelh:dev contains
```
%if 0%{?rhel_version} > 0 || 0%{?centos_version} > 0
%define FOO 1
%endif

Macros:
%if 0%{?rhel_version} > 0 || 0%{?centos_version} > 0
%BOO 1
%endif
:Macros
```
these lines cause the package `home:jengelh:dev/anotherbug` to enter the state: `unresolved: nothing provides gcc5-c++` for the RHEL/centos6 targets, which I think is an error.

**Comment by mlschroe** [comment]
Not a bug. Your Macros: section defines a %if macro. This is probably not what you want. ;-)

Try:
```
%if 0%{?rhel_version} > 0 || 0%{?centos_version} > 0
Macros:
%BOO 1
:Macros
%endif
```
