### ISSUE TITLE
[production][notifications#index] undefined method `number' for #<Review:0x000055b6c12a4e50>

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#9893]
notifications#index threw this 2 times
<pre>
undefined method `number&#39; for #&lt;Review:0x000055b6c12a4e50&gt;
</pre>
[https://build.opensuse.org/my/notifications](https://build.opensuse.org/my/notifications)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5f05eb9b0076420008902d36)

**Comment by DavidKang** [comment]
Handled in PR [9894](https://github.com/openSUSE/open-build-service/pull/9894)
