### ISSUE TITLE
Factory status page doesn't show failing packages anymore

### ISSUE THREAD

**Issue by krop** [openSUSE/open-build-service#9904]
https://build.opensuse.org/projects/openSUSE:Factory/status doesn't show failing packages anymore.

Expected result:
List the failing packages like before, ie: name, devel repository, failure duration

**Comment by krop** [comment]
After unchecking all boxes, the failures appear again, "Limit to currently failing packages" doesn't seem to do what I expected

**Comment by DimStar77** [comment]
FYI: this causes the 'build fail notification' bot to not send out mails, which explains why the number of failed builds in openSUSE:Factory is increasing. Users are not being informed by the bot anymore

**Comment by DimStar77** [comment]
https://github.com/openSUSE/open-build-service/pull/9690 is a potential source of the regression
