### ISSUE TITLE
[production][notifications#index] undefined method `size' for nil:NilClass

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#9909]
notifications#index threw this 0 times
<pre>
undefined method `size&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/my/notifications?show_all=1&amp;type=read](https://build.opensuse.org/my/notifications?show_all=1&amp;type=read)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5f0c2da680f684000dccd8be)

**Comment by hennevogel** [comment]
This is happening when I use the `show_all=1` parameter

https://build.opensuse.org/my/notifications?show_all=1

**Comment by dPliakos** [comment]
Hello! I believe I can fix it
