### ISSUE TITLE
build.opensuse.org - 500: Internal Server Error

### ISSUE THREAD

**Issue by pytpriscila** [openSUSE/open-build-service#9910]
Issue/Feature Description
====================
I can't access https://build.opensuse.org/, whem I try I receive the error:
 "500: Internal Server Error
Oooops, something went terribly wrong, our application crashed :-( We think it's best if you search if this issue is already reported on GitHub. "

**Comment by hennevogel** [comment]
Please answer a couple of questions so we can find out what is wrong.

- When did this happen exactly?
- Have you been logged in? And if yes, what is your user name?

**Comment by pytpriscila** [comment]
@hennevogel, thanks for reply, follow the answers:

When did this happen exactly?
  After I login.

Have you been logged in? And if yes, what is your user name?
  yes, priscila.

**Comment by saraycp** [comment]
Hello @pytpriscila

We have found out that your email address wasn't verified. You should have received an email to do so but in case you can't find it, please go to [this link ](https://idp-portal.suse.com/univention/self-service/#page=verifyaccount) and verify your account.

After that, please let us know if you are able to log in at https://build.opensuse.org.

Thanks

**Comment by pytpriscila** [comment]
> Hello @pytpriscila
> 
> We have found out that your email address wasn't verified. You should have received an email to do so but in case you can't find it, please go to [this link ](https://idp-portal.suse.com/univention/self-service/#page=verifyaccount) and verify your account.
> 
> After that, please let us know if you are able to log in at https://build.opensuse.org.
> 
> Thanks

Thanks for reply, now it's ok.
