### ISSUE TITLE
VALID_SCOPE_TYPES regression since ruby update

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#992]
We see a large amount of crashes in production OBS since the ruby2.2 & rubygem update according to errbit. Henne looked briefly inside and found  https://bugs.ruby-lang.org/issues/10871 which might be related.

Since this the biggest amount of crashes in errbit and it happens by looking at a package since is kind of a blocker atm.

Errors like:
Argum​entEr​ror: ​Inval​id sc​ope t​ype '​' sen​t to ​the r​egist​ry. S​cope ​types​ must​ be i​nclud​ed in​ VALI​D_SCO​PE_TY​PES

**Comment by hennevogel** [comment]
I came there through this https://github.com/rails/rails/issues/20700
