### ISSUE TITLE
Missing popups for "unresolvable" in UI using public beta on build.opensuse.org

### ISSUE THREAD

**Issue by okurz** [openSUSE/open-build-service#9936]
# Issue Description
Having "public beta" enabled on build.opensuse.org for my account "okurz" on package URLs like https://build.opensuse.org/package/show/devel:openQA/os-autoinst the popup for "unresolvable" build status does not show up on hovering nor click.

Expected Result
============
A popup should be displayed showing results like "nothing provides perl(ExtUtils::MakeMaker) >= 7.12, (got version 6.66 provided by perl), nothing provides perl(Test::Warnings) >= 0.029, …". This still works when disabling the public beta switch.

How to Reproduce
===============
1. On build.opensuse.org, being logged in
2. Make sure "public beta" is enabled in the personal profile page
3. Go to https://build.opensuse.org/package/show/devel:openQA/os-autoinst with browser
4. Click on "unresolvable" build result
5. Observe that no popup is displayed

Further Information
===============
* https://build.opensuse.org/package/show/devel:openQA/os-autoinst shows the issue

**Comment by hennevogel** [comment]
![Peek 2020-07-21 15-49](https://user-images.githubusercontent.com/514785/88062986-cd9f5f80-cb69-11ea-9868-04645d1a79f9.gif)

**Comment by okurz** [comment]
Well, thanks for your video. But this still shows the problem even though I haven't checked the question mark icon. The text "unresolvable" is underlined so suggesting a link but it's only `javascript:void(0)` now so different and misleading behaviour than in before. Even more so because other cases like "building" and "succeeded" still are links, linking to build logs

**Comment by hennevogel** [comment]
Yeah, you are right. I guess it should also open the extra info.

**Comment by dmarcoux** [comment]
To summarize: Clicking on `unresolvable` should also display the information which is displayed when clicking on the question mark icon.

**Comment by bugfinder** [comment]
still an issue, anyone looking at this ?

**Comment by dmarcoux** [comment]
Nobody is assigned, so nobody is looking into this.

**Comment by coolo** [comment]
I find this very confusing as well - had to ask. Was completely unable to discover this myself

**Comment by coolo** [comment]
And to be blunt: this affects a lot of people's day to day work - so rolling this out even as you had this as beta feedback is very irresponsible IMO

**Comment by smithfarm** [comment]
Another person affected by this, respectfully looking forward to a fix. Thanks for all the OBS goodness!
