### ISSUE TITLE
Mageia_Cauldron is no longer working

### ISSUE THREAD

**Issue by ole-tange** [openSUSE/open-build-service#9948]
Mageia_Cauldron broke sometime between 20200522 an 20200622.

This worked: https://build.opensuse.org/package/binaries/home:tange/parallel/Mageia_Cauldron

This does not: https://build.opensuse.org/package/live_build_log/home:tange/parallel/Mageia_Cauldron/i586

~~~
[   14s] Welcome to your new installation of [1;36mMageia 8[0m!
[   14s] 
[   14s] Please configure your system!
[   14s] 
[  104s] -- Press any key to proceed --[[0;1;31m TIME [0m] Timed out waiting for device [0;1;39m/dev/ttyS0[0m.
~~~

It looks as if Mageia_Cauldron was re-installed without configuring it.

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us for some specific installations.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
