### ISSUE TITLE
Create notification per User instead of a single group notification

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#9958]
When a group has an email, we create a single entry in the notification table which subscriber is the group instead of creating individual  notifications for each member if the group.

Expected Result
============
Have one notification per user in the group instead of one for the group

**Comment by dmarcoux** [comment]
This is where it's happening: https://github.com/openSUSE/open-build-service/blob/c4adb6f593615c4db2285cb6de170fcab7f6fcaf/src/api/app/models/event_subscription/find_for_event.rb#L51

**Comment by saraycp** [comment]
We can close this issue since we already implemented the notifications' filter by group. More details in [this card](https://trello.com/c/d9PDB2mD/135-filter-by-group).
