### ISSUE TITLE
multibuild: Missing spec file warnings

### ISSUE THREAD

**Issue by vries** [openSUSE/open-build-service#9982]
# Issue Description
Consider multibuild package https://build.opensuse.org/package/show/devel:tools:compiler/dwz , with packages dwz and dwz:testsuite.

During building dwz:testsuite, we find a number of warnings due to using a differently named spec file than expected:
...
[    1s] lamb55 started "build dwz.spec" at Fri Jul 17 20:52:23 UTC 2020.
...
[  154s] ... testing for empty debuginfo packages
[  154s] grep: //.build.packages/SOURCES/dwz-testsuite.spec: No such file or directory
[  154s] ... running 50-check-filelist
...
[  155s] ... testing devel dependencies required by libtool .la files
[  155s] grep: //.build.packages/SOURCES/dwz-testsuite.spec: No such file or directory
[  155s]     (can be skipped by "skip-check-libtool-deps" anywhere in spec)
[  155s] ... running 50-check-packaged-twice
...
[  155s] RPMLINT report:
[  155s] ===============
[  157s] dwz-testsuite.nosrc: W: invalid-spec-name
[  157s] The spec file name (without the .spec suffix) must match the package name
[  157s] ("Name:" tag). Either rename your package or the specfile.
...

Expected Result
============
No rpmlint warning, no grep failure.

How to Reproduce
===============
Look here ( https://build.opensuse.org/package/live_build_log/devel:tools:compiler/dwz:testsuite/openSUSE_Leap_15.2/x86_64 ) for the warnings.

Further Information
===============
I think this should be fixed if we not only patch dwz.spec file for the build flavor, but also rename according the flavor: to dwz-testsuite.spec.

**Comment by hennevogel** [comment]
Guess you found out how to disable rpmlint warnings. This has not much to do with the OBS...

**Comment by vries** [comment]
> Guess you found out how to disable rpmlint warnings. This has not much to do with the OBS...

I don't understand this. I'm working around the warnings by disabling them, but the issue filed here is about the fact that there are warnings, when there should not be any warnings.
 
And AFAIU, it's OBS that causes the warnings, due to the way it has implemented multibuild support. If not OBS, then what component is responsible for producing the warnings?

**Comment by hennevogel** [comment]
> And AFAIU, it's OBS that causes the warnings, due to the way it has implemented multibuild support. If not OBS, then what component is responsible for producing the warnings?

rpmlint is, a package in the distribution. The checks are developed here on github AFAIK: https://github.com/openSUSE/?q=rpmlint&type=&language=
