### ISSUE TITLE
500 when searching steam

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/open-build-service#9984]
# Issue Description

If you type "steam" in that search bar of build.opensuse.org and hit Enter, you got 500 error.

Expected Result
============
It should have 500 errors.

How to Reproduce
===============
1. Go to build.opensuse.org
2. Type "steam" in the search box
3. Press Enter key

Further Information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)

**Comment by DavidKang** [comment]
Releated to #9436
