### ISSUE TITLE
Do we support deploy the OBS cluster in kubernetes?

### ISSUE THREAD

**Issue by TommyLike** [openSUSE/open-build-service#9996]
**Is your feature request related to a problem? Please describe.**
If it's possible to deploy the OBS cluster in kubernetes, it would be much easy to maintaince and upgrade, do we support it now?

**Describe the solution you'd like**
None

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
